### ISSUE TITLE
[UX] Add Rich Text editor (WYSIWYG) to core

### ISSUE THREAD

**Issue by luiselizondo** [backdrop/backdrop-issues#101]
This is probably self explanatory.

Updated:

We'll need to include the ckeditor library, the equivalent of caption_filter module, and get things like adding links using drupal forms so they can be altered.

We should port the CKEditor module pretty much verbatim from D8 to Backdrop. The implementation is seriously one of the best API and integrations with a WYSIWYG out there. And considering it's specifically integrated with Drupal already, it's the fastest approach available.

In D8, we separated the "Editor" module from the "Filter" module. The Editor module builds on top of the "filtered_html" element and even alters the menu entries of Filter module. This was a compromise that we arrived at after reaching an impasse in the Drupal queue. In Backdrop, we should reconsider building Editor integration directly into Filter (or even renaming Filter to Editor).

**Comment by BWPanda** [comment]
Is adding a rich text editor to core about adding the WYSIWYG Drupal module to core, or adding a specific editor (e.g. CKEditor) to core?

Also, not sure if this is relevant/needed, but I've always found the [Wysiwyg Button Order](https://www.drupal.org/project/wysiwyg_button_order) module very helpful, so including similar functionality here would be good.

**Comment by quicksketch** [comment]
> Is adding a rich text editor to core about adding the WYSIWYG Drupal module to core, or adding a specific editor (e.g. CKEditor) to core?

It's a little bit of both. In Drupal 8, I wrote the initial module for implementing WYSIWYG into the filtering system, but it was done as a separate module (editor.module). In addition to that module, we also wrote a default implementation and included that in core (ckeditor.module).

Though that's what we did for D8, I think that we unnecessarily abstracted things a bit. My initial proposals were to either merge filter.module into a new module called editor.module, or just provide editor ability into filter.module. That caused some infighting on drupal.org until we compromised on making a separate module that heavily alters the functionality of filter.module (lots of form_alter, field_alter, and menu_alter happens in editor.module).

My preference for Backdrop would be to integrate the generic portions into filter.module directly, then bundle CKEditor as the default editor.

> Also, not sure if this is relevant/needed, but I've always found the Wysiwyg Button Order module very helpful, so including similar functionality here would be good.

That would definitely be included in our initial release. Earlier in the D8 cycle, I backported the majority of the architecture for CKEditor module (including the button arrangement) into https://www.drupal.org/project/wysiwyg_ckeditor

I haven't updated that module in a long time, but it will likely be the basis for our implementation. We'll need to remove the wysiwyg.module integration and replace it with modifications to filter.module, but otherwise the basics our system are there. Additional integration such as using Backdrop's dialog API will need to be written or backported from D8.

**Comment by ipwa** [comment]
Is inline editing being considered?

**Comment by quicksketch** [comment]
> Is inline editing being considered?

It's unlikely to be included in core, and definitely not in our first pass. Inline editing complicates many things. However, for the most part the inline editing of D8 is an entirely separate module (`quickedit.module`). So once the CKEditor module is backported, it may be possible to recreate the inline functionality as a contrib module.

**Comment by jenlampton** [comment]
@docwilmot I don't think anyone has started working on porting https://www.drupal.org/project/wysiwyg_ckeditor yet, it would be great if you wanted to start on that :)

Not sure if this other issue is a blocker for Rich Text editing, but worth a second look: https://github.com/backdrop/backdrop-issues/issues/159#issuecomment-72972553

**Comment by docwilmot** [comment]
I would love to but I think its smarter if @quicksketch does, since he built the original

and also I dont know how to do 
> integrate the generic portions into filter.module directly, then bundle CKEditor as the default editor.

I think porting WYSIWYG/CKEditor is OK, but a proper solution baked into Backdrop is the right way to go and I cant manage that, sorry.

**Comment by tarekdj** [comment]
@quicksketch, @jenlampton , since wysiwyg_ckeditor module requires wysiwyg I think we should start by porting wysiwyg first. If no one is working on that I think can give it a try the next few weeks.

**Comment by jenlampton** [comment]
@tarekdj we will not need wysiwyg module for Backdrop, since wysiwyg_ckeditor will be moving into core.  Please see @quicksketch's comment above for how we will integrate it.

**Comment by tarekdj** [comment]
@jenlampton thanks for your clarifications.

**Comment by jenlampton** [comment]
@tarekdj we also did a more indepth discussion of an approach to wysiwyg in core in the latest weekly meeting: https://www.youtube.com/backdropcms

**Comment by Graham-72** [comment]
For anyone like me wanting WYSIWYG editing in Backdrop, prior to it being available in core, I have completed a port of the Drupal 7 CKEditor module and it can be found at https://github.com/backdrop-contrib/ckeditor

**Comment by shrop** [comment]
Awesome! Thanks for the work on that to bridge the gap. Welcoming arrival in core at a later time :)

**Comment by klonos** [comment]
Good job Graham! Much appreciated.

**Comment by quicksketch** [comment]
I'm going to start working on a branch for getting CKEditor into Backdrop core.

Here are the initial issues for Drupal 8 that may provide a lot of reusable (non-plugin-ified) code that we can use directly in Backdrop:

[#1833716: WYSIWYG: Introduce "Text editors" as part of filter format configuration](https://www.drupal.org/node/1833716)
[#1890502: WYSIWYG: Add CKEditor module to core](https://www.drupal.org/node/1890502)

And we'll probably lift quite a bit from the [CKEditor for WYSIWYG](https://www.drupal.org/project/wysiwyg_ckeditor) module.

A lot has happened beyond those initial issues of course, but for starters I think it will get us pretty far. After the initial implementation, we'll want to break out separate issues for dialog handling and file uploads.

**Comment by docwilmot** [comment]
:musical_note:

**Comment by quicksketch** [comment]
This is coming along swimmingly.

To facilitate easier collaboration, I've started a new branch for this in the Backdrop repository similar to how we made a dedicated branch for the new admin theme. Going forward with all other major initiatives, I think it would be a great idea to continue this pattern of making feature branches for any feature that will require weeks or months of work.

So far the following is working/not-working:

- [x] Filter formats now have the ability to store an editor and editor settings with each format. This is *not* a separate module, it's built right into filter.module.
- [x] CKEditor version 4.4.7 is included in core/misc with a customized (slimmed down) installation.
- [x] CKEditor module is working as a mix of wysiwyg_ckeditor.module and some D8 backporting.
- [x] CKEditor toolbar can be configured with a drag and drop interface. Port of the original CKEditor code and some rewriting from https://www.drupal.org/node/1872206.
- [x] Filtered HTML text areas bind properly and can add/remove CKEditor when a format that supports it has been selected.
- [x] CKEditor "Advanced Content Filter" (ACF) is working(!) Meaning that only the tags that are allowed by the format are supported within the editor. This is a port of https://www.drupal.org/node/1936392 and https://www.drupal.org/node/2039163.
- [ ] Neither link nor image handling works at all (buttons either will not show up or are not available). This is because we can skip the interim step of using CKEditor's dialogs and skip right to the next item...
- [ ] Using Backdrop native dialogs for link and image (port https://www.drupal.org/node/1879120)
- [ ] Port Image2 plugin use in a "backdropimage" plugin (port of https://www.drupal.org/node/2027181)
- [ ] Image uploading through CKEditor (port of https://www.drupal.org/node/1932652)
- [ ] Have configuration of the toolbar automatically update filter settings (port of https://www.drupal.org/node/1894644)

Other than those items, it *appears* that we've got most of the main system in place. Turns out this goes a lot faster when you've already written the code once. :wink:

**Comment by quicksketch** [comment]
Here's the commit list thus far:

https://github.com/backdrop/backdrop/compare/1.x-wysiwyg?expand=1

You'll probably want to skip the first commit (adding CKEditor) and just look at the others one at a time.

**Comment by mikemccaffrey** [comment]
Hey folks,

It's great that we're getting CKEditor into backdrop, so there is a at
least some WYSIWYG option for people to use.

However, Drupal's reliance on third-party editors has not been a big
selling point for the project. The WYSIWYG interface always feels tacked-on
and users are never really happy using it since the experience is not
nearly as nice as it is with other publishing platforms.

Since Backdrop doesn't have the requirement to support every use case that
people are using Drupal for, perhaps we could consider integrating a clean
and simple text editing widget directly into core to create a pleasant
experience out of the box?

What do you think?

Mike

**Comment by klonos** [comment]
I feel that any official reply to this would most likely be summarized to simply "not enough resources". But I'm not the right person to reply.

**Comment by docwilmot** [comment]
> other publishing platforms
> a clean and simple text editing widget

@klonos is most likely going to be right, but just in case he isnt (or you were offering your services :wink:), I'm not experienced in other platforms so curious as to what you mean by those two phrases.

**Comment by klonos** [comment]
I'd also say that most other popular CMS/blogging platforms that I'm aware of use 3rd party solutions too.

**Comment by quicksketch** [comment]
Joomla and WordPress use both tinyMCE. Not many people are aware of the WYSIWYG being 3rd-party code in WordPress because it is so deeply integrated. My theory is that people have always been disappointed in WYSIWYG not because of the underlying libraries, but because of the lack of adequate integration in Drupal. My hope (for both D8 and Backdrop) is that by providing a library in core and integrating it far beyond what we've ever done in Drupal will yield an amazing experience for content editors.

Regarding which editor to use, there's some interesting back and forth in https://www.drupal.org/node/1260052 and this [spreadsheet comparing Aloha and CKEditor](https://docs.google.com/document/d/164Bm2KPAPelQj2fKauWlajDDuusYh4XSluZNlunlaI4/edit). At this point using CKEditor gives us tremendous benefits due to the amount of code already produced that we can more or less port directly to Backdrop. Newer features in 4.x like the advanced content filter and widgets were developed specifically to match with Drupal's filtering functionality.

**Comment by quicksketch** [comment]
I pushed up changes that make good progress on

- Have configuration of the toolbar automatically update filter settings (port of https://www.drupal.org/node/1894644)

The commit for this set of changes is https://github.com/backdrop/backdrop/commit/03efbe4462234b2f53e05415adc623f38ca9b66b. For the most part, it's a port, but as usual there's a fair amount of modification to get this into Backdrop:

- Removed use of underscore.js and backbone.js (as we don't have these libraries in core).
- Avoided the invisible CKEditor instance on the administration form. I was hesitant about this approach in the drupal.org issue. Using data attributes instead results in a much faster page load and allows for potential server-side validation and warnings, but has the downside of having some configuration (such as class names) in two places (ckeditor_ckeditor_plugins() and ckeditor_add_settings()).

After that it's fairly similar to what we wrote for D8. The UX is identical on this particular feature.

Next up will be image and link support and dialogs. Woot!

**Comment by klonos** [comment]
Gave it a spin just now. The configuration page seems to work fine, but the actual editor is not being rendered when trying to add content - just white space:

![editor_not_rendered](https://cloud.githubusercontent.com/assets/2423362/8025134/2736197a-0d8e-11e5-9105-4d8fb632c294.png)

WIP I guess, but I thought I should report this anyways.

**Comment by quicksketch** [comment]
Thanks @klonos! A disappointing first impression. :( I'm not sure why it didn't show up. It's still working well on my machine, but perhaps I need to try it from a clean install.

**Comment by klonos** [comment]
Just for posterity... I downloaded [backdrop-03efbe4462234b2f53e05415adc623f38ca9b66b.zip](https://codeload.github.com/backdrop/backdrop/zip/03efbe4462234b2f53e05415adc623f38ca9b66b) and did an upgrade from 1.1.1. Initially I thought it might be browser-related (I'm on Win8.1 x64 using latest firefox x64 nightly builds), but it's the same with IE11 and Chrome 43. Checked my site status for any required db updates, but there was none. Cleared all caches, did not help.

> A disappointing first impression. :(

Are you kidding me? I live to test! Finding bugs and filing issues is my thing :)

I would **never** say I was disappointed - I understand all the hard work you guys put in this and appreciate all the effort and time spent. We're like kids just waiting for our gift (a freely available CMS to build our websites) - I'm not that spoiled to say "this sucks" when such a free gift has a minor glitch or two or because a not-yet-released feature is not polished for production use.

**Comment by serundeputy** [comment]
haha well said @klonos thanks for all your hardwork @quicksketch

**Comment by docwilmot** [comment]
Just tried it. The missing editor was fixed by copying the dragresize folder to `\core\misc\ckeditor\plugins` instead of `\core\modules\ckeditor\js\plugins`. But there are two persisting errors, one a backdrop message `Warning: Invalid argument supplied for foreach() in ckeditor_get_acf_settings() (line 537 of C:\wamp\www\backdrop\bdwysiwyg\core\modules\ckeditor\ckeditor.module).` and another javascript message in the console: `Uncaught TypeError: Cannot read property 'getType' of null`.

Otherwise I really like the approach to integrating the editor with the formats. Switching filters worked well. And the editor looks good.

Well done, and as the others have said, this is more already than we should ask for.

**Comment by quicksketch** [comment]
Thanks @docwilmot! I discovered the dragresize plugin isn't necessary any more with the new CKEditor "Image2" plugin we're now using. So I'll fix those error by removing that plugin entirely. The `foreach()` error I'll also look into.

Image and link handling is coming along well and I should be able to push up more changes that get them working. After that, we'll probably start to tighten the implementation and potentially split out file uploading into a separate issue.

**Comment by klonos** [comment]
> Image and link handling is coming along well and I should be able to push up more changes that get them working. ...

Yay!!! Let us know so we can test some more.

BTW, I came by [Craft CMS](https://buildwithcraft.com) and I liked a few things with regards to their editor (did not install the thing - simply from looking at their featured screenshot):

- side-by-side editor / live preview

![craft_cms-wysiwyg_editor](https://cloud.githubusercontent.com/assets/2423362/8096106/e46f789e-1016-11e5-82aa-8eb6c2cb85d5.png)

- how with *each* image upload, there is a set of options in the form of buttons/icons to set the flow of the text left/right/above/below/around the image:

![craft_cms-wysiwyg_editor-image_text_flow](https://cloud.githubusercontent.com/assets/2423362/8096170/6bd565be-1017-11e5-89cb-2d8e32808088.png)

- the fact that they support creating [pull quotes](https://en.wikipedia.org/wiki/Pull_quote) (I didn't know these things had a name) off of the text:

![craft_cms-wysiwyg_editor-pull_quotes](https://cloud.githubusercontent.com/assets/2423362/8096179/83d1dcba-1017-11e5-96c0-f3ee906fdd21.png)

**Comment by klonos** [comment]
@quicksketch: I was about to file a feature request for supporting image captions, but then I remembered that the "Image2" plugin you mentioned. Does it support captions?

**Comment by ipwa** [comment]
@klonos: I don't know about the implementation but the plugin itself does support them: http://ckeditor.com/addon/image2

**Comment by klonos** [comment]
@ipwa Thanx, I recall the screenshots now. Sorry I was too lazy to google this myself - was busy filing new issues and testing things :wink:

**Comment by quicksketch** [comment]
Yes, definitely supports captions. The "widget" support and specifically the ability to have an image and associated caption was one of the many things the folks at CKEditor developed almost specifically for Drupal's implementation. We'll have something to test soon. :)

**Comment by klonos** [comment]
> We'll have something to test soon.

![so_excited](https://cloud.githubusercontent.com/assets/2423362/8109469/2ae50aa4-109a-11e5-8351-eae5dff2c238.jpg)

**Comment by docwilmot** [comment]
> I'm so excited 

:laughing:

**Comment by quicksketch** [comment]
Okay latest changes are up in https://github.com/backdrop/backdrop/tree/1.x-wysiwyg.

Changes now include:

- New Backdrop-native image and link dialogs.
- Image alignment left/right/center support.
- Image caption support.

Functionality-wise, I think we're nearing in on an [MVP](https://en.wikipedia.org/wiki/Minimum_viable_product). File uploading and associating with content is a bit of a tricky issue that we might want to handle separately.

If you guys have some time to test things and report any errors/problems you encounter let me know. I haven't updated the standard profile yet, so to enable the full functionality you'll need to edit a text format, turn on the CKEditor editor, and enable two filters: Image alignment and Image captions. If not enabled, the options for image alignment and captions won't show up in the dialogs (as you might expect).

**Comment by quicksketch** [comment]
Also, a new checklist of things I think we'll want to handle (sooner or later):

- [ ] Teaser break support.
- [ ] Linking an image (I filed an issue on drupal.org for this one: https://www.drupal.org/node/2510380

**Comment by Graham-72** [comment]
@quicksketch - I am hoping to try this. Are we meant to be able to do a fresh install with 1.x-wysiwyg? 
I am getting error messages so maybe I should be trying to update from 1.1.2 ?

A stream of error reports start with:

Warning: array_map(): Argument #2 should be an array in ConfigFileStorage->listAll() (line 1003 of /var/www/vhosts/catherinelarner.com/httpdocs/backdropW/core/includes/config.inc).
Warning: Invalid argument supplied for foreach() in _node_types_build() (line 656 of /var/www/vhosts/catherinelarner.com/httpdocs/backdropW/core/modules/node/node.module).
Warning: array_map(): Argument #2 should be an array in ConfigFileStorage->listAll() (line 1003 of /var/www/vhosts/catherinelarner.com/httpdocs/backdropW/core/includes/config.inc).
Warning: Invalid argument supplied for foreach() in field_read_fields() (line 337 of /var/www/vhosts/catherinelarner.com/httpdocs/backdropW/core/modules/field/field.crud.inc).

**Comment by quicksketch** [comment]
I haven't tried a fresh install yet... perhaps that should be next. Personally I've just been switching back and forth from the latest 1.x to 1.x-wysiwyg. So if you have a 1.1.2 checkout, you should be able to switch to `1.x-wysiwyg`, clear the caches, and start testing.

**Comment by serundeputy** [comment]
> and enable two filters: Image alignment and Image captions

impossible ; i tried  ; not technically impossible; i just don't know how to do it! :smile:

**Comment by quicksketch** [comment]
On the text format that you've enabled CKEdtior, check these two boxes:

![filters](https://cloud.githubusercontent.com/assets/100206/8318684/38cc3420-19c4-11e5-870f-1c43d0769e04.png)

You may need to order the filters so that the "convert image captions" filter comes after the HTML filter, either that or add `<figure>` and `<figcaption>` to the HTML filter tag list.

**Comment by serundeputy** [comment]
![screen shot 2015-06-23 at 6 37 51 pm](https://cloud.githubusercontent.com/assets/6763671/8318881/03cefcc2-19d7-11e5-8408-fa28704d51a0.png)

**Comment by quicksketch** [comment]
Oh. Hm. A cache clear doesn't make them show up by chance?

**Comment by serundeputy** [comment]
nah; reinstalling now;

**Comment by serundeputy** [comment]
reinstalled ; still nah go.  :speedboat:

**Comment by serundeputy** [comment]
omg; please don't be mad at me; i didn't merge in the latest code; :bee:

**Comment by docwilmot** [comment]
I git pulled the branch and followed instructions, but get an error on the node/add page: `( ! ) warning: invalid argument supplied for foreach() in c:\wamp\www\backdrop\backdrop\core\modules\ckeditor\ckeditor.module on line 567` and nothing works.

`dpm($html_restrictions['allowed'])` suggests the function `ckeditor_get_acf_settings()` gets called twice, and in one instance, `$html_restrictions['allowed']` is not an array, just boolean `TRUE`. 

So adding a check for `is_array($html_restrictions['allowed'])` fixed that, and yes all works very well including captions.

**Comment by Graham-72** [comment]
The problem I was having 8 hours ago and reported above was because of using webspace with an old build of PHP that does not work with Backdrop at all. So my mistake and I am trying again with a build of PHP that works fine with all releases so far.

**Comment by quicksketch** [comment]
Thanks @Graham-72. It would be useful to know what version of PHP that was that failed. If Backdrop is trying to run on a version of PHP that doesn't work we should either exit out and fail or fix whatever is preventing it from working.

I've fixed the problem described by @docwilmot with the `foreach()` loop warning. In addition I added CKEditor and the two new filters to the default profile by default.  All tests are now fixed as well (though new tests are needed still).

> i didn't merge in the latest code; :bee:

It's all good :wink: Thanks for testing @serundeputy!

**Comment by Graham-72** [comment]
This was on the build of PHP5.5.9 that I had difficulty with back in January and reported in https://github.com/backdrop/backdrop-issues/issues/590

 

Would it help if I gave you the config details for that build? It would be good to know exactly what libraries are needed for Backdrop. I got caught out recently for not having basic zip in my configuration.

**Comment by Graham-72** [comment]
I have just installed the latest 1.x-wysiwyg with no problem this time. Works a treat - truly excellent work :+1:

**Comment by docwilmot** [comment]
:+1:  functionally excellent.

Minor comments about the editor page itself:
- The separator icon doesnt have alt text so nil on mouseover. Needed since its not very obvious what that icon is.
- The two groups of buttons (active and available should be grouped together. See image:
![editor](https://cloud.githubusercontent.com/assets/1042283/8332766/3ac5e564-1a55-11e5-989b-989c9d0a78d6.PNG)

And also dont forget [hiding the filter options in a fieldset](https://github.com/backdrop/backdrop-issues/issues/938.)

And lets do [put all the filter options in vertical tabs](https://github.com/backdrop/backdrop-issues/issues/1032.)

**Comment by quicksketch** [comment]
Today I was working on handing upgrading from the contrib version of CKEditor, and I'm not quite sure how to handle it.

Initially, I had thought that we would flip the functionality of the /modules directory and make it so that /core/modules would win over /modules (right now the user-modules override core-modules). However, this would cause an API change (although one that wouldn't affect many I think) and it requires some more code maintenance.

Instead, I was thinking that perhaps if you already had the contrib CKEditor module, we'd simply recommend - both in the release notes and in update.php - to delete the module from the /modules directory. This would essentially allow sites that already are happily using the contrib CKEditor module to continue doing so, though perhaps in a incongruous manner now that Editor functionality is built into core. Providing an upgrade path is also somewhat difficult, as the contrib version includes some functionality not included in the core version (and vice-versa). So perhaps the best solution is to let users keep using what's working for them and then manually switch between modules later. What do you guys think?

**Comment by Graham-72** [comment]
>> So perhaps the best solution is to let users keep using what's working for them and then manually switch between modules later.

I think this is perfectly acceptable. Your core version of CKEditor seems easier to configure to personal taste, but maybe a brief tutorial on what needs to be done might be helpful and encourage the change.

**Comment by quicksketch** [comment]
> maybe a brief tutorial on what needs to be done might be helpful and encourage the change.

That's a great idea. Perhaps we could include a full tutorial in the change log entry, as that's likely to be referenced in several places already.

**Comment by klonos** [comment]
...or rename the core one to rich_text_editor so that there is no name conflict and then upon enabling warn that the contrib CKEditor is incompatible and should be disabled first then do the disabling if user agrees and copy any settings over. Too complicated?

**Comment by serundeputy** [comment]
> So perhaps the best solution is to let users keep using what's working for them and then manually switch between modules later.

+1 from me

**Comment by quicksketch** [comment]
> ...or rename the core one to rich_text_editor

Yeah, this is an option. The reason I would shy away from it is because we have a number of APIs (e.g. hook_ckeditor_plugins) that are CKEditor-specific. Typically, hooks and module names are related, and naming a our hooks as `hook_rich_text_editor_plugins()` is a bit generous, when the only type of plugin supported is a CKEditor plugin. Not to mention it's a longer name and more typing. :wink:

Either way, users will need to uninstall their current WYSIWYG solution before using the new core-provided APIs, so I don't think the name is going to be the big problem (although the same-name issue adds to the difficult).

I drafted up a change notice so that I could link to it in the current branch (the changes of which I'll push up shortly): https://api.backdropcms.org/node/42827

**Comment by quicksketch** [comment]
How does this look for a warning message?

![selection_003](https://cloud.githubusercontent.com/assets/100206/9020505/dcacd6d0-37c4-11e5-8595-970053e0e478.png)

**Comment by quicksketch** [comment]
Added the entire directory path to clarify the location:
![selection_004](https://cloud.githubusercontent.com/assets/100206/9020516/b764639c-37c5-11e5-8a04-36db2fcaf812.png)

**Comment by quicksketch** [comment]
Latest code is now pushed up to https://github.com/backdrop/backdrop/compare/1.x-wysiwyg?expand=1

Latest commit adds a small number of tests (as we can't test JS still) and adds the update notification as seen in the screenshot above: https://github.com/backdrop/backdrop/commit/da27845108458b8e8e2712a09266a7f2bc80147a Also includes fixes for the two minor issues brought up in https://github.com/backdrop/backdrop-issues/issues/101#issuecomment-114895775 by docwilmot.

**Comment by klonos** [comment]
Should we display the same warning on the *Site status* page?

**Comment by quicksketch** [comment]
> Should we display the same warning on the Site status page?

Yes, that's an excellent idea. Do you think that should be a warning (yellow) or a notice (blue) in the status report? An error (red) is probably too aggressive, IMO.

**Comment by Graham-72** [comment]
All  :+1: 
and I think a warning (yellow) to remind people like me that it is important to do something about it.

**Comment by serundeputy** [comment]
this is great :smile: 
yellow++;

**Comment by klonos** [comment]
Yep, yellow sounds good.

**Comment by quicksketch** [comment]
Warning message added (sorry about the version warning, that wouldn't show up if I wasn't on the dev version):

![selection_006](https://cloud.githubusercontent.com/assets/100206/9049113/81b32b5e-39f3-11e5-8fb8-131ec93e88e4.png)

I think the latest commit fixes all the tests again.

**Comment by klonos** [comment]
Looks good. :+1:

**Comment by klonos** [comment]
...as for the version warning, I would like to take the chance to shamelessly promote #664

**Comment by quicksketch** [comment]
Cool, I've filed a PR at https://github.com/backdrop/backdrop/pull/1008.

I think this is ready for an initial commit. Then we can work on follow-ups (notably file uploading).

**Comment by docwilmot** [comment]
Looks great, I'd say good to go.

**Comment by quicksketch** [comment]
Great, as usual, let's include and then iterate as needed.

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/issues/1008! Woot! Lots of work to do yet. I'll start filing follow-ups.

**Comment by docwilmot** [comment]
Ladies and Gentlemen, Backdrop now has a built-in text editor! Man that sounds good! Fantastic work, all.

**Comment by serundeputy** [comment]
woot indeed; well done sir;

**Comment by klonos** [comment]
:tada: :balloon: Thank you all guys. Job well done indeed.

I guess we'll be say about 95% in parity with most of the most-advertised D8 new features before or about [the time it is released](https://drupalreleasedate.com) (site says Sept. 8, 2015 at the time of writing). Another target achieved!!!
