### ISSUE TITLE
[UX] Make the layout admin list more informative

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#1028]
Id like to add 
- thumbnail previews of the template being used per layout/path
- the name of the template
- any conditions on that layout
- add a link to the dropbutton to go directly to settings

See idea

![layoutlisting](https://cloud.githubusercontent.com/assets/1042283/8273828/4127d5fc-1843-11e5-90b3-c5a9ab760468.PNG)

---
latest PR: https://github.com/backdrop/backdrop/pull/1385

**Comment by klonos** [comment]
I like it.

**Comment by quicksketch** [comment]
This looks great! The screenshot doesn't include conditionals though, where would those go?

**Comment by klonos** [comment]
I'm thinking that the conditionals list could potentially grow. So how about we hide it in a fieldset like in the modules page (not the "more"/"less" links that we have - the D8 arrow thing)?:

![d8_modules_page-hide-show_module_details](https://cloud.githubusercontent.com/assets/2423362/8294950/7d69f540-1983-11e5-9d7b-a8adafea0b84.png)

**Comment by docwilmot** [comment]
> not the "more"/"less" links that we have - the D8 arrow thing

Somebody should 'port' that. 

> The screenshot doesn't include conditionals though, where would those go?

Not sure where, thats why they're missing. :smile: 
Would be nice if they were immediately visible rather than hidden behind a fieldset, so that the page is more an at-a-glance summary, but I suppose that should work.

**Comment by docwilmot** [comment]
Version 2. Custom built the D8 arrow thing (D8 is the html5 'preview' element, but we dont have that- and it doesnt seem to have good browser support yet).

![layoutlisting2](https://cloud.githubusercontent.com/assets/1042283/8306687/8d99cbb0-197f-11e5-8c97-632ceb6c0bad.PNG)

**Comment by klonos** [comment]
:+1: I especially like the condition count. Nice touch!

**Comment by Graham-72** [comment]
Very nice! :+1:

**Comment by docwilmot** [comment]
@wesruv can you have a look at this please?

**Comment by quicksketch** [comment]
A design opinion would be great, but I think we can proceed with the suggestions as depicted in the screenshots. It's going to be an improvement over the current "non-designed" page we have at the moment.

**Comment by klonos** [comment]
:+1: I second that. Lets take baby steps: improve the current situation first and then revise the design as we have time/energy.

**Comment by jenlampton** [comment]
:+1: I like where this is headed. 

I think the name of the thing should be separated from the layout template info. 

In general, I think we should be careful not to overload the first column with information. Perhaps the conditions can be moved into a new column too? We could mark both the conditions column and the icon column as less-important for responsiveness, if that becomes an issue.

**Comment by docwilmot** [comment]
Thanks @jenlampton, I really didnt like that first column actually, hence the trying to reach @wesruv. My reason for piling it all there was that I felt the name belonged in the first column, but it would look a bit uneven if the screenshot was in the middle (I think we should keep the screenshot), which means the template name would be adjacent to it, and then the conditions should be adjacent to that, and there you go, a mess.

So would you suggest:
- first column Layout name
- second column template screenshot and name and condition

or 

first column Layout name and conditions
- second column template name and screenshot

or??

**Comment by jenlampton** [comment]
I tried the screenshot in the second column to see how much of a mess it might be. I don't think it's actually that bad: (but then, I don't have en eye for these things)
![screen shot 2016-03-29 at 1 24 12 pm](https://cloud.githubusercontent.com/assets/397895/14122693/aab7b478-f5b1-11e5-8aee-cb738f5850d0.png)

**Comment by klonos** [comment]
@jenlampton I just took a quick look at the PR sandbox and it definitely looks better than what we currently have. Although the order of things feels right when I think logic, still visually I like @docwilmot's version better. Reasoning:

- The screenshot feels better on the further left with the layout name next to it. Visually speaking. As @docwilmot says, it looks "uneven".

- Since the screenshot takes quite a bit of vertical space, we might as well take advantage of it. In @docwilmot's design, the layout name can be pushed a bit up to accommodate for secondary info like the name of the template and the number of visibility conditions.

- Having the number of conditions visible offers a decent indicator that there are in fact some defined. Some sort of overview if you like. With your design I'm afraid that on mobile we'll have to hide the separate columns dedicated for secondary info.

- I don't see the use in having any of this information sorted in any way, so there is no actual need to keep that info in separate columns anyways.

**Comment by jenlampton** [comment]
> The screenshot feels better on the further left with the layout name next to it. Visually speaking. As @docwilmot says, it looks "uneven".

I agree that the page looks prettier with the screenshot on the left, I'm just worried that putting it there will create a less usable list than keeping the layout name on the far left. People will already be able to scan for the templates easily - thanks to the addition of the preview image. hm. 

> In @docwilmot's design, the layout name can be pushed a bit up to accommodate for secondary info...

Along the same lines, we need to be careful not to hide the things people are scanning for (the layout name) behind things that are secondary in nature. Views actually does a pretty good job of putting the thing you care about in the same column as secondary information...  hm again :)

> Having the number of conditions visible offers a decent indicator that there are in fact some defined. With your design I'm afraid that on mobile we'll have to hide the separate columns dedicated for secondary info.

A good point. But since we have so much vertical space available it would be a shame to require a click when we could just put the whole condition set in the gap. Let's add the count back (for mobile) though!

> I don't see the use in having any of this information sorted in any way, so there is no actual need to keep that info in separate columns anyways.

When I recommended separate columns I was thinking about scanning, rather than sorting. But perhaps that can be solved in a different way...

**Comment by jenlampton** [comment]
I'm coming around to having the preview on the left... :)

**Comment by gifad** [comment]
This is a great job you are doing here, but…

Keep in mind that a lot (80% ?) of the backdrop targeted users have never heard about Panels, Display Suite, or...
They (at least I) just want to manage the layout (note: singular) of their pages, and just use `admin/structure/layouts/manage/default/edit` which is burried in a third sub-level menu (instead of the first level `admin/structure/block`)
The layouts (note: plural) concept is "blocked" by the "context" thing, which is totally obscure if you never heard about Panels etc…
Having different layouts for different Content Types might be useful, once you realize that you can have multiple layouts, but how to ???
end of rant, sorry

**Comment by jenlampton** [comment]
That's a good point @gifad. I'm really sure how to tackle it, but we should be thinking about how people who have never needed to understand having more than one layout will interact with the two defaults here. 

I've taken a 3rd stab at this based on feedback from @klonos, screenshots shown here at many screen sizes: 
![desktop](https://cloud.githubusercontent.com/assets/397895/14163294/d9974c70-f6a8-11e5-88b0-5b65faa61f12.png)
![tablet](https://cloud.githubusercontent.com/assets/397895/14163298/dbfefcb0-f6a8-11e5-8da3-372c62e9d920.png)
![phone-w](https://cloud.githubusercontent.com/assets/397895/14163301/dec115be-f6a8-11e5-9a3f-515a34ab2bec.png)
![phone](https://cloud.githubusercontent.com/assets/397895/14163303/e197d99e-f6a8-11e5-8771-c9a7551175d2.png)

**Comment by gifad** [comment]
Better, but two thoughts : 

1. Swap title and path (that is use title as title…)
2. Remove (or explain) the storage column : Storage State is Custom exposes the internal parts of he layout, it may be considered as funny, indecent, or confusing if, in your foreign language, layout and storage are closely related (in the furnishing domain)

BTW, overriden is redundant, once you figured the Edit button has a right arrow…

**Comment by klonos** [comment]
@jahaimon 

> ...we need to be careful not to hide the things people are scanning for (the layout name) behind things that are secondary in nature. Views actually does a pretty good job of putting the thing you care about in the same column as secondary information... hm again :)

I was about to mention the example of views. We have title, display (which can be considered the equivalent of the layout template in this context), storage state, *and* type. All that in a single column. It is a UI pattern that I believe people are used to and it works. The way we make the views title stick out when people are scanning for it is by simply making it bold. I think it will work just fine with the layouts too.

The conditions though is an entirely different situation. Besides the count indicator, we need to have a way to expand it (when there is enough screen space) in order to show the actual list of conditions. A similar UI pattern in that case, as I mentioned previously, is the "more" link we use for the description in the modules page.

Well done about setting the importance for columns and being smart about the conditions column (gradually hiding the list first but leaving the count until we have no more space) :+1: 

@gifad 

> 1. Swap title and path (that is use title as title…)

Not sure what you mean here.

> BTW, overriden is redundant, once you figured the Edit button has a right arrow…

I have previously thought of that (for the views UI actually), but I came around because I take for granted my experience with Drupal/Backdrop. Newcomers won't find it that obvious though.

**Comment by gifad** [comment]
> Swap title and path (that is use title as title…)

sorry, this is wrong
looking at the screenshot, where there is a single layout for each path, I thought the layout title would be better in the header, and the path inside the row, as a property (I meant use title as header).
but since there may be several layouts for a given path (and a given layout may not apply to different paths), this is not applicable…

**Comment by klonos** [comment]
OK then.

**Comment by wesruv** [comment]
I decreased the size of the thumbnail so they are 75% of the original size, at that size the anti-aliasing won't completely knock out important details, and the thumbnail doesn't take up so much room. If the screen is hi-res (retina or the like) you won't see any quality loss.

I thought it'd be cool to show any contexts that come with the layout, didn't seem like it deserved it's own column, so I put it under the layout name. We could add a label to it if you all think it's needed.

Also thought it might be nice to have more details in the "Storage Status" column, and also change the column name to "Storage"

Also added some style to the "Default Layouts" header row.

Desktop:
![image](https://cloud.githubusercontent.com/assets/5607236/14190250/b717d9dc-f75f-11e5-833c-2ed44e982b59.png)

Mobile:
![image](https://cloud.githubusercontent.com/assets/5607236/14190260/c362ec68-f75f-11e5-8370-d26bcc68144c.png)

**Comment by wesruv** [comment]
The mobile layout is using a responsive table technique where you use `display: block` on a bunch of table elements, especially `tr` and `td`.

Here's an example: https://css-tricks.com/examples/ResponsiveTables/responsive.php

**Comment by wesruv** [comment]
OH! Forgot I implemented that technique on the views listing page:
![image](https://cloud.githubusercontent.com/assets/5607236/14190589/9c857dfc-f761-11e5-9830-49b904610892.png)

**Comment by docwilmot** [comment]
I'm not sure we need the context. To me it would the majority of the time be obvious from the menu. I think the Storage labels are a bit too verbose now actually. I'd like just "Provided by core", "Provided by core - modified", and "User defined". I like the smaller icons, I think that works better.

**Comment by jenlampton** [comment]
> The conditions though is an entirely different situation. Besides the count indicator, we need to have a way to expand it (when there is enough screen space) in order to show the actual list of conditions.

We don't need an extra click if we show all of the conditions when there is enough space (and hide it when there is not). That's what I was trying to achieve by removing anything that was collapsed on the largest (and most common) screen size.

> The mobile layout is using a responsive table technique where you use display: block on a bunch of table elements, especially tr and td.

@wesruv love it!! 

> I'm not sure we need the context.

I agree, I don't think the context is necessary, and since we are trying to remove the word "Node" from appearing in any UIs - let's not add it here :)

> Also thought it might be nice to have more details in the "Storage Status" column, and also change the column name to "Storage"

Let's be careful not to change any of the terminology around `storage state` in this issue.  We only **just** made that terminology consistent across all of core in 1.3.  If we need to change that terminology again, we need to open a new issue and be careful to do it consistently.  I was actually thinking about opening another issue against views to move storage state into it's own column (that disappears on mobile) to be consistent with this UI.  But at this point, I'm not sure which is better - and which should be improved!

**Comment by klonos** [comment]
- smaller icons :+1: 
- context :-1: 
- "storage state" change :-1: 
- `display: block` on table elements big :+1: but would it be possible to try moving the action drop-button next to the layout name and template?
- applying the same technique in the views UI, also big :+1: separate issue though?

**Comment by quicksketch** [comment]
> I'd like just "Provided by core", "Provided by core - modified", and "User defined".

"Provided by core" might not always be accurate. A contrib module can provide default layouts as well. We could however make it say the name of the module, e.g. "Provided by System". Though if you wanted to replace "System"- and "Layout"-provided configurations with "Core", that would achieve the same out-of-box terminology.

**Comment by jenlampton** [comment]
Let's table the Storage state terminology discussion (or move it to another issue) as that change will involve other systems as well.

**Comment by wesruv** [comment]
I like the consensus that @klonos @jenlampton have.

Gotcha on the storage terminology changes. 

@quicksketch my intention was to say Module name or Core if it came from a core module. Thought that'd be useful information if modules start to add Layouts (e.g. I could see a Google AMP module adding a layout)

I'm not sure that this is worth a ticket, especially if I'm the only confused one. So let me explain where I was coming from, the term "Storage State" seems odd, I'm not sure what "State" adds/means. Feels like the options are: 
* code from a module
* code from a module overriden by config
* config

State implies to me that that the status is more fluid than it is... like something could go from code from a module to config or vice versa... or it could imply that I'd be able to change the state from here? Revert maybe?

"Custom" under storage state doesn't read right for me. I think it's supposed to mean that it's stored in custom config, but if I didn't know any better I'd think that is stored in a more temporary way. I think that's D7 baggage? Custom meant it was in the DB, and if I went to a different site it wouldn't be there, I had to get it in config [in code], and then I'd see "Default".

**Comment by quicksketch** [comment]
> Feels like the options are:
>    code from a module
>    code from a module overriden by config
>    config

In truth, there is no "code" at all. There are only defaults that haven't yet been changed. When you install a module, it copies the default config to your active config. Then it is treated just like everything else and can be modified as needed. So the options are:

- Config copied from a module, not yet modified. (Default)
- Config copied from a module, has been modified. (Overridden)
- Config created by a user. (Custom)

>  or it could imply that I'd be able to change the state from here? Revert maybe?

Yes, you have the ability to Revert on config that has been modified from the module default. And editing a default config will also change the state. As for "Custom" config, you don't have the ability to change the "state" through the UI as a user, since there is nothing to revert back to. Although as a module developer, it's common to create a config through the UI and then manually copy the config to your module to make it into a module-provided config.

Anyway though, I agree with @jenlampton. Let's leave the terminology as-is for now (which matches other places like Views and Image Styles) and handle it separately. We can use the existing issue at https://github.com/backdrop/backdrop-issues/issues/1345 that is discussing the system-wide plan for handling the config state consistently.

**Comment by quicksketch** [comment]
I can't find the current PR to review. :frowning: 

There are 3(?) currently:
https://github.com/backdrop/backdrop/pull/979 by @docwilmot
https://github.com/backdrop/backdrop/pull/1315 by @jenlampton 
???? by @wesruv [mentioned in this comment](https://github.com/backdrop/backdrop-issues/issues/1028#issuecomment-204124319)

I want to make sure everything from the first PR was merged into the second one. And most importantly I can't find Wes's work at all. Was a PR ever filed?

**Comment by docwilmot** [comment]
> I can't find the current PR to review. :frowning:

Unfortunate! :smile: 

Not so sure how @jenlampton's is going. Just tried to reboot the PR to get the sandbox working, but doesnt seem that worked either.

**Comment by jenlampton** [comment]
I haven't done any work on my PR since I think we are liking @wesruv 's approach better, but I don't see a PR form him yet either @quicksketch . Maybe he hasn't fled it yet?

**Comment by jenlampton** [comment]
Okay, I just updated https://github.com/backdrop/backdrop/pull/1315 with smaller images. That could use another review @quicksketch if you are willing :)

**Comment by docwilmot** [comment]
@jenlampton can you push to a new branch or something? Either the sandboxes don't like you or they don't like this branch, but its still not building.

**Comment by jenlampton** [comment]
here we go. Don't know why the sandboxes don't like me :(

**Comment by quicksketch** [comment]
I'll reroll the latest PR at https://github.com/backdrop/backdrop/pull/1371. This needs adjustment after the change from "layout" to "layout_template" in #998.

**Comment by jenlampton** [comment]
@quicksketch looks like we were both working on it at the same time, https://github.com/backdrop/backdrop/pull/1385 is testing now.

**Comment by jenlampton** [comment]
Thanks for the feedback @quicksketch just updated and pushed a new PR at https://github.com/backdrop/backdrop/pull/1385

**Comment by jenlampton** [comment]
Thanks for the additional feedback @quicksketch :) just updated and pushed a new PR at backdrop/backdrop#1385

**Comment by quicksketch** [comment]
It looks like some of the tests from a different PR ended up in the current PR, causing them to fail. I've rerolled this at https://github.com/backdrop/backdrop/pull/1389, replacing the previous PR.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/1389 for 1.4.0. Woo!

**Comment by jenlampton** [comment]
*happy dance*
