### ISSUE TITLE
Add priority tags?

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#1036]
We're now at 17 pages of open issues (5 pages for 1.x-future), and I am really guessing now as to which ones to tackle. Could @quicksketch @jenlampton create priority tags please? (minor, major, critical, nuclear; or 1, 2, 3, 4, 5; whatever). Would that help?

**Comment by klonos** [comment]
Yes please. I wanna mark all **my** issues as "super-urgent" :stuck_out_tongue_winking_eye:

While trying to help triage issue queues in d.org, one of the relatively common tasks I'd come across was having to re/un-assign priority tags (demote) because people thought for example that documentation issues (not as in API documentation - more like questions on how to use something/too lazy to ready the user manual) or feature requests were "critical" or "major". In fact they were too lazy to even read the instructions on using the priority tags themselves where there is a section that clearly said feature requests are **never** critical. Anyways, just ranting here...

Nevertheless, a useful thing priority tags, I say "do it" :+1:

**Comment by serundeputy** [comment]
just `devil`'s advocating over here;
  - we have the milestone tags
  - and [https://backdropcms.org/roadmap](roadmap)

I think these things together, with bug, feature give us a pretty good idea of priority.  Do we need the overhead of more tags; who manages them?

I'm not passionate either way; just putting out some more thoughts `aboot` it.

**Comment by quicksketch** [comment]
I'd like to get @jenlampton's input here. I'm not highly opinionated on this. I think priorities would be useful when browsing, but it does definitely create some friction when having priority-wars.

**Comment by docwilmot** [comment]
> I think these things together, with bug, feature give us a pretty good idea of priority

This is true to an extent but there are many issues not covered by these two pointers that are languishing. Many of the META issues, for example [layout followup issues](https://github.com/backdrop/backdrop-issues/issues/345) has had no progress since last year, while some of the [recently merged PRs](https://github.com/backdrop/backdrop/commits/1.x) seem a lot lower priority than these stalled METAs. ("Add blocks for adding individual fields from entities" from the layout META would make display_suite totally unnecessary! That should be in by now!)

Fact is we dont have many hands on deck yet, so it is reasonable to have @quicksketch  or @jenlampton directing traffic. So a tag that says priority 1 (do this now, or things will be broken) or priority 5 (when all else is finishes, do this) would help me greatly, and I think probably everyone else.

**Comment by klonos** [comment]
Fair enough. But I think we should try restricting priority numbers to one per issue. We can have a top 5 or top 10 issues instead of a bunch of issues with priority "1" and then need to figure out which of these is more urgent.

**Comment by klonos** [comment]
...when it comes to feature requests (because bugs - especially major/critical ones - need to be fixed ASAP), in d.org we had an issue about implementing a "bobble-up" mechanism (using [Vote Up/Down](https://www.drupal.org/project/vote_up_down) or [Rate](https://www.drupal.org/project/rate) IIRC). That seemed like a nice idea, but I don't know if GitHub has the underlying APIs that would allow for that to happen.

**Comment by serundeputy** [comment]
@docwilmot re: #345 maybe tag it with milestone 1.2.0?

bring it to peoples attention that it has a goal?  at least if/until there are priority tags?

just spitballing;

**Comment by docwilmot** [comment]
No consensus and probably unnecessary. Closing.
