### ISSUE TITLE
[UX] Add a default Home Page layout

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1042]
Since the most common use-case for using a different layout is for the front page of a site, I think we should add another layout to the standard install profile. 

One column layout containing:
- Hero Block: w/ Horizontal image - see https://github.com/backdrop/backdrop-issues/issues/1152
- No front page content created yet block.
- Block: View: most recent Promoted posts

Other things to think about:

> Do we change the variable for site_home_page from `node` to `home` 

YES

> Do we enable the default `Front page` view and add a block display to it (also enabling the path `frontpage` 

YES

> Do we add a new (cloned / similar) view for the home page block. 

NO

> Are we okay with losing the text that appears on a fresh install (with a link to create content, if you have access) or should we add this as a block on the new home page, easily removed? 

YES

> What happens to the /node page, do we remove it? 

YES in 2.x See https://github.com/backdrop/backdrop-issues/issues/2114

> What happens to the rss.xml page, do we remove that in favor of the view?

YES.

> If we remove rss.xml, do we remove view-mode and post-count settings at `admin/config/services/rss-publishing`? 

NO. These also affect taxonomy/term/% paths (which should also be replaced with views) so we can't remove them until that is done. See https://github.com/backdrop/backdrop-issues/issues/145

> If we don't remove them, how do we account for the fact that they no longer affect the home page rss feed?

I don't think this is actually an issue, the view has a setting for "Use site-wide RSS settings" and we can take advantage of that if we want. This will also need to be removed when the taxonomy/term/% views get in.

---
~~PR from @jenlampton at https://github.com/backdrop/backdrop/pull/1500~~
PR from @jenlampton at https://github.com/backdrop/backdrop/pull/1539

**Comment by docwilmot** [comment]
I dont get this. Any layout can be a home page layout depending on what you want your home page to look like.

**Comment by quicksketch** [comment]
The suggestion is to ship with a layout pre-configured, e.g. a layout with a path like "front", that is also configured to be shown as the front-page of the site. New users tend to find things easier to modify than to create something new (the same reasoning behind https://github.com/backdrop/backdrop-issues/issues/519). As it's likely that sites will want to customize their front page differently than other pages on the site, providing a preconfigured layout that is already set as the front page can help new users understand the concept of layouts and help them on their way towards customizing their site.

**Comment by docwilmot** [comment]
The confusion here for me was of course you were saying 'layout' I was thinking 'layout template'. We really need to fix that.

With your explanation (and my recognition), very good idea.

**Comment by sutibun** [comment]
We should have nice defaults. How about a swanky homepage.

I took a look and found [this](http://blog.teamtreehouse.com/50-homepage-website-layouts-using-featured-details-icon-lists), which lists different homepage layouts. I liked these in particular.

- [Example 1](http://www.learndot.com/)
- [Example 2](https://www.gradeable.com/)
- [Example 3](http://www.acquisition-labs.com/)

A simple one page layout basically.

I don't know if this can all be done with Layouts but this is my vision for a default Backdrop homepage

![homepage](https://cloud.githubusercontent.com/assets/14132746/9701919/717e1420-540a-11e5-8e01-3678ee794d1a.png)

- **Nav section** Self explanatory. Menu links.
- **Featured image section** - what if the user can click here and upload a custom featured/cover photo. The default is an automagically generated image with the site's name on it along the lines of [Wordle](http://www.wordle.net/)
- **Latest posts** A View listing the latest content with a link to the hello world post
- **Extra content section** Another block for user to add more text
- **Footer section** Self explanatory. Footer links and copyright info.

**With this default homepage, a new user would have something to play immediately** without looking into the settings, creating views, etc. Just click and edit.

On top of that, a Backdrop's default look will stand out from a Wordpress' default.

**Comment by quicksketch** [comment]
Thanks for chiming in here @sutibun! From what you've described, the homepage would use a single-column layout template (which we already have). The only trick to doing what you've suggested is making the new blocks for the out-of-box experience. I think we could get a long ways towards what you're describing by making some kind of "Background image" block, or allowing a custom background image to be added to the header block through configuration.

**Comment by sutibun** [comment]
Yes, @quicksketch single column.

I just don't think a sidebar belongs on a homepage (Depends really but I'd say usually) because then it looks like a blog. I find myself trying to modify (correct?) this. On Wordpress, I can achieve this look since WP theming is fairly simple to me.

For my Drupal site, I've given up trying to make it look how I want it to. I already know how to design using CSS and HTML but I don't want to invest tons of time to learn Drupal design. It took me a few years to finally be at a decent Drupal builder. I'll delay the design curve.

This is likely just my preferences talking, but I think a homepage should look different from the rest of the site.

Since you brought it up, block should also have the capabilities to add images. My hack is to upload an image on an article type, copy the image URL, and paste the image URL on the block. Blah.

**Comment by quicksketch** [comment]
> Since you brought it up, blocks should also have the ability to add images in addition to text.

This will be solved later this month when 1.2 comes out. :smile: See #1088.

However the ability to make a background image is a different thing entirely and should still be a separate feature for us to work on.

**Comment by sutibun** [comment]
@quicksketch Ah, nice.

Maybe it doesn't have to be a background image for the homepage. Simply an image.

**Comment by quicksketch** [comment]
> Maybe it doesn't have to be a background image for the homepage. Simply an image.

We could go both ways on it for sure. Having a built-in background image option may be useful because users typically aren't allowed to input CSS to make such a background. If we decide to just support uploading an image at all, perhaps putting a focus on making blocks fieldable would help: https://github.com/backdrop/backdrop-issues/issues/100

**Comment by docwilmot** [comment]
Layouts can do this of course, even though for now the background image would need to be specified via CSS. My [Senjo Layout](https://github.com/backdrop-contrib/senjo) layout, coupled with the Colihaut theme, in use on [Wilmurt.com](http://wilmurt.com/) is similar in design to what youre suggesting I think, though nowhere as slick as your sample sites.

Should be a good idea to design a block that allows placing a configurable image background and superimposed menu and text.  We could probably even 'improve the slider to have multiple text overlay regions.

And the area below the slider is fullwidth if you dont add any blocks to the sidebar.

But it can be done, at least.

**Comment by sutibun** [comment]
If the block with a background image will take too long, we can go with a regular image for now. It'll be good enough for 1.0 version. There's no need to delay the default homepage layout. We can swap them once the functionality is there.

**Comment by klonos** [comment]
@docwilmot:

> ...in use on [Wilmurt.com](http://wilmurt.com/)...

OT, but are you aware of the ```Notice: Trying to get property of non-object in project_release_node_view() (line 747 of /home5/jkiddees/public_html/wilmurt/modules/project/project_release/project_release.module).``` series of errors on the website?

**Comment by docwilmot** [comment]
No I wasnt, thanks. Only seen for anonymous. Its just a demo site so broken things are likely.

**Comment by klonos** [comment]
> Its just a demo site so broken things are likely.

Thought so. Still thought I'd better mention it :wink:

**Comment by sutibun** [comment]
Yay. This thread got mentioned in the [design meeting](https://youtu.be/ZOnWmiOV9mA?t=34m43s)

Just two thoughts.

1. I understand *that* one page layout look can be considered a design trend.
    
    What I am really for though is **a default homepage that looks different from the rest of the site.** It doesn't necessarily have to be what I suggested with the featured image.
    
    The default homepage design of most CMSs  all look like the blog homepage (2 columns, header, recent posts in asc order & footer ) including the category page, the tags page, etc. It's like there is no thought going beyond **this** design pattern. Sure, it fits for the blog but *must* this design pattern extend to the whole website?
    
    I'd even go so far as to say the category/tag page needs it's own design. Doesn't need to be radical. What if the category page listed [posts with just its title](https://signalvnoise.com/design). Is this great? Maybe. Maybe not. But, at least, one can visually tell when they're on the homepage, the blog, and the category/tag page. ![backdrop-layout](https://cloud.githubusercontent.com/assets/14132746/9806887/914722d8-5810-11e5-9a5e-ce1352ed4e16.png)
    
    It's one of those little things that can help Backdrop stand out. If everyone is zigging, you zag. 
2. I liked what you said earlier.
    
    > New users tend to find things easier to modify than to create something new
    
    I think we also need to consider the Backdrop onboarding experience. By giving new users a default design they can play with and customize immediately (e.g. upload their own featured shot, add custom text after the post listings) it'll impress on them that Backdrop is easy. It'll get them editing instead of thinking where to start.
    
    And what would be a good idea is if every Backdrop version (maybe just major versions?) comes with a new default theme. (I think Wordpress does this) What happens to the old design? It becomes a contrib theme that old users can keep if they want. Every major new version of Backdrop will look different (think iOS 1.0 vs iOS 7)

**Comment by quicksketch** [comment]
I think we're all in agreement at this point that adding a default out-of-box layout configuration for the homepage would be a good idea. And that using the single-column layout would also be a good fit for today's sites. The nice thing is we're not really committing anyone to a particular structure with this. It's just the default configuration, not functionality we need to write or support in the future (and it doesn't affect existing sites). Meaning we can change it to fit with the times if another approach becomes dominate later.

> I'd even go so far as to say the category/tag page needs it's own design.

I think this may be a good idea as well, these pages are sorely neglected. Let's make a new issue for this.

> And what would be a good idea is if every Backdrop version (maybe just major versions?) comes with a new default theme.

That is the hope. We mention this just about every design call. Even if we created one mid-release, we'd be happy to include it (if we could agree upon it). I think the way this will go is a theme would need to be contrib made first, then absorbed into core if it fits the bill. I don't think there's an issue for this. I'd rather see this as a one-issue per attempt rather than a 300 comment monster.

So maybe for starters here, we've all kind of agreed that having a front-page layout configuration would be a good idea. Should we ship with a single-column front page configuration out-of-box and work to add the key blocks later (e.g. a callout block of some kind)?

**Comment by sutibun** [comment]
I say let's start simple and build off a basic foundation. We don't need to build anything complex immediately.

Ship with a single-column layout featuring

- a wide image featuring [something abstract or motivating](https://www.flickr.com/photos/pictoquotes/13143774613/).
    - no slideshow. no background image. Just a simple image tag embedded there via a block.
- some preloaded text (e.g. "welcome to your hompage. Take a look around. Feel free to customize this by hitting the edit button and make the site yours.")
- a view listing recent posts

Just make sure there's a limit to the width of the text section. It becomes unreadable if there's more than 60-70 charaters per line (something to that effect. I forgot my design theory)

**Comment by klonos** [comment]
We can use Drop as an image and have some link to point to the admin UI that allows to change it. That way, we are not only shipping with an image out of the box - we are also "teaching" the user how to do things.

**Comment by sutibun** [comment]
@klonos ah, the dragon! Yeah, we should definitely have that (him/her?)

I always hated the Drupal logo. Looks ugly and creepy. It was always the first thing to go. But everyone likes dragon. I do.

Maybe what we can do instead is *subtly* show off the dragon logo, something similar to how Github does theirs.

![image](https://cloud.githubusercontent.com/assets/14132746/10075166/ea3c6770-6299-11e5-97ea-de37989bb6cb.jpeg)

It's small and deemphasized but still there. Something like the Nike logo placement in ads. It's not overt… but more like a gentle reminder.

![image](https://cloud.githubusercontent.com/assets/14132746/10075165/ea2ea630-6299-11e5-916d-e82306c4fb2f.jpeg)

And because they're tasteful and subtle, we could add them on the footer and the header and get away with it.

**Comment by klonos** [comment]
Just to clarify... I was mostly referring to the dragon image in https://backdropcms.org/presskit#mascot (the second one - the one where Drop is lying down). We could use that as horizontal banner image.

**Comment by sutibun** [comment]
@klonos ah kk

**Comment by jenlampton** [comment]
Yes. :+1:  Yes :+1:  Yes :+1:   Please let's get a default home page layout in core. I *love* where this is going so far.  Who wants to make us one? :)

**Comment by Graham-72** [comment]
I was having a look today at creating a single-column home page layout using an editable custom block so that the user can upload a banner image of their choice, but I got caught by the disappearing image problem referred to in issue #1385 Inline images disappear after a while. Are we hoping to fix this one?

**Comment by Graham-72** [comment]
Now I see that this is also raised as an issue and bug report at #1373 .

**Comment by jenlampton** [comment]
I would love to see this in core, but since it hasn't seen any activity since January and we release tomorrow, I'm officially pushing it to 1.5 :)

**Comment by jenlampton** [comment]
My first pass at a PR includes:
* A new one-column (Boxton) `Home page` layout at /home.
* A new view 'Promoted content'. This is a clone of the Front page view, but provides a block display, and empty text similar to the old front page content: `There is no promoted content in the system yet.`
* switches the front page /node to /home.

**Comment by jenlampton** [comment]
I've made a list of all the slippery-slope things that come from making this change in the top post in this thread. I think we should stop at adding new things with this commit, and save all the removing/replacing old things for Backdrop 2.x.  I'm going to work on getting the tests working and then move on to adding an image/slider block for the home page.

**Comment by jenlampton** [comment]
I'm thinking we should switch from adding a new view to updating the previous one. Remove the page display and add a block. Marking as NW.

**Comment by jenlampton** [comment]
Okay, I just pushed a new PR to https://github.com/backdrop/backdrop/pull/1500.

This one adds the new home page layout in the standard profile.  Could use a review.

**Comment by quicksketch** [comment]
PR is looking great. Feedback left and addressed by @jenlampton. It's currently failing tests though, so needs work.

**Comment by jenlampton** [comment]
Yes, I'm finding some odd functionality in rss.xml that is not reproduced properly in views. Trying to figure out what it is and why it's not working the same way.

**Comment by jenlampton** [comment]
> Wow, that screenshot really drives home how much we should definitely remove the Title from the home page layout in #1042.

@quicksketch said I could remove the title in https://github.com/backdrop/backdrop-issues/issues/1152#issuecomment-245492337 :) I have been wanting to do that for **so** long. :D

**Comment by jenlampton** [comment]
I just pushed a PR that nolonger fails tests!  Needs more review please :)

**Comment by klonos** [comment]
>I just pushed a PR that no longer fails tests!...

Actually, tests are not green:

Some checks were not successful
2 errored and 1 successful checks
zenci/deploy/pr-1500 — Failed to get code from github.
zenci/test/php53/pr-1500
zenci/test/php70/pr-1500 — 0

**Comment by klonos** [comment]
...and the sandbox WSODs.

**Comment by jenlampton** [comment]
Interesting, looks like a random failure on PHP7 only? Yeah, we know about that one: https://github.com/backdrop/backdrop-issues/issues/1478

**Comment by jenlampton** [comment]
I was having trouble with getting the old PR testing so I've made a new one: https://github.com/backdrop/backdrop/pull/1539

**Comment by quicksketch** [comment]
PR is looking really good! And passing tests too, great!

I left some feedback on the PR. I have a hangup with the way the "No promoted content" message is shown. Right now it will double-execute the view, which won't be acceptable. Although I see what you mean that it would be easy to remove the block with these links, this block would have no purpose at all on an existing site. You'd never want to place a block that said "No promoted content", and as it's written currently, if there *were* promoted content, the block wouldn't do anything at all.

---

From a chat in Gitter, @jenlampton suggested that we make a block that is *just* the create content links, which might be useful in an eventual dashboard, so the block would have some purpose. However to move this forward, we decided to just remove these links entirely and move this task to a follow-up. In the mean time we can just add the empty text to the View default configuration.

**Comment by jenlampton** [comment]
Pushed an updated PR that addresses all the feedback left by @quicksketch .

**Comment by quicksketch** [comment]
Looks great now!

One more point of feedback and question though. Why is the path to this new layout "home"? Everywhere in Backdrop we refer to the front page as well, the front page. We don't call it the "home" page, so why would our layout by "home" instead of "front" in the out of box configuration? I'd love for this to go in ASAP, but this has been bothering me for a while now. As we won't be able to easily change this (well other than making all the same test changes over again), I'd like to make sure we use a reasonable name.

**Comment by jenlampton** [comment]
> Why is the path and name of this new layout "home"?

Because that is what normal people call it. I have no idea why Drupal decided to call it the front page, but that's not terminology that the rest of the world uses.

**Comment by quicksketch** [comment]
Well, perhaps not scientific: https://www.google.com/trends/explore?date=today%2012-m&q=%22home%20page%22,%22front%20page%22

It's worth noting that "home page" means multiple things, like a user's personal blog would be called their "home page", as would the default page loaded by a browser when you open a new window. So those trends might not be applicable to our actual problem here.

The internet at large seems to use these terms interchangeably. Drupal's documentation also uses them at the same time: https://www.drupal.org/node/265172

However, there's no doubt that this is intentionally introducing an inconsistency in our system that otherwise we don't have. Right now we use "home page" exclusively to reference a user's homepage when posting a comment to a node. There are a fair number of references to "home page" in code comments or tests, but *never* in the end-user interface (as far as I can find).

> I'd like to fix these too, eventually.

In truth, I don't think we will *ever* change all usage of front page to home page. It'd be a ton of API change and string change. From a search, we have 273 references to "frontpage", "front page" or "<front>" in our code. Providing backwards compatibility for a string like this would be messy, so it'd likely have to be a clean break in 2.x. But if that's the case, we should keep consistency for now and do the entire rename all at once.

**Comment by jenlampton** [comment]
> It's worth noting that "home page" means multiple things

I don't care about the many meanings. I do care what real life human beings call the front page of their site. They don't call it the "front page" of their site. They call it the "home page" of their site. 

> There are a fair number of references to "home page" in code comments or tests, but never in the end-user interface (as far as I can find).

Don't you think that a huge problem when all of our users call the home page of a site it's home page, and **none** of our user-interfaces do?  Think about it this way: when you create a panel page that serves as the home page of a site, what do you call it? You call it a home page. That's exactly what we did here.

> However, there's no doubt that this is intentionally introducing an inconsistency in our system that otherwise we don't have.

As I said before: `The win over having something everyone understands outweighs the inconsistency in this case, imho.`

**Comment by quicksketch** [comment]
Well, doing a little research on sites that I know are running Drupal that I didn't build (though I may have helped on them later):

http://www.grammy.com/home
http://www.msnbc.com/home
https://www.tesla.com/home
https://www.syfy.com/home
https://www.harvard.org/home
https://www.drupal.org/home
http://www.telemundo.com/home

I turns out I couldn't find a single `/front` site of the sites I tried. Note almost all the above sites redirect from `/home` to just `/`. Visiting `/front` on all of them are 404s.

So it looks like this might be a "just me" concern. From the evidence of existing sites out there using Panels or custom callbacks, these sites all at least chose "home" with no prior guidance on what to name the path. So seems fine to me. :+1:

**Comment by jenlampton** [comment]
I would be happy to change the text around the setting for `Front page` to Home page too, if that helps clear up inconsistency issues.  Something like this:

![screen shot 2016-09-12 at 1 28 17 am](https://cloud.githubusercontent.com/assets/397895/18429474/5d7d33cc-7888-11e6-8b83-4eaea257f6f7.png)

See https://github.com/backdrop/backdrop/pull/1543

**Comment by quicksketch** [comment]
Yeah let's make that separate. I'm not sure we'd ever be able to clean up the inconsistencies. Let's move it to a new issue for bikeshedding.

**Comment by jenlampton** [comment]
Bikeshed is located here: https://github.com/backdrop/backdrop-issues/issues/2162

**Comment by quicksketch** [comment]
I made yet another follow-up to help deal with the now-missing login block: https://github.com/backdrop/backdrop-issues/issues/2163

**Comment by quicksketch** [comment]
Well, at least now I feel like we had the discussion on "home" vs. "front" so it's taken place and recorded.

With no further serious concerns, I've merged https://github.com/backdrop/backdrop/pull/1539 into 1.x for 1.5.0. Thanks everyone for this 1.5 year journey! We still have work to do and a lot of file-ups already in the queue, but this lays a tremendously important foundation for future work!
