### ISSUE TITLE
Disabled themes screenshots wrap funny

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#1047]
@wesruv 
Same as https://github.com/backdrop/backdrop-issues/issues/988
![disabledthemeswrapfunny](https://cloud.githubusercontent.com/assets/1042283/8478538/c586420a-2097-11e5-88ca-08d08a7eeb3d.PNG)

---

PR: https://github.com/backdrop/backdrop/pull/2853

**Comment by wesruv** [comment]
Thanks @docwilmot!

**Comment by wesruv** [comment]
PR Ready for this one: https://github.com/backdrop/backdrop/pull/991

**Comment by quicksketch** [comment]
Yikes, it's been a long time since this was filed. I found a few issues in the PR. @wesruv, do you think you could revisit this issue?

**Comment by BWPanda** [comment]
Here's an updated [PR](https://github.com/backdrop/backdrop/pull/2853) that addresses @quicksketch's issues.

I found that the 'fix' for `flex-wrap` actually caused my disabled themes to display 4 to a line (instead of 3 like before the PR) which caused a horizontal scrollbar. So I commented out that line which fixed it, but this'll either need removing or replacing with a different solution if that issue is still relavent for other browsers...

**Comment by klonos** [comment]
@BWPanda care to refresh the PR sandbox?

**Comment by BWPanda** [comment]
@klonos Done

**Comment by klonos** [comment]
Thanks @BWPanda 👍 ...looks much better now:

![screencapture-2853-backdrop-backdrop-qa-backdropcms-org-admin-appearance-2020-06-13-01_18_20](https://user-images.githubusercontent.com/2423362/84550736-187cba80-ad14-11ea-8835-b9cdb7a83fa0.png)

![screencapture-2853-backdrop-backdrop-qa-backdropcms-org-admin-appearance-2020-06-13-01_18_48](https://user-images.githubusercontent.com/2423362/84550742-1d416e80-ad14-11ea-90c6-9e5a1e6086d3.png)

**Comment by klonos** [comment]
...wondering if it'd look better on narrow screens if the theme title/version, description, and "Enable" links we placed beside the theme thumbnails instead of bellow them:

![screencapture-2853-backdrop-backdrop-qa-backdropcms-org-admin-appearance-2020-06-13-01_19_26](https://user-images.githubusercontent.com/2423362/84550835-67c2eb00-ad14-11ea-9b39-23ead3bf9c85.png)

That way we'd put the white space to good use, and avoid too much scrolling when many themes are installed 😉 

I've also left some feedback in the PR.

**Comment by BWPanda** [comment]
I can no longer replicate this issue on the latest Backdrop 1.x... Can anyone else? If so, how?

**Comment by stpaultim** [comment]
I was able to recreate the problem, but in a manner that might not be realistic and applicable. 

I used the Chrome inspector to triple the length of the description for the Basis contrib theme and this broke the layout. 

![Appearance___Simplo](https://user-images.githubusercontent.com/3144571/90088488-abba7800-dce4-11ea-9fbf-8fd387faa95a.png)

**Comment by stpaultim** [comment]
OK, I got it to happen without an manipulation. The description for the Teamwork 15 theme goes onto 4 lines and this is apparently enough to block the next row of themes from floating to the left. 

![Appearance___Simplo](https://user-images.githubusercontent.com/3144571/90088977-e07aff00-dce5-11ea-8e4e-318e4fa21536.png)

**Comment by BWPanda** [comment]
Based on the feedback from @klonos and @docwilmot, I made a new, simpler PR that I think fixes this, without a bunch of unnecessary, duplicated code: https://github.com/backdrop/backdrop/pull/3239

**Comment by docwilmot** [comment]
Tested locally, works well. RTBC for me, although I am not great at CSS.

**Comment by BWPanda** [comment]
Will wait for another review then before I commit this.

**Comment by stpaultim** [comment]
Well, I also tested this locally and it worked for me. I reviewed the code and don't see any problems. But, I'm also not very familiar with css practices/standards in Backdrop CMS core.

**Comment by BWPanda** [comment]
Thanks for filing this @docwilmot (and sorry for the delay)! Thank you @wesruv for the original PR on which the fix was based, and to @quicksketch, @klonos & @stpaultim for testing and feedback. I've merged https://github.com/backdrop/backdrop/pull/3239 into 1.x and 1.16.x.
