### ISSUE TITLE
Email vs e-mail?

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#1056]
Currently both in core in similar numbers. Lets pick one and standardize.
See https://www.drupal.org/style-guide/content#relatedwords
We should also have a similar style guide perhaps.

**Comment by Graham-72** [comment]
Yes, I think we should follow the Drupal styleguide and use 'email', used as an ordinary noun rather than a name, so with a lower-case e unless at the beginning of a sentence or perhaps when a heading. This is also as stated in our Guardian newspaper styleguide http://www.theguardian.com/guardian-observer-style-guide-e .

**Comment by klonos** [comment]
I personally think that email is easier/faster to type, but...

https://www.google.com.au/search?q=email 7,540,000,000 results
https://www.google.com.au/search?q=e-mail 11,490,000,000 results

If we decide to go with the dash-less one, I think also loose the capital "E".

**Comment by MrHaroldA** [comment]
In Dutch, it is officially e-mail. That (and other languages) probably adds up to the count.

**Comment by quicksketch** [comment]
I'd prefer to follow Drupal on this one and use "email" as well. I used "e-mail" in Webform module for years and always regretted it in my heart of hearts. Adding the hyphen is indeed harder to type, which can make selecting a field more difficult from a select list. HTML5 uses `<input type="email" />`; the resulting inconsistency between label and markup can be grating for me.

The New York Times dropped the hyphen: http://www.thewire.com/national/2013/10/tweet-and-email-are-now-fit-print/70864/
As did the AP: http://www.huffingtonpost.com/2011/03/18/ap-removes-hyphen-from-em_n_837833.html

I read that the SF Chronicle still uses "e-mail", but my Google search results of their site seems to indicate otherwise, and "email" seems dominate there as well.

**Comment by quicksketch** [comment]
> See https://www.drupal.org/style-guide/content#relatedwords
> We should also have a similar style guide perhaps.

It's interesting that this is a "drupal.org" style guide, not for Drupal the software itself. That may be one of the reasons why our code-base is mixed instead of standardized one way or the other.

**Comment by quicksketch** [comment]
With https://github.com/backdrop/backdrop-issues/issues/476 going in to add "Email" module this pretty well seals the deal here in favor of hyphen-less "email". Although I'd love to replace every occurrence wholesale, I think we should only change the occurrence that are code comments or non-translated strings, to avoid having translations broken.

**Comment by docwilmot** [comment]
:smile: 
I guess that's it then.

**Comment by jenlampton** [comment]
sounds like we can close this now?
