### ISSUE TITLE
[UX] "Node" versus "Content"

### ISSUE THREAD

**Issue by MrHaroldA** [backdrop/backdrop-issues#1057]
Here's a long shot, but it has been on my mind for years now.

The term "node" is quite vague, and often replaced by "content".
- admin/content could/should be admin/node
- "Content types" could/should be "Node types"
- "Add content" could/should be "Add a node"
- etc / or "visa versa"

I often have trouble explaining to clients what a "node" is, and that it's interchangeable with "content" but used at random.

What's your opinion on this?

**Comment by docwilmot** [comment]
This would be a hell of a beast to tackle, 'node' === 'drupal/backdrop' practically.

**Comment by quicksketch** [comment]
I think @MrHaroldA is recommending that we change the word "content" to "node", which probably isn't as large a change as the other way around. There still are several places, like `/node` where it wasn't converted in the first place. The Views UI is still full of "node" mentions as well.

However, I'm not sure this would be a good change. The word "node" would likely cause immediate confusion, as new users would be very unlikely to know what that word would mean in a Backdrop context. It's after users have been using for a while that the inconsistency between the two terms becomes noticeable.

**Comment by MrHaroldA** [comment]
> The word "node" would likely cause immediate confusion

That is my main concern/annoyance, but like I said; this is probably a way too big change to get uniform. "Node" has always confused our clients, and it's impossible to shield them from it.

**Comment by sutibun** [comment]
The first time I *finally* got the guts to try Drupal 7 some years back, after hearing of its rumored steep learning curve, the mention of "nodes got my head spinning.

I **had no idea what they were talking about**. It seemed like a programming thing.

> Geez. Drupal really is hard.

It immediately gave support to the rumor and left me with the impression that Drupal was to require a lot of work.

It took a while to wrap my head around the word. The best way I got to understand it then was to think of node as synonymous to Wordpress' post.

Only now, knowing Drupal better years later, do I see how silly that was but impressions count. I stuck around because I am stubborn but others might've bounced.

Backdrop *can* have all the latest features, the best themes, the coolest plugins, the best community but **none of that matters if the onboarding experience has such high friction.**

It's like going to the DMV for the first time and the clerk asking, "Where's the DL 694?" You'll be like, WTF is that? You'll **feel** like an idiot for not knowing what that is. (Adding to the **impression** that a DMV is not a place you want to be at)

Already the experience is going down the hills which is sad since it's totally unnecessary.

Had the clerk asked instead, "Good morning. Do you have the California Commercial Driver License Self Certification' form?" you'd at least realize what he is talking about.

It's the same here.

Node is a technical term.

We know what that is... some because we're technical... others... well, we were forced to pick it up along the way.

However you slice it, it's a potential obstacle when someone new to Backdrop has to wrestle with a word instead of the CMS itself.

I push for the removal of any mention of node where a user might see it, including the URL.

**Comment by jenlampton** [comment]
I'm also in favor of removing `Node` from as many places as possible in the UI, Let's tackle them one at a time, please (search for, and if one doesn't exist) open an issue each time you find one we should kill :)

**Comment by mikemccaffrey** [comment]
> I push for the removal of any mention of node where a user might see it, including the URL.

I agree with @sutibun. It seems much more clear if new nodes would start off with paths like /content/123 instead of /node/123. And we might want to consider a full conversion of the "node" module to be the "content" module in backdrop 2.x.

**Comment by MrHaroldA** [comment]
Ok, this is a big POC wit BIG WARNINGS! ;)

```bash

# move .git out of the warzone
mv .git /tmp/git_backup

# replace all occurrences of 'node' with 'content'
find . -type f -exec sed -i 's/node/content/g' {} +
find . -type f -exec sed -i 's/Node/Content/g' {} +
find . -type f -exec sed -i 's/NODE/CONTENT/g' {} +

# revert exceptions
find . -type f -exec sed -i 's/fileicontent/fileinode/g' {} +
find . -type f -exec sed -i 's/importContent/importNode/g' {} +
find . -type f -exec sed -i 's/parentContent/parentNode/g' {} +

# rename directories and files
find . -type d -iname "*node*" -exec rename node content '{}' \;
find . -type f -iname "*node*" -exec rename node content '{}' \;

# revert JavaScript / libraries
git checkout core/misc

# move .git back and spot the differences! ;)
mv /tmp/git_backup .git
```

Installation went fine; as does content creation. I'm running the tests right now ... a couple of failed tests already, and a fatal in the Comment module tests ...

I'm stopping here as this is a bit out of scope for now; but this quick test shows we could migrate from node to content with a big bang!

**Comment by gifad** [comment]
I join the conversation to approve the concept of `content` versus `node` : I'm porting the drupal scald suite, and, for some reasons, I replaced the specific entity `scald atoms` with plain nodes, with appropriate field - it's now a bit confusing to have "media nodes" in the same area as page, article, post...
It would be more natural to have "media content" besides "rich text content".
BTW, we could have "file content", instead of the (hidden) File entity...
Technically, the question which remains open is : should this "content" object be based on entity, or node ?
Or, with a different POV, does revisions and comments shoud be standard on every content ?
Remember that BackdropCMS is a **Content** management system...

**Comment by bd0bd** [comment]
The word "node" is a headache in understanding what this all is about - I think for many people.
