### ISSUE TITLE
Provide an Existing content block for layouts

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1076]
This is something that already exists for panels, and should be easy to port.  We need the ability to add a teaser for node X into a layout.

Side note: Necessary for backdropcms.org find modules page.

**Comment by klonos** [comment]
...do you mean a node-as-block functionality?

**Comment by klonos** [comment]
> Side note: Necessary for backdropcms.org find modules page.

@jenlampton That page has landed in bd.org even though this feature is not implemented yet. What did you have in mind when you posted that side note?

Also, in the spirit of "put things where people expect to find them" (credit to you if I recall correctly), how about we also implemented a way to create a *new node* from a layout? Here's how I envision this feature to work UI-wise:

1. Add a "Add content block" option to the rest of the available list of blocks.
2. This option has two sub-options: "Select existing content" and "Create new content"
3. "Select existing content" exposes a content browser (views generated, with filters to narrow down to specific content types, specific author, date etc.)
4. "Create new content" prompts for content type selection, gets the user to the node create page and upon save redirects back to the layout page where the whole process started from with the content node added as a block. (cancel preforms the same redirect but with no content block added obviously).
5. We add a "Place as a block to a layout" button/link in the node create/edit page (#1131 ??)

**Comment by klonos** [comment]
...well not exactly #1131, but related.

**Comment by jenlampton** [comment]
@klonos 
> ...do you mean a node-as-block functionality?

Yes, but with a view mode selection, so you can display a node's teaser, etc. Though we have the find modules page, it's still incomplete as it's missing several useful bits of information. Hopefully we'll get those added shortly :)

**Comment by klonos** [comment]
If I got this right, what we are trying to achieve here is to get the "Add block" dialog to have an "existing content" option that leads to a content browser where people can select a specific piece of content to be added as a block. As @jenlampton said, there should be options to select the view mode so that people can show a node teaser for example.

If this is the goal, then we should also allow the same to happen from the content create/edit form with a layout/region browser. So this issue here pairs nicely with #1131 which will allow to set the visibility condition for nodes from the content create/edit form as well as #1077 that will do the same from the Layout edit form.

**Comment by dboulet** [comment]
Couldn’t this easily be solved by using Views? Just create a view that displays a single node in a block and add the block to your layout.

**Comment by docwilmot** [comment]
PR Up.

**Comment by docwilmot** [comment]
Essentially ported CTools implementation of this:
- Add an existing node as a block
- Select node by autocomplete or entering NID.
- Select list for view mode
- Option to keep or hide node title
- Option to hide node links (Read more etc)
- Link block title to node
- Override node template just for the block with custom `node--content-block-<NID>

**Comment by gifad** [comment]
This issue is marked "pr - needs review" - does the need apply to this issue or to the PR ?
I chose to comment directly inline the PR, but would report here if requested.

**Comment by docwilmot** [comment]
@gifad I missed your comments on this. The page title seems to be displaying fine. A "block" view mode would be a good idea too, I think. I'll need to figure that out.

**Comment by gifad** [comment]
> The page title seems to be displaying fine.

sure, but if the page shows the same node in other blocks after yours, these blocks will have no node title.
I agree this is perhaps not a real world use case, but I just pointed out that your
```
+    // Hide node title if not required.
+    if (empty($this->settings['leave_node_title'])) {
+      // But first save the title so it can be shown if needed as the block
+      // title.
+      $this->clone_title = $node->title;
+      $node->title = NULL;
```
actually clears the title in the entity cache, which is certainly not intended…

**Comment by docwilmot** [comment]
OK, thanks @gifad. This is done.

**Comment by quicksketch** [comment]
I gave https://github.com/backdrop/backdrop/pull/1246 a review. It looks great! The only minor complaint I have is a namespacing issue, that I think the class should be `NodeBlock` rather than `ContentBlock`. Or if you want to be complete, `NodeContentBlock`, let's just keep it under the node namespace.

A bigger question that mirrors similar requests we've had: what about placing arbitrary entities instead of just nodes? What we have in the PR is great for nodes, and we could go with that. But if we want arbitrary entities later, it will require an upgrade path and possibly an API change.

However, I can't deny that nodes are by far much more common than other types of entities. This implementation also has specialized treatment for the submitted by line. And this is mostly a convenience thing; you can accomplish similar functionality by using a View if really needed. What do you all think?

**Comment by gifad** [comment]
> A bigger question ...

This PR is using `node_view()`; should Entity API be complete, including `entity_view()`, "arbitrary entities" would certainly already have been supported…

Other "details" like _submitted_ could be handled by view modes, via _extra fields_ (missing [pseudo_field](https://www.drupal.org/project/pseudo_field), _a minima_).

**Comment by docwilmot** [comment]
> what about placing arbitrary entities instead of just nodes?

Annoyingly, despite the same query being raised about conditions, I didn't think of that. Hold everything, I'll try and convert this (by May15 :smile: ).

Unless @gifad can take this? I've got to wrestle with all the other #345 PRs, so some assistance would be great.

**Comment by jenlampton** [comment]
> Unless @gifad can take this? 

I can take this one @docwilmot, I've got something about 1/2 done already :)

That's a good point about doing this with a view. Admittedly, that's what I have been doing for all of Backdrop 1.x since we haven't had this feature. I do think the user-experience of building a view for every single node is a bit much. I still think this will be a nice feature addition.

**Comment by docwilmot** [comment]
Great, go forth and conquer.

**Comment by docwilmot** [comment]
(Feeling poetic this evening)

**Comment by dboulet** [comment]
> I do think the user-experience of building a view for every single node is a bit much.

Can you instead have the view accept a single node ID as an argument, then just re-use that block over and over to display any node?

**Comment by jenlampton** [comment]
You can. But you need a UI to define the node ID. Panels has this, bit I
don't think layouts does yet.

- -
Please excuse brevity and typos. Message typed with my thumbs from an Open
Source OS.

**Comment by klonos** [comment]
OT, but:

> ...from an Open Source OS

???

**Comment by jenlampton** [comment]
from my phone :)

**Comment by serundeputy** [comment]
Moving to 1.5 feel free to move it back if someone has the bandwidth to take it on.

**Comment by docwilmot** [comment]
@jenlampton did you every get around to this? I think it was close enough; would be a shame to punt it again.

**Comment by jenlampton** [comment]
@docwilmot not yet, but I think it would be a good one for 1.5, so not giving up yet. I'll unassign from me in case anyone else wants to take a stab at it. :)

**Comment by docwilmot** [comment]
> I can take this one @docwilmot, I've got something about 1/2 done already :)

do you still have the 1/2?

**Comment by jenlampton** [comment]
> do you still have the 1/2?

I can't find the branch :( I stole most of the code from panels though, so it shouldn't take too long to reproduce.

**Comment by docwilmot** [comment]
We had decided to change this to a generic block which allows a user to select any entity (not just nodes) and display as a block. Had a look at this and can't decide how to structure it. 

We can take the easy way out:
- have dead simple block form which asks only for the entity type and its ID and display mode
- a simple submit function that saves the ID
- a `getContent()` that just searches for the `ENTITY_view` and displays the ID'd entity

If we had custom display modes this would be barely "enough" as users could manipulate the rendering of the entity through display modes. But since we don't, it would be nice to have some way to control how the entity displays. The active PR here for a Node block, for example, allows the user to hide the title, hide the "submitted by" stuff, etc. We'd need some way to offer similar options for other entities.

So we would need some way during `Block::form()` to bring in extra fields per entity. Similarly during view in `Block::getContent()` would be nice to control the display of taxonomies differently from nodes for example. So the Block config form could have a select list for selecting the entity type, and loads the specific fields for that entity via AJAX.

This is where I'm not sure. This could mean either a new `hook_entity_block_extra_settings()` with callbacks for `form()` and `getContent()` and so on. Or an `EntityBlockSettings` class and extend for each entity type. 

Either way we'd need some way to build separate forms and call separate submits and have separate displays per entity. Any thoughts? 

P.s. this is looking 1.6-ish, I know, but I still like to finish what I begin.

**Comment by jenlampton** [comment]
> We had decided to change this to a generic block which allows a user to select any entity (not just nodes) and display as a block.

Did we? I think this is a very bad idea.

In Panels-land there is a "block" for a node, a term, and a user, and stops there. By having a different block for each entity-type things get a lot simpler.

In Backdrop-land this could be accomplished by having a three block classes addStandALoneNode, addStandALoneTerm, and add StandALoneUser.  If it's valuable, they could all extend a base class, addStandALoneEntity. I'm not sure how much code will be in common between the three entity types, but if there is some the parent class might be useful.

Keep in mind that we never want to show words like "Entity" or "Node" (if we can help it!) to end users anywhere in our user interfaces (or in our documentation, for that matter).  That's something only developers/coders should need to know about and understand. Asking people "what kind of entity do you want" is not an option - but allowing them to choose  "Add existing User account" or "Add existing category" is something they will understand naturally.

> If we had custom display modes this would be barely "enough" as users could manipulate the rendering of the entity through display modes. But since we don't, it would be nice to have some way to control how the entity displays.

This is definitely scope creep. Let's stick to allowing users to select a `view_mode`.  (it works for panels, it should be fine for us too). We do have a pending core issue for allowing custom view modes in core, and I'd rather see that before we reinvent field UI here.

> The active PR here for a Node block, for example, allows the user to hide the title, hide the "submitted by" stuff, etc. We'd need some way to offer similar options for other entities.

Other entities are less important than nodes. Let's start with getting those features in and add other features later. baby steps!

> So we would need some way during Block::form() to bring in extra fields per entity. Similarly during view in Block::getContent() would be nice to control the display of taxonomies differently from nodes for example.

Yes, `addStandALoneNode extends addStandALoneEntity` would handle this nicely.

**Comment by docwilmot** [comment]
> Did we? I think this is a very bad idea.

That's confusingly surprising!?! In this issue
- we proposed a Node block
- I built one and sent a PR
- @quicksketch reviewed, [said it was "great" but proposed we do a generic block](https://github.com/backdrop/backdrop-issues/issues/1076#issuecomment-213830424)
- Then you said you would do this and [had something 1/2 finished](https://github.com/backdrop/backdrop-issues/issues/1076#issuecomment-213872210)

What exactly did you have 1/2 finished then?

FTR I agree with you anyway; I think separate node, term and user block (and perhaps comments as well) is the way to go here since the configuration, storage and display of each is going to be so different. I don't think "entities" are necessarily similar things enough to have a generic entity block. (And also imagine if we get a beast like commerce in contrib with bunches of different entity types, thats going to really clutter that proposed "Entity" block.

So unless @quicksketch still prefers a generic Entity block (and can advise how to address the concerns in https://github.com/backdrop/backdrop-issues/issues/1076#issuecomment-245802372), I will refresh the Node block PR above, including the namespacing recommendations, and push again. I think it was close enough and could make it to 1.5.0.

**Comment by jenlampton** [comment]
> That's confusingly surprising!?!

I actually disagree with my former self a lot. ;)

> What exactly did you have 1/2 finished then?

I had implemented something similar for a site I was working on. I expect it was www.bootfitters.com. My plan was to take that, pull it into a branch and turn it into a PR. Sorry I dragged my feet so much on that, I should have let you have this one from the beginning.

**Comment by quicksketch** [comment]
> We had decided to change this to a generic block which allows a user to select any entity (not just nodes) and display as a block.

My initial comment above (https://github.com/backdrop/backdrop-issues/issues/1076#issuecomment-213830424) was not a demand or requirement, but just a question of whether a generic block was preferable. That's why I ended with the question, "What do you all think?"

So it sounds like between @jenlampton and @docwilmot we're in agreement that a node-specific block is a good thing. I also think the idea Jen had about (eventually) using a base class for the parts that are the same is great. Then modules that want to expose some/all of their entities for individual placement could do so, but it wouldn't be automatic.

So unless there is opposition to the current PR/approach, I'm fine with moving it in after addressing the current feedback. https://github.com/backdrop/backdrop/issues/1529

PR looks great in general. @docwilmot++

**Comment by quicksketch** [comment]
@docwilmot has addressed all feedback in the PR and we're all in agreement here. So https://github.com/backdrop/backdrop/pull/1529 has been merged into 1.x for 1.5.0! Yay, great job again on adding this highly-desired functionality.

**Comment by docwilmot** [comment]
woohoo!

**Comment by jenlampton** [comment]
Nice work @docwilmot!

**Comment by klonos** [comment]
Thanx you guys!! @docwilmot big 👍 for driving this home 🎉 

Boy is the presentation at DrupalSouth gonna rock 😜
