### ISSUE TITLE
Layouts: add a visibility condition for selecting a specific entity ID.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1077]
We need to add a condition to select a specific node ID (when the node context is available.) This is something that, I believe, existed for panels, and should be fairly easy to port.

Side note: we need this for the "find a module" page on backdropcms.org.

**Comment by quicksketch** [comment]
For anyone else running across this, you can work around this lack of condition by using the "Path" selector, and only show a block when the Path is "node/x" where x is the node ID.

**Comment by quicksketch** [comment]
I took a look at the PR in https://github.com/backdrop/backdrop/pull/1239. Thanks @docwilmot!

I think the current PR would work, but it immediately stands out to me that this could be an Entity ID condition rather than just node IDs. Then it would work for user ID, term ID, etc. I think we have the abstraction in place to make this possible already. Normally I would say let's iterate, but as the plugin name gets stored in existing layout configurations, if we implement this as-is now we'd need an upgrade path if we make it generic for all IDs later.

**Comment by docwilmot** [comment]
Updated to use entity IDs. 
See https://github.com/backdrop/backdrop/issues/1311

**Comment by quicksketch** [comment]
Woo! Brilliant! Needs tests yet, otherwise fantastic. One issue with namespacing the IDs: https://github.com/backdrop/backdrop/pull/1311/files#r58301573

**Comment by docwilmot** [comment]
Now has tests.

**Comment by quicksketch** [comment]
Great! I merged in https://github.com/backdrop/backdrop/pull/1311 for 1.4.0. We'll need to update https://github.com/backdrop/backdrop-issues/issues/1020 to accommodate for this change in the tests.
