### ISSUE TITLE
[UX] Open long filter tips in a dialog and rework the contents

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#1089]
The help text for filters is outrageously outdated. Now that we have a rich text editor, explaining to users how to type HTML seems ridiculous. Additionally, when clicking the "More information about text formats" link, the user can become disoriented opening up a new window (which in most browsers today will open a new tab).

Let's figure out a way to modernize the filter tips.

**Comment by quicksketch** [comment]
Kicking around some ideas here:

- Remove the "long" description filters entirely (including the extended HTML help)
- Remove the "short" descriptions from below the text format selection, and instead move that information to `filter/tips`.
- Open the `filter/tips` page in a dialog instead of in a new window. Change the link to say just "Formatting help"
- Instead of summarizing *all* text formats at once, only display help for the currently selected text format.

**Comment by docwilmot** [comment]
Yes to all of the above.

**Comment by serundeputy** [comment]
thumbs up;

**Comment by klonos** [comment]
:+1:

**Comment by docwilmot** [comment]
> Remove the "long" description filters entirely (including the extended HTML help)

Was just about to launch into this, but are you suggesting remove the concept of "long" filter tips entirely (which would be an API change `function _filter_html_tips($filter, $format, $long = FALSE)`)? or just trim the long to be short? Not clear.

**Comment by docwilmot** [comment]
So I was about to suggest a dialog with listed short filter tips with a "(more)" link for those filters with longer explanations. I think that would be useful for contrib filter modules with extended explanations. For example [Shortcode API](https://www.drupal.org/project/shortcode) has a long list of tips (see image below) which explains their shortcodes, which in fact could be useful when editing. 

But that cant work because calling `callback_filter_tips($filter, $format, $long = FALSE)` either returns the short tips or, if `$long` is true, the short and long combined. There's no obvious way to get just the rest of the long in a "more" link.

So in the modal it will have to be just the short.

BUT, again that means:
- `$long` wont be used anywhere
- modules like same Shortcode which dont have a `$long` but their short version is just everything, are going to make for ugly lists in the dialog.

So for now, I think just the short tips will work out fine for core filters, but we will need in the future to do one or a combination of
- change the callback to be able to return either long or short or both so we can have a more link (API change)
- deprecate the long and just recommend external help (API change)
- for people like shortcode, recommend or enforce a 'short' tips (maybe API change)

OR
- instead of a per-filter "more" link, a single "more" link at the end of the tips  that opens a new page (dialog) with the long filters

![tips](https://cloud.githubusercontent.com/assets/1042283/9520964/42024048-4c91-11e5-9302-f7fd7d54fb19.PNG)

**Comment by quicksketch** [comment]
> Was just about to launch into this, but are you suggesting remove the concept of "long" filter tips entirely (which would be an API change function _filter_html_tips($filter, $format, $long = FALSE)

Sorry just now getting back to this issue. I had thought we would nix long tips entirely. Though perhaps for the short-term, we could keep the "long" page but open it in a new window (the same behavior as the current "More information about text formats" link). We can put this link within the dialog to hide it away.

> modules like same Shortcode which dont have a $long but their short version is just everything, are going to make for ugly lists in the dialog.

Yeah, that may be the case, but it's going to be a lot better than the ugly lists being shown on the form itself. :stuck_out_tongue:

I'm going to take a stab at this issue and try to get it into 1.3.0.

**Comment by docwilmot** [comment]
If we collapse the filter fieldset as per https://github.com/backdrop/backdrop-issues/issues/938 we don't need to do this, and probably shouldn't as it adds an extra unneeded click (Click to open fieldset, find nothing there but another link to click to open a dialog :disappointed: )

**Comment by jenlampton** [comment]
Removing the 1.3.0 milestone. Since this is a UX related issue it can go in any time, and does not need to be officially scheduled for 1.4.0 :)

**Comment by jenlampton** [comment]
No progress made on this since last release, officially bumping from 1.5 to 1.x-future.

**Comment by klonos** [comment]
@bradbulger reported something related in #3516:

> Another example the client raised was the size of the FORMATTING OPTIONS fieldset label. The default `legend` font size is 120% - that's fine for fieldsets containing fields, but in a largely information-only box repeated for every formatted textarea on the form, it's a bit much.

![screen shot 2019-02-01 at 4 08 22 pm](https://user-images.githubusercontent.com/1234634/52156513-6b813080-263d-11e9-9550-f3d187db8dd6.png)

D8 for comparison:

![screen shot 2019-02-01 at 4 07 56 pm](https://user-images.githubusercontent.com/1234634/52156537-8bb0ef80-263d-11e9-985b-2493daf59a6f.png)

**Comment by jenlampton** [comment]
In usability tests the drop-down had proven more distracting than a link, so we're still a step ahead of D8. But I'd be all in favor of removing the capitalization and decreasing the font size too.

**Comment by jenlampton** [comment]
This could be a good use of [Add a help text indicator & tooltip for placing next to things that may be confusing](https://github.com/backdrop/backdrop-issues/issues/3707)!

**Comment by klonos** [comment]
I think that it's safe to close this old issue as outdated now. Since 2015 when this issue was originally filed, we've:

- made this a fieldset that is collapsed by default
- de-emphasized the fieldset, by not capitalizing the legend/title
- are showing help text (filter descriptions) only for the currently-selected text format

Collapsed (default):
<img width="726" alt="Screen Shot 2020-05-17 at 5 22 42 am" src="https://user-images.githubusercontent.com/2423362/82134242-852c9400-97fe-11ea-987f-a52dcc626956.png">

Expanded:
<img width="707" alt="Screen Shot 2020-05-17 at 5 22 56 am" src="https://user-images.githubusercontent.com/2423362/82134245-8e1d6580-97fe-11ea-849c-1fae0cc943f5.png">

**Comment by docwilmot** [comment]
The intention seems to always have been to fix this eventually. Seems that "eventually" has finally arrived, since @bugfolder has found that this missing functionality affects some progress.

I propose adding a "More information" link to the `Formatting options` fieldset, and calling `callback_filter_tips()` with the `$long` parameter. Then change all the exisiting callbacks to add an `else` clause, so that what returned with `$long` is different from without. 

This shouldn't really be a problem since no one has been using `$long` anyway, because, we took it out.
