### ISSUE TITLE
 Add a custom text block

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#1099]
See https://github.com/backdrop/backdrop-issues/issues/345

>  Add a custom text block (with token support) for non-reusable blocks (reusable blocks already are provided by Block module, but cannot be exported with the Layout config, as they are entities).

Currently you can create a "custom block" in the block UI which matches the old Drupal block system. This block can then be placed in a layout (and reused multiple times) using the Layout UI. But this has a few disadvantages

- it is outside of the Layout UI, so complicates the UX
- these blocks are not exportable in config
- no token integration

If we had a "Custom Text" block in the Layouts block list, this would essentially duplicate the "Custom block" functionality. They are also not reusable; after you click "Add block" you write the custom text and place it once. To have another block with the same text, you'd need to make another one. It is unlikely that you'd need the same text in two custom blocks though.

So question is, how to reconcile this. If we create a "Custom text" block, do we keep the old "Custom block" too? If not, how to migrate users?

**Comment by docwilmot** [comment]
See https://github.com/backdrop-contrib/custom_text_block

**Comment by quicksketch** [comment]
Really great PR makes progress on this at https://github.com/backdrop/backdrop/pull/1092. Nice @docwilmot! I left feedback inline on the commit.

**Comment by quicksketch** [comment]
Woo! Looking great. More feedback left on the PR: https://github.com/backdrop/backdrop/issues/1096.

**Comment by klonos** [comment]
Might be a silly question, still... with #1100 implemented, can't we simply create a block that contains the body field of a content type? If so, then why do we need this here?

...or is this part the explanation?:

>  - it is outside of the Layout UI, so complicates the UX
>  - these blocks are not exportable in config
>  - no token integration

**Comment by quicksketch** [comment]
>  can't we simply create a block that contains the body field of a content type? If so, then why do we need this here?

Yeah, but that would only work on `node/%` paths, because those are the only paths at which you'd have a node to work with (from which you could pull it's body field). You can already get something similar by just making a custom block and using that at well.

> ...or is this part the explanation?:

Yes, that's all the explanation. I'd also add that you can't add a new custom block or node from the Layouts UI, so you'd have to create one first before you could reference it.

**Comment by klonos** [comment]
Thanx for taking the time to explain Nate.

**Comment by mikemccaffrey** [comment]
I'm kinda on the fence about this solution of creating a new type of place-once custom blocks, since it actually seems beneficial to be able to reuse text blocks on multiple layouts. If I add a text block with a copyright message in the footer or something, I don't want to have to change it in each and every layout. Would it really be that hard to modify the implementation of the current custom blocks to make them exportable, tokenized, and easier to create from the layout ui?

No matter what path we pursue, we really need to improve our terminology since "custom blocks" and "custom text blocks" sound like the exact same thing. Perhaps if we follow through on #1276 and move the current custom blocks to the content menu, we can start referring to those as "content blocks".

**Comment by docwilmot** [comment]
Or, have only the custom text blocks, (the ones built in layout UI), and add a clone feature or a "Copy text from...." feature.

**Comment by sutibun** [comment]
> If I add a text block with a copyright message in the footer or something, I don't want to have to change it in each and every layout. Would it really be that hard to modify the implementation of the current custom blocks to make them exportable, tokenized, and easier to create from the layout ui?

This is a problem with me too. Makes working with Layouts bothersome... something like Server side includes https://en.wikipedia.org/wiki/Server_Side_Includes (but friendlier. can't think of something better)

That way when create a new layout, don't have to configure header and footer again and again.

**Comment by mikemccaffrey** [comment]
The more that I am working with blocks in Backdrop, the more I'd like us to just change the existing block implementation to store its data in config files instead of the database, like other structural objects like views and layouts. And then the blocks could be created and used in one or more layouts and they can be deployed to production together, without the current back and forth of creating blocks on production and then syncing the content to dev before you can add them to a layout.

How strongly do other folks feel about how we implement blocks? Does anyone want to get on a call or chat to discuss all the competing issues/proposals? I think that @jenlampton's layout UI is one of the most attractive features of Backdrop over Drupal 7, and that we really need to get this workflow right if we are going to recruit more sitebuilders from the drupal community.

**Comment by docwilmot** [comment]
To get this straight for myself:

1. Block = created by hook_block_info() in code; no "data" as such.
2. Custom Block = reusable block created in Block UI; remnant of the old custom block functionality; saves data in `block_custom` table.
3. Custom Text Block = non-reusable block created in Layout UI; PR not yet merged; would save data in config.

I assume you're proposing that number 2 be made to also save data in config, and that we move the creation of number 2 blocks also into Layout UI, essentially re-creating a reusable version of number 3.

I like this idea, I think it is an opportunity, since #3 is not yet merged, to combine the two functionalities into one 'Custom Block' plugin. I thnk the easiest would be simply mimic #2 by having a 'reuse/clone' switch on a number 3.

But the issue of API changes comes up. Is there any way to enable this without breaking APIs?

A chat would be reasonable.

**Comment by quicksketch** [comment]
> I assume you're proposing that number 2 be made to also save data in config, and that we move the creation of number 2 blocks also into Layout UI, essentially re-creating a reusable version of number 3.

The long-term plan had been to make custom blocks into entities, and thus fieldable. By design, entities are content and not configuration. If we nixed the idea of custom blocks (or merged them with custom text blocks), then we'd be committing to not making these fieldable entities.

**Comment by mikemccaffrey** [comment]
> @quicksketch: The long-term plan had been to make custom blocks into entities, and thus fieldable.

As I recently asked in #100, what would the use cases be for fieldable blocks? The only one I've been able to come up with is to add an image field for the inclusions of graphics in the block, but fieldable entities are not the only way to solve that particular problem. Do people have any other examples of how fields would be used on blocks?

> @docwilmot: I assume you're proposing that number 2 be made to also save data in config, and that we move the creation of number 2 blocks also into Layout UI, essentially re-creating a reusable version of number 3.

Exactly, thanks for summarizing the different approaches.

> @docwilmot: I thnk the easiest would be simply mimic #2 by having a 'reuse/clone' switch on a number 3.

I'm not sure I understand this proposal. Would you have to go into one layout in order to clone a custom text block into another layout?

Again, I think it would be easier for each block to have its own config file, so it can be added to one or more layouts. That could result in too many custom blocks appearing in the add dialog, so maybe we can have a checkbox asking if the block should be listed for reuse, or whether it is likely only going to be used in the layout to which it was initially added, kinda like panels has been handling things.

**Comment by jenlampton** [comment]
> As I recently asked in #100, what would the use cases be for fieldable blocks?

@mikemccaffrey I explained this a while ago in one of our weekly meeting calls, but I wanted to post it here too for anyone who wasn't in that call.  Here are two good use-cases for content that doesn't have it's own page:

1) An ad. I want to put ads in the sidebar of my site. These ads have text, images, and a URL to link to. These are all things I can do with fields (but not blocks as they are today).

2) An item for a home-page rotator (I call these slides). This has an image, text, sometimes a link to another page on my site, but should not have it's own page. I can add this content via fields, and then show these items in a slideshow view! Blocks today can not be displayed in a view easily.

> Is there any way to enable this without breaking APIs?

@docwilmot The easiest way to proceed without breaking APIs is to add this new feature of a 'Text block' as we are working on here, and then extend that as needed.  Let's assume the current `Custom block` will become a fieldable entity in Backdrop 2.x, and keep this nice simple text block stored in config.

**Comment by mikemccaffrey** [comment]
> @jenlampton: I like the idea of having a checkbox for "make this Text reusable" that would then cause that text to be saved in it's own config file. If the box is not checked, the config should be saved in the layout.

Agreed. It will be good to have single-layout custom block functionality, where the settings are saved in the layout config file rather than each independently. And once that is implemented (still working on it @docwilmot?), we can figure out some way to convert them into reusable custom blocks if the user later decides that they want to use them in more than one place.

In the meantime, #1428 is coming along well, and should be ready for the next release, with the custom blocks that are currently stored in the db exported to config files.

**Comment by jenlampton** [comment]
As I said in that issue, that's a task for contrib. In core, content is always stored in the database :)

**Comment by jenlampton** [comment]
The PR for this is looking really good. The only feedback I have is on the name. I think "Custom block" and "Custom text block" are too similar and will be confusing for users. What's wrong with calling this a "Text block"? or just "Text" ?

**Comment by jenlampton** [comment]
Also, we should make the labels on the form match blocks:
```
Admin label
Display title
Block content 
```

**Comment by mikemccaffrey** [comment]
> Add a custom text block (with token support) for non-reusable blocks (reusable blocks already are provided by Block module, but cannot be exported with the Layout config).

Okay, the reusable blocks are now going to be exported out into config as part of #1428. So we can start thinking about what it would take to convert a single-use block stored in a layout to a reusable block stored by the block module (and vice versa?).

However, it seems like there is one big difference between existing block implementation and the proposed layout block features, and that is tokens. The content field of the block module uses filtered text and the wysiwyg, which I don't think would play well with tokens, right? Should we try to get it to do so? Should we perhaps think about adding a Token filter that is available to apply to text formats?

**Comment by docwilmot** [comment]
Sorry haven't dealt with finishing this yet. Thought today would be the day, but worked on the Bartik color change this am and it ended up wasting too much time. Anyway, thats another issue...

The PR for this did include token support but youre right, it doesnt work well with the token browser.  (just checked, thought I'd raised an issue for this but can't find it). I think the ideal should be to get it to do so, rather than remove token support. The idea of tokens/shortcodes is quite a hit in the WP world, and I think we should be building on this. 

I had an idea to make the Drupal Shortcode module work with the token browser early last year, but haven't had the time to chase it. Again another issue...

I think the ideal should be that tokens work with the standard out-of-the-box filtered html format rather than requiring selecting a new format.

**Comment by quicksketch** [comment]
https://github.com/backdrop/backdrop-issues/issues/1428 has been merged, making blocks into configuration. That doesn't necessarily affect this issue, we could integrate the new config-blocks later, but IMO it would be preferable to handle it all together.

**Comment by docwilmot** [comment]
actually, @mikemccaffrey would be grateful if you could take this up from me, as with the token support and integration with the new custom blocks, I believe that it is above my skill set now.

**Comment by mikemccaffrey** [comment]
Hey, @docwilmot, I'd be happy to help out. However, let's keep in mind that not everything needs to be done at the same time. Let's just finish up the initial task of adding these custom blocks to layouts, and then we can handle the advanced features like token support and custom block conversion in separate tickets.

Unfortunately, I have not had the chance yet to dig into the code you posted above, and probably won't have time before next week's release, but I should be able to work on it with you sometime soon afterwards.

**Comment by quicksketch** [comment]
Thanks @docwilmot for adding that tag. I'll take a look tonight.

**Comment by quicksketch** [comment]
This looks great @docwilmot! Added some feedback to the PR https://github.com/backdrop/backdrop/pull/1096/files

I'm going to work on the reusable bit and see if I can get that working.

**Comment by quicksketch** [comment]
I filed a PR to your branch @docwilmot that you can merge to get all the changes and get up-to-date with 1.x at https://github.com/docwilmot/backdrop/pull/3.

**Comment by quicksketch** [comment]
I've got a working proof of concept to allow switching between the one-off custom text blocks and the reusable block-module blocks. I'll file a new issue/PR once we get this one handled, which I'm hoping for later today.

**Comment by jenlampton** [comment]
Just a note that it looks like block titles in this new PR are double escaped without https://github.com/backdrop/backdrop/pull/1123

**Comment by jenlampton** [comment]
I just did a thorough review of this PR.  Fantastic work @docwilmot @quicksketch @mikemccaffrey and all involved!  I had a few minor UI improvement ideas, but I'm going to mark this RTBC and we can add those over in https://github.com/backdrop/backdrop-issues/issues/1515. High fives all around :)

**Comment by quicksketch** [comment]
Super! Merged in https://github.com/backdrop/backdrop/pull/1198 into 1.x for 1.3.0.

Thanks @docwilmot for pioneering this great new feature! We'll continue over in #1515 to work on making these blocks interchangeable with the reusable custom blocks.
