### ISSUE TITLE
Add blocks for adding individual fields from entities

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#1100]
Sub-issue from https://github.com/backdrop/backdrop-issues/issues/345 [meta] Layout Followup Issues

Note that this feature would replicate the functionality of Display Suite in Drupal: the ability to have fields from a node (or an entity) placed anywhere in a layout. Candidates for porting:

[Node Fields Block](https://www.drupal.org/project/node_fields_block) presents checkboxes on the "Add node fields block" form to choose a node type then reveals the fields on that node type with checkboxes to choose which fields to create a block. 
Advantage: 
- It seems the simplest. 
- theming options seem more complete

Disdvantage: 
- Only node type fields, doesnt seem to do other entities
- cant seem to be able to mange display setting separately

[CCK Blocks](https://drupal.org/project/cck_blocks) is the most complex: it provides checkboxes on eac field's settings page to enable as block. Then you need to configure the blocks display in a new view mode called CCK Blocks; then the block has to be enabled and added to the page from the blocks list.
Advantage: 
- Separate view mode so each block can be configured to display differently from the node display.

Disavantage: 
- More complex; 
- also only nodes, no other entities.
- actually recommends Field as Block instead!

[Field as Block](https://www.drupal.org/project/fieldblock) provides checkboxes on the "Manage display" form next to each field to make that field available as a block. Blocks then need to be added to the page separately.
Advantage: 
- two steps compared to CCK Blocks three
- works with all entities 

Disadvantage: 
- more complex than Node field blocks

Any thoughts on the best way forward welcomed!

**Comment by docwilmot** [comment]
Any thoughts?

**Comment by klonos** [comment]
Sorry for being silent. I want to chime in on this, but absolutely no time. This coming weekend perhaps.

**Comment by docwilmot** [comment]
No worries. Working on #767 first.

**Comment by quicksketch** [comment]
I think this would be a great idea. However, it's not mentioned the (perhaps) most used module that provides one block per field: Panels. Only in Panels they were "content types", a name that clearly had a conflict.

I have a particular concern about using blocks the way things are currently, because we'd need to literally create one entry in `hook_block_info()` per field, which could have performance issues. We could if we wanted do a single block that provided *all* fields and you would just select the block you wanted, but I think that would be inconsistent with other interfaces like Views that just list all the fields all the time.

So what I'd most like to see is a way for us to expand a single entry in `hook_block_info()` into "children" blocks, which is the way Panels did it with it's content types.

**Comment by docwilmot** [comment]
`content types` is a CTools plugin. Ctools is a bit of a pain to figure out for me. If anyone else has the motivation, please run on ahead

**Comment by docwilmot** [comment]
Reconsidering. Panels has the advantage of subsections to the 'add content' interface. We just have one long list of blocks. If we do have one listing for each field, couldnt that get unwieldy? Perhaps we need to start considering organizing the 'Add block' dialog as well? Or alternatively, the 'a single block that provided all fields' option may be better UI-wise.

**Comment by quicksketch** [comment]
> Perhaps we need to start considering organizing the 'Add block' dialog as well?

Yeah, if we add every field as a block, we'd definitely need at least the filtering textfield in that dialog. I'm not a big fan of the organization of Panels' blocks into separate categories, as it's often not obvious where certain blocks live and it can take 2-3 tries to find the right tab. OTOH, it certainly helps hiding blocks you're not interested in. I think just a search would solve the problem though, I'm never intimidated by the list of fields in Views because I never scroll through it, I just search and select.

**Comment by docwilmot** [comment]
> I think just a search would solve the problem though

Agreed. https://github.com/backdrop/backdrop/pull/1019

**Comment by docwilmot** [comment]
On further inspection, CTools 'content types' aren't the same as fields, they're more a way to render multiple types of content as blocks (panes), including forms, labels, tokens, blocks, messages, and all kinds of random stuff. The one 'content type' which sounds like what I was thinking is the 'entity context' content type, which renders entity fields.

Do we want all of CTools' content type functionality available as Backdrop blocks? Or just fields? I'd imagine someone could probably maintain all the other stuff as contrib if we decided to just do 'fields' alone in core.

What do you think?

**Comment by quicksketch** [comment]
Let's start with Fields and add as we run across more concepts that should be moved into core. The only other one that I'd really like to see in the near future is a plain custom-text block: https://github.com/backdrop/backdrop-issues/issues/1099

**Comment by docwilmot** [comment]
@quicksketch see https://github.com/backdrop-contrib/entity_blocks, borrowing Ctools code mostly. A starting poiint maybe?

**Comment by docwilmot** [comment]
I'd like to make this a PR against core, but not sure where it should go. Field module perhaps? Thoughts please?

Same for https://github.com/backdrop/backdrop-issues/issues/1099

**Comment by quicksketch** [comment]
Hey @docwilmot, so my thoughts on this are as follows:

- Add `hook_block_info()` to field.module to define the new blocks.
- Instead of using the `BlockLegacy` class (the default) which uses `hook_block_view()`, `hook_block_configure()`, etc. We should make a `FieldBlock` class that extends `Block`.
- Then we give the Block class a new power: sub-blocks (or children) by adding a method `getChildren()`.
- Then when displaying a list of blocks, we call $block->getChildren() to display a list of sub-blocks. Layouts would store the same `block:delta` combination as before, but also store they name of the child block (e.g. the field name).
- Field module's `FieldBlock` class would then implement the `getChildren()` method, and make one child block per available field.

The reason for this "children" concept is to prevent the `hook_block_info()` registry from becoming completely overrun with identical blocks whose only difference is the name of the field. Adding hundreds (or thousands) of items to a registry causes the entire site to slow down, so it's always a good idea to minimize the size of a registry. After this is implemented, we could extend it to other module's that make duplicate blocks, like menu.module or webform.module.

**Comment by quicksketch** [comment]
This is the same approach used by Panels, although they use a callback function labelled "content type" (the Panels word for a block).

The example of how they build out one block per field is in: http://cgit.drupalcode.org/ctools/tree/plugins/content_types/entity_context/entity_field.inc

Our Blocks are object rather than CTools plugins, so CTools uses `$plugin['content type']` to point at the `ctools_entity_field_content_type_content_types()` callback, we would use the new `getChildren()` method. After the architectural difference, the contents of these two functions would likely be almost the same, as the Field API hasn't changed that much in Backdrop.

**Comment by quicksketch** [comment]
I took at a look at your https://github.com/backdrop-contrib/entity_blocks module. It looks like it would provide all the functionality we need, but it just needs to be supported by a more robust core system for managing sub-blocks (so we don't swamp hook_block_info() like I mentioned earlier).

**Comment by docwilmot** [comment]
@quicksketch, I'm not really getting how in the "Add Block" dialog this would result in a listing for each field then if there is only one `hook_block_info` entry? Are you suggesting a single entry there, but choose the desired field in the configure dialog?

And if that is the case we could achieve the same thing without a new Block class couldnt we? (Not that I have an issue with a Block class, but just curious)

**Comment by quicksketch** [comment]
We would need to modify the add block dialog to include the children.

Here's the existing code, with the addition of the getChildren() callback:

```php
  $blocks = layout_get_block_info();

  // Assemble all blocks into a single list and sort.
  $block_list = array();
  foreach ($blocks as $module => $module_blocks) {
    foreach ($module_blocks as $delta => $block_info) {
      // Skip blocks that don't have context requirements met.
      $required_contexts = isset($block_info['required contexts']) ? $block_info['required contexts'] : array();
      if ($layout->hasContexts($required_contexts)) {
        // NEW CODE:
        $children = $block_info['class']->getChildren();
        foreach ($children as $child_id => $child_info) {
           $block_list[$module . ':' . $delta . ':' . $child_id] = $child_info;
        }
      }
    }
  }
```

**Comment by docwilmot** [comment]
This is brilliant! Youve done this before havent you!

I have an issue with contexts though. The 'required contexts' key wont work with `hook_block_info` as that will vary based on the field, so I'm passing the `required_context` in the child-block-building function and checking for contexts thus:

```
  foreach ($blocks as $module => $module_blocks) {
    foreach ($module_blocks as $delta => $block_info) {
      $parent_block = layout_create_handler('block', $module . ':' . $delta);
      $children = $parent_block->getChildren();
      foreach ($children as $child_id => $child_info) {
        // Skip blocks that don't have context requirements met.
        $required_contexts = isset($block_info['required contexts']) ? $block_info['required contexts'] : array();
        if ($layout->hasContexts($required_contexts) || $layout->hasContexts($child_info['required_contexts'])) {
          $block_list[$module . ':' . $delta . ':' . $child_id] = $child_info;
        }
      }
    }
  }
```

I've added this to block_legacy.class:
```
  function getChildren() {
    $block_info = layout_get_block_info($this->module, $this->delta);
    return array($this->delta => $block_info);
  }
```

Can this work? Better ideas welcome.

**Comment by quicksketch** [comment]
> The 'required contexts' key wont work with hook_block_info as that will vary based on the field,

Ooo, good point. My first thought would be that we might make one hook_block_info() entry per set of required contexts, but I think you're on a better track making required contexts match *either* the parent item (if specified) *or* individual children (if specified) instead. Very nice!

> I've added this to block_legacy.class:

Hmm, this looks good but I don't like that we'd end up calling `hook_block_info()` twice. Once for the list of parents and then again for the list of children (which is already only going to be a single item). I think we'd be better off if we made another condition when we build the list of blocks. If `getChildren()` is empty, then just append the parent block exactly as-is. This may make it so that some blocks would be keyed by `module:delta:child` while traditional blocks would be keyed by just `module:delta`. The logic may not be as clean, but it would be more efficient than calling `hook_block_info()` twice for each traditional block.

**Comment by quicksketch** [comment]
Also, wow, awesome! Yay! :+1: So happy to see this moving forward.

**Comment by klonos** [comment]
So, to get this right by providing a use-case... this will allow someone for example to have a block with say the author photo/bio next to the node. Right??

**Comment by docwilmot** [comment]
> this new feature will allow someone for example to have a block with say the author photo/bio next to the node (as a block). Right??

If the photo and bio are fields, then yes! Cool, no? I've always been excited about this, its like built in display suite.

Between this and my contrib [Blockify port](https://github.com/backdrop-contrib/blockify) you can arrange site elements all kinds of ways.

**Comment by docwilmot** [comment]
> I don't like that we'd end up calling hook_block_info() twice

True that. Pushed new version. Doing instead:
```
 if (!empty($parent_block->getChildren())) {
   $children = $parent_block->getChildren();
   foreach ($children as $child_id => $child_info) {
     // Skip blocks that don't have context requirements met.
     $required_contexts = isset($child_info['required contexts']) ? $child_info['required contexts'] : array();
     if ($layout->hasContexts($required_contexts)) {
       $block_list[$module . ':' . $delta . ':' . $child_id] = $child_info;
     }
   }
 }
 else {
   $required_contexts = isset($block_info['required contexts']) ? $block_info['required contexts'] : array();
   // Skip blocks that don't have context requirements met.
   if ($layout->hasContexts($required_contexts)) {
     $block_list[$module . ':' . $delta] = $block_info;
   }
 }
```

Travis doesn't like it but I think I know why.

**Comment by PaulHoza** [comment]
Hmm.. this thread is really exciting to me. I'm off traveling so I'm unable
to get at more info right now, so sorry if this is out of place here, but:

One big module that I've used (aside from Display Suite) is the Entity
Reference (https://www.drupal.org/project/entityreference) stuff from D7.
I really like using that to pull in particular fields and renders to place
into various places on other related nodes. IE: pull the photo, name and
job title from a "resume" content type to display in the sidebar of an
article written by that person (flagged with taxonomy or such to denote the
relationship.)

Do you think this work will be along the lines of using Entity Reference,
too?  I'm sorry that I'm plopping this in here, but I've been meaning to
ask suggestions about this stuff and didn't know where to put it.

I need to start work on a new site this week and the lack of Entity Ref and
maybe DS has made me unsure about starting it in Backdrop, but I'd sure
love to.  I am not wholly sure if I can do the same things as the above
modules with Views (filters and such), since it's been a while since I did
more advanced/complex things with Views since those other modules came out.

Sorry for hijacking-ish this thread, but maybe it will also ping your
brains in case you think some sort of Entity Display Reference Suite Block
Field Frankenstein module starts to form up.  :)

Thanks.

**Comment by quicksketch** [comment]
> Do you think this work will be along the lines of using Entity Reference, too? I'm sorry that I'm plopping this in here, but I've been meaning to ask suggestions about this stuff and didn't know where to put it.

Entity Reference would be a separate concept. Backdrop is capable of handing multiple contexts of the same type, but at present it can only pull contexts directly from the URL. So if you had a path of `node/%`, only one node context is available (based on the NID from the URL). What we would need for references (after the module itself exists of course) is for Layouts to have a UI for adding "relationship", just like Views or Panels. So you'd be able to add a relationship to a second node that has been referenced by the first one.

This issue still moves us forward on that goal though. Once relationships are supported, you'd be able to chain as far down as you like to pull out fields from any related piece of content.

**Comment by klonos** [comment]
Yes, my question with regards to a use-case example above:

> So, to get this right by providing a use-case... this new feature will allow someone for example to have a block with say the author photo/bio next to the node (as a block). Right??

Was sort of asking the same question as @PaulHoza (using fewer words and not mentioning but rather implying the use of entity relationships), but @docwilmot's reply:

> If the photo and bio are fields, then yes!...

Gave me the answer I needed (again same as @quicksketch's reply, but with fewer words).

So point is that the feature we are looking to implement here would allow placing "parts" of content on a block (or various blocks) but so on as these parts are already fields of that same entity - no relationship to other entities supported. But Nate is right... it brings us closed to that dream.

**Comment by quicksketch** [comment]
Hi guys, just checking in here. This PR is looking really great. I'm hoping to get a chance to look at it next week after BADCamp.

**Comment by quicksketch** [comment]
I filed a PR against @docwilmot's branch over in https://github.com/docwilmot/backdrop/pull/2.

I was having a hard time distinguishing between "Title type" and "Display label as", so I tried to adjust the options to explain what each one is. Now they are "Block title type" and "Field label display", with some description text. I hope that's better.

Panels also has the ability to display the block title as the field label. That sounded like a good option to preserve and so I made the "Default" block title type use the field label. Rather than previously the "Default" title type didn't do anything, so it was redundant with "None".

Other than the small UI qualms, the functionality worked great! I love love love being able to just place an individual field. Great job.

I found out that @docwilmot probably ran into a significant issue with our context system. It was commented out a section in `hook_block_info()` the "required contexts", and then in the block view callback we had this code:

```
   $block_list = field_get_block_list();
   $context = $block_list[$this->child_id]['required contexts'][$entity_type];
   $entity = menu_get_object($context);

   // Do not render if the entity is not available.
   if (empty($entity)) {
     return;
   }
```

Ack! Pulling from a global (and not entirely reliable) `menu_get_object()` to load the node (or other entity)! Block contexts are supposed to prevent this exact situation.

The reason for doing this was relatively clear though: Our context system couldn't handle the idea of multiple contexts (e.g. "user" and "node") being sub-classes of a parent ("entity"). So while it was possible to have a required context of `node` or `user`, having a required context of `entity` that would work on either did not work. To fix this, my PR adds "aliases" to contexts, so that these kinds of more flexible contexts are possible. Although it sounds complicated, to use them it is as simple as:

```
function field_block_info() {
  $blocks['field_block'] = array(
    'info' => t('Field block'),
    'description' => 'Displays a field from a referenced entity.',
    'class' => 'FieldBlock',
    'required contexts' => array('entity' => 'entity'),
  );

  return $blocks;
}
```

Where `'required contexts' => array('entity' => 'entity'),` is our new addition. And instead of using `menu_get_object()`, our entity (whether a node, user, or other entity) is now accessible at `$entity = $this->contexts['entity']->data;`.

Please take a look at the PR and see if it makes sense. If it looks good, we still need to add in tests to cover this new functionality.

**Comment by klonos** [comment]
> Panels also has the ability to display the block title as the field label. That sounded like a good option to preserve and so I made the "Default" block title type use the field label. Rather than previously the "Default" title type didn't do anything, so it was redundant with "None".

:+1: sounds just fine.

**Comment by klonos** [comment]
...let's see if I can make some time and test so I can give some feedback.

**Comment by quicksketch** [comment]
![selection_019](https://cloud.githubusercontent.com/assets/100206/10769471/7dde6a64-7ca3-11e5-8c88-ca9e29cc921e.png)

![selection_020](https://cloud.githubusercontent.com/assets/100206/10769472/8337486e-7ca3-11e5-95ad-6ccf740a3e0e.png)

**Comment by quicksketch** [comment]
I'm working on finishing this up and should have something to review in the next few days.

**Comment by quicksketch** [comment]
New PR filed at https://github.com/backdrop/backdrop/issues/1178.

- Added tests for adding a field block, checking its formatter settings, and label display.
- We didn't yet have support for formatter settings. Now we do. :smile:
- Fixed the field label display in the dialog.
- Add a custom summary for field blocks that includes the formatter summary.

**Comment by quicksketch** [comment]
Huge gif with a preview of everything:

![2016-01-07 23 25 12 844](https://cloud.githubusercontent.com/assets/100206/12192750/4e2c0624-b596-11e5-8c35-dd5a1fa13d6b.gif)

**Comment by quicksketch** [comment]
I've merged in https://github.com/backdrop/backdrop/pull/1178 for 1.3.0.

Thanks @docwilmot for building out this implementation! This is a great powerful new feature for site builders!

**Comment by docwilmot** [comment]
This is so AWESOME!! Yay!! Very happy!

Don't forget the sister project [Custom Text Blocks](https://github.com/backdrop/backdrop/pull/1096) (now called just plain Text Block as per @jenlampton's suggestion, which I agree is best). Now has tests.

**Comment by jenlampton** [comment]
> This is so AWESOME!! Yay!! Very happy!
 :) :) :)

**Comment by klonos** [comment]
Is this in? I don't see any option to add fields as blocks in 1.3.3.

**Comment by gifad** [comment]
from link in [comment above](https://github.com/backdrop/backdrop-issues/issues/1100#issuecomment-141719628) : 
> Add a Block in Layout Builder. Blocks will only be available in Layouts with a matching context. For example "node" fields are only available on layouts with a "node/%" path.

**Comment by klonos** [comment]
Thanx @gifad. I keep forgetting about this detail.
