### ISSUE TITLE
Only process project (module/theme/layout) if the type in its .info file matches the folder it's placed in.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1132]
So I wanted to test a few PRs that have been made lately against the layout UI. Wanted to install Radix in order to get more layouts than the few we ship with core (especially in order to test wrapping in #988). So I googled "backdrop radix" and downloaded what I thought was [Radix the layout](https://github.com/backdrop-contrib/radix_layouts) when in reality I had just downloaded [Radix the theme](https://github.com/backdrop-contrib/radix).

...here's what I saw in the layout UI:

![backdrop-contrib_layouts-radix-no_screenshot-name_issue](https://cloud.githubusercontent.com/assets/2423362/9562405/095a937e-4eaf-11e5-8d98-fa8f3fb77bb0.png)

I was about to file an issue in the respective contrib project queue, when I realized what was wrong with the whole thing. So, can we please have it so that if say like in this case, a theme is accidentally placed under `/layouts`, then we do not parse the thing beyond the .info if we detect that `type = theme` or `type = module`?

...of course we should have similar checks in place so that modules or layouts accidentally placed under `/themes` are not parsed and so that layouts and themes placed under `/modules` are neither.

**Comment by BWPanda** [comment]
Hmmm, interesting! While I don't see this as being a very widespread problem (especially with Backdrop being able to download projects itself now), if/when it does happen it can be quite humorous. For example, here's my sandbox site with Devel as the default 'theme' :laughing: 

![image](https://user-images.githubusercontent.com/2385329/94989959-e68dad80-05bb-11eb-8605-218d27b95692.png)

And I got absolutely no errors or warnings when I enabled it, set it as the default theme, or even when I refreshed the frontpage to see what the Devel 'theme' looks like (for the record, it's very boring).

**Comment by BWPanda** [comment]
Here's a PR that fixes this: https://github.com/backdrop/backdrop/pull/3347

I only did this for Themes and Layouts, since they look for `.info` files in their respective directories. Modules look for `.module` files (which themes and layouts don't have), so there doesn't seem to be a chance for a layout or theme placed in the `/modules` directory to be displayed on the site as a module.

Now, when checking the `type` of a project to make sure it's not a layout sitting in the themes directory for example, there's a chance the `type` key doesn't exist (since it's technically not required*). In this case, do we:

- Allow the project to be displayed, hoping it's in the correct directory and just doesn't have a `type` defined, or
- Remove the project, effectively making the `type` key required from now on?

In the PR I opted for the first option, since the second would basically be an API change.

\* Here's how the `type` key is described for themes (it's essentially the same for layouts and modules too):
> **type (Required)**
> The type of project. For a theme, this will always be "theme". Other available types are "module" or "layout". Although this property is not required to enable the theme, it is required to properly package the theme on BackdropCMS.org and thus should always be included.

So it is required, but it isn't...?

**Comment by bugfolder** [comment]
I tested this by putting a module and a theme in the `layouts` folder and a module and a layout in the `themes` folder, then visited the paths `admin/appearance` (for themes) and `admin/structure/layouts/settings` (for layout templates). Both pages showed broken versions of the bogus folders.

Then applied the patch from this PR. Both pages were now correct (ignored the bogus folders). So WFM.

Code reviewed. LGTM.

**Comment by bugfolder** [comment]
I note that the spelling errors in spell-check are for lines unrelated to this PR.

**Comment by quicksketch** [comment]
Thanks @bugfolder for reviving and reviewing this issue! The PR @BWPanda filed looks good to me too. A pretty simple fix to prevent the themes and layout templates from listing incorrect projects. I've merged https://github.com/backdrop/backdrop/pull/3347 into 1.x and 1.26.x. Thanks @BWPanda, @klonos, and @bugfolder!
