### ISSUE TITLE
Add info about the layout to hook_block save()

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#1134]
related, or probably rendered unnecessary by https://github.com/backdrop/backdrop-issues/issues/767

In block_legacy.class.inc `formSubmit()` we could change for example to: `$function($this->delta, $form_state['values']['block_settings'], $form_state['block'], $form_state['layout']['name']);`

This would result in: `hook_block_save($delta, $settings, $block, $layout_name)`

**Comment by quicksketch** [comment]
If it's possible for #767 to replace this request, I think that would be preferable. A block really should be entirely independent of the layout in which it is placed. If there is configuration that differs based on the layout used, that should likely just be a configuration option within the block instead of the block making its own modifications based on the layout used.

**Comment by docwilmot** [comment]
Not needed with #767 in. Closing.
