### ISSUE TITLE
[DX] Provide a way to alter search results

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1143]
Here's my use case: weird things are being returned from my search results.  I can easily spot them, and I could remove them if only there were a way!

I had a thought to kill them on the theme layer, but when I looked at `template_preprocess_search_results` I can see that the list of results is generated by concatenating together a string RIGHT HERE.  This means that if I change the array of results in preprocess, it doesn't change my output, since that was assembled before I changed the array.

Suggested solutions:
Add a loop into the `search_results.tpl.php` file and print out the results there, so changes made in preprocess actually have a chance of affecting the output in this template.

**Comment by quicksketch** [comment]
> I can easily spot them, and I could remove them if only there were a way!

I don't think this use-case is correct. If you just removed individual search results from a page of results, some result pages would have fewer than others. e.g. normally 10 results per page, but some pages may only have 8 if you alter-out two of them. In this particular case, the solution should be to prevent those items from being indexed if you don't want them in your search results in the first place.

Restructuring the search results so that they could be altered for other reasons may still make sense, but we'd have to manage it from an API-compatibility perspective.

**Comment by BWPanda** [comment]
Based on the age of this issue (and lack of updates), I'm going to close this until we can get an actual use-case for needing to alter search results. If someone has one, please reopen.
