### ISSUE TITLE
Cant get machine_name field to work in layout modal

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#1146]
Can anyone replicate this? 

I have a machine name field in a block config modal with a 'machine_name' field. It never works; I just get two textfields.

**Comment by quicksketch** [comment]
I think this is probably because the block forms are all nested under a sub-key called "settings". See [`block_admin_configure()`](https://api.backdropcms.org/api/backdrop/core!modules!block!block.admin.inc/function/block_admin_configure/1). In particular:

```
  // Module-specific block configuration.
  if ($settings = module_invoke('block', 'block_configure', $delta)) {
    foreach ($settings as $k => $v) {
      $form['settings'][$k] = $v;
    }
  }
```

So I think to get your machine name element working, you may need to add "settings" to the list of parents. e.g. if "title" were your parent element.

```
  $form['name'] = array(
    '#type' => 'machine_name',
    '#title' => t('Machine name'),
    '#machine_name' => array(
      'source' => array('settings', 'title'),
    ),
  );
```

**Comment by docwilmot** [comment]
` 'source' => array('block_settings', 'title'),` actually. Thanks as usual.

**Comment by quicksketch** [comment]
Nice one. :+1:
