### ISSUE TITLE
[UX] the "edit view" contextual link always goes to master display

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1155]
In Drupal 7, if a user clicked the "edit view" contextual link from a specific display, it would take the user to edit that same display of the view.  

In Backdrop the "edit view" contextual link always goes to the master display.

This change in expected behavior led me to believe that things were broken in views (see https://github.com/backdrop/backdrop-issues/issues/1151).

**Comment by dboulet** [comment]
Looks like this feature was removed in the conversion to Layout module, in commit 6490d6b—maybe by accident? I’ll file a pull request which restores this functionality.

**Comment by quicksketch** [comment]
Thanks for digging up this issue @dboulet! I think you're right that this was accidentally removed. I think my intention had been to remove unnecessary data from transferring all the way up into the theme layer, so some things, like the removal of `$block->content` and the entire `$view` object was intentional. Fewer strings or referenced objects makes for easier debugging for themers and less memory footprint for everyone.

It looks like we can fix the contextual link problem by restoring `#views_contextual_links_info`, but we can just leave out the `$view` item. I think the change in `template_preprocess_block()` can be left as it was, with no `#element` property.

**Comment by quicksketch** [comment]
Manually merged to remove the `$view` variable from the contextual link array. Fixed in https://github.com/backdrop/backdrop/commit/77fab77f045ec90556d5821f19062c58ecae5ff9 in both the 1.x and 1.2.x branches. Thanks @dboulet!

**Comment by dboulet** [comment]
Thanks, @quicksketch! I think the change I had made to `template_preprocess_block()` is necessary to get the contextual links working properly for blocks which are provided by Views. Without the `#element` property, the links are not altered. Check out `contextual_preprocess()` for an example. Sorry, should have included more details in my PR.

**Comment by quicksketch** [comment]
Oh! Let me double check this then. Sorry for modifying it on the way in!

**Comment by quicksketch** [comment]
You're right, there's no edit link for blocks provided by Views. It also looks like `#element` is present for other contextual links, such as those provided on nodes. I'm not a big fan of shoving giant render arrays to the front-end, but looks like this may be a long-term problem to solve with contextual links.

I'll put back in that missing line for `#element` and then everything should be working again.

**Comment by quicksketch** [comment]
Restored missing line in https://github.com/backdrop/backdrop/commit/b89e5cbfafa979481cdc8304890d306ae5c506fb. Contextual links are now working for Views. Thanks again @dboulet!
