### ISSUE TITLE
[UX] Save and Delete button colors are backwards for Menu Links

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1156]
When creating or editing a menu link, the Delete button is "click me" Blue, and the Save button is "ignore me" White.  This needs to be changed.
![screen shot 2015-09-08 at 6 45 08 pm](https://cloud.githubusercontent.com/assets/397895/9750786/e9dc09a8-5659-11e5-8c0b-43cd217538a0.png)

**Comment by MrHaroldA** [comment]
I would live to see this fixed by adding a "#weight" attribute. This way you can add you own custom button, and place it in between the existing buttons without having to add weight to the other buttons.

What also would be cool, is that the Form API would assign incemental weights to elements that don't have that don't have weights. But this could yield in very misplaced items when implemented.

**Comment by quicksketch** [comment]
> I would live to see this fixed by adding a "#weight" attribute.

We haven't regularly added #weight to buttons in core, but I think this would be a good idea. For now this PR fixes the problem at hand in the way most of our other buttons are set up.

As an FYI, it's also possible to set the primary button just by setting the "button-primary" class. The fallback that we're using is that form_process_actions() will automatically assign this class on the first button if not present.

**Comment by MrHaroldA** [comment]
> the "button-primary" class

That would be handy for "ctrl-enter = submit form" actions.

And ... live = love ;)

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/pull/1036.

> That would be handy for "ctrl-enter = submit form" actions.

:smile: Yeah, it makes some good possibilities with programmatic detection of the primary button to submit a form. Though any solution would have to be JavaScript based, as browsers all default to the first button in the form submitting on the enter key.

**Comment by MrHaroldA** [comment]
> The fallback that we're using is that form_process_actions() will automatically assign this class on the first button if not present.

It now looks to me like the "button-primary" class would be nice to have everywhere. What if we'd remove the fallback and only highlight the button with the "button-primary" class? They should be easy to spot, but might take a while to find 'em all.

**Comment by quicksketch** [comment]
> It now looks to me like the "button-primary" class would be nice to have everywhere.

Could you elaborate what you mean by everywhere? We already use it on most forms, or anywhere we have a #type = 'actions' wrapper around the buttons (configuration forms, entity forms, menu items, views, layouts, etc.) I suppose it's not on some forms like the search form, login, or other compact forms that have only a single button.

**Comment by MrHaroldA** [comment]
> Could you elaborate what you mean by everywhere?

If we remove the fallback in form_process_actions(), devs would be forced to assign a "button-primary" to fix the styling of the button.

Or maybe change the fallback in form_process_actions() to only add the class automatically if there's only one button present?

**Comment by quicksketch** [comment]
> If we remove the fallback in form_process_actions(), devs would be forced to assign a "button-primary" to fix the styling of the button.

Yes, that's true. But why would we want to make devs do that manually when it can be done for them? When we added this class, it was certainly a lot easier to add it in one place and then have it affect all the forms at once. Although we did have a few mishaps like this issue, it's actually nice to find because it pointed out an inconsistency in our forms.

I think I'm missing the suggestion that's being made here. I thought you wanted this class to be added everywhere. But do you mean that you wanted it to *not* be automatically added and be manually specified?
