### ISSUE TITLE
/files is there a reason we don't ship w/ an empty /files dir in core? 

### ISSUE THREAD

**Issue by serundeputy** [backdrop/backdrop-issues#1157]
Can we ship with an empty files directory in core?

Save one step in installation?

**Comment by quicksketch** [comment]
This may be a good idea. We do this for settings.php, but we'd end up with the same problem we have with settings.php in that if you track something in version control (like the /files) directory, you can't gitignore it. This may result in people filing more PRs with their files directory committed. We already have this problem with settings.php, so it wouldn't be a new problem for us. You also can't have a truly empty directory in Git. We'd need to have a README.md or .htaccess file in there.

But overall I like the idea that the directory structure is all in-place when you download a tarball. So for end-users this seems like it would be a win, based on the same reasoning we ship with settings.php and not a default.settings.php that you have to copy.

**Comment by klonos** [comment]
> But overall I like the idea that the directory structure is all in-place when you download a tarball.

:+1:

**Comment by saintlynn** [comment]
I filed a pull request here: https://github.com/backdrop/backdrop/pull/1060

I added a README.md, let me know if you want it to say something different.  

I kept the .htaccess file in the files directory.  I think that is the correct thing to do, if not, let me know and I'll take it out.

**Comment by quicksketch** [comment]
> I kept the .htaccess file in the files directory. I think that is the correct thing to do, if not, let me know and I'll take it out.

That seems like it would be correct to me.

> I added a README.md, let me know if you want it to say something different. 

Looks pretty good. I'll shorten it down a bit.

Much to my surprise, when testing this the files directory doesn't show up as modified when there are files in it. Git must treat ignored *files* different than ignored *directories*. This is good news and makes it so that we can include versioned files within the /files directory while ignoring all the other files that are in there (such as config_* directories and all other uploaded files). Doing a `git stash` does *not* affect the files directory (good), the files directory does not show up in `git status` changes (good), and it doesn't need to be reset before doing a `git rebase 1.x`.

So much to my surprise, this seems to have *no* negative affect on developer experience. Combined with the better UX on new installations and clarity of the directory structure, I think this is a win all around.

**Comment by klonos** [comment]
Better DX, better UX during installation...

![its_gooood](https://cloud.githubusercontent.com/assets/2423362/9867138/a07fb8a0-5bad-11e5-869e-dda7c02ae244.gif)

**Comment by quicksketch** [comment]
Merged in manually in https://github.com/backdrop/backdrop/commit/dea1ac60b1bdc06fc319cdfc69ebf01c4d803145 while I was testing out the effects of rebasing/ignoring/stashing.

Great job! And welcome @saintlynn! First ever commit on GitHub. Done like a boss! :smile:

**Comment by saintlynn** [comment]
Thanks, @quicksketch! Great news! Will I get my name on here: https://github.com/backdrop/backdrop/graphs/contributors ?

**Comment by quicksketch** [comment]
> Great news! Will I get my name on here: https://github.com/backdrop/backdrop/graphs/contributors? 

Hm, yes you should, but it looks like Git may not be set up with your real email address on your computer.

I looked at the commit: https://github.com/backdrop/backdrop/commit/dea1ac60b1bdc06fc319cdfc69ebf01c4d803145

But it has this little notice next to your name:
![selection_007](https://cloud.githubusercontent.com/assets/100206/9983916/1e715a5a-5fca-11e5-8a3a-d53ace4cb6ec.png)

This probably means that your email address you have set up in Git does not match your profile on GitHub.com. So you need to add your email address either to your GitHub profile, or set up Git on your machine to use the email already on your GitHub profile. See https://help.github.com/articles/setting-your-email-in-git/
