### ISSUE TITLE
Images aren't responsive in bartik

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1166]
I noticed that in the Bartik theme Images don't have a max-width of 100%.  If the images are larger than the area they are placed in, they break the layout. 

Do we want to add the max-width to images in each theme, or inside some system level CSS file?

**Comment by quicksketch** [comment]
> Do we want to add the max-width to images in each theme, or inside some system level CSS file?

I think system.theme.css would be the most appropriate place for this.

It also looks like our `<figure>` and `<figcaption>` elements might not be responsive due to the use of `display: table;`, which doesn't respect max-width: http://stackoverflow.com/questions/4019604/chrome-safari-ignoring-max-width-in-table

**Comment by quicksketch** [comment]
Filed a PR at https://github.com/backdrop/backdrop/pull/1047 that fixes this for both `img` tags (easy) and `figure` tags (not so easy).

The trouble with our figure tags is that in order to center them, they have to be `inline-block` (so they scale at max-width 100%) and they *must* have a parent wrapper that has `text-align: center;` on it. Previously, we were using a hack, displaying the figure element as a table instead. This centered the element but wasn't responsive. It seems that the only way to center something correctly is to have a parent wrapper.

So if you center align an image (with or without a caption), then it will be wrapped in a `<div class="centered-wrapper">`. Left/right/no alignment doesn't need the wrapper. Does that seem reasonable?

**Comment by quicksketch** [comment]
I only merged this into 1.x as it dealt with captions and figures as well as images. If we're interested, we could backport this to 1.1.x as well, but with our release on Tuesday I can't see much reason to do the backport.
