### ISSUE TITLE
CKEditor (> <) - characters are displayed as HTML and does not have to be like in PHP

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#1176]
Hello Webdevelopers,

I have with my CKEditor at Backdrop 1.1.3 a problem. If I want to display the items the PHP code that works well almost everything.

But the PHP code is displayed:

```
 & lt;? php if ($ comments ['comment_form']):?? & gt;
 & lt; h2 class = "comment-form title" & gt; & lt;? php print t ('Add new comment'); ?   & gt; & lt; / h2 & gt;
 & lt;? php print render ($ comments ['comment_form']); ? & gt;
 & lt;? php endif; ? & gt;
 & lt; / section & gt;
 & lt;? php endif; ? & gt;

 & lt;! - Backdrop CMS Artikelads - & gt;
 & lt; the class = "adsbygoogle"
 style = "display: block"
 Data-ad-client = "ca-pub-XXXXXXXXXXXXXXXXX"
 Data-ad-slot = "xxxxxxxxxxx"
 Data-ad-format = "auto" & gt; & lt; / & gt into;
 & lt; script & gt;
 (adsbygoogle = window.adsbygoogle || []) push ({}).
```

The (<>) - characters are displayed as HTML and not like those characters (<>). How can that make it better and have it displayed as PHP?

That would be what I now have on the heart. Thank you in advance.

**Comment by Graham-72** [comment]
Hi @AlexL777 

With Backdrop 1.2 about to be released this week, I think it might be better to wait and see how your PHP looks once you have upgraded to use that, because it includes CKEditor in core and will advise you to uninstall the contributed module that is giving you this problem.

It will be good to hear how you get on with 1.2

**Comment by AlexL777** [comment]
Hello Graham-72,
Thanks for the good news. As long as I can wait, of course, and will be very happy about the new Backdrop version. The update should not be a problem I guess and that the CKEditor will be in the core, also sounds very good. I then post here shortly an update when I recorded the new Backdrop version. Thank you!

**Comment by MrHaroldA** [comment]
Are you trying to input php code using the Ckeditor? In my recollection, the php-module was one the first to be removed in Backdrop core as it's a really bad idea to allow users to input php on your website.

Code should live in files, not in a database. Databases are for data.

**Comment by AlexL777** [comment]
Yes, so I use a short code snippets in the articles or in the forum to show something. So I've seen it in CKEditor that you can embed PHP code. For the tool as exists. I know that otherwise only from a forum of the visual editors of a forum.

Well, I have a look when Backdrop 1.2 is out, as it will be then. I'm all alone and no one else in the blog :)

**Comment by MrHaroldA** [comment]
IIRC, Backdrop doesn't allow you to input php code through a node edit form, and there are good reasons for that.

I'd suggest that you add your snippet in a preprocess function, or alternatively a template file.

**Comment by AlexL777** [comment]
Well, well :) Then I know.
