### ISSUE TITLE
If content is published on Front page then blocks disappears

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1177]
I have two blocks (Views type) added to layout with conditions "Front page".
Ok, the blocks appears on the front page.
But if I add content to front page then the blocks disappears.
My mistake?
Please help :)
Thank you!

![front_page_1](https://cloud.githubusercontent.com/assets/13515302/9844822/20627aec-5acf-11e5-9afc-62128e3fe127.gif)

![front_page_2](https://cloud.githubusercontent.com/assets/13515302/9844830/27afe5b4-5acf-11e5-9ec0-f42b5b49ba44.gif)

**Comment by quicksketch** [comment]
Hi @bd0bd, thanks for filing this issue. This sounds like a peculiar problem. But I'm not sure if it's a bug or if things are configured incorrectly. It might just a concept learning curve problem (which we'd also like to fix of course).

I think you're doing the right thing by checking the box for "Promote to front page". And I don't think you should be giving your node an alias of "frontpage" (but I'm not sure about this). I assume your View is also configured to only show content that has been promoted? Could you copy/paste the configuration of your view into a [gist](https://gist.github.com/) so we can see how its configured?

Perhaps if you could screenshot your front page and describe what parts should be where, that would also help me understand the request more fully.

**Comment by jenlampton** [comment]
I do think we are going to run into a lot of confusion with that checkbox.  "Promoted to front page" really means "shows up in a list if you are using the the Default front page view". Which may not be the case for very many sites - and may not even be on the front page!

**Comment by MrHaroldA** [comment]
While these node properties are way faster/simpler than fields; it would be nice that all node data is stored in fields. "Status" is a property, but are "sticky" and "promote" properties too?

Fields are easily removed if not needed. You can also set fine grained access on it, change the display, etc.

**Comment by jenlampton** [comment]
They are properties now. Do they need to be? It's debatable.

Some benefits of leaving these three alone are:
1) things remain backwards compatible 
2) things stay fast 
3) it's easy: if all you need is a simple flag, you get that out of the box

See https://github.com/backdrop/backdrop-issues/issues/1190

**Comment by MrHaroldA** [comment]
Those are all pretty valid reasons. Let's not change data properties into data fields ;)

**Comment by bd0bd** [comment]
"Promote to front page" - is a good option in my mind.
But in my case it promotes not a whole page content, it promotes only a summary (announce) of the page (**jenlampton**: "shows up in a list ...").

>
 I assume your View is also configured to only show content that has been promoted?

Sorry, I do not understand what do you mean :)
I make a front page (Basic page) and would like to additionally display 3 blocks on it.

**Comment by bd0bd** [comment]
2 of my blocks:

![blocks](https://cloud.githubusercontent.com/assets/13515302/9878102/b2f532b4-5bc9-11e5-9d0a-3a5c05b0541f.gif)

**Comment by klonos** [comment]
If we actually went ahead and completely replaced the "magic" front page we inherited from Drupal with the (currently by default disabled) "Front page" view, then perhaps that checkbox could change to something like "Include this [content_type_name] in the Front page view", Would that be more clear?

**Comment by klonos** [comment]
...but I think the solution proposed in #1190 also makes sense.

**Comment by bd0bd** [comment]
>
Would that be more clear?

No.
Ok, I have disabled Front page view.
I have created front page - like a Basic page - with URL alias: node.
This page shows up like front page but the blocks disappears.

**Comment by jenlampton** [comment]
@bd0bd There are lots and lots of ways to make a front page. This is both a good thing (powerful!) and a bad thing (confusing!) I am going to list three ways below, but since I'm not sure which you have done, I'm unable to understand why your blocks are disappearing.

By default, your front page is a list of posts that have the box ticked for 'Promoted to front page'.  The blocks that appear on this page would be the blocks that have been added to your "Default" layout (unless overridden).

If you have chosen to replace the default front page with another single page (by first creating a page, visiting admin/config/system/site-information and typing in the path to your *page* there) then you will see only that one page as your home page. The blocks that appear on this page would be the blocks that have been added to your "Default" layout (unless overridden).

If you have chosen to replace the default front page with a layout (by first creating a layout, then visiting  admin/config/system/site-information and typing in the path to your *layout* there) then whatever blocks you place into the new home page layout should be appearing on the home page.

> I have created front page - like a Basic page - with URL alias: node.

I would not recommend using the alias `node`. That is a path that is provided by node module for the default home page. I'd guess that using it as an alias may cause lots of problems. Start by deleting the alias, then see what happens on your home page.

**Comment by bd0bd** [comment]
@jenlampton, thank you very much for explanations! Very useful.
I apologize for the delay in answering - I have been much overloaded with my site and needed to rest, to abstracting from GitHub and other social media :)
Thank you!

**Comment by stpaultim** [comment]
Closing. 
This is a very old question without any clear issue left to be resolved. The "Promoted to Front Page" label was changed in 1.3.0. 
https://github.com/backdrop/backdrop-issues/issues/1190
