### ISSUE TITLE
HTML garbage

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1180]
There is unnecessary code without any content in pages. For example:

```
  <header>

  </header>
```

---

```
  <section class="comments">  

  </section>
```

Please could you advice how to get rid of them if there is no any headers or comments on the pages?
Thank you!

And could you tell me please how to make the pages title:

```
  <h1 class="title" id="page-title">Articles</h1>
```

like this:

```
  <header>
  <h1 class="title" id="page-title">Articles</h1>
  </header>
```

but only for Views type pages (not for Basic pages).

Thank you!

**Comment by quicksketch** [comment]
> There is unnecessary code without any content in pages.
> `<header>`
> `<section class="comments">`

Both of these look like they are issues with the node.tpl.php file in the Bartik theme (`/core/themes/bartik/node.tpl.php`). We should be able to fix these bug in core. But you may also make a copy of the Bartik theme if you so choose by copying it to /themes/my_bartik (or similar), and then modify it at-will.

> And could you tell me please how to make the pages title like this:

The page title is controlled by the layout .tpl.php files. In order to wrap the `<h1>` in a `<header>` tag you would need to make a copy of each layout template file (copied from `/core/layouts/*/layout-*.tpl.php) into your theme. If you wanted to do this, you would definitely need to make your own custom theme. While many markup changes are done from the interface, the page title is at a site-wide layout level, so doing this through the theme is the only way possible.

**Comment by quicksketch** [comment]
The PR at https://github.com/backdrop/backdrop/pull/1054 should fix the problem with the empty wrappers being output by Bartik.

**Comment by quicksketch** [comment]
I merged in https://github.com/backdrop/backdrop/pull/1054 that will fix the empty wrappers in the next version. The question about modifying the markup of the `<h1>` heading unfortunately is a bit more complicated to answer. Let's file a new issue as a question to answer it fully if needed.
