### ISSUE TITLE
Bug: article tag has two attributes role="article"

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1181]
Bartik.
Article tag has two attributes role="article"

```
<article id="node-2" class="node node-page view-mode-full clearfix" role="article" role="article">
```

**Comment by quicksketch** [comment]
Thanks @bd0bd! You're right. I hadn't noticed this in Firefox because when using the inspector it combines duplicate attributes and doesn't show them to you! Looks like we can just remove the `role="article"` from Bartik's node.tpl.php file, because the ARIA role is also added in `template_preprocess_node()`.

**Comment by quicksketch** [comment]
Thanks, a fix has been merged into 1.x and 1.1.x. This will be in the next releases that come out tomorrow.
