### ISSUE TITLE
CKEditor image captions break if you include a colon (:)

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1201]
I was trying to add the following caption to my image: `Three new field-type modules in core: Email, Link & Date.` but the following is output: `Email, Link & Date`.  I tried several variations of the capiton, and discovered that the problem only occurs when a colon is used. When it is, only the text that follows the colon is output.

**Comment by quicksketch** [comment]
This was a strange issue. The problem was the `filter_xss` function, which is run during the "Filter HTML" filter. filter_xss() has a portion for stripping unknown protocols (e.g. http, ftp, news, mailto, etc). What was happening here is a caption like `data-caption="Image: The Caption"` was being parsed to strip any unknown protocols. So "Image:" was considered a protocol, which wasn't in the white list and so was stripped out.

PR at https://github.com/backdrop/backdrop/pull/1067.

**Comment by jenlampton** [comment]
This appears to be a problem in Drupal for `alt` and `title` tags in images as well as for attributes. I'm not sure why we don't have the same problem in Backdrop, but my testing so far shows `alt` and `title` work as expected when containing colons.

**Comment by indigoxela** [comment]
> I'm not sure why we don't have the same problem in Backdrop,...

Because we fixed it in #4158

**Comment by jenlampton** [comment]
@klonos this isn't duplicate, it was fixed in https://github.com/backdrop/backdrop/pull/1067.

**Comment by klonos** [comment]
Right, sorry 😬
