### ISSUE TITLE
Expects parameter 1 to be string, object Given in check_plain

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#1209]
Hello Backdrop developers.

I use Backdrop 1.2 and give me this warning has been displayed in the backend:

```
Warning: htmlspecialchars () Expects parameter 1 to be string, object Given in check_plain () (line 1848 of /www/htdocs/xxxxxxxxxxx/cms/backdrop/core/includes/bootstrap.inc).
```

What does it mean and how can you fix it? Thank you in advance.

**Comment by quicksketch** [comment]
Hi @AlexL777! Thanks for the report. On which pages to you receive this error? If we can reproduce it then we should be able to fix it easily.

Did you upgrade your site to 1.2 or is this a new site?

**Comment by AlexL777** [comment]
Hmm .... the error no longer exists and I do not know how I can reproduce that. Therefore everything first well, Thanks anyway.
--------------------------------------------------------------------------------------------------------

But with me something else very suspicious has occurred and that when I try to log in /user, a window opens with a sex website.

I do not know where it comes from and how to turn off the. This struck me recently and every time I want to login. Is it because of my browser or other settings? I do not know yet.

**Comment by AlexL777** [comment]
I have discovered the error again and indeed at this URL
    /admin/config/people/captcha/captcha/settings

Can you please test times and see if the error occurs with you. Thank you!

**Comment by quicksketch** [comment]
> But with me something else very suspicious has occurred and that when I try to log in /user, a window opens with a sex website.

Yikes! If you can figure out the cause of this, if you're site's code has been modified or if it is an issue on the browser/computer you're using, please let us know. If it looks like your site has been hacked, please send an email to security@backdropcms.org and we'll try to figure it out internally.

> Can you please test times and see if the error occurs with you. Thank you!

Seems like the notice might be an issue with Captcha module rather than a core issue. Could you file an issue at https://github.com/backdrop-contrib/captcha/issues?

**Comment by AlexL777** [comment]
Hello and thank you for the assistance. This sex-window in the browser was no longer appeared, but when it comes again, I'll try to figure out, in which process or what action it occurs when I am in the blog.

At first it was very strange and I thought, I have adware on your PC.
