### ISSUE TITLE
Can not install Devel module - "Cannot determine the type of project."

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1215]
Can not install Devel module.

Error: **Cannot determine the type of project.**

The module is taken from here: https://github.com/backdrop-contrib/devel

**Comment by quicksketch** [comment]
How are you trying to install this project? It looks like this error may be coming from the built-in module installer, rather than if you had placed the module manually in the /modules directory.

Could you try using the URL of the latest release: https://github.com/backdrop-contrib/devel/releases/download/1.x-1.5.3/devel.zip?

Note that you must provide a URL to the module zip file, not the path to the project page. This whole system will be a lot easier once we provide a built-in tool for finding modules, see #870.

**Comment by bd0bd** [comment]
![devel1](https://cloud.githubusercontent.com/assets/13515302/9923176/6a10e142-5cfa-11e5-8063-0446a42bee91.gif)

![devel2](https://cloud.githubusercontent.com/assets/13515302/9923177/6f6343b0-5cfa-11e5-9520-8360e5a449f3.gif)

**Comment by klonos** [comment]
...could this be a side effect of #960??

**Comment by bd0bd** [comment]
I have manually installed Devel in the **/module** folder.
And now I can not deinstall it.
Should I do it manually deletig the module folder in **/modules**?

![devel1](https://cloud.githubusercontent.com/assets/13515302/9923633/fa1726f2-5cff-11e5-8a1e-cf36c76619b7.gif)

![devel2](https://cloud.githubusercontent.com/assets/13515302/9923634/0106c58a-5d00-11e5-8502-93a8efd5dbea.gif)

**Comment by quicksketch** [comment]
Thanks @bd0bd. Really appreciate all your patience and filing all these issues.

> I have manually installed Devel in the /module folder. And now I can not deinstall it.

Backdrop does not provide a mechanism to delete the modules from disk. However I see how this could be strange considering you used Backdrop to add the modules to disk. Let's make a separate issue for this task. To fully remove the module, you indeed have to delete the directory from /modules.

> ...could this be a side effect of #960?? I think so.

Yes, seems likely. Let's use this issue to try and solve this problem.

**Comment by quicksketch** [comment]
Pinging @docwilmot. :smile: Maybe our resident update.module expert take a look at this?

**Comment by docwilmot** [comment]
I think it is #960 causing this. I suspect its because we required every project to have a 'type' parameter, but Devel's submodules (devel_generate and devel_node_access) do not. So the the updater throws an error.

Maybe we should have a more helpful error message?

**Comment by docwilmot** [comment]
I hhavent looked into the cannot uninstall bit, because its wayy past bedtime here. ASAP tomorrow, sorry.

**Comment by docwilmot** [comment]
Confirmed. If you update Devel's submodules to have the type specified, all goes well. So it seems one cannot have subprojects without the type specified. We can do either
1. change so that update module scans only the first level directory and gives the green light it if finds a type in the `.info` file, even if submodules dont have this
2. enforce that all modules including submodules have a type parameter in the `.info` file.

If 1. then I'll try and fix it.
if 2. though, we'd need to update Devel and every other contrib with submodules and also preferably update the Project GitHub code to also throw an error for submodules.

I'm leaning towards 2. because its more complete a solution. We've completely removed the project type guessing alluded to in the first post above, and put in the more reliable type checking and I think we should use it.

**Comment by klonos** [comment]
1 is easy, 2 is the right way to do it.

**Comment by klonos** [comment]
> Maybe we should have a more helpful error message?

Instead of "Cannot determine the type of project." I propose something like "Missing project type property for the following modules: ...[list] ...Please report this to the respective module maintainer(s)"

**Comment by docwilmot** [comment]
> Missing project type property for the following modules

That would be impossible because we wouldnt know if it is a module because we cannot check. :smile: 

Just being pedantic; you're right, something along those lines should be done.

**Comment by klonos** [comment]
> That would be impossible because we wouldnt know if it is a module because we cannot check. :smile:

Touché :smile:

**Comment by quicksketch** [comment]
Sounds great. Well I can update devel.module as it seems to be a bug in its .info files. But I also think it would be great if we provided the more elaborate explanation.

**Comment by quicksketch** [comment]
Updated Devel module and cut a new release 1.5.4.

**Comment by quicksketch** [comment]
De-escalating this as this seems to be a .info file and clarity problem rather than an issue with all installations of modules.

**Comment by sutibun** [comment]
Think it's pointless to mention it at this point but I will anyway.

Getting the same error: "Cannot determine the type of project." when I tried installing the [markdown filter](https://github.com/backdrop-contrib/markdown)

**Comment by quicksketch** [comment]
> Think it's pointless to mention it at this point but I will anyway.
> Getting the same error: "Cannot determine the type of project." when I tried installing the markdown filter


Certainly not pointless! I made an issue at https://github.com/backdrop-contrib/markdown/issues/1

**Comment by quicksketch** [comment]
Updated the tags as I think we're leaning towards encouraging modules to update rather than this being a bug in core. A better error description is still desired though.

**Comment by sutibun** [comment]
@quicksketch Yay, I can install markdown now. Thanks.

There are so many places to put issues, didn't think about the contrib one

**Comment by quicksketch** [comment]
Thanks @sutibun for the followup!
