### ISSUE TITLE
Admin bar and editor disappear when I try to add content Article

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1220]
Admin bar and CKEditor disappear when I try to add content Article or edit the current ones.

![article2](https://cloud.githubusercontent.com/assets/13515302/9934940/bb2abbfe-5d5c-11e5-962d-38f8984faaf8.gif)

![article1](https://cloud.githubusercontent.com/assets/13515302/9934933/b506d7f8-5d5c-11e5-8f28-e858e698fe94.gif)

**Comment by docwilmot** [comment]
Hi @bd0bd 
I notice you just posted an issue with a theme, so I'm suspecting the theme may be the problem here. Can you try another theme and see please? If this problem is specific to a particular theme, then please post an issue in that theme's issue queue. If not post it here again.

**Comment by bd0bd** [comment]
Hi @docwilmot
My admin theme is Seven.
I have tried Bartik like admin theme - result is the same.

**Comment by dboulet** [comment]
Hi @bd0bd, this could be caused by a JavaScript error on the page. Are you able to access the console in your browser, and check it for errors? If you need help with that, just let us know which browser you are using.

**Comment by bd0bd** [comment]
Hi @dboulet!

Google Chrome, Version 45.0.2454.93 m.

But other pages are ok. This problem is only with Article. May be this happens because of this?: https://github.com/backdrop/backdrop-issues/issues/1223

I do not know how to check it for errors.

**Comment by dboulet** [comment]
@bd0bd, navigate to the page with the missing admin bar and editor, then open the JavaScript console in Chrome using the keyboard shortcut `Command` + `Option` + `J` (Mac) or `Control` + `Shift` + `J` (Windows/Linux). Let us know if the console contains any errors.

**Comment by bd0bd** [comment]
![error](https://cloud.githubusercontent.com/assets/13515302/9943729/df14fd02-5d8b-11e5-818b-adbad99e2225.gif)

**Comment by docwilmot** [comment]
Almost there. To the end of that line, there should be a link to where this error is triggered. 

![console](https://cloud.githubusercontent.com/assets/1042283/9943872/9fa8d22a-5d49-11e5-8ba0-e382e2df2366.PNG)

Right click, copy and paste here!

**Comment by bd0bd** [comment]
var label = $('label[for=' + element.getAttribute('id') + ']').text();
      format.editorSettings.title = Backdrop.t("Rich Text Editor, !label field", {'!label': label});

**Comment by klonos** [comment]
> But other pages are ok. This problem is only with Article. May be this happens because of this?: #1223
If I will delete Article views and create it again (a new one) then my articles will not be deleted?

Just for the record, #1223 is not limited to article views. It happens with any view.

**Comment by dboulet** [comment]
Thanks @bd0bd, that was helpful.

I noticed in one of your screen shots, that you are using the filtered HTML format for a regular text input field—it’s the second one, after the Image field. I tried testing this out on my own site by creating a new text field for Articles and then enabling text filtering on it—and in doing so, was able to reproduce your bug.

In more detail, here are the steps to reproduce:

1. Create a new field of the type **Text (short)**, which uses the **Text Field** widget type.
2. In the fields settings, set **Text processing** to **Filtered text (user selects text format)**.
3. If your default text format uses a rich text editor, Backdrop loads it on the node form and tries to use it for your text input field, which produces a JS error.

I think the bug here is that Backdrop should only use rich text editors for fields that use the text area widget, and not for those using a regular text input.

**Comment by quicksketch** [comment]
Thanks everyone. @bd0bd again for filing all these reports. @dboulet thanks for figuring out these steps. I've reproduced it as well.

Aside, how would a filter format on a single-line text field possibly be good idea!? Sigh. Legacy code.

I filed a PR at https://github.com/backdrop/backdrop/pull/1075. This makes filter.module bail from trying to attach editors if it can't find a textarea.

**Comment by quicksketch** [comment]
Merged. This will be in 1.2.1.

**Comment by bd0bd** [comment]
So, right now I am forced return my site back to 1.1.3 :)

**Comment by Graham-72** [comment]
I came across what I think is a similar problem with Global Text Areas in Views when using these for Header and Footer. I found that CKEditor was appearing when I wanted to edit the footer, but not saving any change I made. So I have created a 'no filters' text format and am happy to work with HTML code as an expedient just for these text areas, rather than abandon v1.2 which has so many improvements.

**Comment by bd0bd** [comment]
>
rather than abandon v1.2 which has so many improvements.

Yes, it has.
But too much problems for a Backdrop dummy user like me with this new version :)
It is ok for a user (to quickly find solutions and solve minor problems) who is familiar with Drupal but I am not familiar + my brain is badly sharpened for this sort of things (programming, mathematics, technology).

I will wait a little more for newer Backdrop versions.

**Comment by Graham-72** [comment]
@bd0bd That makes me a little bit sad because you are doing such a valuable job pointing out these problems. From past experience I know that @quicksketch and others will be very quick to fix these things so I hope you will be able to try v1.2.1 as soon as it is released, and then see how many of your needs are now met.

I very much agree with you that we have to have a solution that does not need great familiarity with Drupal, html, php, css etc. and sometimes those of us who do may fail to appreciate the uphill task for others. But I think our hearts are in the right place!

**Comment by quicksketch** [comment]
> I hope you will be able to try v1.2.1 as soon as it is released, and then see how many of your needs are now met.

That time is right now! [Download Backdrop 1.2.1](https://github.com/backdrop/backdrop/releases/tag/1.2.1).

Thanks again @bd0bd for all these reports. In just a few days you uncovered not only new issues in 1.2.0 but also several issues that we hadn't known existed in the 1.1.x releases for months. I hope you'll continue to help us make the software better for everyone. :smile:

**Comment by Graham-72** [comment]
>That time is right now! Download Backdrop 1.2.1.

Thank you @quicksketch  - brilliant service! :+1:  :+1:
