### ISSUE TITLE
Layouts - combine path row with layout name row in one row

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1233]
I offer to combine path row with layout name row in one row:

![layout](https://cloud.githubusercontent.com/assets/13515302/9980883/bf737c52-5fb2-11e5-91eb-1a931d5df768.gif)

**Comment by quicksketch** [comment]
The current arrangement is by-design, in the event that either you have fabricated a new path, or if you have multiple layouts at the same path that are selected via a condition.

In your screenshot, it does indeed seem rather silly, but in a situation like this, you might think twice about combining the two of them:

![screenshot34](https://cloud.githubusercontent.com/assets/100206/9983777/2c6cec58-5fc7-11e5-9854-1c492ee0f899.png)

In the event that you have created an entirely new path with Layouts (rather than overriding an existing one), the row containing the path is used for editing the menu settings. Each row within the path is used for editing the layout.

If you have multiple layouts at the same path, you also need to be able to reorder the layouts within that path.

So in short, the reason why there are two rows is because there are two concepts on this page:

- Each "group" of layouts is actually a menu item path. This menu item needs to be edited separately from the layout, because a group of layouts may all share a single menu items.
- Then within each group, you need to be able to edit each layout individually.

If laid, out, it's set up like this:

- Menu item
  - Layout
- Menu item
  - Layout
  - Layout
  - Layout
- Defaults (all other unspecified menu items)
  - Default layout
  - Default admin layout

In your screenshot, it happens that all the menu items listed can't be edited, so the rows seem unnecessarily duplicated. The UI is set up to accommodate the more complicated (and not at all uncommon) situation of having multiple layouts at the same path and creating new URLs entirely through layouts.

We certainly may be able to improve this UI, but I don't think just consolidating the two items onto one line would be a sure win.

**Comment by bd0bd** [comment]
>
but in a situation like this, you might think twice about combining the two of them

You are right.
