### ISSUE TITLE
Custom layout problem - it should be 2 columns but it is 1 column

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1234]
I try to make layout.

I have cloned the **two_column** layout folder and then changed files names etc.

![lay](https://cloud.githubusercontent.com/assets/13515302/9982937/52892130-5ff5-11e5-8693-e4a69427d2b4.gif)

But finally I get one column layout with sidebar below main content block.

![sdb](https://cloud.githubusercontent.com/assets/13515302/9982947/d58317ee-5ff5-11e5-89cc-1b99f030e0ae.gif)

Pls could you tell me where is my error?
Thank you!

Yes, I have read it https://api.backdropcms.org/layouts

**Comment by quicksketch** [comment]
It's a little hard to tell what the source of the problem is, but I would guess you may need to update your CSS in `contact.css` to match whatever the markup is in your `layout--contact.css` file.

For example in the layout--two-column.tpl.php and two-column.css file, the markup and CSS matches:

![screenshot-edit](https://cloud.githubusercontent.com/assets/100206/9984019/b211b8e8-5fcc-11e5-84b6-f1d21d075cfa.png)

You probably need to update the contents of your CSS and .tpl.php file to match each other.

**Comment by bd0bd** [comment]
@quicksketch thank you very much!

I am wooden Pinocchio :) I have done everything correct but overlooked to change these elements:

![untitled-1](https://cloud.githubusercontent.com/assets/13515302/9984118/9fb10fca-601a-11e5-84ab-9139cb3a5452.gif)

**Comment by quicksketch** [comment]
No problem. I've been there myself. :wink:
