### ISSUE TITLE
Seven theme: Breadcrumb contextual menu rendered behind the primary links/tabs.

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1252]
Updated to 1.2.2.

![unv](https://cloud.githubusercontent.com/assets/13515302/10084979/dadf91ce-630e-11e5-854c-370adc0eef46.gif)

But why it is - Unknown release date (version 1.2.2 available) - and is indicated 1.3?

![1 3](https://cloud.githubusercontent.com/assets/13515302/10085043/548ce490-630f-11e5-821c-6375d22e079f.gif)

**Comment by klonos** [comment]
@bd0bd it is best if you open one issue for each problem you have instead of asking all questions in one issue.

The first problem you are having is legit. I test this myself and I confirm it - even in version 1.2.0.

The second issue is nothing new to Backdrop and it has to do with our dev versions (like the one you are using) not having some sort of timestamp. This is in fact a problem we have "inherited" from Drupal but in Drupal they have solved it by adding build timestamps to their dev versions (same as they do for stable releases). I have already filed an issue against Backdrop here: #664 and it could also be related to #1094

**Comment by klonos** [comment]
...a ```z-index``` issue I guess.

**Comment by bd0bd** [comment]
>
 it is best if you open one issue for each problem

Ok, I will try this way in future.

>
The second issue is nothing new to Backdrop

I see. Thank you very much!

**Comment by klonos** [comment]
No worries @bd0bd

**Comment by Dinornis** [comment]
I think the problem has been addressed.  Closing and marking as fixed.

**Comment by klonos** [comment]
Yep, the primary tabs have been moved to the left, right below the page title. Even if more items are added to the contextual menu, the `z-index` seems to have been adjusted so that the contextual menu is rendered above the primary tabs:

![image](https://cloud.githubusercontent.com/assets/2423362/25871321/74db5966-354a-11e7-9c27-09913d88ddc9.png)
