### ISSUE TITLE
Support creating content types by config

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#1256]
In https://github.com/backdrop/backdrop-issues/issues/571#issuecomment-72962972 it was suggested that we cannot yet bundle content types as config. 

As part of [the discussion on 'package-type modules'](https://github.com/backdrop/backdrop-issues/issues/1238#issuecomment-143128470) I was considering what you would need to build a complex packaging module, and recalled that node types perhaps still can't be done (maybe that changed since? don't know). 

Related [[CMI] Export/Import an entire content type (or other entity type) with its fields all at once](https://github.com/backdrop/backdrop-issues/issues/408).

This issue to see how it could be done.

**Comment by quicksketch** [comment]
> I was considering what you would need to build a complex packaging module, and recalled that node types perhaps still can't be done (maybe that changed since? don't know). 

To be clear, content types can be created via config if you're doing a full import. However, they're not installed properly if you just bundle a node type JSON file in a module. This is a larger problem caused by not running config files through the import process when a module is installed. Instead, right now config is just directly copied from the module `/config` directory into the active config directory. I think the missing piece here is simply ensuring that all config files are run through the config import immediately after the module is turned on.

**Comment by docwilmot** [comment]
> To be clear, content types can be created via config if you're doing a full import
> I think the missing piece here is simply ensuring that all config files are run through the config import immediately after the module is turned on.

**Comment by klonos** [comment]
Was there any follow-up to implement the missing piece of functionality as mentioned in the last comment? Should we reopen this?

**Comment by laryn** [comment]
If I understand this, I'd love to be able to include some node types and fields in a module config and have a custom type with fields be automatically added!
