### ISSUE TITLE
Comment module doesn't properly remove its tables when uninstalled.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1264]
Steps to reproduce:
1) enable comment module (if not enabled already)
2) disable comment module
3) go to uninstall page
`No modules are available to uninstall.`
4) go back to the module list
5) enable comment module
`DatabaseSchemaObjectExistsException: Table comment already exists. in DatabaseSchema->createTable() (line 646 of backdrop/core/includes/database/schema.inc).`

**Comment by jenlampton** [comment]
Quick fix, drop the comment tables yourself:
```mysql
drop table comment;
drop table node_comment_statistics;
update system set status = 0 where name = "comment";
```

**Comment by quicksketch** [comment]
I can't reproduce this problem. Before uninstalling comment:

![screenshot55](https://cloud.githubusercontent.com/assets/100206/10127682/63fa3224-6563-11e5-8cad-1ac976be9b49.png)

After disabling and then uninstalling comment:
![screenshot56](https://cloud.githubusercontent.com/assets/100206/10127685/6c780be2-6563-11e5-90a1-cc8d0e0fe998.png)

I even tried turning the module on again, adding a comment, then uninstalling it again. It still was deleted immediately.

The only thing I can think of here that might cause this would be if you had more than 200 comments on the site. In which case the field deletion problem may have struck again (see #82). Since Backdrop will not delete 200 fields worth of data at one time, it may have required that cron run the "arbitrary number of times" until all comments have been deleted (including their data in field tables).

**Comment by jenlampton** [comment]
In my use-case there were zero comments (I disabled it immediately after using the default profile). But when visiting the uninstall page there was nothing in the list.  Were you actually able to uninstall something?

**Comment by quicksketch** [comment]
> But when visiting the uninstall page there was nothing in the list. Were you actually able to uninstall something?

Yes, after disabling comment module it was available to uninstall on `/admin/modules/uninstall`. That's really odd that it wasn't available for uninstallation, especially if the comment table *was* there, then comment module had to have been installed at some point.

Well, as-is we don't have a way of reproducing this issue now. Should we close it until we have more information (if that ever happens)?

**Comment by jenlampton** [comment]
sounds good.
