### ISSUE TITLE
How do I control what appears in the "formats" ckeditor button?

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1267]
I want to be able to use the codefilter on the backdropcms.org site, but I can't figure out how to add a `<code>` tag. There is no button for this tag, but maybe it is a format? How can I tell what will appear in that list, is there a UI for that or do I need to write JS for ckeditor in order to change it?

**Comment by serundeputy** [comment]
maybe; :sake: 

http://ckeditor.com/addon/codeTag

I don't know how to integrate that, but it appears the js is already written; we (backdrop cms) just need to figure an integration.

**Comment by serundeputy** [comment]
more: :electric_plug: 
https://github.com/danielsvane/ckeditor-code-tag

**Comment by quicksketch** [comment]
This is a good point. CKEditor comes with two buttons: "Format" and "Styles"

The intention for "Format" is that it defines block styles, such as `<p>`, `<h2>`, and `<div>`. The `<code>` tag is a mixed bag because it is not actually a block-level element, it's an inline one, which is why you can wrap a single word in tags such as `<code>example</code>`.

Really a `<pre>` tag is what we'd want for a block-level code element. If you add `<pre>` to the list of HTML tags in the filter, then it shows up as "Formatted" in the "Format" list button:

![selection_008](https://cloud.githubusercontent.com/assets/100206/10127351/917a43ac-655d-11e5-8aa9-d9dc7f236654.png)

The "Styles" button is intended to be used to provide a list of *classes* rather than specific tags, (although the tag must also be specified, such as `p.highlight`).

So it looks like in summary, there is indeed no way to add a code tag. You can fake it by adding a code "style", such as `code.foo` to the Style list. That will result in a tag such as `<code class="foo">`, which is definitely a hack rather than a proper solution.

BTW, the Code Filter module is probably causing some of the confusion, because it makes it so that code tags are *both* inline and block. If you have a single line of text, it makes it inline. If you have multiple lines, then it actually makes a `<pre><code></code></pre>` wrapper, including both tags.

So what's the solution? I think that Code Filter module was built with hand-entered HTML in mind, rather than any kind of editor. Nothing else could distinguish between new-lines being present in the markup or not. So what I think we should do is modify Code Filter so that it uses a more editor-friendly markup, such as `<pre class="code">` and `<pre class="code php">` for example. Or if doing inline, then `<code class="php">`.

The only other solution would be if Code Filter module shipped with a CKEditor plugin that could specifically provide CKEditor-side formatting to match its own filtering, but that solution likely be more work (less of us are familiar with CKEditor plugins) and more likely to break in the future.

**Comment by quicksketch** [comment]
Actually, there is yet another problem with Code Filter module, in that it auto-escapes within `<code>` tags. CKEditor already auto-escapes everything typed into the front-end. So if you were to select a string of text, then wrap it in `<code>` tags, it would end up double-escaped (once by CKEditor on input and once by Code Filter on output).

Generally, it doesn't seem like Code Filter module is at all compatible with the concept of rich-text editor. I think maybe I would just encourage the two not to be mixed together in the same format configuration.

**Comment by jenlampton** [comment]
I have removed the codefilter from the Basic input format on backdropcms.org, and added it to the HTML Code format instead.  Anyone who needs code filtering for now should change to that format.

**Comment by jenlampton** [comment]
closing this issue since the question has been answered. Please re-open if you feel there is more to be discussed here.

**Comment by gifad** [comment]
If you want to show code snippets, CKSource supplies http://ckeditor.com/addon/codesnippet
Of course, you need some lines in a contrib module to enable it…
