### ISSUE TITLE
[UX] Replace "Node" with "Content" in the URL aliases page & token browser?

### ISSUE THREAD

**Issue by sutibun** [backdrop/backdrop-issues#1283]
In the URL aliases page ("admin > config > search > path > patterns"), there are instances of "Node" everywhere... er... token themselves like "[node:title]"

![pattern](https://cloud.githubusercontent.com/assets/14132746/10214376/29f9d71a-67dd-11e5-8230-8490fd8d577c.png)

If you click the "token browser", you see even more

![token](https://cloud.githubusercontent.com/assets/14132746/10214452/0bd6f7f8-67de-11e5-85e2-f3313ceeec3b.png)

I don't know if it matters here or if we want to do something about it or not. Changing it might look a lil' messy I think.

PS: Like how a practical pattern example was given with blog.

> Path patterns automatically alias new content based on wildcards called "tokens". For example the URL "node/10" might be automatically aliased to "blog/my-first-post" using the pattern "blog/[node:title]".

Copy and pasted.

**Comment by klonos** [comment]
This one is much more "involved" than #1282. The tokens themselves, though shown in the UI, are ```code``` themselves.

**Comment by sutibun** [comment]
Hmm... maybe we should replace "tokens" with "snippets"?

**Comment by quicksketch** [comment]
I'm not sure we could replace the actual content of the tokens. Once a token is created, it's *very* hard to take back or change, because it may have been used in many, many different places. I think we may need to slog through with `node` tokens to maintain our backwards-compatibility. The labels of the tokens have already been changed as shown in the screenshot (e.g. Content ID, Content Title), I think that's as much as we can reasonably do.

**Comment by sutibun** [comment]
I had an inkling it would be hard to change but thought I bring it up just in case.

> I think we may need to slog through with node tokens to maintain our backwards-compatibility.

Ah, didn't think about that at all. You're right.

The mob has spoken. I'll close this then.
