### ISSUE TITLE
 Login problem

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1304]
If I will log out and then try to log in then I get this:

![login](https://cloud.githubusercontent.com/assets/13515302/10400965/b8e8ece8-6ec4-11e5-98d3-9b0b9e9545e1.gif)

If I change password then it does not help - after log out I get the same situation if I try to log in.

**Comment by bd0bd** [comment]
May be the above problem has any relation with this issue?
I have one user only - admin - but here is addition user with empty line - I do not understand why:
![user](https://cloud.githubusercontent.com/assets/13515302/10410963/4127a13e-6f5c-11e5-96ff-422d48041900.gif)

**Comment by findlabnet** [comment]
User with `uid 0` - account for anonymous users sessions, so it not a problem (btw, don't try remove this record, it used by system). Maybe someone (human or bot) was try brut-force password for this username and blocked as we can see in error message. Using usernames such as "admin" is bad practice - many of cracker's bots try to use it (thanks to some popular CMS).

**Comment by bd0bd** [comment]
>
don't try remove this record, it used by system

Thank you!

>
Maybe someone (human or bot) was try brut-force password

I have had this idea too. But the problem was repeated two minutes after I have created a new password and loged out.

>
Using usernames such as "admin" is bad practice

Yes, I know this but I like to use "admin" :)

**Comment by quicksketch** [comment]
If you can't log in because of a mistaken password too many times, you can TRUNCATE the `flood` table to clear the recent login attempts. That will let you log in immediately if you don't want to wait 5 minutes.

It's also worth checking this table to see if login attempts are failing frequently. After logging in, you can also check the "Recent log entries" page to look for failed password attempts to see if you're getting a lot of bot-generated login-attempts.

**Comment by bd0bd** [comment]
Thank you!
No there was no my mistakes with password.
`flood` table is empty.
Now everything is ok - I can log out and log in again without problems.

**Comment by quicksketch** [comment]
Hm, thanks @bd0bd. Let's reopen this if the problem occurs again (for you or anyone else).
