### ISSUE TITLE
[UX] Rename labels in add block page?

### ISSUE THREAD

**Issue by sutibun** [backdrop/backdrop-issues#1340]
This I am not sure but throwing it out there. Whenever I go to add a block ("/admin/structure/block/add") I am always confused by the labels. I **always** have to read the descriptive text below to make sure what it means

![add-new-block](https://cloud.githubusercontent.com/assets/14132746/11018593/26cf7afa-8596-11e5-8528-e49a5c0fcd39.png)

Would it make sense to rename them?
- Name => Admin name
- Title => Block title
- Body => Block content

![improved-add-block](https://cloud.githubusercontent.com/assets/14132746/11018595/2b6edb00-8596-11e5-8a2c-40824f782030.png)

Could be me but I feel friction whenever I get to this page.

**Comment by quicksketch** [comment]
:+1: Yes yes yes please.

A simple change and much better UX.

**Comment by jenlampton** [comment]
Brilliant. I'm not sure about "Admin name", don't we call these things "Administrative label"s elsewhere in core? or is that only in D8 / entity land?

**Comment by sutibun** [comment]
I'm not sure if these new names (e.g. admin name) are the best but can't think of anything else at the moment.

**Comment by wesruv** [comment]
This is an issue in a few places, Views comes to mind, probably some other Ctoolsy things... might be good to have a pattern for how we handle this. 

In my past life I used 'Admin Title' and 'Display Title'. Not sure that those were great either.

**Comment by sutibun** [comment]
"Name" and "title" are what get me. They almost seem the same thing if left by themselves.

I do like how "Admin Title" and "Display Title" are much clearer. Particularly "display"... at least, I take it to mean ... for display purposes.... that shoe is only for display purposes.... in other words, meant for users/passerby/visitors to look at.

**Comment by quicksketch** [comment]
Ah, one thing I probably would change here is "Admin name" to "Admin label".

- A "Title" is usually shown above its content.
- In Backdrop, "Name" most commonly refers to "Machine name" (i.e. no spaces, all lower-case).
- "Label" is what we use (or should be using) when we need to have a human-readable version of something that's not necessarily a title.

That's why entities have `$entity->label()`, instead of `$entity->title()`.  Some times may point at `$node->title` but types of data is may differ, e.g. `$user->name`. 

> I'm not sure about "Admin name", don't we call these things "Administrative label"s elsewhere in core? or is that only in D8 / entity land?

Oh, Jen already said the same thing. +1 for admin label.

**Comment by klonos** [comment]
:+1:  for "Admin label" and "Display title"

**Comment by mikemccaffrey** [comment]
> :+1: for "Admin label" and "Display title"

Ditto!

**Comment by wesruv** [comment]
:+1:

**Comment by sutibun** [comment]
The mob has spoken. ^^)b Let's go with it.

**Comment by Graham-72** [comment]
:+1:

**Comment by quicksketch** [comment]
What about the Body field?

- Admin label
- Display title (or "Block title"?)
- Body (or "Block content"?)

**Comment by klonos** [comment]
...well, if we wanted to be 100% precise ti should be:

- Block admin label
- Block display title
- Block content

...but I think that constantly repeating "block" and having more than two words for a labels might be too much. So:

- Admin label
- Display title
- Block content

Reasoning:

1. keeps labels down to two words
2. emphasis between "label" for the admin UI vs "title" that will be displayed in the front-end
3. although people might be familiar with the term "body" (from their mail clients most likely) "content" is less vague (doesn't relate/refer to anatomy).

**Comment by jenlampton** [comment]
I like these: 

Admin label
Display title
Block content

**Comment by wesruv** [comment]
Yeah, so long as they're not fieldable I think that is clearest ^^

**Comment by mikemccaffrey** [comment]
Well, the one issue is that we would be breaking convention by renaming the Name field, which is what is used for the same thing when you create a View, Menu, and Taxonomy. Should we think about changing Name to Admin Label for all of these modules to help keep things clear and consistent?

Also, we may want to change the block Title field to Default Title, since when you place it into a layout, you have the choice of using the default title, or setting a layout specific one.

**Comment by mikemccaffrey** [comment]
Also, whatever we decide, I can make the change as part of the pull request for #1428, since I am already modifying that form to add a Machine Name field, since saving the blocks to configuration needs a better identifier than an auto-incrementing id.

**Comment by wesruv** [comment]
Good call! I love the idea of being clear about what names/titles are for the Site Editor/Builder and which ones are user facing.

**Comment by jenlampton** [comment]
Okay, let's go with 

```
Admin label
Display title
Block content 
``` 
in both #1428 and #1099

**Comment by jenlampton** [comment]
I've updated both those issues with this terminology. closing this as dupe.
