### ISSUE TITLE
Document where the  Admin Bar/Admin Menu update hooks are found 

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1344]
I don't see any code in admin_bar.install to move admin menu's variables into admin_bar's config.

TODO: 

* put a note in admin_bar.install describing why the updates are in system.install instead

**Comment by quicksketch** [comment]
This is because we provide an upgrade from "admin_menu" in D7 to "admin_bar" in Backdrop. Because of the name change, the updates need to live in system.install. So [system_update_1009()](https://api.backdropcms.org/api/backdrop/core!modules!system!system.install/function/system_update_1009/1) is responsible for doing the update currently.

I do think it would be a good idea for us to put a note in `admin_bar.install` describing why updates are not in that file however. Especially as it would be easy for us to forget to put future updates in system.install instead of admin_bar.install (which we need to do for the future upgrades from D7).

**Comment by jenlampton** [comment]
Related: https://github.com/backdrop/backdrop-issues/issues/3687

**Comment by BWPanda** [comment]
> we provide an upgrade from "admin_menu" in D7 to "admin_bar" in Backdrop

I don't see this as being the case... `system_update_1009()` simply enables the Admin Bar module and sets its default values. It doesn't do anything with existing Drupal variables from the Admin Menu module, and searching for `admin_menu_position_fixed` (one of the Drupal variables (of which there is an equivalent Backdrop setting)) in Backdrop core gives no results (i.e. no upgrade path for it elsewhere in core either).

So I'd say we close this issue (as there are no update hooks for Admin Bar/Menu) and look at implementing an upgrade path in https://github.com/backdrop/backdrop-issues/issues/3687.
