### ISSUE TITLE
Views titles triple escaped when source is contextual filter

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1353]
When I add a contextual filter to a block view, and select 
`When the filter value IS available or a default is provided` 
- [ ] Override title 
  `Contact %1` 

I often get something like this:
`Contact Bob Skinner&#039;s Ski &amp; Sport`

**Comment by jenlampton** [comment]
It looks like the problem is in layouts. The escaping that's done in `template_preprocess_block` should really only happen if that title was a custom title provided in the layout UI, not if that title came from a module (assuming the module is responsible for it's own escaping, if necessary).

**Comment by quicksketch** [comment]
Yep, confirmed here's the code from D7:

https://api.drupal.org/api/drupal/modules!block!block.module/function/_block_render_blocks/7

In particular this bit:
```
        // Override default block title if a custom display title is present.
        if ($block->title) {
          // Check plain here to allow module generated titles to keep any
          // markup.
          $block->subject = $block->title == '<none>' ? '' : check_plain($block->title);
        }
```

But in Backdrop, we're *always* escaping the title, rather than just if it's coming from a user-defined custom title:

https://api.backdropcms.org/api/backdrop/core!modules!layout!layout.theme.inc/function/template_preprocess_block/1

```
  $variables['title'] = !empty($content->title) ? check_plain($content->title) : '';
```

I think when Layouts was originally written, I may not have noticed the D7 difference between `$block->title` (the user defined value) and `$block->subject` (the printed block title).

**Comment by quicksketch** [comment]
The PR looks good with it's basic changes, but it introduces a vulnerability that Custom Blocks do not have their $block->subject value sanitized. See how my `<xss>` tag is not escaped when output?

![selection_020](https://cloud.githubusercontent.com/assets/100206/12072868/28451072-b0af-11e5-93b9-0495814e699f.png)

![selection_019](https://cloud.githubusercontent.com/assets/100206/12072870/3cac33b0-b0af-11e5-8a4a-6381f46abf36.png)

So we need an additional `check_plain()` in `block_block_view()`.

**Comment by jenlampton** [comment]
Just patched that hole and tested again, looks good to me now. Could use another test.
