### ISSUE TITLE
First Impressions and Feature Requests

### ISSUE THREAD

**Issue by stephit** [backdrop/backdrop-issues#1359]
_(I guess I am not able to tag my issues as I am not a formal contributor - but this should be added as a Feature Request.)_

Let me preface this by saying that I have been using Drupal since Drupal 5. I am primarily a Site Builder, and although I can get in and hack some code on occasion, it is not my strong point. 

I was at my first Drupalcon in Austin last year. I was absolutely appalled at the direction Drupal was taking - clearly the people in charge have seen dollar signs, and the focus is on promoting big business, cheap foreign labor, data mining, and centralization of the web - all the while crowing about how cutting edge and cool they are. _eyeroll_

I had since heard about Backdrop and have been periodically checking into the project with some interest. I do run Wordpress on a few of my personal sites, but it is still primarily built around blogging. It also has major security issues.

I had a small Drupal 7 site that desperately needed a rehaul, and since I was basically redoing the site, there was no reason to stay with Drupal 7 as it is on its way out. I had to consider whether I'd go with Drupal 8, start over in Wordpress, or give Backdrop a try. I was happy to see that Backdrop is finally in a state where it can be used for a live site. I performed the upgrade from Drupal 7 last night, and so far have been favorably impressed.

What I like, in no particular order:
- THANK YOU for finally fixing that ridiculous waste of folder space where Drupal would have "core" modules and themes in the top level directories, but you had to dig way down into sites/all to install your custom themes and modules. 
- I was very confused at first what happened to blocks, and then I figured out how they fit in with Layouts. Layouts is GREAT! So far, fairly easy to use. 
- The admin interface is well done. You kept enough of Drupal 7 to make it easy to get around, while improving the general UI, and you organized things so they are fairly easy to find. It's more modern while not being dumbed down. Good job.
- I am very happy to see my existing Views ported without problem (from what I can tell so far).
- Upgrade path from Drupal 7 was fairly easy, although I had to sacrifice a lot of modules in order to do it. (I am just not savvy enough to be converting modules myself.)

Here are some of my initial suggestions/feature requests:
- Put a link in the Blocks menu (or at least on the Blocks page) that directs people to Layouts where they can add blocks. This may be redundant but for the average user used to Drupal it is very confusing at first.
- More/better default themes, along with theme creator engine. Bartik is great but it is very 2003. Come up with two or three really nice, lightweight, attractive and RESPONSIVE themes that come in Core so that small businesses can just pick something easily and customize it. Add a theme engine creator where you can change fonts, colors and corner styles. Along with layouts, this would be so helpful for small businesses!

Yes, it's great to have robust frameworks for developers but also have some out-of-the-box themes and customization options for the more casual users and small organizations. 
- UBERCART UPGRADE PATH!! I am a legacy Ubercart user from way back to Drupal 6 on another personal site I have. I dread the day that Drupal 7 is no longer supported. How on earth am I going to convert that site over to Drupal 8? I would LOVE for Backdrop to have an Ubercart module port. I realize that Ubercart is a hot mess, but I'm sure I am not the only one who has a home business e-commerce site that would be a bitch to rebuild from scratch. Backdrop also should have a really nice "optional core" shopping cart for small business. 

Of course, as you might expect, my biggest concern is whether Backdrop will get enough momentum to generate a wide enough developer base and adoption rate. 

Right now the modules offered are limited. I actually, in some respects, like having fewer modules to deal with. I like the idea of having less bloat. And since Backdrop core has many improvements, it's nice that I don't have to use so many modules for basic things. But I am still concerned about long-term functionality. 

For some of my client websites, there's no way they could go from Drupal 7 to Backdrop at this point without a huge amount of time/money spent on module ports. Worse, I work with one client who has a major website running Drupal 6! I'm not sure how Backdrop is going to help people who are still on Drupal 6.

All that said, overall, I am very impressed so far and like the direction. Certainly Drupal needs some competition right now. The egos over there are overwhelming. 

Thank you for helping out the little guy (and gal)! :-D

**Comment by biolithic** [comment]
Hi ,

Thank you for the nice comments and comments on feature requests. Layouts
is nice!

I remember fixing Ubercart modules in 6, and Commerce modules in 7.

If you are up for tinkering with new things in E-Commerce, you can try a
demo of "Basic Cart Plus" module in Backdrop.
*http://goo.gl/On9hdQ <http://goo.gl/On9hdQ>*

It's not done, rough edges to smooth up, etc... but I believe the site is
just Backdrop, a contrib theme out of the box, and that module.  I don't
have unlimited time to do everything, if I have time on a weekend, I'll
work on it.  Hopefully, I get some time to make it stable by the end of the
year unless people really hate it.
username: testadmin
password: testadmin
credit card #: 4242424242424242
credit card date: 12/15
The module just comes with a configuration page that says, "Check the
content types you want to sell" and "Which types are member/subscription
only?" along with another page for admins for entering in API keys.  It's
just a basic cart that overlays your nodes and then doesn't overlay them
when you uncheck the boxes.
If you are ESPN or Crate&Barrel, I highly suggest against using it.  But
hopefully someone will find it easy to use when I get done with it.
There are other e-commerce/cart type modules in Backdrop eco-system I have
started porting but I don't have the time to support them/they suck, so
when I get the time I will pull them off so as not to confuse people.

On themes, do you have more ideas on types of themes?  All themes are
responsive because of Layouts module?  Some Backdrop themes have Livereload
for the command line enabled so that you can type your CSS and see the page
update immediately.  I had on the calendar to get Zurb Foundation 6,
Semantic UI, and a feminine theme done before the year end but I probably
will only get to one of those.  Maybe we should work on something
different?  If Backdrop just shipped with Seven theme and had links to
modules, themes, and layouts pages, that would be OK with me because Seven
is pretty nice and people have their options they want.

Module porting really varies in time spent.  If the module is something
like JQuery functionality, content editing workflow, probably a half hour
or more?.  If the module does things to blocks, permissions, or site
architecture (like Organic Groups or Views), yes, the module will probably
take a while in my and other's experience.

Thanks for your two cents!

**Comment by Graham-72** [comment]
@stephit thanks for your very interesting and constructive post. Could you perhaps from your experience with Drupal give us a list of 10 modules that are not yet ported but would be of use to you? We could then think about tackling them in 2016. From my experience many modules are very straightforward to port, others present significant problems, and I guess that Ubercart would be a major challenge.

**Comment by quicksketch** [comment]
> I performed the upgrade from Drupal 7 last night, and so far have been favorably impressed.

w00t!! Nice one! We have test coverage on this and I've done it several times myself, but I'm thrilled to see a real site using the upgrade path.

> Put a link in the Blocks menu (or at least on the Blocks page) that directs people to Layouts where they can add blocks. This may be redundant but for the average user used to Drupal it is very confusing at first.

Great idea. Just a note at the top of the page would be adequate. Like: `Custom blocks may be reused throughout your site on different pages. To place a custom block, configure a layout from the Layouts configuration page.` (with a link on the last 3 words). Let's make a separate issue.

> More/better default themes, along with theme creator engine. Bartik is great but it is very 2003. Come up with two or three really nice, lightweight, attractive and RESPONSIVE themes that come in Core so that small businesses can just pick something easily and customize it. Add a theme engine creator where you can change fonts, colors and corner styles. Along with layouts, this would be so helpful for small businesses!

I thought for sure we already had an issue for making a new core theme but I can't find it. Absolutely agree. We started with the admin theme but we'd love a new front-end theme as well.

One great thing about Layouts is that the "hard" part of responsive themes is already done: the layout. Adding more responsive layouts out-of-box is another topic which we are considering in #698.

> UBERCART UPGRADE PATH!!

We feel you there. There are many modules besides Ubercart that may be hot messes, but they are used by thousands of sites. Porting modules is *usually* a fairly trivial task. Even though Ubercart is likely a monster, it should be fairly reasonable to port, at least much more so than to D8.

---

Thanks for all the excellent feedback and we're happy to hear that the experience has been mostly positive. I added you as a contributor so you can now tag labels/milestones/etc on GitHub. That process is somewhat-automatic but it's only granted to users who file pull requests at the moment. We're hoping it will be easier to streamline permissions in the future as GitHub evolves.

@stephit++ Welcome! :smile:

**Comment by klonos** [comment]
> I thought for sure we already had an issue for making a new core theme but I can't find it.

I follow the issue queue and I cannot remember any issue filed specifically for that. The only related issues I can think of and that could be of interest to @stephit are #1042, #842 and of course #698 that @quicksketch already mentioned in his previous comment.

> ...Add a theme engine creator where you can change fonts, colors and corner styles. Along with layouts, this would be so helpful for small businesses!

Related to fonts in core: #364

Finally, let me also welcome you to the party @stephit and as a fellow site builder, let me point you to one of my favorite issues here: #1178

**Comment by klonos** [comment]
...now, as for [Ubercart](https://www.drupal.org/project/ubercart), I was surprised to find out that there is actually a D7 version (I thought that everyone had moved to [Drupal Commerce](https://www.drupal.org/project/commerce) - clearly I was wrong) and even has a D8 pre-release. Both these projects seem complex and I believe would take some effort and time to be ported, but if you can spare the energy, you can give them a go. In the meantime, I would suggest [Basic Cart](https://backdropcms.org/project/basic_cart) as a Backdrop alternative too.

**Comment by sutibun** [comment]
> THANK YOU for finally fixing that ridiculous waste of folder space where Drupal would have "core" modules and themes in the top level directories, but you had to dig way down into sites/all to install your custom themes and modules.

monkey liked that too. Helped when installing Bd the first time

**Comment by klonos** [comment]
> I thought for sure we already had an issue for making a new core theme but I can't find it.

@quicksketch now that I think about it, maybe this (closed) issue is what you were referring to: #982 It being closed, no wonder neither you or me could find it :wink:

**Comment by docwilmot** [comment]
Either way, that issue still stands: we definitely need more themes. We got a bit done with [trying to change Bartik's default color](https://github.com/backdrop/backdrop-issues/issues/842) to differentiate ourselves a bit, but that issue is also stuck in the mud.

**Comment by Graham-72** [comment]
Yesterday I suddenly thought it might be a good idea to always have available a clone of Wordpress's current default theme, and today in #982 I read that @docwilmot has already done this with  https://github.com/backdrop-contrib/mero - I must give it a try.

If Backdrop included this out-of-the-box as at least an option, many newcomers would find themselves in familiar territory.

**Comment by stephit** [comment]
Re: Wordpress default theme - that is a great idea. I tried Mero, however, and it didn't seem very Wordpress-like to me. I'll have to compare it to 2015, maybe the header graphic that Wordpress usually includes is missing - which might point to one of the differences in general between Wordpress and Drupal themes - Wordpress themes usually come with more "design" elements in the form of header images and whatnot - things that the more casual user would tend to like. (I always found Drupal themes in general to be a bit unattractive out of the box.)

**Comment by biolithic** [comment]
@stephit , there is currently a general difference between themes in
Wordpress vs Drupal (or Backdrop).  See the following samples questions:

Wordpress:
"Is this theme responsive with three columns?"

Backdrop:
"Is this layout that I am using with the theme responsive with three
columns?"

Wordpress:
"Is this theme HTML5?"

Backdrop:
"Is this version of Backdrop core HTML5?"

Wordpress:
"Does this theme have a mobile menu?"

Backdrop:
"Is there a module I can install which gives my site a mobile menu? (yes)"

Wordpress:
"Does this theme have a header image?"

Backdrop:
"Can I choose a layout with a header region, and place a block with a
header image inside of it? (yes)"

Wordpress:
"Does this theme have widget X?"

Backdrop:
"Is there a module for widget X I can add?  Am I using a theme such as
Bootstrap or PureCSS which already contains CSS classes for widget X I can
copy and paste into my site myself?"

Wordpress:
"Can I get a green theme?"

Backdrop:
"Can I find the variables file in Sass with a variable that says
'PrimaryColor' or 'SiteHeader' and change it to the green I want?"

So currently (and throughout its existence), it has been more about blank
slate and plug in the pieces or connect the Legos than "Here is a site!
Well, to change anything...you need to use a different theme entirely...so
don't change anything on your site ever or the whole system will go down!"
The Unix philosophy of "do one thing well", "maintainability
matters"...yadda yadda

But to find a balance (and documentation) is key!

**Comment by klonos** [comment]
> If Backdrop included this out-of-the-box as at least an option, many newcomers would find themselves in familiar territory.

:+1: "You want to move from WP to BD, but are used to the admin UI? ...we got you covered!!!"

**Comment by biolithic** [comment]
I already made a module for April Fools Day to play joke on a co-worker
that turned his Drupal admin interface into a mock Wordpress admin UI:
View here: https://www.youtube.com/watch?v=ptqC4KpADO0

That's kinda silly...but the Mero theme is nice

**Comment by docwilmot** [comment]
> I tried Mero, however, and it didn't seem very Wordpress-like to me.

I confess this was done out of the need to build more themes, as per the issue it was mentioned in, so it is really Bartik with a fresh coat of paint, and may have some issues unresolved.

I like the idea of good quality ready-to-go themes being readily available. Drupal suffers, over the last few years, from a severe "base-theme" epidemic, which is a symptom of a more developer-centric culture, IMHO. I think if Backdrop is to appeal to our chosen demographic, we should lean towards the ready-to-go themes.

Though not necessarily in core. I agree a good theme or two out of the box, but the rest should be contrib.

I am still appealing to those who can, (looking at you @wesruv) to spend some time building some simple themes. I hear your comments @biolithic, but I think at this time, our need is to grow. Backdrop will not be attractive if people have to dig into SASS, HTML and PHP to make a little club site. So please, a couple of pretty, easy, enable-and-voila nice themes please!

**Comment by biolithic** [comment]
I hear ya Doc, it's just often been since the beginning of the internet:

"I'm going to build our website/app and it will be the best thing ever
because I know I can just sit down and click a few buttons and I know more
than any 'designer' or 'marketer' or 'developer' or 'company' or 'student'
 Who are these so-called 'professionals' with their '9-5 jobs'  What a
crazy idea, to work a job doing the same thing every day?"
"I'm going to use: Microsoft Frontpage or Word or Dreamweaver or GoDaddy
E-Z Magic Maker or Google Page Creator or Tumblr to just click all the
buttons and it will be done this weekend and everyone will love it.  All of
those products currently have bigger meetups than Drupal".
...one month later or more and still a broken site...
"I wonder if I should just hire an "expert" or "company" to get this done
today or this week.  And they know skills like Jquery, the command line,
and custom theming/module extending".
"I wonder if instead of making my own web service when my thing is
something else, I should just 'hire' Facebook, Youtube or Spotify to
advertise my thing I do for a cut of the profits.  I could do it all, but
its OK for them to "make money off me" because they do it better than I do
and I will reach more people with this collaboration.  And I need to
integrate them with my XYZ..."

...if hired, the software project actually gets done on time and makes
money and does the thing the client wanted immediately....

So, there needs to be both kinds of themes I think..

Someone like Jen Lampton can use her coding skills to make a client site in
Backdrop as well as a site builder can use an enable-and-voila theme.  A
developer that can use a tool like Drush or NPM well can make a site from a
mockup/PSD/wireframe much faster than someone who cannot, but there is the
option to use or not use such advanced options.  Plus, not all sites have a
PSD to follow or strategic branding/goal in mind or need productive
tools/time-crunch.

So I guess (possibly because I have lived mostly in the Bay Area and
Chicago, which have people that say, "I want a good dinner.  Let's go to
the restaurant and pay them to make it.  I'm sick. Let's go to the
hospital.  Our office needs cleaned -- hire some good cleaners.  Our org
needs to XYZ.  Let's hire an agency to 'get results'.  My startup idea is
whatever.  Let's hire a marketing guy and an engineer to make it/sell it so
I can instead run around fundraising for it.  The golf course needs mowing
and T-shirts for our event.  Call the landscaping and printing companies."
) I may be blind to some people's needs -- sorry.

So, let's have room for both options in themes!  Are you a Drupal shop?
You can do some Backdrop too.  Are you making a website yourself?  You can
use Backdrop.
(but we although we still need simple and nice themes, someone else can do
them).

**Comment by biolithic** [comment]
Hi, I made a site showcasing all the current contrib themes for Backdrop: 
http://dev-backdropthemes.pantheon.io

They're not all done, might find some visual bugs on all of them, etc... (which we can fix).
I just uploaded and enabled them onto this site with demo content.  I hope it makes it easier for everyone to start make opinions about "more themes" or "core themes" or whatever.

If you look at the site, thanks!

**Comment by wesruv** [comment]
@docwilmot @sutibun @stephit 

I wonder if you peoples (and whoever else would like to) could give me requirements you'd like to see fulfilled from a 'good contrib theme'. 

Because of my background (entrrrprrize!!!) I don't fully understand the use-case/needs, wrapping my head around what people would like to see would help me A LOT.

**Comment by wesruv** [comment]
One thing that could help is if you showed me a theme from Wordpress or Drupal that you have experience with and what you like/dislike about it.

**Comment by wesruv** [comment]
I'd also like to echo what some others have said and say thanks @stephit for this issue! It's very helpful and constructive.

**Comment by docwilmot** [comment]
Hi @wesruv I will give you a whole bunch: http://www.elegantthemes.com/gallery/page/2/

I don't think there is a simple definition of a good contrib theme as such, as requirements vary, but what I feel is that we need a strong selection of install-and-done themes. And most of all, they must be **pretty** out of the box. 

Like the Elegant Themes bunch: theyre very extendable, with lots of shortcodes and widgets and whatnot, but if even you don't need all that, when you install them, they look slick nonetheless. You do not need to fiddle with templates and CSS and override anything to make them look good. 

Thats what I think sells WP themes, and what we (and Drupal) lack.

Simple, simple, simple, but pretty. And I truly believe you could knock together 30 of those by tomorrow morning.

**Comment by sutibun** [comment]
> I wonder if you peoples... could give me requirements you'd like to see fulfilled from a 'good contrib theme'... Because of my background (entrrrprrize!!!) I don't fully understand the use-case/needs

@wesruv why certainly. Let me introduce you to the audience... in a vague and general way.

WHO
====
First, there **isn't** any one particular type of user Bd serves (e.g. The CMS only for lawyers) There's a wide range of use cases/needs. To help, I've tried to narrow down to the most likely and those that could think of on the spot.

1. **Personal websites**
  - *Needs*
    - Wants a look that differs from everybody. If style is the same as all other Bd sites, user might put up with it but will feel unhappy. Understandable as who wants to wear school uniforms every day. Everybody dresses themselves differently for a reason.
    -  Wants site to reflect owner's personality. (e.g. emo => dark colors or girly => pinkish )
    -  Wants to show the world what s/he is all about and why s/he is special.
  - *Types of pages tend to have*:
    -  portfolio
    -  blog
    -  resume
    -  about me
  - *One liner summary*: "It's all about ME!!!"
2. **Photographer/Artist**
  - *Needs*:
    - Wants to present photos in the best light possible. Design fail if fails to achieve this.
    - Wants an artistic look. No plain vanilla design.
    - Wants visitors to hire owner to take their photos.
  - *Types of pages tend to have*:
    -  photo gallery
    -  service details
    -  about me
    -  contact page
  - *One liner summary*: "It's all about WOWing visitors with my work"
3. **Small business owner**
  - *Needs*:
    - Wants to sell their product/service.
    - Wants a place where can promote their product/service
    - Wants to look authoritative, professional and trustworthy
    - Wants it done yesterday. No time to tinker around or learn complicated systems.
  - *Types of pages tend to have*:
    -  blog
    -  service details
    -  shopping cart
    -  about us
    -  in the press
  - *One liner summary*: "Show me the MONEY"
4. **Non-profit organization** 
  - *Needs*:
    - wants to further their cause
    - wants to raise awareness to their cause
    - wants to drive donation and participation
  - *Types of pages tend to have*:
    -  about us
    -  cause info
    -  education
    -  get involved
    -  donate
    -  in the press
  - *One liner summary*: "Let's get everyone INVOLVED"

WHAT
====

That's the audience broadly and briefly speaking. I mention all this because **it's good to keep this in mind amidst all the requirements ppl might throw**. Now we can create themes targeting each bucket but it's possible to create one theme that is usable for everybody imo.

The theme needs to be

- Suitable for mobile and desktop (Responsive/Adaptive design)
- Customizable so users can make it theirs. I'm thinking along the lines of
  - tweaking the color scheme
  - allow users to apply a two column layout (e.g. blog) or one layout column (e.g. sales or about us page) Related issues: https://github.com/backdrop/backdrop-issues/issues/1042#issuecomment-138017926 & #1164
  - unsure if feasible at the time but maybe adding a wide featured/hero image on top of a page.
- Easy to use. Get it up and running.
- the style/look needs to be applicable to many industries/purposes.

I've liked the Colihaut theme because I can see people gravitating towards it. I hope my vague ideas help a bit.

Related: #1361

**Comment by quicksketch** [comment]
It's been a year since this issue was filed. Thanks again @stephit for starting a helpful discussion. It's worth noting in the past year we've solved some of the requests (such as adding a new core theme that brings us a little out of the 2000s). If you have any new experiences to share, please let us know.
