### ISSUE TITLE
 tempstore_set() and tempstore_get() depend on database only

### ISSUE THREAD

**Issue by Gormartsen** [backdrop/backdrop-issues#1398]
Hi All.
I have a question about  [tempstore_set](https://api.backdropcms.org/api/backdrop/core!includes!common.inc/function/tempstore_set/1) and [tempstore_get](https://api.backdropcms.org/api/backdrop/core!includes!common.inc/function/tempstore_get/1).

Why do we use this functions to store data in database, instead of  [cache_get](https://api.backdropcms.org/api/backdrop/core%21includes%21cache.inc/function/cache_get/1) and [cache_set](https://api.backdropcms.org/api/backdrop/core%21includes%21cache.inc/function/cache_set/1) ?

[BackdropCacheInterface](https://api.backdropcms.org/api/backdrop/core%21includes%21cache.inc/interface/BackdropCacheInterface/1) allow to redirect cache to external tools, like memcached. I think it's good to keep it that way.

**Comment by quicksketch** [comment]
It's because tempstore data is not a cache. A cache can be cleared and regenerated at any time. The tempstore is not possible to regenerate, as it contains data made by a user. Examples of tempstore data:

- The current form state for AJAX-driven forms (e.g. file uploads on the node form).
- Any in-progress Views that are being edited or created.
- Any in-progress Layouts that are being edited or created.

If these were in caches, then clearing the cache would throw away in-progress work. Backdrop would be unable to save in-progress nodes, views, and layouts (among other things).

The tempstore implementation is similar to the CTools object storage. You're right this could be swappable, but it's not the same thing as a cache and isn't quite as good a candidate.

**Comment by Gormartsen** [comment]
Got it.
