### ISSUE TITLE
[UX] Change date field package

### ISSUE THREAD

**Issue by mikemccaffrey** [backdrop/backdrop-issues#1405]
We moved the date field into core in issue #254, which is great. Unfortunately, it is not listed with the rest of the fields under the FIELDS package on the module listing page, and is instead by itself in a DATE/TIME category.

Personally, I think it would make much sense to move this field down to be listed with all the other fields. Any objections?

**Comment by klonos** [comment]
This has been mentioned before in various places (but can't find the specific issues/comments right now). I think that there weren't any "objections" per se - just an explanation as per why. If memory serves well, the reason was that Date has a whole "ecosystem" of modules (think Views and views-related contrib modules) and once these got ported, it'd be suiting to go under the same "umbrella" category.

This would be solved if we implemented some sort of "tags" system for modules (inside their .info files that is). It would allow a single module to belong in multiple categories that people could search/filter by. If memory serves well, I think that @docwilmot was a big advocate of this whole notion of this sort of meta-data inside .info files ...and I am 100% behind him on that. The respective issue for implementing this feature is #119 if I'm not mistaken and this falls under the Project Browser initiative (that has stalled in d.org and we are close to getting done) where it would allow users to browse for contrib modules by category/functionality using faceted search (or something awesome like that).

**Comment by docwilmot** [comment]
> This would be solved if we implemented some sort of "tags" system for modules

https://github.com/backdrop/backdrop-issues/issues/37 actually, the oldest open issue! It would require #119. Summarized in https://github.com/backdrop-ops/backdropcms.org/issues/100

**Comment by klonos** [comment]
> ...but can't find the specific issues/comments right now

There you go! ...actually I intentionally referenced you cause I knew you'd jump in and chime.

**Comment by mikemccaffrey** [comment]
> the reason was that Date has a whole "ecosystem" of modules (think Views and views-related contrib modules) and once these got ported, it'd be suiting to go under the same "umbrella" category.

Well, none of the other Date/Time modules are in core, and only a small subset of sites would choose to use any of those contrib modules, so we probably not plan around them.

**Comment by Graham-72** [comment]
> Well, none of the other Date/Time modules are in core, and only a small subset of sites would choose to use any of those contrib modules, so we probably not plan around them.

I agree. Four of what were separate modules within the Drupal Date/Time grouping have been combined to provide Date in core for Backdrop (history is at issue #478). 

Three others are ported as contributed modules: Date Tools, Date all day, and Date Repeat. These support Calendar (not yet ported) as also does Date ical. I suggest we remove the Date/Time grouping and have a new one called perhaps Date Calendar ready for when that is ported perhaps early in 2016.

**Comment by klonos** [comment]
> I suggest we remove the Date/Time grouping and have a new one called perhaps Date Calendar ready for when that is ported perhaps early in 2016.

What should really happen if we are seeking a long-term solution is #37. That would effectively allow the date module to be tagged as "date", "time", "calendar", "field" and "what-have-you" thus allowing it to show up in any search for any of these groups.

**Comment by mikemccaffrey** [comment]
> What should really happen if we are seeking a long-term solution is #37

We can look at pursuing the long term solution suggested of adding tags, but that shouldn't stop us from making this one little tweak right now to the current system.

@quicksketch can you look at merging the pull request at: https://github.com/backdrop/backdrop/pull/1132

**Comment by jenlampton** [comment]
I agree, we need both #37 and this change, but this first cause it's easier :)

**Comment by quicksketch** [comment]
Thanks all. Merged into 1.x and 1.2.x.

**Comment by mikemccaffrey** [comment]
Whee... my first core contribution for Backdrop!

So when should we close these resolved issues? Is it safe to do it now that the pull request has been merged, or should we wait for the next release to go out?

**Comment by jenlampton** [comment]
The issue should close automatically as long as the PR says "Fixes [link-to-issue" in the body. Looks like that's not the case here so yes, closing :)
