### ISSUE TITLE
Using WYSIWYG (CKEditor) in a form

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#1421]
@quicksketch - please is it possible to invoke CKEditor for entering the text into a text area in a form?

I am wondering how to prepare an HTML email, hopefully to send via MimeMail.

**Comment by quicksketch** [comment]
It's not possible to make CKEditor appear on a `#type = textarea` element, because the configuration of the toolbar and plugins is done while configuring a text format.

So to solve this issue, we'd need to implement an issue that's been in-demand for quite a while in the Drupal-world: make it so that the `#type = filtered_html` has the ability to specify which text formats are allowed. e.g.

```
$form['text'] = array(
  '#type' => 'filtered_html',
  '#format' => 'basic',
  '#formats' => array('basic', 'full_html'),
);
```

Then you could simply make it a filtered_html element and only allow a single format (which would need to have CKEditor enabled).

**Comment by docwilmot** [comment]
Isn't this what [`'#type' => 'text_format'`](https://api.backdropcms.org/form_api#text_format) is for?

**Comment by Graham-72** [comment]
Thanks for information. I need to start looking into this soon because today I have achieved working versions of contrib modules Mimemail and Mailsystem on Backdrop. I need to do a bit more testing before being confident that all is OK.

**Comment by Graham-72** [comment]
I have just found that Views Send is providing a WYSIWYG text area. Interesting, and useful.
