### ISSUE TITLE
[UX] Move image styles to structure menu

### ISSUE THREAD

**Issue by mikemccaffrey** [backdrop/backdrop-issues#1423]
Should we perhaps move the `Image style` management to the `Structure` menu? That is where we are listing, editing, and adding all sorts of other system entities like views and layouts.

Then we can keep the things that are merely for configuration, like `Image toolkit` and `File system`, under `Configuration`.

**Comment by wesruv** [comment]
This++

**Comment by quicksketch** [comment]
Would love to hear others' ideas on this. I probably put it under Configuration in the first place as part of the [D7 initial issue](https://www.drupal.org/node/371374). It doesn't seem like it ever came up there. We did have quite an issue with breadcrumbs back then however, because Image Styles are one of the most deeply buried items in the whole menu by the time you're editing a particular effect on a style.

**Comment by klonos** [comment]
I understand how this makes sense from a dev PoV, but being mainly a site builder it feels right where it currently is. It felt natural to search for image-related stuff under config > media. My 2c.

**Comment by docwilmot** [comment]
Agree with @klonos. It isn't "structure" in the ordinary sense.

**Comment by mikemccaffrey** [comment]
> I understand how this makes sense from a dev PoV, but being mainly a site builder it feels right where it currently is.

Great, after years of being excluded from the core drupal community because I am primarily a site builder, now I am being accused of having the perspective of a core developer.

> It felt natural to search for image-related stuff under config > media.

Personally, it has never felt like the natural place to look for it and I am always trying to remember where to go. My first thought always is still to look for an Imagecache menu item.

**Comment by mikemccaffrey** [comment]
> It isn't "structure" in the ordinary sense.

How exactly would you define the difference between structure and configuration, especially now that pretty much everything in both menus are being saved to config files?

To me, Configuration is where you go to change the values in some individually defined variables, while the items under Structure are things that you add during the site building process that are referenced by other things that you add during the site building process, which is definitely the case with image styles.

**Comment by mikemccaffrey** [comment]
PS. I'd also love to see URL Aliases moved to structure, and maybe text formats as well.

**Comment by serundeputy** [comment]
@mikemccaffrey  #899 would keep URL alias settings where they are and adds them to content types, taxonomies, and users.   

so in a sense they are in structure that way.

**Comment by klonos** [comment]
> ...now I am being accused of having the perspective of a core developer.

I wasn't accusing anyone of anything, I was simply expressing my honest opinion as a site builder. My comment was not @mikemccaffrey as you can see.

> How exactly would you define the difference between structure and configuration, ...

"Structure" is home to things that can either be used as building blocks themselves (in the broader sense - not in the Drupal concept) or things that create building blocks and wireframes that can be (re)used to create pages (again, in the broader sense - not the Drupal content type).

"Config" holds things that would belong in the control panel or a system dashboard of an operating system if one makes that parallelism.

> ...especially now that pretty much everything in both menus are being saved to config files?

I'm pretty sure that the site builders that Backdrop has as a target audience (small site owners that do not even have a dev/staging environment) would never think in these terms since they most likely do not even know about or mess with config files ever. Don't mean to push anyone's buttons, but that's exactly what a dev would say.

**Comment by wesruv** [comment]
@klonos I seem them as structure because they effect the layout of the page (a lot!) and it has to do with structuring content. It's used in Manage Display settings and also Views constantly, which makes it feel even more like Structure.

Most everything else in Configuration has to do with 'background settings' that don't effect the appearance/layout/structure of the site at all.

I've always thought it felt alien in config. FWIW, I started as a site builder and grew into themer.

**Comment by docwilmot** [comment]
> @mikemccaffrey: How exactly would you define the difference between structure and configuration, especially now that pretty much everything in both menus are being saved to config files?

As an 'ordinary' user myself, and as @klonos suggests, the word 'structure' isn't technical. It's the structure of a building, or your cheekbones. Its how the webpage looks, not how the techie bits are organized. Its the things that affect the structure (architecture?) of my site. 

But yes, there's stuff in there that doesn't fit that view either (content types? structure?). So in fact it isn't a problem to me to move it there as it does in fact fit, according to your (not-a-site-builder-not-a-dev) vision. :smile:

**Comment by jdanthinne** [comment]
For me, the best fit for Image Styles is simply in Appearance, because that's what it is. Let's not create another debate but even Layouts could be there. It's all about rendering things.

**Comment by serundeputy** [comment]
The best thing for me would be to leave image styles where it is, but have a link to the `/admin/config/media/image-styles/add` on the Manage Display configure pane of the image field itself.

That is where for me when I'm configuring image styles if the one I need is not there I have to go make one, so if it was right at my finger tips that would please me.

**Comment by klonos** [comment]
> The best thing for me would be to leave image styles where it is, but have a link to the `/admin/config/media/image-styles/add` on the Manage Display configure pane of the image field itself.

:+1:

**Comment by jenlampton** [comment]
I have re-labeled this issue from [DX] to [UX] since it seems to be about changing the user interfaces and not about changing the APIs.

I am also not in favor for this change. There's nothing 'structural' about image styles, and keeping it under config makes sense to D7 users (initial target audience). Keeping it with Media settings will make sense to new users as well.

I agree with @serundeputy and love the idea of adding the link to direct users to the correct place. Le'ts contiue with that issue.
