### ISSUE TITLE
Slack channels? 

### ISSUE THREAD

**Issue by dariusgarza** [backdrop/backdrop-issues#1426]
Bringing Backdrop to [Slack](https://slack.com/) might open up the conversation to a wider audience. Slack is great for sharing ideas with rich media and provides access via [IRC](https://get.slack.help/hc/en-us/articles/201727913-Connecting-to-Slack-over-IRC-and-XMPP).

Not sure what it would take to monitor/maintain a slack team however. Thoughts? Suggestions? 

d.

**Comment by quicksketch** [comment]
I'm not sure, Slack is crazy expensive. Their free tier gets people involved, but then they have a devastating $7 *per user* minimum tier: https://slack.com/pricing

Even with the ~25 people we have hanging out in IRC all the time, we'd be looking at $175/mo. Slack also requires invitations to join a group (since after all, you're paying per-user), making it comparatively closed compared to other systems.

We could adopt it based on "we'll just use the free plan forever", but I don't like being subject to the whims of Slack deciding to limit the free plan more or push users into the expensive plans.

**Comment by docwilmot** [comment]
But 
> open up the conversation to a wider audience

Was this the aim for suggesting it, or to really benefit from what Slack has to offer? If it is just for "marketing" then why not go with the free version after all?

Note I know nothing of Slack, just thinking.

**Comment by dariusgarza** [comment]
Ah thanks @quicksketch I had no idea it was so pricey, nor did I realize it was invite only. Saddd pandas 🐼

**Comment by biolithic** [comment]
@dariusgarza is this an issue for meta/team/topic based chat?  For example, Backdrop has the all-in-one reddit, irc, gitter, github issue queue, twitter hashtag, facebook, linkedin and so forth.  

Possibly there is a need for single areas/channels to gab as much as wanted (without being "core issues/requests") on individual topics like performance, design/theming, contrib modules/integrations status, marketing ideas, site workflow, etc?  This may not be your intention, however.

I'm in 3 work Slack channels at the moment and they are good but I haven't set them up, so I nothing little of setting Slack up for a team.  My post is I guess less about Slack and more about projects use Slack to divide their talk up into "general", "design", "jobs", etc which can be created in any technology.

**Comment by mikemccaffrey** [comment]
Gitter is a basic Slack clone, and it has been a pretty good place for us to start chatting.

However it does have two limitations:
- we can only have one room for each repository, and we can't create arbitrary rooms
- there are no direct user-to-user messages

Let us know if anyone finds a platform that supports all the features of Slack, but is free (or low cost) like Gitter, and we can switch to that!

**Comment by quicksketch** [comment]
> Let us know if anyone finds a platform that supports all the features of Slack, but is free (or low cost) like Gitter, and we can switch to that!

I've been intrigued by MatterMost:
http://www.mattermost.org/why-we-made-mattermost-an-open-source-slack-alternative/

And then there are other SaaS options:

https://www.hipchat.com/pricing
http://www.ryver.com/ryver-vs-slack/

But I haven't tried any of these solutions. The primary reason why Slack would be positive would be because it's so popular. People already have it on their computers and phones. I personally have 4 different Slack organizations that I join every day. But ultimately, their pricing model and invitation system make it unsuitable for any kind of open community.

**Comment by sutibun** [comment]
Just found "Let's chat". It's free but dunno much about it. http://sdelements.github.io/lets-chat/

**Comment by dariusgarza** [comment]
Of all the proposed options, perhaps Gitter would be a good place to start. I like that it's already associated with Github so we don't have to belabor the community with something completely foreign. Sure there's a few limitations, but I think it's worth trying to workaround them for now. Gitter is likely to evolve over time, and even if it doesn't, we can always check out another service. 

Gitter also supports images, avatars, code samples, etc, which I think will help create a more engaging experience overall . Perhaps I'm in the minority, but I've never made a habit out of IRC. There's definitely room for a complimentary communication tool :) 

Anyone else wanna see what Gitter has to offer? cheers, d.

**Comment by jenlampton** [comment]
Closing this issue since we have a Gitter: https://gitter.im/backdrop/backdrop-issues

But FTR, I tried to make us a slack too: https://backdropcms.slack.com/messages
Only, I never figured out how to make it public :(

**Comment by klonos** [comment]
The problem with Slack is that the message history goes away after a few days (a week I think?) if you don't have the paid/enterprise version.

Gitter has better integration with GitHub too, so that's a plus.

**Comment by laryn** [comment]
From Gitter a few months back:

> @herbdool : "Sorry to stir the pot again about chat app choice. I'm really liking the sound of https://zulipchat.com/for/open-source/. I haven't tried it but sounds better than gitter. Integrates with GitHub account, can haz dragonbot, has channels and topics (for easier asynchronous communication)"

Of note:

> Zulip Cloud Standard is free for open source projects and affiliated institutions.

**Comment by stpaultim** [comment]
I think we should move the current discussion to: https://github.com/backdrop-ops/backdropcms.org/issues/587
