### ISSUE TITLE
Export reusable custom blocks to configuration

### ISSUE THREAD

**Issue by mikemccaffrey** [backdrop/backdrop-issues#1428]
In issue #1099 @docwilmot has started creating a custom text block that can be added to layouts and are stored in the layout configuration. However, I think we should still retain the current ability to make simple reusable custom text blocks, but save them to configuration so they can be created along with layouts in a development environment and then be deployed together to production.

I think that these reusable custom blocks are the true successors to the current custom block functionality. Since any existing blocks people have created have not been fieldable, they would likely not be intended for the applications proposed in #100. So instead of moving the current custom block list from structure to content, as proposed in #1276, I think we should instead convert the existing block module to store its reusable blocks in configuration.

Once the single-layout custom blocks are created in #1099, we can look at allowing users to convert between the two types. Perhaps we can have a checkbox when creating or editing a single-layout block in the Layout UI asking if the block should be reusable, and if that is checked, the block is saved to its own config file and it becomes available to add when editing other layouts.

**Comment by docwilmot** [comment]
So if we create a non-reusable Text Block, it saves content to the `layout.layout.my_current_layout` config.

If reusable though:
- pick the first layout where you want the block and create a Text Block as usual
- select `[x] Reusable`
- saves content to a `layout.block.my_block` file
- saves a reference to this block in the `layout.layout.my_current_layout`
- the block then appears in the block list (in other layouts) as `Reusable Block: My Custom Block`

Is each `Reusable Block: My Custom Block` now also independently editable?
How do we manage deletes and updates? Hunt down the first one and edit it? 
What happens if you delete `my_current_layout`?

OR:
- To create the first instance of `Reusable Block: My Custom Block` instead of creating it in the Layout UI with the "Add block" button, we use an independent UI, like the current 'Custom Block'. Then would need to go to the Layout UI to place it. That would simplify other CRUD issues with these types of blocks.
- save as `block.my_block`
- they're always reusable

But this is essentially same as what we got now.

I think the second scenario is likely better.

**Comment by mikemccaffrey** [comment]
> Is each Reusable Block: My Custom Block now also independently editable?

No, I'm thinking that if the block has different content, then it is a different block, and should probably be created independently. 

> To create the first instance of Reusable Block: My Custom Block instead of creating it in the Layout UI with the "Add block" button, we use an independent UI, like the current 'Custom Block'.

I would actually use the exact interface that the current custom block has implemented, and just do a module update to make it save the blocks in config instead of code. This seems the dirt-simple solution for getting this done. And if other people want to make some new fieldable block entity in the future, they can create a new module to implement it, since it will likely be radically different.

> To create the first instance of Reusable Block: My Custom Block instead of creating it in the Layout UI with the "Add block" button, we use an independent UI, like the current 'Custom Block'. Then would need to go to the Layout UI to place it. That would simplify other CRUD issues with these types of blocks.

Yes that is a good starting point. Let's get the current reusable custom blocks to save to configuration here, and add the single-layout custom blocks in #1099, and then once those are both established we can look at creating a workflow for a user to easily convert a single-layout block into a reusable block within the layouts interface.

**Comment by mikemccaffrey** [comment]
I've made a bunch of progress on switching over the existing block module to save its settings to config:
https://github.com/backdrop/backdrop/compare/1.x...mikemccaffrey:1428_custom_block_to_config

The tests are currently failing, which is not surprising, so I need to edit them to accommodate the new settings, which replace the numeric bid index with a machine name in delta.

And then once those are passing, I will work on adding an update function to the install file to convert existing database block content into config files.

**Comment by jenlampton** [comment]
I don't think there's any point in switching the current block module to save content to config. Those blocks are content, and should be saved in the database. Adding a "Text block" is the right way to go if you want that text stored in the layout config (or their own files).  Changing the way current blocks work is too much API change. Let's add new features instead.

**Comment by jenlampton** [comment]
Closing since this is likely not going to happen in core.

**Comment by mikemccaffrey** [comment]
Um.... this really does need to happen in core. Even if we create a fieldable block entity in the future in #100, we still want to have simple text blocks that you can easily add to layouts. And even if we create single-layout blocks in #1428, we still need a system to store reusable blocks in configuration that can be used across multiple layouts.

And since any blocks that are currently stored in the block table don't have fields, they are probably not the advanced types of content that need them, so we should probably migrate them to the layout-based custom text blocks. And since there is currently no way for users to indicate that a block is only for use on a single layout, any existing blocks therefore need to remain as reusable custom blocks.

Because of all this, it seems clear that converting the existing block system to using configuration is a smart course of action, even while we are pursuing the other two block initiatives. And it should probably be done as quickly as possible, since the current development workflow of having to create blocks on live and syncing the whole site before you can add them to layouts on dev is a huge pain in the ass when building a backdrop site that properly stores its config in version control.

**Comment by jenlampton** [comment]
I'm not sure I follow your reasoning, but it's not the path we're taking for core. There are three simple things we'll do for core that are feature requests, that we can add in the 1.x cycle.

1) add a Text block.  This is already under way in https://github.com/backdrop/backdrop-issues/issues/1099 and can be done in 1.x (hopefully in 1.3.0)
2) add a checkbox to the text block that makes it reusable (and stores it's text in a separate config file from layouts.  This will be a follow-up to https://github.com/backdrop/backdrop-issues/issues/1099. I'm not sure there is an issue yet for that, but if not, we should make one. This and can be done in 1.x.
3) in Backdrop 2.x, the "Custom block" (or content block) as it is now will become a fieldable entity. There's no point in taking the content out of the database now, only to move it back into the database in 2.x.

Closing again.

**Comment by mikemccaffrey** [comment]
@jenlampton, you convinced Datera to use Backdrop so we'd have another real-world test of Backdrop, and to me it has revealed this issue as a major flaw of our development workflow. Custom panes in panels are exportable to features in Drupal, and we are taking that functionality away in Backdrop.

> in Backdrop 2.x, the "Custom block" (or content block) as it is now will become a fieldable entity. There's no point in taking the content out of the database now, only to move it back into the database in 2.x.

I'm not sure how much you've looked into the code for the existing block module, but the architecture and database scheme is not written in a way that has any overlap without entities are defined and managed. The whole module will likely need to be rewritten from scratch, and an entirely new database table would need to be created.

**Comment by quicksketch** [comment]
I hadn't been a fan of this suggestion when it's been mentioned in the weekly hangouts and while reading through this issue. I hadn't really been buying into the idea.

*However*, after taking a look at @mikemccaffrey's code at https://github.com/backdrop/backdrop/compare/1.x...mikemccaffrey:1428_custom_block_to_config, I think I'm actually more in favor of this approach than making the current block module into an entity (which is what I had expected up until this issue was opened).

Reasons why:

- Blocks right now are assumed to be limited to a small number. We list them all individually on the Add Block dialog. There is no search or pager support on the blocks listing page. If these were intended to be content, we'd only list a single block on the block list and support situations where there were thousands of blocks rather than dozens.
- There is no Views support for listing blocks (unlike other entities).
- There are no "block types" making it so that using blocks for a slideshow or some other non-URL content situation is not very practical. You'd want different types for specialized situations. Even if we did support fields on blocks, we'd also need block types.
- We currently position blocks under structure (although @jenlampton is suggesting that be changed in https://github.com/backdrop/backdrop-issues/issues/1276). And though it easy to change that, the other parts of blocks.

I think @mikemccaffrey is right that they really aren't intended to be entities as they have been used historically. We are much, much closer to storing blocks as configuration (as Mike's code has shown) than we are to converting blocks to entities. Even after we implement the blocks-stored-as-config in https://github.com/backdrop/backdrop-issues/issues/1099, the "reusable" aspect will still need to be handled. If we take the approach suggested here, it will position us well to administer those reusable blocks. We'll already have an API for creating/saving/deleting them, as well as a UI. Checking the proposed "Make reusable" checkbox would just save a standard custom block.

Also exciting, "Custom block" would mean just *one thing*. Regardless, it'd always be stored in config. It'd always be editable within the Layout UI. You could create new blocks within the Layout UI. We'd avoid an entire set of namespace problems by taking this approach.

If we were to implement a URL-less entity type, we could name it something else entirely. It's not a "block" any more because it wouldn't be limited to a place within a layout. You could have multiple types of them and of course they would be fieldable. But whatever we call them, they wouldn't really be "blocks" any more. Or we could just give up on the idea of some URL-less entity type and implement a rabbit hole like module, as suggested in elsewhere (don't we have an issue for that also?)

So much to my surprise, I'm more in favor of this approach than I ever had been before. I think Mike is on to something and it's worth continuing the work here.

**Comment by quicksketch** [comment]
The one question I'm still puzzling about though is whether removing the database table would break our backwards-compatibility policy. All the APIs stay exactly the same, but obviously the table would no longer be queryable. I couldn't find any modules that would be hindered by this limitation. Even modules like https://www.drupal.org/project/views_block_area (assuming they were ported at some point) wouldn't have an issue with the blocks being config instead of in the database. I couldn't find any contrib modules that actually exposed blocks to Views in the same way Nodes and Users are.

**Comment by jenlampton** [comment]
> Custom panes in panels are exportable to features in Drupal, and we are taking that functionality away in Backdrop.

No, those are all in contrib solution  in Drupal. Any of those things could still exist in contrib in Backdrop too. We are not taking anything away.

Arguing with @quicksketch about this now... :)

**Comment by jenlampton** [comment]
Okay - so I'm coming around on this issue. The one thing that still freaks me out is dropping the whole comments database table, because that's a huge, huge change for a mid-cycle release! I think if we are going to do this, we need to do it now because the longer we wait the more we increase our risk. (Assigning milestone 1.3.0).

**Comment by quicksketch** [comment]
The code has some minor whitespace/standards issues but overall looks pretty solid to me. Implementation-wise, the only thing that jumps out at me is:

```
$config = config('block.' . $block['bid']);
```

These should probably be namespaced under `block.custom.[delta]`, in the event that we need a `block.settings` or similar, we don't want it to collide with a machine name of `settings` specified by a user.

**Comment by jenlampton** [comment]
Before we were trying to solve the "Blocks are content" UX problem by taking something we already have (blocks) and turning them into content by 1) changing their name (blocks to custom blocks) 2) moving them(structure to content), 2) changing what we do to them ('configure' to 'edit') and 3) someday making them fieldable entities. (which fwiw, is what Drupal 8 did)

Instead, we are now going to say "Screw blocks as content!" Blocks are just text!! Blocks have always been just text, and just for administrators, and that's how they'll stay. Later on, we'll add something else that is content to solve the UX problem (and we can call that thing something other than `Block`, win-UX-win?).

This makes our path forward look like this:
1) this PR, which stores text blocks in config instead of in a database
2) @docwilmot's PR over at #1099 which will allow people to add new Text blocks from the Layouts UI
3) A new change which will add a new 'Make this block reusable' checkbox to the Text block form, that will join the two together.
4) Add a pageless-node / fieldable doodad to core (something like bean or eck)

As an added benefit, that #4 which had always been slated for Backdrop 2.x now becomes a feature request and not an API change, and we can do it in the 1.x cycle :)

**Comment by docwilmot** [comment]
I don't know about anyone else, but this feels very much like win-UX-win to me. Smooths a few irritations very well. 

> Add a pageless-node / fieldable doodad to core (something like bean or eck)

This will end up being a bit like [ECK](https://www.drupal.org/project/eck) in core.

**Comment by mikemccaffrey** [comment]
> @quicksketch: The one question I'm still puzzling about though is whether removing the database table would break our backwards-compatibility policy. All the APIs stay exactly the same, but obviously the table would no longer be queryable.

Well, we promised that the API would stay the same, but I don't think we've made any such commitments to keeping the data storage the same. In fact, we might want to explicitly say that we are not going to do that, in order to discourage people from bypassing api functions and accessing the data owned by other modules directly.

> @jenlampton: The one thing that still freaks me out is dropping the whole block_custom database table, because that's a huge, huge change for a mid-cycle release! I think if we are going to do this, we need to do it now because the longer we wait the more we increase our risk. 

Yeah, deleting any database tables really freaks me out as well. I probably would not have even proposed it, had the same approach not already worked so well with converting the other core structure module to configuration. Let me know if you have any ideas of how the upgrade process might go horribly wrong so we can do more thorough testing!

> @quicksketch: These should probably be namespaced under block.custom.[delta], in the event that we need a block.settings or similar, we don't want it to collide with a machine name of settings specified by a user.

Good call. I will make that change and update the pull request.

> @quicksketch: The code has some minor whitespace/standards issues but overall looks pretty solid to me. 

Whoops, can you point those out so I can address them as well?

**Comment by mikemccaffrey** [comment]
Okay, updated the pull request with the new config prefix, and I cleaned up some whitespace differences. Most of them were lack of space between if( and foreach(. Let me know if I missed anything.

**Comment by mikemccaffrey** [comment]
Making the field title changes requested by @jenlampton in #1340:

    Admin label
    Display title
    Block content

**Comment by quicksketch** [comment]
PR at https://github.com/backdrop/backdrop/pull/1165 looks ready for merge to my eyes.

@mikemccaffrey if you would rebase on top of 1.x and squash all the commits together, that would save me a small amount of work, but I'm quite capable of squashing them if needed. They rebase without any trouble. Some docs on that if needed here https://backdropcms.org/develop/pull-requests#clean-requests

I think we're all in agreement at this point it's a good idea and beneficial from a UX/DX stand-point. If no one has anything else to add, we can merge this tomorrow or Thursday.

**Comment by mikemccaffrey** [comment]
Okay, @quicksketch, I did the rebase and squash, and also removed that date.info change that snuck in from the other ticket I was working on. Let me know if you need anything else!

**Comment by quicksketch** [comment]
Merged in the PR at https://github.com/backdrop/backdrop/pull/1165 into 1.x!

Thanks @mikemccaffrey for opening our eyes to this excellent solution. You faced down a fair amount of skepticism but conquered in the end. I'm excited to see this tied into the custom text block issue over in https://github.com/backdrop/backdrop-issues/issues/1099.

Change record written up at https://api.backdropcms.org/node/43558.
