### ISSUE TITLE
Notice: Undefined index: quantity in views_plugin_pager_full->options_form() (line 90 of views_plugin_pager_full.inc).

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1435]
I got this while playing with the available options when filing #1430:

`Notice: Undefined index: quantity in views_plugin_pager_full->options_form() (line 90 of \core\modules\views\plugins\views_plugin_pager_full.inc).`

Happened when I clicked on the link with the options part **while the pager was set to mini** (notice how the error points to `views_plugin_pager_full`), after the "Mini |" part (`?q=admin/structure/views/nojs/display/my_view_name/page/pager_options`)

**Comment by klonos** [comment]
Steps to reproduce:

1. Edit any view.
2. Click the "Display a specified number of items" link under the pager options section and change the setting to "Paged output, mini pager". Hit "Apply (all displays)".
3. You are taken to the pager options and the error message is shown at the top of the dialog.

**Comment by klonos** [comment]
Long-standing respective issue in d.org: https://www.drupal.org/node/903466

...despite the issue title matching the error I got, the d.org issue started with this error reported:

``` Notice: Undefined offset: 0 in theme_pager() (line 322 of \includes\pager.inc).```

It is marked as fixed for D8 and set to be ported for D7.

Another d.org issue is this: https://www.drupal.org/node/2466495

...this one was closed as "works as designed" and reports that another fix for [Views PHP](https://www.drupal.org/project/views_php) solved the issue ??? The issue they point to is https://www.drupal.org/node/2276165 which in turn was closed as a duplicate of https://www.drupal.org/node/2123315

Me lost :expressionless:

**Comment by Gormartsen** [comment]
@klonos I can confirm it here.

I created view with mini pager and on configuration page got this message

Error happen here:

https://github.com/backdrop/backdrop/blob/1.x/core/modules/views/plugins/views_plugin_pager_full.inc#L90

I assume that at first execution there is no such a option.

Probably some typo or something like this.

**Comment by klonos** [comment]
...I have reopened https://www.drupal.org/project/views/issues/2466495 and added STR to the issue summary.

**Comment by BWPanda** [comment]
I added acomment to the PR, but will post it here too:

Why not just remove these lines: https://github.com/backdrop/backdrop/blob/1.x/core/modules/views/plugins/views_plugin_pager_mini.inc#L29-L31 ?

The problem is that we're unsetting default values that the parent form sets, which are needed when later calling the parent form. If we don't unset the default values, the parent form canuse those as expected, but then we unset them from the child form where they're not needed. That seems simpler to me and possibly less error-prone...

**Comment by indigoxela** [comment]
Seems like we're not doing a better job than Drupal regarding that bug. :disappointed: 

Is there any chance to revive this issue? Just saw the "quantity" notice again, and am disappointed, that it's still not fixed.

**Comment by stpaultim** [comment]
This is now the oldest issues still active on the bugfix milestone. I confirmed the problem (again) and verified that the PR fixes the problem (again).

**Comment by indigoxela** [comment]
Sorry, have to set it back no needs work, because of the wrong variable in function options_form().

**Comment by indigoxela** [comment]
And I just verified again (locally), that the change in function options_form() isn't actually necessary.
@klonos are you able to do work on this PR today?

**Comment by klonos** [comment]
Having a look now 👀

**Comment by klonos** [comment]
@indigoxela I've reverted the change in the `options_form()` function. I have also added an inline comment above the `$options['quantity'] = NULL;` line, in order to avoid reverting this change and regressing this (the respective code in views 7.x might puzzle people working in cross-ports in the future).

**Comment by indigoxela** [comment]
Now we need someone to test and set the "works for me". Then I can finalize my review and RTBC it.

(Seems like we have another "random buddy" - but that's unrelated here)

**Comment by klonos** [comment]
> Seems like we have another "random buddy"

Added #5226 to the #1478 meta 😉

**Comment by BWPanda** [comment]
In my defense, I asked a question in October 2020. It wasn't answered until August 2021. So it's only been a few months since then, and there's nothing to indicate I need to do anything further. I asked a question, it was answered.

@indigoxela I understand that you're wanting to see this issue addressed quicker, but I don't think trying to guilt-trip volunteers into working on it is the way to go...

Yes we can all spend a few minutes on it and get it done, but a few minutes on different issues adds up quickly. If you personally have the time and inclination to see this fixed, I don't think @klonos would bemoan you making your own up-to-date PR based off his.

**Comment by indigoxela** [comment]
> I don't think trying to guilt-trip volunteers into working on it is the way to go...

Sorry, that wasn't my intention. It happened because of my frustration. A simple problem, a simple fix and no progress - that's challenging for me.

I don't think there will be any better progress, if I provide an alternate - actually the same - solution. Then nobody will test/review it and we're stuck again.

I'll try to be more patient, doing nothing until anyone else picks this up and advocates, carrying it across the finish line. At the risk that this will never happen.

**Comment by klonos** [comment]
Sorry guys, it's my fault 😓 ...it would help if people would either ask questions in the issue queue, or leave a comment in the form of "I've left some feedback in the PR". I know that I should be watching my email notifications, but for better or worse I don't 😓 

I'm working to rebase this now, and fix any issues...

**Comment by klonos** [comment]
...to answer some of the points above:

> ...I don't think @klonos would bemoan you making your own up-to-date PR based off his.

@BWPanda is absolutely right - for this and any PR I have filed, if you see me not responding, ping me on Zulip, and if I don't respond in a timely manner there, then by all means either file a completely new PR, or base a new PR off of mine 😄

**Comment by klonos** [comment]
Sorry, had to go away while the tests were running. This is ready for review again.

**Comment by BWPanda** [comment]
I reviewed the code and made a small request.

I'd like to play devil's advocate though and ask: have we looked into what was trying to access this index for it to throw an error about not finding it? Perhaps the bug lies there instead...?

**Comment by klonos** [comment]
> I reviewed the code and made a small request.

Fixed. ...but happy to remove that link altogether if you believe that it provides no value and that the inline comment is enough to explain the entire issue behind the odd choice of using `NULL` instead of `unset()`.

> I'd like to play devil's advocate though...

Be my guest 😅 ...I don't think that I know how to get to the bottom of this.

**Comment by jenlampton** [comment]
I've both tested the PR in the sandbox, and reviewed the code. I don't think the link to the GitHub issue is necessary @klonos  and I would prefer not to add links to issues into the codebase, the explanation there is enough. However, I do'nt think removing that URL should hold up this issue any longer -- so RTBC. 

I'm going to go file a PR against you PR @klonos, and if you are available to merge it, great, if not, let's just get this one done :)

**Comment by quicksketch** [comment]
Thanks everyone for their work and patience on this issue. I've merged the extremely simple fix at https://github.com/backdrop/backdrop/pull/3261 into 1.x and 1.20.x. Thank you @klonos, @indigoxela, @BWPanda, @Gormartsen, @jenlampton, @stpaultim, and @laryn!
