### ISSUE TITLE
Editing a user role label results in a new role being created with no machine_name

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#1446]
When here: admin/config/people/roles I attempted to change the label of a role. After saving a new role shows up with the label I created but the original role also remains. The new role doesn't appear to have a machine name and shows up as this file: user.role..json

**Comment by klonos** [comment]
I confirm this one. Contents of the ```user.role..json``` file:

```
{
    "_config_name": "user.role.",
    "name": "",
    "label": "test role change",
    "weight": 4
}
```

**Comment by klonos** [comment]
...the role cannot be edited/deleted.

**Comment by gifad** [comment]
The current (edited) role is passed from the form to the submit callback thru the $form_state argument, which it's declared by value...
Fixed by changing user.admin.inc, line 812, from : 
`function user_admin_role($form, $form_state, $role) {`
to : 
`function user_admin_role($form, &$form_state, $role) {`

**Comment by klonos** [comment]
This was fixed in https://github.com/backdrop/backdrop/commit/d629605b3e53ef9d6087523a5a6967146ba68c5f#diff-c8ee76d3d3f3295ac2b3b420545c95d5 (as part of fixing #1386)
