### ISSUE TITLE
Changes to Interface translations directory configuration are not saved

### ISSUE THREAD

**Issue by dboulet** [backdrop/backdrop-issues#1447]
The locale module adds a configurable setting on the File system page for specifying the Interface translations directory. Changing this setting and submitting the form has no effect, the setting is always reset to the default. The only way to change it is through settings.php.

This should either be changed so that the setting is saved in the JSON configuration file, or the settings form input field should be removed, since it’s misleading.

**Comment by klonos** [comment]
Totally forgot about this issue here. What was the purpose of providing an option for the translations directory again? Why can't we hard-code it instead (the way we have `/themes` and `/modules` directories)?

**Comment by dboulet** [comment]
I think that this is simply just a leftover from Drupal 7, where the setting was saved in the database as a variable.

**Comment by klonos** [comment]
I am all for removing this, BUT if we do, then...

1. What is the default? Is `files/translations` defined as a default elsewhere?
2. Does placing .po files under `files/translations` still work (do these files get picked up and translations imported properly)?
3. Do we have this documented so that people know where to put their .po files?
4. Why was there an option for this directory in the first place? I mean was there any valid use case where the directory needed to reside outside the `/files` dir?

**Comment by quicksketch** [comment]
> What is the default? Is files/translations defined as a default elsewhere?

'files/translations' is defined in [`install_find_translation_files()`](https://api.backdropcms.org/api/backdrop/core!includes!install.core.inc/function/install_find_translation_files/1)

> Does placing .po files under files/translations still work (do these files get picked up and translations imported properly)?

Yes, and we have a test to confirm it as well in `InstallerLanguageTestCase`.

> Do we have this documented so that people know where to put their .po files?

You can click on the link from the installer to see the documentation:
![selection_135](https://cloud.githubusercontent.com/assets/100206/15259646/1de63c92-1918-11e6-949f-e332316b5ba9.png)
![selection_136](https://cloud.githubusercontent.com/assets/100206/15259647/2160e782-1918-11e6-86c5-3bc9fd8d57ee.png)

However obviously this still points to drupal.org. We should make a documentation page of our own that we can link to. Other than being Drupal rather than Backdrop, the documentation still mostly applies.

> Why was there an option for this directory in the first place? I mean was there any valid use case where the directory needed to reside outside the /files dir? If so, do we still provide a way for people to override the default?

Leaving it as an option only definable in settings.php seems completely acceptable to me. It would be an unusual option to change, and if you wanted you could do it in settings.php. The primary purpose is for the installer (in which case the UI won't be accessible yet), but this directory is also used when installing a new language for the first time.

**Comment by quicksketch** [comment]
Thanks @dboulet! Merged into 1.x and 1.3.x.
