### ISSUE TITLE
Establish a "fonts" directory in a place where it can be shared between core and contrib themes.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1452]
I'm not sure if this is makes sense or if it's worth pursuing at all, but here it is...

I noticed a considerable difference in the filesize of the .zip from the master branch since the last time I had to download it, so I decided to analyze the size of our various directories. I noticed that when extracted, the ```/core/themes``` directory takes up almost half the size of the entire distribution. Digging further down revealed that Seven takes up 99% of that space and that is because of the ```fonts``` directory. Then I realized that fonts is a resource that various themes might need to access and it might either be a waste to include the same font in more than one themes or simply silly to point to a specific font of a theme from another theme (what happens if the theme that actually ships with the font is removed from the installation?).

So the question here is should we introduce a top-level ```/core/fonts``` directory (as well as a ```/fonts``` directory for contrib themes)?

**Comment by klonos** [comment]
...related: #364

**Comment by quicksketch** [comment]
I made a new issue at https://github.com/backdrop/backdrop-issues/issues/2105 and just found this one in the process. In the issue to add a new core theme (Basis) https://github.com/backdrop/backdrop-issues/issues/1361, we'll need Open Sans for both Seven and Basis. As such we'll need a central place to put the font instead of having each theme duplicate the same font.

My plan had been to register Open Sans as a library in system.module like other JS/CSS libraries (tabledrag, collapsible fieldsets, etc.) Right now all of our extra JS/CSS/etc that is used across core is put in the `core/misc` directory, which might not sound sexy but is something we'll probably have to wait until 2.x to come up with a centralized place that is truly shared across multiple contrib themes (e.g. a libraries directory).

**Comment by quicksketch** [comment]
PR filed for OpenSans at https://github.com/backdrop/backdrop/pull/1501.

The location of OpenSans is now:

`/core/misc/opensans/opensans.css`

With all needed fonts in that same directory. As themes don't yet have the ability to have libraries or use paths relative to the site root (they are always relative to their current location), I added this CSS library call in `hook_preprocess_page()` instead. We can use this same approach for the responsive tabs in https://github.com/backdrop/backdrop-issues/issues/2105.

**Comment by klonos** [comment]
Seems reasonable to me, but we still should revisit this for 2.x so that we can have `/core/fonts` & `/fonts` directories available. It will make better themer/dev experience I believe.

**Comment by quicksketch** [comment]
As a library, I think it'd also be easily possible for us to move the location of OpenSans in 1.x if we really needed to.  As themes/modules won't need to leverage the path in the first place, they'll just `backdrop_add_library()` it by name.

I'll go ahead and merge this PR to help push forward the work on Basis. We don't have much time to delay for 1.5.0.
