### ISSUE TITLE
[DX] Backdrop does not detect modules of certain names

### ISSUE THREAD

**Issue by serundeputy** [backdrop/backdrop-issues#1476]
If i name a module 
- `headless` it is not detected by backdrop `/admin/modules` if I name it `big` backdrop seems happy. 
- `decoupled` is not detected 

These module names were detected by Backdrop on the `/admin/modules` page:
- pacpac
- pataloodale
- aaaaaaaa

I don't know the scope of what names are detected and which are not, but here are the steps to reproduce the problem:
- Make a new directory called `headless` in ./modules/
- Add a `headless.info` file to the `headless` directory with the following contents:

``` php
name = headless
description = "Use Backdrop CMS to serve JSON data to apss, front end frameworks, APIs and/or wherever."
backdrop = 1.x
type = module
```
- Add a `headless.module` file to the `headless` directory with the following contents:

``` php
<?php

```
- Flush all caches
- Visit `/admin/modules`
- Search for `headless`

The new module is not detected by Backdrop CMS :(

@jenlampton thought this has something to do with `backdrop_system_listing`

that is what I know.

**Comment by serundeputy** [comment]
Just downloaded `on_the_web` and it also was detected on the `/admin/modules` page. :hammer:

**Comment by quicksketch** [comment]
We need to get this fixed before the next release. Not picking up modules is a critical problem.

Do you know if this is an issue with 1.2.x or just 1.x?

**Comment by serundeputy** [comment]
> Do you know if this is an issue with 1.2.x or just 1.x?

@quicksketch I can confirm on 1.2.2 have not tried 1.2.x ... although I can not reproduce with `on_the_web` any longer, but still occurring with custom `headless` module.

**Comment by quicksketch** [comment]
I found the source of the problem. When we added the ignoring of vendor-specific directories (less, node_modules, scss, etc) in #1110, the Regex had an issue:

```
/^(\..*)|assets|css|scss|less|js|images|templates|node_modules|bower_components$/
```

Even though we include a start and end delimiter (^ and $), directories that contain any of the above items will still be matched if they end in any of those phrases. So "headless", happens to be an unfortunate suspect because it ends in the word "less".

To fix this problem, we need an additional set of parenthesis around the entire list. That makes it match as we expected.

**Comment by quicksketch** [comment]
PR filed in https://github.com/backdrop/backdrop/pull/1169

**Comment by quicksketch** [comment]
>  decoupled is not detected 

I couldn't reproduce this problem. Though I found my first attempt I renamed "headless.info" to "decoupled.info". This file was found but I overlooked it on the modules page because it still had `name = Headless` in the file. Maybe something similar happened when you were testing?

In any case, after the patch both headless.info and decoupled.info are picked up.

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/issues/1169. Thanks for the exhaustive testing on this @serundeputy!

**Comment by serundeputy** [comment]
Yeah! it works on `1.x` thanks @quicksketch New contrib module coming soon :)
