### ISSUE TITLE
10 languages website

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1504]
Hi!

I am going to build 10 languages website.
Can I do it with Backdrop CMS?

I need it something like LG website: http://www.lg.com

Thank you!

**Comment by klonos** [comment]
You can add as many languages as you wish in Backdrop. Did you check ```admin/config/regional/language```?

**Comment by bd0bd** [comment]
@klonos, thank you!
But I do not see/understand how to do:
domain.com
domain.com/fr
domain.com/it
domain.com/de
etc.

**Comment by findlabnet** [comment]
You can set "Path prefix" in `admin/config/regional/language/detection/url`. Default language - without path prefix, and rest of - as in your list.

**Comment by bd0bd** [comment]
@findlabnet, thank you very much! :)

**Comment by findlabnet** [comment]
You are welcome!

**Comment by bd0bd** [comment]
Sorry, I do not understand the logic how to male different languages Backdrop site.
10 languages > 10 menus > 10 different versions of the same pages.

**Comment by bd0bd** [comment]
May be there is a multi language demo site I could see inside admin panel?

**Comment by klonos** [comment]
Hey @bd0bd did you manage to get your domain prefixes to work after all?

**Comment by bd0bd** [comment]
Hi @klonos, no, I did not.

**Comment by klonos** [comment]
>Sorry, I do not understand the logic how to make different languages Backdrop site.
10 languages = 10 different languages menus > 10 different versions of the same pages.

@bd0bd been a while since. We now have translation-enabled menus (#225) and taxonomy (#2360) in core.

Re using different pages for translated content, that is discussed in #52.

Also, having to use multiple blocks per language is discussed in #1691 and #2956.

>> Hey @bd0bd did you manage to get your domain prefixes to work after all?
>
> Hi @klonos, no, I did not.

AFAIK we have had no reports of problems with the domain and/or path prefixes not working in language detection. Perhaps it has something to do with your specific setup (web server configuration or domain configuration).

I will go ahead and close this issue here.
