### ISSUE TITLE
Transliteration: enable the "Lowercase transliterated file names" setting by default

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1505]
This is the recommended setting, yet it is not activated by default. Allowing both lower and upper case will cause problems for Windows users.

---
PR by @BWPanda: https://github.com/backdrop/backdrop/pull/2896

**Comment by quicksketch** [comment]
I asked @jenlampton about this as well. With it lowercasing on upload off, I ran into an issue on Ubuntu because my file system is case sensitive. Though in my case it was caused by some failed tests, so I couldn't reproduce it easily. But essentially there is a problem where MySQL is not case sensitive but if files are case sensitive, they can end up causing duplicate keys in the MySQL table.

The point Jen made was that users like to be able to control their file names. If they upload a file that has a particular name, including capitalization, they prefer it stay that way.

**Comment by jenlampton** [comment]
I think if we are unable to detect a file system that does not allow case-sensitive file names then this setting should be enabled by default. People do like it when the PDFs they upload have the same name after they are uploaded as they did before. When those names start changing they get grumpy.

Also - we should track usage of who's on a windows  file system (or maybe just one that will cause problems with this setting).  I'd be curious to see if that number grows or shrinks over time :)

**Comment by klonos** [comment]
> I think if we are unable to detect a file system that does not allow case-sensitive file names...

What if production is Linux but dev is Windows? Wouldn't in these cases syncing production <-> dev cause havoc?

> When those names start changing they get grumpy.

Perfectly understandable, but I'm thinking grumpiness vs havoc here.

> However, if we are going to be causing trouble, maybe avoiding that risk is worth the grumpiness.

Exactly!

**Comment by olafgrabienski** [comment]
If we need more votes to go on with the issue: I prefer lowercase file names by default because it means less technical trouble. And it would be consistent to the settings of URL aliases, which is also an advantage.

**Comment by markabur** [comment]
> The point Jen made was that users like to be able to control their file names. If they upload a file that has a particular name, including capitalization, they prefer it stay that way.

That's been my experience as well. Some clients are very particular about names of file attachments and get dismayed if they see that the file was renamed.

However, that said, my pickiest client as far as that goes is OK with transliterating and lowercasing filenames _as long as_ we leave the "Transliterate the displayed file name" option unchecked -- so that the displayed file link is the original filename, but if you click the link you get a renamed copy of the file. They are fine with that, and appreciate having tidy-looking, foolproof URLs. 

In any case I think it always makes sense to enable lowercasing when filenames are going to be transliterated anyway. If you don't want files renamed at all, then don't enable transliteration of filenames in the first place.

**Comment by klonos** [comment]
> is OK with transliterating and lowercasing filenames as long as we leave the "Transliterate the displayed file name" option unchecked -- so that the displayed file link is the original filename

Yes! ...that makes perfect sense to me 👍 

The issues begin for example say with a local Windows server running an intranet or internal Backdrop CMS-based solution. In windows you simply cannot have `monthly report.xls` and `Monthly Report.xls` in the file system as two separate files. What happens when there is an existing node with a `monthly report.xls` attachment and then someone else tries to create another node with a `Monthly Report.xls` attachment? Does the 1st attachment get replaced/overridden (👎)? Do both nodes point to the same file (👎)? Does the creation of the 2nd node trigger a validation error? ...it should.

**Comment by BWPanda** [comment]
Made a [PR](https://github.com/backdrop/backdrop/pull/2896) that fixes this.

As to @klonos' question about monthly reports, I just tested this and in that case the `Monthly Report.xls` file would be renamed to `monthly_report_0.xls` and everything would still work (nothing would be overridden, etc.).

**Comment by olafgrabienski** [comment]
I've logged in the sandbox site and saw that "Lowercase transliterated file names" are enabled, as expected.

One side note about the help text:

> Enable to convert file names to lowercase. (...)

In my opinion, the prefix "Enable to" isn't needed, and it sounds quirky to me. I'd prefer a more straightforward version:

> Convert file names to lowercase.

Unfortunately, in this form all Transliteration help text starts the same way ("Enable to ..."), so it's reasonable to follow this pattern for now. Well, I guess I should open a separate issue.

**Comment by BWPanda** [comment]
> all Transliteration help text starts the same way

Yep, that's why I did that here to (consistency).

> I guess I should open a separate issue.

👍

**Comment by klonos** [comment]
>>all Transliteration help text starts the same way
>
>Yep, that's why I did that here too (consistency).

Small PRs like this one is where we usually grab the chance to fix UX/UI issues and inconsistencies. I say just go ahead and remove the extraneous "Enabled to ..." bit from all the help text. Less help text -> more chances that people will read it 😉 

PR is simple; I would have RTBC'ed it, but there is a failing test that needs to be fixed first. For now WFM 👍

**Comment by olafgrabienski** [comment]
> ... just go ahead and remove the extraneous "Enable to ..." bit from all the help text.

There are however a few more "Enable to" phrases in the Backdrop UI, so maybe in this case it's worth to treat them in a separate issue. (I'm fine with both.)

**Comment by quicksketch** [comment]
Updated the PR at https://github.com/backdrop/backdrop/pull/2896 to fix the failing test.

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/2896 into 1.x and 1.16.x. Thanks folks! This is one of those things that I wouldn't be surprised to get some negative feedback on our decision. Though I agree with the reasoning here and there's an easy option to flip it back to not lowercase files on upload.
