### ISSUE TITLE
Change the name of "Layout" module to "Layouts"

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1513]
We have a terminology problem with "layout" as the word means many different things (as mentioned in https://github.com/backdrop/backdrop-issues/issues/998#issuecomment-143658572) 
1) a project type ("Download a layout") propsed : **Layout set**
2) a particular project  ("Enable the Layout module") propsed : **Layouts module**
2) a set of configuration details ("Save the layout") propsed : **Layout**
3) the shape the content makes when placed into a page ("Select which layout to use") propsed : **Layout template**

I noticed a parallel with the views module, but views aided this by calling the module Views (plural) where the thing you build is a view (singular).

Would it help if we followed the same pattern with layouts and called the module Layouts (plural) and the thing layout (singular).

**Comment by quicksketch** [comment]
I imagine this is just for the presentation name, not the actual code-name right? We're not going to try to rename `layout.module` to `layouts.module` at this point.

Regarding this particular issue, almost every core module that provides a type of data has this going on. Name => type of data: Node => node, Block => block, Comment => comment, Menu => menu, etc. They all provide a type of data and they all are singular. Views is an anomaly for being plural.

My preference on this one would be to keep the display name as is, so that it matches the underlying code name.

**Comment by jenlampton** [comment]
> We're not going to try to rename layout.module to layouts.module at this point.

That's why I tagged it 2.x :)

**Comment by jenlampton** [comment]
closing :)
