### ISSUE TITLE
[UX] Make text blocks reusable (into custom blocks)

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1515]
This is a follow up for https://github.com/backdrop/backdrop-issues/issues/1428 and https://github.com/backdrop/backdrop-issues/issues/1099. 

Let's add a checkbox to the "Add new custom block" form so that the new custom blocks we create in the layouts UI appear in the custom blocks list, save to their own separate config file, and become full-featured custom blocks!

**Comment by quicksketch** [comment]
I almost have this working over in my branch for this feature at https://github.com/quicksketch/backdrop/tree/1515/reusable_blocks

Once we merge https://github.com/backdrop/backdrop-issues/issues/1099, I'll update it with those changes.

**Comment by quicksketch** [comment]
Initial PR for this at https://github.com/backdrop/backdrop/pull/1202. Needs tests but should be working with converting text blocks into reusable custom blocks.

Right now it's only a one-way process. You can make a text block into a reusable custom block but not the other way around. The cleanup process on undoing the making a reusable block could be a bit messy: needing to loop through all layouts and determining if the block is in use anywhere else... Or maybe we can come up with a smarter/easier solution. What if unchecking "reusable" didn't delete the underlying block?

In any case, if we go the other way and allow undoing, we'll need to update the implementation of block.module's blocks. In order to do this interchanging, it will need to use a Block class rather than the legacy `hook_block_configure()` approach we're using right now.

**Comment by quicksketch** [comment]
Tests added. This needs some review! Anybody up for it?

**Comment by quicksketch** [comment]
Customary big-GIF:

![2016-01-13 22 55 53 686](https://cloud.githubusercontent.com/assets/100206/12317781/32008224-ba49-11e5-8633-8a1c72a4db08.gif)

**Comment by jenlampton** [comment]
this is looking fan-didly-tastic!!!  I created a few follow up issues for the block UI that will make creating blocks slightly less painful for users, but those don't need to get done before this goes in, so I've tagged them both as follow-ups to this issue. This PR looks good to me!

**Comment by mikemccaffrey** [comment]
I haven't had a chance to review the code, but based on the big GIF, this seems like a great solution!

**Comment by quicksketch** [comment]
Doh, though our tests aren't passing. This broke something with the new field blocks. I'll take another look.

**Comment by quicksketch** [comment]
Turns out this was due to my desire to use a lighter-weight profile in the Layout tests. I switched it to the "minimal" profile which makes the tests run faster but was missing the "page" and "post" node types. I fixed up this missing requirement and they should be passing now. PR updated at https://github.com/backdrop/backdrop/pull/1202

**Comment by quicksketch** [comment]
There was one last test failure. Now fixed. We'll let Travis run through it one more time.

**Comment by quicksketch** [comment]
I've merged in https://github.com/backdrop/backdrop/pull/1202 for 1.3.0. woot!

**Comment by docwilmot** [comment]
Was just testing. A bit late then! Well done, looks great.
