### ISSUE TITLE
[UX] Remove the FULL HTML format from the Standard install profile

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1519]
As discussed over in https://github.com/backdrop/backdrop-issues/issues/1091, we think it would be better for users to have fewer text formats to need to understand out-of-the-box.  Since the Full HTML format is the easiest to configure (as it is now, there are no filters and no editors on it) and the name is less than ideal for a lot of use cases (some people like to add a rich-text editor, so having 'HTML' in the name is counter-intuitive for end-users who are not actually able to enter HTML).

- - - - - - - 
PR by @stpaultim = https://github.com/backdrop/backdrop/pull/3023

**Comment by stpaultim** [comment]
I came to file a bug report that there is not text editor associated with the Full HTML text format. 

I find it very confusing that I have a text editor for `Filtered HTML`, but that the text editor goes away when I switch to `Full HTML.` I expect to have more CKEditor options available with `Full HTML.`

Having read https://github.com/backdrop/backdrop-issues/issues/1091, I understand the wrongheadedness of my thinking and while not excited about removing `Full HTML,` I think it would be better than leaving it in without a text editor. 

In D7 the lack of a text editor in core was a major complaint. Having a `Full HTML` text format without a text editor feels like a regression to me. 

All of this is a vote in favor of getting rid of `Full HTML` and allowing users to set it up on their own   (unless we would rather add a text editor to it). 

Can we simply remove it from the install profile. Since this only effects new installations, it should not hurt any existing sites, RIGHT?????

This sounds like a PR that even I could do!

**Comment by klonos** [comment]
I will reiterate my proposal from https://github.com/backdrop/backdrop-issues/issues/1091#issuecomment-140272744

> I was thinking that perhaps it would be better if the text formats had an enabled/disabled status (same as views). This way:
>
>instead of removing the HTML format entirely, we simply disable it for the standard profile by default.
>instead of having those users that need it re-create it from scratch, we provide a single-click solution to get it back.

I also find it a very annoying and serious UX bug that the "Disable" action in `admin/config/content/formats` actually completely deletes the text format instead of disabling it. I thought that I had filed a bug report for it, but I was not able to find any issue, so I've filed #3962 for it.

**Comment by jenlampton** [comment]
I think it's important that people are able to enter HTML, but I'm fine
with having it disabled (but re-enableable) on the default profile.

@stpaultim the reason you are confused about editors, is because when we
added the editor, we didn't change the default format's name, so it still
has HTML. You have been trained that when you enter "HTML" you get an
editor, and that's our fault :)

**Comment by stpaultim** [comment]
I agree that naming is probably the problem here. I login as admin and go to create a page. I see that the default editor is `filtered html` and I have a WYSIWYG text editor that provides me with push button tools to generate that html. 

I'm thinking that I would like more options in my WYSIWYG editor and I see that there is a `full html` editor available, that will probably provide me with more WYSIWYG options to generate that html. I click on that and all my WYSIWYG options go away. Now, I'm thinking WTF? 

;-)

![Create_Page___sprinting](https://user-images.githubusercontent.com/3144571/62426607-9dd31f80-b6ac-11e9-999b-548f81a6ced5.png)

![Create_Page___sprinting](https://user-images.githubusercontent.com/3144571/62426620-c1966580-b6ac-11e9-819b-e9287613496a.png)

The problem is that I am thinking about the editor options in terms of features that they will provide me, NOT in terms of the filters they employ and neither the naming or help text provided is very useful in making that distinction. 

If we were to keep both, I would name them something like (names that help end user understand their purpose):

Limited WYSIWYG
(help text: filtered HTML)
Full HTML Filter
(help text: direct edit your HTML)

**Comment by stpaultim** [comment]
So, this issue is about removing the FULL HTML format from the Standard install profile. The discussion about naming them should be here: https://github.com/backdrop/backdrop-issues/issues/3709

**Comment by docwilmot** [comment]
why not just add all the editor buttons to full html? I'm not quite understanding why we'd remove it?

**Comment by stpaultim** [comment]
@docwilmot - There was an extensive discussion on that in an older issue: https://github.com/backdrop/backdrop-issues/issues/1091

@jenlampton in particular doesn't seem to want the WYSIWYG editor on the FULL HTML text format and there seemed to be a growing consensus that removing or disabling FULL HTML might be a good idea. 

Personally, I think either option would be an improvement over current situation but given prior discussion I am comfortable with what I thought was the emerging consensus.

**Comment by findlabnet** [comment]
From my modest experience, [BUEditor](https://backdropcms.org/project/bueditor) is amazing editor for unlimited (Full)HTML format, simple and extensible.

**Comment by klonos** [comment]
I'm just gonna throw this out there: perhaps rename "Full HTML" to something like "Raw HTML"?

**Comment by olafgrabienski** [comment]
> I also find it a very annoying and serious UX bug that the "Disable" action in admin/config/content/formats actually completely deletes the text format instead of disabling it. I thought that I had filed a bug report for it, but I was not able to find any issue, so I've filed #3962.

@klonos I've found the original issue #1575 and will close #3962.

**Comment by stpaultim** [comment]
I find the "Full HTML" filter to be very confusing and thinking it might be an easy win to simply remove it for now, I created a quick PR that simply removes it from the install profile. 

Removing it from the install profile will only effect new sites. 

However, simply removing it might not be possible without some additional UI work, because the "Formatting options" sections doesn't seem to work well with only one text format. 

![Create_Page___PR_3023_backdrop_backdrop_testing_site](https://user-images.githubusercontent.com/3144571/71329154-15cca580-24e7-11ea-93e7-5d2995f060b4.png)

Actually, this may not be a problem at all to a new user. I think it's only a problem for an experienced developer expecting to see options here. 

OPTIONS:
- Accept this as an improvement
- Force display of `Editor` options, even when only one options is available
- Change the name of `Full HTML` to `RAW HTML` or something else instead

![Create_Post___PR_3023_backdrop_backdrop_testing_site](https://user-images.githubusercontent.com/3144571/71329183-a60aea80-24e7-11ea-8bb6-17fd11b3126f.png)

I think that any of these options would be a big improvement. I continue to find `FULL HTML` to be very confusing name for this filter (and there seems to be consensus on this).

**Comment by olafgrabienski** [comment]
> I find the "Full HTML" filter to be very confusing and thinking it might be an easy win to simply remove it for now

In my opinion we shouldn't remove *Full HTML*. I agree however to rename the format and to disable it on new installations. Let's however continue to provide the format on new installations and set reasonable defaults, primarily enabling the *Correct faulty and chopped off HTML* filter.

Reminder: If we want to disable the format on new installations we have to check if it's already possible to enable it, cf. https://github.com/backdrop/backdrop-issues/issues/1575.

**Comment by jenlampton** [comment]
We have problems with naming the formats, as well as problems with the word
"formats" (or filters, or editors) but there's another issue for that too.
I'll find a link for that one too, it's an oldie...

**Comment by jenlampton** [comment]
Found it: [UX] Rename name "Filtered HTML" input format to "Basic"
https://github.com/backdrop/backdrop-issues/issues/1188

**Comment by stpaultim** [comment]
@jenlampton - You mentioned that the code look fine, other than all the tests that it breaks. BUT, is this a good idea functionally, even if it does not display anything under the `Formatting options` fieldset?

@olafgrabienski - I hear your concern. 

I would argue, that there seems to be a consensus that this filter has value but given it's current name and functionality is very confusing. I would argue, that unless we can fix the problems with this filter, we are better off not creating/enabling during install - it's just too confusing to be helpful to most users (it confuses beginners and advanced users can recreate it on their own pretty easy and name it whatever they want). 

I would rather get rid of it until we settle the other issues than to leave it in place, confusing users until we figure this all out. I see little downside to removing it. It's easy to bring back once we decide on what to call it and how to configure it. 

However, I'm not seeing consensus on removing it AND if we can come to a decision on renaming it, that would probably be the best option. I'm thinking I might create another PR that does rename it to `raw html.` We'll see if that triggers a final discussion/decision on what to call it?

**Comment by Graham-72** [comment]
As site-admin site-designer and site-builder I almost always change my setting to be 'Full HTML'. I don't mind if its name is changed but I don't want the option to disappear.

**Comment by olafgrabienski** [comment]
> I would argue, that unless we can fix the problems with this filter, we are better off not creating/enabling during install

A fix might be difficult and need some time but that's what we usually do: fix the issue instead of not enabling the functionality. I also see that the current situation might be confusing for some people. At the same time I guess, not providing *Full HTML* (or a renamed equivalent) would confuse people coming from Drupal. Personally, I don't use *Full HTML* often but I see other people use it all the time in Drupal.

**Comment by jlfranklin** [comment]
> I also see that the current situation might be confusing for some people. At the same time I guess, not providing Full HTML (or a renamed equivalent) would confuse people coming from Drupal. Personally, I don't use Full HTML often but I see other people use it all the time in Drupal.

Same here.  I've used it with clients when they needed some odd HTML on exactly one page and it wasn't worth coding anything up for it.  

I agree with @klonos, "Raw HTML" is a much better name for this, but I'd keep the machine name the same or provide some kind of alias.  There's a lot of contrib code that assumes "Full HTML" (`full_html`) exists.

If we are going to remove it, how about we create a new profile with the existing settings.  Call it "Classic" or something like that.

**Comment by olafgrabienski** [comment]
> ... "Raw HTML" is a much better name for this, but I'd keep the machine name the same or provide some kind of alias.  There's a lot of contrib code that assumes "Full HTML" (`full_html`) exists.

Another idea:

- Leave "Full HTML" as is (for contrib, upgrades from D7 and people coming from Drupal) but disable for new installations.
- Provide a new format called "Raw HTML", similar to "Full HTML" but with revised filter configuration.

**Comment by jenlampton** [comment]
> ... "Raw HTML" is a much better name for this, but I'd keep the machine name the same or provide some kind of alias. 

We can provide an upgrade path that will convert `full_html` to `raw_html` for existing sites. 

Can you provide an example of contrib code that assumes a particular format name @jlfranklin? It's not a safe thing for contrib to do since even those default formats can be deleted on any site, but I'd like to see an example to see if we could recommend some kind of constant or something else to use instead...

**Comment by docwilmot** [comment]
I still feel this is a step backwards. There are people who prefer to use an editor, but want to be able to use more tags. I cannot imagine that we are helping those people by asking them to go to the configuration and add buttons, when there already was an option to show full HTML. I think we should keep full HTML and throw the kitchen sink of available buttons in there.

**Comment by jenlampton** [comment]
I personally agree that removing this text format is not ideal, but I don't feel strongly about it, since it's easy enough to add back.

The last thing we want is people using the `Full HTML` format thinking that is a safe way to "use more tags". In reality, doing so will open a security hole by disabling all XSS Protection. 

We don't want people removing the `Limit allowed HTML tags` filter (which is what the `Full HTML` Text format does) just because it's "easier" than building a secure way to enter content.

I am looking forward to the improvements to the Text format UI, and hope that will solve the problems with the right/secure way to set up a Text format also being the more difficult way.

**Comment by docwilmot** [comment]
> In reality, doing so will open a security hole by disabling all XSS Protection

Ah, hadnt thought of that.

**Comment by jenlampton** [comment]
It doesn't look like this issue has consensus. It also looks like I was the one who aded the 1.15.1 bug-fix milestone, but I don't think qualify as a bug-fix. Removing milestone.

**Comment by stpaultim** [comment]
I had proposed changing "Full html" to "Raw HTML" as an alternative solution (this was suggested by others). I've opened a new issues to address that question directly. https://github.com/backdrop/backdrop-issues/issues/4499

**Comment by klonos** [comment]
Thanks @stpaultim 👍 ...I'm in favor of renaming the text format so that it makes better sense UX-wise; and with #1575 now in, we can ship the standard profile with this format disabled if we think that this is best (less confusing for new users). There will be no UX degradation when it comes to getting this functionality back for those that need it; instead of having to re-create that format from scratch, they can simply head to the text format page and enable it ...alternatively, we just rename the format (as part of #4499) and close this issue here 😉

**Comment by klonos** [comment]
> ...we can ship the standard profile with this format disabled

Here's a simple PR that does just that: https://github.com/backdrop/backdrop/pull/3198

...I expect some tests to fail, since they may need that format enabled. I'll fix those if there's consensus that we want this after all.

**Comment by findlabnet** [comment]
Not clear to me, why main (in many cases) format should be disabled by default.

**Comment by klonos** [comment]
@findlabnet whether you are logged in as a site admin or another role (content editor for example), the "main" or rather "default" text format in CKEditor-enabled text fields is "Filtered HTML". See here for which roles have access to which formats out-of-the-box:

![image](https://user-images.githubusercontent.com/2423362/88479528-619d6c80-cf58-11ea-9df9-a7ed1a045e13.png)

As you can see, the "Filtered HTML" format is at the top of the list, so that one gets to be the "main" one.

Anyway, my point is that (site admins aside) other users on a vanilla installation of Backdrop CMS will only see the "Filtered HTML" option. The problem arises when most site admins enable the "Full HTML" format for their content editors. ...that's when the confusion starts.

As @jenlampton mentioned earlier in this thread:

> The problem is that a format is the combination of filters (php) and/or editors (js). What we currently call "Full HTML" has no editor and virtually no filters. What we currently call "Filtered HTML" has both Filters and an Editor.

...so that thing there :point_up:, plus the fact that site admins seem to have a habit of enabling the "Full HTML" format for other roles, as an "easy fix" to allow them to use more HTML tags. Once the "Full HTML" format becomes available to them, users seem to expect to have a rich text editor with it, which would allow them to do things by clicking buttons (which is not what they get with the "Full HTML" format as it ships out-of-the-box). What site admins should be doing instead is editing the existing "Filtered HTML" format (or cloning it into a new one), and allowing whatever HTML tags are required + adding respective buttons to the editor toolbar.

Having written all the above has made me realize that neither disabling nor removing the Full HTML format would solve the UX issues we are trying to solve 🤔 ...perhaps what we should be doing instead is to show a warning when the "Display any HTML as plain text" filter has been disabled in a text format, and at the same time access has been given to the text format to roles other than the admin. ...that, plus rename the "Full HTML" format, as per #4499

**Comment by findlabnet** [comment]
In my experience, some clients who have gotten weird problems from the "rich" text editors, now enjoy using BUEditor (after very little HTML study.) 
And textareas of such content types are configured as "Full HTML" with the necessary filters enabled.

**Comment by klonos** [comment]
@findlabnet I understand that BUEditor may be your personal preference, but bringing it up in this issue only derails discussion. Besides, I don't see how replacing one editor with another would solve the issues we are aiming to solve here. We are not discussing training people to use HTML or another editor; and even if we used BUEditor, the text format would still be called "Full HTML", which is where the confusion and false expectations begin.

FTR though: the usage of https://www.drupal.org/project/bueditor is below 7k (out of ~1mil Drupal sites), and the respective Backdrop port [counts only ~40 sites](https://backdropcms.org/project/usage/bueditor) (out of ~1400). Although usage stats do not say much in themselves, they are still a metric to consider when deciding how easy/good a piece of software is. CKEditor was not a random choice for Drupal 8 core (and Backdrop by inheritance); it was selected for very good reasons, after an extensive comparison of various rich text editors (see https://www.drupal.org/project/drupal/issues/1260052). That d.org issue started with a call to provide an objective evaluation of any other editors to be considered, but nobody recommended BUEditor at that point 🤷

I believe that the battle plan here should be:

1. #4499: Rename the "Full HTML" text format to "Raw HTML"
2. #4501: Allow text formats to be cloned via the UI, so that site admins do not see the "Raw HTML" format as an easy solution to grant content editors with whatever super-powers they demand.
3. #4502: Dynamically add a warning to any text format that has the "Display any HTML as plain text" and "Limit allowed HTML tags" filters disabled.
4. Close this issue here as a wont-fix.

From previous discussions here, we seem to have consensus re point 1.

**Comment by klonos** [comment]
...back to this issue here, I believe that the battle plan here should be:

1. #4499: Rename the "Full HTML" text format to "Raw HTML"
2. #4501: Allow text formats to be cloned via the UI, so that site admins do not see the "Raw HTML" format as an easy solution to grant content editors with whatever super-powers they demand.
3. #4502: Dynamically add a warning to any text format that has the "Display any HTML as plain text" and "Limit allowed HTML tags" filters disabled.
4. Close this issue here as a wont-fix.

From previous discussions here, we seem to have consensus re point 1.

**Comment by stpaultim** [comment]
Since we have committed #4499 - I think we can close this issue as per the last battle plan (previous comment) by @klonos.
