### ISSUE TITLE
Attempting to re-run cron while it is already running.

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#1551]
I have this warning message in watchdog every time cron task is run "automatically".
It's followed by "Cron run completed.", so the issue is minor, but...

**Comment by BWPanda** [comment]
I'd ask if this is still an issue, but the author's account was deleted, so I guess we'll just close this unless someone experiences the same thing...

**Comment by stpaultim** [comment]
@BWPanda - I see this happen quite a bit myself, but haven't considered it a nuisance enough to worry about.

**Comment by BWPanda** [comment]
@stpaultim If you want to go ahead an reopen this issue then, please post details about where/how you experience this.

**Comment by oadaeh** [comment]
This usually happens if there is a combination of too long running cron jobs along with executing cron to close close together. I suggest first checking those things to make sure there isn't overlap.
It would be nice if there was a log option, like there is in Elysia Cron. Then one could enable that setting to see when the various jobs started and ended to see where the problem might be.

**Comment by klonos** [comment]
> It would be nice if there was a log option, like there is in Elysia Cron. Then one could enable that setting to see when the various jobs started and ended to see where the problem might be.

Now, thats a nice idea. Perhaps an "Enable debugging mode" checkbox under `admin/config/system/cron`?
