### ISSUE TITLE
[DX] Log warnings in the watchdog when a wrapper function is used (for backwards compatibility).

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1568]
Quite often when we change something in Backdrop that might be the norm for devs coming from Drupal, we include wrapper functions that provide backwards compatibility with the Drupal ones. This way, if someone uses the old, Drupal way, things still work.

That's great practice for DX+ but I think we should be logging warnings in the watchdog each time a wrapper function is used pointing to documentation or/and change records about the change. This way, even if the dev does not happen to notice them, users will eventually notice them and report back to the dev. Then the dev can check documentation and update their code to use the Backdrop functions instead of the wrapper ones.

Worth doing or nah?

---

Current PR: https://github.com/backdrop/backdrop/pull/1351

**Comment by klonos** [comment]
...got the idea from https://github.com/backdrop/backdrop-issues/issues/1495#issuecomment-170152996

**Comment by sentaidigital** [comment]
Worth doing, yes.  In fact, I would say let's take it a step further and add a `WATCHDOG_DEPRECATED` as a possible severity.

I say this because I'd like to see Backdrop CMS adopt an N-1 compatibility policy for new major releases, and this would be a key change to that end.

I got into Drupal somewhere around 6.8, and thought it was amazing.  When Drupal 7 was first released, given the number of unported modules, I expected that it would be unusable for professional development for at least six months while the community caught up.  Yes, many of the major modules had been ported, but it is the little finishing touches of the smaller modules and that make the difference between a good, functional site and a professional, top-shelf site.  So, while Drupal 7 had some great new features in it, the maturity of the Drupal 6 contributed modules made it easier to do more with D6 than D7, and easier to sell.

Today, some five months after Drupal 8.0.0 was released, the first page of [most installed Drupal modules](https://www.drupal.org/project/project_module) still lists several as "not yet ported", including Webform, XML Sitemap and Media.  That's some serious functionality, both front-end and back-end, still missing from Drupal 8.

I have clients all but forced off of Drupal 6 that would love to go to Drupal 8, but it's just not possible.  I would hate to see Backdrop suffer the same.

What I would like to propose, and what `WATCHDOG_DEPRECATED` would be key to, is an effort to ensure that Backdrop 1.x modules run unchanged on a Backdrop 2.x core.  I see general support for this in [Principal 1](https://backdropcms.org/philosophy) on the Philosophy page, but the commitment to N-1 compatibility isn't explicitly stated.

It will mean that API changes in the 2.x code need to be architected to ensure N-1 compatibility, either with wrapper functions, renamed functions and variables, or special logic to catch calls from old modules.  Anytime a function or structure is used in an old way, a `WATCHDOG_DEPRECATED` warning should be created. 

While it will make building Backdrop 2.x harder, I think the benefits are worth it.  It will give Backdrop 2.x site builders the mature library of modules on Day 1 that Backdrop 1.x cultivated, the watchdog warnings will give module developers a hot list of code issues (with links to the relevant documentation!) that they need to address to bring their modules up to spec, and it will give site owners confidence that the ROI on their investment today in Backdrop will be a gentle upgrade path tomorrow.

As Joel and the bots would say, what do you think, sirs?

**Comment by quicksketch** [comment]
I took a look at the PR in https://github.com/backdrop/backdrop/pull/1304. Overall I think the idea of making deprecated function calls traceable and logged is a good idea. However, it should also be non-intrusive. If this change were implemented as-is, a moderately trafficked site with even a few common legacy functions would be absolutely flooded with watchdog calls (one for every page load).  Logging that aggressive could both bring down a database or fill up a hard drive over a period of time.

So in general, I think this is a good idea, but perhaps it should be a developer-only option or exposed temporarily via settings.php, like the theme debug mode.

> What I would like to propose, and what `WATCHDOG_DEPRECATED` would be key to, is an effort to ensure that Backdrop 1.x modules run unchanged on a Backdrop 2.x core.

You're right that we're not explicitly committed to an N-1 compatibility policy. We've put out numbers like "20% change" allowed, but it's hard to actually quantify something like that. I don't think we'll attempt to make Backdrop 1.x modules run on 2.x without *any* changes, but we will try to ease the process wherever possible (such as we did with the Drupal compatibility layer to ease the transition from D7).

As with the Drupal compatibility layer, if we start logging every deprecated function that is called, after 2.x has been around for a while, some functions will definitely become deprecated that may have been acceptable in 1.x. So if you had a module that attempted to be both Bd1 and Bd2 compatible, it's inevitable that you'd get these deprecated warnings on Bd2, making N-1 compatibility a log-noisy thing on the newer version, just as it would be right now with the current PR and D7-functions.

So in general, I think this may be a good idea but we need to think of a better way to throttle or limit these warnings so they use useful if you want them but not overwhelming if they're not resolved immediately.

**Comment by sentaidigital** [comment]
> If this change were implemented as-is, a moderately trafficked site with even a few common legacy functions would be absolutely flooded with watchdog calls (one for every page load). Logging that aggressive could both bring down a database or fill up a hard drive over a period of time.

I want the watchdog messages to be noisy enough that developers are encouraged to update their modules, but not so noisy that site builders disable all logging or ISPs discourage customers from installing Backdrop.  The code in the PR that limits a watchdog warning to once per call per page view is trying to minimize the noise while at the same time provide useful guidance to module developers.

But, you're right, it can be overwhelming very quickly and that there should be some kind of throttle/limiter/filter/kill switch.  The PR already limits messages to once per call per page view, but more should be done.  I haven't looked at the theme debug mode, that might work.  While reading your comment, my initial thought was to add an "Enable messages of severity" setting for watchdog, with deprecated and debug disabled by default and a big warning in the setting's description text.

I'll take a look at the options and update the PR.

**Comment by sentaidigital** [comment]
> So if you had a module that attempted to be both Bd1 and Bd2 compatible, it's inevitable that you'd get these deprecated warnings on Bd2...

N-1 compatibility should not encourage modules to be Bd1 _and_ Bd2 compatible.  They're either a Bd1 _or_ Bd2 module as indicated by their info file.  Bd2 core is simply willing to load modules with `backdrop=1.x` and provide best-effort API support.  It may sound like I'm splitting hairs, but I don't want module writers to get complacent or demand a patch in Bd 2.5 because their Bd1+2 module does something weird and doesn't work right in Bd2.  The answer to such a bug report is calling out there is no such thing as a Bd1+2 module and the module developer needs to port his Bd1 module to Bd2.

N-1 cannot guarantee that a Bd1 module will work, but I think it can achieve better than 90% coverage of all modules to work or "mostly work".  

N-1 becomes harder if a module has dependencies that are updated to Bd2.  Site builders may have to run the old version of a dependency or those dependencies may need to provide N-1 themselves.  The N-1 support in core APIs can make it easier for modules to provide their own N-1 support, but if a module changes the name of one of its hooks there's not much core can do about that.  `backdrop_alter()` and `module_invoke_all()` call what they are told, not what they used to be told.  The modules would have to provide N-1 and call the old hooks themselves.

To help module developers, core APIs like `module_invoke_all()` may need flags or sister functions to generate appropriate watchdog messages so a module to call one hook on all modules with backdrop=1.x and another on all modules with backdrop=2.x.

When Bd2 starts changing its APIs, it would be good to ask the module maintainers of some of the more popular and extended modules, like Webform (hi, Nate), to help shape core's N-1 support and encourage N-1 thinking in the contrib community.

**Comment by quicksketch** [comment]
> The answer to such a bug report is calling out there is no such thing as a Bd1+2 module and the module developer needs to port his Bd1 module to Bd2.

Agreed. Sounds like we're on the same page here.

>  Bd2 core is simply willing to load modules with backdrop=1.x and provide best-effort API support.

I don't know about this. At minimum I think we should require the .info file to be updated. If a user wants to try and hack a module to make it run on 2.x when it was written for 1.x, they're taking on the responsibility of having hacked the module. But I expect that Backdrop 2.x would no more attempt to load a 1.x module than Backdrop 1.x would try to load a Drupal 7 module. While we won't have the tremendous amount of renaming that we did between D7 and Bd1, that experience showed that it's very unlikely for modules to work between versions with any consistency. Running a module that "mostly works" seems like it would inevitably cause data corruption and completely unexpected results.

The current compatibility policy is intended to make it easier for developers to port and maintain modules. Intentionally loading 1.x modules under 2.x would be significantly expanding backwards-compatibility, suggesting that *users* should be able to use N-1 modules, rather than compatibility being present for the ease of developers. I don't think that is a promise that we could fulfill.

**Comment by sentaidigital** [comment]
Latest patch includes filtering of watchdog messages based on system.core:watchdog_enabled_severity_levels, enabled via settings.php just like theme_debug.  Rather than filter for _just_ `WATCHDOG_DEPRECATED`, it allows for filtering of messages of any severity.

**Comment by sentaidigital** [comment]
@quicksketch I can't remove the "pr - needs work" labels as I don't have the ability to change the labels on this issue, but an updated PR is here.

Getting this into 1.4 would let us merge backdrop-contrib/devel#15.

**Comment by klonos** [comment]
@sentaidigital :wink:

**Comment by quicksketch** [comment]
> I don't have the ability to change the labels on this issue

You do now. Thanks!

Overall looks great! What are you thinking for a UI to enable the deprecated notices? Perhaps we put it in Devel module?

Note that we need a `hook_update_x()` in `system.install` to add the new config option for `watchdog_enabled_severity_levels` to existing sites. A basic test to confirm log entries are created for deprecated entries would also be appreciated, e.g. `BootstrapWatchdogTestCase` (which we don't have yet).

**Comment by sentaidigital** [comment]
Yes, putting it into Devel.  There's a patch already in backdrop-contrib/devel#15 that exposes `watchdog_enabled_severity_levels` along with `theme_debug`.

CMI doesn't automatically apply new config options?  I thought the point of putting them in the *.config files was to ensure there was *always* a default. (And it's always the same.)

**Comment by quicksketch** [comment]
>  I thought the point of putting them in the .config files was to ensure there was *always a default. (And it's always the same.)

The default configs are copied on the first install of a module, so there is always a default based on the original config file. But when adding new options to existing configs, we need an update hook to set the value. There are a lot of such examples in system.install already.

**Comment by sentaidigital** [comment]
I've added some test cases, but I suspect the way I did it violates some testing code conventions.  Let me explain.

I needed an `assertLogMessage()` and an `assertNoLogMessage()`.  The `ModuleTestCase` helper had the former and I could easily create a similar method for the latter.

The tests for this issue clearly belong in the Bootstrap group.  So, I created a helper class for the two asserts, called it `WatchdogTestCase` and then created a `BootstrapWatchdogTestCase` class with the actual tests.

In the interest of code reuse, I changed the parent class for `ModuleTestCase` to `WatchdogTestCase` and removed the original `assertLogMessage()` method.  In order for SimpleTest to know where to load the parent class of `ModuleTestCase`, I had to add it to `simpletest_autoload_info()`.  It is this last autoload piece that I'm uncertain follows convention.

**Comment by quicksketch** [comment]
This PR needs a rebasing after the `@deprecated` notice fixes went in (https://github.com/backdrop/backdrop-issues/issues/1760).

>  In order for SimpleTest to know where to load the parent class of ModuleTestCase, I had to add it to simpletest_autoload_info(). It is this last autoload piece that I'm uncertain follows convention.

While putting the class into `simpletest_autoload_info()` works, we've avoided putting test classes into the autoloader because 99% of the time they aren't being used, but test classes also make up more than 50% of the total number of classes in Backdrop. For other test cases that implement a different class, we've simple been doing an `require_once()` at the top of the class file, which is a bit primitive (not using an autoloader at all), but also works.

**Comment by quicksketch** [comment]
For an example, see `core/modules/field/tests/field_views.test`, which loads the class for `ViewsSqlTest` from `views_query.test`:
```
require_once BACKDROP_ROOT . '/core/modules/views/tests/views_query.test';
```

**Comment by sentaidigital** [comment]
OK.  Since the preferred method is `require_once`, I'll update the patch to use that and rebase.

**Comment by sentaidigital** [comment]
Just saw the note about the update hook. Added that into backdrop/backdrop#1351.

**Comment by quicksketch** [comment]
Great, thanks @sentaidigital! We're really out of time for the 1.4.0 release; I'm afraid this will have to wait until 1.5.0, but this will be one of the first features for that release!

**Comment by sentaidigital** [comment]
That's fine.  I wasn't looking in my email today, and the reminder about the update hook wasn't where I was looking.  If it showed up on my notifications page it was cleared when I dealt with another item.  Is there a way to get Github to retain notifications until you explicitly clear them?

**Comment by quicksketch** [comment]
Hi @sentaidigital! Yeah I think this is likely to make it. I've been giving focus to our priority features from the roadmap, but as those are either held-up or already in, I'm going to loop around and take another look at this.

**Comment by quicksketch** [comment]
I did another round of feedback. Overall looking great! Do you think you could implement this suggestion to skip calculating the calling function with debug_backtrace() if the logging isn't enabled in the first place? https://github.com/backdrop/backdrop/pull/1351/files#r78489088

**Comment by sentaidigital** [comment]
Feedback implemented.  Ready for review.

**Comment by quicksketch** [comment]
The PR looks great! I love `watchdog_severity_enabled()`, a well-named and reused function. Well done! The only thing I'd like to see is a `@since 1.5.0` on that new function. I can handle that small addition and we can merge this.

**Comment by sentaidigital** [comment]
A few other things should be tagged `@since 1.5.0` including `watchdog_deprecated_function()`, `backdrop_goto_deprecated()` and the `WATCHDOG_DEPRECATED` severity level, itself.

**Comment by quicksketch** [comment]
I manually merged the PR to add a few `@since 1.5.0` docblocks. Commit hash is https://github.com/backdrop/backdrop/commit/5fede86b4645806d5564245d842380609000251c. Thanks so much @sentaidigital for your work on this! This will be in 1.5.0. You rocked it!

**Comment by quicksketch** [comment]
@sentaidigital Hey, I just noticed in my merge that it was credited to https://github.com/jlfranklin instead of https://github.com/sentaidigital. I think I can change author attribution after the commit was completed if that's the wrong username. You might check your [git email](https://help.github.com/articles/setting-your-email-in-git/) lines up with your GitHub account. Though if you manage two accounts for personal/professional reasons I understand. Thanks!

**Comment by quicksketch** [comment]
My follow-ups ended up on a separate commit, here they are: https://github.com/backdrop/backdrop/commit/7b0d95bb42ad31e6b09d6e906283e9069b9340e5.

**Comment by klonos** [comment]
Thanx for making an idea reality @sentaidigital 👍 I predict that this small feature will be very valuable along the way.

**Comment by sentaidigital** [comment]
@quicksketch, I manage two accounts, sentaidigital and jlfranklin.  I have no issue with the commit attribution as it is, but thanks for offering to do git surgery. 

@klonos, happy to do it, especially when I have the same itch.  :)
