### ISSUE TITLE
Allow custom blocks to be translated.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1576]
As it is now, if one needs a custom text in a specific region in a multilingual site, they need to create one custom block per language and then use visibility conditions. Once that's done, they end up with as many blocks as they have languages and all these blocks have the title "Custom block" in the Layout UI, so there is no way to tell which is which (#692).

**Comment by klonos** [comment]
...what was the point of having custom blocks be in config again? (...instead of implementing a node-as-block feature I mean?)

Use case: I need to place an announcement in the header of the website for a short period of time and I need the text to be translated. How I would expect this to work ideally is this:

1. There would be a "Block" content type out of the box with the only difference from Page and Article being that it would have its "make available as block" option enabled by default.

2. I could enable translation for this content type. I would then create an "Announcement" node of this type and translate it.

3. I would finally head to the Layout UI and add the block to a region and language would be automatically picked up as a visibility condition.

**Comment by quicksketch** [comment]
> ...what was the point of having custom blocks be in config again? (...instead of implementing a node-as-block feature I mean?)

So blocks were moved into config because they were considered to be much more close to being architecturally matching what we needed for one-off "text blocks" becoming "reusable". Making blocks into entities (and thus translatable) would have been a rewrite of block.module. So rather than rewriting blocks to be entities, we made them useful for implementing "reusable" checkbox on text blocks.

However, that doesn't mean that node-as-block is out. We're still planning/brainstorming on this idea over in https://github.com/backdrop/backdrop-issues/issues/100. Even prior to that happening, we'll probably implement being able to place arbitrary entities into Layouts in https://github.com/backdrop/backdrop-issues/issues/1076.

So based on your ideal workflow, your feature would be implemented between those two other issues. And you wouldn't use the "Custom block" module at all, because as you've noted, they're not translatable.

**Comment by klonos** [comment]
> So based on your ideal workflow, your feature would be implemented between those two other issues.

Thought so. Does that make this issue here moot? ...because AFAIK nodes are already translatable. All we're missing is the ability to have them as blocks.

> And you wouldn't use the "Custom block" module at all, because as you've noted, they're not translatable.

There was an initiative for translatable CMI though. We have an issue for that someplace. Right?

**Comment by quicksketch** [comment]
> There was an initiative for translatable CMI though. We have an issue for that someplace. Right?

Yep, and that would be a 3rd way of solving this problem. The issue for that is https://github.com/backdrop/backdrop-issues/issues/704.

So let's close this issue with a number of already in-progress alternatives that would solve it.
