### ISSUE TITLE
Incompatibility with PHP 5.3.3

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#1579]
Warning: DOMDocument::saveHTML() expects exactly 0 parameters, 1 given in _filter_image_caption() (line 2380 of /home/www/backdrop/core/modules/filter/filter.module).

This is just a php warning, but **the body field is lost** !
I did nothing hazardous, just add a caption to an image...

from http://php.net/manual/fr/domdocument.savehtml.php : 
`public string DOMDocument::saveHTML ([ DOMNode $node = NULL ] )`
but
Version     Description
5.3.6   ~~Le paramètre node a été ajouté.~~ The node parameter was added. 

https://backdropcms.org/requirements states : PHP 5.3.2 or higher

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2479

**Comment by quicksketch** [comment]
Thanks, looks like we could avoid this problem by using `saveXML()` instead of `saveHTML()`. For our purposes I expect they would be the same.

Out of curiosity, what hosting provider or operating system is this on? We support old versions of PHP, but it's good to get an idea what sort of situations people would encounter an old version like this.

**Comment by gifad** [comment]
> what hosting provider or operating system is this on?

http://p1347.phpnet.org/
It's 4 years old VM on a shared hosting, with security fixes only
Runs backdrop with nice dropdown responsive menus, though : http://p1347.phpnet.org/backdrop/l/3rgz8UIEd0Vd/

**Comment by olafgrabienski** [comment]
I just got this warning when I tried to add an image with a caption on a Backdrop 1.8.0 site:

`Warning: DOMDocument::saveHTML() expects exactly 0 parameters, 1 given in _filter_image_caption() (line 2454 of /(...)/core/modules/filter/filter.module).`

Result: The image is not displayed when I use a caption.

This happens on a quite old server of a client, still running on PHP 5.3.3.

@quicksketch You said we could avoid this problem by using `saveXML()` instead of `saveHTML()`. Can we do this as a bugfix for the next release? And if you need more information about the PHP configuration let me know.

**Comment by olafgrabienski** [comment]
> I just got this warning when I tried to add an image with a caption on a Backdrop 1.8.0 site
> Result: The image is not displayed when I use a caption.

Just ran again in this issue as the editors of the site in question now really want to display pictures with a caption in the body field. @quicksketch by reading https://github.com/backdrop/backdrop-issues/issues/1579#issuecomment-175910274 I understood that you have a solution but I don't know how to implement it by myself. Are you up to do the fix?

**Comment by klonos** [comment]
Hey @olafgrabienski is this still an issue? Next time this happens, can you please try applying this patch: https://patch-diff.githubusercontent.com/raw/backdrop/backdrop/pull/2479.patch

This is a single line of code change. In `core/modules/filter/filter.module` look for `saveHTML($node)` (around line 2461 at the time of writing), and change that to `saveXML($node)`. Then please report back if this fixes the problem for you.

Thanks

**Comment by olafgrabienski** [comment]
@klonos I can‘t try to reproduce the issue anymore as PHP on the server has finally been upgraded a while ago.

**Comment by herbdool** [comment]
It would be good to test the PR regardless of PHP version since we need to know if there's a regression or not.

**Comment by olafgrabienski** [comment]
The PR works in the sandbox site. I was able to add an image with a caption in a post without problems, and there were no error messages in DBlog.

**Comment by quicksketch** [comment]
Thanks folks, merged https://github.com/backdrop/backdrop/pull/2479 into 1.x and 1.12.x.
