### ISSUE TITLE
Layouts: Support vocabulary context for the taxonomy/term/% path.

### ISSUE THREAD

**Issue by Al-Rozhkov** [backdrop/backdrop-issues#1587]
First of all huge thanks for Backdrop! I absolutely love this fork, especially UX improvements and performance numbers. Actually backdrop performance and memory usage is a miracle for me. It has views and panels in core and still faster than d7.

My question is about `taxonomy/term/%` path in layouts.
![01](https://cloud.githubusercontent.com/assets/16973264/12696964/ef5679ba-c790-11e5-8669-6878de1e1596.jpg)

There is no term context in Contexts list. So I can't create different layouts per vocabulary.
I tried different approach with taxonomy/term/% page in Views. I used Vocabularies validation criteria.

![02](https://cloud.githubusercontent.com/assets/16973264/12697041/13c39ce6-c792-11e5-98d2-cbd12fa967f0.jpg)

But it's impossible to have several views with `taxonomy/term/%` paths. Only first one is working. And term pages of other vocabularies returns "Page not found".

I understand that I can create custom path like `category/%` in Layouts and add View block to it. But in that case I can use only term id as argument. So page can't have url like this: `category/food`.

**Comment by sutibun** [comment]
hi hi ^^)/~~~

Definitely not a Bd Layout expert so don't quote me on this (don't fully understand myself) but I thought I heard someone say in the past that, _at the moment_, you can't do "complicated" Layout filters. Just based on simple URLs.

**Comment by Al-Rozhkov** [comment]
There is same issue in d7 Views module. That is why projects like Taxonomy Views Integrator (https://www.drupal.org/project/tvi) exist. In Panels it's done much better with taxonomy/term/% path and vocabulary condition. I guess Backdrop will have more panels like solution in future.

It would be great to hear Backdrop core developers about plans on complex conditions in Layouts system. What version of Backdrop will handle this? Or may be it is room for contrib project (like TVI).

P.S. Sorry for my English. I try my best to explain myself without mistakes :)

**Comment by klonos** [comment]
In D7 it made sense for projects like TVI to exist in contrib because they were there to supplement another contrib project (Views in this case) so that it gets better integration with a core feature (taxonomy/vocabularies). In Backdrop though we've merged Views into core, so I believe that this feature should be supported by core - not in contrib. This would provide better UX and tighter integration between Layouts (and context in general I guess), Views and Taxonomy.

@quicksketch ??

**Comment by sutibun** [comment]
Pretty sure more complex conditions are coming... otherwise, Bd Layout would be pretty, well you know.

Think just a matter of priority and timing.

**Comment by quicksketch** [comment]
I tried out the PR at https://github.com/backdrop/backdrop/issues/1258. It has the right idea but it didn't actually make the Taxonomy context available. As we have entity fields and type selection, you should immediately be able to place fields on taxonomy term pages as blocks, as well as use a taxonomy term selection criteria.

It looks like we just need to change `$info['term']` into `$info['taxonomy_term']`, so that the plugin name matches the entity type. I'll make an update and write a basic test to make sure it gets picked up.

**Comment by quicksketch** [comment]
I filed a new PR at https://github.com/backdrop/backdrop/pull/1331 that changes "term" to "taxonomy_term" (the only code change) and added a test. Diff is at https://github.com/backdrop/backdrop/pull/1331/commits/b9b0e3922299a3f636c0d5061ac0b360a5b1543c

**Comment by quicksketch** [comment]
Tests passed. Merged in https://github.com/backdrop/backdrop/pull/1331 for 1.4.0.

**Comment by klonos** [comment]
Just tested this and it works!:

![backdrop-commit_1331-term_context_in_layouts](https://cloud.githubusercontent.com/assets/2423362/14764763/c637331c-0a07-11e6-8b61-cac8e4a26eed.png)

@Al-Rozhkov you might wanna give the 1.x dev a go and see whether what was implemented is enough for your use case.

**Comment by klonos** [comment]
...another screenie with `taxonomy/%` as the path:

![backdrop-commit_1331-term_context_option_in_layouts](https://cloud.githubusercontent.com/assets/2423362/14765059/4cf7980a-0a13-11e6-81b0-90774ffe86a1.png)
