### ISSUE TITLE
Upgrade from Drupal 7: Taxonomy module Update #1002 fails with errors

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1588]
When upgrading from a Drupal 7 site (latest version) I get the following errors during upgrade:
```
Failed: PDOException: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes: ALTER TABLE {taxonomy_term_data} ADD INDEX `taxonomy_tree` (`vocabulary`, `weight`, `name`); Array ( ) in db_add_index() (line 2947 of backdrop/core/includes/database/database.inc).
```
I believe this is the error mentioned in https://github.com/backdrop/backdrop-issues/issues/1081, where @xmacinfo resolved the problem by switching taxonomy tables to InnoDB.

Can we include that switch as part of our upgrade path so those who upgrade don't need to do that manually?

**Comment by xmacinfo** [comment]
Most of my MyISAM tables (from old Drupal versions) were left as is when I upgraded a site to Backdrop. Switch to InnoDB was required only for the taxonomy tables.

We can either check for all database table engines if they use InnoDB or not, or only check the Taxonomy ones.

Or we could make Backdrop compatible with both InnoDB and MyISAM engines, including the taxonomy tables.

**Comment by quicksketch** [comment]
I've merged https://github.com/backdrop/backdrop/pull/1494 for 1.x and 1.4.x, so this will solve the problem with Taxonomy indexes being too long. I'm not sure if we should do a blanket conversion of tables or not, but that can be a separate issue (either as a bug or feature). The UTF-8 MB4 upgrade will also accomplish this change, but it's an explicit operation rather than an automatic update: #884.

**Comment by tux-86** [comment]
InnoDB is not always enabled especially on shared hosting. So we need different workaround for this.

**Comment by jenlampton** [comment]
Interesting, I hadn't considered that it might not be available for some. Thanks for the feedback @tux-86.  We should either list this in our server requirements, or better yet, find out what the actual problem is with this update and see if there isn't a better solution that would work for everyone.

**Comment by xmacinfo** [comment]
Please note that this problem applies _only_ the the _taxonomy_ tables.

I left out other tables in MyISAM and Backdrop works fine (updated a site that was created in D6 and upgraded to D7 and then Backdrop, left a lot of tables in MyISAM).

So we only need to check in the taxonomy tables are in InnoDB, if not, why not:  

- create temporary tables for the taxonomy, 
- do the migration, 
- drop the old MyISAM tables,
- rename the taxonomy tables (from temporary names to permanent ones)?

**Comment by quicksketch** [comment]
Here's the D8 issue for dropping MyISAM support for the record: https://www.drupal.org/node/2275535

Drupal 8 introduced that as a requirement. D7 still supports MyISAM (though it prefers InnoDB if it exists).

> InnoDB is not always enabled especially on shared hosting. So we need different workaround for this.

Are there any examples of this? In the D8 issue it was mentioned that Bluehost, HostGator, Site5, and GoDaddy; the lowest of low-end hosts.

> So we only need to check if the taxonomy tables are in InnoDB, if not, why not: 

@xmacinfo Is there are reason why we would need to do all that manually instead of just doing a single ALTER TABLE and letting MySQL do the engine conversion as in https://github.com/backdrop/backdrop/pull/1494/files?

**Comment by xmacinfo** [comment]
> Is there are reason why we would need to do all that manually instead of just doing a single ALTER TABLE and letting MySQL do the engine conversion?

@quicksketch No, of course not. :-)

**Comment by quicksketch** [comment]
Okay, I think this specific issue is fixed up. We'll see if it helps users upgrading from D7.
