### ISSUE TITLE
CSS: Views filters and/or positioning funny

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1598]
May need a little CSS cleanup here: 
![screen shot 2016-02-01 at 1 16 47 pm](https://cloud.githubusercontent.com/assets/397895/12731502/2556d84c-c8e6-11e5-943f-8b61dee43e5f.png)

**Comment by alexfinnarn** [comment]
I took a look at this...I think since the group operators have a label, the "all groups" filter should include a label to instead of being hidden. 

To make the formatting align, the label for the operator select could be placed after the element. It is awkward when speaking to say "I changed the operator OR" instead of "I changed the OR operator."

The other issue here is the replacement of the operator for each individual filter. It looks like the JS selector needs more definition to only change within each group, instead of the first group changing every group that follows. This is only a display problem (expected results on save), but it is confusing to a user.  

<img width="1278" alt="2016-03-25_1354" src="https://cloud.githubusercontent.com/assets/3640707/14052634/4d268f5a-f291-11e5-83d4-9830d6084060.png">

Thoughts?

**Comment by BWPanda** [comment]
I've made a PR that implements @alexfinnarn'ssuggestions re. the operator labels:

![image](https://user-images.githubusercontent.com/2385329/89851094-095ca080-dbcf-11ea-800a-c381e3f1c0a9.png)

The other issue @alexfinnarn brought up (about the inconsistency) was fixed in https://github.com/backdrop/backdrop-issues/issues/3936.

**Comment by stpaultim** [comment]
If I understand correctly, the point of this issue is to simply make this page easier to read/understand and look better. Is that right?

I tested the PR and it works. However, I'm not sure that the page looks that much better. Having the operator selectors line up is nice. 

1) In my opinion, the biggest visual problem on this page is each filter group is not as clearly defined as it could be. I would like a sharper border around each field group or a differentiation in the background to make the filter groups very clear. I don't know what the best way to accomplish this is, through shading or borders? Do we have a design solution elsewhere in Backdrop CMS that we can borrow?

![Administer_content__Content____PR_3232_backdrop_backdrop_testing_site](https://user-images.githubusercontent.com/3144571/89853046-e6da7100-db55-11ea-9e7d-ac89b5893b69.png)

2) The help text/label "Operator to use on all groups" or "Operator (all groups)" is not helpful to me. Currently, this operator has no label and I don't think it needs a label IF we there is a clearer boundary around each filter group. When the filter groups are clearly distinguished, then I think the purpose of this operator becomes very clear without any label. I think that the only problem with the current use of this operator is the lack of definition between where one group starts and the next ends.

**Comment by BWPanda** [comment]
I've played around with borders, etc. to make it look better (actually to make it look like it did in D7), and then there are two options for the Operator drop-downs:

## Operator labels
![image](https://user-images.githubusercontent.com/2385329/89857479-8db71f80-dbdf-11ea-882d-ccbe9beadbc4.png)

## Indents
![image](https://user-images.githubusercontent.com/2385329/89857516-a9bac100-dbdf-11ea-9bd5-2cf3958814f8.png)

Preference?

**Comment by BWPanda** [comment]
I've updated the PR. There are two commented-out lines that will switch to the alternative option above if you want to play with it.

**Comment by stpaultim** [comment]
@BWPanda - This is an improvement. I wish there was more contrast or sharper borders, but I think that is an overall issue with the color scheme for the administrative theme and not something that should be addressed in this issue. What you have done is helpful. 

I realized now, that the  labels - **"Operator to use on all groups"** and/or **"Operator (all groups)"** was confusing me, because I was confused about the actual functionality. 

It looks like (it appears that) you can set the operator between the 1st and 2nd filter group to be different than the operator between the 2nd and 3rd filter group. In fact, all group operators must be the same - hence the label that I found confusing. The label was there for good reason. 

In my ideal world, there would only be one location where you can change the group operator and then we would just display the actual selection between each group. It does not seem like a good idea to provide multiple different places to change a single operator. BUT, that is probably beyond the cope of this issue - which is about CSS and styling. 

This issue is more complicated than I thought. I'm just going to throw out another idea, that may or may not be helpful. 

![operators](https://user-images.githubusercontent.com/3144571/89864293-54e06180-db71-11ea-9ad9-3db743932241.png)

Something like this might be better - but, may be beyond the scope of this issue:

![__operators___exported_-1_0__RGB_color__1_layer__1060x700_–_GIMP](https://user-images.githubusercontent.com/3144571/89865109-bce37780-db72-11ea-96a4-3517e717f11b.png)

**Comment by oadaeh** [comment]
> It looks like (it appears that) you can set the operator between the 1st and 2nd filter group to be different than the operator between the 2nd and 3rd filter group.

That is correct and the way it should be.

> In fact, all group operators must be the same

That is NOT correct.

I should not be forced to make all groups be either AND or OR. I should have the option of specifying one group as AND and another as OR in the same filter set. Granted, that logic is probably not used frequently, but removing that option removes basic functionality that would require quite a bit of programming to overcome.

**Comment by stpaultim** [comment]
> I should not be forced to make all groups be either AND or OR.

Well, that is not the way it currently works. If this is broken, do we have an issue open for it?

**Comment by oadaeh** [comment]
Alright, I'll try to take a look at it soonish and see what is up there. If it is not actually working as it should be, I'll find or create an issue for it.

**Comment by oadaeh** [comment]
Okay, it looks like I was wrong, and it is making all groups be either AND or OR. I also tested a rather current version of D7 Views, and it behaves the same way. I was sure it did not work that way, because I remember creating a view that had both an AND and an OR group, but maybe what I'm remembering is not the functionality I desired and expected, but running into this limitation and having to work around it (which seems logical to me as a thing that would probably more impress itself in my memory than the other).

**Comment by stpaultim** [comment]
This has been open for discussion a long time. I'm marking it "works for me" because I think it's a small but clear improvement in the UI and has been sitting for too long. 

We can open new issues and make additional improvements in the future, unless anyone has anything to suggest now. 

I like this better than with the two lines that are commented out. I think we should remove those and merge this.

BEFORE:
![image](https://user-images.githubusercontent.com/3144571/167781495-9c274424-0b7a-43c7-b845-596993df176c.png)

AFTER:
![image](https://user-images.githubusercontent.com/3144571/167781561-d4566b02-1b55-4a00-bc57-15d3e9548a61.png)

**Comment by BWPanda** [comment]
Commented lines removed.

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/3232 into 1.x and 1.22.x. Thanks @BWPanda, @stpaultim, @oadaeh, @alexfinnarn, and @jenlampton!

**Comment by klonos** [comment]
@BWPanda @quicksketch can we please also merge [this tiny follow-up](https://github.com/backdrop/backdrop/pull/4198) which accounts for LTR as well?

Before:
![image](https://user-images.githubusercontent.com/2423362/190024339-6677741b-5341-42b7-8e8d-c511b9281a47.png)

After:
![image](https://user-images.githubusercontent.com/2423362/190024609-ed48eba0-64b7-4b2e-ae42-2304a8208596.png)

**Comment by quicksketch** [comment]
Thanks @klonos, looks good to me!

**Comment by BWPanda** [comment]
Thanks @klonos & @quicksketch. I merged https://github.com/backdrop/backdrop/pull/4198 into 1.x and 1.22.x.
