### ISSUE TITLE
Update core/includes/transliteration/bg.php to follow the up-to-date transliteration standards for Bulgarian

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1604]
todo from https://github.com/backdrop/backdrop-issues/issues/1544#issuecomment-180761933

> Only one note: in file bg.php line 67 (`0x044D => 'e'`) is unnecessary. This is for Russian letter (a.k.a. "э") . It is not used in Bulgarian. This is not an error - this line is not used in Bulgarian transliteration. This line can be deleted in next updates for simplicity.

- - - - - - - - - - - 

<strike>PR by @chuyich - backdrop/backdrop#3339</strike> (obsolete)

<strike>Alternate PR that does more (for discussion) by @stpaultim backdrop/backdrop#3350</strike> (obsolete)

Alternate PR by @amilenkov with new standard https://github.com/backdrop/backdrop/pull/3355

**Comment by chuyich** [comment]
Hi, I'm working on this #GHC20

**Comment by ArchanaAnand0212** [comment]
a pull request from @chuyich created here: https://github.com/backdrop/backdrop/pull/3339

**Comment by stpaultim** [comment]
This is an interesting issue in that I don't know how to test it. I'm going to flag a member of our community from Bulgaria to take a look at this. Atten - @VasasA 

I will add the labels required and wait for someone with some knowledge of Bulgarian to comment.

**Comment by VasasA** [comment]
I'm from Hungary. Sorry...

**Comment by klonos** [comment]
Yup, wrong country. @stpaultim I think that you meant to ping @amilenkov 😅

**Comment by amilenkov** [comment]
Hello, I'm online and I'm ready to help, but I don't know how - I'm not a programmer and I use github only as a source of information, but not as a tool for working with code. I'm more of a graphic designer and copywriter than a programmer.

I am from Bulgaria, I develop Backdrop CMS sites in Bulgarian and other languages, but for 4 years with each new version of Backdrop my first job is to replace the file bg.php in core / includes with my own version for more correct transliteration in order to better search engine optimization.

**Comment by amilenkov** [comment]
And I've been doing this since the time I worked with Drupal 7 - there the corresponding file is x04.php in the transliteration module.

**Comment by VasasA** [comment]
@amilenkov I think this is the simplest test methode: There is a [link](http://3339.backdrop.backdrop.qa.backdropcms.org), and a user name (admin) with password (o8WFeu4F) on the [page of the pull request](https://github.com/backdrop/backdrop/pull/3339#issuecomment-702375818). Please login, and test the bg.php
If not work, download the modified Backdrop from [this page](https://github.com/chuyich/backdrop), and test it.

**Comment by amilenkov** [comment]
@VasasA I did a check in the first way and wrote about it at

http://3339.backdrop.backdrop.qa.backdropcms.org/bg/a-b-v-g-d-e-zh-z-i-j-k-l-m-n-o-p-r-s-t-u-f-x-c-ch-sh-sht-y-j-ju-ja

**Comment by amilenkov** [comment]
@VasasA I did a second test by downloading from the above link backdrop-1.x.zip, unzipped and compared line by line the contents of bg.php with the version of this file from backdrop-1.17.1.

The only difference is that from the version of bg.php for backdrop-1.17.1 line 67 has been dropped

  0x044D => 'e',

And this is correct because it is a letter of the Russian alphabet, which is not used in Bulgarian. I wrote about this some time ago on GitHub.

In everything else, however, the two versions of bg.php are the same and for me the problem of making a better and search engine-optimized transliteration for Bulgarian remains unsolved. This is not achieved with this version of bg.php.

**Comment by VasasA** [comment]
@stpaultim  @ArchanaAnand0212  Here is the suggested bg.php, what is published by @amilenkov on the [test site](http://3339.backdrop.backdrop.qa.backdropcms.org/bg/a-b-v-g-d-e-zh-z-i-j-k-l-m-n-o-p-r-s-t-u-f-x-c-ch-sh-sht-y-j-ju-ja).
Antony's experience:
>From 2017-2018 I started to replace in my websites bg.php with my own version of transliteration and I was convinced in practice that Google indexes and understands transliterated addresses in Bulgarian much better... 
... Better SEO transliteration (and much more often used by Bulgarian sites or when people type Bulgarian on a keyboard that does not contain Cyrillic):

```php
/**
 * @file
 * Bulgarian language transliteration overrides.
 * According Google transliteration rules
 */
$overrides['bg'] = array(
  0x0410 => 'A',
  0x0411 => 'B',
  0x0412 => 'V',
  0x0413 => 'G',
  0x0414 => 'D',
  0x0415 => 'E',
  0x0416 => 'Zh',
  0x0417 => 'Z',
  0x0418 => 'I',
  0x0419 => 'J',
  0x041A => 'K',
  0x041B => 'L',
  0x041C => 'M',
  0x041D => 'N',
  0x041E => 'O',
  0x041F => 'P',
  0x0420 => 'R',
  0x0421 => 'S',
  0x0422 => 'T',
  0x0423 => 'U',
  0x0424 => 'F',
  0x0425 => 'H',
  0x0426 => 'C',
  0x0427 => 'Ch',
  0x0428 => 'Sh',
  0x0429 => 'Sht',
  0x042A => 'A',
  0x042B => 'J',
  0x042C => 'J',
  0x042E => 'Yu',
  0x042F => 'Ya',
  0x0430 => 'a',
  0x0431 => 'b',
  0x0432 => 'v',
  0x0433 => 'g',
  0x0434 => 'd',
  0x0435 => 'e',
  0x0436 => 'zh',
  0x0437 => 'z',
  0x0438 => 'i',
  0x0439 => 'j',
  0x043A => 'k',
  0x043B => 'l',
  0x043C => 'm',
  0x043D => 'n',
  0x043E => 'o',
  0x043F => 'p',
  0x0440 => 'r',
  0x0441 => 's',
  0x0442 => 't',
  0x0443 => 'u',
  0x0444 => 'f',
  0x0445 => 'h',
  0x0446 => 'c',
  0x0447 => 'ch',
  0x0448 => 'sh',
  0x0449 => 'sht',
  0x044A => 'a',
  0x044B => 'j',
  0x044C => 'j',
  0x044E => 'yu',
  0x044F => 'ya',
);
```

**Comment by stpaultim** [comment]
@VasasA @amilenkov 

Sorry, but I don't know anything about transliteration - so this is very confusing for me. 

@amilenkov - Please tell me if I understand correctly:

1) The change in the Pull Request is correct.
2) That you have been replacing this file anyway because there are many other problems with this file. Your preferred settings are listed above?

NOTE: I created a Pull Request with the information provided by @amilenkov AND @VasasA to see if that is helpful. Please, check this out:
https://github.com/backdrop/backdrop/pull/3350

QUESTION: Is it possible for us to merge all these changes at once without breaking existing sites in Bulgarian?

**Comment by VasasA** [comment]
@stpaultim The PR 3350 is the same as the proposed changes by @amilenkov. Thank You! :+1:
> Is it possible for us to merge all these changes at once without breaking existing sites in Bulgarian?

Maybe @olafgrabienski and @amilenkov can answer the question.
I think we accept the authority of @amilenkov.

**Comment by amilenkov** [comment]
@stpaultim @VasasA

I also regret that I understand too little about programming and using GitHub :)

But if your question "The change in the Pull Request is correct." means that removing line # 67 from core / includes / transliteration / bg.php is correct, yes, it is correct and fill safe.

This line did not create any problems, this letter "э" with Unicode U+044D is not used in Bulgarian, it is used in Russian and maybe other Cyrillic languages, just this line of code is redundant when transliteration from Bulgarian to Latin (to text in English alphabet). 

Regarding the other changes in the transliteration from Bulgarian: 

The current state of bg.php is not wrong, it is just not well optimized for search engines. 

This is one of the transliteration methods for Bulgarian that I preferred and still use entirely when naming files on my computer or when uploading to a web server because in this way there is a clear direct correspondence between each Bulgarian letter and its transliteration letter or string with English letters. In other transliteration methods, which are rather phonetic, the same letter of the English alphabet is used to represent several Bulgarian letters and the reverse transliteration will not return the expression correctly in Bulgarian.

However, search engines are not interested in this, nor in government regulations, they monitor and comply with the most common practice of sites with Bulgarian pages and their URLs written in English letters. And they understand and index some URLs correctly, they recognize transliterated keywords in them, but they do not recognize and not index keywords with unusual or rarely used transliteration.

I suggest you leave this as it is at the moment. In the coming days or weeks I will do a new study and publish the result on this page as a PDF report. Or elsewhere, if you advise me where it is best to post.

There are Bulgarian government decisions on the transliteration of the Bulgarian language into Latin, there is separate legislation of the European Union, but users and creators of websites do not comply much with these norms and create their own rules. And search engines also do not comply with regulations, but follow the most common practice in the URLs of sites and have learned to understand certain ways of transliteration and do not understand others.

On the Internet, things are changing rapidly and what was appropriate in 2017-2018 (when I created my version of bg.php) may not be right today. Therefore, let me do a new study and I will share the result here.

In the meantime, as far as I understand, you can consider the question

> Remove line # 67 from core / includes / transliteration / bg.php since it's not used in Bulgarian.
> # 1604

for resolved and completed.

And about question: Is it possible for us to merge all these changes at once without breaking existing sites in Bulgarian?

As far as I know, I am the only user of Backdrop CMS in Bulgaria so far. I maintain a site for Backdrop CMS in Bulgarian, but the statistics so far do not report visits, except for random bounces.

There used to be 4-5 years ago a small but well-functioning Drupal community in Bulgaria. After the release of Drupal 8, it fell apart and its website http://www.drupalbg.org/ was closed.

I knew a lot of people there - some left Drupal and started working with various PHP frameworks, others switched to WordPress or other CMS. I also knew some long-term and experienced developers with Drupal 7 who are no longer alive.

I recently ordered and paid for a list of Drupal sites in Bulgarian, provided by www.wappalyzer.com - they sent me a list of 250 Drupal sites in Bulgarian. The list is not complete, it lacks some of my sites, others are presented, also others that I know they were made with Drupal are not represented, but it is a good starting point. I've been researching this list for the last few weeks. 

There are some large sites of big corporations and government agencies that are already on Drupal 8 and even 9. They are few. The predominant number are with Drupal 7 (and even found a few with Drupal 6 and 5) and most of them have not been updated for 2-3 or even 5 years (I'm checking CHANGELOG.txt). They are simply abandoned, there is no one to support them since Drupal 8 came out and the community fell apart. 

I was recently assigned to maintain a Bulgarian website with Drupal 7, which is not made by me, but the developer no longer works in Bulgaria (a very complex site, with many dozens of additional modules, dozens of Views, it will not be easy to convert it to Backdrop when needed). And my new client told me that she was looking for a very long time before finding out who could maintain her site with Drupal 7 in Bulgaria. There are offers from Bulgarians who work for large international web development corporations with Drupal 8 / 9, but their prices are impossibly unaffordable for small or medium businesses in Bulgaria.

So in my opinion the future for Backdrop CMS in Bulgaria is coming in the next few years. So there is no risk to damage existing sites with changing bg.php, and after I do research and suggest you well thought out and modern transliteration rules tailored to search engines, I guess we will be ready to offer better services to future users of Backdrop CMS in Bulgaria. This can safely wait a few more months.

**Comment by amilenkov** [comment]
@stpaultim @VasasA

In the last 3-4 hours I did a complete research for the correct transliteration in Bulgarian with a view to search engine optimization.

I believe that this article in Wikipedia should be taken as a basis, which is in English, but reflects exactly the Bulgarian legislation and practice at the moment:

https://en.wikipedia.org/wiki/Bulgarian_alphabet

Another source is this:
https://en.wikipedia.org/wiki/Romanization_of_Bulgarian

The table in first link in the third column shows the official transliteration according to the latest law of transliteration in Bulgaria and the file bg.php should be processed according to it. If this legislation is to be followed, changes are needed in bg.php.

A survey of top SEO experts in Bulgaria shows that this way of transliteration is also adopted by Google. For example, see here: http://www.seo-bg.com/seo-google-transliteration-transliteracia.php

There is only one exception, for the Bulgarian letter "ц" the official transliteration requires "ts", but in practice no one observes this and the English letter "c" is used for "ц" because when mathematics is studied in Bulgaria, the Latin letter "C", which is used in various formulas and calculations, is pronounced as "це". ts / ц sounds as in English "fits" 

In addition, the English letter C is not used to transliterate any other Bulgarian letter in the official transliteration and becouse it is "free" it is reasonable and economical to simply write "c" instead of "ts". This is done by almost all Bulgarians, not only when transliterating web addresses, but also when chatting in Latin without a Cyrillic keyboard or sending CMS messages - they write C as C.

This is why Google accepts it as normal and reads such transliterated Ц as C in addresses correctly. I did a lot of searches for Bulgarian keywords containing the letter Ц with transliterated expressions, in which Ц is written as C and Google always returned correct results on Bulgarian pages.

The reasonableness of this way of transliteration of Ц can also be seen from an older ISO standard from 1995 for the transliteration into Latin characters of Cyrillic characters, which also recommends transliteration of Ц by C

https://en.wikipedia.org/wiki/ISO_9

This ISO standard is also presented in the second column of the table from the first link, this column precedes the third column with today's official Bulgarian transliteration.

As a result, I propose that I make changes to the bg.php file in accordance with these facts and send it for testing, please write how to do it if you accept.

**Comment by VasasA** [comment]
@amilenkov Please try this description: https://backdropcms.org/news/creating-pull-requests-against-core-easy-noob-way

**Comment by indigoxela** [comment]
Wow, several overlapping and partly contradictory standards! I'm impressed. :smile:

@amilenkov provide a new bg.php any way you're comfortable with. This could be via a pull request, but if that's too unfamiliar for you, choose any other way.

**Comment by amilenkov** [comment]
@VasasA

Thanks for 
Please try this description: https://backdropcms.org/news/creating-pull-requests-against-core-easy-noob-way

I did what and as far as I understood, I got a test installation and everything works correctly there, here is an example of correct transliteration:

http://3355.backdrop.backdrop.qa.backdropcms.org/a-b-v-g-d-e-zh-z-i-y-k-l-m-n-o-p-r-s-t-u-f-h-c-ch-sh-sht-a-y-yu-ya

http://3355.backdrop.backdrop.qa.backdropcms.org/Upercase-A-B-V-G-D-E-Zh-Z-I-Y-K-L-M-N-O-P-R-S-T-U-F-H-C-Ch-Sh-Sht-A-Y-Yu-Ya

If something is wrong, please write me to fix it if I can, or to send a simple bg.php file.

**Comment by indigoxela** [comment]
@amilenkov Cool, many thanks!

Now we need to figure out a way to fix the failing tests (PathPatternBulkUpdateTestCase TransliterationTest) without being able to read or understand anything. :wink:

**Comment by indigoxela** [comment]
I found a funny way to test this using [Google translate](https://translate.google.com)

They provide a (sort of) transliterated version along with the translation.

- Бърз тест за всяка дума (translated)
- Bŭrz test za vsyaka duma (latin charset (sort of) version by Google)
- Brz-test-za-vsaka-duma (path alias by Backdrop)

Bŭrz  becomes Brz... @amilenkov is this correct?

**Comment by amilenkov** [comment]
@indigoxela

Yes, I know the ability of a Google translator to transliterate, and I studied it many times. However, this transliteration is incorrect and very uncertain. Yes, a text transliterated with roman letters in this Google way will be understood by most Bulgarians (from the educated who have studied most foreign languages with the roman alphabet), but they would never write it with roman letters that way.

For example, in the Bulgarian alphabet and on the keyboards for computers or smartphones in the Bulgarian language there are no diacritical marks, for example bŭrz - there are no such sign ŭ in the standard Bulgarian language / alphabet or keyboard when typing on a computer or even with old typewriters.

No Bulgarian, if he has to write the word "бърз" (that mean "fast") in English letters, will write it as Bŭrz - he will write it as barz or burz. The official transliteration introduced by Bulgarian law in 2009 is "barz". It is reasonable because the Bulgarian letters "ъ" and "а" are pronounced in many, almost identical ways. "ъ" really sounds similar as in English words "but" or "butcher".

I have carefully studied all aspects and I am convinced that what I proposed through

http://3355.backdrop.backdrop.qa.backdropcms.org

is the best way - fully compliant with the existing Bulgarian legislation and the most common practice that Bulgarians use to type Bulgarian text with an English keyboard. At the same time as well recognized by search engines.

Not only now, I have been thinking and reading about this for more than five years. I have examined all Bulgarian transliteration systems, in addition to the official one, there are at least a dozen other variants proposed at different times and by different scholars, government agencies or philological organizations.

I believe that I am competent for this. I am not a programmer, I was a philosopher in my higher education and I even taught philosophy for 6 years as a senior assistant professor at the largest Bulgarian university - Sofia University. 

That was a long time ago, I've been an entrepreneur and freelancer since 1991, and all I know about computers, prepress, graphic and web design is self-education. I've been trying to learn PHP for a few years now, but so far I've only managed to make a few simple games.

I have been making websites for 15 years and I have made many dozens with Drupal and for 5 years - with Backdrop.

**Comment by amilenkov** [comment]
@indigoxela

as about: Brz-test-za-vsaka-duma (path alias by Backdrop) - 

This is the way Backdrop transliterates Bulgarian if the Bulgarian language is not active to the page and the system perceives it as English or Language neutral - the letter Ъ is omitted altogether and does not appear in the transliterated string. Also, the letter Я is transliterated with "a", which is incorrect, correct is "ya".

In such cases the system does not use bg.php, but some other algorithm that I do not know where it is managed, and it is not necessary to know, you just need to activate the Bulgarian language and things happen according to bg.php.

**Comment by indigoxela** [comment]
@amilenkov I didn't mean to suggest Google translate as measurement, they're known to be unreliable. The intention was rather to do some useful testing, if possible. :wink:

> This is the way Backdrop transliterates Bulgarian if the Bulgarian language is not active to the page...

Ah, got it! That was my mistake, I forgot to set the node language for that page.

I'd say: "works for me", but we still need to fix that single failing test. (Which doesn't mean that you have to do that.)

`array('bg', 'първа статия', 'pyrva statija'),`

If I get it right, that should now actually become `parva statiya` instead?

**Comment by amilenkov** [comment]
@indigoxela

Yes! 'parva statiya' is OK.

**Comment by indigoxela** [comment]
> 'parva statiya' is OK.

Maybe you want to fix that test yourself? (And become a real core contributor :wink: )

The only thing you have to do is changing the expected transliteration [here](https://github.com/amilenkov/backdrop/blob/821bf5a379c93d35b06d7503393814d8b9e3b66b/core/modules/simpletest/tests/transliteration.test#L53) and push your changes.

If you don't feel "adventurous" enough, we can do it for you.

**Comment by amilenkov** [comment]
OK, I'm very interested even, but I'll try tomorrow morning (now it's 5:30 PM here and I have to go to work somewhere else).

**Comment by amilenkov** [comment]
@indigoxela

Changed line 53 = 'parva statiya' backdrop/backdrop#3363 

Is that what I had to do and is it OK?

**Comment by amilenkov** [comment]
I made it again in other way not creating new PR but editing this:

https://github.com/amilenkov/backdrop/blob/1.x/core/modules/simpletest/tests/transliteration.test

**Comment by stpaultim** [comment]
> I made it again in other way not creating new PR but editing this:

This is only a problem, because we now have two Pull Requests for one issue. Maybe a core committer can manage both. But, I think the better way to handle this is to do the following:

**Go here and make that final edit: https://github.com/amilenkov/backdrop/blob/patch-1/core/modules/simpletest/tests/transliteration.test**

I am pretty sure that if you edit it here, it will add this change to your existing PR instead of creating a new one. 

You already have a git branch "patch-1" on your fork of Backdrop for the current Pull Request - backdrop/backdrop#3355. If I am correct, you and edit any file on that branch and it will automatically update your Pull Request.

**Comment by indigoxela** [comment]
@amilenkov We're almost done, but your two PRs are a bit confusing. Mind to give it another stab and add your test change to your initial PR?

If it's too difficult for you, we'll take care of it.

**Comment by amilenkov** [comment]
@stpaultim @indigoxela

I did the editing you recommend, 

> 
Go here and make that final edit: https://github.com/amilenkov/backdrop/blob/patch-1/core/modules/simpletest/tests/transliteration.test

but if there are problems again, let the professionals in the community make the necessary changes, I don't want to waste any more your time and create more problems.

I promise not to do anything (editing code , PR) more in GitHub until I have studied some good guide for working with GitHub :-)

I just wanted to help with the transliteration in Bulgarian because this would be useful for future users from Bulgaria and probably my knowledge of at least Bulgarian could be useful to you.

**Comment by indigoxela** [comment]
> I did the editing you recommend

Hey, that's perfectly correct. :+1: You might have noticed, that the automated test is passing now.

> I promise not to do anything ... more in GitHub until I have studied ...

Don't worry, no one expects you to be a total Github expert from the beginning. Everyone of us started as newbie.

> ...this would be useful for future users from Bulgaria and probably my knowledge of at least Bulgarian could be useful to you.

That's the point. You help to solve a problem, none of us could fix. :wink:

Marking this as RTBC and setting a milestone. I'll update the issue title accordingly, as the issue has evolved a bit.

Please note: before this gets merged, a core committer will review it. That might take some time.

**Comment by stpaultim** [comment]
> I just wanted to help with the transliteration in Bulgarian because this would be useful for future users from Bulgaria and probably my knowledge of at least Bulgarian could be useful to you.

Keep reporting issues and don't be afraid to try and fix them. We are all learning...

Thanks for your expertise on this issue.

**Comment by VasasA** [comment]
@amilenkov Thank You very much for your accurate work! :+1: 
I have also just learned how to modify a PR from this issue. :smile:

**Comment by quicksketch** [comment]
This issue brings me joy watching the global participation to make a better Backdrop CMS experience.

Thanks @amilenkov, @chuyich, @ArchanaAnand0212, @indigoxela, @klonos, @stpaultim, and @VasasA for your work and collaboration!

I've merged https://github.com/backdrop/backdrop/pull/3355 into 1.x and 1.17.x.

It also seems this makes the same suggestions as suggested in https://github.com/backdrop/backdrop-issues/issues/3314, so I've closed that issue as a duplicate.

Extra extra thanks to new contributors and volunteers @chuyich and @ArchanaAnand0212 for re-igniting the work on this issue.
