### ISSUE TITLE
CKEditor - unable to add text after a link without editing source.

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#1612]
I had a page with some linked text (see screenshot below) and I wanted to add some text after it, without it becoming part of the link. I could not do this in WYSIWYG view and had to switch to source in order to insert text immediately after the link.
![edit basic page admin page - deben rowing club 2016-02-13 07-57-23](https://cloud.githubusercontent.com/assets/10559274/13026673/850db13e-d228-11e5-9b95-9af5c10e290e.png)

---

PR by @quicksketch: https://github.com/backdrop/backdrop/pull/1863

**Comment by serundeputy** [comment]
@Graham-72 

I could not reproduce this.

* I configured the `Filtered HTML` format to use the link widget.
* Went `node/add/page`
* Wrote some text
* Added a link
* Added text after the link (it was not linked)

Can you list the steps that lead you to observe this issue?
Does it happen to you if you follow the above steps?

I'm using backdrop `1.x`; are you using a different version?

thanks,
~Geoff

**Comment by Graham-72** [comment]
@serundeputy 

Thanks for looking at this. I am using backdrop 1.3.2, with Full HTML format using CKEditor.
I followed your steps and still had the problem as shown below.
I wonder whether there is an interaction between filters?
![create basic page - graham s backdropcms trial 2016-02-14 05-29-41](https://cloud.githubusercontent.com/assets/10559274/13032060/bcbf354e-d2dc-11e5-8240-84fa82feec20.png)

**Comment by klonos** [comment]
> had to switch to source in order to insert text immediately after the link.

@Graham-72 that's why it's useful to place the "unlink" button in the toolbar:

![backdrop-ckeditor_toolbar_buttons-remove_link](https://cloud.githubusercontent.com/assets/2423362/13032600/33ffdcc4-d34d-11e5-940c-a4abb270fea5.png)

This way, you can select the part of the text tat you do not want as link and remove the link from it using this button.

I'm also on 1.3.2, and while giving this a shot, I found #1613 and this one (notice the before-mentioned unlink button becoming active each time this bug comes into effect):

![backdrop-ckeditor-link_activate_at_end_of_text_bug](https://cloud.githubusercontent.com/assets/2423362/13032656/44355676-d34f-11e5-9f5a-ae7f5e728e4c.gif)

So what happens here is this:

- I have intentionally added a full stop at the end of the phrase. I did this in order to troubleshoot whether the bug was triggered and the link mode activated if the full stop was deleted (by hitting backspace in the keyboard).
- The link mode seems to be triggered randomly, but that is not the case. A closer look reveals that when the caret is placed between the end of the text and the full stop, it all depends to the position of the mouse cursor when the mouse-up event is triggered (mouse button released). If the mouse cursor happens to be *after* the cursor (between the cursor and the full stop actually), then the link mode is not activated. If the mouse cursor is ether precisely on top of the caret or before it (between the text and the caret), then the link mode is activated (you can see the "unlink" toolbar button activated).

...so here you go. Needs to be fixed upstream you think?

**Comment by klonos** [comment]
...similarly what happens if you use the keyboard left/right arrow keys to navigate to the end of the text of the text with the link:

- If you move from the left towards the right, when you reach the end of the linked text, the link mode is still active.
- If you move from the right of the text towards the left, when you reach the linked text, the link mode is inactive:

![backdrop-ckeditor-link_mode_using_keyboard-text_to_the_right_of_the_link](https://cloud.githubusercontent.com/assets/2423362/13032762/63a26c84-d353-11e5-9a5f-608e46e58f4d.gif)

That all of course assuming that the intention was to reach the end of the linked text. The situation and conditions/results are reverted if one tries to add text to the beginning of a link:

- If you move from the right towards the left, when you reach the start of the linked text, the link mode is inactive.
- If you move from the left of the text towards the right, when you reach the beginning of the linked text, the link mode remains active:

![backdrop-ckeditor-link_mode_using_keyboard-text_to_the_left_of_the_link](https://cloud.githubusercontent.com/assets/2423362/13032767/70d5577c-d353-11e5-91f7-6b2034148969.gif)

The trick here is that I used that full stop @Graham-72 :wink:

![yes_i_know_suspenders](https://cloud.githubusercontent.com/assets/2423362/13032768/79bef1ae-d353-11e5-8ded-0f27de279dea.jpg)

**Comment by klonos** [comment]
...of course, if the link is at the end of the line and there is no way to move either the mouse cursor or the keyboard caret to the end of it (no non-linked full stop for example), then the added text will always be linked. Again, the "unlink" toolbar button comes to the rescue in such cases.

**Comment by Graham-72** [comment]
@klonos thank you for your tip about using the unlink tool, I shall definitely make sure to have this available in the future.
Thank you also for your brilliant demonstrations of what is happening. However, there is one odd thing that I see happening. If I add one space after a link it is not appearing underlined as part of the link, but if I type a second space they both become underlined. But if I type a different character (or full stop) immediately after a link, it is immediately underlined and clearly part of the link. So it would seem that a space is receiving some special treatment? 
In my ideal world the WYSIWYG editor would interpret the addition of a space as an indication that I am adding text not to be included in the link, but perhaps my expectation is too high.

**Comment by mahiaayush** [comment]
Hi All,

I am creating a functionality in my custom editor similar to insert link. I have created the plugin which generates a tag in the editor named (ext-link). Currently, I am facing an issue that, once inserted I am not able to insert space after the <ext-link> element as the cursor is still getting inside the tag. I have gone through the below URL and tried to include that code mentioned over there, but didn't worked for me.
URL: "https://dev.ckeditor.com/ticket/5978"

Sample Code:
   " if(event.data.keyCode== 32 && a.getAscendant("ext-link",true)){
					    var text = a.getText();
							var length = text.length;
							var selection = EditorInstance.document.getSelection();
							var range = selection && selection.getRanges()[0];
							var range = selection && selection.getRanges()[0];
							var ranges = selection.getRanges();
							if( range.collapsed && length == range.endOffset) {
								var collapsedElement = new CKEDITOR.dom.text( '' );
								// Insert the empty element into the DOM at the range position.
								var parent = a.getParent();
								parent.append( collapsedElement );
								range.startContainer = collapsedElement;
								range.startOffset	= 0;
								range.endContainer	= collapsedElement;
								range.endOffset		= 0;
								selection.selectRanges( ranges );
								ev.cancel();
							}
							if(range.startOffset == range.endOffset && length == range.endOffset) {
								//Figure out how to step out of the a node but still be in the parent node
								event.cancel();
						}"

Can any one help me here.

Thanks in advance,
Aayush Mishra

**Comment by quicksketch** [comment]
I can reproduce this issue still on the latest 1.x of Backdrop, and I see it on the CKEditor demo at http://nightly.ckeditor.com/latest/standard/ckeditor/samples/

- Insert cursor into the editor.
- Type `foo`
- Highlight `foo` and click link button.
- Set URL to `foo`. Save dialog.
- This results in `foo` being selected. Hit the right-arrow key to move cursor after the word.
- Type ` bar`.

Expected `foo` is linked. `bar` is not. Instead both are linked.

This issue may be rooted in CKEditor, but with our custom link implementation, I think it's possible for us to change the way it works.

**Comment by quicksketch** [comment]
PR filed at https://github.com/backdrop/backdrop/pull/1863 that changes the behavior of inserting links. After creating a new link, the cursor is moved *after* the link element. So the next character the user types is not a part of the link.

I think this behavior is more desirable than the current approach, where the link is selected. The current behavior may result in the user typing and wiping out the word they just made into a link. The new behavior lets the user continue typing uninterrupted without futzing with unlinking the next word. If they want the next word to be part of the link, they need to delete back into the previous word and continue typing from there.

FYI, this approach matches the behavior of Google Docs. The selection is moved after the word and not linked.

![google-docs-link](https://cloud.githubusercontent.com/assets/100206/25730946/63b80c7c-30f6-11e7-97cc-4411a495d55f.gif)

Testing on the PR would be appreciated.

**Comment by Graham-72** [comment]
Patch works on my test site. 👍 Thanks, excellent.

**Comment by Dinornis** [comment]
Although I was not able to reproduce the problem I do like the improvement in the PR.

**Comment by Graham-72** [comment]
I am finding the problem is still there if the fix is not applied, so please merge the PR.

**Comment by olafgrabienski** [comment]
Tested it in the PR, using Google Chrome on Mac OS X, looks good. One issue though: In the code is inserted a non breaking space after the link. Example:

`Lorem ipsum dolor sit amet. <a href="http://www.example.com">Lorem</a>&nbsp; ipsum dolor sit amet ...`

**Comment by Graham-72** [comment]
That's interesting, because with Windows 10 in Firefox or Chrome I can add a normal space, not non-breaking. In fact any other character will do. The script is not adding the space, just moving the insert point.

**Comment by Dinornis** [comment]
You can see the non breaking space in the source at http://1863.backdrop.backdrop.qa.backdropcms.org/about
I edit the node in OSX Safari. After applying the link I just hit space and typed the rest of the line.  Note sure how the `&nbsp;` gets inserted.

**Comment by Dinornis** [comment]
I just did another test at http://1863.backdrop.backdrop.qa.backdropcms.org/linktest and it seems the `&nbsp;` anomaly is browser related, not happening in OS X Firefox.

**Comment by quicksketch** [comment]
Looks like the `&nbsp;` issue is a Webkit (Chrome/Safari) issue in CKEditor itself. I think https://dev.ckeditor.com/ticket/11415 is reporting the same issue. I can see it in Chrome on Linux as well.

I tried this locally *without* the PR and it still exists there as well. So I think we may either wait for CKEditor to fix this, or make an issue to see if we can work-around the problem.

**Comment by quicksketch** [comment]
I've merged https://github.com/backdrop/backdrop/pull/1863 into 1.x and 1.6.x. Thanks everyone for the testing!
