### ISSUE TITLE
Not standard layout

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1629]
Hi!
If there is no an layout like this one then should I do it myself?
Thank you!

![l1](https://cloud.githubusercontent.com/assets/13515302/13162688/3cc36bc2-d6c8-11e5-8991-5ef7b7f2513b.gif)

![l2](https://cloud.githubusercontent.com/assets/13515302/13162689/3cc3f7ae-d6c8-11e5-8254-491cba49a17a.gif)

**Comment by Graham-72** [comment]
I think you might find that Radix Bartlett would do this for you. I have used it for something similar. Of course, you need to modify the CSS to get the relative column widths that you need.

https://github.com/backdrop-contrib/radix_layouts

**Comment by klonos** [comment]
@Graham-72 you beat me to it :wink:

**Comment by bd0bd** [comment]
@Graham-72, thank you! This is exactly what I have did two days ago.
But it is different from what I need.
![l](https://cloud.githubusercontent.com/assets/13515302/13186349/b0ab6fe0-d767-11e5-8f1f-055ec708ed17.gif)

**Comment by Graham-72** [comment]
You do not have to use every region. It seems to me that to meet your required layout you should ignore the 'Header' and put those four blocks in the region named 'Content header'.

**Comment by bd0bd** [comment]
Yes, I understand, thank you!
It's not kosher way :)
But *Page title* should not be above **Sidebar**, it should be in **Content Column 1**.
Also, the default Bartik theme does not work within this layout:
![l2](https://cloud.githubusercontent.com/assets/13515302/13186936/421ccf8a-d76a-11e5-9a63-9e1f82e3ae9a.gif)

**Comment by Graham-72** [comment]
I'm not sure what is kosher in this context! 
Yes, Bartik out-of-the-box will not work and you have to modify CSS and, to get the page title in the required place, modify the template a small bit. This is what I have done.

**Comment by bd0bd** [comment]
Not Kosher - I mean this is somewhat not very right way to do :)
Sure, I can modify the template.
Thank you very much for support!

**Comment by Graham-72** [comment]
> I mean when something is done not very right way

I have come to the view that adapting themes is very much the right way to produce one's own style of site.

Also, I am very much respecting your pioneering work with a multi-lingual site. Good work which will help many people I am sure.

**Comment by bd0bd** [comment]
> I have come to the view that adapting themes is very much the right way to produce one's own style of site.

May be. Thank you!

**Comment by klonos** [comment]
I agree with @Graham-72 here. You'll need to either sub-theme Bartik (do not edit it directly because when you upgrade Backdrop to a newer version, you'll lose all your custom code) or copy the layout that matches the most your target design and then edit it to your specific needs (replace the "Content Header" region with "Header" and remove the main header for example). Sometimes you'll need to do both sub-theming and design a custom layout in order to achieve close to 100% of what you're after.

Main point is that themes and layouts included with core are meant to be used either as is for simple designs by less advanced users or as starting points (templates) for more advanced themers.
