### ISSUE TITLE
Trouble installing new layouts 

### ISSUE THREAD

**Issue by maxmeno** [backdrop/backdrop-issues#1688]
Maybe it's me, but I can't add any layout to the default ones.

First I tried to install them from /admin/structure/layouts/install 

The first time the response for Radix was _project not recognized_, while on a second attempt I got this:
_Archivers can only operate on local files: temporary://update-cache-8a32889f/master.zip not supported_

For senjo, two_column_flexible, juiced_up_layouts the system always said that they were already installed. But I had never installed them.

(Sorry if this is not new, but I find it hard to search on the Github issue queue)

I then tried following the instructions from https://backdropcms.org/guide/layouts
The /layouts folder has now four subfolders:
juiced_up_layouts
radix_layouts
senjo
two_column_flexible
with all the README.md files where they are supposed to be. 

None of those is seen by BD when I try to work on a new layout or to modify an existing one.

Any idea?

**Comment by klonos** [comment]
You seem to have stumbled on our layout terminology problem (#998)...

So there are (screenshots pending in order to make this more understandable):

- Layout **packages**. These are the things that are listed on GitHub or backdropcms.org and you can download them in a .zip format.
- Layout *packages* may include one or more layout **designs** or **blueprints** (so the Radix layout *package* for example includes the "1 column", "2 columns", "2 columns flex", "2 columns flex flipped" layout *designs*).
- Once you have downloaded and installed a layout *package*, the layout *designs* it includes become available for you to choose when you want to create a new layout in the **Layout UI* (the admin page of your site where you manage its layouts).
- So in order to create a **layout** you need to specify a layout *name*, a layout *design*, a path and (optionally) visibility conditions.
- Now, if you are a coder/themer, you also need to know that each layout *design* included with a layout *package* consists of a .info file and a .tpl.php file. The .tpl.php file is called a layout **template**.

So your problem here is (I guess) that you expected that after installing a layout *package*, a layout would magically appear as available in your Layout UI page (```/admin/structure/layouts```) along with the "Default Layout" and "Default Administrative Layout" layouts that come out of the box when you install Backdrop. If so, then you are wrong... what you need to do is to create a new layout by clicking the "+ Add layout" link. Then you will come to a screen where it asks you to select a layout name, *design* (this is where you actually see what you have installed in the form of thumbnails) and path. Save that form and you have yourself a new layout that you can add blocks to.

**Comment by maxmeno** [comment]
> what you need to do is to create a new layout by clicking the "+ Add layout" link

I did.
No new _layout design_ is available when I start creating a new layout or to modify one of the existing ones - just the 4 default ones.

I was interested in one of the more complex designs from Radix, I only tried to install the other three to see if maybe something was wrong with the Radix package.

Not knowing the long discussion you had for #998, I was expecting things to work differently. The layout package installation through the UI does not work, apparently, and one does not have a chance to know if a package has been already installed or not... There should be a list somewhere of all the installed packages, I think.

**Comment by gifad** [comment]
> There should be a list somewhere of all the installed packages

You can find informations at the bottom of `admin/reports/updates`

**Comment by maxmeno** [comment]
That page only lists BD core + modules + themes.
No layout packages in sight

**Comment by gifad** [comment]
> That page only lists…

It would list layouts, if any were installed !

**Comment by maxmeno** [comment]
So, I'm back at square one…

a) if I try installing a layout package from `/admin/structure/layouts/install` , either via URL or via upload, DB tells me that's **installed already** (but the `root/layouts` folder was empty...)
b) I manually installed some packages (and now I have 4 folders in `root/layouts`), but
c) no layouts are listed at `/admin/reports/updates`
d) if add a new layout or try to modify an existing one, only the core layout designs are available to be selected.

What can I try next?

**Comment by serundeputy** [comment]
Hi @maxmeno 

I was just testing this out and I can confirm what you report, however, a cache clear solved if for me.

* Download a theme say `senjo`.
* unzip it
* put it in `BACKDROP_ROOT/layouts/senjo`
* Now if you visit: `/admin/structure/layouts/add`
  * the new `senjo` layout does not show up as an option
* Clear cache from menu `Home | Flush all caches`
* Now visit: `/admin/structure/layouts/add`
* The `senjo` layout is now available

You can simplify this process using drush w/ the [backdrop/drush](https://github.com/backdrop-contrib/drush) extension:

* `drush dl senjo`
* `drush cc all`
* Visit `/admin/structure/layouts/add` and the layout(s) will be available to you.

Hope this helps.

thanks,
~Geoff

**Comment by maxmeno** [comment]
It did help, thanks a lot, @serundeputy 
Cache clearing, the good old cure-all remedy ;-)

I didn't need to re-install anything, all the layout designs showed up right away.
Maybe it could be a good idea mentioning this extra step in the documentation.

Two things left. 
1) The two layout design out of the Radix package (the only ones that I really needed and I had manually installed), _Radix Sanderson_ and _Radix Sanderson Flipped_ are available to use but not listed in `/admin/reports/updates`: could this be because I did not install the whole package?
2) Is it a known fact that installing layouts via the UI does not work, yet?

Thanks again, I can move forward now.

**Comment by serundeputy** [comment]
Hell0 @maxmeno 

> 1) The two layout design out of the Radix package (the only ones that I really needed and I had manually installed), Radix Sanderson and Radix Sanderson Flipped are available to use but not listed in /admin/reports/updates: could this be because I did not install the whole package?

I think they are not listed on the updates page because there is no release of `radix_layouts` layout package, but that page does not matter to use the layout.

Just download the `radix_layout` package, extract it and put it in `BACKDROP_ROOT/layouts`, clear cache and the `Radix Sanderson` and `Radix Sanderson Flipped` will be available as a choice when you are adding a layout `/admin/structure/layouts/add` or editing an existing layout.

-----

> 2) Is it a known fact that installing layouts via the UI does not work, yet?

This one depends on your server set up and having FTP configured on your server.  The handbook at https://backdropcms.org/guide/modules has this to say about it:

> 2. Automatically through the user interface (may not work on many types of servers)

Having said that I've never used the UI to install module in Drupal or Backdrop.  I don't have FTP configured anywhere to test this.  I always use ssh, drush and git to manage the codebase.

**Comment by maxmeno** [comment]
Just to close the issue:
I have some Drupal sites on the same server and I do module upgrades through the UI, no problem. If this does not work in DB it cannot be because of the server config.
Also, you pointed to a page that talks about modules - the corresponding page about layouts,
https://backdropcms.org/guide/layouts
does not mention installation through the UI at all.

**Comment by klonos** [comment]
> Cache clearing, the good old cure-all remedy ;-)
> 
> I didn't need to re-install anything, all the layout designs showed up right away.
> Maybe it could be a good idea mentioning this extra step in the documentation.

Most of the issues reported here stemmed from the fact that cache needed to be cleared. This was sorted in #984 though, which makes it so that caches are automatically cleared for users, when new layout templates are added via the Project Installer.

> Also, you pointed to a page that talks about modules - the corresponding page about layouts, https://backdropcms.org/guide/layouts does not mention installation through the UI at all.

I have filed #3909 to document that themes and layouts can be installed via the admin UI (Project Browser).

I will go ahead and close this old issue. @maxmeno if still having problems with the latest version of Backdrop, can you please file separate issues for them? ...a lot has changed in the past 3+ years 😅
