### ISSUE TITLE
Layout hooks do not pass correct Layout object

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#1700]
layout.api.php incorrectly states : 
`function hook_layout_presave(Layout $layout)`
the argument is actually an array.

Additionally, I'm afraid that other modules implementing `hook_layout_insert` or `hook_layout_update` will be passed unaltered, unsaved, data.
(the altered data are assigned to the embedding Config object, not to the Layout object itself)

---
PR by @docwilmot https://github.com/backdrop/backdrop/pull/1842

**Comment by klonos** [comment]
> ...`hook_layout_presave` or `hook_layout_presave`...

??

**Comment by gifad** [comment]
Sorry for the typo, issue summary edited; thanks.

**Comment by klonos** [comment]
No worries :wink:

**Comment by docwilmot** [comment]
This is still true. Assigning to next bug fix.

**Comment by Gormartsen** [comment]
level up. 
I found out it as well)

**Comment by jenlampton** [comment]
Pushing this to the 1.6.2 milestone since there's no PR and we are releasing 1.6.1 tonight.

**Comment by docwilmot** [comment]
Pushed a PR,
But I simplified the invocation of `hook_layout_presave($layout_name, array $layout)` to `hook_layout_presave(Layout $layout)` (as it should be according to `layout.api.php`) by removing the unnecessary `layout_name`.

My thinking is to fix the hook we'd need to be breaking APIs either case (converting from array to object will break anything already using the hook), so why not correct everything in one go?

Will need to fix tests if this is acceptable.

**Comment by docwilmot** [comment]
tests fixed

**Comment by serundeputy** [comment]
@docwilmot I'm going to defer to @quicksketch 

> hook_layout_presave(Layout $layout) (as it should be according to layout.api.php) by removing the unnecessary layout_name.

This is an API change.  @quicksketch given that it is a bug and Layouts themselves are an API change compared to D7 API can we put it in the `1.x` cycle?

Or do we have to find a way to correct this with API change?

**Comment by docwilmot** [comment]
The whole thing is broken actually, so I dont think any of the changes avoid an API change.
- we need to change `array $layout` to `Layout $layout`. 
- remove the unnecessary `$layout_name`
- change the Layout info passed in `hook_layout_insert/update()` to the object *after* save rather than the object before save.

Any one of those are API changes; my thought is that it makes little sense fixing one and not all.

**Comment by jenlampton** [comment]
I'm with @docwilmot, let's fix the broken API, even if that means changing it. If we don't, no one can use the API in 1.x :)

**Comment by quicksketch** [comment]
I think this change is good. The summary states the situation pretty well. Any changes made during hook_layout_presave() don't get passed to hook_layout_insert/update().

These hooks were added in Backdrop 1.2, in https://github.com/backdrop/backdrop-issues/issues/767. 

The API change looks acceptable to me to solve the problems in the API, but the implementation is still a bit off. Any changes made to the `$layout` object won't be saved into the `$data` variable, and thus not saved to config. We need to rearrange the hook invocation so that it happens prior to `$data` being created.

**Comment by quicksketch** [comment]
Additionally, this change would make it so that `hook_layout_insert()` is never called, because the layout will no longer be "new" after it's been saved and then loaded fresh.

```
    $new_this = layout_load($this->name);
    if (!empty($this->is_new)) {
      $new_this->invokeHook('insert');
    }
    else {
      $new_this->invokeHook('update');
    }
```

We desperately need tests to cover these hooks. The current implementation is broken, but the new one is also in different ways.

**Comment by docwilmot** [comment]
> We need to rearrange the hook invocation so that it happens prior to $data being created

True 
> hook_layout_insert() is never called, because the layout will no longer be "new" after it's been saved

[Sounds familiar](https://github.com/backdrop/backdrop-issues/issues/2654)

**Comment by quicksketch** [comment]
As a bug, we can commit a fix any time, so this isn't held up by our 1.7.0 release deadline. However, as an API change I'd like this to land on a minor release rather than a bugfix release. We shoot for fixing between feature freeze (May 1) and release (May 15).

**Comment by quicksketch** [comment]
Thanks @docwilmot for updating the PR. I've merged https://github.com/backdrop/backdrop/pull/1842 into 1.x for 1.7.0.

This needs a change record to indicate the API change.

**Comment by quicksketch** [comment]
Change record filed at https://api.backdropcms.org/node/44962.
