### ISSUE TITLE
Demo Backdrop CMS

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1702]
Why not to make a demo-site of Backdrop CMS at https://backdropcms.org ?
Demo-site - with full admin control.
Anyone could quickly test admin panel etc.
Add/delete pages etc, almost all the things admin can do.
I know (from my many years experience) it will help to promote Backdrop, will attract new users who never used Drupal or other CMSs before or who would like to switch from another CMS to Backdrop.

**Comment by klonos** [comment]
Hello @bd0bd a couple of things:

1. We only file issues about the actual code of Backdrop (the CMS product) here. For issues specific to backdropcms.org (the website), please file issues here:

2. In backdropcms.org there is already a link to launch a full-fledged Backdrop demo site in [Pantheon](https://pantheon.io) (account required, but it's free)

3. There's already an issue for this here: https://github.com/backdrop-ops/backdropcms.org/issues/172 (that's for testing modules, themes and layouts) and a somehow related one here: https://github.com/backdrop-ops/backdropcms.org/issues/5 (for testing pull requests). You can follow these issues for when there's something available.

Given all the above, I'll take the liberty to close this issue here. Hope it's OK with you.

**Comment by bd0bd** [comment]
>In backdropcms.org there is already a link to launch a full-fledged Backdrop demo site in Pantheon (account required, but it's free)

Yes, I am sorry for off-top :)

It is a headache for a user to register.
It is something like a wall.
A newcomer can not know about this demo - there is no any visible information about the demo on the https://backdropcms.org/
SET UP ON PANTEON - this is not clear what this is all about, would be right to rename it to DEMO - this is simple and understandable for people.

**Comment by klonos** [comment]
> SET UP ON PANTEON - this is not clear what this is all about, would be right to rename it to DEMO

:wink: 

> It is a headache for a user to register.
> It is something like a wall.

I realize this is something that people might not want to do or simply find hard to do, but that's what we have available at the moment. I'm afraid you'll simply either use Pantheon (again: it's free) or wait till we build something like simplytest.me ...but that may take some time.

**Comment by bd0bd** [comment]
Personally for me it is not important now cause I am not a newcomer.

But I know this option will help Backdrop to attract new users and promote Backdrop.
I say **I know** because I know :)

**simplytest.me** - this is not enough good solution.
Good solution - a button DEMO and nothing more. After a person press this button on Backdrop demo site is installed and launched within 30-90 seconds.

Thank you!

**Comment by klonos** [comment]
> simplytest.me - this is not enough good solution. ...After a person press this button on Backdrop demo site is installed and launched within 30-90 seconds.

That's exactly what simplytest.me does. I don't get what you don't like about it.
