### ISSUE TITLE
[UX] make page title into it's own block (containing also tabs & action links)

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1704]
Follow up to https://github.com/backdrop/backdrop-issues/issues/952

[UX] One of the limitations of the layout system in 1.x is that you can't drag-and-drop a page title to a specific part of the page. I often find myself creating custom layouts (by copying those provided) simply because I need my title to be in a slightly different part of the page.

[DX] There are only a few variables left in the layout template that are not immediately intuitive when looking at the code. For the most part, a layout contains only page layout elements. The exception to that rule are the following variables: `php $title_prefix, $title, $title_suffix, $tabs, $action_links`.  These variables are often a mystery to people new to creating layouts, and when omitted can wreak havoc on a site.

Recommended solution:

By creating a "Page title" block that contains roughly the following code, we can solve both these problems:

``` php
<a id="main-content"></a>
<?php print render($title_prefix); ?>
<?php if ($title): ?>
  <h1 class="page-title">
    <?php print $title; ?>
  </h1>
<?php endif; ?>
<?php print render($title_suffix); ?>

<?php if ($tabs): ?>
  <div class="tabs">
    <?php print $tabs; ?>
  </div>
<?php endif; ?>

<?php print $action_links; ?>
```

This can be done by providing a specific page-title.tpl.php file, or a theme function that includes all three concepts (page title, tabs, action links) and calling it from inside a single block.

I checked all the layouts in core and in radix_layouts, and these things are always together in all of those layouts. I think it is a safe assumption to make that the tabs and action links always be somewhere near the title. If people want to place them elsewhere, then they can do so using theme functions, or by providing their own custom blocks.

---
PR from @docwilmot at https://github.com/backdrop/backdrop/pull/1782

**Comment by klonos** [comment]
Question: what are `$title_prefix` and `$title_suffix` actually printing and why aren't they wrapped in an `if` condition same as `$title`?

Also why isn't `$action_links` wrapped in an `if`?

> I checked all the layouts in core and in radix_layouts, and these things are always together in all of those layouts. I think it is a safe assumption to make that the tabs and action links always be somewhere near the title. If people want to place them elsewhere, then they can do so using theme functions, or by providing their own custom blocks.

Isn't this whole issue here because we made an assumption in the first place that has ended up creating UX & DX pain? Why assume things again instead of fixing this in one go? I don't see anything wrong with providing all the different things that comprise the current title group of things as individual blocks. This would give users the freedom to have a Lego build time if they want to customize their layout more than what we assume to be a "one size fits all".

So, a big :+1: in general, but with a few points for discussion.

**Comment by docwilmot** [comment]
> by providing their own custom blocks.

There's a block for that! https://github.com/backdrop-contrib/blockify

**Comment by klonos** [comment]
:smile: Perhaps retitle this to "Merge Blockify module to core"?

**Comment by docwilmot** [comment]
But seriously, the new Custom Blocks and the new Field Blocks were ported mostly from CTools; I used the 'custom' and the 'entity_context' code from [this directory of CTools 'content types'](http://cgit.drupalcode.org/ctools/tree/plugins/content_types). Blockify just provides a couple of things you find in the ['page' directory](http://cgit.drupalcode.org/ctools/tree/plugins/content_types/page) of that list.

If you browse through the rest of the bunch that we didnt port, its quite bit of good stuff, which I think we could actually put in core?

**Comment by klonos** [comment]
I was serious about it. We should put it into core.

**Comment by docwilmot** [comment]
Or perhaps, probably best, put it in contrib and see who uses it. A Blockify Plus module.

**Comment by wesruv** [comment]
I'm a big fan of title, tabs, actions, etc. to having their own block. That is all :smile:

**Comment by jenlampton** [comment]
In our call today we discussed the possibility of:
* adding a title stuff block
* making the variables in the template empty if the block has been placed.

If we work it this way we can add this feature in 1.x!

**Comment by docwilmot** [comment]
An idea:
- a "Title combo block" with title, tabs and action links
- individual blocks for
  - actions
  - messages
  - tabs
  - title

Fix so that if any of those blocks are used option to disable the existing layout rendering.

**Comment by jenlampton** [comment]
> Fix so that if any of those blocks are used option to disable the existing layout rendering.

If any block is used the layout rendering should be disabled automatically.

**Comment by docwilmot** [comment]
In case there may be strange people who want to duplicate those bits in a block?. Optional but default on? I'm mostly agreeing with you but want to raise the option in case somebody disagrees.

**Comment by jenlampton** [comment]
not 80% use case :)

**Comment by docwilmot** [comment]
True, and they could also just use another instance of the block too.

**Comment by quicksketch** [comment]
I took a look at the current PR and it's making a good start. However, I agree with @klonos (https://github.com/backdrop/backdrop-issues/issues/1704#issuecomment-195165522) in that just putting title, tabs, action links, and messages all into a single block is too presumptuous. I can think of a lot of situations where I would want some but not all of these properties.

For example I might want to remove the page title and tabs, so I might remove this block. But then the messages disappear! You might want another header element (e.g. Breadcrumb) inbetween the page title and the page tabs, but that's not possible with only having a single block for all these header elements. Even if we added the ability to place a block multiple times with different elements shown, I don't think that's a intuitive approach.

**Comment by docwilmot** [comment]
Actually this isnt what this PR does? Except if I am misunderstanding. It uses the `getChildren()` method we introduced with Field blocks to have a single `hook_block_info()` entry to provide individual blocks for each of these page elements.

**Comment by quicksketch** [comment]
Oh! I'm sorry I didn't actually test it out in the sandbox; I only read the code. I didn't realize you'd used a single class to provide all those different elements with child deltas. It's not the approach I expected, but I can see why it would be put together that way (all these elements are "special" in a way).

Do you think it's a cause for concern that Breadcrumb is in this same category (conceptually), but is handled entirely differently with a separate block?

**Comment by quicksketch** [comment]
Looking at the markup that is generated, I'm not bothered by the difference from the way breadcrumbs are handled. Here's a screenshot of the markup generated:
![screenshot from 2017-01-01 18-29-24](https://cloud.githubusercontent.com/assets/100206/21584118/737bd064-d050-11e6-8116-5760b5a2b423.png)

As far as naming these child deltas, it's important to remember that those deltas will be used in the markup. So I'd probably rename a few deltas:

- local_task_tabs => tabs
- system_messages => messages

Also the class itself I'd rename from `TitleComponents` to a more generic `PageComponents`.

From a theming stand-point, I was a little confused by the single template being used both for individual items and for the entire "combo" version. @jenlampton, you're the most experienced person regarding template consolidation. What's your take on using a single template multiple times per page for different elements? Here's the template in question: https://github.com/backdrop/backdrop/pull/1633/files#diff-eb33c537ce115e8d7a162c2b3f7ad081

**Comment by jenlampton** [comment]
In general I think template consolidation is a good thing, we just need to be sure that theme devs have a way to override everything individually, too. If I wanted a special div and class around all the elements in the combo block, but not the elements in the individual block, I'd need a way to do that. 

Can we add theme hook suggestions for each block?
```
page-components.tpl.php
page-components--combo.tpl.php
page-components--tabs.tpl.php
page-components--messages.tpl.php
page-components--actions.tpl.php
page-components--title.tpl.php
```

**Comment by docwilmot** [comment]
Added `theme hook suggestions` and tests. Ready for review.

**Comment by jenlampton** [comment]
I'm testing the PR but it looks like the page title blocks do not work. They prevent the layout page title from displaying, but do not display a title themselves.

**Comment by jenlampton** [comment]
I moved the system messages block into the admin layout, and now system messages are also not appearing. 

I think this might have to do with these items not being rendered late enough, it looks like these blocks are still part of system module and not layout module. Did they ever get moved?

**Comment by docwilmot** [comment]
@jenlampton I see why system messages blocks dont work: there is an error on https://github.com/backdrop/backdrop/pull/1633/files#diff-4069bef0c8037fa96f53813774940102R713. should be `messages` not `system_messages`.

And, there is a `Warning: mb_strlen() expects parameter 1 to be string` error (the only error remaining) that I need to track down.

So apart from the main block generating code needing to be moved to Layout module (if still recommended), there isn't much left to fix.

As a followup, the "Page title" pseudoblock in the Layout UI should disappear when there is a Page title or Title combo block. But that could be later.

**Comment by docwilmot** [comment]
Update:
- fixed missing message and actions blocks
- fixed `mb_strlen` error
- fixed page title display and added default `.page-title` CSS class for new title blocks
- more tests

**Comment by jenlampton** [comment]
This issue has officially been deemed a feature, thus pushing to 1.7.

**Comment by docwilmot** [comment]
boohoo

**Comment by jlfranklin** [comment]
I'm looking forward to 1.7 already!

(I recently created a modified version of Moscone in a client's Backdrop site with title and tabs moved to the content area.  This feature will let me revert the layout to a stock Backdrop layout.)

**Comment by docwilmot** [comment]
Just had a thought about this: if we add a page title block, shouldnt we remove the pseudoblock on the "place blocks" page (probably via AJAX)? And if so how to manage the page title settings?

**Comment by jenlampton** [comment]
> shouldnt we remove the pseudoblock on the "place blocks" page

Yeah, that would be slick 👍 

> how to manage the page title settings?

Page title settings should probably become settings on the page title block, no?

**Comment by klonos** [comment]
>boohoo

I'm not thrilled that things have to be pushed to 1.7 either @docwilmot, but we need to stick to the code freeze that we've introduced (otherwise what's the point, right?). Besides, as we said already: contributor fun and stress-free developing over fancy, feature-rich releases.

> I'm looking forward to 1.7 already!

Me too!

> > shouldnt we remove the pseudoblock on the "place blocks" page
> 
> Yeah, that would be slick 👍 
> 
> > how to manage the page title settings?
> 
> Page title settings should probably become settings on the page title block, no?

I thought that the plan was to *replace* the psuedo-block (which is a hack compared to how the rest of the blocks work) with the actual page title block that this PR would introduce (with next step being to separate the page title (usually an `<h1>` within the html body) from the head `<title>` ...but that's a different issue). So, I was expecting the new "Page title" block added with this PR to be providing all the options that the pseudo-block included (such as "Copy from block"). Is there something I'm missing?

**Comment by jenlampton** [comment]
> I thought that the plan was to replace the psuedo-block (which is a hack compared to how the rest of the blocks work) with the actual page title block that this PR would introduce

We can't do that until Backdrop 2.x. But we can add this as a new block in Backdrop 1.x :)

**Comment by docwilmot** [comment]
New PR at https://github.com/backdrop/backdrop/pull/1782
- AJAX to remove/replace the existing "page title" pseudo-region which currently holds page title settings.
- Those title settings are now in the dropbutton links for Title and Combo blocks.

**Comment by laryn** [comment]
@docwilmot I tested this PR in the sandbox and see the "Page Title" and "Tabs (local tasks)" blocks which seemingly can be added to regions as expected, and if "Page Title" is added, the pseudo-region does disappear. 

However, when I try to save the layout it is very inconsistent. Often it reloads the Layout screen without having saved any of the blocks (even standard blocks like "Main page content").

**Comment by docwilmot** [comment]
Thanks, will look at this soon.

**Comment by docwilmot** [comment]
Should be fixed now.

**Comment by laryn** [comment]
@docwilmot How do we refresh the sandbox site? I am happy to test again afterwards.

**Comment by docwilmot** [comment]
The sandbox updated. Test away!

**Comment by laryn** [comment]
Yes, the problems I was having saving Layouts seem to be fixed. I was able to move Tabs/Title around and also add fields, main content, etc. without trouble now:

<img width="1216" alt="screen shot 2017-04-07 at 9 27 19 am" src="https://cloud.githubusercontent.com/assets/871421/24804612/96bf6486-1b74-11e7-8748-410604ef7470.png">

👍👍👍

**Comment by laryn** [comment]
PS. Sorry for the body copy there. That was from an Arrested Development lorem ipsum generator and I didn't really read it first.

**Comment by quicksketch** [comment]
I think this needs a little more work yet, consistency fixes and the naming/return value of `layout_page_component_blocks_exist()` is confusing. I posted a bunch of feedback to the PR at https://github.com/backdrop/backdrop/pull/1782.

I'm also curious about how we should handle tabs when placing the tabs block or the combo block. I suggested in the PR that it might be nice to have a `'none'` display option. Meaning you could place either of those blocks, and then just disable the display entirely. The up side of this is it would allow end-users to disable the (usually unsightly) `View | Edit | Revisions` tabs on the front-end of the site. The down side is that they might shoot themselves in the foot and not be able to figure out how to edit a piece of content. However, I have had multiple clients express confusion over the presence of those tabs ("why does it look different when I'm logged out?") and I have removed them in a few situations. Thoughts?

**Comment by docwilmot** [comment]
Great, I expected more work. Wasn't sure the `childDelta` approach would pass scrutiny. Will fix the concerns before code freeze. 

I'm fine with option for no tabs; what would be great to counteract the foot-shooting though is to have contextual links to nodes on full page view.

**Comment by quicksketch** [comment]
> what would be great to counteract the foot-shooting though is to have contextual links to nodes on full page view.

Yep, that would be a good improvement anyway IMO. Separate issue though!

**Comment by laryn** [comment]
@docwilmot @quicksketch Maybe that portion RE: contextual links fits on this issue:
https://github.com/backdrop/backdrop-issues/issues/2626

**Comment by docwilmot** [comment]
Fixed all issues, back to NR.

**Comment by Al-Rozhkov** [comment]
Thanks for your work, @docwilmot. I love this feature.

I have tested sandbox and I can't set custom title.

![custom-page-title](https://cloud.githubusercontent.com/assets/16973264/25046355/0a5b37a8-2142-11e7-9db3-b94606575452.jpg)

I have "Custom page title" setting but menu item title is used.

**Comment by docwilmot** [comment]
@Al-Rozhkov youve uncovered a hard problem here:
- although page title settings are on the dropbutton for title/combo blocks, these page title settings save to the layout itself not the block.
- custom page titles are set only when layout's `preprocess` runs, with a `backdrop_set_title()`
- the page title/combo blocks `preprocess` runs *before* layout's preprocess, by which time its too early to call `backdrop_get_title()` because layout hasn't set it yet.
- layout info isnt available to blocks, so we cant check the layout settings when the title blocks render.

I suspect I'll need advice on this one @quicksketch.

**Comment by serundeputy** [comment]
@docwilmot I filed a PR against your branch which disables the ability to set a custom title on a `title` block.  Instead the user should use the traditional `node/%/edit` form to edit the page content.

They should use this feature `title` as block to control the positioning and markup of the `title` block not the content.

What do you think?
----
https://github.com/docwilmot/backdrop/pull/5/files#diff-404314c54e22c64668d001dc79b2a05cR47

**Comment by docwilmot** [comment]
@serundeputy is that link accidentally the wrong commit? Stuff in there not related to this issue.
But re
> Instead the user should use the traditional node/%/edit form to edit the page content

The page title settings allow layouts to set a title for the layout itself, not nodes in the layout, so I'm not quite understanding your suggestion.

**Comment by serundeputy** [comment]
ahh; I misunderstood.  I thought it was to set the title of the page.

> Stuff in there not related to this issue.
That is just because the `page-comp` branch is behind `1.x` by the extra stuff you are seeing.

**Comment by serundeputy** [comment]
Why would a block set the title for a layout though?

**Comment by docwilmot** [comment]
> Why would a block set the title for a layout

It's the page title block, so seems legit. 

I'm thinking to solve this, we just move the title settings from a dedicated dialog as it is now, and just add those options directly to the page title block dialog instead.

**Comment by quicksketch** [comment]
I pushed an update directly to the PR in https://github.com/backdrop/backdrop/pull/1782. (@docwilmot Sorry I botched something and had to rebase it, so that may require you to check out the branch from scratch.)

I changed three things (commit https://github.com/backdrop/backdrop/pull/1782/commits/202120e6dfe038f24c69c189f466afbc735fb6a0)

- I moved the setting of the page title to the `prepare()` step in `LayoutRendererStandard`. That way the title is set before any rendering at all. Then `layout_preprocess_layout()` only checks for the existing title instead of setting it. I believe this should fix the problem described by @Al-Rozhkov and @docwilmot.
- The "Block title type" option was showing but not saving. I can't think of a useful reason why we would want a title on any of the page components, plus it makes awkward situations like putting a block title on the page title. So I've hidden the options for setting a title on this new block.
- Lastly, I moved the new class into the root of the `system` module instead of being under `/includes`. Although I can see the purpose in making a directory, we shouldn't just have a single item in there. There is background and a dedicated issue for this at #486 and #558.

**Comment by quicksketch** [comment]
Looks like we have a few test failures from my latest changes. I'll tidy it up a bit further.

**Comment by quicksketch** [comment]
Well the tests caught a sort of nasty situation where a title may be set in the layout configuration but then get overridden by a `backdrop_set_title()` from within a block or menu callback. So I had to add a call to `backdrop_set_title()` before rendering blocks, and then _again_ after rendering them. It's not elegant but at least it's self-contained in `LayoutRendererStandard::renderLayout()`. I think that should get all our tests passing.

**Comment by klonos** [comment]
Hey everybody. Truth is that I have not checked this issue here for a while and you all seem to have done great work here! I just gave the PR sandbox a quick spin and yes, as a long-time Drupal/Backdrop site builder, I understand how this works. I can now place the page title in a sidebar and that is a fantastic feature 👍 

...I have to admit though that the whole process of having to add a (second) title block in order to customize the position of an existing title element in the manage blocks UI feels a bit funny. Same how removing the custom title block makes the default page title block show up again.

As a novice user, I'd expect to be able to just drag the default page title from its current, fixed position to another region. Why again are we not doing that?

**Comment by olafgrabienski** [comment]
@klonos Yes, probably not easy to understand for beginners, but seems that we can't do otherwise in 1.x, see https://github.com/backdrop/backdrop-issues/issues/1704#issuecomment-272041687.

PS: I've to admit that even "as a long-time Drupal/Backdrop site builder", I'm not sure how to use the page title block feature correctly unless I read the whole thread of this issue. For example, when I set the *Page title* to "No title", are messages, tabs ecc. also gone (and to be replaced for instance by the Title combo)? It should be transparent in the UI or at least well documented which of such elements are changed when you change the default Page title.

**Comment by klonos** [comment]
> PPS: ... and however, really a great feature.

Yes, of course I am not personally going to complain when we get that feature in. I think I'll be using it like crazy. All I'm saying is the way it currently works in the UI is confusing. We can get the functionality in now (as in with 1.7.0) and we can iron the UX at a later 1.7.x release, but I think leaving it as is for 2.x is too long. It simply feels half-baked IMO.

**Comment by quicksketch** [comment]
> I'd expect to be able to just drag the default page title from its current, fixed position to another region. Why again are we not doing that?

Yeah being able to move the page title pseudo-block around on the page would indeed be pretty neat, but is pretty tricky to implement. In order to treat each "page component" equally, we'd also need to add pseudo-blocks for action links, local tasks (tabs), and messages. I'm not sure that is possible without changing our `layout.tpl.php` markup.

> It should be transparent in the UI or at least well documented which of such elements are changed when you change the default Page title.

You're right we should at least add to the description of the Title block, "This block replaces the normal page title." And similar description for each other type of block. Descriptions in the block summaries (what shows when placed in the layout in the admin UI) would also help.

**Comment by quicksketch** [comment]
I updated the PR to add more verbose descriptions regarding what happens when the block is placed. This description shows up both in the add block listing and on the block preview.

![selection_199](https://cloud.githubusercontent.com/assets/100206/25511342/1693b840-2b7b-11e7-8c42-b8285378488f.png)

![selection_200](https://cloud.githubusercontent.com/assets/100206/25511343/1a52bf44-2b7b-11e7-9fb3-5d9d77f2bc22.png)

I also added the word "Page" in front of each block title, so "Title combo" becomes "Page title combo" for example. And renamed "System messages" to "Page messages". This makes it so you can find all the page component blocks a bit easier by searching for "page".

**Comment by olafgrabienski** [comment]
> I updated the PR to add more verbose descriptions regarding what happens when the block is placed.

That's a great addition, makes the usability much better in my opinion.

Playing around with the respective blocks in the PR sandbox, I noticed that the "Page title" block has less features than the `normal` page title. On the latter you are able to choose from the following options:

- Default page title
- Custom page title
- Copy from block
- No title

It would be nice to transfer these options to the page title block. Can we still do this for 1.7, or is it too late, code freeze coming soon? 

If we can't add these options now, there is a backward compatibility issue: When someone had configured a custom title in the 'normal' block and places later a Page title block, the custom title isn't displayed anymore. Is that okay for the moment, and should we inform users about this restriction?

**Comment by docwilmot** [comment]
@olafgrabienski we moved those options to the dropbutton on the block rather than the block configure form.
I thinks this is good now, code review and feature review.
RTBC

**Comment by olafgrabienski** [comment]
> we moved those options to the dropbutton on the block rather than the block configure form.

@docwilmot Good to know! It seems then that the options are not respected on display but only in the `<head>` of the document. (Just tested the custom title option in the sandbox.)

**Comment by docwilmot** [comment]
Blast, youre right. @quicksketch seems the call to `backdrop_set_title($node->title)` in function `node_page_view(Node $node)` is at fault here.

**Comment by jenlampton** [comment]
The call in `node_page_view()` was not an issue when the title override settings were in the layout. Why is an issue now that they are in the block?

**Comment by docwilmot** [comment]
The layout-determined page title was set (ie `backdrop_set_title(t($settings['title']))`) in `layout_preprocess_layout()` before, which ran last. Now its set really early, in `LayoutRendererStandard::renderLayout()` using the block data. So this now gives Node a chance to intercept that and mess things up.

**Comment by jenlampton** [comment]
It should be set the same time it was before. The same data should still be in the same place in the layout config (I think?), so the same code that was setting the title before, should still be running now.

**Comment by docwilmot** [comment]
I'm thinking the best option here is to actually have the page custom title set in the block configure and save it in the block instead of layout settings. Then it will be simple to pull it out of the block in `layout_preprocess_layout()`.

It is more intuitive there to me come to think of it. If its the "Page title" block it should save the custom page title settings too.

**Comment by docwilmot** [comment]
> It should be set the same time it was before. The same data should still be in the same place in the layout config (I think?), so the same code that was setting the title before, should still be running now.

Previously (before this PR was born), page titles were set by whatever means including `Node`'s intrusion. Then at the last minute, layout would check if the customs settings exist, and override everybody with a `backdrop_set_title(t($settings['title']))`. 

Now though, the custom block title stuff is set too early, before Node and layout_preprocess.

**Comment by jenlampton** [comment]
Yes, I understand. I was asking why that was changed? Is there a use case I am missing? (Are we trying to account for the use case of having more than one page title block?)

**Comment by docwilmot** [comment]
No, see https://github.com/backdrop/backdrop-issues/issues/1704#issuecomment-294230210. 
@quicksketch then attempted to fix this by making layout set the title earlier so it would be available. We didnt account for Node I suspect.

**Comment by jenlampton** [comment]
It seems to me that it shouldn't matter what happens before blocks/layouts execute as long as the operation ends in blocks and then layouts. Do I have the ordering of blocks and layouts rendering mixed up? Do blocks render after layouts, and not before?

Or, Is node somehow getting between the block and layout?  (If that's the case it sounds like both block and layout need to be later -- not earlier.)

Here's how I envision the ordering of page title getting/setting working:

* The page title block should print whatever title set before it executes using `backdrop_get_title()` -- or it can override that (based on it's own settings) and do it's own `backdrop_set_title()` if necessary. 

* Then when layouts executes it will set the `<head>` title based on what's now in `backdrop_get_title()` -- which may (or may not) have been overridden by the block -- and then checks for the block, and only continues with it's own page title if the block isn't already on the page.

**Comment by docwilmot** [comment]
The story of custom titles (note this is all about **custom titles**).
- Once upon a time all was well:
- Everyone could call `backdrop_set_title()`, but in the end, *at very the last*, `layout_preprocess()` ran
  - checked if a custom title existed in layout settings
  - if this was the case, that was the final title, thats, it, no arguments.
- But along came title blocks
  - layout still set the custom title at the very end
  - the title block needed that title to display *as its content*, so needed to call `backdrop_get_title()` to find the title
  - but by the time title blocks made that call, the `layout_preprocess()` had not yet run (since it was at the very last), so there was no way title blocks could know what the custom title was!
- In rode @quicksketch and moved that custom-block-title-checking `backdrop_set_title()` all the way to the beginning of everything, before blocks, before regions, before Node content.
  - title blocks now had the custom title when they were ready to set their content
  - but now Node ran *after* that custom-block-title-checking `backdrop_set_title()` (because that runs before everything), but *before* the page title block did its own`backdrop_get_title()`. 
  - thus Node screweth everything up

The End

p.s test this by noting that the custom page titel on node pages always shows the node title regardless of custom title settings, but that commenting out the `backdrop_set_title($node->title)` call in node module fixes that right up.

**Comment by jenlampton** [comment]
I love the story!  But I don't see any indication that node is the problem. It looks like blocks and layouts just aren't playing nice together.

**Comment by docwilmot** [comment]
> It looks like blocks and layouts just aren't playing nice together.

Yep, thats the thinking. Not Node, just we havent found the right place to set/get title yet.

What do you think of the suggestion here: https://github.com/backdrop/backdrop-issues/issues/1704#issuecomment-298086379

We are putting the custom-/from block-/no- title settings as a dropbutton on the title blocks, but why not put them in the block configure form instead? It seems smarter to me, and would stop all the issues here.

**Comment by jenlampton** [comment]
I love the idea of putting the page title settings into the configure form. It makes the most sense from a UX perspective (I was planning on trying to move them there after May 1 anyway). 

But I think setting the titles as per https://github.com/backdrop/backdrop-issues/issues/1704#issuecomment-298091037 is my preference. 

But let's see if @quicksketch has a reason that might not work. We may need to force the page title block to render after all the others (to assure node does not squeeze itself between block and layout)

**Comment by quicksketch** [comment]
My implementation should have already accounted for calling `backdrop_set_title()` within the node menu callback (or any other menu callback). I must not have gotten it quite right though. I'll take one more look at this and see if I can work this without moving the title settings. Agreed overall though, if moving the title settings can solve the problem that may be better from both a code and UX perspective.

**Comment by quicksketch** [comment]
I see the problem now. This is a toughie one. My solution works for the overall page title (both the H1 in the page template and the page header), but not for a title block.

I think just replicating the title settings to the block is the right move. We can probably undo my "fix" at the same time, it may not be needed any more with the new approach.

@docwilmot Do you want to take another go at this?

**Comment by docwilmot** [comment]
At the day job now, so will have to be this evening or tomorrow. Shouldnt be too hard though.

**Comment by klonos** [comment]
Everybody, but especially @docwilmot beautiful minds ❤️ (not just intelligent people).

**Comment by docwilmot** [comment]
> Shouldnt be too hard though

Haha!
Putting the settings in the block configuration fixes custom titles, but the "from block" settings is the new problem. Since blocks dont know which layout theyre in, I cant generate a list of blocks in the current layout to display in the block config form.

**Comment by quicksketch** [comment]
Okay I've pushed yet another update to the PR.

This version removes some of the previous approach and instead of using `backdrop_set_title()` multiple times, stored the page title in a new protected variable inside of `LayoutRendererStandard`. This makes it so that we can easily set `$this->page_title` within the renderer while not worrying about blocks or menu callbacks calling `backdrop_set_title()`, because it's entirely separate. Before any `PageComponent` blocks are rendered, the title is manually set (there's a special condition in `renderBlock()` to pass the page title to the `PageComponents` instance).

If the layout title has not been explicitly set, we fallback to to using `backdrop_get_title()` to pass to the block. If a title has been explicitly set, we call `backdrop_set_title()` just before calling `theme('layout')`, so preprocess functions could still override/change/ignore it if they desired.

**Comment by docwilmot** [comment]
Excellent, that works perfectly in the sandbox. 
I'll let someone else RTBC this, but it was already reviewed, and the new addition is fine so I think its good now.

**Comment by Al-Rozhkov** [comment]
It works great! Only "No title" doesn't work as I expected. The result is the same as "Default page title", but settings description is `Hide the page title for this layout.` I understand that it is bad practice to hide title on nodes and to have only site name in <title> tag. But still... The setting says `Hide the page title` :-)

**Comment by jenlampton** [comment]
Thanks @Al-Rozhkov I think that was just an oversight! :)

**Comment by quicksketch** [comment]
Thanks @Al-Rozhkov, nice catch there. I was working to expand test coverage and included this test case as well. I fixed it so that if page title is hidden when placing the title block, the entire block itself should be hidden, matching our behavior elsewhere.

**Comment by quicksketch** [comment]
Heh, I actually added the tests but forgot the fix, resulting in tests failing.

Fix for no page title is now in place as well. All tests passing and we have great coverage of the new functionality.

I've merged https://github.com/backdrop/backdrop/pull/1782 into 1.x for 1.7.0. A huge thanks to @docwilmot for totally owning this feature and revising it a dozen times.
