### ISSUE TITLE
URL aliases - set to zero

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1712]
Please advice how to set to zero aliases numbers?

For example, if I add a new page then it has number 1 - node/1.
If I delete this page and the alias node/1 and then add a new page then it will be number 2 (node/2) but I need it to be number 1 (node/1).

How I can understand the statistical information (history) is stored in the database - what is table name?

Thank you!

**Comment by jenlampton** [comment]
Hi @bd0bd, you don't have any control of the internal system path (or the node id) for any page.  That is an auto-increment ID and will always be the next one in the sequence. It's very dangerous to go changing these nid values in the database, because there is data in many supporting tables that is joined to the main node table using this id.

Fortunately, this is why we have path aliases. If `node/1` was the about page, you can add the alias `about` for that page. Then if you delete `node/1` and add `node/2` you can add an alias for `node/2` that is also `about` so you never need to worry about the node IDs or system paths.

**Comment by bd0bd** [comment]
Hi @jenlampton, thank you!
I understand you and the situation () but I would like to change ID.
I like an order.

I would like to fix it myself in the database.

**Comment by bd0bd** [comment]
Well, I do not know if this is right way but I did it this way:

1. I have deleted all my nodes via admin panel.
2. In the database I have did this:

ALTER TABLE  `node` AUTO_INCREMENT=1
ALTER TABLE  `node_revision` AUTO_INCREMENT=1

Is it ok or it could damage something?

**Comment by bd0bd** [comment]
I wonder if it was ok what I did:

ALTER TABLE node AUTO_INCREMENT=1
ALTER TABLE node_revision AUTO_INCREMENT=1

Would be grateful if somebody would tell me if this is good solution and I did not damages anything by doing this.

Thank you!

**Comment by BWPanda** [comment]
Do you still need help with this @bd0bd?

**Comment by BWPanda** [comment]
Seems this can be closed now.
