### ISSUE TITLE
To fix the bug with front (home) page in multi language website

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1747]
Hi!

Yesterday a new version - 1.3.4 - of BD was done.
But the bug (sorry, I am not sure if this is a bug, I think it is an imperfection) - https://github.com/backdrop/backdrop-issues/issues/1638 - still is not fixed although about 30 days are left from the time I have wrote about this problem.

I understand that you do not care much about this issues (multi language websites) because it is not very important for you (is not of current interest). But may be someone of you could tell me how I can fix it myself? I mean this problem with front page.

:smile: 

Thank you!

**Comment by Graham-72** [comment]
I would like to add my comment to what @bd0bd is asking although I am unable to help him, not personally having the technical skills or the languages. Multi-language sites are very important in many parts of the world, not least here in Europe, and somehow we must give this issue higher priority. But who has the expertise and the time to tackle this as a priority? Also, should it not be marked a UX issue?

**Comment by klonos** [comment]
@bd0bd I completely understand your frustration (I am a non-native English speaker from Greece, I build multilingual websites and I currently live in Australia which is a multi-cultural country), but still filing another issue about the same problem just because you did not get a reply in what you perceive a "timely" manner is simply not the way to do things. I am afraid that you will have to simply be patient and wait for when people have the time and energy to work on this feature. A friendly reminder here that everybody that works on Backdrop CMS is doing so without getting paid for it. They contribute their spare free time whenever Real Life permits it.

Multi-lingual support is not an easy task that could be solved in a matter of days or a couple of months. It will take a considerable amount of time to get it right. What I suggest if you are in a serious pressure to deliver a website where multilingual support is something that needs to be implemented straight away, is to perhaps choose a different CMS that already includes multi-language support *now*. Unfortunately for Backdrop, multilingual support is not planned for until version 2.0.0 and as you can see from the [official roadmap](https://backdropcms.org/roadmap#2.0.0), we have not even set a date for that release. So AFAIK it could even be in 2017.

Point is as I said, if a specific website you are building *requires* perfect multilingual support, then Backdrop is not ready for this yet. You can use another CMS for that site and if you still like Backdrop, then use it for the rest of the websites you are building that do not rely on features not implemented yet.

I hope you understand. Closing this issue and lets keep the original one open.

**Comment by bd0bd** [comment]
Thank you!
