### ISSUE TITLE
Translating option for a View page

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1748]
For any basic pages I have a link "Translate" but do not understand how to make the same for view pages.
Please advice :smiley: 

![untitled-1](https://cloud.githubusercontent.com/assets/13515302/14034239/543ca7a2-f232-11e5-9177-411e1d34a1ae.png)

**Comment by bd0bd** [comment]
No any way to translate a view page?

**Comment by dboulet** [comment]
Hi @bd0bd, in Drupal 7 we have the [Internationalization Views](https://www.drupal.org/project/i18nviews) module for translating views, but it doesn’t look like any of the Internationalization modules have yet been ported to Backdrop.

As a word-around, you can create one page in your view for each language on your site, and add a filter to each to only show content in one specific language.

![screen shot 2016-03-25 at 11 34 03 am](https://cloud.githubusercontent.com/assets/208615/14048629/894e55ee-f27d-11e5-952a-3d852257955e.png)

**Comment by bd0bd** [comment]
@dboulet, thankyou!

> As a word-around, you can create one page in your view for each language on your site

I understand this but this solution is ok if I have 2 or 3 languages.
I have 11.
- 33 navigation blocks
- 22 views pages for 2 pages - Articles and News.

:(

**Comment by dboulet** [comment]
I see, yes that is a challenge.

Actually, I think that my solution is not optimal, because every page would need a different path and your users would not be able to switch between languages easily.

The best solution currently is to filter the content in your view by the current language. That way, the one view can be used for all languages. Unfortunately, things like the page title will not be translated, which I think is really what you are after.

You could of course create your view as a block instead. Then create your pages as translated nodes and place the view on the page in the configuration of your layout.

**Comment by bd0bd** [comment]
@dboulet, thank you for your help!
