### ISSUE TITLE
"Database log messages to keep" setting is stored into `row_limit` instead of `log_row_limit`

### ISSUE THREAD

**Issue by rstamm** [backdrop/backdrop-issues#1753]
"Database log messages to keep" setting is stored into `row_limit` instead of `log_row_limit` in function `dblog_logging_settings_submit`

**Comment by olafgrabienski** [comment]
Maybe related: using Backdrop 1.4.2, when I change the default value of "Database log messages to keep" from 1000 to another value, the changed configuration is not saved. (No issues with other configuration changes on the site.)

**Comment by klonos** [comment]
I think it is very much related @olafgrabienski ...I'll try a PR.

**Comment by quicksketch** [comment]
I've add both @rstamm and @olafgrabienski to our organization group so you can now add labels (e.g. bug report) as needed. Thanks for the report!

**Comment by quicksketch** [comment]
I beat you to this @klonos. PR filed at https://github.com/backdrop/backdrop/pull/1449.

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/pull/1449 for 1.4.3. Thanks everyone!

**Comment by Graham-72** [comment]
This fix is causing me a problem. The update of one of my sites is failing and I cannot figure out why.
![backdrop database update - create hope 2016-07-19 11-18-50](https://cloud.githubusercontent.com/assets/10559274/16951376/a76d1340-4dbc-11e6-9dda-00a2b8887e24.png)
![backdrop database update - create hope 2016-07-19 11-20-58](https://cloud.githubusercontent.com/assets/10559274/16951394/b0980434-4dbc-11e6-94ba-fd7a0e059d97.png)

**Comment by serundeputy** [comment]
@Graham-72 can you give us the output of the error message by clicking on the `logged` link or going here: `http://backdrop/admin/reports/dblog` and paste the relevant errors in this issue?

thanks,
~Geoff

**Comment by Graham-72** [comment]
@serundeputy it is not producing an error message in 'Recent log messages'.

**Comment by klonos** [comment]
@Graham-72 does your `/files/config_[hash]/active/system.core.json` contain an entry for `row_limit`, or one for `log_row_limit`? ...or both?

**Comment by Graham-72** [comment]
@klonos it has "log_row_limit": 1000 but no entry for row_limit.
I built the current site using BD 1.4.2.
After update to 1.4.3 everything is OK if I replace file core/modules/system/system.install with the version from 1.4.2 thereby omitting the test for row_limit.

**Comment by klonos** [comment]
Hm, it looks like the 1056 update script was applied and the config setting has been updated (with the old one removed from the `system.core.json` file). The reason why you are still prompted to re-apply the update is because most likely the `schema_version` was not updated in the db in the `system` table for `core/modules/system/system.module`. I'm sure that if you have a look in your db, then that value will still be `1055`. Try manually (via phpmyadmin for example) setting that value to `1056` and you should be ok.

The thing though is why did the updating of the db fail?

**Comment by Graham-72** [comment]
@klonos  thanks. Yes, the schema version was still 1055 in the db so I have now updated it manually.

**Comment by klonos** [comment]
Glad you got this sorted, now you know how to troubleshoot and what to do next time a similar issue happens 😉 

The reason I knew which way to point you was that something like this has happened to me in the past (in Drupal I think). Not sure what might be causing this failure to update the db schema after the script has run successfully though.

**Comment by Graham-72** [comment]
>The reason I knew which way to point you was that something like this has happened to me in the past 

It would be good to have something in our documentation about the way the update system works and where the schema version is stored. Now I know the answer perhaps I should draft this, or does it already exist?

**Comment by klonos** [comment]
This thing that happened is a bug. Messing directly with `schema_version` and the db in general is not a thing that people should be doing and so not something that we should have in the docs (not the user docs at least). If we do have it on the docs, then caution warnings should be all over the place.

AFAIK, the API docs are documenting how schema-related things work (https://api.backdropcms.org/api/backdrop/core!includes!install.inc/function/backdrop_get_installed_schema_version/1 and elsewhere). But that's for devs - not for consumption by the "general public".

I can try to locate the d.org issues and/or forum topics from which I acquired this knowledge, but I doubt that they will be of any help. What generally happens is that people report these sort of bugs and either people that know things or others that simply had this happen to them (like myself and now yourself) tell them what to try. IMO, we do need these reports because if there is a reason this is happening, we need to track it down and fix it. If people resort in sorting this out themselves, we'll be just treating the symptoms, not getting to the root of the issue.

Having said all that, does anybody have any clue as to why this might be happening (`schema_version` in db not updated after the update script has run successfully)?

**Comment by Graham-72** [comment]
>AFAIK, the API docs are documenting how schema-related things work

@klonos I accept what you say and for the most part agree with you. My difficulty in solving the problem for myself was that I failed to search for information on 'schema version' because I did not realise that this was the technical term for this information. Whilst it may not be appropriate to provide documentation for 'messing directly' with data tables, it would be helpful if somewhere there was an explanation of how Backdrop keeps track of module updates and, in summary, what it does when running update.php.
