### ISSUE TITLE
[UX] Update the `Install X` links to `Install new Xs`

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1757]
This was discussed in https://github.com/backdrop/backdrop-issues/issues/998 and will be consistent with https://github.com/backdrop/backdrop-issues/issues/1399.

What do we think?
- `Install new modules` / `Install new themes` / `Install new layouts`
- `Install more modules` / `Install more themes` / `Install more layouts`
- `Install other modules` / `Install other themes` / `Install other layouts`
- `Install module package` / `Install theme package` / `Install layout package`
- `Install module project` / `Install theme project` / `Install layout project`
- ~~`Add new module package` / `Add new theme package` / `Add new layout package`~~
- ~~`Add new module project` / `Add new theme project` / `Add new layout project`~~
- ~~`Find new module packages` / `Find new theme packages` / `Find new layout packages`~~
- ~~`Find new module projects` / `Find new theme projects` / `Find new layout projects`~~
- ~~`Find new modules` / `Find new themes` / `Find new layouts`~~

---

PR from @jenlampton: https://github.com/backdrop/backdrop/pull/1547

**Comment by jenlampton** [comment]
Just re-read the issue...  looks like it was package and not project. I'm fine with either. (Actually, I prefer project but either is an improvement over what we have now!)

**Comment by docwilmot** [comment]
Perhaps the merging of Project Browser could help here, as in @quicksketch's suggestion at https://github.com/backdrop/backdrop-issues/issues/998#issuecomment-111625539 we could change all these links to "Find new themes" or "Search for layouts" since we're rerouting these links to PB, so the "install" part would no longer be accurate anyway.

**Comment by jenlampton** [comment]
That's a good point @docwilmot, I hadn't thought of that. I would like the language to indicate to users that the things they are "finding" are not already part of their site. Not sure how to do that without using "Install"...  but open to suggestions!

**Comment by klonos** [comment]
> I wonder what word WP uses on their plugins page?

Here you go :wink: :

![wp-plugins_page](https://cloud.githubusercontent.com/assets/2423362/14100236/c4b46512-f5d7-11e5-9e51-2c3215d507bc.png)

**Comment by jenlampton** [comment]
Interesting, WP just says `Add new` with no noun. Also there is no indication that they can "search" or "find" from that page... it's just assumed.

I think we need the noun in Backdrop, but I'm fine with using "new" instead of "install". I could go either way with search/find. 'Find new Xs' ?

**Comment by klonos** [comment]
> ...there is no indication that they can "search" or "find" from that page

My bad, not a full-width screenshot. Here's a better one:

![wp-plugins-installed-search](https://cloud.githubusercontent.com/assets/2423362/14119458/f9298dba-f639-11e5-82b0-c7a47614f874.png)

...and there's also a search box in their "add plugins" page (their version of Project Browser):

![wp-plugins-add_new-search](https://cloud.githubusercontent.com/assets/2423362/14119487/10dac230-f63a-11e5-820f-0b11b18bd6f3.png)

Anyways, I think that there is a distinct difference between "new"/"add"/"create" vs "install" and that using one in the place of the other can be misleading. "Add" is for example to be used for new content types or new content where the users create something new from scratch themselves. They *add* something that they can then *edit* (or *update* or *delete*). "Install" on the other hand is something ready-made that you just use as is. Once something is installed, you cannot *edit* it - you *configure* it (or *enable* or *disable* or uninstall*). Does that make sense?

**Comment by jenlampton** [comment]
Yes, after reading your comment I agree with you again and want to use the word "Install".

**Comment by klonos** [comment]
...perhaps they use "add" because they allow editing plugins through their UI:

![wp-plugin_editor](https://cloud.githubusercontent.com/assets/2423362/14119787/93623304-f63b-11e5-8bad-b3b5f1a8b49a.png)

**Comment by jenlampton** [comment]
OMG!

**Comment by klonos** [comment]
I know. Cool but dangerous.

**Comment by klonos** [comment]
...it would have already been in the list of the issue for the feature parity with WP if it wasn't for the security implications that come with it.

Although, I have to admit that it would be so much easier to simply copy the contents of a raw file from GitHub (from a PR) and paste it directly in the file instead of uploading patches and going through the command line.

**Comment by serundeputy** [comment]
#gross;

**Comment by Bojhan** [comment]
Installed makes sense, we also had this discussion for D8. In general using "add" when it refers to new entities of any type (content, comment, etc.) and "install" when refers to things which are downloaded and system level.

**Comment by serundeputy** [comment]
Is this in relation to the Project Browser tabs on `/admin/appearance/install` and `admin/modules` or is this about something else?

I'm moving to 1.5, but feel free to put back if someone feels like the can want to tackle it by 15 May 2016.

thanks!

**Comment by docwilmot** [comment]
I think this is sufficiently resolved by the new labels in Project Installer. If someone somehow still has an issue with this, reopen.

**Comment by klonos** [comment]
...well, we went form this very confusing thing (both "Add layout" and "Install layout" as + links):

![layout](https://cloud.githubusercontent.com/assets/1042283/8138666/7c592f00-1112-11e5-8a24-02cd7cfba73e.PNG)

...to this ("Add layout" as a + link and "Install layouts" as a tab that opens the layout part of the Project Browser):

![backdrop-layouts-add_link_vs_install_tab](https://cloud.githubusercontent.com/assets/2423362/15268479/471da8dc-1a23-11e6-8eb1-d6fc1f2a6dcf.png)

Also, in #998 (still open) we were initially contemplating about what we should call the various things and I believe that there is currently a general consensus that both layout .tpl.php files and their respective UI representations (screenshot tile thingies) will be called "layout templates". So we are perfectly clear on that.

In the current situation though (and let me clarify here that I personally fully understand what each thing does - I am just trying to put myself in the shoes of newcomers), the UI might be confusing. So, I still thing that changing the tab from "Install layouts" to "Install layout packages" or "Install layout projects" would help clarify things.

Finally, in the spirit of being consistent throughout the UI, I think that there was also consensus on that if we changed this for the layouts, we'd also change the "Install themes" and "Install modules" text to include either the word "package" or "project". That is what this issue here is about.

My 2c

**Comment by quicksketch** [comment]
Is there actually a PR for this change? I'm not seeing one in this thread.

**Comment by jenlampton** [comment]
branch was 1757-install-new.

**Comment by quicksketch** [comment]
Hm. After re-reading this discussion, I'm not sure we came to a conclusion. The current PR's "Install new module project" wasn't even in the suggestion list, and IMO it seems pretty obtuse:

![screenshot from 2016-09-14 01-34-56](https://cloud.githubusercontent.com/assets/100206/18505354/af7a93ec-7a1b-11e6-8f30-4f6c9ca2ce18.png)

**Comment by jenlampton** [comment]
>  it'll just look very wordy

I agree. Adding the needs feedback tag to see what others think.

**Comment by jenlampton** [comment]
Pushing to 1.x-future since after looking at that screenshot, I'm not sure I like any of these suggestions better than what we have now. We should discuss and make a decision, and we don't have time to do that before tomorrow.

**Comment by jenlampton** [comment]
I think this would be a minor UX win for 1.6, but we need some more feedback.

**Comment by klonos** [comment]
This is a very small (both UI- as well as code-wise) but nevertheless important change that improves UX. We should get it in. What sort of other feedback are you after @jenlampton??

PS: would be great if you closed/reopened the PR to get a fresh sandbox 😉

**Comment by jenlampton** [comment]
>  What sort of other feedback are you after @jenlampton??

The text on the tab, is "Install new modules" good to go, or do we want to bikeshed that some more? :)

**Comment by klonos** [comment]
>> PS: would be great if you closed/reopened the PR to get a fresh sandbox 😉

>done!

You need to wait a couple of minutes before reopening after you have closed a PR, otherwise the sandbox fails to be properly destroyed and then rebuild. Can you please give it another go when you get a chance? Thanx.

**Comment by jenlampton** [comment]
Well I'm glad somebody knows how things work around here :)  trying again...

**Comment by klonos** [comment]
Just passing on the knowledge of how the cogs turn. It's basically advice previously passed on to me by @Gormartsen which is the person that actually has put the cogs together for us 😄 

PR sandbox looks great and PR changes are trivial. RTBC from me 👍

**Comment by serundeputy** [comment]
Thanks everyone! Looks good!

Merged into `1.x` will ship with `1.6.0`.
