### ISSUE TITLE
Full config import with content type deletion allows for broken content to remain

### ISSUE THREAD

**Issue by alexfinnarn** [backdrop/backdrop-issues#1758]
I searched for an issue like this but didn't find anything. New to filing issues here so forgive me if there is already an open issue. 

While messing around with configuration management, I noticed that you can delete a content type that still has published content associated with it. If you've created a new field associated with that content type, you will see an error saying you have to delete the field elsewhere, but if no new fields were created, there is no warning about having orphaned content. 

I think there should at least be a warning that you are deleting a content type that has live content associated with it. I know there are probably a lot of cases where people can jack their site up using CM, but this seems like an simple-ish check to do when deleting a content type through the UI. 

This also seems like something that could be done in the contrib space using `hook_config_data_validate`?

To reproduce:
* Install a new site
* export full config
* add a content type with existing fields
* make new content with that content type
* import export of full config
* see broken content still there

**Comment by alexfinnarn** [comment]
Since nodes are part of core, unlike other custom entities you can create, I think this check is a good idea. I added a function to check whether a node type has content taken from the field module's similar function.

**Comment by quicksketch** [comment]
Hi @alexfinnarn! Thanks for opening this issue.

A quirk in the history of Drupal/Backdrop, perhaps, but it's entirely possible to delete a content type through the UI even if content exists. You get this warning:

![selection_128](https://cloud.githubusercontent.com/assets/100206/15038343/e2932ba8-1257-11e6-9e60-00dfaa3426f0.png)

However, just because you can do this rather unusual thing through the UI, I think you are right that if we are doing validation for fields, we should add the same thing for the content type itself.

A background on why that validation is thrown however: we added that validation because fields take a long time to delete their data. Deleting a field doesn't actually delete its data immediately, it takes a number of cron runs to fully "clean up" the database. As deleting a field via config would remove any information about the field, the clean up would not be possible. So the field warning was created for a technical reason, not necessarily for the benefit of the user of the config system. Deleting a node type doesn't have this same problem, it's just allowed to be orphaned without the type information being persisted.

But anyway, I think you're right. Let's keep users from shooting themselves in the foot. If they want to delete an entire content type, they should remove the matching content of that type themselves.

**Comment by quicksketch** [comment]
I can't really determine whether this is a bug or a request to add a feature. For the sake of not holding it up on minor release, we'll mark it as a bug so that it can be fixed at any time.

The PR at https://github.com/backdrop/backdrop/pull/1334 looks great to me. Excellent job! I would like to at least manually test this however. It should also have an automated test to ensure it works properly. We already have a test for ensuring config hooks fire, so I think the only thing we need is to test `node_type_has_content()` function. Adding a new test to `NodeTypeTestCase` seems like it would be the appropriate location.

**Comment by alexfinnarn** [comment]
Thanks for the review and quirky history lesson @quicksketch :) 

I added a test for the node_type_has_content() function which passes for me. Let me know anything else I need to do for this PR.

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/pull/1334 into 1.x and 1.3.x. Great job @alexfinnarn!
