### ISSUE TITLE
[SEO] sitemap.xml in core.

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1764]
I would like to offer to add sitemap module in core.
So that any new created page would be automatically added to sitemap.xml - I have this option in my old CMSs.

Please could you tell me module name to generate sitemap.xml?
It is not problem in Drupal but I am not sure how to make this in Backdrop.

Thank you!

**Comment by mikemccaffrey** [comment]
We should probably looking at porting either the d7 or d8 modules into contrib first:
https://www.drupal.org/project/site_map
https://www.drupal.org/project/sitemap

Creating sitemaps by default in platforms like Wordpress make a lot of sense, since they are explicitly for publishing content publicly. However, usage in Backdrop/Drupal seems a bit more complicated, due to all the different combinations of entities and permission levels.

**Comment by bd0bd** [comment]
>However, usage in Backdrop/Drupal seems a bit more complicated

Yes, it is somewhat a headache with Drupal.
I do not understand why the developers do not make it simple like it is on other CMS-s.

**Comment by mikemccaffrey** [comment]
> I do not understand why the developers do not make it simple like it is on other CMS-s.

I agree that we should make it easier to add and configure a sitemap.xml file. However, I just want us to be careful when implementing it, since Drupal is often used to publish private content that is intended only for users of a certain role. We need to make sure that we are not accidentally revealing any page information that is not supposed to be public knowledge.

**Comment by BWPanda** [comment]
Sitemap modules are available in contrib now, I'm not sure we should add that to core... Closing, but if there's strong feelings about this being added to core we can reopen.

**Comment by klonos** [comment]
FTR: WordPress also leaves this to contrib addons.

**Comment by oadaeh** [comment]
Not anymore: https://wordpress.org/news/2020/08/eckstine/

**Comment by klonos** [comment]
There's currently 3 sitemap-related contrib projects that have been ported:

- https://github.com/backdrop-contrib/xmlsitemap with [~170 sites using it](https://backdropcms.org/project/usage/xmlsitemap)
- https://github.com/backdrop-contrib/easy_xmlsitemap with [~50 sites using it](https://backdropcms.org/project/usage/easy_xmlsitemap)
- https://github.com/backdrop-contrib/text_sitemap with [barely any sites using it](https://backdropcms.org/project/usage/text_sitemap)

Still, this is roughly ~20% of Backdrop sites using a sitemap solution. ...of course, that doesn't mean that this is a discoverable feature which people choose to not use. I'm sure that if WordPress included a solution OOTB, it must be what people expect out of a modern CMS. Should we revisit this then?

**Comment by oadaeh** [comment]
I think it's more what Google and other search engines expect. I think most site owners don't even know what it is, much less whether they need it or not.
