### ISSUE TITLE
Suspend and/or schedule publishing/unpublishing a custom block.

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#1776]
Is there a way I could suspend publication of a block i.e. unpublish it as one can for a node?

I have a small block that provides a special notice to site visitors and appears in three or more layouts. It would be useful to be able to suspend it when not needed then republish it later with different text.

**Comment by klonos** [comment]
:+1: we currently allow adding or removing blocks. A checkbox that would toggle enabled/disabled state would be great. Would also be great if we could schedule this when we get scheduled publishing/unpublishing for nodes in (#857).

**Comment by Graham-72** [comment]
The other place I looked for it (while working as a user) was in the listing of custom blocks under operations where there might be a third option e.g. suspend in addition to configure and delete.

But incidentally I found a serious column heading alignment problem.
![custom blocks - graham s backdropcms trial 2016-04-03 06-23-22](https://cloud.githubusercontent.com/assets/10559274/14230934/a8420e8e-f965-11e5-82fe-68ecedeab282.png)

**Comment by quicksketch** [comment]
> A checkbox that would toggle enabled/disabled state would be great. Would also be great if we there was an option to schedule this (would have to copy the functionality of scheduled publishing/unpublishing for nodes once #857 gets in).

I don't know, this starts getting into a lot of duplicated functionality. I think I'd recommend just positioning a scheduled node as a block once we finish up #1076. Note that nodes are not exportable, so your layout would be dependent upon this NID actually existing between environments. Still, it'd save you all the trouble of published/unpublished/scheduling/etc.

In the short-term, you can immediately do the same thing by assembling a view that only has a single item (whether of a particular type or just one node), expose it as a block, and position that in the layout.

**Comment by docwilmot** [comment]
Set a stringent visibility condition? Say, for example only visible to admin or user/1.

But I dont think this is a bad idea though, with custom blocks, as if you want to hide it, you'd need to remove it from the layout, which would lose the content. Resorting to tricks to hide it seems less slick than a simple "Dont show this" checkbox.

**Comment by Graham-72** [comment]
> do the same thing by assembling a view that only has a single item

After submitting the original question I realised that this is just what I have been doing in D7 and it works very well, with the possibility of controlling date and time when it appears/disappears. But it takes quite a bit of setting up, not something I would expect an occcasional user to do.

Thanks @docwilmot for the visibility condition suggestion. I shall try it out.

**Comment by docwilmot** [comment]
Actually how about introducing a date as a visibility condition @quicksketch? Any thoughts on that?

**Comment by klonos** [comment]
> Actually how about introducing a date as a visibility condition...

You must have read my mind. :+1: ...but it will have to support date ranges for this to function properly.

Although, I admit that a simple user that does only the basic things might not look for a visibility condition. If they perceive custom blocks as pieces of content, then they might expect a publish/unpublish/schedule feature available.

**Comment by klonos** [comment]
...taking the liberty to make this a feature request.

**Comment by quicksketch** [comment]
The PR at https://github.com/backdrop/backdrop/pull/1354 looks pretty good as far as adding a visibility condition. It allows scheduling a block to show (or not to show) between a certain date range. I'm having trouble estimating if this is a highly needed functionality or not though. Seems like it might be a better fit for contrib.

If you just wanted to _manually_ hide/show a block in the UI, you could put a permission on it or create a condition that would never be true (path = "DISABLED" or something). That's not an intuitive solution, but I'm not sure that a date range condition would be very intuitive either. What do you guys think of this solution?

Here's the current screenshot of the visibility condition:
![selection_137](https://cloud.githubusercontent.com/assets/100206/15261309/5377b72e-1921-11e6-9d02-8f9f5b00257c.png)

**Comment by klonos** [comment]
The UI looks good to me, but as @quicksketch mentions in the PR:

> Neither start nor end times are required here. What happens if these values are left empty?

@quicksketch I was thinking about that when I saw the UI screenshot you posted over in the issue. This is a bit tricky: you see we have 3 possible use cases:

1. Publish a block for a specific period (date range - both start and end date required)
2. Publish a block after a specific date (only start date is required)
3. "Expire" a block after a specific date (only end date is required)

In order to allow all these, we cannot have both fields required (if it was so, we wouldn't be able to allow for use cases 2 and 3 above). On the other hand, if we have both fields optional, then we allow them to be left empty, which constitutes a validation error. So how do we do it? Is there a way to conditionally make fields required or more precisely to have a validation that requires *at least* one of the fields to be filled in?

I think I recall a UI when the end date field was shown only if the user enabled a "specify end date" checkbox, but that would not account for use case 3 then.

...as I said, tricky one!

**Comment by klonos** [comment]
...reading my comment above, the only way I see this implemented with the ability to have proper validation is to have the user select one option from a radio set that lists all 3 use cases and then have the start date, end date or date range fields be shown using `#states`. This would make the form be comprised of the following elements:

- a **required** radio set with 3 options: "Publish after a specific date", "Unpublish after a specific date" and "Publish during a period between two dates" (which one is the default TBD)
- 4 fields in the form (hidden/shown using states depending on the selected option of the radio set):
  - publish date (**required**, shown only when option "Publish after a specific date" is selected)
  - expiration date (**required**, shown only when option "Unpublish after a specific date" is selected)
  - start date (**required**, shown only when option "Publish during a period between two dates" is selected)
  - end date (**required**, shown only when option "Publish during a period between two dates" is selected)

But I'm not sure if `#states`-hidden required fields still hit the validation checks (?).

**Comment by klonos** [comment]
...if we want to tell those 4 fields apart and still have small names/labels for them, I believe we can go with "start date", "end date" and "from date" & "to date" (the last two are a pair).

Also, as a note, we could have something like https://www.drupal.org/project/range in core (would be useful for other cases too) and extend it to support date fields (currently only number fields are supported, but AFAIK dates are stored in UNIX timestamp in the db which is a number).

All these ideas can be follow-ups though. We can go simple if we want to implement this feature now and iterate with improvements as we go (baby steps++). For instance, I wouldn't mind if we left those fields there as they are for now and have some help text to explain what happens when the start date is left empty vs when the end date is left empty vs both dates filed in.

**Comment by klonos** [comment]
NOTE: if not done already, we should have validation in place so that we ensure that the end date is not before the start date.

**Comment by docwilmot** [comment]
> Neither start nor end times are required here. What happens if these values are left empty?

I'd propose *not* to make them required and fix this with help text and a validation function.
- if only start date set, then publish then and never unpublish; if end date only, do opposite
- if none, error on validate.

> Seems like it might be a better fit for contrib

I suppose it could start there. If thats consensus, then I'll close the PR and move.

> That's not an intuitive solution, but I'm not sure that a date range condition would be very intuitive either

Agreed. I didnt do this with the intention of providing a method to inactivate a block actually, just thought a date condition would be cool to write. We probably need to consider a better way to inactivate blocks to satisfy this issue request if this is still seen as needed functionality.

**Comment by klonos** [comment]
> We probably need to consider a better way to inactivate blocks to satisfy this issue request if this is still seen as needed functionality.

The original idea/request by @Graham-72 was to have the blocks be deactivated instead of deleted. A simple set of Hide/Show actions added to the ones available in the block dropbuttons would suffice I believe:

![backdrop-layouts-show_hide_actions_for_blocks](https://cloud.githubusercontent.com/assets/2423362/15268830/6a2a2aba-1a2f-11e6-9817-a8cd208d49ab.gif)

...but IMO it would be cool to be able to schedule this in addition to being able to manually show/hide.

**Comment by quicksketch** [comment]
Great suggestion @klonos, I think that's a much better/faster way to hide/show blocks, and it would work for all blocks, not just "Custom blocks". It would work but could still be a little tedious if you'd placed 4 instances of the same block 4 different layouts. However, I think it would be both relatively simple to implement and be the least confusing way to provide such an option to the user.

> ...but IMO it would be cool to be able to schedule this in addition to being able to manually show/hide.

Yeah both the current scheduling PR and the manual show/hide are great ideas. Do both belong in core though?

Regarding the validation errors when both fields are optional, it's fairly straight-forward to add a validator to make sure that at least one of the two fields is filled out.

> This is a bit tricky: you see we have 3 possible use cases:

I thought about these three use-cases as well. What makes this set of scheduling options a little crazier is that the "NOT" negation option actually makes it so you can schedule 2 of the use cases in different ways but accomplishing the same result:

- Publish a block after a specific date (only start date is required) *OR* (only the end date is required and the "NOT" option is used)
- "Expire" a block after a specific date (only end date is required) *OR* (only the start date is required and "NOT" option is used)

Personally I find negating confusing in all situations except negating between a date range.

**Comment by jenlampton** [comment]
> Do both belong in core though?

I don't think this is an 80% use-case. I've used a lot of panels & blocks and never needed to schedule block content. I'm not sure what will evolve in Backdrop now that blcoks are easier, but I definitely think this is something that should happen in contrib first, and then be moved to core if popularly used.

**Comment by klonos** [comment]
If we have nodes exposed as blocks (#1076) and then block visibility conditions based on node published state, than that would essentially be this feature request here.

**Comment by jenlampton** [comment]
but even less likely, as nodes exposed as blocks aren't usually the kind that need to publish or expire ;)

**Comment by klonos** [comment]
Yeah, how I would go about it is this:

- add a boolean field to the content type that would serve as the piece of text that needs to be scheduled for publishing/unpublishing (would call that "announcement" or "scheduled" or something that makes sense for the specific use case)
- create a view of content of that type
- add a block display to that view
- have the view results filtered by that field when it is set to true
- have the view results filtered by published
- place the view block in the layout/region I want it to show up

Limitations of that solution:

1. Need to add filter to the view to make sure there is only one node shown. You can filter by specific nid, but not that intuitive and requires editing the view each time instead of the content (requires elevated privileges to content authors).

2. Too many steps involved. Having the ability to expose a node as a block and then perhaps select layout/region to place it in is far more intuitive and faster.

**Comment by docwilmot** [comment]
There seems to be some reservations re considering this for core. I agree it probably a wildly desired option. I think I'll push my code to contrib and see how it fares there. Maybe also someday attempt the show/hide option as contrib too. @klonos unless you want to press this further, I think we go ahead and close this issue.

**Comment by klonos** [comment]
Even if I pressed this harder, I cannot put code where my mouth is. So lets close and see if the download/usage stats of the contrib module justify putting this in core at some point in the future.

@docwilmot can you please let us know in this thread when you push your code to contrib?

In the meantime, I'll file a separate issue for the small show/hide block feature (sorry @Graham-72 for hijacking your issue and eventually having it closed).

**Comment by klonos** [comment]
Done :wink:

**Comment by docwilmot** [comment]
https://github.com/backdrop-contrib/block_scheduler

Name not quite accurate, as a visibility condition can apply to blocks, layouts and menu items, but this sounds cooler than "Plugin Scheduler"

**Comment by klonos** [comment]
@docwilmot thanx! Much appreciated :+1:

**Comment by klonos** [comment]
>...but this sounds cooler than "Plugin Scheduler"

If you ask me, I'd call it by what it does because you seem to have nailed it in [the release description](https://github.com/backdrop-contrib/block_scheduler/releases/tag/1.x-1.0.0): Adds a Datetime Visibility Condition

Datetime Visibility Condition sounds way cooler and spot-on :wink: Too late to rename you think?
