### ISSUE TITLE
Menu items with images

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1816]
I would like to have a left bar with pictures and names of people. When we click on any picture then a resume (or bio) page is displayed in right column.

Well, we can make a block with pictures and place it in left bar. But the only problem in this case - we do not have an active class (**active-trail active**) for pictures as we have it for any menu items. So my idea is to use a menu navigation  block but I do not know if it is possible to use pictures with menu items.

In the CMS I have used before there is this option (inside admin panel). The menu module has setting **Use Images** - you can activate it if you need it and add images for each item.

Is it possible somehow to use images in BD menu items?

Thank you!

**Comment by Graham-72** [comment]
Can you not use Views to do this? Or perhaps if you had a more advanced menu module that numbered each menu item you might be able to do something with background images. 
Views together with layouts is a powerful combination well worth considering.

**Comment by bd0bd** [comment]
@Graham-72, thank you! But I do not undersrand how to do it.

In my previouse CMS it is very simple - I type in item name and upload image. Nothing more.

**Comment by Graham-72** [comment]
I guess you need some new module written for Backdrop to do this. But in any case views is worth mastering.

**Comment by bd0bd** [comment]
I can not understand what do you mean about Views.

**Comment by bd0bd** [comment]
This is CMS where I can add image to item:

![1](https://cloud.githubusercontent.com/assets/13515302/14767450/f29c704a-0a2d-11e6-8f5a-675280c022da.png)

**Comment by Graham-72** [comment]
Yes, I was just thinking that if there is currently no ready-made module in Backdrop to do this for you, you might want to consider the use of the inbuilt Views module to arrange your data (text and images, with links) on the page.
https://backdropcms.org/support/services is an example and this could be elaborated so that a link in one column will control what appears in the other.
But it takes quite a lot of learning.

**Comment by gifad** [comment]
Ha ha, I was just copying the url of https://backdropcms.org/support/services, not for the way it's built, but for its content : 
> If you are looking for assistance with design, development, hosting, or maintenance, please browse the list below.

> Contractors for Hire

Backdrop is made for the 80%, but you have to guess 80% of what…

**Comment by bd0bd** [comment]
Ok. Thank you!

I understood that BD has no this possibility.

**Comment by gifad** [comment]
Or you can do it by yourself, but you have to learn drupal first…
Anyway, there must be some investment.

Backdrop is free software, free as in free speech, and free as in free beer as well,
but there is no free lunch !

**Comment by bd0bd** [comment]
@gifad, I am not beginner. I am almost 20 years with these things. 

I mean that may be this is not a right place to talk about this :smile:
This is appropriate place: http://forums.philosophyforums.com/

**Comment by gifad** [comment]
@bd0bd, you **are** a beginner. I am almost 50 years with these things (although they were not exactly "free" at this time).

seriously, ask google for "drupal image menu module", and kindly request someone here to port some on backdrop, in their "free" time…

**Comment by pepperstreet** [comment]
Hello, just following your discussion and I am relatively new to Backdrop. Currently testing and making decisions for my future "CMS-Arsenal" ;) 

Regarding the initial question... I tend to agree with @gifad and his suggestion about Views, Layouts and Blocks. Your task seem to be "content" and "content-type" related: You have profiles with images and data. Probably you need a list of profiles and a navigation to the profile details. Either that list could be your "navigation" or you create a special list as a separate "block". All this sounds like "views", not an advanced menu module. I would go the "views" route. 

However, your question and CMS example leads me to a **related idea**. I just had a quick look into the BD menu -> Edit link options. Which are indeed limited. At least I expected to find a parameter for a **custom CSS class**. Maybe even an option to add a modern **icon-/webfont** markup...
_(should I open an issue for that? Could not find a matching issue)_

**Comment by klonos** [comment]
@pepperstreet here are a few existing issues related to menus that you might find interesting:

Add an icon font to core: #364
Add Menu Block features to core (feature parity with D8): #845
[UX] Provide responsive drop-down menus out of the box: #1457
Make menu items translatable in core: #225

As it is currently, you can add classes to blocks (menu blocks too), but I take it that you need the ability to add classes to individual menu item links in order to be able to add icon fonts to them though. I also did not find any issue already filed for that. Not sure why I haven't filed one already, because I do need that feature too in order to migrate some sites to Backdrop. Guess I was waiting for #364 to be in core first.

**Comment by klonos** [comment]
I guess what you need is https://www.drupal.org/project/icon ported to backdrop.

**Comment by klonos** [comment]
@bd0bd what you need is https://www.drupal.org/project/menuimage ported, but as others said, I would go with views if I were you. For my drupal sites, I often find https://www.drupal.org/project/menu_views that allows to select a view to be rendered as a menu item (or rather the results of a view to be rendered as menu items).

**Comment by Graham-72** [comment]
@bd0bd I have had a quick try at porting menuimage but with only partial success. The module will install and uninstall, it will add the image field to the menu item edit form and it will upload the image. But at the moment it will not display the image in the preview or in the menu.

I have not got time at the moment to find out what is wrong. From what you can read about this module do you think it might be useful to you? How urgently do you need something like this?

I can understand you not wishing to use views because this requires a lot more than just ticking a box and uploading a file. But it is IMHO one of the best things about Drupal and Backdrop.

**Comment by bd0bd** [comment]
Thank you very much to all of you!

**Comment by Graham-72** [comment]
Incomplete port of menuimage is now at https://github.com/backdrop-contrib/menuimage

I will try and make time to finish it soon. Though anyone else is welcome to have a look.

**Comment by jenlampton** [comment]
Fantastic, thank you @Graham-72 ! :) I'm going to close this core issue. Please open a new issue if anyone would like to request moving X module into core.
