### ISSUE TITLE
Allow title to be hidden when displaying a teaser in views

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#1881]
I'd like to display a node teaser in a view, but without the node title being added and linking to the node itself. Currently you can choose whether or not links and comments are displayed, so I'd like to propose another option to display (or hide) the node title.

Something like this:
![firefox_screenshot_2016-05-17t05-26-02 783z](https://cloud.githubusercontent.com/assets/2385329/15312193/5b3f75a6-1c45-11e6-92e8-d50936274269.png)

**Comment by klonos** [comment]
:+1: I see the use in this. Although we'd need to make sure that this is on by default.

Also, while at it, can we make the "Display links" label a bit more clear. Some might think that having this checkbox unchecked hides any links that are in the body text. Something like "Display the "Read more" links".

Final though: by allowing users to hide both the teaser title and the "read more" links, we allow them to shoot themselves on the foot because there would be no way to navigate to the actual node from the teaser. Perhaps throw a an inline warning when both checkboxes are unticked or have a permanent help text explaining that.

**Comment by BWPanda** [comment]
> Although we'd need to make sure that this is on by default.

Yes (that's why it's ticked in my screenshot above) ;)

> Can we make the "Display links" label a bit more clear.

Yes please!

> By allowing users to hide both the teaser title and the "read more" links, we allow them to shoot themselves on the foot because there would be no way to navigate to the actual node from the teaser (still a valid use case though I believe).

My use case is that I want to have a block on the frontpage that gives an intro to the site. I've therefore made this block the teaser for the About Us node, but don't need it to link through to the About Us page as there's already a link in the menu for that. So yes, there are use cases where having neither the title nor links are legitimate and intended.
Having said that, I'm not sure about adding warnings to that effect. I think users that configure the teaser that way are either doing it intentionally or will soon realise what they did and fix it themselves.

**Comment by klonos** [comment]
> I think users that configure the teaser that way are either doing it intentionally or will soon realise what they did and fix it themselves.

Fair enough.

**Comment by BWPanda** [comment]
I've created a [PR](https://github.com/backdrop/backdrop/pull/2781) for this. Not sure if I found the best way to prevent the title being output, so feedback and testing welcome.

**Comment by klonos** [comment]
PR looks really good @BWPanda 👍 ...I left a small, nit-picking comment 😅

Here's a few more comments:

- The option for the title does not show up when creating a view and selecting the "Create block" option, while the options for links and comments are shown:

    ![2019-07-09-01-46-2781 backdrop backdrop qa backdropcms org](https://user-images.githubusercontent.com/2423362/60824209-8bb8ab00-a1ec-11e9-9e76-427f48846568.png)

    (we should really have these options be checkboxes instead - for consistency, and because there's no point having drop-downs for 2 on/off options)

- We should allow these options to be set per block **instance**, instead of setting them globally in the view (this can be a separate, follow-up issue though):

    <img width="620" alt="Screen Shot 2019-07-09 at 1 58 23 am" src="https://user-images.githubusercontent.com/2423362/60824692-624c4f00-a1ed-11e9-84cc-8d1cccd16fd9.png">

**Comment by BWPanda** [comment]
@klonos Thanks for the feedback. PR updated.

There's still an issue with the `display: inline` of the checkboxes on the wizard form that I can't seem to fix, so help needed there...

**Comment by BWPanda** [comment]
I've updated the PR to fix the display of the checkboxes. Please review and test.

**Comment by stpaultim** [comment]
Sandbox does not work. Please, refresh. @BWPanda

**Comment by BWPanda** [comment]
@stpaultim Works now.

**Comment by klonos** [comment]
Things work as expected, and code looks good. Thanks @BWPanda 👍

**Comment by BWPanda** [comment]
Thanks @klonos for your help with this. I've merged https://github.com/backdrop/backdrop/pull/2781 into 1.x.

**Comment by jenlampton** [comment]
This is a strange request, and I would guess it would only be used by a tiny percentage of sites. We should try to get feedback from more people when a new feature is requested, since [our goal is to keep Backdrop Simple](https://backdropcms.org/philosophy#principles). Feature bloat was a common problem with Drupal, and one of the areas where Backdrop is trying to be different.

The views UI in particular is a pain-point because it is already overwhelming to new people. The more options we add, the more overwhelming it gets. There are plenty of other solutions for this particular problem, here are two off the top of my head:
* use a view of fields instead of teasers
* use another view mode and hide the title in the template file

All this said, adding a checkbox is the least of our concerns with the views-ui :) I have a follow-up idea and will post it shortly.
