### ISSUE TITLE
Inconsistencies with the width of expanded responsive primary tabs.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1882]
Don't know if this is with the latest bootstrap layout commits in 1.4.0 or older:

![backdrop-inconsistent_widths_of_expanded_responsive_primary_tabs](https://cloud.githubusercontent.com/assets/2423362/15317841/89423ddc-1c66-11e6-825a-74ab7e3ec39f.png)

...also the horizontal white line is not present in the first expanded item.

**Comment by klonos** [comment]
...here's how it looks with three menu item expanded:

![backdrop-inconsistent_widths_of_expanded_responsive_primary_tabs](https://cloud.githubusercontent.com/assets/2423362/15317916/f0e60d92-1c66-11e6-86a9-0d65341904ba.png)

**Comment by quicksketch** [comment]
Hi @klonos! I can't see a problem from the screenshots posted. The width of the expanded menu is based upon the width of their contents. "Comment display" is the widest item in both screenshots above, and the width of both menus is identical at ~250px. I measured the vertical gap between menu items, and they are also identical between screenshots. Perhaps a side-by-side comparison would show the problem?

**Comment by klonos** [comment]
Perhaps it's more clear with this animation:

![backdrop-issue1882-responsive_tabs_inconsistencies](https://cloud.githubusercontent.com/assets/2423362/15434673/5ea539c0-1efb-11e6-9952-4e7e04b110d1.gif)

**Comment by klonos** [comment]
I believe that it was @wesruv that came up with this awesome idea and implemented the entire thing, so better if he has a say I think.

**Comment by wesruv** [comment]
I'd say this is working as intended.

* The width of the dropdown is based on the widest item in the dropdown with some extra padding on the right side, because I thought that looked better that way.
* I don't want to expand the width of the last tab, and since these tabs aren't children of the inactive tab I don't want them to line up too much.
* I also don't want to cram too much JS into the page, so I'd rather not calculate how much width it takes to make the dropdown reach the left side of the page, this also wouldn't look right in most scenarios until the screen gets quite skinny.

Connecting the ellipsis control to the first item is a bit odd, I'll admit, but I feel like it associates it with the dropdown a lot better than the other ways that could have been handled.

**Comment by klonos** [comment]
All fair enough. I guess this is a matter of how one sees this.

To be clear, I wasn't going for width consistency per se (that would come as a side-effect). I was going for alignment of the start of text of the expanded menu items with the tab that sits on top. That way, the user would not have to zig-zag their eyes as they scan the available options.

**Comment by klonos** [comment]
...so far all comments here point to wontfixing this issue, so feel free to close it if the things I pointed out seem to be of no concern to anyone else.

**Comment by wesruv** [comment]
Sounds good, definitely worth revisiting issues with this when we eventually redesign the admin theme.
