### ISSUE TITLE
[UX] Layout UI: Allow regions & blocks within to be re-used (Copy Region)

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#1886]
My Front layout has exactly the same header and footer as my Default layout, it's just the Content that's different (and the template). But I currently have to make any changes to the header and footer to two different layouts (and I can only imagine the hassle others have with even more layouts).

So, I propose new functionality something along these lines:
- Add a new 'Symlink' block (name needs discussion)
- This block's configuration will have the option to display an entire region from another layout (e.g. Header from Default) or display a specific block from a region in another layout (e.g. Header Block from Header in Default)
- If Entire Region is chosen, when this block is rendered it'll display all blocks from the chosen region and layout
- If Specific Block is chosen, when this block is rendered it'll display the specific block from the chosen region and layout

The benefit of this is that if changes are made to the header block in the Default layout, those changes will automatically be reflected anywhere the new Symlink block is used and where it links to the Default layout's Header region, or Header Block in the Header region.

I use the name 'Symlink' block to help you understand what I mean by this block's intended functionality - similar to that of a symlink in a file system.

I think the use-cases for this are endless and quite powerful, and that it'll make it much easier to create and manage multiple layouts.
Thoughts?

**Comment by dboulet** [comment]
I have thought about this as well. I wonder if it could work more like Views: when creating a new view, there is a “default” display and all other displays inherit its configuration options until they are specifically overridden. You could have a similar arrangement with layouts: the default layout would act as a “master” layout and any regions common to other layouts (for example: header, footer) could pull in the blocks from the master layout by default. You could then have the option to “override” the region in a specific layout.

It would probably require an overhaul of the layout system, but could be powerful.

**Comment by BWPanda** [comment]
> It would probably require an overhaul of the layout system...

Yes indeed.

> ...but could be powerful.

Yes indeed!

**Comment by biolithic** [comment]
I just spent today working on Views plugins and I'm sick of the Views
interface!
Just kidding, will think about this issue.

**Comment by quicksketch** [comment]
An interesting solution was posted in the D8 world to this same problem. D8 also has "block instances" but doesn't have multiple layouts like we do, so they can run into a less severe form of the same problem.

One solution that has come up is the idea of "Block configurations", although I can't remember the name of the module that provides it... The idea is that you configure a block once, e.g. the "Main menu block". Then instead of placing the main menu block itself, you place a pre-configured version, such as "Configured block: Main menu". You can then edit the configuration of the block, and it shows up everywhere any instance of that block shows up. You are not able to change any block settings, they take effect everywhere that block is used. To configure the block settings, there is a new listing page of pre-configured blocks, which is accessible at a dedicated path.

This sort of combines the best of both worlds (with a little added complexity): You can reuse a pre-configured block everywhere you want the same settings, and if you have a one-off page that uses slightly different settings, you can place an instance of the original block that allows for full flexibility.

**Comment by BWPanda** [comment]
@quicksketch The only problem I see with that idea (apart from getting confused by the different terms and what 'pre-configured' vs. 'configured' is, though I imagine we'd make sure it was all named in an easy-to-understand way) is that it allows for the reuse of blocks, but not regions.

Say you have 10 different layouts (I don't know why, just go with me), and they all have the same 5 blocks in the header ('cause the header's the same on each page regardless). If you decide at some stage that you want to remove one of those blocks, or add a new one, you have to do that to each of the 10 layouts individually. If we could re-use regions as well (as per my suggestion), then the main/default layout would have 5 blocks in the header region, but each of the other 9 layouts would only have a single block (which references the header region in the default layout). So adding or removing a block would be as simple as doing it once to the default layout and all the others would be updated automatically.

**Comment by klonos** [comment]
Not much time lately and I'm still trying to catch up with all the issues posted during the last 10 days or so. Reading @BWPanda's issue summary (by the way long time no see in the queues, welcome back), my reaction and initial thoughts were the same as @dboulet: this resembles the way views displays work.

The way I see it though, we should not have reusable/symlinked **regions** but rather reusable/symlinked **blocks** + the ability to group blocks into block "containers" (think how iPhone and Android app shortcuts can be dragged onto another and they form a group). These block containers would also be blocks (in other words blocks within blocks), so they would have all of the features that blocks have ...including the ability to be made reusable/symlinked!

I don't think that we should have a notion of a "master" block that has "symlinked" instances. Not in the UI at least. Reason for this is that as a user places copies of reused blocks, they might at some point need to remove that very first, initial block but retain the rest in their respective layouts. Also, if one creates a reusable block and then places it in various regions of different layouts, they would not need to remember which layout holds the one that is the "master" one nor would they have to leave the layout they are currently editing. Editing the configuration form any layout, should reflect the changes to all instances. Removing any instance would not remove the reusable block from other layouts it is used in. So, in essence unless the very last instance is removed, the reusable block is not deleted. But in order to cover that use case too, lets add a "Remove all instances" action for reusable blocks *only*. Perhaps also a "Manage instances" action that lists all instances of the reusable block with info about which layout and which region in each layout hold them.

Use cases to make my point:

1. If we have reusable/symlinked **regions** with blocks in them, they would not be able to be moved around while still retaining their reusability. If these were reusable/symlinked **block containers** instead, we'd be able to place one of them say in the header of the front page, while have another instance in the footer and/or the sidebar of other layouts. Being blocks, they would have a name/title like all blocks have, so they would show up in the block browser and the users would be familiar with the process of adding them to other layouts... 
  - edit any one layout and add a "Recent comments" block and a "Recent posts" block in any region.
  - make both blocks reusable.
  - drag the "Recent posts" block onto the "Recent comments" block -> a "Container" block is created
  - rename the "Container" block to "What's new" and make it reusable.
  - edit another layout and click the add block button of a different region -> there is a "What's new" (reusable) block available with a description that says: "Contains the following blocks: "Recent comments" (reusable) and "Recent posts" (reusable)"

We could also allow users to:
  - remove the "master" block (the one they initially created), but leave all other instances intact.
  - break the symlink of either the master block or any one of its instances so that they keep any configuration made so far, but start differentiating this block from the rest of the instances.
  - be able to change all instances of such reusable blocks from whichever layout they happen to be editing instead of having to remember which layout holds the "master" version and then having to edit that specific layout.

So, I propose this:

1. Introduce the ability to make blocks reusable/symlinked/whatever-we-end-up-calling-them. 
2. Introduce the ability to group blocks in containers that are also blocks (so they have the same features as other blocks, like being reusable/symlinked).

**Comment by BWPanda** [comment]
I'm a bit confused, but I like what I do understand :smile: :+1:

**Comment by klonos** [comment]
@BWPanda the two points from my proposal above translated for the context of this issue here:

1. Allow *single* blocks to be reused in other layouts/regions
2. Allow *entire groups* of blocks to be reused in other layouts/regions

The reason why I insist on making *blocks* reusable instead of *regions* is for more flexibility (reuse *some* of the blocks within a region). Making the entire region reusable would "lock" the user to having to reuse *all* blocks within it.

In order to cover the use case where a user actually wants to reuse the entire region, we introduce the feature of block groups (#1691). Since block groups are blocks too, they also inherit the reusability feature. So there you have it: -> place all blocks of a region within a container block -> make that group block reusable -> magic!!

**Comment by BWPanda** [comment]
@klonos Ah, that explains better, and I like that idea! Thanks!

**Comment by klonos** [comment]
...I am usually sleep deprived and when that happens I tend to write lengthy posts that might not make sense to people. Seems like after I get some rest I'm able to better word things and get the message across more efficiently :wink:

**Comment by klonos** [comment]
> @klonos Ah, that explains better, and I like that idea! Thanks!

Then you wouldn't mind the issue title change?

**Comment by BWPanda** [comment]
> Then you wouldn't mind the issue title change?

Not at all. I just proposed an idea, so whatever is decided on to implement it or something similar, go for it! :)

**Comment by quicksketch** [comment]
I also like the idea of "reusable block groups" much more than reusable regions. I could see this being used to assemble something like a mega menu that might be made up of several blocks and reused on every page.

Though now that I say that, this makes me think that this suggestion is essentially "Mini Panels" from Drupal 7 (though without a layout part). Although adding a layout requirement to this request would be an increase in scope, it would solve another major shortcoming of our layout system when compared to Panels.

**Comment by jenlampton** [comment]
I like all these ideas:
* copy region from X layout
* copy block and settings from X layout
* include a mini-layout as a block

I'm not sure which of these should be in core. I could see all of them existing in contrib immediately, and I'm tempted to work on a block-recycle or region-recycle module for my own use :)

**Comment by klonos** [comment]
...for posterity/clarity, the feature request is not only for being able to copy things (as in cloning them), but to also keep the settings of the copies in sync no matter where you change them from.

**Comment by docwilmot** [comment]
After we shipped 1.5.0 with two versions of the Primary Navigation block (https://github.com/backdrop/backdrop-issues/issues/2222) it occurred to me that this issue could have prevented that. Thought I'd have a look. 
To clarify though, would these sync'd blocks share only settings, or everything including conditions and styles? @klonos @quicksketch?

**Comment by klonos** [comment]
See, we have 2 use cases here:

1. Some people want the ability to copy/place the same block in different layouts and when they change the settings (including conditions and styles) from within one layout, they want the changes to be applied to all instances of the block throughout the layouts.

2. Some others want to be able to have the same block copied to another layout but they need to tweak them independently from one another.

@docwilmot as you pointed out, #2222 is one example of use case 1 where being able to keep the configuration of two (or more) block instances in sync would have saved us the UX WTF, but that doesn't mean that use case 2 is not legit. The way we currently have it by default, blocks behave according to use case 2. The pickle here is to come up with an intuitive way to enable both behaviors and allow people to switch from one to the other.

As I have mentioned before, this resembles the way views displays work and how we give people the option to apply changes to either all displays (default) or the one currently being edited:

![backdrop-issue1886-views_displays_options](https://cloud.githubusercontent.com/assets/2423362/18836029/7f0b6102-8441-11e6-8b14-c2344c980b22.png)

...could we implement something similar to that with blocks and layouts?:

![backdrop-issue1886-layouts_block_layouts_options](https://cloud.githubusercontent.com/assets/2423362/18836076/ba0428ac-8441-11e6-95a6-7efa9d5c84ba.png)

Then, in order to denote a block instance which is not synced with the rest of the instances in other layouts, we could either be appending a plain asterisk on the custom block instances (like we do for overridden views displays):

![backdrop-issue1886-overridden_block_title-asterisk](https://cloud.githubusercontent.com/assets/2423362/18836472/8cd15d12-8443-11e6-8d1b-fa54b3064646.png)

...or some text (TBD) in brackets:

![backdrop-issue1886-overridden_block_title-text-overridden](https://cloud.githubusercontent.com/assets/2423362/18836484/9826e48e-8443-11e6-999c-bed61d2111e0.png)

![backdrop-issue1886-overridden_block_title-text-customized](https://cloud.githubusercontent.com/assets/2423362/18836501/a7fe4e24-8443-11e6-8b07-ae38cf7efae5.png)

**Comment by docwilmot** [comment]
I think I understood all that @klonos. Question was actually not answered though. What would the sync'd blocks share: only block settings (in the example above block settings would be "Menu style and "Maximum depth") or share everything (settings, as just described, *plus* "Style settings" and "Visibility conditions"). It would make a difference in the coding.

**Comment by jenlampton** [comment]
Visibility conditions may depend on contexts that are not present on all
layouts...

On Sep 26, 2016 8:39 AM, "docwilmot" <notifications@github.com> wrote:

I think I understood all that @klonos <https://github.com/klonos>. Question
was actually not answered though. What would the sync'd blocks share: only
block settings (in the example above block settings would be "Menu style
and "Maximum depth") or share everything (settings, as just described,
*plus* "Style settings" and "Visibility conditions"). It would make a
difference in the coding.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/backdrop/backdrop-issues/issues/1886#issuecomment-249589244>,
or mute the thread

**Comment by docwilmot** [comment]
> Visibility conditions may depend on contexts that are not present on all layouts...

True that. Settings alone then.

> As I have mentioned before, this resembles the way views displays work and how we give people the option to apply changes to either all displays (default) or the one currently being edited:

Reasonable idea, and I think out of the box every block in the "Home" and "Admin default" layouts should be a clone of the copy in the "default" layout (perhaps, haven't considered all consequences for all blocks). And when creating a new layout, the blocks should also be automatically be clones of the "default" layout's blocks. And when adding new blocks in an existing layout it should default to a clone if that block exists in the default layout, with an option to revert.

But one significant difference from Views though is that we'd need a UI to allow a person to select which block they want to create a clone from. I may want to have all my Nav blocks sync'd except for my "Users" layout and my "Company directory" layout, and want those two sync'd to each other instead.

So I was thinking instead of the Views-style "Defaut" and "Overridden", when a user goes to create a Nav block (for example), we have a select or radio or just a plain list of existing Nav blocks, with instructions to "Create a sync'd copy from..." (wording TBD). That, or an action link in the block config form that is labelled "Create a sync'd copy from..." but loads a new dialog with existing blocks of that type.

When you try to edit a clone any changes would apply to all other clones. With an option to override. If you override, then this block now becomes another unique clonable option.

**Comment by docwilmot** [comment]
> that is a simple checkbox that says make this block reusable

First impression, typed a great response as to why you're mistaken, but you're not. That's just what we should be doing. Except that "reusable" is probably not descriptive of what this would be in this case (synchronized, settings-sharing). 

And maybe we don't need the reusable checkbox at all; just make everything reusable by default. So the first core Nav block will appear in the block list as "Primary navigation", clicking to add it to another layout creates a clone of it. But if we wanted to make a new family of linked Nav blocks (as in [my example](https://github.com/backdrop/backdrop-issues/issues/1886#issuecomment-249628452) above), have a link/button that says "Create a new instance" (or better words which @jenlampton will figure out) which breaks the sync with the existing family, add a new label ("Primary navigation for users", and add this new block to the "Add block" list as a separate Nav block.

**Comment by jenlampton** [comment]
> everything reusable by default

I don't think everything should be reusable by default, we already have the default layout that solves the everything-reusable use-case. I agree that we should make some things shared by default, the menu is a great example. There may be other things that should have shared settings too, but they should be evaluated on a block-by-block basis.

> better words which @jenlampton will figure out

Ha! :)

**Comment by klonos** [comment]
Trying to brainstorm this...

1. Definition/naming-wise, instead of having people add blocks, we should convey the notion of adding block _instances_ instead.
2. A block instance would be a block (a thingie that does things) + the thingie's configuration.
3. A block as we have it now (the thing we add from the "add block" dialog) *already* has a default configuration, so nothing needs to change there.
4. All blocks would thus acquire the ability to be reverted to their default configuration.
5. Initially (fresh installation), all blocks added to various layouts from the "add block" dialog would be synced copies of each other. The would be the default behavior.
6. Once a different block instance is created (user breaks the config sync link of a specific block instance on a layout), then multiple config instances (or "families" as @docwilmot described them in his previous comment) of that block are created.
7. We need to decide how to allow the user to break the sync link in the UI (the views-like drop down is an option, lets brainstorm for more/better ways).
8. Once a block has at least one of its instances that are placed on layouts not using the default synced configuration "profile" (that could be another term), then when the user tries adding a block next time, we either a) present all the block instances as available options in the "add block" dialog, or b) we can have an extra step added in the last step of the "add block" dialog that prompts the user to choose from a list of available configuration profiles that they want the instance being added to be linked and synced to (this step is skipped on vanilla installations because all blocks instances have only the default, out-of-the-box config profile):

  This block has x instances. Select which instance you want to create a copy from:
  (x) Default configuration profile
  ( ) as used in layout x, region y
  ( ) as used in Layout y, region z

9. Besides the adaptation of the "add block" dialog (initiated from the respective action available _for regions_) which would serve as a "copy block and config **form** region x of layout y", it would be convenient if we also offered a second "copy this block instance **to** region z of layout y" way as @docwilmot previously said from an action available _for blocks_.

My thoughts so far of how this could work.

**Comment by docwilmot** [comment]
Simpler version: 
- allow blocks to disable clonability

if a block is clonable:
- The first instance of that block appears in the block list normally; it is placed normally. The next instance is by default a clone.
- In code, define a `sync_group` property for Block class. Store the group name and which block instances are members of the group; key this by layout with UUID as value.
- Once you create a second instance create a `sync_group` which gets the group name from the name of the first block. Add this `sync_group` to both blocks. (or maybe the first block starts with a `sync_group` with only itself as a member).
- List the `sync_group` name in the block list. This way, if there is only one `sync_group` this is completely transparent. e.g only `Primary navigation` will be in the block list as long as there is only one `sync_group` since that will be the name of the group.
- Since all blocks have the same `sync_group` info, there isnt a parent vs child relationship. Changes to one are sync'd to all. All instances say "Changes will be saved to all Primary navigation blocks". Deleting one doesnt delete the others. Perhaps an option when deleting to "Delete all".
- Have a link/button on each to create a unique instance. Require a label. This creates a new `sync_group` with this label which now appears in the block list as a different block (eg "User navigation") with some indication that this is actually a new group built from Primary navigation. Clicking this creates a new instance of course of the second group. 
- and so on.

**Comment by mikemccaffrey** [comment]
Hey folks, I worry that block instances could get very confusing very fast. I really think that we should consider the idea of region inheritance instead.

I'm thinking that when you clone a layout, each region is set to inherit the contents from matching region in the original layout. And then you can customize just the regions in the cloned layout that you would like to be different from the original layout.
 
That way, if a region such as the header is the same across all the layouts, you only need to update it once in the default layout and any change (including adding or deleting blocks) will be make across all the other layouts that are inheriting its contents.

Is there any reason you can see that this approach wouldn't work?

**Comment by docwilmot** [comment]
> I worry that block instances could get very confusing very fast

Probably true, although I feel the suggestion above does well to mitigate that. Some.

> consider the idea of region inheritance

The issue I find with that is that a "region" isn't a defined concept in Backdrop as such. Layouts don't need to have the same regions, contrib layouts aren't obligated to maintain naming conventions, there are no `foo_region_x` functions. It would be fragile to attempt region inheritance without creating new mandates for regions.

**Comment by mikemccaffrey** [comment]
> The issue I find with that is that a "region" isn't a defined concept in Backdrop as such. Layouts don't need to have the same regions, contrib layouts aren't obligated to maintain naming conventions, there are no foo_region_x functions. It would be fragile to attempt region inheritance without creating new mandates for regions.

Well, if you are cloning a layout just to make a couple of small changes (which seems like a very common use case), then it will have the same template and regions and it is simple to handle.

However, if you do want to use a different layout template with different regions, it would still be easy to allow people to specify inheritance by saying "I want this region to inherit the contents of X region in Y layout."

**Comment by docwilmot** [comment]
I'm thinking @mikemccaffrey is right after all. Its much more likely that a user would need a region to be sync'd than an individual block. Can we get consensus? I'd like to give this a try.

**Comment by jenlampton** [comment]
@docwilmot the reality is that there are good use-cases for both shared regions (the header and footer are great examples) and for shared block settings (I often want the same block in all sidebars, but I also have other/different blocks in each sidebar).  

If you want to take a stab at either I'd say go for it. Let's create a separate issue for locked/reused/inherited regions.

**Comment by mikemccaffrey** [comment]
> the reality is that there are good use-cases for both shared regions (the header and footer are great examples) and for shared block settings (I often want the same block in all sidebars, but I also have other/different blocks in each sidebar).

Well, I think that we need to consider the complexity, both in terms of the code and in terms of the user experience. The region inheritance seems like a relatively simple solution to implement and for the users to understand. I can't even begin to understand how we would implement block instances on the back-end or how exactly they would work on the front-end (though if someone has an elegant solution, I'd love to hear it).

However, allow me to throw another possible solution out there: we create a separate block type called Block Copy, which takes as its configuration a layout and the block within it that you'd like to duplicate in the current layout. That seems like something that could even be added to contrib first to try it out.

**Comment by jenlampton** [comment]
> I think that we need to consider the complexity, both in terms of the code and in terms of the user experience

this. 100% this.

> a separate block type called Block Copy.

I love this idea! The one thing I worry about is the "clone a layout" use-case, that would duplicate the blocks instead of copying them when most people in that situation probably wanted them copied. But, if we can get regions to inherit, maybe this will be less of an issue?

**Comment by klonos** [comment]
I cannot speak about code complexity as either solution would be above my skills, but it seems to me that although region sync would be the easy solution, it will leave end users with less flexibility. Examples:

A user wants to add a synced copy of the "Promoted content" block that is available in the main content area of the home page layout to the the default layout sidebar. They expect any changes they make to the block configuration to be reflected on both instances when they edit the settings of that block in either region/layout. The home page layout also includes a hero block in the same region as the "Promoted content" block but the user does not want that block copied or synced to the default layout sidebar. In this case, it's easier to understand that **the blocks in those two layouts/regions are synced clones of each other** than **the two regions are synced clones but some blocks from one region are not cloned to the other**

A similar scenario would include having the primary nav block in the header region of the home page layout while having a synced clone on the sidebar for the default layout. Users still expect the header block to be a synced clone across any header region of all their layouts, but they also expect the primary nav block to be a synced clone *despite* the fact that it is moved to another region for the default layout.

So, scenarios where region clones would not work as good as block clones are:

- having both cloned and non-cloned instances of blocks in the same/equivalent region of two different layouts.
- having a cloned block in different regions of different layouts
- adding/removing blocks from synced regions (some people might see additions/removals as a feature while others an undesired side-effect).

**Comment by jenlampton** [comment]
I don't think it needs to be an either/or @klonos. If we added a `Block Copy` block recommended by both @BWPanda in the first post, and @mikemccaffrey in one of the last we could follow that same pattern and add a `Region Copy` block in the same manner. Adding both these features would solve both use-cases, and allow site-builders to decide which they need on a site-by-site basis.

Here are the pair of issues (both tagged with 1.6, but we'll see about that)

* this one https://github.com/backdrop/backdrop-issues/issues/1886 `Copy Region`
* the other https://github.com/backdrop/backdrop-issues/issues/2245 `Copy Block`

**Comment by jenlampton** [comment]
Related: https://www.drupal.org/project/multiblock

**Comment by mikemccaffrey** [comment]
> We've basically com full-circle at and are back to the recommendation from the first post. I've just split the single "copy thing" block proposed into two, a Block Copy and a Region Copy

Personally, I'd still prefer to see the region inheritance. Then when you view a clone device layout, you see all the indidual blocks in a region, but greyed out. And then if you decide to override the region, it would create new instances of the blocks for editing.

**Comment by klonos** [comment]
> And then if you decide to override the region, it would create new instances of the blocks for editing.

Yeah, but that would then override **all** blocks contained in that region. That would effectively "unlink" all the blocks from their clones even though say the intention was to customize only one block in that region and leave the rest synced with their clones. Having the cloning be in the block level allows for more granularity on customization. Having *an option* to also copy entire regions would cover your use case. So, **bottom line: we need both block copies as well as region copies** and although the same set of block copies may functionally be similar to a region copy in some use cases, it is not the same thing.

**Comment by jenlampton** [comment]
> Personally, I'd still prefer to see the region inheritance. Then when you view a clone device layout, you see all the individual blocks in a region, but greyed out. And then if you decide to override the region, it would create new instances of the blocks for editing.

I don't see a reason that same experience can't be created with the region-clone block. 

> but that would then override all blocks contained in that region.

Not necessarily. It could convert all the other blocks to block-copies, leaving them tied to their source. You'd loose new blocks added to the other region automatically appearing in this one, but it could still be a huge time saver if all you needed was one different block setting.

**Comment by klonos** [comment]
>> but that would then override all blocks contained in that region.

> Not necessarily. It could convert all the other blocks to block-copies when one was overridden, leaving them tied to their source. ...

Yep, that would work greatly. But brings us back to the fact that we need both region **and** block copies.

**Comment by jenlampton** [comment]
> But brings us back to the fact that we need both region and block copies.

Yes. We have two issues!

**Comment by docwilmot** [comment]
I've pushed a PR for Copy Blocks. 

This one's harder conceptually though. We cant just have a region block because the region would be rendered wrapped within all the block HTML, contextual links etc., which really wouldnt work well for theming I imagine

Except if we override and `block_theme` to just print the naked block content for CopyRegion blocks, without any HTML wrappers. Keeping in mind that the "block content" would just be the parent blocks youre copying. This might work.

The alternative is to actually modify `layout.renderer_standard` to merge regions and blocks from the parent layout during the `prepare()` method, which seems like maybe an API change? not sure.

Im thinking the first option. @quicksketch?

**Comment by docwilmot** [comment]
First push. A region copy block.

**Comment by jenlampton** [comment]
@quicksketch mentioned in the meeting today that he was worried about selecting the source from any arbitrary layout. I think if that's a blocker, we could change this so that the source layout is only the default layout, then contrib can extend that to include other layouts (if needed).

**Comment by jenlampton** [comment]
Copying comment from https://github.com/backdrop/backdrop-issues/issues/2245#issuecomment-267449304: 

> Everyone agreed that there was no reason this approach couldn't be contrib module today, tested and improved in contrib, and then merged into core in a later release. Removing the 1.6 milestone in favor of a contrib module.

**Comment by BWPanda** [comment]
Sounds like the concensus was that this be a contrib module instead. Closing then.

**Comment by stpaultim** [comment]
There was a lot of interest in this functionality and a lot of good discussion. If, in fact this is being relegated to contrib, is there a better way of documenting what has been discussed?

Ideally, I would think that before we close this, we should reopen an issue in contrib land with a summary of this discussion OR at least a link to this closed issue. 

If we simply close this issue - isn't there a risk that all this good discussion will just get lost?

**Comment by docwilmot** [comment]
Actually @stpaultim this happened: [Copy Blocks Module](https://github.com/backdrop-contrib/copy_blocks) allows copying regions and blocks. So I think we could close this.

**Comment by stpaultim** [comment]
@docwilmot - Thanks for that. I've never tried that module. I'll close this again, but I'm going to leave it on the agenda for now as a reminder that I want to follow up on this.

**Comment by klonos** [comment]
FTR, https://backdropcms.org/project/usage/copy_blocks shows only 75 sites using this module out of 1600+ built in Backdrop. That may mean that this is indeed not an 80% use case, but recent discussions in [Zulip](https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/Outreach/near/232624256) and [a post in the forum](https://forum.backdropcms.org/forum/region-layouts) suggest that this may be another one of those things where people simply do not know that this contrib exists, otherwise they'd be using it 🤷🏼 ...to me, it still feels like it belongs in core, but perhaps once the contrib module usage stats go up, we could reconsider.
