### ISSUE TITLE
[UX] Improve the admin label for Views block displays

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1887]
![backdrop-views_ui-block_label-none_should_read_default](https://cloud.githubusercontent.com/assets/2423362/15343454/50f60c86-1ce0-11e6-8c2a-8ab315e09b83.png)

We should at the very least have it say "Default". We should definitely change that, but if we are to change it, we might as well take it up a notch...

Since "default" might seem cryptic (because it does not actually convey what the actual name will be), I propose to either describe what elements are going to be used, or display the actual value.

So instead of "none" or "default", it should either be "Use view and view display name" or better have it be "View: [view_name]: [view_display_name]" (with the tokens dynamically replaced by the actual values of course and we should fix #1889 too).

**Comment by BWPanda** [comment]
Try this on for size: https://github.com/backdrop/backdrop/pull/2775

**Comment by BWPanda** [comment]
@klonos You able to test this?

**Comment by stpaultim** [comment]
@BWPanda - Sandbox is still broken on this one. Can you refresh again?

**Comment by BWPanda** [comment]
@stpaultim Done

**Comment by stpaultim** [comment]
![Default_Layout___PR_2775_backdrop_backdrop_testing_site](https://user-images.githubusercontent.com/3144571/91669702-8a2b0000-eadc-11ea-8594-93717930d3e3.png)

So the actual admin label = "View: Test"

But the view lists it as "View: Test: Block"

Is that a mistake or is there a reason for that?

![Test__Content____PR_2775_backdrop_backdrop_testing_site](https://user-images.githubusercontent.com/3144571/91669708-9911b280-eadc-11ea-8c1e-e232e8bc7303.png)

**Comment by BWPanda** [comment]
Good point @stpaultim, PR updated.

**Comment by bugfolder** [comment]
I tested this by creating a View ("1887 Test") with three blocks: "Block", "Block 2", and "Block with a long name".

Admin display on the Views listing shows:

![image](https://github.com/backdrop/backdrop-issues/assets/29214084/7c32c889-0d2b-4ee4-926f-4d9063f71c88)

Within the View, each Block display shows:

![image](https://github.com/backdrop/backdrop-issues/assets/29214084/fe2e75c0-a7c6-4878-9de7-c327c0143e06)

and

![image](https://github.com/backdrop/backdrop-issues/assets/29214084/c62e2c09-322c-4a25-bad2-e4612ceb53d4)

and 

![image](https://github.com/backdrop/backdrop-issues/assets/29214084/6e2d7c18-c1a4-4af7-8a2a-2e70fe7d15b4)

So the first one doesn't show the Block name as part of the default admin label. (This is presumably due to the issue that https://github.com/backdrop/backdrop-issues/issues/1889 is addressing and would be addressed by that issue.)

I question whether the labels should be shortened with ellipsis here. That seems like a question that's out of scope of this issue (since it's the standard behavior that would be applied to a really long user-created admin label), but I do observe that other settings with the View editor get word-wrapped (like the "User pager: Display a specified number of items | N items" setting), so there's a precedent for that.

On a Layout page, the blocks are showed un-ellipsed:

![image](https://github.com/backdrop/backdrop-issues/assets/29214084/14d8da36-37dc-4f05-8e51-80283b7eb811)

So I think this is WFM.

This PR and https://github.com/backdrop/backdrop/pull/2774 (associated with https://github.com/backdrop/backdrop-issues/issues/1889) alter the same code, so when one of them is merged, the other will be conflicted, code-wise (not intent-wise). Both changes look good.

Otherwise, code reviewed, LGTM.

**Comment by quicksketch** [comment]
Thanks folks! I merged https://github.com/backdrop/backdrop/pull/2775 into 1.x and 1.26.x. A nice improvement on the default labels. Thanks @BWPanda for the PR, and @stpaultim and @bugfolder for reviewing!
