### ISSUE TITLE
Bartik: Artifact vertical lines in the comment arrow.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1894]
Before/after PR:

![backdrop-bartik-vertical_artifact_lines_in_comment_arrow](https://cloud.githubusercontent.com/assets/2423362/15356821/704e275e-1d3e-11e6-9fec-6ff5f087ab48.gif)

**Comment by quicksketch** [comment]
I couldn't reproduce a problem on a clean install of Backdrop. It looks like the border color is specified in bartik/css/colors.css:
```
.comment .comment-arrow {
  border-color: #ffffff;
}
```

It's specified in this file so that if the background color changes from white to a different color then the arrow border matches. Could you provide information on when/how the problem occurs? Then if we fix it, we will probably need to do so in colors.css rather than in style.css.

**Comment by klonos** [comment]
I cannot seem to be able to reproduce this anymore either. Sorry for taking long to respond.
