### ISSUE TITLE
Research continuous integration testing platforms besides Travis CI

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#1906]
This is a follow-up to https://github.com/backdrop/backdrop-issues/issues/1422, where we first encountered new, slower Travis CI servers. The new Travis servers are about 6 times slower than the old ones. Our test runs currently execute in about 15 minutes after we made the following improvements:
- We split concurrency from 2 builds (one for 5.3 and one for 7.0) into 6 (3 for 5.3 and 3 for 7.0), cutting time in half.
- We added a `--cache` tag to `run-tests.sh` that caches install profiles, cutting time in half again.

Had we been on the old Travis infrastructure, our times would have been cut from 15 minutes down to about 4 minutes. From a testing standpoint, this would be wonderful. Let's continue evaluating options to get faster and hopefully more consistent test results.

**Comment by quicksketch** [comment]
Vendors I've tried so far, copied from #1422:

- [Circle CI](https://circleci.com/): Up to 4 containers free for open source, so concurrent builds are possible. Does not do build matrices, though it may be possible to leverage parallelism to [emulate similar functionality](https://discuss.circleci.com/t/build-matrix/584/2).
- ~~[CodeShip](http://codeship.com)~~: Doesn't support Apache (or other web servers). No sudo support. Unable to run tests.
- ~~[ContinuousPHP](http://continuousphp.com)~~: Unable to run shell-script based tests (only PHPUnit or similar allowed). Did provide multiple PHP version testing though.
- [Shippable](http://shippable.com). So far the best contender. Supports multiple build versions and parallelization. Unfortunately doesn't include PHP 5.3, but does do 5.4 - 7.0. Build times seem similar to Travis though. They have a BYOH option so we could use their platform but use our own servers.
- ~~[Semaphore CI](http://semaphoreci.com)~~: Doesn't include GD or PHP-FPM in any of its PHP builds. Meaning you have to recompile it (+8 min runtime). Only a single version of PHP testable at a time. Not parrallelizable.
- ~~[Probo CI](http://probo.ci)~~: Build for Drupal sites. It runs PHP 5.5, multiple versions (or even selecting a PHP version) does not seem possible currently. They are a very new service, so hopefully something like that is planned. The good news is they complete our entire build in *10 minutes*, which is by far the fastest I've tested. They also provide "live sandboxes" as a side-benefit.
- [Snap CI](http://snap-ci.com): ~~Only a single version of PHP testable at a time.~~ Their support has provided a [work-around](https://gist.github.com/fernando-alves/ea16f57d56ea3ca3d2db29e6ba904c2c) enabling parallel processing of different versions. CentOS based, I haven't figured out how to get Apache wired to PHP. Might require manually installing PHP-FPM.

I've taken the liberty of crossing out ones that I don't think are currently capable of the features we need for Backdrop.

**Comment by quicksketch** [comment]
@Gormartsen is also working on making his service (which currently handles our live sandboxes) also do testing. A proof of concept is up at http://git.lc/Gormartsen/backdrop/test/test-php53-Gormartsen_backdrop_16-6142

I also don't think we need to exclude Travis CI from being a possibility. If we could get greater parallelism (we're currently capped at 5 concurrent builds) or faster servers, the current solution works well other than it's too slow and capped so our builds pile up on each other.

**Comment by Gormartsen** [comment]
I added 2 PR's:
- backdrop/backdrop#1413 :
  - core/misc/zen-ci/init_test.sh - this script is installing backdrop on INIT phase
  - core/misc/zen-ci/run_tests.sh - this script is wrapper for core/scripts/run-tests.sh to setup all necessary options for test run
  - changes to core/scripts/run-tests.sh (optional). Added option --zenci allow to report selected data back to ZenCI. This way run-tests.sh can actually set Travis status . Like ' 549 tests passed.' Or '** tests failed' . Also it provides summary to report page. Like

   ```
Update: Update core functionality (UpdateCoreTestCase)

fail "Checked available update data for one project." found update.test:195
    ```
    
    It helps to see what exactly get failed or produced exceptions, instead of scrolling down the log to see this messages.

- backdrop-ops/backdropcms.org#247 - this one add tests section to already used config file for QA integration.

## ZenCI features list:
- multiple PHP version testing.
- custom OS image .I built php53 and php70 images to run tests. It's ready to go OS images. No need to do apache, php and etc installs. Option `box: 'backdrop-php70'` tells system a box name to run a tests.
- different CPU templates. Right now I am able to provide 2,4 and 8 CPUs. templates for php53 and php70 based on 8 core CPU. In near future there is 16 and 32 core CPU templates are coming.
- there is no concurrent job limit. All tests starts as soon as PR or commit pushed. There is technical limit for now: I am using google compute engine and still have some QUOTA limit until project on Testing phase. It means that I have no more than 8 cores per region. This limit will be removed around first days of June. After that there i no limit to CPU cores and I am expecting no delays with tests delivery. Until then, there is possible delay with test box delivery.
- Possible to use your own server to run tests. Instead of define box option, user can provide server ip and tests will be started on that sever via SSH connection by public_key.

There is few more features but they are not applicable for test running task.

## Few test build results:
http://git.lc/Zen-CI/backdrop


Run tests for **php70** on pull request 3 — 549 tests passed.  details
Processed in: **6 min 4 sec**
Run tests for php53 on pull request 3 — 549 tests passed.  details
Processed in: **7 min 22 sec**


Run tests for **php70** on pull request 3 — 549 tests passed.  details
Processed in: **4 min 22 sec**
Run tests for php53 on pull request 3 — 549 tests passed.  details
Processed in: **9 min 33 sec**



Run tests for **php53** on pull request 3 — 549 tests passed.  details
Processed in: **8 min 21 sec**
Run tests for php70 on pull request 3 — 549 tests passed.  details
Processed in: **5 min 28 sec**

**Comment by quicksketch** [comment]
Thanks @Gormartsen! I really appreciate the work you've put into making this alternative! Although I'm nervous about committing to a custom solution. I know your intention to make a public service out of it and gives me more confidence. The nice thing is that we have the ability to switch between providers fairly easily, so we can give this a shot and see how well it performs. Of course also having you personally on the job is also a big advantage; having a system that is optimized for Backdrop is tremendously useful.

I left some feedback on your PR, I would like to keep any specialization needed for ZenCI in a single place. Though we can increase the abilities of the test running script in a generic fashion to help if needed.

**Comment by Gormartsen** [comment]
@quicksketch your comment on PR is answered.

**Comment by Gormartsen** [comment]
@quicksketch I updated PRs. I replaced option zenci with --summary. 

This option write to file errors and exceptions. 
ZenCI wrapper tests script is using this file to update status with summary.

Please check and let me know.

There is few tests examples for you:
http://git.lc/Zen-CI/backdrop/test/test-php53-Zen-CI_backdrop_5-6536
http://git.lc/Zen-CI/backdrop/test/test-php70-Zen-CI_backdrop_5-6538


Run tests for **php70** on pull request 5 — 549 tests passed.  details
Processed in: **4 min 52 sec**
Run tests for **php53** on pull request 5 — 549 tests passed.  details
Processed in: **8 min 36 sec**

**Comment by Gormartsen** [comment]
@quicksketch Let me know if you are ok with proposed changes and ready to enable it.
I agree that we can keep travis as a backup testing.

Somebody mentioned that for code sprint events tests speed is very important.
I have a few ideas how to enable Sprint Mode to PR.

We can utilize 16 core CPU and have special settings for misc/zen-ci/run_tests.php script to run in 16 (or even 20) concurrency mode.

It will speed up php53 tests up to 4 minutes in total + setup environment time. It will be like ~4-5 minutes since PR posted.

php7 is already under 5 minutes in total. Actual tests takes 3-4 minutes. There is no need to run it on more that 8 core CPU platform. If we start it on 16 core CPU it will low down total time from 5 minutes to 3-4 minutes. It's cute a small benefit.

**Comment by quicksketch** [comment]
I'd like to give this a shot @Gormartsen. I'll clean up your PR a bit for coding standards and make a new PR. Let's start a new issue specifically for Zen.ci/Git.lc. I made one over at https://github.com/backdrop/backdrop-issues/issues/1947.

**Comment by quicksketch** [comment]
Per https://github.com/backdrop/backdrop-issues/issues/1947#issuecomment-236012669, we've been using ZenCI for months now with great success. Travis CI has been disabled on our repositories. Let's close this issue as fixed.
