### ISSUE TITLE
URL node/###/delete shows the wrong layout if default admin theme is chosen for editing content

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#1916]
On this particular site using 1.4.2 I've chosen "Use the administration theme when editing or creating content". The expected behaviour is that when deleting nodes from /node/###/delete that it'll use the Default Administrative Layout and the admin theme. What actually happens is that it does *not* use it but shows default layout for most node/### urls while still showing the admin theme.

**Comment by quicksketch** [comment]
Hi @herbdool, thanks for filing this issue. I can't seem to reproduce this problem. I set the default admin layout to "Taylor Flipped" and the front-end layout to "Moscone". Visiting `node/1/delete` uses the the admin layout ("Taylor Flipped") as expected. I also tried overriding the path `node/%` to see if that would cause the problem, but the layout template I selected showed up on the node page but not the node delete page.

It is worth noting that if `node/x/delete` is a 404 or 403 page, then the layout does *not* get used. But that is intentional because the layout for the 404 or 403 pages use the template specified at their internal paths (e.g. if you made `node/1` your 404 page, it would use the layout from `node/%`).

**Comment by herbdool** [comment]
Sorry @quicksketch I should have tested it on a fresh site to compare. I don't see it on the fresh site. It might have something to do with an upgrade from Drupal 6 to 7 to Backdrop.

The node definitely existed.

**Comment by herbdool** [comment]
This might be a bug but not in the way I thought. I'll explain how I created the issue: I had created a layout for the front page and had specified the path as node/% and the visibility condition as "front page". I had an existing node assigned to the front page on the site information form. The site looks fine, but for any node/%/add, node/%/edit, node/%/delete it would show the front page layout (when the content editing screen is set to the admin theme). Looks like front page visibility won't exclude those paths.

To avoid it use visibility condition = node/## or create a layout path without the wildcard and assign that path to the front.

**Comment by klonos** [comment]
Sounds like a bug to me. If a layout is set for the front page (as in visibility condition "is front page" - *not* to a specific node ID or path), it shouldn't be applied to the respective add/edit/delete subpaths of the front page. ...especially when the content edit theme is set to the admin theme.

**Comment by klonos** [comment]
...in my tests though, I could not reproduce this issue:

1. create a new "front page" layout with path `node/%`
2. set a single visibility condition of "is front page"
3. create a node
4. set the site front page to the `/node/1` (or whatever `nid` the content created in step 3 above)
5. visit front page -> "front page" layout used
6. edit front page node -> admin layout used

**Comment by herbdool** [comment]
I can't replicate it on a different site either. I tried editing front page node and any other node. I'm just going to close this.
