### ISSUE TITLE
Module search does not work

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1921]
For example I want to install zurb6_full_toolkit module.

I do not see it in the list.

Well, I try to search it: _zurb_, _zurb6_ or _zurb6_full_toolkit_

**No results found.**

Very sorry to see things like this.

**Comment by biolithic** [comment]
for zurb6_full_toolkit does the path admin/structure/layouts/install exist
on your site after installing Project Browser module in 1.4+?

Note, this is a layout project but nothing happens when you download it.
It is a toolkit for you to copy and paste code to make your own custom
layouts like the BD core layouts, but with extra regions.

**Comment by bd0bd** [comment]
I try to install it in /admin/modules/install because it is a MODULE.

And there is no b4_radix_full in the list.

**Comment by quicksketch** [comment]
> I try to install it in /admin/modules/install because it is a MODULE.

From the .info file of the projects, they appear to be layout templates:

https://github.com/backdrop-contrib/zurb6_full_toolkit/blob/master/zurb6_full_toolkit.info

The `type = layout` line indicates they are layout templates. Currently the pages for installing themes, layouts, and modules are separate. So for installing these layout templates, you have to go to admin/structure/layouts/install.

**Comment by bd0bd** [comment]
Thank you very much!
