### ISSUE TITLE
Prevent URLs or email addresses turning into links

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#1926]
Scenario: I'm writing a page and in the Body field I want to enter a dummy email address (e.g. info@mybusiness.com). When I save the page, the text filters are run and the email address is turned into a clickable link. I don't want that. However, I cannot remove the 'Convert URLs into links' filter from the text format, as I need other pages to have clickable links (e.g. URLs or real email addresses), and I cannot create a new text format without the URL filter to use for this specific page as I may need other URLs or email addresses on the same page to be turned into links...

So I'm wondering if there's a way (or if not yet, can we make one) where I can tell a specific URL or email address to not turn into a link (either before or after saving the node)?

---
PR by @BWPanda: https://github.com/backdrop/backdrop/pull/2776

Advocate: @BWPanda

**Comment by quicksketch** [comment]
Hi @BWPanda! Thanks for making this request. As far as I know, this is *not* currently possible. Even a module like https://github.com/backdrop-contrib/codefilter won't prevent emails and URLs from being linkified.

I'm not sure how this would be implemented from a core-standpoint. But from a contrib-standpoint, you could probably make a special filter that *removed* links under certain circumstances. e.g. Links within `<code>` tags, backticks, square brackets, or some other indicator.

**Comment by quicksketch** [comment]
Just thinking out loud here... I think it would be reasonable for Backdrop core to not linkify email addresses and URLs when within `<code>` tags. Though I think that change might make for a substantially more expensive filter callback. If we implement it, lets also benchmark to see what kind of cost that would have.

Separately, code tags are particularly difficult to deal with right now in CKEditor, see https://github.com/backdrop/backdrop-issues/issues/1267.

**Comment by BWPanda** [comment]
I had no idea how one would indicate that an email address shouldn't be linkified, but your suggestion about wrapping it in something (<code>, brackets, etc.) is a good one.

**Comment by BWPanda** [comment]
Here's a [PR](https://github.com/backdrop/backdrop/pull/2776) that addresses this by skipping any potential links in a `<nolink>` tag. I made this tag up (but it seems others have [had the same idea](https://docs.moodle.org/37/en/Nolink_tags) before me), and it works both by adding the tag manually to your textarea's source code, or using CKEditor's `Styles` dropdown with '`nolink.nolink|No link`' as a listed 'class' (unfortunately you can't add styles without classes, hence the duplication).

Maybe not the best solution (e.g. not a valid HTML tag for one), but one of the simplest I could think of that doesn't style your non-links a certain way (e.g. like using `<code>` or `<pre>`).

Feedback/other suggestions welcome.

**Comment by klonos** [comment]
I find it the `<nolink>` tag a great idea actually 👍

**Comment by BWPanda** [comment]
If #2980 gets committed, then that'll make it easier for people to add `nolink` tags.

**Comment by olafgrabienski** [comment]
Useful! The [PR](https://github.com/backdrop/backdrop/pull/2776) works for me when I add `<nolink>` to the allowed HTML tags of the *Filtered HTML* format.

Test page: http://2776.backdrop.backdrop.qa.backdropcms.org/test-page

**Comment by docwilmot** [comment]
Could we get `_filter_url()` to actually just remove the `<nolink>` tag instead of ignoring it?

**Comment by BWPanda** [comment]
@docwilmot When someone creates a new node, adds <nolink>, saves, it gets removed, then they edit the node, will the <nolink> tag not be gone and therefore URLs become unwanted links?

**Comment by docwilmot** [comment]
No its only removed on display. The text stored in the database is never affected the filter right?
The main reason for my suggestion is not to have an invalid HTML tag on display.

**Comment by quicksketch** [comment]
>  The main reason for my suggestion is not to have an invalid HTML tag on display.

I agree. I don't think we should be outputting non-standard HTML tags on the output. From reading the code, it looks like auto-linking is _already_ disabled if you use a `<code>` tag. As that's valid HTML and already is working, couldn't you simply use that?

**Comment by BWPanda** [comment]
Which is worse: outputting a non-standard tag, or using a tag for a purpose other than what it's designed for?

To me, using `<code>` for simply preventing URLs turning into links seems hacky. Any even if you're ok with that, there's often custom styling for `<code>` tags. We likely don't want URLs displayed on a different background colour, or in a different font...

**Comment by quicksketch** [comment]
I don't think this really makes it "right", but you get the same results here on GitHub. For example typing a URL or email is a link normally:

joe@example.com
https://example.com

But when you wrap in backticks it doesn't link:

`joe@example.com`
`https://example.com`

You're right you'll get the styling of the code tags which might not be desirable.

It looks like the [Moodle documentation](https://docs.moodle.org/37/en/Nolink_tags) referenced earlier points out that `<nolink>` was available historically but they replaced it with `<span class="nolink">` on output for W3C compliance.

**Comment by BWPanda** [comment]
I think I'd prefer the `span` option then. It also seems to me like a nice thing to have where looking at the source code would show the `nolink` class as a form of 'documentation' as to why the URL's not clickable.

**Comment by docwilmot** [comment]
Or why dont we remove the tag like I suggested?

**Comment by BWPanda** [comment]
> Or why dont we remove the tag like I suggested?

Yes, I meant to say that that's also an option. Though I think I'd personally prefer to have something in the resulting source code that indicates the 'nolink' status. I'll try working on a solution that uses a span tag. If you want to work on your solution @docwilmot we can test both, otherwise I'll revert to yours if I get stuck otherwise.

**Comment by BWPanda** [comment]
I've updated the [PR](https://github.com/backdrop/backdrop/pull/2776) with code that checks for the `nolink` class and prevents linking those elements. My regex is not very good, so improvements/optimisations/testing/etc. very welcome.

Here's an explanation of my regex:
`<([a-z0-9]+)\s+[\s\S]*?class=[\"'][\s\w-]*(?:$ignore_classes)[\"'\s]+(?:\s|>)`

- `<`: Start HTML tag
- `([a-z0-9]+)`: The tag element name (1 or more letters and numbers), captured group to add to `$open_tag` if match found
- `\s+`: 1 or more whitespace characters (to separate tag element from attributes)
- `[\s\S]*?`: 0 or more characters (any), but lazy (so as not to skip the 'class' attribute)
- `class=`: The start of the 'class' attribute
- `[\"']`: Either a " or a ' (which surround the classes)
- `[\s\w-]*`: 0 or more whitespace, letter, number, underscore and hyphen characters (basically any classes that come before the one(s) we want)
- `(?:$ignore_classes)`: The class(es) we're looking for (un-captured group)
- `[\"'\s]+`: 1 or more ", ' or whitespace characters (either more classes, or the end of the 'class' attribute)
- `(?:\s|>)`: Either whitespace or the end of the HTML tag (copied from existing regex)

It seems to be working with a very simple test, but more testing obviously needed.

**Comment by olafgrabienski** [comment]
Another idea, or workaround: Switch the Editor to Source code, and add an empty `<a>` element, i.e. without the `href` attribute:

`<a>https://www.example.com</a>`

Depending on the CSS, the URL might be still be styled as a link, but it's not clickable.

The W3C says on https://www.w3.org/TR/2016/REC-html51-20161101/textlevel-semantics.html#the-a-element:

> If the `<a>` element has no `href` attribute, then the element represents a placeholder for where a link might otherwise have been placed, if it had been relevant, consisting of just the element’s contents.

Further reading:

- https://stackoverflow.com/questions/5292343/is-an-anchor-tag-without-the-href-attribute-safe
- https://css-tricks.com/how-to-disable-links, amongst others with a section about CSS styles for 'disabled' links

**Comment by klonos** [comment]
Sorry for taking so long to review this @BWPanda ...this seems like a very useful feature, as it would otherwise make people scratch their heads with the dead-end the current situation puts them into.

Anyway, I've tested the regex, and it seems to be failing in certain cases. Here's what I've used to test various cases I could think of:
```
<s0meTAG class="nolinktest">
<s0meTAG class="testnolink">
<s0meTAG class="test-nolink">
<s0meTAG class="test_nolink">
<s0meTAG class="nolink" >
<s0meTAG class="nolink">
<s0meTAG  class="nolink">
<s0meTAG  class="nolink" >
<s0meTAG class=" nolink">
<s0meTAG class=" nolink ">
<s0meTAG class="nolink ">
<s0me-TAG class="nolinktest">
<s0me-TAG class="testnolink">
<s0me-TAG class="test-nolink">
<s0me-TAG class="test_nolink">
<s0me-TAG class="nolink" >
<s0me-TAG class="nolink">
<s0me-TAG  class="nolink">
<s0me-TAG  class="nolink" >
<s0me-TAG class=" nolink">
<s0me-TAG class=" nolink ">
<s0me-TAG class="nolink ">
<s0meTAG some="thing" class="nolink">
<s0meTAG class="nolink" some="thing">
<s0meTAG some="thing" class="nolink" something="else">
<s0me-TAG some="thing" class="nolink">
<s0me-TAG class="nolink" some="thing">
<s0me-TAG some="thing" class="nolink" something="else">
<s0meTAG class="test1 nolink test2">
<s0meTAG class="nolink test">
<s0meTAG class="test nolink">
<s0meTAG class="">
<s0meTAG>
<s0me-TAG class="test1 nolink test2">
<s0me-TAG class="nolink test">
<s0me-TAG class="test nolink">
<s0me-TAG class="">
<s0me-TAG>
```

Here's a test with the first version of the regex (same as in your PR): https://regex101.com/r/1jceDp/1

There's a few things to note:

1. Using `(?:$ignore_classes)` (which translates to `(?:nolink)`) in the non-capturing group, has the effect of matching the individual characters in the word "nolink" instead of the whole word. So the regex as is ends up matching the classes `testnolink`, `nolinktest`, `test-nolink`, `test_nolink`, etc.

  In order to fix this, we need to set word boundaries, i.e. `\b(nolink)\b`. I have started from scratch, in order to simplify the regex with: https://regex101.com/r/1jceDp/2

  Now, `\b` seems to include hyphens before/after the word, so it works for underscores, but it still matches things like `test-nolink`, `nolink-test`, and `test-nolink-test` etc.; so I had to use a negative lookbehind to exclude hyphens before (`(?<!\-)`), and a negative lookahead to exclude hyphens after (`(?!\-)`): https://regex101.com/r/1jceDp/3

2. With the exact word "nolink" matched as expected, next thing is to wrap that in a `class=`: https://regex101.com/r/1jceDp/4

  That works, but does not account for multiple classes or any spaces. I could go with trying to match whitespace and words, but since we have set word boundaries in "nolink", all we should care about is the starting/ending single- or double-quotes - nothing in between matters. So I went with matching exactly one single instance of those, with `[\"']{1}` and then allowing for 0 or more instances of any character in between: https://regex101.com/r/1jceDp/5

  If I wanted to be pedantic about it, I could have made the second `.*` lazy/non-greedy (`(.*?)`), which would only match characters till the first occurrence of a `"` or a `'`. So the whole thing would match the `class="` bit, move on with any other spaces and/or classes before it finds the `nolink` class, then the `nolink` class itself, then continue with any spaces and/or classes after that, and then finally stop at the end of the inline classes declaration. I don't think that this adds any real value though, so I went with a simple `.*`, which accounts for any attributes declared after the classes.

  I then:
  - appended `\s?>` to account for any spaces before the closing `>`, as well as the `>` itself: https://regex101.com/r/1jceDp/6

3. HTML tag _names_ are allowed to have only letters and hyphens (hyphens denote non-standard, custom-created tags). I guess that people that do not know this may use numbers as well, but since the intention here is not to fix things to comply with standards, it doesn't hurt to account for numbers in the regex; but we do need to tweak it to account for hyphens.

  So, assuming that expecting digital in the tag name is fine, the `[a-z0-9]+` bit in the original regex in the PR that checks for the start of a tag, should be `[a-z0-9-]+` instead (uppercase letters, which are valid for HTML tags are already accounted for by the `i` at the end of the regex).

  After that, the `\s+` to account for one or more whitespaces if OK, but the `[\s\S]*?` bit can be replaced by a simple `.*` (because it really doesn't matter - the regex will stop at the first occurrence of `class="`, because of the `class=[\:']{1}` bit) 😉 

Final regex here: https://regex101.com/r/1jceDp/7 (it could use more 👀 so that people can come up with more possible scenarios and see if the regex still accounts for them)

**Comment by klonos** [comment]
@BWPanda can you please restart the PR sandbox as well when you get a chance, as it's broken? Thanks.

**Comment by klonos** [comment]
...I would also like us to update the filter help text, to denote that this feature is there. Something along these lines this perhaps?:

> Web page addresses and e-mail addresses turn into links automatically. **Add a `nolink` class to any linkified text to prevent it from being rendered as a link.**

There's more to this, since even the help text would only increase visibility for site builders/editors (and the curious ones that expand the "Formatting options" fieldset); but I'll file a follow-up issue, to improve the UX for content editors.

**Comment by BWPanda** [comment]
I've updated the PR to be hopefully easier to maintain. Instead of trying to match the 'nolink' class in the regex, the regex now just gets the string of all classes, then uses PHP to explode and find any 'nolink' classes.
I also updated the help text.

![Peek 2021-03-05 15-01](https://user-images.githubusercontent.com/2385329/110065707-e3455a80-7dc3-11eb-8906-b8dca7d1c3c2.gif)

**Comment by BWPanda** [comment]
I'm now advocating for this issue.

**Comment by philsward** [comment]
I'm not opposed to a class as the trigger, but I have to wonder if it might be better to approach it as a token type of regex so "any" filter can utilize it. Not all text formats will allow classes...

Example Token (token may not be the right term to call it btw)

someone@somewhere.com:nolink

www.somedomain.com:nolink

This would allow someone with a limited HTML text filter that includes links, but doesn't allow classes to participate in creating this text.

Just a thought and might allow other "token extensions" down the road. (Probably need to find a better term than token... Format Psudos?)

**Comment by olafgrabienski** [comment]
Works for me in a post of the sandbox website:

`<p>www.example.com</p>` and `<p>info@example.com</p>` are displayed as links,
`<p class="nolink">www.example.com</p>` and `<p class="nolink">info@example.com</p>` are displayed as normal text.

@philsward I see, the solution isn't ideal (text format needs to allow classes, class has to be on the parent element), but it's a great improvement, and it works on posts and pages of a vanilla Backdrop site, so I'm all for it. What do you think about filing the appended 'token' idea as a separate issue?

**Comment by philsward** [comment]
@olafgrabienski I'm open to the new issue for the "token" idea. Before I do that, what is the general consensus on that idea? Is it warranted it am I overthinking it?

**Comment by BWPanda** [comment]
@philsward I think there's merit to the idea; not just for this use-case, but possibly other things as well. So I'd say open an issue to discuss it and we can see if there's more consensus there.

**Comment by quicksketch** [comment]
The PR looks good to me @BWPanda! We need test coverage for this new behavior. Could you expand the existing `FilterUnitTestCase::testUrlFilter()` tests to include new checks?

**Comment by BWPanda** [comment]
@quicksketch I added a test to the PR, please let me know if that's suitable...

**Comment by quicksketch** [comment]
Thanks! PR looks good and new test coverage covers a lot of possibilities. Looks RTBC to me. I'll leave this open for a few days to collect any further feedback.

**Comment by BWPanda** [comment]
Thanks to @klonos, @quicksketch, @olafgrabienski, @docwilmot & @philsward for your help, feedback, etc. I've gone ahead and merged https://github.com/backdrop/backdrop/pull/2776 into 1.x as it's been RTBC for almost 2 weeks now.
