### ISSUE TITLE
Upgrade Travis-CI to use trusty distribution

### ISSUE THREAD

**Issue by deekayen** [backdrop/backdrop-issues#1945]
I know with #1906 lingering, this may not be the most welcome idea, but the end of life for Ubuntu precise will be upon us in no time. I spent the day upgrading the .travis.yml file to make successful builds using the travis-ci trusty beta environment.

I didn't really expect this to be something as formal as doing a pull request, but I did save the patch between the current precise version and trusty.

Here's my last successful build before creating this issue: https://travis-ci.org/deekayen/backdrop/builds/133834857

Highlights:
- Uses minimum version of PHP 5.5 instead of 5.3 since trusty shipped with 5.5.9 (travis also doesn't offer 5.3 as an option in trusty).
- RUNSPLIT creates 4 jobs instead of the current 6. It adds a minute to the elapsed time, but reduces the compute time by about 6 minutes. This frees up time for another job on a different build. I think the reduction is savings from not doing the VM setup two more times.
- MySQL server isn't installed by default, so this change adds it in the new apt addon.
- Ubuntu multiverse isn't in the default travis image, so this build config has to add it to be able to install libapache2-mod-fastcgi.
- The default name of the apache site filename changed. This adjusts to use the new one.
- The precise travis home directory has more permissive access it seems, so this has to chmod for Apache to be able to read the cloned files.
- The vhost.conf file had to be modified to override the default setting to deny access to the directory. Without the change, Apache returns a 403 forbidden error when trying to load localhost.
- I also sort of "accidentally" left out the addition of install-xcache.sh, which didn't seem to impact the results much - should discuss its need and whether to remove the install-xcache.sh file from the path as part of this.

Gist with a patch and the result file: https://gist.github.com/deekayen/10b286c90fd66184bddc1db4b75ec4f9

If you're interested, I'm keeping the branch in my fork in case I should turn it into a pull request.

**Comment by quicksketch** [comment]
Thanks @deekayen! Updating those .travis.yml files can be quite tedious, thanks for taking this on. I think it would be great to use the Trusty distro instead. The only caveat here is that we need to still test PHP 5.3. If we're not running tests on it, it is as good as not supported at all. Without testing it, we could easily run into situations where we'd ship a release that wouldn't work due to simple syntax differences (e.g. the new array syntax `[]` instead of `array()`).

Trusty is still supported until April 2017 (https://wiki.ubuntu.com/Releases), so we still have another year of PHP 5.3 being supported (CentOS 6 is in a similar boat, though they [provide maintenance updates all the way until 2020](https://wiki.centos.org/About/Product)!)

So this is great to get onto the newer platform, but we need to keep testing 5.3 unless we decide to drop support for it entirely.

**Comment by klonos** [comment]
https://github.com/phpbrew/phpbrew

https://github.com/phpenv/phpenv

**Comment by Gormartsen** [comment]
@klonos building PHP before test will postpone actual test run. It will affect total test time dramatically.

 Here https://docs.travis-ci.com/user/trusty-ci-environment/

They should delivery mega image with all php versions, but it's not done yet:

> We do not currently have any PHP versions pre-installed in the mega image. This is at the top of our list for our next update.
But we do have phpenv installed and it’s able to install the following PHP versions.
PHP 5.3
PHP 5.4
PHP 5.5
PHP 5.6
PHP 7.0.0 RCs

So php-env should be able to install php5.3 at this stage.  But again, it will extend test time.

**Comment by klonos** [comment]
Yep., thought it might be so. Just thought I'd mention it anyways.

**Comment by deekayen** [comment]
phpenv failed when I gave it 5.3 to chew on in travis: https://travis-ci.org/deekayen/backdrop/jobs/134352772

5.4 did install with phpenv (with a demonstration of random failures on a known-clean sha1): https://travis-ci.org/deekayen/backdrop/builds/134353137

I understand the support conflict since 5.3 was the default package in precise, but I'd be sad if the next test system was selected based on its ability to support PHP 5.3 - it was released in 2009 and was EOL in 2014. Even PHP 5.4 was EOL last year. I don't mean this thread to be in a rush to do a trusty upgrade - I was more looking for a place to save my work for others.

**Comment by Gormartsen** [comment]
@deejayen tnx for sharing!

IT is frustrating to be stuck with old distro release.

For situation like this, since you use the same distro release , you can build deb package for php53 on your own server and then upload somewhere online.

On setup phase just download and install it . It will save startup time.

For my clients I even have old centos5.x with php5.2 for Drupal 6 websites. 
And even this days, when php7 is on stable release and drupal7 kinda support it, I have server with php53 for Drupal 7 clients.  I tried once to upgrade to php5.6 and encounter too many issues with self written or contrib modules and themes.

Not every client can allow upgrade budget, and php53 compatibility test at this point is very important.

**Comment by photodude** [comment]
FYI you could have specified specific distros for each PHP version.
Precise for PHP 5.3 and trusty for anything else.
example
https://github.com/joomla-framework/database/blob/master/.travis.yml
