### ISSUE TITLE
How to work out which config file a config option is in?

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#1954]
In converting a theme from Drupal to Backdrop, I had to convert `variable_get()` to `config_get()`. However `config_get()` requires you to know which config file the variable/config option is stored in. In #621 someone had the same problem, but it was never explained how to find this out without searching through each config file.

Is there an easy way to find this out?

If not, I'll add a feature request to the Devel module as Drupal's version has `/devel/variable`.

**Comment by jenlampton** [comment]
I usually either grep through the config directory for the variable name, or if I have an idea which module might provide (or at least use) that value, I grep through that module for the variable name.

**Comment by BWPanda** [comment]
After doing this myself more recently, I agree that simply searching through your site's config directory should help find what you're looking for. And yes, it'd be hard to list all config options in a useful way.

**Comment by Michael-IDA** [comment]
Hi Peter,

Would you re-open this issue?  Maybe change the title to include ‘programmatically?’

As desired I’ll open a separate issue, but this one seems appropriate?

Copy/pasting the relevant bits from the other issue.

> Instead of:
> 
> ```
> $variable = variable_get('foo', 'bar');
> variable_set('foo', $variable);
> ```
> 
> It looks like this:
> 
> ```
> $variable = config_get('mymodule.settings', 'foo');
> config_set('mymodule.settings', 'foo', $variable);
> ```

`config_get($config_file, $option = NULL)`

So...  How does one find out programmatically what `$config_file` `foo` is in?

(e.g. for code that isn't in a module environment, so you’ve got no way to hard code it.)

Crappy example...

Drupal:
```
$variable_default = 'bar';
$variable_name = $look_this_up_for_me;

$variable = variable_get($variable_name, $variable_default);
```

Backdrop:
```
$variable_default = 'bar';
$variable_name = $look_this_up_for_me;

$config_file = {return the JSON file name that contains $look_this_up_for_me}

$variable = config_get($config_file, $variable_name);
if empty($variable) {
  $variable = $variable_default;
}
```

As others have indicated, yes you could scandir the config_xyz directory for JSON files, load each one, search for your var, but uhg the performance hit :(

Gotta be a better way?

Thanks,
Michael

**Comment by jenlampton** [comment]
@Michael-IDA can you give us an example of where this is needed? 

Most of the time, if you are trying to get/set/delete a variable, you know what the variable is used for. If you know what the variable is for, you usually also know what module provided it. Then you can check that module for the config files it provides to find the one that contains the value you are after.

> (e.g. for code that isn't in a module environment, so you’ve got no way to hard code it.)

I'm particularly curious about this, when would you need a variable but not be in a "module enviornment"? A real-world use-case would be helpful here :) 

Thanks!

**Comment by BWPanda** [comment]
> How does one find out programmatically what `$config_file` `foo` is in?

Thanks for the question @Michael-IDA, I'm sure many people have this problem when first starting with Backdrop config :slightly_smiling_face: 

The short answer is that there's no easy way to do this; but neither is there a need to do it.

To explain, let's look at how variables work in Drupal 7... In the coding standards it [says](https://www.drupal.org/docs/develop/standards/coding-standards#s-persistent-variables):

> Persistent variables (variables/settings defined using Drupal's `variable_get()`/`variable_set()` functions) ... should use the grouping/module name as a prefix, to avoid name collisions between modules.

Drupal's variables are global in the sense that if one module sets a variable `foo` (e.g. `variable_set('foo', 'My foo value')`) and another module also sets a variable `foo` (e.g. `variable_set('foo', 14)`), then the `foo` variable is going to be changed from `'My foo value'` to `14`. That's why the coding standards recommend prefixing variable names with the group/module name (e.g. `variable_set('my_module_foo', 'My foo value')` vs. `variable_set('another_module_foo', 14)`).

In Backdrop, we've simply changed this recommendation into a requirement. When a module creates a config value (e.g. a variable), the module/group name is used as the prefix: `config_set('my_module.settings', 'foo', 'My foo value')`. The name of the config file where the value is stored (`my_module.settings.json`) can be thought of as the prefix for the values therein.

In the Drupal example above, you don't ask for the value of the `foo` variable, you ask for the value of either the `my_module_foo` variable, or the `another_module_foo` variable. Basically you need to know what a module is calling their variables before you request them.

It's the same in Backdrop. You don't ask where to find the `foo` value, because there could be lots of `foo` values: one in `my_module.settings.json`, another in `system.core.json`, etc.

**Comment by Michael-IDA** [comment]
> @Michael-IDA can you give us an example of where this is needed?
> I'm particularly curious about this, when would you need a variable but not be in a "module enviornment"? A real-world use-case would be helpful here :)

```
alias lastcron='echo `drush vget cron_last --exact | awk '\''{print $2}'\''` | { read a; date -d @$a; }'
```

Migration code, see: https://forum.backdropcms.org/forum/data-migration-d7-backdrop
(hmm, it'd be in the 'etc.' part...)

Nightly maintenance tasks.  (Could hard code that though, but really breaks portability/re-usability)

@BWPanda , I'll have to read your reply in the morning :(

Best,
Michael

**Comment by BWPanda** [comment]
@Michael-IDA For the specific example you gave above, it looks like `cron_last` was converted to a state value instead: https://api.backdropcms.org/change-records/statekey-value-storage-system-implemented

So I guess you can just use `state_get('cron_last')` in this case...

**Comment by docwilmot** [comment]
Doesnt Drupal Devel list all variables? Can backdrop Devel do the same?

**Comment by Michael-IDA** [comment]
Hi All,

> So I guess you can just use `state_get('cron_last')` in this case...

That makes it significantly worse.  It was also an example, substitute any variable you wish, here’s Ubercart’s:

```
# drush vget uc_
date_format_uc_store: "m/d/Y"
field_bundle_settings_uc_order__uc_order: Array

  {snip ~50 lines}

uc_add_item_redirect: "cart"
uc_cap_cart_form_enabled: 1
uc_cap_cart_form_weight: "0"
uc_cart_add_item_msg: 0

  {snip ~25 lines}

uc_currency_thou: ","
uc_customer_list_address: "billing"
uc_footer_message: "none"
uc_googleanalytics_version: "analytics.js"
uc_image_product: "uc_product_image"
uc_length_format_cm: "!value cm"

  {snip ~250 lines}

uc_weight_format_oz: "!value oz"
uc_weight_unit: "lb"
uc_affiliate2_path: "c"
```

There are 35 odd Ubercart modules on the site I yanked that from, about half are Enabled.  Someone’s suppose to know what module one of those is in to be able to change a value?  They’d need to at least learn how to use a grep like function before they could even start.

And that’s the issue right there.  And I’ll try to explain why not being able to just list all variables, with out knowing the internal structure of a module (all?), is an issue (and arguably for Backdrop as a whole a long term issue).

> People who benefit by config_:  10,000+- core contributors and module developers [1]
> People who are inconvenienced by config_ not acting exactly like vget:  1,000,000+- “regular users” [1]

I’m not arguing that having better data integrity isn’t a ‘good thing,’ but this seems to be completely at odds with the implied mission statement for Backdrop.  “Do not inconvenience ‘regular users’ like Drupal 8+ has.”

# # #

There’s going to be a mass migration away from D7 starting 6 months before it goes EOL because of the barriers (git, composer, lando, symfony, etc.) to using D8+.  The more barriers ‘regular users’ (mom&pops, small business people, home hobbyists) have to using Backdrop the more those users will NOT switch to Backdrop.

Why?  Because if they’re going to have to learn all that, then they’re going to use something like Joomla as it has a bigger environment.  If they don’t want to learn all that, then they’re obviously not going to use Backdrop, they’ll go to something like WordPress.

# # #

Yes there was only one variable ‘foo’ in D7, but the only people that created an issue to was the core/module developers.  For everyone else it was a benefit.  It was also a benefit that you (as a non-developer) did not have to know exactly it’s name, you could just get close and find what you needed.  ‘Cause `date_format_uc_store` is so well named everyone’s going to know that off the top of their heads ;O

# # #

I’ll close here, all of the above is ultimately related to this config_ issue, anything else I’d add now would be going completely off topic.

Best Regards,
Michael

[1] Numbers are referential.  Although I suspect 100 to 1 is probably low.

**Comment by jenlampton** [comment]
> Someone’s suppose to know what module one of those is in to be able to change a value? They’d need to at least learn how to use a grep like function before they could even start.

Well, yes. :) 

People shouldn't be changing any variables unless they know what that variable is for. Knowing what the variable is for also means knowing which module provided it, as well as the risks of changing something that's not intended to be changed in this way.

The variable system from Drupal 7 is still there in Backdrop. If you have a custom module, and would prefer that your own variables are installed in the variables table in the database rather than in configuration management, it's perfectly fine to use the old system.

> People who benefit by config_: 10,000+- core contributors and module developers [1]
> People who are inconvenienced by config_ not acting exactly like vget: 1,000,000+- “regular users” [1]

It's not only developers who benefit from config. There is a user-interface for importing and exporting configurations from one site to another, so using config benefits the non-coder site architect too. 

It's also better for people who are first learning web development, because the values are stored in easy-to-learn JSON syntax, and in easy-to-find files on the filesystem (instead of hidden in a database where learning MySQL is necessary).

It's also better for anyone who needs to make changes to a website after it's been launched, since it allows new features to be added without site downtime. There are content-freezes necessary for editors while databases are copied upstream. 

> ... this seems to be completely at odds with the implied mission statement for Backdrop. “Do not inconvenience ‘regular users’ like Drupal 8+ has.”

The audience you are after here -- developers who are trying to change variables using drush -- is not the audience of "Regular users" for Backdrop CMS. Drush may be a common tool for "regular users" of Drupal, but Backdrop is not a tool for developers -- it's a tool for people. There are a lot more people who benefit from configuration management, than developers who use drush. 

> And I’ll try to explain why not being able to just list all variables, with out knowing the internal structure of a module (all?), is an issue 

To be clear, it shouldn't be a problem to list all config values (including the files they are contained in) in one place, we just aren't doing it yet :)

It is also possible for drush to support changing config values in the same way it changed variables (maybe it already does?) so everything you are asking for here is within reach! It just wasn't a priority for Backdrop because we focus on the needs of the non-developer before the needs of the developer.

**Comment by Michael-IDA** [comment]
Hi Jen,

Sorry for the delayed reply, business before pleasure and all that.

I think I politely disagree with some of your definitions, so, if you’ll indulge my follow up questions?  And do understand these are my opinions (granted from 15 years of using Drupal, 40 years of being a programmer, and 20 years of having an MBA), but everything below is my opinion none the less...

> > ... this seems to be completely at odds with the implied mission statement for Backdrop. “Do not inconvenience ‘regular users’ like Drupal 8+ has.”
> 
> The audience you are after here -- developers who are trying to change variables using drush -- is not the audience of "Regular users" for Backdrop CMS. Drush may be a common tool for "regular users" of Drupal, but Backdrop is not a tool for developers -- it's a tool for people. There are a lot more people who benefit from configuration management, than developers who use drush.

I don’t seem to agree with your definition of "regular users of Drupal” being developers because they extensively relied on drush.  Drush is a tool that 90+% of Drupal clients I’ve ever had used.  The didn’t use it to develop anything they used it to do routine activities.

> People shouldn't be changing any variables unless they know what that variable is for. Knowing what the variable is for also means knowing which module provided it, as well as the risks of changing something that's not intended to be changed in this way.

In my opinion, what you wrote there is extremely short sighted, developer centric, and continuing in that mindset will long term hurt Backdrop.

vget and vset are the bread and butter of what people use in drush.  And they really did not know, did not need to know, nor could care less, what module the variable came from.  Having to know the module would literally be both an impediment to their workflow and a waste of their time.

Want to turn a site into maintenance mode?  Three simple commands _that they never had to actually remember_:

```
# drush vget main
default_nodes_main: "10"
googleanalytics_cross_domains: ""
googleanalytics_domain_mode: "0"
maintenance_mode: 0
maintenance_mode_message: "<p>This site is currently under maintenance.  :(</p>

<p>Maintenance started at: &nbsp;Sun Mar  5 16:21:31 CST 2017</p>

<p>We'll be back in an hour or so.</p>

<p>Thanks for your patience!,</p>

# drush vset maintenance_mode_message "<p>This site is currently under maintenance.  :(</p><p>Maintenance started at: &nbsp;Mon Oct 12 18:55:23 CDT 2020</p><p>We'll be back in an hour or so.</p><p>Thanks for your patience!,</p>"

# drush vset maintenance_mode 1
```

And here’s an example I grep’ed from a client’s .bash_history:

```
drush vset -y pathauto_node_pattern "content/[node:title]"
drush vset -y pathauto_blog_pattern "blogs/[user:name]"
drush vset -y pathauto_forum_pattern "[term:vocabulary]/[term:name]"
drush vset -y pathauto_user_pattern "users/[user:name]"
drush vset -y pathauto_taxonomy_term_pattern "[term:vocabulary]/[term:name]"
drush vset -y statistics_count_content_views 1
drush vset -y date_default_timezone "America/Chicago"
```

Why is he changing those?  I have no clue[1], I just do his hosting, but he had a reason and him having to dig through all the modules to be able to do what he could do in a half dozen simple commands isn’t going to endear him to Backdrop.

[1] I’d guess a new site based on the commands, especially default timezone.  Probably just dup’ed an existing site and started changing what needed changing.

> To be clear, it shouldn't be a problem to list all config values (including the files they are contained in) in one place, we just aren't doing it yet :)
> 
> It is also possible for drush to support changing config values in the same way it changed variables (maybe it already does?) so everything you are asking for here is within reach! It just wasn't a priority for Backdrop because we focus on the needs of the non-developer before the needs of the developer.

. . .

> we focus on the needs of the non-developer before the needs of the developer.

That statement is why I’ve been recommending my clients look at Backdrop as a replacement for Drupal as opposed to pointing them at either WordPress or Joomla.

The non-developer (regular user in my terminology) just wants to get things done.  If Backdrop throws up enough roadblocks and obstructs them then Backdrop (as the smallest ecosphere ) gets crossed off the migration list.

# # #

And now I am off topic of which config file has which config option, and if you want to move this resultant discussion to some other place to gather greater user (non-developer) input, just say where.

The only drush alternative that does not add roadblocks to using Backdrop from someone with D7 familiarity is Brush.  Brush does not have vset/vget capabilities.[2]  Whether the other two drush alternatives have the capability is a mute point, 90% of regular users / non-developers are going to walk from Backdrop if they’re forced to get their drush ‘fix’ from them.

Why?  They are non-developers.  Lando?  Composer?  It’s not in their lexicon.  Issuing a wget and unpacking a tarball?  Sure, they’ve been using that for years and it’s common commands.  Yet the Backdrop docs don’t have how to use a wget and unpack a tarball.  My opinion?  Backdrop is hurting itself by its docs not starting with wget/ftp / tarball/zip and _then_ showing alternative means of achieving the same.

Tracking back to the config option thing.  My recommendation is to add vget, vset, and every other Drupal 7 command back into Backdrop so that from the non-developer’s standpoint everything ‘just works’ like it did.

I’m not saying to remove config, state, or any other functionality Backdrop has adopted, just make the usage of any Backdrop functionality that is different from D7’s functionality both completely transparent and exactly like D7 to these people:

> we focus on the needs of the non-developer

So, I guess, now that I’ve talked myself through why this issue was such a sore tooth to me, would global policy change suggestions like the two above (docs/transparent functionality) be considered?  And if so, where should I make them? [3]

[2] Yes, I’ve signed up to fix the Brush code to provide that transparently, but that’s a maybe at this point while I poke around in the Backdrop world to see if it’s suitable to recommend to clients.
[3] Obviously here isn’t it ;)

# # #

While not closing the discussion, I’m again out of time, so I’ll stop with this so you understand I have investment in Backdrop’s survival or failure:

As I stated above, I have 15 years of Drupal knowledge.  I’d very much like to be able to continue using it, and I really wish I’d known about Backdrop when it was being originally forked.  But, ultimately, whether my clients switch to Backdrop isn’t my decision, but I’d sure like to help make it easy for them to choose Backdrop.

Best Regards,

Michael
Internet Design Alliance, owner
http://inet-design.com/
Hours (US CST):  Mon - Thur, 8am – 6pm | Fri, 8am - Noon
Emergency calls:  24x7

**Comment by alanmels** [comment]
While working with Backdrop sites, we started to frequently hit the subject matter of this issue. Therefore, we at AltaGrade have pushed some improvements to [Brush](https://github.com/backdrop-contrib/brush) and now you can quickly fire up the `brush cget` command to find where certain config option is. Here is the help output for the command:

```
docker@cli:/var/www/docroot$ brush help cget
Get a list of some or all site variables and values.

Examples:
+----------------------------------------+------------------------------------------------------------------+
| brush config-get                       | List all variables and values.                                   |
| brush config-get system.core           | List all variables in "system.core.json" file.                   |
| brush config-get system.core clean_url | Display value of "clean_url" key in "system.core.json" file.     |
| brush cget entity_type                 | List values of the "entity_type" key in all configuration files. |
| brush cget *entity*                    | List variables whose keys contain string "entity".               |
+----------------------------------------+------------------------------------------------------------------+


Arguments:
+-------------------------------+----------------------------------------------------+
| config-name                   | The config object name, for example "system.core". |
| key                           | The config key, for example "clean_url".           |
+-------------------------------+----------------------------------------------------+


Options:
+-------------------------------+------------------------------------------------------------------------+
| --pipe                        | Use var_export() to emit executable PHP. Useful for pasting into code. |
+-------------------------------+------------------------------------------------------------------------+


Aliases: cget, vget
docker@cli:/var/www/docroot$ 
```

**Comment by jenlampton** [comment]
> Want to turn a site into maintenance mode?

Backdrop has a UI for that: 
<img width="1296" alt="Screen Shot 2020-10-27 at 9 04 47 PM" src="https://user-images.githubusercontent.com/397895/97389594-ee2d3300-1897-11eb-8c2c-53fddf2ddfec.png">

There are a lot more people who will choose use the UI to change this setting than who are comfortable using the command line. These people are Backdrop's priority. 

For those who used `drush`, there are fantastic contrib solutions like `brush` that you can use for comparable functionality. Thank you @alanmels

**Comment by BWPanda** [comment]
I believe this question has been discussed and answered sufficiently, so I'll close this issue now.
