### ISSUE TITLE
Transliteration of taxonomy terms and their language

### ISSUE THREAD

**Issue by amilenkov** [backdrop/backdrop-issues#1995]
The correct transliteration of the title of the content in automatic URL alias depends on the language of the content. To perform a correct transliteration of a title of the Bulgarian language, for example, is necessary for that content type to be enabled Multilingual support and secondly the particular article to be defined as one of Bulgarian language.

In taxoniomy terms I can't do the same - to specify their language. That's probably why they are not transliterated properly in Bulgarian and I need to disable automatic URL alias and make them manually.

Is there a way to transliterate terms correctly, without having to specify their language or it is managed in a way that I don't know.

**Comment by klonos** [comment]
I think that this is yet another issue with core not being 100% multilingual. Unfortunately, I don't have a solution and our roadmap has this as a vague target for 2.0 😞 

When we start work on i18n, I intent to be very involved. This is as serious as making core accessible.

**Comment by amilenkov** [comment]
Many thanks for the information! It looks like I don't have to start sites that require extended multilingual support with Backdrop, but stay with Drupal 7 and wait future development of Backdrop.

I saw that there is started port of i18n, but at a very initial stage:
https://github.com/backdrop-contrib/i18n

I think embedding all the possibilities of the i18n in core will be an unnecessary complicating of core, not all sites need this. 

Simple, small multilingual sites with group of translated pages may be made with the existing tools of Backdrop at the present time easy and well. 

I would prefer a little and compact core and install extended multilingual support only for the sites that really need it.

I think it would be better if efforts to put i18n in the core be instead directed to the port of i18n as separate group of modules - the work will be done faster and easier.

The idea to include more and more popular modules in the core looks attractive, but would complicate it unnecessarily and making it harder for support and learning of new users.

**Comment by klonos** [comment]
I understand how you feel. Tradition has it tough that if something stays in contrib, it gets neglected over time or at least does not get as much attention as core.

There are workarounds currently to achieve certain things with core in D7 and in Backdrop, but they are far from "easy" and "well". You can look at #1690 for example.

Another thing to consider is plain marketing. D8 has multi-language support in its core. We need feature parity with that in order to have people seriously consider us an alternative to upgrade their D7 sites to.

So, I think i18n (or the majority of it) should be in core. Disabled by default, but in core ("not all sites need this" as you said).

**Comment by klonos** [comment]
PS: I now live in an English-speaking country and although Australia is a multi-cultural country, I have not had the need to build any multilingual websites yet. It seems that I will need i18n less and less, but I know how important it is as a feature and intent to allocate as much time and energy as I can afford to in order to get this right in Backdrop 2.0

**Comment by amilenkov** [comment]
> Another thing to consider is plain marketing. D8 has multi-language support in its core. 

This would be true provided Backdrop and D8 have the same market. I think that those who will choose Backdrop will make this not because it looks like a D8, but on the contrary because it's different. Because it is small, fast, compact, easy to learn and to work.

Otherwise, I have nothing against the i18n core. Personally I would be comfortable. Just consider this aspect also - which is more important - to have everything in the core or to have a simple and easy to build, study and support system.

I know that I can use the D8. It has a good multilingual support. I installed it, I worked a bit with it. I don't like it. Because it is a huge, heavy. I don't use Drush and work with FTP. Uploading D8 takes me three times longer than the D7. Maintenance of sites, updates, backups takes much more time.

And I see a trend.
I started to work with Backdrop version 1.2.1:
27.5 MB, 1883 files (unzipped on my computer)
Yesterday I installed version 1.4.3:
28 MB, 2155 files

It's not that bad yet, compared to D8 - < 50MB, < 13000 files, but if it continues without the limit Backdrop would lose important competitive advantage. On the market it is important not to be similar to competitors, especially when competitors are big and strong, but to be different  and to have your market niche where they are weak.

**Comment by klonos** [comment]
Well, the complexity in D8 is far from just the size of it and the number of the files. The adoption of Symphony and the OOP rewrite is what makes it hard(er) to work with it. Files and subsystems are easy to ignore if not needed, but when the entire system is written in a way that one is not familiar with, then that is a totally different thing.

Besides, when features are required for the functionality of a website, the respective contrib projects that provide them will be eventually added and although these files will not reside under `/core`, they are still added to the total of the codebase that a developer needs to become familiar with. It is tricky to find the balance between adding features that the majority of users needs and still keeping the modules merged into core to a minimum. I will not compare the only ~20% usage of i18n to the ~95% of views and the ~85% of token for example or the ~50% of date, but it is still one of the top 40 most popular modules. In fact, Redirect (in core since 1.4.0), References (planned for inclusion in 1.5.0), Email Field (in core since 1.2.0) all are examples of projects with lower usage stats than i18n.

Now, although our target audience is small to medium sized businesses and non-profits, we never said that Backdrop cannot be used by larger organizations or even the enterprise. Independently to that, in order to make a choice, people will look at features first and system requirements next. If we do not have feature parity with D8 (as well as Wordpress), then we loose the game at stage 1. When it comes to stage 2 (system requirements), I doubt that storage space is an issue nowadays even on the cheapest of hosts and the number of files do not add any load to the server AFAIK. I give you added complexity, but that is well-balanced by the features added. So, there is a gain for end users (contrary to the increase of complexity after the rewrite in D8, that is mainly in order to benefit coders).

**Comment by amilenkov** [comment]
Thank's klonos!

One reason to like Backdrop is that it is developed of so responsive, devoted and loving their work people like you.

I understand perfectly your point of view. But let me tell you briefly about my point of view - because I guess people like me will be significant part of the your users.

I'm not a programmer. 

I am a private entrepreneur with my own very small business. I am graphic designer and prepress specialist from more than 20 years and besides sites I do prepress and desktop publishing work for printed advertisement materials. 

I am also photographer and copywriter, marketing consultant and business adviser for my clients - mostly micro and small businesses in Bulgaria. I have over 500 regular customers from number of years and for part of them I've done also  websites.

I know well the basics of HTML and CSS and have very basic knowledge in PHP. 

Before I started with Drupal few years I did simple HTML static sites and some websites with WordPress, Joomla and e107 cms. 

Work with Drupal since version 5. I know well the system - in the sense that I understand all the options and I can manage them as an administrator. I have worked with and I know well over 150-200 contrib modules.  If I had enough time I could have written a book on Bulgarian language for using Drupal / Backdrop.

There is a Bulgarian forum for Drupal and I am active member and often give advice to beginners.

I cannot develop modules. I have learned, however to develop themes and all my sites are with made by me individual themes and designs. I have learned to make themes for Backdrop too and even developed my own Backdrop layouts because I prefer to work with the HTML structure and CSS styles in my way of working - as simple as possible. 

So far I have developed over 100 sites with Drupal, from which now are active and I support more than 60.

In this situation, for me, it's totally irrelevant that D8 has been developed with the Symphony and OOP. I can't and will not program with them. They are not the reason for me to choose Backdrop.

Backdrop or Drupal are tools for me to develop website as I use Adobe Illustrator for vector graphics processing, Photoshop for working with photos and InDesign to design books and magazines. I don't know what kind of programming language is written in Illustrator, but I know how to use it to develop logos.

Big part of my work on websites does not consist in the development of new sites, but in the maintenance of existing ones.

People beg me to upload new content, make changes, to do search engine optimization. Regularly updating all those over 60 site when new versions of modules and the core. After any change, after each update I do backup. I have installed Backup and migrate module in all sites, but always do second, manual backup of the database and files in the site.

And finally copy backup files in 3 different places - one - remote backup server of my hosting provider. 

Yow are right - number of files do not add any load to the server. But if you do backups several times daily and carefully save them in three different locations - bigger file size means more time for transfer. And as we know, time is money:-)

Drupal 8 interferes with my job that's too big and heavy and increases my working time on installation and maintenance of the sites. File size is part of it. That's why I prefer Backdrop as more compact and lightweight.

The second very important reason is that I cannot explain to my clients why their sites must be made anew with D8 after they have already been made and they have paid me for the design and development.

That's why I'd love to have multilingual support but it doesn't matter to me whether it would be in the core or separate module.

You developers know better than me how to develop the system. 

As a user I have only one appeal - keep it simple, compact and easy to work with. Let it be evolutionary development saving work already done from developers of modules and creators of websites. Not through revolutions, deleting the work already done.

I understand that developers need to program and invent new things, otherwise their work is devalued. Revolutions prove their professional development and success.

I think Backdrop can be successful only if it is understood that this is not just software, but above all social community connecting developers and users.

In this respect there is much to be done. 

I see a well-established cooperation network of developers in Github. 

However, Github is difficult for use by people who are not programmers and you will hardly find, for example, their opinion as to whether they want i18n in the core or separate module.

In my opinion Backdrop needs social network in it's own website, forum, groups, a place where non-programmers can ask questions, ask for help and express their opinions.

This will relieve the developers because more experienced users (may be like me) could answer questions of beginners. For example how to use or configure specific feature.

You could organize online polls about what development path users prefer and do what's best for the community, not in the opinion of the narrow circle of developers.

I can imagine also a system there in which users can carry out online donations for the development of the modules required by them.

In such a scenario likely you would have taken the right decision whether i18n to be in the core or a separate module.

**Comment by klonos** [comment]
>You developers know better than me how to develop the system. 

I'm far from a developer. I only do minor code reviews and fixes that are mostly search and replace. I would not actually call that coding. In the PMC, I represent the non-coding site builders like you and me.

>However, Github is difficult for use by people who are not programmers and you will hardly find, for example, their opinion as to whether they want i18n in the core or separate module.

That's totally true. That's why both in d.org as well as in Backdrop, I think that we should establish usage metrics. These will help us understand what most people use without them even having to register and say something. The numbers will talk 😉 

>In my opinion Backdrop needs social network in it's own website, forum, groups, a place where non-programmers can ask questions, ask for help and express their opinions.

That's underway: https://github.com/backdrop-ops/backdropcms.org/issues/250

...it's just that there's so much to be done and only a handful of us, so things might be taking a bit longer than ideal, but we're slowly getting there. Perhaps things will start moving faster as the community grows and we get more hands on deck.

> You could organize online polls about what development path users prefer and do what's best for the community, not in the opinion of the narrow circle of developers.

True that. I have already filed a couple of issues for that too: https://github.com/backdrop-ops/backdropcms.org/issues/246 https://github.com/backdrop-ops/backdropcms.org/issues/211

Voting would be a very valuable tool in catching the "pulse" of the community.

**Comment by Gormartsen** [comment]
@amilenkov hi! I added proposition to remove tests files from repository.
It should save time in your case of backdrop usage.
