### ISSUE TITLE
Text Editor. Insert Image does not work

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#2002]
BD 1.4.3

![rtgrt](https://cloud.githubusercontent.com/assets/13515302/16570171/3f9faa76-4249-11e6-865b-5c7aabad03a3.png)

**Comment by klonos** [comment]
I tried both adding and editing an already inserted image. They both worked fine for me. I also tried doing both these tasks in maintenance mode since I see that in your screenshot. Again, both adding as well as editing an image worked fine for me.

I would a) try to [start Chrome in "safe mode"](https://superuser.com/questions/822429/how-to-start-chrome-without-plugins) so that no extensions are running and b) disable any Backdrop contrib modules you might have installed.
