### ISSUE TITLE
[UX] post number in frontpage not working

### ISSUE THREAD

**Issue by gembes** [backdrop/backdrop-issues#2021]
admin/config/system/site-information, "Number of posts on front page" not affect to frontpage, still and always 10.

**Comment by klonos** [comment]
Hello @gembes ...there isn't any setting in `/admin/config/system/site-information` for the number of content shown as far as I know. You must most likely have enabled the "Front page" view under `/admin/structure/views`. All views have a "Pager" setting with which you can limit the amount of content shown. So this settings is also available in the "Front page" view, which is most likely what you have set. Right?

If so, then I know what your issue is: the front page setting under `/admin/config/system/site-information` is still set to the default of `node` (so the non-configurable list of content is still shown). What you need to do is to change that to `frontpage` (the default path of the "Front page" view). That will effectively set the "Front page" view as your front page, replacing the `node` list.

Try that and let us know if it works for you.

**Comment by gembes** [comment]
hello @klonos ,
its default. i dont touch any views, here my secreenshot
![setting_003](https://cloud.githubusercontent.com/assets/20469101/16868136/340f051c-4aa0-11e6-8a55-0c88349089a4.png)
![views_004](https://cloud.githubusercontent.com/assets/20469101/16868140/39f374b8-4aa0-11e6-955d-b24dc6f9774e.png)

set to 3 post but in frontpage, still 10.
but when i change manually  in files/config_xxxxx/active/system.core.json frontpage become 3 post.

**Comment by gembes** [comment]
adding this line before ->save();
`->set('default_nodes_main', $form_state['values']['default_nodes_main'])`
complete code
`  config('system.core')
    ->set('site_name', $form_state['values']['site_name'])
    ->set('site_logo_theme', $form_state['values']['site_logo_theme'])
    ->set('site_logo_path', $form_state['values']['site_logo_path'])
    ->set('site_favicon_theme', $form_state['values']['site_favicon_theme'])
    ->set('site_favicon_path', $form_state['values']['site_favicon_path'])
    ->set('site_favicon_mimetype', $form_state['values']['site_favicon_mimetype'])
    ->set('site_mail', $form_state['values']['site_mail'])
    ->set('site_slogan', $form_state['values']['site_slogan'])
    ->set('site_frontpage', $form_state['values']['site_frontpage'])
    ->set('site_403', $form_state['values']['site_403'])
    ->set('site_404', $form_state['values']['site_404'])
    ->set('default_nodes_main', $form_state['values']['default_nodes_main'])
    ->save();`

**Comment by gembes** [comment]
@klonos , please add that line to core..
thank

**Comment by serundeputy** [comment]
Thanks @gembes !
Good find; great bug report very detailed!

`PR`: https://github.com/backdrop/backdrop/pull/1464
I've added the suggested code to save the config for `default_nodes_main` and added a test to make sure it is saved and works as expected.

test site:
Website: http://1464.backdrop.backdrop.qa.backdropcms.org
Username: admin
Password: zzX3q6h4

**Comment by klonos** [comment]
@gembes sorry about that. I always replace the front page with a view and it's been long since I used that setting that I forgot it existed.

@serundeputy you beat me to it once again 😉 Thanx.

**Comment by klonos** [comment]
...and the code looks good (also the logic of the test added) and it now seems to work as expected. Setting to RTBC.

**Comment by quicksketch** [comment]
Great fix @serundeputy! Thanks for reporting @gembes. :+1: 

Merged for 1.4.4.

We might also consider some kind of combining of this setting with the Views setting. Perhaps as part of #1042.
