### ISSUE TITLE
Custom Layout issue. "Main page content"  block is not available.

### ISSUE THREAD

**Issue by Gormartsen** [backdrop/backdrop-issues#2057]
How to reproduce:
- Create custom layout
- set path to randomstring
- save

As a result:
The content region does not have "Main page content block".
"Add block" does not see "Main page content block" either.

I have a custom module that return content on "randomstring" and I had to manually add default block to layout.json file.

Similar issue if path is equal "admin". 
"Main page content block"  exists but when you try to edit it, there is errors:

```
Notice: Undefined offset: 1 in layout_block_add_page() (line 941 of core/modules/layout/layout.admin.inc).
Warning: Invalid argument supplied for foreach() in element_children() (line 7012 of core/includes/common.inc).
Warning: Cannot use a scalar value as an array in backdrop_render() (line 6397 of core/includes/common.inc).
Warning: Cannot use a scalar value as an array in backdrop_render() (line 6450 of core/includes/common.inc).
```

**Comment by jenlampton** [comment]
The main page content block is only available if you are on a page with context (node/% or user/% or taxonomy/term/%).

If your custom module generates a page at path /custom/% then Backdrop should recognize that context and give you a main page content block. I'm not sure offhand how contexts are defined to the system, but maybe check node term or user modules for examples?

**Comment by quicksketch** [comment]
> The main page content block is only available if you are on a page with context (node/% or user/% or taxonomy/term/%).

The main page content block is available if you are on *any page that is an existing system path* (e.g. a path like `node` or `admin` would work as well), it doesn't have to have a wildcard in it. This property of "overridding existing path" is itself a context, upon which the main page content block depends.

So overall though, this is all as-expected. A custom created path at which nothing else exists won't have a main page content block, because nothing would be in it. A path like this actually results in the Layout module itself providing the menu callback, so if it were possible to place the main page content block inside, it would result in recursive embedding of a layout within a layout (within a layout, etc.)
