### ISSUE TITLE
[UX] Add the ckeditor spell-check plugin

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2071]
I got a request today to add "All the buttons" from CKEditor back into backdrop. When I followed up asking what in particular was missing, one answer I got was the Spell-Check button.  I had personally thought this wasn't necessary anymore since browsers and OSes now do spell-check, but let's take a poll. Did anyone use the spell-check feature in Drupal (or in WordPress) and should we include it in Backdrop?  Should it be enabled in the editor out-of-the-box?

Existing CKEditor plugins
---

- https://ckeditor.com/cke4/addon/scayt and https://ckeditor.com/cke4/addon/wsc both use a [3rd party service](http://webspellchecker.net/) - so it is a no-no for core.

- https://ckeditor.com/cke4/addon/nanospell also [3rd-party](http://ckeditor-spellcheck.nanospell.com/#try) - also no-no

- https://ckeditor.com/cke4/addon/foundeospellchecker

    > All spell checking is done on your server without sending content to a third party for checking.

- https://ckeditor.com/cke4/addon/jqueryspellchecker

**Comment by Graham-72** [comment]
I personally do not use the spell check in CKeditor. But perhaps one day a client might want or expect this feature? I would not need it enabled out-of-the-box but would prefer it to be there as an option.

**Comment by robertfabian** [comment]
I'm the (relatively) naive user who raised questions about CKeditor. My concern is with the out-of-the-box experience. Many potential users will have experience using CKeditor in other contexts, e.g. in Drupal 7. The Full CKeditor configuration provides a raft of buttons (not all of which work, but they're present). The impression is that the version of CKeditor installed in Backdrop is somehow limited. After investigation, I did find two real limitations - anchor refuses to stay in the row of action buttons and there is no (obvious) way to link to a file that has been uploaded using CKeditor (through use of IMCE or CKfinder). Spell checking is a nice to have feature that would flesh out the CKeditor buttons available under Backdrop (even if it's not really necessary on most desktops). Disclaimer: I've dabbled with the web since the TCP/IP network was opened to the public in '94. But working on the web has never been a major focus, certainly not back when I was an active consultant.

**Comment by quicksketch** [comment]
Using the browser-based one is much better in my opinion. The built-in checker will use the browser's native language and custom dictionaries, as opposed to making site-specific dictionaries.

**Comment by quicksketch** [comment]
There is a PR for the browser-based approach at https://github.com/backdrop/backdrop-issues/issues/2386, which is a one-liner fix.

**Comment by jenlampton** [comment]
yep, let's do that first :)

**Comment by Gormartsen** [comment]
I use http://grammarly.com/ plugin.

**Comment by jenlampton** [comment]
I'm going to postpone this issue since after allowing browser spellcheck to work, we haven't gotten any more requests for a spell checker.

**Comment by quicksketch** [comment]
I think this issue can be closed. We fixed this with the browser spellcheck in CKEditor 4 and the browser spellcheck works in CKEditor 5 as well: that editor never hijacks the right click so it's always available, even when tables are used.
