### ISSUE TITLE
[UX] Remove the 'default' tag from all views

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2074]
This should be an easy one.

**Comment by BWPanda** [comment]
I was just about to post about this. I can see the benefit or having this tag for views provided by Backdrop core (so you know what was provided initially and what was added after the fact), but why custom views have this tag added by default is beyond me...

+1 for removing the 'default' tag from custom views.

**Comment by klonos** [comment]
Now with views in core and also with admin_views in core, I think that it would make sense to be adding the tag "core" for the views provided by core, "custom" for all views manually added by the user and perhaps "%module name%" for all views regardless core/custom. If not tags, then these could be a "provided-by" property that we append to the description. We are currently adding "Default (module-provided)" to every view AFAICT and that is not very useful.

As it is now, these tags would have no value, but if we added an instant search filter at the top of the views list (#503), then it would be very useful, because as you must have also experienced yourselves, most sites end up with a few dozens of views.

Anyways, I have previously filed #1897 in which I mention this issue here too. If we consider that a meta-issue, then this one could be considered one of its child-issues 😉 ...otherwise duplicate.

**Comment by BWPanda** [comment]
Here's a PR that removes the 'default' tags from views in core, removes the addition of the 'default' tag for newly-created views using the wizard, and prevents display of tags in the views overview when empty: https://github.com/backdrop/backdrop/pull/3364

**Comment by stpaultim** [comment]
For those like me, that are aware of tags for views but never use them, a user can add a custom tag to a view with the "Change name/description" option on the view page. 

![Administer_content__Content____PR_3364_backdrop_backdrop_testing_site_](https://user-images.githubusercontent.com/3144571/95688734-ed2aaf00-0bd1-11eb-8f80-0d4900db0477.png)

They show up here:

![Views___PR_3364_backdrop_backdrop_testing_site_](https://user-images.githubusercontent.com/3144571/95688778-40046680-0bd2-11eb-9934-9e908c51a5a4.png)

I think that this PR makes sense. It works for me. I like the idea of putting a "core" tag for all views provided by core. But, that could be a followup issue.

**Comment by bugfolder** [comment]
Code reviewed, LGTM.

**Comment by quicksketch** [comment]
There are a lot of other good suggestions here, but I think just getting `default` removed from the out-of-box views and new ones that are created is a good start. Thanks @BWPanda for the PR and @bugfolder for reviewing it! I merged https://github.com/backdrop/backdrop/pull/3364 into 1.x and 1.26.x.

**Comment by klonos** [comment]
Sorry to reopen this, but we missed a spot. The PR was not rebased, and in the meantime, we also added the "Promoted cards" view into core, and that one still has the `default` tag. PR coming up shortly...

**Comment by klonos** [comment]
...here: https://github.com/backdrop/backdrop/pull/4541

**Comment by quicksketch** [comment]
Nice one, thanks @klonos! I merged the follow-up at https://github.com/backdrop/backdrop/pull/4541 into 1.x and 1.26.x.
