### ISSUE TITLE
Tableselect.js "select all" should only select column checkboxes in a tabeselect table

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#2085]
See https://github.com/backdrop/backdrop-issues/issues/2077#issuecomment-241290475

If you create a table using `theme_tableselect` and one of your table columns renders a custom form checkbox element, the "Select all" checkbox applies its behaviour to **all** checkboxes including your checkbox elements. 
See example after clicking the checkbox in the header upper left:

![tableselect checkboxes](https://cloud.githubusercontent.com/assets/1042283/17840834/3e437b8e-67de-11e6-8613-d2490736b50a.PNG)
It should only apply to the row selection checkboxes in the very first column.

---

~PR by @docwilmot: https://github.com/backdrop/backdrop/pull/1761~
PR by @quicksketch: https://github.com/backdrop/backdrop/pull/2176

**Comment by quicksketch** [comment]
Ha! I have not seen this before.

So to make this a little more robust, would you also run into situations (even after this fix) if you had *multiple* columns that had a select-all checkbox? With the current PR, we add a class for `row-select`, but if multiple columns had this behavior, you'd end up with the same problem. I don't think we have any interfaces like this, but it might be possible on something like the User Permissions page if a select all checkbox were added at the top of each role.

If a class is being used explicitly for JS behaviors, we should use a data-attribute instead. That might help the multiple checkbox situation where a data attribute could be used to map together the select all checkbox and the children checkboxes. e.g. `data-select-checkbox="1"` `data-select-checkbox="2"` (for two rows of columns of checkboxes).

This class/data-attribute would be better to be modified in `form_process_tableselect()` rather than `theme_tableselect()` so that it would not affect the (unlikely but possible) situation that the theme function had been overridden.

**Comment by docwilmot** [comment]
Looking at this again. 
> would you also run into situations (even after this fix) if you had multiple columns that had a select-all checkbox

I dont think this is possible with `theme_tableselect`. I dont see anywhere in the code which allows for multiple "select all" checkboxes in the header. This could I suppose be done using custom javascript, but then I imagine the developer should be responsible for generating the code to select those checkboxes. In the interest of @jenlampton, I think adding code in core to accommodate this would certainly not satisfy the 80% directive.

**Comment by quicksketch** [comment]
I tested out the PR but it broke some other functionality tableselect.js is suppose to provide:

- Highlighting checked rows.
- The ability to click one box, hold shift, then click on a second box. Which should select all the boxes in between the two that were checked.

As this functionality applies to all the checkboxes in the column (not just the select all checkbox), it looks like we may need to add the data-* attribute to all the checkboxes, not just the first one. Either that or do something based on counting the column number.

**Comment by docwilmot** [comment]
I suspect you may have tested a Views-generated table. Above works fine for non-Views tables.
Adding `'#attributes' => array('data-first-col-select' => array('first-col-select')),` to the checkboxes fields in `views_form()` fixes this.

**Comment by jenlampton** [comment]
Can someone add steps required to test to this issue? I'd like to test it but I'm not sure how. Are we supposed to test both a system table and a views table?

**Comment by quicksketch** [comment]
Hey @docwilmot, thanks for the updated PR. I was indeed checking a Views table. I think you're right that worrying about the multiple columns of checkboxes is unnecessary at this point.

My last concern is purely around namespacing. As this is in tableselect.js, I feel that the data attribute should match. I filed a PR at https://github.com/backdrop/backdrop/pull/2176 that updates the same places as your PR, but uses `data-tableselect-id` instead. In theory we could add support for multiple columns later and the markup would not need to change from what it is now. I also switched tableselect.js's `.click()` handlers to the more efficient `.on()`, so we only have one binding for the whole table instead of one per checkbox.

**Comment by quicksketch** [comment]
To test:

- Visit a Views-based page like /admin/content and ensure that the select all checkbox works. Also check that clicking one checkbox, holding shift, then clicking a second checkbox selects all rows in between.
- Visit a non-Views page like /admin/content/comment and ensure tableselect.js works there in the same way.

We don't have a core use-case to test the situation described in the summary, so we're only checking for regressions here.

**Comment by olafgrabienski** [comment]
> - Visit a Views-based page ...
> - Visit a non-Views page ...

Tested in the sandbox on `admin/content` and `admin/content/comment`, works good on both!

**Comment by quicksketch** [comment]
Thanks @olafgrabienski! Merged https://github.com/backdrop/backdrop/pull/2176 into 1.x and 1.9.x.
