### ISSUE TITLE
Disable user pictures by default.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2090]
If our long term plan is to switch to fields on users instead of using the old legacy user-pictures that are on the account settings page, shouldn't we disable user pictures by default on new installs? 

---
PR by @BWPanda: https://github.com/backdrop/backdrop/pull/3369

**Comment by BWPanda** [comment]
Untested [PR](https://github.com/backdrop/backdrop/pull/2730) but should work.

**Comment by klonos** [comment]
Tried to test on the PR sandbox, but it is currently throwing the installer at me.

**Comment by jenlampton** [comment]
Tried to get you a new sandbox: https://github.com/backdrop/backdrop/pull/2730
If this doesn't work we may need a rebase on the PR.

**Comment by klonos** [comment]
...still getting the installer 😞

**Comment by BWPanda** [comment]
Couldn't get old PR working, so made a new one: https://github.com/backdrop/backdrop/pull/3369

**Comment by indigoxela** [comment]
I think it's a good idea to disable user_picture by default.

The PR doesn't work yet, though (verified in the sandbox).

The problem is that the standard profile enables that setting in [its hook_install](https://github.com/backdrop/backdrop/blob/5aba056ecbcaa20db3292fc70c0556fa1a178044/core/profiles/standard/standard.install#L174).

**Comment by BWPanda** [comment]
Ha, well that's what I get for doing stuff late at night 😊 Will fix soon.

**Comment by BWPanda** [comment]
Ok, PR updated. Please try again @indigoxela.

**Comment by indigoxela** [comment]
Works like a charm now.

And the code looks good, RTBC.

Someone else should set the milestone.

**Comment by BWPanda** [comment]
Can I get an ok from @jenlampton or @klonos? If so then I'll merge this.

**Comment by quicksketch** [comment]
I agree this seems like a good idea for most sites because we usually only have a small number of administrators (or frequently only one account). User pictures are primarily for the less-common community sites, and even then you might use a field instead of the built into "picture" support.

Merged https://github.com/backdrop/backdrop/pull/3369 into 1.x for 1.18. Thanks!

**Comment by jenlampton** [comment]
> Can I get an ok from @jenlampton or @klonos? If so then I'll merge this.

Ooops...  Ok from me! :) Thanks @BWPanda and @quicksketch

**Comment by klonos** [comment]
Are user pictures a Backdrop-only thing? ...if not, then how do we handle upgrades from D7 that were using user pictures?

**Comment by jenlampton** [comment]
This only disables them on new sites... they are still there :)
