### ISSUE TITLE
[UX] Move settings for Administrator role and Anonymous users to Roles page

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2091]
We have a config page where people manage roles. Let's put all the settings relating to user roles in the same place.

**Comment by quicksketch** [comment]
Great idea. PR at https://github.com/backdrop/backdrop/issues/1497 needs some work and almost certainly will need to update existing tests. We can push this into 1.5.0 if it is ready before release time.

**Comment by quicksketch** [comment]
I like this idea. Here's a screenshot of the new roles page in action. The fieldsets are collapsed by default, I've expanded them for illustration purposes. Code-wise, this looks ready. But I'd like to hear others' feedback on how they feel about the move and the positioning of these settings on the roles page.

![selection_166](https://cloud.githubusercontent.com/assets/100206/18021111/08dc1d24-6b9a-11e6-98cf-6fa87d87fd1a.png)

I had considered perhaps we could move these settings to the individual roles (e.g. the "Anonymous name" could be in the Anonymous role configuration), but that wouldn't work for the Administrative role which can be on any role. I suppose it could be changed to a checkbox for "Make this the administrative role", but I find that confusing when affecting *other* roles by checking an option on one role. So anyway... I don't think my alternative is better than this implementation.

**Comment by klonos** [comment]
@quicksketch what you said above pretty much covers my thoughts about the change. Less pogo-sticking throughout the UI = UX+, so 👍 from me.

...thoughts for improvement:

1. The "Administrator role" drop-down menu AFAICT offers as options any role besides the *Anonymous* + a special "disabled" option.
  a) initial thought is that I am scared to select "disabled" as admin role because I'm afraid that it will actually do what it suggests... disable the admin role. What we actually mean here though is to disable the feature to auto-assign all permissions.
  b) why only allow one role to have this feature?

  > ...but I find that confusing when affecting other roles by checking an option on one role.

  Instead of having that be an entirely section of its own (separate fieldset), we could have it as an additional column with checkboxes right in the list of roles (the anonymous role will not have a checkbox available). Help text below (or above) the list would explain what happens when you select that checkbox. Here's what it could look like:

![backdrop-issue2091-mockup-assign_all_permissions_column](https://cloud.githubusercontent.com/assets/2423362/18127273/ad7c936e-6fc2-11e6-89df-158cf4f87681.png)

2. As you can see from the mockup above, I have changed the label of the anonymous role to "Guest". So, why do we need that separate fieldset again?

**Comment by olafgrabienski** [comment]
> What we actually mean here though is to disable the feature to auto-assign all permissions.
> b) why only allow one role to have this feature?

The mockup suggests the option to _enable_ the auto-assign feature for multiple roles. In my opinion it should allow the feature for only _one_ role (including to change it to another role). Allowing multiple roles here seems too suggestive to me, or even dangerous. Besides, what use case do you have in mind?

**Comment by jenlampton** [comment]
Can we create follow-up issues for some of these ideas? This issue is to
put all the role settings on the role page.

**Comment by klonos** [comment]
@olafgrabienski, yes, I did have a specific use case in mind where 2 roles are required to have this feature, but it would be a rare case and besides a) I can simply assign the admin role to users that require this (it just won't make sense "semantically", but that's mostly OK) and b) you are right that having the ability to set *ALL* roles to be assigned full rights can be potentially dangerous. Depriving that ability from the anonymous/guest role mitigates that risk, but still I understand what you are saying. Perhaps if this column had a "Full permissions" label and the checkboxes were radio buttons instead?

> Can we create follow-up issues for some of these ideas? This issue is to put all the role settings on the role page.

Yes, the whole idea of having any role-related settings be in that page will be a UX win, so let's do that as a first step. Lets also make sure that any future related setting are placed there as well. The reason why I posted my ideas here instead of separate, new issue(s) was in order to achieve UI simplification/decluttering:

1. We should move the ability to define a custom name for anonymous users in that page, but people can already achieve that goal by simply editing the label of the in-built *Anonymous* role. Right? So, how about we remove this fieldset entirely?

2. The "pick admin role" drop-down shows a list of all roles to pick from (minus anonymous). We already have that list at the top of the page, so why not (re)use that UI instead of having a separate, dedicated fieldset?

...anyways, please go ahead with the initially proposed change and lets iterate if people agree with the rest of the suggestions.

**Comment by jenlampton** [comment]
> Can we create follow-up issues for some of these ideas?

Fine, I'll do it. The idea was to keep this issue on track so that we can get it reviewed and closed without talking about other things. In drupal we used to block improvements on things that might have been better improvements and then nothing ever gets done. I'm hoping to make iteratins much smaller (and faster) with Backdrop.

**Comment by quicksketch** [comment]
I've merged https://github.com/backdrop/backdrop/pull/1497 for 1.5.0. Thanks everyone for the feedback. @jenlampton opened a follow-up issue at https://github.com/backdrop/backdrop-issues/issues/2112 where we can discuss alternatives further if needed.

**Comment by jenlampton** [comment]
*highfives*
