### ISSUE TITLE
Canceling the deletion of a role redirects to the "Manage user accounts" page instead of back to "Roles" page.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2109]
Found this while testing https://github.com/backdrop/backdrop-issues/issues/2108

PR coming up...

**Comment by klonos** [comment]
Random php7 failure. Closed and reopened PR to run the tests again and all came green the second time.

**Comment by serundeputy** [comment]
@klonos since this is a change in functionality it needs a test.  I've added a test and filed a `PR` against your branch.  I'm not sure I've done that correctly, but when you get a chance if that looks good to you merge it to your branch and push back up again that should update this `PR`.

thanks,
~Geoff

**Comment by klonos** [comment]
@serundeputy thanx for the test addition. I've merged your test in my PR and closed yours. Waiting for the tests to run and we should be back to business 😉

**Comment by klonos** [comment]
Tests are all green. Back to NR then.

**Comment by quicksketch** [comment]
Great job! Merged https://github.com/backdrop/backdrop/pull/1505 into 1.x and 1.4.x. :+1:
