### ISSUE TITLE
Allow more than one role to be the "Administrator role"

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2112]
Follow-up to https://github.com/backdrop/backdrop-issues/issues/2091#issuecomment-243737629 from @klonos 

The "pick admin role" drop-down shows a list of all roles to pick from (minus anonymous). We already have that list at the top of the page, so why not (re)use that UI instead of having a separate, dedicated fieldset?

Instead of having that be an entire section of its own (separate fieldset), we could have it as an additional column with checkboxes right in the list of roles (the anonymous role will not have a checkbox available). Help text below (or above) the list would explain what happens when you select that checkbox. Here's what it could look like:

![backdrop-issue2091-mockup-assign_all_permissions_column](https://cloud.githubusercontent.com/assets/2423362/18127273/ad7c936e-6fc2-11e6-89df-158cf4f87681.png)

**Comment by jenlampton** [comment]
I'm personally against this idea since it's a minority use case. It seems like something that could easily be implemented in contrib.

**Comment by jenlampton** [comment]
Comment from olafgrabienski originally posted on https://github.com/backdrop/backdrop-issues/issues/2091#issuecomment-243737629

> b) why only allow one role to have this feature?

The mockup suggests the option to _enable_ the auto-assign feature for multiple roles. In my opinion it should allow the feature for only _one_ role (including to change it to another role). Allowing multiple roles here seems too suggestive to me, or even dangerous. Besides, what use case do you have in mind?

**Comment by jenlampton** [comment]
comment from @klonos originally posted on https://github.com/backdrop/backdrop-issues/issues/2091

@olafgrabienski, yes, I did have a specific use case in mind where 2 roles are required to have this feature, but it would be a rare case and besides a) I can simply assign the admin role to users that require this (it just won't make sense "semantically", but that's mostly OK) and b) you are right that having the ability to set ALL roles to be assigned full rights can be potentially dangerous. Depriving that ability from the anonymous/guest role mitigates that risk, but still I understand what you are saying. Perhaps if this column had a "Full permissions" label and the checkboxes were radio buttons instead?

**Comment by jenlampton** [comment]
The reason why I posted my ideas here instead of separate, new issue(s) was in order to achieve UI simplification/decluttering:

**Comment by quicksketch** [comment]
@jenlampton Did you delete those original comments from #2091? I can't find them there any more.

Anyway, from the discussion that has happened thus far and repeated again here as "crossposts", I also think that the ability to assign multiple admin roles or to even give the admin role option that level of emphasis is unneeded.

**Comment by jenlampton** [comment]
> Did you delete those original comments from #2091?

@quicksketch yes, I moved them here - along with screenshots!

**Comment by Dinornis** [comment]
An example of where this would be useful? I could not think of a situation where I would use this feature.

The ability of assigning multiple roles to a single user already provides a very easy permissions management.

**Comment by jlfranklin** [comment]
I can see times when a hierarchy of roles or meta-roles that grant a set of other roles _might_ be useful.  

Think of a site that hosts multiple events and each time an event is added, a role is added.  Event coordinators need to have all roles of all events, but you don't want to go back to each event coordinator and add on a new role to their profile every time you have an event, so a top-level role of "event coordinator" mapping to all event roles is given to such users.  When a new event role is added to the event coordinator role, all of the event coordinator users get the new permissions of the new event role.

That's not a great example, because a) the event coordinators are not "all permissions" roles, b) there are almost certainly better ways to do that with taxonomy fields in the user profiles, organic groups membership, or granting "event coordinator" some blanket "edit all nodes" permissions, and c) it would be better to do in contrib.

**Comment by jenlampton** [comment]
I still think this is an edge case, and something that can/should only be supported by contrib.

**Comment by klonos** [comment]
I agree with closing this issue as not being a core-worthy feature (yet) or an edge case at the very least. IIRC, when I was making these suggestions, I think I had https://github.com/backdrop/backdrop-issues/issues/1285#issuecomment-152736114 in mind.
