### ISSUE TITLE
should config exports indent 2 spaces?

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2115]
When I export a view using the config UI and want to add it to backdrop, I spend a lot of time decreasing the indentation since the UI exports with 4 spaces and our coding standards dictate only 2. Should we update the UI to use only two spaces, or is four the JSON standard?

**Comment by quicksketch** [comment]
Four is the standard for JSON exports because it's the only thing that PHP's `json_encode()` supports when you pass in the `JSON_PRETTY_PRINT` flag. We have a backwards-compatibility option for PHP 5.3 which doesn't have this flag, but in 5.4 and higher we pass off pretty printing of JSON directly to PHP and don't make any modifications.

**Comment by jenlampton** [comment]
Ah okay. What does that mean for our exports and default configs? Should we leave them as 4 spaces instead of 2?

**Comment by quicksketch** [comment]
> Ah okay. What does that mean for our exports and default configs? Should we leave them as 4 spaces instead of 2?

Yep. And most (all?) core files JSON are already 4 spaces. If there are any with 2 we should convert them to 4.

**Comment by jenlampton** [comment]
> If there are any with 2 we should convert them to 4.

Good, that will make things easier!  I had found one that was 2 spaces I was trying to replace (the frontpage view).  Thank you!!!
