### ISSUE TITLE
[UX] Remove confusion about site_mail address during install

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2117]
As a follow-up to https://github.com/backdrop/backdrop-issues/issues/1696

@quicksketch mentioned:

> 90% of the time I enter my personal email address into the Backdrop installer. I think most people do the same. This is wrong. My Backdrop website isn't going to be able to send email as "gmail.com". 

Tasks:
- Remove "Site mail" from the installer.
- Default the installer to use `noreply@[current-domain-name.com]` based on the current domain name. 

---
~~PR from @jenlampton https://github.com/backdrop/backdrop/pull/1654~~
PR from @quicksketch https://github.com/backdrop/backdrop/pull/1702

**Comment by jenlampton** [comment]
> Remove "Site mail" from the installer.

yes, definitely yes! 👍 

> Default the installer to use noreply@[current-domain-name.com] based on the current domain name.

Also yes. 👍

**Comment by jenlampton** [comment]
@klonos said over in https://github.com/backdrop/backdrop-issues/issues/2229#issuecomment-263025288

> All the websites I maintain have the admin email set to admin@domain and that is usually set to be forwarded to the owner's email (bob@domain) as well as mine. That is in order to notify of any problems/errors someone that can fix them (me) as well as the site owner (in order to keep them in the loop and so that they can contact me in case I missed the email somehow.)

> ...so setting the admin email to no-reply@domain by default is not a good thing in my case.

I wonder if setting the DEFAULT to no-reply@domain is okay? Just to get it off the installer screen? There will still be the other UI for changing it...

**Comment by klonos** [comment]
...back from that customer. Thanx for copying this over @jenlampton 👍 

Right, to the issue at hand. So, everyone's mileage varies, but my use case above can only be considered a single use case if one looks at it from the point where it is a single person (myself) practicing the above-described procedures. If you look at it from the number of websites I've configured that way, then there are multiple use cases. 

This workflow of mine is also one of the main reasons I requested to ship core with an additional "site owner" role in https://github.com/backdrop/backdrop-issues/issues/1285#issuecomment-152736114 : so that non-tech-savvy people are not handed credentials to the admin/root of the website). Still elevated privileges compared to anonymous and logged in users, **but** limited to the basics that a site owner should be doing plus any extras per case.

**Comment by jenlampton** [comment]
> If you look at it from the number of websites I've configured that way, then there are multiple use cases.

The same can be said for any of the other use cases too ;)  The beauty is in the eye of the beholder and we have too many different beholders to be making assumptions about things like additional role names (or if they are necessary) or which user might be an "administrator".

But back to this issue, how do you feel about setting a sensible default for people (no-reply@domain.com) and allowing that to be overridden at admin/config/system/site-information?

**Comment by olafgrabienski** [comment]
On `admin/reports/updates/settings` you can enter "E-mail addresses to notify when updates are available". What about making this feature more general, providing an option on `admin/config/system/site-information` to enter e-mail addresses to be notified in other cases, such as discussed in #2229?

**Comment by jenlampton** [comment]
That's a good idea! Can you post that comment over on #2229 too, so it doesn't get lost?

**Comment by docwilmot** [comment]
I'm not quite grasping the "why" of this issue. The site should have a contact email (which isnt necessarily someone's personal email, but could be), and it seems reasonable to have it added during install. So why we removing it again?

**Comment by klonos** [comment]
> But back to this issue, how do you feel about setting a sensible default for people (no-reply@domain.com) and allowing that to be overridden at admin/config/system/site-information?

I *personally* do not object to that and also *personally* would prefer it and say "go for it". ...but remember I represent the non-drupal/backdrop-savvy site builders and I always try to put myself in their shoes. Removing that field from the installer will indeed make the initial setup process faster and less complicated (not significantly, but still), but so would removing the site name and slogan fields and the timezone field and so on. This might end up reducing the installer to a single step, but when the user finally gets to the "Congratulations! You've successfully installed Backdrop." page, how much of their website will actually have been set up? Sure, we can link to the site info config page form the "Congrats!" page, but what have we then accomplished? Postponed configuring that info till later and instead of the clean installer UI (where people are asked to provide all that info in a single place), we ask people to do so from the admin UI by having to deep-dive into the admin menu and its structure? Not sure.

On the other hand, people are used to be asked to configure their user name, email and also things like computer name, timezone and language from installing any of the 3 major operation systems. I don't think we're doing anything different with our installer that would compromise UX. And asking for the site email address is not exception IMO.

**Comment by klonos** [comment]
> I'm not quite grasping the "why" of this issue. The site should have a contact email (which isnt necessarily someone's personal email, but could be), and it seems reasonable to have it added during install. So why we removing it again?

Exactly what I was saying 😄

**Comment by klonos** [comment]
👍 in @olafgrabienski's suggestion to make the site email address be the one that receives notifications about updates + errors/warnings.

**Comment by jenlampton** [comment]
> I'm not quite grasping the "why" of this issue. The site should have a contact email (which isnt necessarily someone's personal email, but could be), and it seems reasonable to have it added during install. So why we removing it again?

Backdrop has never had one of those. If you think it should have one then okay, let's add it! (but please create another issue for that - or see @olafgrabienski's suggestion in  in #2229

This issue is not remove anything, but to hide a setting that most people don't understand from the installer. Since most people don't understand the question, they get the answer wrong, and enter in something that won't work.

We know an answer that is correct and will work, so the recommendation here is to enter in that value as a default, and don't ask the question as part of the installer. (But we are leaving the setting where it is otherwise, incase people like @klonos who do understand what the setting is would like to change it :)

**Comment by serundeputy** [comment]
the why is because the site tries to send email from this address which it can not duo:

>This is wrong. My Backdrop website isn't going to be able to send email as "gmail.com".

thus setting it to an email that matches the sending domain.  that is the why.

**Comment by jenlampton** [comment]
> Removing that field from the installer will indeed make the initial setup process faster and less complicated (not significantly, but still), but so would removing the site name and slogan fields and the timezone field and so on.

The difference here @klonos is that the site name will need to be set 100% of time on Backdrop sites, people know the answer to this question during install time, but most importantly, your site is not broken if you get the answer wrong. The nuisance of having it in the installer is negligible, and the benefit of removing it is nil.

With the site email address, most people have no idea what that setting is for **especially** new users. Even @quicksketch gets that question wrong! The benefit of hiding it is 2 fold, simpler install yes, but more importantly - fewer broken sites!!!  For the more advanced users who want to change it, we have a setting.

This change is directly inline with our principles of valuing those with less experience over those with more.

**Comment by klonos** [comment]
@serundeputy yeah, that makes better sense now, but who would be setting that email to a gmail one while setting up their website on their own domain, for which they most likely already have ...@damain email addresses configured for? Even so, why not then limit that field to be requesting only the username part of the email and have the domain part default to the domain the installation is happening on (and be read-only)? Something similar to how we prepend the domain to certain paths and only request the rest of it like when setting the home page and the 403/404 error pages?

[email_field]@auto-detected.domain.name

**Comment by jenlampton** [comment]
> but who would be setting that email to a gmail one while setting up their website on their own domain

Beginners.

**Comment by klonos** [comment]
> ...why not then limit that field to be requesting only the username part of the email and have the domain part default to the domain the installation is happening on

How about that then?

**Comment by jenlampton** [comment]
We could do that too! But I'd also like to see it gone from the installer :)

**Comment by docwilmot** [comment]
Thanks @serundeputy 

> the why is because the site tries to send email from this address which it can not duo:

Strangely, I have always put my private email address in there and the sites have always sent me email. Its sometimes flagged as spam, but it gets there!

Note though that if we ask Backdrop to only send email to `whatever@domain.com` we are also explicitly saying to our nontechies that they must also learn how to set up mail forwarding on a server.

Wordpress allows you to put any email you want as the site email.

So FWIW, I don't agree with this issue as it complicates this for the nontechie users.

**Comment by jenlampton** [comment]
> if we ask Backdrop to only send email to whatever@domain.com ...

I think you still are misunderstanding this setting, it the FROM address not the TO address.

> ... we are also explicitly saying to our nontechies that they must also learn how to set up mail forwarding on a server.

That's also not the case. the no-reply address we are going to set as default will work without the user needing to do anything else on their end. There is no actual email address or account required.

> I don't agree with this issue as it complicates this for the nontechie users.

Unfortunately Backdrop does not have any control of how email providers across the internet decide to solve spam problems. All we can do is read and understand the standards that are set, and do our best prevent our users from being caught in the trap of having their email messages not delivered (or marked as spam, or blocked, or blacklisted)

> Wordpress allows you to put any email you want as the site email.

Then we have a chance to do a better service for our users here than Wordpress does :)

**Comment by docwilmot** [comment]
> I think you still are misunderstanding this setting, it is the FROM address

Absolutely right I misunderstood! On that note I now approve this message (issue). Excuse the noise

**Comment by klonos** [comment]
> I think you still are misunderstanding this setting, it the FROM address not the TO address.

This is the key issue then. This needs to be both TO and FROM depending on the case. Error and update notifications need to be sent TO this address (so that an admin person receives them and acts accordingly), while welcome messages etc. need to be sent FROM this address (in order not to be flagged as spam).

Either this or we need to introduce the notion of two separate email addresses: one (lets call it website/bot email) will be "when I sent out messages, which address should I be using" (this can possibly be a no-reply@domain address, but it **must** be originating from the same domain as the website) and a second (lets call it admin email) that will be a "who do you need to notified if there's something wrong with the website" (this can even be an external, for example gmail address).

**Comment by klonos** [comment]
...the second email address could actually be a list of email addresses of people that need to receive notifications. The website/bot address needs to be a single one.

**Comment by olafgrabienski** [comment]
@jenlampton Re https://github.com/backdrop/backdrop-issues/issues/2117#issuecomment-263034091: Sorry, back again late (time zone issue). Will post the idea in https://github.com/backdrop/backdrop-issues/issues/2117#issuecomment-263033413 to #2229 at the next opportunity.

**Comment by docwilmot** [comment]
@olafgrabienski I think https://github.com/backdrop/backdrop-issues/issues/2117#issuecomment-263033413 is a different issue from #2229 and deserves its own issue (its a great idea).

**Comment by jenlampton** [comment]
> This is the key issue then. This needs to be both TO and FROM depending on the case.

Right now we have only  a single case where a Backdrop site sends emails TO any kind of admin notifying them of anything at all, and that's the update notification mentioned in [this comment](https://github.com/backdrop/backdrop-issues/issues/2117#issuecomment-263033413. If we want to repurpose that field for something more general, move it to another location, and dream up other reasons to email the admin-types, we can do that! :) But please - let's not do that in this issue :)

This issue is only about taking the setting that almost nobody understands off of the installer. PR on the way :)

**Comment by klonos** [comment]
Alright, I took a look at the "Configure site" step of the installer again and here are my thoughts:

1. The help text for the site email address is solid. It clearly explains what that email will be used for, what needs to be done and why: "Automated e-mails, such as registration information, will be sent from this address. Use an address ending in your site's domain to help prevent these e-mails from being flagged as spam.". Also, being grouped in the "Site information" fieldset along with the site name field makes even clearer.

2. Because we know that very few people read the help text, we could be pre-filling that field with an email. Something like `no-reply@%auto-detected-domain%`. This should give them a hint that this email address needs to be from the same domain as their server (even if they skip reading the help text). All they might want to change there would be the `no-reply` part of the email address. Even if the skip changing it, there's no harm done.

3. I believe that the "Site maintenance account" needs to change to "Site administrator account" or plain "Site administrator".

4. The admin email needs help text added to it to state that this is the email that will be receiving email notifications about updates and site problems. Also make it clear that this may be an external email like gmail.

5. The "Receive e-mail notifications" checkbox needs to be moved bellow the site admin email address. The notifications can be for pending updates, but they can also be notifications about other site problems. We should default that to checked by default (since in most cases there is a single site admin and it's their job to be acting on any site issues). More elaborate sites with many admins can add more people to the list in `/admin/reports/updates/settings`.

> If we want to repurpose that field for something more general, move it to another location, and dream up other reasons to email the admin-types, we can do that! :) But please - let's not do that in this issue :)

Agreed. I will file a separate issue for that (points 4 and 5), but I remember someone else already either mentioning that before or actually filing an issue. Will look into that.

Now, people not understanding the purpose of the site email is actually yet another manifestation of the more general issue of people not being bothered reading help text and this unfortunately applies in other places in the UI. As far as I am concerned, we are doing the best we can here with the already existing help text, which is accurate and as plain as can be (point 1 above).

Still, point 2 is valid and I believe that it will solve the issue of people not filling that field in properly. PR coming up :) ...PR fight, en garde ⚔

**Comment by jenlampton** [comment]
> The help text for the site email address is solid.

Yes, and we still have this huge problem. Which is why we need to remove it from the installer entirely.

> I believe that the "Site maintenance account" needs to change to "Site administrator account" or plain "Site administrator". 

Okay, Can you please create an issue for that somewhere else? :)

> The admin email needs help text added to it to state that this is the email that will be receiving email notifications about updates and site problems. 

But that's not how Backdrop works :) As stated [above](https://github.com/backdrop/backdrop-issues/issues/2117#issuecomment-263084838) there is only a single instance where people are emailed, and it has nothing to do with anything in this installer form, or this issue.

Can we please move this conversation somewhere else where it won't be lost when this issue is closed? Pretty please?

**Comment by docwilmot** [comment]
Agreed again, lets remove it and move on. This is a minor issue, not worthy of a PR fight.

**Comment by jenlampton** [comment]
Thanks @docwilmot .  Here's a PR that removes the confusing mail setting, and also clarifies what the "site maintenance account" is, since apparently people also do not understand that :)  I've changed the heading to "Master user account" and added some description text that explains why it's special.

![screen shot 2016-11-26 at 3 06 41 pm](https://cloud.githubusercontent.com/assets/397895/20644481/80de0d62-b3ea-11e6-84fa-2e0d3a78dded.png)

**Comment by docwilmot** [comment]
The new description text about bypassing permission checks is still too much for a first installer. 
"This account has full administrative permissions including the ability to delete all users and content. Please guard these credentials carefully"

**Comment by jenlampton** [comment]
> full administrative permissions including the ability to delete all users and content. 

There's nothing in here that indicates why this account is special. I think it's important that we tell people why it's different than all the other accounts that have `full administrative permissions including the ability to delete all users and content.` I'm open to new language though :)

Suggestions?

**Comment by jenlampton** [comment]
What if we made it more personal? Something like.. `When you log in using this account, access restrictions set anywhere on the site will not apply to you.`

**Comment by docwilmot** [comment]
Point is this is just to "scare" the user into being careful, not necessarily to explain what `user/1` technically can do. Thats not necessary in this context. In other words, "whoever has these login details can really destroy your site". Doesnt matter if anyone else can do the same, this one can, so hide this login well.

**Comment by jenlampton** [comment]
> Point is this is just to "scare" the user into being careful

But that's not the point at all. 

> not necessarily to explain what user/1 technically can do. Thats not necessary in this context.

If it's not necessary to explain the master account in this context, then let's just remove the text. If we don't add anything helpful then the text is just clutter.

**Comment by jenlampton** [comment]
Pushed a new PR that removed the over-explain text:
![screen shot 2016-11-26 at 4 59 45 pm](https://cloud.githubusercontent.com/assets/397895/20644828/cfbf835c-b3f9-11e6-91f2-d7ed88253365.png)

**Comment by olafgrabienski** [comment]
In my opinion, pre-filling a still visible setting as well as hiding the setting improve the situation a lot. I prefer the latter, but am fine with both of them.

On one important issue there hasn't been feedback so far:

> what if development happens on a different domain? Maybe we should set a warning message on validation if the domains don't match, but we can't restrict the fields.

If the domains don't match, we could display a warning on the *Status report* page with a link to the relevant form, similar as we made in #2040 regarding the setting of error messages.

**Comment by klonos** [comment]
I was starting to come around the idea of removing the site email from the installer because setting the default to no-reply@domain seemed like a reasonable decision. We'd be providing a sensible default and removing the respective field from the installer. So, we'd keep the installation experience as simple as possible and at the same time people would still be able to customize this after installation in the site info admin page.

BUT... we are using the site email as the recipient email address in the default contact form (https://github.com/backdrop/backdrop/blob/1.x/core/modules/contact/contact.install#L20). Setting this to a no-reply address would mean that the site contact form would not work out of the box and that would be a feature regression and a step backwards for #1168

**Comment by findlabnet** [comment]
Just about language - word "Master" may be insufficiently tolerant for some very nice people.
We need further discussion like this: https://www.drupal.org/node/2275877?

**Comment by klonos** [comment]
I meant to mention this as well. Not sure about other languages, but "master" would not be possible to translate properly to Greek (without having to use medieval terminology that is). Although "administrator" is also a user *role* in Drupal/Backdrop, I see no reason why not using that to refer to user 1. In Windows, there is an administrator and the administrators user group, so it will not be such a hard concept to grasp.  In small sites (such as our target audience), there would possibly be a single administrator user and their account could be "Bob" instead of "admin" or "administrator". I don't see any harm in that.

**Comment by jenlampton** [comment]
> If the domains don't match, we could display a warning on the Status report page with a link to the relevant form, similar as we made in #2040 regarding the setting of error messages.

Yes, I had the same thought. Can someone please create an issue for that? It's not related to this issue as it's a problem we currently have today.

> Just about language - word "Master" may be insufficiently tolerant for some very nice people.

I wondered about that too. I usually use the word "Root" myself, but I thought that was too developer-y. Does anyone have any suggestions other than administrator? :)

> In Windows, there is an administrator and the administrators user group, so it will not be such a hard concept to grasp. 

What's the difference between the two in windows? The problem I have with using the same word is that there is such a huge difference in meaning in Backdrop. I wonder if the same is true for the Windows example?

The problem with people not understanding this account is special is that's it's a huge security risk. People often remove the "Administrator" role from this user thinking they are decreasing the access that person has, but in reality that action does nothing.

**Comment by jenlampton** [comment]
Pushed a new PR with Primary, definitely better:
![screen shot 2016-11-27 at 2 11 31 pm](https://cloud.githubusercontent.com/assets/397895/20652296/7a96d7c4-b4ab-11e6-8fda-a1b92286fe43.png)

**Comment by klonos** [comment]
>> If the domains don't match, we could display a warning on the Status report page with a link to the relevant form, similar as we made in #2040 regarding the setting of error messages.

> Yes, I had the same thought. Great idea :) See #2364

**Comment by klonos** [comment]
>> In Windows, there is an administrator and the administrators user group, so it will not be such a hard concept to grasp.

> What's the difference between the two in windows?

The one (singular "administrator") is a user account and the other (plural "administrators") is a user group (to which the administrator user belongs). So, it's pretty much the equivalent of the situation you'd have in a Drupal/Backdrop website if you'd define "administrator" or "admin" as user 1 with that user account being assigned the admin role.

Now, I'm a Windows user and I'm used to that situation. So, that explains why I'm not bothered by changing the "Site maintenance account" to "Site administrator". As I mentioned before, in its simplest form, a Drupal/Backdrop small website would have a single user that would be the site administrator (would be assigned the "Administrator" role). Now, that user can also be called "Administrator" and perhaps that account's credentials might be shared among the people that need to perform admin tasks, but there might as well be more users, like "Bob", "Jane" that can be assigned the "Administrator" role. No harm either way.

**Comment by klonos** [comment]
> Now instead of using the FROM address to send TO, it checks the user 1 account, and if it's not blocked, the TO address is set as that user's email. If the User 1 account is blocked at the time the contact module is enabled (which isn't very likely, but you never know!) then no default site wide contact form will be created.

This is OK in cases where the site owner and the site administrator are the same person, but in cases where the site admin (user 1) is just the guy that has build the website, they don't want to be receiving contact emails from people trying to get a quote for whatever it is that the site owner sells. No good.

I still think that the way to go is leave the site_email be the email that the contact form sends to by default. If people want to change that to be a personal email address (of the person that will be replying), they can define that either during the installer or in the site info page. This is a setting that users will most likely want to customize and by not removing it from the installer we would not have to try to change the habit of what people have been using this field for all along. So we do not need to train, convince or upset them and we do not need to change anything in the UI.

Now, for the email that outgoing email is sent from, we can simply have that default to no-reply@domain (since most people would not want to customize it) and decouple it from the site_email field and the respective json config file setting. We do not need to expose any setting for this email in the UI at all (although it would be nice to have).

**Comment by klonos** [comment]
...so basically what I'm saying is that instead of telling users "No, no, no, you are not using this field right because we use it for outgoing mail and it might be flagged as spam and blah-blah-blah", we say "OK, keep using this field by adding the email of the person that is responsible of this website (as a business/organization) and we'll just use another email for the outgoing messages, one that complies with whatever machines expect ("no-reply" and same domain as the website) and one that you do not need to worry about".

**Comment by jenlampton** [comment]
But the thing you want (a contact email) does not exist in Backdrop. I've
created an issue to add one, please can you add a comment over there?

**Comment by klonos** [comment]
Yes, of course I will. But the thing I'm trying to say is that when users use this form, they fill that field with an address that they believe will be the contact email. It's just an instinct. So, if this instinct is a fact, lets not remove the field, lets just make it do what the users expect it to do. That is the point of usability, right?

What was being done wrong in this form is that a) we were requesting users to enter an email that should not be allowed to have a configurable domain (it should be the domain of the site) and b) we shouldn't be gathering that info because it can pretty much default to something that users will most likely never change or even care to change. So, yes, that field was meant to gather the FROM address and yes, we shouldn't be doing that in the first place. But, since that field is there and since users seem to be filling in the site contact email there, then lets just make good use of that and have it gather info that will help us make things work out of the box (#1168).

If we end up removing that field in this issue here, then what argument will I have when I request to add a `contact_email` field in its place and people reply "But we removed that, why didn't you say something back then?".

**Comment by klonos** [comment]
...BTW, I am working on a PR that stores the email entered in this field in a new `site_contact` setting that then contact.module uses to set up the default contact form. I also move the "Receive e-mail notifications" checkbox right below the site admin account email (since that's where other forms on the web ask you if you wish to receive notifications). If that's checked, it adds user1's email to the list of emails to be notified (that currently resides in `/admin/reports/updates/settings` but basically wherever we and up putting that list in #2365).

**Comment by jenlampton** [comment]
But if you want a 'contact email' on the install form, then we should add
it as part of the issue that adds a 'contact email' setting to Backdrop --
and in a PR on that issue. This issue is unrelated (except that people keep
confusing the two).

**Comment by jenlampton** [comment]
Also just to reiterate, we are not removing any settings in this issue,
were just hiding one that's misunderstood from the installer. This
misunderstood setting is currently used all over backdrop - as the FROM
address. Removing it from the installer is a very minor change.

To add a new setting that's a TO address (even adding it onto the
installer) is also a very minor change - and has another issue!

Changing this FROM setting to a TO setting is a very large change, and I'm
worried thays what you're up to @klonos.  Just trying to save you are time
and trouble. It's not necessary.

**Comment by docwilmot** [comment]
what a lovely bikeshed, just in time for christmas too. you shouldnt have! :smile: 

Seriously though, @klonos makes a good point re the `contact module` requiring `$site_mail`. But that simply means that if we accommodate this we should have *two* fields in the installer, (one for the TO, one for FROM), because as @jenlampton says we cannot simply repurpose the existing textfield as that would cause more confusion and issues for those users/site owners who weren't fooled and are actually using it as the FROM address all along. Its an API change level decision IMHO.

So its either change to *two* mail textfields in the installer or *no* mail textfields.

But none of this absolutely *has* to be in the installer; it could be a separate setting, as #2365 is dealing with. An a cleaner installer is a better first impression.

Lets kill it.

**Comment by jenlampton** [comment]
The good thing about a bikeshed is that it means that everyone cares passionately - about user experience!!! :) :) :)

> What was being done wrong in this form is that a) we were requesting users to enter an email that should not be allowed to have a configurable domain

Actually, it should. Please read the [comments above](https://github.com/backdrop/backdrop-issues/issues/2117#issuecomment-263035280) as to why, it's been stated before. 

> If we end up removing that field in this issue here, then what argument will I have when I request to add a contact_email field in its place and people reply "But we removed that, why didn't you say something back then?".

Well, 1) you certainly *did* say something...  but 2) these fields are for two different settings. We're removing the one people don't understand **here** and we're adding something completely different in [this issue](https://github.com/backdrop/backdrop-issues/issues/2365).  Plus, if we do it all right away no one will be able to forget this dialog (sorry everyone!) :P

> Let's kill it.

Yes please. There's a PR here: https://github.com/backdrop/backdrop/pull/1654 It needs a review :) I think we were stuck at which word to use for "Principal" before we got sidetracked.

**Comment by olafgrabienski** [comment]
> I think we were stuck at which word to use for "Principal" before we got sidetracked.

I'm no native English speaker, so I compared the different proposals with the help of a dictionary. "Primary User Account" seems to be a good choice.

**Comment by jenlampton** [comment]
Great, the PR is currently using `Primary user account` so I think this is good to go then :) Can we get this issue marked RTBC?  I'd love to see this UX win added in 1.6 :)

(Once this gets in we can start working on https://github.com/backdrop/backdrop-issues/issues/2365 - to add the feature everyone expected, but that didn't actually exist in Backdrop.)

**Comment by quicksketch** [comment]
Of the two approaches, I'm a fan of removing the option entirely from the installer. Switching the default TO address in contact module to be that of user #1 also makes a lot more sense than sending to the "site_mail" option, which as noted is frequently a send-only account. So this not only simplifies the installer but also prepopulates a better default for Contact module. If sites do indeed want their password-reset emails to come from a reply-friendly address, the option still exists to change it. But this approach makes for much better reliability of emails getting delivered out-of-box, without allowing users to shoot themselves in the foot.

I gave the PR at https://github.com/backdrop/backdrop/pull/1654 a review, it has a few issues and needs additional tests to cover the new `backdrop_get_bare_domain()` function.

**Comment by jenlampton** [comment]
Addressed all the feedback and pushed a new PR.

**Comment by quicksketch** [comment]
Sorry about my not-to-helpful comment above. I read the entire issue through again today and realized it seems we're all on the same page now.

- The "site_mail" value is _supposed_ to be used as a FROM address, which MUST be the same as the site domain in order to send emails that don't immediately get flagged as spam. This value is used for registration emails, password resets, etc.
- The "site_mail" value is incorrectly also used for the contact module to be the default TO address. We can fix this problem by using the UID `#1` email address instead, as that will actually be the administrator's personal email.
- As the "site_mail" value is so frequently misunderstood (including by most of us even in this very issue), we should remove it from the installer and provide a reasonable default that will work on most sites.
- And as a follow-up, we might make a site-wide email TO address in https://github.com/backdrop/backdrop-issues/issues/2365.

I rerolled the PR to make it handle subdomains consistently. They are now always stripped off (previously they were only stripped off if the TLD was two letters). This results in a domain like `foo.bar.example.com` being shortened to just `example.com`, to construct an address like `noreply@example.com`. I expanded the test coverage and reworked the tests a bit to separate out the tests that require a `BackdropWebTestCase` from those that can be `BackdropUnitTestCase` (making for faster test runs when testing URL-related functions like this).

**Comment by jlfranklin** [comment]
Will these remain configurable post-install?  Setting reasonable defaults sounds great, but there are times when outbound mail is being handled by a parent or partner organization and the site email needs to be able to use their domain in the email address.

**Comment by jenlampton** [comment]
Thanks for the cleanup on `backdrop_get_bare_domain` @quicksketch, the current approach is more consistent 👍  I've given the latest PR a new test, RTBC from me.

**Comment by jenlampton** [comment]
> Will these remain configurable post-install? 

Yes, the post-install configuration remains unchanged from how Backdrop works today.

**Comment by jlfranklin** [comment]
Hmm... The email address is blank in the the PR's test instance:

http://1702.backdrop.backdrop.qa.backdropcms.org/admin/config/system/site-information

![screen shot 2017-01-01 at 7 06 19 pm](https://cloud.githubusercontent.com/assets/17887377/21583577/8e553150-d055-11e6-8217-e10b672a11bf.png)

**Comment by jenlampton** [comment]
that should have been no-reply@backdropcms.org. Maybe we should add http://1702.backdrop.backdrop.qa.backdropcms.org as one of our domains into the testing script, ot be sure it is able to propperly guess the bare domain?

**Comment by quicksketch** [comment]
Here's our code in `system_install():`

```
+  // Set the site_mail to a sensible default.
+  $site_mail = 'noreply@' . backdrop_get_bare_domain($_SERVER['SERVER_NAME']);
+  if (valid_email_address($site_mail)) {
+    config_set('system.core', 'site_mail', $site_mail);
+  }
```

So my guess is that the email address we're getting back isn't valid for some reason, so the config doesn't get set. I'll check this out a bit more.

**Comment by Dinornis** [comment]
> We can fix this problem by using the UID #1 email address instead, as that will actually be the administrator's personal email.

Just wondering if this could cause issues for sites that disable/remove `UID #1`  for security reasons.

**Comment by jenlampton** [comment]
@Dinornis yes, and that's why we're also working on https://github.com/backdrop/backdrop-issues/issues/2365

**Comment by quicksketch** [comment]
To clarify, the issues that might be caused are very slim. The UID #1 email address will be used for the contact module by default, but this is only a propopulated field value that can be changed. And even if UID #1 is blocked, as long as the contact module email is valid it won't cause any issue.

> So my guess is that the email address we're getting back isn't valid for some reason, so the config doesn't get set.

Ah, I figured this one out. Because the testing servers install via the command line, a server name isn't available in `$_SERVER['SERVER_NAME']`. I think we may just need to restore the ability to specify a site mail via `install.sh`.

**Comment by quicksketch** [comment]
The install.sh script has been fixed and sandboxes are now getting site_mail set again. I think it's interesting that Backdrop actually has code to handle site_mail being empty, even though it's a required field. I actually found that email was sent just fine even without a FROM address at all, and the system-wide mail system was used (e.g. `apache@hostname.local`).

But in any case, this now maintains full compatibility by keeping the option in the `install.sh` script, while simply removing the option from the installer UI, providing a reasonable default instead.
