### ISSUE TITLE
Layouts: Provide context tokens for use in page title (and elsewhere)

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2130]
Here's my use case. I have a taxonomy term named "Technology". I want the title of that page to be `Technology committee`. In both panels and views in D7 this was possible using special placeholders for the context, for example `%1 committee` would work on all term pages.

~~Do we have an equivalent token(?) in Backdrop?~~ If not, can we add a `[context:THING]` set of tokens that can be used anywhere in the layouts UI? (page title, block titles, block content, block settings, etc)

**Comment by klonos** [comment]
Related (?): #2103

**Comment by quicksketch** [comment]
We don't run tokens on the title currently. Here's the code from `layout_preprocess_layout()`:

```php
    if (!isset($variables['title'])) {
      if ($settings['title_display'] === LAYOUT_TITLE_NONE) {
        $variables['title'] = NULL;
      }
      elseif ($settings['title_display'] === LAYOUT_TITLE_CUSTOM) {
        $variables['title'] = check_plain(t($settings['title']));
        backdrop_set_title(t($settings['title']));
      }
      else {
        $variables['title'] = backdrop_get_title();
      }
    }
```

In theory we could just start running `token_replace()` on the title if one is specified. But we need to pass in the `$data` parameter. I suppose for starters we can loop through `$layout->getContexts()` and pass in the first type of object that we find. But for paths that have multiple contexts of the same type, things are likely to get tricky because I don't think the core token API supports finding multiple tokens of the same type. e.g. a token like `[node:title]` won't be able to understand which node to use if two nodes are passed in. The core token API also doesn't support tokens like `[node1:title]` vs. `[node2:title]`. You can't set arbitrary names for token types (though we could perhaps expand it to do so).

We can do the "for starters" idea fairly easily though. To handle multiple contexts we'll need to both expand the token API and start naming our contexts within the Layout UI so they have machine names.

**Comment by jenlampton** [comment]
> token like [node:title] won't be able to understand which node to use if two nodes are passed in

That's why I'm recommending we do it more like panels and provide a specific token for context. something like `[context1:node:title]` vs `[context2:node:title]` would be fine. The context token wouldn't be an arbitrary name, it would be something provided to token via layouts  (or system? wherever context is provided).

Is there any chance we can just pull the existing code from this from panels, and replace the placeholders with real tokens?

**Comment by jenlampton** [comment]
dupe of https://github.com/backdrop/backdrop-issues/issues/1860
