### ISSUE TITLE
Coding standards: URLs, variables, language and markup in user-facing text passed through t().

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2131]
I see (dead people - no, just my OCD kicked in again) multiple ways of how this is done in various places throughout the codebase. Lets take this one by one:
1. Why the empty `array()` here?
   
   `t('Some text with no URL in it.', array(), array('langcode' => $langcode));`
2. Which one is (or should be) the standard when we have no title for a URL?:
   
   `t('Some text with http://www.some.site/page in it.');`
   
   `t('Some text with <a href="http://www.some.site/page">http://www.some.site/page</a> in it.');`
3. Which one is (or should be) the standard when we do have a title:
   
   `t('Some text with <a href="http://www.some.site/page">a URL</a> in it.');`
   
   `t('Some text with <a href="@url">a URL</a> in it.', array('@url' => 'http://www.some.site/page'));`
4. Do we use `@` or `!` (when there's only one thing to replace)?:
   
   `t('Some text with <a href="@url">a URL</a> in it.', array('@url' => url('admin/internal/path')));`
   
   `t('Some text with <a href="!url">a URL</a> in it.', array('!url' => url('admin/internal/path')));`
   
   Sub-question here: I haven't actually found any occurrence using `%` in URLs, but I see it used for variable replacement in `t()`. Is that an option too?
5. A combined question for points 3 and 4 above: do we wrap a URL in `url()` only when it is an internal path, or do we need to wrap all URLs/paths in `url()`?
6. I found only [a single occurrence](https://github.com/backdrop/backdrop/blob/1.x/core/modules/path/path.admin.inc#L519) of something like this:
   
   `t('Some text with <a href="!url">a URL</a> in it.', array('admin/internal/path'));`
   
   Bug/typo? Shouldn't it be `array('!url' => 'admin/internal/path')` instead?
7. Some `t()` functions use `langcode`, others both `langcode` and `language`, but most do not use any:
   
   `t('Some text with <a href="@url">a URL</a> in it.', array('@url' => url('admin/internal/path')), array('langcode' => $langcode));`
   
   `t('Some text with <a href="@url">a URL</a> in it.', array('@url' => url('admin/internal/path', array('language' => $language))), array('langcode' => $langcode));`
   
   If I have this right, this is required for UI translations. Right? Why don't we do that for _all_ `t()` functions then?
8. When there are two or more variables in a `t()`, we sometimes use `%` for non-URLs/paths and `@` for URLs/paths:
   
   `t('Some text with a %variable and <a href="@url">a URL</a> in it.', array(%variable => $variable ,'@url' => url('admin/internal/path')));`
   
   ...sometimes we use `%` and `!`:
   
   `t('Some text with a %variable and <a href="!url">a URL</a> in it.', array(%variable => $variable ,'!url' => url('admin/internal/path')));`
   
   ...and elsewhere we use `!` for everything:
   
   `t('Some text with a !variable and <a href="!url">a URL</a> in it.', array(!variable => $variable ,'!url' => url('admin/internal/path')));`
9. Also, I found two occurrences ([here](https://github.com/backdrop/backdrop/blob/1.x/core/modules/redirect/redirect.admin.inc#L502) and [here](https://github.com/backdrop/backdrop/blob/1.x/core/modules/redirect/redirect.admin.inc#L580)) where the variable would also hold markup (`<em>` tags concatenated before and after). In these specific cases, shouldn't the markup be inside the `t()` function instead?
10. Speaking about markup inside `t()`, I think that I have seen that variables using `%` are automatically rendered as italics (a good thing). But sometimes we use markup when referring to names of say permissions, content types or sections of the website etc., while other times we use double quotes:
    
    `t('This is some <em>quoted</em> text.')` vs. `t('This is some "quoted" text.')`)
    
    Again, what should the standard be?

In general, I see either `!`. `%` or `@` used as a variable/placeholder in t(). What is (or should be) the standard?

**Comment by quicksketch** [comment]
> A combined question for points 3 and 4 above: do we wrap a URL in url() only when it is an internal path, or do we need to wrap all URLs/paths in url()?

Yes, you found the key item for items 1-4. Only internal URLs need to be substituted because they change depending on where you have installed Backdrop (e.g. in a subdirectory, clean URLs on/off, etc). External URLs are *usually* better of within the string so they can be translated as well, for example to link to a Wikipedia page that is in the translated language.

> I found only a single occurrence of something like this:
> t('Some text with <a href="!url">a URL</a> in it.', array('admin/internal/path'));
> Bug/typo? Shouldn't it be array('!url' => 'admin/internal/path') instead?

Yeah, bug.

> Some t() functions use langcode, others both langcode and language, but most do not use any:

Any that use "language" is a bug. They should all be "langcode" (that's an API change from Drupal 7 we inherited). Specifying langcode is optional as the site-wide language for the interface will be used if no langcode is provided. Specifying the langcode is only required if A) You want to display something different than the current page's language or B) You're translating something besides a string (usually a URL), in which case you need to pass in the language you want the URL to be in. This is because the language for the current page and the language for the displaying the URL is not always the same thing, or you are linking to other translated versions of the same page.

> When there are two or more variables in a t(), we sometimes use % for non-URLs/paths and @ for URLs/paths

The documentation for the `t()` function might help here: https://api.backdropcms.org/api/backdrop/core%21includes%21bootstrap.inc/function/t/1

The key part:

- `@variable`: Escaped to HTML using check_plain(). Use this as the default choice for anything displayed on a page on the site.
- `%variable`: Escaped to HTML and formatted using backdrop_placeholder(), which makes it display as <em>emphasized</em> text.
- `!variable`: Inserted as is, with no sanitization or formatting. Only use this for text that has already been prepared for HTML display (for example, user-supplied text that has already been run through check_plain() previously, or is expected to contain some limited HTML tags and has already been run through filter_xss() previously).

> Do we use @ or ! (when there's only one thing to replace)?

When dealing with URLs, I think we have some serious inconsistency here. If the URL is hard-coded, `!url` is probably better. But if it's user-provided, it needs to be `@url` so that it is sanitized. 90% of the time the output will be the same between these, because URLs don't tend to include special HTML characters like `<>"'`. The `@` version protects against non-safe input (like JavaScript tags). The `!` version doesn't do anything at all, so if you have a weird URL it's less like to break it. I don't think we *actually* have any URLs like this however, so `@` is probably the one we would use if we wanted consistency everywhere.

> But sometimes we use markup when referring to names of say permissions, content types or sections of the website etc., while other times we use double quotes.

Yeah... inconsistency galore here too. Italics are supposed to indicate "Hey this isn't translated", but if the input IS translated (such as a content type name), then quotes are used to indicate the proper name for the Content type/View/Layout/etc. I also just find the quotes are a lot more clear than italics when dealing with trying to describe a particular thing.

So in general if the string passed in is also translated, `@` is used instead of `%`. For example it *should* be `t('New @type content has been saved', array('@type' => $type_label)`, where $type_label has already been translated. But if the label were not possible to translate, `%type` would be used. And if you were talking directly about the content type, I would want to see `t('The content type "@type" has been saved.', array('@type' => $type_label))`, with quotes around the translated version of the label.

I think that's all of them. `t()` is a tricky function and even with the already fairly extensive docs there are places where it falls short in explanation.

**Comment by klonos** [comment]
>> I found only [a single occurrence](https://github.com/backdrop/backdrop/blob/1.x/core/modules/path/path.admin.inc#L519) of something like this:

>>  `t('Some text with <a href="!url">a URL</a> in it.', array('admin/internal/path'));`

>>  Bug/typo? Shouldn't it be `array('!url' => 'admin/internal/path')` instead?

>Yeah, bug.

PR for that coming up...

**Comment by klonos** [comment]
>  Bug/typo? Shouldn't it be `array('!url' => 'admin/internal/path')` instead?

...`array('!url' => url('admin/internal/path'))` actually 😉

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/1600, but let's keep this open as a question for now. We could still bring some consistency to this, but I'm not sure how to go about it.

**Comment by klonos** [comment]
I say baby steps. I'll file some follow-up PRs fixing issues here and there and eventually also draft a coding standards document for approval.

**Comment by BWPanda** [comment]
I think we can close this now. I was going to go through and answer all of @klonos' questions above just for posterity (as I think he knows all the answers himself now), but I think our documentation for `t()` is pretty good (https://docs.backdropcms.org/api/backdrop/core%21includes%21bootstrap.inc/function/t/1) and Drupal's [Localisation API](https://www.drupal.org/docs/7/api/localization-api) docs have some good examples and do's/dont's too.
