### ISSUE TITLE
[UX] Add a HTML tag selector (Format dropdown) into the Rich-Text editor

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop/backdrop-issues#2148]
In the current Backdrop version, I miss the Format dropdown of CKeditor for HTML headings. @jenlampton assumed in https://github.com/backdrop/backdrop-issues/issues/1520 (how do I get the URL of a specific comment?) that "we used to have the "Formats" option available by default". If this is the case, it should be added again.

Maybe related: https://github.com/backdrop/backdrop-issues/issues/2142 (Add back the missing ckeditor link/unlink/anchor buttons)

---

PR from @jenlampton at https://github.com/backdrop/backdrop/issues/1545

**Comment by jenlampton** [comment]
Reading back over the `ckeditor to core` issue it doesn't look like we included formats by default, but I agree it would be good to include it now. We don't want people thinking ckeditor is limited just because they haven't gotten to the config screen yet. 

@olafgrabienski in order to get a link to a comment you hover of the "X time ago" next to the person's name and right-click save-link-as. Or at least, that's how I do it ;)

**Comment by quicksketch** [comment]
I doubt this will be in 1.5.0, but we'll see. It is just enabling a new option by default.

To be clear, we're talking about the "Format" select list which shows a list of available block elements (h1, h2, h3, p, blockquote, etc), not the "Styles" select list, which needs further configuration of specific tags/classes to be used.

And a reminder the way the "Format" select list works is that it automatically shows *all* block level elements that are specified as allowed tags with the text format. For the "filtered_html" text format, that would be:

- blockquote
- h3
- h4
- h5
- p

Note that `<code>` is not a block level element, so it's not included. Perhaps we should reopen #1267 as a feature request to support it.

**Comment by olafgrabienski** [comment]
Yes, no pressure to put it in 1.5 though it would perfectly match the "editorial experience" slogan.

Related question: Why do the allowed heading elements in "filtered html" start with `h3` and not with `h2`? Is that because of blocks who get a `h2` block title as default, so it's good to not have a following `h2`?  For pages with their `h1` page title it would however be nice to allow `h2` as default. (Wouldn't be so easy to implement, I guess.)

**Comment by jenlampton** [comment]
> Why do the allowed heading elements in "filtered html" start with h3 and not with h2? 

It's not because of blocks, it's because of node teasers. If you are on a page that showed 10 node teasers (the default home page, for example), that page uses the `h1` as the page title, `h2` for each node title, and anything within each should start with `h3`, semantically speaking.

I'm not sure how important this heading ordering is these days, I sortof get the feeling it's mattering less and less. Maybe let's open up a follow-up issue about semantics and see if we can get consensus on allowing H2 or even H2 in text areas?

**Comment by olafgrabienski** [comment]
Thanks for your feedback! In my opinion, starting with `h3` is also a good default. I'd say, let's first get the format dropdown in the editor and consider then, if it's worth to open a new issue.

**Comment by jenlampton** [comment]
Okay, well PR for testing! https://github.com/backdrop/backdrop/issues/1545

**Comment by olafgrabienski** [comment]
That was quick! I read, "Some checks were not successful", but the interface in the editor looks good, and the formats work as well.

**Comment by jenlampton** [comment]
I'm sure there are some tests that need to be updated. (I didn't check) will do that in a little bit.

**Comment by quicksketch** [comment]
It may have been a random fail. PHP 5.3 passed but PHP 7.0 didn't. I restarted the tests.

How do we feel about the positioning of the buttons? (Bikeshed warning!)

![screenshot from 2016-09-12 17-04-57](https://cloud.githubusercontent.com/assets/100206/18457148/1cdd3262-790b-11e6-9b7d-915c13e1a0a6.png)

**Comment by jenlampton** [comment]
> How do we feel about the positioning of the buttons?

I have no strong feelings about positioning. Should we copy WP?

**Comment by olafgrabienski** [comment]
Maybe it's good to group the block element related buttons (Headings/Normal, Lists and Alignment). It seems more logical, but that not might be important for other users:

![screen-backdrop-editor-default-suggestion](https://cloud.githubusercontent.com/assets/14188307/18466333/93c10828-799b-11e6-8e40-d452082b9381.png)

Re WordPress: We can't copy it directly, because the formats are not visible as default, they're in the 'kitchen sink', opened via a toggle button:

![screen-wordpress-editor-default](https://cloud.githubusercontent.com/assets/14188307/18466409/e7155a56-799b-11e6-939c-55028e85e379.png)
![screen-wordpress-editor-toggled](https://cloud.githubusercontent.com/assets/14188307/18466408/e7141cb8-799b-11e6-8538-8276a5f8e0ec.png)

What I like in the WordPress formats dropdown: they call a paragraph a "Paragraph". Also mentionable: they allow all headings beginning from H1:

![screen-wordpress-editor-toggled-formats](https://cloud.githubusercontent.com/assets/14188307/18466526/564122e8-799c-11e6-9672-b4f0f9265953.png)

**Comment by jenlampton** [comment]
> Maybe it's good to group the block element related buttons

Hm, I don't like this idea. I prefer most-commonly-used-first. Let's copy WP as 1) they have likely done studies on this and 2) we are after the same end-users, so familiarity will be good.  Let me see what I can muster...

**Comment by jenlampton** [comment]
I just pushed a new PR that also orders these the same way as WP, with the exception of the `Format` drop-down, since that wasn't in there on WP.  I left that where it was in the last PR, but I'd be open to suggestions as where it might be better. 

> What I like in the WordPress formats dropdown: they call a paragraph a "Paragraph". 

I spent a little time looking for where the word 'Normal' comes from, and I don't think that's us - it's CKeditor adding that. If there is a setting to change it, we have not yet implemented it, so it may take a little work.  @klonos or @olafgrabienski would one of you please open a follow-up issue for that? :)

**Comment by olafgrabienski** [comment]
> PR is here: backdrop/backdrop#1545

This PR doesn't reflect the changes to the order of the editor buttons. Is there another one?

**Comment by olafgrabienski** [comment]
@jenlampton Looking at the screenshot, I like the WP-like order, but I'm not sure about the image button in middle of text related buttons. Actually, the image button is the only one which is not at the same place as in WordPress (which has a separate "Add Media" button _above_ the editor, cf. screenshots in https://github.com/backdrop/backdrop-issues/issues/2148#issuecomment-246611303).

I'd like to separate the image button as well (though not above the editor), or to group it with the link buttons which work in a similar way.

**Comment by jenlampton** [comment]
> This PR doesn't reflect the changes to the order of the editor buttons

It does. Did you reinstall since pulling the new branch?  The button set-up is done on install, so just pulling won't show you anything different than before.

> I'd like to separate the image button as well, or to group it with the link buttons which work in a similar way.

In backdrop we have some accessibility features that are not in WP.  Our buttons are grouped in a way that will help people using assistive technology find the button they want. Moving things around isn't simply an asthetic or workflow-related choice for us, it needs to be a semantic one too.  Here's the groups we have currently:

![button-groups](https://cloud.githubusercontent.com/assets/397895/18528384/ac7e0662-7a7d-11e6-9332-a8fd9b9b5130.png)

I'm kindof on the same page with you about changing the position, but I wonder about the "cost of change" in this case. If you were relying on the screen reader to help you find the blockquote button, and for the last 1.75 years you'd found it under "media" (I know - wut?!) if we move it elsewhere now - would you be able to find it? If we moved it somewhere smarter, would that be a UX win in your eyes, or would you be mad that we moved it?

**Comment by jenlampton** [comment]
I tried a few different positions of the buttons, and I think I like this one: 
![screen shot 2016-09-14 at 1 31 53 pm](https://cloud.githubusercontent.com/assets/397895/18528895/adf793ee-7a7f-11e6-86e8-e79c434854f1.png)

* Moves `Blockquote` into `Formatting` group (but leaves it on the far right within)
* Moves `Media` group (now containing only `Image`) over to the right of links.

Thoughts?

**Comment by Graham-72** [comment]
I always provide my users with a 'Paste as plain text' icon, and put it alongside the Image icon.

**Comment by olafgrabienski** [comment]
> Did you reinstall since pulling the new branch?

No, I didn't. (How would I do that?)

Regarding the accessibility features: I see! There will be possibly users who don't like the changes because they're used to the former behaviour, whether screen reader users or not. UX changes should however be possible if they make sense. And to move Blockquote out of Media seems to be a good idea (but: see below).

> Moves Blockquote into Formatting group (right of B/I but left of the Format drop-down)

Semantically perfect, but doesn't reflect at all the "most-commonly-used-first" principle. Blockquote seems a bit like an alien there. I'd be fine with your suggestion as Blockquote is a difficult one, sort of hybrid, but not sure at all if it's really a win

Are there others who want to weigh in?

**Comment by jenlampton** [comment]
> I always provide my users with a 'Paste as plain text' icon, and put it alongside the Image icon.

I notice WP includes this in the "Kitchen sink" too. Can we create another issue to add it?

**Comment by quicksketch** [comment]
Well, we're only talking about new installs here. Existing sites of course will be free to rearrange as desired. I think this is a good improvement as I also tend to enable and use this option on every site. I tend to put my dropdowns all the way on the right end of the toolbar, but I wouldn't complain about it being where it is in this suggestion. It's definitely better than not being there in the first place.

One thing I like about this is that I can never keep straight the "Format" vs. "Styles" dropdowns. If formats is already enabled and I've been creating content, I'll know what it is by the time I go to configure the text format.

The PR is ready to merge IMO. But I'll leave this for the completion of this discussion.

**Comment by quicksketch** [comment]
At first I also thought the moving of blockquote was weird, but from our groups I can see that as quite sensible.

I merged https://github.com/backdrop/backdrop/pull/1545 into 1.x for 1.5.0. Thanks everyone!
