### ISSUE TITLE
Menus cannot be dragged to the left (in order to be moved 1 level up) unless they are the last child of their parent.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2159]
I was trying to create a long menu in order to test the PR for #2107, when I noticed this unexpected behavior... so if a menu item has submenu items below it and it is not the last child of the parent menu, then it cannot be dragged to the left:

![backdrop-menu_items_cannot_be_dragged_to_the_left](https://cloud.githubusercontent.com/assets/2423362/18428084/58a62e12-790f-11e6-8320-e98ea2d0506f.gif)

**Comment by klonos** [comment]
...and a simpler example:

![backdrop-menu_items_cannot_be_dragged_to_the_left-simpler_example](https://cloud.githubusercontent.com/assets/2423362/18428192/f1ade41a-790f-11e6-9567-b05580d91432.gif)

**Comment by klonos** [comment]
...so to summarize: a menu item cannot be dragged to th right if it has siblings unless it is the last child of its parent. ...I think ... 😕

**Comment by quicksketch** [comment]
This behavior is actually intentional. The short version of the rule is simply this:

"The you can't re-parent any children by moving the parent. You have to move the children instead."

If you dragged a child that had siblings to the left, the sibling would suddenly become the parent of all its lower siblings. Although this seems strange given your example gifs, if those contained actual categories it would be a lot more sensible. Take a simple list:

```
- Sports
  - Volleyball
  - Basketball
  - Soccer
- Academics
- Administration
```

If you dragged "Volleyball" to the left, suddenly "Basketball" and "Soccer" become children of "Volleyball". All the children loose their parent just by moving one child, and it results in a completely incorrect hierarchy.

This restriction also exists when moving any other items around in the tree, you can't reparent children using other items besides siblings either. It's actually not about siblings at all, but the rule preventing any children from being reparented by injecting a new parent above them.

**Comment by BWPanda** [comment]
Closing as 'works as designed'.
