### ISSUE TITLE
[UX] Change `Front page` to `Home page` in core

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2162]
We have a lot of places in core that refer to the home page of the site as a `Front page`. This is a bit of a drupalism and I would love to see us move to calling it the `Home page` consistently. That, however, will be a lot of work. Here are some of the places we need to update:

- [x] #3855 | [UX] Update "Front page" to "Home page" on the Site information page
- [ ] The silly `<front>` placeholder
- [x] After running update.php link
- [x] Layout "Is this the front page." condition
- [x] Redirect module validation
- [x] Token for `[site:url]` description
- [ ] ~The API-level config variable `config_get('system.core', 'site_frontpage');`~
- [x] more TBD

Spun off from https://github.com/backdrop/backdrop-issues/issues/1042#issuecomment-246280693

---

~~PR by @jenlampton: https://github.com/backdrop/backdrop/pull/1544~~
PR by @klonos: https://github.com/backdrop/backdrop/pull/2729 (excludes `system.admin.inc`, which is done in #3855 / https://github.com/backdrop/backdrop/pull/2728)

**Comment by jenlampton** [comment]
Initial PR changes only the Site information form.

**Comment by klonos** [comment]
> That, however, will be a lot of work.

Oooor... some search & replace 😄 ...lets see what the test bot things about that.

**Comment by klonos** [comment]
> ...lets see what the test bot things about that.

Only 1 test failure is not bad for a 46-file PR 😅 ...but as I said, it was mostly string changes. The remaining failure seems to be because of #3794 (although not 100% sure).

**Comment by klonos** [comment]
...I have closed and reopened the PR, and this time all tests passed.

**Comment by herbdool** [comment]
> I think that we should leave `<front>` placeholder and 'site_frontpage' in system.core config for separate PRs.

I don't think we can change those at all without potentially breaking lots of sites.

**Comment by jenlampton** [comment]
We can't change <front>, and we should keep it for bc, but we can change
the UI so nobody needs to see it. A checkbox/radio/drop-down would be
better everywhere it's used. See how we changed the block title settings
(to remove <none>) as an example.

**Comment by BWPanda** [comment]
I tested the PR via the sandbox site, and all looks good. I marked off the checkboxes above that were covered by this PR. I crossed off the `site_frontpage` config one since that's not possible, and left the `<front>` one unchecked as I believe that deserves its own issue.

Browsed the code in the PR and that looks good too.
RTBC from me.

**Comment by jenlampton** [comment]
Why is site_frontpage not possible? It's just an update hook, isn't it?

**Comment by klonos** [comment]
@jenlampton this may be used in contrib and custom code. Perhaps if they used `backdrop_is_front_page()` instead, then this wouldn't be an issue. Can we do a grep across all config, to get an idea? That should give us more confidence.

**Comment by quicksketch** [comment]
Well I haven't heard any opposition to the proposal, but I feel like it should probably be rationalized regardless:

- Is Home page more common than Front page?
- What popular platforms or sites use which terminology?
- Is it worth the incurred cost/debt of having mixed terminology where our API uses "front" but the UI uses "home"?

**Comment by indigoxela** [comment]
Hm. Actually "Home page" seems worse to me that "Front page".
"homepage" is often used as synonym for "the whole site". So "Front page" is no drupalism IMO.

See this [Wikipedia disambiguation](https://en.wikipedia.org/wiki/Home_page_(disambiguation))

Especially in German "Homepage" is used for the complete websites. I don't know how other languages use it.

Also, changing 46 files in core to create more ambiguity... really?

**Comment by BWPanda** [comment]
As far as Wordpress goes, at least from developer's standpoint, 'front' refers to the actual frontpage (whatever you set it to), while 'home' refers to the blog page (i.e. the list of blog posts which is set as the frontpage by default). Source: https://wordpress.stackexchange.com/a/30389
My personal guess is that in time their `is_home()` function will be deprecated or renamed.

I'm happy to keep Backdrop using the term 'front' page, as long as we're consistent and don't use 'home' page as well.

**Comment by klonos** [comment]
At the time of writing https://www.google.com/search?q=home+page returns 17,670,000,000 results, while https://www.google.com/search?q=front+page returns 4,160,000,000 results.

Aslo, https://en.wikipedia.org/wiki/Home_page mentions:

> A home page (also written as homepage) is the main web page of a website.

...while https://en.wikipedia.org/wiki/Front_page does not have any direct reference to anything related to web besides a link to https://en.wikipedia.org/wiki/Home_page_(disambiguation) at the very end of the long list of references. Following that link, you get this definition:

> Home page is a generic term for website's front page.

https://www.google.com/search?q=define+home+page

> 1. the introductory page of a website, typically serving as a table of contents for the site.
> 2. a web page set as the default or start-up page on a browser.

https://www.google.com/search?q=define+front+page

> the first page of a newspaper, containing the most important or remarkable news of the day.

Hope all this helps make a decision.

**Comment by findlabnet** [comment]
>Also, changing 46 files in core to create more ambiguity... really?

IMHO, it happens often recently - so much wasted efforts which could be used for some real improvements instead.

**Comment by BWPanda** [comment]
![image](https://user-images.githubusercontent.com/2385329/92726761-753e4e80-f3b1-11ea-96e4-3788c79cb200.png)

https://trends.google.com/trends/explore?date=today%205-y&q=homepage,%22home%20page%22,frontpage,%22front%20page%22

**Comment by herbdool** [comment]
Seems like people are re-litigating what was already decided. The UI was already changed from "front" to "home" in previous PRs. I personally didn't think it mattered but too late to change now. From what I can tell @BWPanda reviewed and approved this PR https://github.com/backdrop/backdrop/pull/2729 by @klonos. That PR seems to only change code comments and a handful of other references. Seems okay to me since we're already down that path. So long as we keep BC as others have noted.

**Comment by indigoxela** [comment]
One important note that native English people tend to miss: this needs *a lot* of translation updates necessary, which is sort of frustrating for translators.

**Comment by herbdool** [comment]
@indigoxela that's an important point. Especially given that there aren't a lot of volunteers translating Backdrop yet.

**Comment by BWPanda** [comment]
Taking off the RTBC label until we get concensus whether we'll be committing this or not.

**Comment by stpaultim** [comment]
> Seems like people are re-litigating what was already decided

I don't feel very strongly about this change. However, I agree with @herbdool and the observation that this decision seems to have been made. We already use the term "home" in most places in the UI. This PR seems to be mostly updating code comments and code to reflect this (although it does make some user facing changes). 

Are those objecting to this PR suggesting 

1) That we should change much of the UI BACK to using "Front" instead of "Home"
or
2) That we should stick with the current mix of "front" and "home." 
or 
3) Something else?

It seems to me that at this point, it is probably best to follow through and complete a change that seems like it has been happening for a while.

![home-vs-front-3](https://user-images.githubusercontent.com/3144571/103182849-348d1700-4874-11eb-88b2-59d6581b4cf7.png)
![home-vs-front-2](https://user-images.githubusercontent.com/3144571/103182851-3525ad80-4874-11eb-9e87-ec13b9d9f9f1.png)
![home-vs-front-1](https://user-images.githubusercontent.com/3144571/103182852-35be4400-4874-11eb-8d8f-b5b8c906805e.png)

**Comment by olafgrabienski** [comment]
> I understand the concern about translations, but isn't a bit late to be holding this up because of that?

Added the `needs - translation update` label now (might not have been available at issue opening). I see this label as a reminder to put the question if changing a language string is important enough to trigger the need of translation updates. In *my* opinion, this one is important enough.

**Comment by stpaultim** [comment]
> I see this label as a reminder to put the question if changing a language string is important enough to trigger the need of translation updates. In my opinion, this one is important enough.

Thanks, I think this is helpful. But, what does this mean practically for this issue? 

Has there been any changes from "front" to "home" already that have effected translations OR is this the first PR that requires a change to translations. I suppose I understand the very real concerns about translations, but what I don't yet understand is the implication for this issue (which seems like it is part of a larger change that has been happening for a while). 

Does this just mean that we need to make sure that all translations are updated before we make this change to core? Would moving back to "front" be less work on the translation front?

**Comment by jenlampton** [comment]
> Has there been any changes from "front" to "home" already that have effected translations

Since we already have instances of both "Front" and "Home" in core, there should already be translations for both those words. The real issue would be for the supportive text, where the word appears in the middle of a sentence. In those cases the whole sentence would not translate anymore, since we changed the string it was matching against.

> is this the first PR that requires a change to translations. 

When we added the home page layout, it was necessary to add new translations for "Home page". 

> Does this just mean that we need to make sure that all translations are updated before we make this change to core?

It happens the other way around, after we update core, we will need to update translations to match the new string included in core (we don't want to do it before the change is in, in case the string changes again)

> Would moving back to "front" be less work on the translation front?

Probably not, since we've already started making this change.

**Comment by olafgrabienski** [comment]
Thanks for answering the questions, @jenlampton!

> where the word appears in (...) a sentence. In those cases the whole sentence would not translate anymore, since we changed the string it was matching against.

FYI a few examples (for a more complete list [search on the translation server](https://localize.backdropcms.org/translate/languages/de/translate?project=backdropcms&status=0&release=41&search=front%20page)):

- Is this the front page.
- The front page
- Any page except the front page
- Is not the front page
- Is the front page

**Comment by stpaultim** [comment]
This issue was RTBC, but some people have raised concerns, which seem to be blocking this issue right now. It seems to me that there are three paths forward (as I described before). 

1) Leave things as they are with inconsistent use of of the terminology for front / home page
2) Reverse previous changes to the UI and consistently use the term front page (instead of home page)
3) Proceed with this PR to consistently use the term home page (instead of front page). 

It seems to me that current concerns about option #3 risk leaving us with option #1, which I think is the worst possible choice. While, I support this change to home page, I would rather revert to using front page over the status quo. 

I think it would be helpful if those who have raised objections to this PR are clear about their preferred path forward. @indigoxela and @BWPanda have both expressed concerns, but it's not clear to me if the intend is to simply encourage us to be cautious about these kinds of changes in the future with translation implications, stick with the status quo, or to revert previous changes from front page to home page?

**Comment by BWPanda** [comment]
I've never opposed this PR/issue. I re-read my comments above, and the point I was making was that I prefer consistency (i.e. everything being the same) over the current situation where we use both words in different places.

So I'm ok with this moving forward as 'home page' (option 3 from @stpaultim's comment above) (since that seems to be the most popular term, based on the Google Trends screenshot above). Failing that, I'm happy to move everything to 'front page' (option 2 from @stpaultim's comment). What I don't want is the current situation to remain (option 1).

**Comment by indigoxela** [comment]
@stpaultim I never understood the need for the renaming, but silently accepted that it will happen anyway. My concerns were about all the required translation changes, but I also accepted that these will happen. So I'm not blocking this issue in any way, I just don't put any effort in getting it done - which isn't quite the same as blocking. :wink:

**Comment by stpaultim** [comment]
Sorry for the misunderstanding @BWPanda, glad to clear that up. Thanks for the clarification @indigoxela.

This issue has never been a priority for me, but I don't like the state we are in now and think it's a good idea to finish what we have started (to the extent that we are able). I am also interested in this issue, because we have other technical and/or documentation issues that would benefit from resolving this issue. 

I very much understand the concern about translations and encourage us to be careful about making text changes that effect translations (certainly to keep the issue of translations in mind). Unfortunately, I don't work with translations enough that I think about this issue as much as I should. I'll try to pay more attention to how changes in core terminology effect translations in the future. 

It seems to me that we have pretty good consensus that the current state is the least optimal option (between going back to front, status quo, or moving forward with home page). While not everyone is convinced of the need for this change, I am not aware of anyone that outright objects to this change at this point. 

Since this had the RTBC label and it was removed due to a lack of consensus AND because it seems to me that we have at least some consensus that moving forward is better than doing nothing, I'm going to give it the RTBC label again and see if we can get this issue moving and resolved.

**Comment by BWPanda** [comment]
As a core committer, if I see an issue with a label 'RTBC' then I think, "Ooh, I can merge something!" But in September I came here and saw the back-and-forth comments and so decided to remove the RTBC label just to give people a chance to discuss and come to a decision before a core committer went ahead a merged it.

Based on the discussion/comments since then, I feel @stpaultim has done the right thing by adding RTBC back and that we can commit this and standardise the terminology we use for the home/front page. I'll merge this PR next week unless someone else beats me to it.

**Comment by stpaultim** [comment]
@BWPanda - For the record, I think you made the right call to remove the RTBC label at the time. Hopefully we've moved on since then. If not, we'll find out in the next few days. ;-)

**Comment by philsward** [comment]
+1 to get it done.

**Comment by BWPanda** [comment]
Thanks @klonos for the PR, and @jenlampton for opening this issue originally. Thanks also to everyone who participated in the discussion. I've merged https://github.com/backdrop/backdrop/pull/2729 into 1.x and 1.17.x.
