### ISSUE TITLE
[UX] Change 'Submitted by' to 'Posted by'

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2184]
The language for the submitted text has always baffled me.  Why submitted? Can we change this to 'Posted by'? (Is that what Wordpress uses?)

---

PR: https://github.com/backdrop/backdrop/pull/2740

**Comment by BWPanda** [comment]
It appears WP doesn't use any explanation text, just displays the date and username:

![image](https://user-images.githubusercontent.com/2385329/59555189-6ce14300-8fb7-11e9-9884-7d0d1a33af3a.png)
https://s1.demo.opensourcecms.com/wordpress/2019/06/15/this-is-a-title/

We currently have: `Submitted by !username on !datetime`
@jenlampton's suggesting: `Posted by !username on !datetime`
And WordPress uses: `!datetime by !username`

Be good to hear feedback from some more people.

**Comment by BWPanda** [comment]
As for me, I can see @jenlampton's dislike/confusion with the word 'submitted', and I do think 'posted' makes more sense, so I'd be happy to see the default text changed to that.

**Comment by jenlampton** [comment]
I'm also fine with copying WP :)

**Comment by olafgrabienski** [comment]
I like the WP format `!datetime by !username` because it's more neutral, not emphasizing the action of posting but the factual information.

Actually, I'd prefer just `!datetime !username`, without any preposition. Not sure, if we'd need a delimiter then, like a comma or a `&middot;`.

Or, if all three elements including the `by` could be wrapped in separate `span` elements with suitable CSS classes, this would allow to get rid of the default preposition and to add a custom preposition or a delimiter via CSS content.

**Comment by klonos** [comment]
I think that when this issue was originally posted, we may have been referring to the respective checkbox in the content type "Display options" as `Submitted by` (label or help text). This is not the case now, so all good on that front 👍

I also agree that `submitted by` is kinda "icky". So I vote for `!datetime by !username`.

> ...all three elements including the `by` could be wrapped in separate `span` elements with suitable CSS classes, this would allow to get rid of the default preposition and to add a custom preposition or a delimiter via CSS content.

Although this seems like a good solution, if we wrapped everything in span tags, it would make translations of this string harder. Moreover, I think that this is a problem to be solved by #2379, where power to customise this is given to the site builder instead of requiring code/CSS changes. Same kind of flexibility we have introduced in #3753 for the dblog date format.

**Comment by BWPanda** [comment]
Made a PR based on the current feedback: https://github.com/backdrop/backdrop/pull/2740

**Comment by klonos** [comment]
PR looking good @BWPanda, but can we change instances of "submitted" and "post information" etc. within inline comments and description/help text to either "author and date information" or "author username and publish date"? ...this is what we are using in `/admin/structure/types/manage/[content_type]/configure#edit-node-submitted`

**Comment by olafgrabienski** [comment]
Works for me in the sandbox!

**Comment by BWPanda** [comment]
@klonos I've updated the PR with changes as suggested. Please let me know if there's anywhere else you think I should change the wording.

**Comment by klonos** [comment]
RTBC 👍 ...added the bug milestone label; feel free to remove the label and add the milestone 😉

**Comment by quicksketch** [comment]
Looks great! As a front-end UI change I've merged this in for 1.14.0 only.
