### ISSUE TITLE
Fix for egg-shaped notification icon reverted in Basis

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2192]
see 
![screen shot 2016-09-15 at 1 04 15 pm](https://cloud.githubusercontent.com/assets/397895/18565532/eec81c52-7b44-11e6-81ae-15c8a6ede86e.png)

**Comment by jenlampton** [comment]
The problem is this: 

```
* {
  box-sizing: border-box;
}
```

It seems to me this is way too general. Border box is great, but do we really want everything on the whole site using it?  It breaks our admin bar here, and it's also likely to break a ton of contrib.

**Comment by quicksketch** [comment]
This has been fixed in https://github.com/backdrop/backdrop/pull/1562 by adding `box-sizing: content-box` back using `admin_bar.css`. So the immediate problem at hand is resolved. We can keep discussing flipping the default here if needed.

**Comment by jenlampton** [comment]
I think fixing core and breaking who-knows-how-much of contrib is not the right solution. We should have less brittle CSS in basis.

**Comment by quicksketch** [comment]
I would propose that if your contrib module is dependent upon padding and width in combination and not specifying the `box-sizing`, it's the contrib module CSS that is brittle, assuming it's parent is going to `box-sizing: content-box` because it's the browser default. It would be the same as assuming any other browser-default style, which you can basically never do.

As existing sites aren't going to be broken (they'll keep using Bartik or whatever else theme they have), it could be fine for contrib to adjust to the styling of Basis. If they have specifically styled themselves for the out-of-box theme, they will have other issues besides just this one. Contrib needs to be robust about its CSS, as Basis isn't going to be the only theme that does this or other styles that may override the browser defaults.

**Comment by jenlampton** [comment]
>  It would be the same as assuming any other browser-default style, which you can basically never do.

You are asking all contrib to add `box-sizing: content-box` to everything they need margin/padding on. I've built a lot of themes, and a lot of modules that provide CSS, and I've *never* added that. This would be asking a lot: for a contrib to need to update most of it's CSS, just to make their projects (which previously worked) work again, in what will be the default Backdrop theme.

**Comment by jenlampton** [comment]
I'm being convinced...  Closing this issue to fight other more important battles.
