### ISSUE TITLE
Change CSS file names in basis to exclude 'l-'.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2195]
In Basis there is a css file `l-header.css` and a bunch of selectors within that target elements in the header.  In general, a theme shouldn't target a layout selector. `.l-header` is for layout/positioning only (and layout/positioning CSS should be left to the layout selected). This is important for the separation of layout + design. Can we instead inject a class of our own, and target that instead?

---
PR https://github.com/backdrop/backdrop/pull/1568

**Comment by jenlampton** [comment]
Okay, now that I look at the CSS for this more closely, I may be mistaken. It's the other way around!  It's layout projects that should **only** target l-classes, not theme projects that should **never** target l-classes. So, I'm fine with the CSS in basis as-is, I just really dislike these filenames :)

**Comment by quicksketch** [comment]
> I do dislike the names of the files starting with the l- though. Can we change that?

I would also be in favor of dropping the `l-` filename prefix. I thought that it might make sense if everything inside of those files were *all* prefixed with `.l-header`, that is, the file contained nothing but the header region styling, but as it contains styling for both the header region and the header block, I think switching to just `header.css` makes sense.

`l-footer.css` actually does what I would expect, with the exception of `.drop-lounging` class. But I think `l-footer.css` is going to just cause head scratching rather than help set a pattern; A pattern that might not actually be working well in the first place.

So +1 for dropping `l-` from filenames from me, but leaving the styles within them the same.

**Comment by quicksketch** [comment]
I've merged in https://github.com/backdrop/backdrop/pull/1568 to remove the `l-` prefix.
