### ISSUE TITLE
Make Breadcrumb design more subtle

### ISSUE THREAD

**Issue by wesruv** [backdrop/backdrop-issues#2246]
They're a tertiary element on the page but we're giving them a lot of visual dominance.

**Comment by wesruv** [comment]
![image](https://cloud.githubusercontent.com/assets/5607236/18976732/2ddf0584-8682-11e6-9d43-8b572b32cdec.png)

PR Here: https://github.com/backdrop/backdrop/pull/1592

**Comment by jenlampton** [comment]
Hm, I like that these are less dominant. but I don't think they read as breadcrumby as they did before this change (here's a before screenshot, for comparison).

![screen shot 2016-09-29 at 5 25 49 pm](https://cloud.githubusercontent.com/assets/397895/18976807/d57fae74-8669-11e6-8ae7-fcfaddedbc6f.png)

Trying to think what it is...  I think with the dark background the arrow thingies worked nicely with the border of the box. Now with no box, they seem a bit out of place, maybe?

**Comment by wesruv** [comment]
@jenlampton 
![image](https://cloud.githubusercontent.com/assets/5607236/18976872/7c9f9070-8683-11e6-83f4-280b4f04a575.png)

**Comment by jenlampton** [comment]
Here's a stab at leaving the box but making it light instead of dark. (inverting the colors in skin.css)
![screen shot 2016-09-29 at 5 31 00 pm](https://cloud.githubusercontent.com/assets/397895/18976897/9e9aeada-866a-11e6-9515-6bd36405bbc1.png)

**Comment by wesruv** [comment]
I tried a bunch of things, none of them worked, only thing I changed from yours is I thought the arrow was a bit too hard to read, so I beefed it up by 1px:
![image](https://cloud.githubusercontent.com/assets/5607236/18976993/a5727340-8684-11e6-8632-e5fc5509931d.png)

**Comment by jenlampton** [comment]
I think this is much better :) but now with how pretty the tabs & crumbs are, I really dislike those pills...

**Comment by quicksketch** [comment]
When the breadcrumb is in the header, the light background doesn't work so well. Should we address what happens when in the header (as when using Basis as the admin theme)?

![screenshot from 2016-09-29 19-20-11](https://cloud.githubusercontent.com/assets/100206/18978683/efa4e408-8679-11e6-9c25-15b6a50d8a68.png)

**Comment by quicksketch** [comment]
Well, we can handle that in a follow-up. I've merged https://github.com/backdrop/backdrop/pull/1592 for 1.5.1. Thanks!

**Comment by klonos** [comment]
Talking about things we don't like about the breadcrumb in Basis:

1. Please don't get me wrong. The breadcrumb looks OK when there are multiple crumbs, but here's how it currently looks when there is only one crumb and no secondary tabs (that's my 1.5.0 local with the primary tabs visible since I'm logged in):

 ![backdrop-basis-breadcrumb-only_one_crumb](https://cloud.githubusercontent.com/assets/2423362/18978463/cbe13ebc-8706-11e6-8519-888b7f3544df.png)

 (notice how the eye needs to move up and down to follow the trail)

 ...and here's how it looks in the PR sandbox (not logged in, so no primary tabs):

 ![backdrop-basis-breadcrumb-only_one_crumb-pr1592-not_logged_in](https://cloud.githubusercontent.com/assets/2423362/18977497/23a79e6a-86fe-11e6-9be3-0ab5dee2b130.png)

 The PR is better (less visual emphasis), but still not that great IMO. It's just a horizontal bar across the screen that draws unnecessary attention. Which brings me to...

2. In my head, I want the combination of breadcrumb > page title > primary tabs > secondary tabs to be a visual trail of where I am at. The way we have it now, it is page title > primary tabs > secondary tabs > breadcrumb. I don't think that this works that well. The breadcrumb should not come between the title/tabs section and content if you ask me.

 ...we are doing it so much better in the admin layout:

 ![backdrop-admin_layout-breadcrumb_trail_flow](https://cloud.githubusercontent.com/assets/2423362/18978515/1fb8fa20-8707-11e6-8323-64318d45f965.png)

 You can see that clearly if you switch using Basis as the admin theme:

 ![backdrop-admin_layout-breadcrumb_trail_flow-basis_as_admin_theme](https://cloud.githubusercontent.com/assets/2423362/18978558/5c09736a-8707-11e6-87c7-5b3f157590f5.png)

 I'm not saying that the breadcrumb belongs in the header, but it needs to be coming **before** the page title. Unfortunately, the page title pseudo-region (actually a pseudo-block) cannot be moved around (#933).

**Comment by jenlampton** [comment]
It can if we override the template files in the theme :) just throwing that
out there...

**Comment by olafgrabienski** [comment]
> The breadcrumb looks OK when there are multiple crumbs, but here's how it currently looks when there is only one crumb ...

In my opinion, the situation when there is only one crumb, is even misleading. Unless you have a more nested page structure on a website, the breadcrumb looks like there is just another "Home" link on the page. Adding the current page as an unlinked crumb would improve the situation a lot.

This (as the position of the breadcrumb) seems to be theme agnostic though. Structurally, you get the same result in Bartik at least.

@klonos - I'm very interested in better breadcrumbs as well. As the original issue has been fixed, would you open another one to move the discussion there?

**Comment by wesruv** [comment]
Made new issue ^

**Comment by klonos** [comment]
Thanx @wesruv 👍 ...lets close this one then.
