### ISSUE TITLE
Make default hero in Basis a repeating image

### ISSUE THREAD

**Issue by wesruv** [backdrop/backdrop-issues#2249]
![image](https://cloud.githubusercontent.com/assets/5607236/18979640/cfd61c52-869a-11e6-803b-8f17bbbe4c1c.png)

Oops, decided to put this off when I originally made the image and forgot to come back to it 😝

**Comment by olafgrabienski** [comment]
@wesruv - Inspecting the block with Chrome Dev tools, I found out that are two definitions regarding the default image:

**core/themes/basis/css/skin.css**
```
/* Default background when hero doesn't have image */
.block-hero-no-image {
  background-color: #0074bd;
  background-image: url(../images/texture.png);
  background-repeat: no-repeat;
  background-position: center center;
  background-blend-mode: luminosity; /* Colorizes bg image */
}
```

**core/themes/basis/css/component/hero.css**
```
.block-hero-no-image {
  background: #0074bd url(/core/themes/basis/images/texture.png) no-repeat center center;
  background-blend-mode: luminosity;
}
```

Don't know if having two definitions is related to this issue, I noticed a strange thing though: When I disabled the background definition of the latter in Chrome Dev tools, the image looked just fine! Really strange, but however not happening in Firebug.

**Comment by wesruv** [comment]
Yea, it's intentionally defined twice, component.css is the defaults and skin.css is meant to be overridden and customized. All of the color/aesthetic styles are duplicated in skin.css without the structural styles.

I wanted to make the image so it tiled well, have a PR for it here:  
https://github.com/backdrop/backdrop/pull/1687

**Comment by wesruv** [comment]
![image](https://cloud.githubusercontent.com/assets/5607236/21443166/fe185e5a-c870-11e6-852d-49ed06f81207.png)

**Comment by klonos** [comment]
Sorry for chiming in late, but although a repeating image may work well with patterns, not sure how it will look with actual images.

**Comment by olafgrabienski** [comment]
I just tested the PR, and interestingly the image is full width on a approx. 1900px screen anyway, no matter what value is used in `background-repeat`. I tried to override it with `no-repeat` in Chrome dev tools and Firebug, and in both cases the image remained full width. Strange things happen. (Saw that there is a new image file in the PR, maybe releated?)

**Comment by quicksketch** [comment]
> Don't know if having two definitions is related to this issue, I noticed a strange thing though: When I disabled the background definition of the latter in Chrome Dev tools, the image looked just fine!

Yeah, I found the same thing. It's because the later definition (in hero.css) uses a single `background` property, which overrides the `background-size` property provided by `.block-hero`. I don't think this is intentional, it appears that if you upload an image, the `background-size: cover` will be present, but if you leave the default, `background-size` gets wiped out. I'll file a PR that fixes this accidental overriding of the background-size property.

**Comment by quicksketch** [comment]
PR filed at https://github.com/backdrop/backdrop/pull/1703.

So once background-size is not overridden, we don't really need a repeating background image at all, because the existing image will be stretched to fit (as it would if an image were uploaded).

I'm still open to replacing the image if we think the new one is better, or if it were actually intentional that we would repeat the default but stretch uploaded images. But from the looks of things, it appears this was more of an accident than intentional that `background-size` was getting wiped out when using the default image.

**Comment by quicksketch** [comment]
I've merged in https://github.com/backdrop/backdrop/pull/1703. @wesruv if I've misunderstood, please reopen and we can switch to a repeating image instead.

**Comment by wesruv** [comment]
Oh oh, I see! I can adjust my PR to fix the issues that were noticed in this issue.

**Comment by wesruv** [comment]
Ok, just now catching up.

When I first made this I held off on spending the time to make the texture repeat, because I didn't know if people would like it. I left it 'broken' so I'd remember to make tile, but then forgot 😞 

So this was the intention the whole time, and I don't want to stretch the texture, especially since I already did the work to make it tile.

Stretching the user uploaded image just because it's the sane-est default considering not every one of our users will know how to make an image that fits, or can make an image tile. If they do they probably know CSS 😛 

I rebased and recreated my PR here, it is the correct way to handle the bg texture:
https://github.com/backdrop/backdrop/pull/1709/files

**Comment by quicksketch** [comment]
Okay coolio. The new PR at https://github.com/backdrop/backdrop/pull/1709 behaves like I would expect and matches the original intention: that user-uploaded files will stretch but the default one will repeat.

Merged into 1.x and 1.5.x.
