### ISSUE TITLE
Make menu items translatable in core

### ISSUE THREAD

**Issue by kriboogh** [backdrop/backdrop-issues#225]
Just installed backdrop to see where you guys are heading and if there is something I can participate at. I noticed there's a couple of ideas on improving the multilingual experience (like the translate english feature, thank you!).

Is there any development track being planned about in-core translation possibilities for menus, vocabularies/taxonomy terms, blocks and other stuff I might be missing, so we wouldn't need i18n modules but have it directly in core?

Specific for menu's, what would be needed on a database level so that menus are translatable (edit: i did just see title and description are currently translatable through the t function) and you can have a different set of items per language. On a admin UI level, the way I would see it is we foresee a translate tab for the menu item edit page and the list items page of that menu item would have tabs for each language, where each tab lists the items for the specific language (number of items can be different for each language).
When attaching content to a menu (on its edit page) you select the menu item in the dropdown and the item is added to the item list of the menu based on the language of the content.

Also, would it be a good idea to make better use of the 'context' for translations. For example, the titles and descriptions of menu could be given a context 'menu' for the t() function. This is not just for menu but t() usage in general.

Food for thought?

---

~~PR by @kriboogh: https://github.com/backdrop/backdrop/pull/1093~~
PR by @quicksketch: https://github.com/backdrop/backdrop/pull/2054

**Comment by kriboogh** [comment]
@quicksketch Just updated the code so it works again with 1.2.x

**Comment by kriboogh** [comment]
couple of screenshots
![screen shot 2015-09-23 at 17 08 49 2](https://cloud.githubusercontent.com/assets/1898759/10049160/963e2434-6216-11e5-855c-968c41a1582d.png)
![screen shot 2015-09-23 at 17 13 08 2](https://cloud.githubusercontent.com/assets/1898759/10049150/8c941600-6216-11e5-8c63-d5dbd223e9f3.png)
![screen shot 2015-09-23 at 17 15 45](https://cloud.githubusercontent.com/assets/1898759/10049212/c8b809ac-6216-11e5-964b-23fad62b0071.png)

**Comment by quicksketch** [comment]
Awesome @kriboogh! Could you file a pull request so this shows up in the list of things for review?

From the looks of the screenshots, I'm a little confused by some of the options. I'm guessing this comes from the i18n module, but I think we may be able to clean things up a bit for Backdrop.

In particular, I'm not sure that we need both `Enabled` and `Enabled, with translation`. From the sounds of things `Enabled, with translation` only hides the entire menu based on language. Is that correct? In Backdrop-land, menus are displayed via a block. So if you wanted to show a menu only in a particular language, then you could add that block to the page and then add a condition that it only be shown if the current language were the same as that menu's language.

I'm also a little perplexed here because these don't really seem like "translatable" menu items so much as "language-aware" menu items. If a menu item were translatable, I would expect to have a single link with a "Translate" option in addition to "Edit", in which I could enter in the translations for a link, rather than having every link be entirely separate and displayed all in one long list.

**Comment by kriboogh** [comment]
Yeah, i basically tried to mimic the i18n flow.

The idea behind the two options is this:

Enabled: 
The menu can be attached to a specific language, all items you create within this menu are automatically set to this language. The menu, if placed on a page, will only be shown when the current language is the language of the menu. 
OR 
You can leave the language of the item to be undefined, so it will show up on the page regardless of the current language, only the items within this menu can be defined to be of a specific language. and then create menu items for each language. So for example you define a menu "Navigation", enable multilingual without a specific language. Create 3 menu items "Item (EN)", "Item (FR)", "Item (UND)".  Now when the "Navigation" menu is shown, using English, only the "Item (EN)" and "Item (UND)" will be visible.

Enabled, with translation:
With this option you can create translation sets for menus. What this means is, when you have a menu "Navigation", enabling multiligual with translation, you have to chose a specific language for it. All items created in this menu are now created with this language. You will also get an extra tab "Translate" when managing the menu. Here you need to select a different menu for each language. So if you have english and french you would have a 2 different menu's "Navigation (EN)" and "Navigation (FR)" which are linked together. This way when you put the "Navigation (EN)" in a block to display a menu in a page, and switch to french, it will automatically display the "Navigation (FR)" menu.

**Comment by klonos** [comment]
I would love to see this in 1.4.

**Comment by klonos** [comment]
> In particular, I'm not sure that we need both `Enabled` and `Enabled, with translation`. From the sounds of things `Enabled, with translation` only hides the entire menu based on language. Is that correct? In Backdrop-land, menus are displayed via a block. So if you wanted to show a menu only in a particular language, then you could add that block to the page and then add a condition that it only be shown if the current language were the same as that menu's language.

@quicksketch I think we should have it the other way because in cases with say 10 languages, people would end up with 10 different menu blocks to manage **in every layout**. I think that we should have one single menu block per menu and have it be language aware.

**Comment by klonos** [comment]
...I mean, consider the horrible UX because of the amount of clicks when having to add 10 different menu blocks (one per language) plus to set their visibility conditions vs having to add a single menu block that automagically adapts to the site language.

**Comment by bd0bd** [comment]
One menu should be enough for 10 and more languages.
In the CMS I use I do not need to add any additional menus.
I simply switch website to necessary language and edit menu items which have only ID #-s.
![menu](https://cloud.githubusercontent.com/assets/13515302/13093818/110bf0bc-d529-11e5-98b3-3b5b5aa7f4f1.png)

**Comment by quicksketch** [comment]
Yeah, thanks for the feedback @bd0bd and @klonos. I agree that having 10 blocks for 10 languages isn't where we want to be. From @kriboogh's description in https://github.com/backdrop/backdrop-issues/issues/225#issuecomment-142856839, it sounds like I got the difference between "Enabled" and "Enabled, with translation" backwards. "Enabled, with translation" enables what I would expect (more or less) where the menu items for a particular language are all displayed together and you translate the entire menu for each language separately.

What do you guys think about the "Enabled" use-case then?

> The menu can be attached to a specific language, all items you create within this menu are automatically set to this language. The menu, if placed on a page, will only be shown when the current language is the language of the menu.
> OR
> You can leave the language of the menu to be undefined, so it will show up on the page regardless of the current language, only, the items within this menu can be defined to be of a specific language. Then create menu items for each language. So for example you define a menu "Navigation", enable multilingual without a specific language. Create 3 menu items "Item (EN)", "Item (FR)", "Item (UND)". Now when the "Navigation" menu is shown on a page in English, only the "Item (EN)" and "Item (UND)" will be visible.

The first way could be emulated if desired using separate blocks and language conditions (as painful as it might be, it could make sense for something like a language-specific menu that doesn't have any translated equivalents).

I find the second way of handling menus to be confusing, (where the menu language is undefined). I wouldn't expect to have menu items of multiple languages all mixed together in a single list while administering the menu. That really creates a disconnect between what the administrator sees and what will actually be displayed on the front-end. Not to mention the concept of "Undefined" language menu items showing up in every is puzzling. I suppose you might have an icon for "Home" or something, but even then, you'd want to translate the underlying alt/title text for accessibility (screen-readers, etc.)

**Comment by quicksketch** [comment]
I just reviewed https://github.com/backdrop/backdrop-issues/issues/2907, which is a very small step towards total menu item translation ability, and so I'm revisiting this now.

I'm still against the multiple options for translating a menu: I think they are confusing and provide too many ways to accomplish what should be simple. But my suggestion above gets into functionality that does not exist in Backdrop (having the ability to translate individual menu items, rather than having separate menu items that just have different languages). So instead of reworking in a way that requires API changes, here is a proposal that accomplishes menu item translations with minimal work:

- When creating menu items, if Language module is enabled each menu item allows the assigning of a language for that individual menu item.
- The menus themselves would not have any language settings. No default language, "no Enabled" vs. "Enabled, with translation".
- Administering a menu would have a select list at the top, allowing you to filter the menu by a particular language.
- Creating a new menu item would default to the language that the menu is currently filtered by in the admin UI.
- Undefined language menu items continue to show up in all languages (current behavior).
- Menu items that have a language defined only show up when the interface language matches the menu item language (current behavior).

This approach limits the ways a menu can be configured, keeping it simple to set up and consistent. I don't think it would require any API changes or additions at all. It would be purely a UI enhancement, since menu links already have the ability to map to a language.

If some sites need the ability to have menus tied to a particular language and manage each menu independently, with automatic showing or hiding the entire menu based on site language, that could be provided via a contrib module. Then core would provide out-of-box functionality for translating **menu items**, and leave more complex alternatives involving language at the **menu** level to contrib.

**Comment by quicksketch** [comment]
I've filed a PR at https://github.com/backdrop/backdrop/pull/2054 that takes @kriboogh's "Multilingual: Enabled" approach and pares it down to just include that method. With fewer options, it makes for a smaller diff: 15KB vs. 45KB.

**Comment by herbdool** [comment]
I've tested @quicksketch's PR and it works as expected. Great work on providing a simplified solution in core! I agree on leaving more complicated solutions for contrib. I18n in D7 always confused me to some extent no matter how many times I install it.

**Comment by olafgrabienski** [comment]
I've also tested the PR (in the sandbox site), nearly all parts work good so far, and I like the simple approach!

(@quicksketch, you mentioned the API change, I'm not sure what it means. To which type of Backdrop release could the current PR be applied?)

Back to testing: Amongst other things, I added menu items during content creation. As recently suggested in #2907, with this PR menu items get the same language as the content, very nice!

Regarding language functionality at the menu level I agree with the suggestion to leave it for contrib, but with one exception: Translation of the menu title should be provided by core in my opinion. (We could however add this functionality later.)

I noticed one (usability) issue, regarding the *Manage menu* page: No matter in which language I add a menu item, after saving it, the page shows only English items. So, when I add a non English item, I don't see it in the menu list before switching the filter (again) to the respective language or to "All languages". I'd suggest to not show English but "All languages" by default. (What do you think: remove RTBC because of this issue?)

**Comment by quicksketch** [comment]
> Translation of the menu title should be provided by core in my opinion. (We could however add this functionality later.)

Agreed, the menu title should be translatable. Because the menu configuration itself is a config file, Menu title translation would be part of Config Translation (#704). In the mean time you can already translate menu titles using the Locale interface.

> No matter in which language I add a menu item, after saving it, the page shows only English items. So, when I add a non English item, I don't see it in the menu list before switching the filter (again) to the respective language or to "All languages". I'd suggest to not show English but "All languages" by default. 

Good point. I think we go back to the menu listing page and make sure the items shown match whatever setting was just used to add the new menu items. I'll update the PR.

> you mentioned the API change, I'm not sure what it means. To which type of Backdrop release could the current PR be applied?

It means this will have to wait until 1.10 unfortunately, as we're after feature freeze. API change or not, this would be inappropriate to include in a bugfix release, as it's clearly new functionality.

**Comment by olafgrabienski** [comment]
> In the mean time you can already translate menu titles using the Locale interface.

Is that supposed to also work with custom menus, or only with the ones provided by core?

> I think we go back to the menu listing page and make sure the items shown match whatever setting was just used to add the new menu items.

Sounds good!

> this will have to wait until 1.10 unfortunately, as we're after feature freeze.

I see! And I think, 1.10 will be a release with some more great multilanguage improvements.

**Comment by olafgrabienski** [comment]
Changed milestone to 1.10 and PR status to "needs work" (make sure that menu items shown after saving a new item match the setting that was used to add the new item)

**Comment by bjoern-st** [comment]
@quicksketch 
Sorry, it might be a little bit late, but perhaps you might want to have a look at my little project
https://github.com/bjoern-st/multilingual_menus

As you can see in the function multilingual_menu_form_menu_edit_item_submit() all I had to do to mark menu items with a language is to store the language object as $item['options']['language']. 

![grafik](https://user-images.githubusercontent.com/33264593/36895116-03254df6-1e0e-11e8-921a-f741959c20b7.png)

As you can see on the picture above, after loading the menu items, each menu item then has automagicaly a value "#localized_options" including the language object. 

Unfortunately this "options" value is stored as a blob in the database - which means, that the menu items can't be filtered while loading from database, so by default all menu items are loaded. 
So you would have to filter out the menu item corresponding to the current language by its "#localized_options" value in the function "menu_build_tree" or "_menu_build_tree". 

This seems to be not so straight forward, but with this approach you would come along with only a few changes and you you don't need ab api-change.

**Comment by quicksketch** [comment]
Wow, so we bumped this back to needs work just based on one minor item: redirecting back to the same language after adding a menu item. I added this to the PR at https://github.com/backdrop/backdrop/pull/2054 in https://github.com/backdrop/backdrop/pull/2054/commits/75104f850687c41b90e81fcc68909b794580d6ab.

**Comment by quicksketch** [comment]
I've merged https://github.com/backdrop/backdrop/pull/2054 into 1.x for 1.10. Thanks @kriboogh for getting the ball rolling on this feature, @olafgrabienski, @klonos, and @bjoern-st for your feedback and testing!

**Comment by olafgrabienski** [comment]
I guess I came one minute too late for a review! Happy to see this merged!
