### ISSUE TITLE
Add a notice in installer when stuff outside the "core" directory changes

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#2258]
Updating core is easy now with the new "core" directory. So when I upgraded to 1.5.0 I simply swapped out that directory, as usual, not remembering we changed `standard.profile`.  Other people wouldn't know that.  We should add a notice somehow during the update script.

**Comment by klonos** [comment]
Either that, or we add a `/core/profiles`, move core profiles there and keep `/profiles` for custom/contrib ones (same thing we do with core vs contrib modules/themes/layouts).

**Comment by serundeputy** [comment]
That is true. That being said these `/profiles` directories only affect new installations going through the installer not a site that is installed and being updated.

Some indication is in order though.

**Comment by klonos** [comment]
Yeah, I'm not sure how many things we'd break and how badly they'd break, but if we moved the minimal, standard and testing profiles under `/core` (which seems only reasonable), then we'd be able to get update hooks in them without worrying for situations where people upgrade only by copying the `/core` directory.

If we did this now (1.x), then issues I foresee...

a) we'd need to make sure that the logic favors the `/core` ones (in order to pick up the changes with the update hooks). This might end up being confusing because with modules, themes and layouts it's the opposite: contrib is favored over core when the same filenames are used.

b) what happens with the existing profiles under the root `/profiles` folder? As you pointed out @serundeputy, these only run during first-time installations, so it shouldn't be an issue (but perhaps we should prompt users to delete them anyways).

c) what happens if there is a case where contrib wants to override a core profile? Are there any legit use cases where something like that would be required that you can think of?

...or do we wait and do this in 2.x?

**Comment by klonos** [comment]
...anyways, the point is that the whole move of core things under `/core` was made with having in mind that this is how things work: everything that is core goes under `/core` and people need to replace only that folder in order to upgrade. Should we call placing core profiles in the `/profiles` folder out of `/core` and architectural oversight (and hence a bug) and fix it? As I said it only feels like the right thing to do.

**Comment by rstamm** [comment]
I would appreciate it if `/profiles/*` moves to `/core/profiles`

**Comment by klonos** [comment]
Yeah, after discussing this matter during the [weekly meeting today](https://www.youtube.com/watch?v=oqt3_UcBPe8), I would like to propose that we rename and re-purpose this issue to move the `/profiles` folder contents (the entire `minimal`, `standard` and `testing` subfolders) under a new `/core/profiles` folder and leave the `/profiles` folder for contrib. This way, we'd address the original issue as described in the issue summary and we won't have to either warn people about things outside the `/core` directory or force them to change their habits (upgrading by swapping the core folder).

Is that OK with you @serundeputy or do you think that your initial proposal is still a goal worth pursuing?

**Comment by mikemccaffrey** [comment]
I vote for moving the core profiles to core/profiles.

Are there any other files outside of the core directory that we might need to change on a core update?

**Comment by klonos** [comment]
@serundeputy, @quicksketch, @jenlampton what are your thoughts on this? Do we have to wait till 2.x or can it be done in the 1.x cycle? ...and if in 1.x, is it a bug or feature (in other words 1.5.x or 1.5)?

**Comment by klonos** [comment]
...and by "this", I meant the move of the core profiles under a `/core/profiles` directory.

**Comment by serundeputy** [comment]
This is hard to say as there could be installs depending on this structure.  So, at the least I'd say `1.6.0` with a big proper message in the release notes, release announcements  and `update.php`, but depending on the consequences for people who added a profile under `/profiles`?  Are there such people?  Depending on those concerns maybe `2.x`, but I defer to @quicksketch on this one.

**Comment by klonos** [comment]
> This is hard to say as there could be installs depending on this structure.

I doubt that, mainly because installation profiles run only during initial installation. In fact, I think that we should first do the move and only then implement #1591 (if we decide to do so).

**Comment by docwilmot** [comment]
This is being dealt with in https://github.com/backdrop/backdrop-issues/issues/3025
