### ISSUE TITLE
Error when upgrading site from 1.3 to 1.5

### ISSUE THREAD

**Issue by mikemccaffrey** [backdrop/backdrop-issues#2278]
I've just upgraded one of my dev sites from 1.3 to the latest 1.x branch right after 1.5 went out.

When I visit the home page, I get this error:

`Warning: include(/var/www/dev/backdrop/core/layouts/two_column/layout--two-column.tpl.php): failed to open stream: No such file or directory in /var/www/dev/backdrop/core/includes/theme.inc on line 1517`

It looks like the current layouts were not updated properly when the new ones were introduced.

**Comment by quicksketch** [comment]
Unfortunately, this is expected behavior... the theme registry still contains the old location of the template file. It needs to have the cache cleared to pick up the moved template file. The "fix" is to visit update.php, which will clear all caches as part of the update process. There may be some way to avoid this, but I can't think of a reasonable way to handle it. Clearing caches in the event of a missing entry seems like that could easily lead to a new set of problems with the cache getting reset all the time.

And if you're on Pantheon, of course if we fix the "Run update.php" checkbox (through fixing Drush on Pantheon) then that would solve the problem on that particular platform without needing to manually visit update.php.

**Comment by mikemccaffrey** [comment]
Um... I did run drush updb, which I believe should clear all the caches.

**Comment by klonos** [comment]
...I'm gonna go ahead and close this one as outdated. Please feel free to reopen if this is still an issue.
