### ISSUE TITLE
Available updates doesn't respect "Security updates only" setting

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#2284]
I have a site in development with "Security updates only" checked under admin/reports/updates/settings -- but it still emailed me a notification from 1.5.0 to 1.5.1 which wasn't a security update. (Unless this was fixed in 1.5.1 in which case it's not an issue anymore.)

---
PR by @opi: https://github.com/backdrop/backdrop/pull/2262

**Comment by quicksketch** [comment]
Thanks for reporting this issue @laryn! This has not been fixed in 1.5.1, so it's a current issue.

The code that sends notifications is in `_update_cron_notify()`. Either the problem is that we're not checking/setting this value properly, or that the site being out of date throws a `REQUIREMENT_ERROR`. It should only do that for security updates, but if it's doing it for all updates, then the notifications become incorrect.

**Comment by laryn** [comment]
Thanks @quicksketch -- that function [looks okay at a glance](https://github.com/backdrop/backdrop/blob/92026349212b0383a006f12a19ce5f0be0099e37/core/modules/update/update.fetch.inc#L387-L392). (The params variable is empty unless REQUIREMENT_ERROR is set or the notifications are set to all, so it seems that the code that sends the email shouldn't fire.)

**Comment by laryn** [comment]
I haven't been able to get back to digging into this one yet, but I think I've narrowed things down a bit in terms of the end result -- it seems to be working okay as long as the "Check for updates of disabled and uninstalled modules, themes, and layouts." box is checked. One site was sending notifications and one was not and that was the only difference in their config.

**Comment by olafgrabienski** [comment]
I just noticed the same issue on one of my sites. Good to know the workaround (checking for disabled and uninstalled modules), thanks @laryn !

**Comment by BWPanda** [comment]
This is still an (annoying) issue...

**Comment by klonos** [comment]
@BWPanda can you please post a list with versions of core/contrib that make this issue happen. If I could reproduce it, perhaps I would be able to do something about it 😉

**Comment by BWPanda** [comment]
@klonos My settings are as follows:
- Check for updates: Daily
- Check for updates of disabled and uninstalled modules...: Disabled
- E-mail addresses to notify...: A single email address
- E-mail notification threshold: Only security updates

Some modules with updates that trigger an email:
- Simple Mail System 1.x-1.0.1 | Recommended version: 1.x-1.0.2 (2018-Jul-23)
- Comment Notify 1.x-1.1 | Recommended version: 1.x-1.3.1 (2018-Jul-24)
- Font Awesome 1.x-1.2.4 | Recommended version: 1.x-1.2.5 (2018-Jul-25)

But! Looking at my config files, I noticed that the 'update_threshold' setting was '0', whereas the options for the form element are:
- 'all' => t('All newer versions'),
- 'security' => t('Only security updates'),

Also, the default config file that ships with the Update module has '0' as the default value, and when upgrading from Drupal it sets the value (if the variable is empty) to '0'. That might have something to do with it...

**Comment by klonos** [comment]
Thanks @BWPanda 👍 ...this helps.

**Comment by opi** [comment]
After some digging, I found 2 different bugs:
- The `update_threshold` setting is not correctly initialized. It is set ot `0` instead of `all` or `security`. (https://github.com/backdrop/backdrop/blob/1.x/core/modules/update/config/update.settings.json#L12)
- When a set of radios have a `#default_value` set to `0`, the last radio is checked. (It does not happen with `ǸULL` of `FALSE`).So if you just look at the update setting form without ever submitted it, then you believe that "security" radio is checked. To be confirmed, and fixed in another issue.

@BWPanda did setting the `update_threshold` setting to `security` fix your problem ?

**Comment by BWPanda** [comment]
@opi I think so, I'll check back in a day or two to confirm though.

**Comment by opi** [comment]
Simple PR https://github.com/backdrop/backdrop/pull/2262 that fixes the default threshold value. Set to `all` as in Drupal 7.

**Comment by klonos** [comment]
Good catch on both findings @opi!! RTBC from me 👍

**Comment by klonos** [comment]
...actually the first finding was @BWPanda, so 👍to you too 😄

**Comment by opi** [comment]
We should probably add a hook_update to fix existing installation.

**Comment by klonos** [comment]
You are right @opi, we should. Setting back to NW for that.

**Comment by opi** [comment]
PR updated with a `hook_update` that change the `update_threshold` setting form 0 to *all*.

**Comment by klonos** [comment]
@opi I left a comment in the PR. Please update the update hook number (should not be `2000` as these are reserved for Backdrop 2.x). Other than that, RTBC 😉

**Comment by opi** [comment]
My bad. Fixed.

**Comment by klonos** [comment]
RTBC 👍

**Comment by BWPanda** [comment]
> @BWPanda did setting the update_threshold setting to security fix your problem ?

@opi Sorry for the delay, but yes, it did.

**Comment by quicksketch** [comment]
Thanks I've merged https://github.com/backdrop/backdrop/pull/2262 into 1.x and 1.10.x!
