### ISSUE TITLE
File::uri() not consistent with other Entity types

### ISSUE THREAD

**Issue by mikemccaffrey** [backdrop/backdrop-issues#2300]
As part of building the Link formatter for the Reference module, we encountered a problem where the `$entity->uri()` function for file entities includes a stream wrapper identifier in the beginning like "public://field/image/imagefield_1g3q2W.png".

Right now, it tries encoding the "public://" into the url itself, creating a bad link.

Option 1: We should add a check in the url() function to check if a path starts with stream wrapper identifier, and format the resulting url using the stream wrapper.
Option 2: We should change `File::uri()` to be consistent with other entity types, and link to `file/[fid]` page instead of a direct path to the file itself.

At the time this issue was originally created, Files did not yet have pages. Now that they do, we have two options to solve this problem.

**Comment by quicksketch** [comment]
I took a look at this problem and unfortunately it gets messy. While I think it makes sense to make url() support stream wrappers, we have some problems making this possible.

I tried just putting `file_create_url()` in `url()` like this:

```
  // Convert file URIs into URLs. This always results in an external URL. It may
  // be shorted back into a relative one below.
  $scheme = file_uri_scheme($path);
  if ($scheme && file_stream_wrapper_valid_scheme($scheme)) {
    $path = file_create_url($path);
  }
```

But we have methods like `BackdropPrivateStreamWrapper::getExternalUrl()` that call `url()` inside of them. This causes either double-encoding and/or double unclean URL handling. So instead of getting a path like `?q=system/files/example.png` you get `/?q=%3Fq%3Dsystem/files/example.png`.

The best idea I can come up with is introducing a new method on stream wrapper classes that returns the Backdrop internal path if possible. e.g. "files/example.png" or "system/files/example.png", that could then be passed into url() safely. If this method returned FALSE, then the absolute URL returned by `getExternalUrl()` would be used instead.

**Comment by quicksketch** [comment]
Making a new method like `getBackdropPath()` also has new problems. For a `public://` file path, if we returned "files/example.png" and clean URLs were turned off, running through `url()` would result in `/?q=files/example.png`, which we also don't want.

**Comment by jenlampton** [comment]
Is this a blocker for entity reference? Or just something that's related?

**Comment by jenlampton** [comment]
No PR here yet, pushing to 1.7

**Comment by jenlampton** [comment]
As this issue has already missed a core release and still doesn't have a PR, I'm going to remove the milestone. If we determine that this is a priority (a blocker for reference module?) We can reschedule it as soon as it has a PR.

**Comment by quicksketch** [comment]
I updated the issue summary here to better reflect the options we have. Now that files have menu paths (i.e. `file/[fid]`) we also have the option of making `File::uri()` consistent with other entity types, rather than making the wider-impacting change of modifying `url()` and `l()` to support file paths.

**Comment by indigoxela** [comment]
So cool, @herbdool many thanks for digging into this. It works!

A small nitpick: in function file_multiple_delete_confirm() - the confirmation step when batch deleting files via the admin overview - the url of the link to the file changed from the actual file to the entity path. I'm assuming that's not by intention, or is it?
To verify: go to /admin/content/files check one or more files and execute the action. In the confirm step, compare the url of the file. Now it's file/FID, but before it was like files/path/whatever/filename.ext.

What we might also need to check: file url tokens.

**Comment by herbdool** [comment]
@indigoxela regarding file_multiple_delete_confirm(), it wasn't intentional but I think it's ok since it's clearer which exact entity is being deleted. And it matches the link that appears in the usages tab. Before was it a functioning URL or broken on that confirmation page?

**Comment by indigoxela** [comment]
> Before was it a functioning URL or broken on that confirmation page?

It was (is) functioning, but a link to the actual file, not the entity. That changes with your PR, which turns it into a link to the entity.

**Comment by herbdool** [comment]
So it's been tested and code reviewed. Anyone want to update the labels? Mark it ready or needs work? And if the latter what needs work? @indigoxela @argiepiano

**Comment by indigoxela** [comment]
Yes, sorry for the delay. Personally, I'd prefer the url in the confirm form to stay the same, but have no strong feelings, if it becomes the entity url. I don't feel qualified to decide what it should be, though.

**Comment by argiepiano** [comment]
As suggested by @quicksketch I did a search on github for contrib modules that used the `uri()` method for files. I did not find any instance of that.   There are two instances in core - one to generate tokens and the other one the delete confirm mentioned above.

**Comment by herbdool** [comment]
@argiepiano you ok with marking it rtbc?

**Comment by quicksketch** [comment]
I think we're ready and in agreement that this is RTBC. I'll wait another week for any last opposition, but I think this should move forward.

**Comment by herbdool** [comment]
Sounds good - next week we'll merge if no objections.

**Comment by quicksketch** [comment]
Change record published to https://docs.backdropcms.org/change-records/file-uri-now-returns-path-to-file-entity-page-not-the-file-path
