### ISSUE TITLE
Basis: in the contact form, the email field and its label are inline and the "required" asterisks are black and with a dotted underline instead of red.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2311]
Here's how the form looks in Bartik:

![backdrop-contact_form-bartik](https://cloud.githubusercontent.com/assets/2423362/19829265/d455a0b4-9e27-11e6-9d75-1818326f71af.png)

...in Seven:

![backdrop-contact_form-seven](https://cloud.githubusercontent.com/assets/2423362/19829272/e100003e-9e27-11e6-9cb5-13adb6c8822b.png)

and in Basis:

![backdrop-contact_form-basis](https://cloud.githubusercontent.com/assets/2423362/19829275/e9b250d8-9e27-11e6-968b-44f414f39377.png)

---

PR by @klonos: https://github.com/backdrop/backdrop/pull/1629

**Comment by klonos** [comment]
Screenshot from the PR sandbox:

![backdrop-issue2311-pr1629](https://cloud.githubusercontent.com/assets/2423362/19829357/e88ff488-9e29-11e6-8bb4-db1484796177.png)

**Comment by klonos** [comment]
...while at it, I have changed the fields in https://github.com/klonos/backdrop/blob/patch-58/core/themes/basis/css/component/backdrop-form.css#L11 to be in alphabetical order (perhaps we'll need to add more later and that would make it easier to see which ones are missing).

I have added the changes to the required asterisk (red color, remove underline) right after the `display: block;` part. Let me know if you think they belong elsewhere (different .css file or different part of the current one). Otherwise, tests are green 😉

**Comment by klonos** [comment]
> Otherwise, tests are green

...well, I had to close and re-open the PR to get the random failures to go away, but the php70 test still suffers from https://github.com/backdrop-ops/backdropcms.org/issues/276 the correct URL with the passing tests is without the `-4` appended at the end: https://zen.ci/backdrop/backdrop/test/test-php70-backdrop_backdrop_1629-72d8c9c

**Comment by olafgrabienski** [comment]
Looks good to me. Is there a particular reason why you asked if the changes should belong to a different place?

**Comment by klonos** [comment]
@olafgrabienski Thanx for taking a look. No particular reason. It's just because Basis is @wesruv's "baby", he might have better suggestions as to where css needs to go (since he is trying to make Basis easily sub-themable etc.).

**Comment by Dinornis** [comment]
Tested fine, tagging as fixed.

**Comment by quicksketch** [comment]
I'll add that in Firefox, we still have a dotted line because they started using `text-decoration: dotted underline` for `abbr[title]` elements. So right now in fact you have TWO dotted underlines:

![screenshot from 2017-01-08 20-39-50](https://cloud.githubusercontent.com/assets/100206/21757389/a02b908a-d5e2-11e6-8533-799f72ee86c3.png)

Apparently this is a recent change in Firefox and is coming soon in Chrome: http://stackoverflow.com/questions/26276556/remove-underlining-caused-by-abbr-tag

So I think we should do a couple of things here:

- Update https://necolas.github.io/normalize.css/ so that we have consistent underline/border behavior on `abbr` tags.
- Update `system.theme.css` to override the new rule and disable the text underline.
- Also update `backdrop-form.css` in Basis, as it doesn't include `system.theme.css`.

**Comment by quicksketch** [comment]
Actually I don't see any reason to hold this issue up. It makes an improvement for sure. Let's go ahead and get this one in and then we'll worry about normalize.css (and updating the rule) in that issue.

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/pull/1629 into 1.x and 1.5.x. Let's solve the lingering problem with underlining abbr differences in the normalize.css issue at https://github.com/backdrop/backdrop-issues/issues/2460.

**Comment by quicksketch** [comment]
And thanks @olafgrabienski, @Dinornis, and @klonos for carrying this one! :+1:
