### ISSUE TITLE
[UX] Add the "new" marker to the content overview listing

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#2350]
Couldn't find an existing issue for this, so hope I haven't missed something.

This is something missing from Backdrop that is in Drupal by default I believe...

**Comment by klonos** [comment]
It is not in D8 and unless I'm mistaken nor is it in the D7 core (non-views) content list. It is in D7 version of admin_views though. A very helpful addition nevertheless that we should do. I believe we should add it to the fields but exclude it from display (but do expose it as a filter) and then rewrite the result of the title field to have it rendered as `[title][timestamp]`. Here's how it would look:

![backdrop-issue2350](https://cloud.githubusercontent.com/assets/2423362/20588886/b7fa90e2-b26c-11e6-95aa-ef2b08b6b4c2.png)

**Comment by klonos** [comment]
PR up for initial review: https://github.com/backdrop/backdrop/pull/1652

Questions:

1. This PR affects only new installations and when the user reverts the "Admin Content" view to its defaults. I need to figure out how to check if the view is already in its default state and then create an update hook that will update the active view *only* in those cases.

2. The diff with the original .json includes certain values that are left empty (like `"ui_name": ""` for example). Can these be omitted instead (and should they)?

3. I noticed that for the ["status" filter, its `group` property is set to numeric `1` (`"group": 1`)](https://github.com/backdrop/backdrop/blob/1.x/core/modules/node/config/views.view.node_admin_content.json#L287), whereas for the rest of the filters it is set to string `"1"` (`"group": "1"`). Does it matter? Which is correct? Typo? Should I just go ahead and change it in this PR?

**Comment by BWPanda** [comment]
> It is not in D8 and unless I'm mistaken nor is it in the D7 core (non-views) content list.

It is indeed in D7 core (just checked) :smile:  See here: https://api.drupal.org/api/drupal/includes%21theme.inc/function/theme_mark/7.x

> I believe we should add it to the fields but exclude it from display (but do expose it as a filter) and then rewrite the result of the title field to have it rendered as [title][timestamp].

That seems a bit complicated.
What I did to add it to my site was to override the admin view, add the `Content: Has new content` field, hide the label but leave the field otherwise displaying normally, move it just below the `Content: Title (Title)` field, then edit the `Table` format settings to display the `Content: Has new content` field in the `Title` column. Easy, no re-writing needed.

![firefox_screenshot_2016-11-24t22-21-11 308z](https://cloud.githubusercontent.com/assets/2385329/20610655/af8fd92e-b2f0-11e6-9da8-3cd7639cb008.png)

**Comment by quicksketch** [comment]
I think this is a great idea.

Updating the PR to use the approach suggested by @BWPanda is a good idea IMO. Just put the two fields in the same column instead of using tokens.

For the upgrade path, I'd suggest something like this:

```
function views_update_1004() {
  // Only update if the frontpage view is in the default state (4 === VIEWS_STORAGE_DEFAULT).
  $config = config('views.view.frontpage');
  if ($config->get('storage') === 4) {
    // Make changes to the config file.
    $config->save();
  }
}
```

The diff of the config file in the PR also contains more changes than is strictly necessary. We can remove any lines that are just the default settings from the JSON (anything in the "alter" section). I'll usually manually clean up the JSON a bit to minimize the amount of code changes to include only the needed views config.

**Comment by BWPanda** [comment]
Created a new PR. I wasn't sure what was ok to delete from the config diff, so left everything in there. Can update if needed.

**Comment by stpaultim** [comment]
The Sandbox is broken. Can someone restart the sandbox? (Atten: @BWPanda)

**Comment by stpaultim** [comment]
@BWPanda - Sorry, but sandbox is still broken.

**Comment by BWPanda** [comment]
@stpaultim Looks like it's working now. Get in quick before it breaks again :stuck_out_tongue_closed_eyes:

**Comment by klonos** [comment]
Tested this:

1. Logged into the PR sandbox and visited the content listing -> "new" indicators were shown for the 2 default pieces of content for the admin user 👍 
1. Viewed the "About" page -> visited the listing again -> the "new" indicator was gone from the "About" page, but was there for the "Your first post!" post 👍 
1. Ticked the "New/updated content" checkbox and clicked on "Filter" -> content was filtered as expected 👍 
1. Created a new user account, with "Editor" role, and logged in as that user -> both content had the "new" indicator for this user 👍 

RTBC 🙂

**Comment by stpaultim** [comment]
Looking good to me.

**Comment by BWPanda** [comment]
Thanks everyone! I've merged https://github.com/backdrop/backdrop/pull/2399 into 1.x.
