### ISSUE TITLE
[DX] Add a config_clear() wrapper to be the equivalent of variable_del().

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2355]
In our docs we say that varaible_del is [no longer supported](https://api.backdropcms.org/node/28616) but we do not provide a suitable alternative, nor instructions on what to do if you need to replace it. 

As far as I can tell, what used to be a simple one-liner like this:
```
variable_del("xmlsitemap_settings_{$entity}_{$bundle_old}");
```
Now needs to look something like this:
```
$config = config('xmlsitemap.settings');
$config->clear("xmlsitemap_settings_{$entity}_{$bundle_old}");
$config->save();
```
But we did not provide a clean wrapper function `config_del()` that matches Drupal's `variable_del()`.  I think this is an oversight that's caused a DX regression.

---
~~PR by @jenlampton: https://github.com/backdrop/backdrop/pull/1651~~
~~PR by @Graham-72: https://github.com/backdrop/backdrop/pull/1800~~
~~PR by @klonos https://github.com/Graham-72/backdrop/pull/1~~
~~PR by @klonos https://github.com/Graham-72/backdrop/pull/2~~
PR by @jenlampton: https://github.com/backdrop/backdrop/pull/1651

**Comment by quicksketch** [comment]
The PR at https://github.com/backdrop/backdrop/issues/1651 looks good, but isn't a bit inconsistent that the method is `$config->clear()` but the function is `config_del()`? I see the attempt at matching D7 terminology, but that seems like a compromise that favors the D7 terminology over being consistent with our own API. So I'd probably encourage us to use `config_clear()` instead.

As for why `$config->clear()` exists, it's because `$config->delete()` will delete the entire configuration file, while clear removes a single entry from within the file.

**Comment by jenlampton** [comment]
> I see the attempt at matching D7 terminology, but that seems like a compromise that favors the D7 terminology over being consistent with our own API. 

What if the D7 terminology was better? `Delete` people will understand, but `Clear`?  In this case, the point of these wrappers is to add backwards compatibility, or maybe backwards-similarity, and if the name is better too, double win?

**Comment by jenlampton** [comment]
Thinking about this from the beginners perspective, if you see `config_del` and you know what it does, then try `config->delete()` because you think it's a match, and instead accidentally delete your whole config file, that's a problem. I'm really dislike the word clear, but unfortunately I think we're stuck with it. :( Maybe in 2.x we can change it to remove or something with more meaning.

**Comment by quicksketch** [comment]
I would also avoid any abbreviation, "del" was used I imagine because it made "pretty" function names that were all the same length: variable_get/set/del. If we were to have wrappers for the delete method as well, I would be in favor of naming it `config_delete()` (in addition to `config_clear()` for removing a single value).

**Comment by jenlampton** [comment]
thought... It would really be nice to find/replace `variable_` with `config_` when porting modules. :)

**Comment by herbdool** [comment]
I prefer config_clear() for internal consistency. I end up reading the porting modules docs regardless of the D7 approach.

**Comment by Graham-72** [comment]
Without knowing much about the other implications of this, I would have been delighted to have config_del() that would work as a mirror of config_set() and allow one to delete a whole entry in a config file or allow removal of a single value within an entry. I would make use of this in porting and writing modules.

If there are problems with naming it config_del(), then I accept that some other name or names should be used, but then to avoid confusion config_del() should not be used for either purpose. In any case, I look forward eagerly to having this capability!

**Comment by Graham-72** [comment]
Please could we have a decision on this one and include the new function as soon as possible. I am happy to work with config_clear(). I find when porting from D7 I have to treat variable_get() functions separately from variable_set() ones, so no real problem if variable_del() is also different and has to become config_clear() rather than config_del().

**Comment by jenlampton** [comment]
Let's go with `config_clear()` since we seem to be getting consensus around that. Who wants to update the PR?

**Comment by klonos** [comment]
PR looks good, thanx @Graham-72 👍

**Comment by quicksketch** [comment]
The PR looks great! Docs are inline with what we have thus far for other functions as well.

I would like to add a few more things though:

- We should test a call to `config_clear()` to make sure it works as expected. We can do this in `testReadWriteConfig()`.
- We should add a `@since 1.7.0` line to the docblock for the function to make it clear when this wrapper became available.

**Comment by Graham-72** [comment]
@klonos please unassign me as I am not competent to add the test requested by @quicksketch. 😃

**Comment by herbdool** [comment]
I can give it a shot.

**Comment by Graham-72** [comment]
@herbdool Thanks.

**Comment by klonos** [comment]
> @klonos please unassign me
...
>I can give it a shot.

Done and done 😉

**Comment by klonos** [comment]
...in fact, I thought I'd just butt in and do that myself. @Graham-72 here's two PRs against your PR branch:

- https://github.com/Graham-72/backdrop/pull/1 adds the `@since 1.7.0` in the docblock
- https://github.com/Graham-72/backdrop/pull/2 renames function `testReadWriteConfig()` to `testReadWriteClearConfig()` and adds tests for deleting config values via `$config->clear()` and `$config_clear()`.

@quicksketch can you please review these (mainly the second one) before @Graham-72 merges them in his branch?

Disclaimer: that's the first time I'm touching a test, so warning that I wrote this by gut feeling and it could be total rubbish.

**Comment by quicksketch** [comment]
@klonos All changes look good. If we can get these all together in a single PR this looks good to me.

**Comment by quicksketch** [comment]
Thanks https://github.com/backdrop/backdrop/pull/1651 looks great. Merged into 1.x.
