### ISSUE TITLE
Add an interface to view and manage files

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2375]
This is part of https://github.com/backdrop/backdrop-issues/issues/1448, as one step closer to a media solution for Backdrop. This first issue will tackle the following new features:

* Adds a view that lists all files
* Adds a permission for accessing that view
* Adds an action to bulk-delete files
* Adds a URL to delete individual files.
* Adds a permission for deleting individual files.
* Moves views file data into file module.

---
~~PR by @jenlampton: https://github.com/backdrop/backdrop/pull/1658~~
~~PR by @quicksketch https://github.com/backdrop/backdrop/pull/1696~~
PR by @jenlampton https://github.com/backdrop/backdrop/pull/1711

**Comment by jenlampton** [comment]
Ran into https://github.com/backdrop/backdrop-issues/issues/2374 while implementing this.

**Comment by docwilmot** [comment]
Doesnt https://www.drupal.org/project/file_entity do this? I thought we were merging that?

**Comment by jenlampton** [comment]
We have already included most of file_entity in Backdrop, but not this part. Hence the issue :)

**Comment by jenlampton** [comment]
Setting to NW because @mikemccaffrey pointed out that without files there's no view. We need to include empty text.

**Comment by quicksketch** [comment]
The PR at https://github.com/backdrop/backdrop/pull/1658 is actually missing the view itself. The config file doesn't appear to be in the PR.

**Comment by jenlampton** [comment]
Doh, sorry folks. adding back. As per https://github.com/backdrop/backdrop-issues/issues/2301 also made the view name "Manage files".

**Comment by serundeputy** [comment]
@jenlampton The view looks great.

TODO:
  * hook_update() to move the `views.view.file_admin.json` config file to the active config.
    * otherwise if you upgrade a site the view does not show up.
    * Installing a new site with this patch puts the config and view in place as expected.

Needs work:
  * If I add an image file to a post:
    *  the file is on the post
    * the file is in the `file_managed` table
  * Delete the file via the new `MANAGE FILES` view
  * Go back to the post and there is a broken image in the rendered display of the post
    * file entry in `file_managed` is gone but there is still an entry in `field_data_field_image`

![screen shot 2016-12-23 at 5 32 26 pm](https://cloud.githubusercontent.com/assets/6763671/21463450/552e8568-c937-11e6-9652-81fa381e3ab4.png)


Perhaps the delete call back needs to see where the file(s) are used and update those entities as well?

**Comment by klonos** [comment]
>Perhaps the delete call back needs to see where the file(s) are used and update those entities as well?

- Yeah, it would be great if there was a "This file is used in the following places:" confirmation message upon attempting to delete files.

- Talking about confirmation. There is a confirmation when deleting a single file via the "Delete" operation available as a button, but no confirmation if either a single or multiple files are being deleted via the VBO "Delete file(s)" action.

- Also, when deleting files from two posts and then attempting to edit and re-upload the same files, I got the "The website encountered an unexpected error. Please try again later." error. The following errors were logged...

  error:
  ```
  Recoverable fatal error: Argument 1 passed to file_usage_delete() must be an instance of File, boolean given, called in /core/modules/file/file.field.inc on line 272 and defined in file_usage_delete() (line 718 of /core/includes/file.inc).
  ```

  warning:
  ```
  Source image at public:// not found while trying to generate derivative image at public://styles/large/public/.
  ```

  notice:
  ```
  Page not found
  files/styles/large/public
  ```

  Revisiting those nodes still displayed the images, so I tried to edit them and of course their image fields were empty. Clearing caches made the images not show when viewing the nodes. Perhaps a cache clear is in order when deleting files (in the background)?

- The view name is "Administer files". It should be "Manage files" in order to be in tandem with the changes happening in #2301 / https://github.com/backdrop/backdrop/pull/1665. Note that the following need to also happen in order to have consistency in the UI as well as in the config files:
  - The view config file under `/core/modules/file/config/` needs to be `views.view.manage_files.json` (currently `views.view.file_admin.json`)
  - The view name needs to be "Manage files" (currently "Administer files")
  - The view machine name needs to be `manage_files` (currently `file_admin`)
  - The display title of the view needs to be plain "Content" (currently "Manage files"). This sets the actual page title, and if set to "Manage files" have sorta WTF in the UI. Hope the screenshot below explains it better:
    ![backdrop-issue2375-view_page_title_needs_to_be_content](https://cloud.githubusercontent.com/assets/2423362/21465791/7ab9a802-ca05-11e6-80a3-75b810fffa9b.png)
    (also see https://github.com/backdrop/backdrop-issues/issues/2301#issuecomment-266178815)
  - The pager needs to be set to paged with 50 items (currently set to only show 100 items)

**Comment by quicksketch** [comment]
I'm working on a reroll that fixes the problems mentioned so far. It's not ready for a PR yet, but includes:

- An update hook to create the view on existing sites.
- Added usage list when deleting a file.
  ![screenshot from 2016-12-29 21-15-09](https://cloud.githubusercontent.com/assets/100206/21560005/2d322216-ce0c-11e6-8eee-cd830b286a63.png)
- Add file usage count to the view listing itself.
- Added sorting to the view columns.
- Fixed the page title.
- Added a file name search box (exposed filter).
  ![screenshot from 2016-12-29 21-16-51](https://cloud.githubusercontent.com/assets/100206/21560007/38914bdc-ce0c-11e6-86be-f18d6f1ba271.png)

I haven't addressed the deleting fatal error yet, but I hope to get to it and file an updated PR by end of day tomorrow (Dec 30).

**Comment by jenlampton** [comment]
Hi all!  (I'm back from the land of the living-dead, at least for a little while!) We also need to update all the places these files are used, for example, removing the FID from file fields.

**Comment by quicksketch** [comment]
Okay new PR is up at https://github.com/backdrop/backdrop/pull/1696. More additions:

- Added confirmation page when bulk deleting files. This page is less expressive when showing usages, but that is expected as if you were deleting a lot of files that could be hundreds of usages. Screenshot: ![screenshot from 2016-12-30 15-51-49](https://cloud.githubusercontent.com/assets/100206/21574862/c8896064-ceaf-11e6-91a8-0703dd0d353c.png)
- I realized if you click the "Execute" button without selecting an action you get a nasty warning and your checkboxes are cleared. Fixed that by making the "Operation" select list `#required`.
- Both this form and the node form were exhibiting some strange behavior when selecting items, clicking Execute, then hitting back and selecting _different_ items. The result would be a merge of all the first selection and the second selection. That could be extremely dangerous when deleting items if unchecked items suddenly re-checked themselves!
- I fixed the fatal errors exhibited when a file had been deleted and then a piece of content that referenced that file is later changed (such as uploading a new file).

More on this last issue: Both D7 and D8 seem to *not* address a file being deleted out from under a piece of content other than to handle it a bit more gracefully. The rows are left in place in the field_data_* and field_revision_* tables. I actually think this lazy approach makes the most sense because the thought of silently removing the fact a file had ever existed from revisions seems like terrible revision management. It's better to leave the fact that the file existed _at some point_, even if it's no longer present.

The behavior now simply acts as though there was never a file attached (even though the data still exists in the database). We could potentially improve handling for "broken" files like this similar to what we do for missing blocks or views fields: maintain the fact something was there but don't allow editing it (other than to remove it).

Of course, any deleting of a file that is actively in use should be discouraged in the first place, and the messaging we have in place in the PR reflects that already.

TODO: We need further code reviews (there is a lot being added here) and testing.

**Comment by docwilmot** [comment]
"1 usage" may not be very helpful. Can you make that a hyperlink that opens a list of usages?

**Comment by quicksketch** [comment]
> "1 usage" may not be very helpful. Can you make that a hyperlink that opens a list of usages?

Yeah, there is already a separate function specifically for generating that list of links. It's just a matter of how elaborate we get with the UI. I don't think we can actually leave the confirmation page, or else the list of files to be deleted will be lost, so we would need to open that list in a dialog or load in via AJAX.

**Comment by jenlampton** [comment]
How about we at least fix the language? Maybe a little `format_plural` on the "1 usage" to make it "1 use" vs "2 uses".  Or maybe "Used 1 time" vs "Used 2 times".

**Comment by olafgrabienski** [comment]
Another small issue: The filters on the "Find content" page and the "Manage files" page have different buttons: "Filter" vs. "Apply". See in comparison:

**Find content:**
<img width="676" alt="screen-pr-1969-find-content-filter" src="https://cloud.githubusercontent.com/assets/14188307/21581623/ccd74470-d039-11e6-8022-567ea58dbe25.png">

**Manage files:**
<img width="676" alt="screen-pr-1969-manage-files-filter" src="https://cloud.githubusercontent.com/assets/14188307/21581624/d876712a-d039-11e6-910a-275d9bb2ebf5.png">

In my opinion "Filter" is better, because it's semantically more clear, and it's less likely to confuse the "Filter" button with the "Execute" button of "Operations".

**Comment by jenlampton** [comment]
I'm writing tests right now...

**Comment by quicksketch** [comment]
Thanks @jenlampton for the fixes and the initial tests! This is a great start for sure and looks like an effective list of files on which we can check functionality. I would like to expand the test coverage to include actually attempting to delete files (individually and in bulk). Right now this only tests the listing, sorting, and the access to the delete links. A good start for sure but not comprehensive.

I've merged https://github.com/backdrop/backdrop/pull/1711 into 1.x for 1.6.0. However, I'm filing a follow-up for additional tests: https://github.com/backdrop/backdrop-issues/issues/2455

**Comment by klonos** [comment]
Sorry for coming late to the party, just a couple of minor nits/questions:

- The commit included [an update hook that adds the view to sites that have been upgraded](https://github.com/backdrop/backdrop/blob/1.x/core/modules/file/file.install#L120). The way the update hook works is that it duplicates the contents of the view being introduced from the `/core/modules/file/config/views.view.file_admin.json` file, stored in a `$view_config` array and then does a `$config->setData($view_config);` and finally a `$config->save();`. Is this (the duplication of the entire view) the preferred way, or should we be reading the .json file and then doing a `json_decode` instead? (#2434)

- The new view being introduced [includes a `'core' => '1.6'`](https://github.com/backdrop/backdrop/blob/1.x/core/modules/file/config/views.view.file_admin.json#L11). Is that required? What is this number used for anyways and why is views adding it in the first place? (#2432)

**Comment by jenlampton** [comment]
> Is this (the duplication of the entire view) the preferred way

Yes, that's the way to do it. Copying the .json file will not work as there may be changes to that .json file in the future, and we need it to be installed - in this update hook - in the exact format it's in right now.
