### ISSUE TITLE
Upgrade / Migrate Options from Drupal 6

### ISSUE THREAD

**Issue by Dinornis** [backdrop/backdrop-issues#2437]
I came across Backdrop only recently and so far I am very impressed with how much you all accomplished in such a short time, well done.  I like the overall philosophy and the roadmap.
If I needed to build a new website I would definitely go with Backdrop.

**What choices do Drupal 6 website maintainers have to migrate or upgrade their D6 sites to Backdrop?**  According to the handbook there are not yet any tools available to upgrade a site from Drupal 6 to Backdrop CMS.  **Are there any plans for developing a script that would simplify the migration of content from D6 to Backdrop CMS?**

A while back I built and to this day maintain a website for a small local community on a voluntary basis using Drupal 6.  Now I am looking for an alternative to Drupal and Backdrop CMS appears to be a better match for a volunteer based community website.

At this point, only the content, users and URL aliases are important to retain, everything else I can discard. I am okay to build all the views from scratch and the site needs a new responsive theme anyway.  I very much like the separation of layouts from themes in Backdrop, great idea.

**Comment by klonos** [comment]
Welcome to Backdrop CMS and the issue queue @Dinornis!

> According to the handbook there are not yet any tools available to upgrade a site from Drupal 6 to Backdrop CMS.

Correct. I have not tried any Drupal to Backdrop migrations yet, but I think that some others have. Especially @jenlampton which I guess will chime in here at some point. If I have this right, the only migration supported (which we actually call an upgrade) is from D7 to Backdrop. So I guess that unfortunately currently your best chance is to do a D6 to D7 upgrade (which I know will be a pain) and then go from D7 to Backdrop which from what I hear is pretty straight-forward.

The only hiccup you might come across is if you have any custom modules or contrib modules that you *absolutely* need that have not been ported to Backdrop yet. If the site(s) you are considering to move across are fairly simple, then most modules will either have already been ported to Backdrop contrib or their functionality merged in Backdrop core.

Personally, instead of going through the trouble of a D6 to D7 move to get to Backdrop, I would just do a straight rebuild in Backdrop. But I realize that this might be hard and a lengthy process. I would start by making a list of features implemented and modules used on your D6 website and then comparing these with what has been ported to Backdrop contrib and what Backdrop core offers. I would then make a list of features that cannot be implemented and modules not ported and weigh how important these are to the operation of the site. If you *absolutely* need something that is not there, then I'd turn to the contrib issue queue requesting for any modules to be ported or to our Gitter channel to ask for any alternative ways that certain things might be possible to be accomplished in Backdrop.

>Are there any plans for developing a script that would simplify the migration of content from D6 to Backdrop CMS?

Not that I am aware of, but I could be wrong,

>At this point, only the content, users and URL aliases are important to retain, everything else I can discard. I am okay to build all the views from scratch...

Well, it does sound like it's time for a rebuild 😄 ...it will be fun and I assure you that Backdrop is much more fun to be working with. It's not just the improvements that we've implemented compared to D7. We have also integrated most of the popular modules you might need in core, so there's definitely less work to do.

> I very much like the separation of layouts from themes in Backdrop, great idea.

I have only just yesterday watched a screencast of Panels and Page Manager, since I never got to play much with them during the D6/D7 cycle, and this was my reaction:

>PS: I have to say that not having touched Page Manager before and only slightly experimented with Panels, I now appreciate even more the awesomeness and at the same time the simplicity of our Layouts and the Layout UI!!

Pure magic!

> ...I like the overall philosophy and the roadmap.

I have been following the project since its first steps and I am myself very impressed by the progress made despite of the fact that we are a very small project still and thus seem to be lacking "manpower". I guess what we lack in numbers we make up for in will and determination to continue the legacy of Drupal 7 and of course in love of the project itself. You can obviously tell that I am thrilled by the way we function as a community ❤️ There are some very wonderful people with brilliant minds here and if you stick around you'll see this for yourself.

**Comment by Dinornis** [comment]
Thank you for the quick reply klonos.
> If I have this right, the only migration supported (which we actually call an upgrade) is from D7 to Backdrop. So, I guess that unfortunately currently **your best chance is to do a D6 to D7 upgrade** (which I know will be a pain) and then go from D7 to Backdrop which from what I hear is pretty straight-forward.

I would prefer to avoid the D6 to D7 process if possible.

> Personally, instead of going through the trouble of a D6 to D7 move to get to Backdrop, I would **just do a straight rebuild in Backdrop**. But I realize that this might be hard and a lengthy process.

What do you mean by straight rebuild in Backdrop?  How would you get the data over from the old site?

Here is a rough overview of the site data:
1400 nodes
 250 users
  20 roles
  25 node types
  15 content fields
  70 taxonomy terms (7 vocabularies)

Although the site uses a lot of contrib modules, I think only these are important in terms of retaining content:
* Forum (plus Advanced Forum)
* CCK (Email Field, File Field, ImageField, Phone)
* Content Taxonomy
* ImageCache (plus related modules)
* Link
* Location
* Privatemsg
* Pathauto

The biggest issue will probably be with the Forum module.  The handbook states that it has been removed from core. I should probably open a separate issue on that topic.

> I have been following the project since its first steps and I am myself very impressed by the progress made despite of the fact that we are a very small project still and thus seem to be lacking "manpower". I guess what we lack in numbers we make up for in will and determination to continue the legacy of Drupal 7 and of course the love of the project itself. You can obviously tell that I am thrilled by the way we function as a community ❤️ There are some very wonderful people with brilliant minds here and if you stick around you'll see this for yourself.

 +1 on that, I feel the same.
Thank you again for your time.

**Comment by jenlampton** [comment]
Telephone exists: https://github.com/backdrop-contrib/telephone

**Comment by herbdool** [comment]
Looks like someone ported the equivalent, Addressfield https://backdropcms.org/project/addressfield. It's a bit of work to migrate that though.

**Comment by herbdool** [comment]
Someone would need to port Privatemsg. It looks like activity only picked up again in the last six months on Drupal 7 so there's hope a full release comes out there soon https://www.drupal.org/project/privatemsg

**Comment by Dinornis** [comment]
Thanks guys, I appreciate the input.

What is the process of getting the Forum content from D7 over to Backdrop?

Step 2. Part 4 of the [Upgrading from Drupal 7 Backdrop documentation](https://backdropcms.org/upgrade-from-drupal) says to disable and uninstall the Forum module that will result in loss of content.

How do I migrate the D7 Forum content over to Backdrop Forum contrib module?

**Comment by herbdool** [comment]
I would not uninstall forum in Drupal 7. Then upgrade core to Backdrop then upgrade the contrib Forum module. 

Always good to make a backup of the database at each major step so you can rerun if something messes up

**Comment by Dinornis** [comment]
Don't follow instructions?  I like that 😄

**Comment by Graham-72** [comment]
> Someone would need to port Privatemsg

I had a go but it is not finished. https://github.com/backdrop-contrib/privatemsg. I will have another look at it soon.

**Comment by klonos** [comment]
Sorry for being away lately guys. Personal life mishaps.

> Step 2. Part 4 of the Upgrading from Drupal 7 Backdrop documentation says to disable and uninstall the Forum module that will result in loss of content.

AFAIK these pieces of content are not actually deleted from the database; it's just that their `type` db field has no equivalent content type defined any longer. We already cover this case in the same piece of documentation, as a sub-section of Step 2, Part 4:

> **Note**: uninstalling some of these modules (Blog, Forum, Poll) will result in loss of content (or, more accurately, content that doesn't know what type it is).

That part explains that there isn't really any loss of content, but our documentation continues with this:

> Please either delete content of these types before you uninstall the modules, or migrate the content to a custom type.

I think that it is not realistic to be asking people to delete their content before moving to Backdrop. I mean, nobody would seriously consider Backdrop if that's what they'd have to do.

I also believe that asking people to migrate their content to other custom content types is too much work (which translates to too much time/cost, which is against our principles). How does one even do that? ...I mean instead of just telling people "migrate the content to a custom type" shouldn't we make that a link to another documentation page with instructions on how to go about doing it ...and perhaps mentioning modules like [Node Convert](https://www.drupal.org/project/node_convert) which seems to be the only contrib module that does that? But how much success have people had using it? Shouldn't we be at least pointing them to it as a possible way to achieve this task? ...and how about other projects like [Drupal-to-Drupal Data Migration](https://www.drupal.org/project/migrate_d2d) and also the [D8 core Migrate suite (IMP)](https://groups.drupal.org/imp) that help people move from D7 to D8? Shouldn't we be planning to have something like that in Backdrop core?

Anyways, how bad would it be to keep any "orphan" content in the database, left in a "disabled" state? Perhaps either core or contrib will be able to deal with it at some point.

**Comment by jenlampton** [comment]
These modules were removed from core because they are used on only **a minority** of websites. It helps us focus on the things that are most important by removing things that aren't. People who want to move to backdrop will find ways to move their content (and yes, once they do that we can link to better documentation on how to do so) but keep in mind that this is not our priority, because it will benefit only a few people.

> Shouldn't we be planning to have something like that in Backdrop core?

We have something like this in Backdrop core. It's been in Drupal since the very beginning: update.php. Drupal 8 removed this, but Backdrop still includes it. Having it in core means **the majority** won't need to use any kind of migrate script at all.

Let's keep our focus here :)

**Comment by serundeputy** [comment]
This is a hard problem.

It is not easy to write instructions on a web page that tell people how to do it.

For example, if you are migrating from a simple Wordpress site that has Posts and Pages.  Then the source data has a fixed structure and you can have your migration script, module load in the wordpress data and map to backdrop content types.

That in and of itself writing down the details would take some time to spell out to a novice or non-coder.

But when factoring in complex, D6, D7, or wordpress sites the fields (source data) is not static since any one of those sites may have custom content types with any number of fields and each field could be any one of many types of data (text, video, numbers, reference ...).

So every migration needs to be studied separately. Take into account all the desired attributes of the source data and where you'd like to end up in your new site (exact parity, some stuff stays some stuff goes, or some stays and some is a complete rework of data and function).

That is why migrate in D7/D8 is an api that you can leverage to load data, move data and optionally transform in between.

**Comment by serundeputy** [comment]
> This is a hard problem.

Just want to point out that is a hard problem to solve abstractly {`any data source` --> backdrop}, but to solve the specific problem of fixed site (example.com) to new backdrop example.com is certainly manageable, but requires a programmer to look at the data, make the maps and write the importers, i.e. I didn't mean to make it sound like there is no hope for people to migrate, there is.  But to solve in general as a contrib or core solution is very hard.

**Comment by Dinornis** [comment]
@jenlampton 
>... People who want to move to backdrop will find ways to move their content (and yes, once they do that we can link to better documentation on how to do so) ...

Sounds more like catch 22 to me 😄

**Comment by jenlampton** [comment]
No, not really. It's rare that documentation is written before solutions exist ;)

**Comment by Dinornis** [comment]
No, not from a developer's view.

**Comment by olafgrabienski** [comment]
For Drupal 6 and WordPress users I consider a flexible content migrate solution (or even workaround) which is manageable for non coders as very important. The *Migrate* module is for developers. A good alternative for site builders could be the *Feeds* module.

In Drupal 7, I used the [Feeds](https://www.drupal.org/project/feeds) several times. It is complex (as a migration is conceptually complex) but it was really worth using it. There is also an early [Backdrop version of Feeds](https://backdropcms.org/project/feeds) Has anyone tested it?

**Comment by Dinornis** [comment]
Why are there still so many websites running D6?
What keeps their owners from upgrading to D7/D8 or moving to a diferent platform?

**Comment by serundeputy** [comment]
Most likely they are still on D6 due to the cost and planning to undertake the move to D7, D8 or Backdrop.

Typically this will require a migration and a theme rebuild at the very least.

**Comment by Graham-72** [comment]
Yes, several hours of work perhaps?

**Comment by serundeputy** [comment]
> Yes, several hours of work perhaps?

Depends on the site; I've been involved with sites that take 6 months to a year worth of work, but yes several hours for a modest site with a couple content types and a one-to-one correspondence with theme (no redesign).

**Comment by Egarbeil** [comment]
@Dinornis - unless you work for free, your clients have to be willing and able to pay for the migration from D6 to another CMS (whether D7, backdrop, D8, Wordpress, etc.).  My experience (and I have a lot of it) is that getting clients to pay for an upgrade unless there's a compelling business advantage is fairly difficult. That can be a very large part of the problem.  They don't really care if the CMS is obsolete.

**Comment by BWPanda** [comment]
I'm gonna call this question sufficiently answered.
