### ISSUE TITLE
Getting Started with Testing

### ISSUE THREAD

**Issue by Dinornis** [backdrop/backdrop-issues#2442]
I would like to try to help with testing.  Sorry, if there is already an issue that explains this, I could not find it.

* There are 23 issues for the 1.6.0 milestone, which one should I start with?
* What do I need to get started?
* I only see the Master branch.  Is there a DEV version I need to download for testing?

Thank you.

**Comment by jlfranklin** [comment]
Because of the way Github manages access control, the issue queue is here in this otherwise empty repository, while the Backdrop code itself lives in the [backdrop/backdrop](https://github.com/backdrop/backdrop) repository.  The 1.x branch there is the current head of development.  

If you are setting up your own testing environment, you may want to look at #2439.  It improves the requirements checks and test case setup for some tests.  The patch there makes it more obvious what you need to do to get all the tests to pass.

**Comment by Dinornis** [comment]
Thank you John, now I know where to download the latest development version.

In terms of testing, I think you are probably talking about some type of automated testing.  I am not a coder and was thinking of manual testing from the site builder / end user perspective.

Would that be helpful?

**Comment by serundeputy** [comment]
Hi @Dinornis !
Yes, yes, yes testing is welcome and very helpful.

Every issue that has a Pull Request (`PR`) associated with it spins up  development/testing sandbox that you can visit, test the issue at hand, and report back on your findings.

For example this issue: #2402 has a `PR` and is labeled `status - has pull request`.
![issue-anonotation](https://cloud.githubusercontent.com/assets/6763671/21578864/9bb547a0-cf5f-11e6-8dbf-158429b4168f.png)

We try to put links to the latest `PR` at the bottom of the original post
  * Click a link to a `PR` and you can see the links to the sandbox with the new code to test:
![sandbox-sites](https://cloud.githubusercontent.com/assets/6763671/21578876/071bdc48-cf60-11e6-8e3f-6e84679ba385.png)


You can also download these `PR`'s locally for more thorough examination, testing and editing with git.

<img width="706" alt="screen shot 2016-12-31 at 1 51 43 pm" src="https://cloud.githubusercontent.com/assets/6763671/21578882/50822fa4-cf60-11e6-86ba-1eb8672e6455.png">

Hope that helps get you started.

Feel free to ask follow up questions! 

thanks for the help and intereset!
~Geoff

**Comment by Dinornis** [comment]
Thanks Geoff, much appreciated.
Do I have to worry about concurrent logins with these testing boxes or anything like that?  I don't want to hinder / cause trouble for someone else logged in.

**Comment by serundeputy** [comment]
no, you can test away.   if you believe a sandbox is messed up beyond repair we can request that it be rebuilt by having a maintainer close and reopen the PR in question.

**Comment by quicksketch** [comment]
Welcome @Dinornis! Yeah we're right at crunch time this weekend as feature freeze is tomorrow. Backdrop 1.6.0 comes out Jan 15.

Like Geoff said, the best thing to do is to use the sandboxes and test out the functionality, then leave feedback in the associated issue. Sometimes it gets overwhelming because we might have 5 or 6 pull requests all related to the same issue, which is why we try to keep the main thread of conversation in the issue, as pull requests may be closed or replaced several times.

Direct links for listings that need help:

Issues that have pull requests that need review: https://github.com/backdrop/backdrop-issues/labels/pr%20-%20needs%20review
Issues that simply "need feedback" (usually just opinions): https://github.com/backdrop/backdrop-issues/labels/status%20-%20needs%20feedback

I've also sent you a GitHub invite to join the Docs & Organization team, which will allow you to label issues. If something needs work, feel free to retag it as "pr - needs work". Or if you think it is ready, retag as "pr - reviewed and tested".

**Comment by Dinornis** [comment]
Thanks guys, that is very useful. I will try to be helpful where I can, although my time availability can be quite sporadic.  I am still not sure I understand what happens when to admins are logged into a PR site at the same time without stepping on each others toes.

**Comment by BWPanda** [comment]
Question seems to be answered. Closing.
