### ISSUE TITLE
Update normalize.css to 5.0

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#2460]
Sort of a spin-off from https://github.com/backdrop/backdrop-issues/issues/2311, where we're dealing with inconsistent browser behaviors for `abbr[title]` CSS. Firefox now adds a dotted underline, while all other browsers use a bottom-border.

Of course, normalize.css is supposed to handle these sorts of discrepancies, and it does, but our version is too old. Let's update to squash these new cross-browser differences. We are currently running 3.0.1, and the latest version is 5.0.0.

**Comment by quicksketch** [comment]
Would love to have this updated for 1.6.0. @wesruv and any other front-enders want to weigh in here?

The overall change list here seems pretty minimal, most of the changes seem like reorganizing the existing rules, plus slight expansion to cover newly discovered inconsistencies. There's also a small bit of refinement, so overriding rules target exactly what it different (e.g. targeting `border-width: 0` instead of `border: none`).

**Comment by klonos** [comment]
👍 on keeping 3rd party libraries/utilities/thingies we use up to date. If we spot any quirks here and there because of the update, we can fix them individually. Upgrading to newer version get us improvements and fixes for free and it seems that with normalize.css specifically we are a couple of years behind and there's a tone of change in the meantime: https://github.com/necolas/normalize.css/blob/5.0.0/CHANGELOG.md

**Comment by quicksketch** [comment]
Great, I've merged in https://github.com/backdrop/backdrop/pull/1730 for 1.6.0. The effect on Basis and other core themes is 0% in my before/after checking. But if anything does crop up we can address it separately.
