### ISSUE TITLE
Backdrop console needs Backdrop to remember the conf_path

### ISSUE THREAD

**Issue by jlfranklin** [backdrop/backdrop-issues#2464]
The function `find_conf_path()` will take a hostname and path, then use the array set in `sites/sites.php` to determine the right sites directory.  It is called by`conf_path()` with the values in `$_SERVER`.

Backdrop Console ([b](/backdrop-contrib/b)) can call `find_conf_path()` to get the configuration path, but won't have a `$_SERVER` array, and `conf_path()` will always return the default `settings.php`, unless `find_conf_path()` remembers the path found the first time and returns that blindly.

See backdrop-contrib/b#12 for more details.

---

PR: https://github.com/backdrop/backdrop/pull/1742

**Comment by jlfranklin** [comment]
The PR attached is a hack, but it's the minimum necessary to get backdrop-contrib/b#12 to work.  Other possible solutions:

* Change `conf_path()` to accept an optional array with the overrides for the `$_SERVER` values
* Make `conf_path()` work differently if run through PHP's CLI.
* Copy over large parts of bootstrap to b.

**Comment by jlfranklin** [comment]
> Change conf_path() to accept an optional array with the overrides for the $_SERVER values

Changed the PR to go with this option.

**Comment by quicksketch** [comment]
Thanks @jlfranklin! The PR looks pretty good. I like the additions to make Backdrop a bit more multisite friendly on new installs.

Regarding the changes to `conf_path()`, it seems that these changes could be worked-around in `b` or other command line tools by setting the $_SERVER variables to be the required values, but that doesn't seem very legit. So I think the principle of passing in values into $conf_path is a good one.

Considering we're only dealing with two variables ($script_name and $http_host), and its unlikely to need additional values in the future, I think we might be better off adding two parameters to `conf_path()` rather than an `$options` array. What do you think?

**Comment by quicksketch** [comment]
This PR needs rerolling after merging https://github.com/backdrop/backdrop/pull/1724.

**Comment by jlfranklin** [comment]
Rerolled.  I had to close and re-open the PR to get the merge test to work, even though the 5.3 and 7.0 tests themselves ran fine.

**Comment by BWPanda** [comment]
Because of its age, and the fact that there are new PR's against `b` that don't require changes to core to support multisites, I'm going to close this issue. Feel free to re-open though if these changes are still desired in core.
