### ISSUE TITLE
Regional settings form: None of the options get saved besides the "Time zone for new users" setting.

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#2478]
At admin/config/regional/settings, and selected `Users may set their own time zone.` But the setting doesn't stick after saving.

I've tried this on a relatively clean install. If no one else can confirm I'll try again on a completely fresh install.

---
PR by @jlfranklin at https://github.com/backdrop/backdrop/pull/1783

**Comment by jlfranklin** [comment]
Does that form user `system_settings_form()`?

**Comment by Dinornis** [comment]
The form id is system-regional-settings, is that what you meant?  I would be glad to dig further if you let me know where.

**Comment by Dinornis** [comment]
Here is part of the code from `system.admin.inc`:

  $configurable_timezones = $system_date->get('user_configurable_timezones');
  $form['timezone']['configurable_timezones'] = array(
    '#type' => 'checkbox',
    '#title' => t('Users may set their own time zone.'),
    '#default_value' => $configurable_timezones,
  );

  $form['timezone']['configurable_timezones_wrapper'] =  array(
    '#type' => 'container',
    '#states' => array(
      // Hide the user configured timezone settings when users are forced to use
      // the default setting.
      'invisible' => array(
        'input[name="configurable_timezones"]' => array('checked' => FALSE),
      ),
    ),
  );
  $form['timezone']['configurable_timezones_wrapper']['empty_timezone_message'] = array(
    '#type' => 'checkbox',
    '#title' => t('Remind users at login if their time zone is not set.'),
    '#default_value' => $system_date->get('user_empty_timezone_message'),
    '#description' => t('Only applied if users may set their own time zone.')
  );

  $form['timezone']['configurable_timezones_wrapper']['user_default_timezone'] = array(
    '#type' => 'radios',
    '#title' => t('Time zone for new users'),
    '#default_value' => $system_date->get('user_default_timezone'),
    '#options' => array(
      BACKDROP_USER_TIMEZONE_DEFAULT => t('Default time zone.'),
      BACKDROP_USER_TIMEZONE_EMPTY   => t('Empty time zone.'),
      BACKDROP_USER_TIMEZONE_SELECT  => t('Users may set their own time zone at registration.'),
    ),
    '#description' => t('Only applied if users may set their own time zone.')
  );

  return system_settings_form($form);

**Comment by serundeputy** [comment]
@jlfranklin 
Possibly related: https://github.com/backdrop/backdrop-issues/issues/2473

I've not looked into this (#2478) issue but #2473 is using `system_settings_form()`.

**Comment by jlfranklin** [comment]
Ah... I think I know what's going on with both of them.  

(Pulling this from memory, I need to confirm with some tests.)

Checkbox elements act differently compared to other elements.  If they're checked, they return a value, often (string) "1", but it can be anything if you add `'#value' => $foo` to the form.  If it's not checked, nothing at all is returned, and the `$form_state['values']` array does not even have an entry for the checkbox element.  `system_settings_form_submit()` needs to notice which checkbox elements are missing and mark them as unset.

**Comment by klonos** [comment]
Could be unrelated. Was that form working prior to 1.6.0?

I see that [`system.date.json` has this](https://github.com/backdrop/backdrop/blob/1.x/core/modules/system/config/system.date.json#L6):

```json
    "user_timezone_configurable": 1,
    "user_timezone_default": 0,
    "user_timezone_warn": 0,
```

...while in [`system.admin.inc`, `system_regional_settings()`](https://github.com/backdrop/backdrop/blob/1.x/core/modules/system/system.admin.inc#L1872) we save/retrieve these as `user_configurable_timezones`, `user_default_timezone` and `user_empty_timezone_message`.

**Comment by klonos** [comment]
...also, I see that `system_regional_settings()` has no respective `system_regional_settings_submit()` handler.

**Comment by klonos** [comment]
...but could be wrong (rookie).

**Comment by jlfranklin** [comment]
I'll dive into it and submit a PR.

**Comment by jlfranklin** [comment]
First off, to whoever originally wrote this, I feel your pain.  I've done the same, and while I was writing #675, no less.

What's in a name?

The form calls that field `configurable_timezones`, so that is what `system_settings_form_submit()` uses.  In most of the code, it's referenced as `user_configurable_timezones`, except in two places: core/modules/date/date.inc:794 and core/modules/system/config/system.date.json:6, where it is called `user_timezone_configurable`.

The simplest patch would be to rename the form element, the reference in date.inc and the system.date.json default to `user_configurable_timezones`, but I don't like to rename form elements like that.  It can break `hook_form_alter()` in contributed modules.  The other two options are renaming the variable (even worse), and adding a custom submit handler to deal with the one item.

Which solution do you guys prefer?

**Comment by klonos** [comment]
The test failures are random (https://github.com/backdrop/backdrop-issues/issues/1478#issuecomment-257330354), but this (as well as #2473) happened at some point because we obviously we do not have tests in place that cover these forms. So I think that tests are in order here.

Now, I'm not sure whether we should be changing `user_timezone_configurable` to `user_configurable_timezones` or the other way around (I kinda like the consistency of the `user_timezone_*` set of settings in the .json file), but the "Remind users at login if their time zone is not set." checkbox doesn't get saved either. As I mentioned in my comment above, that's because of the inconsistency with `user_timezone_warn` (the setting saved in the `system.date.json` file) and `user_empty_timezone_message` (the setting as used in code). So this needs to be updated too. Let's do it in a single PR.

**Comment by klonos** [comment]
...the funny thing is that the "Time zone for new users" setting (radio options) does get saved despite the inconsistency between `user_timezone_default` and `user_default_timezone` (wonder why that is the case?).

**Comment by klonos** [comment]
...actually, that seems to be the only setting that gets saved in that form. Try to change the "Default country", "First day of week" and "Default time zone" and save the form. You'll see that these settings are not retained despite the "The configuration options have been saved." message.

**Comment by jlfranklin** [comment]
> Now, I'm not sure whether we should be changing user_timezone_configurable to user_configurable_timezones or the other way around.

There are downsides to each.  Either external readers of the value will need to check the version of Backdrop or modules implementing a `hook_form_alter()` will need to do the same.  I can't think of a concrete case of either, so it may not matter in this case, but at the same time I'd like to set a precedent for how to handle such situations.

To make it fully backwards compatible, the `Config` object would need to know there are old aliases, map all of them to the same config item, and generate `WATCHDOG_DEPRECATED` warnings for the non-canonical aliases.

> So this needs to be updated too. Let's do it in a single PR.

Agreed.

**Comment by herbdool** [comment]
Thanks for taking this on @jlfranklin. I discovered this issue while working on a PR for webform and I noticed the variable had changed from Drupal 7. Webform uses the variable for its date component. I updated it to user_timezone_configurable but it's not too late to change.

**Comment by klonos** [comment]
>To make it fully backwards compatible, the `Config` object would need to know there are old aliases, map all of them to the same config item, and generate `WATCHDOG_DEPRECATED` warnings for the non-canonical aliases.

Yes! Absolutely yes 👍 but how do we do that? Should we be creating some sort of "registry" of old config item names? We could just leave the old items in place and change their value to some sort of "redirect". Something like so:

```json
    "user_timezone_configurable": "config_redirect:system.date.user_configurable_timezones",
    "user_timezone_default": "config_redirect:system.date.user_default_timezone",
    "user_timezone_warn": "config_redirect:system.date.user_empty_timezone_message",
    "user_configurable_timezones": 1,
    "user_default_timezone": 0,
    "user_empty_timezone_message": 0,
```

**Comment by herbdool** [comment]
If a contrib module is calling for "user_timezone_configurable" but it's deprecated then we do need to account for that in this issue, IMO. Calling `config_get('system.date', 'user_timezone_configurable');` in the contrib module needs to find the new variable somehow.

**Comment by jlfranklin** [comment]
> We could just leave the old items in place and change their value to some sort of "redirect".

My initial thought was to add it to `hook_config_info()` as an optional value `aliases`.  The `aliases` would be an array mapping old values to new values.  It would be hard to tell the difference between a string and an intentional alias in the JSON, unless we set aside a special key for it.

**Comment by herbdool** [comment]
So your thought is that hook_config_info() can accept aliases and then we'd have date_config_info which lists the aliases?

**Comment by jlfranklin** [comment]
> So your thought is that hook_config_info() can accept aliases and then we'd have date_config_info which lists the aliases?

Actually, `system_config_info()`, since it's part of the System module's `system.date`, but yes.

The `hook_config_info()` returns information that the `Config` object couldn't care less about, and is implemented by a lot of modules that have no aliases.  A new `hook_config_aliases()` may be in order.

**Comment by klonos** [comment]
During the dev meeting today, we decided to give this a few more days and if we don't fix things, then revert the changes from ??? and release a 1.6.1 perhaps even as soon as next week. Backdrop 1.6.0 as it is now feels really broken in many places and there could be forms that are not so often used that we have not discovered yet that are broken.

Point is to either fix this situation or revert the change that causes it. We can re-introduce ??? at a later stage, but I also would like us to write tests for the forms that we discovered that got broken so that things like this don't happen again in the future.

**Comment by jenlampton** [comment]
Assigning to @quicksketch so he can prepare for a release next Friday 2/10, one way or another.

**Comment by jenlampton** [comment]
sorry, wrong issue. please ignore my PR and label changes...  nothing to see here!

**Comment by jlfranklin** [comment]
On Gitter.im, @jenlampton  said:
> I thought it was #675
> we should find the commit so that we can revert it easily. @jlfranklin if you know which one it was please let us know

Looking back through the commits, the immediate issue is, indeed, from #675 (backdrop/backdrop@08217b253f5abaf238115851e4261a3a3aaf5ba3), specifically this hunk:

```diff
@@ -2040,31 +1926,7 @@ function system_regional_settings($form, &$form_state) {
     '#description' => t('Only applied if users may set their own time zone.')
   );
 
-  $form['actions']['#type'] = 'actions';
-  $form['actions']['submit'] = array(
-    '#type' => 'submit',
-    '#value' => t('Save configuration'),
-  );
-  return $form;
-}
-
-/**
- * Form submission handler for regional settings.
- *
- * @ingroup forms
- * @see system_regional_settings()
- */
-function system_regional_settings_submit($form, &$form_state) {
-  config('system.date')
-    ->set('default_country', $form_state['values']['site_default_country'])
-    ->set('first_day', $form_state['values']['date_first_day'])
-    ->set('default_timezone', $form_state['values']['date_default_timezone'])
-    ->set('user_configurable_timezones', $form_state['values']['configurable_timezones'])
-    ->set('user_empty_timezone_message', $form_state['values']['empty_timezone_message'])
-    ->set('user_default_timezone', $form_state['values']['user_default_timezone'])
-    ->save();
-  // Display status messages for this form.
-  backdrop_set_message(t('The configuration options have been saved.'));
+  return system_settings_form($form);
 }
 
 /**
```

In the old submit handler, the form's `*_timezone` elements are saved in `system.date` with a `user_` prefix added to them, whereas `system_settings_form_submit()` will use the form element names.  (There is a similar issue with one of the Simpletest forms and a DB Log form.)

However, confusion over the name goes back to #179 (backdrop/backdrop@c3d026ab1437382ff3a026fbd8c45451598100ee) where @quicksketch used `user_configurable_timezones` consistently in the code, but put `user_timezone_configurable` in the `system.date.json` file.  I think the entry in the `system.date.json` file led @Graham-72 to use `user_configurable_timezones` in #478 (backdrop/backdrop@8be71667004cf14ebaf4f8f15326c5ce9d99ef63 core/modules/date/date.inc:794).

We can:

- revert the affected forms and correct the settings name in `date.inc` and `system.date.json`
OR
- Update all instances of `user_configurable_timezone` to use `user_timezone_configurable`.
OR
- Use the PR backdrop/backdrop#1781 to map all variations of the setting name to one name (including form elements)

I'm in favor of the last as it provides a mechanism to deprecate old configuration settings names and prevents any config modules from breaking if they inspect setting by the old name or update the form via `hook_form_alter()`. 

How would you guys like to handle this?

**Comment by jenlampton** [comment]
> revert the affected forms

This is my biggest concern. We don't know how many places in core have been affected by this change. Are there other forms that are also affected that we don't know about yet, just because no one has encountered or reported the problem? 

Re this instance: my guess is that the key in the config file exactly matches the variable name as it was in Drupal 7. My preference would be not to change that, as there may be contrib modules checking these core variables. If we want to keep the use of `system_settings_form()` here, it might be better to change the form element keys.  Form structure is not technically an "API" so we can change it in the 1.x cycle. I expect it's less likely that changing a form element key will affect contrib than changing the config/variable name.

Another option would be to have a few places in core where we deliberately don't use `system_settings_form()`. Doing things "long hand" in places where the form element keys don't match the variables would mean we could keep both the form structure and the variable names, thus not impacting contrib at all.  I think this would be my preference for 1.x.

**Comment by jlfranklin** [comment]
> This is my biggest concern. We don't know how many places in core have been affected by this change. Are there other forms that are also affected that we don't know about yet, just because no one has encountered or reported the problem?

No, we know exactly how many places, because we can see which forms had form element/config setting name mismatches in the patch for #675.

> @jlfranklin was this what you had in mind with `revert the affected forms and correct the settings name in date.inc and system.date.json`?

It is.  Specifically, reverting this form, plus the two cited above for DB Log and Simpletest.

**Comment by jenlampton** [comment]
> It is. Specifically, reverting this form, plus the two cited above for DB Log and Simpletest.

Fantastic :) Let's do that then for Friday's release, and we can create follow-ups if we want to switch those forms back to using `system_settings_form()` in the future.

**Comment by herbdool** [comment]
Even if we revert, there will be a mismatch, right @jlfranklin? In webform I had switched to user_timezone_configurable because that's what was in the json file (https://github.com/backdrop-contrib/webform/commit/3373defad0f4c46d39d0ea1063b59d5cb6023c5e). I can change that in webform but I'll need to know which variable will work.

**Comment by jlfranklin** [comment]
The patch hunk you see above is what will be undone.  Backdrop will use `user_configurable_timezones`.

**Comment by jlfranklin** [comment]
And the system.date.json file will be updated to replace `user_timezone_configurable` with `user_configurable_timezones`.  The date.inc usage will be corrected, too.

**Comment by jlfranklin** [comment]
@herbdool, if you used any of the other settings from `system.date.json`, check against this patch:

```diff
@@ -3,9 +3,9 @@
     "first_day": 0,
     "default_country": "",
     "default_timezone": "UTC",
-    "user_timezone_configurable": 1,
-    "user_timezone_default": 0,
-    "user_timezone_warn": 0,
+    "user_configurable_timezones": 1,
+    "user_default_timezone": 0,
+    "user_empty_timezone_message": 0,
     "formats": {
         "long": {
             "label": "Long Date",
```

**Comment by Dinornis** [comment]
Sorry, I don't see a link to the correct PR.

**Comment by jlfranklin** [comment]
@dinornis,
https://github.com/backdrop/backdrop/pull/1783

**Comment by Dinornis** [comment]
Thanks @jlfranklin I just tested the PR and it seems to be working okay.

**Comment by quicksketch** [comment]
Thanks @jlfranklin for the PR!

Regarding this change:
 ```
     "default_timezone": "UTC",
-    "user_timezone_configurable": 1,
-    "user_timezone_default": 0,
-    "user_timezone_warn": 0,
+    "user_configurable_timezones": 1,
+    "user_default_timezone": 0,
+    "user_empty_timezone_message": 0,
```

We probably want to avoid changing the actual config keys that are stored. If needed, it would be better to replace the names of the elements in the form if needed to match the original config keys. But as we're manually saving this form again now, we could leave both as-is.

**Comment by jlfranklin** [comment]
@quicksketch, added the `hook_update_N()`.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/1783 into 1.x for 1.6.1, thanks @jlfranklin!
