### ISSUE TITLE
Migrating to core entity functionality from contrib entity_view_mode module?

### ISSUE THREAD

**Issue by jackaponte** [backdrop/backdrop-issues#2480]
I'm excited to begin using entity view modes as part of the core Entity module!

I had to wrangle with errors on trying to apply the core 1.6.0 update with `entity_view_mode` still enabled:

```PHP Fatal error:  Cannot redeclare entity_view_mode_load() (previously declared in /var/www/test/core/modules/entity/entity.module:34) in /var/www/test/modules/entity_view_mode/entity_view_mode.module on line 157```

After disabling the contrib module I was able to successfully update my site, but I can't see any way to migrate my view modes created with the `entity_view_mode` contrib module into the new core functionality.

For now I'll just recreate them by hand, but should we give users of the `entity_view_module` a heads up before they upgrade? And is there a migration path for existing entity view modes that I'm missing, or might it be possible to add one?

---

PR by @quicksketch: https://github.com/backdrop/backdrop/pull/1762

**Comment by serundeputy** [comment]
ugh; I was not even aware of `entity_view_mode` in backdrop-contrib.  

Yes, we should provide a warning and an upgrade path. Marking as `1.6.1` bug.

thanks @jackaponte

**Comment by quicksketch** [comment]
I'll take a crack at this.

**Comment by quicksketch** [comment]
I made a PR at https://github.com/backdrop/backdrop/pull/1762. It should handle both D7 and Backdrop contrib `entity_view_mode` module. Conveniently, the data model is identical. Also interesting because the view mode state (enabled/disabled) is stored in Field module, that automatically works without any effort at all. The only thing that needs to be pulled in is the list of new view modes.

This also adds the `entity_view_mode` module to the list of merged modules, so it will prevent the contrib module from being re-enabled later:

![screenshot from 2016-08-31 21-26-45](https://cloud.githubusercontent.com/assets/100206/22133883/f4e0cc2e-de77-11e6-9e59-004354889f13.png)

Anyone up for doing another round of testing?

- Upgrade from a D7 site with Entity View Modes enabled and configured.
- Upgrade from a Backdrop 1.5.x site with Entity View Modes enabled and configured.

It doesn't look like the contrib module in Backdrop supported an upgrade from D7, so this actually fixes a deficiency for sites upgrading from D7.

**Comment by jackaponte** [comment]
Wow, thanks for the quick work, @quicksketch!

I'll admit I don't really know how to check out a specific pull request to test those changes...but I started with a Backdrop 1.5.2 site with Entity View Modes enabled and configured, downloaded Backdrop 1.6.0, manually applied your [pull request's changes](https://github.com/quicksketch/backdrop/commit/2b89a1e273c753680e5f7e98e606b8fd894f7b15), then ran the database updates. Worked like a charm, entity view modes were properly migrated to the core Entity module.

**Comment by klonos** [comment]
> I don't really know how to check out a specific pull request to test those changes...

@jackaponte what I do is visit the PR link (usually posted in the first comment of an issue), then switch to the "Commits" tab and click on the "< >" button that shows "Browse the repository at this point in the history" when you hover over it:

![backdrop-github-getting_to_the_pr_branch](https://cloud.githubusercontent.com/assets/2423362/22174439/f9bf7bf2-e032-11e6-9b80-08baa0162bb6.png)

...then I click the big, green "clone or download" button (as I would do in the original Backdrop repo) and download the zip file:

![backdrop-github-download_a_version_of_core_with_the_pr_changes](https://cloud.githubusercontent.com/assets/2423362/22174447/20fa95bc-e033-11e6-93d7-69697eabd037.png)

😉

**Comment by jackaponte** [comment]
Thanks @klonos! Super helpful. I'll give that method a try next time around.

**Comment by quicksketch** [comment]
Great, well with my own testing and @jackaponte's confirmation, let's mark this RTBC for 1.6.1.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/1760 for 1.6.1.
