### ISSUE TITLE
[UX] Admin / Seven theme - style exposed filters more like operations, and vice versa

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2513]
On admin views it bothers me that the exposed filters do not have a pretty white background / gray border, and the bulk operations do. This seems to give unnecessary attention to the bulk operations.

What if we reversed the style, and instead added the highlight to the filters, instead of the bulk operations?

Before:
![screen shot 2017-02-02 at 3 47 27 pm](https://cloud.githubusercontent.com/assets/397895/22573712/1adc9894-e95f-11e6-987d-3f9182672669.png)

After:
![screen shot 2017-02-02 at 4 00 30 pm](https://cloud.githubusercontent.com/assets/397895/22573989/cc573600-e960-11e6-8046-805a540e1f24.png)

---
PR by @jenlampton: https://github.com/backdrop/backdrop/issues/1777

**Comment by jenlampton** [comment]
In the PR at https://github.com/backdrop/backdrop/pull/1777 I removed the fieldset around all views bulk operations. I don't think it makes much sense for this to be a fieldset, but then I'm also not sure it can be removed in the 1.x cycle.

**Comment by klonos** [comment]
I think I like it better with the border around the filter section too. If we cannot remove the fieldset in the 1.x cycle (because people are using exposed filters in their front-end and such a change might end up messing their themes), perhaps then we could remove the border from the fieldset with CSS and leave the fieldset removal for 2.x ...or not do it at all.

Either way, if we remove the fieldset, we'd need to add ([or rather unhide](https://github.com/backdrop/backdrop/blob/1.x/core/modules/views/handlers/views_handler_field_bulk_form.inc#L127)) the label of the operations drop-down menu (because we lose the "Operations" fieldset label).

**Comment by jenlampton** [comment]
> Either way, if we remove the fieldset, we'd need to add (or rather unhide) the label of the operations drop-down menu (because we lose the "Operations" fieldset label).

You don't think the `Choose an action` text is clear enough?

**Comment by klonos** [comment]
Yah, you are right @jenlampton. RTBC from me 👍  ...do you think perhaps set a milestone?

**Comment by klonos** [comment]
...can you please also close and re-open the PR to refresh the sandbox?

**Comment by jenlampton** [comment]
voila: https://github.com/backdrop/backdrop/pull/1777

**Comment by quicksketch** [comment]
I like this change as well, but let's target it for 1.8.0, not that long of a wait.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/1777 into 1.x for 1.8.0. Thanks @klonos and @jenlampton!
