### ISSUE TITLE
Autocomplete needs theming 

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#2517]
Two issues came up working on https://github.com/backdrop/backdrop-issues/issues/1206#issuecomment-277214181
- the autocomplete DIV's 1px solid border doesnt match Seven's CSS and extends wider than the textfield. In short, its ugly.
- autocomplete DIV goes under the actions area in dialogs. Something to do with z-indexes I imagined but a scrollbar also shows up, which suggests an overflow issue maybe. I couldnt figure it. The dialog has a z-ndex of 9996 and the modal overlay 9995. But changing autocomplete index to 9999 didnt help. Image below. Note there were more items in the select list (below `admin (user)`), but they are hiddn under the grey actions area. Note also a scrollbar.
![autocomplete](https://cloud.githubusercontent.com/assets/1042283/22605287/3c2b0396-ea1d-11e6-999a-2564ecbbaf0d.PNG)

- the autocomplete list items seem to have transarent gaps between them in Basis
![acbasis](https://cloud.githubusercontent.com/assets/1042283/22605363/85c58f58-ea1d-11e6-93c3-a1ab0273b879.PNG)

---
PR from @jenlampton at https://github.com/backdrop/backdrop/pull/1840

**Comment by jenlampton** [comment]
Here are some screenshots for review:

Seven:
<img width="544" alt="seven" src="https://cloud.githubusercontent.com/assets/397895/25256660/4e3fcf02-25e7-11e7-9d4a-d8eee5404209.png">

Basis: 
<img width="529" alt="basis" src="https://cloud.githubusercontent.com/assets/397895/25256662/520a9b58-25e7-11e7-9578-395d7c9fb178.png">

**Comment by jenlampton** [comment]
> and extends wider than the textfield.

In the modal (or any time a form element is sized down) the jQuery function `.innerWidth()` does not return the correct width for the autocomplete options because the input field itself is sized down in css via `max-width: 100%;` so the computed width is wider than the space available. It looks like setting the "right" property via inline CSS will fix this in most cases. Pushing an update to the PR now.

**Comment by jenlampton** [comment]
Speaking of jQuery doing the math wrong, it also looks like on small screens the autocomplete doesn't know where to position itself: 

<img width="692" alt="screen shot 2017-04-20 at 7 40 16 pm" src="https://cloud.githubusercontent.com/assets/397895/25260483/6900390c-2601-11e7-8af2-1bceaba115bc.png">

**Comment by jenlampton** [comment]
> autocomplete DIV goes under the actions area in dialogs

Okay, I believe I fixed both the jQuery math problem and the overflow problem

Seven: 
<img width="641" alt="screen shot 2017-04-20 at 8 13 00 pm" src="https://cloud.githubusercontent.com/assets/397895/25262268/d2798ea6-260b-11e7-990f-15b5d76f2beb.png">

Basis: 
<img width="554" alt="screen shot 2017-04-20 at 8 13 30 pm" src="https://cloud.githubusercontent.com/assets/397895/25262279/e0d82192-260b-11e7-8160-decff1bc3bf3.png">

I updated the PR. What's left is fixing the window-resize code.

**Comment by klonos** [comment]
> Okay, I believe I fixed both the jQuery math problem and the overflow problem

👍 👏 ...have you noticed the dropdown lost of options being a couple of pixels narrower than the autocomplete field on Basis on its right side though?

**Comment by klonos** [comment]
...also, when you hover over one of the options in the list, the blue background could use some padding:

![image](https://cloud.githubusercontent.com/assets/2423362/25269741/4afb6e3e-26c1-11e7-956b-74d04072b6d7.png)

...either that or have the background span across the entire line.

Then, what about adding zebra stripping in the drop-down list of options and how do we handle text that spans wider than the list?

**Comment by klonos** [comment]
...that's in Seven. In Basis, there's no background color at all when you hover over the options in the list.

**Comment by jenlampton** [comment]
Tell me what you want changed and I'll do it...
1) zebra striping (in seven? basis? all themes?)
2) hover color (in basis? all themes?)
3) fix the 2 pixel issue (it's the border width, yes, I noticed but was hoping no one else would ;)

**Comment by docwilmot** [comment]
This looks great @jenlampton. I'd say once the resize issue is fixed this is MVP and mergeable, since its blocking that other PR.
re the other stuff, I dont think zebra striping is necessary in a small single column list; thats more useful if you want to align values across table columns. Any hover color is fine for me as long as it matches another theme color

**Comment by quicksketch** [comment]
I'll take a stab at fixing the resize issue.

**Comment by quicksketch** [comment]
I've updated the PR at https://github.com/backdrop/backdrop/pull/1840. Things got a little out of hand fixing the resizing.

- We should use the "optimizedResize" ability added in #1489 to position the autocomplete popup. But because the dialog did not yet use the optimizedResize, I was seeing sync issues if the dialog is moving on resize separately from the autocomplete popup. Thus the updated PR switches both the dialog and autocomplete to use optimizedResize.

Additionally I found that optimizedResize needs to support removing resize events, otherwise you end up with a memory leak as the autocomplete dialog is replaced on every character typed.

So we ended up with a lot more code changed than just "styling", but I think we have nearly all the issues with autocomplete and the dialogs solved at this point.

I updated the styling slightly in both Basis and Seven. Here are the implementations currently:

![selection_197](https://cloud.githubusercontent.com/assets/100206/25309553/30ef2eee-2785-11e7-9fe9-c3a9feb02378.png)

![selection_198](https://cloud.githubusercontent.com/assets/100206/25309554/33bc0f2a-2785-11e7-8d53-bfc49eeb130b.png)

**Comment by jenlampton** [comment]
Looks great!!!

**Comment by serundeputy** [comment]
I pulled this down and tested locally on bartik, basis and seven. Full screen and small screens. Looks great!

Marking as RTBC.

**Comment by serundeputy** [comment]
Great work everyone.  Merged into `1.x` will ship with `1.7`.

**Comment by serundeputy** [comment]
Backported to `1.6.x` too for shipment with `1.6.4`.
