### ISSUE TITLE
[DX] Allow theme_image() to use the D7 'path' instead of 'uri'

### ISSUE THREAD

**Issue by jlfranklin** [backdrop/backdrop-issues#2521]
Drupal 7's `theme_image()` took `path` for the path to the image, but Backdrop uses `uri` instead.  Old modules should still be allowed to use `path` with a deprecation warning.

---
~PR by @jlfranklin: https://github.com/backdrop/backdrop/pull/1786 (path is supported but deprecated)~
PR by @quicksketch: https://github.com/backdrop/backdrop/pull/1941 (path is allowed permanently)

**Comment by klonos** [comment]
👍 @jlfranklin ...minor coding standard issue with the `watchdog` function and a newbie suggestion to consider or dismiss. Other than that PR looks OK to me. Thanx.

**Comment by jlfranklin** [comment]
@klonos, updated the patch per the review:

* lowercase 'image'
* don't wrap call arguments

**Comment by quicksketch** [comment]
A couple of thoughts here:

- I think it may be better to put this new code in a preprocess function instead, say `template_preprocess_image`, so that we don't have backwards compatibility code in `theme_image()`.
- I'd also be tempted to allow `path` permanently, and not throw a deprecated warning in the first place. We're still passing in paths (not URIs) to theme_image() all over the place. Should we just let either be used and distill them down into a single variable in preprocess?

**Comment by quicksketch** [comment]
I filed a new PR at https://github.com/backdrop/backdrop/pull/1941 as an alternative that makes both "path" and "uri" permanently supported (instead of deprecating one or the other).

**Comment by quicksketch** [comment]
I'll take the 3 thumbs-ups as confirmation. :smile:

I've merged https://github.com/backdrop/backdrop/pull/1941 into 1.x for 1.8. As this is a small API addition and includes `@since 1.8.0` documentation, it won't be included in 1.7.x.

**Comment by quicksketch** [comment]
API change record filed as well: https://api.backdropcms.org/node/44993
