### ISSUE TITLE
views_autoload_info specifies bad filename for test classes

### ISSUE THREAD

**Issue by jlfranklin** [backdrop/backdrop-issues#2530]
Views includes `ViewsTestCase` and `ViewsSqlTest` in its `hook_autoload_info()` implementation because "[t]hese are used as base classes so frequently its easiest to include them in the registry rather than include them manually."

However, it maps the two to `tests/views_query.inc` instead of `tests/views_query.test`.

---
PR by @jlfranklin https://github.com/backdrop/backdrop/pull/1788

**Comment by quicksketch** [comment]
Thanks @jlfranklin! We may need to discuss this suggestion further.

The reason we don't normally use the auto-loader for test cases is because the autoloader is only available for *currently enabled modules*, and that means modules enabled by the site running the tests, not the process that is being run by the tests. So this approach would save quite a few manual `include_once` calls, but its an approach that wouldn't work for most other modules, because tests can be run on modules that are both enabled or disabled. A good example of this is that the core test suite runs for all modules, even those that are disabled by default (like the translation-related modules). If we used the autoloader within a test for a disabled module, the test wouldn't be able to find the related class.

So we have options here:

- We could just remove the lines for the tests from `views_autoload_info()`, since they're not used anyway.
- We could merge the PR as is because Views is a required module and so will always be available and the autoloader doesn't cause a problem.
- Implement an autoloader solution for tests that doesn't require modules be enabled.

Thoughts?


It does look like this would save quite a few `include_once` calls, but this approach will not work for all modules

**Comment by jlfranklin** [comment]
IIRC, this issue and PR started off when I tried to write a new views-derived test case and the base classes could not be found.  After a bit of poking around, "hey, the autoloader has the wrong filenames.  We should fix that."  That was followed up with the happy discovery that the `include_once` calls were all unnecessary.  There was no ambition to create a test-specific autoloader.  

I think I've been bitten in the distant past when testing a Drupal module by the same test-driver vs test-site split that you mention here.  It bothered me then, but I didn't have the bandwidth to look deeper into it, let alone craft a solution.  I think I was trying to use functions in the module to create test data from the test-driver side, but the module wasn't enabled in the test-driver and thus the tests failed.  Or something like that.

I'm leaning towards a hybrid of options 2 and 3: Commit as-is today, and open an issue to explore a better autoloader solution for SimpleTest tomorrow.

**Comment by quicksketch** [comment]
Thanks @jlfranklin for the feedback. Looking at the options again now, my preference is for the first option (removing the lines from the autoloader). If we set an example in Views module (or any other core module), it's one that other modules will follow. Until we an autoloader for tests, we should treat them consistently and not give Views special treatment just because it's a required module.

**Comment by Dinornis** [comment]
Removing the PR labels as there is no PR yet.  Hope that's okay.

**Comment by jlfranklin** [comment]
Cleaning up my queue.  There are two candidate PRs for this issue: backdrop/backdrop#1788 and backdrop/backdrop#2283.  The former removes many `require_once` calls and fixes the entries in the autoloader so they work as intended.  The latter leaves the `require_once` calls and removes the autoloader entries.

**Comment by herbdool** [comment]
I did a code review of https://github.com/backdrop/backdrop/pull/2283. Looks good.

**Comment by quicksketch** [comment]
Thanks @jlfranklin for the update! I've merged the second PR (https://github.com/backdrop/backdrop/pull/2283) into 1.x and 1.10.x. I think it's better to be consistent here until we have an auto-loader for test files.
