### ISSUE TITLE
"Add Existing Content" block doesn't respect the "Show author and date information" checkbox.

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#2536]
Toggling the "Show author and date information" option does nothing from what I can see.

In Backdrop 1.6.0

----
~~PR: https://github.com/backdrop/backdrop/pull/2047~~
PR by @herbdool https://github.com/backdrop/backdrop/pull/2684

**Comment by Al-Rozhkov** [comment]
I can confirm this bug. When I watch variables in hook_preprocess_node, `display_submitted` is not overwritten and `block` flag is set to false.

**Comment by olafgrabienski** [comment]
I confirm the bug as well, it's still active in Backdrop 1.8.0.

As Rabbit Hole is being ported to fix [Add a system of page-less nodes](https://github.com/backdrop/backdrop-issues/issues/100) in contrib, there are new use cases for "Add existing content" blocks, and this bug will concern more sites in the future. @Al-Rozhkov are you still/again up to have look at the issue?

**Comment by Al-Rozhkov** [comment]
Unfortunately I don't have time to work on this. Anybody can pick this up.

**Comment by serundeputy** [comment]
Added PR to check for NodeBlock in `node_view()` and then check `display_submitted` from the block form.

Website: http://2047.backdrop.backdrop.qa.backdropcms.org
Username: admin
Password: Lci5EopL

**Comment by herbdool** [comment]
@serundeputy works!

**Comment by serundeputy** [comment]
Updated PR fixing test failures.

**Comment by quicksketch** [comment]
The PR looks like it would work but it's mixing the data model (the `$node` object) with the display information (by setting `$node->display_submitted`). It shouldn't matter where the node is being rendered, the `$node` object should always just contain the node data. Instead we should be passing a variable to `theme('node')`, or in our case because this is a renderable, as `$content['#display_submitted'] = TRUE;`

We're already doing this, but it looks like this value might be getting wiped out in `template_preprocess_node()`. Could you take another look at this @serundeputy?

**Comment by herbdool** [comment]
The issue was that it was assuming the node was using a view_mode == "block" when actually the user can set it to anything. I've come up with a small PR https://github.com/backdrop/backdrop/pull/2684. Maybe @olafgrabienski you feel like testing? Thanks!

**Comment by olafgrabienski** [comment]
@herbdool Thanks for the new PR! It's working in the sandbox site, test page: http://2684.backdrop.backdrop.qa.backdropcms.org/about.

**Comment by herbdool** [comment]
PR approved by @serundeputy

**Comment by quicksketch** [comment]
Looks great! Nice and simple. Merged https://github.com/backdrop/backdrop/pull/2684 into 1.x and 1.13.x.
