### ISSUE TITLE
Add date (and time) field to core

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#254]
If possible, it would be great to add this feature shortly after release. 

[d.o issue](https://drupal.org/node/501428)

**Comment by docwilmot** [comment]
This is done!

**Comment by mikemccaffrey** [comment]
Great that this is in core, since it is a fairly standard field type. However, is there any reason that it is listed on the module page in its own "DATE/TIME" category instead of with the rest of the fields in "FIELDS"? Do you know @Graham-72?

**Comment by Graham-72** [comment]
@mikemccaffrey it was ported as a separate contributed module for use with Backdrop v1.1 and then, fortunately, @quicksketch was able to adapt it and integrate into core for v1.2 . I think it is listed separately for historical reasons, in order to handle transition for those of us who were then using the contributed module. But this possibly is not the full story.
