### ISSUE TITLE
drupal_is_denied equivalent missing from backdrop. Should we add one?

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2543]
The function `drupal_is_denied()` is not in Backdrop. It was first moved into ban module, which was later removed from Backdrop. See the Drupal change notice, here: https://www.drupal.org/node/1794068

I would like to propose we add a comparable function `backdrop_is_denied()` that does only the IP address lookup part, something like this: 

```php
function backdrop_is_denied($ip) {
  // Because this function is called on every page request, we first check
  // for an array of IP addresses in settings.php before querying the
  // database.
  $blocked_ips = variable_get('blocked_ips');
  $denied = FALSE;
  if (isset($blocked_ips) && is_array($blocked_ips)) {
    $denied = in_array($ip, $blocked_ips);
  }

  return $denied;
}
```

We'd need to decide on the proper place to do the lookup, since variable_get may not be the right place, config may not, and settings.php may not, but we should do something, shouldn't we?

**Comment by jlfranklin** [comment]
There are a lot of ways to block access by IP, well before the connection gets to Backdrop.  The simplest for most users may be in the `.htaccess` file, and doing so is [documented by web hosting providers](https://help.dreamhost.com/hc/en-us/articles/216363167-How-do-I-deny-access-to-my-site-with-an-htaccess-file-).  They can also be blocked with Varnish or other front end caching solutions, firewall software like IPTables is built to do exactly this, and services like Cloudflare provide blocking as part of their offering.

I think we would be better off documenting the `.htaccess` method, pointing out other solutions, and referring site builders to their hosting provider or local network / system administrators for solutions specific to their environment.

**Comment by quicksketch** [comment]
I agree with @jlfranklin, block IPs should be a server-level configuration rather than in the software. However if wanted to implement a Contrib-based solution, we could do so simply using `hook_init()` to check the access and end the generation of the page early for such a banned user. Although it may not be entirely efficient because it would do a full bootstrap, compared to generating a page banning a user is comparatively simple.

So in general, I don't think we should re-introduce anything into core.

**Comment by jenlampton** [comment]
I've added a change record to explain what to do with contrib modules that called drupal_is_denied, would love a review: https://api.backdropcms.org/node/44866

**Comment by klonos** [comment]
I realize that this issue here is ancient, but for historic reasons I would like to point that .htaccess is an apache-only thing (according to our [telemetry](https://backdropcms.org/project/backdrop/telemetry) 75% of Backdrop sites are using apache) and also that although any blocking should ideally be done at the server/infrastructure level rather than the application level, not everyone has access to that (referring to budget/cost, technical aptness, or lack of access to such configuration options in cheaper hosting solutions etc.).

One thing that comes up very frequently is blocking IPs that are making requests to `/wp-login.php` (bot scans). Sure, you can add something in your .htaccess to block that, or tweak the `$settings['404_fast_paths']` setting in `settings.php`, but that would only block (or fast-reject) requests to that specific path - it would not ban the IP where those requests are coming from, which mans that further scans/attacks from a known malicious IP are not blocked (which is the goal after all).
