### ISSUE TITLE
Missing explanation or submission guidelines.

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#2545]
The text I add in the 'explanation or submission guidelines' field on the form for configuring a content type is not appearing at the top of the page when creating or editing content of this type. I believe it should be in a help region in the layout?
![missingexplanation](https://cloud.githubusercontent.com/assets/10559274/23091202/577aee90-f5a8-11e6-8058-350b232e9fe6.png)

---

PR https://github.com/backdrop/backdrop/pull/1793

**Comment by quicksketch** [comment]
Thanks for filing this issue @Graham-72. I think you're right, that string doesn't end up displaying anywhere currently because of our removal of the help module. We need to display that message on the top of the node form. This might be an opportunity to introduce a help element, as we have this issue in a number of places where we need to display inline help.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/1793 into 1.x and 1.6.x. This will be in 1.6.2. Thanks @Graham-72 for reporting!
