### ISSUE TITLE
Node layout main menu drop down missing

### ISSUE THREAD

**Issue by SamStamport** [backdrop/backdrop-issues#2552]
Although the main menu configuration on node layout is identical to the home page menu the menu on the home page has drop down menu functionality, but the node layout menu does not.

**Comment by olafgrabienski** [comment]
Thanks for the report. If I understand the issue correctly, I couldn't reproduce it on a 1.6 site.

- Which Backdrop version do you use?
- What do you mean by "node layout": the Default Layout? And if yes, did you change it?

**Comment by ColumbiaBlooms** [comment]
I'm using Backdrop 1.6.0.

At http://localhost:8080/BD/admin/structure/layouts I have Home Page, Node Layout, Default Layout, and Default Administrative Layout. I'm pretty sure that Node Layout is used for displaying pages other than the home page and that Home Page layout is used for the home page because each of the four layouts is using a different template. Default Layout is different from the Node Layout. I made several changes to Home Page Layout & Node Layout.

Here's an example of what happens. On my home page I have a menu item named "About". When I hover my mouse over it another menu item "History" appears beneath it. This does not happen after I navigate to the actual About page. On the About page there is no drop down to "History" when I hover my mouse over "About".

I'd be happy to help answer other questions you may have and to gather more documentation for you. Let me know ...

One factor that may be at play here is that this site was ported from my D7 site. There may be debris left over from the port. 

I'm running on Windows 10 with XAMPP, Apache, & MySql.

**Comment by olafgrabienski** [comment]
I'm also using Backdrop 1.6.0 and on `admin/structure/layouts` I see no Node Layout but only Home page, Default Layout, and Default Administrative Layout. To display pages other than the home page, the Default Layout is used. I guess that's the default configuration of Backdrop. How did you get the Node Layout?

**Comment by ColumbiaBlooms** [comment]
I don't know how I got the Node Layout. I thought it was a default.

Does it matter that I have a Node Layout? I thought that blocks configured the same way should behave the same way no matter the layout.

**Comment by klonos** [comment]
@ColumbiaBlooms as it is currently, each layout has the ability to use a different layout template (and thus have different regions), have different blocks and same types of blocks with different configurations. So if you have a menu block as a drop-down in the header region of one layout, you can have the same menu as a block in a sidebar in another layout and also have it be rendered as a hierarchical tree instead. This is a feature, not a bug. It's how layouts work.

Now, we have of course faced the need to be configuring a block (or an entire region) in one layout and have it's configuration be "propagated" across different layouts. The way we have envisioned this to work is by the use of block "clones" and region "clones". These features have not been implemented yet though. Here are the respective issues that you might wanna give a read-through in order to see what's been discussed and what's being planned:

[[UX] Layout UI: Allow regions & blocks within to be re-used (Copy Region) · Issue #1886](https://github.com/backdrop/backdrop-issues/issues/1886)

[[UX] Layout UI: Allow blocks & settings to be re-used (Copy Block) · Issue #2245](https://github.com/backdrop/backdrop-issues/issues/2245)

As @olafgrabienski already mentioned, core ships with 3 layouts out of the box (admin, front page and default). If you have another one, then you must have added it at some point. The menu included in that might have not be configured to be rendered as a drop-down, but you can easily do that I trust.

**Comment by ColumbiaBlooms** [comment]
Thanks so much for the information on how layouts & blocks work in Backdrop. This is what I love about Backdrop support. All too often this kind of context/tutoring was absent from Drupal support. Please keep up the good work!

Problem solved!

**Comment by klonos** [comment]
👍
