### ISSUE TITLE
Move core profiles under /core/profiles

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2555]
This makes total sense to me and I honestly do not know why we haven't done this in the first place.

IIRC, we had certain issues with updating things in the standard profile because as it is now it resides outside `/core` and that is what we tell people to replace during updates. If the core installation profiles were in the `/core` directory, then they would get updated with the current procedures and documentation we have in place.

Doing this would leave the `/profiles` directory free for any contrib profiles (what people usually refer to as "recipes", see #1591).

---

PR by @quicksketch: https://github.com/backdrop/backdrop/pull/2125

**Comment by BWPanda** [comment]
Yes! I was just looking at this thinking "I wonder how many updates I've been missing out on since I've only ever updated the Core directory when a new version of Backdrop comes out?"...

As per everything else in Backdrop, core functionality (modules, themes, profiles, etc.) should reside in folders under /core, and contrib functionality (modules, themes, profiles, etc.) should reside in similarly-named folders outside of /core.

**Comment by BWPanda** [comment]
In the weekly video, @quicksketch said that updating install profiles wasn't a big deal for sites as they're already installed and working. While that's true, it's a different case for multisites where the install profiles need to be up-to-date for future site installs. So this is still important and necessary IMO.

**Comment by quicksketch** [comment]
> So this is still important and necessary IMO.

:+1:

**Comment by quicksketch** [comment]
I took a stab at this in a PR at https://github.com/backdrop/backdrop/pull/2125.

It looks like profiles were special in that they were only allowed in a single place. This now expands it to allow profiles in both `/core/profiles` and `/profiles`. With the root `/profiles` taking precedence over a `/core/profiles` one. There is still special handling for profiles over the way modules/themes/layouts are discovered, primarily because profiles need to be discovered early in the installation and they also have the capability to have modules nested within them. The module search order now goes:

- sites/[site_name]/modules
- /modules
- /profiles/[profile_name]/modules
- /core/profiles/[profile_name]/modules
- /core/modules

**Comment by klonos** [comment]
Thanks @quicksketch ...I briefly took a look at the PR. I could try "kicking the tires" over this weekend, but it says it has conflicts currently.

I think that we should be providing a `/profiles` dir on the root folder OOTB, along with a README file, same as we do for the root modules/themes/layouts folders.

**Comment by quicksketch** [comment]
Thanks, rerolled the PR https://github.com/backdrop/backdrop/pull/2125

> I think that we should be providing a /profiles dir on the root folder OOTB, along with a README file, same as we do for the root modules/themes/layouts folders.

I'm not sure about this. While custom/contrib modules/themes are all but certain on a Backdrop site, an additional install profile is exceptional.  Though I suppose the same thing could be said for the `sites` directory now, which we have left in place even though it's not used on most installations either. I think my hesitation here is that we don't have any way to distribute or package install profiles right now, surfacing a feature that isn't well supported and exceptional seems unnecessary. :shrug:

**Comment by klonos** [comment]
>>I think that we should be providing a /profiles dir on the root folder OOTB, along with a README file, same as we do for the root modules/themes/layouts folders.
>
>I'm not sure about this. ...

@quicksketch [as discussed during the dev meeting today](https://www.youtube.com/watch?v=nlBSiFD51ac&feature=youtu.be&t=1343), we should not worry too much about this. If needed, we can add this directory at a later point. The only thing that we should perhaps make sure right now is that such a directory is in fact taken into account if people do add one on their own.

**Comment by BWPanda** [comment]
> ...an additional install profile is exceptional. Though I suppose the same thing could be said for the sites directory...

I must be an exceptional use case then 😊 I always use a custom install profile and multisite setup.

**Comment by jenlampton** [comment]
We should add this to our metrics data: https://github.com/backdrop/backdrop-issues/issues/285

**Comment by klonos** [comment]
> I must be an exceptional use case then 😊 I always use a custom install profile and multisite setup.

...and which is why I have just filed #3205 as a follow-up.

> We should add this to our metrics data: #285

Also just did :)

**Comment by quicksketch** [comment]
Sorry I forgot to come back and update this issue. I've merged https://github.com/backdrop/backdrop/pull/2125 into 1.x for 1.10. We'll need to include this change in the release notes, per our policy of notifying of any changes outside the "core" directory.

**Comment by BWPanda** [comment]
Made a CR here: https://docs.backdropcms.org/change-records/core-installation-profiles-moved-to-the-coreprofiles-directory
