### ISSUE TITLE
CKeditor: Uploaded inline images broken on sites installed in a subfolder of root (regression after Backdrop 1.5.1)

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2562]
This is a follow-up to #2261 the changes of which have made inline images not load on sites where clean URLs are either intentionally disabled or not available as an option:

Backdrop 1.5.0:

![backdrop-issue2562-150](https://cloud.githubusercontent.com/assets/2423362/23481578/08cbf45c-ff20-11e6-9ba3-f5e70cfb3a63.png)

```html
<img alt="" data-file-id="1" src="http://localhost/files/inline-images/0_euro.jpg" height="100" width="100">
```

Backdrop 1.5.1+:

![backdrop-issue2562-151](https://cloud.githubusercontent.com/assets/2423362/23481588/11cad550-ff20-11e6-8d6c-2b1aa50f8c2b.png)

```html
<img alt="" data-file-id="1" src="/files/inline-images/0_euro.jpg">
```

---

PR https://github.com/backdrop/backdrop/pull/2068

**Comment by klonos** [comment]
PS: both screenshots are on path `http://localhost/?q=node/1/edit`

**Comment by klonos** [comment]
Perhaps a really simple solution would be to be checking whether clean URLs are enabled or not and then only conditionally apply changes from #2261 / https://github.com/backdrop/backdrop/pull/1605/files ...looking into that.

**Comment by olafgrabienski** [comment]
@klonos Do you know what's the reason why the issue happens only with clean URLs disabled / not available? I'm asking because the intention of #2261 was better portability, and it would be good to reach this goal both for clean URLs enabled and disabled / not available.

**Comment by klonos** [comment]
@olafgrabienski hold on, I was actually in the process of typing something here. Gimme a couple of minutes 😄

**Comment by klonos** [comment]
The changes from #2261 were undoubtedly needed in order to provide portability between environments, so we should not revert. We just did not take under consideration the case of non-clean URLs, that's all.

I suspect that trying to fix this in filter.module would not provide a global solution, so might be better to correct how [`file_create_url()`](https://api.backdropcms.org/api/backdrop/core!includes!file.inc/function/file_create_url/1) works for example. I believe that we should keep storing the `src` as not relative (as we currently do after 1.5.1), but provide a workaround (or a shim of some sort) when we detect that non-clean URLs are in use.

Here's what the net has said...

## Use `onerror`:

```html
<img src="/relative/path/to/image.file" onerror="this.onerror=null;this.src='http://absolute/path/to/image.file';" />
```

- The `this.onerror=null;` part is in order to avoid endless loops when the alternative image is also not found (file truly gone).
- The absolute path to image is actually `$GLOBALS['base_url']` + `src`

## Use an `<object>` tag:

```html
<object data="http://absolute/path/to/image.file" type="image/png">
   <img src="/relative/path/to/image.file" />
</object>
```

Sources:

https://stackoverflow.com/questions/7995080/html-if-image-is-not-found
https://stackoverflow.com/questions/3984287/how-to-show-alternate-image-if-source-image-is-not-found-onerror-working-in-ie
https://stackoverflow.com/questions/92720/jquery-javascript-to-replace-broken-images

**Comment by olafgrabienski** [comment]
Hm, why do we need a workaround? Do you think it isn't possible to fix the issue for the clean-URLs-disabled-or-not-available use case?

**Comment by klonos** [comment]
There could be a way of course. I just do not currently see how. Perhaps others with more experience (like @quicksketch for example that also created the PR for #2261) can chime in. I just wanted to save people some time in case there is no obvious way, so I did a bit of research on the nets. That's all 😉

**Comment by olafgrabienski** [comment]
I see! Do you have any idea about the reason for the issue? An image path like `/files/inline-images/0_euro.jpg` looks fine to me but I guess I miss something.

**Comment by klonos** [comment]
Beats me at the moment. Proper node paths are perfectly fine too, but they just don't work without clean URLs.

**Comment by quicksketch** [comment]
I'm not understanding the issue here either. I can't see anything wrong with an image tag such as the one currently generated:

```
<img alt="" data-file-id="1" src="/files/inline-images/0_euro.jpg">
```

That should work find with or without Clean URLs enabled (and without Apache support for rewriting URLs). That should just be the local path to the file, and that's it. Are you sure this isn't some issue with a copy of the site that just doesn't have that file available within its files directory?

**Comment by olafgrabienski** [comment]
> both screenshots are on path http://localhost/?q=node/3/edit

Does the issue happen also when you view the node? (http://localhost/?q=node/3)

**Comment by markabur** [comment]
I'm unable to reproduce this issue as described... I can turn clean urls off and images still get inserted just fine.

If the site is installed in a subfolder, then I do get a broken image as in the second screenshot. But the node-edit url in that case is like `http://localhost/backdrop/?q=node/1/edit` rather than `http://localhost/?q=node/1/edit`.

**Comment by klonos** [comment]
>If the site is installed in a subfolder, then I do get a broken image as in the second screenshot.

@markabur Yes, that is the case. This is on my local, where I keep all projects under subfolders. Do you think that this could be an issue with subfolders an not non-clean URLs?

**Comment by markabur** [comment]
No, it's just that the absolute URL generated for the image doesn't include the subfolder as part of the path. 

E.g. if I am on `http://localhost/backdrop/?q=node/1/edit` then the image src ought to start with `/backdrop/files/inline-images/` but it just starts with `/files/inline-images/`. 

Adding in the subfolder would fix the broken images on localhost, but then when the site is deployed on a server, *not* in a subfolder, the images would be broken there. Developing a website inside of a subfolder has always been tricky for exactly this reason, even for static HTML sites.

**Comment by klonos** [comment]
Yes, this is exactly what's happening. I don't know why I didn't think of that. Perhaps because there were other issues I'm having with non-clean URLs and I often tend to blame that.

As I said previously, the changes that came with #2261 solved one important issue (image/file paths not working when changing environments), but broke a thing that was previously working fine: multiple installations (local or remote) under subdirectories of webroot.

I think that what would serve us best is to have a system setting of how things should be working (essentially [Pathologic](https://www.drupal.org/project/pathologic) in core). Now, if there was also a way to safely detect what is happening and adjust that setting on the fly during runtime, then that would be awesome.

**Comment by LeeteqXV** [comment]
Just for perspective:
Up until now it has been VERY useful to be able to run websites from subfolders, both in order to test a site on a different domain than its main one (dev) without updating A records etc., but also more importantly to be able to protect the login to such sites with the SSL certificate of the main domain, without having to buy more SSL certs, or to generate self-signed ones.

**Now with the developments the last couple of years, that latter concern is almost turned inside-out:**

As we can use LetsEncrypt / AutoSSL with cPanel/WHM and other such tools to get automatic valid, free certificates, we now see that there are sometimes added complexity/confusion in the automatic update process for AutoSSL IF using subFOLDERS for sites. IF, however, we use subDOMAINS instead, which the AutoSSL++ processes prefer, then we do not have such problems.

If insisting on using subfolders with AutoSSL, one has to add (**and subsequently manage** across site updates...) new rules to htaccess to make the SSL certificates work. Not very tempting.

**This may mean that in case this issue here regarding the CKeditor is "complex", perhaps the time has come to simply standardise on using subdomains that points to the actual subfolder, and end support for running directly from the subfolder?**

Also shared hosting solutions allow easy creation of subdomains pointing to either new or existing subfolders.

**Comment by LeeteqXV** [comment]
Several modules have been struggling with the complexity of not being able to depend on the site being run from the "real root", so many maintainers may simplify their code if we decide to stop supporting running directly from subfolders. 

(Notice that this does not mean we should not still support INSTALLING TO a subfolder, which may be practical for autoinstallers etc. (??), but mainly require that the subsequent running of the site (in particular in regards to avoind problems with contributed modules) is done from a "real root", either a domain or a subdomain.)

**Comment by LeeteqXV** [comment]
(PS. I am unsure whether there are other concerns/complications related to multisite installs that may affect the question of supporting running from subfolders. Could it be that that realm would even benefit from not having to support subfolders??.)

**Comment by LeeteqXV** [comment]
(And, btw, this is a digression, so if it is interesting, this should be branched off as its own feature request and discussed with the Drupal community to make sure all relevant concerns are addressed.)

**Comment by quicksketch** [comment]
I am in agreement that installing at the root of the host is definitely better from a consistency-standpoint, it makes things easier for developers in general.

However, it's completely valid to install Backdrop in a subdirectory. And it's completely possible that it's done not just for localhost development, but the production server itself is installed in a subdirectory.

I think the "fix" here is to simply support subdirectories when generating that image path, matching whatever the current installation subdirectory is. Then we trust it to developers to use the same directory structure between environments (or use a solution like Pathologic module). Right now, our image paths actually don't support subdirectories at all (even if it's intentional), so this continues to be a bug in Backdrop rather than something the user has done wrong.

**Comment by quicksketch** [comment]
I've filed a PR at https://github.com/backdrop/backdrop/pull/2068 that makes our absolute path code work with subdirectories.

The following test code now returns the following:

```
    $file = file_load(5);
    $absolute_path = parse_url($GLOBALS['base_url'], PHP_URL_PATH) . '/';
    $url = file_create_url($file->uri);
    $url = str_replace($GLOBALS['base_url'] . '/', $absolute_path, $url);
    dvm($url);
```

On a site where Backdrop is installed in the root:
`'/files/inline-images/Screenshot_from_2018-01-12_08-32-52_1.png'`

Or on a site where Backdrop is in a subdirectory:
`'/backdrop/files/inline-images/Screenshot_from_2018-01-12_08-32-52_1.png'`

**Comment by quicksketch** [comment]
I've merged the simple fix in https://github.com/backdrop/backdrop/pull/2068 into 1.x and 1.8.x.
