### ISSUE TITLE
Admin bar: Cannot disable components

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#2584]
Sorry but I am getting sick.
24 days left and the bug still exist.
After working with Backdrop I can see Drupal is much more reliable.
A lot of bugs and permanent negligence.
It is very pitty.

![rtyrtys](https://cloud.githubusercontent.com/assets/13515302/24059672/fc4d01f6-0b60-11e7-9093-a95a73fcd8c4.png)

**Comment by klonos** [comment]
> Sorry but I am getting sick.
...
> After working with Backdrop I can see Drupal is much more reliable.

@bd0bd this is the 3rd time you say this. The previous 2 times I refrained from saying anything because of my position as a member of the PMC of the project, but this has reached a point that this is personally annoying me as a person that dedicates their time to contribute to open source projects. Nobody is forcing you to try Backdrop CMS and/or use it for your site. If you see Drupal as a better product, then please use that instead and refrain from making such comments here.

We have an issue for this already: #2556 (which I am sure you already know because it was you that opened it), so closing this one. If you are under the impression that opening multiple issues for the same problem or annoying the people that are working on fixing them **for free, on their spare time** is going to speed things up, I'm sorry to tell you that that might have the opposite effect.

**Comment by Graham-72** [comment]
@klonos Well said! This comment was 'out of order' and intemperate, particularly in view of the activity at #2556. Thank you for all the time and effort you are putting in to working on this and so many other things.

**Comment by klonos** [comment]
Sorry for "loosing my cool", but the specific user is the complete opposite of @ColumbiaBlooms which with #2560 persisted by trying suggested solutions and provided detailed feedback along the way. He even pushed a notch further by updating the documentation after he solved his own issue, so that others do not waste their time looking for a solution.

Now, @db0db on the other hand, filed the original issue about a month ago and stated to be annoyed with the "permanent negligence" on our end, while he never tried any of the suggested patches nor provided any feedback. Well, sorry if we are not up to your standards mate. If you feel like you have everything possible on your end to help, then what else can I say.
