### ISSUE TITLE
Add the main page content block to layouts that do not have "main page content" 

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2636]
Main page content block not available for the Home page layout.
Why is that?

**Comment by Al-Rozhkov** [comment]
I guess, there is no context for it. Nothing to show.

**Comment by klonos** [comment]
Yeah, that makes sense.

**Comment by bd0bd** [comment]
Hm, why there is no Main page content block in the Sutro layout? There is area CONTENT but there is no Main page content block  for this area.

**Comment by klonos** [comment]
@bd0bd Sutro is a layout *template*. Which layout are you trying to apply it to? ...if it is the "Home page" layout, then see @Al-Rozhkov answer above ^^

**Comment by bd0bd** [comment]
Basic page.
I create  a basic page and switch from default layout - Moscone Flipped - to Sutro.

**Comment by markabur** [comment]
@bd0bd It's confusing, but when you add a custom layout using a node/[nid] path like that, it doesn't work the way you expect. In general, any layout that has a non-wildcard path will not have a "content" block as there's no place for the content to come from (just like in your home page layout). When you create a custom layout using node/5 as the path, you are completely circumventing the system's built-in way of handling the "node/5" path, which actually makes the node content inaccessible -- not what you want.

Instead, configure the Contact layout to have "node/%" as the path, and "Node NID is 5" as a visibility condition. That way the system will still go through its normal process for loading node/[nid] content, and you'll have a content block available in your layout.

![screen shot 2017-04-13 at 10 03 59 am](https://cloud.githubusercontent.com/assets/314312/25015416/8e67c5ec-2030-11e7-849c-3c350e6cd15f.png)

**Comment by bd0bd** [comment]
Thank you very much! :+1:

**Comment by markabur** [comment]
Ya, this trips me up too sometimes and the only I was going to remember was to type it up myself... thanks to @quicksketch for original explanation in #735.

**Comment by docwilmot** [comment]
What if we automatically fixed this for the user? Meaning if a user types in `entity/numeric ` we automatically converted this to ` entity/%` and added a condition for `entity id = numeric `?

Any downside? @jenlampton?

**Comment by jenlampton** [comment]
That sounds awesome :) 

Can we add a condition for `path` instead of `entity ID`? I feel like that's going to be more in line with what people expect to happen.

We should also add a message saying "A condition has been added for this layout to match the path you entered" so that people don't think it's a bug. 

But yes, a big +1 for this!!

**Comment by Al-Rozhkov** [comment]
Please somebody native english speakers specify better title, I'm struggling to formulate it :)

**Comment by stpaultim** [comment]
This issue was closed and then reopened with the suggestion 3 comments up. I don't think that the title is very helpful and I don't understand the suggestion that @docwilmot made enough to edit the title myself. Any help?

Is this related to: https://github.com/backdrop/backdrop-issues/issues/3750 - Layouts: Add support for custom contexts

**Comment by docwilmot** [comment]
Layout provides the Main content block only if that layout is overriding an existing path (a path that is in a `hook_menu()` somewhere). So if you create a layout with path:
- `admin/content` => MCB available
- `node/%` => MCB available
- `path/provided/by/contrib/module/%` => MCB available
- `previously/nonexistent/path` => MCB **not** available

No module provides a path `"home"` in any `hook_menu()`, so no MCB.

My comment there had nothing to do with the original title sorry, was just a response to https://github.com/backdrop/backdrop-issues/issues/2636#issuecomment-293962088

To fix this issue, and provide the MCB on the home layout, I suppose we could add a "home" path entry to `system(or layout)_menu()` with `node_page_default()` as the page callback. Side effects uncertain.

**Comment by bugfolder** [comment]
@klonos, from your question 3 comments up, should there be a new issue like "Make blocks defined by Dashboard module available to any layout?" 'Cuz it seems like it's easily done if there's a need.

**Comment by klonos** [comment]
Not sure if all Dashboard-provided blocks would make sense being added anywhere else other than the Dashboard layout, but the reason for my comment above was that I had the need to be able to add a specific Dashboard block to the home layout.

**Comment by docwilmot** [comment]
Sorry missed the mention here. We left off dashboard from the list of available contexts, for no proper reason whatsoever. That context should be available to any other layout, you're right, since we discussed, when planning the dashboard, that users should be able to use another layout as their own dashboard. 


In fact in `layout.contex.admin.inc` line 81 if you simply delete 'dashboard' from the line `if (!in_array($key, array('string', 'overrides_path', 'dashboard'))) {`, the layout settings UI doesnt show that it works, but it does, without error. Dashboard then shows up in the list, and you can addd dashboard blocks to any layout with this added context, and the blocks show in the front end.

As it is now though, the only way dashboard context is available to any layout is by path, unfortunately, specifically `admin/layout`. And there isnt a `hook_layout_context_info_alter()` either. 

So short term, dont think this is doable without hacking. Long term we should:
- add 'dashboard' as an available context in the custom context UI
- change the `menu path` for dashboard context to include a wildcards like `admin/dashboard/%`, `dashboard/%`, `user/dashboard/%` etc
- and add a `hook_layout_context_info_alter()`

**Comment by klonos** [comment]
Thanks for the insight/summary @docwilmot 🙏🏼 

Would you like me to create a separate issue for all that?

**Comment by jenlampton** [comment]
> To fix this issue, and provide the MCB on the home layout, I suppose we could add a "home" path entry to system(or layout)_menu() with node_page_default() as the page callback. Side effects uncertain.

I'm not sure we should fix this issue. If we provide a "main page content" block on a page that has no main page content, then that block would print nothing, so it would not show up at all. This might create an even more confusing experience than not being able to add the empty block to the page.  

I've created https://github.com/backdrop/backdrop-issues/issues/5539 to address the issue of what happens when people create the wrong type of layout by accident.
