### ISSUE TITLE
Update the README.txt files in core for Backdrop

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#266]
Here's a list of the README.txt files that deserve a review:

- [x] /core/modules/simpletest/files/README.txt 
- [x] /core/themes/stark/README.txt 
- [x] /files/config_[hash]/active/README.txt 
- [x] /files/config_[hash]/staging/README.txt
- [x] /modules/README.txt
- [x] /profiles/minimal/translations/README.txt
- [x] /profiles/standard/translations/README.txt
- [x] /themes/README.txt
- [x] /layouts/README.txt (https://github.com/backdrop/backdrop-issues/issues/559)

Note, as per https://github.com/backdrop/backdrop-issues/issues/428 we will remove these two:
- [x] /core/modules/README.txt - @todo remove
- [x] /core/themes/README.txt - @todo remove

**Comment by quicksketch** [comment]
As a general pattern, we should probably also rename all these files to .md and use Markdown inside of them.

**Comment by klonos** [comment]
I believe we agreed on removing the README.txt/md files from ```/core/modules/``` and ```core/themes/``` in #428

**Comment by jenlampton** [comment]
Good catch, I updated the original issue to node this.

**Comment by klonos** [comment]
I was just wondering... the two README.txt files that end up in ```/files/config_[hash]/active/``` and ```/files/config_[hash]/staging/```, where do they come from? Is their content created "on-the-fly" from code as they are created during install or do we have some "original" copies someplace in the initial folder structure and we copy them from there?

**Comment by jenlampton** [comment]
line 693 core/includes/install.inc ;)

**Comment by BWPanda** [comment]
Added '/layouts/README.txt' checkbox above.

**Comment by klonos** [comment]
> As a general pattern, we should probably also rename all these files to .md and use Markdown inside of them.

I'm not sure about this one. I mean, personally I'm a consistency freak (a little bit of OCD never hurt anybody) and you can clearly see that from the latest admin menu [UX] issues I've filed recently. It would be great for us familiar with the format that most likely also have a viewer/editor already installed in our OS and all. It is also great for consistency and for GitHub that formats these files nicely for display. But what about the average user? I'm not sure about other OSes, but If you double-click a .md file under (vanilla) Windows you get a prompt telling you that there is no application installed to open the file with. If the user is a bit above the average user, then they'll simply choose notepad and be done with it I guess. But most users would be intimidated by the dialog and leave the file be.

On the other hand, it is safe to assume that less tech-savvy users rarely actually RTFM. These files are there for users that -in theory- are quite computer-savvy (site admins, themers etc.). So I guess it's ok to "ignore" the inconvenience we are likely to cause to a few for the purpose of making it easier for the actual target audience.

Just wanted to say this so that we do take it into account if we actually convert the READMEs to .md.

**Comment by quicksketch** [comment]
I'm not sure which READMEs actually need updating (other than potentially converting to .md files), but this isn't a blocker for 1.0.0, so I'm moving it to the general 1.x category.

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/issues/993. If any files need updating, let's handle reviewing/updating them in individual issues.

I admit I didn't see @klonos's reservations until after I did the merge. I think he's laid out a fairly comprehensive set of pros and cons in his comment. I think overall, the consistency is a win. We've already standardized on README.md files for both core and contrib in the root of projects, and those are definitely the *most* important files to be read by end-users (although as pointed out, they are parsed and displayed by GitHub).

OTOH, we've used .txt for files that aren't formatted with markdown, e.g. LICENSE.txt.

I don't know, I could go either way on this one. I like the idea of using .md files in the event that we revise these files to use more markdown in the future.

**Comment by klonos** [comment]
What about the README.txt files inside the config dirs of already existing installations? Leave them be?

**Comment by quicksketch** [comment]
Yeah, I think leave them be. The .txt/.md files only are generated when the config directory is set up for the first time and won't be generated again later, so there still should only be a single file there.

**Comment by klonos** [comment]
Fair enough. Just thought that a rename during update was in order.

**Comment by quicksketch** [comment]
So it doesn't seem like anyone is strongly opposed to .md files. We'll leave these as-is for now. If there's a strong case to be made for using .txt, we can revisit. This was included in 1.1.3. I accidentally moved it as this issue was still open at the time of the release.
