### ISSUE TITLE
[UX] CKEditor - Increase Font Size in ckeditor-iframe.css

### ISSUE THREAD

**Issue by Dinornis** [backdrop/backdrop-issues#2680]
Maybe the current `font-size: 14px;` in `/core/modules/ckeditor/css/ckeditor-iframe.css` could be increased (perhaps to 16px) as a stopgap until a decision is made in https://github.com/backdrop/backdrop-issues/issues/1198 ?

**Comment by jenlampton** [comment]
yes, I like this idea. However, I'm going to remove the milestone from this issue since there's no PR yet and we are releasing today. However, it's possible that an issue labeled as a "task" can be included in the next bug-fix release, and as soon as we have a PR for review, the milestone can be added back.

**Comment by jenlampton** [comment]
I think I'd like to focus on https://github.com/backdrop/backdrop-issues/issues/1198 instead of adding a stop-gap solution. Closing this issue as duplicate :)
