### ISSUE TITLE
Provide an option to make e-mail optional on registration form.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2708]
Some might want to give their site users the freedom to not disclose their email address if they don't want to. In Drupal, there is this module that does this: https://www.drupal.org/project/optional_mail. From that module's description:

>This module must be used in very specific cases. Consequently, it might possibly cause problems with some Drupal features, such as the user's personal contact form and the e-mail checking of new user accounts (this feature is disabled by this module, by the way).

So I'm really worried about the implications. Lets wait for more feedback.

**Comment by jlfranklin** [comment]
The requirement for a user to have both a username and an email address is one of the fundamentals of Drupal (and therefore Backdrop) that many modules depend on.  This is an data architecture change, which is technically different from an API change, but still breaks compatibility between core and contrib modules and thus should be treated in a similar manner.

Since there is already a Drupal module for this, it may be best to mark this as a "contirb candidate" and put off a major change like this for BD2.

**Comment by BWPanda** [comment]
Going to close this in favour of contributed options(s).
