### ISSUE TITLE
Image uploading directory problem for CKEditor

### ISSUE THREAD

**Issue by vinviny** [backdrop/backdrop-issues#2728]
## Describe your issue or idea
Link to the uploaded image is wrong if I install backdrop not in the root directory, but in the subdirectory.

### Steps to reproduce (if reporting a bug)
I installed my backdrop not from the root (/public_html/), but from (/public_html/abcd/).
Then, when I upload image from CKEditor, it seems that they are going to /abcd/files/inline-images.
However, the Editor makes the source code for the image like /files/inline-images/mypic.png,
not like /abcd/files/inline-images/mypic.png. So, the image link is broken when I retrieve my post.

![image](https://cloud.githubusercontent.com/assets/29224326/26820360/8bf53b96-4add-11e7-97ef-2775a87e70a9.png)

### Actual behavior (if reporting a bug)
The name of subdirectory /abcd is missing, so that the image link is broken and no image appears.

### Expected behavior (if reporting a bug)
The editor should append /abcd in front of each image link.

### Relevant version/system information (if applicable)
1.7

**Comment by olafgrabienski** [comment]
@vinviny Thanks for reporting the issue! As far as I know, installing Backdrop in a subdirectory leads to exactly the reported problem - see https://github.com/backdrop/backdrop-issues/issues/2562, especially https://github.com/backdrop/backdrop-issues/issues/2562#issuecomment-284095784 and below.

The issue is not fixed yet, but there is a workaround: Use a subdomain like `abcd.example.com` instead of `example.com/abcd`.

**Comment by vinviny** [comment]
Thank you for the idea of using subdomain. It works well now!
