### ISSUE TITLE
Backdrop CMS and Software Freedom Conservancy

### ISSUE THREAD

**Issue by karensandler** [backdrop/backdrop-issues#2753]
Hi, I'm Executive Director of the Software Freedom Conservancy.

I am excited to write that Conservancy's Project Evaluation Committee has approved Backdrop CMS for membership in Conservancy. A committee comprised of Nate Haug, Jen Lampton, Mike McCaffrey, Wes Ruvalcaba, Jack Aponte, and Gregory Nestas has been working with Conservancy to negotiate a document called a "fiscal sponsorship agreement" (FSA). This committee will be signing this document on behalf of the Backdrop community.

You can find a template of the agreement available on Conservancy's website at: https://sfconservancy.org/members/apply/ConservancyFSATemplate.pdf (there are .odf and .tex files available too).

If you have questions or concerns, we suggest you discuss them on this forum or with Conservancy privately if you prefer.

Conservancy's "Project Intake group" can be reached by the alias project-intake@sfconservancy.org and is comprised of the following people: Bradley M. Kuhn, Karen Sandler, Tony Sebro, Jeremy Allison and Tom Callaway. All of us are members of Conservancy's Project Evaluation Committee and will be happy to answer questions.

Conservancy strongly suggests that a public discussion of the FSA occur on the general discussion list for contributors of your project, which is why I've posted this information here on the Backdrop issue tracker.

If we don't receive any actual objections to Backdrop CMS joining Conservancy by Friday July 14, 2017, we plan to execute the FSA on that date.

We look forward to Backdrop CMS joining Conservancy!

**Comment by serundeputy** [comment]
Hello @karensandler !

I read over the ConservancyFSATemplate.pdf document; I'm no expert, but looks to me like the gist of it is that SFC is going to help the Backdrop Community!

I have no objection and am in fact in support of the Backdrop PMC getting on board with this agreement.

Thanks for your help with this @karensandler and SFC!

**Comment by robertgarrigos** [comment]
I thins could be of a great help to the Backdrop Community!

**Comment by herbdool** [comment]
Read the draft and it looks good.

**Comment by klonos** [comment]
Legal lingo is not my forte and English not being my mother language is not helping. I trust that this is for the benefit of Backdrop CMS and will gladly co-sign so long as other members of the PMC see nothing wrong with the agreement.

**Comment by heyrocker** [comment]
So the way I am reading this, is that the Conservancy basically acts as an agency through which donations flow, which frees up the project from the overhead of setting up their own financial accounts and the like (this would be similar to the role the Drupal Association plays in acting as fiscal agent for many of the Drupal camps around the US.) In return the Conservancy gets 10% of said donations for overhead. Is that correct basically?

Is the Representation section in this document boilerplate text, or has it already been modified to meet the wishes of the project? Specifically, the employment section seems to be in conflict with the current committee makeup.

**Comment by laryn** [comment]
I also am not an expert but I like the general principle of the "umbrella org" for start ups. How long does this agreement hold, and can either side end the relationship if they wanted to? Could someone from the BackdropCMS committee that's been working on this chime in to lay out the benefits and potential pitfalls?

**Comment by quicksketch** [comment]
The interpretations laid out by @heyrocker are correct: the Conservancy basically acts as a financial and legal umbrella for it's member projects (which includes [many other projects](https://sfconservancy.org/projects/current/), notable ones including Git, Inkscape, phpMyAdmin, Wine...)

Although the Conservancy takes a 10% cut of all revenue, that's a great deal compared to what happens without them. For example in on my 2016 taxes I had declared over $10,000 in "income" on my personal taxes that came from Backdrop donations. Americans pay a 25% tax rate for any income over $37,950. Since I make more than that annually, for every dollar donated to Backdrop we only get 75 cents towards the project. With the Conservancy, that money is tax-free. So instead of 75%, we get 90%.

In addition, because SFC is a 501(c)(3) organization, donations they receive are tax-deductable as charitable donations for those giving money. So by becoming a member of the SFC, both the giver and recipient pay less money to the U.S. government, because it's considered charity on both sides.

As for downsides... we're not sure how difficult it is going to be moving money in and out of the Conservancy. Nearly all donations right now go towards one of three things: infrastructure (hosting costs), design (such as the logo, mascot, and backdropcms.org design), and marketing (hoodies, t-shirts, stickers). As we give swag away as gifts for donations, for the most part it pays for itself, but infrastructure and design are regular drain.

> Specifically, the employment section seems to be in conflict with the current committee makeup.

This is also true. We could work with the Conservancy to adjust the requirements for our project. But we'd like to follow the guidelines they've laid out for other projects. As you point out, the current PMC has two employees from the same company (@wesruv and I both work at Lullabot). But there is another group as well: Jen and I are married, which could also be a "conflict" or colluding group. Our plan is to have myself step off the PMC to avoid both potential conflicts, while remaining as a core committer. We may also make some sort of advisory role so I can participate in PMC discussions even if I can't vote.

**Comment by heyrocker** [comment]
Thanks those are some great points, I hadn't thought about the 501(c)3 aspect or the impact of your tax rate vs the 10%. I mean this sounded like a solid deal for Backdrop before I even knew those points. Hearing them just makes it that much more compelling.

**Comment by mtift** [comment]
In 2015, on the [first episode of Hacking Culture](https://www.lullabot.com/podcasts/hacking-culture/nate-haug-forking-drupal), I interviewed Nate about Backdrop 1.0, and during the interview I recommended he checkout out the Software Freedom Conservancy as a potential home for Backdrop. Both organizations do great work, so it's great to see this become a reality! I looked over the agreement and hereby add my support.

**Comment by karensandler** [comment]
To address @laryn's questions, when we were originally architecting Conservancy  we made sure that it was easy for projects  to leave the org. You can check out section 8 of the agreement, which deals with termination. Either Conservancy or the project can terminate the agreement with 60 days notice, and there's a lot of language around finding an appropriate successor org. The main thing here is that once assets are in a charitable organization we have to make sure they are appropriately used in the public interest and consistently with our mission, we can't just transfer them to individuals or for profit companies, for example. I think that the rules and laws for charities are a real feature for Conservancy and how we're organized but only so long as a project understands this and is a good fit for this approach.  If you are not certain already, you should consider consulting with a lawyer to evaluate this for you. (And here's where I have to put in my disclaimer - I am a lawyer in addition to being Executive Director, but I'm not your lawyer or lawyer to Backdrop CMS. I hope it's obvious that this isn't intended as legal advice!)

The agreement has no automatic expiration date - once a project joins Conservancy they are a part of our organization, and would have to exercise the termination provisions to leave. 

To echo what @quicksketch said, the 10% we take in from our member projects doesn't cover the staff salaries to do the work that our projects need, so we fundraise from the public to close the gap.

https://sfconservancy.org/supporter/

**Comment by tomgrandy** [comment]
I have no objection with Backdrop becoming a member with the Software Freedom Conservancy.  This will benefit both the organization by providing it with non-profit status it needs as well as freeing up @quicksketch and @jenlampton from having to report monies associated the project as personal income.  Also, the membership will allow the team to do what they do best, development of the content management system.

**Comment by mikemccaffrey** [comment]
I'm excited about this partnership! It seems like the missions of both organizations are clearly in line with each other, and it should be a fruitful relationship for both groups!

**Comment by laryn** [comment]
I am in favour of this, too -- looks great!

**Comment by Dlair** [comment]
Having reviewed the documents you have my +1 also. Since the 14 July deadline has now passed, can we get an update on this?

**Comment by jenlampton** [comment]
Thanks @Dlair, 
The next steps are for all current PMC members to sign the FSA, and get the contract in place. We'll post an update here when that's done, if not before. Also, keep an eye on the [backdrop blog](http://www.backdropcms.org/news) for news and updates about other changes that will help with that process :)

**Comment by laryn** [comment]
I think this is all complete, right? Re-open the issue if I'm wrong!

**Comment by klonos** [comment]
Everything besides the blog post 😅
