### ISSUE TITLE
[i18n] Fix untranslated string

### ISSUE THREAD

**Issue by opi** [backdrop/backdrop-issues#2777]
After patching https://github.com/backdrop/backdrop-issues/issues/2772, I noticed that some other string are not wrapped with `t()` function.

Commands used to find them:
```
git grep "#title' => '" path/to/backdrop/core
git grep "#description' => '" path/to/backdrop/core
git grep "#value' => '" path/to/backdrop/core
```

**Comment by opi** [comment]
addressed in https://github.com/backdrop/backdrop/pull/1933

**Comment by opi** [comment]
Got other untranslated strings in the following files, but I don't know if it worth translating : 

- core/modules/simpletest/tests/ajax_test.module
- core/modules/simpletest/tests/batch_test.module
- core/modules/simpletest/tests/common.test
- core/modules/simpletest/tests/form_test.module

**Comment by quicksketch** [comment]
Thanks @opi! Merged https://github.com/backdrop/backdrop/pull/1933 into 1.7.x and 1.x.

> Got other untranslated strings in the following files, but I don't know if it worth translating :

You're right, we intentionally do not translate strings in tests or test modules, because those modules are never shown on a public site and just adds unnecessary strings for translators that would never be used. The ones you include in the PR were all great fixes. Thanks!
