### ISSUE TITLE
Fix the 404 page not found errors about missing favicon.ico

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2784]
This is the respective Backdrop issue for https://www.drupal.org/node/174940.

This seems to be happening because certain browsers blindly search for favicon under `http://example.com/favicon.ico` without checking. Most browsers nowadays are supposed to respect: `<link rel="icon" href="http://example.com/img/icon.png">` and we already have logic that points to `/core/misc/favicon.ico`, but I just got these annoying 404 errors in my log today using the latest version of Crome. So, I guess we should fix things if we can.

In Drupal contrib land there's https://www.drupal.org/project/favicon that as people report, fixes this problem. From the module's README:

> ## Logic for determining which file to use
> 
> 1. First, the value of the `favicon_uri` variable is checked. There is no UI to
>   set this variable, so it should be set only using settings.php if needed.
>   The path should be relative to the Drupal root directory.
>   ```
>   $conf['favicon_uri'] = 'sites/all/images/favicon.ico';
>   ```
> 
> 2. Second, if a file exists at `sites/example.com/favicon.ico` or whatever the
>   current subdirectory under `sites/` is current will be used.
> 
> 3. Third, if the current theme's setting has the 'Use default favicon' checkbox
>   checked, the theme's default favicon will be used.
> 
> 4. Fourth, if the current theme has a manually provided favicon, it will be used.
> 
> 5. Lastly, the default Drupal favicon located at misc/favicon.ico will be used.
> 
> The result of which favicon is used is stored in the cache using a combination
> of the current theme, current base URL, and current sites subdirectory.

---
PR: https://github.com/backdrop/backdrop/pull/2000

**Comment by quicksketch** [comment]
So I took a look at the Favicon module (http://cgit.drupalcode.org/favicon/tree/favicon.module). It uses a trick where it registers /favicon.ico as a path in the menu system. Then all requests to /favicon.ico actually bootstrap Drupal to serve the image file. It looks like the returned value might not even be used by the page cache.

I think for the out of box Backdrop, this would be heavy handed, especially since browsers support reading the `<meta>` tag for favicon, but they _also_ check at `/favicon.ico`. I think the correct solution for us is to simply not have Backdrop handle the page for `/favicon.ico`.

We already exclude `/favicon.ico` from the clean URLs configuration:

```
  # Pass all requests not referring directly to files in the filesystem to
  # index.php. Clean URLs are handled in backdrop_environment_initialize().
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteCond %{REQUEST_URI} !=/favicon.ico
  RewriteRule ^ index.php [L]
```

So it's already excluded there. But what's happening is that all 404 errors are routed to Backdrop in this line of .htaccess:

```
# Make Backdrop handle any 404 errors.
ErrorDocument 404 /index.php
```

Note that 404 pages are going to go to Backdrop anyway because of the Rewriting rules.

This error document rule has been in place since 2003, prior to the rewrite rules having been updated to handle all documents anyway (or when Clean URLs where a lot less common).

I would suggest that we remove these lines from the default .htaccess, allowing the Rewrite rules to handle any 404 pages, and specifically exclude the /favicon.ico path from being recorded.

**Comment by quicksketch** [comment]
I also don't like Backdrop handling 404 pages because it can obscure problems with RewriteRules not actually working properly. You can comment-out the RewriteRule section and the 404 handling will accidentally continue serving pages at their "clean" URLs, but it will return a 404 in the response headers (making these pages un-indexable by search engines).

So removing this 404 line would solve multiple problems.

**Comment by olafgrabienski** [comment]
Can't evaluate the technical aspects but I like the expected result (less file related "not found" errors) a lot.

**Comment by klonos** [comment]
As an end user, and having new Drupal/Backdrop users in mind, I don't really care about the solution we choose to go with. The point is to eliminate non-error errors from the log, because otherwise people might think that Backdrop is "broken".

^^ my way of saying that I trust @quicksketch's technical judgement 😄

**Comment by BWPanda** [comment]
Would this affect how [Search404](https://github.com/backdrop-contrib/search404) works?

**Comment by quicksketch** [comment]
> Would this affect how Search404 works?

Yes, it would affect it, but probably in a positive way. Backdrop will always handle 404 pages for any not-found *paths* such as if you tried to visit typo paths like `/aboutt` or `/purtfolio`, even without this option in .htaccess. Disabling 404 in .htaccess would stop Backdrop from serving 404 pages for file-based paths like `/favicon.ico`, `/files/example.png`, or `/robotss.txt`. Usually you don't want to be doing a search on those kinds of 404s anyway, as the requesting page is usually part of an `<img>` tag or other non-HTML requests.

**Comment by quicksketch** [comment]
How about we merge this for 1.9.x and that will give us a nice long period of time to see these changes in action. I think it's a good idea, having Backdrop *not* handle file-based 404s will both be good for performance and reduce the noise in watchdog.

**Comment by quicksketch** [comment]
Thanks! Committed https://github.com/backdrop/backdrop/pull/2000 to Backdrop 1.x for 1.9.0!
