### ISSUE TITLE
[DX] allow any config value to be overridden via settings.php

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop/backdrop-issues#2805]
## Describe your issue or idea
I would like to be able to export/import config files without overwriting some key config values. For instance private files directory. This is a value which might be different in devel and production environments, thus when updating configs it overrides private files directory value and you need to change it manually every time.

It would be great to be able to hardcode some configs in settings.php so they don't get overwritten during config import.

Here's a list of specific variables (and thier respective issues) that we should support in core, even without global variable-override support:
* [ ] https://github.com/backdrop/backdrop-issues/issues/4174 | error_level
* [ ] @todo | aggregate CSS & aggregate JS

----
~~PR https://github.com/backdrop/backdrop/pull/2607 by @herbdool (specific overrides)~~
PR https://github.com/backdrop/backdrop/pull/2984 by @quicksketch (global overrides)

**Comment by jenlampton** [comment]
Any setting that could vary in different environments should be using the State system instead of config (or variables).  See https://api.backdropcms.org/api/backdrop/core%21includes%21bootstrap.inc/function/state_get/1

I'm not sure why file system directories are config and not states, that does seem like something that may have been an oversight.

**Comment by herbdool** [comment]
That doesn't seem right to me. The file system path should rarely change between environments, no? Any path embedded in the WYSIWYG would stop working. A state is something that can change while using the site which doesn't fit the file system path. That shouldn't change during use.

**Comment by jenlampton** [comment]
Hm, that's a good point about embedded images. However, private files most likely wouldn't be embedded, and those are the ones that often have strange "paths" that can vary by environment. (I struggle with this on Drupal sites I currently have hosted on Acquia, for example.) Maybe public/private should be handled differently?

> It would be great to be able to hardcode some configs in `settings.php` so they don't get overwritten during config import.

There was a reason we removed the variable/config overrides from settings.php, but I don't remember exactly what it was anymore. @quicksketch do you recall?

@robertgarrigos I wonder if this might not be a good use-case for a Backdrop version of strongarm module?

**Comment by robertgarrigos** [comment]
I found the state function and thought, like @herbdool, that it should be used for changes on the same site, not between environments which I would understand as different sites. In any case, I didn't realise that the private files path would have such an impact in changing environments. I would think that having a config for that would actually avoid such problems.

Any way, this issue was not about a single config value but about the ability to override any config value. Otherwise, how do you do when deploying a site? There is the devel module, the theme debug config, private files path (although I might need to reconsider this), all the performance configs, etc. You would provably use all these config/modules on a devel environment but you would need them off on a staging or production environment. Do you just go to change all those values every time you deploy a change to your project? This is where yes, variable/config overrides with in settings.php would be handy.

@jenlampton using strongarm, wouldn't it be like using a sledgehammer to crack a nut? Strongarm for Drupal requires ctools and features and I guess it would need a heavy rewriting in order to run without those modules and adapt it to the new config management. But yes, you got the concept: I would love to see something like strongarm in backdrop core. Something simpler, though.

**Comment by jenlampton** [comment]
> Otherwise, how do you do when deploying a site? ... Do you just go to change all those values every time you deploy a change to your project?

For me personally, my dev sites are a copy of production, and not vice versa. The configuration files I commit always contain the values I want on production, so deploying is never an issue.  My process is to enable the development modules or adjust settings I need for development *only* in the development environment, and never commit those changes. (I do usually commit modules like devel, but those are never enabled on production.) 

The location of all config files is also customizable via `settings.php`.  I usually put my live site config in a directory named `live-active` and my dev site config in `dev-active`. By keeping two separate sets of config, I can have any values I want differ between environments.

Then, when I do a config sync from live -> dev, I usually check what's about to be imported, and adjust as needed (for example, copying my dev site copy of `system.core.json` into my staging directory before import - or making a copy of the json and doing a single-file import afterward.)

I agree, in explaining this it seems like the only reason I'm able to do this work-around is because of how well I understand the system already...  it seems like we need an easier way. :)

I'm going to take a look into how Drupal did this, as they have the global `$conf` in `settings.php` and also use CMI. That's the same boat we're in...

**Comment by robertgarrigos** [comment]
```it seems like we need an easier way```

Agree ;-)

**Comment by olafgrabienski** [comment]
For Drupal 8, there is the [Configuration Split](https://www.drupal.org/project/config_split) module. Maybe an interesting approach also for Backdrop?

**Comment by herbdool** [comment]
@jenlampton This is what Nate mentioned to me a while back in gitter (don't have the link anymore):

> $conf only affects variable_set/get(), which are deprecated as they're not config-management friendly. If it's something like an authorization token you're storing, $settings in settings.php is the best bet, then use settings_get(). We've had a few modules that want things in config or settings.php, and we don't have a universal way of overriding config_get(). So what I've seen is doing a settings_get() first, and if empty, use config_get()
$setting = settings_get('my_setting');
$setting = isset($setting) ? $setting : config_get('my_module.settings', 'my_setting');

So the module needs to support this alternative way of overriding config and I think few do. I made it so it would work with devel modules like Reroute Email so it could be set per environment.

I'm not sure if overall this would be a need for the 80% or not.

**Comment by jenlampton** [comment]
I feel like the solution we had in D7 was a good one. for the few settings you wanted to override per environment you could specify those in settings.php. Something at the core level that takes this into account after config sync, and on config read would likely be the best way to handle it. I'm not sure something like that even could live in contrib. Maybe?

**Comment by jlfranklin** [comment]
@robertgarrigos , Silkscreen 1.8-dev supports this.  You'll need to grab the latest [Silkscreen 1.x branch](https://github.com/silkscreencms/silkscreen), the [Layered](https://github.com/silkscreencms-contrib/config_layered) configuration driver and the [Memory](https://github.com/silkscreencms-contrib/config_memory) configuration driver, then follow the set up instructions in the Layered README.md.

Silkscreen is a drop-in replacement for Backdrop, much like Pressflow was for Drupal 6.  The current 1.x branch is missing the last 8 weeks of Backdrop development, because I'm waiting for BD 1.8 to drop before doing the next merge.

**Comment by robertgarrigos** [comment]
thanks @jlfranklin I'll have a look.

**Comment by opi** [comment]
For the example, these are some settings (from Drupal) that I'd like to override locally, but still want the production value to be saved in my config files: 
```
# Debug
$conf['error_level'] = ERROR_REPORTING_DISPLAY_ALL;
$conf['theme_debug'] = TRUE;
# Reroute email
$conf['reroute_email_address'] = "user@domain";
$conf['reroute_email_enable'] = true;
$conf['reroute_email_enable_message'] = true;
# Performance & caching
$conf['cache'] = FALSE;
$conf['block_cache'] = FALSE;
$conf['preprocess_css'] = FALSE;
$conf['preprocess_js'] = FALSE;
# LESS
$conf['less_devel'] = TRUE;
$conf['less_watch'] = FALSE;
```
** Source https://gist.github.com/opi/fda934602521d69291c308f030a01c68**

**Comment by klonos** [comment]
Related: #3300

**Comment by herbdool** [comment]
It's not an easy solution and not sure we can avoid an API change. In D7 the problem was that if you saved a form that had overridden values those values got saved into the db, which probably confuses people. D8 came up with a complex solution to avoid this https://www.drupal.org/docs/8/api/configuration-api/configuration-override-system. I'm not sure if a generic solution could be simple or not, or just identify a few variables and add specific PRs for them alone.

**Comment by herbdool** [comment]
I think this is the accepted approach for checking if there's an override in settings.php for a variable in config:

```
      $custom_theme = settings_get('maintenance_theme');
      if (empty($custom_theme)) {
        $custom_theme = config_get('system.core', 'maintenance_theme');
      }
```

https://github.com/backdrop/backdrop/blob/4426b2be634baa40dab541b2c6a248fe6b1ad6c6/core/includes/theme.maintenance.inc

I'm not sure if it's worth overhauling this but if people submit a PR then they also need to account for places in core and contrib that are already using this approach. And need to ensure that the override won't get saved to config if it's in a form.

**Comment by herbdool** [comment]
Here's an example of a non-intrusive, barebones approach for one variables, the `error_level`: https://github.com/backdrop/backdrop/pull/2607 -- it only changes where `error_level` is called that it first checks the settings file.

It's backwards compatible and simple. And the override won't get saved to the config file accidentally. But it doesn't include any way of showing the end user that the variable is overridden in the settings file when they're on the form. That could be a different issue since it would be good to first allow people to use this and then improve the UX.

**Comment by jlfranklin** [comment]
> It's not an easy solution and not sure we can avoid an API change. In D7 the problem was that if you saved a form that had overridden values those values got saved into the db, which probably confuses people. D8 came up with a complex solution to avoid this.

D7 would save the value, but the form would continue to show the override.  D8 (unless they've changed it) shows the database value, even when it's not in effect.  I found D8 lying to me about the current state of the setting to be much more frustrating than D7.

> I think this is the accepted approach. [...]

That's clearly built to be used in specific instances, and unfortunately it won't work in the general case.  There are plenty of settings where the override could legitimately be something where `empty()` returns TRUE.  If we patch CMI to check for overrides, we'll have to inspect the underlying settings variable directly to see if the `array_key_exists()`.

**Comment by herbdool** [comment]
@jlfranklin that's why I took a different approach in my sample PR https://github.com/backdrop/backdrop/pull/2607 by wrapping `settings_get` around the `config_get` the former which checks if the array key is set.

I figured we'd need a way to show which form items are overridden, but was thinking that for a minimal viable solution might be good to get something merged before that's figured out. We'd need to show a message for each form item that's overridden. Or disable them - easier to implement but still doesn't explain the override status.

**Comment by jenlampton** [comment]
I wonder it would be worth looking into adding a hook that would allow people to define the config names for keys that could be overridden. In core we could define the ~5 that we know are needed most often, but it would open the door to allowing contrib to add more.

We'd need to turn it around so `config_get()` called `settings_get()` instead, but only for those 5 magical keys.

If there was a match, we could also set a message to the user saying that X value had been overridden, and changing the setting in the UI may have no affect. It may even be possible to disable that form element too, if the hook provided the config name, a human-readable label (for the message), and a form API key (or keys) (to disable the element).

**Comment by herbdool** [comment]
I've updated my proof of concept PR to provide some UX so admins can see if a variable is overridden. It uses a `#pre_render` and a new `#config_variable` property of the element (only way to know what config file and variable is associated with the form element).

![Screenshot from 2019-04-23 16-23-48](https://user-images.githubusercontent.com/1071483/56613359-7caa5f80-65e4-11e9-8fb0-9490e0f80032.png)

I'm sure it could be prettier but wanted to share as a concept.

@jenlampton I don't like the idea of config_get calling settings_get, even if for only some variables. This seems like it invites an infinite loop. People can already call `settings_get('variable', config_get('config_file.settings', 'variable))` so if they do that then it could end up calling itself ad infinitum.

**Comment by jenlampton** [comment]
I like the UX in the proof of concept @herbdoo,l but I don't like the implementation. The idea of needing to hard-code override support into every use of every variable in core turns my stomach. 

> People can already call settings_get('variable', config_get('config_file.settings', 'variable)) so if they do that then it could end up calling itself ad infinitum.

Oh jeez, yeah. I'd forgotten about that. 

Maybe we need something new? Something that can take values set in settings.php and hook into `config_get()` in a way that works for contrib.  Maybe `overrides_get()`?

**Comment by herbdool** [comment]
@jenlampton there are two parts to this. So if I understand you don't like the first part which makes it explicit to do something like `settings_get('variable', config_get('file', 'variable'))`. Core already does something similar:

```
$custom_theme = settings_get('maintenance_theme');
if (empty($custom_theme)) {
  $custom_theme = config_get('system.core', 'maintenance_theme');
}
```

I figured it probably made sense to continue the same approach. Especially since we likely do not want to do with all variables. And we still want to use the `config_get` in the form, otherwise we will have the same problem as in D7 where saving the form will save the overridden value to the config file, which we don't want. Even if we created an `override_get()` we would still have that problem and it would somehow have to be aware that it's being called from a form in some cases. Not sure how that would work, but seems complex.

The second part is displaying it in form elements. I'm also not sure how an `override_get()` would help with this.

In D8 the form API and configuration API and the override API all seem to be more tightly integrated from what I've seen. I just don't think it's possible in Backdrop without breaking backwards compatibility. Perhaps I'm wrong, but I'm not sure if I want to spend a tonne of time on this. Does anyone else want to take a crack at this?

**Comment by jenlampton** [comment]
> So if I understand you don't like the first part which makes it explicit to do something like settings_get('variable', config_get('file', 'variable')).

Exactly. In order to support all config, this would require rewriting every place in core that config is called. That's a lot of re-writing!

> Core already does something similar... I figured it probably made sense to continue the same approach.

What we had in the settings file for Drupal 7 worked, because it override all variables. It doesn't work in backdrop because it doesn't override all of config. If we continue the same approach, we're going to be running up against the same limitations.

> Especially since we likely do not want to do with all variables.

We've already proven that we aren't very good at guessing which variables we do want to do it with. Which variables they are needs to be pluggable, so that contrib can fill in where core gets it wrong. 

> And we still want to use the config_get in the form

...which we can do if retrieving the settings happens as part of `config_get()`.

> ... we will have the same problem as in D7 where saving the form will save the overridden value to the config file

... we can mitigate this if we use the same logic in `config_set()` to skip values that have been overridden.

> Even if we created an `override_get()` we would still have that problem ...

I'm not sure I understand, which problem? In my mind, `settings_get()` would become deprecated/removed, and `overrides_get()` would be the replacement. Using a different name would allow the backwards compatibility, and the freedom to create a new system that works how we need it to.

> it would somehow have to be aware that it's being called from a form in some cases. Not sure how that would work, but seems complex.

I was thinking that `config_get()` would check the list of overridden values, call `overrides_get()` (only) when there is a match, and `overrides_get()` could set some kind of flag for each value as a replacement is substituted.

When the form is rendered, we can check the form element keys for a match in the flags, disable that element, and set a message. (This sounds simple, but I bet you're right and it's going to be horribly complex in implementation...)

> Does anyone else want to take a crack at this?

I'd like to take a crack at it....  but, likely not before code freeze on Tuesday. :)

**Comment by herbdool** [comment]
>> So if I understand you don't like the first part which makes it explicit to do something like settings_get('variable', config_get('file', 'variable')).

> Exactly. In order to support all config, this would require rewriting every place in core that config is called. That's too much re-writing.

> > Core already does something similar... I figured it probably made sense to continue the same approach.

> What we had in the settings file for Drupal 7 worked, because it override all variables. It doesn't work in backdrop because it doesn't override all of config. If we continue the same approach, we're going to be running up against the same limitations.

>> Especially since we likely do not want to do with all variables.

> We've already proven that we aren't very good at guessing which variables we do want to do it with. Which variables they are needs to be pluggable, so that contrib can fill in where core gets it wrong.

There's nothing stopping any contrib module from checking the global settings variable now. I did it with Reroute Email module.

I don't think it makes sense to make every variable overridable. If more variables need to be overridden they can be added in future commits. Nothing stopping us.

>> And we still want to use the config_get in the form

>...which we can do if retrieving the settings happens as part of `config_get()`.

>> ... we will have the same problem as in D7 where saving the form will save the overridden value to the config file

>... we can mitigate this if we use the same logic in `config_set()` to skip values that have been overridden.

Somehow the function needs to know it's being called in a form for that to happen. And to do that you probably have to pass it a new parameter. Then do that for all calls in all forms.

>> Even if we created an `override_get()` we would still have that problem ...

>I'm not sure I understand, which problem? In my mind, `settings_get()` would become deprecated/removed, and `overrides_get()` would be the replacement. Using a different name would allow the backwards compatibility, and the freedom to create a new system that works how we need it to.

We can't deprecate `settings_get`. It's being used extensively in core outside of any calls to config.

>> it would somehow have to be aware that it's being called from a form in some cases. Not sure how that would work, but seems complex.

>I was thinking that `config_get()` would check the list of overridden values, call `overrides_get()` (only) when there is a match, and `overrides_get()` could set some kind of flag for each value as a replacement is substituted.

>When the form is rendered, we can check the form element keys for a match in the flags, disable that element, and set a message. (This sounds simple, but I bet you're right and it's going to be horribly complex in implementation...)

We can't assume the form element key matches the config key, there are lots of cases where they don't match. And it doesn't address how it would know which file it came from.

>> Does anyone else want to take a crack at this?

>I'd like to take a crack at it....  but, likely not before code freeze on Tuesday. :)

**Comment by jenlampton** [comment]
> There's nothing stopping any contrib module from checking the global settings variable now. 

I'm not talking about overriding settings - I'm talking about overriding config. The new system will replace settings entirely with a more robust solution that matches what we had in Drupal 7.

> I don't think it makes sense to make every variable overridable. If more variables need to be overridden they can be added in future commits. Nothing stopping us.

Just to clarify - I meant every value in every config file. There's no way core can know which contrib config values will need to be overridable, and it wouldn't make sense to hard code config values in core anyway.

> We can't deprecate settings_get. It's being used extensively in core outside of any calls to config.

We can, once it's replaced with `config_get()` and `overrides_get()` (or whatever). When the new system is committed, `settings_get()` should remain only as wrapper function around the replacement functionality, at that point it should be safe to deprecate.

> We can't assume the form element key matches the config key, there are lots of cases where they don't match (particularly in contrib). 

Yep, this is why we need the hook. `hook_overrides_info()` can provide the config name, the human readable name, and any form element keys that match. It may need more stuff too, but it's hard to predict without the proof of concept :)

**Comment by herbdool** [comment]
> We can, once it's replaced with config_get() and overrides_get() (or whatever). As long as the new system can do everything settings_get/set did (and everything we lost from D7) then we can replace those instances in core that are not related to config, with whatever we end up doing instead. When the new system is committed, settings_get() should remain only as wrapper around the replacement functionality. At that point it should be safe to deprecate, and later remove.

@jenlampton excuse my bluntness: we can not and do not want to deprecate `settings_get()`. It serves a purpose separate from CMI. All these settings are set in settings.php and have nothing to do with CMI (read more https://github.com/backdrop/backdrop-issues/issues/280):

hash_salt
update_free_access
maintenance_theme
form_cache_expiration
404_fast_paths_exclude
404_fast_paths
404_fast_html
proxy_server
proxy_port
proxy_username
proxy_password
proxy_user_agent
proxy_exceptions
reverse_proxy
reverse_proxy_addresses
reverse_proxy_header
omit_vary_cookie
allow_authorize_operations
https
backdrop_drupal_compatibility

In Drupal 8 they renamed the `$conf` global to `$config` and that now serves the purpose of overriding CMI https://www.drupal.org/node/1882698.

So far in the contrib modules I've worked on which can override CMI, I've used @quicksketch's recommendation:

> $conf only affects variable_set/get(), which are deprecated as they're not config-management friendly. If it's something like an authorization token you're storing, $settings in settings.php is the best bet, then use settings_get(). We've had a few modules that want things in config or settings.php, and we don't have a universal way of overriding config_get(). So what I've seen is doing a settings_get() first, and if empty, use config_get()
$setting = settings_get('my_setting');
$setting = isset($setting) ? $setting : config_get('my_module.settings', 'my_setting');

If we add some changes that conflict with that approach we'll need to find out which other contrib modules use that approach and get them to change it and get the users to change their settings files.

**Comment by jenlampton** [comment]
> @jenlampton excuse my bluntness: we can not and do not want to deprecate settings_get(). It serves a purpose separate from CMI.

I haven't looked at any code for this yet and I'm sure it will all make more sense when I have. I must was thinking about whatever ended up in settings.php to replace whatever was there in D7 to override variables (but was also used for something else). I must have been thinking of `$config` in Drupal 8.

I'd still like to work on a proof-of-concept PR for this after May 15th, as I'm pretty sure my approach will work. I agree that we'll need to be careful about how contrib was using settings to override config, but I'm pretty sure we can do that by adding another function as the recommended approach.

**Comment by herbdool** [comment]
Here's another way to get some of the functionality, at least in terms of developers wanting to set different variables for dev environments: https://www.thirdandgrove.com/this-custom-drush-command-will-make-you-a-better-drupal-developer - create a drush command to enable/disable modules and set config variables all in one go.

**Comment by klonos** [comment]
Related?: #4079

**Comment by alanmels** [comment]
> https://www.thirdandgrove.com/this-custom-drush-command-will-make-you-a-better-drupal-developer

I also thought to use drush to set certain variables on local dev, however CLI gives:

```
The drush command 'variable_set' could not be found.  Run `drush cache-clear drush` to clear the commandfile cache if you have installed new          [error]
extensions.
```

so the command has not been integrated yet. Also as I understood commands like `variable_get` and `variable_set` will be deprecated in Backdrop 2.x, so more viable solution would be nice.

**Comment by herbdool** [comment]
@alanmels `variable_set` only work at this point for contributed modules that haven't migrated their variables to use config. Everything in core only uses `config_set`

**Comment by herbdool** [comment]
@alanmels Here's an example of how to set things with a custom drush command. I've tested it locally. (Just need to create a .info file and an empty .module file. Or you could get fancier and pass arguments to make it more flexible.)

```
<?php

/**
 * @file
 * Custom Drush integration.
 */

/**
 * Implements hook_drush_command().
 *
 * @return
 * An associative array describing your command(s).
 */
function dev_mode_drush_command() {
  return array( 'golocal' => array(
      'description' => dt('Puts your site in local development mode.'),
    ),
  );
}

/**
 * Put the site in local development mode.
 */
function drush_dev_mode_golocal() {
  // Enable dev friendly modules.
  $enable = array('devel', 'reroute_email', 'dblog', 'installer', 'update', 'field_ui');
  module_enable($enable, TRUE);
  foreach ($enable as $e) {
    if (module_exists($e)) {
      drush_log(dt('Module enabled: @module', array('@module' => $e)), 'ok');
    }
  }

  // Disable any production modules that you don't want to run locally.
  $disable = array();
  module_disable($disable);
  foreach ($disable as $d) {
    if (!module_exists($d)) {
      drush_log(dt('Module disabled: @module', array('@module' => $d)), 'ok');
    }
  }

  // Make sure the rerouting of email is turned on so we don't send emails to
  // actual users from our local installations.
  if (module_exists('reroute_email')) {
    config_set('reroute_email.settings', 'enable', 1);
    config_set('reroute_email.settings', 'address', 'dev@example.com');
    drush_log("Email is being rerouted to dev@example.com.", 'ok');
  } else {
    drush_log('Emails will be sent to users!', 'warning');
  }

  // Allow everyone to see devel messages like dpm().
  if (module_exists('devel')) {
    user_role_grant_permissions('anonymous', array('access devel information'));
    user_role_grant_permissions('authenticated', array('access devel information'));
    drush_log("Enabled devel permissions to roles.", 'ok');
  }

  // Set some dev-friendly settings
  config_set('system.core', 'cache', "0");
  config_set('system.core', 'error_level', "all");
  config_set('system.core', 'preprocess_js', "0");
  config_set('system.core', 'preprocess_css', "0");
  config_set('system.core', 'page_compression', "0");
  drush_log('Page cache, page compression, JS optimization, and CSS optimization disabled.', 'ok');

  backdrop_flush_all_caches();
  drush_log('All caches cleared.', 'ok');

  drush_log('Site ready for development!', 'ok');
}
```

**Comment by jenlampton** [comment]
Another thing we could think about doing is moving some of these config values to the state system. Maybe CSS and JS aggregation is a state, and not a setting? What about the other things we'd like to override locally, should we review each of them?

**Comment by alanmels** [comment]
@herbdool, thanks for sharing a code, but I was looking for more viable solution for posterity when commands like `config_get` , `config_set` , if I understood correctly, will be deprecated in Backdrop 2.x.

**Comment by alanmels** [comment]
> Another thing we could think about doing is moving some of these config values to the state system. Maybe CSS and JS aggregation is a state, and not a setting? What about the other things we'd like to override locally, should we review each of them?

Jen, I don't feel Backdrop knowledgable enough to suggest any way, however what I am sure about is that I don't want Backdrop to fall behind of all the convenient features that Drupal developer can set prior starting to work on a new project. I thought it was a simple thing to set certain variables to desired values, just like it's possible on both D7 and 8, however the reality turned out differently. I am not sure why at all overriding ANY variables in settings.php file was prevented in the first place?

**Comment by jenlampton** [comment]
> I am not sure why at all overriding ANY variables in settings.php file was prevented in the first place?

It wasn't intentionally prevented. This was a side effect of having an efficient configuration management system. Since our config values are stored in json and read directly off disk, there is no "alter" layer between retrieving those values and rendering a page. 

In both Drupal 7 and Drupal 8 the configuration is stored in the Database, and such a layer sits between when the values are extracted from database, and when they are passed to the rest of the system, allowing overrides from settings.php to squeeze their way in.

We have talked about adding an alter layer into our system -- but have paused due to concerns about how much slower it would make everything if it were necessary to run all configuration retrievals through such a layer. (Though, no actual data has been gathered on this yet, since it has not yet been built)

We have also talked about allowing only a few values to be altered, but deciding which ones has been troublesome. We can support what's in core -- but what about contrib?

There has also been some talk about allowing some backdrop sites to choose to store their configuration in the database, but that would still be an opt-in solution on a site-by-site basis (and requires a significant core change).

I agree that this is something we need -- but no obvious solution has prevented itself yet. Hence the "needs more feedback" label on this thread.

**Comment by alanmels** [comment]
@jenlampton Thanks for the detailed explanation. Now I see this issue better.

>have paused due to concerns about how much slower it would make everything if it were necessary to run all configuration retrievals through such a layer. 

Whatever the outcome of this discussion will be, I am for better performance of Backdrop in the first place. Better no changes than causing reduced efficiency.

**Comment by herbdool** [comment]
@alanmels 

> commands like config_get , config_set , if I understood correctly, will be deprecated in Backdrop 2.x.

I think you mean variable_set is being deprecated. My code above doesn't include any deprecated functions.

**Comment by herbdool** [comment]
Core already "alters" some config settings but does so as one-offs. Higher up in this thread I already posted this actual code from core:

```
$custom_theme = settings_get('maintenance_theme');
if (empty($custom_theme)) {
  $custom_theme = config_get('system.core', 'maintenance_theme');
}
```

If the maintenance theme is set in settings.php then it used. Otherwise it uses what is set in the config system.

So it is already possible. We've just had disagreement on whether to continue this pattern for other config or whether to come up with a whole new layer.

**Comment by jenlampton** [comment]
@herbdool I was trying to address that with this paragraph:

> We have also talked about allowing only a few values to be altered, but deciding which ones has been troublesome. We can support what's in core -- but what about contrib?

**Comment by alanmels** [comment]
> @alanmels
> 
> > commands like config_get , config_set , if I understood correctly, will be deprecated in Backdrop 2.x.
> 
> I think you mean variable_set is being deprecated. My code above doesn't include any deprecated functions.

You are right, I've got confused. We will use your method until this issue is addressed. Thanks!

**Comment by herbdool** [comment]
> Another thing we could think about doing is moving some of these config values to the state system. Maybe CSS and JS aggregation is a state, and not a setting?

I can think of a couple problems with changing some config to state:

* It's a breaking change so would need to be 2.0.
* Can't set state in settings.php which was what we were trying to achieve.
* State is typically not configured in the UI. If these were changed they would be exposed in the UI.
* State is only stored in the database so can't deploy these states even though they might seem to be config.

**Comment by jenlampton** [comment]
I've re-titled this issue to be the more global problem of overriding any/all config values in settings.php, but I really like the simplicity of the PR in https://github.com/backdrop/backdrop-issues/issues/4174. I think we should switch to using that method for the variables that are most commonly overridden.

**Comment by docwilmot** [comment]
Late to the party here but why not add a check for settings in `Config::get()`? The `$settings` global will already be already available, so I imagine it would be a matter of adding `global $settings; if (isset($settings[$key]...`. 

Is that likely to affect performance?

**Comment by herbdool** [comment]
@docwilmot I think because we don't want it to use the $settings['key'] in all config_get calls. For instance, if we override `error_level` we don't actually want the override value to have it be the default value in the form. It would cause headaches if someone then saved the form because the override value would then get saved into the config system. This was a problem with D7.

**Comment by alanmels** [comment]
> @docwilmot I think because we don't want it to use the $settings['key'] in all config_get calls. For instance, if we override `error_level` we don't actually want the override value to have it be the default value in the form. It would cause headaches if someone then saved the form because the override value would then get saved into the config system. This was a problem with D7.

@herbdool, I don't think there is such a problem on D7, because as soon as you put an override in the `settings.php` file (or `settings.local.php`), the respective configuration page always picks its value and reflects on the form accordingly. Look at the following gif:

![error_log](https://user-images.githubusercontent.com/56604405/68251318-eeec0a00-0033-11ea-8ad1-4598af0d53c3.gif)

In other words, saving any form never overrides the desired configuration. I don't see any obstacles in doing the same on Backdrop.

**Comment by docwilmot** [comment]
Oh dear, so it seems we have two bad UX choices:
1. the form saves what you want but Backdrop will ignore your saved choice and use the override, as in [PR by @herbdool](https://github.com/backdrop/backdrop/pull/2964/)
2. or the form refuses to save what you want because the override stops it, as in the image above by @alanmels 

I would prefer choice 2 above. If I'm overriding config, there shouldnt be that much of an issue if the config value saved is always exactly the value I want (which I hardcoded in `settings.php`). The visual feedback is clearer here. This option would result if we added a `global $settings` check in `config_get()`.

Not saying this is the answer, but I dont think we have options apart from 1 and 2 above.

In either case, we should add an entry in the status page and/or a watchdog entry if an overridden config is used.

**Comment by jenlampton** [comment]
> Oh dear, so it seems we have two bad UX choices:

I had an earlier example that disabled the form element when the value was overridden. That would at least make it clear to the viewer that saving the form isn't an option.

We'll also provide a message to the user when they save the form, so we could state the overridden value there too. 

> In either case, we should add an entry in the status page and/or a watchdog entry if an overridden config is used.

ooooooh good idea :)

**Comment by docwilmot** [comment]
> that disabled the form element when the value was overridden

I cannot imagine how to make this work generically though. We'd need to add a `'#disabled' =>config_is_overridden('whatever')` to  form elements that use a config result as default value which is allowed to be overridden. And invent a `config_is_overridden(()` function of course.

This means it is only going to be reasonable if we specify which configs are overridable. So agreeing with your comment at https://github.com/backdrop/backdrop-issues/issues/2805#issuecomment-485499524 in other words.

**Comment by quicksketch** [comment]
I posted a proof of concept for an "override everything" capability akin to that of Drupal 8. For consistency, I adopted their exact syntax in settings.php for overriding:

```
$config['system.core']['site_name'] = 'My Backdrop site';
$config['system.core']['file_temporary_path'] = '/tmp';
```

Though of course the config names and keys are different.

The PR does include a `$config->isOverridden()` and `config_is_overridden()` check, which could be used to disable fields, but I haven't integrated it in any way into `system_settings_form()`, though I would think that would be possible with a little additional effort.

PoC PR: https://github.com/backdrop/backdrop/pull/2984

**Comment by herbdool** [comment]
I've come back to this once I've realized that we may need to set `file_temporary_path` dynamically on Pantheon, since it isn't a relative path. In the short term a temporary patch to core, but would be good to get @quicksketch POC good enough to merge.

**Comment by herbdool** [comment]
I'm happy with @quicksketch's PR. I think it's ready to merge as is. And the UI can come later. It works for me. And it avoids the main problem in d7 where saving the form in the UI would copy the override into the config file. So this avoids that confusion. Coming up with messages in every form is important but not a blocker in my mind.

**Comment by klonos** [comment]
> ...the UI can come later.

I fully agree with that. That could be something that someone like myself can work on (to take the load off of @quicksketch and other core committers); whereas the implementation of this feature (work that's already been done by @quicksketch) is something I would struggle with.

Thanks once again @quicksketch for working on this 👍

**Comment by klonos** [comment]
... @herbdool if you agree, can you please add the 1.16.0 milestone (I cannot do it myself, since I'me the one that added the `milestone candidate - minor` label to the issue).

**Comment by herbdool** [comment]
@klonos I've added the milestone

**Comment by quicksketch** [comment]
Thanks @herbdool and @klonos! I had forgotten this one had a working PR. :joy: 

@herbdool Awesome thanks for the tests! I expanded on them to cover overriding nested values and to cover the writing (or not) of overridden config values to disk.

Could you take one more look: https://github.com/backdrop/backdrop/pull/2984 ?

Responding to some feedback from the PR:

>     is $conf still being used? Can we remove it if not? [Update: we cannot]

`$conf` is the legacy settings.php from Drupal 7. It is still used in `variable_set()` and `variable_get()` calls. Though variables are deprecated, they continue to work in Backdrop currently. Fortunately we don't make any mention of the old variable in settings.php and on most sites the `$conf` variable is entirely empty.

>     How will this interact with the config translation functions?

Because `getTranslated()` ultimately calls `get()` (which takes into account overrides) if you were to override a translated config value, the translations would use the overridden string when `t()` is called on it. Matching strings would need to exist in Locale module in order to actually include the translation.

>     I can't tell what setOverrides() is for. It's not used in the PR.

It's a setter method to set the internal list of things that the `Config` class thinks is overwritten. It don't think it's going to be common to use it, since the overrides are set in the constructor already. However, since we have getOverrides() it seemed that the complement should be provided as well.

**Comment by herbdool** [comment]
Tests still passing. Okay, I've taken another look at the tests - much more comprehensive. It looks like it covers all the bases now.

And thanks for your responses. Seems like this PR shouldn't be a problem for any of that. Looks good to me!

**Comment by quicksketch** [comment]
Merged into 1.x for 1.16.0. Thanks everyone for the great suggestions, code, reviews, tests, and feedback!

**Comment by herbdool** [comment]
Where would we add some documentation for this? And perhaps a follow-up issue for adding to the docs? @klonos you might know?

**Comment by klonos** [comment]
We already have inline documentation in the settings.php file itself @herbdool so we go that bit covered. We could also add a change record in https://api.backdropcms.org/change-records since this seems more like a develop-y thing, or it could go under https://api.backdropcms.org/advanced-installation. Anyone has any better idea?

**Comment by herbdool** [comment]
@klonos there's a "needs change record" label on this so at least that. Though I'm not sure of the workflow for adding that.

Also something in the advanced section would be helpful. Someplace so if someone does an internet search it'll come up.

**Comment by klonos** [comment]
I've created a draft change record for this here: https://api.backdropcms.org/change-records/any-config-value-can-be-overridden-via-settingsphp

I tried to provide examples for things like specifying values that are arrays, and for nested settings.

I could use some 👀 on it re the validity of the examples.

PS: Once we have polished wording and examples in the change record to cover most common use cases, I think that it might be worth updating the docblock in the actual settings.php file.

**Comment by klonos** [comment]
...I'm reopening this issue for visibility purposes. Let's close once documentation and change record are published.

**Comment by herbdool** [comment]
@klonos I would preview it but I don't have a user account on the API site. Perhaps you or @jenlampton could give me one?

**Comment by jenlampton** [comment]
A welcome message with further instructions has been e-mailed to the new user herbdool.

**Comment by herbdool** [comment]
thanks @jenlampton 

@klonos I updated it. I used examples from the code here https://github.com/quicksketch/backdrop/blob/61ee9aa44d93808bf01bbd49991ebdbdee981857/core/includes/config.inc#L662.
