### ISSUE TITLE
Restore admin-list icons to "Add content" page

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2856]
## Describe your issue or idea
As @olafgrabienski reported in https://github.com/backdrop/backdrop-issues/issues/2802#issuecomment-330380451, he was surprised that there were no icons on the "Add content" page after an update to 1.8.

We specifically removed them in https://github.com/backdrop/backdrop-issues/issues/1178 to clean up the UI on most administration pages. However, I feel that the node/add page is special, and perhaps deserves to keep it's icons. Should we add them back?

---

PR https://github.com/backdrop/backdrop/pull/2016

**Comment by olafgrabienski** [comment]
Thanks @jenlampton ! Actually, I only noted that the icons were missing because I got a not-found-message related to the former used icons after the core update. Apart from being surprised about the missing icons, I'm not sure if they are really missing.

Here a comparison:

**With icons (this PR):**

![screen-backdrop-pr-2016-node-add-with-icons](https://user-images.githubusercontent.com/14188307/30597741-2e9a071a-9d58-11e7-8fd9-e6dd817df06f.png)

**Without icons (current Backdrop 1.8.0):**

![screen-backdrop-pr-2016-node-add-without-icons](https://user-images.githubusercontent.com/14188307/30597758-3bb6d63a-9d58-11e7-989f-ef1fe8029905.png)

In a way, the version without icons looks cleaner, doesn't it?

*If* we don't add some icons back to the *Add content* page, we might however state the removal of the icons more clear in the 1.8.0 release notes. I guess for most people it's hard to understand that they were removed in #1178.

**Comment by jenlampton** [comment]
>  I only noted that the icons were missing because I got a not-found-message related to the former used icons after the core update

I wonder if the not-found-message was because your cache needed to be cleared (old CSS file lingering, maybe?) or if there is a bug somewhere that we are still referencing the old item-list icon.

>  I only noted that the icons were missing because I got a not-found-message related to the former used icons after the core update

I really can't tell. They both look good to me :) Let's add some tags and see if we can get some more opinions.

**Comment by quicksketch** [comment]
Seems like we should restore them if they were inadvertently removed. Though I'm open to removing them if we agree that it's better without them entirely. Small comment on the current PR that we could improve: https://github.com/backdrop/backdrop/pull/2016#pullrequestreview-65148539

**Comment by Dinornis** [comment]
I do like icons if they serve a purpose, for example helping to find items quicker on a crowded page.  In this case I don't see any advantage in keeping these.

**Comment by klonos** [comment]
What @Dinornis said ^^ ...these icons do not serve any purpose AFAIKT. I say lets just keep them removed until someone complains that they miss them for a good reason :)

**Comment by jenlampton** [comment]
okay, closing issue then :) thanks all!
