### ISSUE TITLE
[UX] Installation requirements page looks broken

### ISSUE THREAD

**Issue by opi** [backdrop/backdrop-issues#2873]
## Describe your issue or idea

When using the web installer, the requirements page looks broken because the table is larger than the available space. Probably because this page use a `body.maintenance-page` class. As far as I see, there is no specific "install" classes.

### Steps to reproduce (if reporting a bug)

Try to install a Backdrop with bad `files` folder permission

### Actual behavior (if reporting a bug)

![image](https://user-images.githubusercontent.com/2423362/232447269-a40403fb-80c9-44d3-9dad-27ed5b22d9ed.png)

### Expected behavior (if reporting a bug)

**Solution 1**: Wrap the text of the requirements labels
![image](https://user-images.githubusercontent.com/2423362/232447593-99b4dddb-d4f1-4fe5-8634-a0d5f38a11b5.png)

**Solution 2**: Make the requirements page wider
![image](https://user-images.githubusercontent.com/2423362/232450039-1c4d6953-4af0-4b42-995a-58a67a330d69.png)

**Solution 3**: Move the requirements labels above the respective status/details text
![image](https://user-images.githubusercontent.com/2423362/232462259-a4bbed3d-95bb-4175-a866-b0dff970a679.png)

**Comment by jenlampton** [comment]
I wonder if we really need two columns in the table here. What if we used only a single column in the table, and used <divs> to place them on the same line - only when screen sizes are large enough to see them that way.

**Comment by quicksketch** [comment]
Just a note here that the left column of the installer has already been fixed (the alignment of items). We're only talking about the table on the right having problems at this point.

This table has problems both on desktop and mobile. On Desktop, the items may be squashed unnecessarily because the installer has a narrow presentation that caps out around 600px wide:

![image](https://user-images.githubusercontent.com/100206/38700206-28fdc4c0-3e4f-11e8-8919-c83bb3b50e78.png)

On mobile, things actually look pretty good but you don't have the capability to read the extended descriptions:

![image](https://user-images.githubusercontent.com/100206/38700257-4f7214da-3e4f-11e8-8442-90c1989c40ca.png)

**Comment by opi** [comment]
Issue came with this long label "Mysql Database 4-byte UTF8 support"

**Comment by olafgrabienski** [comment]
I'd suggest to change the desktop version to do the same as mobile, i.e. to put the label always *above* the description. And, desktop and mobile should both display the "more" link which lets you show the extended description.

**Comment by quicksketch** [comment]
Great suggestion @olafgrabienski, that sounds great to me too. It would solve both problems at once.

Markup may need to be modified for this purpose. Note this table is the same one that is used at `admin/reports/status`, so changes will affect both places.  On that page we do have a bit more horizontal space to work with on desktop, as we're not confined by the width of the installer screens.

**Comment by jenlampton** [comment]
I love this idea too @olafgrabienski, looks like now we just need someone to write the code for this? I'm adding the 'good first issue' tag since it might not be too much work to re-work a table...  but that might be an overly optimistic assumption...

**Comment by opi** [comment]
Playing around with this issue on Status report and Installation requirements, some thoughts:
- Desktop and mobile should have the same content.
- Having the label above is nice, and good for readability
- The more/less button pattern is odd. What about always showing extended description ?

Here is some screenshots 

![](https://i.imgur.com/MUpd3o9.png) 

![](https://i.imgur.com/Hhpcika.png)

![](https://i.imgur.com/oUlKcVa.png)

![](https://i.imgur.com/R67FZUa.png)

**Comment by olafgrabienski** [comment]
@opi In my opinion it's also okay to always show the extended description.

**Comment by klonos** [comment]
If I am not mistaken, in the site status report we always show errors and warnings expanded (with a "less" link) and show status and info messages collapsed (with a "more" link). I think that this makes sense because people are surely going to need to expand errors in order to fix things, while status messages they can ignore.

**Comment by jenlampton** [comment]
removing milestone. Adding milestone candidate tag.

**Comment by klonos** [comment]
Here's a PR that implements the design in the 3rd solution from the issue summary: https://github.com/backdrop/backdrop/pull/4405 (I've updated all the screenshot there by the way)

Relatively simple changes:
- I have added a new `phase-*` class to the page from `theme_status_report()`. So now we can specifically target `.phase-install`, `.phase-update`, or `.phase-runtime` in our CSS. This was inspired by this comment made by @opi in the original report:
  > As far as I see, there is no specific "install" classes.
- Added `'phase' => 'install'` in `core.install.inc` and 'phase' => 'update' in `update.php`, as an additional variable passed to `theme('status_report', ...)`.
- Tweaked `theme_status_report()` to place the label and description of each check in a single cell in the table if `$phase == 'install'`, and to be placing them in separate cells in all other cases (like previously).
- Added a couple of lines of CSS, targeting `.system-status-report.phase-install` specifically.

The result is what is shown in the screenshot in "Solution 3" in the issue summary. To test this on your local, you can:
- clone the PR branch from https://github.com/klonos/backdrop/tree/issue-2873
- edit the `core/modules/system/system.install` file around line 178, and change:
  ```diff
     // Make sure PDO is available.
  -  if (!extension_loaded('pdo')) {
  +  if (extension_loaded('pdo')) {
  ```
Try to run the installation.

**Comment by klonos** [comment]
OK, I've rebased the PR, and have also made these additional tweaks:
- Changed the wording of the text from `Check the messages and try again.` to `Resolve the problems and try again.` (since resolving any problems is what's actually required before trying again.)
- Moved the `Resolve the problems and try again.` text/link at the top of the table. Since errors and warnings are bubbling up the table rows, this change brings the text closer to the actionable "target" - the rest of the table rows are simply information and ticks of things being OK, so most people can even skip those.

Here's what this currently looks like:
![image](https://github.com/backdrop/backdrop-issues/assets/2423362/3e2956ae-cb39-4ddc-b1b9-58b8ef9055d9)

PS: the various error/warning rows in this table have more/less links, so we should make sure that these are using the improved toggles being introduced in #5090.

**Comment by yorkshire-pudding** [comment]
Haven't tested but screenshots look good

**Comment by klonos** [comment]
Noting that I am reusing this for #2858 and I'm really happy with the clean-up/result! There's some overlap in the changes made to `theme_status_report()` and `system.admin.css`, so I'll have to update the PR here once I'm done there.

**Comment by quicksketch** [comment]
I gave this another review and it looks great! Wow this is such a huge improvement to a rather important page. I merged https://github.com/backdrop/backdrop/pull/4405 into 1.x and 1.26.x. Thanks @opi, @klonos, @jenlampton, @olafgrabienski, and @yorkshire-pudding!

**Comment by klonos** [comment]
Yay! 🎉 ...this unblocks further work on #2858 now.
