### ISSUE TITLE
Dropdown: Menu item with sub-item doesn't expand anymore

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop/backdrop-issues#2879]
## Describe your issue or idea

I recently updated a Backdrop site to 1.8.0 with the core dropdown menu. After the update I noticed that main menu items with sub-items (menu parents) had no visual indicator of the sub-items, and they didn't react on mouseover anymore.

### Steps to reproduce (if reporting a bug)

Create a menu with some items and some sub-items (don't touch the "Show as expanded" checkbox during the item creations), place the menu in a layout, and configure it as dropdown menu.

### Actual behavior (if reporting a bug)

The menu items with sub-items are not perceptible as menu parents. The graphic indicator is missing, and you can't expand the parent via mouseover. (After you have clicked the parent and when you visit the respective page, everything is fine for *this* part of the menu but nor for other items with sub-items.)

### Expected behavior (if reporting a bug)

A menu item with sub-items is visually perceptible and opens on mouseover - irrespective of the state of the "Show as expanded" checkbox. (See https://github.com/backdrop/backdrop-issues/issues/2107#issuecomment-246253411 on this question.)

### Relevant version/system information (if applicable)

Backdrop 1.8.0 - I'm wondering if the current behaviour is a side effect of issue #2773 regarding the "Hierarchical tree" style which became part of the 1.8.0 release.

---

~PR by @akalata: https://github.com/backdrop/backdrop/pull/2029~
PR by @jenlampton https://github.com/backdrop/backdrop/pull/2072

**Comment by BWPanda** [comment]
I'm experiencing this too!

**Comment by olafgrabienski** [comment]
Thanks @akalata for the PR, and welcome to the Backdrop issue queue! (I didn't see the PR earlier because notifications seem to work for the issue itself but not for a related PR. Have updated the issue description with a link to the PR.)

I had a look at the automatically generated PR sandbox site and created some menu sub-items in the About section. Looks good: the About item is perceptible as menu parent, the graphic indicator is showing up, and the parent is expandable via mouseover as expected.

Not all tests on the PR were successful, tagging the issue as "pr - needs review" hoping that someone can have a look at the code.

**Comment by opi** [comment]
I understand that the feature introduced in #2773 breaks the behaviors of the dropdown menu style.

But I think the real issue is that the menu items or not "Show as expanded" by default. If you chack that box in every menu item, child items will be displayed. See related issue #2782

**Comment by olafgrabienski** [comment]
> But I think the real issue is that the menu items or not "Show as expanded" by default.

I see! Doesn't the PR fix it by adding a condition to not expand the items only in certain situations? (Missing coding skills to evaluate the PR more detailed.)

**Comment by opi** [comment]
The PR force child items to be displayed (expand) in every case, even if the "expand" checkbox is not checked. This is not correct IMHO, but this is the default behavior in Backdrop <1.8.x ;

**Comment by olafgrabienski** [comment]
I see your concern! Do you suggest to add the "Expand all" checkbox of #2773 also for the Dropdown menu style?

**Comment by MegaphoneJon** [comment]
> But I think the real issue is that the menu items are not "Show as expanded" by default.

Thanks for documenting this @opi! While I agree there's a UX improvement to be made here, this solved the immediate issue for me.

**Comment by jenlampton** [comment]
> But I think the real issue is that the menu items are not "Show as expanded" by default.

For a drop-down menu all items for all elements need to always be "expanded" -- so the value of that checkbox should not change anything for drop-down menus . This is definitely a bug, especially since sites that were working before updating to 1.8.0 suddenly became broken. :(

I've reviewed the PR in the sandbox, and this seems to fix the issue for me. The code also looks good, RTBC!

**Comment by quicksketch** [comment]
Though the PR seems to work, I'm worried about removing the default value from `system_menu_block_defaults()`. It's intended to provide the list of defaults so that we never accidentally hit an "undefined variable" value when checking the settings. I think @jenlampton is working on rerolling to correct this concern.

**Comment by jenlampton** [comment]
I've pushed a new PR at https://github.com/backdrop/backdrop/pull/2072/files that changes the default values from FALSE to TRUE. This has the same effect, but doesn't remove the keys from the defaults array.

**Comment by quicksketch** [comment]
We can't change the default from `FALSE` because it's there for compatibility. Prior versions of Backdrop didn't have the expand_all option at all, so for those sites need to remain with the default set to `FALSE`. By changing it to TRUE it will suddenly expand everyone's menus upon upgrading. There's also a fault in the latest PR that would prevent it from working properly: https://github.com/backdrop/backdrop/pull/2072/files#r161649510

I took a stab at this one as well, as it's holding up the 1.8.2 release. Could you review https://github.com/backdrop/backdrop/pull/2073? With the time available, we may need to bump this to the next release.

**Comment by jenlampton** [comment]
That also seems to do the trick, marking RTBC.

**Comment by quicksketch** [comment]
Super, thanks. Now we can get 1.8.2 out the door.
