### ISSUE TITLE
[UX] Remove check for hook_node_form() before printing type in node type list

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2881]
## Describe your issue or idea

Sometimes when you add a module that provides a content type (like forum or book) and then disable and uninstall the module, you may still have links in the admin menu to the content type configurations. But, oddly, that type is no longer listed on the admin/content/types page.

That's because this check is run:
```php
if (node_hook($type->type, 'form')) {
```

I don't know why a node type would need a `hook_node_form()` implementation in order to be listed here, this is the node type UI. 

I recommend we remove this check.

---
PR: https://github.com/backdrop/backdrop/pull/2021

**Comment by quicksketch** [comment]
Thanks, you're right this is a strange check. The edit forms still exist, and they show up in the admin menu. Why wouldn't they be listed on `node/add`? It's a weird check that has probably existed since the dawn of this page. As removing the check has no actual impact on functionality (it's only a display modification) I've merged in the PR to 1.x and 1.8.x.
