### ISSUE TITLE
Add the option to disable translation links

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop/backdrop-issues#2910]
~~In Drupal 7~~ In Drupal 7, *using the i18n module*, there is an option to disable translation links. This option is missing in Backdrop.

By "translation links" I mean the language switcher links which point to the other language(s). They are visible by default at the bottom of a node when there is at least one (published) translation of the node.
In Drupal 7, if you use the *i18n* module, there are two ways to disable these translation links:

- Set the "Language" (pseudo) field on the *Manage display* page at `admin/structure/types/manage/MY-TYPE/display` to "Hidden".
- Go to the *Node options* tab of the *Multilingual settings* page at `admin/config/regional/i18n/node`, and enable the option "Hide content translation links".

~~The first way is part of Drupal 7 core, so~~ In my opinion it would be good to add the option to Backdrop.

----

~~PR: https://github.com/backdrop/backdrop/pull/2041~~
PR: https://github.com/backdrop/backdrop/pull/3398

**Comment by serundeputy** [comment]
@olafgrabienski give this a test when you get a chance:

Website: http://2041.backdrop.backdrop.qa.backdropcms.org
Username: admin
Password: hfdN7aRN

Crates a `Content Options` tab at: `/admin/config/regional/language/node-configure`
<img width="1707" alt="screen shot 2017-11-28 at 8 01 04 pm" src="https://user-images.githubusercontent.com/6763671/33352438-e7743e9a-d476-11e7-9acd-c481feb5b491.png">

Similar to how the `i18n` module does it in Drupal 7.

If a user checks that box the translation links are not rendered as part of nodes that have translations. If the uncheck the links will be there.

TODO
----
- [ ] Update hook to give existing sites a default config value of `0` for `translation_hide_translation_links` in `translation.settings.json`

**Comment by olafgrabienski** [comment]
Correction: The option in question is **not** part of Drupal 7 core, sorry for for the incorrect information! I've modified the issue description and changed the labels respectively.

**Comment by olafgrabienski** [comment]
@serundeputy Thanks for the PR! Looks very good to me, works as expected, also with teasers.

**Comment by olafgrabienski** [comment]
@quicksketch suggested in a video chat to change the wording of the checkbox label from *Hide* to *Show* content translation links, which would then be enabled by default. I agree that this sounds more straightforward.

**Comment by serundeputy** [comment]
Updated PR: https://github.com/backdrop/backdrop/pull/2041

* Flipped language and logic to `Show content translation links` 
* Added D7 upgrade path for the `i18n` setting
* Tested D7 upgrade from site with `i18n` that had setting for Hiding the translation links 👍

**Comment by olafgrabienski** [comment]
@serundeputy The UX change looks good to me. Can't evaluate the other changes. However RTBC, or do we need another review?

**Comment by quicksketch** [comment]
I posted some feedback to the PR: https://github.com/backdrop/backdrop/pull/2041#pullrequestreview-86055668

Conceptually looks like it would work. I find the location and contents of the new settings form to be not very intuitive. Somehow I would expect translation content settings to contain more than just a single option, but I suppose that is because most content settings for translation are on individual content types, rather than global settings like this.

It got me thinking that it would be ideal to be able to disable any type of node/comment link, but that is probably going to far down the rabbit hole.

As a separate possibility, perhaps we could do the following:

- Move the enabling of translation to a new vertical tab on the node type.
- Add the checkbox for "Show links to translations" to this tab.

Mocked up via the browser inspector, here's what this might look like:

![image](https://user-images.githubusercontent.com/100206/34469898-f5cbb3c2-eedb-11e7-9592-7fa0b287187a.png)

Personally, I've always had trouble finding the translation setting (they are currently under "Publishing options"). So moving it to a dedicated tab both makes it more discoverable and provides a location for other multilingual settings.

**Comment by quicksketch** [comment]
One more comment: I find the "Multilingual support" radio buttons also to be terribly confusing.

**Comment by olafgrabienski** [comment]
Oh yes, moving translation and other multilingual settings to a separate tab in the content type settings - including the checkbox for translation links - is a great idea! That will help to find these settings easily.

> I find the "Multilingual support" radio buttons also to be terribly confusing.

I've never used the option "Enabled" so far, only "Enabled, with translation". Not sure but I guess the "Enabled" option (without translation) is for sites which contain primarily *different* content per language, letting you just assign languages to certain content items. If someone can confirm this assumption I'd try to improve the help text respectively.

Apart from that, the "Enabled" (without translation) use case is a good reason to not call the vertical tab "Translation settings". "Multilingual settings" would be more convenient, in my opinion.

> ... it would be ideal to be able to disable any type of node/comment link, but ...

That would really be ideal! It could be part of an improved "Manage display" page where you can dis/enable not only node links but also other node related options or information like author or post date as discussed partly in https://github.com/backdrop/backdrop-issues/issues/2084#issuecomment-244819268.

**Comment by jenlampton** [comment]
Removing milestone.

**Comment by olafgrabienski** [comment]
> This should have been moved to needs work. There are multiple code reviews on the PR that need addressing

@serundeputy - are you up to work on this again and to address the code reviews? Would be great!

Let's also discuss then the idea of https://github.com/backdrop/backdrop-issues/issues/2910#issuecomment-354667126 regarding the vertical tabs and get this thing finished, probably for 1.11.

(For reference a current issue of interest regarding the vertical tabs: "clean up help text on "Multilingual support" content type radios", https://github.com/backdrop/backdrop-issues/issues/3070)

**Comment by indigoxela** [comment]
FTR the i18n module for Backdrop also ships with that setting. If it went into core, it should get removed from the module.

**Comment by herbdool** [comment]
A new PR: https://github.com/backdrop/backdrop/pull/3398. I took a slightly different approach. The setting is now per content type and it's in the multilingual support vertical tab.

So it's not as sophisticated as in i18n where it's exposed as a pseudo field. But this should help most people.

**Comment by olafgrabienski** [comment]
@herb, the PR looks great. I've tested it in the Tugboat sandbox, and everything is working fine for me:

- Went to the Tugboat sandbox and logged in.
- Enabled Content Translation, Language and Locale.
- Added German language.
- Went to `admin/structure/types/manage/page`, and set **Multilingual support** to **Enabled, with translation**.
- Created an English "Test page".
- Translated the page to the German "Testseite".
- Checked if there were Translation links below the body: Yes (as expected)
- Went to `admin/structure/types/manage/page` again, and disabled **Show content translation link**.
- Checked again if there were Translation links below the body of my test pages: No (as expected)

Finally, I've repeated the steps for Posts to see if the handling of Translation links works also in Teasers which is the case.

One question: The **Show content translation link** setting is displayed with **Multilingual support > Enabled, with translation** but also with just **Multilingual support > Enabled** (without translation). What's the use-case for the latter?

**Comment by herbdool** [comment]
@olafgrabienski ah right, with "Multilingual support > Enabled" it wouldn't show the link anyway, is that correct?

**Comment by olafgrabienski** [comment]
> with "Multilingual support > Enabled" it wouldn't show the link anyway, is that correct?

Exactly! With "Multilingual support > Enabled", when I create an English page, I can't translate it, so there's no equivalent in another language, hence no translation (aka switch language) link.

**Comment by herbdool** [comment]
@olafgrabienski I've updated it and added an automated test.

**Comment by olafgrabienski** [comment]
@herbdool Thanks for the update! Setting display changed as expected, and works still like a charm.

**Comment by indigoxela** [comment]
Nice! And the UI is much better compared to i18n_node, where it's really confusing with the global setting _and_ the pseudo field.

I really think that the "Multilingual support" vtab is the better place for this setting.

On minor thing:
@herbdool It might make sense to name the setting / form item "show_translation_links" (plural instead of singular), to avoid misconception that it's about the "Link to add a translation". But maybe I'm wrong.

Code is looking good, RTBC from my side.

**Comment by klonos** [comment]
I wanted to test what the current process looks like (**on a vanilla Backdrop installation**), before I actually test the PR sandbox, so that I can compare the before/after experience. Here's what I've done:

1. **Fresh 1.17.2 installation** (using our demo sandboxes actually)
1. Enable the Locale, Language, and Content Translation modules
1. Added another language to the site.
1. Went to `admin/structure/types/manage/page` and enabled the "Enabled, with translation" option
1. Created a new page with its language set to English
1. Once the node was saved, I clicked the "Translate" tab -> no option to translate the page in the untranslated language:

![image](https://user-images.githubusercontent.com/2423362/99129650-dafbc080-2616-11eb-9d4d-8f579af1f238.png)

...shouldn't there be a link there to allow me to translate the page? Am I missing any steps before that is an option?

**Comment by indigoxela** [comment]
> ...shouldn't there be a link there to allow me to translate the page

Sure, just compare it with the testing sandbox. Log in as admin and go to https://pr3398-evb83rluhyplzqth8lniruofxtxtakmj.tugboat.qa/de/node/4/translate

Everything works as expected.

**Comment by klonos** [comment]
>Not sure, which step of the multilingual setup you missed in your demo install.

Not sure what I did wrong either ...I tried the same steps again, and this time I got the links 🤷

**Comment by klonos** [comment]
I've tested things in the PR sandbox, and things indeed seem to work as expected 👍

**Comment by herbdool** [comment]
Thanks all. @indigoxela I'm okay with either links or link. I made it singular just because there's only one link shown at a time. Or maybe that's because I've only worked with bilingual sites. Oops, I should check that.

**Comment by indigoxela** [comment]
> I made it singular just because there's only one link shown at a time

There's one for each available translation. :wink: 
![translation-links](https://user-images.githubusercontent.com/842066/99221798-8bb5bb80-27e1-11eb-9b4d-bcc3dbec0c1e.png)

**Comment by quicksketch** [comment]
This looks great! I like this approach and the implementation looks really good.

However, there appears to be an issue with the update hook: https://github.com/backdrop/backdrop/pull/3398#pullrequestreview-550980630

Separately, I think the UI strings all look fine. But I think the setting in the `node.type.[type].json` file should be namespaced under the module like `comment` and `menu` modules do:
```
"settings": {
        ...
        "comment_default": 1,
        "menu_default": true,
        "menu_options": [
            "main-menu"
        ],
        "comment_enabled": false,
        "comment_per_page": 50,
        "comment_mode": 1,
        "comment_anonymous": 0,
        "comment_subject_field": false,
        "comment_user_picture": true,
        "comment_form_location": 1,
        "comment_preview": 1,
        "comment_close_enabled": false,
        "comment_close_days": 14,
        "menu_parent": "main-menu:0",
        ...
    },
```

So instead of `show_translation_links` I would prefer `translation_show_links`. Separately, in another issue I wouldn't mind adding a matching setting for `comment_show_links` (or similar).

**Comment by herbdool** [comment]
Ready for another code review - made minor changes to setting name and fixed update hook.

**Comment by klonos** [comment]
Code looks good to me 👍 ...thanks @herbdool

**Comment by quicksketch** [comment]
I've merged https://github.com/backdrop/backdrop/pull/3398 into 1.x that adds this new setting. Thanks @herbdool, @olafgrabienski, @klonos, @indigoxela, and @serundeputy!
