### ISSUE TITLE
Backdrop Module "Mentions" has Error

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#2945]
## Describe your issue or idea

Hi Developers,

After upgrading to Backdrop 1.9.0 some modules have errors in the frontend. Can you please look at the module "mentions". Unfortunately this does not work.

Otherwise showed with today's upgrade so many errors.

After that, I was reasonably forwarded under `/user` to `/user/login`.

Modules like "ck editor mentions" and "mentions" are still to be adapted. There is something wrong with the "library".

Thanks in Advance.

### Steps to reproduce (if reporting a bug)

Fresh Upgrade to Backdrop 1.9.0.

### Actual behavior (if reporting a bug)
errors shown

### Expected behavior (if reporting a bug)
no errors

### Relevant version/system information (if applicable)

Rootserver, PHP 7.1, MariaDB 10.2, Plesk, Subdomain

**Comment by jenlampton** [comment]
Hi @AlexL777, thanks for reporting this issue. However, if there is an issue with the mentions module, that issue will need to be reported [in the mentions issue queue](https://github.com/backdrop-contrib/mentions/issues) otherwise it's likely that it won't get fixed. 

It will also help the developers if you can copy/paste any errors that you see, as we might not see them on our sites.

**Comment by jenlampton** [comment]
Thats great!  Congratulations :)  I'm going to close this issue, please do let us know if you need any more help.
