### ISSUE TITLE
[UX] Added a "Taxonomy term: Depth" Visibility condition for blocks and layouts.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2955]
## Describe your issue or idea

Just as I often have different layouts for nodes, by node-type, I often need different layouts for categories based on term-depth. For example, my top-level terms need landing pages, but my deeper terms could use their own layout (or even the default layout).

However, without a Visibility condition to select only the top-level terms, I can't do that. Here's one that matches the term depth condition from Panels. 

## Draft of feature description for Press Release (1 paragraph at most)

Backdrop now includes a "Taxonomy term: Depth" Visibility condition for blocks and layouts.  This condition will allow a different block or layout to be selected, depending on the depth of the term you are viewing. For example: a top-level term can have its own landing page layout, and child terms could use the default layout, instead.

---

Advocate: @stpaultim

**Comment by docwilmot** [comment]
Tested this in the sandbox:
- added a layout for `taxonomy/term/%`
- went to add block: the new "Term depth" condition was available
- added block with condition depth 1
- added some hierarchical terms and visited their pages
- block is only visible on term pages of top terms as expected.

I wonder if a description of "Depth" on the `form()` method might be good since term depth isn't likely to be a well-understood concept.

And maybe tests but we seem to have no tests for other access plugins so no fault there.

I think we could use `taxonomy_term_load_parents_all()` instead of the current query. With a depth of 4, you would be making 4 queries as it is now, whereas `taxonomy_term_load_parents_all()` uses a static cache. I havent checked but I wonder if a simple `count()` on the results of that function would give the depth.

**Comment by jenlampton** [comment]
Changing to NW and bumping milestone.

**Comment by klonos** [comment]
Thanks for opening this ticket @jenlampton ...and for the PR 👍 

It's those little things that make backdrop great 😄 

PS: I wonder if the same concept could be implemented for URL path depth. If the wildcard `*` works when used multiple times (never actually tried it), then this is moot. For example landing pages could have a visibility condition of `/something/*`, and sub pages would have their visibility condition set to `/something/*/*`. Anyone tried this before?

**Comment by jenlampton** [comment]
I found that no level of explanation was as good as a visual example, so I kept it short and added a visual example :) 
<img width="590" alt="screen shot 2018-12-12 at 8 40 36 pm" src="https://user-images.githubusercontent.com/397895/49916127-48f94500-fe4e-11e8-9a46-d3b809145c66.png">

**Comment by jenlampton** [comment]
Feature freeze is in 40 mins. Since there are no reviews, this is getting bumped.

**Comment by stpaultim** [comment]
I re-rolled this PR and made a new version, mostly just to build a sandbox for it. It's exactly the same as Jen's PR, here for testing and comments. 

I don't recall ever needing this feature, so I think there is a legitimate discussion about if this should be a core feature. But, in general, I like having options like this in core. 

I tested the functionality and it worked for me. But, there may still be questions about UI. 

@jenlampton - is this still something that interests you? Feel free to take the PR back - I'm not likely able to work on this much.

**Comment by indigoxela** [comment]
@stpaultim many thanks for re-rolling this PR, I've left some small suggestions on it. Should the previous PR by @jenlampton get closed?

**Comment by stpaultim** [comment]
I addressed the easy suggestions, but the issue around visibility for methods isn't something I understand at the moment. I will either need additional coaching or am happy to turn this back over to @jenlampton :-).

**Comment by indigoxela** [comment]
I think we should clarify, who's actually working on this issue. Currently it's "works for me" - but set by the person who provides the PR. That's uncommon.

Another thought. Personally, I didn't need this functionality so far, but it looks like a good addition. But wouldn't that also be a good contrib candidate? Not sure if it's an 80% use-case.

**Comment by stpaultim** [comment]
> I think we should clarify, who's actually working on this issue. Currently it's "works for me" - but set by the person who provides the PR. That's uncommon.

Good point. At the time I marked this as "Works for Me" I had done nothing but rebased the work of @jenlampton. But, since it is my name that is on the active PR and I have not committed new changes, I should probably not be the one that marks it "Works for me."

I've removed that tag and will wait for others to review.

**Comment by docwilmot** [comment]
> But wouldn't that also be a good contrib candidate? Not sure if it's an 80% use-case.

True that

**Comment by jenlampton** [comment]
> Not sure if it's an 80% use-case.

This is one of those things that if it were there, people would use it. When it's not there, people find other ways. 

Anyone coming from Drupal 7 + panels will get stuck trying to figure out how to make up for the pieces that are missing in Backdrop.  I worry that people who use Backdrop expecting a layout system as powerful as panels will be disappointed. I'd personally rather see a handful of useful options that people would use (but maybe don't today) than only a few options that we know are in use.

**Comment by stpaultim** [comment]
> Not sure if it's an 80% use-case.

In my opinion, the 80% use case is a helpful guideline that works better for some situations than others. I think it's fairly safe to say that visibility conditions are a positive feature for most site architects. Visibility conditions in general would pass the 80% use case rule. 

When looking at individual visibility conditions, it's not so clear to me that the 80% use case rule/guideline should apply to each individual condition. Visibility conditions are valuable when you have a powerful set of visibility conditions. For me, I would decide whether this goes into core based upon a couple of things. 

1) Would adding this specific condition contribute to making an already important feature even more powerful?
2) Is it a complicated addition, either in code or user interface?
3) If relegated to a contrib module, would site architects even know that they should look for it or know how to find it in a contrib module?

There are small obscure features that belong in contrib modules for good reason. But there are also small obscure features that are almost too small to fit into a contrib module, because most folks that might like/need them, will not even know to look for them or know how to find them. 

There are a lot of features in the views module that by themselves would never pass the 80% rule/guideline. But, views is powerful because of all the little things it can do and in my opinion is one of the most powerful reasons to use Backdrop. 

I'm in favor of adding more visibility conditions to layouts, because they make a very important feature in Backdrop (Layouts) even better and because, I believe, that the cost is very low.

**Comment by indigoxela** [comment]
@stpaultim I'm a bit confused... Nobody objected to this feature, why do you think it's necessary to defend it?

**Comment by stpaultim** [comment]
I read the comment from @docwilmot as suggesting that this would be better left for contrib. I may have misread the situation.

**Comment by docwilmot** [comment]
No, you read it right, as far as my opinion in this situation.

**Comment by jenlampton** [comment]
I'm with @stpaultim that this is a smaller piece of a whole feature that meets the 80% use-case. 

> If relegated to a contrib module, would site architects even know that they should look for it or know how to find it in a contrib module?

If we were to move this into a contrib module, I'd vote for naming it "panels" and including along with all the stuff that we accidentally left out of core. That would at least help all the people coming from Drupal 7, since they will probably add the panels module without thinking about it. That wouldn't help people (or websites) starting fresh in Backdrop, however. They'd still get the less complete experience. They wouldn't know what to look for.

**Comment by stpaultim** [comment]
I'll just note that this issue was discussed towards the end of the dev meeting today. The consensus seemed to be in favor of including this visibility rule (and perhaps others) in core.

**Comment by stpaultim** [comment]
Since my last issue is now RTBC, I'm going to advocate for this one for 1.23.0, because I think it's quite close to being finished. There is one objection to including this in core. However, we discussed this during the last development meeting and there seemed to be fairly widespread agreement that this feature is suitable for core. Please, correct me I misunderstood the sentiment. 

I've incorporated some feedback from @indigoxela. But, having not been the original author of the code and the fact that I'm quite inexperienced with OOP, I welcome feedback on whether or not that feedback was correctly implemented.

**Comment by stpaultim** [comment]
@herbdool - I merged your suggsetion! Thanks for all your work in the issue queue this last weekend.

**Comment by quicksketch** [comment]
I made a few suggestions for tidying up the implementation: https://github.com/backdrop/backdrop/pull/4062#pullrequestreview-1089384979

**Comment by quicksketch** [comment]
I've merged https://github.com/backdrop/backdrop/pull/4062 into 1.x for 1.23.0.

f56c0db4b8ca2ac598a697c2a2e74e6e00ed50ae by @jenlampton, @stpaultim, @docwilmot, @indigoxela, @herbdool, and @quicksketch.

Thanks folks!
