### ISSUE TITLE
Hero image does not display when Backdrop installed in sub-directory

### ISSUE THREAD

**Issue by jjmonterey** [backdrop/backdrop-issues#2965]
Similar to Issue#2562 (closed)
Installed  Backdrop in sub-directory -> xampp/htdocs/backdrop

After uploading an image to the hero block it does not display (path: files/hero)

![hero_1](https://user-images.githubusercontent.com/5239865/35641298-c7f23470-068d-11e8-86cc-4d3caa436f63.jpg)

I can overide with the css as per the image below, but ONLY when the image is placed within a folder in the theme css folder.   

![hero_2](https://user-images.githubusercontent.com/5239865/35641559-810b766a-068e-11e8-880f-bc238d17b5d0.jpg)

Also experience the same behavior when creating a custom block and uploading the background image to  the path files/images and  using the css:
 .testblok {
  background-image: url(/files/images/image.jpg);
}
the BG image will not load

If the image is uploaded to theme css/images folder with the following css it will display.

.testblok {
  background-image: url(images/image.jpg);
}

This seems only to occur when Backdrop is installed in a subdirectory.

**Comment by olafgrabienski** [comment]
Linking to the related issue mentioned above in the description: #2562

**Comment by Graham-72** [comment]
I am thinking that the problem may be because the hero block has its own code for uploading the hero block image and the code (block.hero.inc) needs the same modification as made to filter.pages.inc to solve the subdirectory problem #2562. I will test this idea out.

Regarding other background images set by CSS I think it is important that the CSS file and the images are installed/uploaded within the site's own themes directory. For the images I prefer to use an images subdirectory within the css directory.

**Comment by Graham-72** [comment]
The PR https://github.com/backdrop/backdrop/pull/2089 would seem to solve the problem for the hero image, though it had better be tested on different servers.

**Comment by quicksketch** [comment]
The PR at https://github.com/backdrop/backdrop/pull/2089 looks good to me. I tested it out and the paths seem to be correct, and code looked good. Merged into 1.x and 1.9.x. Thanks @Graham-72 and @jjmonterey!
