### ISSUE TITLE
Should add a clearfix class to the node `content` DIV

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#2982]
By default, node content looks like this, based on `node.tpl.php` in `node.module` itself:
```
<main class="l-content col-md-9" role="main" aria-label="Main content">
  <article id="node-18" class="node clearfix" role="article">
      <footer> stuff </footer>
          <div class="content">
          <section class="comments">
```
Bartik overrides `node.tpl.php` to add clearfix, so that `<div class="content clearfix">` doesnt bleed into the comments.

Basis doesnt do this, so I just had a node with a small image field as the last item, and the comments DIV rides up into the node content.

I can fix with custom CSS, but Basis should fix that.

---
PR by @BWPanda: https://github.com/backdrop/backdrop/pull/2802

**Comment by quicksketch** [comment]
Looks like https://github.com/backdrop/backdrop-issues/issues/2295 might be the same issue.

Though I agree this would be better to fix with the `clearfix` class than duplicating the same CSS again. I think we could/should add `clearfix` directly to the default `node.tpl.php` file's `<div class="content">` wrapper.

**Comment by quicksketch** [comment]
Tagging as good first issue. File to be modified is `/core/modules/node/templates/node.tpl.php`.

**Comment by BWPanda** [comment]
PR here: https://github.com/backdrop/backdrop/pull/2802

**Comment by olafgrabienski** [comment]
I've tested the PR in the sandbox:

- Created a post and put in an image via CKEditor
- Changed the HTML with the browser's dev tools to match the following:

```
<div class="content clearfix">
  <div class="field field-name-body (...)"><p>MY BODY-TEXT</p></div>
  <img class="align-left" src="MY-IMAGE" (...)>
</div>
```

**Having the `clearfix` class, everything is fine:**

![screen-backdrop-pr-2802-with-clearfix](https://user-images.githubusercontent.com/14188307/62716359-53320a00-ba02-11e9-86a3-4f11e5b67bcb.png)

**In contrast, without the `clearfix`class of the PR, the content and comments are overlapping:**

![screen-backdrop-pr-2802-without-clearfix](https://user-images.githubusercontent.com/14188307/62716842-1c102880-ba03-11e9-8151-364acc1be760.png)

**Comment by klonos** [comment]
Noting that these 7.x core issues are related (but on a different level):

https://www.drupal.org/project/drupal/issues/2332087
https://www.drupal.org/project/drupal/issues/569362

...not anything that can/should be done as part of this issues here; just noting it because I saw `$content_attributes` being printed right after the classes, and I wondered if that variable could also contain additional classes. In that case, shouldn't we be merging those classes, or is it done automagically?

I have tried figuring out what `$content_attributes` may contain and where it comes from, but it is not documented (hence my search and the d.org issues I came across).

Pinging @jenlampton and @wesruv in case they have more insight.

**Comment by klonos** [comment]
> ...or is it done automagically?

In other words, if one does this in HTML:

```html
<div class="class-1 class-2" class="class-3 class-4">
```

...does it automatically get converted to this?:

```html
<div class="class-1 class-2 class-3 class-4">
```

If yes, then OK; but if either the first set of classes or the second one gets discarded, then there obviously is a problem.

**Comment by klonos** [comment]
...OK, so I have tried this in `node.tpl.php`:

```php
<div class="content class-1" class="class-2"<?php print backdrop_attributes($content_attributes); ?>>
```

The result is that `class="class-2"` gets ignored:

```html
<div class="content class-1">
```

I also tried adding this before the div declaration:

```php
<?php $content_attributes = array('test' => '123', 'class' => 'another-class'); ?>
```

...which resulted to this:

```html
<div class="content class-1" test="123">
```

So it seems that we are in fact ignoring any classes set via `$content_attributes`. Is that expected behaviour, or an oversight?

**Comment by klonos** [comment]
...so I think that in order to be doing this properly, we should be doing something like this:

```php
<?php
$content_attributes['class'][] = 'content';
$content_attributes['class'][] = 'clearfix';
?>
<div <?php print backdrop_attributes($content_attributes); ?>>
```

Am I thinking wrong here?

**Comment by klonos** [comment]
...actually this seems more elegant (adds the `content` and `clearfix` classes to the beginning of the array):

```php
<?php array_unshift($content_attributes, 'content', 'clearfix'); ?>
<div <?php print backdrop_attributes($content_attributes); ?>>
```

**Comment by jenlampton** [comment]
@klonos there can only be one `class` attribute on a tag. This is not valid HTML:
`<div class="a" class="b">`

Since we want attributes to be alterable, our code usually looks like this:
`<div class"<?php print implode(' ', $content_attributes['class'])?>" <?php print backdrop_attributes($content_attributes); ?>>`

But we usually also pre-process `$content_attributes['class']` into `$classes` so it's not quite so ugly. Most templates look like this:
`<div class"<?php print implode(' ', $classes)?>" <?php print backdrop_attributes($content_attributes); ?>>`

In most places in Backdrop we print the classes out separately from the rest of the attributes. That makes it easy for someone to add a class wherever needed, without needing to get into an attributes array, or worry about preprocessing anything themselves.

**Comment by klonos** [comment]
OK, I see that in the same file we do this:

```php
<article id="node-<?php print $node->nid; ?>" class="<?php print implode(' ', $classes); ?> clearfix"<?php print backdrop_attributes($attributes); ?>>
```

...so next question is does the `$classes` variable contain the classes that are to be added to the `<article>` tag, or the `<div>` element later on? Seems to me that that would add the same classes to both ...which does not sound right. Maybe I need to get my head around this 🤔

**Comment by klonos** [comment]
...oh, the one is `$attributes` while the other is `$content_attributes`; so the right question is which one does `$classes` include the classes from?

**Comment by jenlampton** [comment]
Probably $attributes. Check the preprocessor.

**Comment by klonos** [comment]
So yeah, seems that something like this would be "proper" then:

```php
<div class="content <?php print implode(' ', $content_attributes['class']); ?> clearfix"<?php print backdrop_attributes($content_attributes); ?>>
```

...and last question (sorry 😅): should there be a space after the last double quote, before we print the rest of the attributes?

**Comment by klonos** [comment]
...unless we need to also be preprocessing `$content_attributes['class']` into a `$content_classes` variable 🤷‍♂

**Comment by klonos** [comment]
> Check the preprocessor.

Don't know what that means (though I should) ...how do I do that?

**Comment by jenlampton** [comment]
I usually read template_preprocess_node() in the API docs.

No space ;)

**Comment by quicksketch** [comment]
For the time being, I've merged https://github.com/backdrop/backdrop/pull/2802 because it fixes the immediate issue and is the lowest impact. We can restructure the attributes separately if we want to do that in a new issue. Thanks @klonos, @olafgrabienski, @BWPanda, and @jenlampton!
