### ISSUE TITLE
array_key_exists() expects parameter 2 to be array, null given file.install:653

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#2987]
I am attempting to apply the most recent security release 1.9.2 from 1.8.1. When attempt to run the database updates (via drush), I get:

`array_key_exists() expects parameter 2 to be array, null given file.install:653                                                                                        [warning]`
`PHP Fatal error:  Unsupported operand types in /var/www/htdocs/core/modules/file/file.install on line 691`

`Fatal error: Unsupported operand types in /var/www/htdocs/core/modules/file/file.install on line 691`
`Drush command terminated abnormally due to an unrecoverable error.                                                                                                     [error]`
`Error: Unsupported operand types in /var/www/htdocs/core/modules/file/file.install, line 691`

The same is true if I run the updates from the UI. I'm a bit at a loss as to what to do here, any help would be appreciated!

---
PR: https://github.com/backdrop/backdrop/pull/2106

**Comment by olafgrabienski** [comment]
@elizolivares I've tried to reproduce the issue updating one of my Backdrop test sites. The updates ran without any problem.

I had only a 1.8.0 site without drush at hand though, so the update was not exactly the same as on your site, only similar.

Guess we need more feedback. I'm going to tag the issue as such.

**Comment by olafgrabienski** [comment]
Fyi I'm listing the single database updates, which ran on my test site, below. Hope it helps to find the reason for the issue, there are for instance two database updates regarding the file module.

system module
1063 - Set a default value for the X-Frame-Options header. This will not allow the site to be rendered in an iframe on another domain unless specified.

dblog module
1000 - Account for possible legacy systems where dblog was not installed.

file module
1001 - Add a Manage file link to the admin files view.
1002 - Switch the 'edit files' permission from file_entity to 'manage files'.

node module
1014 - Change {history}.nid to an unsigned int in order to match {node}.nid.

search module
1001 - Add the default value for the "search_logging" configuration value.

update module
1003 - Removes the testing-only values from the update.settings config.

**Comment by jenlampton** [comment]
Here is line 691 in `/core/modules/file/file.install`:
```php
$dropbutton['fields'] = array('edit' => 'edit') + $dropbutton['fields'];
```

@elizolivares can you tell us what PHP version you are running? Maybe it doesn't like this array plus business...

**Comment by jackaponte** [comment]
@jenlampton I'm working on this with @elizolivares; we're running PHP 5.6.33 in both environments we've tested in so far. I just tried the update myself on a clean copy of the Backdrop 1.8.1 site and ran into the same errors in my local environment; the errors stop the database updates from running and continue on repeated attempts to run said updates.

**Comment by jenlampton** [comment]
That's great that the problem is repeatable! If you switch to a different
PHP version (or use a different array merge syntax) can the upgrade
continue?

**Comment by jackaponte** [comment]
Hey @jenlampton -- it actually turns out that this was repeatable on two different copies of this particular site because the `views.view.file_admin.json` config file was missing from this site's active configuration. The database updates were actually choking on line 653 in `/core/modules/file/file.install`; here's that line and the few preceding lines:

```
/**
 * Add a Manage file link to the admin files view.
 */
function file_update_1001() {
  $config = config('views.view.file_admin');

  // Get all the fields.
  $fields = $config->get('display.default.display_options.fields');

  // If the file field is not already there...
  if (!array_key_exists('edit', $fields)) {
```
It looks like that config file should be created during `file_update_1000`. We're not sure why that file didn't get created on this particular site; could be that it did get created but somehow it got lost? We also upgraded this site from Backdrop 1.5.0 all the way to Backdrop 1.8.0 in one fell swoop, so maybe somehow `file_update_1000` didn't get triggered in that big leap or something else went awry during the update so that the config file wasn't created.

This did not happen with another Backdrop site that I upgraded from Backdrop 1.8.1 to Backdrop 1.9.0 in the same environment.

**Comment by jenlampton** [comment]
It seems that we should account for what happens when a config file doesn't exist. Its a valid use-case for someone to delete one of our provided admin views, so perhaps an `if($config)` would be a good addition when we do updates like this.

```php
function file_update_1001() {
  $config = config('views.view.file_admin');
  if ($config) {
    // Get all the fields.
    $fields = $config->get('display.default.display_options.fields');
```

**Comment by jenlampton** [comment]
I've filed a PR for this particular issue at https://github.com/backdrop/backdrop/pull/2106, but we should make an effort going forward to always check for (optional) config files before updating them.

**Comment by jackaponte** [comment]
> Its a valid use-case for someone to delete one of our provided admin views, so perhaps an if($config) would be a good addition when we do updates like this.
...
> we should make an effort going forward to always check for (optional) config files before updating them.

Good point and agreed, Jen! Thanks for filing that PR here.

**Comment by quicksketch** [comment]
Although we don't allow fully deleting default views from the UI (you can only disable them), it is possible for a site to manually delete the config file directly anyway. So adding the check is completely reasonable. Let's merge the PR to prevent the error in this scenario. If we can determine _why_ the config file went missing (or was not created) let's make a new issue to address that problem.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2106 into 1.x and 1.9.x. Thanks!
