### ISSUE TITLE
[DX][UX] System settings form should make the Save configuration button primary (blue)

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3034]
## Describe your issue or idea

Developers will be creating lots of contrib moules with settings forms, likely using `system_settings_form`. By default, the button placed by this function is not blue, the primary button color. 

<img width="734" alt="screen shot 2018-04-15 at 1 00 03 pm" src="https://user-images.githubusercontent.com/397895/38782757-f3e2773a-40ac-11e8-9c9d-fc93401ce86b.png">

I believe we'll get a better and more usable product by making it easier for developers to build user-friendly interfaces.

Let's add the`button-primary` class to this button in `system_settings_form()`, to make the `Save configuration` button blue.

### Steps to reproduce (if reporting a bug)

* Create a form with `system_settings_form()`

### Actual behavior (if reporting a bug)

* confirm the `Save configuration` button is gray

### Expected behavior (if reporting a bug)

* confirm the `Save configuration` button should be blue

---
PR: https://github.com/backdrop/backdrop/pull/2133

**Comment by opi** [comment]
wonder why my own custom form already have the `button-primary` class...

**Comment by opi** [comment]
answer: defined in https://api.backdropcms.org/api/backdrop/core%21includes%21form.inc/function/form_process_actions/1

**Comment by quicksketch** [comment]
Yeah, this is strange. The class should already be getting added. All other forms in core that use system_settings_form() seem to have the class correctly added. e.g. admin/config/media/file-system (`system_file_system_settings`).

![image](https://user-images.githubusercontent.com/100206/39078117-dad1dd7c-44bb-11e8-8db3-b9f2e9d31998.png)

Seems like this might be caused by the contrib module in question doing something usual, such as defining `$form['actions']` prior to calling `system_settings_form()`. In which case not only would the class not be added but the form actions wrapper would be missing.

**Comment by jenlampton** [comment]
> Seems like this might be caused by the contrib module in question doing something usual

I don't think so,  Here's the code: https://github.com/backdrop-contrib/block_embed/blob/1.x-1.x/block_embed.admin.inc

**Comment by jenlampton** [comment]
Oh, I think I know what it was... yeah. It seems to be fine now. Closing :)
