### ISSUE TITLE
[UX] add button-danger class to dblog 'Clear log messages' button, and move the clear log fieldset before the filters fieldset

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3064]
## Describe your issue or idea

This is a follow-up to https://github.com/backdrop/backdrop-issues/issues/2353#issuecomment-385196934

The button to `Clear log messages` on the dblog deletes stuff from the database, yet it doesn't have a confirm form. For people who are not already familiar with the dblog messages page, more warning here might be helpful.

I personally think a confirm form might be a overkill for this button, but at the very least it should have a button-dangerous class so that there's an indicator that there's no going back once you click on it.

BEFORE:
![screen shot 2018-04-28 at 11 39 08 am](https://user-images.githubusercontent.com/397895/39399760-cbf57b06-4ad8-11e8-922d-14b170f63544.png)
AFTER:
![screen shot 2018-04-28 at 11 47 57 am](https://user-images.githubusercontent.com/397895/39399841-0fc43bd2-4ada-11e8-982c-ecb33baca308.png)

---
PR: https://github.com/backdrop/backdrop/pull/2152

**Comment by jenlampton** [comment]
I've pushed a PR for this change: https://github.com/backdrop/backdrop/pull/2152

This PR also includes two other tiny changes:

* changes the fieldset description text from `` to `This action will permanently delete the log messages from the database.` to make the text a little clearer and more human.
* Moves the clear button's fieldset above the filters, to bring the filters closer to the form it's filtering.

**Comment by klonos** [comment]
...I would eventually like to see this page revamped a bit more, but that can come in a follow-up ticket. Noting my thoughts here, so that they do not get lost in time:

1. **Consider adding checkboxes to the table and converting the delete button a bulk operation**. This would allow people to filter messages out, and then delete only specific ones.

2. **Consider moving the filters out of the (collapsed by default) fieldset**. I believe that the only reason why we have them inside a collapsed fieldset at the moment is because the select boxes in the filter are too long, and they would otherwise be "pushing" the table with the log messages (the important stuff) down. This would in turn requiring the user to scroll in order to see the most recent ones. This problem might not be obvious in big screens, but it would become an issue on small screens (site admins might not be doing most of their day-to-day site tasks on such screens, but taking a quick look in the log on one's phone when a site owner reports an issue is not that far-fetched of a scenario).

**Comment by klonos** [comment]
...actually @jenlampton, I think that the button needs some margin from the text. 10px would be good I think...

Before:

![screen shot 2018-04-30 at 8 52 05 am](https://user-images.githubusercontent.com/2423362/39411766-081f3e6a-4c54-11e8-953f-a7f8bf8c5041.png)

...after:

![screen shot 2018-04-30 at 8 51 35 am](https://user-images.githubusercontent.com/2423362/39411765-000dac20-4c54-11e8-9880-800da4fc1700.png)

Do you think you can squeeze that little change in this PR? Thanks.

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/2152 into 1.x and 1.9.x. Thanks!

**Comment by findlabnet** [comment]
@klonos 
> Remove the "Operations" column from the table:
> ...we currently have no use for it

We currently used it for links to view edited content or search results at least.

**Comment by jenlampton** [comment]
@klonos that needs to be fixed globally for all fielsdets, but I agree. I
think I made a separate  PR somewhere...

**Comment by olafgrabienski** [comment]
@opi Reviewed and made it RTBC.
