### ISSUE TITLE
[UX] clean up help text on "Multilingual support" content type radios

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3070]
## Describe your issue or idea

For the Multilingual support setting on content types, the description text for all three options is shoved into a single block of text. This makes it very hard for me to understand the difference between available options. I'd prefer that each option have its description nearby.

![screen shot 2018-04-30 at 10 39 23 pm](https://user-images.githubusercontent.com/397895/39462629-93c5042c-4cc7-11e8-9157-02c1ba83ffea.png)

This would be much better:
![screen shot 2018-04-30 at 10 55 01 pm](https://user-images.githubusercontent.com/397895/39462883-8e2c3646-4cc9-11e8-9a94-9a7685491989.png)

---
PR: https://github.com/backdrop/backdrop/pull/2162

**Comment by olafgrabienski** [comment]
Wow, that's an excellent improvement! From a sandbox site perspective, the PR looks also good and works well.

(For reference: the settings are on the "Publishing settings" tab of the content type configuration form. Maybe add that in the issue description.)

One issue only: On first sight, I was not sure if the help text "Existing content will not be affected by changing this option." is related to all options or only the last one. Inspecting the position and reading it again, I suspected it's related to all options. So I thought, maybe we can make that more clear, saying for instance "Existing content will not be affected by changing *any* of these options." But then I realized that changing an option so that is has less features, e.g. from "Enabled" to "Disabled", lets disappear things like the language selection on the node edit form. So, I think the help text is either way misleading. Have no idea so far, what do you think @jenlampton ?

**Comment by quicksketch** [comment]
This seems like a very good improvement to me. @olafgrabienski so are you suggesting that changing this setting *does* affect existing content? And so we should just remove the `Existing content will not be affected by this operation.` string entirely?

**Comment by jenlampton** [comment]
> are you suggesting that changing this setting does affect existing content? 

No, it does not affect existing content. But I added which content would be affected for each radio:
```
New content...
New content...
Content...
```

**Comment by olafgrabienski** [comment]
>> And so we should just remove the `Existing content will not be affected by this operation.` string entirely?

> so I think it's still safe to remove the string

I agree!

**Comment by quicksketch** [comment]
Great improvement. Merged https://github.com/backdrop/backdrop/pull/2162 into 1.x and 1.10.x.
