### ISSUE TITLE
Publish should be default instead of Schedule

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#3076]
## Describe your issue or idea

I just installed the latest dev and am testing out some of the new features. The scheduler option (https://github.com/backdrop/backdrop-issues/issues/857) is great, however it is the default selection when creating a node and it seems to me that the usual 'publish now' should remain default.

---

PR by @quicksketch: https://github.com/backdrop/backdrop/pull/2167

**Comment by quicksketch** [comment]
Thanks @laryn, absolutely should stay "Published" by default. There is a per-content type setting for which is the default. Is this on an upgraded site or a brand new install?

**Comment by laryn** [comment]
@quicksketch This is a new install (Lando/local from the latest Backdrop dev), and both Page and Post have Scheduled as the default.

**Comment by quicksketch** [comment]
I filed a PR at https://github.com/backdrop/backdrop/pull/2167.

Basically the problem here is that we have radio buttons with values of 1 (Published), 0 (Draft), and 2 (Scheduled). But the default value we are passing to the form element is the Boolean `TRUE`. As both `1 == TRUE` and `2 == TRUE`, both end up marked as the default value. And either in the HTML or in Backdrop, this makes the second radio button (Scheduled) become the default.

The solution I think we should use here is use the node constants `NODE_PUBLISHED` (1), `NODE_NOT_PUBLISHED` (0), and `NODE_SCHEDULED` (2), rather than Boolean `TRUE` and `FALSE`. So this PR makes Backdrop assign those values instead of a Boolean out of the box, and any node types that are saved with a Boolean are converted to use the integer values instead on load. I included an update hook to be thorough so that existing node types would be updated for consistency. Though on-load, any existing Boolean values would be updated to be correct anyway, so it will be backwards-compatible with any existing node types.
