### ISSUE TITLE
[UX] separate help text for publishing options

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3122]
## Describe your issue or idea

After adding the new scheduled publishing feature in Backdrop 1.10 I noticed that help text for two separate items is grouped together, after all items are listed. 
<img width="2348" alt="screen_shot_2018-05-15_at_2 07 02_pm" src="https://user-images.githubusercontent.com/397895/40084645-ad6724ba-584c-11e8-8418-cbd2e24299e0.png">

It would be easier to read and understand if the help text for each item were listed immediately after the item itself.

---
PR by @opi: ~https://github.com/backdrop/backdrop/pull/2195~
PR by @klonos ~https://github.com/backdrop/backdrop/pull/3247~
PR by @jenlampton: ~https://github.com/backdrop/backdrop/pull/3613~
PR by @stpaultim (based upon priors) https://github.com/backdrop/backdrop/pull/3742

**Comment by mikemccaffrey** [comment]
Is there actually a way to put description text between the items in a radio select?

Do we need this description text at all? The options seem pretty straightforward.

**Comment by opi** [comment]
PR https://github.com/backdrop/backdrop/pull/2195

Description text are below each radio button. Screenshot:
![capture d ecran de 2018-05-17 14-27-04](https://user-images.githubusercontent.com/159548/40177288-6ad84938-59de-11e8-9cdb-9f0638426bdd.png)

**Comment by mikemccaffrey** [comment]
Looks pretty good, but since the help text is right next to the option, we no longer need the "Context saved as XXX" to point out which option each help sentence is describing. We can shorten the Schedule for Later help text to one line with something like:

"Save as draft and set a date and time for the content to be automatically published."

The downside to this approach is the three radio buttons no longer look like they are part of the same group, especially with the checkboxes below at the same vertical spacing. Can we add some sort of visual element between the radio buttons and the checkboxes? Or maybe move Promoted and Sticky to the top and have a title above the three radio buttons saying "Publishing status"?

**Comment by docwilmot** [comment]
I think it looked better as it was, with one description below.

**Comment by jenlampton** [comment]
I was going to post the same feedback as Mike. With each option having it's own description we now also have the opportunity to shorten the text and make each description clearer, which will also make this page more scannable. 👍 

> Or maybe move Promoted and Sticky to the top

Since promoted and (especially sticky) are less important, I wouldn't want them moved above the radios. That's going to make it harder for people to find the option they need more of the time.

What if we added more vertical space?

> a title above the three radio buttons saying "Publishing status"?

I definitely think these radios need a label, but I prefer `Published state` :)

**Comment by opi** [comment]
Thanks everyone for feedback, I've updated the PR to:
- shorten the *scheduled* description
- add a title above radios ("published state", but I do not have a strong feeling on wording)
- also separate help text on content type configuration form (`admin/structure/types/manage/post`)
- only display option's label, without description, on the vertical tab summary 

![capture d ecran de 2018-05-18 18-10-38](https://user-images.githubusercontent.com/159548/40245771-d0f1137e-5ac6-11e8-9f2e-e6b00033d065.png)

**Comment by quicksketch** [comment]
I think I agree with @docwilmot here, I'm not sure it's an improvement. The gap between different options disconnects the radio buttons from each other. At first glance I might think Published and Draft are together but "Schedule for later" is separate.

I'm not sure it will help more, but perhaps we need to add a short description to "Published" as well, just so that all options are treated equally? And by putting a heading on "Published state" we may also need a heading on the Promoted/Sticky checkboxes, such as "Promotion options". 

Either that or we take a "less is more" approach and just eliminate the description text entirely. Just let's be consistent with treatment for all these options whichever way we go.

**Comment by jenlampton** [comment]
> The gap between different options disconnects the radio buttons from each other. At first glance I might think Published and Draft are together but "Schedule for later" is separate.

That sounds like a problem with our core CSS, not with the established UI pattern. We can create a follow-up item to get each option closer together (and maybe indent the descriptions too) if the problem is aesthetic.

> perhaps we need to add a short description to "Published" as well

I'd be open to that. Any suggestions for that text?

> And by putting a heading on "Published state" we may also need a heading on the Promoted/Sticky checkboxes, such as "Promotion options".

I was thinking this too. But then I also wondered if these items didn't belong in a completely separate vertical-tab, as they don't really have anything to do with publishing...

**Comment by olafgrabienski** [comment]
IIRC we have three suggestions now:

1. leave one description text below the options
2. finetuning of the separated description text
3. eliminate the description text entirely

I'm equally fine with 2. and 3.

**Comment by jenlampton** [comment]
My preference is either for 2, or using more words in each item label if we go with 3.

**Comment by olafgrabienski** [comment]
I see! And I guess the wording could even need more improvements: While "Published" and "Draft" are states, "Schedule for later" is an action. I'm aware that the latter is a special case because one is actually going to take an action (set the date) but it looks however inconsistent.

Here the two more consistent variations for comparison:

- Publish
- Save as Draft
- Schedule for later

or:

- Published
- Draft
- Scheduled

**Comment by jenlampton** [comment]
I prefer:

Publish now
Save as Draft
Schedule for later

**Comment by olafgrabienski** [comment]
Hm, "Publish now" makes no sense when you visit the edit form of already published content. Should the text change then after it has been published?

**Comment by jenlampton** [comment]
> Hm, "Publish now" makes no sense when you visit the edit form of already published content.

haha, I just had that same thought and changed it back to simply `Publish` :)

**Comment by klonos** [comment]
If we really want to solve the disconnect/confusion, we could add some padding to the set of checkboxes. That should provide some sense of grouping. Here's how the current PR would look with the font set to bold for the "Published state" header, and 20px left padding for the group of radios:

![screen shot 2018-06-02 at 12 54 58 pm](https://user-images.githubusercontent.com/2423362/40869801-8459a310-6664-11e8-8968-572065f1a904.png)

...we can do this now, as an intermediate workaround, but we should definitely work on #3157 (which is likely to render this work here obsolete).

**Comment by klonos** [comment]
Publish
Save as draft
Schedule for later

^^ I'm in favour of this too. ...and although I understand that the intend is to add emphasis to the word "draft", still we do not use camel case in sentences in our UI... otherwise we'd have "Schedule for **L**ater" and "Sticky at **T**op of **L**ists" 😄

**Comment by olafgrabienski** [comment]
> Publish
> Save as draft
> Schedule for later

Sounds good! Is it technically possible to change the labels so that they express the state (e.g. Publish**ed**) when the content has been saved?

**Comment by jenlampton** [comment]
> Is it technically possible

Yes!

> so that they express the state (e.g. Published) when the content has been saved?

I was thinking the button should still express the action that happens when you click it, so once a post is published it should say either "Save" or "Update".

**Comment by olafgrabienski** [comment]
>> so that they express the state (e.g. Published) when the content has been saved?

> I was thinking the button should still express the action that happens when you click it, so once a post is published it should say either "Save" or "Update".

I guess you were talking about the submit buttons, weren't you? I talked about the radio buttons beneath the heading "Published state", e.g. "Publish" which shouldn't change to "Save" or "Update" after publication but to "Published".

**Comment by klonos** [comment]
Can we please get consensus on the following (and leave the submit button labels for #1383):

1. Statuses: Publish / Save as draft / Schedule for later
2. Add a "Promotion options" heading for promoted/sticky
3. Add left padding to the set of radios/checkboxes

**Comment by klonos** [comment]
...for the content type settings, here's how it currently looks:

![screen shot 2018-06-22 at 2 33 24 pm](https://user-images.githubusercontent.com/2423362/41758137-075b09b4-762a-11e8-9de8-e30c8ecbcf7a.png)

1. I think that having the "Show option for scheduling" checkbox after the respective radio box makes weird UX. Just try check/unchecking it multiple times, and try to "follow" it. 👎 It also makes things inconsistent, since the rest of the respective "Show option ..." checkboxes further down the same form come first ...we should move it above the respective set of radios.

2. Add padding to the radio/checkboxes sets.

...here's how it'd all look when put together:

![screen shot 2018-06-22 at 2 38 23 pm](https://user-images.githubusercontent.com/2423362/41758273-eb1a83aa-762a-11e8-9570-52cb029a29f6.png)

Note that the help text for the individual radio options should be further padded, while the help text for the checkbox sets should have the same padding as the checkboxes (as it refers to both checkboxes in the set).

**Comment by olafgrabienski** [comment]
> Can we please get consensus on the following ...

> here's how it'd all look when put together ...

@klonos I'd like to comment but I'm not sure if you're still trying to get consensus on the 3 suggestions in https://github.com/backdrop/backdrop-issues/issues/3122#issuecomment-399317590 or if you modified your goal while doing the mockup in the last comment.

**Comment by alexfinnarn** [comment]
seems like this is still in discussion? I see `status - needs feeback`, but I think if that label is on an issue then `pr - needs review` should be taken off.

**Comment by jenlampton** [comment]
Setimes the feedback is easier if there's a PR to review with the suggested
change. The two labels can coexist :)

**Comment by quicksketch** [comment]
The current PR is still the same as the first screenshot: https://github.com/backdrop/backdrop-issues/issues/3122#issuecomment-389848837

**Comment by docwilmot** [comment]
No decision for over a year? Shall we remove all milestones?

**Comment by klonos** [comment]
I want to push this to finish. The current PR has conflicts since it has not been updated recently, so I've filed a new one: https://github.com/backdrop/backdrop/pull/3247

Things I've tried to address, based on previous feedback/suggestions/comments (let me know if I've missed anything):

>>perhaps we need to add a short description to "Published" as well, just so that all options are treated equally?
>
>I'd be open to that. Any suggestions for that text?

I went with "All site visitors will be able to access this content." for now, but we can tweak further.

>>And by putting a heading on "Published state" we may also need a heading on the Promoted/Sticky checkboxes, such as "Promotion options".
>
>I was thinking this too. But then I also wondered if these items didn't belong in a completely separate vertical-tab, as they don't really have anything to do with publishing

I think they are relevant to publishing. I went with adding a fieldset around these options; we cannot use a title, since these are 2 individual `'#type' => 'checkbox'` elements - not a single `'#type' => 'checkboxes'` one. The fieldset label is "Additional options" or "Additional actions" (depending on whether this is a new node, or editing an existing one).

I could try to change this to a single `'#type' => 'checkboxes'` element instead, so we could then use a title for it, but that's a bit more work to separate these during form submit. Happy to do that if you think that it'd be better.

>Hm, "Publish now" makes no sense when you visit the edit form of already published content. Should the text change then after it has been published?

I agree! We should be treating these differently. I went with different labels, depending on `$node->nid` exists. Here's how it looks when creating new content:

![image](https://user-images.githubusercontent.com/2423362/90302896-17057500-deb2-11ea-899f-bae66a973c1f.png)

...and here's how it looks when editing existing content:

![image](https://user-images.githubusercontent.com/2423362/90302915-4ddb8b00-deb2-11ea-9155-38b282f8cdf4.png)

Finally, with re to this:

>>The gap between different options disconnects the radio buttons from each other. At first glance I might think Published and Draft are together but "Schedule for later" is separate.
>
>That sounds like a problem with our core CSS, not with the established UI pattern. We can create a follow-up item to get each option closer together (and maybe indent the descriptions too) if the problem is aesthetic.

We have #4272 as a follow-up which would resolve this 😉 ...no need to hold up this issue over that.

**Comment by stpaultim** [comment]
This is my first comment on this issue. I like it and tested the PR and it seems to work as advertised. 

One possible note (not a blocker in my view) - once the node is saved as 'draft' or 'schedule for later' the label for 'Publish Now' is changed to 'Published,' even though it has not yet been published. It could still say 'Publish Now' in draft or scheduled for later state. 

I wouldn't have noticed this, if we weren't already changing it when the node is published. I really don't see this is as a blocker, but wanted to offer it as an observation.

**Comment by olafgrabienski** [comment]
Have had a look at the PR's sandbox website, and I like it as well. In contrast to the current behavior, it's already a big improvement.

**Comment by stpaultim** [comment]
I put this on the agenda for the next Design/UX meeting. I'm also going to mark this as Works for Me, because I think it's an improvement and my suggestions can be broken into a new issue.

**Comment by klonos** [comment]
Hey @stpaultim 👋 ...thanks for reviving this. I have rebased and pushed (no actual code changes), which triggered the tests to run again. This time they came back green, so it seems that the single php7-only failure must have been one of the usual random ones.

Setting this to "needs code review".

**Comment by stpaultim** [comment]
This was discussed in the US/Design meeting today. @jenlampton, @klonos, @philsward, and @stpaultim all indicated approval of this PR with one exception. 

We suggested removing the word "all" from "Published content can be accessed by all site visitors."

Just because something is published does not mean that ALL site visitors can view it, depending upon other permissions. 

@jenlampton already made of a note of this in the PR and suggested that once that change was made this is probably RTBC.

**Comment by olafgrabienski** [comment]
> We suggested removing the word "all" from "Published content can be accessed by all site visitors."

Good point! The text has to be changed for both places: content type settings and node form.

Btw, looking at both places, the texts are in a quite different state (see below). I guess it's not intentional, is it?

Content type setting
--------------------
Publish immediately
Published content can be accessed by all site visitors.

Save as draft
Content saved as draft can be accessed only by the content creator or site administrators.

Schedule for later
Content is saved as draft, and will be automatically published on the date and time selected.

Node form
---------
Publish now
All site visitors will be able to access this content.

Save as draft
Only the content creator or site administrators will be able to access this content.

Schedule for later
The content is saved as draft, and will be automatically published on the date and time selected.

**Comment by klonos** [comment]
> ...once that change was made this is probably RTBC.

I've removed the `else` bit that @jenlampton and @BWPanda suggested, and rebased. Tests are all green 👍 

> I guess it's not intentional, is it?

It is intentional @olafgrabienski. When you are on the content type configuration form, all these options apply to to all content, so the intention is for every help text to mean "content of this type **saved in this state** will be ... by default". When editing or creating content, each individual help text is meant to mean "this specific piece of content will be ... soon as you click save".

**Comment by olafgrabienski** [comment]
> It is intentional (...)

Now I see the principle behind the differences, thanks for the clarification, @klonos!

That said, shouldn't the change discussed above (remove the word "all") be applied to both the content type settings and the node form?

**Comment by olafgrabienski** [comment]
Uh, this one didn't make it into `1.17.5`! @klonos Are you able to update the PR (remove "All" / "all"), so that the improvement can go in the next release?

**Comment by indigoxela** [comment]
Looks like there's consensus here. I see that text changes have been requested - remove the superfluous "all" from two strings.

@klonos are you able to do these tiny changes? Shouldn't be too time consuming.

**Comment by jenlampton** [comment]
Rebased and removed the two "all"s: https://github.com/backdrop/backdrop/pull/3613.

**Comment by klonos** [comment]
Thanks @indigoxela and @jenlampton for reviving this 🙏🏼 

I cannot mark this RTBC, since I worked on the code, but reading through this thread, there's only one UX that remains:

![chase-checkbox](https://user-images.githubusercontent.com/2423362/116833372-6b2bc300-abc1-11eb-8b44-b5d6bafbdfaa.gif)

^^ ticking/unticking that checkbox moves it from under your cursor, which is a UX no-no. I proposed to move that checkbox above the list of radio options, but never got any feedback re that.

**Comment by jenlampton** [comment]
> I proposed to move that checkbox above the list of radio options, but never got any feedback re that:

I like it, nice clean solution.

**Comment by jenlampton** [comment]
Okay, I pushed this change to the PR: https://github.com/backdrop/backdrop/pull/3613

**Comment by klonos** [comment]
Thanks @jenlampton 👍🏼 ...I've re-reviewed the code, and it LGTM; also tested things, and I could not spot anything obviously wrong or any UX issues.

Since I co-wrote the PR, I cannot mark as WFM or RTBC; anyone else give it a final round of testing/review please?

**Comment by olafgrabienski** [comment]
Finally found some time to have a look at the sandbox website. Works for me!

**Comment by indigoxela** [comment]
The code is looking good :+1: 

One thing worries be a bit: the form structure slightly changed, which might have impact on existing hook_form_alter() implementations. However, I've no idea what policies apply regarding that - if there are any.

The form structure change:

- `$form['options']['sticky']` turns to `$form['options']['additional']['sticky']`
- `$form['options']['promote']` turns to `$form['options']['additional']['promote']`

If that's OK, the change could get merged. I *would* tentatively mark it as RTBC. But... both sandboxes lead to 404. Does anyone know, why?

**Comment by klonos** [comment]
> both sandboxes lead to 404.

One of them does work @indigoxela. Care to have another try: https://github.com/backdrop/backdrop/pull/3613#issuecomment-830978105

**Comment by indigoxela** [comment]
Ah, right, the Tugboat sandbox works again.

Tentatively marking as RTBC. See my previous comment for the reason (form structure).

**Comment by quicksketch** [comment]
> One thing worries be a bit: the form structure slightly changed, which might have impact on existing hook_form_alter() implementations.

I'm uncertain about the "Additional Actions" wrapper as well. Although it's less likely that someone would need to form_alter() these options now that sticky/promote can be enabled/disabled per content type, I could still see situations where they might be modified for other reasons (change the label, adding descriptions, changing to radios, setting `#access` for certain roles, etc). Form structure is not a strictly protected API, but I think avoiding this change for the minor benefit of a wrapper would be a safer move.

@jenlampton would you be okay with compromising to remove the wrapper so we could take the part that has less impact and solves the main problem from this issue?

**Comment by jenlampton** [comment]
> would you be okay with compromising to remove the wrapper so we could take the part that has less impact and solves the main problem from this issue?

Yeah, let's see what it looks like without the wrapper.

**Comment by stpaultim** [comment]
I'm going to try and update this PR if that is OK.

**Comment by jenlampton** [comment]
Go for it!

**Comment by stpaultim** [comment]
If I understand correctly, the next step on this issue was to remove the wrapper around the additional items. 

**WAS (in recent PR)**

![additional-3](https://user-images.githubusercontent.com/3144571/133185340-7e9b9795-7a1e-4833-a982-d8fff2ac0a95.png)

**Without wrapper (have not pushed this code yet):**

![additional-2](https://user-images.githubusercontent.com/3144571/133185382-1f360d52-a225-402e-a818-54305bc0a357.png)

![additional-1](https://user-images.githubusercontent.com/3144571/133185390-633a49e6-55a0-45a8-b45c-b0b7e77b7fac.png)

**Comment by stpaultim** [comment]
**Here is a version without the wrapper**

![additional-4](https://user-images.githubusercontent.com/3144571/133187721-e62a7984-3924-4bb7-88b3-8d7546773683.png)

![additional-5](https://user-images.githubusercontent.com/3144571/133187771-ed7c66ea-eaed-4f81-9d46-fb81d9be5070.png)

**Comment by klonos** [comment]
Thanks @stpaultim 🙏🏼 ...your approach does what @quicksketch requested: removes the wrapper, so that the form structure doesn't change for the 2 checkboxes 👍🏼 

The addition of the "Additional actions" label is achieving a nice visual distinction/grouping 👍🏼 ...the implementation is not right though (adding a label to the form using `'#type' => 'markup'`). `<label>`'s should have a matching input element, and specify a `for="..."` attribute. See the "Publish action" label for the radios above the checkboxes in the same form for example, which has `<label for="edit-status">Publish action </label>`. Labels need to be created that way in order to help people using screen readers, whereas the way you have implemented this is most likely to confuse people that rely on assistive technologies.

So we have a decision to make here:
- Adding a wrapper to the checkboxes provides the required visual grouping/separation 👍🏼 ...but it also changes the form structure, which can possibly break current form overrides 👎🏼 
- Removing the wrapper reduces the possibility to break existing from customizations 👍🏼 ...but it makes the 2 checkboxes appear to be as part of the previous set of radios on the form 👎🏼

**Comment by klonos** [comment]
...we might be able to get away with it by using the `aria-labelledby` attribute:

- https://stackoverflow.com/questions/24204063/can-i-use-multiple-labels-for-a-form-element
  > You can have multiple labels that point to the same form control and it's legal.
  > According to [HTML 4 Documentation](http://www.w3.org/TR/html401/interact/forms.html#h-17.9.1):
  >
  > > The LABEL element may be used to attach information to controls. Each LABEL element is associated with exactly one form control.
  > > 
  > > The for attribute associates a label with another control explicitly: the value of the for attribute must be the same as the value of the id attribute of the associated control element. **More than one LABEL may be associated with the same control by creating multiple references via the for attribute**.

- https://stackoverflow.com/questions/12164617/how-to-have-one-label-for-multiple-select-boxes/14433073
  > ... you can also use `aria-labelledby` and reverse the naming reference ...
  > ```html
  > <label id="date">Check in date</label>
  > <select aria-labelledby="date">
  >     
  > </select> 
  > <select aria-labelledby="date">
  >     
  > </select> 
  > <select aria-labelledby="date">
  >     
  > </select>
  > ```
- more usage examples: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-labelledby_attribute

@stpaultim I've tried to create a PR against yours that does the above, but since many things have recently been merged into core, your branch needs to be rebased. This is the PR: https://github.com/stpaultim/backdrop/pull/2 but the actual changes to review/merge are in this commit: [`1e6baa9` (#2)](https://github.com/stpaultim/backdrop/pull/2/commits/1e6baa9b852f6d1d40db7b716265c958e66f48bb)

**Comment by stpaultim** [comment]
> @stpaultim I've tried to create a PR against yours that does the above, but since many things have recently been merged into core, your branch needs to be rebased.

I thought I rebased yesterday. I'll check. Thanks for the follow-up. I am not surprised about the problems with my PR - I was trying things that I'm pretty unfamiliar with. I'll look at your PR later today.

**Comment by klonos** [comment]
> I thought I rebased yesterday.

You most likely must have done so ...but @laryn has gone out on a merge frenzy in the meantime 😅

**Comment by stpaultim** [comment]
@klonos - I've rebased and merged your changes. Please, review to make sure I merged them correctly. I did have to resolve one conflict. https://github.com/backdrop/backdrop/pull/3742

**Comment by klonos** [comment]
Looks good @stpaultim 👍🏼 

![image](https://user-images.githubusercontent.com/2423362/133325606-6c3ba56f-e342-470d-bb44-44f479f85887.png)

(My branch is freshly-rebased, and it currently has no diff when compared against yours)

**Comment by stpaultim** [comment]
@klonos - should this be returned to "Needs Testing" and "Needs Code Review"?

**Comment by klonos** [comment]
Yes please

**Comment by klonos** [comment]
@jenlampton would it be OK to close your PR, so to have only @stpaultim's open? (it was based off of yours).

**Comment by jenlampton** [comment]
Yes!

**Comment by stpaultim** [comment]
Status report on this PR: 

This issue was RTBC, but [here](https://github.com/backdrop/backdrop-issues/issues/3122#issuecomment-849283502) @quicksketch found an issue of concern asked for additional work. 

I created a new PR based upon the suggestions by @quicksketch. @klonos found some issues with my PR and offered another PR, which has been merged into my PR. 

In theory, this one should be pretty much ready to go. But, it needs a fresh round of testing and then Code Review. 

Atten: @quicksketch, @jenlampton, @klonos, @indigoxela

**Comment by klonos** [comment]
Thanks for summarizing things @stpaultim 🙏🏼 

I have tested things on the PR sandbox, and everything worked as expected. I also reviewed the code, and it looks good to me, but as I have contributed to it, I shouldn't be the one to mark RTBC.

**Comment by jenlampton** [comment]
It's been quite a while since I looked at this, so I think It's okay for me to review again now. I love this! It's such a big improvement from what we have now :) RTBC and WFM!

New content:
<img width="1287" alt="Screen Shot 2021-12-22 at 11 41 54 AM" src="https://user-images.githubusercontent.com/397895/147146875-4bc42030-d975-4dc6-93f9-9b2c77f55c78.png">

Existing content:
<img width="1227" alt="Screen Shot 2021-12-22 at 11 42 44 AM" src="https://user-images.githubusercontent.com/397895/147146846-a01ac17c-8044-4547-8373-9c31a59d3eb0.png">

**Comment by quicksketch** [comment]
Latest version at https://github.com/backdrop/backdrop/pull/3742 all looks good to me too. I've merged into 1.x for 1.21.0. Thanks @stpaultim, @opi, @klonos, @olafgrabienski, @jenlampton, and @mikemccaffrey!
