### ISSUE TITLE
Update not worked - Backdrop 1.10.0

### ISSUE THREAD

**Issue by AlexL777** [backdrop/backdrop-issues#3124]
## Describe your issue or idea

Hi Developers,

I have just uploaded the directory `/core` to the server and unfortunately right in the frontend error that says nothing. You can take a look at https://backdrop.cms-blogger.eu.

How can I debug backdrop if the webpage is unreachable?

There must be some useful error message to see, otherwise you can not fix the problem.

I work under Centos 7.4, PHP 7.1, MariaDB 10.2.14 and Plesk Onyx.

**Comment by opi** [comment]
@AlexL777 did you run the database update ? either with `drush updb` or visiting `/update.php` on your website.

**Comment by findlabnet** [comment]
I can confirm same problem. 
When attempt to run DB update - site freeze in maintenance  mode.
In dblog lot of messages like
 `PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'base.scheduled'...`
Environment:
Debian 8.10, 
PHP 5.6.33, 
MySQL 5.5.60
SSL and CDN by cloudflare.com (ProWebsite plan)

**Comment by AlexL777** [comment]
Thanks for the Hints @opi . My Problem is solved 👍

**Comment by quicksketch** [comment]
Great, thanks @AlexL777 for the follow-up! Yes, update.php _must_ be run right after the upgrade. It's mentioned in the release notes: https://github.com/backdrop/backdrop/releases/tag/1.10.0

> It will be necessary to run the update script (located at `/update.php`) for this release.

Although we made it so that the site is still able to do a login (so you can run update.php), visiting any piece of content will throw errors saying the "scheduled" column is missing from the node table, which was added this release.
