### ISSUE TITLE
Security report removed - Backdrop Security Team notified.

### ISSUE THREAD

**Issue by sevck** [backdrop/backdrop-issues#3139]
Description:
Cross-site scripting (XSS) vulnerability in Backdrop CMS might allow remote attackers (users) to inject arbitrary web script or HTML via the source editor, which will result in Stored XSS when an Administrator tries to edit the post.

Vulnerability Type: Stored XSS

Attack Vectors:

Login as user on Backdrop CMS
Click on Content -> Add Content -> Page
Change to HTML mode in content box.
Add XSS Payload : <img src=1 onerror=alert('xss')>, set Formatting options Editor: Full HTML
Save the blog.
Access this Page
Open the malicious blog and click on edit.
XSS!
Attack Impact:
This could be used to perform actions against the administrators (or any user editing that post) and could potentially lead to hijacking the user’s session/token. This could happen by users navigating to the attacker’s post on their own, or by the attacker somehow persuading the victim to navigate to the post.

Note: It'll not result into XSS in the normal view mode, but when admin or other user will try to edit the post code will be executed.[Stored XSS from User to Admin.]

Credit:
This issue was discovered by ﻿QingTeng cloud Security of Minded Security Researcher jianan.huang

---

Please do not use this issue queue to report security issues*. If you believe
you may have discovered a security issue with Backdrop CMS, contact the Backdrop
Security Team directly at security@backdropcms.org. In order to keep everyone
safe, we manage security issues separately in a private repository. So please
refrain from publicly blogging, or tweeting about it until the issue has been
resolved.

**Comment by klonos** [comment]
@sevck thank you for taking the time to report the issue, but the proper channel to communicate this is via the email above. I have removed your comment above and forwarded your findings to the Backdrop Security Team.

**Comment by klonos** [comment]
@sevck thank you for reporting this issue. We have evaluated your findings and have concluded that this is a non-issue, or by-design feature if you like...

By changing the input format to Full HTML, one chooses to bypass Backdrop's built-in XSS protection. This format is for administrator use only, because it does present these kinds of risks. So the risk is mitigated by the fact that there are permissions that administrators can use in order to restrict the use of this text format to specific users/roles.

If you have further concerns, please do not hesitate to contact the Backdrop Security Team directly via security@backdropcms.org

Thanks once again.
