### ISSUE TITLE
Base/sub install profiles

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#3174]
**Update:** It was decided that this feature won't go into Backdrop core, but it is easy enough to create sub-profiles without any core changes. Sub-profiles just need to run the base profile manually as the first step in their install hook, and list the base profile's dependencies in their info file. See the attached test profile here as an example: https://github.com/backdrop/backdrop-issues/issues/3174#issuecomment-629072580

---

I'd like to propose adding the ability for install profiles to define a 'base profile'. Here's the equivalent Drupal issue for this feature request: https://www.drupal.org/project/drupal/issues/1356276

The way I see this working is that an install profile defines a 'base profile' in it's .info file (like themes can define a 'base theme'), then when that install profile is used to setup a new website, the base profile is run first, then the regular profile.

This would make it easier, for example, in https://github.com/backdrop/backdrop-issues/issues/3126 to create additional install profiles based off the Standard one without having to re-invent the wheel as it were.

Also, my use case (admittedly probably only useful to me) is wanting to create install profiles that setup packaged websites for my clients. Clients can purchase the basic package, which sets up a website the way I like to build them for my clients (content types, configuration, etc.), or they can purchase the advanced package, which (in addition the the basic package) sets up additional features (extra modules, advanced configuration, etc.). This would save me having to duplicate my basic install profile.

---

Advocate: @BWPanda

---

PR by @BWPanda: https://github.com/backdrop/backdrop/pull/3038

**Comment by klonos** [comment]
Thank you for opening this issue @BWPanda 👍 ...I really like this idea. My only concern is **how** we could make it so that certain things (modules/themes/layouts) from the base profile could be excluded/disabled/removed/overridden in the derivative profile.

I perfectly understand Sun's thought process and reasoning behind his (lengthy) comment here (which challenges the **how** into a **we should NOT**), but I do not agree with it. That's thinking like a developer *first*, rather than an end-user.

This is related to #1829 BTW.

**Comment by klonos** [comment]
...as the summary of the d.org issue states (emphasis mine):

> An early resolution was to include a tag to [exclude dependencies and themes](https://www.drupal.org/node/1356276#comment-11434177). In an effort to clearly define focus for this patch, this functionality was [removed](https://www.drupal.org/node/1356276?page=1#comment-12293758) from this patch. **The use case for `excluded_dependencies` and `excluded_themes` is still very much valid**, so this feature request has been given [its own issue](https://www.drupal.org/node/2914389).

**Comment by BWPanda** [comment]
I wonder if a simple solution would just be to support base profiles 'as is', meaning they're run in their entirety with no customisation from the sub-profile. If the sub-profile wants to change something about the base profile, it can just do so in its code (e.g. delete a content type, re-assign permissions, uninstall modules, etc.)...

My new use-case for this is wanting an install profile that adds default content and some configuration, but I want a default Backdrop site otherwise (i.e. the Standard install profile). Currently I'll have to clone the Standard profile and add to it, but being able to make a sub-profile of it (with no changes needed) would be nice.

**Comment by cellear** [comment]
There's clearly a desire to be able to bundle functionality in larger chunks than is provided by modules, themes, and layouts.  Install profiles scratch this itch to some extent, but to me they seem like too much of a one-way exclusive trip.  I like the ability to bundle together modules, themes, libraries, content, and other bits and pieces into a named coherent bundle, but I'd desperately like to be able to do more with them.  Such as:

- Add them to an existing site.
- Remove them
- Combine them
- Select subsets

You get the idea.

This has been approached before, with Features module for one, and with Panapoly "Applications" for another.  I'm sure there have been many more.

Nevertheless I think it would be a big win.  Perhaps it could be achieved by leveraging CMI?

**Comment by BWPanda** [comment]
I think you're thinking about 'recipes' @cellear: https://github.com/backdrop/backdrop-issues/issues/3763 ...?

**Comment by BWPanda** [comment]
I made a [PR](https://github.com/backdrop/backdrop/pull/3038) that tries to address my simplified use-case above. However the installer's failing part-way through installing the modules (and can't access any error message to see what's going on)...

**Comment by BWPanda** [comment]
I've updated the PR and the installation now completes without any errors. It seems like both my normal install profile and its base install profile are setup, however currently my normal install profile is installed in the middle of the other modules, and the base install profile is installed at the very end (order should be: modules, base profile, normal profile). If I can fix the order then this might actually work!

**Comment by kreynen** [comment]
@BWPanda can you share your profile and sub profile? Or create generalized versions I could use to test this. I'm really interested in looking at what you are doing and understanding the use case of the profile/sub profile in Backdrop.

There was a discussion in the Pantheon Slack the other day about how Open Atrium had stopped updating with the D7 core updates. This happened with the less popular Open News distribution/install profile that Phase2 also abandoned. Users of Open News profile were basically screwed because Phase2 refused to add new maintainers to a project they'd invested in "productizing", but had lost interest in maintaining the project. Without a fair amount of technical expertise and effort, users who had built a site on Open News were forced to rebuild the site one way or another.

Hindsight being 2020, it's now clear we made a lot of mistakes with how profiles worked in D7.

**Comment by BWPanda** [comment]
@kreynen So you just need to create a simple profile that has `base = standard` in its info file, and then changes something about the standard install (e.g. removes the default About page).

If, after running the installation and choosing your new profile, the site looks like regular Backdrop, you know the Standard profile ran successfully. If the About page is gone, you know your profile also ran and that it correctly ran after the Standard profile.

**Comment by kreynen** [comment]
One (of many) reason that https://www.drupal.org/project/drupal/issues/1356276 never made it into Drupal core is that while the approach seemed to work when expanding on the base (installing and configuring additional functionality), it was never clear how updates should be handled when the base configuration had been overridden.  Perfection became the enemy of progress killing.

Are you only concerned with what's included and installed initially or are you trying to recreate the way modules, libraries and themes are updated/maintained in packaged install profiles?

**Comment by BWPanda** [comment]
> it was never clear how updates should be handled

Can you explain what you mean by that?

Once a site is installed, any changes to the install profile are ignored (as far as I know). That functionality (allowing install profiles to affect existing sites) is what's being discussed in other issues (like the 'recipes' one I linked above).

This issue is simply about creating an install profile that copies functionality from another install profile without having to reinvent the wheel.

**Comment by kreynen** [comment]
I have a few things to finish up before taking the kids to swim lessons, but I'll find some time later this week to highlight some of the specific issue in the years of posts to https://www.drupal.org/project/drupal/issues/1356276 as well as the issues we ran into when we pushed for Umami to be created as a subprofile of Standard vs. another profile in core with https://www.drupal.org/project/demo_umami_subprofile

When I worked with the Knight Foundation to develop solutions for community media groups, I did something similar to the use case you are describing. We built dozens of sites on https://www.drupal.org/project/cm_starterkit_easy, https://www.drupal.org/project/cm_starterkit_moderate and https://www.drupal.org/project/cm_starterkit_difficult using https://www.drupal.org/project/profile_switcher to add the additional features to a site as an organization was ready (as well as migrate out of a packaged install profile). Initially this architecture worked well, but as sites went in different directions the install profiles became harder to maintain. We couldn't include an update_hook to fix X because a few of the sites changed the configuration to do something different than what was originally installed.

Over the years there have been a number of people who've made the case that install profiles should have been used just for installs and instead of building specific version of contrib modules  with .make that lived in profiles/module, the install profile should have simply guided you through the process of adding the recommended modules to sites/all and setting initial variables. 

I always advocated for .profile to do more and for an easy process to get all of the code required to run start a site based on an install profile. 

I was wrong.

**Comment by BWPanda** [comment]
Here's an install profile to test with: [test_profile.tar.gz](https://github.com/backdrop/backdrop-issues/files/4076089/test_profile.tar.gz)

It's a sub-profile of 'Standard' and does only two things: create an Editor user called 'Mary' and deletes the 'About' page node.

To test:

- Extract the above file to `/profiles` (so you have `/profiles/test_profile/test_profile.info`).
- Install Backdrop, selecting the 'Test Profile' install profile (instead of 'Standard'). Do everything else as you normally would.
- Once the site's setup, check that:
  - There's a Post node called 'Your first post!' (this means the 'Standard' install profile still ran).
  - There's a user account called 'Mary' with the role 'Editor' (this means the 'Test Profile install profile also ran).
  - There's no Page node called 'About' (this means the 'Test Profile' install profile ran after the 'Standard' install profile).

**Comment by BWPanda** [comment]
The latest commits now have this working nicely! You can define `base profile` in your install profile's `.info` file and it'll install that profile before yours (see testing instructions above).

**Comment by laryn** [comment]
Tested as described in https://github.com/backdrop/backdrop-issues/issues/3174#issuecomment-575547442 and outcome was as described.

**Comment by stpaultim** [comment]
I started to reply to this with skepticism, because I questioned the use case for wanting to build an install profile that inherits from the standard install profile (seems like an edge case). But, like @BWPanda, I have put a fair amount of work into my own install profile and I can see real value in the option to create my own triplo_base_profile and then other profiles that inherit those settings but are customized for specific situations. 

The more I think about this, the more I like it and think that I would use it.

**Comment by BWPanda** [comment]
I just tested installing different modules as dependencies of the sub-theme (e.g. I added the following to the sub-theme):

```
dependencies[] = book
dependencies[] = contact
```

These modules aren't part of the Standard install profile, so the fact that they showed up as enabled in the site means this is working nicely too.

However I then noticed that every other enabled module couldn't be disabled. This is because it was listed as a dependency of the Standard profile. Normally this doesn't happen with the current profile, but when the current profile depends of the Standard one, and the Standard one depends on various modules, those modules can't be disabled.

I've made a new commit that fixes this by only listing the base profile as a dependency during installation. Outside of that, any profiles other than the current one are removed from the module dependency check.

Finally, note that, as discussed, this method of sub-profiling is a simplified version of other suggestions (where people want to disable modules of the base profile from a sub-profile). This isn't possible in this PR, and I think if that sort of functionality is desired it should be a separate issue. However, anyone wanting to do this can simply do something like the following in their sub-profile's `.install` file:

```php
// Disable/uninstall certain modules from the base profile.
$modules = array('date', 'link', 'number');
module_disable($modules);
backdrop_uninstall_modules($modules);
```

**Comment by BWPanda** [comment]
Not sure whether to reset the 'works for me' label after making a new commit...

**Comment by BWPanda** [comment]
Not sure why this was added to 1.15.1 milestone (that's for bug fixes, right?)...

**Comment by hosef** [comment]
I took a look at the changes in your PR. Everything looks good to me and it all seems to be working in my initial tests.
There is one problem with the current implementation though and that is that there is no installation profile in core that uses a base profile. Because of this, there are no tests that verify if this is working. I think an easy solution would be to make the testing profile depend on the minimal profile. We should leave the module dependency on the layout module even though that is also in the minimal profile to make sure that duplicates don't cause problems. We should also add a new dependency to verify that the modules are enabled correctly. I think adding a dependency on block would be ok, since it doesn't add any new database tables.

**Comment by bd0bd** [comment]
Well, I do not use Backdrop CMS any more and I am not going to use it in future.
Drupal 7 is better suitable for business.
Bye Backdrop!

**Comment by kreynen** [comment]
@bd0bd not sure what that has to with anything being discussed in this issue, but best of luck with that.

**Comment by klonos** [comment]
We could make the Minimal profile a base profile for both the Testing and the Standard profile. The idea being that you start off of the Minimal, and add any extras in the Standard.

**Comment by kreynen** [comment]
Isn't core Backdrop already supposed to be the recommended install for project's target audience? If you are determined to go down this road, what about creating a Umami style demo site that only leverages core functionality that uses standard as the base? 

Part of the reasoning for including Umami in Drupal core was that it made it easy for people to demo what's possible with just Drupal core on free hosts like Pantheon. Backdrop's default install is already a better starting point than Drupal's standard, but I think it would still benefit from this type of demo configuration.

**Comment by BWPanda** [comment]
> There is one problem with the current implementation though and that is that there is no installation profile in core that uses a base profile.

I agree that having one of the core install profiles be based on Minimal would be a good idea, however @quicksketch raised concerns about this (specifically relating to the Standard profile) in the dev meeting last night.

I'd therefore like to propose moving the discussion about core profiles to a new issue, and focus here on getting this feature committed.

**Comment by klonos** [comment]
I agree: #4338 😉

**Comment by klonos** [comment]
...code LGTM 👍 (just some suggestions on comment wrapping and punctuation 😅)

**Comment by klonos** [comment]
...also, I'm gonna do @quicksketch a favor and say "Tests??" 😅

**Comment by BWPanda** [comment]
Ah, the magic 'T' word. My kryptonite; rendering my contributional powers useless. I will continue trying to advocate for this issue, but it'll need someone with a knowledge of tests to step in and write them. Unfortunately, from what I've see previously, it may mean this issue is now stalled indefinitely...

**Comment by BWPanda** [comment]
Based on the comments so far I'm going to mark this RTBC (pending tests of course).

**Comment by oadaeh** [comment]
I'm pretty sure the point @hosef was making about core install profiles was because of tests, not to add a new feature to this one:

> Because of this, there are no tests that verify if this is working.

**Comment by BWPanda** [comment]
@oadaeh Understood. I was referring to @klonos' suggestion for the Standard profile being based on the Minimal one. Writing tests for this will likely need to use either @hosef's suggestion, or a new profile solely for testing this feature.

**Comment by klonos** [comment]
> I was referring to @klonos' suggestion for the Standard profile being based on the Minimal one.

Well, if that happened, then I imagine that the test would look something like:

1. install the Standard profile
2. make sure that the modules specified in the Minimal profile have also been installed.

With #4338 not yet in place, I imagine that it will look like this instead:

1. Create an "abc" profile (as part of the tests) that enables modules a, b, and c.
2. Create another "xyz" profile that enables modules x, y, and z.
3. Install the xyz profile.
4. Make sure that modules a, b, and c have also been enabled.

**Comment by hosef** [comment]
I have started working on adding a test for this. I am running into some weird behavior with the test setup code that I might have to fix, so it may take a little while.

**Comment by quicksketch** [comment]
I'm conflicted about this feature. While a base profile sounds convenient (e.g. just like the "standard" profile but with one more thing), it appears as though this functionality is going to be hard to verify through our current testing framework because the install system operates differently for tests than it does for a normal installation. Even if we can make the testing framework imitate a normal install so that it respects base profiles, it's still not going to be running the same thing as a "real" installation of Backdrop.

Custom (or even contrib) install profiles are also less frequently used than custom modules or themes, and they generally cover a lot less functionality. Overall, my perspective on this feature is that it's a minimal convenience while at the same time being untestable and uncommon.

There's also a fairly easy work-around for the use-case of "just like standard except for one thing", and that's to simply include the file from the other profile and then call that profile's `hook_install()`. Although it's been years since it's been maintained, that's exactly what I did in the "Surveyor" install profile for Drupal 7:

https://git.drupalcode.org/project/surveyor/-/blob/7.x-1.x/surveyor.install
```
/**
 * Implements hook_install().
 */
function surveyor_install() {
  // Invoke the standard install profile for basic setup. We don't want to be
  // different than a normal Drupal installation.
  include_once DRUPAL_ROOT . '/profiles/standard/standard.install';
  standard_install();

  // Remove the body field from Webform nodes.
  $instance = field_info_instance('node', 'body', 'webform');
  field_delete_instance($instance);
}
```

Of course that won't handle all the situations this PR would cover, such as nested dependencies. But I don't think those scenarios are common enough to require core support, especially if custom or contrib profiles could manage equivalent functionality with more work on their part.

**Comment by BWPanda** [comment]
> There's also a fairly easy work-around for the use-case of "just like standard except for one thing"...

I need to test this, but my initial reaction is that this would work for 99% of the cases that this PR/issue handles. In other words, I'd be happy to close this as a 'won't fix' and to instead let each install profile do its own thing as @quicksketch described.

**Comment by BWPanda** [comment]
So I'm testing this with my Spam Challenge profile, and I have is this error:

```bash
Error: Class &#039;TaxonomyVocabulary&#039; not found in standard_install()
(line 228 of /var/lib/tugboat/backdrop/core/profiles/standard/standard.install).
```

I guess the solution is to include whatever file defines that as well, but I wonder how Standard does it, since it doesn't seem to need to include anything...

**Comment by quicksketch** [comment]
Ah, one more caveat. In your .info file, you have to duplicate all the modules used in standard, plus any contrib modules you would like to add. See the D7 Surveyor install profile as an example:

https://git.drupalcode.org/project/surveyor/-/blob/7.x-1.x/surveyor.info

**Comment by quicksketch** [comment]
With code-freeze today, I'm pulling this out of the 1.16.0 milestone. @BWPanda do you think we should pursue this further?

**Comment by BWPanda** [comment]
@quicksketch No worries re. milestone, but I'd like to keep this open until I have my install profile working based on your suggestions above. Than I'll know that the alternative solution works and we can close this. Just haven't had much of a chance to get to it as yet...

**Comment by BWPanda** [comment]
Meh, can't figure it out, but not important right now. Closing.

**Comment by jenlampton** [comment]
I've added the works-as-designed label, is that what we use for issues that will not be implemented in core?

**Comment by BWPanda** [comment]
Sorry for my short comment yesterday, I was just frustrated with not getting stuff working, but it seems to be stuff in my profile un-related to the whole sub-profile thing.

After listening to your concerns in the dev meeting, I tried again today with the test profile I originally [attached above](https://github.com/backdrop/backdrop-issues/issues/3174#issuecomment-575547442). I edited it to uses @quicksketch's suggestions, and it seems to work. The Standard install profile works and does its stuff, and then the test install profile does its stuff too. There was an issue with the frontpage not showing up, but that might be unrelated. Main thing is that both the base and sub profiles are run as expected.

Here's an updated copy of the test profile as an example for anyone wanting to do sub-profiling in future: [test_profile.tar.gz](https://github.com/backdrop/backdrop-issues/files/4632797/test_profile.tar.gz)
