### ISSUE TITLE
Add predefined color schemes to Basis

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#3209]
## Describe your issue or idea

In https://github.com/backdrop/backdrop-issues/issues/3028, we added color support to Basis. But currently, there is only a single pre-defined color scheme (the default Basis-blue). We should include a few out-of-box color schemes for Basis like we do for Bartik.

---

PR by @hosef https://github.com/backdrop/backdrop/pull/2613

**Comment by klonos** [comment]
Thanks for opening this one @quicksketch. I think that this will make Basis a bit more popular 👍

Any suggestions re colors? Should we start by imitating the Bartik ones?

@wesruv? ...this is your baby.

**Comment by quicksketch** [comment]
As boring as it may sound, the most likely colors to be popular are blue and gray. Rather than getting crazy, I think a second blue variant, and two gray ones would provide popular options.

I'm also of the opinion if a color scheme doesn't look good we shouldn't include it. Sometimes it can be tempting to get crazy just to show the level of flexibility, but users are pretty good at shooting themselves in the foot with color module as it is.

**Comment by klonos** [comment]
...at some point long ago, I recall @wesruv saying that he envisioned that we could be asking the user to input some colors of their brand (upload their logo for example), and then we have some sort of "magic" thing happening, where we take these colors and theme the site to match them.

Not sure if this was just a crazy "how awesome would it be if" idea, or if you actually had some plan @wesruv ??

**Comment by klonos** [comment]
...something like http://www.coolphptools.com/color_extract or https://github.com/thephpleague/color-extractor

**Comment by klonos** [comment]
Thanks @Harry-Flatt ! 👍 ...way too many things to do over the weekend, but might take a crack at adding these in.

Also worth noting, as mentioned today in the dev meeting, that we could perhaps try to add the color schemes that come with Bartik.

**Comment by herbdool** [comment]
Thanks for getting the ball rolling on this! I took a look at some of these. I second the lack of options. Seems like there need to be a few more colour options in order to fix edge cases. I noticed that color module will blend colours for some areas and that can be hit or miss. In the following it's definitely a miss 
 for the tabs when I test out tropical:

![screenshot from 2018-08-20 21-10-39](https://user-images.githubusercontent.com/1071483/44374775-10f47d80-a4be-11e8-8a45-f9aff9d1a32c.png)

It seems like the link colour for text ends up being the same for the tabs and breadcrumbs which just looks bad.

**Comment by oadaeh** [comment]
I created the initial PR to take care this.
It was more challenging than I imagined, because there was a lot of color manipulation that needed to be done to get things looking okay, and that is not my forte. As a result, there might be a few colors that don't go 100% with the palette.
I added the schemes from Bartik, except for Blackdrop and Blue Lagoon, because they both seemed rather close to the default Basis scheme.
I also added the schemes from Harry, except for Cyber (because of the dark on light issue, which I really didn't want to try to fix). Both Metro and Tropical seemed to be lacking some color definition for a couple of the items (as noted by @herbdool), so I had to add a couple in, and they might also not go 100% with the palette.
I'm not sure how much more time I will have over the next week for this to have it ready for release, but I can do my best to make small, quick changes in a timely manner, if people reviewing are specific with changes that should be made.
Anyway, for what it's worth, there it is.

**Comment by quicksketch** [comment]
I bumped this to 1.11.1, as today is release day for 1.11.0. I think this could qualify for being in bug fix releases on the grounds of being a UX improvement. If we can get a design eye on this to give an approval, that would also be wonderful.

**Comment by oadaeh** [comment]
@quicksketch do you have anyone in mind?

**Comment by quicksketch** [comment]
Well @wesruv in particular, since he did the original theme. But any self-described designer would be appreciated. :smile:

**Comment by jenlampton** [comment]
In today's design meeting we confirmed this is a task and can be added into any bug-fix release. Adding milestone back.

**Comment by jenlampton** [comment]
I have an idea about the colors @hosef, can we lighten or darken the background in the instances when the contrast isn't high enough? or is that too hard to determine?

**Comment by hosef** [comment]
@jenlampton Unfortunately, the Color module has no context about which background colors and text colors get used together.

However, since #3257 has been completed, I was able to add a few more settings and categorize them so it doesn't look so overwhelming.

**Comment by jenlampton** [comment]
I'm finding it strange that the Account links in the header have a hover color. I'm going to open a separate unrelated issue about that.

**Comment by jenlampton** [comment]
It looks great! 
I left a few color adjustment recommendations on the PR. There were a few places where that I thought the contrast might not be high enough (usually in the footer) and a few color tweaks just for personal preference, but I'm excited to have this in core :) Yay thank you for your persistence on this one @hosef!

**Comment by hosef** [comment]
@jenlampton I implemented the color changes you recommended.

I also discovered that the arrows and text in sub menus were not updating when the header text color was changing, which made it almost impossible to read on light themes. That has also been fixed.

**Comment by jenlampton** [comment]
There is no goldfish in Drupal 7. Bartik has:
* Firehouse
* ice
* plum
* slate

**Comment by jenlampton** [comment]
@hosef I think the last commits are good enough for me! thank you :)

**Comment by quicksketch** [comment]
I've merged https://github.com/backdrop/backdrop/pull/2613 into 1.x for 1.13.0. With the imminent release, I don't think we need to backport this one.
