### ISSUE TITLE
[UX] Removing 'main content' block causes some page elements not to display

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#3247]
## Describe your issue or idea

In certain situations, removing the 'Powered by Backdrop' block causes some page elements (e.g. page title, local tabs, etc.) not to display.

### Steps to reproduce (if reporting a bug)

1. On a standard, out-of-the-box setup, add a new layout with path set to `node/%`
2. Remove the main content block
3. Add the "Page tabs (local tasks)" block to the content region
4. Visit an existing node while logged in as admin (note how the View/Edit tabs are displayed)
5. Remove the 'Powered by Backdrop' block
6. Visit the same node again

### Actual behavior (if reporting a bug)

The tabs have disappeared.

### Expected behavior (if reporting a bug)

Only the 'Powered by Backdrop' block should have disappeared.

The same thing happens if, in step 3, you instead add the 'Page title combo' block or the 'Page title' block.

For an explanation of how this was discovered, and possibly a bit more info, see https://github.com/backdrop/backdrop-issues/issues/3228#issuecomment-410171699 onwards.

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2386 (**all credits for the fix should go to @docwilmot ** )

**Comment by BWPanda** [comment]
From the linked issue, a further note: When clearing caches then the page title and local tabs are displayed properly. However on subsequent refreshes they're gone again.

**Comment by jenlampton** [comment]
No PR here yet, removing milestone. (We can add it back into the next bug-fix release as soon as we have a PR)

**Comment by stpaultim** [comment]
I got burned by this issue today (I think I did once before as well). I'm feeling a little stupid because of the big warning on the block not to remove it. In my case, I removed it the Main Content Block and everything continued to work fine for weeks, because I was in DEV mode and was rebuilding the theme on every page load. As soon as I turned this off, my custom title block began to act very weird on my production site. #3387

I spent about two hours trying to debug this problem today. I would endorse Jen's comment "It may be worth revisiting how we can prevent these issues instead of adding the warning, and always load the context at provided system paths." 

How can I help?

**Comment by stpaultim** [comment]
OK, this problem just got a little worse for me. I had removed this block because I had used blocks for node fields in specific regions. When I put the "Main Content Block" back, my content was duplicated. I suppose, I just need to keep at least one field in the node display and use that for the main content block. 

But, I am thinking that this might be a more serious problem than I thought before.

**Comment by jenlampton** [comment]
> When I put the "Main Content Block" back, my content was duplicated.

Yes, you'll need to configure the default (or full) view mode to show a sub-set of fields. I like the idea of leaving one, and using it instead of the field block. Maybe the body?

**Comment by klonos** [comment]
...wondering if the same bug persists if one adds a visibility condition that effectively hides the Main Content block. If not, then that would make it ("hiding" the block) a great workaround for now.

**Comment by docwilmot** [comment]
just had a look at this, sorry for the delay. The solution is a bit of an embarrassing error, in `system_theme()`.
This:
```
    'page_components' => array(
      'variables' => array('settings' => NULL, 'child_delta' => NULL),
      'template' => 'templates/page-components',
    ),
```
Should be this:
```
    'page_components' => array(
      'variables' => array('settings' => NULL, 'child_delta' => NULL),
      'template' => 'templates/page-components',
    ) + $base,   <------------the  preprocess function isnt being called because I left this out in the original PR.
```

Please test adding that line on your sites to see if that fixes it; if someone could do a PR, if that works, would be good.

**Comment by klonos** [comment]
Great catch @docwilmot 👍 ...and since PR sandboxes are "free", I have filed a PR with the single-line fix and have tested the STR provided by @BWPanda in the issue summary. Tests are green, and it works!! 😄 

@stpaultim can you please give the fix a go on the site you were having the problem with and then mark this as RTBC? Thanks.

**Comment by stpaultim** [comment]
Does this mean we can and/or should remove the warning "This block may be required for this page to work properly." Or might there be other problems?

![test___riverton](https://user-images.githubusercontent.com/3144571/48678467-6dad1600-eb49-11e8-9b22-12ee17e0e28e.png)

**Comment by jenlampton** [comment]
I think we should test the fix with taxonomy/term pages as well, to confirm that the page still "works properly" before we should remove the message.

**Comment by docwilmot** [comment]
The warning is right. If you override a non-fieldable page with a layout, like an admin page or a page with its own page callback, or a view, nothing will show if you remove that block. 
Maybe we could make the main content block smart enough to detect if it's on a page with available fields and modify the message/warning to say please remember to replace the output with appropriate blocks or something, but that seems a bit excessive. Maybe.

**Comment by herbdool** [comment]
I've tested with taxonomy and I see no error with the PR. So I think it's good to go.

**Comment by herbdool** [comment]
Thanks @docwilmot, @klonos, @BWPanda, @stpaultim! Merged https://github.com/backdrop/backdrop/pull/2386 into 1.x and 1.11.x.
