### ISSUE TITLE
XSS (Stored) in Backdrop cms

### ISSUE THREAD

**Issue by security-provensec** [backdrop/backdrop-issues#3258]
Affected software: Backdrop cms

Type of vulnerability: (...)

Discovered by: (...)

Website: (...)

Author: (...)

Description: (...)

Proof of concept: (...)

**Comment by olafgrabienski** [comment]
@security-provensec Thanks for the report. I've removed the text because we manage security issues in a private repository. If you believe you may have discovered a security issue with Backdrop CMS, please contact the Backdrop Security Team directly at security@backdropcms.org. Please refrain from publicly blogging or tweeting about any potential security issue until it has been resolved.
