### ISSUE TITLE
Node Preview saving should behave the same as saving from node edit for "hidden path" nodes

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#3275]
## Describe your issue or idea

`node_preview_banner_form_node_submit` should react the same way as `node_form_submit` for hidden path nodes.

Because of the new node preview functionality https://github.com/backdrop/backdrop-issues/issues/3062 *and* the ability to hide node paths https://github.com/backdrop/backdrop-issues/issues/100, we need to ensure that when someone saves a node from the preview that they don't get redirected to a "page not found" if they don't have permissions to see hidden paths.

Those without permission to view hidden paths should be redirected back to the edit page when saving on node preview.

Note that we already have this functionality when saving from the node edit page: they are already being redirected back to the edit page. This is just about replicating that existing functionality to the node preview.

**Comment by klonos** [comment]
Thanks @herbdool. I feel that it would be a much better UX if we made it so that users which have permission to edit/create a specific piece of content would also bypass the `view hidden paths` permission *for that specific piece of content*. In other words, this would make more sense to me:

1. redirect to the actual piece of content as per usual (because it is a WTF to disallow a user to view the content they just created).
2. after the "content xyz has been created/updated/scheduled" success message, we also repeat the description of the hidden path setting as a warning/info message:

`This piece of content can be viewed when placed as a block or when rendered as part of a listing, but will not be accessible at its direct URL without proper permissions. This facilitates "hidden path" content that is meant to be embedded with other content and never on its own. Users who have the "View hidden paths" permission will still be able to access the direct URL of this specific piece of content, while those without this permission will receive a "Page not found" error.`

Having said that, if we decide that this is best as implemented in the PR you have filed, then I have left a few comments in the PR about making it clearer what that bit of code does.

**Comment by herbdool** [comment]
@klonos this issue is just a bug report meant to make it into 1.11.0. Can you add your feature changes to a new issue?

As you can see from https://github.com/backdrop/backdrop/pull/2286/files#diff-7461e8a6902482c1fc141e24028ebfaaR448 I just copied this verbatim from the PR already merged and added it to this submit handler as well. So any change here also needs to be a change there and if it's not a bug fix it probably shouldn't go into 1.11.0.

**Comment by klonos** [comment]
Fair enough, but how about we also hide the "View" tab?

**Comment by herbdool** [comment]
@klonos can you make a new issue for that? This is specifically to fix a bug on the node *preview* and what happens when someone is hitting save on that page when viewing a "hidden path".

**Comment by quicksketch** [comment]
https://github.com/backdrop/backdrop/pull/2295 looks great. This only fixes the submit handler to match the normal save button. It does not address the issues @klonos brought up. But as always, let's take the easy wins and iterate. Thanks @herbdool for fixing this inconsistency!
