### ISSUE TITLE
Edit exiting image in body - error when removing

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#3276]
### Steps to reproduce (if reporting a bug)

1. Edit an existing page with an image embedded.
2. Click on the image to get the image dialogue.
3. Click "Remove"
4. Select a different image from the library.
5. Click Update

### Actual behavior (if reporting a bug)

Nothing will happen. No error message and the dialogue won't close.

### Expected behavior (if reporting a bug)

Expect it to work the same way of just selecting a different image from the library *without* first clicking Remove. That way works fine.

### Relevant version/system information (if applicable)

1.11.0 release candidate. Related to new image browser: https://github.com/backdrop/backdrop-issues/issues/3134

cc @Graham-72 @docwilmot 

---

PR https://github.com/backdrop/backdrop/pull/2300

**Comment by Graham-72** [comment]
I think this bug exists prior to the PR for #3134.

**Comment by olafgrabienski** [comment]
I confirm that the bug exists also in older Backdrop versions, I've tested it with 1.9.5. In that version there is no image browser, so in step 4 of the "Steps to reproduce" I've selected a different image from my local disk, and the behaviour was exact the same as in the issue description.

**Comment by herbdool** [comment]
Okay, thanks for checking. I wonder if we leave it for the 1.11 milestone in case someone still wants to squash it.

**Comment by quicksketch** [comment]
Let's see if we can fix this for 1.10.x as well. If we don't get to it before Sept 15, this will get bumped into 1.11.1. Thanks @Graham-72 and @olafgrabienski for confirming this was a preexisting issue.

**Comment by quicksketch** [comment]
I filed a PR at https://github.com/backdrop/backdrop/pull/2300. The root of this problem is that we change the button label in the dialog from "Update" to "Insert" if we upload a new image. When we change the label out from underneath the dialog, it continues to submit the previous label ("Update") instead of the new one ("Insert").

To fix this, we should ensure the form just doesn't change the label unexpectedly. If we're updating an image, the label on the button should always be "Update". That's what the PR at https://github.com/backdrop/backdrop/pull/2300 does.

**Comment by herbdool** [comment]
This now works. Thanks @quicksketch!

**Comment by quicksketch** [comment]
Great, thanks folks! Merged https://github.com/backdrop/backdrop/pull/2300 into 1.x and 1.10.x.
