### ISSUE TITLE
[UX] Add proper indentation to taxonomy checkboxes/radios to denote child terms.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3292]
[RJL edit: advocate is @bugfolder.]

This is how a form widget looks like for a vocabulary with nested terms, when configured to be rendered as a checkbox list:

<img width="268" alt="screen shot 2018-09-18 at 5 52 51 am" src="https://user-images.githubusercontent.com/2423362/45661663-1ff33d80-bb07-11e8-9fab-df1f2c0215df.png">

For D7, you can use the [Taxonomy Term Reference Tree Widget](https://www.drupal.org/project/term_reference_tree) module to improve how this widget works, but I believe that all the bell and whistles it offers would be too much for core. We should just get rid of the dashes from the checkbox labels and add indentation to the checkboxes. It would be so much better and more readable like so:

<img width="275" alt="screen shot 2018-09-18 at 5 56 44 am" src="https://user-images.githubusercontent.com/2423362/45661822-d525f580-bb07-11e8-8cec-6b82a9d4568e.png">

Related:
https://drupal.stackexchange.com/questions/85011/how-to-get-rid-of-the-sign-before-sub-taxonomy-term
https://drupal.stackexchange.com/questions/121053/add-class-to-sub-taxonomy-terms
https://www.drupal.org/project/drupal/issues/648264 (Core taxonomy.module issue, pending since 2009 - although for dropdowns)

**Comment by klonos** [comment]
I tried giving this a go, but got lost along the way 😞 ...there are some articles that indicate that this should be done at the Form API level or in [`options_field_widget_form()`](https://api.backdropcms.org/api/backdrop/core%21modules%21field%21modules%21options%21options.module/function/options_field_widget_form/1). Not sure how to go about it.

**Comment by opi** [comment]
@klonos https://api.backdropcms.org/api/backdrop/core%21modules%21taxonomy%21taxonomy.module/function/taxonomy_allowed_values/1

**Comment by klonos** [comment]
@opi thanks 😄...I have already figured where the dash is being added. What I could not figure out was how to alter the form to add classes to the checkboxes of children terms.

**Comment by BWPanda** [comment]
@klonos This issue was opened before https://github.com/backdrop/backdrop-issues/issues/4218 and https://github.com/backdrop/backdrop-issues/issues/4770 were merged.

Now that they've happened, is this still an issue or not?

**Comment by klonos** [comment]
Sorry for the late reply here @BWPanda ...yes, still the same issue, just now middots shown instead of dashes:
![image](https://user-images.githubusercontent.com/2423362/214900794-838681ea-2911-4e61-86dd-7898cd502dc4.png)

**Comment by klonos** [comment]
Hey @bugfolder, as discussed in today's design meeting, since you are the maintainer of the https://github.com/backdrop-contrib/term_reference_tree module that offers this functionality, perhaps you can pull out just the code that provides the indentation and provide a PR against core? ...something for your to-do list 🙂

**Comment by bugfolder** [comment]
Sure.

**Comment by bugfolder** [comment]
In looking into how to do this cleanly, the most straightforward solution would be to allow the taxonomy module to put classes onto the individual checkboxes (or radio buttons), e.g., `taxonomy-term-depth-1`, `taxononmy-term-depth-2`, and so forth. That's currently not easily done.

There currently is a way to put individual `#description` onto checkboxes and radio buttons, which is done like this:

```
$form[] = array(
  '#type' => 'checkboxes',
  '#options' => array('key1' => t('Option 1'), 'key2' => t('Option 2')),
  'key1' => array('#description' => t('Description 1')),
  'key2' => array('#description' => t('Description 2')),
);
```

And it would be fairly straightforward to modify `form_process_checkboxes()` to handle something like this, which would be a way of putting classes on the individual buttons:

```
$form[] = array(
  '#type' => 'checkboxes',
  '#options' => array('key1' => t('Option 1'), 'key2' => t('Option 2')),
  'key1' => array('#description' => t('Description 1'), '#attributes' => array('class' => array('class1'))),
  'key2' => array('#description' => t('Description 2')), '#attributes' => array('class' => array('class2'))),
);
```

But it seems a bit awkward to split the description of the elements between the option list and then individual keyed arrays. Also, that doesn't fully solve this problem because `taxonomy_options_list()` and `taxonomy_allowed_values()` only return the list of option strings, and for this one would need two separate arrays; the list of strings, and a list of keyed additional properties.

So I'd like to suggest that we add a capability to the Form API to accept more fully structured option lists, e.g., something like this:

```
$form[] = array(
  '#type' => 'checkboxes',
  '#options' => array(
    'key1' => array(
      '#title' => t('Option 1'),
      '#description' => t('Description 1'),
      '#attributes' => array('class' => array('class1')),
    ),
    'key2' => array(
      '#title' => t('Option 2'),
      '#description' => t('Description 2'),
      '#attributes' => array('class' => array('class2')),
    ),
  ),
);
```

And then we'd modify `form_process_checkboxes()` and `form_process_radios()` to check each option element; if it's a string, then it processes it as it's currently being done, but if it's an array, then it uses the properties in the array. (Note that it would have to merge group and individual `#attributes` properties, if both had `class` values.)

This seems like it would be broadly useful. It would certainly make this issue simpler to address, because then taxonomy module could return a structured option list that contains the term depth classes as attributes, thereby making indentation straightforward.

Before I go working on a PR, I'd like to get some feedback on what people think of this approach.

**Comment by bugfolder** [comment]
In looking into how to do this cleanly, the most straightforward solution would be to allow the taxonomy module to put classes onto the individual checkboxes (or radio buttons), e.g., `taxonomy-term-depth-1`, `taxononmy-term-depth-2`, and so forth. That's currently not easily done.

There currently is a way to put individual `#description` onto checkboxes and radio buttons, which is done like this:

```
$form[] = array(
  '#type' => 'checkboxes',
  '#options' => array('key1' => t('Option 1'), 'key2' => t('Option 2')),
  'key1' => array('#description' => t('Description 1')),
  'key2' => array('#description' => t('Description 2')),
);
```

And it would be fairly straightforward to modify `form_process_checkboxes()` to handle something like this, which would be a way of putting classes on the individual buttons:

```
$form[] = array(
  '#type' => 'checkboxes',
  '#options' => array('key1' => t('Option 1'), 'key2' => t('Option 2')),
  'key1' => array('#description' => t('Description 1'), '#attributes' => array('class' => array('class1'))),
  'key2' => array('#description' => t('Description 2')), '#attributes' => array('class' => array('class2'))),
);
```

But it seems a bit awkward to split the description of the elements between the option list and then individual keyed arrays. Also, that doesn't fully solve this problem because `taxonomy_options_list()` and `taxonomy_allowed_values()` only return the list of option strings, and for this one would need two separate arrays; the list of strings, and a list of keyed additional properties.

So I'd like to suggest that we add a capability to the Form API to accept more fully structured option lists, e.g., something like this:

```
$form[] = array(
  '#type' => 'checkboxes',
  '#options' => array(
    'key1' => array(
      '#title' => t('Option 1'),
      '#description' => t('Description 1'),
      '#attributes' => array('class' => array('class1')),
    ),
    'key2' => array(
      '#title' => t('Option 2'),
      '#description' => t('Description 2'),
      '#attributes' => array('class' => array('class2')),
    ),
  ),
);
```

And then we'd modify `form_process_checkboxes()` and `form_process_radios()` to check each option element; if it's a string, then it processes it as it's currently being done, but if it's an array, then it uses the properties in the array. (Note that it would have to merge group and individual `#attributes` properties, if both had `class` values.)

This seems like it would be broadly useful. It would certainly make this issue simpler to address, because then taxonomy module could return a structured option list that contains the term depth classes as attributes, thereby making indentation straightforward.

Before I go working on a PR, I'd like to get some feedback on what people think of this approach.

**Comment by argiepiano** [comment]
It may be easier (and safer) to create a new "tree" widget type for taxonomy terms, like the one provided by Term Reference Tree, rather than modifying what Taxonomy currently uses. Term Reference Tree also provides a few new FAPI elements that allow for the correct formatting of the tree (e.g. `checkbox_tree`) - these could possibly be added to core as well.

The solution @bugfolder is proposing would alter/expand the options array structure expected by the FAPI elements. I'm just curious to see if it's possible to make these  changes without breaking stuff in contrib etc.  

One more thought: currently `taxonomy_allowed_values()` is  used by both taxonomy widget types: the select list and the checkboxes/radios. Meaning that this function would need to be aware of the type of widget we are using in order to return the "right" type of `#options` array  structure (either a flat one currently in use, or the one described in @bugfoler's question). Unless we modify the `select` FAPI element to also accept, and basically ignore the additional `#description` and `#attributes` keys in the new `#options` array.

Side note: the current implementation of radios and checkboxes elements already accepts `#attributes` in addition to `#description` as explained by @bugfolder above  - no modification needed for that part...

Side note 2: if we go with @bugfolder's proposal and make it work, I suggest using `#label` instead of `#title`.

**Comment by bugfolder** [comment]
> no modification needed for that part... So, this already works in Backdrop:

Except for my typo (double parenthesis on second description 😉). But, even corrected, it doesn't quite do what I'd like (or at least, what's needed here); it puts the inner class on the `<input>` element, but what would be more useful is to put it on the `<div class="checkbox form-item form-type-checkbox form-item-1-key1">` that wraps the checkbox.

**Comment by argiepiano** [comment]
> At least, my idea is that since passing it as an array is new, only new code would make use of option-list-as-nested-array.

I get that; my questions/reservations, though, are about the function(s) providing the options array to the core widgets (`taxonomy_allowed_values()` or the callback defined in `taxonomy_options_list()`) will be returning the "new" options array (with those new keys). This may break contrib modules that make use of those callbacks.

**Comment by bugfolder** [comment]
Ah, gotcha.

**Comment by bugfolder** [comment]
And looking into this further, it's looking doable with just `hook_field_widget_form_alter()` and some CSS. More soon.

**Comment by bugfolder** [comment]
PR added. It does indentation for checkboxes and radios, but left the select list with dots. Here's what it looks like in LTR and RTL:

![both](https://user-images.githubusercontent.com/29214084/221209203-bfef1f56-6605-4361-90d1-b4726698f9d7.jpg)

Several contrib modules use `taxonomy_allowed_values()` (H/T: @argiepiano) so I added a flag to the function with a default value that matches the historical behavior, which is used by the select list element.

I only created the CSS for depth up to 5, wasn't sure how deep should be accommodated.

**Comment by bugfolder** [comment]
You'll notice in the above that there's slightly less space between the checkbox and the tag in the RTL example (on the right) than in the LTR example (on the left). That's because Seven theme uses margin-right for both LTR and RTL. (It should be using margin-left for RTL.) That also necessitated adding extra CSS to override Seven for RTL, since we needed to override the (erroneous) margin-right to accomplish the indentation.

But I think the proper thing to to is to fix the spacing CSS in Seven, by putting the spacing on the left, using margin-left, for RTL. So I've pushed an edit to the PR that fixes this issue in Seven. This, in turn, allows the CSS in taxonomy module that handles RTL to be much simpler. (Maybe this fix to Seven should be a separate issue, but it seems small enough that perhaps bundling it into this issue is OK.)

**Comment by bugfolder** [comment]
I see @klonos  has reviewed the PR (thanks!) and commented (and I think we've resolved that point). The remaining issue I'd seek feedback on is how deep I should go in creating CSS classes for the indentation. Currently I've done levels 0–5. Is that enough, or should there be more (and if so, how deep)?

**Comment by argiepiano** [comment]
@bugfolder, this is great! Simple, elegant and powerful. 

I left two comments in the PR. As for levels of indentation... 5 seems more than enough for me!

**Comment by bugfolder** [comment]
Comments appreciated and used, PR updated. All tests are passing. Thanks for the review (and comment on depth)! Moving this to needs/needs status for further review/testing as needed.

**Comment by klonos** [comment]
> @bugfolder, this is great! Simple, elegant and powerful.

It is! ...thank you @bugfolder 🙏🏼 ...and thank you @argiepiano for pointing out the narrower hook scope, and the method to load the additional css without completely overwriting any existing css 🙏🏼 

> The remaining issue I'd seek feedback on is how deep I should go in creating CSS classes for the indentation. Currently I've done levels 0–5. Is that enough, or should there be more (and if so, how deep)?

I hadn't checked the comments here nor in the PR till now, because I was so annoyed by that CSS implementation. It's not ideal at all, and very limiting when it comes to depth. To test this, I've created 25 terms, and I've intentionally indented them all one under the other. Most likely a very extreme case, but as expected, it does stop working after you've set the terms deeper than our "predicted" max handling.

I then vaguely remembered a technique I used in the past with `data-*` attributes, and I started experimenting on my local. I thought that if we added `'data-indentation-depth' => $term->depth,` to the attributes of each checkbox/radio, then we could use something like `margin-left: attr(data-indentation-depth em)` in CSS, which would be awesome! ...well, as it turns out, no browser supports that (see [this](https://stackoverflow.com/questions/41618475/performing-calculations-calc-on-data-attributes-in-css-e-g-modulus)  [this](https://stackoverflow.com/questions/8769786/css3s-attr-doesnt-work-in-major-browsers) and other sources) - you can only do such "dynamic" `data-*` attribute manipulations in CSS with `content` (with the `:before` and `:after` selectors). Dang it! 😞

Then my research lead me to [The CSS attr() function got nothin’ on custom properties](https://css-tricks.com/css-attr-function-got-nothin-custom-properties), which concludes to this:

> You know what _can_ pass any sort of value and is equally easy to implement as attributes? CSS custom properties!

Well that worked nicely on my local. Although I still had reservations re using an inline style to pass `$term->depth` to CSS), I was able to add `'style' => '--indentation-depth: ' . $term->depth . 'em',` to the checkbox/radio attributes, and then `margin-left: var(--indentation-depth);` in the CSS. But that basically hardcodes the `em` unit, which we don't want. ...I've tried various things, but it turns out that you cannot concatenate things to CSS custom properties (see [this](https://stackoverflow.com/questions/38336341/css-variables-and-string-concatenation)). Double dang it! 😞

Anyway, I then checked how the indentation is done in core for menus/vocabularies, and they both seem to be adding one or multiple `<div class="indentation">&nbsp;</div>` tags before the element, and then in `core/modules/system/css/system.css` we style the `div.indentation` selector. Can we do that here as well @bugfolder? (try adding this tag before each checkbox/radio as many times as each respective `$term->depth`). I believe that that would allow infinite depth to be handled, and be inline with what we do for the rest of core.

**Comment by bugfolder** [comment]
> Can we do that here as well @bugfolder? (try adding this tag before each checkbox/radio as many times as each respective $term->depth).

So, I first thought about using `#prefix` in the `$options_extra` array, but that puts the prefix before the `<div...>` wrapper, and (as you said) we need it inside that wrapper. So it needs breaking into the rendering of the '`#type' => 'checkbox'` form element.

(Gee, a `#indentation` property in FAPI would be handy here.)

**Comment by bugfolder** [comment]
Ah, `#field_prefix` will do the trick. Coming soon...

**Comment by bugfolder** [comment]
PR revised. I left in the CSS fix for Seven theme spacing, because (with or without this PR) it fixes the spacing for RTL systems for checkboxes and radio buttons, but if folks think that should be a separate bugfix issue, happy to split it off.

**Comment by argiepiano** [comment]
The use of `theme_indentation` is brilliant. I had never seen that before, but I see it's used to create indentations for the menu tabledrag. 

My only concern with the way this is used is that the indentation div now is surrounded by `<span>` (b/c of the `#field_prefix` use). I don't know if this is cause for concern or not. 

Since we are not using an attribute now, I'm wondering if it may be more direct to just act on the `#options` values and add that `div` there, right before the label of each option, instead of using `#field_prefix`.

Something like:

```php
function taxonomy_field_widget_options_buttons_form_alter(&$element, &$form_state, $context) {
  if ($context['field']['type'] == 'taxonomy_term_reference') {
    foreach ($context['field']['settings']['allowed_values'] as $tree) {
      if ($vocabulary = taxonomy_vocabulary_load($tree['vocabulary'])) {
        if ($terms = taxonomy_get_tree($vocabulary->machine_name, $tree['parent'])) {
          foreach ($terms as $term) {
            $element['#options'][$term->tid] = theme('indentation', array('size' => $term->depth)) . $term->name;
          }
        }
      }
    }
  }
}
```

This is a simpler way, but I don't know if it may mess up other things (like translations). I see that `menu` does this in a similar way, prepending the divs right before the title of the menu ([see line 72 of menu.theme.inc](https://github.com/backdrop/backdrop/blob/1.x/core/modules/menu/menu.theme.inc#L72))

I'm not really sure if this is a better approach, but just putting it out there for consideration.

**Comment by argiepiano** [comment]
One other issue with the current approach @bugfolder:

Before the patch:
<img width="175" alt="Screen Shot 2023-02-25 at 9 23 36 AM" src="https://user-images.githubusercontent.com/9938978/221368001-f7d9dda8-94b7-4ac2-83f6-34f6a709a603.png">

After the patch:
<img width="166" alt="Screen Shot 2023-02-25 at 9 23 52 AM" src="https://user-images.githubusercontent.com/9938978/221368013-919d6df8-3590-4e3f-bc29-3d1c8dbf87c6.png">

Notice the missing `N/A` that core provides for these widgets.

**Comment by klonos** [comment]
I have to say that I'm starting to like this issue more that I thought ...a) because it's a great UI/UX improvement, but also b) for all the things I'm learning ...some of them are great, some of them show how much things suck (because of technical dept there's in Drupal/Backdrop/HTML and CSS specs/Browser support etc.) ...but the good thing is that I see people's resourcefulness to solve these issues. Oh these lovely rabbit holes! 😅 

...and of course I love the tag-teaming that's going on in this issue as well.

**Comment by bugfolder** [comment]
@argiepiano, your point about sanitization (or lack thereof) is super-important, thanks! Unfortunately, `_options_get_options()` already adds the default mid-dots. (I'd originally thought about just stripping off the mid-dots from the beginning of the existing options, but someone, somewhere, is going to create a term name that starts with a mid-dot.)

But I think I have an approach.

**Comment by argiepiano** [comment]
@bugfolder adding dots to the options themselves bothers me. This is a theming aspect of the options, yet it's not done in the theming layer. I may be opening a huge can of worms here, but wouldn't it make more sense to somehow modify the element handlers and/or theming functions for radios and checkboxes to either add the dots, or add the divs? Perhaps by adding a parameter to the radio / checkbox FAPI element?

This way this thematic modification is delayed until the theming stage, AND people can modify it (e.g. using a different character instead of the dots).

**Comment by bugfolder** [comment]
> Perhaps by adding a parameter to the radio / checkbox FAPI element?

Oh yeah, I totally agree; hence my comment above about wishing for a `#indentation` FAPI property!

I do like your new approach (although I went with something modified). I doubt that adding the `<span>`s would mess up the translation any more than core's current practice of adding dots.

**Comment by bugfolder** [comment]
New PR. I still used the values of `taxonomy_allowed_values()` so that the choice of using the term name remains in that function, rather than in two places. But I added sanitization. (Is `check_plain()` the right one in this circumstance?)

**Comment by klonos** [comment]
> ...the way core adds dots to the options themselves bothers me.

Yeah, I don't think that anyone is a huge fan of that. It's been a while since I've been 👀 this (for our menu parent selector as well): https://jsfiddle.net/TrilceAC/7fhqL38m (uses nested radio buttons instead of a select + a tiny 1-liner JS)

**Comment by argiepiano** [comment]
@bugfolder, thanks for the changes! 

I believe there is a pretty straightforward way to add the `#indentation` FAPI property for radios and checkboxes that doesn't break things and is backward compatible. 

I've experimented with this and it works well in my testing. It involves adding another theme wrapper to `#theme_wrappers` for elements `radio` and `checkbox`. Also involves keeping your approach almost intact, but instead of adding the indentation to the values of the `#options` array in the widget alter hook, we would add the `#indentation` property to the "extras" that you had before.

Would it be OK if I submitted a pull request against yours (directly to your repo), and you can take a look? 

The benefit of having this done this way is that the indentation functionality will be available to all radio and checkbox elements, and will be easy to theme it, e.g. by extending the new wrapper function.

**Comment by bugfolder** [comment]
> Would it be OK if I submitted a pull request against yours (directly to your repo), and you can take a look?

Sure.

**Comment by argiepiano** [comment]
@bugfolder, I'm working on #5999. While working there I realized that the PR here assumes that the option values will always be available at `$field['settings']['allowed_values']`. That's not always the case. It's possible to use `$field['settings']['options_list_callback']` to obtain the option values for the widget.

So, this is getting complicated - and the main culprit is the fact that those dots are added so deep in the process, instead of adding them during the theming of the widget. Hopefully #5999 will help some...

**Comment by argiepiano** [comment]
@bugfolder, I've submitted a PR for #5999. It added indentations for `radios`, `checkboxes` and `select` (although with select, the indentation is accomplished by adding dots.

So, please take a look. That PR will make it possible to modify `taxonomy_allowed_values` to remove those darn dots from there, now that the indentation has been moved to the theming layer.

But, we will still need to alter the widget, in order to populate the new `#indentations` FAPI property.

**Comment by bugfolder** [comment]
https://github.com/backdrop/backdrop-issues/issues/5999 looks great! I will update this PR to make use of it (and to account for `options_list_callback` per the above).

But I raise the question of whether it's safe to modify `taxonomy_allowed_values()`, if other code is depending on the presence of the dots.

Core only uses `taxonomy_allowed_values()` in `taxonomy_options_list()` (implementation of `hook_options_list()`), so that looks OK.

Here's a GH search through contrib: https://github.com/search?q=org%3Abackdrop-contrib+taxonomy_allowed_values&type=Code

These are the modules that use `taxonomy_allowed_values()`:

* https://github.com/backdrop-contrib/feeds
* https://github.com/backdrop-contrib/geshifilter (no releases yet)
* https://github.com/backdrop-contrib/title (no releases yet)
* https://github.com/backdrop-contrib/taxonomy_access

Taxonomy Access is just filtering `taxonomy_allowed_values()`, so that will be OK.
For Feeds, it's creating targets for mapping to taxonomy terms, so it would seem that behavior would actually be improved if feed sources didn't have to include the mid-dots! But this definitely changes behavior.

So what do you think, @argiepiano and @klonos? Can we go ahead and drop the dots from `taxonomy_allowed_values()`?

**Comment by argiepiano** [comment]
To me, this level of change (basically a visual change that doesn't affect functionality: moving the widget's individual taxonomy term theming to the theming layer, where it belongs) is acceptable.   The fact that it wouldn't affect the current contrib modules using `taxonomy_allowed_values()` is also significant, and further justification for this change.

**Comment by jenlampton** [comment]
> Can we go ahead and drop the dots from taxonomy_allowed_values()?

What does it look like without the dots for feeds? Can people still see the indentation clearly? If so then I'd say yes, let's drop the dots.

**Comment by bugfolder** [comment]
>  If we can create an alternative PR with no dots, I would be happy to test it and post a screenshot

I've removed the dots from `taxonomy_allowed_values()` in the current PR but haven't yet added `#indentation` where needed. (That would need the PR from #5999 to be applied in order to have any effect.) Meanwhile, @jenlampton, can you test whether this change breaks Feeds import/export of taxonomy terms? (I see that Feeds has its own tests, but trying to run them emits an error "Class 'FeedsMapperTestCase' not found," which I think is unrelated.)

**Comment by bugfolder** [comment]
PR now updated to use `#indentation`. Apply PR https://github.com/backdrop/backdrop/pull/4364.diff from #5999 to test.

**Comment by klonos** [comment]
@bugfolder I am getting the following error repeated twice, and no indentation:

> - Notice: Undefined index: option_list_callback in taxonomy_field_widget_options_buttons_form_alter() (line 1861 of /var/lib/tugboat/core/modules/taxonomy/taxonomy.module).
> - Notice: Undefined index: option_list_callback in taxonomy_field_widget_options_buttons_form_alter() (line 1861 of /var/lib/tugboat/core/modules/taxonomy/taxonomy.module).

Steps:
1. install Devel and enable devel_generate
2. generate a few terms for the "Tags" vocabulary (I generated 25)
3. edit the "Tags" vocabulary, and rearrange the generated terms so that there's multiple indentations with various depths
4. add a taxonomy reference filed to any content type, and set the widget to "Check boxes/radio buttons"
5. Save -> error 👎🏼 

Setting up your PR on my local to play with things.

**Comment by bugfolder** [comment]
>  I am getting the following error repeated twice,

Fixed, a misplace parenthesis. Rebased the PR so it's not necessary to patch with 4364.diff.

**Comment by klonos** [comment]
Thanks @bugfolder 🙏🏼 ...looks good in general, but:
- the nesting breaks after level 6 (as expected - limited by the CSS classes we've added in #5999)
- there is no nesting and no middots when I switch the widget to a select with a single value allowed
- there is no nesting when the widget is set to a multi-select

Those things might or might not be easy to fix, but we are definitely in a good path, and the DX is much better with #5999, as it requires fewer code changes to implement this now.

Still need to play with this on my local.

**Comment by klonos** [comment]
@bugfolder please see this PR against yours that fixes the missing indentation/middots when the widget is set to a select (single or multi): https://github.com/bugfolder/backdrop/pull/7

The cause was that your PR had only an implementation of `hook_field_widget_WIDGET_TYPE_form_alter()` for widgets of type `options_buttons` - I've added another one for `options_select`.

Since both hook implementations are doing the exact same thing, I've added a new helper function `_taxonomy_field_widget_options_process()`, which I am calling from both. For the name of the helper function, I initially thought to call it `_taxonomy_field_widget_options_add_indentation()`, but `*_process` makes it less wordy, and is generic enough to leave room for other processing that we may need to do in the future.

So now the only issue that remains to figure out is how to handle more (infinite?) depths, without using dozens of CSS classes. That may need to be a follow-up issue thought, as it has nothing to do with this here - it is a limitation of how we've implemented things in #5999.

**Comment by klonos** [comment]
...now that I think about it, perhaps what I did was silly, and we should use a single implementation of `hook_field_widget_form_alter()` instead of multiple implementations of `hook_field_widget_WIDGET_TYPE_form_alter()` 🤔

**Comment by bugfolder** [comment]
Looks good, @klonos, thanks! Main PR updated.

**Comment by klonos** [comment]
Pinging @argiepiano re test/review since you worked on #5999 (I can't since I have provided part of the code).

**Comment by bugfolder** [comment]
I know we need 3rd-party review, but I'll note that I checked the post-klonos PR with checkboxes, radios, and selects, and also both LTR and RTL.

**Comment by argiepiano** [comment]
Tested, reviewed, LGTM and RTBC! Thanks for your patience, @bugfolder and @klonos!

**Comment by klonos** [comment]
> I've added a milestone - minor tag. Can someone add the actual milestone?

We need an advocate for this are you advocating for any other feature @argiepiano or @bugfolder ?

**Comment by klonos** [comment]
> That's not the same as it being assigned to me, right?

Right. You just need to represent and summarize progress for this during the weekly meetings.

We usually edit the original post (or issue summary) and the advocate name there.

**Comment by bugfolder** [comment]
Since all the work is done on this one (I hope!), sign me up!

**Comment by klonos** [comment]
Nice! ...the sooner this gets merged, the sooner we can have you be advocating for another feature then 😉 

PS: I am changing this to a task, since it is basically implementing something based on another thing that got merged into core, with the latter being the actual feature. The milestone still needs to remain 1.25.0, since the feature we depend on (#5999) was only merged into 1.x, slated for the next minor release.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/4382 into 1.x for 1.25.0. Thanks @bugfolder, @argiepiano, and @klonos!
