### ISSUE TITLE
[UX] make block delete action a form button (not a tab)

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3299]
## Describe your issue or idea
When managing blocks, there is no "delete" button on configure block form. Instead, there is a tab at the top of the page. This is a strange UX pattern. I'd prefer to see the a delete button on the configure form.

### Steps to reproduce (if reporting a bug)

* Configure an existing reusable custom block. 
* Try to figure out how to delete it.

### Actual behavior (if reporting a bug)

* Find a menu tab

### Expected behavior (if reporting a bug)

* Find a delete button

---
PR: https://github.com/backdrop/backdrop/pull/2603

**Comment by stpaultim** [comment]
@arjunk2004 

This is what I understand for this issue.
1) Go here: admin/structure/block
2) Create a test block and save it - just add test data
3) Go back to here: /admin/structure/block and click "configure"
4) Now you are on a page to edit an existing block. It is my understanding that the user is confused, because they expect to see a delete button near the bottom of this page rather than that Delete tab at the top. 

The button at the bottom would be more standard.

**Comment by arjunk2004** [comment]
Okay, that makes sense. Thank you!
I'll try and figure that out

**Comment by arjunk2004** [comment]
Issue https://github.com/backdrop/backdrop-issues/issues/2265 is related and I thought it was a valid issue.

**Comment by stpaultim** [comment]
Just tested. This looks like it does as expected when editing a block. However, the delete button is now available on the block add form, before the block even exists. I think this is a problem. This button should only show up on the edit form.

![Add_custom_block___PR_2603_backdrop_backdrop_testing_site](https://user-images.githubusercontent.com/3144571/56463294-cc93e700-6396-11e9-8dd1-c2ef2c9198a3.png)

**Comment by jenlampton** [comment]
Nice catch @stpaultim!

**Comment by arjunk2004** [comment]
I will work on a fix for that... I'm just going to figure out how to do some stuff.
Thank you for testing that and catching it pretty quickly @stpaultim!

**Comment by arjunk2004** [comment]
I changed the code a bit, it should work now, it works for me at least...

**Comment by stpaultim** [comment]
I tested the PR = http://2603.backdrop.backdrop.qa.backdropcms.org/node/1/edit

I created a new custom block and did NOT see any delete button on the new block creation form. Once I created the block, I clicked on the "configure" link and found a delete button at the bottom of the page, near the "Save Block" button as expected. 

I clicked on the delete button and the subsequent confirmation and my block was in fact deleted. 

I am not reviewing the code, because that's not my thing. :-)

**Comment by herbdool** [comment]
Code looks good. The element type of link matches that of the node edit form. I assume it doesn't use element type of button because it needs to identify it as a secondary button?

**Comment by klonos** [comment]
Yep, looks and works good 👍 ...proposing 1.12.7 for milestone.

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/2603 into 1.x and 1.12.x. Thanks (and welcome again!) @arjunk2004 for your work on this. This will be in 1.12.7 and 1.13.0.

Thanks @stpaultim. @herbdool, and @klonos for the reviews!
