### ISSUE TITLE
Global dropdown field in Views strips token from query

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#3306]
## Describe your issue or idea

The global dropdown field in Views strips the token from the URL parameters. It's supposed to have a &token=...

### Steps to reproduce (if reporting a bug)

Create a view of comments. Add the "approve link" for comments. Add the global dropdown field and include the approve link.

### Actual behavior (if reporting a bug)

The approve link on its own includes a token at the end of the URL but in the global dropdown there is no token in the URL.

### Expected behavior (if reporting a bug)

The dropdown field should include everything in the URL.

---
PR by @herbdool: https://github.com/backdrop/backdrop/pull/2314

**Comment by herbdool** [comment]
Actually the problem is in class `views_handler_field_links` which only has option to include destination and  has no way to include anything else in the URL query.

**Comment by laryn** [comment]
I tested this on the sandbox and the PR allows the token to remain on the approve URL for comments as intended.

**Comment by quicksketch** [comment]
Can we automatically determine which paths require a token and which ones do not? If certain pages (like /comment/x/approve) _always_ require a token while other pages _never_ require them, it seems that we're asking a question of administrators that we shouldn't have to. I'm also concerned that `backdrop_get_token($path)` won't work reliably for paths that do require tokens.

This also seems like an idea area where test coverage is lacking.

A completely different approach rather than modifying this in views is to modify it using `hook_url_outbound_alter()`, capture when `comment/x/approve' is about to be output and then assign the `token` attribute if it is missing. That could be an easy way that any module could ensure tokens were present if required.

**Comment by herbdool** [comment]
I've taken @quicksketch suggested approach of using `hook_url_outbound_alter()` and I've added it to the main PR https://github.com/backdrop/backdrop/pull/2313. So I'm closing this issue and PR.
