### ISSUE TITLE
Color Module loading base theme CSS instead of child theme CSS

### ISSUE THREAD

**Issue by sethlbrown** [backdrop/backdrop-issues#3341]
Base theme is Basis (color enabled), have a sub theme that is overriding skin.css. Changes to skin.css aren't showing up, and skin.css from my sub theme does not seem to be loaded at all.

What is loading is:  /files/color/basis-6e8e97c7/skin.css?ph6hq8

Wes thinks that color module is overriding base theme's css and completely ignoring the child CSS.

**Comment by stpaultim** [comment]
I am having this same problem. Here is what I think is happening right now, based upon my current experimentation. 

1) When you install a theme with the color module, the theme uses the css provided by default in the theme.

2) Once you make any changes with the color module, the color module creates a new set of CSS files in the files directory (files/color/temp-directory/). Once these files exist, Backdrop CMS loads these css files instead of the files in theme/css. At this point, any changes you make to the original css files in your theme no longer have any immediate effect. Clearing the cache does not help. 

3) If you delete the css in files/color/temp-directory your site looses all styling until you make any changes in with the color module at which point a new set of CSS is generated.

**Comment by stpaultim** [comment]
Based upon my last set of comments, I am not sure if this is a bug or works as designed. The problem is simply that one can not use the default CSS files in ones theme when using the color module. One might argue that it is a best practice to create custom files for all overrides anyway. 

Is there anything we can do to better document this process to help future themers avoid this confusion.
