### ISSUE TITLE
SA-CORE-2013-002 - Denial of service

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#34]
## Security fix in [Drupal 7.20] (https://drupal.org/drupal-7.20-release-notes)

Drupal 7 decided that on-demand image generation was a security problem, and implemented a solution that involved adding a query string to the end of generated images.  This broke many contrib modules that inserted derived images into content, and the like.

I propose that we take a second look at the threat (is it real or perceived?) and come to a more sensible solution that breaks less of contrib - if possible.

### Denial of service

Drupal core's Image module allows for the on-demand generation of image derivatives. This capability can be abused by requesting a large number of new derivatives which can fill up the server disk space, and which can cause a very high CPU load. Either of these effects may lead to the site becoming unavailable or unresponsive.

For reference, here is the [notice on drupal.org] (https://drupal.org/SA-CORE-2013-002)

**Comment by quicksketch** [comment]
I'm going to take a stab at solving this problem in what I hope is a sane manner:

- Fix the exploit of recursive paths being allowed in image styles. That's an obvious fix with no downside.
- Introduce flood protection for *anonymous image generation* and set it to a modest limit (say 5 images at a time).
- Leverage calls to `image_style_url()` to detect authorized image generation. Keep a list of all requested URLs, which are considered whitelisted.
- When generating an image, check if it's in the whitelist. If it is, allow the image generation unconditionally. If the image is not in the whitelist, use one of the available anonymous image generation slots. If no slots are available, return a 403 Access Denied.
- Keep the whitelist trim by removing the image from the list after it is generated, or after the whitelist entry expires from tempstore.

This gets us a balance of security and convenience. Completely unauthorized image style generation is highly throttled by default, while loading a page with 50 images at once is considered okay and all of them will be generated ASAP. As almost all image styles are run through image_style_url(), most images will get whitelisted and act just like they do today. The throttled behavior is a fallback for situations such as an inline image in the body of a node, which is less common and unlikely to occur en masse.

**Comment by quicksketch** [comment]
Initial PR filed at https://github.com/backdrop/backdrop/pull/635.

Here's the performance impact rundown on the changes:

- If a page is requested and all images for that page already exist, there is one `is_file()` call per image style image. Although is_file() checks have been the source of criticism, the actual impact is almost always negligible because of the combination of PHP's stat cache, OS caches, and disk caches. Unless you're running NFSv3, in which case you're going to have a lot more problems than image styles.
- If any image style images are not yet generated, 2 additional SQL queries (one read and one write) and a lock request are made at the end of the page request.
- During image generation, 2 additional SQL queries are made. If unauthorized, up to 5 lock requests are made.

The overall impact is negligible. On my localhost with 10 front-page images, the page request time is increased by about 1ms. Each image check itself is about 0.01ms, so a page with 100 images wouldn't be impacted much more than one with 10.

Image generation is slightly slowed checking for locks, but it's going to be negligible compared to the cost of the image manipulation itself.

I'm overall happy with this result. It's a solution that's more compatible with CDNs than the Drupal 7.20 approach and is more convenient while not being dangerous.

**Comment by quicksketch** [comment]
Here's the XHProf results:

![image-style-flood-xhprof](https://cloud.githubusercontent.com/assets/100206/5608220/3ca71f1a-9431-11e4-84ae-62f0bf0f9c45.png)

This is for 10 images displayed on the homepage. Resulting in an increase of about 4ms of CPU time and 12kb memory increase.

**Comment by quicksketch** [comment]
I merged in https://github.com/backdrop/backdrop/issues/635 to address this before our initial release.

**Comment by jenlampton** [comment]
RAWK

**Comment by quicksketch** [comment]
- [x] Denial of service (double-checked)
