### ISSUE TITLE
Installation fails for v1.11.0 - v1.11.3 on MAMP

### ISSUE THREAD

**Issue by VladimirAus** [backdrop/backdrop-issues#3429]
* Downloaded v1.11.3
* Using MAMP with PHP 7.1.22 and MySQL 5.7.23

After passing database details in installation screen I get 

```
ParseError: syntax error, unexpected '=>' (T_DOUBLE_ARROW) in backdrop_install_config_directories() (line 17 of /projects/backdrop.local/settings.php).
```

And  the following in `settings.php`

```
...
$database = 'mysql://xxx:xxx@127.0.0.1/backdrop_xxx';
$database_prefix = '';
  'default' => '',
);
...
```

Confirmed on 2 different machines.

**Comment by laryn** [comment]
@VladimirAus Can you check if it's similar to this one (and if the PR here works for you?)
https://github.com/backdrop/backdrop-issues/issues/3223

**Comment by jenlampton** [comment]
I've read through both issues, and it does appear that this is the same as the issue reported in https://github.com/backdrop/backdrop-issues/issues/3223. Thanks for submitting the error report @VladimirAus! 

If you have the time, it would be great to report if the Pull Request at https://github.com/backdrop/backdrop/pull/2350 fixes the issue for you, too. That PR was slated for the 1.11.3 release but just missed it. The good news is that 1.11.4 should be out in a week or two since there's so much bug-fixing going on right now!

**Comment by klonos** [comment]
Hey @VladimirAus I really enjoyed your talk in the recent DrupalSouth. Thanks for that 👍

...I guess my email re giving Backdrop a go since you compared other CMSes might have something to do with you filing this bug report. I hope that this has not put you off from giving Backdrop a go. As @jenlampton said, the fix for this will be in the next 1.11.4 bug fix release, but perhaps you'd want to hold off till Jan 15 and give the 1.12 release a spin 😉

For a list of new feature going in for 1.12, you can have a look [here](https://github.com/backdrop/backdrop-issues/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed+milestone%3A1.12.0).

**Comment by VladimirAus** [comment]
No worries @klonos 
I recently gave a talk about Backdrop at Brisbane Drupal meetup as well.

Although developers have no issues fixing settings file, couple of my clients tried Backdrop and couldn't get pass the installation and not keen on trying it again :/

**Comment by klonos** [comment]
Sorry to hear that @VladimirAus, but bad timing I guess. FWIW, as I mentioned in my previous comment, this bug is fixed now.
