### ISSUE TITLE
Enable manual self-updates on new sites

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3453]
This is a follow-up to https://github.com/backdrop/backdrop-issues/issues/3271, and will set the default value for allowing self-updates to TRUE. This will be a requirement for automatic updates. 

---
~~PR: https://github.com/backdrop/backdrop/pull/2441~~
PR: https://github.com/backdrop/backdrop/pull/2612

**Comment by quicksketch** [comment]
I think the current PR isn't the right one. Looks like it removes an update hook, rather than adding one.

**Comment by jenlampton** [comment]
> Looks like it removes an update hook, rather than adding one.

That's correct. All sites already have the correct value for that variable, so no update is necessary.

**Comment by jenlampton** [comment]
Okay, trying this again. New PR up for review: https://github.com/backdrop/backdrop/pull/2612

**Comment by klonos** [comment]
The code change is trivial, and the PR sandbox has the setting enabled, so RTBC 👍 

Do we need an update hook for this? That would be changing the current behavior of already installed sites. Not a bad thing, since this is not the auto-updates setting.

**Comment by jenlampton** [comment]
I was thinking: no update hook. Not sure we want to change a value people
have already decided against.

**Comment by klonos** [comment]
RTBC then. @quicksketch or anyone else, please feel free to kick back to NW if you think that we should change that setting for existing sites.

**Comment by quicksketch** [comment]
Thanks! During the 1.12.x cycle we've definitely proven this functionality works. And when it doesn't (due to permissions usually), it doesn't affect the site negatively, it just throws an error saying it couldn't modify the files. That part definitely has room for improvement, but doesn't block us from enabling this option for new sites. 

I don't think we should modify this setting on existing sites, since we have no way of identifying a site-owner's preference. Though really maybe this shouldn't be an option at all in the future. It's either "Allow updates" or not, for everything (both core and contrib). The risk and benefit to your site is equal for both kinds of updates.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2612 into 1.x for 1.13.0.
