### ISSUE TITLE
Backdrop 1.12.3 release

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3547]
Backdrop 1.12.3
==================================

## Pre-release tasks

- [x] Merge commits @quicksketch
- [x] Create a new bugfix release @quicksketch
- [x] Create the next bugfix milestone @klonos 
- [x] Move all unfinished issues to the next bugfix release milestone @klonos 
- [x] Draft Release notes @jenlampton
  - [x] Short, descriptive summary of the release
  - [x] Note if any changes were made to files outside the `core` directory
  - [x] Note if updates (update.php) needs to be run
  - [x] Include changelog since last version (generated with drush rn)

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch 
- [x] Tag for release, and push tag to GitHub @quicksketch
- [x] Revert version number back @quicksketch
- [x] Create release notes on GitHub @jenlampton 
- [x] Update the front page download link on b.org @klonos  
- [x] Tweet that a new release is out @jenlampton 
- [x] Mark the release as a security release if that is the case @klonos 

## Post-release tasks

- [ ] Push the bug-fix release to the [Pantheon Backdrop repository](https://github.com/backdrop-ops/backdrop-pantheon) @quicksketch
- [x] Push the bug-fix release to the [Platform.sh Backdrop repository](https://github.com/platformsh/platformsh-example-backdrop) @jenlampton 
- [x] Push the bug-fix release to the [Docker Backdrop repository](https://github.com/docker-library/official-images/blob/master/library/backdrop) @jenlampton 
- [ ] Push the bug-fix release to the [TugBoat Backdrop repository](https://github.com/backdrop-ops/backdrop-tugboat) @quicksketch 
- [x] Close the previous milestone @klonos
- [ ] Update the Wikipedia articles @klonos 
  - [ ] https://en.wikipedia.org/wiki/Backdrop_CMS
  - [ ] https://en.wikipedia.org/wiki/List_of_content_management_systems

**Comment by jenlampton** [comment]
* Issue for Platform: [Update Backdrop CMS to version 1.12.3](https://github.com/platformsh/platformsh-example-backdrop/issues/12)
* Issue for Docker: [Update Backdrop CMS to version 1.12.3](https://github.com/backdrop-ops/backdrop-docker/issues/36)

**Comment by quicksketch** [comment]
Tag is cut: https://github.com/backdrop/backdrop/releases/tag/1.12.3

**Comment by jenlampton** [comment]
Release notes:
---

This release fixes security vulnerabilities. Sites are urged to upgrade immediately after reading the notes below and the security announcement: [Backdrop core - Critical - Remote Code Execution - SA-CORE-2019-003](https://backdropcms.org/security/backdrop-sa-core-2019-003)

**Update information**
- The database update script does **not** need to be run.
- No changes have been made to the .htaccess, robots.txt or default settings.php files in this release, so upgrading custom versions of those files is not necessary.

**Other Changes since 1.12.2:**
*  Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3512">#3512</a>: Test that array index '#type' is set in form_process_actions().

**Comment by jenlampton** [comment]
Tweet sent: https://twitter.com/backdropcms/status/1098326658715512833

**Comment by jenlampton** [comment]
Docker image PR testing now: https://github.com/docker-library/official-images/pull/5424

**Comment by BWPanda** [comment]
I'm assuming we can close this now...
