### ISSUE TITLE
Formatting options: flickering fieldset expand/collapse animation

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3596]
This is a follow-up to #3516...

When expanding/collapsing the fieldset, there is this subtle "jump" in the animation, which doesn't happen when expanding/collapsing other, "regular" form fieldsets.

**Comment by olafgrabienski** [comment]
Confirmed, I also see this "jump" (tested on Mac OS X, Firefox).

**Comment by klonos** [comment]
Thanks for confirming @olafgrabienski 👍 ...my testing was on Chrome/Mac

**Comment by jenlampton** [comment]
no PR. Removing milestone.

**Comment by klonos** [comment]
Found this which may help: https://ricostacruz.com/jquery.transit

**Comment by indigoxela** [comment]
> When expanding/collapsing the fieldset, there is this subtle "jump" in the animation

I also came across this jump while working on an otherwise unrelated issue: #4342

Reason for this jump is Backdrop.collapseScrollIntoView in file core/misc/collapse.js

This is very old code. A generic js function is available to accomplish the same with way less effort: [scrollIntoView](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView)

This function also has a parameter `behavior: smooth` which does a soft scroll. But... older browsers don't support that yet:

https://caniuse.com/scrollintoview

However: it might be that even if the old buddies don't support the smooth scrolling, scrollIntoView might already be an improvement. It's less jumpy OOTB.

Any interest here to try that out? Or is support for "smooth" in all browsers a must?

**Comment by laryn** [comment]
If `scrollIntoView` is less jumpty OOTB and even better on most, I support using it here.

**Comment by indigoxela** [comment]
A [PR](https://github.com/backdrop/backdrop/pull/3853) is available for testing.

In particular we need Safari and Internet Explorer 11 users to do a check if fieldset animations are better or worse than before.

In Firefox and Chrome they're for sure smoother.

To check, you need to either find a large (collapsed) fieldset or resize the browser window, so the expanded fieldset would end up (partly) outside the viewport. Then expand it.

**Comment by docwilmot** [comment]
Definitely smoother (Chrome). 

And no worse in IE 11, probably better (no scroll, but without this PR there's a bit of a strange stutter jump, which "improves" to one jump with the PR)

**Comment by indigoxela** [comment]
I ripped out a little too much before :wink:, so I had to restore optimizedResize to trigger resizing of initially small dialogs. Nothing changed with the scrollIntoView usage, though.

@olafgrabienski maybe you want to test with Safari and possibly on IOS?

**Comment by olafgrabienski** [comment]
> maybe you want to test with Safari and possibly on IOS?

Sure! Here my impressions, tested with expanded fieldset outside of the viewport:

- Firefox on Mac OS: super smooth
- Safari on Mac OS: not as smooth as Firefox but better than without the PR
- Safari on iOS: behaves generally different than a notebook or desktop browser (no page jump); no difference between PR sandbox and a vanilla demo site

**Comment by klonos** [comment]
I just tried it on Safari on Mac OS, and I could not notice any difference. ...which is a good thing 😅

**Comment by herbdool** [comment]
I think people have tested all the popular browsers, plus IE 11 which is on the way out. The code looks good. Marking this as RTBC.

**Comment by laryn** [comment]
Thanks for reporting @klonos, and for the fix that helps modernize some of the aging code @indigoxela! Thanks for testing and review @herbdool, @docwilmot, and @olafgrabienski. Merged https://github.com/backdrop/backdrop/pull/3853 into 1.x and 1.20.x.
