### ISSUE TITLE
[UX] Contextual links for teaser block views covered by contextual links for nodes

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3615]
**Description of the bug**
While working on https://github.com/backdrop/backdrop-issues/issues/2690, we noticed that contextual links (for blocks!) are also missing for block displays - but only when the view is displaying 'content' instead of 'fields'.

This is because there is no padding on block wrappers, so the "node" overlaps the "block" and therefore the node contextual links cover up the block contextual links, making them inaccessable.

**Steps To Reproduce**
To reproduce the behavior:
1. Go to the default home page in Basis
2. Attempt to configure either the promoted view, or the promoted block via contextual links.

**Actual behavior**
Only the content's contextual links are visible.

**Expected behavior**
Both the block and the content should have visible contextual links.

**Additional information**
In Drupal 7, the inner most contextual links were slid a little bit to the left, allowing the outer contextual links to peek through. We should adopt the same behavior in Backdrop.

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2545
Alternate (JS) PR by @BWPanda: https://github.com/backdrop/backdrop/pull/3227

**Comment by klonos** [comment]
Hey @jenlampton good catch 👍 ...the contextual links for article teasers and the one for the views block are indeed overlapping. I initially wondered why the contextual cog icon for the 1st article teaser persisted when I hovered away from the 1st teaser, and over the second and third teasers ...because that was not the contextual cog for the article teaser; it was the one for the view.block 😄 🙄 Thanks for figuring that out; it's been bugging me for so long and it now seems so trivial.

> In Drupal 7, the inner most contextual links were slid a little bit to the left, allowing the outer contextual links to peek through. We should adopt the same behavior in Backdrop.

Hmm, I am not a CSS guru, but google has not helped when I searched for "css target deepest class"; every solution I found seemed to suggest using jQuery. Besides, I have tried to mock with the `right:` property in the browser inspector, and it seems that aligning the contextual cog icons for the `.block` wrapper and the first `.node` wrapper next to each other (by sliding the inner one to the left) makes it look odd:

<img width="555" alt="Screen Shot 2019-03-24 at 11 55 03 am" src="https://user-images.githubusercontent.com/2423362/54873513-ceb46580-4e2b-11e9-9153-ab08542e7f8e.png">

> This is because there is no padding on block wrappers, so the "node" overlaps the "block" and therefore the node contextual links cover up the block contextual links, making them inaccessable.

Yes, I have found that adding a padding seems to place the outer-most contextual cog icon above and to the left of the first `.node` wrapper, which IMO looks and works better (conveys some visual "nesting"):

<img width="545" alt="Screen Shot 2019-03-24 at 11 55 36 am" src="https://user-images.githubusercontent.com/2423362/54873523-e2f86280-4e2b-11e9-870c-7f83573c6e26.png">

Adding a padding to the views block (`.block-views-promoted-block`) fixes things, but we need to target the views block specifically, otherwise other blocks get that padding (menu blocks, the logo block, the footer block etc.). Here's what I have thought of and tested:

- The `.block-views-promoted-block` class is specific to that view, so adding the padding there will not solve this problem for all views-generated blocks 😞 
- CSS unfortunately does not support parent selectors, so we cannot target `.view-content` and then go "up" the DOM 😞 
- The other classes added to views blocks (`.block` and `.contextual-links-region`) are too generic, so will also affect other elements, thus should be used either 😞
- We could add a `.view-block` to all views-generated blocks (similar to how we are adding a `.view-content`) and target that, but why add more classes when we don't need to. Right?
- We could use [substring-matching (or "partial") selectors](https://stackoverflow.com/questions/3338680/is-there-a-css-selector-by-class-prefix), like `div[class^="block-views-"], div[class*=" block-views-"] { padding: ... }`. These seem to be supported by IE7+ and other modern browsers, but we are not using them anywhere else in core. I am assuming that there must be a very good reason 😄 😞 
- Adding the padding to the `.block-content .view-content` class works, and so does adding it to `.block-content .view`, but are they a good place to add the padding to, and if so, then which one of the 2 is best?
    
Lastly, where do we add this CSS too? The spacing between the view contextual cog icon and the first view item might not be ideal in all themes (depending on other styling choices made). Nevertheless, I think that we should not be adding it to Basis theme only, because other themes are affected by this.

So options:

- `/core/modules/contextual/css/contextual.css` this makes sense in that we are making this change in order to fix a problem with contextual links (although all selectors in that file start with `.contextual-`, while this one will be `.block-content [something]`, which seems odd). It also makes it so that the padding is only added when the contextual module is enabled (some people do not like contextual links). Do we want this?
- `/core/modules/views/css/views.css` this is the opposite/alternative of the above option. Depends on what the answer is for that 😄

I have filed a PR and for now have gone with `.block-content .view-content` as the selector, in `/core/modules/contextual/css/contextual.css`, and a `10px` padding. Let me know if more/less padding is required, or if things need to be moved elsewhere, or if I have missed any alternative solution that might be a better option for this problem.

**Comment by klonos** [comment]
...here's how this looks in Basis and Bartik:

<img width="1161" alt="Screen Shot 2019-03-24 at 11 33 58 am" src="https://user-images.githubusercontent.com/2423362/54873573-d9bbc580-4e2c-11e9-8fe8-c2a688a33ab9.png">

<img width="949" alt="Screen Shot 2019-03-24 at 11 33 10 am" src="https://user-images.githubusercontent.com/2423362/54873572-d9bbc580-4e2c-11e9-824c-783c625b9c50.png">

**Comment by klonos** [comment]
...here's a thought: when creating many promoted nodes, if you need to edit the view while scrolled to the very bottom of the page, you need to scroll back up to the first item to reach the "container" contextual link menu, which is not ideal UX. How about if we merged the "Configure view" and "Configure block" contextual options into the contextual options for each view item? That way, we'd eliminate this overlapping issue + improve UX (less/no scrolling to edit the view that renders the item currently within the user viewport):

<img width="995" alt="Screen Shot 2019-03-24 at 12 13 08 pm" src="https://user-images.githubusercontent.com/2423362/54873645-92363900-4e2e-11e9-9947-9e61726fd497.png">

Perhaps separate issue 😄

**Comment by jenlampton** [comment]
Here's a thought: How about when we hover over a contextual link, we also
add a border around the area the link affects? That would make it clear
which link is for the view, and which was for the node.

Re moving views links to node links: I dislike this idea. Not all views use
view modes and we'd be creating inconsistency between different views. I'd
rather have it always be in the same place for all views.

**Comment by klonos** [comment]
> Here's a thought: How about when we hover over a contextual link, we also add a border around the area the link affects?

We already do that:

<img width="547" alt="Screen Shot 2019-03-24 at 9 14 25 pm" src="https://user-images.githubusercontent.com/2423362/54877976-ec102080-4e79-11e9-9b9e-09675329e308.png">

> Not all views use view modes and we'd be creating inconsistency between different views. I'd rather have it always be in the same place for all views.

Fair enough. I can see how this would complicate things.

It would be great if the contextual cog icon was always positioned within the viewport, instead of it being permanently at the very top-right of the area/element it provides links for. The point being that the user should not have to scroll up in cases of large areas in order to find the contextual menu.

**Comment by jenlampton** [comment]
I don't think floating wheels would be an improvement... you'd never know
what you were editing! The context for the editable-thing is provided,
mostly, by the title. I'd rather have to scroll, but know what I'm editing,
then never know what was in the cog wheels. It gets even crazier with
nested editable-things wheels, like in this example with views and blocks.

**Comment by jenlampton** [comment]
I don't think we can add padding to the front-end like this because we will be affecting everyone's themes. It would be safer to move the cog wheel with javascript if we can detect circumstances where there would be an overlap. Marking as NW.

**Comment by BWPanda** [comment]
Here's a PR https://github.com/backdrop/backdrop/pull/3227

And a screencast:
![Peek 2020-08-10 16-49](https://user-images.githubusercontent.com/2385329/89757758-87ff0280-db29-11ea-847c-fd2ca54f8b48.gif)

It works on the homepage, but I'm not sure where else this happens in order to know if it fixes all scenarios...

**Comment by BWPanda** [comment]
The JS I used is this: `$wrapper.siblings().find('.contextual-links-wrapper').eq(0).css('margin-top', '20px');`

To explain: it looks for any contextual link wrappers (`$wrapper`), then looks in each of its sibling elements (i.e. the elements for which its providing the links). Within each sibling, it looks for any other contextual links wrappers (`find('.contextual-links-wrapper')`), chooses the first one only (`eq(0)`)*, then adds a top margin to it.

* Without this part, all child contextual links would be pushed down 20px, which looks a bit weird for the second post for example:
![image](https://user-images.githubusercontent.com/2385329/89758059-3e62e780-db2a-11ea-97df-6576b59546e4.png)

**Comment by stpaultim** [comment]
As an advocate for the issue that triggered this one (it was one of my biggest pet peeves), I can't believe that I haven't noticed this problem. 

I've tested the solution and it works for me.

**Comment by herbdool** [comment]
Code looks good. One unrelated test failure

**Comment by BWPanda** [comment]
Thanks everyone involved in making this happen; especially @jenlampton, @klonos, @stpaultim & @herbdool! I've merged https://github.com/backdrop/backdrop/pull/3227 into1.x and 1.16.x.
