### ISSUE TITLE
[UX] Allow the "Book outline" vertical tab in the content create/edit form to be hidden from users with the "Administer book outlines" permission

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#3638]
**Description of the need**
This is a long standing confusion. In Drupal there are multiple issues for this: 

- https://www.drupal.org/project/drupal/issues/502430
- https://www.drupal.org/project/drupal/issues/848470
- https://www.drupal.org/project/drupal/issues/2862291

The first issue describes it well:

> It is somewhat disconcerting to users who have the 'administer book outlines' permission to see the 'outline' tab and 'outline' fieldset on every single node type, regardless of whether that node type has been configured to be allowed in books. I can see a use-case where that might be a desired feature, but i think its probably relatively rare.

Note, that book module seems to be the oddball here. If you disable menus for a content type not even user 1 has ability to add them to a menu from within the content type.

**Proposed solution**

Create an additional checkbox in the `content/book/settings` form that when checked allows book outlines for any content type, not just the designated book-types. By default this is checked to be backwards-compatible, so that any current sites that might rely on "seeing outline information on all content types regardless of config settings" won't be broken by this after upgrading. Unchecked it will mean that nobody will see the outline tab on every content type.

**Advocate:** @herbdool

**Comment by klonos** [comment]
Thanks for raising this issue @herbdool 👍 ...I find this to be a UX bug actually, so I have updated the issue title and label accordingly.

I quickly mocked up these 2 suggestions (in both of them, I've changed the "Content type for child pages" setting to a drop-down select, instead of the current radio set. It's a simple one-line change, simply does not make sense otherwise, and it becomes a UX issue in sites with a big amount of content types)...

1. Separate checkbox form element, with help text added/updated for both the new checkbox, as well as the existing set of options:

    <img width="643" alt="Screen Shot 2020-01-05 at 9 33 08 pm" src="https://user-images.githubusercontent.com/2423362/71778786-57407300-3006-11ea-9065-8a29c6c84f51.png">

2. Additional "special" option in the existing set of options, with help text added specifically to it, to explain that this only applies to users with a specific permission:

    <img width="673" alt="Screen Shot 2020-01-05 at 9 52 50 pm" src="https://user-images.githubusercontent.com/2423362/71778804-940c6a00-3006-11ea-90ec-f3db98928daa.png">

I'm happy to go either way, but in general, I find the current behaviour annoying. I would prefer it if we fixed this by:

- Removing the current functionality, so that the "Administer book outlines" permission does not have this "special" behavior. If we want to keep this feature (which I think we should **not**), then we should introduce a separate "Bypass content type restrictions for book outlines" permission for it.
- Adding a generic "Allow all content types" checkbox.
- If the above checkbox is unticked, then a list of content types is shown to choose from.
- Add a per-content-type setting for this option.

**Comment by herbdool** [comment]
@klonos I like the dropdown.

Thinking now, based on this comment https://www.drupal.org/project/drupal/issues/502430#comment-12284751 that perhaps it should be a new permission rather than another checkbox on the book settings:

> Also, the current behavior is a documented feature - I can see the rationale for wanting to change it, but am not sure yet-another-setting-in-the-admin-UI is a great way to do it. Splitting out a new permission along the lines of "add any content to books" (as discussed in #30 above) sounds like a better solution - yes, there are some backwards compatibility concerns with that, but relatively minor (there probably isn't too much contrib/custom code out there that interfaces with this part of the Book module, and mostly the concern would be broken links).

**Comment by herbdool** [comment]
@klonos I am also wondering if we should remove the book outline tab entirely and just have the vertical tab when editing. They have exactly the same functionality.

**Comment by stpaultim** [comment]
I agree with the goals of this proposal. I read through the first Drupal issue and while some folks are calling this a feature, no one is really arguing that the current behavior is good. 

With an out of the box editor role, this might be a little less serious of a problem, because it's easy to give editors permissions that make sense, but I see how this could be a problem and don't see any reason to not make this better (along with the other positive changes we've made to the book module).

**Comment by schoenid** [comment]
Well I see the similarity to my bug report [#5626](https://github.com/backdrop/backdrop-issues/issues/5626#issuecomment-1133586739)

But what I mention, is the risk or the problem for 0815-users, causing an unpredictable behaviour on using books together with other content, which may become invalid, if assigned to books. I see my bug report not as "feature request", but as request to handle a bug with a high risk for users.

**Comment by herbdool** [comment]
@schoenid you'll need to explain how someone could recreate your steps to confirm if it's a bug. We can't guarantee that core will work with all contrib modules. I don't know what you're using for "groups" but it doesn't sound like a core module.

**Comment by stpaultim** [comment]
I think that part of the problem here are these two contradictory statements. 

1) Content types allowed in book outlines
2) Users with the Administer book outlines permission can add all content types.

Read very literally, if a content type is not allowed in a book, then why is possible for someone who administers book outlines to add that content to a book. 

A simple text improvement would be to clarify this a bit.

1) Content types that users without "Administer book outlines" permission may add to books outlines
OR
2) Change the permission from "Administer book outlines" to "Add any content to book outlines"
OR 
3) Add a new permission

![image](https://user-images.githubusercontent.com/3144571/169673574-4e624c52-07f4-4818-9cd6-3466b43c09ca.png)

**Comment by schoenid** [comment]
> I don't know what you're using for "groups" but it doesn't sound like a core module.

The ["Organic Groups"](https://github.com/backdrop-contrib/og) module.
A group is just a special type of content.

---

Please have a look to my bug report [#5626](https://github.com/backdrop/backdrop-issues/issues/5626#issuecomment-1133586739) and the problems I've reported to consider a solution:

- For Non-Administrators the horizontal "OUTLINE" tab is not visible, but the vertical "Book outline" tab.

... This makes in my eyes no sense: either both or none ...

- A user, which has no rights to administer book outlines, has the ability, to use the "Book outline" tab, which allows him to add content to a book, which is not allowed.

- A Non-Administrator is able to add any content to a book outline, but is not able, to remove it from the book outline.

**Comment by schoenid** [comment]
> I think that part of the problem here are these two contradictory statements.
> 
> 1. Content types allowed in book outlines
> 2. Users with the Administer book outlines permission can add all content types.
> 
> Read very literally, if a content type is not allowed in a book, then why is possible for someone who administers book outlines to add that content to a book.

Again: just to clarify.

The description or statements deviates from reality. 

- Not only users with the Administer book outlines permission can add all content types, but all users with the create and edit permission (which is not covered in the description).

**Comment by herbdool** [comment]
I've added a PR https://github.com/backdrop/backdrop/pull/4101 as per @klonos' first suggestion.

![2022-06-22 14 19 34 bd1 lndo site d69379419019](https://user-images.githubusercontent.com/1071483/175108762-0b39b81a-f323-4925-a372-57a5533f4047.png)

I enabled it by default for backwards compatibility, though I'm open to disabling it by default given that this usually confuses people.

**Comment by quicksketch** [comment]
Nice, thanks @herbdool. Could we clarify the first checkbox's label to indicate it's admin-only? I find it confusing that without the descriptions, the two different fields seem like they're in direct conflict with each other.

Something like "Allow admins to use all content types in book outlines" with the description "Overrides the specific content type list and allows all content types for user accounts with the _Administer book outlines_ permission."

It would be nice if this admin override setting were below "Content types allowed in book outlines", but then we run into the single checkbox following a list of checkboxes issue; they look related.

And for both descriptions, we try to avoid "users" and specify either "people" if referring to the human or "user account" if referring to the characteristics of their account. So just add "Affects user **accounts** with the ..."

**Comment by herbdool** [comment]
@quicksketch changes made, tests passing

**Comment by stpaultim** [comment]
Current PR:

![image](https://github.com/user-attachments/assets/ee29fed6-93f9-43ba-840d-53d3b2bf77f6)

Was hoping I could offer a suggestion for making the help text shorter, but made it longer instead. I don't know that this is an improvement. It just adds `book module` to actually make info more specific. Just a thought. 

`Overrides the specific content type list for book module and allows all content types for user accounts with the Administer book outlines permission.`

Looking at this now, I would like a little help text to clarify "Content type for child pages", but that may be out of scope for this PR.

In case your are interested, I think "Content type used for child pages" might actually be enough. I think that as I look at that setting, it's not clear to me that I am selecting the content type that will be used when I create a new child page. Adding the word "used" seems a little helpful to me. 

Again, this is not urgent and could be looked at later, but I thought I would mention it.

**Comment by quicksketch** [comment]
PR looks acceptable to me. If anyone has concrete improvements for verbiage, or has an idea for improving the UI, please make suggestions.

As it is though, I think this increasing the complexity of this UI is worth the trade-off of simplifying the UI and preventing a lot more confusion when creating nodes of any type while Book module is enabled.

I would be in favor of setting `book_admin_allowed_all` to 0 on new installs, while existing sites keep the current behavior (as done by the update hook already).

**Comment by herbdool** [comment]
@quicksketch thanks. I've switched it like you suggested. I'm happy to reduce that confusion on new sites.

**Comment by quicksketch** [comment]
Code looks good, I would appreciate another QA review, maybe @stpaultim or @schoenid?

**Comment by stpaultim** [comment]
Doing another test now!

**Comment by stpaultim** [comment]
I think I've given it a pretty good test, including testing how the editor roles interacts with these settings with and without permissions. I can think of some other possible improvements, but I think they are outside the scope of this issue. I will open new issues. 

I'll give this a WFM!

**Comment by quicksketch** [comment]
Thanks @herbdool for picking this one up again! I merged https://github.com/backdrop/backdrop/pull/4101 into 1.x for 1.30.0. Nice!
