### ISSUE TITLE
[DX] settings.php: Improve the documentation of settings.local.php

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3673]
This is to incorporate some of the wording included in https://git.drupalcode.org/project/drupal/commit/9ba8724

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2578

**Comment by herbdool** [comment]
RTBC

**Comment by quicksketch** [comment]
Thanks! Merged https://github.com/backdrop/backdrop/pull/2578 but only into 1.x because we have to note in each release if there are changes to settings.php or other files outside the core directory. Only putting into 1.13 means we don't have to have bugfix versions that modify settings.php, increasing the chance of merge conflicts.
