### ISSUE TITLE
Layouts: Add support for custom contexts

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3750]
For example make a context for node ID 1, completely separate from the path.
Part of #345

Summary:

If you add a context to a Layout, this is data that the layout will be able to make available to the blocks on this layout. Certain blocks may actually require this data to be available or they wont show. For example, you create a block that you want to show the picture of the user whose profile you are viewing. You can add a `Visibility condition`, but the block will still show up in the block list when you're configuring or creating any layout. Or you can add a `required context` in the block's definition in code, then that block will only show up in the block list for layouts that have the User Context applied.

Prior to this PR, the user context would only be available on pages where the path had a wildcard representing a user, like on a `user/%` page, or a path `anypath/%` where you selected `User` context from path on the layout config page. User blocks would be available in the block list on such layouts. Any fields on the user entity would be available as blocks on that layout. The User object that the blocks received would be whichever user ID whose page was being viewed. So a block on `user/2` would only have info from user with UID 2.

This PR allows you to add specific contexts to any layout. So path "anypath/mypath" could have a context for User 5, or any other user. User blocks would show up in that layout, even though it's not a user path. A block on that layout would have info only on user 5. All the Field Blocks from User 5 would be available on that layout.

Context for any entity can be added to a layout in similar ways. A context for Node 26 added to a layout would make all the Field Blocks from Node 26 be available on that layout.

---
PR by @docwilmot: https://github.com/backdrop/backdrop/pull/3120
PR by @quicksketch (built on top of above PR): https://github.com/backdrop/backdrop/pull/3271

**Comment by docwilmot** [comment]
@quicksketch @jenlampton I wanted to start on [relationships](https://github.com/backdrop/backdrop-issues/issues/2134) but though would be best to do this issue first, to devise a clear way to store both contexts and relationships (which are a kind of context) in config. But hit a snag discussed [in Zulip](https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/oop/near/193565122).

Essentially, in Layouts abstract class `LayoutContext` does not extend the `LayoutHandler` class, unlike other handlers, because contexts are not stored in config. Well, now we're aiming to make contexts store in config. So what are the implications of changing `LayoutContext` to extend `LayoutHandler` at this stage? 

The Zulip convo essentially said: API change. So I'm ceasing and desisting till we can decide how this can go forward.

We could save contexts in config without extending the class, but that would mean two similar APIs for handlers to save to config. I think.

Would love your opinions.

**Comment by docwilmot** [comment]
First try
- `LayoutContext` now extends the `LayoutHandler` class. No obvious side-effects on local.
- there is now an "Add context" link on Layout configure pages (`/admin/structure/layouts/manage/layout-name/configure` except for Default layout, which is not configurable that way.)
- if you add a node context for node 2, for example, to a Layout, then field blocks become available on that Layout (because there is now an available Node context) regardless of the path of your Layout. Note previously field blocks would only show up if your path was like `ENTITY_TYPE/%` or `node/%` becasue that was the only way to add an entity context. If you added now a field block for node body field, the body of node 2 would show up on the page.
- however, this is currently not very extensible; any entity will be available to create a context, but there is no API to add other types of context apart from entity contexts. CTools had query string contexts, and node form context etc. 
- for now, if you create a new type of context, via `hook_context_info()` this will show in the select list, the `CONTEXT::form()` would show, and values would save, but the method of displaying the added context in the context table is now hardcoded to entities. I havent figured out a way to make this generic.
- just realised `Dashboard` shows up as a context on the sandbox, will need to figure this out.

**Comment by docwilmot** [comment]
This is working quite OK now, would be grateful for some testing.

**Comment by klonos** [comment]
I did a "light" review, but I need to get my head around contexts vs visibility conditions (in an end-user/UX context). My concern is that we may be exposing dev concepts in the UI, hence complicating things for novice end users 🤔

**Comment by klonos** [comment]
...I was re-reading this:

> if you add a node context for node 2, for example, to a Layout, then field blocks become available on that Layout (because there is now an available Node context) regardless of the path of your Layout. Note previously field blocks would only show up if your path was like `ENTITY_TYPE/%` or `node/%` becasue that was the only way to add an entity context. If you added now a field block for node body field, the body of node 2 would show up on the page.

...and it got me thinking that this is another case of developers building the UI in an inside-out way, exposing things that the end user should not know about, assuming that this is common knowledge. So I think that the entire way of thinking here is the opposite of what it should be: it assumes knowledge of contexts, node IDs, the fact that certain field blocks will become available once a specific context becomes available, etc., whereas I would expect that the UI would be providing options of what the desired end result is, and then "work its magic" in the background (I would go as far as saying that anything related to contexts would be hidden behind an "advanced settings" section or something).

In other words, we currently have this workflow where we assume that people creating layouts are advanced developers or site builders, with knowledge of the "building blocks" required to reach the end result, which for the sake of an example is to be able to add field blocks in a layout. So:

-> Assume that the user knows that allowing content field blocks requires the `node/%` or the `ENTITY_TYPE/%` context.
-> Have them add that context in the layout they are creating/editing (via a UI that is confusing for a novice user).
-> When the user saves the form, they must imagine/assume that the effect of what they have just done is to be allowing field blocks in the layout (there is no obvious visual indication with regards to that in the form they just saved).

All the above is "developer magic"; whereas I would expect things to work in this (over-simplified) way:

-> Present a series of various block options as a select list. This list should have a title that end users understand, like "Select what blocks are available within this layout".
-> One of the options is "Content field blocks".
-> User ticks the "Content field blocks" checkbox and saves the form.
-> Backdrop figures out what contexts are required, and adds them to the layout*.
-> Advanced users can navigate to a "Manage contexts" section, where they can tweak things that make no sense to novice users.

Am I dreaming?

*I fully understand that this bit is tricky - we cannot possibly read people's minds and magically work out what they intent to be doing. But that's why there'll also be an advanced section, which will allow "manual" context configuration.

**Comment by docwilmot** [comment]
Do in followup? For now we already have contexts, this PR just builds on that, I'd just like to know if the code and testing works TBH.

I'll admit though that the context table should be hidden completely unless the user adds a context, as it is in current 1.15; I need to restore this behaviour.

**Comment by klonos** [comment]
> Do in followup?

Agreed 👍

**Comment by olafgrabienski** [comment]
> would be grateful for some testing

Would love to play around with the PR's sandbox site, but I'm not quite sure about the scope of the issue, or what to test.

**Comment by docwilmot** [comment]
> Would love to play around with the PR's sandbox site, but I'm not quite sure about the scope of the issue, or what to test.

😄 
Sorry, not clear it seems. 
Really the concept of a "context" really means making blocks available on a layout. If a layout has a `node/3` context, all the fields on Node number 3 would be available to add to that layout. 

So, to test, create a node, add some content in the body and/or image or any other field. Save. Say this ends up being Node 3, after you save. This will be your source of field blocks.

Now create a layout with a random path (`olaf/isgreat` for example), then add a context for Node, and type in NID 3 (note I just remembered that the autocomplete isnt working yet, so please just type the NID, dont try to autocomplete). Then go to the add block page of your new  layout. You will notice that although this isnt a `node/%` page, the field blocks are still available. Add the Body (and/or whatever field) block to your layout. Save. 

Go to path `olaf/isgreat` and see that the body (or image or whatever field) of Node 3 will be visible at that path.

You can do the same for other entity types. Add fields to user/term entities, create a user/term as a source for blocks, then add a context for that user/term to your new layout. You can use the same layout and add multiple contexts. So blocks from Node 3, 4, 5 and blocks from User 2, 3, 4, etc all can be available to that layout.

Final caveat, I also just realised that my last commits made the sandbox tests red again after being all green, so this is assuming I havent completely broken it. It was all green yesterday. 😢

**Comment by olafgrabienski** [comment]
Thanks for the explanation, sounds like a pretty awesome feature! At first sight it didn't work for me in the sandbox site, but that was because I tried it with autocomplete (which itself works but lead to an error later on).

Here's what I did first:

- created the post `posts/test-post-a` with body text, image etc.
- added a test layout (path: `test/layout/a`, context to `posts/test-post-a`)
  (autocomplete worked when typing the node title)
- visited `test/layout/a`, result: empty page (apart from header and footer, as expected)
- added body field block to the *Content* region of the layout
  (tried also other fields and other regions)
- visited `test/layout/a` again, result: HTTP ERROR 500
- removed field from layout
- visited `test/layout/a` another time, result: empty page, as above and expected

Second try:

- removed the above mentioned context `posts/test-post-a`
- added new context to (node) `3`
- added some field blocks to various regions of the layout
- visited `test/layout/a` again, result: fields are there, great!!

Additional:

- added title block to the layout => doesn't appear on `test/layout/a` (probably as expected but limiting use cases pretty much)
- added user context to the layout => didn't find user related blocks in the block placement dialog
- noted the (new?) *Menu settings* link on the *Layout* overview page, and put the layout in the primary menu => 👍

**Comment by olafgrabienski** [comment]
> I also just realised that my last commits made the sandbox tests red again

Maybe related and helpful: there are some PHP notices on the DBlog page of the sandbox website.

**Comment by herbdool** [comment]
This is complex to review. I didn't dive too deeply to figure out what is all going on so I probably missed some things. 

I'm also wondering if we need to expand tests to account for this change.

**Comment by docwilmot** [comment]
I think this is ready for review. Will add a summary at the top.

**Comment by indigoxela** [comment]
Seems like the sandbox needs a refresh. I get a WSOD when trying to log in.

**Comment by docwilmot** [comment]
@olafgrabienski @herbdool @klonos care for another round of reviews?

**Comment by olafgrabienski** [comment]
@docwilmot I've had another look at the sandbox. In comparison of my last try, the autocomplete issue is fixed but some issues remain.

What works:

- created the post `posts/test-post-a` with body text, image etc.
- added a test layout (path: `test/layout/a`, context to Node ID 3
- added some field blocks of the layout
- visited `test/layout/a`: fields are displayed 👍 

Doesn't work / Limitations:

- When I enable "Display the current page title as the last breadcrumb" on the breadcrumb block in the layout, the title doesn't appear in the breadcrumb. Same with the default page title and when I add a title block to the layout, the title doesn't appear. Is it an expected behavior because the title isn't a field? It's however irritating and limiting use cases pretty much.
- I've added an additional user context (User account ID 1) to the layout but didn't find user related blocks in the block placement dialog.

**Comment by docwilmot** [comment]
@olafgrabienski 
- Breadcrumb block works fine for me. 
- The page title doesnt appear if you create a random path even without this PR, 
- And are you sure you added fields to the user before you tested, because it works for me.

**Comment by olafgrabienski** [comment]
> - Breadcrumb block works fine for me.

The block itself works but "the current page title as the last breadcrumb" (enabled in block settings) is missing. I get an empty span instead:
```
<ol>
  <li><a href="/">Home</a></li>
  <li><span></span></li>
</ol>
```

> - The page title doesnt appear if you create a random path even without this PR

Got it. But doesn't this PR arouse use cases where you expect to have the node title available?


> - And are you sure you added fields to the user before you tested

Oh no, I didn't think of adding fields, thanks for the hint! (Had tried other information as Username and Picture, but I guess they're not available for the same reason as node titles.)

**Comment by docwilmot** [comment]
I think I understand your point. You're expecting that the page title of a context node will be available as a title block or a breadcrumb option. That isn't the case, since page title isn't a field.

**Comment by olafgrabienski** [comment]
> That isn't the case, since page title isn't a field.

I see! What would be the use case of custom contexts when important data like node titles or let's say user names and user pictures aren't available? Or do you see a chance to tie non-field data to custom contexts in a follow-up?

**Comment by docwilmot** [comment]
Contexts simply make the data available to blocks on the layout. Its up to developers to code blocks that use the info. Field blocks are already coded to use context data. 

Title blocks, not yet.

In the case of titles, the layout title component has an option "Copy from block"; one could probably code an option to "Copy from node" and give a select lists of Node contexts available on the Layout, for example. Same could probably be done for the Title Block.

I suppose context might be hard to fully grasp. I did a [summary in the original post](https://github.com/backdrop/backdrop-issues/issues/3750#issue-439842072) last week. Have a look, hope it helps.

**Comment by docwilmot** [comment]
Could I get a milestone for this please, to get it on a reviewer's radar? I'll self-advocate since it seems unclear to most.

**Comment by herbdool** [comment]
I'm going to review this, hopefully get it ready for merging soon.

**Comment by klonos** [comment]
I realize that this sounds like a very important feature, but I still cannot get my head around it 😓 (not anyone's fault - it's me). Perhaps it's because I cannot imagine any real-life use cases for this at this point. I just see that I've been asked to review, and did not want to leave the impression that I don't care.

**Comment by herbdool** [comment]
@docwilmot I looked through the code. Nothing stood out to me as an issue but I'll give it a deeper look once more.

I get the general approach here of allowing other entities as being added as context to a layout. And I think it's okay that a first iteration doesn't have an autocomplete for the entity id.

Though in my testing I can't figure out why @olafgrabienski testing isn't showing the field he added for the user. With the current sandbox there is a test post http://3120.backdrop.backdrop.qa.backdropcms.org/posts/test-post-a and the layout has contexts for a node and a user. 

![Screenshot from 2020-07-15 11-43-45](https://user-images.githubusercontent.com/1071483/87566058-780e1300-c690-11ea-89be-6fdc77409e6e.png)

layout blocks:

![Screenshot from 2020-07-15 11-39-40](https://user-images.githubusercontent.com/1071483/87566004-66c50680-c690-11ea-8297-f75a35214bd7.png)

The node fields display fine but not the user fields.

![Screenshot from 2020-07-15 11-51-36](https://user-images.githubusercontent.com/1071483/87567171-fcad6100-c691-11ea-8436-a4fc6ac5dc45.png)

I would expect the "about" field on the user to also show up here. But I don't see anything. I wonder if this is an existing issue unrelated to this PR. When I switch the block to use the current user context and also remove the user 1 context the field still doesn't show up.

**Comment by stpaultim** [comment]
I did very minimal testing on this PR and didn't run into any technical problems. The basics worked for me. The biggest problem with this PR is conceptual/usability and I'm hoping to offer some thoughts on that. 

1) I've long thought that field blocks are a hidden treasure in Backdrop CMS. Super valuable, but easily missed or not noticed if one doesn't know they are there. As I understand it, field blocks are a form of "contexts" that we already have in core. I'm hoping that as we implement this feature it mades fields blocks easier to find and understand as well. I think that my suggested text does that. 

2) The title "contexts" means nothing to me or to the average site builder. We need to work on terminology. My initial thought was something like "contextual data" or something that better describes what is happening. What this feature does is make field information from specific entities/users/nodes/terms available as blocks to any layout. How about calling this feature "Contextual field blocks."

3) Change the help text (here is a suggestion to get us started, not sure if this is really accurate). 

FROM:
`Make specific field blocks available to this layout from a specific node, user, term, or entity. Adding a wildcard to the layout path also exposes field blocks appropriate to the context. `

TO
`Make specific field blocks available to this layout from a specific node, user, term, or entity. Adding a wildcard to the layout path also exposes field blocks appropriate to the context. `

(Optional) Contexts define what blocks are available within this layout. Most wildcards in the path will be associated with a context automatically.

![Lions___PR_3120_backdrop_backdrop_testing_site](https://user-images.githubusercontent.com/3144571/87866270-33f76880-c945-11ea-9ed9-210f77c0d029.png)

**Comment by jenlampton** [comment]
> As I understand it, field blocks are a form of "contexts" that we already have in core.

Not exactly. There are blocks that will only appear in the block list if their required context is available. Field blocks require a fieldable entity, so a `node`, `user`, or `term` context must be present for them to appear. The contexts we have in core are `node`, `user`, and `term`.

> I'm hoping that as we implement this feature it mades fields blocks easier to find and understand as well. 

All this feature does is make it possible for you to attach an existing context to a layout. Before this change, the only way to get a layout with a context was to place it on a path where the context is added automatically by core, so on `node/%`, `user/%`, or `taxonomy/term/%`.

> The title "contexts" means nothing to me or to the average site builder. We need to work on terminology.

`Context` is the correct word to use for the concept. People who know nothing about building websites would guess correctly about the definition, which is better than we can say for most of the other language we use for abstract concepts in core :) 

I am strongly against changing the word **context** -- but I am all in favor of changing how we explain how contexts relate to website development, and Backdrop layouts in particular.

We also need to be careful here because we might accidentally end up breaking all the existing knowledge of everyone coming from Drupal.

> What this feature does is make field information from specific entities/users/nodes/terms available as blocks to any layout. 

Not exactly. It makes all things that require the context available. Blocks are only one example of a `thing` that requires a context, and `field information` is only one example of a `block` that requires the context. 

A visibility condition is another example of a `thing` that might require a specific context. The condition for node type, for example, is only available when a node context is present.

In Panels-land, these `things` were called `plugins`.

> Change the help text

Yes please :) This is something that we really need to improve. Contexts are confusing and how they relate to building websites is even more confusing. Anything we can do to help that along would be a big improvement -- but it should happen in another issue so that it won't block this change from getting in.

**Comment by stpaultim** [comment]
Well, I think I need to sit this issue out, because just when I thought I was understanding this issue, I'm back to thinking I have no idea what is happening here - after several lengthly attempts to explain it to me and after experimenting with the PR. I'd rather not confuse this issue any further, so I'll anxiously watch and see how things go.

> People who know nothing about building websites would guess correctly about the definition

Well I thought I had an intuitive idea of what this means, but apparently I don't understand this feature at all.

**Comment by jenlampton** [comment]
@stpaultim I think you are still right that the UI needs some work, but I'm sure we can work on that in a separate issue. I also think you're close to understanding it, and maybe with a few more real-world examples you can help us find a way to make it clearer to everyone else :) I'll see if I can find some better examples we can all play with.

**Comment by klonos** [comment]
> Yes please :) This is something that we really need to improve. Contexts are confusing and how they relate to building websites is even more confusing. Anything we can do to help that along would be a big improvement -- but it should happen in another issue so that it won't block this change from getting in. 

Done: #4496 😉 ...I've created that as a documentation task, and collected all the comments from here and Zulip that I found useful. Lets' use all of that to produce some documentation and examples. We can link to that documentation from the help text in the layout edit form.

**Comment by klonos** [comment]
> I also think you're close to understanding it, and maybe with a few more real-world examples you can help us find a way to make it clearer to everyone else :) I'll see if I can find some better examples we can all play with.

I'm on the same boat 😅 ...trying to get my head around what contexts are exactly, and how they work. I believe that the common ground here is that I have never used Panels with Drupal before; for people that have, it seems to be common knowledge.

**Comment by quicksketch** [comment]
I posted another review to https://github.com/backdrop/backdrop/pull/3120#pullrequestreview-473048985

In using this functionality, it behaves exactly as I would expect. I can add a context to a fixed-path layout and have corresponding blocks become available.

![Selection_221](https://user-images.githubusercontent.com/100206/90990434-38233100-e556-11ea-8b03-d49122101b61.png)
![Selection_220](https://user-images.githubusercontent.com/100206/90990438-3e191200-e556-11ea-829c-fd811feae97b.png)

I particularly like the additional display of the matching node title or user name in the select list to make it clear which entity is being used, rather than just "ID: 10".

The one big hang-up I have is that this causes an API change in the `load callback` used for contexts. Besides the API change, the new approach necessitates wrappers for all of our existing load functions just to convert them from an array to a single value:

```
/**
 * Callback function to load node context.
 */
function layout_context_node_load(array $settings) {
  return node_load($settings['id']);
}

/**
 * Callback function to load user context.
 */
function layout_context_user_load(array $settings) {
  return user_load($settings['id']);
}
```

I posted some thoughts on how we might avoid these wrappers and the API change in the [code review](https://github.com/backdrop/backdrop/pull/3120#pullrequestreview-473048985).

**Comment by quicksketch** [comment]
@docwilmot I filed a new PR that adds one commit to make the "load callback" backwards-compatible. Can you take a look at https://github.com/backdrop/backdrop/pull/3271 (the last commit) and see what you think?

**Comment by docwilmot** [comment]
That looks like it solves problems. 

But still concerned about argument order as you mentioned [here](https://github.com/backdrop/backdrop/pull/3120#pullrequestreview-450182919). Context would be reading from a config file; can we be sure the file `key => value` pairs would always be converted to array in the same order with any system or version of PHP? Or  what if users decide to manually edit settings? They'd probably expect having the correct keys would be enough, not the order of the pairs. That would be an unusual requirement for config file data.

Maybe add a new `load argument order` to `hook_layout_context_info()` that lists the load function arguments in the correct order, then we can reference that to build the final array for `call_user_func_array()`?

Or is there any way to get the argument order of a function before you call it?

**Comment by quicksketch** [comment]
> Or is there any way to get the argument order of a function before you call it?

Yeah, we _can_ do that with PHP's Reflection API: https://www.php.net/manual/en/reflectionfunctionabstract.getparameters.php But I'm not much a fan of that sort of magic mapping where the name of the parameter has meaning outside of the function.

>  can we be sure the file key => value pairs would always be converted to array in the same order with any system or version of PHP?

As far as I've seen, this is always consistent across all versions of Backdrop (and Drupal), where it comes in the same as the POST order. Though if needed, I think a context handler could add an additional submit handler to rearrange the values.

> Maybe add a new `load argument order` to hook_layout_context_info() that lists the load function arguments in the correct order, then we can reference that to build the final array for call_user_func_array()?

If we need a solution for the load order and ensuring it comes in the right order, this would be the preferred approach for me. This would make it similar to [`hook_menu()`](https://api.backdropcms.org/api/backdrop/core%21modules%21system%21system.api.php/function/hook_menu/1) Where we have `page arguments` and `load arguments` that determines what gets passed into the callbacks. But it's not exactly an identical situation.

**Comment by herbdool** [comment]
I've reviewed the code change that @quicksketch made. Makes sense to me. (I had previously reviewed the rest of the PR). I haven't tested.

**Comment by docwilmot** [comment]
@herbdool any thoughts on the concerns here https://github.com/backdrop/backdrop-issues/issues/3750#issuecomment-683366850? We'll be asking devs to be rigid about the order of data in a config file, a new thing. For now we dont have any contrib or core `load callback`s except the existing entity load functions so maybe this shouldnt really hold up the issue. I think we could make a followup and/or wait till a real world problem actually surfaces.

**Comment by herbdool** [comment]
@docwilmot yes, I think we make it a follow-up if any issues surface.

**Comment by herbdool** [comment]
I've tested @quicksketch PR now too. It works as expected

**Comment by quicksketch** [comment]
Thanks @herbdool! I merged https://github.com/backdrop/backdrop/pull/3271 to get this completed before feature freeze tonight. At this point we only have `load callback`s that take a single argument in all cases. Once we get into contrib or advanced contexts, we'll see if argument ordering is helpful to add as well.

HUUUUUGE props to @docwilmot for taking on this massive effort to master one of the most complicated parts of Layouts and open us up to more possibilities in the Layout system.

And thanks to continuous drivers like @stpaultim, @olafgrabienski, @klonos, and @herbdool!
