### ISSUE TITLE
Shouldn't taxonomy_get_vocabularies() be deprecated?

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#3756]
[`taxonomy_vocabulary_get_names()`](https://api.backdropcms.org/api/backdrop/core%21modules%21taxonomy%21taxonomy.module/function/taxonomy_vocabulary_get_names/1) is deprecated, saying:

> This function previously queried the database for a list of vocabulary names, but now is unnecessary as vocabulary names are stored exclusively in configuration. The return value is compatible with that of loading the full vocabularies through taxonomy_vocabulary_load_multiple().

The code for this function, less the deprecated watchdog call, is simply:
```php
return taxonomy_vocabulary_load_multiple(FALSE);
```

[`taxonomy_get_vocabularies()`](https://api.backdropcms.org/api/backdrop/core%21modules%21taxonomy%21taxonomy.module/function/taxonomy_get_vocabularies/1) is not deprecated, and yet it's code is also simply:
```php
return taxonomy_vocabulary_load_multiple(FALSE);
```

So shouldn't `taxonomy_get_vocabularies()` be deprecated as well?

**Comment by klonos** [comment]
...what is happening is that both these functions now are literally the same (minus the call to `watchdog_deprecated_function()`). We could deprecate both over `taxonomy_vocabulary_load_multiple()`, but it would be for different reasons. One would be deprecated because we do not query the db any more, and the other because it seems to simply be a wrapper function around `taxonomy_vocabulary_load_multiple()`.

**Comment by BWPanda** [comment]
Ok, I think I understand this now.
