### ISSUE TITLE
Move node actions into node.actions.inc file

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3807]
I just noticed today that all the user actions are nicely organized in a `user.actions.inc` file, but the node actions are still burried in `node.module`. It would be nice to separate these for both performance and sanity.

--

PR by @isabelhaas : https://github.com/backdrop/backdrop/pull/2702

**Comment by laryn** [comment]
Sandbox is down -- @isabelhaas can you close and then reopen the PR?

**Comment by jenlampton** [comment]
I tried to get us a new one, see: https://github.com/backdrop/backdrop/pull/2702

**Comment by docwilmot** [comment]
I'm marking this RTBC because the code is fine and works. Theres just one tiny extra two line breaks.

**Comment by quicksketch** [comment]
Thanks @isabelhaas and @docwilmot! I've merged https://github.com/backdrop/backdrop/pull/2702 into 1.x for 1.16.0. Thanks @jenlampton for filing the issue.

I've only merged this into 1.x for 1.16.0 since it's not a bug that's being fixed and sometimes the addition of new files can trip people up in bug fix releases (e.g. forgetting to `git add` the new files).
