### ISSUE TITLE
[UX] URL alias pattern page cleanup

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3835]
**Description of the bug**
Field labels on the Default URL Alias patterns fields are hard to decipher. 
See page: /admin/config/urls/path/patterns
<img width="1140" alt="Screen Shot 2019-05-31 at 10 50 50 AM" src="https://user-images.githubusercontent.com/397895/58724681-1c9c9b00-8392-11e9-9310-c8dab8897296.png">

I recommend: 

* Move the phrase in parentheses to description text
* Add the type pf default (content, or Taxonomy term) after the word default, so:
  - `Default URL alias pattern` becomes `Default content URL alias pattern`
  - `Default URL alias pattern` becomes `Default taxonomy term URL alias pattern`

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2926

**Comment by klonos** [comment]
I am picking this up, lets get a few nits out of the way.

**Comment by klonos** [comment]
`Default content URL alias pattern` makes it sound like this is the URL alias pattern for the "default content"; so I went with `Default URL alias pattern for content` instead. Similarly for vocabularies.

While I was at it, the help text for the user account alias pattern was `Each of the fields below support tokens.`, even though there is only a single field in that fieldset. I have made it so that in that case

- the help text is rendered under the field instead of in the fieldset
- singular is used: `This field supports tokens.`

<img width="676" alt="Screen Shot 2019-10-08 at 2 28 17 am" src="https://user-images.githubusercontent.com/2423362/66325722-78e07e80-e973-11e9-9a51-c82aae52466c.png">

**Comment by klonos** [comment]
...btw, I have tested this on my local with #1828, and it looks so much better:

![Screen Shot 2019-10-08 at 8 13 44 am](https://user-images.githubusercontent.com/2423362/66349017-9af1f500-e9a3-11e9-8135-5b9b50675db7.png)

**Comment by bugfolder** [comment]
Here's a before and after:

![image](https://github.com/backdrop/backdrop-issues/assets/29214084/8e6d5bbe-6173-4220-b406-32d903461c45)

WFM.

Code reviewed, LGTM.

RTBC.

**Comment by bugfolder** [comment]
@klonos, could you add the magic "Fixes" word to the first comment of your PR https://github.com/backdrop/backdrop/pull/2926?

**Comment by klonos** [comment]
Done + rebased the PR.

Looking at this with fresh eyes, I've noticed and addressed the following:
- I have changed `Each of the fields below support tokens` to `Each of the fields below supports tokens` ("supportS" instead of "support").
- In the previous PR, we had already moved the "applies to all ..." text for the default use case of single-language sites, but not when multiple languages have been enabled for content types and vocabularies.
- The addition of the 'pattern label' key was not documented in `hook_path_info()`.
- The addition of the 'pattern label' key and the changes in the PR would have broken previous implementations of the hook. So I have added code in `path_get_info()` to account for that (2 lines of code in a single conditional). That way, we provide backwards compatibility by moving the text in 'pattern description' to the 'pattern label' key in previous implementations of the hook (that did not specify 'pattern label') - for details, see inline comments added.
- We were repeating the word "URL" in each `URL alias pattern for all ... URLs` label, which didn't sound right (it sounded as if we were saying "URL alias for URLs" instead of "URL alias for this thing"). Initially, I tried changing that to the following, which I think is more accurate and makes the labels/fields easier to scan as well (the "target thing" is mentioned last):
  - from `URL alias pattern for all [content-type] URLs` to `URL alias pattern for all content of type [content-type]`
  - from `URL alias pattern for all [vocabulary] URLs` to `URL alias pattern for all terms in the vocabulary [vocabulary]`

The above resulted in more accurate, yet slightly lengthier labels for the fields. Also, this placement of the "target thing" at the end of each label may apply to English and other languages, but that might not be the case for all languages available out there. That also got me thinking that although the field for the default pattern of each category is special (it is used as fallback), it is not visually indicated as such in any other way. So I thought that perhaps it'd be better if we grouped all the fields for the non-default, specific patterns together. That way, it'd be more obvious how these fields work + we'd be able to shorten the field labels (by omitting the "URL alias pattern for" bit, which is repeated and adds visual "noise").

Here's the result:
![image](https://github.com/backdrop/backdrop-issues/assets/2423362/c2258fdc-24ff-48f2-a50f-ccae20a598ab)

**Comment by bugfolder** [comment]
Not to get too nit-picky (and I do really like all the changes), but since "Default URL alias pattern for content" falls within the "Content URL alias patterns" fieldset, and "Specific URL alias patterns" is (appropriately) not "Specific URL alias patterns for content," how about keeping parallel construction and making the first field title just "Default URL alias pattern"?

Ditto for Taxonomy term URL alias patterns group.

And since there is only one pattern in "User account URL alias patterns," should it be singular "User account URL alias pattern"?

Also just wondering, if the field title duplicates the fieldset title, just rearranged words, do both need to have all of the words?

**Comment by klonos** [comment]
> ...since "Default URL alias pattern for content" falls within the "Content URL alias patterns" fieldset, and "Specific URL alias patterns" is (appropriately) not "Specific URL alias patterns for content," how about keeping parallel construction and making the first field title just "Default URL alias pattern"?

That is actually the opposite of what I was trying or would like to achieve. Since we have at least 2 items in the same form called "Specific URL alias patterns", then we should ideally be distinguishing them by appending a "for xyz" suffix. BUT:
- The `Default URL alias pattern for content` string comes as a whole from the `'pattern label'` key in the info coming from the `node_path_info()` implementation (same as the string for the help text comes from the `'pattern description'` key).
- Respectively, the `Default URL alias pattern for taxonomy terms` string also comes from the `'pattern label'` key in the info in the `taxonomy_path_info()` implementation, and the help text for the field from the respective `'pattern description'` key.
-`hook_path_info()` doesn't currently provide any key to specify the text for the label for the specific patterns (naturally, since that is something introduced in the PR). Should I add one, specify the strings for node and taxonomy for core, use those in the form, and then fall back to the generic `Specific URL alias patterns` string for those hook implementations that do not explicitly specify that string? (think contrib/custom modules)

Point is that the "for xyz" suffix should ideally be coming from the label/title in the `hook_path_info()` of the path type. However, there is a problem (rabbit hole alert!!!): because the label for the path type (specified by the `'label'` key in the various `hook_path_info()` implementations) is starting with a capital letter, it fits nicely as a prefix in front of all the "`Xyz` URL alias patterns" titles/summaries in the top-level fieldsets. It is however causing that odd capital letter in the middle of the string in all the "Browse available tokens for `Xyz`" links 👎🏼 (preexisting issue - not part of this PR). Whereas the various "Default URL alias pattern for ..." stings do not have that issue, because they are specified as a whole string in the hook implementation.

If all the above is confusing, then have a look at the form, and consider the variations required for taxonomy terms for example (again, preexisting issue):
![image](https://github.com/backdrop/backdrop-issues/assets/2423362/e64ab787-ecc6-4af4-b1a9-5b23f5992d46)
In the screenshot above, the strings are coming from:
(1) the `'label'` key in the various `taxonomy_path_info()` implementation used as a prefix/suffix
(2) the entire string is specified as a whole

Now, we cannot simply use `ucfirst()` or any other PHP trickery to fix that capital letter mid-sentence in the "browse for available tokens" links, because we don't know how that would work in other languages, nor whether the replacement part of the string will come as a suffix or a prefix or end up in the middle of the sentence 🤷🏼 ...welcome to the world of being able to specify plurals for labels and both a lowercase and uppercase variants! 😅 

We could go ahead and specify all these strings in the `hook_path_info()` implementations, but how far do we want to go with that? ...and some of that may actually break the API (change instead of addition).

> And since there is only one pattern in "User account URL alias patterns," should it be singular "User account URL alias pattern"?

Yes 👍🏼 ...that should be relatively easy via the use of a `format_plural()`.

> Also just wondering, if the field title duplicates the fieldset title, just rearranged words, do both need to have all of the words?

We could visually hide the field label, but it should be there for a11y reasons. I'm OK with that ...or rather indifferent ...or ambivalent (it reduces the length/complexity of the form, but it breaks consistency 😅).

**Comment by klonos** [comment]
> ...that should be relatively easy via the use of a `format_plural()`.

Well, not via `format_plural()`, since the `'pattern items'` array is not defined if only one item - so `count()` (which `format_plural()` relies on) can't be used. Still doable though, and still a valid suggestion 👍🏼

**Comment by klonos** [comment]
OK, @bugfolder, how about this?:
![image](https://github.com/backdrop/backdrop-issues/assets/2423362/e2287b0e-431e-488f-b7a0-484eee5a9507)

1. the top-level fieldsets have been changed to always be expanded and non-collapsible.
2. the specific pattern fieldsets are changed to be collapsible instead, since these might be "empty" (nothing configured - default pattern used), and they are:
   - expanded by default if specific patterns have been configured for the path type
   - collapsed by default if no specific patterns have been configured (default pattern used, so saves vertical space and scrolling)
3. "live" fieldset summary text indicates whether specific patterns have been specified or not (provides an indication when collapsing/expanding the various fieldsets, and when the form loads initially with some fieldsets collapsed)
4. if a specific path pattern type has only a single/default pattern, singular is being used in the label of the top-level fieldset, and the label of the field is visually hidden.

Thoughts?

**Comment by klonos** [comment]
...if every fieldset is collapsed, you get this:
![image](https://github.com/backdrop/backdrop-issues/assets/2423362/b2515ef6-ecf1-48fd-9c61-e308bc875541)

**Comment by bugfolder** [comment]
I like that! (Feeling a little guilty over nit-picking, but this is looking even better than before, which was also an improvement.)

**Comment by klonos** [comment]
...yup, I like it much better too 😃 

I pushed a small commit to slightly improve the "customized" summary text, by indicating how many out of the total items have been configured with custom patterns:
![image](https://github.com/backdrop/backdrop-issues/assets/2423362/695e1c2b-6cde-4c8e-a8f0-744bacf96390)

**Comment by bugfolder** [comment]
Tested, works for me. Code looks good, too.

**Comment by quicksketch** [comment]
Thanks @klonos and @bugfolder (and @jenlampton for opening this)! I merged https://github.com/backdrop/backdrop/pull/2926 into 1.x and 1.26.x. Code and UI look good to me too.
