### ISSUE TITLE
Empty 'Date format for log messages' field

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#3847]
**Description of the bug**
I just went to the 'Logging and errors' page for the first time in a while and noticed the 'Date format for log messages' field which is both required and empty for me.

Was this field added as part of a recent update? If so, I think the default value wasn't set properly (or else it's not displaying properly).

**Steps To Reproduce**
I'm not sure... I tried a new install (the lazy way, by using a recent PR demo site :stuck_out_tongue_closed_eyes:) and the field there has a value. So guessing it's some kind of upgrade error...

**Comment by BWPanda** [comment]
Closing as others tested similar sites and didn't have any issues. So assuming its something with my site then...

**Comment by klonos** [comment]
FTR @BWPanda, the change that added that field there was #3753.

The only reason I can think of for this setting ending up empty is if (for some bizarre reason), the `short` date format that comes with vanilla core had been removed. This format is used in `dblog_update_1001()`, which was added as part of #3753, in order to populate the default value for that newly-introduced setting. But AFAIK, the `short` date format, as the other 2 default core date formats cannot be removed ...not via the admin UI at least.

Hope that gives you some ideas as to what to look for.
