### ISSUE TITLE
Exclude content with hidden path display from search results if the user has no permission to view such content.

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop/backdrop-issues#3862]
**Description of the bug**
Content of types with the setting "Hide path display" (introduced in #100) is displayed in Backdrop core search results. While I'm not sure if it's clearly a bug, at least I didn't expect such content to show up, and in my opinion it also doesn't make sense.

**Steps To Reproduce**

0. If not already done, enable the Search functionality of Backdrop core.
1. Enable "Hide path display" in the *Display settings* of the content type above, e.g. for Posts.
2. Go to `admin/config/search/settings`, and invalidate the search index.
3. Rebuild the search index by running cron several times, until it's 100%.
4. Search for a string which exists in content of the 'hidden path' type.

**Actual behavior**

There are items of the 'hidden path' content type in the search results.

**Expected behavior**

Hidden path content items don't show up in the search results.

**Additional information**

- Backdrop CMS version: 1.12.x:

---
PR by @herbdool: https://github.com/backdrop/backdrop/pull/2824

**Comment by olafgrabienski** [comment]
A good alternative in my opinion: Allow to exclude content types in the core search settings (couldn't find a respective feature request so far).

**Comment by herbdool** [comment]
I don't think this is a bug. The content should be seen in a list, the "Hide path display" only prevents it from being seen in its own path, such as `node/1` and doesn't deal with `search/foobar` and so on. If you don't want some content to display in search results you might need some node access module.

**Comment by laryn** [comment]
Does the search result display a link that is broken, or just list the content with no link?

**Comment by olafgrabienski** [comment]
> Does the search result display a link that is broken, or just list the content with no link?

As far as I remember, the search result displays the link to the content (to its own path).

**Comment by olafgrabienski** [comment]
> The content should be seen in a list, the "Hide path display" only prevents it from being seen in its own path, such as node/1 and doesn't deal with search/foobar and so on.

Yes, I agree that "Hide path display" shouldn't prevent the content to be part of a list. However, the search results provide a link to the node which doesn't make sense for 'hidden path' content.

I'm no longer sure about the "Expected behaviour":

- Don't display the link to the content?
- Don't display the result? (see issue description)

More / other ideas?

**Comment by herbdool** [comment]
I think the expected result would be to not show the link. Or just exclude the content type in the search settings. Though we could replicate this with a View. In that case the admin needs to know that a link to the node will result in a 404.

**Comment by klonos** [comment]
The point of implementing #100 was to block users from being able to directly access content of certain (configurable) type(s). This here seems like a "loophole" or something that we missed to think of.

If you watch the first 1min of [this tutorial](https://www.youtube.com/watch?v=UlBOlq2_APU), you will see that the person explains that the goal is to achieve excluding slide nodes from search results, because people should not be able to access them directly; which is our case. The tutorial uses https://www.drupal.org/project/custom_search, which seems to be somewhat popular ([40k+ sites reported using it](https://www.drupal.org/project/usage/custom_search) at the time of writing this), but it does many more things (which should be left for contrib).

It seems that in our case (and given that #100 was implemented in core), we do not need to provide any option for this, but rather automatically exclude any rabbit-hole'ed nodes from the search results. So we'd basically need to tweak the search query to take that into consideration.

**Comment by klonos** [comment]
...there seem to be many contrib modules out there that can be used to restrict search results per content type. I won't list them all here, but https://www.drupal.org/project/search_exclude seems to be doing what we're after here:

![image](https://user-images.githubusercontent.com/2423362/60125231-b9562b00-97ce-11e9-9e27-f71f4d2bb3d2.png)

...the catch here though being that there should be no UI in our case, because ticking the "Hide path display" of a content type implies that it should not be accessed at all:

> [ ] **Hide path display**
>If enabled, this content can be placed as a block or within a listing but will not be accessible at its URL without proper permissions. This facilitates "hidden path" content that is meant to be embedded with other content and never on its own. Users who have the "View hidden paths" permission will still be able to visit the full page URL, while those without this permission will receive a "Page not found" error.

Perhaps we'd need to update the label and/or help text of that checkbox to say something along the lines of:

> [ ] **Hide from search results, and prevent direct access**
> This facilitates "hidden path" content that is meant to be embedded with other content, but never directly viewed on its own. The content can still be accessed when placed as a block, or within a views listing.
>  - Users who have the "View hidden paths" permission will still be able to visit the full page URL, and content of this type will be available to them in search results.
>  - Those without this permission will receive a "Page not found" error when trying to directly access this content, and they will not see content of this type in search results.

**Comment by BWPanda** [comment]
Since there's a 'needs more feedback' tag, I'll give mine...

I agree that 'hidden' nodes shouldn't be displayed in search results. My main use case for using the Rabbit Hole module in Drupal was to prevent people seeing and accessing 'Slideshow' nodes (used solely in a frontpage slideshow view). So I would never want one of those slideshow nodes to appear in search results (either with a link to the node or not).

**Comment by herbdool** [comment]
Putting this here so I won't lose the info. There are two ways to address this with search. By default search indexes all nodes. So some D7 modules excluded content at the node access stage, by filtering the index (e.g. https://www.drupal.org/project/search_config) or excluding content before it even gets indexed (e.g. https://www.drupal.org/project/search_index). The latter would be a more radical change to core.

**Comment by olafgrabienski** [comment]
Do we still need "more feedback" here? My impression is that most or all people agree that 'hidden' nodes shouldn't appear in the search results.

Regarding the implementation approach, I don't have a clear opinion. Excluding content before it gets indexed sounds reasonable to me.

**Comment by BWPanda** [comment]
I agree. No point filling up the DB with content that's not going to get displayed.

**Comment by klonos** [comment]
I agree too 👍

**Comment by herbdool** [comment]
Thought about it more. Since the "Hide path display" option uses node access it should use node access with excluding from search too. That's because roles with the permission to see those nodes, should still be able to see them in the search.

**Comment by herbdool** [comment]
I've got a PR https://github.com/backdrop/backdrop/pull/2824. It'll need some good code review.

**Comment by olafgrabienski** [comment]
> Since the "Hide path display" option uses node access it should use node access with excluding from search too. That's because roles with the permission to see those nodes, should still be able to see them in the search.

I see your point, from a technical point of view. On the other hand, as a person with "Hide path display" permission, I wouldn't *expect* to see hidden content in the search results. Probably because I provide core search usually for all visitors and I don't see it as an administrative tool. I guess if 'hidden content' was visible in the search results due to my privileged role, I'd however be confused and would ask me: do other people see these results as well?

Hm, I still think that 'hidden' content shouldn't be displayed in core search results at all. What do others think?

**Comment by BWPanda** [comment]
I tend to agree with @herbdool in that users who can't access a node's path shouldn't see those nodes in search results, but users who can access a node's path should see those nodes in search results.

**Comment by klonos** [comment]
Yup, I see @herbdool's reasoning as perfectly valid too.

**Comment by klonos** [comment]
...as for @olafgrabienski's point of view, I find that reasonable as well. Perhaps we should have some visual indication for the results that are hidden-paths-enabled. Perhaps something similar to the ping-ish background we use for the draft pieces of content when users with the "View own/any unpublished content" permissions?

**Comment by herbdool** [comment]
@klonos I like the idea of a visual indication, though I propose we do it as a follow-up so as not to hold up this bug. Then we can also perhaps put the indicator on individual nodes too.

**Comment by klonos** [comment]
We have discussed this issue during the dev meeting today, and the consensus was that:

- we should include the rabbit-hole'd content in the search index
- we should have it so that rabbit-hole'd content is not shown to users that will get a 404 if they follow the link in a search result
- perhaps follow up with another issue, to add visual indication to rabbit-hole'd content (same as we do for unpublished content)

**Comment by olafgrabienski** [comment]
@herbdool I've had a look at the sandbox site of the PR, it looks good to me!

- Created a content type "Slide", enabled "Hide path display".
- Created two slide items (Slide A, Slide B) and ran cron a few times to index the new content.
- Searched for "slide" as admin user.
  - As expected, I got two results.
  - In the *Advanced Search*, the Slide content type was available as an option, also fine!
- Enabled (advanced) search for the anonymous role.
- Visited the site as anonymous user, and searched for "slide".
  - As expected, there were no results.
  - In the *Advanced Search*, the Slide content type was not available, perfect!

**Comment by herbdool** [comment]
@indigoxela interested in doing a code review? I'll swap for reviewing the core update bug PR.

**Comment by indigoxela** [comment]
@herbdool I left a comment in your PR

I'm not 100% sure, if I'm the right person for this job, but I do my best.

**Comment by klonos** [comment]
...approving the PR also works 😉 

<img width="910" alt="Screen Shot 2019-08-27 at 3 28 58 am" src="https://user-images.githubusercontent.com/2423362/63732055-f72d0980-c87a-11e9-89b9-fa56a8716a1d.png">

**Comment by indigoxela** [comment]
@herbdool your PR looks good now, marked it as "ready to be committed".

**Comment by quicksketch** [comment]
The code looks good, minor comments: https://github.com/backdrop/backdrop/pull/2824#pullrequestreview-282322113

We need test coverage for this functionality change.

**Comment by herbdool** [comment]
Working on tests

**Comment by herbdool** [comment]
I've added tests.

**Comment by quicksketch** [comment]
Thanks @herbdool, @olafgrabienski, @klonos, @BWPanda, and @indigoxela! Merged https://github.com/backdrop/backdrop/pull/2824 into 1.x and 1.13.x.

**Comment by olafgrabienski** [comment]
Tested again using the [1.14 preview](https://github.com/backdrop/backdrop/releases/tag/1.14.0-preview), on one of my sites, looks still good!
