### ISSUE TITLE
[UX] Move user Status and Roles settings to a separate fieldset

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#3894]
**Description of the need**
On the User account edit form, there are the main user fields (e.g. username, email address & password), then there are the `Status` and `Roles` settings, then there are any additional custom fields you add (via `/admin/config/people/manage`). There's no way to move custom fields between the default user fields and the `Status` and `Roles` settings.

Here's what it currently looks like:

![current](https://user-images.githubusercontent.com/2385329/60239362-137deb80-98b6-11e9-9a1f-9eee370ecf63.png)
(where `Age` is a custom field)

![Screenshot - Manage fields - Backdrop Sandbox (sandbox lndo site)](https://user-images.githubusercontent.com/2385329/60239875-cbf85f00-98b7-11e9-8647-064a2b451c27.png)

**Proposed solution**
And here's what it would ideally look like:

![proposed](https://user-images.githubusercontent.com/2385329/60239552-d108de80-98b6-11e9-90f6-ec935a7b872c.png)

![Screenshot - Manage fields - Backdrop Sandbox (sandbox lndo site) 2](https://user-images.githubusercontent.com/2385329/60239877-d155a980-98b7-11e9-908d-8fa79408e84b.png)

Adding these setting into their own fieldset will not only allow moving them around the form independently of the main fields, but would also allow them to be placed in a vertical tab in https://github.com/backdrop/backdrop-issues/issues/3872.

---
PR by @BWPanda: https://github.com/backdrop/backdrop/pull/2755

**Comment by herbdool** [comment]
I think this should be BC so ok to proceed.

**Comment by BWPanda** [comment]
Made a PR that addresses this feature request: https://github.com/backdrop/backdrop/pull/2755

**Comment by klonos** [comment]
Great suggestion @BWPanda 👍 ...I especially like the fact that the status and roles settings can be moved around via the form in `/admin/config/people/manage` 👏 

I have left a small suggestion in the PR, but would also like to propose renaming the label of the draggable element from "Account settings" to "Account status and user roles", in order to match the "User name and password" element:

![Screen Shot 2019-06-29 at 4 01 48 am](https://user-images.githubusercontent.com/2423362/60361886-c53a2b00-9a22-11e9-8c6d-984f4e136a0a.png)

**Comment by BWPanda** [comment]
@klonos Another good suggestion. Done and PR updated :slightly_smiling_face:

**Comment by klonos** [comment]
Another good PR @BWPanda 🙂 ...PR approved, issue RTBC'ed 👍 

Because this is labeled as a feature request, I have added the milestone suggestion for the next minor release; if it is deemed to be a UX bug/task though, we can consider adding this in the next bug release. ...especially because it seems to be blocking #3872 (which is a UX task, slated for the next bug release).

**Comment by BWPanda** [comment]
If someone else thinks this is a bug, we can change the milestone, but until then setting the milestone to (what I hope is) the next minor release.

**Comment by jenlampton** [comment]
I'm not sure it's a bug, but it is a UX issue.

**Comment by jenlampton** [comment]
On second thought, this change does rearrange the form structure. Sites like backdropcms.org that have already heavily altered the user_edit form might be affected. Maybe it's better to wait for 1.14

**Comment by klonos** [comment]
...thought so. Fair enough.

@BWPanda perhaps when #3872 gets merged, you can update the PR here to move those things in the vtabs set 😉

**Comment by BWPanda** [comment]
Already done. There's a line in this PR that will add this to vertical tabs once they're created.

**Comment by oadaeh** [comment]
What about making the field set collapsible? So that if there have been several roles defined, it can be collapsed and the user doesn't have to scroll past them all to get to whatever is beneath the field set. I like collapsible field sets for situations like that. :)

**Comment by klonos** [comment]
@oadaeh all this will be within a vertical tab once #3872 gets merged, so it won't take as much vertical space/scrolling 😉

**Comment by oadaeh** [comment]
Okay. I wasn't sure that was the intention.

**Comment by BWPanda** [comment]
@oadaeh Good suggestion. @klonos is right that the intention is that this'll eventually be moved into a vertical tab, however since this is a separate issue, I like to treat this as it's own thing. Therefore, if the other vertical tab issue never gets committed, I think this should still be collapsible as you suggest. So I've updated the PR with that change.

**Comment by klonos** [comment]
@BWPanda 👍 ...still RTBC (the test failure is one of those random ones).

**Comment by quicksketch** [comment]
Thanks looks good hear too! Merged https://github.com/backdrop/backdrop/pull/2755 into 1.x for 1.14.0.
