### ISSUE TITLE
Set password_inc variable

### ISSUE THREAD

**Issue by VasasA** [backdrop/backdrop-issues#3928]
**Description of the need**
I want to set `password_inc` variable through Backdrop API. The `state_set()` and `config_set()` don't work, because the core picks up this variable with `settings_get()`: https://github.com/backdrop/backdrop/blob/1.x/core/modules/user/user.module#L1758

**Additional information**
https://api.backdropcms.org/api/backdrop/core%21includes%21password.inc/1
https://api.backdropcms.org/api/backdrop/core%21includes%21bootstrap.inc/function/settings_get/1

I want to convert this D7 function:
https://git.drupalcode.org/project/simple_ldap/blob/7.x-1.x/simple_ldap_user/simple_ldap_user.install#L10

**Comment by VasasA** [comment]
This code works, but doesn't use Backdrop API. Is it problem? If not, you can close this issue.
```php
function simple_ldap_user_init() {
  $GLOBALS['settings']['password_inc'] = drupal_get_path('module', 'simple_ldap_user') . '/simple_ldap_user.password.inc';
}
 ```

**Comment by herbdool** [comment]
I'm not sure if there's anything to do here in core.

`variable_get` and `variable_set` had a convenient but not so robust way of first checking the settings.php file for overrides before retrieving the variable from the db. It caused a bit of a mess because the override could end up being saved into the db, which wasn't wanted.

So in Backdrop (and in early Drupal 8 development I think) these were deprecated in favour of two separate features: Settings and Configuration. As the docs for settings_get describe: "Settings are used for low-level, global configuration. Unlike config_get(), this function is used to retrieve values that cannot be changed via the user-interface..."

Setting the password file is a low-level global configuration, and is then best left to Settings. For the most robust people should set it in the `settings.php` file. Using `$GLOBALS['settings']['password_inc']` will only work if in a hook that runs all the time like hook_init and it has to run early enough so it is before the system needs the password file. I'm not sure if `hook_init` does that, would need to test that.

Seems to me that configuring LDAP is always going to be done by administrators who are probably competent that they can add a line to the settings file manually. Safest way to run it.

**Comment by VasasA** [comment]
Yes. But this is dangerous: If an admin disables the Simple LDAP module, and forgets modify the `settings.php` or hasn't got access right for the `settings.php`.
