### ISSUE TITLE
Remove all default words (stop words) from path alias "Strings to Remove" settings

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#3931]
**Description of the need**
It's bothered me for a while that Pathauto removes prepositions (of, over, up, etc) and articles (the, an, a) from URLs by default. I ran across an article describing exactly why this is a bad idea:

https://onlinemediamasters.com/why-you-shouldnt-remove-stop-words-from-urls/

> Removing stop words can actually hurt your SEO because it can make your URLs read differently. For example, /growing-up-with-hearing-loss/ is NOT the same thing as /growing-hearing-loss/ (the version where stop words are removed). 

I also noticed that StackOverflow always includes all words:

Title: "How to make a whole 'div' clickable in html and css without JavaScript?"
URL:   https://stackoverflow.com/questions/8160494/how-to-make-a-whole-div-clickable-in-html-and-css-without-javascript

Whereas if this were using Backdrop's default rules it would read `how-make-whole-div-clickable-html-css-without-javascript`, which IMO is both less readable and harder to remember.

**Proposed solution**
All default words should be removed from the "Words to Remove" setting on Path Alias Settings.

---
PR by @BWPanda: https://github.com/backdrop/backdrop/pull/2841

**Comment by klonos** [comment]
I think that this should be converted to a setting/checkbox. Existing sites should remain as is, but new installations should default to off. That way we will not have any feature regression.

...it has always bothered me that there are only English stop words. Perhaps as a follow-up we should make it so that translators are able to specify language-specific stop-words (still off by default).

**Comment by BWPanda** [comment]
Here's a [PR](https://github.com/backdrop/backdrop/pull/2841) that simply clears the default setting, so new sites will have all words in URLs, but existing sites won't have any changes automatically.

I don't think changing this to a single checkbox is a good idea, because then you lose the ability to customise this list...

**Comment by BWPanda** [comment]
PR updated to fix tests.

**Comment by olafgrabienski** [comment]
Thanks for the PR, @BWPanda! Works for me in the sandbox site.

**Comment by quicksketch** [comment]
Looks great to me! Seems like this should be a minor version change, since it affects the behavior of sites (though only new installs). Marking as a candidate for minor.

**Comment by BWPanda** [comment]
Agreed.

**Comment by quicksketch** [comment]
Thanks @BWPanda! Merged https://github.com/backdrop/backdrop/pull/2841 into 1.x for 1.15.0. The change is simply that the default values are removed, no changes to functionality or UIs.
