### ISSUE TITLE
Views filters: Group `OR` operator shown as `AND` in the "Rearrange filter criteria" dialog

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3936]
Filters overview 👍:

![Screen Shot 2019-07-17 at 11 57 14 am](https://user-images.githubusercontent.com/2423362/61341556-2880e580-a88a-11e9-9bbd-de42a7d4eebb.png)

"Rearrange filter criteria" dialog 👎:

![Screen Shot 2019-07-17 at 11 57 03 am](https://user-images.githubusercontent.com/2423362/61341608-62ea8280-a88a-11e9-92a4-f8fe20922a66.png)

---
PR by @isabelhaas: backdrop/backdrop#2827

**Comment by klonos** [comment]
Thanks @isabelhaas ...things work as expected in the PR sandbox 👍 

I have only tested the UI bug though - I did not actually test the AND/OR functionality of the actual queries. I am confident that things would still work, as the only thing changed is the js that updates the `AND`s/`OR`s *visually*.

I would have marked this as RTBC, were it not for the fact that things work as expected in the latest Views 7.x-3.23:

![Screen Shot 2019-08-24 at 2 49 25 pm](https://user-images.githubusercontent.com/2423362/63636959-4a3a6d00-c67f-11e9-8b71-12baa56efacb.png)

...and the same part of the code is identical: https://git.drupalcode.org/project/views/blob/7.x-3.x/js/views-admin.js#L700

I guess what I am trying to say is that I would like to understand why the same bit of code works fine in 7.x, while it is broken in Backdrop. So I would like some eyes by someone more knowledgeable (a core committer perhaps?).

**Comment by BWPanda** [comment]
Thank you @isabelhaas for the PR! And to @klonos for testing/reviewing. I've merged https://github.com/backdrop/backdrop/pull/2827 into 1.x and 1.16.x.

@klonos The reason Backdrop experiences this issue and Drupal doesn't is because Backdrop runs jQuery v1.12 while Drupal runs jQuery v1.7 (on my sites anyway). On my Drupal site, when I updated jQuery to v1.10 (using jQuery Update) it started experiencing the same problem. So there must have been something in jQuery itself between v1.7 and v1.10 that caused this.
