### ISSUE TITLE
tabledrag.js should not use for...in to iterate over an array

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3951]
**Description of the bug**
I'm having the same problem as described in https://github.com/backdrop/backdrop-issues/issues/2482, but on version 1.13.2.

In the console, I see the error:
`TypeError: rowSettings is undefined    tabledrag.js:744:7`

**Additional information**
Here's [a similar issue on d.o](https://www.drupal.org/project/drupal/issues/800968) that explains that we cannot use `for...in` because that breaks on some browsers. I found an example of `for..in` in tabledrag.js.

**Comment by jenlampton** [comment]
Well, fixing the `for...in` in tabledrag.js. did not fix my problem. Changing title to target `for...in` but will search harder for the cause of my stickiness!

**Comment by jenlampton** [comment]
Changing issue type to task since there are no reports of this causing problems in Chrome on Windows (yet).

**Comment by quicksketch** [comment]
`for/in` loops can cause problems when looping over arrays because it returns object properties in addition to the array items. So when looping in this way, we need to include `hasOwnProperty()` to check if it's an array item and not an object property.

For example from tabledrag.js:
```
  for (var group in this.tableSettings) {
    if (this.tableSettings.hasOwnProperty(group)) {
```

This is the correct approach that prevents browser-specific issues and avoids conflicts with 3rd party libraries. I checked all of the tabledrag.js file and all instances of looping looks like it's set up correctly.

Since this was actually an issue with Node Queue and there's no known core issue, I'm closing this issue.
