### ISSUE TITLE
Undefined index in theme_get_setting().

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3981]
**Description of the bug**
```
Notice: Undefined index: in theme_get_setting() (line 1463 of backdrop/core/includes/theme.inc).
```

**Steps To Reproduce**
To reproduce the behavior:
1. Enable the metatag favicon module
2. Configure the global metatags at `admin/config/metadata/metatags/config/global`
3. Check the logs for the above php notice.

**Comment by jenlampton** [comment]
In line 1450 you can see that sometimes the theme returned is an empty string:
```php
$theme = !empty($GLOBALS['theme_key']) ? $GLOBALS['theme_key'] : '';
```

That means we can't assume we can use it as the key of an array in line 1463:
```php
$theme_info = $themes[$theme];
```

PR adds a check for an empty string.

**Comment by quicksketch** [comment]
I looked at the PR and it doesn't look like it would be adequate to fully prevent PHP notices. But overall I have to wonder if this might not be a problem with Metatag Favicon module. If it's asking for theme information before a theme is even loaded, it's not going to get back accurate results. We shouldn't be building work-arounds into a function that suppresses notices when they're actually raising a valid problem: There isn't a theme loaded at the time the data is being retrieved.

**Comment by jenlampton** [comment]
I've updated the PR based on feedback left on it. The new version returns early if no theme is set.

**Comment by indigoxela** [comment]
I agree with @jenlampton that we can't do this:

Snippet from function theme_get_settings:
 ```
 if (!isset($theme)) {
    $theme = !empty($GLOBALS['theme_key']) ? $GLOBALS['theme_key'] : '';
  }

  if (empty($configs[$theme])) {
```
As long as we have to assume that `$theme` can be an empty string.

How about something like that:
```
 if (!isset($theme)) {
   if (empty($GLOBALS['theme_key'])) {
     backdrop_theme_initialize();
   }
   $theme = $GLOBALS['theme_key'] ;
 }
```
Caution - completely untested, just a quick mockup.

**Comment by oadaeh** [comment]
Does `$GLOBALS['theme_key']` get set somewhere in `backdrop_theme_initialize()`? (I didn't see that it was.) If not, `$theme = $GLOBALS['theme_key'];` needs to be in an `else { }` block.

**Comment by indigoxela** [comment]
> Does $GLOBALS['theme_key'] get set somewhere in backdrop_theme_initialize()?

Yep, it does: https://api.backdropcms.org/api/backdrop/core%21includes%21theme.inc/function/backdrop_theme_initialize/1
```
  // Store the identifier for retrieving theme settings with.
  $theme_key = $theme;
```

> $theme = $GLOBALS['theme_key']; needs to be in an else { } block.

No, that wouldn't work. My snippet initializes the theme in case the global is empty to make sure we _always_ have `theme_key` in place.

But again - I didn't actually try this.

**Comment by indigoxela** [comment]
In the meantime the bug in Metatag Favicon module has been fixed. But I belief that we still have an open question here.

Taking a closer look at [theme_get_setting()](https://api.backdropcms.org/api/backdrop/core%21includes%21theme.inc/function/theme_get_setting/1):

1) Variable `$theme` defaults to the current theme if not set, which works fine when the function is called in themes but can fail if called from a module.

2) If `$theme` is set to something non-existent, or a theme has been removed - this results in an "Undefined index" notice.

Are these two cases something we need to take care of in core, or are these tasks for the contribs that cause it?

Both problems could easily get fixed where they arise.

1) Provide the theme's name (e.g. get it from config and provide as $theme param) instead of relying on global theme_key being set.

2) This possibly shouldn't be hidden/catched to give admins a chance to fix it.

**Comment by indigoxela** [comment]
The PR does not fully catch the problems with "undefined index". Not sure if it should.

I tried to find a way to reproduce/simulate and this was my approach: I created a minimal module with following code:

```
<?php

function garbage_preprocess_page(&$variables) {
  theme_get_setting('toggle_favicon', '');
  theme_get_setting('toggle_favicon', 'nosuchtheme');
}
```
Enabled it, visited front page, flushed caches - and got two notices as expected:

- Notice: Undefined index: in theme_get_setting()
- Notice: Undefined index: nosuchtheme in theme_get_setting()

Then I applied the patch. The first message was fixed, but not the second. The question is: should it?

I'm asking because recently an issue has been opened where such a problem appeared while migrating from Drupal.

**Comment by klonos** [comment]
> I'm asking because recently an issue has been opened where such a problem appeared while migrating from Drupal.

It might not be the same issue @indigoxela, as the error message in #5073 is different.

**Comment by BWPanda** [comment]
PR looks good to me, though it should be debased to use the latest test suite. Ping @jenlampton.

**Comment by quicksketch** [comment]
Thanks @BWPanda. I think this is fine also. It might not prevent 100% of errors as noted by @indigoxela, but I don't think we need to continue holding up a fix that has clear benefits and no downside. I merged in https://github.com/backdrop/backdrop/pull/2820 into 1.x and 1.22.x. Thanks folks!
