### ISSUE TITLE
Image file may not be referenced.

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#4017]
When trying the 1.14 preview release I successfully uploaded an image file using 'add a file' in content - manage files.

The file was then available in the Image Library when editing a page but when I tried to add it to a page I was shown an error 'The file used in the Upload an image field may not be referenced'.
![ErrorScreenshot](https://user-images.githubusercontent.com/10559274/64318770-c3f12580-cfb2-11e9-909b-ef44af944a33.jpg)

I am not sure what this means. Hopefully it can be fixed, either by changing the wording or, better still, by allowing the image to be inserted by the editor.

---
PR by @Graham-72: https://github.com/backdrop/backdrop/pull/2855
PR by @klonos: https://github.com/backdrop/backdrop/pull/3065

**Comment by Graham-72** [comment]
It seems that this is because the uploaded file has temporary rather than permanent status and the error message is produced by `function file_managed_file_validate()` in file.module.

**Comment by Graham-72** [comment]
My PR fails. Something is wrong with my logic - rethink required.

**Comment by Graham-72** [comment]
Tests now pass with the revised PR. An image file can be uploaded, appear in the Image Library and then be inserted using WYSIWYG editing.

However, I do not know whether the removal of this validation test causes other problems. I do not understand why it existed and when using Backdrop I have never previously seen the error message it produced (The file in the ...... field may not be processed.)

**Comment by docwilmot** [comment]
@Graham-72 if a file element is about to be saved, the file assigned to that element (referenced) must be being "used" by something; a node or user or something, otherwise some other module or code could hypothetically delete the file, and the file element would end up referencing a file thats deleted. So normally the code dealing with the upload should call `file_usage_add()` after the upload and save.  Hence the call to `file_usage_list()` and the error if there is no usage recorded.

File module doesnt't call `file_usage_add()` when you upload a file, so I suspect `filter_format_editor_image_form_submit()` probably should? Not sure. This looks like we need @quicksketch.

**Comment by indigoxela** [comment]
Hi, just stumbled across the same problem. And I can't understand the logic (not the PR, the core logic). Or, at least I have questions.

```
>   // If referencing an existing file, only allow if there are existing
>   // references. This prevents unmanaged files from being deleted if this
>   // item were to be deleted.

```
Aha, seems clear so far...

```
      if ($file->status == FILE_STATUS_PERMANENT) {
        $references = file_usage_list($file);
        if (empty($references)) {
          form_error($element, t('The file used in the !name field may not be referenced.', array('!name' => $element['#title'])));
        }
      }
```
Aha, OK, a file is in state "permanent", but has no usage. It's not possible to reference it, because if THIS new reference is deleted (calls file_usage_delete), this file will get marked temporary and deleted on next garbage collection run. --- And vanishes from wherever it was used (unmanaged) before.

Now the weird thing: If one uploads an image via admin/content/files "+ Add a file" (file/add), it's never usable anywhere, right? So, why does this "+ Add a file" link exist anyway? What is it good for?

Another thought: why are these "unusable" files shown in the file browser anyway. They're just causing form errors and probably user confusion.

**Comment by chill-fpraz** [comment]
Same issue here with a clean install of 1.15. From a UI perspective, the ability to upload files on the Managed files page is confusing if the image can't be referenced via the core image module. Maybe one solution is to mark the file as "uploaded", with same legitimacy as "referenced", until it's used...?

**Comment by indigoxela** [comment]
Hm, what are our options to solve this issue...

Filter out unusable files in view image_library (the image browser).
That would at least prevent the above error message, as only files appear in the browser, that can get referenced.

Either remove the "Add file" link on admin/content/files completely or find a way to mark an uploaded file as used (referenced by itself?), so it's usable. (Somewhat like @chill-fpraz's suggestion)

I don't think there's a way to fix this retroactively, as we don't know if a "permanent" file without usage count is an uploaded one or an unmanaged one (possibly from a migration).

Or are there any better ideas?

**Comment by klonos** [comment]
I have filed a PR here: https://github.com/backdrop/backdrop/pull/3065 (waiting for the tests to run)

It adds a call to `file_usage_add()` in `file_add_form_submit()`, which fixes the issue for me.

**Comment by klonos** [comment]
...tests are green 🙂

**Comment by indigoxela** [comment]
Cool, that works! ... at least for newly uploaded images.

I wonder if we should filter out unusable files in image library (views.view.image_library.json). That would prevent the error with previously uploaded files.

@klonos do you think it's worth it?

**Comment by klonos** [comment]
@indigoxela I take it that by "unusable files" you mean any file uploaded via the "Add file" link, prior to this fix. Right? ...if so, then not sure how to deal with those 🤔 ...we could try an update hook that goes through them and makes them "usable" again (add them as being used by the File module via `file_usage_add()`).

Open to more discussion/suggestions.

**Comment by indigoxela** [comment]
Revisiting this issue after some time, I do think now, that this should go into core as-is.

Fiddling with files that have status permanent but no usage might have side effects. And the PR is working fine for newly added files.

**Comment by docwilmot** [comment]
> an update hook that goes through them and makes them "usable" again (add them as being used by the File module via file_usage_add()).

I'd support that.

**Comment by jenlampton** [comment]
Code change looks straightforward. RTBC if we don't need the update hook. 

> Fiddling with files that have status permanent but no usage might have side effects.

I'm also concerned about possible side effects.

**Comment by quicksketch** [comment]
This looks like a fine work-around for the time being. We have done this same approach in other places where a file is considered "independent", have it reference itself. However long-term I'd like to make an "official" way to designate files as independent/stand-alone/manually-uploaded. A new database column and then check for that property whenever we're doing file clean-up.

This as-is solves a major WTF with images and I can't think of any down-sides. Files are already allowed to be deleted even if they're in-use, you're just given a warning.

I've merged https://github.com/backdrop/backdrop/pull/3065 into 1.x and 1.15.x. Thanks everyone!
