### ISSUE TITLE
Add option for the "Recent content" block to control which content types to include.

### ISSUE THREAD

**Issue by VasasA** [backdrop/backdrop-issues#4020]
**Description of the bug**
Layout block's conditon is ignored.

**Steps To Reproduce**
I created a new content type: "Events"
I created a new layout, and add a block (Recent content) with a condition: Type is "Events"
![kép](https://user-images.githubusercontent.com/8567234/64494950-a31b1f80-d293-11e9-96e3-5c88c5d62c18.png)

**Actual behavior**
There are the nodes with type "post" and "page" on the result page.
![kép](https://user-images.githubusercontent.com/8567234/64494979-25a3df00-d294-11e9-982a-4f829e6f22dc.png)

**Expected behavior**
There are only the nodes with type "Events" on the result page.
![kép](https://user-images.githubusercontent.com/8567234/64495049-1c674200-d295-11e9-80f6-82f43f84b264.png)

(Am I doing something wrong?)

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2857

**Comment by klonos** [comment]
Hello @VasasA 👋 this is a visibility condition; it controls _where_ the block is shown - not _what_ it displays. So if you try to view this block in a page other than event type content, it will not be shown.

The current implementation of the "Recent content" block is hard-coded, and it only includes an option for how many items to show.

There is this old ticket to convert that block to a view: #146 ...which would allow you to control what is being shown, by editing the block view display that generated that block. In the meantime, if you'd like to control what is shown in that block, I'm afraid that you will need to create a custom view of your own, with a block display, and use that block instead of the "Recent content" one that comes with core.

**Comment by klonos** [comment]
> The current implementation of the "Recent content" block is hard-coded, and it only includes an option for how many items to show.

Actually, lets make this a feature request to add an option for content type to this core block 🙂

**Comment by VasasA** [comment]
@klonos Thank You very much! I understood. I created a new view with block display instead of the "Recent content", it works! :fireworks: 
![kép](https://user-images.githubusercontent.com/8567234/64519053-af36c980-d2f3-11e9-849c-1b14666686ed.png)

**Comment by klonos** [comment]
Here's a PR, that adds an option to select which content types to include/exclude: https://github.com/backdrop/backdrop/pull/2857

<img width="617" alt="Screen Shot 2019-09-09 at 8 29 27 pm" src="https://user-images.githubusercontent.com/2423362/64523857-956fa380-d340-11e9-8381-1da1ed7013a7.png">

It additionally does the following:

- changes the "Number of recent content items to display" from a select, to an HTML5 number field (better accessibility), and sets its min value to 1 (was 2 before - but displaying the single most recent content is a valid use case), and does not limit the max value (previously maximum was hard-coded to 30 items).
- changes the "More" link to "All recent content", and adds a query to its URL, to sort the content list by most-recently updated, in descending order.
- changes `theme_more_link()` to accept a text for the link (still defaults to "More" if not provided), and an optional query for the URL.
- `node_get_recent()` now accepts an optional `$types` parameter, to limit which content types to include in the db_query.

**Comment by klonos** [comment]
...I still don't like the styling (or lack of it) of the block in Basis:

<img width="406" alt="Screen Shot 2019-09-09 at 5 40 19 pm" src="https://user-images.githubusercontent.com/2423362/64524710-7bcf5b80-d342-11e9-944b-52500e2f8399.png">

...and also the columns with the "edit"/"delete" links should not be rendered for anonymous (users with not enough permissions in general):

<img width="387" alt="Screen Shot 2019-09-09 at 8 42 51 pm" src="https://user-images.githubusercontent.com/2423362/64524789-ac16fa00-d342-11e9-8b8e-888f8886d2ea.png">

**Comment by klonos** [comment]
...I have pushed a change to render the columns with the "edit"/"delete" links only if the user has permission to these actions:

<img width="392" alt="Screen Shot 2019-09-09 at 9 01 50 pm" src="https://user-images.githubusercontent.com/2423362/64525830-1892f880-d345-11e9-86c1-f2c113f36ed0.png">

**Comment by VasasA** [comment]
I tested this PR in my test environment, and it works:
Screenshot of "Recent content" with admin user:
![kép](https://user-images.githubusercontent.com/8567234/64646360-3b8ddd00-d417-11e9-91dc-6548f7951449.png)

Screenshot of "Recent content" with "anonymous":
![kép](https://user-images.githubusercontent.com/8567234/64646554-a0493780-d417-11e9-9eb1-3af03b41fbfe.png)

Screenshot of "Recent content" with a user (munkatars) who created the first content, and has access for edit it or delete it:
![kép](https://user-images.githubusercontent.com/8567234/64646827-1c437f80-d418-11e9-87cd-818b6c20c144.png)

**Comment by stpaultim** [comment]
This is a simple idea that makes a lot of sense to me. There is a PR, but the sandbox is broken. If it's working as expected, it could be a small easy win for 1.17.0. 

Can someone reset the sandbox? @klonos

**Comment by klonos** [comment]
>Can someone reset the sandbox?

Done @stpaultim 👍

**Comment by klonos** [comment]
We still have time till feature freeze, so I think that I might be able to squeeze in a couple of tweaks:

- convert those "edit"/"delete" links to dropbuttons instead. That should give more horizontal space for the title/author to fit better.
- add a `by: ` prefix in the author name. As it is now, when the person viewing the block is admin, the author names are links (to the user account page), which makes it hard to tell them apart from the content title.
- perhaps add a checkbox to optionally show the date the content was created.

**Comment by klonos** [comment]
@stpaultim I have file a separate PR in #4576, which includes many improvements/options etc. Please test when you get some time, and let me know if there's anything that's a good fit for inclusion here.

TBH, the PR for this issue here already included a few things that may be considered scope creep. So I have removed those. Let's simply get the MVP in here, which is the ability to include/exclude content types from the list. The only tiny bits that I left in other than selecting content types are:

- converted the "Number of recent content items to display" option from a select to a number field
- conditionally add the edit/delete cells in each row + fill in the missing cells with colspan 1 or 2 for the content cell.

**Comment by stpaultim** [comment]
@klonos - I think I like the scope of this issue as it is. You have done nice work in the larger pull request, but I suspect some of those other new features will generate more discussion than this simple one and I would hate to see us delay this change.

I like the changes to filter by content type and select any number of posts rather than choose from a select list.

**Comment by stpaultim** [comment]
@klonos - I think I found a small bug. 

1. If I create a test account "Tim Erickson" with authenticated user role
2. If I give authenticated users the ability to delete their own posts and pages
3. If I create a post and a page
4. If I log in as Tim Erickson and view the recent content block, there is a problem with the delete column. See screenshot. 

![Home___PR_2857_backdrop_backdrop_testing_site](https://user-images.githubusercontent.com/3144571/91385368-527b3a00-e7f6-11ea-9595-03783c553d3c.png)

I assume this is not intentional or desirable.

**Comment by klonos** [comment]
> ...I suspect some of those other new features will generate more discussion than this simple one and I would hate to see us delay this change.

Yup, that's what I thought too. That's why I trimmed this PR down to only the basics 😉 

> I assume this is not intentional or desirable.

No, it's not. I'll fix that...

**Comment by klonos** [comment]
...should be fixed now @stpaultim. Please give it another spin when you get the chance.

**Comment by VasasA** [comment]
I tested this PR in my test environment with Lateral theme, and it works:

**Screenshot of "Recent content" with admin user:**
![kép](https://user-images.githubusercontent.com/8567234/91615031-03164480-e983-11ea-9f96-9ba3862618d0.png)

**Screenshot of "Recent content" with "anonymous":**
![kép](https://user-images.githubusercontent.com/8567234/91615080-1fb27c80-e983-11ea-84d5-42618ffff290.png)

**Screenshot of "Recent content" with a user (loren) who has some permissions:**
![kép](https://user-images.githubusercontent.com/8567234/91615242-6902cc00-e983-11ea-9178-d9f8e85c007b.png)

**Comment by stpaultim** [comment]
Works for me!

**Comment by jenlampton** [comment]
> ...I have pushed a change to render the columns with the "edit"/"delete" links only if the user has permission to these actions

Can we move these both into an "Operations" Column, or even better yet -- as drop buttons?

**Comment by jenlampton** [comment]
See related: https://github.com/backdrop/backdrop-issues/issues/146

**Comment by jenlampton** [comment]
I've pushed a PR over there that rebuilds this block as a view. 

Here's the front-end view of the block:
<img width="358" alt="Screen Shot 2020-08-29 at 5 49 34 PM" src="https://user-images.githubusercontent.com/397895/91648738-188d7c00-ea20-11ea-823b-bdadabe701b8.png">

Here's what the configure form looks like for the views version:
<img width="594" alt="Screen Shot 2020-08-29 at 5 52 20 PM" src="https://user-images.githubusercontent.com/397895/91648788-73bf6e80-ea20-11ea-9f38-be9026027320.png">

**Comment by klonos** [comment]
Yeah, let focus on #146. I should have done that in the first place actually.
