### ISSUE TITLE
[A11Y] Remove 'article' role from 'article' elements

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#4033]
Similar to https://github.com/backdrop/backdrop-issues/issues/4032...

`<article ... role="article">`
This code gives the following warning when validated:

> The `article` role is unnecessary for element `article`.

We should change instances of the above code to remove `role="article"`. Note that we can't do this in every situation, as some `role` attributes are added in preprocess functions, but the element type is set in the template file (e.g. `node` module).

For more information, see: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Article_Role

---

PR: https://github.com/backdrop/backdrop/pull/2872

**Comment by indigoxela** [comment]
Hm. This only improves the comments. The actual nodes still have the redundant attribute.

I it worth it anyway then? Not sure...

**Comment by BWPanda** [comment]
> Is it worth it anyway then? Not sure...

@indigoxela That's like asking if it's worth fixing only one bug in core rather than fixing all of them. Of course we want to fix all bugs, but it's hard to do and takes time. So an incremental approach is needed.

The same here. Obviously we'd like to fix all issues of this in core, but nodes are somewhat harder to fix in this regard (see my above comment re. preprocess functions). But I don't think that means fixing what we can easily is less worthwhile...

**Comment by klonos** [comment]
@BWPanda I agree with incremental fixes/improvements 👍🏼 ...this is what we have been doing in Backdrop for years now, and it has made a great difference eventually.

Code looks good to me, but before we can mark this RTBC though, I need to fully understand this:

> Note that we can't do this in every situation, as some role attributes are added in preprocess functions, but the element type is set in the template file (e.g. node module).

Why is it that we can't do this? Is it because we'll be breaking backwards compatibility?

**Comment by BWPanda** [comment]
@klonos If I recall correctly, from 3.5 years ago, I believe it's because when the 'role' attribute is set (in https://github.com/backdrop/backdrop/blob/1.x/core/modules/node/node.theme.inc#L250), we don't know what the HTML element will be, since it's set separately (in https://github.com/backdrop/backdrop/blob/1.x/core/modules/node/templates/node.tpl.php#L87).

I guess we could assume that the template file won't be overridden and just remove the 'role' attribute regardless. Then if anyone does override it and use a different HTML element for nodes for which the 'role=article' attribute would be appropriate, they can add it back in themselves...

Happy to hear thoughts on whether we just remove `$variables['attributes']['role'] = 'article';` from `node.theme.inc` as part of this issue.

**Comment by klonos** [comment]
Exactly 👍🏼 ...we could be checking what we have in the `$attributes` variable before we do `<?php print backdrop_attributes($attributes); ?>`. So if the `$attributes` array includes a `role` and that is set to `article` and what we are adding to the `node.tpl.php` file is an `<article>` HTML element, then we can either omit adding the role (`unset()` it), or add a different role as appropriate. It can still exist in the `$attributes` variable so that other themes can be free to use it, but in that case why not leave it up to the specific theme implementation to be adding the `role` attribute as needed (depending on HTML elements being used, and if they need a `role` attribute specified or not)?

> Happy to hear thoughts on whether we just remove `$variables['attributes']['role'] = 'article';` from `node.theme.inc` as part of this issue.

I would say yes, remove it 👍🏼 ...I haven't checked the commit history, but I'm assuming that either of these two things have happened:
- we added the role at a time where we were using `<div>` instead of `<article>` in the `node.tpl.php` file.
- we added the role without actually checking the HTML output for validity with a11y tools.
Either way, we should fix this.

**Comment by BWPanda** [comment]
Looks like it happened here: https://github.com/backdrop/backdrop/pull/1051/files It was `role='post'` but was then changed to `article`.

**Comment by BWPanda** [comment]
PR updated to remove role from nodes too now.

**Comment by klonos** [comment]
Thanks @BWPanda 🙏🏼 ...code looks good, and things work as expected now 👍🏼 

I have also run a search across our codebase for instances of `'article'` and `"article"` (case-sensitive), and these 3 were the only relevant ones I could find. RTBC/WFM.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2872 into 1.x and 1.24.x. Thanks @BWPanda, @klonos, and @indigoxela!
