### ISSUE TITLE
Welcome block link text follow-ups

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4042]
Follow-up to https://github.com/backdrop/backdrop-issues/issues/3994

This issue contains minor changes to links on the New welcome block, as follows:

1) `View your site` changed to `View the home page`
2) `Edit the about page` comes before/above `Add a new post`
3) We don't have a `Main menu` backdrop, changes this to `Primary navigation`
4) Don't show the link to colorize Basis if Basis is not the default theme
5) `Configure the layout of your home page` changed to `Modify the layout for your home page`
6) `Modify the layout of your home page` moved to the bottom of the 2nd column, since it's a more advanced task
7) `Update your site information` moved to the first column, since adding a logo is one of the first things people do. 
8) `Update your site information` made more specific: `Add a logo, or change the site name`
9) `Here are some links to get you started:` changed to `Here are some links to help get you started:`
10) Removes the `change the theme` link since we don't have more than one front-end theme by default. 
11) Adds an external link icon next to links to the user guide and forum links.

<img width="1276" alt="changes" src="https://user-images.githubusercontent.com/397895/64927044-82365b00-d7ba-11e9-8cc2-ba2f432cbe63.png">

Other thoughts: 
* The headings were copied from Wordpress, but what if we made them more specific to the things that you were doing. Something like `Edit content` `Configure your site` and `Get help`  that might be more helpful. 

This PR changes variable names for each column of links to `links_col1`, `links_col2`, `links_col3` so that we have more flexibility with columns in the future.

---

PR: https://github.com/backdrop/backdrop/pull/2879

**Comment by stpaultim** [comment]
Until the welcome block can easily be hidden, I think that we should add a link under "More actions" that says "Hide this block" and links to the layout for the dashboard. 

This would provide a relative beginner a direct hint on how to get rid of this big block if they would like and would also serve as a reminder/hint on how to customize the dashboard for themselves, simply by leading them there.

**Comment by jenlampton** [comment]
@stpaultim I think that might be misleading, because the layout for the dashboard doesn't tell people where/how to hide the block. It won't be much help for a total beginner, they'd get lost there.

**Comment by stpaultim** [comment]
I'm not sure it's any more confusing that the current link "Configure the layout of your home page" that takes you to the home page layout or several other links. Maybe, the label for the link should better set expectations and read "Customize your dashboard (ie - hide this block)"?

NOTE: The problem I am trying to solve is that once a user has read through this block a few times, they might want to remove it. It takes up a lot of real estate and has diminishing value over time. 

I would like to avoid a situation in which a user grows to hate this block because they no longer need it but don't know how to get rid of it or hide it.  

The best option would be make it [dismissable](https://github.com/backdrop/backdrop-issues/issues/3996) or [collapsible](https://github.com/backdrop/backdrop-issues/issues/3995)

But, I think providing a hint/link is much easier to accomplish and does lead them to / expose them to the dashboard layout, which has educational value. I think that most new site owners will not realize that they have this control. I think the hardest part of hiding this block will simply be finding the dashboard layout. Once there, it's not that hard. 

![Dashboard__admin_dashboard____localhost](https://user-images.githubusercontent.com/3144571/64926989-2b388200-d7ca-11e9-9a21-f94ef8bcf44c.png)

**Comment by jenlampton** [comment]
> The problem I am trying to solve is that once a user has read through this block a few times, they might want to remove it. It takes up a lot of real estate and has diminishing value over time.

Don't we have other follow-up issues (plans) for how to resolve this? I'm not sure we should focus on adding a link here that's temporary. Can we push this conversation to those issues?

**Comment by docwilmot** [comment]
Maybe we should reconsider https://github.com/backdrop/backdrop-issues/issues/1725

**Comment by stpaultim** [comment]
I am fine with the PR as it is. I see you removed the link to the layout page for home page and understand your rational, but disagree with it mildly. It is consistent with your concerns for my . proposed link ;-)

I like the fact that users were being led to the layout page and exposed to it, but you are right it's the most complicated page that was being linked to.

**Comment by stpaultim** [comment]
I am also noting that if you click on contextual menu to edit a block, you are ALMOST take to the layout page, so it's not as hard to find as I was thinking. 

![Dashboard__admin_dashboard____PR_2879_backdrop_backdrop_testing_site](https://user-images.githubusercontent.com/3144571/64927242-d39c1580-d7cd-11e9-8a07-f6bf7ad94f18.png)

**Comment by jenlampton** [comment]
> I am fine with the PR as it is. I see you removed the link to the layout page for home page and understand your rational, but disagree with it mildly

Actually, I moved it to the bottom of the 2nd column.

**Comment by klonos** [comment]
...assuming that the last test failure is fixed by the last commit, this is RTBC 👍

**Comment by quicksketch** [comment]
I have a few more items of feedback in a new review https://github.com/backdrop/backdrop/pull/2879#pullrequestreview-288391054.

**Comment by stpaultim** [comment]
I'm not ready to do code review, but I checked it out and it still looks good and works for me.

**Comment by klonos** [comment]
Re-reviewed, and it LGTM. @jenlampton has implemented the changes requested by @quicksketch, so back to RTBC 👍

**Comment by quicksketch** [comment]
Awesome thanks @stpaultim and @klonos! Merged into 1.x for 1.14.0.

**Comment by klonos** [comment]
...and thanks @jenlampton 🙂

**Comment by stpaultim** [comment]
Here are links to the issues previously created to allow dashboard blocks be dismissed or collapsed. 
https://github.com/backdrop/backdrop-issues/issues/3995
https://github.com/backdrop/backdrop-issues/issues/3996
