### ISSUE TITLE
Welcome block follow-up: review block as editor

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4043]
Follow up to https://github.com/backdrop/backdrop-issues/issues/3994

I logged into backdrop as a new editor, and landed on a dashboard with the following links on the welcome block:

<img width="1226" alt="editor" src="https://user-images.githubusercontent.com/397895/64927224-db9f8980-d7bc-11e9-9d96-b5b34f1122cf.png">

Are we fine with these links for editors? If so, we can close this issue.

**Comment by jenlampton** [comment]
I'm pretty happy with these links, but wanted confirmation from at least 1 other person that these are okay :)

**Comment by klonos** [comment]
I take it that you opened this one because the block seems rather empty @jenlampton. We can surely work on improving this, but remember that we can change it on next, bug/UX releases 😉 ...so no reason to rush it for 1.14.0.

**Comment by jenlampton** [comment]
> I take it that you opened this one because the block seems rather empty @jenlampton. 

I opened it because I wanted to make sure that we tested it as an editor. I hadn't done this before so wanted consensus that this works as designed :) We can close it if so!

**Comment by stpaultim** [comment]
Nice thinking to test this. I had not tested the editor view of this block since permissions were added to PR. 

The block is a little thin for editors, but I have no obvious or quick improvements.

Did notice that the "create a new post" link is actually repetitive with the "create content" block right below it. But, I don't think that is a problem. It could be an opportunity in the future to free up a space for a different link if needed.
