### ISSUE TITLE
PHP Notice in layout_context_required_by_path() when adding a layout that triggers the dashboard context

### ISSUE THREAD

**Issue by hosef** [backdrop/backdrop-issues#4077]
**Description of the bug**
A PHP notice is issued when creating a layout below the admin/dashboard/ path.

**Steps To Reproduce**
To reproduce the behavior:
1. Go to '/admin/structure/layouts/add'
2. Create a new layout using a path starting with 'admin/dashboard/'
3. Go to the new layout or the edit page for the new layout

**Actual behavior**
There will be several entries in the log with a message similar to 
`Notice: Undefined index: path placeholder in layout_context_required_by_path()`

**Expected behavior**
There should not be any errors

**Additional information**
It appears that the layout module assumes that layout contexts will have some kind of placeholder, and throws errors when it does not. Either we need to change the way contexts are handled, or we need to add a path placeholder value to `dashboard_layout_context_info()`

**Comment by stpaultim** [comment]
Just a note. I was able to create layouts that start with admin/ or admin/content. The problem seems to be specific to admin/dashboard/

**Comment by oadaeh** [comment]
The problem is that the 'path placeholder' element as defined in [hook_layout_context_info()](https://api.backdropcms.org/api/backdrop/core%21modules%21layout%21layout.api.php/function/hook_layout_context_info/1) is missing. The documentation says that it's optional, but the element itself is not optional, only the value, because line [1751 of layout_context_required_by_path()](https://github.com/backdrop/backdrop/blob/30df6dd2e29ea4af1b87ca5aaff49d3e6be2b91c/core/modules/layout/layout.module#L1751) checks the value without first making sure it is set.

I think the bug is actually either in the documentation or in the layout_context_required_by_path(), but if I did it right, I've submitting a patch to fix dashboard_layout_context_info(), based on how it is handled in layout_layout_context_info().

https://github.com/backdrop/backdrop/pull/3116

PS: If layout_context_required_by_path() is modified to check 'path placeholder', then it should also check 'menu paths', which [has the same problem](https://github.com/backdrop/backdrop/blob/30df6dd2e29ea4af1b87ca5aaff49d3e6be2b91c/core/modules/layout/layout.module#L1735).

**Comment by oadaeh** [comment]
Hmm, I am now seeing these layout-based PHP notices when saving a view I created. If I can pin down the specifics there, I'll post them here.

**Comment by argiepiano** [comment]
I'm seeing this error again in Backdrop 1.25.1 and PHP 7.4. Any chance to rebase this PR to get this fixed, @oadaeh?

**Comment by oadaeh** [comment]
I closed my previous PR and created a new one that checks if the array element is empty instead. My reason is that code will still fail if something else does not fill it in, so it seems like the fix should be at the potential point of failure.

**Comment by herbdool** [comment]
PR works for me.

**Comment by quicksketch** [comment]
Thanks folks! This seems pretty harmless to me, although there might be a better way to specify the default keys at an earlier point, getting this fixed directly will do the job.

Thank you @oadaeh for the PR and @hosef for filing the issue! Thanks to @herbdool,  @argiepiano, and @stpaultim for the feedback! Merged https://github.com/backdrop/backdrop/pull/4882 into 1.x and 1.29.x.
