### ISSUE TITLE
[UX] Flexible Layout Templates - better labels for "row width behavior" 

### ISSUE THREAD

**Issue by stpaultim** [backdrop/backdrop-issues#4081]
**Description of the bug**

I've struggled a bit to understand the implications of the various options for Row Width Behavior. Mostly, it's not clear to me the difference between "Maximum width" and "Always full width of page." I was having problems getting a hero images to stretch to the full width of page. Turns out that "Always full width of page" is the best answer for that. 

Existing options:

- Maximum width (adds the 'container-fluid' row class)
- Fixed width (adds the 'container' row class)
- Always full width of page (no row classes added)

I suggest that we use the word "hero" somewhere to indicate the full width without any margin.

Very weak proposal to get things started, hoping for some better ideas: 

- Fixed width (adds the 'container' row class)
- Maximum width (adds the 'container-fluid' row class)
- Always full width of page (no row classes added - for hero blocks)

Specifically, I'd like some wording to better help me understand "Maximum width" - I still don't quite understand the use case for this one.

EDIT: Current proposal (using this for PR)

- Fixed maximum width - adds the 'container' row class.
- Fluid width - adds the 'container-fluid' row class (no max-width but padding).
- Full width - no row classes added (e.g. for Hero blocks).

- - - - - - - -

PR: By @stpaultim = https://github.com/backdrop/backdrop/pull/2923

**Comment by olafgrabienski** [comment]
In a way, it's misleading to use the term "Maximum width" for `container-fluid`: Actually, it's the `container` class which has a `max-width` definition in the layout grid CSS file. In contrast, `container-fluid` doesn't have `max-width` in the CSS.

Here's my understanding of the three options:

- Fixed maximum width. Row class `container`.
- Fluid width (no max-width but padding). Row class `container-fluid`.
- Full width (e.g. for Hero blocks). No row classes.

I've also tried make the phrases a bit more concise, e.g.
- "Full width" (2 words) vs. "Always full width of page" (5 words)
- "Row class `container`" (3 words) vs. "adds the 'container' row class" (5 words)

Note that I'm not an Englisch native speaker, though.

**Comment by olafgrabienski** [comment]
> Specifically, I'd like some wording to better help me understand "Maximum width" - I still don't quite understand the use case for this one.

@stpaultim I guess my comment above doesn't answer the use case question regarding the option currently named "Maximum width" (container-fluid class). I guess fluid width layouts were quite popular years ago but they aren't very common anymore. The way I see it, a popular use case of fluid width was to adapt the width to different screen sizes. But that was mainly before CSS media queries allowed a real responsive webdesign.

**Comment by stpaultim** [comment]
I went ahead and created PR to move this forward. Hoping that we might get this change in with other fixes to Flexible Layout Templates. However, open to additional improvements.

**Comment by jenlampton** [comment]
I don't like the current suggestions `Row class container.` or `Row class container-fluid.` because it's not clear that the classes `container` and `container-fluid` will be added when I select either of these options. The previous wording `(adds the 'container-fluid' row class)` was much clearer. Knowing when the classes is added will be beneficial to people already familiar with bootstrap layouts.

I do think we need to do a better job of explaining the difference for people who are not familiar with Bootstrap.  I'm going to explain the differences here in a lot of words, but I'm hoping this will lead to us being able to choose the right words to put into a much shorter version. :)

Having no class added to the row will make the row always be the full width of the page. 

Adding the `.container` class will set a max width for the columns inside the row. For example: at size XL the width could be 1200px, at size MD it could be 768px and at size SM it could be 544px -- content on this row will never bleed outside these widths. At sizes smaller than 544px, the row will become the full-width of the page. **When shrinking screen sizes, the max-width of items in the row will jump from 1200px to 768px to 544px, and then shrink with the page**

Adding the `.container-fluid` class (in addition to the `container` class) makes the width of items in the row fluid, so at a screen size of 920px, the row could be 920px wide. Without the `.container-fluid` class at 920px, the row would be 768px wide instead. **When shrinking screen sizes, the width will scale smoothly all the way down**

Adding the `.container` class will set a maximum width for each breakpoint, meaning no row will ever be the full-width of the page. In order to achieve a full-width row, both these classes must be removed.

**Comment by klonos** [comment]
This then is a good use case where this dropdown `select` should be changed to a set of radio options instead. Each radio can have its own description right below it 😉

**Comment by olafgrabienski** [comment]
> Adding the `.container-fluid` class (in addition to the `container` class) makes the width of items in the row fluid ...

AFAIK, the `container-fluid` behavior (no `max-width`) is only applied when there's NO `container` class in the same element. Core layout templates add *both* classes for some reason, making it so that `container-fluid` doesn't apply there. Example: `<div class="l-wrapper-inner container container-fluid">`

> Adding the .container-fluid class (...) makes the width of items in the row fluid, so at a screen size of 920px, the row could be 920px wide.

Yes, but note also the (IIRC only) difference to full-width, a small `padding` and `margin: auto`:

```
.container-fluid {
  padding-right: .9375rem;
  padding-left: .9375rem;
  margin-right: auto;
  margin-left: auto;
}
```

**Comment by stpaultim** [comment]
Another try:

- Fixed maximum width - adds the 'container' row class.
- Fluid width - adds the 'container-fluid' row class (no max-width but padding).
- Full width - no row classes added (e.g. for Hero blocks).

**Comment by jenlampton** [comment]
> This then is a good use case where this dropdown select should be changed to a set of radio options instead. Each radio can have its own description (help text) right below it 😉

I love it!

> AFAIK, the container-fluid behavior (no max-width) is only applied when there's NO container class in the same element.

According to the bootstrap docs, `container-fluid` is *supposed* to extend `container`. It doesn't do anything on it's own. I disliked this when we put it in, but decided sticking with the bootstrap "normal" would be better than redoing it our own way.

@stpaultim I think we need more words. I think the labels are getting better, but let's try longer descriptions :)

**Comment by jenlampton** [comment]
I just checked the [current boostrap 4 docs](https://getbootstrap.com/docs/4.3/layout/overview/#containers) and it seems that container thing has changed. Unfortunately, I'm not sure we can change our grid-system in 1.x, or we'll break everyone's themes :(

**Comment by olafgrabienski** [comment]
>> - Fixed maximum width - adds the 'container' row class.
>> - Fluid width - adds the 'container-fluid' row class (no max-width but padding).
>> - Full width - no row classes added (e.g. for Hero blocks).

> I think we need more words. I think the labels are getting better, but let's try longer descriptions

The last suggestion is much better than the current situation, and I've the impression we don't get better ones at the moment, so let's go with it. We can always improve it further in a follow-up.

I wanted to test the PR but the sandbox doesn't work. @stpaultim Can you restart the sandbox somehow?

**Comment by stpaultim** [comment]
I refreshed the sandbox and it works for me now. If you are still having trouble with it, try clearing browser cache or opening in a new browser window.

**Comment by klonos** [comment]
@stpaultim I have filed a PR against your fork here: https://github.com/stpaultim/backdrop/pull/2

> I think we need more words. I think the labels are getting better, but let's try longer descriptions :)

Yes @jenlampton 👍 ...and changing the select to radios allows just that 😉. So instead of this (which has the potential to get even messier in other languages):

![Screen Shot 2019-11-23 at 7 27 31 pm](https://user-images.githubusercontent.com/2423362/69476169-93d75700-0e2a-11ea-8288-dac7921b3828.png)

...we can now do this:

![Screen Shot 2019-11-23 at 7 44 06 pm](https://user-images.githubusercontent.com/2423362/69476174-9df95580-0e2a-11ea-88ff-a1ac8c8ee9fa.png)

@stpaultim if you merge my PR to your repo/branch, you can then go crazy with the descriptions 😜 (and also possibly link to external documentation).

**Comment by jenlampton** [comment]
This is getting so much better!!!!  :)

**Comment by stpaultim** [comment]
Love the radio buttons and the new format. 

This language confuses me a bit "No additional width behavior classes added to the row (e.g. for Hero blocks)." Make me wonder which type of classes are being added, since the comment is specific to "width behavior classes."

Is there any reason we can't simply state: 
"No additional classes added to the row (e.g. for Hero blocks).?"

If no one objects (or explains why the wordier text is helpful) in the next 24 hours, I'll modify the PR to reflect this minor change. We can always change it back.

**Comment by klonos** [comment]
> Is there any reason we can't simply state:
> "No additional classes added to the row (e.g. for Hero blocks).?"

Within the same fieldset ("Style"), there's another field called "Additional classes". Using plain ""No additional classes added..." makes me think that this option negates any classes added to that field; so thought I'd make it more specific.

**Comment by stpaultim** [comment]
That didn't occur to me, but now that I see it. Your concern makes sense. 

How about "No additional ```container``` classes added to the row (e.g. for Hero blocks)."?

The other two options both have ```container``` classes and saying no additional ```container``` classes would probably address the concern you raised and be easier for someone like me to understand. I wasn't smart enough to make the connection to ```width behavior classes```.

I think that even if someone had their own ```container``` class in the the "Additional row classes" field, they would understand that this does not apply to them. In fact, if they did, they would be unlikely to be checking this box/option anyway.

**Comment by olafgrabienski** [comment]
>> "No additional width behavior classes added to the row (e.g. for Hero blocks)."

> How about "No additional `container` classes added to the row (e.g. for Hero blocks)."?

To me, the combination of the terms "additional" and "added" sounds strange, isn't it saying the same thing twice over? Here's a new suggestion:

"No container-related classes added to the row (e.g. for Hero blocks)."

(I'm not sure if "container-related" is convenient. Wanted to avoid the use of `container` in code style notation, which might be misunderstood as reference to that specific class.)

**Comment by stpaultim** [comment]
@olafgrabienski - The argument in favor of using both additional and added is the argument that @klonos made about the possibility that a user might be adding classes in the "Additional row classes" field. 

By using both words, I read it to say that we are not adding any "additional" container classes beyond anything you (the user) might be adding in the "Additional row classes" field.

IMHO: This is getting pretty nit-picky and any of the recent options are better than what currently exists. So, I'm suggesting improvements but don't want to hold this issue up.

**Comment by olafgrabienski** [comment]
> I read it to say that we are not adding any "additional" container classes beyond anything you (the user) might be adding in the "Additional row classes" field.

I see the intention but it *really* sounds strange. Here's another idea: Let's move the "Additional row classes" input *below* the "Row width behavior". Would be a better fit, in my opinion: First, Backdrop may add some classes to rows, and then you (the user) can define *additional* classes to rows. If we think it this way round, we don't need any "additional adding" for the row width behavior.

**Comment by klonos** [comment]
> No container-related classes added to the row (e.g. for Hero blocks).

I like that ^^ ...no additional additions added additionally 😄

**Comment by stpaultim** [comment]
@klonos, @olafgrabienski, @jenlampton - how does this look?

![Test___PR_2923_backdrop_backdrop_testing_site](https://user-images.githubusercontent.com/3144571/70758519-ee1c5700-1d08-11ea-941c-02c0af9dd0e1.png)

Please, test PR in sandbox. Should be up to date with this image at this time.

**Comment by olafgrabienski** [comment]
@stpaultim Thanks for updating the sandbox! Looks as in the image above now. That's already a great improvement!

In my opinion it still makes much more sense to not start with the "Additional classes" but to move them *below* the "Row width behavior". Here's a comparison:

### 1) Current PR:

![screen-backdrop-flexible-layout-row-style-1](https://user-images.githubusercontent.com/14188307/70787935-14390a00-1d90-11ea-9ce6-1e63c0929673.png)

### 2) Suggestion:

![screen-backdrop-flexible-layout-row-style-2](https://user-images.githubusercontent.com/14188307/70787936-14d1a080-1d90-11ea-8ed2-9d0abf1d9189.png)

**Comment by stpaultim** [comment]
@olafgrabienski - Please check now. I've incorporated your change.

**Comment by olafgrabienski** [comment]
@stpaultim - Thanks for moving the field! Checked in the sandbox website, looks good! (I hope you like it as well.)

**Comment by klonos** [comment]
Yup, this looks good to go @stpaultim 👍 ...I've got one trivial nit though ...I've left a comment in the PR.

**Comment by stpaultim** [comment]
@klonos - Thanks. I accepted your changes to the PR.

**Comment by herbdool** [comment]
Code looks good to me.

**Comment by quicksketch** [comment]
Thanks! Merged https://github.com/backdrop/backdrop/pull/2923 into 1.x and 1.14.x.
