### ISSUE TITLE
PHP warning: Headers already sent on PHP 7.2.+

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#4111]
When installing Backdrop using `./core/scripts/install.sh` I see lots of the following warnings:

```
PHP Warning:  ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /home/travis/www/core/includes/bootstrap.inc on line 740
PHP Stack trace:
PHP   1. {main}() /home/travis/www/core/scripts/install.sh:0
PHP   2. install_backdrop() /home/travis/www/core/scripts/install.sh:171
PHP   3. install_begin_request() /home/travis/www/core/includes/install.core.inc:75
PHP   4. backdrop_bootstrap() /home/travis/www/core/includes/install.core.inc:239
PHP   5. _backdrop_bootstrap_configuration() /home/travis/www/core/includes/bootstrap.inc:2810
PHP   6. backdrop_environment_initialize() /home/travis/www/core/includes/bootstrap.inc:2987
PHP   7. ini_set() /home/travis/www/core/includes/bootstrap.inc:740
```

See full output here: https://travis-ci.com/BWPanda/b/builds/130475206#L243

I believe this has to do with PHP v7.x.

The full list of places that trigger this are:
- bootstrap.inc on line 740
- bootstrap.inc on line 741
- bootstrap.inc on line 742
- bootstrap.inc on line 745
- bootstrap.inc on line 747
- settings.php on line 160
- settings.php on line 161
- settings.php on line 169
- settings.php on line 176
- bootstrap.inc on line 973

---

- <strike>https://github.com/backdrop/backdrop/pull/3138</strike> by @quicksketch (breaks install)
- https://github.com/backdrop/backdrop/pull/3382 by @indigoxela (removes a single line of text)

**Comment by BWPanda** [comment]
Note that Backdrop still installs successfully (these are just warnings, not errors), but it'd be nice to get rid of them regardless.

**Comment by klonos** [comment]
I think that it's a php 7.2 (and possibly 7.3) compatibility issue @BWPanda. Seems similar to https://www.drupal.org/project/drupal/issues/3009351 (does not apply to us, since we have removed the `Statistics` module) and the linked https://www.drupal.org/project/drupal/issues/2238561 (NR) and https://www.drupal.org/project/drupal/issues/3025335 (RTBC).

**Comment by totten** [comment]
Just to confirm affected versions, I did a quick run on PHP 7.1 - 7.4:

* __PHP 7.1__: No warnings
* __PHP 7.2, 7.3, 7.4__: Warnings

**Comment by indigoxela** [comment]
It's still a problem, of course.

Maybe this Drupal Issue (and patch) has helpful hints: https://www.drupal.org/project/drupal/issues/2901753

**Comment by indigoxela** [comment]
Here's a [PR](https://github.com/backdrop/backdrop/pull/3135) as a starting point. With these changes I was able to install via commandline on php 7.3 without nagging.

The trick is to wrap the session stuff in `if (!backdrop_is_cli())`.

**Comment by quicksketch** [comment]
Thanks @indigoxela! Another approach that may be better would be to initialize the environment before printing out any messages. The problem is that the install.sh script prints out "Installing Backdrop. This may take a moment..." before it does anything else. If we bootstrap Backdrop first, then print the message, we don't have the problem. Plus this way all the `ini_set()` calls fire so we can get the same settings whether through CLI or the UI.

I filed a PR that takes this approach at https://github.com/backdrop/backdrop/pull/3138. If you could try it out that would be awesome.

**Comment by indigoxela** [comment]
> Another approach that may be better would be to initialize the environment before printing out any messages. ...so we can get the same settings whether through CLI or the UI.

Totally makes sense :+1:

**Comment by indigoxela** [comment]
Tested it with php7.4. There seems to be a side effect:
```
Installing Backdrop. This may take a moment...
An error occurred. Output of installation attempt is as follows:

Site name field is required.
Username field is required.
E-mail address field is required.
Password field is required.
```
Backdrop still installs, but the user 1 account name is "placeholder-for-uid-1".

As a quick check I commented out `backdrop_bootstrap(BACKDROP_BOOTSTRAP_CONFIGURATION);`
The "headers sent" warnings were there (as expected), but the user credentials were set correctly.

**Comment by indigoxela** [comment]
How to proceed here...?

A single line is the cause for our trouble with php versions > 7.1:
`print "Installing Backdrop. This may take a moment...\n";`

My (closed) PR had the disadvantage of different php settings for installing via command line or via web installer.

@quicksketch's won't do the trick either, because params provided via command line are ignored (install fails).

Hm... is this single line of text really _that_ important?

We could:
```
if (version_compare(PHP_VERSION, '7.2.0', '<')) {
  print "Installing Backdrop. This may take a moment...\n";;
}
```
Note: even if the "headers sent" warning appear, Backdrop still installs, but some CI environments consider the warnings as failure. And some auto-installers of webhosters might, too.

**Comment by quicksketch** [comment]
Hm, another approach: We could wrap the entire script in another script that prints the message, then calls the current script to run the install. That would separate out the execution of PHP from the printing of the message.

But yeah... I'm thinking that perhaps that message just isn't worth it. Rather than hide it for new PHP versions, I'd prefer to just remove it entirely.

**Comment by alanmels** [comment]
Hitting this today on a system with PHP 7.4:

```
Installing Backdrop .. Installing Backdrop. This may take a moment... PHP Warning: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /home/in/public_html/core/includes/bootstrap.inc on line 741 PHP Warning: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /home/in/public_html/core/includes/bootstrap.inc on line 742 PHP Warning: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /home/in/public_html/core/includes/bootstrap.inc on line 743 PHP Warning: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /home/in/public_html/core/includes/bootstrap.inc on line 746 PHP Warning: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /home/in/public_html/core/includes/bootstrap.inc on line 748 PHP Warning: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /home/in/public_html/settings.php on line 160 PHP Warning: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /home/in/public_html/settings.php on line 161 PHP Warning: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /home/in/public_html/settings.php on line 169 PHP Warning: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /home/in/public_html/settings.php on line 176 PHP Warning: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /home/in/public_html/core/includes/bootstrap.inc on line 971 PHP Warning: session_name(): Cannot change session name when headers already sent in /home/in/public_html/core/includes/bootstrap.inc on line 974 Backdrop installed successfully. 
```

**Comment by indigoxela** [comment]
> I'm thinking that perhaps that message just isn't worth it. Rather than hide it for new PHP versions, I'd prefer to just remove it entirely.

Sure, this [PR](https://github.com/backdrop/backdrop/pull/3382) removes the offending line.

**Comment by BWPanda** [comment]
I just tested this by initiating a new Tugboat sandbox.

I checked another PR's Tugboat sandbox and there's one of these warnings in the log after installing the site. I then checked this PR's sandbox and there was no such error. So looks good to me!

**Comment by quicksketch** [comment]
I've merged https://github.com/backdrop/backdrop/pull/3382 into 1.x and 1.17.x. It might not be the best solution because it removes the in-progress message, but it's the simplest and least likely to cause any problems just removing that one line message.

Thanks everyone for their feedback and testing on this issue!
