### ISSUE TITLE
[UX] Remove uppercase transform on fieldset labels in Seven theme

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4125]
This is part of #4124.

The most obvious elements that are unnecessarily capitalized are the fieldset labels. We have discussed and fixed this in #3516, for the fieldset that holds the text field formatting options. This issue is about fixing it globally in the admin UI.

PS: Lower-casing the labels of fieldsets, may somewhat mitigate issues like #3930.

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2929

**Comment by stpaultim** [comment]
Testing. I'm seeing that it's having the intended effects in these locations:

admin/appearance/settings/basis
admin/people/create
admin/modules/list

I have a question about this:
admin/config/people/settings

![Account_settings___Demo](https://user-images.githubusercontent.com/3144571/67152101-fa9aab00-f295-11e9-888e-d07b5c53ee24.png)

**Comment by klonos** [comment]
The PR is only touching the CSS of `legend`, `summary`, and `fieldset` elements, so this shouldn't be happening. Let me check...

**Comment by klonos** [comment]
@stpaultim as I suspected, the PR was created before #1828 was merged into core. All it needed was a sandbox refresh. All should look as expected now, if you care to take a second look 😉

**Comment by stpaultim** [comment]
Works for me!

**Comment by klonos** [comment]
..I've re-refreshed the PR sandbox after the recent 1.16.0 release.

Before:
![Screen Shot 2020-05-17 at 5 36 55 am](https://user-images.githubusercontent.com/2423362/82134439-a1c9cb80-9800-11ea-9c58-23d3adcbaad9.png)

After:
![Screen Shot 2020-05-17 at 5 08 28 am](https://user-images.githubusercontent.com/2423362/82134437-9d9dae00-9800-11ea-81b4-db73b9521958.png)

**Comment by herbdool** [comment]
Looks good to me.

**Comment by quicksketch** [comment]
Thanks folks! This is a good change and helps with a lot of situations where uppercase is not legible or appropriate.

This has some pretty substantial impact on the display of the administration pages. Because it can be so jarring, and because there have only been a few individuals participating in this issue, I've only merged it into 1.x (for 1.17.0) so that we can use the rest of the release cycle to collect any additional comments and feedback on this.

Please, if you have further thoughts or want to advocate for this being suitable for 1.16.x (say if a several more people also support the idea), we can pull this into the next bug fix release as well.
