### ISSUE TITLE
Improve the styling of color input elements in the admin theme

### ISSUE THREAD

**Issue by hosef** [backdrop/backdrop-issues#4155]
**Description of the need**
When a contributed module attempts to add a color input, the current styling in Seven causes it to look very weird. Because of this, any module that has one will need to provide it's own styling of the form.

**Proposed solution**
We can move some of the CSS styles from the Color module to Seven, and that should provide a reasonable base for module developers to use.

- - - - - - - - - - - - 

PR by @hosef - https://github.com/backdrop/backdrop/pull/2947

**Comment by indigoxela** [comment]
@hosef what's the best way to test this?

**Comment by stpaultim** [comment]
@hosef - You will need to generate a fresh sandbox and provide instructions on testing.

**Comment by stpaultim** [comment]
It seems that this module is intended to fix problems in contrib modules, so for the sake of testing, I created a simple test module with a color input element. This module is available for anyone for at least the next month (through May 2022). 

https://github.com/stpaultim/test_module

Here is what the input looked like on my test environment - without the fix.

![image](https://user-images.githubusercontent.com/3144571/162602492-dbef37f2-17b0-4f47-b251-5a4139952e43.png)

I used the manual install process to install this in the current PR sandbox and the test form looks like this:

![image](https://user-images.githubusercontent.com/3144571/162602470-e7556448-7589-4ef7-88f8-974dced42f8b.png)

I will mark this "works for me."

**Comment by indigoxela** [comment]
I know of two existing contrib modules that use type color: Fullcalendar Views NG and Mosaic Grid.

Both now get rounded color pickers, in FVNG it looks a bit odd, because that one already styled the input, but it's still OK. In MG it's definitely an improvement.

It doesn't conflict with color module's color.admin.css, so that's OK, too. RTBC :+1:

**Comment by indigoxela** [comment]
@stpaultim I had to switch the milestone, as this is a feature request, not a bugfix.

**Comment by stpaultim** [comment]
> I know of two existing contrib modules that use type color: Fullcalendar Views NG and Mosaic Grid.

I'm quite sure that Fanciblock and Configurable Block Styles also use it.

**Comment by docwilmot** [comment]
> @stpaultim I had to switch the milestone, as this is a feature request, not a bugfix.

Surely this is a bugfix? I dont think the form element was intended to look like it does.

**Comment by quicksketch** [comment]
Seems like a bugfix to me too.

I made a small modification to the selectors to use classes instead of the `type` attribute to match existing form element selectors. It should have the same level specificity as before.

I've merged https://github.com/backdrop/backdrop/pull/2947 into 1.x and 1.21.x. Thanks @hosef, @indigoxela, @stpaultim, and @docwilmot!
