### ISSUE TITLE
Unable to push new module to production site and sync configuration

### ISSUE THREAD

**Issue by bradbulger** [backdrop/backdrop-issues#4160]
I added the Notify module to my development site and committed it, including the module's notify.settings.json file in the config directory. I pushed these changes to my production environment. I separately enabled the Notify module on the production site, and then tried to sync config settings. The sync always fails:

> Configuration sync failed. The following errors were reported:
> The configuration "notify.settings" is not owned by any module. Try enabling the module that provides this configuration, then importing again.

I went to Notify's config page on the production site and saved it. So there is a notify.settings.json file in the active config directory. So the screen shows "1 configuration changed". But the import still fails with that error.

The only fix is to manually copy the settings file from the staging directory to the active directory.

**Comment by bradbulger** [comment]
This is a bug in Notify, I believe - the port didn't implement hook_config_info(), which is what Backdrop's config_get_info() uses to determine what module owns what settings file.

**Comment by klonos** [comment]
Hmm, not 100% sure that `hook_config_info()` is the culprit here (I could be wrong). It may be a matter of workflow, and the order in which certain actions have happened.

What happens if you repeat the above, but instead of push config changes, and then enable the module, you enable the module and then push the config.

PS: in D8, which modules are enabled/disabled can be managed via config ([`core.extensions.yml`](https://api.drupal.org/api/drupal/core%21config%21install%21core.extension.yml)), which is something we are missing in Backdrop. Perhaps we should consider this as a feature/improvement.

**Comment by bradbulger** [comment]
Doing things in different order etc. did affect the results, but fundamentally, the config sync screen depends on calling that hook to find the owner and it hadn't been implemented. Adding it to the Notify module made the problem go away. I found that because Comment Notify, for instance, was not giving the same problems, while everything else about it was the same (when & where created, when enabled vs when the config was pushed, etc.).
