### ISSUE TITLE
Poll: how do people use their settings.local.php files

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4190]
This is a follow-up to a HUGE discussion on Gitter today 😄 

Some people seem to use the term "local" for literally their local (their laptop/desktop), while others seem to be using it to denote relatively "local" (to whichever environment each time). This makes it so that you have either one of the following 2 use cases:

1. ???

2. ???

Please use 👍/👎 on any of the following two comments, to help us get a heartbeat of how the community feels this should work by default.

👍 means "_I strongly agree with this_"
👎 means "_I strongly disagree with this_" (you don't need to down-vote if you are OK with it)

**Comment by klonos** [comment]
1

**Comment by klonos** [comment]
2

**Comment by jeffporten** [comment]
I like how you assume that we've adopted this convention.

My laptop is localhost. When I apply semantic tags to anything else, I use something more descriptive than "local," because I trust myself to be unsure what I meant three months from now. Something that lives in a dev environment and should never leave gets prefixed or suffixed "dev."

**Comment by klonos** [comment]
@jeffporten are you saying that there is a 3rd option that we have not thought of?

**Comment by alanmels** [comment]
We at AltaGrade use the `settings.local.php` file to pull all developer overrides and put the file in the .gitignore file, so it never gets to production. At the same time, we never modify the `settings.php` file letting it sync between all environments. So I voted to number 1.

**Comment by klonos** [comment]
Point 1 is how myself and most people I know work, so i've up-voted that.

I find point 2 confusing, so I have down-voted it.

**Comment by jenlampton** [comment]
I think 2 only comes into play when you commit `settings.php` into version control, where 1 could be used for any set-up.

**Comment by alanmels** [comment]
This poll is important for how https://github.com/backdrop/backdrop-issues/issues/4174 could be decided, if the results will be taken into account at all. I really do not want temporary overrides like `error_level` and `theme_debug` to end up in the main `settings.php` file, which can be synced between environments. All the developer overrides should live in the separate settings file which should be added into .gitignore and just called by the `settings.php` file to take effect only on certain environment.

**Comment by jeffporten** [comment]
> @jeffporten are you saying that there is a 3rd option that we have not thought of?

Just that it's never occurred to me to use "local" as a descriptive tag embedded in the names of my files. "Local" is a word that appears in localhost, or /usr/bin/local, not in filenames. This discussion of coming up with a semantic tag for "only lives here" regardless of where "here" is (as opposed to my semantic "dev" tag), or restricted to hardware in front of me, is very interesting—but if I saw settings.local.php neither meaning would immediately occur to me. My first thought would be that it was a file used by a piece of Backdrop or other machinery I wasn't familiar with.

**Comment by jenlampton** [comment]
> I really do not want temporary overrides like error_level and theme_debug to end up in the main settings.php file

The results of this poll won't determine if anything gets excluded from `settings.php`, but it will determine what gets put into the a `settings.local.php` file if one gets included in core.

**Comment by jeffporten** [comment]
@klonos For what it's worth: my IT skills are self-taught and this is one of those things that I probably missed by not being a CSE major before doing this for 25 years. Not saying my idiosyncratic methods should be entertained, just saying that if people think either meaning is self-explanatory, it's really not and needs to be documented.

**Comment by jenlampton** [comment]
>  At the same time, we never modify the settings.php file letting it sync between all environments. 

@alanmels where do you put the db credentials? They can't be the same on all environments, can they? Or are these distinct servers so the database creds can be identical?

**Comment by klonos** [comment]
> They can't be the same on all environments, can they? Or are these distinct servers so the database creds can be identical?

That is the case in most (if not all) of my setups. So staging is usually an exact clone/replica of master/prod.

**Comment by BWPanda** [comment]
3. You don't use `settings.local.php` at all, probably because you don't have separate local/dev environments... 😊

**Comment by indigoxela** [comment]
Handling of settings.php was the very first thing I struggled with in Backdrop. Almost all other web projects I know generate a new settings/config file on install - a file that doesn't ship with the software.
I accepted this handling as a - sort of - charming oddity of Backdrop.

For a while I tried to use approach 2 (settings.local.php contains all settings, no matter where), but that wasn't worth the effort. So currently I'm not using settings.local.php at all. Everything goes to settings.php.

If, on the other hand, it would be possible to override the typical dev settings (aggregation, error display...) in a settings.local.php, I'd happily adopt approach 1.

**Comment by alanmels** [comment]
> > At the same time, we never modify the settings.php file letting it sync between all environments.
> 
> @alanmels where do you put the db credentials? They can't be the same on all environments, can they? Or are these distinct servers so the database creds can be identical?

@jenlampton DB credentials can be on each of the main or any of multiple local setting files, the ones in the `settings.local.php` files take over if both present. In that way, you can safely sync the main `settings.php` file between environments, at the same time letting each `settings.local.php` file to have its own overrides, DB settings, etc. 

That's why D8 puts all the overrides such as:

```php
/**
 * Show all error messages, with backtrace information.
 *
 * In case the error level could not be fetched from the database, as for
 * example the database connection failed, we rely only on this value.
 */
```
$config['system.logging']['error_level'] = 'verbose';
```php
/**
 * Disable CSS and JS aggregation.
 */
$config['system.performance']['css']['preprocess'] = FALSE;
$config['system.performance']['js']['preprocess'] = FALSE;
```

```php
/**
 * Disable the render cache.
 *
 * Note: you should test with the render cache enabled, to ensure the correct
 * cacheability metadata is present. However, in the early stages of
 * development, you may want to disable it.
 *
 * This setting disables the render cache by using the Null cache back-end
 * defined by the development.services.yml file above.
 *
 * Only use this setting once the site has been installed.
 */
# $settings['cache']['bins']['render'] = 'cache.backend.null';

/**
 * Disable caching for migrations.
 *
 * Uncomment the code below to only store migrations in memory and not in the
 * database. This makes it easier to develop custom migrations.
 */
# $settings['cache']['bins']['discovery_migration'] = 'cache.backend.memory';

/**
 * Disable Internal Page Cache.
 *
 * Note: you should test with Internal Page Cache enabled, to ensure the correct
 * cacheability metadata is present. However, in the early stages of
 * development, you may want to disable it.
 *
 * This setting disables the page cache by using the Null cache back-end
 * defined by the development.services.yml file above.
 *
 * Only use this setting once the site has been installed.
 */
# $settings['cache']['bins']['page'] = 'cache.backend.null';

/**
 * Disable Dynamic Page Cache.
 *
 * Note: you should test with Dynamic Page Cache enabled, to ensure the correct
 * cacheability metadata is present (and hence the expected behavior). However,
 * in the early stages of development, you may want to disable it.
 */
# $settings['cache']['bins']['dynamic_page_cache'] = 'cache.backend.null';

/**
 * Allow test modules and themes to be installed.
 *
 * Drupal ignores test modules and themes by default for performance reasons.
 * During development it can be useful to install test extensions for debugging
 * purposes.
 */
# $settings['extension_discovery_scan_tests'] = TRUE;
```

in https://git.drupalcode.org/project/drupal/blob/8.8.x/sites/example.settings.local.php, so developers could easily copy and adapt it for each environment. 

The even moved `$settings['rebuild_access']` from the main `settings.php` file  (see https://git.drupalcode.org/project/drupal/blob/8.8.x/sites/default/default.settings.php) to `example.settings.local.php`:

```php
/**
 * Enable access to rebuild.php.
 *
 * This setting can be enabled to allow Drupal's php and database cached
 * storage to be cleared via the rebuild.php page. Access to this page can also
 * be gained by generating a query string from rebuild_token_calculator.sh and
 * using these parameters in a request to rebuild.php.
 */
$settings['rebuild_access'] = TRUE;

```

And to answer your last comment in https://github.com/backdrop/backdrop-issues/issues/4173#issuecomment-549005825:

> See, this is the exact same workflow I use. I'm not alone :) This is option 2 in #4190. But I'm not sure why you voted for 1 if you are doing number 2.

my hesitance to create such a poll when suggested by @klonos in gitter was about my lack of English and that I wouldn't be able to formulate the issue in right way. And here I should admit that the was poll's questions constructed probably do not exactly reflect my concern. From my point of view, each environment can have its own `settings.local.php` file, it would indeed be **local** frm the  prospective if each environment. We are on the same page with you on this.

What we disagree on is that you say on https://github.com/backdrop/backdrop-issues/issues/4173#issuecomment-548993477:

> I am against adding any developer-specific settings to a settings.local.php file, should we choose to add one. In Drupal 8, I believe they intend their example file to be used by developers. In Backdrop **this file is not for developers**.

and so you are advocating placing overrides in the main `settings.php` file. In my firm believe Drupal has placed all the overrides in https://git.drupalcode.org/project/drupal/blob/8.8.x/sites/example.settings.local.php not without a reason. And `settings.local.php` is exactly for developers. And that remains true for Backdrop also. The fact the you are using it slightly differently than most of the developers (this is not my personal opinion, @klonos also thinks so), does not change the files role and place in Backdrop context.

I have some feeling that we are missing some important point to arrive to the same page. Yesterday, I was doubting my command of English. Today I started to think that the main point for you is DB credentials, so I am asking you to run the following test:

1. Place DB credentials of the website on production in the main `settings.php` file, leaving in tact this part:

```
/**
 * Include a local settings file, if available.
 *
 * To make local development easier, you can add a settings.local.php file that
 * contains settings specific to your local installation, or to any secondary
 * environment (staging, development, etc).
 *
 * Typically used to specify a different database connection information, to
 * disable caching, JavaScript/CSS compression, re-routing of outgoing e-mails,
 * Google Analytics, and other things that should not happen on development and
 * testing sites.
 *
 * This local settings file can be ignored in your Git repository, so that any
 * updates to settings.php can be pulled in without overwriting your local
 * changes.
 *
 * Keep this code block at the end of this file to take full effect.
 */
if (file_exists(__DIR__ . '/settings.local.php')) {
  include __DIR__ . '/settings.local.php';
}
```

2. Sync the whole code-base together with the `settings.php` file to any of your other environments - development, testing,   stage, etc. - regardlessly where it physically is, and create the `settings.local.php` for that environment and put completely different DB credentials in it.

And then you will see the DB credentials in the `settings.local.php` will connect to the local database with all the developer overrides taking effect only in that particular environment. You can now include the `settings.local.php` file in the .gitignore file and never care whatever changes in that file your customers can make.

I really believe there is some kind of misunderstanding here and that I am just failing to properly conduct my thoughts, and that if you run some tests will start seeing what I mean. 

Believe me, @jenlampton, I do love the flexibility and agility of Backdrop. At the same time, I really would not ignore lot's of careful thoughts put by Drupal community to come up with such files as https://git.drupalcode.org/project/drupal/blob/8.8.x/sites/example.settings.local.php. With all due sincere respect to you personally, I simply say can not accept the idea some files in Drupal for developers, whereas in Backdrop the same files are for regular users.

**Comment by alanmels** [comment]
> > I really do not want temporary overrides like error_level and theme_debug to end up in the main settings.php file
> 
> The results of this poll will not determine if anything gets excluded from `settings.php` (that's a whole separate issue), but it will determine what gets included in the `settings.local.php` file if one gets included in core.
> 
> Edit: here's the issue this poll will help: #4173

Thank you for pointing the right issue. All got mixed up in the heat.

**Comment by stpaultim** [comment]
I am voting on and describing the way I currently do things. I am not against change nor do I feel strongly about this issue. It's easy enough for each developer to adjust these files, in my opinion. 

For me, settings.local.php is relative to the environment. As I have stated, in some projects I have simply excluded settings.php from git and then I do all of my settings in the settings.php file. 

When, I'm working teams I pretty much leave settings.php intact AND keep it in git. But, I create a settings.local.php file for each environment and allow each developer to create their own. In settings.local.php I include my database credentials as well as any overrides or settings that are specific to that environment. 

This seems very intuitive to me and I'm confused about the controversy here.  Unless we change the way Backdrop sites are normally configured, I've never envisioned anyone but developers using a settings.local.php file. 

I fail to understand why a developer would need a settings.local.php file if they are putting their DB credentials in settings.php. I guess, I am assuming that the DB credentials are always different in each environment, maybe that is not the case.

Again - this is what makes sense to me and what I've done in the past, but I'm totally open to being re-educated and changing my practice.

**Comment by alanmels** [comment]
> I fail to understand why a developer would need a settings.local.php file if they are putting their DB credentials in settings.php. I guess, I am assuming that the DB credentials are always different in each environment, maybe that is not the case.

@stpaultim Tim, thanks for your input!

One example, why lot's of developers use the `settings.local.php` file to have DB credentials of local environment and at the same time all the developer overrides is that they can move data between environments without breaking anything. At any time they can pull data from remote production site (which has all the caches enabled, no error shown on UI, no theme rebuilt on every screen refresh, etc) to local development environment (with its own database, all the caches turned off, all the errors are shown on UI, theme get rebuild on every refresh). Similarly they can push data from development branch to production (or for that matter to testing or stage) without breaking anything there and without having to edit settings.php file at all.

**Comment by BWPanda** [comment]
Can we close this now?

**Comment by klonos** [comment]
I think yes 👍🏼
