### ISSUE TITLE
Allow menus to be always click/touch activated rather than hover

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#4200]
**Description of the need**
SmartMenus has a setting to turn a dropdown hover menu into a click/touch menu. I'd like to add that as an option when configuring a menu block.

---

PR by @laryn: https://github.com/backdrop/backdrop/pull/2980

**Comment by olafgrabienski** [comment]
I've had a look at the PR's sandbox site, it works well!

One suggestion: On the block configuration form for a *Dropdown menu*, there are two checkboxes now:

- Display menu toggle button on small screens
- Use a click to open, instead of a hover

I'd suggest to move the "Display menu toggle" option to the bottom, like in the config form for *Hierarchical tree*. Otherwise people might think, the "Use a click to open" text refers to the toggle button.

**Comment by laryn** [comment]
PR has been revised.

**Comment by olafgrabienski** [comment]
@laryn Thanks for moving the checkboxes, I think it's really better that way. Apart of that, the PR still works in the sandbox website, great! In my opinion, the new setting a useful addition.

**Comment by herbdool** [comment]
Code looks good

**Comment by klonos** [comment]
I also find this change very useful, as it exposes an already existing feature of the 3rd party library we use for the drop-down menus 👍 

The help text for the new feature was initially this:

> When checked, the menu will expand when clicked rather than when hovered.

Because that was simply repeating the label of the checkbox, I suggested this alternative:

> This option may work better on mobile, where there is no cursor, and menu expand/collapse relies on touch events.

And we finally ended up with this:

> Menus that don't appear or disappear on hover can be better for usability in some cases.

cc'ing @jenlampton, as she usually has better words for things 😄

**Comment by herbdool** [comment]
I wanted to note that this won't affect small mobile screens since the mobile menu already requires clicks. It might help with a large iPad, however. This option makes it behave more like Bootstrap.

**Comment by quicksketch** [comment]
This is in good shape and works well. In the introduction of the dropdown option, there was some intention of properly supporting "Menu Style Settings", where settings would be specific to a particular menu style. However, our other settings like "Show expanded" and "Starting Level" are also menu style specific, so we have precedent for style-specific settings already.

**Comment by jenlampton** [comment]
> This option may work better on mobile, where there is no cursor, and menu expand/collapse relies on touch events.

The current core menu already uses click/touch on mobile, where there is no cursor. This setting is to make click/touch replace the hover setting on **desktop**. This new description text is misleading. How about we remove the description text entirely if it is identical to the label?

> I wanted to note that this won't affect small mobile screens since the mobile menu already requires clicks.

Ah, yes. What @herbdool said :)

> This option may work better on devices where there is no cursor, and menu expand/collapse relies on touch events instead.

But the core menus already work on MOST devices where there is no cursor. I still don't think this text is helping...

> Menus that don't appear or disappear on hover can be better for usability in some cases.

Are you also recommending this text for the description for the checkbox? I'm not sure what this text has to do with the setting...

I'm creating a follow-up where we can debate the description text. This should not hold up the merge :) https://github.com/backdrop/backdrop-issues/issues/4253

**Comment by quicksketch** [comment]
Thanks! Merged https://github.com/backdrop/backdrop/pull/2980 into 1.x for 1.15.0.
