### ISSUE TITLE
[D8] Keep a snapshot of configuration directory in database

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#4212]
**Description of the need**

Odds are that some day someone will mess with active config directory by either improperly editing files or getting them deleted. And it won't be a trivial task to bring such a broken website back to functional state in case if no backups were taken to restore from.

**Proposed solution**

What if Backdrop could take a snapshot of the configuration directory on each cron and keep it updated and saved in the database, and use it to re-create configuration directory content in case if it is missing or broken?

**Real-life case**

Some relevant quotes from real-life case on Gitter of [November 17, 2019 4:28 PM](https://gitter.im/backdrop/backdrop-issues?at=5dd14af492a84f79fe82d804):

> @alanmels:  @serundeputy, this made me think: why don't we keep a snapshot of config files in DB just in case if the directory or some config files get deleted?
> 
> @serundeputy: maybe not a bad idea; prolly experiment w/ a contrib module and if it is working well and proven we could make a case for core
> i think there may be a core issue already about autobackups already; so we should read what is in there too

The closest one I could find in core issues is probably https://github.com/backdrop/backdrop-issues/issues/2409, but its subject is different. So I've decided to create a new feature request just in case if it's worth considering and implementing.

**Comment by stpaultim** [comment]
I think it's an interesting idea. It seems like a reasonable solution to a real problem. It's not clear to me that it's the best solution, especially in core. But, I would definitely experiment with this as a contrib module and advocate for potentially bringing it into core later - if it turns out either better, easier, or more effective than other solutions - for example: Backup and Migrate in core #2409.

I look forward to hearing what others have to say.

**Comment by Graham-72** [comment]
I like this idea. Whenever I do a core update of one of my sites I copy a snapshot of the active config folder to a private place on the server just in case of mistakes and I would be pleased if this was done automatically. But I need this as a roll-back copy just in case of mistakes in updating i.e. don't overwrite it immediately on update. [There is also my separate automatic daily snapshot of server webspace for drastic roll-back, 'belts and braces'.]

**Comment by BWPanda** [comment]
This sounds like a request to automatically backup config to the DB. But is the DB really the best place to backup config files to? And what's wrong with just backing up the files to a different folder?

I see this as definitely in the contrib space, not core. Unless Backup & Migrate ever gets into core, then maybe. But even then, backing up contrib to a separate folder, not the DB.

**Comment by indigoxela** [comment]
> But is the DB really the best place to backup config files to?

Rant: config stored in DB (as binary blob) is such an anti-feature in Drupal. :stuck_out_tongue_closed_eyes: 

Note that in the meantime Backup & Migrate also handles config, also scheduled, so this issue here might be obsolete. 

@alanmels are you using B & M to create config backups already? If so, it might be time to close this issue here.

**Comment by alanmels** [comment]
Yea, in retrospect I'm not sure why I didn't give Backup & Migrate a try. Let's close this one.
