### ISSUE TITLE
Typo in select.inc.

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#4261]
**Description of the bug**
The code comment on line 1449:
```
  /**
   * Implements SelectQueryInterface::addField().di
   */
  public function addField($table_alias, $field, $alias = NULL) {
```

Note the stray "di"

---

PR: ?

**Comment by jenlampton** [comment]
no PR here. removing milestone.

**Comment by ps23Rick** [comment]
Hi Jen at-al. I'm looking to tackle some easy low hanging fruit as it were.. This sounds like a good start -- is this ok to open a PR on?  I just tackled a task for the headless module elsewhere here on GitHub.  Just thought I'd check.. thx

**Comment by jenlampton** [comment]
> is this ok to open a PR on?

Yep! Go ahead, and thanks!

**Comment by ps23Rick** [comment]
Ok.. The PR is open on this one.. One of the CI tests failed but in looking at the log I think its some sort of non-code issue?  Perhaps someone with more background than I do on this CI engine can figure that part out..?  Thx!

**Comment by jenlampton** [comment]
> One of the CI tests failed...

Yes, we get random test failures from time to time, we are working to identify and fix them as they crop up! 

> The PR is open on this one.

I don't see a link to your PR, would you please add one?  (Also: if you put the text 'Fixes [link]` in the PR description GitHub will add the link automatically into the sidebar on this issue)

You are also welcome to edit the top post in any issue and add a link to the PR so that others can find it later w/o needing to scroll through all the comments.  We've been doing that on most core issues (since before GitHub added the sidebar list of PRs)

**Comment by ps23Rick** [comment]
ok.. I'm slowly getting used to GitHub.. I've got 30 years of dev experience but have always used proprietary CM tools.. Slowly but surely.. lol

**Comment by jenlampton** [comment]
This looks great! RTBC :)

**Comment by BWPanda** [comment]
Merged https://github.com/backdrop/backdrop/pull/3112 into 1.x and 1.15.x. Big thanks to @ps23Rick for the PR and to @docwilmot and @jenlampton for finding/reviewing!
