### ISSUE TITLE
I don't see maintenance page after putting site in maintenance mode

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#4264]
Sometimes* when I put the site in Maintenance mode, then log out, I still see the regular frontpage, not the maintenance page. Hard-refreshing my browser doesn't help. Only clicking a link to view a different page displays the proper maintenance page, or clearing all caches (via Drush) then refreshing my browser.

Is there a way we can avoid this by maybe automatically clearing caches when the site's put in maintenance mode, or wouldn't that work if the user keeps browsing the site a bit before logging out...?

(* This makes it tricky - sometimes it works and sometimes it doesn't... Not sure how to reproduce.)

**Comment by indigoxela** [comment]
That really sounds like a caching thing, at least this is the first idea I have.

If you have access to the database, you could check for an entry in table cache_page. Then check if the problem only occurs when a front page entry exists in that table.

If so, a cache flush might be necessary when switching to maintenance mode (not sure).

**Comment by klonos** [comment]
> Is there a way we can avoid this by maybe automatically clearing caches when the site's put in maintenance mode

Hmm, depends on how one sees this functionality. If the intention is to have cached pages be served to site visitors (while in maintenance mode), and only hit the maintenance page when/if cache expires, then automatically clearing caches would defeat the purpose. So I think that this behavior may be by design (although admittedly a UX WFT for the person that puts the site in maintenance mode).

**Comment by BWPanda** [comment]
> depends on how one sees this functionality

Good point... :+1:

**Comment by BWPanda** [comment]
@indigoxela Thanks for the tip. It turns out that it is a caching issue, but even after clearing the page cache on submission of that form, I still had to hard-refresh my browser as its caching was having an effect too.

But doing both fixes it :smiley: Here's the code I used in case it helps anyone else:

```php
/**
 * Implements hook_form_FORM_ID_alter() for system_site_maintenance_mode.
 */
function mymodule_form_system_site_maintenance_mode_alter(&$form, &$form_state, $form_id) {
  $form['#submit'][] = 'system_clear_page_cache_submit';
}
```
