### ISSUE TITLE
Non standard property “zoom” [CSS]

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#4276]
**Description of the bug**
In the developer console I often see this on Drupal 7 and Backdrop sites:

> This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”.

The [Mozilla docs](https://developer.mozilla.org/en-US/docs/Web/CSS/zoom) say:

> This feature is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user. There may also be large incompatibilities between implementations and the behavior may change in the future.

A [search of the codebase](https://github.com/backdrop/backdrop/search?q=%22zoom%3A+%22&unscoped_q=%22zoom%3A+%22) suggests there's one usage of this in the `system.css` file. Do we need it?

---

PR: https://github.com/backdrop/backdrop/pull/3145

**Comment by BWPanda** [comment]
Looks like it's used for IE7 support. Are we still supporting that...?

**Comment by laryn** [comment]
Don't think so? Also, [IE7 has 0.01% of market share](https://caniuse.com/usage-table), so probably safe to ax this line in the CSS.

**Comment by klonos** [comment]
I don't have any strong opinion on this one. https://caniuse.com/#feat=css-zoom says that 93.79% of globally-used browsers support the property:

![Screen Shot 2020-05-19 at 10 54 11 pm](https://user-images.githubusercontent.com/2423362/82372015-de294180-9a23-11ea-8b82-d13d971e1f5d.png)

It seems that it is supported by every current version of all popular browsers, with the exception of Firefox (4% global usage), Firefox mobile (0.23%), and Opera mini (0.69%) - so ~5% of users really.

We could invoke our [3rd principle](https://backdropcms.org/philosophy#principles) "Focus: Include features for the majority."

> Backdrop core should only include features and tools that benefit the majority of sites that are running it.

The oxymoron here is that we have this bit of code in place in order to serve a browser that has less than 0.02% usage:

![Screen Shot 2020-05-19 at 11 07 37 pm](https://user-images.githubusercontent.com/2423362/82373058-a9b68500-9a25-11ea-95f9-a227a4e31023.png)

...yet this error is thrown by browsers that are the least used globally - none of the popular browsers will complain about the usage of `zoom` 😅

**Comment by indigoxela** [comment]
Yes, please let's get rid of that silly "zoom:" - the browser this workaround was necessary for is dead and gone for so long now.
(I admit, I danced on its grave :smiling_imp:)

**Comment by BWPanda** [comment]
Thanks @laryn and @klonos. I've merged https://github.com/backdrop/backdrop/pull/3145 into 1.x.

**Comment by BWPanda** [comment]
I don't feel this is an important enough change to worry about also merging it into 1.19.4...
