### ISSUE TITLE
Enforce password value on pass reset form (set required)

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#4281]
**Description of the bug**
When following a password reset link, the input fields aren't mandatory. It's possible to submit the form without any values set and one gets logged in.

The message "Your account password has been updated." shows, but that's of course wrong. Nothing has changed in the database (table users).

**Steps To Reproduce**
To reproduce the behavior:
1. Go to /user/password and enter your user name to get a reset link
2. Follow that link
3. Submit that form without entering any input

**Expected behavior**
I'd actually expect those password fields to be mandatory.

![screenshot-reset-form](https://user-images.githubusercontent.com/842066/72665569-ed629900-3a09-11ea-8b35-568ea2348eb4.png)

**Additional information**
- Backdrop CMS version: 1.15.x-dev 

------
PR by @indigoxela = https://github.com/backdrop/backdrop/pull/3044

**Comment by alanmels** [comment]
I believe the effect should be completely opposite: not to show the form to user at all and let him pass  to `/user/uid/edit` page if he really wants to set new password as it's done on Drupal. Because there are cases when one-time login is used just to get access and not to actually change the password.

For example, as a Drupal-specific hosting provider we often help our customers with various Drupal-related tasks, and when requested we just SSH in, run `drush uli` command for the respective website and instantly login without asking customer to share their admin password. 

It would be nice to have the same easy way to get in to Backdrop from CLI. If the above enforced, then we would have to set new password or request from customers each time we need to get in. And it becomes terribly problematic and even risky (in case if we start sending passwords back and forth) when dealing with hundreds of websites.

**Comment by indigoxela** [comment]
> not to show the form to user at all and let him pass to /user/uid/edit page

That might seem like a smart idea, but wait... , there seems to be a misunderstanding. :wink: 
This is a reset form just for users to reset their password. NOT for hosting provider support.
Please don't confuse people reading this thread.

> It would be nice to have the same easy way to get in to Backdrop from CLI.

That's something _completely_ different. Please search the console projects (drush/drop/b) for a solution, as your request has nothing to do with the reset form.

**Comment by alanmels** [comment]
@indigoxela Just to be clear: the one-time authorization link that is sent to reset password and that the `drush uli` command generates is exactly the same one and they work in exactly the same manner. Please run some tests to see how both Drupal 7 and 8 works and how Backdrop is shifting away and making some things more difficult.

**Comment by indigoxela** [comment]
@alanmels I don't need to run any tests, I'm aware what you're after. The thing is, that using the password reset link and form for support tasks is some sort of abusing it.
It's not meant to do that.

**Comment by alanmels** [comment]
@indigoxela I am sorry I often look at things from hosting provider, however the feature (being able to log in without changing password) is also important for developers. I didn't want to highjack your issue, but then creating another one asking just the opposite of what you are asking here would be not correct. Let's be constructive and consider all options here in the issue you already created.

Please run some tests and see how Drupal works: the one time authentication link is just that - for providing instant access to anyone how got that link regardless via e-mail or command line; it does not enforce people to reset their passwords, it just takes them to `/user/uid/edit` page, so whoever wnats could indeed set new password. However all the developers, support staff members can proceed without changing password. And it make perfect sense as otherwise Backdrop would be making hard things for not only hosting vendors, but developers in the first place, who need to login to application sites (Drupal, Backdrop) probably more often than the end-users themselves.

So I do request the one-time authentication link does not even stop on that form, but instantly takes user to `/user/uid/edit` page instead.

**Comment by quicksketch** [comment]
> Because there are cases when one-time login is used just to get access and not to actually change the password.

Backdrop provides the ability to automatically log you in (without setting a password) by adding `/login` to the end of the URL. If you use Drush today with Backdrop you can see this is already the case:

```
$ drush uli
http://localhost/user/reset/1/1579546056/PWfQl7qf--foVGCHthZbz8VmE-pecBAH04Rd8ASOmgY/login
```

But if you use a password reset link, the `/login` is omitted in the URL sent in the email. Then the user is only prompted to set a password, completing the form logs them in.

I agree with @indigoxela that these fields should be required. Looks like it might just be a case of a missing `#required` attribute.

For reference here's the issue where we changed the behavior from Drupal 7: #140

**Comment by BWPanda** [comment]
Yes, I was just testing this when @quicksketch beat me to it :smile: 

I did a password reset from `/user/password` and the link in the email I got was: `https://panda.id.au/user/reset/[blah/blah/blah]`
That takes me a to a 'Reset password' page with the login form @indigoxela screenshotted above.

Then I did `drush uli` and it gave me this link: `https://panda.id.au/user/reset/[blah/blah/blah]/login`
That takes me to the homepage, logged in, with the message "You have used your one-time log-in link and are now logged-in."

@indigoxela is referring to the first link, while @alanmels is referring to the second. Two different use cases, both valid points (and I agree with both). But this issue is only about the first link, and I agree that the fields should be required.

**Comment by alanmels** [comment]
Because, drush for Backdrop is still missing lot's of commands we frequently need on AltaGrade, we've been using [Drop](https://github.com/backdrop-contrib/drop) instead, which does not add the `/login` part. I will fix that today. 

Thank you, @quicksketch and @BWPanda for pointing out the difference in the link, and thank you @indigoxela for initiating this discussion that helped to figure out important feature. Taking into account there is a way to instantly login I totally agree with your suggestion to make those fields required.

**Comment by indigoxela** [comment]
I've created a PR, tests are passing now.

@alanmels to clarify: this doesn't conflict with the "silent login" link (with /login attached), as created by drush.

The tests could get improved, as now there are two very similar tests regarding one-time login.

We might better check that:
1. password reset form requires a value
2. "silent login" works properly (by attaching /login)

**Comment by stpaultim** [comment]
This works for me. 

But, I notice that we only ask for a new password once when a user creates a new account. We only ask for a a new password once when an authenticated user chooses to change their password. 

Should we ask for it twice when a user uses password reset to create a new password. 

I don't feel strongly about this. But, it seems like Backdrop CMS has already made a decision that we don't want to require the double password thing. So, why not be consistent. 
(That's all I have to say about this :-) 

Thanks for your work on this issue.

**Comment by indigoxela** [comment]
> ... it seems like Backdrop CMS has already made a decision that we don't want to require the double password thing. So, why not be consistent.

Good point. As we're already working on it, why not switch to a single field?
```
  $form['pass'] = array(
    '#type' => 'password',
    '#password_toggle' => TRUE,
    '#password_strength' => TRUE,
  );
```
Or are there any concerns? Who is able to decide that?

**Comment by indigoxela** [comment]
> Or are there any concerns?

I can answer that myself. Yes, there's a concern: Changing the form field type _could_ be a contrib-breaker, for instance for passphrase_policy module. This has to be evaluated, though.

Setting the same field to required is a task for a simple bugfix release, changing the form item type requires more evaluation and probably isn't appropriate for a bugfix release.

@stpaultim I'd rather recommend to create a new issue for the form field type change.

Let's stick with the simple change here.
Please test and review.

**Comment by herbdool** [comment]
I agree with sticking to the simple bug fix for now. Though I do think it needs a test to ensure password is required before it can be approved.

**Comment by herbdool** [comment]
Oh looks like it does have new tests.

**Comment by herbdool** [comment]
Marking this ready based on my review and @stpaultim test.

**Comment by quicksketch** [comment]
Thanks everyone! I've merged https://github.com/backdrop/backdrop/pull/3044 into 1.x and 1.16.x.

I like @indigoxela's suggestion to eliminate the confirm field and use the password toggle instead, but that would probably be a 1.17.0 change.

**Comment by klonos** [comment]
Follow-up to change the password to a single field + toggle: #4440
