### ISSUE TITLE
With multiple image fields, only one thumbnail shows up per save

### ISSUE THREAD

**Issue by stpaultim** [backdrop/backdrop-issues#4284]
**Description of the bug**
If a content type has more than one image field. When a user goes to create a new node, only one of the images fields displays the thumbnail, per save. Each time I have the node, I can load one more image and see the thumbnail immediately, along with the thumbnails for all previously save images. 

NOTE: Even when thumbnails are not visible, they image is loaded upon save and the thumbnail will be visible upon editing the node. 

HOWEVER, on a field that allows more than one image per field, you can not add additional images until the thumbnail shows up. So if you have two images fields, one of which allows multiple images. You must load images to the multiple image field FIRST or you may not be able to enter all your images without saving. 

This issue based upon report in the forum: https://forum.backdropcms.org/forum/content-type-two-image-fields

**Steps To Reproduce**
To reproduce the behavior:
1. Create a new content type with three image fields. On any one of the images fields, allow unlimited images for that field. 
2. Create a new node and upload one image to each image field. Note that whichever field you use to upload your image first, will work as expected.  However, for the second and third fields, the thumbnail will not display. 

If you try to enter images to the multi-image image field AFTER adding an image to another field, the thumbnail will not display and you will only be able to one image.

3. Save your node. Notice, that all images are saved (even if there was no thumbnail). 
4. Edit node and notice that thumbnails are visible for all images. But, that if you try to add new images, the thumbnail will only show up in the first field you edit. 
5. Repeat. 

**Expected behavior**
I expect that I can upload all the images at once and that I will see all the image thumbnails before saving the node. 

**Additional information**
I tested this on a fresh version of Backdrop CMS 1.15.0 with no additional modules or customizations. 

![Create_Test___Backdrop](https://user-images.githubusercontent.com/3144571/72846835-fb612580-3c66-11ea-9742-73550b0a7ec4.png)

![Create_Test___Backdrop](https://user-images.githubusercontent.com/3144571/72847029-58f57200-3c67-11ea-97e0-588035a744bb.png)

**Comment by indigoxela** [comment]
I could reproduce it.

The problem doesn't seem to be caused by the image browser. I disabled it for both fields, but the problem persists. In the second field (unlimited values) the thumbnail doesn't show up on node creation, but after the node has been saved once, everything is fine - if the first (single value field) has an image.

If I remove all images on an existing node, the problem strikes again.
Something in the single-image field (if empty!) seems to be a blocker for the second (multi-value) field.

Nothing in the browser console, nothing in dblog.

**Comment by indigoxela** [comment]
Further digging: It doesn't matter, if it's a multivalue field. Simply the fact that there are several image fields on the same form seems to cause the problem.

And the behavior is just like it is when disabling javascript in the browser. So very likely it's a javascript bug (possibly in file.js).

I tried to find out more in [Backdrop.behaviors.fileButtons](https://github.com/backdrop/backdrop/blob/9ed127933df9994ec3e96f9110520359451a183d/core/modules/file/js/file.js#L32), but... as soon I put in a console.log() there in attach/detach, everything works fine.

Aha, a bug that vanishes as soon as one tries to inspect it more closely... May the force be with someone else.

**Comment by laryn** [comment]
I wonder if it somehow related to the image library select button that was just added?

**Comment by indigoxela** [comment]
@laryn no, that was already checked, see my [previous comment](https://github.com/backdrop/backdrop-issues/issues/4284#issuecomment-577059639).

**Comment by pgwa** [comment]
Same problem with previous version 1.14.3

**Comment by stpaultim** [comment]
The user that originally reported  this issue, just asked for an update in the Forum.
https://forum.backdropcms.org/comment/3830#comment-3830

**Comment by indigoxela** [comment]
Some more head scratching...

https://github.com/backdrop/backdrop/blob/c7b3b150369d47df2f786f6cf8da35052c7d3af2/core/modules/file/js/file.js#L23-L26

If I comment out the line that removes the Backdrop.file.autoUpload handler, things work as expected.

The problem seems to be that this `detach` runs twice - with different contexts.

1. The complete node form (!)
2. The current ajax wrapper

And the first run removes all auto-upload handlers, also from unrelated file fields, so there's no more auto-upload functionality.

**Comment by indigoxela** [comment]
I think, we're very close to a solution - here's a [PR](https://github.com/backdrop/backdrop/pull/4029).

There are still open questions, though. From the docs for that third param to function `detach`:

```
 * @param trigger
 *   A string containing what's causing the behaviors to be detached. The
 *   possible triggers are:
 *   - unload: (default) The context element is being removed from the DOM.
 *   - move: The element is about to be moved within the DOM (for example,
 *     during a tabledrag row swap). After the move is completed,
 *     Backdrop.attachBehaviors() is called, so that the behavior can undo
 *     whatever it did in response to the move. Many behaviors won't need to
 *     do anything in response to the element being moved, but because IFRAME
 *     elements reload their "src" when being moved within the DOM, behaviors
 *     bound to IFRAME elements (like WYSIWYG editors) may need to take some
 *     action.
 *   - serialize: When an Ajax form is submitted, this is called with the
 *     form as the context. This provides every behavior within the form an
 *     opportunity to ensure that the field elements have correct content
 *     in them before the form is serialized. The canonical use-case is so
 *     that WYSIWYG editors can update the hidden textarea to which they are
 *     bound.
```

In context of the node form and auto-upload - isn't the whole detach pointless here?

1. unload - why removing handlers from something that gets removed anyway?
2. move - why removing handlers from something that might still need them?
3. serialize - why removing handlers from something that gets freshly added to a form?

So the correct fix could be to remove that whole detach from Backdrop.behaviors.fileUploadChange. But I'm not completely sure. Testing and feedback welcome!

**Comment by kswan** [comment]
@indigoxela I tested your PR and it is a big improvement. The auto-upload is working. 

I should mention that my test case is a bit different from this issue, but I believe the underlying problem is the same. My issue is shown in #5569. 

I minor issue I noticed is that the progress bar shows for the first field, but not the others.

Thank you for your work on this.

**Comment by kswan** [comment]
@indigoxela I tested removing the detach section from Backdrop.behaviors.fileUploadChange and Backdrop.behaviors.fileButtons. With the detach sections removed, the auto-upload and progress bar worked for all fields.

This is what I tested:
```
/**
 * Attach behaviors to managed file element upload fields.
 */
Backdrop.behaviors.fileUploadChange = {
  attach: function (context, settings) {
    $(context).find('input[data-file-extensions]').once('validate-extension').on('change', Backdrop.file.validateExtension);
    $(context).find('input[data-file-auto-upload]').once('auto-upload').on('change', Backdrop.file.autoUpload).each(function() {
      $(this).closest('.form-item').find('.file-upload-button').hide();
    });
  },
//  detach: function (context, settings, trigger) {
//    if (trigger === 'serialize') {
//      return;
//    }
//    $(context).find('input[data-file-extensions]').off('change', Backdrop.file.validateExtension);
//    $(context).find('input[data-file-auto-upload]').off('change', Backdrop.file.autoUpload);
//  }
};

/**
 * Attach behaviors to the file upload and remove buttons.
 */
Backdrop.behaviors.fileButtons = {
  attach: function (context) {
    $('input.form-submit', context).once('file-disable-fields').bind('mousedown', Backdrop.file.disableFields);
    $('div.form-managed-file input.form-submit', context).once('file-progress-bar').bind('mousedown', Backdrop.file.progressBar);
  },
//  detach: function (context) {
//    $('input.form-submit', context).unbind('mousedown', Backdrop.file.disableFields);
//    $('div.form-managed-file input.form-submit', context).unbind('mousedown', Backdrop.file.progressBar);
//  }
};

```

**Comment by indigoxela** [comment]
@kswan many thanks for testing! It's a bit uncommon to start a fresh PR when there already is one, though. Especially if it's more or less the same approach.

Re your change in Backdrop.behaviors.fileButtons ... I'm sure - this needs further testing and recherche.

**Comment by indigoxela** [comment]
I updated my PR to reflect the latest findings. Yes, also in Backdrop.behaviors.fileButtons the detach is useless. For the same reasons like in Backdrop.behaviors.fileUploadChange - it makes no sense to remove handlers, no matter if the trigger is unload, move, or serialize. And especially with serialize it does harm (breaks progressbar).

**Comment by kswan** [comment]
@indigoxela Excellent. Thank you. 
Sorry for the unhelpful PRs.

**Comment by argiepiano** [comment]
Code LGTM. I've tested in several different situations with single and multiple value image fields and the fix seems to do its job. Thanks @indigoxela and @kswan!   (I cannot help but wonder why those detach methods were added to those functions? They are inherited from D7).

**Comment by indigoxela** [comment]
> I cannot help but wonder why those detach methods were added to those functions? They are inherited from D7

They're inherited, but Backdrop does things differently. The auto-upload functionality has been added in #1199, Drupal 7 does no automatic upload on file selection. Drupal 9 does, but limits the trigger to "unload". They remove the handler and then remove the element anyway. Which is odd, but does not break anything.

**Comment by quicksketch** [comment]
The PR at https://github.com/backdrop/backdrop/pull/4029 gave me pause... I would think unloading behaviors would be a best-practice that we should encourage. However, I see the problem created here and @indigoxela's arguments seem solid: there's no need to manually remove behaviors from DOM elements that are about to be removed.

There are some situations where `unload` is still useful though, such as if two parts of the page are interacting with each other, or if a part of the page is removed and it should clean up cruft left in the global `Backdrop.settings` variable. However, that isn't happening here and removing the unload has no detrimental effect. The behavior attachment also already has `.once()` guard classes to prevent double-binding, so we're safe there too.

Since I can't see any problem with this and we now have multiple confirmations of this fixing the problem, I've merged https://github.com/backdrop/backdrop/pull/4029 into 1.x and 1.21.x. Thank you @indigoxela, @stpaultim, @kswan, and @argiepiano for fixing this bug!
