### ISSUE TITLE
[DX] Themes with color support: CSS changes not taking effect unless theme settings are re-saved.

### ISSUE THREAD

**Issue by stpaultim** [backdrop/backdrop-issues#4295]
**Description of the need**
I just ran into a situation in which I made a css change and could not get it to take effect, regardless of how many times I cleared the browser cache or the Backdrop cache. 

I examined the css and the new rule was there in the css, the theme was loading the css sheet, but I could not find the rule in the inspector. 

I finally realized that I am using the color module for this site and that the color module is rewriting that particular css sheet and storing it in files/color

The ONLY way I could get my new css change to take effect, was to resave the color settings for the theme. It's always weird when you are forced to resave something that you haven't changed (or are not aware that you have changed). 

**Proposed solution**
Add a "rebuild color scheme" link in the admin menu that basically just resaves (and rebuilds) the color files. Put this near the "clear cache" link/button. 

Then if you are trouble shooting a theme issue and doing the obvious things, like clearing the cache, you'll also be reminded to rebuild your color settings - if it makes sense. 

**Alternatives that have been considered**
???

I would love to hear alternative ideas to help new users in this kind of situation. 

**Additional information**
Most experienced developers don't use the color module, they hard code their color changes into their theme. I ran into this while working on Tatsu, which I'm specifically building for users that are likely to use the color module. 

This type of developer (or site architect) is not likely to think about how the [color module works](https://www.triplo.co/blog/color-module-backdrop-cms) and recognize the need to resave their settings. 

___

PR by docwilmot: https://github.com/backdrop/backdrop/pull/3110

**Comment by stpaultim** [comment]
We talked about this on the DEV call today. 

I believe that @hosef is going to create a PR (maybe elsewhere) that rebuilds the color module style sheets anytime that the cache is cleared.

**Comment by hosef** [comment]
I spent some time looking into this, but it appears that there is currently no way to respond to clearing the caches.

I did have an idea about checking for a particular cache entry and rebuilding the files if it doesn't exist. However, that seems like a bad work around to the problem that there is no hook that gets called after  a cache clear of any kind.

Should we create a hook_post_cache_clear()? It may not be useful for most sites, but I think it would enable some very interesting functionality such as the ability to warm critical cache bins so that users never saw a performance hit.

**Comment by docwilmot** [comment]
Could we just add color resetting directly into `cache_clear_all()`?

**Comment by hosef** [comment]
There is an issue to mark that function as deprecated. #2158
In general, I think it's better to make it work for any module that might want to respond to cache changes than to make specific workarounds just for the color module since a lot of people just want to disable the color module and use a custom theme.

**Comment by docwilmot** [comment]
>There is an issue to mark that function as deprecated. #2158

Then we could add code to either:

`backdrop_flush_all_caches()`
`system_rebuild_theme_data()`
`backdrop_theme_rebuild()`

> In general, I think it's better to make it work for any module that might want to respond to cache changes

I dont get this. We're trying to get color styles to reset when we flush caches, isn't that the point?

**Comment by stpaultim** [comment]
It looks like this would have helped this person who was asking for help in the forum:
https://forum.backdropcms.org/forum/does-not-recognize-changes-subtheme-basis

**Comment by stpaultim** [comment]
> I dont get this. We're trying to get color styles to reset when we flush caches, isn't that the point?

Just to be clear, we don't want the color styles to reset to the original. We just want to rebuild the stylesheets that are effected by the color module. 

The color creates new versions of some stylesheets that override the originals, if a change is made to the original stylesheet that change is not reflected in the color module versions and is not reflected on the site. The idea is that when we "flush the caches" these stylesheets are rebuilt and will include any changes to the original stylesheets.

**Comment by docwilmot** [comment]
Right, I get  that, but point is we want this to happen when caches clear, so why a hook? Why not just trigger it in the process of clearing caches? We dont use a hook for any of the other individual cache clearing options.

**Comment by docwilmot** [comment]
Or: Add a function to Color that does this rebuild (maybe there already is such a function), and add a link to Admin Bar called "Rebuild color styles" that calls this function; and then add that function to `_admin_bar_flush_cache()` so it also runs when you click "Flush all caches"

**Comment by docwilmot** [comment]
@stpaultim PR available

**Comment by stpaultim** [comment]
I assume I need to test this locally, since I can't think of a way to verify what is happening in the test sandbox.

**Comment by klonos** [comment]
Code LGTM @docwilmot ...thanks 👍 

@stpaultim if you can provide some basic steps to reproduce the issue, I could test on my local.

PS, I find this to be a DX bug, so I have re-labeled it accordingly. Please feel free to change back if this change does not make sense.

**Comment by klonos** [comment]
...while waiting for some STR, so that I can test the specific issue at hand, I've done some more generic testing, and here's what I've noticed:

1. While Basis is set to the "Basis (default)" color set/scheme, the "Color scheme" option is not shown under "Clear caches". Is that expected? ...I mean, there are no color .css files generated for the default Basis color scheme, so I guess so(?).

2. After switching to any color palette and saving the theme settings, the "Color scheme" option is still not shown in the admin bar, until caches are cleared at least once. Should we be clearing caches when submitting theme settings?

3. After switching back to "Basis (default)" and saving, the "Color scheme" option is still not shown in the admin bar. Again, is that expected? ...I mean, switching back to "Basis (default)" makes it so that new .css files are generated under /files/color. Shouldn't these be cleared instead? If not, then I see no consistency with point 1 above.

In general, I think that `$theme_config->get('color')` should be returning TRUE for Basis (any theme with color support in general), even when it is set to be using the default color scheme (no color-generated .css files).

**Comment by docwilmot** [comment]
> While Basis is set to the "Basis (default)" color set/scheme, the "Color scheme" option is not shown under "Clear caches"

that is correct. I suppose we cpould make it so that the link always shows? More input/opinions would help.
> After switching to any color palette and saving the theme settings, the "Color scheme" option is still not shown in the admin bar, until caches are cleared at least once. 
> After switching back to "Basis (default)" and saving, the "Color scheme" option is still not shown in the admin bar. 

Good catch. Its actually Admin Bar cache that needs clearing, so shouldnt be an issue to add that to the theme settings form submit.

**Comment by klonos** [comment]
> I suppose we could make it so that the link always shows?

On my local, I have experimented with `if (!empty(color_get_info($theme)))` as the conditional, which seems to work better (and less lines of code as a bonus). Still, I got some UX weirdness when I wanted to clear color caches from the admin theme (trying to simulate the case where a person would have multiple tabs open, both backend and frontend). So I think either show the option unconditionally as you suggest (having the code live in Color module code already covers `if module_exists('color')`), or loop through all themes, and have the option be shown when at least one active theme has color support.

> Its actually Admin Bar cache that needs clearing, so shouldnt be an issue to add that to the theme settings form submit.

👍 ...if the future we realize that there are other caches that need clearing when saving theme settings, we can add them in. For now, clearing color caches (actually rebuilding the .css file) would work 😉

**Comment by hosef** [comment]
I took a look at the PR and tested it on my local environment, and I noticed a few things that I think might need to be addressed

- It does not appear to work unless you specifically click the button to clear the color scheme. I tried using the Flush all caches button, running cron, and using drush cc all. This would make it hard to find for anyone who is new to Backdrop and might not know it is there.
- It calls cache clear all inside of the function that re-saves the color settings. Since this is supposed to happen when caches are already being cleared, we should not do this because any module that has an expensive rebuild option could potentially need to do that twice each time.
- It only rebuilds for the current theme. If you edit 2 themes, such as having an admin theme with color support, and then run this, the second theme will still show the old colors.

In light of these things, I think it might be best to trigger the rebuild from `backdrop_clear_css_cache()` although I still don't like the idea of putting things like that in the includes folder. That would give us the benefit of not needing to provide extra links for the user to find and click and would make it work with other methods of cache clearing as well.

**Comment by docwilmot** [comment]
@hosef all good points.

**Comment by klonos** [comment]
...it seems that we are clearing all caches in system_theme_settings_submit() after all btw: https://github.com/backdrop/backdrop/blob/1.x/core/modules/system/system.admin.inc#L478

**Comment by docwilmot** [comment]
New PR addressing issues from @hosef

**Comment by hosef** [comment]
I reviewed the code, and it looks good to me. I tested clearing caches on the test site and didn't see any errors in the log.

**Comment by quicksketch** [comment]
Instead of putting Color module support directly in common.inc, we could use `hook_flush_caches()` instead. https://github.com/backdrop/backdrop/pull/3110/files#r415120485

Code looks fine, we just need to change where it gets called in one place.

**Comment by docwilmot** [comment]
I've stared at this as long as I can, and I cannot think of any reason why `hook_flush_caches()` wouldnt be reasonable. The new `color_rebuild_settings()` saves color config based on color info, not anything to do with CSS files. And the cache clearing functions in `hook_flush_caches()` don't seem to influence color changes at all. So the two should be doable independently AFAICT.

**Comment by docwilmot** [comment]
Done and tested and works, no errors or issues yet.

**Comment by hosef** [comment]
I have reviewed and tested the latest changes and they are working as expected.

**Comment by quicksketch** [comment]
Super, thanks for rearranging that @docwilmot and thanks @hosef for testing a second time. This sounds like it also inadvertently will fix doing config syncs with new color settings between environments. Sweet.

Merged https://github.com/backdrop/backdrop/pull/3110 into 1.x and 1.15.x. Thanks!
