### ISSUE TITLE
Enhancing testing performance. Also, PHPUnit?

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#4306]
I haven't timed it, but running tests (either via the Testing module in Backdrop or on GitHub when submitting a PR) seems to take a long time. I'm wondering if there's a way of enhancing the performance of tests to make them run better/faster...?

I'm no expert in this area (hence the 'Question' label for this issue), but is there any room for re-writing tests to be more performant?

Also, we use SimpleTest which, if I understand correctly, was custom written for Drupal. What about moving to PHPUnit instead? I know we don't want to use existing technologies just because they exist (e.g. Symphony, Composer, etc.) like Drupal 8 does, but would there be any performance improvement there?

---

PR by @hosef: https://github.com/backdrop/backdrop/pull/3076

**Comment by klonos** [comment]
I do not have hard numbers, but I recall that when we originally implemented the whole ZenCI thing, php5 tests would take 7-8mins or so, and php7 tests would take 4-5min. Over the years, I've gradually noticed these times go up to perhaps 10mins and 7mins respectively.

I think that this is expected, considering the amount of code and respective tests added over the years, but if it seems alarming to others, then perhaps we should look into it a bit further.

**Comment by quicksketch** [comment]
For what it's worth, Drupal's tests (both D7 and D8) range from 1 - 1.5 hours. Ours used to take about 50 minutes years ago before Gor optimized the installation process. Now instead of installing Backdrop once for each test, it installs it once for each install profile and then caches the initial state.

I think we have the opportunity to get some other easy wins just by using a newer version of PHP (we still run 7.0 and 5.3) and possibly faster(?) servers. AFAIK we're running on Google Cloud services, which Zen.CI is kindly providing to us for free. One issue we have with that service is that the machines are ephemeral. So sometimes you'll see tests run half-way through but then it has to start all over because the server was decommissioned. If test run times get longer, this will become more of a problem.

As for optimizations to the tests themselves: a beneficial change is to switch at many tests as possible from the Standard Profile to the Testing Profile. Combining multiple small tests that cover similar functionality into larger ones is also faster, since a re-install isn't needed between each one.

One simple change we could do help identify expensive tests is put the execution time next to each one. That could at least point out tests that are expensive:

![image](https://user-images.githubusercontent.com/100206/74472929-9b216600-4e57-11ea-9e81-ba107108964a.png)

I believe PHPUnit has limited usefulness in our situation because most APIs require a fully working Backdrop install (such as having a database back-end). PHPUnit is mostly used for ensuring that APIs work independently from the rest of the system. It's speed is because it's not dependent on any outside systems, it's just PHP code running to ensure inputs and outputs of functions and classes return the expected value.

Overall though, a test run time of less than 10 minutes with the amount of coverage we have is incredible. Optimization is always good but we're already in an exceptionally good place for the amount of integration testing we have.

**Comment by BWPanda** [comment]
> Optimization is always good but we're already in an exceptionally good place for the amount of integration testing we have.

Good to know :+1: I didn't really have/know of a reference point, so glad that we're doing pretty good as is.

**Comment by hosef** [comment]
So, I thought this was going to be a quick and easy change, but I was thwarted by the integration testing integration tests. :\

Essentially I had to add the text from the timing to an actual test. This seems to work fine for now because the stub test is so fast that it gets rounded to 0 seconds every time If it ever took 0.001 seconds, then it would cause the tests to fail.
I think it might be fine to change the test so it ignores the timing part or matches a regex, but I wanted to see what other people thought about that.

**Comment by BWPanda** [comment]
> I think it might be fine to change the test so it ignores the timing part or matches a regex

Yes, I was about to suggest seeing if you can change `assertEqual()` to something like `assertStartsWith()` (not sure if that's a real thing) so that the timing part is ignored...

**Comment by hosef** [comment]
I changed the test to use `strpos()` wrapped in `assertTrue()` and testing for all the text right up to the number of seconds. This should cover the old test case while also not breaking if the tests ever take longer to complete.

**Comment by BWPanda** [comment]
@hosef Your PR adds the "Took N seconds to run" text to the end of each test:

![image](https://user-images.githubusercontent.com/2385329/74560421-31947b00-4f6f-11ea-855f-4d5106c46091.png)

Here's how ZenCI shows times next to the build steps:

![image](https://user-images.githubusercontent.com/2385329/74560575-8506c900-4f6f-11ea-8574-2cc8ad7e01ad.png)

And here's TravisCI's:

![image](https://user-images.githubusercontent.com/2385329/74560616-994ac600-4f6f-11ea-8774-e31477299244.png)

My point being that putting the times in a sentence kind of hides it next to all the other text. So in order to make it more obvious and readable, I suggest changing "Took N seconds to run" to something like "[N sec]" or "[Ns]" instead (the brackets will also help separate it from the other text).

**Comment by hosef** [comment]
I was working on another change already and decided to implement your suggestion in there, so the number is in brackets now.

Additionally, I made a change so that running the tests from the UI can also use the profile caching mechanism that @quicksketch  mentioned. In my quick tests, it appears to make the tests anywhere from 2x to 10x faster depending on which profile they use.

**Comment by BWPanda** [comment]
![image](https://user-images.githubusercontent.com/2385329/74564611-242fbe80-4f78-11ea-9802-8add4debd01e.png)

Ooh, very nice! :smiley:

**Comment by hosef** [comment]
Changing the status because I want to make some more changes.

**Comment by klonos** [comment]
I did a light pass on the PR and have left some comments. A more thorough review by someone more knowledgeable should be done though.

**Comment by hosef** [comment]
Based on discussion from the meeting yesterday, I decided to revert the changes to the default installation profile for tests.

I believe the PR should be ready for review.

**Comment by quicksketch** [comment]
@hosef I got an intermittent failure on one of the modified bootstrap tests, could you take a look? https://github.com/backdrop/backdrop/pull/3076#issuecomment-601393322

**Comment by hosef** [comment]
I have fixed the intermittent test failures.

**Comment by quicksketch** [comment]
The code looks great to me. Moving this to RTBC.
