### ISSUE TITLE
Language field can't be moved around reliably

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#4321]
**Description of the bug**
Content types that has multilingual support enabled receive a new "Language" field. When organizing fields on the "Manage fields" page, this field can be moved around and reorganized. e.g.
![Screen Shot 2020-02-27 at 3 24 16 PM](https://user-images.githubusercontent.com/871421/75488217-8f649200-5975-11ea-8e66-ef1bfe36020b.jpg)

Unfortunately, when visiting the "Create content" page for this content type, that Language field gets displayed in a different location. e.g.
![Screen Shot 2020-02-27 at 3 24 29 PM](https://user-images.githubusercontent.com/871421/75488290-ad31f700-5975-11ea-9b2c-68ec9f8fc69f.jpg)

# STR

1. enable the Language module and activate another language
2. enable "Multilingual support" on a content type
2. install the Field Group module
3. create a field group on the content type and put a few fields in it, including "Language"
5. visit the "Create content" page for this content type (the language field will not be inside the Field group).

This also works without the field group module just in terms of basic rearranging of fields -- tested on a demo sandbox: simply drag the "Language" field to the bottom of the list of fields on the "Manage fields" page. It always displays near the top, underneath "Title" on the "Create Content" page.

--
PR https://github.com/backdrop/backdrop/pull/3087 by @indigoxela

**Comment by indigoxela** [comment]
I can confirm that there's some odd behavior in field ordering on node_form.

My first idea was, that some caching is the problem, but that's not the case.

I tested with the page content type (no field groups). First with only the default fields, then I added another field via field_ui (which didn't change anything).

The position of the "Language" select list turned out to be somewhat unreliable. I've no clue, what's causing this.

**Comment by indigoxela** [comment]
Ha! Much easier than I thought: it's another round for _language_ vs. _langcode_

The form item in node form is `$form['langcode']`, but the pseudo field (which gets the weight set from field module) is named `...['form']['language']`, hence the weight doesn't apply.

The fix is a one-liner. Please test and review.

**Comment by laryn** [comment]
Wow, yes, that does it. Great sleuthing!

**Comment by BWPanda** [comment]
Merged https://github.com/backdrop/backdrop/pull/3087 into 1.x and 1.15.x. Thanks @laryn for finding/filing this issue, @indigoxela for the PR, and @herbdool for the review! Nice simple fix :smiley:
