### ISSUE TITLE
Usability during installer: directory files/config_*/active not writable. What to do after I fix?

### ISSUE THREAD

**Issue by chrisfromredfin** [backdrop/backdrop-issues#433]
I noticed during the installer that if the files directory isn't set up beforehand and with the proper permission, you get notified about it in the installer, which is nice. Most of the time when this happens (i.e. if settings.php isn't writeable) then there's a "try again" link which tips me off that "hey, this is OK and expected, here's what you need to do to try again."

With the files folder, there's no try again link. Instead I chose to refresh, which worked, but it did give me that "scary" warning about "confirm form re-submission." 

![screen shot 2014-11-24 at 9 25 49 am](https://cloud.githubusercontent.com/assets/278442/5171884/7e3913f6-73e9-11e4-94b6-fe9d50e76a6e.png)

**Comment by quicksketch** [comment]
Okay we merged in a PR for fixing most of the meta at https://github.com/backdrop/backdrop-issues/issues/531. We couldn't fix this exactly (by putting a reload link) because this error may occur both when installing and when updating from Drupal 7. However, we improved the permission checking on the initial screen so that the files directory is checked as writable prior to starting the main installation process. So this should have the same effect, unless you manually create a read-only config directory (which I dare say is going to be unusual). So I'm going to mark this resolved by https://github.com/backdrop/backdrop/pull/659. If you still encounter installation issues, please open a new issue or comment in https://github.com/backdrop/backdrop-issues/issues/531.

Thanks again for trying out Backdrop! We're all excited for our initial release.
