### ISSUE TITLE
Conditional Fields listed as ready in contrib, but isn't

### ISSUE THREAD

**Issue by guidot** [backdrop/backdrop-issues#4359]
**Description of the bug**
[Top 100 Drupal 7 modules](https://backdropcms.org/upgrade-from-drupal/top-100-drupal-7-modules) lists the _Conditional Fields_ module as "ready in contrib", even though it doesn't have a release yet.
I was puzzled not to find it in the list of modules. It took me a while to discover the project page on github.

**Expected behavior**
Maybe it should be relabeled to "underway in contrib", but as there hasn't been any activity for more than a year this still may give a wrong impression.

**Comment by stpaultim** [comment]
I changed the icon to "underway in contrib."

https://github.com/backdrop-contrib/conditional_fields/issues/2

**Comment by Al-Rozhkov** [comment]
@stpaultim please, do the same for Calendar module. It is far from production ready state. Core patching needed.

**Comment by stpaultim** [comment]
@Al-Rozhkov - Sure thing. I just made that change as well. 

This is the first time I've edited that page, so I'm going to bring it up during the dev meeting tomorrow to make sure I understand the process (if any). I wonder if someone thought that "Full Calendar" module was a replacement. 

If so, I think that would be misleading. We could have a option for "similar module available" - but it's already a lot of work to keep this list up, not sure we should make it any more difficult.

**Comment by guidot** [comment]
@stpaultim This may exceed this issue, but I think the list is also too cluttered with each name having its own symbol. What about grouping them by status? That would be easier to read.

**Comment by stpaultim** [comment]
@guidot - Thanks for sharing that input. I'm going to raise this issue at our meeting today and see what folks think. I've not been involved in the creation or maintenance of this page in the past, so I'm not sure what the overall thinking is.

I recommend that we take this discussion to the Backdropcms.org issue queue, since it's really a topic about content on BackdropCMS.org and not anything to do with Backdrop CMS core. 
https://github.com/backdrop-ops/backdropcms.org/issues/674

If you have any other ideas, please suggest them there. And do continue to offer suggestions, we appreciate them. 

(I think I will close this issue here, since the immediate issue raised has been addressed and there is an alternative place to discuss this further.)
