### ISSUE TITLE
Why do the Default and Admin Default layouts have different paths?

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#4383]
Default layout `path = ""` whereas Admin Default `path = NULL`.
Minor, but if you call `menu_get_item()` on the first path, it returns `FALSE` but on the second it returns a menu item.
Bug?

**Comment by indigoxela** [comment]
I can't really tell, why it's different, but noticed, that in [system_update_1025()](https://github.com/backdrop/backdrop/blob/10167aae01ea19486e532871cfbaf238adebfa14/core/modules/system/system.install#L2250) both values get set to NULL, so that seems to be the preferred value.

Possibly an oversight in the early Backdrop days?

I compared the sandbox with a regular install (single export of layout.layout.default). Both values seem to work fine, but I'm also for consistency.

**Comment by quicksketch** [comment]
Thanks @docwilmot and @indigoxela! Merged https://github.com/backdrop/backdrop/pull/3290 into 1.x and 1.17.x.
