### ISSUE TITLE
PHP Notice and error in Color module

### ISSUE THREAD

**Issue by findlabnet** [backdrop/backdrop-issues#4399]
**Description of the bug**

Case: I use custom theme which haven't support for Color module, but module is enabled.
When I try visit theme settings page (like admin/appearance/settings/[theme-name]) I get notice then error:

`Notice: Undefined index: default in color_form_system_theme_settings_alter() (line 42 of /***/core/modules/color/color.module).
Error: Unsupported operand types in color_form_system_theme_settings_alter() (line 42 of /***/core/modules/color/color.module).`

![color](https://user-images.githubusercontent.com/11479969/82117459-b5315400-9778-11ea-9677-ee5745a6ff14.png)

**Expected behavior**

Key should be checked (exists/not empty) before looping.

**Additional information**
- Backdrop CMS version: 1.16.0

**Comment by hosef** [comment]
I created a PR that should fix this issue.

**Comment by klonos** [comment]
@hosef can you please restart the PR sandbox so that we can test this? ...some weirdness happening with ZenCI there 😞

**Comment by quicksketch** [comment]
Thanks @findlabnet for filing this issue and @hosef for the PR!

@klonos I rebuilt the sandbox for testing but it had the same error again.

**Comment by klonos** [comment]
This is RTBC, thanks @hosef 👍 

The code change is pretty simple, and I've tested it the following way:

- Used the project browser to install and enable the Bootstrap Lite theme.
- Enabled all php errors in development settings.
- Tried to access the settings page of the Bootstrap Lite theme.

When trying the above steps in a demo tugboat site with the recent 1.16.0 version, there are errors. When doing the same in the PR sandbox, there were no errors.

Can someone please add the 1.16.1 milestone to this issue? (according to https://backdropcms.org/user-guide/adding-milestones-issues I can't do it, because I'm the one that added the issue label for it)

**Comment by quicksketch** [comment]
Thanks @hosef and @klonos for the fix! @findlabnet thanks for your prompt report of this regression in 1.16.0, we really appreciate it!
