### ISSUE TITLE
CSS issues since V1.16

### ISSUE THREAD

**Issue by metatop** [backdrop/backdrop-issues#4414]
https://github.com/backdrop-contrib/css_injector/issues/4#issue-623477649

**Comment by metatop** [comment]
[https://github.com/backdrop-contrib/css_injector/issues/4#issue-623477649](url)

**Comment by oadaeh** [comment]
This might be related to https://www.drupal.org/project/drupal/issues/3138421 (which I'm not convinced is entirely related to Chrome, but might be).

**Comment by metatop** [comment]
I've only really tried it on Firefox.

**Comment by jenlampton** [comment]
A cache clear was needed with the 1.16 update, and without it a site could experience the problems described in the other issue.

I'm going to mark this issue as "cannot reproduce" until we can have someone else confirm the bug. But let's leave the issue open in the css injector queue so that anyone else using the module has a chance to also report any issues with it.
