### ISSUE TITLE
Tests: CI random failures in bootstrap.test because of reduced time in `sleep()`

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4418]
I've been seeing these random failures in PRs more and more lately:

```
Bootstrap: Page cache test (BootstrapPageCacheTestCase)

fail Background fetch copy served after granting access. bootstrap.test:308
fail Access denied page title shown. bootstrap.test:309
```

As part of the changes committed with https://github.com/backdrop/backdrop/commit/7572f3d41e157a04b262ee262884b6d463ef0ae2 in #4306, we've reduced the `sleep()` time in multiple places, in order to reduce the time tests take to run. It seems that we have now ended up in random failures; so we need to re-start tests, which ends up in more waste of time 😓 

Lets please keep this ticket as a record of which of these tests fail, and lets eventually slowly increase the `sleep()` times where needed.

**Comment by oadaeh** [comment]
To me, it seems like a bad thing that we have to reduce the performance of the tests for everything/one else, just so that the CI can handle them.

**Comment by indigoxela** [comment]
> it seems like a bad thing that we have to reduce the performance of the tests for everything/one else, just so that the CI can handle them

I agree on that, but... it's also a bad idea to silently accept that tests are failing anyway (many times recently).

This might result in a situation when we just ignore that failing test when it _rightly_ fails. Which is the  opposite of the actual purpose of automated tests.

**Comment by oadaeh** [comment]
Sorry, I did not mean to imply that we should just leave the tests failing as they are. I do agree that they should be working correctly, and if that means restoring the sleep() calls for now, then so be it. It just seems to me that there might be a better way to address this problem.

**Comment by indigoxela** [comment]
> Sorry, I did not mean to imply that we should just leave the tests failing as they are

No worry, I didn't read it like that. :wink:

> It just seems to me that there might be a better way to address this problem

Do you have a specific idea? Any helpful hint?

**Comment by quicksketch** [comment]
I made a PR at https://github.com/backdrop/backdrop/pull/3173 that reverts the changes back to the longer lifetimes.

The problem that we're encountering here is that the tests are dependent upon the speed of the server that runs them. I think currently if a server takes longer than 3 seconds to return the page request in the test, then the test fails. The test previously allowed up to 6 seconds, which I don't recall having seen fail.

I think we could make this test less dependent upon real time by updating the cache table timestamps, but then we're emulating the passage of time instead of using actual passage of time, which can be prone to a different problems like developer error or difficulty in understanding.

Currently about one in four PRs are failing because of this issue, so I'd like revert the change for now and we can look into re-optimizing it in a new issue.

**Comment by herbdool** [comment]
@quicksketch all tests passing and I did a code review. Looks good.

**Comment by klonos** [comment]
I wonder if there'd be a way to have the tests poll for success instead of wait and try. It seems that we are trying to hardcode the wait time, whereas the task may have completed sooner than those 3sec or 5sec or whatever amount of time we set. Wouldn't it make sense to instead say poll every 1sec for say up to a max of 10sec (random number there); then fail?

**Comment by quicksketch** [comment]
That's a great idea @klonos. Then it would still us "real" time but not fail on the first attempt if the server was too slow.

I'll keep that in mind if we attempt to optimize these again. Or if @hosef is interested in revisiting the optimization of this test, perhaps he would be willing to try out that approach?

For the time being, reverting the change solves this issue of the actual random test failures. Let's open a new issue if we decide to take that on, or if we continue to see intermittent test failures from this test.

**Comment by klonos** [comment]
Created a follow-up so to keep that idea in our radar: #4456
