### ISSUE TITLE
Allow selecting an existing date format for log messages

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#4425]
**Description of the need**

The "Date format for log messages" field at `/admin/config/development/logging` requires entry of PHP codes, but we have existing date/time formats at `/admin/config/regional/date-time` we could use instead.

![image](https://user-images.githubusercontent.com/2385329/83130427-f44f9580-a0e6-11ea-96f1-8b34202d158e.png)

**Proposed solution**

Change the "Date format for log messages" text field to a select list where you can choose an existing date format instead. This would provide more consistency without requiring people to enter their preferred date format in two seperate places.

**Comment by BWPanda** [comment]
Made a PR, here's what it now looks like: 
![image](https://user-images.githubusercontent.com/2385329/89032360-d406b600-d377-11ea-99e2-dff2a1b5d97e.png)

I added an update hook that takes the old format pattern, looks for a matching date format and uses that if found, otherwise creates a new custom date format with that pattern.

**Comment by BWPanda** [comment]
Actually, I forgot to convert to the new format on new installs. Since the format pattern used by default didn't match any existing date formats, I created a new one. So here's how it actually looks OOTB now: 
![image](https://user-images.githubusercontent.com/2385329/89033389-07e2db00-d37a-11ea-9ed2-61c7a38549e3.png)

**Comment by indigoxela** [comment]
Nice, and makes sense!
But the tests need some update, too. It seems that tests still rely on the textfield item.

**Comment by klonos** [comment]
Really nice indeed @BWPanda 👍 

...I've left a comment in the PR re the use of a conditional, but I could be wrong. A couple of suggestions:

- I'm annoyed by the fact that the word "Date" is being capitalized in the labels of the existing OOTB date formats; can we fix those as part of this? I don't think that that deserves an issue of its own.
- Thinking about UX, if a site admin comes to this page -> sees that there are no formats that match their needs -> uses the link in the help text to go to the date formats page -> creates a new date format, or tweaks and saves the newly-introduced one -> now they need to "manually" return to the dblog configuration page to change the setting. Can we fix/improve that please? ...I was thinking either one of these options:
  - add a destination to the link in the help, or in `$_SESSION`
  - set `target=”_blank”`, so that they can configure the format on another browser tab, then close the tab and return to the tab with the dblog config form (would still require them to refresh the page for the select to be refreshed with the new format)
  - Add a message of type `info` to the format edit page, if the format is what is currently used in `config_get('system.core', 'log_date_format');`. Something along the lines of `backdrop_set_message(t('This date format is being used for <a href="@logging">log messages</a>, array('' => url('admin/config/development/logging'))), 'info');`

**Comment by BWPanda** [comment]
Thanks for the feedback @klonos. I think both your suggestions deserve their own issues.

Regarding your 2nd suggestion, I like the first two options (the first of which takes preference in my mind if it works).

**Comment by klonos** [comment]
Sure. These can be follow-ups then. 

RTBC 👍

**Comment by BWPanda** [comment]
Thanks @klonos & @indigoxela for the feedback & testing. Merged https://github.com/backdrop/backdrop/pull/3207 into 1.x and 1.17.x.

**Comment by jenlampton** [comment]
I'm having a lot of problems with date formats on sites I'm upgrading from previous versions. I'm going to open a follow-up issue and note some of the things I'm seeing there.
