### ISSUE TITLE
Remove all instances of "blacklist" and "whitelist" from core

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4441]
In an effort to systemic racism from our project, I would like to remove all instances of `blacklist` and `whitelist` from core. 

See also:
* [coder_review#11](https://github.com/backdrop-contrib/coder_review/issues/11 ) configure the coder rule to scan for the terms `blacklist` and `whitelist` too.
* https://www.drupal.org/project/drupal/issues/2993575
* https://www.drupal.org/project/coder/issues/3151838
* https://mobile.twitter.com/s_bergmann/status/1269917026107248641
* https://github.com/php/php-src/pull/5685

---

PR: https://github.com/backdrop/backdrop/pull/3168

**Comment by jenlampton** [comment]
The PR here replaces `blacklist`, `Blacklist`, `Black list`, `black list`, `whitelist`, `Whitelist`, `White list`, and `white list` in both noun and verb forms:

* `blacklist` replaced with `blocklist`
* `whitelist` replaced with `allowedlist`
* `blacklisted` replaced with `disallowed`
* `whitelisted` replaced with `allowed`

I chose 'blocklist' initially because it was shorter than 'disallowedlist' but on hindsight, maybe `disallowedlist` is better?

**Comment by serundeputy** [comment]
I think `blockedlist`/`blocked` or `disallowedlist`/`disallowed` so that they match up makes sense to me.  Rails is using `denylist` (https://github.com/rails/rails/issues/33677).

**Comment by jenlampton** [comment]
I think my preference is not to use `blocked` since we use that for user accounts, and it sort of has a different meaning. Do you have a preference for `disallowed` vs `denied`?

I like `denylist` / `denied`.

**Comment by serundeputy** [comment]
> I like denylist / denied

nice and concise.

**Comment by Wylbur** [comment]
Thanks for doing this!  I like denylist / denied.

**Comment by jenlampton** [comment]
I'll update the PR with `denylist` / `denied`.

**Comment by laryn** [comment]
For consistency then, would it be:

 - `denylist`/`denied`
 - `allowlist`/`allowed`

**Comment by jenlampton** [comment]
The PR already has `allowlist` / `allowed` so I am changing `denylist` / `denied`

**Comment by jackaponte** [comment]
Thank you for this y'all! A good step...though I should probably finally make that issue about removing "master" and "slave" language from Backdrop, too!

**Comment by jenlampton** [comment]
And related repositories ;)

**Comment by jackaponte** [comment]
> And related repositories ;)

Ah, good to know! Which other related repositories would need master/slave language changed?

**Comment by jenlampton** [comment]
I've started working through all repos in backdrop-ops and deleting the `master` branch (replaicing it with `main`)

**Comment by jackaponte** [comment]
> I've started working through all repos in backdrop-ops and deleting the `master` branch (replaicing it with `main`)

Ah gotcha! This is interesting. I haven't contemplated "master" on its own, e.g. for git (or say for master copies of audio recordings?) I've mostly seen objections to master/slave language for databases, specifically because of the "slave" part and because slave databases are dependent on master databases. 

But if you've seen folks commenting on this and encouraging moving away from "master" by itself, I'm open to that analysis and shifting that too! Please point me towards any such commentary.

**Comment by jenlampton** [comment]
Most of these are articles about what GitHub itself is doing, but it's going around.

* https://www.bbc.com/news/technology-53050955
* https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/
* https://www.cnet.com/news/microsofts-github-is-removing-coding-terms-like-master-and-slave/
* https://www.vice.com/en_us/article/k7qbyv/github-to-remove-masterslave-terminology-from-its-platform
* https://www.businessinsider.com/github-replacing-software-code-terms-master-slave-2020-6
* https://www.cnet.com/news/microsofts-github-is-removing-coding-terms-like-master-and-slave/

**Comment by jackaponte** [comment]
Thank you @jenlampton! Got some reading to do. :)

**Comment by BWPanda** [comment]
I struggle to write this, because I'm afraid of what people will think of me for having an opinion that seems to differ from the majority. But it's partly that fear that motivates me; because I don't want us to get to a place where people feel they can't speak up, give an opinion, etc. And I'm worried that's what will happen.

So here it is:
I disagree with this issue.

I don't think the terms 'blacklist' and 'whitelist' are racist, and I don't think they're used in Backdrop as such, or in any offensive way. Since the creation of the world, the terms (or even concepts) of 'black' and 'white' have been associated with evil and good respectively. Where is the racism in that?

I know I'm probably not going to change anyone's minds here, and that's fine (I'm mentally preparing myself for my first ever thumbs-down). I'm not going to quit using Backdrop because we replaced certain words in core. But I do want to caution us about just going along with what (some of) the rest of the world seems to be doing. What other words will people be offended by in future (with or without just cause)? Where will it stop?

**Comment by klonos** [comment]
>What other words will people be offended by in future (with or without just cause)? Where will it stop?

I understand your concerns @BWPanda, but instead of not doing anything at all, I'm for doing anything that's a low-hanging fruit. That's why I suggested that we fix the instances of these strings in core that are obvious/easy, and then leave the rest for future iterations. I just don't want us to waste energy/time on this issue, when it's just in order to be PC.

**Comment by laryn** [comment]
The PMC page indicates that the PMC (and by implication the project) "should reflect all perspectives from within the Backdrop community" (including yours @BWPanda ☺️). 

> ... just in order to be PC.

With respect, I submit that the term "politically correct" is a euphemism. Would you say, for example, "I don't want to waste energy or time on this issue when it's just in order to be respectful of people who have historically been harmed by language like this?"

I'd also suggest that language is situated in particular times and places and cultures, and rather than immutable meanings that are present and always have been (e.g. "from the creation of the world"), meanings shift and take on additional meaning and baggage, and I am for an openness to exploring places where meaning may be encoded in language we're using without our realization and adjusting to make the project more inclusive.

**Comment by stpaultim** [comment]
@BWPanda - I'm hesitant to speak up on this issue as well, because we're living in a difficult time in which opinions are highly polarized and nuanced discussion on topics like this is very difficult. I see points on both sides and then I feel bad about that, because I'm told today that everyone should be on either on one side or the other. 

I am skeptical that changing these words (in a vacuum) would/will have any impact on the world. BUT, I believe that the act of changing these words causes us as humans to reflect on a real and serious problem and engage with it. It sends a message to others and the world that we are aware of and responding to what is happening in the world. The fact that so many people believe that these words have power, in some ways does give them power and changing them does send a signal.

I have not been active with this issue, because I feel like I have limited energy to put into social change and it's not clear to me that this is the best place for me to put that energy. BUT, I have no objection to others working on this change and am supportive in whatever ways I can be.

I am concerned that focusing on these kinds of changes distracts us from (or potentially excuses us from) bigger and more important changes that we all need to be making in our daily lives, but I would prefer to leave that judgement to others to make for themselves. 

I also start to ask myself, is the issue queue the place to be discussing this? And then I remember, that I once gave a presentation at Drupal Camp on "Open Source as a Political Act." I work with BackdropCMS, because I think I'm doing a small thing that will make the world a better place in it's own small way. I hope and expect our community will respond to injustice in the world, but that we will also respect and understand that many of us have differing views on what we are doing and what kind of impact it will have and on what the best/most effective course of action is.

> Where will it stop?

It won't stop, language is always changing and the meaning/impact of words is always changing. But we don't always have to respond to it in the same way, nor do we necessarily need to respond to every similar proposal in the future. But, right now we are in a special time and there is a sense of urgency in the world which is motivating some of us (in my opinion) to take this action at this time. I am supportive of that.

**Comment by wilburec** [comment]
@BWPanda 
Here in the US we are dealing with intense race relations, trying to clean up systemic racist practices that have been in place since we brought slaves here.  

This is really an important issue for us here in the US.  It's so important because it's so prevalent that people don't even see it - because it has just been this way since our country was formed.  

White - this is a term used for white people - it can mean pure, good, angelic.
Black - this is a term used for black people - it can mean evil, impure, excluded.   
Blacks or African Americans are the descendants of people who were brought here against their will.  They were stripped of their culture, language, history, and  were not treated as human.  

We don't HAVE to use there words, there are lots of great alternatives we can use.  And lots of these words are much more appropriate because that their meanings are exact - like approve/approval and deny/denial.  

Because of the racist association of black/white, people are coming to realize that using these terms for good/evil or accepted/rejected has the unintended consequence of perpetuating racistic stereotypes.  People here in the US are ready to take action and stop these practices.  It's a time in our history to take on these practices and stop them so that future generations can be clear of this type of unintended racistic language.  

Lots of people that work on this project are ready to take on these actions.  We think it's important and necessary to start addressing the systemic racism in the US.  

I know you don't think that this is racist, but we do, and it's very important for us to do this work.  

The effort for us to do this is changing our code, AND changing our active vernacular.  That's a pretty low cost to help with the US's epic problem of systemic racism.  

If we find other instances of encoded racism in our project terminology we should absolutely take that on and deal with it. No matter how many times it happens.  No matter who brings it up.  

The practice of us improving our code and out language and out treatment of humans must never stop.  

You don't have to agree with us.  But please let us do our work.  

If there are real issues with this change, please let us know and we will address them!

Thanks for your input!

**Comment by docwilmot** [comment]
This is a difficult one. I agree with what you said @BWPanda in that I dont think those words are particularly meant to be in any way related to race at all. But in our world right now I support anything that helps to shine a light on the fact that `black != bad` and I think doing this as a group helps show our support for that idea.

**Comment by jenlampton** [comment]
I've rebased the current PR, updated the function name for the update hook, and added the new instance of `whitelist` added from the drupal patch. I'd love to see this get into 1.21!

**Comment by indigoxela** [comment]
@jenlampton this issue's labels are a bit confusing now. You added "milestone candidate - minor" yesterday, but it also still has "milestone candidate - bug" and the label "task".

I'm assuming the "minor" is because of some backwards compatibility concerns with your PR. But maybe we could bypass compatibility problems, or create a follow-up for problematic changes, that need a BC layer?

I've also left a comment on your PR re the changes in the ckeditor changelog - which I belief should not happen in Backdrop.

**Comment by jenlampton** [comment]
I believe I've addressed all the feedback on the PR. Thank you @indigoxela @herbdool and @klonos for reviewing!

**Comment by klonos** [comment]
Thank you for moving this along @jenlampton ...last couple of things that I believe were missed. Comments/suggestions in the PR.

**Comment by jenlampton** [comment]
@klonos I've merged your suggestions, thank you for catching those noun/verb differences :)

**Comment by klonos** [comment]
Things are looking good to me now 👍🏼 ...thanks @jenlampton 🙏🏼
