### ISSUE TITLE
Provide option to skip deleting config staging files after a config sync

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#4447]
**Description of the need**

There's a long [standing issue in Pantheon](https://github.com/backdrop-ops/backdrop-pantheon/issues/27) (and likely Platform.sh too) where the live code directory is locked. If a developer puts config into the repo it means that it creates a problem by deleting files (or tries to delete) that shouldn't be.

This is where it happens: https://github.com/backdrop/backdrop/blob/c41843f24c6c434be89ef5ad4e3ce00e499cf2b9/core/modules/config/config.sync.inc#L104

**Proposed solution**

Maybe the staging directory never needs to be cleared? Perhaps it helps by forcing people to start fresh each time. But I propose adding an advanced setting for `settings.php` to skip this step. That way it can accommodate different workflows.

Something like:

```
--- a/core/modules/config/config.sync.inc
+++ b/core/modules/config/config.sync.inc
@@ -100,10 +100,12 @@ function _config_sync_finished($status, $results, $operations) {
   if (!empty($results['completed_changes'])) {
     backdrop_set_message(t('Configuration sync completed. @files configuration files synced.', array('@files' => count($results['completed_changes']))));
 
-    // Clean up the staging directory.
-    $config_dir = config_get_config_directory('staging');
-    $config_storage = new ConfigFileStorage($config_dir);
-    $config_storage->deleteAll();
+    if (!settings_get('skip_staging_directory_cleanup')) {
+      // Clean up the staging directory.
+      $config_dir = config_get_config_directory('staging');
+      $config_storage = new ConfigFileStorage($config_dir);
+      $config_storage->deleteAll();
+    }
   }
 
   backdrop_flush_all_caches();
```
----
PR https://github.com/backdrop/backdrop/pull/3171

Advocate: @herbdool

**Comment by jenlampton** [comment]
The only problem I foresee with this is that the UI at `admin/config/development/configuration/sync` will always show unwanted information if that directory is not cleared out after each sync.

What if we disabled the "automatic" comparison of config files on this page when `skip_staging_directory_cleanup` was set? We could add a button that could trigger the comparison instead. 

What happens with a single config file import? Does it still work? (Does it even use the staging directory?)

**Comment by herbdool** [comment]
Yes, I thought that too but this is also a feature. It's similar to how d8 does it by showing what is overridden compared to the "canonical" version in staging. Since this is an advanced setting I think it's okay that it shows this automatically. Most people won't bother with this, but for those who do this'll make life a lot easier.

Single file imports don't use the staging directory.

**Comment by herbdool** [comment]
Perhaps you meant importing a full archive of the config files? In that case, when uploading a tarball it appears that the function will delete the files in the staging directory if it's not empty. So this shouldn't affect current behaviour.

```
function config_import_full_form_submit(array &$form, array &$form_state) {
  if ($fid = $form_state['values']['import_tarball']) {
    // Empty out the existing staging directory.
    $config_storage = config_get_config_storage('staging');
    $config_storage->deleteAll();
```

**Comment by herbdool** [comment]
Wondering if @quicksketch thinks this is a good idea.

**Comment by quicksketch** [comment]
This was on the agenda for the dev meting today. I completely agree this is a good idea to not delete the staging configuration upon import.

On most of my sites, we have the staging config managed in Git. So deleting them causes the git repository to show a modified state. Then every deployment we have to restore the default state before pulling in the changes.

I think the current behavior is probably most useful if you're importing archives of configuration through the UI. But for sites that replace the files directly on the server and usually export all of their configuration on a regular basis, leaving the files as-is makes it easier to track what config changes have occurred on the production environment that need to be exported.

Personally, I would think it might make sense to have this new behavior be the default. But in order to have it change on new installs without affecting current ones, the setting would have to be a config value itself. Would that be problematic to have the configuration of how config is cleaned up be in config? I imagine because the cleanup happens after the config comes in, the newest value of that config would determine the cleanup behavior. If we can avoid a settings.php setting, that generally makes things easier to test, less to document, and we can provide a UI for the option.

**Comment by herbdool** [comment]
@quicksketch thanks for the feedback.

I changed it to a config in the PR. I can confirm that it will use the newest value that comes in after the sync so if the value is set to not cleanup staging it won't. Of course, someone can still override it in settings.php if they wish.

I haven't worked on a UI for it yet but I can see it being useful to at least help people understand what's going on.

I wasn't sure about making it default. Won't it depend what the 80% is doing and also what current site builders are used to? I'd prefer it be default too but want to see what others think.

So still todo would be: add a UI and tests.

**Comment by klonos** [comment]
Noting that if we change this to be the default, we may need to update existing articles/documentation.

**Comment by jenlampton** [comment]
> Noting that if we change this to be the default

I'm not sure we should change it to be the default. I think that most the people we hear from here on GitHub are the people who have their files on version control, and we aren't getting any input from all the people who don't operate this way. Would they prefer to keep things the way they are now? idk.

**Comment by herbdool** [comment]
So sounds like we might want to leave the default behaviour to be clearing the staging directory. With that in mind how do we make it easier for people to know about the other option? Expose the option in the UI? A settings tab at admin/config/development/configuration/settings?

**Comment by jenlampton** [comment]
> Expose the option in the UI? A settings tab at admin/config/development/configuration/settings?

Do we need a UI? (Is the setting going to be in config?) I was thinking it would go in settings.php - and in that case a docblock there could do the trick. Maybe right under config location?

**Comment by herbdool** [comment]
@jenlampton may want to read the whole thread. I've added a UI based on @quicksketch feedback.

**Comment by jenlampton** [comment]
> But in order to have it change on new installs without affecting current ones, the setting would have to be a config value itself. 

Since we don't want to change the value for new installs, we don't need the value to be in config anymore (though, I don't believe @quicksketch's logic that a value in setting's php wouldn't also be suitable if we did want to). 

My answer to the question `Expose the option in the UI?` is still `Not if we don't need a UI for this` and since the people who are going to be using this feature aren't the people who would need (or want?) a UI for it, than my vote is still `No` :)

**Comment by herbdool** [comment]
So this PR originally just had a setting in settings.php. Now it's got a config and a UI. Do we go back to the initial state? Or somewhere in between? A config setting with no UI but still add a docblock in settings.php?

**Comment by jenlampton** [comment]
Let's wait for more feedback before changing it again. @BWPanda do you have thoughts? @docwilmot @klonos?

**Comment by docwilmot** [comment]
No thoughts sorry. Dont use staging workflow.

**Comment by klonos** [comment]
Same boat as @docwilmot here 🤷

**Comment by herbdool** [comment]
@indigoxela might be interested in chiming in.

**Comment by jenlampton** [comment]
And what about @laryn?

**Comment by BWPanda** [comment]
The only time I use config is when working with the BackdropCMS.org sites. Since the [instructions](https://github.com/backdrop-ops/backdropcms.org/tree/main/config#setup) say to checkout the staging directory after synching, then I believe this change will make it easier for me and others (one less step). As for whether this should be default or not, or in settings.php or config, I've no idea...

**Comment by jenlampton** [comment]
I wonder about @oadaeh, @hosef, or @stpaultim do you use config and/or keep it in version control?

**Comment by stpaultim** [comment]
In theory, I've experimented with keeping config in version control, but don't have enough experience with it to have a decision on whether I like it or not. I'm inclined to think that I would like to work versioned config into my work flow, especially since I recently copied dev config into prod by accident and didn't have an easy backup of my config.

Most of my current use of moving config files around is manual (outside of git).

I'm having a hard time taking a position on the issue of how to implement this.

**Comment by klonos** [comment]
Also pinging other members of the community that come to mind, like @olafgrabienski and @jlfranklin

**Comment by indigoxela** [comment]
> @indigoxela might be interested in chiming in

Sorry, I'm not using a (git based) staging workflow, too, so I can't contribute anything useful here.

**Comment by olafgrabienski** [comment]
I'm also not using a staging workflow. (Interested to learn more about it, but didn't need it urgently so far.)

**Comment by klonos** [comment]
I guess that Backdrop is indeed attracting the kind of developers that prefer simpler workflows (which makes sense, and makes me happy), while still accomodating more "enterprisey" workflows for those that either prefer them, or have to use them 🙂 

This bit of the help text:

> ...so ensure the settings are correct on the other site before importing here.

Makes me think that we should still add a section in settings.php, which overrides this setting:

```php
/**
 * Skip the configuration staging directory cleanup
 *
 * For some development workflows (such as when the configuration files are in
 * version control) it may be necessary to not delete the staging config files
 * after each configuration sync.
 */
// $config['system.core']['config_sync_clear_staging'] = 0;
```

**Comment by herbdool** [comment]
Looks like I might need to put it on next week's agenda (maybe I should advocate for this - how do I do this @klonos?) to hash it out between @jenlampton and @quicksketch. I'm on the fence. Perhaps putting it in settings.php but using a config variable is a compromise. That leaves room for in the future to add a UI if preferred.

**Comment by BWPanda** [comment]
@herbdool To advocate for something, just add:

> **Advocate:** @herbdool 

to the original post then either add, or ask someone else to add, this issue to the meeting agenda template.

**Comment by jenlampton** [comment]
> To advocate for something...

We also need one person to add the milestone candidate label (dibbs!) and another to remove the label and add it into the 1.18 milestone :)

> Perhaps putting it in settings.php but using a config variable is a compromise. 

I like it!

**Comment by klonos** [comment]
There you go 🙂 ❤️

**Comment by quicksketch** [comment]
I like this as a config value, it makes testing easier (because settings in settings.php cannot be overridden in testing, easily at least). Thanks @herbdool for already including test coverage on this new setting as well. :+1:

I think having the UI makes sense because it gives us a place to expose this feature to less experienced developers and site-builders. "Hidden" config settings is usually limited to exceptionally unusual situations, like changing the Update module XML feed location from backdropcms.org to another server.

@jenlampton prefers we have it in settings.php so that the config settings can be set up all at the same time. As a compromise, could we just include it in both places? Basically leave the entire PR as-is, but then also add the chunk of overriding documentation @klonos wrote up in https://github.com/backdrop/backdrop-issues/issues/4447#issuecomment-740549252.

**Comment by jenlampton** [comment]
> "Hidden" config settings is usually limited to exceptionally unusual situations

Based on feedback in this issue -- I wonder if this isn't an exceptionally unusual situation?

The kinds of people who do need this setting won't use the UI (because they manage config in code).

The people who are going to be working in the UI are not the people who care if their config files are deleted or not. They'll either play with the setting and see that it does nothing for them (because they manage config in the UI) or worse, they might think that the setting is broken because nothing has changed for them in the UI (since they aren't looking at the files).

My logic here is similar to the argument for removing `syslog` from core. You enable it, but you don't see anything change.

> a place to expose this feature to less experienced developers and site-builders. 

It sounds like the logic for this is that "we need a place to document it" but since that is solved by https://github.com/backdrop/backdrop-issues/issues/4447#issuecomment-740549252 that logic doesn't hold up either.

If we want documentation in the UI, why don't we just add some text telling people that the setting exists in `settings.php`?  Do we do that anywhere else in core?

**Comment by jenlampton** [comment]
> Do we do that anywhere else in core?

It looks like we mention `settings.php` in the UI in a few places: the installer, the updater, if your mysql connection fails, and on the status report if the `trusted_host_patterns` isn't set. It's not really a pattern, but were not against it either.

The current PR adds the setting on `admin/config/development/configuration/settings`. If the goal is to get people to know about the change, it would probably be more effective if we put some text on the config sync page instead. 

We could say something like `The location where your configuration files are stored, and how you want them managed, can be defined in your `settings.php` file. That we we cover the config locations too!

**Comment by BWPanda** [comment]
> The kinds of people who do need this setting won't use the UI (because they manage config in code).

I don't like the assumption that just because people do things in code they don't need a UI for stuff...

**Comment by jenlampton** [comment]
It's not that they don't need a UI for anything -- they just won't be in *this part* of the UI because their workflow doesn't include it.

**Comment by quicksketch** [comment]
Looking through `system.core.json`, there are several examples of other hidden settings. These are some I've never changed:

```
action_recursion_limit
cron_threshold_warning
cron_threshold_error
field_purge_batch_size
config_sync_batch_size
```

While there are others that I have definitely needed to change, albeit only once or twice:

```
active_menus_default
form_cache_expiration
x_frame_options
```

I don't think any of the above values warrant documentation in settings.php or a UI. Though some kind of API docs would be helpful; right now the only way to find how any of these work is to search through the code base.

I guess for now putting in in settings.php only is fine. This option breaks the mold in that it's the first explicit hidden setting we would document in settings.php. I'm the only one pushing for a UI so perhaps if there is a larger group or some other justification that makes this more obvious that we should implement it at that time.

**Comment by jenlampton** [comment]
> This option breaks the mold in that it's the first explicit hidden setting we would document in settings.php.

What about the config directory locations? (or database connection info) Neither of those have UIs, and are only documented in `settings.php`. 

The only difference here is that we decided to make this a config value instead of a hard-coded thing, and that was only so that we could test it more easily. :)  If anything, people will probably wonder why they need to use the config-override syntax for this value, when the others don't require it. 

Though... I was just thinking that if we are going to add some text to the config sync page about this option, we should maybe also print the location of config files there too. Wouldn't that be helpful? :)

**Comment by klonos** [comment]
> What about the config directory locations? (or database connection info) Neither of those have UIs, and are only documented in `settings.php`.
>
> The only difference here is that we decided to make this a config value instead of a hard-coded thing, and that was only so that we could test it more easily. ...

Not sure about the reason and testing more easily, but if we had config overrides from the get-go, perhaps those other hard-coded things would have also been introduced as a config value(?) 🤷

...also, when it comes to `trusted_host_patterns` specifically, when porting the feature from D8 (#2568), we did discuss introducing a UI for it, but decided not to after all. We did leave that as a possibility for the future though (#3630), especially once when we have other things in place (like #3624 and #4331).

I guess what I'm trying to say is that, even just for the sake of consistency, I prefer the config syntax in `settings.php`. Especially if things have the potential for a UI (not necessarily in core). Now, if that also makes it easier to test things, then that's a bonus.

**Comment by herbdool** [comment]
Just updated the PR. I got rid of the settings page and added some text to the config sync page.

![Screenshot from 2020-12-14 16-13-52](https://user-images.githubusercontent.com/1071483/102136474-6d1a0300-3e27-11eb-8bb0-cc0971c553a3.png)

I've left it a config setting so we have the option later on. (@quicksketch I thought it was possible to just set `$GLOBALS['settings']` for testing?)

The last couple comments (displaying config path settings) and converting `$settings` to `$config` overrides seem to be beyond the scope of this issue (@jenlampton and @klonos can create new issues?). (Though I should mention that displaying the location of the config files in the UI could be a security risk.)

**Comment by jenlampton** [comment]
I've been using this PR on the site I'm actively working on right now. I LOVE IT!!!

**Comment by herbdool** [comment]
@jenlampton @klonos I've updated the wording.

**Comment by jenlampton** [comment]
I still think `not to empty` is more grammatically correct than `to not empty`.  Something about split infinitives? (I think the line break and the asterisk in the middle are probably not intentional.)

**Comment by klonos** [comment]
> ...don't we need an update hook to set the default value of `config_sync_clear_staging` on existing sites?

Yes we do. We're clearing config based on `if (config_get('system.core', 'config_sync_clear_staging'))`, which on existing sites will return `FALSE`, since that setting does not exist. This will effectively be changing behavior.

**Comment by herbdool** [comment]
@jenlampton good catch about the update hook. I've added it.

**Comment by jenlampton** [comment]
Looks great, RTBC!

**Comment by quicksketch** [comment]
Thanks @herbdool for the updates! I've merged https://github.com/backdrop/backdrop/pull/3171 into 1.x for 1.18.0. Thanks everyone in this issue for weighing in and making suggestions!
