### ISSUE TITLE
[UX][DX] Remove the option for configuring the admin theme to always be the same as the default theme.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4461]
This annoys me on both a UX and DX level...

## UX

![Screen Shot 2020-06-28 at 11 30 24 am](https://user-images.githubusercontent.com/2423362/85943396-8510cf80-b938-11ea-9f7e-49073fb4c224.png)

This ^^ is a Drupalism/Backdropism, and we should fix it! The "Choose "Default theme" to ..." help text is similarly annoying to all the "leave blank to ..." help texts; we shouldn't have to be explaining "special" options, when we can use clearly distinct UI elements that convey clear messages of what each form element does.

As a newcomer, when I click that dropdown select, I am assuming that all the available options there are themes ...the "Default theme" option is not though; and what if there is an actual theme, with "Default theme" as its name? (but more on that in the DX section).

Here are the 2 alternatives that would make much more sense from a UX PoV:

- We could make it clear that the first option is a "special option" (and remove the help text):

    ![Screen Shot 2020-06-28 at 12 30 44 pm](https://user-images.githubusercontent.com/2423362/85943835-42042b80-b93b-11ea-80dc-16a65fb9b4af.png)

- Or ideally remove the "special option", and replace it with a distinct checkbox instead:

    ![Screen Shot 2020-06-28 at 12 01 13 pm](https://user-images.githubusercontent.com/2423362/85943208-37479780-b937-11ea-8001-2d573d3c4a12.png)

    Notice how the vertical space is not increased ^^ (so no additional scrolling required), because we have practically converted the help text into a checkbox 😉 ...if the checkbox is ticked, the admin theme select would be hidden via `#states`:

    ![Screen Shot 2020-06-28 at 12 01 37 pm](https://user-images.githubusercontent.com/2423362/85943218-43cbf000-b937-11ea-968e-d964c5bc2ab6.png)

## DX

This is the "magic" we use to inject that "special" option in the select options:

```php
  $form['admin_theme']['admin_theme'] = array(
    '#type' => 'select',
    '#options' => array(0 => t('Default theme')) + $theme_options,
    '#title' => t('Administration theme'),
    '#description' => t('Choose "Default theme" to always use the same theme as the rest of the site.'),
    '#default_value' => config_get('system.core', 'admin_theme'),
  );
```

...so when that option is selected, `config_get('system.core', 'admin_theme')` returns a string `0` instead of a theme name (what is actually saved in `system.core.json` is `"admin_theme": "0",`) 🤦 ...some may say that this is fine, but then instead of being able to do simple, straight-forward things like this (note that almost no comments to explain what's going on):

```php
  $config = config('system.core');
  $theme_default = $config->get('theme_default');
  $theme_admin = $config->get('admin_theme');
  ...
  // Add notes to default and administration theme.
  $theme->notes = array();
  $theme->classes = array();
  if ($theme->is_default) {
    $theme->classes[] = 'theme-default';
    $theme->notes[] = t('default theme');
  }
  if ($theme->is_admin) {
    $theme->classes[] = 'theme-admin';
    $theme->notes[] = t('administration theme');
  }
```

...one has to do this:

```php
  $config = config('system.core');
  $theme_default = $config->get('theme_default');
  $theme_admin = $config->get('admin_theme');
  ...
  // Add notes to default and administration theme.
  $theme->notes = array();
  $theme->classes = array();
  if ($theme->is_default) {
    $theme->classes[] = 'theme-default';
    $theme->notes[] = t('default theme');
  }
  // When the admin theme is set to be the same as the default theme, then
  // admin_theme in system.core.json is set to the string "0".
  if ($theme->is_admin || ($admin_theme == FALSE && $theme->is_default)) {
    $theme->classes[] = 'theme-admin';
    $theme->notes[] = t('administration theme');
  }
```

**Comment by klonos** [comment]
PR up for review: https://github.com/backdrop/backdrop/pull/3178

**Comment by jenlampton** [comment]
I love this improvement. I've tested the PR and it works great. I love how the other questions are hidden now when the default theme is set.

One thought I had is that we don't really need the word `always` in `Always use the default theme as the administration theme`, since we either will or we won't. How about `Use the default theme as the administration theme` instead?

I left some minor code style feedback on the PR on handling config setters, but this is really close!

**Comment by klonos** [comment]
Thanks @jenlampton 🙏 ...I've addressed all feedback left in the PR, so it's ready for another pass 😉

**Comment by jenlampton** [comment]
Code looks great! There was one extra line of whitespace that could be removed, but I'm not going to let that prevent this from being RTBC!

**Comment by mikemccaffrey** [comment]
Personally, I'd say we should just remove the special case and have them
just select a theme for admin. This is a lot of complexity to save two
clicks every couple of years.

**Comment by klonos** [comment]
🤔

**Comment by quicksketch** [comment]
I tried out the sandbox site and I agree with @mikemccaffrey, this option to match the default theme is unnecessary in the first place.

While having that checkbox hide/show the other admin-theme related options hides redundant settings, it's jarring to have them hide/show, possibly because this as the bottom of the page so the visible contents end up scrolled down outside the viewport after toggling on. Something else I dislike is that we've put the most important setting -- the "Administration theme" select list -- after a confusing option for matching the default theme.

Here's a screen recording of the current implementation:
![admin-theme](https://user-images.githubusercontent.com/100206/87082149-6683c180-c1df-11ea-9dfb-65df3be4e228.gif)

I'm in favor of simply removing the option from the select list and add an update hook to save the admin theme setting to config. The checkboxes for content creation and login will result in the same behavior either way if admin theme and default theme are the same, but I think that's fine. It's helpful to me to know that those options exist. And the default behavior of Backdrop is going to be to have Seven as the admin theme.

**Comment by jenlampton** [comment]
> Something else I dislike is that we've put the most important setting -- the "Administration theme" select list -- after a confusing option for matching the default theme.

This is a good point. People are already confused enough about what a `default theme` is. The simplest solution is to remove the option all together.

**Comment by klonos** [comment]
> @klonos would you be willing to take another stab at it?

I do; I'm currently on vacation though till Aug 2, so working on issues sporadically. If people wanna file a PR against mine, or create a new PR based off of mine, then by all means 🙂

**Comment by klonos** [comment]
New PR up for review, which removes the "Default theme" option altogether: https://github.com/backdrop/backdrop/pull/3199

**Comment by indigoxela** [comment]
Funny, how a *simplification* can baffle a Drupalized brain. :rofl: 

This change really makes sense. And it works like a charm.

**Comment by klonos** [comment]
I've fixed merge conflicts cased by the update hook number (there were a few more update hooks added since I last updated this PR), and I have also rebased. All tests are green now! 🎉

**Comment by quicksketch** [comment]
Merged this into 1.x for 1.20.0. I did not pull it back into 1.19.x, since 1.20.0 comes out today.
