### ISSUE TITLE
Create a list of blocks and the modules that provide them

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#449]
As per https://github.com/backdrop/backdrop-issues/issues/345#issuecomment-65741612

---

Latest PR from @docwilmot: https://github.com/backdrop/backdrop/pull/1528

**Comment by BWPanda** [comment]
Ha! It seems someone else was also missing the block listing: http://enzolutions.com/articles/2014/12/29/backdrop-cms-first-impressions/
:smiley:

**Comment by BWPanda** [comment]
Updated PR for latest code.

**Comment by herbdool** [comment]
I'll vote for this too.

**Comment by docwilmot** [comment]
I'd vote for this but not under reports menu; under layout
```
Layout
-Add layout
-List layouts
-List available blocks
```
Makes more sense there.

**Comment by docwilmot** [comment]
Posted an update of @BWPanda's PR at https://github.com/backdrop/backdrop/pull/771
- switched to use existing `layout_get_block_info()` rather than loading all layouts
- added two new columns for 
  - required contexts
  - block usage
- added new function `layout_get_block_usage($delta = NULL)` to get data about where blocks are being used.

**Comment by docwilmot** [comment]
May not get into 1.4.0 given the time, but wont be from lack of trying :smile:

**Comment by quicksketch** [comment]
The PR looks good. A few things:

- A test to check that block usages are shown.
- Some help text would be useful at the top of this page describing what is being displayed.

**Comment by quicksketch** [comment]
We'll get it in the next release (hopefully)!

**Comment by docwilmot** [comment]
8 hours late :cry: 
Rebased, repushed, with tests and all too. See you in 4 months.

**Comment by klonos** [comment]
Wanted to give this a go, but the PR sandbox WSODs on me. :disappointed:

**Comment by docwilmot** [comment]
Strangely, I had to run update on the sandbox. Try again.

**Comment by Gormartsen** [comment]
@docwilmot ++

updb is in TODO list, when PR get synchronized (updated).

**Comment by klonos** [comment]
Looks really good, but I'd rather it be `[layout]: [region]` instead of [layout] ([region]) and also capitalize the region name.

Also, if a block is added in two regions within the same layout (edge case, but can happen), then we have separate `<li>`s for each instance:

![backdrop-issue449-pull1386-layouts_and_regions_list-one_layout_item_per_region_item](https://cloud.githubusercontent.com/assets/2423362/15543006/746851a0-22d6-11e6-8535-b46a7108b1ab.png)

...it would be better I think to either list the layout once and append all regions in a comma-separated list:

![backdrop-issue449-pull1386-layouts_and_regions_list-single_layout_item_with_comma-separated_list_of_regions](https://cloud.githubusercontent.com/assets/2423362/15543005/74676c72-22d6-11e6-9697-15a413bcb9ea.png)

...or have them in nested `<li>`s:

![backdrop-issue449-pull1386-layouts_and_regions_list-single_layout_item_with_nested_list_of_regions](https://cloud.githubusercontent.com/assets/2423362/15543007/7471e22e-22d6-11e6-9314-3cea4d855569.png)

**Comment by BWPanda** [comment]
I think the Layout and Region should be in separate columns in the table, and that the columns should be sortable. That way we can sort by Layout or Region to find all blocks in them more easily. That, or add exposed filters to do the same thing.

**Comment by klonos** [comment]
@BWPanda++ on the filtering ...not so sure about splitting layouts and regions to separate columns though ...although some region names are common in many layouts (header/footer, top/bottom, content etc).

Anyways, I would like to take this chance to shamelessly promote #503 (introduce a reusable filtering system that has consistent look/feel in various listing pages).

**Comment by jenlampton** [comment]
No progress made on this since May, officially bumping from 1.5 to 1.x-future.

**Comment by docwilmot** [comment]
New PR up, although bumped to future.
https://github.com/backdrop/backdrop/pull/1531

**Comment by olafgrabienski** [comment]
Seems that the test site of the PR haven't been installed. Clicking the link, I get the install page (core/install.php).

**Comment by jenlampton** [comment]
If you close and open the PR you can generate a new test site.

**Comment by olafgrabienski** [comment]
Found the new test site, thanks!

Regarding the block list: As a newer backdrop user, I'm late here. Wanted to ask why the vote to put the block list not under Reports but under Layout (https://github.com/backdrop/backdrop-issues/issues/449#issuecomment-88636619) isn't in the PR. I guess it would be helpful to have the Block list near the Layouts, and I didn't find any objection in the issue. Did I miss something?

If the list however remains under Reports, shouldn't the name of the menu item be "Blocks" (in analogy to "Fields" etc.) and not "List blocks" (which in return would make perfectly sense under Layout).

**Comment by quicksketch** [comment]
This functionality looks great. When reading the issue here I found myself again resisting it, but then when I saw what it actually did, I thought it was very valuable. Nice job @docwilmot again on this.

> Wanted to ask why the vote to put the block list not under Reports but under Layout (#449 (comment)) isn't in the PR. I guess it would be helpful to have the Block list near the Layouts, and I didn't find any objection in the issue. Did I miss something?

I think we may have a consistency issue here. Right now we have two other major modules providing very similar pages under Reports: Views and Field. I think we should create a separate issue to decide on rearranging all of these reports at the same time. How does that sound?

**Comment by quicksketch** [comment]
I left some feedback on the PR: https://github.com/backdrop/backdrop/pull/1531 Looking great though! I'll slate this for 1.5.0 and we can see if we can make it in. We can move it if it's looking unlikely.

**Comment by olafgrabienski** [comment]
That sounds good! Even though, in the moment, I'm not sure what to propose exactly. Have to think about it!

**Comment by docwilmot** [comment]
> I'll slate this for 1.5.0 and we can see if we can make it in. We can move it if it's looking unlikely.

Great. Its not urgent obviously so no rush.
Also need to do column priority for mobile.
And @quicksketch you OK with my fake tablesort? 
```
  $order = tablesort_get_order($header);
   $sort = tablesort_get_sort($header);
 
   backdrop_sort($rows, array($order['sql'] => SORT_STRING));
```
I made an issue (https://github.com/backdrop/backdrop-issues/issues/2149) to modify `backdrop_sort()` to allow sort direction because this implementation only allows sorting one direction: ascending. Should we keep this?

**Comment by quicksketch** [comment]
>  And @quicksketch you OK with my fake tablesort? 

Yeah fake table sort is fine, as we don't have any way to tablesort on non-SQL columns currently.

> I made an issue (#2149) to modify backdrop_sort() to allow sort direction because this implementation only allows sorting one direction: ascending.

As we don't have a reverse `backdrop_sort()` yet, but you need one now, why not do a standard-`backdrop_sort()` and then just `array_reverse()` the order?

**Comment by docwilmot** [comment]
> just array_reverse() the order

Brilliant. Worked of course.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/1531 into 1.x for 1.5.0. Way to knock out another one @docwilmot! Thanks @olafgrabienski for your input and @BWPanda for getting the ball rolling on this so long ago.
