### ISSUE TITLE
Cannot exit link and continue typing on the same line. (Issue exist on ClassicEditor downloaded sample)

### ISSUE THREAD

**Issue by kherona** [backdrop/backdrop-issues#4491]
**Description of the bug**
When adding a link to any word in the editor, I cannot ever exit the link unless I press enter (go to new line). Pressing escape, multiple spaces or anything else fail.

**Steps To Reproduce**
Download CKEditor 5 ClassicEditor build and use the sample html file and add link.

**Actual behavior**
Link editing is not exiting, below is an example from sample downloaded (same problem on my site):

![Untitled Project](https://user-images.githubusercontent.com/21297414/87860736-f26cba80-c950-11ea-92ad-7b83b79080cf.gif)

**Expected behavior**
Link editing should exit on space or exit or both.

**Additional information**

Tested this on Chrome + Firefox. Same behavior.

**Comment by stpaultim** [comment]
@kherona - Is this an issue with Backdrop CMS? 

Backdrop CMS uses CKEditor, but I don't recognize the configuration used in the screenshot and am confused by the reference to ClassicEditor. 

Is it possible this issue is in the wrong issue queue?

Maybe, I'm just missing something. Please, confirm that you are using Backdrop CMS.

**Comment by kherona** [comment]
Hello sorry, I must have raised this in the wrong url..  (you can close this, I'll raise the problem with CKeditor team).

Thanks

**Comment by stpaultim** [comment]
No problem. If you are having problems with CKEditor integration for Backdrop CMS, then this is the right place.
