### ISSUE TITLE
CKEditor settings not respecting language.

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#4492]
**Description of the bug**

The code is the description :wink: 

https://github.com/backdrop/backdrop/blob/c98bf5148875a4e829754d30afd940d79c8ee87f/core/modules/ckeditor/ckeditor.module#L520

```
 global $language;
...
...
'language' => isset($language->language) ? $language->language : '',
```

Anyone else having a deja-vu here? That should be:

1. `$language->langcode`
2. No need for isset() - that's a global. (OK, it has no _language_ property, it's *langcode*)

What's the problem for users, if the editor's ui lang isn't set correctly?

1. The tooltips on editor toolbar don't show in the right language (en is the fallback)
2. Web browsers also depend on that lang="XX" and possibly mark everything as misspelled inside the editor

I did a recursive grep through core and found several more instances of `$language->language`.
Every here and there there's another _language vs. langcode_ issue - shouldn't we fix this once and for all throughout core?

**Comment by indigoxela** [comment]
Here's a [PR](https://github.com/backdrop/backdrop/pull/3195) for the CKEditor language problem.

**How to test:** you need at least a second language because "en" always works (is the fallback).

Then check the toolbar titles of CKEditor - if the editor ships with a language file for your current language, the toolbar titles should show up in that language.

You can also check if the editor's iframe gets the proper `lang` attribute (browser dev tools), and alternatively check the html source code for the ckeditor `language` variable.

**Comment by jenlampton** [comment]
> shouldn't we fix this once and for all throughout core?

Yes!  Let's make an issue for that: https://github.com/backdrop/backdrop-issues/issues/4495

I had one question on the PR about removing the isset. Even though `$language` is a global, I worry that there might be instances where the langcode property might not be set, or where it might be null. If it doesn't hurt to leave it in there, I say better safe than sorry.

**Comment by quicksketch** [comment]
> Even though `$language` is a global, I worry that there might be instances where the langcode property might not be set, or where it might be null.

I merged the current PR, sorry I didn't see the current tag of "needs work". Adding back the `isset()` wouldn't hurt, though searching through the code base we seem to have a mix of checking for the global value and just assuming it's there.

Setting the page language is a late-bootstrap operation, here's the full list of stages:

```
 *   - BACKDROP_BOOTSTRAP_CONFIGURATION: Initializes configuration.
 *   - BACKDROP_BOOTSTRAP_PAGE_CACHE: Tries to serve a cached page.
 *   - BACKDROP_BOOTSTRAP_DATABASE: Initializes the database layer.
 *   - BACKDROP_BOOTSTRAP_LOCK: Initializes the locking system.
 *   - BACKDROP_BOOTSTRAP_VARIABLES: Initializes the variable system.
 *   - BACKDROP_BOOTSTRAP_SESSION: Initializes session handling.
 *   - BACKDROP_BOOTSTRAP_PAGE_HEADER: Sets up the page header.
 *   - BACKDROP_BOOTSTRAP_LANGUAGE: Finds out the language of the page.
 *   - BACKDROP_BOOTSTRAP_FULL: Fully loads Backdrop. Validates and fixes input
```

Unless the page is being served by the page cache, or it's a special operation page that does it's own bootstrap,  pages are going to be using the final stage `BACKDROP_BOOTSTRAP_FULL`. You need that to do anything like deliver a menu route, render a form, or load a node. I think where you see checking `isset($language)` to be common is in functions that might be called without a full bootstrap. I don't think `ckeditor_get_settings()` qualifies for being loaded without a full bootstrap, because it calls `backdrop_alter()` (creating a hook to let all loaded modules respond). And it's inside of a .module file, which would only be loaded on full bootstrap anyway.

So... I don't think the `isset()` check is necessary. But I could be wrong and it doesn't hurt having it in there. If someone files a follow-up PR, we can merge it too.

**Comment by quicksketch** [comment]
I forgot to mention, thanks @indigoxela! I merged https://github.com/backdrop/backdrop/pull/3195 into 1.x and 1.16.x.
