### ISSUE TITLE
Add webp support

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#4509]
**Description of the need**

A common "Opportunity" listed in Google PageSpeed insights is to "Serve images in next-gen formats." Backdrop does not currently support any next-gen formats.

**Proposed solution**

Backdrop should at least support `webp` which can make large images dramatically smaller with its better compression.

As of php 7.1.0 gd supports webp. To be backwards compatible, but still provide webp support on more recent php, we can check for the constant `IMAGETYPE_WEBP`.

**Initial idea(s)**

 - This PR is adapted from Vincent Demers in the Drupal 7 `imagecache_actions` module queue: https://www.drupal.org/project/imagecache_actions/issues/2982694#comment-13035990 
 - The second half of his patch is implented in a branch in the `image_effects` module (the Backdrop version of `imagecache_actions`) pending this core support.
 - I've done a few tests and see major compression gains on large hero-style images: 
   - 343 KB (JPG) vs. 265 KB (WEBP)
   - 109 KB (JPG) vs. 41 KB (WEBP)

---

1.18.0 milestone advocate: @indigoxela, status: RTBC (last update 2020-11-30)

---

- <strike>PR by @laryn based on Vincent Demers work: https://github.com/backdrop/backdrop/pull/3204</strike> (outdated)
- PR by @indigoxela to [add webp support to core](https://github.com/backdrop/backdrop/pull/3265) (if gd version supports webp)

**Comment by laryn** [comment]
The PR can be tested with the `Coloractions` submodule of `Image Effects` (using the "Change file format" image style action) along with this PR:
https://github.com/backdrop-contrib/image_effects/pull/9

**Comment by klonos** [comment]
I'm supportive of this 👍 ...the PR looks very minimal, and there was only a trivial coding standard thing to fix.

**Comment by klonos** [comment]
...IE excluded (typical 🙄 ), most major browsers support this format: https://caniuse.com/#feat=webp

**Comment by oadaeh** [comment]
I feel like this is related to https://github.com/backdrop/backdrop-issues/issues/3136 and https://github.com/backdrop/backdrop-issues/issues/3851.
And I feel like this is the first thing that needs to be done: https://github.com/backdrop/backdrop-issues/issues/3136#issuecomment-506351365
Then it will be easier to add any image type without workarounds and exceptions.

**Comment by indigoxela** [comment]
I was really curious, how much it needs to let Backdrop "talk" webp on a recent php version. It turned out - a minimal change is needed to get both, upload and derivatives running.

The downside: webp requires at least **php 7.1.0.**

I've created an [experimental PR](https://github.com/backdrop/backdrop/pull/3265) for further discussion.

**Note:** you can't test webp in the sandbox - way too old php.

Test locally: Apply changes, then set an image field to allow webp extension (for instance admin/structure/types/manage/post/fields/field_image).
Then upload a webp image, check that derivatives get also created as webp.

@laryn: I'm aware that you're actually after webp *output*, even if the uploaded image wasn't, but that should be easier, too - as soon as Backdrop provides it without hacks and hooks. :wink:

**Comment by docwilmot** [comment]
> The downside: webp requires at least php 7.1.0.

Also curious: what aspect of the implementation requires PHP 7.1?

**Comment by indigoxela** [comment]
Two things re my PR  might be interesting:

1) Why I know the exact php version we can use webp - the constant came together with support of webp in function getimagesize:

https://www.php.net/manual/en/image.constants.php#constant.imagetype-webp

2) Where this "magic" 18 comes from in the mapping:

That's the value of constant `IMAGETYPE_WEBP`

**Comment by docwilmot** [comment]
I'm now confused. How does @laryn's PR work with @indigoxela's PR? Whats the difference here? Are we approaching two different things (image manipulation server-side vs display)? Need some clarity here I thinks.

**Comment by indigoxela** [comment]
These two PRs are pretty different approaches.

Mine tries to add webp support to core, @laryn tries to get in the hooks, so he can do his stuff in contrib (which he currently can't).

**Comment by herbdool** [comment]
I haven't tested either PR, but I like that @indigoxela's PR is backwards compatible.

**Comment by laryn** [comment]
I am certainly not wedded to the PR I submitted -- it was largely based off a patch I found in the contrib queue on the Drupal side to shoehorn `webp` support in. I'm happy to rework anything on the contrib side if we can get official support in core via @indigoxela's PR.

**Comment by docwilmot** [comment]
Perhaps you two should have a discussion and attempt to merge both PRs?

**Comment by indigoxela** [comment]
> Perhaps you two should have a discussion and attempt to merge both PRs?

That's a good idea.

I tested my PR with parts of @laryn's PR and his new module branch - his contrib module works if I only add his two hook new definitions. The change beginning with line 784 becomes obsolete.

Another finding: `backdrop_alter('image_style_deliver', $style, $image_uri, $derivative_uri);` is actually not necessary, because that part can already be accessed via [hook_menu_alter()](https://api.backdropcms.org/api/backdrop/core%21modules%21system%21system.api.php/function/hook_menu_alter/1) - by overriding the `page callback` for `$items[$directory_path . '/styles/%image_style']`.

So the only thing his contrib module needs, is my small core change plus one additional hook - but wait, there's more...

He needs to alter the path provided by [file_create_url()](https://api.backdropcms.org/api/backdrop/core%21includes%21file.inc/function/file_create_url/1) - which already uses a hook: hook_file_url_alter().

@laryn very likely the only thing you need is that we add webp support to core. Everything else is (should be?) already accessible by existing hooks - at least that's what my impression is after playing with your experimental module branch.

**Comment by indigoxela** [comment]
I wonder if it makes sense to split this Issue into two tasks:

1. Add webp support to core
2. Provide additional hook(s) for contrib, if necessary

It seems that @laryn is short at time (as ususally :wink: ) and this sort of blocks progress here.

**Comment by laryn** [comment]
@indigoxela yes, I am short on time but your plan sounds good. Let's get webp support in as a first step.

**Comment by herbdool** [comment]
@indigoxela wondering if we should also check for imagemagick support?

In theory, there could be other image toolkits too but very unlikely.

**Comment by indigoxela** [comment]
> wondering if we should also check for imagemagick support?

That's a good point. Although none of the toolkit modules seems to be ported yet, we should consider them. An alter hook in function image_field_widget_form will be helpful. PR has been updated.

**Comment by herbdool** [comment]
@indigoxela I'm suggesting a small change. Looks good otherwise

**Comment by indigoxela** [comment]
My PR has been updated accordingly.

Again for testers: you can't use the sandbox because of the old php versions. Test locally with php at least 7.1.0.

**Comment by jenlampton** [comment]
This is tagged as a new feature, but scheduled for a bug-fix release? Bumping to 1.18 for now. Also if this is a new feature, the PR needs tests :)

**Comment by indigoxela** [comment]
> Also if this is a new feature, the PR needs tests :)

Sure, I agree, but there's a problem: these tests would also require a php version 7.1.0 or newer - something we don't have in our testboxes. So I've no idea what to test for. The only thing that comes to my mind: test that webp is not supported in php 5.3 nor 7.0. :wink:

**Comment by domaingood** [comment]
I think Its time to move PHP 7.3 Min requirement for backdrop. Because Php 5 not supported by PHP nor PHP 7.0, 7.1, or 7.2
https://www.php.net/supported-versions.php

**Comment by oadaeh** [comment]
While it is a nice idea, we cannot stop supporting older versions of PHP just because they are EOL. Several Linux distributions and hosting companies still support older, EOL versions of PHP, and so Backdrop still has to be able to work on many of them.

**Comment by indigoxela** [comment]
@jenlampton as the "needs test" label on this issue would block it until we have test boxes with newer PHP versions than we have now, and as this issue here is a contrib blocker, I remove the "needs test" label. I hope that's OK for you.

**Comment by jenlampton** [comment]
Ok with me, but might not be okay to core committers.

**Comment by herbdool** [comment]
I think we can still add automated tests but just run it locally.

**Comment by indigoxela** [comment]
Tests have been added. I belief they provide something useful for both, old and new php versions.

I can switch php versions on my dev, tested with 5.6 and 7.2.

**Comment by jenlampton** [comment]
Who's the advocate for this issue? Is it @laryn? I see it has a milestone so want to do updates weekly in our meetings :)

**Comment by indigoxela** [comment]
I'll be advocate for this issue so @laryn can advocate for something else.

**Comment by quicksketch** [comment]
We do need to get the test bot running newer versions of PHP. I would suggest we not block this issue though, write tests that only execute on PHP 7.1+ and we can run them locally to approve this PR.

**Comment by indigoxela** [comment]
@quicksketch Did you miss that tests have already been added a month ago?

That should be updated in the dev agenda (I don't have permission to).

**Comment by indigoxela** [comment]
What a shame, our new Tugboat testing boxes have php 7.2, but the bundled gd version (2.1.0) doesn't support webp. Just verified that via phpinfo (admin/reports/status/php, section gd).

So testing this PR still needs to happen locally.

**Comment by indigoxela** [comment]
Having a closer look now... Wait, php is new enough, constant IMAGETYPE_WEBP is set, but there's still no webp support in gd.

My PR needs to take this into account, too.

**Comment by indigoxela** [comment]
Back on track. I fixed it by adding an extra check using `gd_info()`. Both checks are needed, the constant verifies that `getimagesize()` is able to handle webp, `gd_info()` verifies that gd is compiled with webp support.

Let's see it as an advantage that the new test boxes ship with an uncommon php/gd combination.

**Comment by indigoxela** [comment]
How to test:

1. Make sure that your php version new enough (7.1.+)
2. Make sure that your gd version supports webp: go to admin/reports/status/php, scroll down to the gd section and search for "WebP Support - enabled"

![webp-support-enabled](https://user-images.githubusercontent.com/842066/98461642-30b31180-21ae-11eb-8157-e0ad0da203eb.png)

Then add or edit a content type with image field and add "webp" to allowed extensions in the field settings.

Add or edit such a node type, upload a webp image and check that:

1. After uploading the thumbnail gets created (node form)
2. The node can get saved
3. After saving the image appears in node display and is of type webp

If your php/gd does *not* support webp, you shouldn't be able to upload a webp image even if you added it to the extensions list in in image field settings.

**Comment by philsward** [comment]
Tested. See: https://github.com/backdrop/backdrop/pull/3265#issuecomment-723827341

(oops!)

**Comment by indigoxela** [comment]
@philsward no need to excuse, you're welcome :smiley: 

> PHP 7.4
> Need me to test any older versions? I have 7.2, 7.3 and 7.4 installed in my environment

Testing additional versions of PHP/gd is very helpful. Which gd version was it in that test? Is it a development environment or more like "real" hosting?

**Comment by philsward** [comment]
@indigoxela GD Version	bundled (2.1.0 compatible)

It is a real hosting server. CentOS7 cPanel environment

Using PHP-FPM in case that matters

Tested 7.2.34
Tested 7.3.23
Tested 7.4.11

All look good!

**Comment by indigoxela** [comment]
Based on @philsward's testing I'm setting this to "works for me". (Although more testing in different environments could be helpful and is appreciated.)

Remaining task: code review. @herbdool and @klonos mind to chime in? You both already started reviewing.

**Comment by herbdool** [comment]
I've looked through the code again and I think it looks great now. Thanks @indigoxela

**Comment by domaingood** [comment]
I m want to webp test But where I can get this full zip file for test

**Comment by philsward** [comment]
@domaingood if you aren't using command line git, you have to look at each one of the committed files on GitHub, tell it to show you raw, then use the link to that file to either wget it via command line or download it local and upload it to your environment.

You have to replace each one of the files that have been committed with the original ones in your core base.

Sorry for not explaining better, I'm typing on mobile and not directly in front of the desktop interface.

Point is, you can find the changed files here within this issue on git. They are not zipped as a package but rather the actual file that has changed.

**Comment by indigoxela** [comment]
> I m want to webp test But where I can get this full zip file for test

@domaingood testing is always welcome. Maybe a little more convenient (when not using git) is to download the [branch zip file](https://github.com/indigoxela/backdrop/archive/4509-experiment-webp.zip), extract it locally and replace the "core" directory of your testing web with the one from the zip file.

If using git, clone only the relevant branch: `git clone -b 4509-experiment-webp --single-branch https://github.com/indigoxela/backdrop.git`

**Comment by klonos** [comment]
@indigoxela thanks for all your work on this 🙏 ...I believe that it will be a great addition to the list of features when we ship 1.18.0 👍 

I don't want to upset you about inline comments etc. 😅 ...but if you have time/energy, you could change the lower-case mentions of PHP, GD and WebP (see https://en.wikipedia.org/wiki/WebP and https://developers.google.com/speed/webp for the correct way that this is written by its creators), unless we are referring to the file extension instead of the standard, in which case it should be `.webp`.

One other piece of feedback: we will advertise that Backdrop 1.18.0 ships with WebP support, and we can stress that this is **only if the installed PHP version supports it**. Still, most people will not read the fine print, or may not be tech-savvy enough to understand all that. How do we handle the fact that they may add `.webp` as an allowed extension in their field configurations, while it is not supported? Can we add a check for this, and warn site builders? My goal would be to catch things early, before end users (i.e. content editors) start seeing errors when trying to upload such images. I would like some sort of message like "you've added .webp in the allowed file extensions, but this system does not support it" be added either to the site status page, or the file extensions filed in the file config form, or both (and this can be a follow-up). Thoughts?

**Comment by indigoxela** [comment]
> I don't want to upset you about inline comments etc. sweat_smile ...but if you have time/energy, you could change the lower-case mentions of PHP, GD and WebP

:laughing: Sure, will do so.

> Still, most people will not read the fine print, or may not be tech-savvy enough to understand all that. How do we handle the fact that they may add .webp as an allowed extension in their field configurations, while it is not supported?

Good question... "warn" in how far and where?

> My goal would be to catch things early, before end users (i.e. content editors) start seeing errors when trying to upload such images

With "errors" you mean "form validation errors", right? I wouldn't know how to prevent that if they upload unsupported stuff.

**Comment by indigoxela** [comment]
Ah, [there it is](https://github.com/backdrop/backdrop-issues/issues/3851). We already have an issue for field setting validation (prevent supported extensions in field settings).

**Comment by quicksketch** [comment]
The PR looks totally great! I did a code review on it and everything seems to be exactly where it should be and safely checking if the web server supports webp before adding it. I also love that it is extensible so that the ImageMagick module can also add system-wide support for `webp`.

With @herbdool's already existing RTBC, I've merged https://github.com/backdrop/backdrop/pull/3265 into 1.x for 1.18.0. 

Big thanks to everyone who worked on this issue! @indigoxela, @laryn, @klonos, @docwilmot, @herbdool, @philsward, @domaingood, and @oadaeh!
