### ISSUE TITLE
[UX] Redirect to the dblog settings page after configuring a date format for it.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4523]
This is a follow-up to #4425.

Consider this scenario:

1. navigate to `admin/config/development/logging`
2. see that there are no formats that match your needs
3. use the link in the help text to go to the date formats page
4. create a new date format, or tweak and save the newly-introduced one from #4425
5. now you need to "manually" return to the dblog configuration page to change the setting

Can we fix/improve that please? ...I was thinking either one of these options:
  - add a destination to the link in the help, or in `$_SESSION`; then use that to automatically redirect people to `admin/config/development/logging` once they save the date format.
  - set `target=”_blank”`, so that they can configure the format on another browser tab, then close the tab and return to the tab with the dblog config form (would still require them to refresh the page for the select to be refreshed with the new format)
  - Add a message of type `info` to the format edit page, if the format is what is currently used in `config_get('system.core', 'log_date_format');`. Something along the lines of `backdrop_set_message(t('This date format is being used for <a href="@logging">log messages</a>, array('' => url('admin/config/development/logging'))), 'info');`

**Comment by BWPanda** [comment]
I just tested the first option (adding a `destination` parameter to the link), but it doesn't work, as it's lost as soon as you click a new link (e.g. 'Configure') on the new page. So I think opening the link from the help text in a new window/tab (option 2) is the way to go.

**Comment by BWPanda** [comment]
PR: https://github.com/backdrop/backdrop/pull/3245

**Comment by jenlampton** [comment]
I'm not sure this is necessary. 

I just went through this exact process on 3 different sites:
1. go to the log - see my dates are messed up
1. go to the dblog configuration page - see that the date format option is no longer here, but there is a new date format
1. follow the link from here to the date format settings - adjust the new format
1. go back to the log

> now you need to "manually" return to the dblog configuration page to change the setting

I never wanted this.

I think the extra redirects might have been useful if we didn't provide the new date format, but since we do, there's no reason to return to the dblog configuration page after adjusting the new format.

**Comment by BWPanda** [comment]
This is no longer relevant as the linked issue was reverted, so none of the STR apply now. Closing.

**Comment by klonos** [comment]
For posterity, here's what the UI that allows you to tweak the date format used in the logs looks like now:

![image](https://user-images.githubusercontent.com/2423362/156175872-0e788b5f-7f89-436b-8312-f8dd6c6ced36.png)
