### ISSUE TITLE
Replace links to PHP date formatting notes

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4536]
PHP.net moved the page with date format documentation from `https://www.php.net/manual/en/function.date.php` to `https://www.php.net/manual/en/datetime.format.php`

We should update the links on `admin/config/regional/date-time` and in the description text for the `Custom date format`.

**Comment by BWPanda** [comment]
There's a bit of scrolling needed to find the actual table of formats, and no way to link straight to it from what I can see. Since I doubt those formats would change much, I wonder if it'd be better for us to create our own page to link to...? Either in Backdrop itself (in a modal like the tokens one), or on b.org/api.b.org.

**Comment by jlfranklin** [comment]
The [Date/Time Format Help](https://backdropcms.org/project/date_format_help) will include the documentation directly on the "Add date format" page.

**Comment by klonos** [comment]
> in a modal like the tokens one

You're in my head @BWPanda 👍 ...separate issue though (feature request).

**Comment by klonos** [comment]
...let's get this out of the way for now: https://github.com/backdrop/backdrop/pull/3259

> ...no way to link straight to it from what I can see.

https://www.php.net/manual/datetime.format.php#refsect1-datetime.format-parameters 😉 

Question: since this is already being used in a bunch of places, should we add it to a constant or helper function in date.inc, so that we need to update one place next time?

**Comment by BWPanda** [comment]
> should we add it to a constant or helper function in date.inc, so that we need to update one place next time?

@klonos That sounds good. Want to update the PR with that in mind?

**Comment by stpaultim** [comment]
I was wondering what happened. I was just working on date formats last night and had difficulty finding that page, and I followed the inline link. Let's get that fixed quickly. :-)

**Comment by klonos** [comment]
> Want to update the PR with that in mind?

Sure thing @BWPanda ...but should it be a function or a constant?

> Let's get that fixed quickly.

Added milestone for the next bug fix release.

**Comment by BWPanda** [comment]
> should it be a function or a constant?

I think a constant is fine, assuming that works. Don't see the need for a whole function just for that...

**Comment by jenlampton** [comment]
> Added milestone for the next bug fix release.

Ah, good idea. Seconded :)

**Comment by herbdool** [comment]
Looks good!

**Comment by BWPanda** [comment]
@klonos is yet to add that constance value... Also there are test failures which I'm guessing are random/unrelated, but I can't see them to confirm (grumble grumble https://github.com/backdrop/backdrop-issues/issues/4351)...

**Comment by quicksketch** [comment]
Search/replace seems fine to me. We don't have constants for URLs elsewhere and if PHP does change the URL again (seems unlikely), we can just update them again.

**Comment by klonos** [comment]
Back to RTBC then 🙂

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/3259 into 1.x and 1.16.x. Thanks @klonos, @jenlampton, @BWPanda, and @herbdool!
