### ISSUE TITLE
Add specific permission for the ability to schedule posts

### ISSUE THREAD

**Issue by stpaultim** [backdrop/backdrop-issues#4543]
**Description of the need**

In #4541 it was pointed out that the only way to allow users to schedule a post is to give them "administer content" privileges, which is quite permissive and allows a user to edit other users posts. In that issue, it was the editor role under consideration and that option seems reasonable. 

But, do we want to make it possible for a user to schedule their own posts WITHOUT giving them permission to edit other peoples posts? If so, we may need a new permission. 

I am not sure myself, if this permission is necessary, but it seems like a legit use case (raised by @klonos), so opening this issue for further input.

**Proposed solution**

Add a specific permission that allows a user to schedule their own content.

**Alternatives that have been considered**

Including this in advanced workflow features - https://github.com/backdrop/backdrop-issues/issues/4355
Contrib

**Additional information**

I don't believe that we currently have the option to grant a user the ability to create a node, but not publish it. If we did, the permission to schedule content might be included. I am not sure that we need that specific permission in core. That option might be better handled by advanced workflow modules (in core core or contrib)

**Comment by klonos** [comment]
Thanks for raising this issue @stpaultim, but I think that we should close it as a duplicate of #815, and include the ability to schedule in the scope of #815. You see, #815 was created in 2015, before #857 that introduced content scheduling (in 1.10.0, in 2018), and back in 2015, the only options in the "Publishing options" vertical tab in the content edit form were "Publish" and "Save draft".

So, if we decide to go with a single permission that allows publishing + saving as draft + scheduling, then we should close this issue here. If we decide to be more granular, we can aim for a set of 2 permissions: one for publishing/drafting (which would basically be #815), and a separate permission for scheduling (which would be this issue here).

**Comment by stpaultim** [comment]
Makes good sense to me.

Closing as duplicate.
