### ISSUE TITLE
Regression: CKEditor broken after #4527

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#4592]
**Description of the bug**

On nodes with CKEditor enabled fields and image fields the editor is broken.

js error:
`Uncaught TypeError: Backdrop.editors is undefined`

The problem seems to be the order of js files.
If fillter.js runs after ckeditor.js Backdrop.editors is undefined in ckeditor.js

I can fix the problem locally, if instead of adding the js file via `#attached` adding it via `backdrop_add_js()`, I don't even need to set a weight. ckeditor.js gets loaded after filter.js then (as the js dependencies are properly defined).

It seems that when using `#attached` the js file "slips" into the wrong js group.

**Steps To Reproduce**

1. Get a version of Backdrop including [this recent change](https://github.com/backdrop/backdrop/commit/9e72b28d570d585cdb68d87e203d96278a152a2f)
2. Go to node/add/post (post has a textarea with CKEditor enabled and an image field)
3. Editor won't load

**Additional information**

- Backdrop CMS version: latest dev

**Proposed solution**

~Use `backdrop_add_js()` instead of '#attached' in file_managed_file_process(). Or are there better ideas?~

Use a `#attached` library that handles the dependency instead of adding the CSS and JS individually.

PR: https://github.com/backdrop/backdrop/pull/3283/files

**Comment by jenlampton** [comment]
Hm, I think using `#attached` is the right way to add the js here. Would it be possible to fix the problem by specifying a group or weight for both `filter.js` and `editor.js` instead?

**Comment by quicksketch** [comment]
It looks like filter.js and filter.css are grouped together in a library provided by Filter module. CKEditor's hook_library_info() already states it's dependent upon the "filter" library, so if we switch this to using the library instead of the direct CSS/JS files, they should be put in the right order for us by the library system.

**Comment by quicksketch** [comment]
I posted a PR to https://github.com/backdrop/backdrop/pull/3283/files that demonstrates the fix. In my testing I believe this solves the problem, but it would be great to have someone else verify that the filter.js and filter.css files are loaded in the right order now on a site where the problem is known to exist.

**Comment by klonos** [comment]
Well, the regression we has is easy to test: on a vanilla Backdrop installation of the latest 1.x branch, CKEditor loads fine for node types that don't include an image field ("Page" OOTB), whereas there's no CKEditor for node types that have image fields ("Post" OOTB). I've tested this in the PR sandbox, and it works as expected in both types, so we've addressed the regression.

I've also tested to ensure that we have not re-introduced #1259 or #4527 👍

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/3283 into 1.x and 1.16.x.
