### ISSUE TITLE
Add an admin UI for control over which libraries (& versions of) are in use

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#462]
As a follow-up from https://github.com/backdrop/backdrop-issues/issues/159

It would be handy if we could build an admin UI that listed all available libraries, and the versions that are both available and in use.  We could have something like the modules page that provides admins the ability to toggle them each on and off. 

We could either start from porting the libraries module from Drupal to Backdrop, build something that works like the jQuery Update Drupal module, or start fresh with our own admin UI for managing these things.  

Whatever approach we take, I'd like to see the solution mature in contrib before it gets moved into core.  I'm going to mark this issue as postponed for now, but please add a comment linking to the backdrop contrib project and remove the tag when we're ready to consider this module for inclusion in core.

**Comment by klonos** [comment]
Related: jQuery Update provided an admin UI for selecting which version of jQuery would be used for the website and at some point they've added the option to select a different version of the jQuery for the admin pages in the backend (because some pages/elements/features would break when using specific versions of jQuery). Here's how their 2.x config UI looks like:

![jquery_update-2 x_settings](https://cloud.githubusercontent.com/assets/2423362/6985805/d00ac2f6-da82-11e4-877a-0fca7650bd43.png)

With their latest 3.x version, they still allow to set a site-wide version, but the fallback to a different version was converted to a theme-specific option to account for other installed themes as well:

![jquery_update-3 x_settings](https://cloud.githubusercontent.com/assets/2423362/6985813/e8e96f0c-da82-11e4-887f-533184ece7a3.png)

Given the fact that our version of jQuery is updated and we fixed any known issues or will fix any issues that come up (because they'll be core bugs), what are our intentions with regards to this specific library?...

1. Do we intent to provide CDN support? Some people use this for increased speed.

2. Do we promise to keep up to date with the latest version (and fix any UI issues that updating may cause)?

3. What is our policy with regards to contrib themes and/or modules that use this library? I mean, if updating the version that we ship with core breaks them, how do we handle that? Do we consider this a contrib issue and let the project deal with it, or do we ship a few (latest minor) versions back and provide a UI similar to the one that jQuery Update provides?

**Comment by klonos** [comment]
...with regards to point 2 above, we do have "Updated jQuery and jQuery UI" listed as an improvement over D7 in our home page.

**Comment by quicksketch** [comment]
> Do we intent to provide CDN support and/or compression options? Some people use these for increased speed.

Not in core I don't think. Shared CDN library loading is a bit of a double-edged sword.

> Do we promise to keep up to date with the latest version (and fix any UI issues that updating may cause)?

We'll update jQuery within the current main branch (1.x) of jQuery to accommodate for bug fixes, yes. We have yet to see what the next versions of jQuery will bring. Now that they have adopted semantic versioning, the [next version of jQuery will be 3.0](http://blog.jquery.com/2014/10/29/jquery-3-0-the-next-generations/). It's not clear how significant the changes in the next version will be.

> if updating the version that we ship with core breaks them, how do we handle that?

If possible, I'd like to keep core up-to-date and use a contrib module to provide the *old* versions. So instead of jQuery Update, we'd have a jQuery Downgrade contrib project.

---

For this entire proposal, I'm not sure a UI for this is a good fit for core. Modifying your library versions is something that's very likely to break modules or themes. It shouldn't be up to the end-user to figure out which library versions to use (or be allowed to change them). The core and contributed modules using the libraries should ensure they have compatible versions or refuse to function entirely.

**Comment by klonos** [comment]
Fair enough. Now that I thought this over and after your remarks, a UI for jQuery + older versions does seem more fitting in contrib land. I think *jQuery Legacy* sounds better than downgrade though :wink:

**Comment by klonos** [comment]
...does this though mean that this whole issue is a won't-fix?

**Comment by jenlampton** [comment]
I think so.  If we get a UI proven in contrib we can open a new issue to move that into core :)

**Comment by klonos** [comment]
Once again, fair enough.

**Comment by mikemccaffrey** [comment]
I created #1593 to discuss the issue of whether there should be a UI in core to allow libraries to be served from CDNs if desired, which might also include the ability to select different versions.
