### ISSUE TITLE
[UX] Redirect to the Dashboard after install

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4673]
When we install a new Backdrop site, we redirect people to the front page immediately after logging them in. But once your backdrop site is up and running, we redirect people to the dashboard immediately after logging them in.

I'd like to recommend that we redirect people to the dashboard after installation.

Follow-up to https://github.com/backdrop/backdrop-issues/issues/4162

**Comment by stpaultim** [comment]
This issue is at least in part inspired by watching a new contributor navigate around the site trying to find where to update the site name and logo. I expected them to find the dashboard and all the helpful tips that are on the dashboard, but this user never found it until we suggested they click on the dashboard link.

I think it would be helpful for a new user to know that this dashboard page exists and that it might be a good place to go for basic help.

**Comment by klonos** [comment]
I won't object to this change if that's what most people agree is the best UX, but wanted to express my opinion.

Manually logging in vs. being automatically logged in once the installer finishes are two different "user journeys". Once the site installation has finished, people are likely to visit the site's home page, to click on the "log in" link. This means that they get to see what a freshly-installed Backdrop site looks like, so it makes sense to redirect them to the Dashboard after they log in. When the installer finishes though, the person performing the installation has no idea what the front page and the frontend theme looks like, so IMO it is a good thing that we are not redirecting them to the Dashboard.

Now, I don't deny the UX issue here, since people seem to miss noticing that there is an admin menu bar at the top; perhaps they do notice it, but it just seems overwhelming because there are so many options in there. I think that there's a way to solve this, while still allowing people that install Backdrop to get a peek at what the site they just installed will look like for their site visitors. So how about instead of redirecting them to the Dashboard, we add an "info" message right bellow the "Thank you for installing Backdrop" success message? Something with a link to the Dashboard, like this:

> You can use the admin menu at the top of the page, to navigate around the administrative interface. If you are new to Backdrop, then [the Dashboard]() may be a good place to start.

**Comment by stpaultim** [comment]
I will look at your PR. I do view providing contextual help to find the dashboard might be an alternative to this solution. 

I agree that there is value in landing on the front page after install. But, I would also argue that it's much easier to get to the front page from the dashboard than it is the reverse. I'm not fully decided on which option is best. I just think it's important that we help new site owners find the dashboard quickly.

**Comment by jenlampton** [comment]
> When the installer finishes though, the person performing the installation has no idea what the front page and the frontend theme looks like, so IMO it is a good thing that we are not redirecting them to the Dashboard.

I think it's a bigger problem that people don't know what to do after they complete the installer. The Dashboard has a lot of helpful links to other things they can do, the home page has nothing. :(

**Comment by stpaultim** [comment]
@klonos - Is there a META issue for issues related to this? (I'm not sure what they would be)

**Comment by klonos** [comment]
> I will look at your PR.

There's a silly mistake in it which brings up fatal php errors (I just whipped it up via the GitHub web UI 😅 ) ...I've fixed it on my local but I'm having issues pushing to that branch for some reason.

> Is there a META issue for issues related to this?

Not that I know of 🤷 

>The Dashboard has a lot of helpful links to other things they can do, the home page has nothing. :(

Yup, that's why I'm proposing this:

![image](https://user-images.githubusercontent.com/2423362/95142137-abd27380-077b-11eb-9ba0-7221d7044bea.png)

**Comment by klonos** [comment]
...PR (manually) updated.

**Comment by stpaultim** [comment]
This works as expected. i believe that this PR is a clear improvement over the status quo - pending some text changes. I do not have a strong preference between this option or the suggested solution to redirect to the Dashboard after installation. I see pros and cons to both.

Regarding text changes. I do not think that the message about the admin menu is very helpful and adds clutter. I believe that the admin menu is pretty easy to see and find. Do we have any evidence that new users are having difficulties finding or understanding the admin menu?

I think a simpler message that is focused on finding the Dashboard would be more helpful. 

"Tip: New users should visit **the Dashboard** for ideas on how to get started with their new Backdrop CMS site."

**Comment by stpaultim** [comment]
This issue is tagged for the bugfix release, but has not had any action in almost a year. I added it to the agenda for the next UX meeting to see if we can break the logjam and decide on a path forward?
https://docs.google.com/document/d/1C42vvx0U61Hmj1HKsbOULtEOV0XWI4Y0KrOKvej1Zi8/edit#

**Comment by jenlampton** [comment]
I just happened to talk to @quicksketch about this yesterday, and he said that he likes that you get taken to "your website" after installation. He said that WordPress does the same thing. 

I can see the benefit of showing someone a fully functional website (before they do any configuration), even if it does leave people with the "What next?" reaction. I would expect the natural "next" action would be to explore, starting in the top left, seeing the admin bar, reading "Dashboard" and navigating there to find all the goodies.

I wonder if this should get some user-testing?

**Comment by stpaultim** [comment]
> I wonder if this should get some user-testing?

I'm in favor of user testing it. However, if you remember we had an informal user test that at least partially lead to this issue being opened: https://github.com/backdrop/backdrop-issues/issues/4673#issuecomment-702464030

**Comment by klonos** [comment]
> I can see the benefit of showing someone a fully functional website (before they do any configuration)...

Same 👍🏼 

> I would expect the natural "next" action would be to explore, starting in the top left, seeing the admin bar, reading "Dashboard" and navigating there to find all the goodies.

Only user studies would shed light on that (whether the "Dashboard" link in the admin bar, or the admin bar itself are easily discoverable).

We already provide an obvious/prominent way for people to get from the Dashboard to "the website" (via the "View the home page" link in the "Welcome to Backdrop CMS" block). Perhaps we should similarly provide a more obvious/prominent way to go from "the website" to the Dashboard. That's what I was going for with this PR.

**Comment by stpaultim** [comment]
Since opening this issue, we've implemented a number of the ideas discussed and added a link to the dashboard. I'm inclined to close this issue as having been addressed in a different way.

**Comment by klonos** [comment]
For posterity, here's what you get after finishing the installation with #5624 (which got implemented in v1.23.1):
![image](https://user-images.githubusercontent.com/3144571/168408032-277c70ca-0007-4c29-9c3e-e5616ae2a6ca.png)
