### ISSUE TITLE
Consolidate places where admin bar cache needs flushing

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#4681]
In `admin_bar.module` there are ~12~ 15 functions that need to flush the cache: https://github.com/backdrop/backdrop/blob/1.x/core/modules/admin_bar/admin_bar.module#L81 (scroll down from that line to see the majority of them).

In the rare event that the code needed to flush the cache changes, or needs adding to, etc., I wonder if a seperate function should be created that does this and then each of those ~12~ 15 functions can just call that one...? See PR for an example of what I mean.

**Comment by BWPanda** [comment]
Here you go: https://github.com/backdrop/backdrop/pull/3352

**Comment by indigoxela** [comment]
I might be missing something obvious, but what is the advantage of function `_admin_bar_cache_flush` compared to `cache('admin_bar')->flush()`?

**Comment by BWPanda** [comment]
> what is the advantage of function `_admin_bar_cache_flush()` compared to `cache('admin_bar')->flush()`?

Maybe nothing (hence the 'question' tag). I just looked at all the places where `cache('admin_bar')->flush()` was being called and thought: I wonder if it'd be better to have that code defined once rather than a dozen times...

Possible benefits:
- If the syntax ever changes
- If we ever need to change the way we flush caches
- If we ever decide to run any additional code before/after a cache flush

**Comment by herbdool** [comment]
I think this is an abstraction that we don't need.

**Comment by BWPanda** [comment]
Closing then.
