### ISSUE TITLE
Overriding the .htaccess and robots.txt files

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#4682]
**Description of the need**

Since updating core discards all modifications made to the `.htaccess` and `robots.txt` files, users have to take additional precautions not to break their websites. They usually back those files up before updating and then
re-create their modifications in the updated version of the files. 

I am exploring here a possibility to make it easy for everybody and to introduce a new feature to override those two files.

**Proposed solution**

What if we introduce a new feature to Backdrop that checks if two files - `.htaccess` and `robots.txt` - exist in the `/sites/default` directory and if they do, then disregard the same files located in the Backdrop root directory? In other words, we could recommend to Backdrop users to never edit those two files in the document root, but instead copy them to `/sites/default` directory and make whatever changes they want to them. 

The problem here is that web-server (Apache) interprets the `.htaccess` file's content as applicable to the specific directory (and sub-directories) where it is located, in this case `/sites/default`. I am not sure if it's possible to just place custom directives in another file and make it override the `.htaccess` file in the root. 

If it's not possible or too difficult to override the `.htaccess` file, then overriding the `robots.txt` file should be pretty simple.

**Comment by BWPanda** [comment]
> Since updating core discards all modifications made to the .htaccess and robots.txt files

Here are part of the instructions for [updating Backdrop](https://backdropcms.org/upgrade):

> 6. Rename the core directory in the root directory of your current codebase "core-old" or similar, and move it outside your Backdrop docroot.
> 7. Put the new core directory from the latest release of Backdrop CMS inside your docroot.
>    - Note: If any of the files outside the core directory have been changed and need to also be updated, they will be explicitly mentioned in the release notes.

In other words, to update Backdrop you simply copy over the `core/` directory from the update to your installation. This doesn't override any `.htaccess` or `robots.txt` files since they reside outside of `core/`. Because of this, each release of Backdrop specifically states whether or not changes were made to those files outside of core so you know to update them yourself (usually you'd just to a diff or something to see what changed, then apply those changes to the files as necessary yourself).

For example:

> No changes have been made to the .htaccess, robots.txt or default settings.php files in this release. Updating customized versions of those files is not necessary.

(from https://github.com/backdrop/backdrop/releases/tag/1.17.1)

**Comment by alanmels** [comment]
@BWPanda Wow, that makes lot's of things much easier. Let me close this issue, because I created it believing Backdrop update was similar to updating Drupal 7.

**Comment by indigoxela** [comment]
> I created it believing Backdrop update was similar to updating Drupal 7

It's pretty different. And you can update core via UI.
