### ISSUE TITLE
Views UI: "Save & exit" button accidentally made primary instead of the "Continue & configure" button

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4694]
@BWPanda [asked in Zulip](https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/Views/near/212958631):

> Can anyone point me to the issue where it was decided to make the Views' 'Save & Exit' button the default, instead of 'Save & Continue'? It changed sometime since 2015: https://github.com/backdrop/backdrop-issues/issues/999#issue-87900725

@BWPanda that seems like a bug to me. With the change that came with the PR for #882, what happens in a series of `'#type' => 'actions'` buttons is that the submit button that comes first in-code always gets the `.button-primary` class. The PR for that issue specifically moved the "Save & exit" button to come after the "Continue & configure" (see [here](https://github.com/backdrop/backdrop/pull/875/files?file-filters%5B%5D=.css&file-filters%5B%5D=.inc#diff-8e6c268efd723011d5ecd609622469ecL431). ...the order of the 2 buttons in-code [remains unchanged till today](https://github.com/backdrop/backdrop/blob/1.x/core/modules/views_ui/views_ui.admin.inc#L469), so **in theory** the "Continue & configure" button should still be the primary one.

I think that the culprit is [this line](https://github.com/backdrop/backdrop/commit/bae764ee21840cc510db68e3bd5c4cd3fe970ff7#diff-8e6c268efd723011d5ecd609622469ecR437), which came as a result of https://github.com/backdrop/backdrop/commit/2823cc0e6ca96df6d72939f8587d9b0fd1f2f7d3 (back in 2011), but the solution implemented for that issue might not be accounting for the re-ordering of the 2 buttons (which for us has happened in #882).

**Comment by klonos** [comment]
Interesting related D8 change: [New Form API submit button property and CSS classes to denote the primary button in a form](https://www.drupal.org/node/1848288)

Perhaps we should consider the same change, and if no specific `'#button_type'` property has been set, then fall back to the current auto-magic way of making the button that comes first be the primary one ...but that would be a totally separate issue 😅

**Comment by BWPanda** [comment]
> I think that the culprit is this line, which came as a result of backdrop/backdrop@2823cc0 (back in 2011)

Confirmed. Commenting out that line shows the buttons as they should be ('Continue' first as default).

**Comment by BWPanda** [comment]
Actually, after looking into this more, I discovered that the code from #882 which adds the 'primary' button class first sorts the elements by weight (see the `$sort` parameter of `element_children()`). However this appears not to work since the two 'submit' type buttons don't have a weight set. Simply adding a weight to one of them make this work properly: https://github.com/backdrop/backdrop/pull/3366

**Comment by indigoxela** [comment]
Yep, works for me.

Here's a screenshot from the sandbox:
![add-view-buttons](https://user-images.githubusercontent.com/842066/96336833-83534f00-1082-11eb-976e-e24b69151e03.png)

Probably it has never been actively decided which one should be the default one. It probably happened because Backdrop inherited the button order from D7.

See this Drupal 7 screenshot for comparison:
![drupal7-views-buttons](https://user-images.githubusercontent.com/842066/96336861-b7c70b00-1082-11eb-807d-99b6e6637afb.png)

Of course, "Continue and configure" is the 99.9% use case here. :wink:

**Comment by quicksketch** [comment]
Thanks team! I've merged https://github.com/backdrop/backdrop/pull/3366 into 1.x and 1.17.x.
