### ISSUE TITLE
Fix the code in hook_admin_bar_output_build

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#4700]
Coming from https://github.com/backdrop-ops/api.backdropcms.org/issues/99 per @BWPanda's recommendation.

Example on https://api.backdropcms.org/api/backdrop/core%21modules%21admin_bar%21admin_bar.api.php/function/hook_admin_bar_output_build/1 never works unless the following line:

```
$content['menu']['myitem'] = array(
```

is changed to

```
$content['menu']['menu']['myitem'] = array(
```

Confirmed by https://github.com/backdrop-contrib/shortcut/blob/a772d2c1f8fa0cb6cabaab0cbc4b6fad8bd89d8c/shortcut.module#L631

**Comment by indigoxela** [comment]
Confirmed with a 5-liner custom module and also verified with the implementation in the [admin_bar module](https://api.backdropcms.org/api/backdrop/core%21modules%21admin_bar%21admin_bar.module/function/admin_bar_admin_bar_output_build/1).

This should be `$content['menu']['menu']`.

@alanmels I've left a comment with a suggestion at your PR. Otherwise it's looking good.

**Comment by alanmels** [comment]
@indigoxela, thanks for the review. PR is updated per your recommendation.

**Comment by BWPanda** [comment]
Thanks @alanmels & @indigoxela! I've merged https://github.com/backdrop/backdrop/pull/3373 into 1.x and 1.17.x.
