### ISSUE TITLE
[UX] When adding a new Text (short) field, the textfield widget should be the default

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4717]
**Description of the bug**

When adding a new `Text (short)` field, the `Text area (multiple rows)` widget is selected by default

Ninety-nine % of the time, this is the wrong answer. `Text (short)` fields should use the `Text field` widget. I believe this default was set when we changed all text fields to use all text widgets, but seems to have been broken in a recent release.

Experiments reveal:
* When changing the `Field type` from `Text (short)` to `Text (long)` the widget correctly switches to `Text area (multiple rows)`.
* When changing the `Field type` from `Text (long)` to `Text (short)` the widget **does not switch** back to ``Text field``.
* When the `Field type` is `Text (long)` with the field widget set to `Text field`, and you change the Field Type back to `Text (short)` -- the widget **incorrectly switches** back to `Text area (multiple rows)`.

It might not be the default value that's broken, but the value that is always used?

**Steps To Reproduce**

To reproduce the behavior:
1. Go to any entity's "Manage fields" tab
2. Add a `Text (short)` field
3. Look in the `Widget` column and see what option was selected by default.

**Actual behavior**

Text area (multiple rows)` widget

<img width="1070" alt="Screen Shot 2020-10-23 at 5 01 03 PM" src="https://user-images.githubusercontent.com/397895/97062767-39221000-1551-11eb-9399-8f451fb3cded.png">

**Expected behavior**

`Text field` widget

<img width="1046" alt="Screen Shot 2020-10-23 at 5 04 08 PM" src="https://user-images.githubusercontent.com/397895/97062852-a5047880-1551-11eb-8a80-1a95b175d411.png">

**Additional information**

Add any other information that could help, such as:
- Backdrop CMS version: 1.17.1

**Comment by indigoxela** [comment]
Since #684 all text widgets are allowed for all text fields (pretty odd, but, well...).

Selection of the default widget for a type happens in [field_ui.js](https://github.com/backdrop/backdrop/blob/10167aae01ea19486e532871cfbaf238adebfa14/core/modules/field_ui/js/field_ui.js#L40), or actually does _not_ happen.

That code didn't change in years.

The default_widget is correctly defined in [text.module](https://github.com/backdrop/backdrop/blob/10167aae01ea19486e532871cfbaf238adebfa14/core/modules/field/modules/text/text.module#L18), the sorting in the field UI admin for select list is alphabetical.

The problem is somewhere in js. But `console.log(widgetDefault);` outputs the right value when switching the "Type of data to store." select list. My assumption is that the problem happens in jQuery.fn.fieldUIPopulateOptions.

As this is a js problem, I'm out. :wink:

**Comment by herbdool** [comment]
@indigoxela thanks for the hints on this one.

I've got a PR https://github.com/backdrop/backdrop/pull/3840

It was assuming that `selected` was undefined but it never is. It is `NULL`.

**Comment by jenlampton** [comment]
I can confirm the PR works for me. Thank you so much @herbdool  this tiny bug has been a thorn in my site since we introduced the flexibility for text widgets. 🥰

**Comment by jenlampton** [comment]
Code change also look straightforward.

**Comment by quicksketch** [comment]
Nice! Merged https://github.com/backdrop/backdrop/pull/3840 into 1.x and 1.20.x. Thanks @herbdool, @indigoxela, @jenlampton, and @klonos!
