### ISSUE TITLE
Token: element_children produces notice on integer keys (php 7.4)

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4754]
This is the respective issue as https://www.drupal.org/project/token/issues/3154183

I do not have steps to reproduce that yet, but we have the same code in https://github.com/backdrop/backdrop/blob/1.x/core/includes/common.inc#L7228

The patch in the d.org issue has been RTBC'ed and seems a simple and straight-forward change.

**Comment by klonos** [comment]
I've tried to reproduce this on a vanilla 1.18.x-dev, with php 7.4.7:

- navigate to `admin/config/development/logging` and enable all errors
- use devel_generate to generate a few taxonomy terms
- navigate to `admin/config/urls/path/patterns`
- set the pattern for all taxonomy terms to `[term:vocabulary]/[term:parents:join-path]/[term:name]`
- navigate to `admin/config/urls/path/bulk-update`
- select all taxonomy terms, and apply the "Update existing URL aliases" action

There were no errors in the UI, nor any logged in the dblog 🤷 

...I've asked our Drupal brethren in the d.org issue to provide simple steps to reproduce this.

**Comment by indigoxela** [comment]
> There were no errors in the UI, nor any logged in the dblog

I didn't dig any deeper, but tried to reproduce it in D7 - no errors, nothing in dblog on php 7.4. It seems that this problem only affects Drupal 8.

**Comment by BWPanda** [comment]
Marking this as a question until we can confirm it's actually a bug in Backdrop.

**Comment by quicksketch** [comment]
I don't think this applies to us because we don't actually have the code segment from the Drupal issue.

> I do not have steps to reproduce that yet, but we have the same code in https://github.com/backdrop/backdrop/blob/1.x/core/includes/common.inc#L7228

That line is for the Backdrop `element_children()` function, but the affected code from Drupal is `token_element_children()`.

In particular, the problem is with `$key[0] !== '#'`, where a string is being treated as an array to get the first character. I couldn't find this bit of code anywhere left in our codebase. We got all of them fixed in previous issues.

**Comment by klonos** [comment]
Happy to close then. Let's reopen if it actually proves to be an issue for Backdrop.
