### ISSUE TITLE
[D8] Enable the "Transliterate prior to creating URL aliases" setting by default for new sites

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4756]
`admin/config/urls/path/patterns/settings`

D8:

![image](https://user-images.githubusercontent.com/2423362/99022314-28baef00-256b-11eb-991b-7b67d3284816.png)

Backdrop:

![image](https://user-images.githubusercontent.com/2423362/99022360-3d978280-256b-11eb-867a-24d7cd76564b.png)

Is there any specific reason why we have it disabled?

**Comment by klonos** [comment]
...while at it, we should add a link to the transliteration settings page.

**Comment by BWPanda** [comment]
Here's a PR: https://github.com/backdrop/backdrop/pull/3400

> we should update the help text to add a link to the transliteration settings page.

I assume you're referring to `/admin/config/media/file-system`, in which case I disagree. That page just has settings for transliterating file names, which have nothing to do with URL aliases...

**Comment by indigoxela** [comment]
> Here's a PR

Hehe, easy to review. :wink: 

@BWPanda Something went wrong with the Tugboat sandbox - it wasn't created.

But seriously: I'd totally appreciate that change, because I tend to forget to turn it on initially. And I always turn it on. To my knowledge transliteration can't do any harm. And IMO it's the 90% use-case to have it turned on.

Backdrop gets installed with the path module enabled. It seems logical to me that transliteration gets enabled by default, too. One thing less to remember after install.

**Comment by klonos** [comment]
> I assume you're referring to...

Sorry @BWPanda ...I don't remember what I was referring to, but certainly not the file transliteration settings. While I was creating this issue, I have a D8 and a Backdrop site side by side, so chances are that I got confused with the differences between them ...carry on 😅

**Comment by BWPanda** [comment]
For such a simple change I figured it's ok to merge my own PR. Thanks @klonos and @indigoxela! https://github.com/backdrop/backdrop/pull/3400 has been merged into 1.x and 1.17.x.
