### ISSUE TITLE
Try to get more donations by re-thinking the way Backdrop gathers them

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#4767]
There has been a longer discussion in our Zulip chat regarding how we could improve the way Backdrop collects donations: https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/monetizing.20Backdrop

Currently the Donate button is [hidden away on a subpage](https://backdropcms.org/contribute). Suggestions have been made to add a "Pay what you want" button (including 0$ option) next to the download link.

**Please note**

Actually the discussion started as another "monetizing" thing, but that has been objected.

But then, inspired by the [elemtaryOS approach](https://www.forbes.com/sites/jasonevangelho/2019/09/03/paying-for-linux-distros-and-foss-software-successful-elementary-os/) which seems to be successful, the direction of the discussion changed.

That's why we didn't re-open existing issues (#2419, #3757), but started a fresh one.

**The focus here is different**

We're trying to evaluate a different design/wording for our donation button and where to put it so it gets more attention.

**TODO**

Could this - in any way - contradict the Software Freedom Conservancy requirements.

**Comment by philsward** [comment]
In addition to making this prominent for core, I would like to explore the options on making this available to individual contribs as well.

If you are going to respond with a "hard no", all we ask is that you explain your position so we can have transparency on your decision.

Some things to think about: what are the pros? What are the cons? How will it affect the community one way or the other? What will Backdrop look like in 5 or 10 years going one direction or the other?

I really like the idea of donations/tips with a "pay what you want" style CTA.

**Comment by philsward** [comment]
Spitball idea: donations are held by Backdrop. Maintainer must login to send payment to themselves (like PayPal loose example)

Present three options for payout:
1) Pay Me Now
2) Pay what you want to help out Backdrop
3) Pay what you want to help out a fellow maintainer.

It would be kind of cool to see a list of the top 5 or 10 core maintainers for the month and quickly be able to send them tips of no specific maintainer comes to mind.

**Comment by indigoxela** [comment]
> Spitball idea

Sure. :laughing: 

> Pay what you want to help out a fellow maintainer

The reason I actually jumped into that discussion (and opened this issue) was not because I think that *some* single maintainers or contributors should get payed. I suspect this could cause frustration and might be considered unfair to the others. I don't want to get payed either, BTW, I voluntarily contribute like all the others, one among equal.

What I'm actually after is to figure out, if we can be more successful in collecting money for our infrastructure (testing system, tools... as examples). That's where I see the demand.

**Comment by BWPanda** [comment]
For those not familiar, here's how Elementary OS's "Pay what you want" system works:

![Peek 2020-11-20 22-34](https://user-images.githubusercontent.com/2385329/99795911-b062b800-2b80-11eb-9b2d-555f48a1363c.gif)

I personally wouldn't recommend copying this exactly for Backdrop, since their system tends to be an 'opt-out' payment system (i.e. you pay to download it unless you specifically enter $0). I'd prefer to use an 'opt-in' donation/tip system for Backdrop.

Also, this payment system that Elementary uses for downloading their OS is the same that they also use in their AppCenter:

![Elementary AppCenter](https://miro.medium.com/max/3912/1*3YBvnkvrB9rGm9RE5kp5eQ.png)

**Comment by klonos** [comment]
Shouldn't this discussion be in https://github.com/backdrop-ops/backdropcms.org/issues instead?

**Comment by indigoxela** [comment]
> Shouldn't this discussion be in https://github.com/backdrop-ops/backdropcms.org/issues instead?

I'm not sure. IMO the discussion goes (or should/could go) beyond backdropcms.org. But then again, several issues over there seem do.
I don't think it's possible to move existing comments, though.

**Comment by klonos** [comment]
> I don't think it's possible to move existing comments, though.

Yup 😓 ...that's why I asked @indigoxela ...we'd need to close, and you'd all need to copy-paste your comments over there 🤷

**Comment by oadaeh** [comment]
I think the reason why that has worked so well for elementary OS is because the way the form is constructed and worded. The "Pay What You Want:" text and the "Purchase elementary OS" button imply something _must_ be paid.
Then if you click on "Custom," a description shows up that simply says "Enter any dollar amount." Most people do not naturally assume that $0 is a viable choice.
There is a difference in people's mindsets when they read those things. They are using carefully crafted psychology/marketing text to achieve their results.

**Comment by philsward** [comment]
> I don't want to get payed either, BTW, I voluntarily contribute like all the others, one among equals.

To combat this, a checkbox could be added to each maintainers payout dashboard:

[ x ] Automatically send all of my proceeds to the Backdrop foundation.

Originally, I thought about allowing each maintainer to opt out of receiving anything, but that isn't fair to the community if they want to support the project or maintainer.

**Comment by BWPanda** [comment]
I feel a good idea would be to first work out a better solution for core. Then contrib can come later after a separate discussion about that.

I say this because I feel like a lot of people who would support better donations for core would oppose the same for contributed. So maybe better to focus on core first and then see how that goes...?

**Comment by indigoxela** [comment]
> I think the reason why that has worked so well for elementary OS is because the way the form is constructed and worded. ... They are using carefully crafted psychology/marketing text to achieve their results.

Yes, exactly. And I think Backdrop shouldn't go that far.

However, I still see a lot of potential to gain more without using (sort of) dirty tricks like that.

1. Place the donation button near to the download link
2. Reword it (but in a decent way)
3. Provide a short text explaining *why* Backdrop needs money (infrastructure...)

> I feel a good idea would be to first work out a better solution for core.

I agree, why blocking something we obviously can find consensus on, with something we can't.

**Comment by indigoxela** [comment]
[Cunningham's Law](https://github.com/lukasz-madon/awesome-concepts#cunninghams-law) applied... :grin: A draft for wording: 

Backdrop CMS is free (like free speech and free beer). However, the infrastructure it needs for [a list of things that require payment] is not.
Show your appreciation by donating [or another word here] an amount of your choice and help us to keep up our good work.

Two buttons:

- Donate
- I'm a tightwad (= download)

**Comment by philsward** [comment]
Focusing on Backdrop first is fine with me.

However, I don't think everyone is looking at the full picture when it comes to contribs. 

It's not about the money. It's about giving people, organizations and businesses a tool to support the community.

I won't go into lengthy detail, but let's look at the community and contribs this way:

By not monetizing contribs, it creates a lopsided community. Not everyone can give their time, or knowledge, or feedback but this is the overwhelming expectation in order to "give back".

It alienates 1/3 of the community (actually, a lot more) because the one thing they can and want to give back, they can't because they aren't allowed.

As a result, those people never really engage with the community because they have nothing to contribute. A lot of them don't want to leech from the community, but what choice do they have?

Good people want to give. It's taught in religions, it's taught in various cultures, it's taught in good homes. What that giving looks like, should not be one sided or dictated by the community but rather encouraged as a whole part of the community.

My motivation on this has nothing to do with making money believe it or not. My motivation is for creating a healthy community where the vast majority who can't or wont give back directly, can by financially supporting those who are directly involved.

All I ask is that we don't rob someone of their opportunity to "give".

**Comment by philsward** [comment]
Here's the problem with the word "donate": it implies giving to a charitable cause. "We're begging for money".

I guarantee this is why the conversion for elementary OS became so much higher when they moved to the "Pay what you want" CTA. It's not misleading, it's not evil, it's not underhanded. It's simply presenting the option of payment in a way that isn't demanding or makes people feel like they're giving handouts, but rather puts the power in the hands of the user. "I choose to pay this!". As opposed to "I feel obligated to give this...". If anything, donate is the "evil" CTA because it's implying "you should feel bad about yourself because you didn't give to a worthy cause that is obviously desperate for money".

> [Cunningham's Law](https://github.com/lukasz-madon/awesome-concepts#cunninghams-law) applied... :grin: A draft for wording: 
> 
> Backdrop CMS is free (like free speech and free beer). However, the infrastructure it needs for [a list of things that require payment] is not.
> Show your appreciation by donating [or another word here] an amount of your choice and help us to keep up our good work.
> 
> Two buttons:
> 
> - Donate
> - I'm a tightwad (= download)
>

**Comment by olafgrabienski** [comment]
The "Pay / Give what you want" approach is interesting! In my opinion it's *not* okay when the "Pay / Give nothing" option is hidden. Not wanting to pay anything, for whatever reason, should always be a clear and *welcoming* option. I think, we don't want to loose a single person who doesn't try Backdrop because she or he has the impression it's not free to use.

(Speaking more generally, I'd say Backdrop needs people more than money, even if getting more money is a good thing.)

I'm also not sure about verbs like "to pay" or "to purchase" in this context. Be aware that purchasing something might chang expectations. I see the point agains "Donate", not sure if I agree, though. Just in case, are there other alternatives to "donate" apart from "pay" and "give"?

**Comment by findlabnet** [comment]
In addition, any “purchase” involves some kind of guarantee.

**Comment by indigoxela** [comment]
> In my opinion it's not okay when the "Pay / Give nothing" option is hidden.

I agree, that's what I also find problematic with the elemtaryOS approach.

> are there other alternatives to "donate" apart from "pay" and "give"?

Possibly contribute, support, sponsor. But that's rather a job for the native speakers. :wink: 

> “purchase” involves some kind of guarantee.

I agree, purchase isn't the right word in this context.

**Comment by docwilmot** [comment]
I think I would like to see a variation of Elementary OS' buttons but with an additional $0 or "free" button and a clear explanation that this is a donation. So:

```
**Backdrop CMS is free (like free speech and free beer). However, the infrastructure it needs is not [where your donations go link].
Show your appreciation by donating an amount of your choice and help us to keep up our good work. Or download for free if you would rather contribute later**

**Pay what you want**

[Free] [$1]  [$5]  [$10]

**[Download button]**
```

I don't have any hangups on the would "Pay" if the SFC say its OK. If its likely to increase contributions and it doesn't change our stance as a registered charity, then its just a word we can change any time.

I say we go for this.

**Comment by domaingood** [comment]
I don't want to use  "to pay" or "to purchase"  Purchase elementary OS i was confuse to when I trying to test drive elementary OS.
My Opinion

**Donate what you want**

[Free] [$1]  [$5]  [$10] [custom]

**[Download button]**

> 'm also not sure about verbs like "to pay" or "to purchase" in this context. Be aware that purchasing something might change expectations. I see the point agains "Donate", not sure if I agree, though. Just in case, are there other alternatives to "donate" apart from "pay" and "give"?

**Comment by jlfranklin** [comment]
The language on the [Contribute](https://backdropcms.org/contribute) page has already be scrutinized, right?  Why are we debating "pay" vs "donate" vs "give"?

Putting any kind of payment option right on the download page is treading close to an anti-pattern, IMHO.  Libreoffice does it best, and even there I don't like it.

How about an animated CTA linking to the Contribute page that draws some attention after the download has started?  In my head I'm envisioning static text "Want to give back?", and below that a vertical carousel cycling though all the headers from the Contribute page (donate, shop, code, design, ...), clicking on it takes you to the Contribute page or (optionally) to the specific section.

**Comment by philsward** [comment]
> "Want to give back?"

"Give back what you want:"

I couldn't think of anything better when I posted about the donate word, and I couldn't figure out what was so... Empowering about "Pay what you want", but after some sleep and reading through comments, I think it's the **what you want** that gives the feeling of choice instead of obligation.

**Comment by philsward** [comment]
Does anyone have any hard data on how well the current verbiage is working?

> Why are we debating "pay" vs "donate" vs "give"?

To maximize conversions

**Comment by indigoxela** [comment]
> The language on the Contribute page has already be scrutinized, right?

It doesn't seem to work very well. That's what we're trying to improve.
Currently it is necessary to *actively* search for the donate button, as it's sort of hidden on a subpage. And IMO the text above that button could get improved, too.

> Libreoffice does it best, and even there I don't like it.

Which page/pattern are you referring to?

> How about an animated CTA linking to the Contribute page...

That might be an option. Mind to provide a mockup?

**Comment by oadaeh** [comment]
>> are there other alternatives to "donate" apart from "pay" and "give"?

> Possibly contribute, support, sponsor. But that's rather a job for the native speakers. wink

While I have never felt like some project asking for donations was begging, I can see how others could get that impression.
To me, "support" implies a level of coming together with others to help boost/build something, without sounding like begging, i.e., being a part of it, rather than being some outside party.
"Sponsor" has the added connotation of control or oversight, which I don't think is desired.
Contribute is the title of the https://backdropcms.org/contribute page, so I think it would not be a good idea to use the same word in both places.

**Comment by jenlampton** [comment]
> Suggestions have been made to add a "Pay what you want" button (including 0$ option) next to the download link.

I think having a `Contribute` button more prominent is a great idea!  (I'm using this language only because it seems that most people are in favor of it...)

> Could this - in any way - contradict the Software Freedom Conservancy requirements.

I know "Donate" is okay -- I can ask specifically about "Contribute". I don't think "Pay" is allowed.

> In addition to making this prominent for core, I would like to explore the options on making this available to individual contribs as well.

My only concern is that this placement might be misleading. Would the person donating expect their donation to go directly to the maintainer(s) of that project, and be upset when the money is sent to the Backdrop project instead?

> Spitball idea: donations are held by Backdrop. Maintainer must login to send payment to themselves (like PayPal loose example)

Oh. I don't think we want to get into the business of being a bank. I would prefer that Backdrop avoid "taking a cut" of a transaction between two other parties. If people want to donate directly to someone else, maybe we can find another way to facilitate that, but I don't think we need to be in the middle.

> What I'm actually after is to figure out, if we can be more successful in collecting money for our infrastructure (testing system, tools... as examples). That's where I see the demand.

I agree that this is where we should focus our efforts first. If this proves wildly succesfull we can look at expanding into other areas.

> By not monetizing contribs, it creates a lopsided community...

@philsward can you elaborate more about why contrib-specific donations matter? Your post was mainly about providing people with an opportunity to donate, but we would be doing that already with a more obvious "Contribute to backdrop" process -- even without contrib-specific donations.

I can see how building a platform for our maintainers to make money could seem like its doing them a favor, but that's not part of Backdrop's mission. There are other platforms that already do this well. Services like [GitHub Sponsors](https://github.com/sponsors), [GratiPay](https://gratipay.com), and [Patreon](https://www.patreon.com), and I'd prefer to spend our energy on what we do best -- building a CMS.

One thing I would like to mention is that we are currently trying to support a "Bounty" program for developers -- where one person has $x dollars to spend on a feature, and can hire another person who is willing to do it for that amount. The bounty option is included in the contrib queue, when someone opens [a port request issue](https://github.com/backdrop-ops/contrib/issues/new?assignees=&labels=Port+request&template=port-request.md&title=Port+request+for+...). Here is an example of how are encouraging money changing hands between members of our community, but we don't need to handle the transactions.

> Shouldn't this discussion be in https://github.com/backdrop-ops/backdropcms.org/issues instead?

yes, it should because we are mainly talking about a change to the home page. But here's a related idea that belongs in this queue: 

This was an idea we had very early on (But I can't find the original issue for it).. was to build a "Recommended donation" amount directly into the modules/themes/layouts page. I was thinking it could be something like $20 for core + $5 for each contrib project. This would be something that developers could *easily* add onto their invoices to clients, and immediately funnel back into the community. It would also provide us the option of putting a "Contribute" button directly inside Backdrop itself! (We would probably also need an "I already contributed" checkbox that would disable the display of the message -- but these are details we could easily sort out)

**Comment by philsward** [comment]
>@philsward can you elaborate more about why contrib-specific donations matter? Your post was mainly about providing people with an opportunity to donate, but we would be doing that already with a more obvious "Contribute to backdrop" process -- even without contrib-specific donations.

To put it quickly, I use a lot of different modules. Sometimes, I need things done on a specific module, or I would like the opportunity to support the maintainer of a particular module. Some modules are very large and complex. Other modules directly influence the inflow of money for a business or organization and without solid versions of those modules, the business could loose money. In my opinion, allowing people to directly fund the contrib space is far more important than funding core. By funding the contrib space, it would inherently result in more direct help on core.

>Oh. I don't think we want to get into the business of being a bank. I would prefer that Backdrop avoid "taking a cut" of a transaction between two other parties. If people want to donate directly to someone else, maybe we can find another way to facilitate that (see note about Bounties below), but I don't think we need to be in the middle.

So I'm honestly on the fence about this overall... I see both sides of the isle.

I would love for us to at least explore the option of Backdrop being the bank but before we have this discussion, we would want to set the ground-rules of what the foundation can and can't do as the bank.

**Comment by jenlampton** [comment]
Should I ask the SFC where they stand on those kinds of transactions?  I
don't think it's something they've addressed with any of their other member
projects, but might be worth asking.

Jen

**Comment by philsward** [comment]
Ping @jenlampton 

FOSS vs FLOSS

https://www.gnu.org/philosophy/floss-and-foss.en.html

SFC falls under the FLOSS ideology

https://sfconservancy.org/

From what I can tell in 5 min of googling, these discussions will be perfectly fine under the SFC guidelines.

It wouldn't hurt to ask though.

**Comment by jenlampton** [comment]
What we're talking about *now** has nothing to do with Backdrop the softeare (which, yes, is FLOSS). What we're talking about is being a bank. And since SFC handles the money - they might have opinions about how much liability they want to undertake.

**Comment by philsward** [comment]
@jenlampton Ok. I am unaware of SFC's role in the financial side of Backdrop then.

I see the bank role as being more of a facilitator of transactions, not the place where the money is stored. I realize this is a bit of a gray statement though.

If there is a 3rd party service that can handle the physical transaction between the two parties, store it, and Backdrop simply ties into this by making it widely available then this is the direction I would suggest we explore first. I just want to make sure there is flexibility and we don't pigeon-hole ourselves into donations for example, because donations are the only thing that 3rd party service offers.

**Comment by klonos** [comment]
> I am unaware of SFC's role in the financial side of Backdrop then.

This is a list of all services the SFC offers to all its members: https://sfconservancy.org/projects/services

**Comment by philsward** [comment]
@klonos thanks for that share. From what I can tell, they offer a lot of flexibility to their members. It appears to me (on the surface) that they are there to facilitate how a project operates but not necessarily dictate how things are done.

It also sounds to me like they may have some people on staff or at least know experienced folks to get us in touch with. Very cool stuff.

**Comment by klonos** [comment]
Can we please move this discussion out of the core issue queue now that we have https://github.com/backdrop-ops/backdrop-community?

**Comment by indigoxela** [comment]
> Can we please move this discussion

Sure, is it (technically) possible to move an issue thread to another repo? Or do we have to copy/paste?

**Comment by indigoxela** [comment]
@klonos no, that's for sure foo much effort, I copied the Issue description over. :smile:

I'm not sure, what comments other people want to transfer over to the other repo.

**Comment by indigoxela** [comment]
I think, this has a more appropriate place in backdrop-ops/backdrop-community#3 closing here in favor of the other queue.
