### ISSUE TITLE
Should be able to choose menu item language when editing a node

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#4769]
On a multilinguage site the language of a menu item can be set here `/admin/structure/menu/item/*/edit`. But when going to `node/*/edit` the menu item language isn't an option. Instead it would be useful to show the option there. Like this:

![Screenshot from 2020-11-23 11-23-52](https://user-images.githubusercontent.com/1071483/99987402-69daac80-2d7e-11eb-8b59-67770c9406a0.png)

Note, the menu item language can be set even if node translation isn't enabled. If both are enabled it's possible that the two languages could be different, but that's no different than what's possible now. At least if we show the menu item language on the node edit form then they'd be able to see if they should be set the same. Any other improvements should be a new issue. Another thing which should be a new issue is which parent menu item is displayed. Even in the main menu editing interface the user needs to switch interface languages to be able to see the parent menu items as options in that language.

UPDATE: turns out that by default the menu link language is set to be the same as the node language when saved. But when editing the full menu list this can be changed. But if someone edits the node it'll revert back to the node language. Maybe that's not an issue, not sure, but it should be clearer

**Comment by herbdool** [comment]
@indigoxela you may be interested in reviewing. It's a simple PR.

**Comment by herbdool** [comment]
Oops, I haven't got the saving from the node edit form working yet.

**Comment by herbdool** [comment]
I think it's working now. If this is too much I thought another alternative is to just display the menu language on the node edit but only allow it to be edited on the other admin UI.

**Comment by indigoxela** [comment]
@herbdool it seems, your PR introduced a regression. At least, there are exceptions in the Menu module tests.

**Comment by herbdool** [comment]
@indigoxela thanks, should work better now.

**Comment by klonos** [comment]
Thanks for working on this @herbdool 🙏 ...this request makes total sense 👍 

I've tested the PR sandbox, and have the following comments:

1. Since we have two language selectors in the node edit form, I would like us to be specific about them, and have their labels be "Content language" and "Menu item language".
2. I find it odd UX to have the node language be "None", while the menu language is "All". I would prefer those to be the same, and for us to find better, self-explanatory if possible words. Perhaps something like "Unspecified" or "Language-neutral"? Or be descriptive and have both menu options be "Always shown" or "Shown on all languages".
3. I was thinking that we could make the "Follow content language" checkbox be another option in the dropdown select instead (less form elements -> less busy form -> less confusion -> better UX).
4. If we do keep the checkbox, I like how the select menu is locked/disabled 👍 ...but can we try to see if `#states` allows also setting the value to whichever language is set for the content (while the select remains in disabled mode)? The UX reasoning here is that the content language selector field may be placed higher on the form (after the node title field for example). In such cases, the user will need to scroll back up to see the language selected. We could avoid all that up/down scrolling by having the locked menu item language selector show the content language selected (again, less scrolling -> better UX).

**Comment by indigoxela** [comment]
While working on #4857, which tries to fix the inconsistency for menu item language vs. available parents, I also thought about the node form, which has the same problem (available parents are set via `$language` (the current language), the node's language isn't considered - which is wrong IMO.

I'm not sure yet, if a second language selector on the same form is really the best option. Another potential problem I see is, that the node language select list and the menu item vertical tab aren't next to each other. And the latter isn't visible by default.
So changing the node language while the menu item should be synced can lead to situations, where the existing menu item parent isn't available for the switched language. This might lead to even more inconsistencies.

**Comment by herbdool** [comment]
This is starting to get too complicated. Perhaps we should just stick with the current behaviour where the node langcode is used whenever the node is saved.

**Comment by indigoxela** [comment]
> This is starting to get too complicated.

Hey, you opened that can of worms ... :laughing: 

> Perhaps we should just stick with the current behaviour where the node langcode is used ...

That's actually what I would have suggested. Two language dropdowns just seem too much. And who would want to set an node's menu item language to something different than the node language (in the node form!) - that's at most an edge case.

What we really should fix, is the parent options select list, which currently only shows items in the interface language or neutral ones. I consider that a bug, it should respect the node language instead. But maybe we can cover that in the [other issue](https://github.com/backdrop/backdrop-issues/issues/4857)? It's a bit more complex in the node form, though, regarding UX.

**Comment by herbdool** [comment]
I'm going to close this issue.
