### ISSUE TITLE
Check if empty database table exists before throw exception

### ISSUE THREAD

**Issue by findlabnet** [backdrop/backdrop-issues#4771]
**Description of the bug**

When checked an issue https://github.com/backdrop-contrib/ip_blocking/issues/5 I've found 9 years long discussion of same problem on d.org: https://www.drupal.org/project/drupal/issues/1551132 and working solution for D7: https://www.drupal.org/files/issues/2020-07-02/1551132-113.patch

**Steps To Reproduce**

To reproduce the behavior:
1. Database from any D7 site (in migration process) already have empty table named `blocked_ips`.
2. When install/update module [IP address blocking](https://backdropcms.org/project/ip_blocking) update hooks throw exeption: 
`DatabaseSchemaObjectExistsException: Table blocked_ips already exists. in DatabaseSchema->createTable() (line 661 of /app/core/includes/database/schema.inc)`

**Actual behavior**

The fatal error interrupts the update hooks. And the schema version ends up staying at -1 in the system table so it can't run the updates at all.

**Expected behavior**

Check if empty database table exists and delete it before re-creating.

**Comment by findlabnet** [comment]
[PR](https://github.com/backdrop/backdrop/pull/3411) added.

**Comment by indigoxela** [comment]
@findlabnet many thanks for providing a PR. I didn't test, but it should fix the problem. ... If the table is empty. If the table isn't empty, the problem persists.

Drupal 7 adds the table blocked_ips by default. That's why it's there when upgrading from D7. But that whole thing has been removed from core and went to contrib. The db table isn't removed, though. That's where I see the problem.

Shouldn't there be an update hook, that removes the (unused) table when upgrading from D7?
Is there an existing update hook as an example? Can't seem to find one.

For housekeeping reasons it would be better to take care of orphaned db tables from D7. No matter if a contrib module exists or not. Why keeping stuff that's not in use anymore?

**Comment by findlabnet** [comment]
I have tried to solve a specific problem related to the module I maintain.
This is a reasonable check for an empty table because the new table structure has been extended by a module.

When I introduced this module in 2016, I made the mistake of using the same name for the table as in D7.
Maybe I need to fix this now via an update for this module (and for my new add-on module) to rename the table?

In any case, this does not solve the problem of orphaned tables inherited from D7 or some not very carefully constructed modules.

>Is there an existing update hook as an example? Can't seem to find one.

Same here. This is just cite from [issue](https://github.com/backdrop-contrib/ip_blocking/issues/5#issuecomment-722512749).
Suggestions?

**Comment by herbdool** [comment]
@indigoxela I can see the benefit of leaving the table since there might be data they want to keep. Though I could go either way.

@findlabnet I think this PR works well enough. If the table isn't empty someone would need to intervene. Or perhaps the contrib module could try to rename the old table as the first step - if it can be run before the schema is called.

**Comment by indigoxela** [comment]
One thought: can we somehow limit that table dropping to table names, of which we know that they ship with D7? Dropping tables - even if empty - worries me a bit.

We'd need a list of modules that have been removed from core and ship with db tables (like ip_blocking).

**Comment by findlabnet** [comment]
Module-specific [issue](https://github.com/backdrop-contrib/ip_blocking/issues/5) resolved in new [release](https://github.com/backdrop-contrib/ip_blocking/releases/tag/1.x-1.0.6).
If old table exists when this module install, it will be renamed to `blocked_ips_d7`, then on status report page user can see info about it.

So, if we do not know about other similar incidents, this issue can be safely closed and the PR removed.

**Comment by indigoxela** [comment]
> Module-specific issue resolved in new release.

Great! Glad that you found an elegant solution.

> So, if we do not know about other similar incidents, this issue can be safely closed

I'm not sure, you might have found something that could cause more trouble in future.

**Comment by findlabnet** [comment]
> something that could cause more trouble in future.

Maybe it's better to deal with problems as they arise?

**Comment by indigoxela** [comment]
> Maybe it's better to deal with problems as they arise?

I like your pragmatic attitude. :wink: @findlabnet Feel free to close this issue, as you opened it.

**Comment by findlabnet** [comment]
The current issue is resolved at the contrib module level, so I am closing this issue. 
Thanks to all involved!
