### ISSUE TITLE
Update the views grid style to be responsive

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#479]
Currently, views grids use a HTML table that is hard to make responsive.  The grid element markup should be rewritten to use DIV tags so that it can be more easily rearranged on smaller screen devices.

Take a look at the [views responsive grid module](https://www.drupal.org/project/views_responsive_grid) for some ideas about new markup.

---
PR by @docwilmot: https://github.com/backdrop/backdrop/pull/1784

**Comment by docwilmot** [comment]
This is not ready. It is a port of the Views Responsive Grid module which changes Backdrop's grid table to divs. 
But D8 used slightly different code to generate grids. This is a start, to discuss possible way forward. Will list D8 differences shortly.

**Comment by jenlampton** [comment]
I don't think we need to match the D8 markup exactly. I've been manually overriding all my views-view-table templates in my backdrop sites to get around this problem, and would welcome advice on a path forward :)

**Comment by klonos** [comment]
Should we set this for 1.6.0? Is it a feature request (adding a new "responsive grid" view format would make it so) or is it a bug fix (the current grid format is not responsive)?

**Comment by jenlampton** [comment]
It's a bug.

- -
Please excuse brevity and typos. Message typed with my thumbs from an Open
Source OS.

**Comment by klonos** [comment]
I was hopping that somebody would say that 😄

**Comment by docwilmot** [comment]
Sadly still not ready. Will try and relook.

**Comment by docwilmot** [comment]
This PR provides Views grid plugins with DIVs rather than tables, but it does not include any CSS. I'm not sure how we should do this. Core provides Bootstrap so should this be involved? And should Seven provide the CSS, or Views?

**Comment by docwilmot** [comment]
![grid](https://cloud.githubusercontent.com/assets/1042283/22652222/aaedc60a-ec53-11e6-9054-e83ea640c1f4.PNG)

**Comment by docwilmot** [comment]
One more query for feedback too: Is there likely to be any situation where a person might actually *want* to keep table-based grids? Should we be offering both?

**Comment by jenlampton** [comment]
I think if people want tables they'll use the table style. If they want a grid, we shouldn't be using a table for that.

**Comment by docwilmot** [comment]
> I think if people want tables they'll use the table style

Not  to belabor a point but table-based grids are a totally different thing from the Views table style. 

I was asking if there is any situation, in your expertise, where a table-based grid might be preferred over a DIV-based grid. In to fact be clear  I'm now officially agreeing we shouldnt bother to consider both for this PR. But now I'm curious. Any thought? Do table have any advantage?

**Comment by jenlampton** [comment]
IMHO, no. If you want a table, you use the table. If you want a grid, you want divs.

**Comment by docwilmot** [comment]
I added an option to have column widths set. There were two options for the CSS:
- flexbox (in use now in the sandbox); only issue is if the last row has fewer items than the previous rows, the columns in the last row exapnd to fill the whole width. This could be fixed with a max-width.
- width %; this avoids above but then item heights will be variable. Flexbox ensures that every item in every row stretches to the same height as the tallest item.

Weigh in on your opinion of these options please!
Note the PR is yet incomplete as I havent incorporated @klonos suggestions, nor have I dealt with vertical rows yet.

**Comment by docwilmot** [comment]
Flexbox: note the last row has only two items instead of four. These last two stretch to take up 50% space each. If we used `width: 25%` instead, this wouldnt happen

![flex](https://cloud.githubusercontent.com/assets/1042283/24583120/13f9cebe-1706-11e7-9abb-5eafc3af6639.PNG)

**Comment by quicksketch** [comment]
I did a review of the PR. Some issues:

- Unchecking "Remove default views classes" totally breaks the grid functionality. This option should either be removed or come with a stern warning, because it's not a grid without it checked.
- Do we need all these class options?
![image](https://cloud.githubusercontent.com/assets/100206/25552755/c6ced1fa-2c56-11e7-94cc-27ae26d814e5.png)
If we keep them, I'd like if we could at least collapse them all into a single fieldset.
- I unchecked 'Automatic width" and get a fatal error on viewing.
- Watchdog logs a PHP error `'views_element_validate_integer' not found or invalid function name in _form_validate() (line 1482 of /home/qa/github/backdrop/backdrop/pr/1784/core/includes/form.inc).`

There's also some comments on the PR. Of note, @docwilmot had asked whether inline CSS was acceptable for specifying the flexbox percentages. IMO I think this is acceptable.

> Inline styles seem reasonable here. It specifies the number of columns in the same way that tables would (but with the benefit of being responsive). Plus we avoid the dependency on loading Bootstrap (for themes/layouts that aren't using it).

**Comment by jenlampton** [comment]
Descoping from 1.7 since we are 4 days from release.

**Comment by jenlampton** [comment]
I'm looking at the PR again and wondering why we are adding new classes and CSS to handle the grid display when we have Bootstrap 4 gridsystem in core. It's even already packaged up as a nice separate library and could be included only when the views grid style was selected.

I'm thinking about this because it will be confusing for people who are using the Bootstrap grid everywhere else on their site (because, layouts), to not see the familiar bootstrap grid classes on a views grid, too. 

I have a vague memory of discussing using boostrap for this issue once, but I can't remember what the down sides were. I might clean up the current PR and then give it a stab and see if I run into any of them right away...

**Comment by jenlampton** [comment]
Hey, crazy idea. Most modern browsers now support `grid`: https://css-tricks.com/snippets/css/complete-guide-grid/

* If we were to switch our HTML tables to DIVs using the `grid` property the existing sites would function the same way they do now - causing no break in functionality.
* We would also solve the bug of themes not being able to make grids responsive, since they would now be able to override the `grid` column widths for whatever breakpoints they choose. 
* We'd also avoid adding any overwhelming new UIs by needing to ask people to specify breakpoints and # of columns in those breakpoints. 
* We'd also avoid any confusion with bootstrap vs not-bootstrap grids appearing in people's markup.
* This also a clean enough change that we might be able to get something in by 1.8

win-win-win-win-win?

**Comment by olafgrabienski** [comment]
The grid idea is promising but maybe it's too late for 1.8. Actually the last two approaches (Bootstrap 4 and Grid) sound both good to me. Are others fine with them, or only the one or the other, e.g. @docwilmot ?

**Comment by jenlampton** [comment]
@olafgrabienski Ive opened https://github.com/backdrop/backdrop-issues/issues/2811 to be a clearer explanation of a plan we can execute for 1.8.  I'd like to leave this one as `Update the views grid style to be responsive` since there's some good code here that could still be used to that end. (I think the two requests are separate.)

**Comment by docwilmot** [comment]
We fixed this in https://github.com/backdrop/backdrop/commit/2838ad37fd7b06fa6105098f7ec076bfbd750c73
