### ISSUE TITLE
Prevent undefined index 'settings' in theme_has_color_support()

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#4842]
**Description of the bug**

The error `Undefined index: settings in theme_has_color_support()` is displayed for default themes without any settings.

**Steps To Reproduce**

To reproduce the behavior:
1. Find a theme that doesn't have any settings (colour or otherwise) - e.g. Seven
2. Make it the default theme for the site
3. Go to the Dashboard

**Actual behavior**

`Undefined index: settings in theme_has_color_support()` error displayed.

![image](https://user-images.githubusercontent.com/2385329/103387753-9346df00-4b59-11eb-8d6c-257809391d89.png)

**Expected behavior**

No error displayed.

**Comment by BWPanda** [comment]
Simple fix: https://github.com/backdrop/backdrop/pull/3464

**Comment by indigoxela** [comment]
I think, there's a related issue: https://github.com/backdrop/backdrop-issues/issues/4463

**Comment by indigoxela** [comment]
> Simple fix: backdrop/backdrop#3464

@BWPanda Didn't test this yet, but are you sure this works as expected for subthemes of themes with color support?

**Comment by indigoxela** [comment]
I verified the Notices with Seven and Purple (contrib theme without any settings).

```
    Notice: Undefined index: settings in theme_has_color_support() (line 1518 of.../core/includes/theme.inc).
    Notice: Trying to access array offset on value of type null in theme_has_color_support() (line 1518 of .../core/includes/theme.inc).
```
And I can confirm that the PR fixes it.

I also installed several other themes (with settings, but some without color support) in the sandbox and verified that there are no side effects. Works for me. :+1:

**Comment by indigoxela** [comment]
The code is looking good, RTBC from my side.

@klonos You might have had one of the several other Color module related issues in mind, when starting a review. For the undefined index notice on the dashboard page when there's _no setting at all_ the `!empty()` check is correct.

This, of course, does not prevent the "Customize the current theme" link to appear in the welcome block, if the only setting of that theme was `settings[color] = false`. Neither does it prevent the settings page creation (e.g. admin/appearance/settings/seven). But I don't think that this issue here tries to cover that. Or does it?

We have separate issues for these (and other) Color module problems, one for [subthemes](https://github.com/backdrop/backdrop-issues/issues/4463), one for the [settings page](https://github.com/backdrop/backdrop-issues/issues/3458), one ongoing meta issue for the [bigger picture](https://github.com/backdrop/backdrop-issues/issues/1905).

**Comment by BWPanda** [comment]
> But I don't think that this issue here tries to cover that. Or does it?

Nope. Didn't actually notice that, but it's a separate issue. This is just about removing the scary error message from the Dashboard.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/3464 into 1.x and 1.17.x. Thanks @BWPanda and @indigoxela!
