### ISSUE TITLE
Fix layout and views menu items get undeletable but stay visible once created

### ISSUE THREAD

**Issue by philsward** [backdrop/backdrop-issues#4844]
### Problem
When creating a menu item through a layout "menu settings" on a single URL path, it creates a "hard coded" link that persists even after removing that link from the menu setting of the layout. This link becomes impossible to remove.

**Reproduce**
1) Navigate to the layout list page: /admin/structure/layouts
2) Edit the "Menu Settings" of a single url layout group (Home is fine, adding and testing other groups produce the same result)
3) Set the "Type" to **Normal Menu Entry**, add a title called TEST and save
4) Visit the menu settings page: /admin/structure/menu/manage/main-menu
5) Notice the new "TEST" menu that can only be edited. There is no option to delete it.
6) Go back to the "Menu Settings" of the layout and change the "Type" back to **No menu entry**
7) Again visit the menu settings page: /admin/structure/menu/manage/main-menu and notice the link is still there with no way to delete it.

**Update:** This also spills over to Views. If a view menu has been created and is later set to "no menu entry", the menu is not removed and there is no way to delete it.

### Archived Description
**Description of the need**

I see this as more of a bug than a feature request, however unless I'm doing something wrong, it appears that the home menu link is referencing /home instead of /

**Proposed solution**

The hard coded menu should always point to the domain root / <front> (unless there are translation?)

**Alternatives that have been considered**

The workaround is to create a new menu entry, use <front> as the path and disable the OOTB hard coded Home menu item.

**Additional information**

![image](https://user-images.githubusercontent.com/3436110/103396503-5a771d80-4af9-11eb-955a-884aaa6d78d3.png)
![image](https://user-images.githubusercontent.com/3436110/103396523-6bc02a00-4af9-11eb-9990-f281ab388fc7.png)

Workaround
![image](https://user-images.githubusercontent.com/3436110/103396560-9316f700-4af9-11eb-9039-79893e93074e.png)

**Comment by klonos** [comment]
I just tested on a couple of test sandboxes (one from a recent PR and another Tugboat demo sandbox from b.org), and it seems that the "Home" menu item is not "hard-coded"; it is instead set to `<front>`, which AFAIK will always point to whichever is set to be the home page:

![image](https://user-images.githubusercontent.com/2423362/103399110-31ca4480-4b48-11eb-90bf-13054c2880b4.png)

Am I missing something?

**Comment by philsward** [comment]
@klonos not sure. I might have to spin up a sandbox and try to reproduce it.

I did set a menu entry for the home layout, then deleted the "duplicate" home menu item, then disabled the layout menu entry. Not sure where that hard coded home item came from. I was under the impression it was always there.

**Comment by philsward** [comment]
@klonos I've updated the original description with steps to re-produce.

Changing to a bug issue because this is indeed the wrong execution of this workflow.

**Comment by klonos** [comment]
Thanks @philsward 👍 ...I'll try to reproduce this and see if I can figure out the source of the issue.

**Comment by philsward** [comment]
@klonos sounds good. @jenlampton said she ran across it a bit ago but didn't have time to investigate.

Looks like both Views and Layouts will need to be addressed.

**Comment by indigoxela** [comment]
@philsward I suppose, you added the menu link via the layout menu settings.

Go to admin/structure/layouts and edit the "Menu settings" of you home layout - set it back to "No menu entry" and that menu item will be gone. Then you can create on for "<front>" on admin/structure/menu/manage/main-menu. That should fix it.

**Comment by philsward** [comment]
@indigoxela I tried that with the home layout and a custom layout and setting both to no entry did not remove the link.

What you suggested is the correct workflow, but that's not what is happening.

Maybe this has been fixed in head?

**Comment by BWPanda** [comment]
I can confirm this. I created a new layout with path `test` and a menu entry in the main menu. That all works fine. However, after editing the layout menu item to 'No menu entry', clearing caches and running cron, the menu item remains in the main menu.

**Comment by philsward** [comment]
@BWPanda you can also confirm this entry is impossible to remove once it's created?

When you get a chance, can you test the same thing with a view that is a page?

**Comment by BWPanda** [comment]
> can also confirm this entry is impossible to remove once it's created?

Yep. 
![Peek 2021-01-02 20-25](https://user-images.githubusercontent.com/2385329/103454650-44a46b00-4d3a-11eb-8139-a2f976fbb019.gif)

> can you test the same thing with a view that is a page?

Yep, same issue - menu item created when 'Normal menu entry' selected, and it's *not* removed when 'No menu entry' is then selected.

**Comment by indigoxela** [comment]
Fancy, I could also reproduce it today. But it worked properly when I tested it yesterday. :confused: 

The problem seems to be that the config file (example: layout.menu_item.test_layout.json) does not get deleted, only the "type" gets set to "none".

We should properly handle type "none".

@docwilmot is there a good reason why that json file doesn't get removed when setting back to "no menu item"?

**Comment by indigoxela** [comment]
What a mess...

To my understanding this problem arises in [function _menu_navigation_links_rebuild()](https://github.com/backdrop/backdrop/blob/f6317bfd98c67f96a763fa2115ee18f1dd7f3ae1/core/includes/menu.inc#L2967)

After the menu item has been created as "Normal menu item" (can be in layout or views, both are affected), it stays visible until one switches it to "Menu tab" - which hides it properly (sets the value in db table menu_links, column "hidden" to -1).

If setting the item to type "none", it becomes a `MENU_CALLBACK`, but the "hidden" value wont get updated, because of the logic in function _menu_navigation_links_rebuild().

If changing, for instance, the _path_ of the layout, the menu item disappears from table "menu_links". Probably that would be the correct behavior? Deleting if it shouldn't be visible anyway? The path stays in the menu_router table but the menu item in table menu_links should get removed? Who can answer that?

**Comment by indigoxela** [comment]
Ha! Drupal 7 shows the same behavior in views when switching from a normal menu entry back to none. The menu item stays visible. https://www.drupal.org/project/drupal/issues/1029022

And in Backdrop this also affects the Layout module.

**Comment by indigoxela** [comment]
A [PR](https://github.com/backdrop/backdrop/pull/3474) based on the Drupal patch is available for testing and review.

I've tested it with both, layouts and views menu items, and it works as expected.

**Comment by stpaultim** [comment]
I tested the PR in the sandbox using both views and layouts as described above. It works for me.

**Comment by BWPanda** [comment]
Doesn't work for me... I tested the Tugboat PR and if I create a Layout, I no longer see the 'Menu settings' button to configure its menu item...

![image](https://user-images.githubusercontent.com/2385329/103490595-0bbae200-4e71-11eb-8cfe-7df98b23b526.png)

**Comment by klonos** [comment]
When @quicksketch was reviewing https://github.com/backdrop/backdrop-issues/issues/2714#issuecomment-753546534 he mentioned:

> The only particularly weird thing I saw is that the admin bar maintains the links to each update page, even though the tabs are hidden.

I believe that what Nate noticed was in fact the same side-effect as this issue here. The difference is that the steps-to-reproduce here trigger it manually, via the admin UI for layouts/views, whereas my PR triggers it (only for existing sites) because the code changes the menu item from `'type' => MENU_LOCAL_TASK` to `'type' => MENU_CALLBACK` programmatically.


I'll try to reproduce this in the context of #2714, and if I get to be able to reproduce it consistently, then I'll give @indigoxela's PR a go and report back whether it fixes things or not.

**Comment by quicksketch** [comment]
PR code looks good to me. New test coverage and everything :+1:

**Comment by BWPanda** [comment]
Ok, tested the PR patch on my local and the Menu Settings button shows up there. PR fixes the problem.

**Comment by BWPanda** [comment]
Thank you @indigoxela, @philsward, @klonos, @stpaultim & @quicksketch! I've merged https://github.com/backdrop/backdrop/pull/3474 into 1.x and 1.17.x.
