### ISSUE TITLE
Fix case of File Type descriptions

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#4853]
File Type descriptions are inconsistent in their use of case. Some have the file type written in title case, while others use lowercase...

See: admin/structure/file-types

![image](https://user-images.githubusercontent.com/2385329/103476871-75090980-4e0d-11eb-8777-ac60168a0c0c.png)

We should standardise the case for all of these. My personal perference is lowercase.

**Comment by Siddharth1010** [comment]
Hey @BWPanda could you assign me to this and let me know where the issue lies?

**Comment by BWPanda** [comment]
Sure thing @Siddharth1010! Looks like this text is set in `core/modules/file/file.install` and also `core/modules/file/config/file.type.[TYPE].json`.

**Comment by stpaultim** [comment]
@Siddharth1010 - If you need any help with the process of writing a Pull Request or getting feedback, let us know. You can find us in Zulip for chat support as well.

https://backdrop.zulipchat.com/

**Comment by Siddharth1010** [comment]
Thank you @stpaultim. I would really appreciate your help

**Comment by BWPanda** [comment]
@Siddharth1010 created a PR here: https://github.com/backdrop/backdrop/pull/3477

**Comment by BWPanda** [comment]
One tip for next time @Siddharth1010, when you write "Fixes #4853..." in the PR, you'll need to use the full URL of the issue, not just the #ID number. For example: `Fixes https://github.com/backdrop/backdrop-issues/issues/4853`

This is because issues and in one repo, and PRs in another.

**Comment by Siddharth1010** [comment]
@BWPanda Thank you. I'll keep that in mind next time :)
I have closed the PR. When should I reopen it?

**Comment by stpaultim** [comment]
> I have closed the PR. When should I reopen it?

@Siddharth1010 - You only need to wait about 1 minute before you reopen it. Go ahead and reopen it now!

**Comment by stpaultim** [comment]
@Siddharth1010 - Two comments

1) In the future, start the title of your PR with the issue number. 

![pr-tips](https://user-images.githubusercontent.com/3144571/103504814-244ddc80-4e1e-11eb-868d-b92d914933d1.png)


2) When you add the comment "Fixes ...." You should add the path to the issue it fixes like this:

   `Fixes backdrop/backdrop-issues#2134` Github will automatically shorten it to "Fixes #2134". But if you don't do it the long way, then the link does not get created.

**Comment by BWPanda** [comment]
@Siddharth1010 I updated the post in the PR for you so the PR and issue are properly linked now.

There's one test failure, but it looks unrelated. So I'm marking this as RTBC.

**Comment by Siddharth1010** [comment]
@stpaultim Thank you. I'll make sure I do it right next time

**Comment by stpaultim** [comment]
@Siddharth1010 - No problem. We'd rather have you do it wrong than not do it at all! It's really great to see new people submitting PR's. 

Did you see that your PR is now linked to this issue, because you got this message correct `Fixes backdrop/backdrop-issues#4853 `

![newscreenshot](https://user-images.githubusercontent.com/3144571/103505361-a8549400-4e1f-11eb-9282-989fdbae222b.png)

**Comment by stpaultim** [comment]
@Siddharth1010 - I see that @BWPanda already verified that the test fail is unrelated and marked this Ready to be Committed. 

Looks like you are about to have your first commit to Backdrop CMS core! Congratulations AND thank you!

**Comment by stpaultim** [comment]
@Siddharth1010 - I hope to see more Pull Requests from you in the future!

**Comment by BWPanda** [comment]
@stpaultim Could you do the milestone please? 🙂

**Comment by Siddharth1010** [comment]
@BWPanda @stpaultim Thank you so much. I look forward to more PR's :)

**Comment by stpaultim** [comment]
@BWPanda - Done. Is it required to add an issue to a milestone before it can be committed, even if everything else is done?

@Siddharth1010 - Here is more information about how we use Milestones.
https://backdropcms.org/user-guide/adding-milestones-to-issues

Normally, we like to add issues to a milestone before they are committed to core (I am not sure if this is required). Normally, one user add the "Milestone Candidate - Bug" tag if an issue is eligible to be fixed in a bug-fix release. Then any other member of the community can remove the "Milestone Candidate" tag and actually add the issue to the Milestone (as I did) if they agree that this is a good candidate for the next release. 

This is not anything you need to worry about. Other members of the community can deal with this until you get familiar with the process.

**Comment by stpaultim** [comment]
@Siddharth1010 - One other note. You do not need to be assigned an issue to work on it or submit a Pull Request. It does not hurt, but you can just post a comment in the issue queue to let others know that you are working on the issue and proceed, without being assigned to the issue. 

I never assign myself to issues, but maybe I should.

**Comment by BWPanda** [comment]
> Is it required to add an issue to a milestone before it can be committed?

For normal issues, no. But if you want a bug fix or task issue to be committed to the next bug fix release, then yes. Without the milestone, this issue would just get committed to 1.x. With the milestone, it'll now be committed to 1.17.x as well.

**Comment by BWPanda** [comment]
Thanks so much @Siddharth1010 for your work on fixing this issue, and congrats on your first Backdrop contribution to core! 🎉

I've merged https://github.com/backdrop/backdrop/pull/3477 into 1.x and 1.17.x.
