### ISSUE TITLE
Rename 'Enable' buttons for display modes

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#4890]
Display modes can be 'customised', or 'not customised'. As discovered in https://github.com/backdrop/backdrop-issues/issues/3036 (see that issue for more background on this one), the 'not customised' ones aren't 'disabled' per se since you can still select them, for example, in Views' settings - they just end up using the Default display mode's settings.

![image](https://user-images.githubusercontent.com/2385329/105164809-b3225f00-5b69-11eb-9139-2e77bc245c41.png)

On the Manage Displays page, 'customised' display modes can be 'reset' (makes sense 👍🏻 )
However, 'not customised' ones can be 'enabled'... (huh? 👎🏻 )

Recommend changing the 'Enable' text to 'Customise' instead.

**Comment by BWPanda** [comment]
Here's a PR: https://github.com/backdrop/backdrop/pull/3579

![2021-03-29_16-40](https://user-images.githubusercontent.com/2385329/112791667-c263e280-90ad-11eb-9891-da04b7ffce3a.png)

**Comment by olafgrabienski** [comment]
I've tested the PR quickly on the sandbox website, works for me.

I'm a bit skeptical about one thing. Let's take content type Page as an example: Once you click the "Customize" link of a "Not customized for Page" display mode, it changes its position under the "Customized for Page", no matter if you really customize it via "Manage display".

There is already a success message with a link to the "Manage display" page (*The display mode Full content can now be **customized**.*). Great! I guess however the link isn't noticeable enough. At least, I didn't notice it in the first test attempts. Maybe the link would be more noticeable if we split the message in two: one success message and a warning containing the link.

**Comment by BWPanda** [comment]
@olafgrabienski I'm confused... Why would you want to add a *warning* here?

**Comment by olafgrabienski** [comment]
> Why would you want to add a warning here?

To make the link for actually customizing the display more visible. Probably it isn't the best solution, and I'm definitely open for other suggestions. Or don't you see an issue with the current behavior? (Once you click the "Customize" link of a "Not customized for Page" display mode, it changes its position under the "Customized for Page", no matter if you really customize it.)

**Comment by BWPanda** [comment]
Well, it kind of *is* customised once you click the link... When display modes are 'not customised', if you choose to use one somewhere (e.g. Views), it'll display just like the default display mode. But once you 'customise' one, even if you don't rearrange any fields, etc., it'll no longer use the default display mode.

**Comment by olafgrabienski** [comment]
> But once you 'customise' one, even if you don't rearrange any fields, etc., it'll no longer use the default display mode.

Thanks for the clarification, @BWPanda, sounds reasonable! (Going to mark the PR as "Works for me".)

**Comment by klonos** [comment]
So:

- With the label of the action being "Enable" as it currently is, it does indeed not make 100% sense in this case (although there is some logic that supported it being used, and it somewhat kinda matches other similar UI patterns).
- Currently, with the PR as it is (and as @olafgrabienski pointed out), there is a small WTF when you click "Customize" and the display is moved to the "customized" section (without it actually being customized).

In other words, none of the two situations is ideal really. So here's what I'm thinking would be a better UX:

1. We leave the button label as "Customize" as per the current PR 👍🏼 
2. Change the action of that button so that it leads to the "Manage display" page for that display.
3. Add a "Cancel" link/button to the "Manage display" form.
4. If the user clicks "Save" + there were changes in the display, they get redirected to the "Manage display" page, and the display is "enabled" and moved in the "customized" section.
5. If the user clicks "Save" but there were NO changes in the display, they get redirected to the "Manage display" page, and the display remains in the "uncustomized" (default) state (alternatively, we could have the "Save" button be disabled while there are no changes in the form).
5. If the user clicks "Cancel", they get redirected to the "Manage display" page, and the display remains in the "uncustomized" (default) state, in the "not customized" section.
6. For even better UX, we add new or tweak existing status messages, to either say:
   - "The xyz display is now customized for this content type" (if "Save" was clicked, and there have been changes)
   - "No changes were made in the xyz display" (if no changes, or "Cancel" was clicked).

What do you think?

**Comment by BWPanda** [comment]
What happens if people are used to the current functionality and want to 'enable' a display mode without further customising it? That no longer seems possible with your proposal @klonos...

I'd be happier to implement points 1-3 and skip the rest...

**Comment by indigoxela** [comment]
I agree with @BWPanda - especially step 5 in @klonos suggestion seems problematic to me. It makes the "Save" button behave like a Cancel button depending on data, which could be confusing.

**Comment by klonos** [comment]
Fair enough. Happy to test points 1-3 when you get time to implement it that way @BWPanda 👍🏼 

I have tested the UX on my local, and thought that the submit buttons when editing a display may be better as "Save and keep customized" (primary) and "Reset to default" (secondary):

![image](https://user-images.githubusercontent.com/2423362/113022243-14c80080-918d-11eb-9809-7d9c0f24e832.png)

...instead of a "Save" button and a "Cancel link":

![image](https://user-images.githubusercontent.com/2423362/113022433-4640cc00-918d-11eb-9322-9d24c3b0a530.png)

**Comment by indigoxela** [comment]
I'm a bit confused regarding the current state of this issue. Does it need work, or testing / review? What can we do to get it back on track?

The change in the PR is minimal (one word!) and it's logic. "Enable" definitely is wrong here, "Customize" is way better.

**Comment by jenlampton** [comment]
Since the current PR is RTBC for the name change, I think we should address the recommendation from @klonos in a separate follow-up issue, so that this improvement can get in first. 

I've created https://github.com/backdrop/backdrop-issues/issues/5129 where we can continue working on that improvement.

**Comment by quicksketch** [comment]
I've merged https://github.com/backdrop/backdrop/pull/3579 into 1.x and 1.19.x. Thanks!
