### ISSUE TITLE
[A11Y] Add screenreader label to Admin Bar Menu Search Input Field

### ISSUE THREAD

**Issue by ericvanderwal** [backdrop/backdrop-issues#4997]
**Description of the need**

The backdrop CMS admin bar has an input field for Menu Search. Currently, this input field has no label.

`<input placeholder="Menu search" autocomplete="off" autocorrect="off" autocapitalize="off" type="search" size="60" maxlength="128" class="form-search">`

**Proposed solution**

A label should be added HTML code. My suggestion is to use the 'label for' tag method. My understanding is that bootstrap 4 is under the hood already? If so, the css tag should hide the label from displaying but work correctly with screen readers. If not, it can be added, as it can be used in various places.

```
<label for="menuSearch" class="sr-only">Administration Bar Menu Search</label>
<input id="menuSearch" placeholder="Menu search" autocomplete="off" autocorrect="off" autocapitalize="off" type="search" size="60" maxlength="128" class="form-search">
```

css

```
.sr-only{
   position:absolute;
   left:-10000px;
   top:auto;
   width:1px;
   height:1px;
   overflow:hidden;
}
```

**Alternatives that have been considered**

An alternative can be using the aria-label. However, I prefer using the CSS trick, as it doesnt require the screen reader to be able to understand the aria tags. If we have no other choice, then I think aria is a reasonable solution, but using CSS should support more screenreaders.

**Further Reading**
https://blog.pope.tech/2020/02/28/missing-form-label-search/
https://github.com/twbs/bootstrap/issues/10446

**Comment by indigoxela** [comment]
This is the existing code:

```
  $search['search']['search'] = array(
    '#type' => 'search',
    '#title' => t('Admin search'),
    '#title_display' => 'attribute',
    '#attributes' => array(
      'placeholder' => t('Menu search'),
      'autocomplete' => 'off',
      'autocorrect' => 'off',
      'autocapitalize' => 'off',
    ),
  );
```
The problem is that the - actually existing label - is suppressed with `'#title_display' => 'attribute',`. IMO we should use the label properly.
See the docs: https://docs.backdropcms.org/form_api#title_display

Using "invisible" should be appropriate. It adds a label and hides it via css class "element-invisible". PR underway.

**Comment by indigoxela** [comment]
I'm not sure yet, if the provided [PR](https://github.com/backdrop/backdrop/pull/3564) fully covers the problem. It might need more work. Testing and feedback is welcome.

**Comment by indigoxela** [comment]
Ah, got it, adding the `#id` enables the missing `for=` attribute.

**Comment by klonos** [comment]
Thanks @indigoxela 🙏 ...yes, using `'#title_display' => 'invisible'` is the proper way to "hide" form elements in Drupal/Backdrop.

Not 100% about the addition of the id though. I mean sure, it fixes the problem at hand, but if `for=` is being added only by providing an ID, then we'll have the same issue in all our forms. Sounds to me that all form elements should have an ID then, and if that is the case, then it might be appropriate to have automatic IDs be generated for all elements (instead of "manually" adding one here).

**Comment by klonos** [comment]
@ericvanderwal in case you didn't already know, each time one of us provides a fix for an issue reported, the pull request is linked from the right-hand sidebar, in the "Linked pull requests" section:

![Screen Shot 2021-03-15 at 2 15 18 am](https://user-images.githubusercontent.com/2423362/111089407-68eba780-8534-11eb-87ca-13dbfb7c4c6b.png)

...in the PR, if you scroll to the very bottom, past any comments, you will find 2 comments that provide a sandbox with the code change, so that you can test:
- the comment by the "backdrop-ci" user is our legacy sandboxes (they sometimes fail to work)
- the comment by the "Dragon Bot" user is our newest implementation, using https://www.tugboat.qa (these are the ones you should be looking for)

The comment provides a link to a sandbox site, as well as the admin username/password to use. So please test this when you get a chance, and report back if the issue you've reported is properly fixed or still needs work.

Thanks 🙏

**Comment by indigoxela** [comment]
> Not 100% about the addition of the ID though. I mean sure, it may be fixing the problem at hand, but if for= is being added only by providing an ID, then we'll have the same issue in all our forms.

@klonos In most other forms the ID gets generated automatically, hence the necessary "for=" gets added, too. The admin bar seems to be one of the (rare?) exceptions. "aria-label" or "aria-labelledby" are the second best solution in cases, where a label tag with "for" attribute can't get added for whatever reason - which is not the case here IMO.

**Comment by indigoxela** [comment]
> provided that we add a @todo comment, to eventually figure out why the proper ID is not being added ... (or even file a follow-up issue for it)

It just depends on the context of the form item, I guess. To figure out, if this is considered a bug, it seems appropriate to create a new issue. Which just [has happened](https://github.com/backdrop/backdrop-issues/issues/4999).

**Comment by indigoxela** [comment]
@ericvanderwal testing is welcome!

You can use the sandbox, which automatically gets created for every pull request. It's also linked on the pull request [Conversation](https://github.com/backdrop/backdrop/pull/3564) page, but for convenience:

- Website: https://pr3564-ubp8igeextjmdxjpfdeprfcrnjp8jhzw.tugboat.qa/
- Username: admin
- Password: 3b9062013441

These sandboxes need some seconds to resume. After that you can log in with above credentials and do your testing.

**Comment by indigoxela** [comment]
@ericvanderwal friendly reminder... :smile: We'd really appreciate your testing of the changes. It shouldn't be too time-consuming. In case, you're not sure, how to use the testing sandboxes, don't hesitate to ask here or in our Zulip chat.

**Comment by ericvanderwal** [comment]
Thank you for your patience everyone (and more importantly your fixes). I have reviewed the changes on tugboat and the accessibility issue on the search bar has been corrected.

**Comment by klonos** [comment]
...and the code looks simple/good to me. RTBC 👍🏼

**Comment by stpaultim** [comment]
Remove Milestone Candidate label, it's already in the Milestone.

**Comment by laryn** [comment]
Thank you for filing the issue (and testing the PR) @ericvanderwal! And @indigoxela for the fix, @klonos for the code review. Improving accessibility in Backdrop :+1: :+1: 

I've merged https://github.com/backdrop/backdrop/pull/3564 into 1.x and 1.19.x.
