### ISSUE TITLE
Remove comment.module and replace with something like reply.module

### ISSUE THREAD

**Issue by SebCorbin** [backdrop/backdrop-issues#50]
This module needs love, but it's a more unified way to handle comments http://drupal.org/project/reply

**Comment by mikemccaffrey** [comment]
Since the comment module is in core, we are likely going to work on improving that rather than starting over with a different module. However, we should be definitely be able to replicate some of the same functionality and maybe even port over some code from the Reply module, but that should be done on a feature-by-feature case.

Perhaps we can create some tickets for the features that people like in Reply, create tickets, and add them to the comment meta at #2047?
