### ISSUE TITLE
Add a link to the BackdropCMS.org page on module list for each module

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#5003]
**Description of the need**
On the module list at `admin/modules` page would be nice to be able to see a link to the module's detail page on BackdropCMS.org and/or the repo on GH. 

**Proposed solution**
Add a link under the "more/less" toggle.

**Comment by RakeshPotnuru** [comment]
@docwilmot 
Can I work on this issue?

**Comment by stpaultim** [comment]
@RakeshPotnuru - You do not have to ask to work on an issue, unless you can see that someone else is already working on it. Just post a note saying that you are working on it and get started. If you have any questions, please feel free to ask here.

**Comment by stpaultim** [comment]
@RakeshPotnuru - If you need help getting started. Feel free to try our chat channel: https://backdrop.zulipchat.com/
If you have not read this yet, this is a good place to get started: https://backdropcms.org/news/openforce-2022-getting-started

**Comment by RakeshPotnuru** [comment]
@stpaultim 
Can you share relevant links for this issue?

**Comment by stpaultim** [comment]
@RakeshPotnuru is looking at Backdrop CMS for the first time, can anyone provide any tips or pointers at how to get started on this issue. I won't have time until tomorrow.

**Comment by VasasA** [comment]
1. If you open the `admin/modules` page, you can see "more" links in the descriptions of the modules. Open the first.
2. There is a line with "Tags:..." string. It is generated by `core\modules\system\system.theme.inc` Search `Tags:` string in this file (`function theme_system_modules_fieldset()`).
3. There is a `$requirements` variable. You should expand the `$requirements` with some new lines contain necessary links.
4. Links can be generated by `$key`, because it is the machine name of the module
  - Module's detail page: `'https://backdropcms.org/project/' . $key`
  - Module's repo on GitHub: `'https://github.com/backdrop-contrib/' . $key`
  Except the core modules. Core modules haven't got detail page and the 'repo' is only a subdirectory in [the core repo](https://github.com/backdrop/backdrop).

**Comment by klonos** [comment]
Thank you for working on the PR @RakeshPotnuru 🙏🏼

There are some test failures, but before you work further on the PR...

I had a quick look, and suggested the following:
- The new `div` introduced to hold the links has a class of `admin-requirements` (same as the `dvi` that holds the module tags) - I suggested that we also add another class; perhaps `project-links`.
- Instead of "module's detail page" and "module's repository", I suggested using "project information" and "GitHub repository", since that gives some indication as to where these links would take you.

I was about to suggest that we set `target="_blank"` on the links, so that there is no disruption to the workflow when checking the details of modules (navigating away from the site, then having to return - repeat). But then thought that it might be better altogether if we used the same UI pattern here as in the Project Browser, where we use a single link (the module name) to open a pop-up dialog with the project information (which we could improve to include a link to the GitHub project). Thoughts?

**Comment by RakeshPotnuru** [comment]
@klonos 
Those changes are ok.
As per the issue, we just need to add links for more information about modules. So why do we need to show project information?

**Comment by klonos** [comment]
@RakeshPotnuru the information shown in the `https://backdropcms.org/project/MODULE_NAME` links is the same as the project info in the pop-up dialog. For example:

- `https://backdropcms.org/project/devel`:
  <img width=50% src="https://user-images.githubusercontent.com/2423362/156989723-2ae1d0a5-3e72-41ea-9f75-55bd86734417.png">
- and the respective pop-up with the details/info from the Project Browser:
  <img width=50% src="https://user-images.githubusercontent.com/2423362/156989858-33b5d23e-2bca-42b5-b9bb-77d0d5b329b4.png">

It was just a suggestion, so it's fine if others also think that it's not a good idea 👍🏼

**Comment by stpaultim** [comment]
I've reviewed the PR in sandbox and I like it. My initial reaction to the pop-up idea was that it's unnecessary and I don't want to derail the PR of our enthusiastic new contributor. 

But, then I thought about the fact that this pop-up is displaying the README, which often has instructions on how to use a module. Wouldn't it be nice to have those instructions available right on the module page. 

The more I think about it, the more I like it. I'm curious what others think about this?

NOTE TO @RakeshPotnuru: It is not unusual in our issue queue, that once we have a PR to look at, the scope of the discussion changes, sometimes dramatically. Sometimes, the initial PR never get's accepted, but does lead to a completely new and better idea/feature - which is also a very important contribution. 

Thanks for giving us this PR to move this issue forward.

**Comment by stpaultim** [comment]
Also, I just noticed that the PR creates links for core modules that do not work - because they do not have project pages. I think that we can only have links for contrib modules, how much harder is that?

**Comment by RakeshPotnuru** [comment]
@stpaultim 
```php
if ($module_data[$key]->info['project'] !== 'backdrop') {
  $requirements .= '<div class="admin-requirements">' . t('Links:') . ' ' . l(t("module's detail page"), 'https://backdropcms.org/project/' . $key) . ', ' . l(t("module's repository"), 'https://github.com/backdrop-contrib/' . $key) . '</div>';
}
```

**Comment by VasasA** [comment]
@stpaultim 
> I just noticed that the PR creates links for core modules that do not work.

I think it is a speciality of the sandbox. Try without sandbox. There is a tag in every released module's `.info` file: `project = `
Only in the core modules: `project = bakcdrop`

**Comment by stpaultim** [comment]
@RakeshPotnuru - Don't forget to restore this PR so that folks can review it and see your work.

**Comment by stpaultim** [comment]
I put this on the dev meeting agenda for tomorrow. We have a PR that needs testing, feedback, and review. 

https://forum.backdropcms.org/forum/mar-10th-weekly-meeting-agenda-items?page=0%2C0#comment-3875

**Comment by BWPanda** [comment]
@klonos
I disagree with having a popup showing the module's README. If a contrib module is able to be installed, it's already on the system, so someone's already put it there (and presumably knows what it does). The only exception to this is core modules (some people might know know what they do), but ironically they don't have READMEs to show anyway. So I think ditch the popup idea and just go with the basic links for now.

@RakeshPotnuru
Some general feedback on the direction of the PR:

- Checking the 'project' in the info data to differentiate core modules doesn't seem like a solid solution here. I know @VasasA pointed out why it doesn't work in the PR preview site, but it also doesn't work on my local development site. I think a better way to check for core modules is to check if the 'uri' starts with `core/`:
![image](https://user-images.githubusercontent.com/2385329/157638549-56e77fc3-2a1b-44a8-a876-e63436bccbde.png)

- I'm not entirely comfortable with the call to `system_rebuild_module_data()` in the theme function... Since it's only used to check for core modules in the `if` statement, I think a better solution might be to do that check where the rest of the `$variables` are fetched outside this function, then just add a simple 'core' boolean to the `$variables` array that you can check here. I haven't looked further into this to know where that should happen though...

- I wonder if a better wording for the links might be something like:
  `Project links: BackdropCMS.org, GitHub`
  If not, at least capitalise the 'P' in 'project' 🙂 

Thanks for your contributions so far!

**Comment by VasasA** [comment]
@BWPanda Thank You for better and elegant way to check for core modules: I found a solution:
Insert this row into `core\modules\system\system.admin.inc` into line 789:
```php
  $form['#core'] = $extra['core'];
```
And the fixed code in the `core\modules\system\system.theme.inc`:
```php
    if (!$module['#core']) {
      $requirements .= '<div class="admin-requirements project-links">' . t('Links:') . ' ' . l(t("BackdropCMS.org"), 'https://backdropcms.org/project/' . $key) . ', ' . l(t("GitHub"), 'https://github.com/backdrop-contrib/' . $key) . '</div>';
    }
```
(Remove this line: `$module_data = system_rebuild_module_data();`)

**Comment by bugfolder** [comment]
> I disagree with having a popup showing the module's README

I, too, don't think the module's README should be in the popup, for the reasons articulated by @BWPanda.

**Comment by stpaultim** [comment]
@RakeshPotnuru - We discussed this at our meeting last week and the consensus was that we should get your last Pull Release working properly and treat the suggestion by @klonos as a new issue. 

I think we should start with the links and then discuss if we want more later. Are you interested in updating your last Pull Request with the feedback that has been provided, but staying with the same idea.

**Comment by stpaultim** [comment]
@RakeshPotnuru - Are you able to restore this PR?

**Comment by RakeshPotnuru** [comment]
> @RakeshPotnuru - Are you able to restore this PR?

I will open a new one. I can't restore.

**Comment by stpaultim** [comment]
@RakeshPotnuru - Excellent work. I've tested this PR and it works for me. 

The feedback from @VasasA has been incorporated and the PR no longer shows links to core modules. 

@klonos - There is opposition to the idea of using the same UI pattern as we have in the project installer, so I recommend that you save that for a new follow-up issue if you wish to pursue. I believe that this issue can proceed as it is. 

@BWPanda, @bugfolder, @VasasA or @docwilmot - does anyone else have any feedback? Can we get a code review?

**Comment by VasasA** [comment]
I have tested and reviewed, it it correct. :+1:

**Comment by stpaultim** [comment]
@VasasA - Are you prepared to mark this RTBC or do you want to wait for another review?

**Comment by BWPanda** [comment]
It works, and code looks good to me.

**Comment by BWPanda** [comment]
No advocate, but since this is RTBC now, adding to the minor milestone.

**Comment by VasasA** [comment]
It's great, thank You! :fireworks:

**Comment by stpaultim** [comment]
@RakeshPotnuru - Excellent work helping us make Backdrop easier to use and understand.

**Comment by quicksketch** [comment]
Hey folks, sorry to bump this back down but I think using `$key` in the `foreach` loop to link to the project page won't work in all situations: in particular custom modules (which have no matching project pages) and projects that contain more than one module (like "references" project).

As @RakeshPotnuru found earlier, you can get the project name from `$module_data[$key]->info['project']`. That should be checked for a value (it is not always present) and then that should be used as the basis for creating the links to backdropcms.org and GitHub.

**Comment by BWPanda** [comment]
Oops, thanks @quicksketch. I missed that. I confirmed on the PR sandbox site by installing References. The Node Reference submodule links to https://backdropcms.org/project/node_reference (which doesn't exist), and the same for User Reference (https://backdropcms.org/project/user_reference).

**Comment by docwilmot** [comment]
Is @RakeshPotnuru likely to finish this, or should I give it a try?

**Comment by RakeshPotnuru** [comment]
I will do it @docwilmot

**Comment by RakeshPotnuru** [comment]
Hi, I should change back to the first version of PR, right? Is that ok?

**Comment by stpaultim** [comment]
@RakeshPotnuru - I'm not sure what the first version looked like, so I'm not sure. 

Just make sure to address the issue raised by @quicksketch - https://github.com/backdrop/backdrop-issues/issues/5003#issuecomment-1099606957

If that is what you did in first version, then I guess the answer is yes?

**Comment by RakeshPotnuru** [comment]
This one - https://github.com/backdrop/backdrop/pull/3980/files

**Comment by stpaultim** [comment]
This is what it looks like when it's working:

![image](https://user-images.githubusercontent.com/3144571/164553877-d6ba6c91-bce0-4edc-8e1f-70a05a49682f.png)

**Comment by docwilmot** [comment]
I'm thinking for this to work it would actually need a request to Backdrop CMS project release service (or Project Installer Module) and the GitHub API to determine if the project has a release or a repo.

**Comment by indigoxela** [comment]
> I'm thinking for this to work it would actually need a request to Backdrop CMS project release service (or Project Installer Module)

I agree, but that might make that page a little "expensive" performance-wise.

@RakeshPotnuru in Backdrop it's also possible to install custom modules - actually that's pretty common. But these modules don't have a page on B-org nor our Github contrib repo, so the links would be misleading and 404, anyway.

Here's an example screenshot. You may have guessed: "Foobar" is no official module, so the automatically added links lead nowhere.

![wrong-links-module](https://user-images.githubusercontent.com/842066/164625004-45a1239a-0ac3-498a-afa0-801d25459384.png)

**Comment by docwilmot** [comment]
Added a comment in https://github.com/backdrop-ops/backdropcms.org/issues/870 to get us some way to get all available Backdrop projects. That would be a blocker to doing this issue properly. I suggest we postpone this issue till that is available.

**Comment by quicksketch** [comment]
> I'm thinking for this to work it would actually need a request to Backdrop CMS project release service (or Project Installer Module) and the GitHub API to determine if the project has a release or a repo.

I think the .info files already include most information needed. Added information right now is as follows:

```
; Added by Backdrop CMS packaging script on 2021-10-15
project = webform
version = 1.x-4.24.2
timestamp = 1634307705
```

Custom modules shouldn't include a "project" value, and I don't think it's unreasonable to assume that projects have a matching URL at both backdropcms.org and GitHub, since everything is tied together. The GitHub project name determines the backdropcms.org project name, which is the value saved into the .info file.

We could start including slightly more information if needed, such as the GitHub project URL if we wanted to support non-contrib modules, but for now only supporting contrib modules seems like a good start.

**Comment by stpaultim** [comment]
This had a milestone only because it was RTBC. Maybe we should remove the 1.22.0 milestone. I will remove the "Works For Me" label, since I'm pretty sure it's not in a working state until we resolve this last problem.

**Comment by indigoxela** [comment]
> I think the .info files already include most information needed...

They do, but as this packaging script info is a comment, I suspect that info isn't available at that point (on the listing page). Didn't dig deeper, though.

**Comment by BWPanda** [comment]
The first line's a comment, the other three aren't...

**Comment by indigoxela** [comment]
> The first line's a comment, the other three aren't...

Hm, sure, but the three other ones can also exist in custom modules - timestamp is probably unlikely in use unless created with our packaging service. At least, I don't add that to custom modules.

**Comment by BWPanda** [comment]
'project' isn't even documented as an option, so I don't see how/why custom modules would specify that... https://docs.backdropcms.org/creating-modules#info-files

**Comment by jenlampton** [comment]
> I don't see how/why custom modules would specify that...

Back when people had features servers to manage their own custom projects it was more popular. I've been using private GitHub packages for that service these days, so I could see it still being valuable for custom projects. 

That said, If I've got a set-up advanced enough to be managing my own packages, I'll know those are custom projects, and I'll understand if the links don't work as expected.

**Comment by docwilmot** [comment]
> I think the .info files already include most information needed. Added information right now is as follows:

Thats a good point. It would still skip modules downloaded directly from GitHub, but I suppose that would probably be OK for the average user. @RakeshPotnuru are you willing to try again? Apologies for the back and forth.

**Comment by RakeshPotnuru** [comment]
@docwilmot If this issue needs deep understanding of the core, then I may not be the right person. So you can work on this if you like to.

**Comment by docwilmot** [comment]
@RakeshPotnuru you'd need to check if the info file has a `project` key in `_system_modules_build_row()`, like
```
  if (isset($info['project'])) {
    $form['#project'] = $info['project'];
```
then in `theme_system_modules_fieldset()` check if a project exists and use that instead of `$key`.

**Comment by stpaultim** [comment]
@RakeshPotnuru - This sounds like something you can do. Do you want to give it a try? We just have a few days before feature freeze on version 1.22.0. 

I'm going to remove "Works for me" label. I tried to do this a few days ago, but removed the wrong label. :-(

**Comment by RakeshPotnuru** [comment]
@stpaultim @docwilmot 
Okay then, I will do.

**Comment by RakeshPotnuru** [comment]
I think it's working now.

<img width="895" alt="image" src="https://user-images.githubusercontent.com/70439799/165504893-8087a76e-9d35-49ac-a304-140d602884d3.png">

**Comment by stpaultim** [comment]
We have a updated PR ready for testing and review.

**Comment by quicksketch** [comment]
The hiding/showing of the links is good now, but the links themselves may still point to a non-existing project if the project contains sub-modules. I made one more suggestion to the PR: https://github.com/backdrop/backdrop/pull/3996/files#r862387168

**Comment by docwilmot** [comment]
This has been updated.

**Comment by argiepiano** [comment]
I've tested and reviewed the code. LGTM 👍🏽

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/4063 into 1.x for 1.22.0. Thanks @RakeshPotnuru and everyone for the collaboration to make this happen!

**Comment by olafgrabienski** [comment]
> Also, I just noticed that the PR creates links for core modules that do not work - because they do not have project pages

I've updated a test site from 1.21.4 to 1.22.0-preview, and there are still Github links for core modules that don't work. Reading the comments, I had the impression the issue had been adressed. Can someone confirm?

- https://backdropcms.org/project/backdrop - works √
- https://github.com/backdrop-contrib/backdrop - doesn't work

**Comment by olafgrabienski** [comment]
> the issue had been resolved

Thanks for the feedback! Shouldn't it work 1.22.0-preview then, or am I missing something?

**Comment by argiepiano** [comment]
@olafgrabienski I think you are right. The PR hard-codes backdrop-contrib, but all core modules are hosted in backdrop/backdrop, not backdrop-contrib/backdrop.

Should we open another issue for this, since this has been merged?

**Comment by argiepiano** [comment]
Wait a moment, this functionality only adds links to contrib modules, not to core ones. Am I missing something?

**Comment by argiepiano** [comment]
Very strange. I just updated a 1.21.4 site by manually downloading 1.22.0preview from [here](https://github.com/backdrop/backdrop/releases/tag/1.22.0-preview) and I'm seeing the same problem you have - it's adding links to core modules. I had previously tested this on a site that I had updated a few days ago and that wasn't the case (see images comparing the two sites - both say 1.22.0-preview!!!)


Definitely worth digging into. 

<img width="1168" alt="Screen Shot 2022-05-11 at 11 47 59 AM" src="https://user-images.githubusercontent.com/9938978/167914181-41c9f8ba-906b-4590-84f9-6f4150b8f254.png">
<img width="1142" alt="Screen Shot 2022-05-11 at 11 46 55 AM" src="https://user-images.githubusercontent.com/9938978/167914200-1cd81b00-fa5a-4d64-8076-ecf6f8965e4e.png">

**Comment by argiepiano** [comment]
OK I think I know why this is happening. We did not catch this on Tugboat because it uses the dev versions, which are not packaged by B-org yet. However as soon as you have a release, b-org adds this, which makes the `project` key not empty

```
; Added by Backdrop CMS packaging script on 2022-05-02
project = backdrop
version = 1.22.0-preview
timestamp = 1651537776
```

So, the solution is to check if the project is 'backdrop' then we should output a different URL

**Comment by argiepiano** [comment]
(or maybe Tugboat is not using the dev version, but it's definitely using an unpackeged version?)

**Comment by argiepiano** [comment]
another clue that confirms that the info file is the culprit for 'project' being empty: admin_bar and other core modules in my site that doesn't show the links do not have the added packaging links. Perhaps when I downloaded them they had not been yet packaged (?)

**Comment by olafgrabienski** [comment]
Follow-up issue: #5623
