### ISSUE TITLE
Behat testing?

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#5005]
I've mentioned before that I've been writing and managing [Behat](https://docs.behat.org/) tests for a D7 site in my day job, on and off for the last year or so. They're interesting to me because, when done correctly and thoroughly, people can 'write' tests without needing any coding skills.

For those unfamiliar with Behat tests, here's what they look like:

```feature
Scenario: Logging in to a Backdrop site as an Administrator
  Given I am logged out
  And I am on the homepage
  When I click "Login"
  And I fill in "Username or email" with "admin"
  And I fill in "Password" with "password"
  And I press "Log in"
  Then I should be on "/admin/dashboard"
  And I should see "Welcome to Backdrop CMS!"
```

They work by having code in the background parse these statements, and run certain functions that perform the necessary actions for each one. For example, the function for `I am logged out` would make a request to the URL `/user/logout` to make sure the user is logged out before continuing. This is possible because Behat tests happen in an actual browser. Links can be clicked, URLs accessed, source code checked, etc. All done programatically just by writing non-code scenarios like the above.

The caveat is that Behat tests are primarily geared towards testing the UI. Making sure that when you click here and enter this text, then you'll see this message or be redirected to this page. Stuff like that. They're not used for testing code (e.g. does calling this function with these arguments return the value I expect).

So I'm wondering... Is there a place/need for Behat tests in Backdrop? If so, I might be interested to help setup a Behat testing system for Backdrop...

**Comment by philsward** [comment]
Makes me wonder if accessibility tests could benefit from this (if even possible). Then again there may be better tools for that...

Interesting idea though.

**Comment by indigoxela** [comment]
Interesting. I never worked with Behat.

> This is possible because Behat tests happen in an actual browser.

What sort of browser? One that can execute Javascript?

> They're not used for testing code (e.g. does calling this function with these arguments return the value I expect).

Hm, so it's probably no real replacement for our Simpletest (Could-be-worse-test :smirk:) module.

**Comment by jlfranklin** [comment]
Behat is awesome.  I don't remember it requiring a browser, and I know I've used the [Drupal API driver](https://behat-drupal-extension.readthedocs.io/en/v4.0.1/drupalapi.html) to run tests in a local dev environment or a Jenkins pipeline.

It does support using Selenium, which can be used to drive a browser.  Pantheon has a [blog post](https://pantheon.io/blog/javascript-testing-behat) about setting up JS testing through a browser.

> Hm, so it's probably no real replacement for our Simpletest

No, it's not a replacement for Simpletest.  It is excellent for writing tests that non-technical stakeholders can read and understand.

**Comment by klonos** [comment]
> It is excellent for writing tests that non-technical stakeholders can read and understand.

I would also add "and contribute" as well 😉 

I am wondering re what the requirements are for running Behat tests. I could look into it, but since both @BWPanda and @jlfranklin seem to already be knowledgeable, I might as well ask them to enlighten us 😅 

...the reason I'm asking is because I wouldn't wanna "force" people to be installing additional tools on their system (same reasons why we don't require composer/symfony etc.).

**Comment by BWPanda** [comment]
Re. browser, the setup I use for work uses a headless version of Chrome (which I believe is faster than Selenium) for JavaScript-required tests: https://gitlab.com/DMore/behat-chrome-extension

For non-JS tests, it uses Goutte: https://github.com/FriendsOfPHP/Goutte

Its no replacement for Simpletest, but I believe there are some tests we've written in Simpletest that might be better done in Behat... I'll take a look.

Re. requirements, there's a bunch of stuff you need to install/configure, but I've just been using Lando to setup the environment and run all the tests.

What I'll to is make a POC Lando file that people here can test. That'll give you an idea how it works, and help me to know if my D7 setup is transferrable to Backdrop.

**Comment by jlfranklin** [comment]
> What I'll to is make a POC Lando file that people here can test. That'll give you an idea how it works, and help me to know if my D7 setup is transferrable to Backdrop.

I'll do the same sans Lando.  I'm curious to know if it works on Backdrop, myself.

**Comment by stpaultim** [comment]
Just be clear, are we talking about using Behat for automated testing of core?

Or are we simply talking about making sure that Behat works with Backdrop for Backdrop users that wish to write Behat tests for their projects?

I have done some work with Behat tests (mostly writing them and using them). I've not done any custom work with Behat myself. I love using Behat tests, but don't usually find time to implement them.

Knowing that Behat is available for Backdrop users seems like it would be nice. Since we must have Simpletest for core automated testing, it's not yet clear to me that using Behat for core tests is helpful or practical. I look forward to hearing what others are thinking.

**Comment by BWPanda** [comment]
> are we talking about using Behat for automated testing of core?

That was the purpose or my original question, yes.

**Comment by jlfranklin** [comment]
> Just be clear, are we talking about using Behat for automated testing of core?

I don't consider Behat to be a suitable replacement for Simpletest.  Behat (and Gherkin in general) is built for behavior driven development (BDD) testing. That is, when I do something on the site, the site responds thusly.

Simpletest is built for unit testing.  it can test things limiting the scope of the test to a single function or an API.  Think database API: calling `db_update()` with a string in an integer column returns an error.  While you can make a page that returns the error for a Behat test, you're testing the database API, the menu router, the theming layer and everything that connects them.  Simpletest is testing just the database code.

That said, there is a lot of value in creating a base set of Behat tests in addition to the Simpletest suite both for our own use and as a starting template for sites that want to do BDD with Behat.  There is also a lot of value in creating a library of Backdrop-specific Behat phrases to make such testing easier.  For example, I don't think there is a phrase to do things like sort a column in a view or drag a taxonomy term to the third row and indented one level.

I wouldn't put it into core straight away.  It'd be better to do it as a backdrop-ops project first.

**Comment by BWPanda** [comment]
Here's an initial demonstration of Behat: https://github.com/BWPanda/backdrop_behat

To test it:
- Make sure you have Lando installed
- Clone/download/extract the `backdrop_bahat` repo
- From inside that directory, run `lando start`
- Once started, run `lando behat`

I wrote two basis tests: one tests logging into Backdrop as an admin user, the other tries to edit the About page as an anonymous user (and fails). Tests are `*.feature` files in the `features` directory.

There is a [Drupal extension for Behat](https://www.drupal.org/project/drupalextension) which I use in D7 and which allows for many more options in terms of the sort of tests you can write. @jlfranklin touched on this above. Examples include:
- Given I am logged in as a user with the "administrator" role
- When I run cron
- When I am viewing a "tags" term with the name "My tag"
- etc.

I tried to use this with Backdrop, but it didn't work (said I didn't have the right version (6, 7, 8) of Drupal). It may just need to be forked and then tweaked, or it may need lots of work to become Backdrop-compatible. Either way, I didn't bother for now. But that'll likely need to happen should we decide to pursue Behat testing for Backdrop...

Hope that helps!

**Comment by BWPanda** [comment]
> I believe there are some tests we've written in Simpletest that might be better done in Behat... I'll take a look.

The Views UI tests I think could be converted to Behat:
- Tests creating views with the wizard and viewing them on the listing page.
- Tests enabling, disabling, and reverting default views via the listing page.
- Tests the ability of the views wizard to create views filtered by taxonomy.
- Etc.

So could come of the user tests:
- Reset the password by username via the password reset page.
- Make an unsuccessful login attempt.
- Tests Field API fields on user registration forms.
- etc.

I'm sure there are many more.

**Comment by klonos** [comment]
@BWPanda even if we don't do something with Behat in core, perhaps a blog post on it would help site owners/builders get started with it. In the agency I work for, we include Behat testing for the main functionality of the site as an additional/optional service, and most customers go for it (in order to avoid regressions and save time on manual testing/UAT).

> It may just need to be forked and then tweaked, or it may need lots of work to become Backdrop-compatible.

I see value in making it work with Backdrop 👍🏼

**Comment by BWPanda** [comment]
> I see value in making it work with Backdrop

Agreed. I'm just not sure I'm willing to put in the time & effort for that; especially if it's not for core...

**Comment by quicksketch** [comment]
In my experience with Behat, it has not enabled non-technical users to effectively write tests. The promise of Gherkin, which allows you to write "plain sentence testing instructions" doesn't come through, because most tests require some sort of specialized check, such as a value being present in the database, in the UI, or comparing values against each other. This means that one of the two has to be done:

* A new Gherkin assertion has to be created by a developer.
* A new module or UI has to be written by a developer expressly for the purposes of checking the result.

Projects with Behat on them end up with dozens of specialized checks

The only thing Gherkin brings to the table is that it makes tests _readable_. It does not really make them more writable. My experience is that it actually makes testing harder than before, both because it's difficult to figure out exactly what magic sentences you should type, and because it's a layer of abstraction between the test instructions and the test execution. More advanced IDEs (like PHPStorm) can actually autocomplete the Gherkin sentences, but even then it's a challenge.

That said, I think having Behat as a working solution for testing existing Backdrop sites would be valuable. Many developers have a preference for that format of testing.

**Comment by BWPanda** [comment]
Since my original question of using Behat testing for Backdrop core seems to have been answered, I'll close this issue. It can remain here for posterity though, in case people want to use Behat in Backdrop for other purposes.
