### ISSUE TITLE
Is it posible to build the configuration page by grabbing modules that have a "configure" operation from the modules list?

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#508]
In #494 we are looking at ways to improve the modules page by organizing the modules list in groups that are more "meaningful".

In #506 we are looking at various ways to improve the UX of the configuration page (`/admin/config`).

It would be good if these two pages used similar grouping for consistency. Now, I was thinking that it will be really tedious having to maintain the items listed in the config page manually and to keep them in parity/sync with the modules list (its grouping might change in the future). On the other hand, I see that system config options provided in the config page are provided by core modules. These modules have (or _should_ have if not) a "configure" operation available in the modules list.

So, I thought that we could perhaps automate this by "grabbing" all the modules that do have a "configure" operation available in the modules page and then building the config page off of these modules. At the same time, we would use the same grouping that these modules have in the modules page to group the respective config links in the config page. This way, a change in a single place (modules page) would reflect changes in both places and keep them in sync for us.

Does this make sense? Is it possible? Can we make it for 1.0.0? If not, what we could do at the very least is to "manually" make sure that these two pages have similar groupings before we launch.

**Comment by jenlampton** [comment]
For starters, I'm not sure it *would* be good to have the same groupings on the modules page as on the config page. We use these two different pages for two very different things, and I think making the two groupings match will make them both less effective.

The config page groups by the location of the item in the menu system. We have modules that don't add settings pages into the menu system.

The module page groups by type of functionality (roughly). We don't have settings or special config for all modules, or module types. "Fields" for example, don't fit this model, since all those settings pages are associated with the entity types.

Consistency is generally good, but I'm against this proposal.

**Comment by quicksketch** [comment]
I'd also point out that several modules make multiple configuration pages, so grouping these 1-to-1 between the modules page and the configuration page wouldn't be a complete solution.
