### ISSUE TITLE
Step 3.5 of installation does not support strict CSP-SOP configuration

### ISSUE THREAD

**Issue by narcisgarcia** [backdrop/backdrop-issues#5086]
**Description of the bug**

I've tested Backdrop 1.18.3 it on a Debian 10 server (Apache 2.4 PHP 7.3) and page "Installing Backdrop CMS" does not walk forward by itself.

```
X-Frame-Options "SAMEORIGIN"
X-XSS-Protection "1; mode=block"
Content-Security-Policy "default-src 'none'; img-src 'self' data:; media-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline' data:; font-src 'self' data:; object-src 'self'; base-uri 'self'; connect-src 'self'; form-action 'self'; frame-ancestors 'self'"
Referrer-Policy "same-origin"
```

If I disable all CSP & SOP policies, installer wizard runs well.
WYSIWYG editor does not work with strict CSP & SOP too.

**Comment by findlabnet** [comment]
Do you have any other web application working well with your "CSP & SOP policies"?

**Comment by indigoxela** [comment]
@narcisgarcia first of all: welcome to the Backdrop community! :vulcan_salute: 

One question comes to my mind: at the time you try to install Backdrop on your Debian - do you already have a valid certificate set up and https works properly on your vhost? If that's not the case, then your (non-csp part of) setup might be the culprit.

**Comment by indigoxela** [comment]
@narcisgarcia I took a look. The culprit about your CSP are probably this:

`script-src 'self';` You'll need 'unsafe-inline', too. Otherwise the js settings won't work. Which is probably also the reason, why CKEditor doesn't work with that policy. I didn't try it out, though, it's only an assumption.

IMO this is a wontfix. And as @findlabnet already stated - you'll have trouble to get any web CMS (with wysiwyg editors) running with it.

**Comment by klonos** [comment]
Related(?): #5477

**Comment by quicksketch** [comment]
@klonos Yes looks very related! Could you possibly copy the report over to this issue and mark that one a duplicate? I think that solution would at least solve the installation portion of the problem described here.

**Comment by klonos** [comment]
@quicksketch I would otherwise agree, but this issue here is a very specific bug report, wheres #5477 is a more generalized task. It might be that it ends up solving this bug partially or in its entirety, but it wouldn't be the goal per se - it would be a side-effect.

Besides, this specific issue here might simply be a matter of misconfiguration/oversight in the definition of `Content-Security-Policy` as @indigoxela pointed out in her last comment.

**Comment by quicksketch** [comment]
Okay, I'm fine with that. Can we mark this a support request then and close it? Solution 1 is to modify `Content-Security-Policy` as @indigoxela suggested to work with Backdrop as-is. Solution 2 is to wait for #5477, which will allow `script-src 'self';` as an adequate configuration out of the box (though many modules may continue to inline their own JS).

**Comment by jenlampton** [comment]
We don't have a `type = "support request" `(as those are usually done in the forum) but we do have a `type = "question"` so Ive added that label. I am closing this issue as there have been no further replies for quite a while.
