### ISSUE TITLE
Function system_image_toolkit_settings_submit() prevents nested form arrays from saving properly

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#5110]
**Description of the bug**

For a long time there was no additional image toolkit, which is probably the reason, why it took so long until this was discovered.

Now there is one. And there's [a problem](https://github.com/backdrop-contrib/imagemagick/issues/6) with this function.

**Steps To Reproduce**

Provide an additional image toolkit and nest your form items, for instance in a fieldset.

**Actual behavior**

Nested form item values do not get saved.

**Expected behavior**

Should work the same as in Drupal 7, I guess?

**Additional information**

This is the problematic code:
https://github.com/backdrop/backdrop/blob/e088561f6df7a1e5194ec9f5c4c9b69960876fee/core/modules/system/system.admin.inc#L1935

It came in with "Issue #170: Converting file system, clean URL, and private key variables to config." back in 2014

A workaround for contrib is to avoid nested form items, but that might be an unnecessary restriction.

**Comment by quicksketch** [comment]
Looks like from the ImageMagick module, this difference occurred in the porting of ImageMagick, rather than being a core change (see https://github.com/backdrop-contrib/imagemagick/issues/6#issuecomment-864338197).

Drupal 7 calls `system_settings_form()` on the entire form, which also directly saves values based on the form structure. So the saving of values should be the same, even though in Backdrop this has a dedicated submit function instead of using `system_settings_form()`.

**Comment by indigoxela** [comment]
I interpret this as "should get fixed in contrib". :smirk:

@quicksketch many thanks for having a look and recommending a solution in the contrib modules' issue.
