### ISSUE TITLE
Change `admin/people` dropbutton operation from "Cancel" to "Cancel account"

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop/backdrop-issues#5118]
**Description of the bug**

The dropbutton operation for cancelling a user account on the `admin/people` page is called "Cancel". While the single term "Cancel" in this context means "Disable or delete", it means "Stop or abort an action" in most (I guess all) other places of the Backdrop interface.

This isn't a (big) problem in an English interface: readers are usually able to get the meaning of the term in context. But in German (and maybe other languages) you have to decide between two translations of "Cancel", depending on the context. The translation "Abbrechen" is fine for most places but not correct in the user account dropbutton.

**Actual behavior**

It's not possible to translate the term "Cancel" correctly for all places in Backdrop.

**Expected behavior**

Being able to translate the term "Cancel" without issues.

**Comment by olafgrabienski** [comment]
Possible approaches:

- Add string contexts to the term "Cancel" (see below)
- Change the term "Cancel" in the dropbutton to "Cancel account"

I prefer to change the term as it improves the situation for English as well.

---

[String contexts](https://docs.backdropcms.org/api/backdrop/core%21includes%21bootstrap.inc/function/t/1) could look like this:

`t('Cancel', array(), array('context' => 'Stop or abort')`
`t('Cancel', array(), array('context' => 'Disable or delete')`

**Comment by indigoxela** [comment]
+1 for changing the text in the dropbutton. A screenshot might better explain, why:

![cancel-dropbutton](https://user-images.githubusercontent.com/842066/122341235-89683b00-cf43-11eb-88ca-6e8edd62fe17.png)
Pretty ambiguous, no?

While on that page it can be assumed, that "cancel" means "delete or disable" in this context, "Cancel account" would be less ambiguous.

I'd suggest a minimal change only in class [views_handler_field_user_link_cancel](https://github.com/backdrop/backdrop/blob/08f9bf83c717088a7544325c2e4b05a626e55a50/core/modules/user/views/views_handler_field_user_link_cancel.inc#L25)

So, either
```
$text = !empty($this->options['text']) ? $this->options['text'] : t('Cancel account');
```
OR
```
$text = !empty($this->options['text']) ? $this->options['text'] : t('Cancel', array(), array('context' => 'User account');
```
IMO the context is only needed there, because that's the only time that single word occurs in a context other than "Cancel this form action".

**Comment by laryn** [comment]
I agree 'Cancel account' is more clear.

**Comment by indigoxela** [comment]
A [PR](https://github.com/backdrop/backdrop/pull/3647) is available for testing and review.

A screenshot in German:
![dropbutton-text-new](https://user-images.githubusercontent.com/842066/122527784-f0592300-d01b-11eb-841c-3180ae81b837.png)

BTW this does *not* need any translation update, because the string "Cancel account" already exists and this correct translation is used.

(Off topic: my first PR after months, and ZenCI welcomes me with an internal server error... :grin:  I'll turn it off and on until it works.)

**Comment by olafgrabienski** [comment]
> BTW this does not need any translation update, because the string "Cancel account" already exists ...

Oh, sure, that's great! Thanks for checking.

**Comment by olafgrabienski** [comment]
> A PR is available for testing and review.

> A screenshot in German

Many thanks for the PR! Works for me in the sandbox. Here a screenshot of the English interface:

<img width="363" alt="backdrop-pr-cancel-account" src="https://user-images.githubusercontent.com/14188307/122539002-6c0c9d00-d027-11eb-99ce-de0b59b1e0c6.png">

**Comment by jlfranklin** [comment]
Given the new meaning "cancel" has, especially when applied to people, perhaps a better term can be used.  "Cancel" isn't the right term in the first place.  Cancelling an action anywhere else in the site means the effect is not applied.  You may be half-way through a "create new thing" wizard, click Cancel and the new thing never exists.  Similarly, cancelling an order means the order is dropped before it is fulfilled.

Delete is a better term here, or Remove.

**Comment by indigoxela** [comment]
> Given the new meaning "cancel" has, especially when applied to people, perhaps a better term can be used. "Cancel" isn't the right term in the first place.

@jlfranklin This term is used for cancelling accounts throughout Backdrop. If you want the term to get changed everywhere, please open a new issue for that and don't block this fix for sites in other languages. Otherwise we discuss here for ages and in the meantime many translators wait for a simple fix.

**Comment by olafgrabienski** [comment]
I also stumbled upon the meaning of the term "Cancel" and I'd be interested to discuss alternatives in a separate issue.

**Comment by stpaultim** [comment]
I support this change. I also wonder if @jlfranklin has a point about the overall use of "Cancel" for accounts. I've wondered about this myself. But, I also agree that is a bigger issue and should be handled separately.

**Comment by klonos** [comment]
> ...my first PR after months, and ZenCI welcomes me with an internal server error... 😁 I'll turn it off and on until it works.)

IKR? 🙄 🤷🏼 

> I also stumbled upon the meaning of the term "Cancel" and I'd be interested to discuss alternatives in a separate issue.

Here you go: #5121 😉

**Comment by quicksketch** [comment]
I'll add that "Cancel" and "Delete" are not interchangeable, since cancelling an account has several different actions on the account, including either deleting or disabling the account:

![image](https://user-images.githubusercontent.com/100206/123891793-4b3d2500-d90e-11eb-8682-cbc91ed43835.png)

So I agree that just updating the dropbutton to be more descriptive is a good step here.

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/3647 into 1.x and 1.19.x. Thanks folks!
