### ISSUE TITLE
Views exposed grouped filter of numeric field doesn't show "value" input fields

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#5127]
**Description of the bug**

When creating a View, whenever you try to add an exposed grouped filter for a numeric field, the configuration page doesn't show a "Value" input field. The "value" input field should appear in the 4th column of the configuration modal window, after "Operator". This bug seems to happen only for numeric fields (e.g. the nid field).  

**Steps To Reproduce**

1. Create a View for Content or any custom entity that contains a numeric field (e.g. the entity ID field or any other). 
2. Try to add a filter for that numeric field. 
3. Select "Exposed" then "Grouped". 
 
The configuration modal doesn't show the "Value" input field, even if you change to a different operator that requires a value. 

**Actual behavior**

The Value column where the input fields should appear is empty. If you examine the source of the page you will notice that all input fields for Value have a "display: none;" style applied to them.

**Additional information**

- Backdrop CMS version: 1.19.1
- Browser(s) and their versions: Chrome 91.0

**Comment by indigoxela** [comment]
Confirmed, the "value" field is hidden. And as it's an inline style (display: none), it seems to happen in some Javascript. The value field is essential, as it's a required field for grouped filters.

I also verified, that this works fine in Drupal7, so some Backdrop js messes it.

**Comment by indigoxela** [comment]
A [PR](https://github.com/backdrop/backdrop/pull/3663) is available for testing.

Note that it still needs work. It currently only addresses the broken states in views UI, but not yet the broken ajax output in the same form when adding another item.

**Comment by argiepiano** [comment]
Thank you for the quick attention. The fix works fine in my case for this specific issue!

**Comment by indigoxela** [comment]
> Thank you for the quick attention.

Thanks for reporting. :+1: 

The PR has been updated to also address the redirect problem now (json output in browser).

For reviewers:

Instead of "blindly" unsetting things by numeric key, it now overrides the existing state setting to match the (nested) group items.
The change regarding button class should actually be self-explanatory. The class "use-ajax-submit" prevents the direct json output.
I also changed the way the title (form label) gets hidden (WAI - label is required) and added a placeholder. That's not directly part of the reported issues, but I think we should fix accessibility problems as we see them.

The steps for testing (for instance in the sandbox) are:

1. Create a view of nodes
2. Add a numeric filter (e.g. nid), set it as exposed, set it to grouped, configure the grouped items
3. Add more items

An example for a grouped filter:

- nid 1 - 5 (set the range accordingly)
- nid 6 - 10 ...

**Comment by argiepiano** [comment]
I've tested as indicated, adding different options to the grouped filter (ranges, "greater than" and other options),  and also added more items by clicking the button. Everything seems to be working as expected. Thanks for the quick work!

**Comment by indigoxela** [comment]
@argiepiano great, many thanks for testing!

**Comment by herbdool** [comment]
This code looks good to me and your reasoning is sound. Thanks @indigoxela !

**Comment by quicksketch** [comment]
Thanks for reviewing @herbdool! I've merged https://github.com/backdrop/backdrop/pull/3663 into 1.x and 1.19.x.

Thank you @indigoxela for the PR and thank you @argiepiano for filing the issue and testing!
