### ISSUE TITLE
Various maintenance-page.tpl.php error messages.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#514]
Running update.php brings up these errors:

```
Notice: Undefined variable: language in include() (line 2 of C:\www\backdrop\core\themes\seven\maintenance-page.tpl.php).
Notice: Trying to get property of non-object in include() (line 2 of C:\www\backdrop\core\themes\seven\maintenance-page.tpl.php).
Notice: Undefined variable: language in include() (line 2 of C:\www\backdrop\core\themes\seven\maintenance-page.tpl.php).
Notice: Trying to get property of non-object in include() (line 2 of C:\www\backdrop\core\themes\seven\maintenance-page.tpl.php).
Notice: Undefined variable: head in include() (line 5 of C:\www\backdrop\core\themes\seven\maintenance-page.tpl.php).
Notice: Undefined variable: styles in include() (line 6 of C:\www\backdrop\core\themes\seven\maintenance-page.tpl.php).
Notice: Undefined variable: scripts in include() (line 7 of C:\www\backdrop\core\themes\seven\maintenance-page.tpl.php).
Notice: Array to string conversion in include() (line 9 of C:\www\backdrop\core\themes\seven\maintenance-page.tpl.php).
```

Also, the update.php page is no longer themed.

**Comment by jenlampton** [comment]
I think deleting before replacing *is* the standard update procedure.  When you update a module you delete the whole directory before adding the new version.  Why should updating core be any different? 

I think people may have developed these habits from working with Drupal just because core was so hard to delete before replacing, but now that it's in it's own directory it shouldn't be an issue - even in minor versions. 

We may just need to clearly state update instructions someplace so we can point people to the "standard update procedure" since we are going to be seeing this happen a lot.

**Comment by jenlampton** [comment]
I've updated the documentation on https://backdropcms.org/guide/upgrade but I think we should also update the in-browser documentation at `/core/update.php?op=info` to match.
See https://github.com/backdrop/backdrop-issues/issues/529
