### ISSUE TITLE
Offer link to latest release

### ISSUE THREAD

**Issue by gitressa** [backdrop/backdrop-issues#5156]
**Description of the need**
Lando has a [quick start example for Backdrop](https://docs.lando.dev/config/backdrop.html#getting-started) pointing to the 2.5 years old version `1.12.1` from January 2019:
```
# Initialize a backdrop recipe using the latest backdrop version
lando init \
  --source remote \
  --remote-url https://github.com/backdrop/backdrop/releases/download/1.12.1/backdrop.zip \
  --recipe backdrop \
  --webroot backdrop \
  --name my-first-backdrop-app
```

**Proposed solution**
Wouldn't it be cool if Backdrop offered a link pointing to the latest release, so this would be possible?
```
# Initialize a backdrop recipe using the latest backdrop version
lando init \
  --source remote \
  --remote-url https://github.com/backdrop/backdrop/releases/download/latest/backdrop.zip \
  --recipe backdrop \
  --webroot backdrop \
  --name my-first-backdrop-app
```

**Comment by laryn** [comment]
This sounds like a great idea to me -- and perhaps the script that fires when a release is made could be modified to copy the new release into that location automatically without much difficulty?

**Comment by laryn** [comment]
It seems this link may already exist:

 - https://github.com/backdrop-ops/backdropcms.org/issues/298#issuecomment-526704480
 - https://github.com/backdrop/backdrop/releases/latest/download/backdrop.zip

**Comment by klonos** [comment]
Hey @serundeputy 👋🏼  🙂  ...if you are around and can spare a moment, can you please see if you can update the quick start example code in https://docs.lando.dev/config/backdrop.html#getting-started or forward this request to someone from the Lando team who has the power to do so?

We need the URL in the `--remote-url https://github.com/backdrop/backdrop/releases/download/1.12.1/backdrop.zip \` bit to be updated to point to https://github.com/backdrop/backdrop/releases/download/latest/backdrop.zip instead of a specific version.

Thanks in advance

**Comment by laryn** [comment]
@klonos @serundeputy FYI I found the link to the repo where those docs are and made a PR:

https://github.com/lando/lando/pull/3103

**Comment by klonos** [comment]
This is not the right queue for this issue though 😅

**Comment by gitressa** [comment]
This was added, and being used in https://docs.lando.dev/backdrop/getting-started.html so closing this issue. Thanks @laryn, @klonos and @reynoldsalec!
