### ISSUE TITLE
Random failures or timeouts in BatchProcessingTestCase

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#5205]
Part of #1478

Sometimes it's a failure, but in GHA it may also happen that it stalls and runs into a timeout without doing anything.

The symptom:

```
 Error: The operation was canceled.
```
The timeout is set to 20 minutes, as no test fraction will ever rightly run that long.
Expanding the "System status" section shows that the processes running the test BatchProcessingTestCase are still there, but the server load is low, so obviously nothing happens.

If the test does not run into a timeout but fails, the message is:

```
Detailed test results
---------------------
Exception Notice     batch_test.callba   95 _batch_test_finished_helper()      

Exception Notice     batch_test.callba   95 _batch_test_finished_helper()      

---- Batch API: Batch processing (BatchProcessingTestCase) ----

Fail      Other      batch.test         103 BatchProcessingTestCase->testBatchF
Fail      Other      batch.test         106 BatchProcessingTestCase->testBatchF
Fail      Other      batch.test         107 BatchProcessingTestCase->testBatchF

Status    Group      Filename          Line Function                            
--------------------------------------------------------------------------------
    Trying to access array offset on value of type bool
    Trying to access array offset on value of type bool
    Batches defined in separate submit handlers performed successfully.
    Execution order was correct, and $form_state is correctly persisted.
    Redirection after batch execution is correct.
```

**Comment by indigoxela** [comment]
Setting "help wanted" label, because I simply can not reproduce the problem locally. If anyone can, please provide steps.

**Comment by indigoxela** [comment]
A solution might be around the corner in [another batch related issue](https://github.com/backdrop/backdrop-issues/issues/4862).

**Comment by quicksketch** [comment]
I'm switching to this issue from over in https://github.com/backdrop/backdrop-issues/issues/4862, because the underlying problem in that issue seems to be Batch API related.

I found that we're having a race condition in Batch operations that seems particularly pronounced in testing. This is because Batch operations in testing have a zero-second delay in between steps. A real browser using JavaScript has a delay between checking for updates and making the next request. See [`BackdropWebTestCase::checkForMetaRefresh()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21simpletest%21backdrop_web_test_case.php/function/BackdropWebTestCase%3A%3AcheckForMetaRefresh/1) for some details about how SimpleTest makes requests for batch operations in the non-JS version.

The specific problem we're having is that Backdrop returns the HTML content of pages (such as the batch page), and then finishes "background processing" on the same PHP thread. This includes things like cron runs, cache writes, and shutdown functions (see [`backdrop_page_footer()`](https://docs.backdropcms.org/api/backdrop/core%21includes%21common.inc/function/backdrop_page_footer/1)). Batch API uses a shutdown function to update the status of the batch. So what can happen here is that the first batch request might get the HTML returned and start requesting the second page in the batch before the first request has finished writing the updated batch information.

As far as I can see, the fix seems really simple: just don't use a shutdown function to update the batch information. I can't see why the shutdown function is needed in the first place, since control always returns back to the batch page callback so that the batch page can be displayed. Perhaps at the time is was considered the "safest" approach, but with background processing that's not the case in Backdrop.

If correct, this should solve at least the following "random" test failures, because the all use batch operations:

* BatchProcessingTestCase
* InstallerBrowserAdministrationTestC
* ConfigurationUITest
* PathPatternBulkUpdateTestCase
* UpdateCoreTestCase

PR at https://github.com/backdrop/backdrop/pull/3735

**Comment by quicksketch** [comment]
> I simply can not reproduce the problem locally. If anyone can, please provide steps.

You can accomplish this by putting a `sleep(5)` in `_batch_shutdown()`. This causes the batch updating to almost always finish after the subsequent page load.

**Comment by quicksketch** [comment]
I re-ran tests on https://github.com/backdrop/backdrop/pull/3735 5 times so far with none of the above tests failing.

**Comment by herbdool** [comment]
I've tested the url alias bulk action and run the automated tests. I'm not getting any regressions so I think this change is safe.

**Comment by quicksketch** [comment]
Thanks @herbdool! I'm going to merge this to hopefully drastically reduce our random failures. Merged https://github.com/backdrop/backdrop/pull/3735 into 1.x and 1.19.x.
