### ISSUE TITLE
Add to Olivero frontend theme to core

### ISSUE THREAD

**Issue by domaingood** [backdrop/backdrop-issues#5242]
Olivero, one of the Drupal core initiatives, seeks to create a new default front-end theme for Drupal with a modern look and feel. This theme is now a part of Drupal 9.1 as an "experimental" theme. We seek to stabilize it and make it the default theme for Drupal 9.2.

Latest Tugboat Preview (running HEAD)
http://lb.cm/olivero

**Comment by indigoxela** [comment]
Olivero is a twig based theme for a totally different CMS, so there's disproportionate effort to migrate it to Backdrop.

**Comment by stpaultim** [comment]
@domaingood - I tend to agree that the purpose of porting a Drupal 8/9 theme to Backdrop is not clear to me. 

If the goals is to add another new quality front end theme to core that is inspired by Olivero, I can see that. But, if we decide to add another front end theme to core, I think we could build a new one or port something from Drupal 7.

**Comment by domaingood** [comment]
@stpaultim backdrop core defult theme basis is old and classic design & need to make new quality front end theme to core that is inspired by Olivero. So, I also link HTML files too. We have to make new better theme with more features also in sort time any devloper can make new sub theme and extand it.It's necessary to make popular CMS and more users in CMS market.

**Comment by klonos** [comment]
I really like the Olivero theme a lot too and find it very modern. ...there's been an enormous amount of work from the Drupal community to build this theme, and we could/should leverage it. Having said that, I agree with @indigoxela and @stpaultim that it seems like a lot of effort to port it, since it is built for D8/9+, using technologies like twig etc.

Here's what I think should happen:
1. Someone or a group of interested people should make the effort to port Olivero to contrib.
2. Once in contrib, we can get metrics of how many sites are using it as their main theme, or as a base theme for their main theme (#5186).
3. If usage stats show a big number of sites/people preferring it, then we could consider either adding it to core (if no better frontend theme has been developed in the meantime), or make it one of the recommended themes (#3193).
