### ISSUE TITLE
Enable telemetry module on new installs (in 1.21.0)

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5253]
This is part of the #5231 meta.

I think that we should tackle the following items here:
- [x] Enable telemetry module on new installs
- [x] Add easy opt-out to disable telemetry module
- [ ] Add Admin Dashboard block to telemetry module

**Comment by docwilmot** [comment]
First PR effort is up. 
Note we need to complete our data collection policy and the PMC needs to formally agree to this before committing to Backdrop.

**Comment by quicksketch** [comment]
The PR looks good. The only big issue is that the link for our policy should go to backdropcms.org/privacy, rather than the philosophy page. I wasn't sure about adding a Dashboard block (or the wording in it), but if we want to add one I think the block in the PR looks fine:

![image](https://user-images.githubusercontent.com/100206/147802624-09dc91e7-26a8-4b79-9ded-5bd9d59c3b82.png)

I was thinking we could explain more about what "Telemetry is enabled" meant, but with previous concerns in #285 about scaring people into turning it off, perhaps that simple statement is sufficient.

**Comment by docwilmot** [comment]
We agreed at todays sprint to remove the block. There is already an entry in the status report that provides the same info. Agreed also to add the links to the policy and the collected data to the status report. PR updated.

**Comment by quicksketch** [comment]
PR looks good to me. I like this more than cluttering the dashboard with a block that doesn't actually report any dynamic data and admins do not need to visit on a regular basis.

**Comment by quicksketch** [comment]
I have merged https://github.com/backdrop/backdrop/pull/3872 into 1.x for 1.21.0! Yay, very simple but a big decision here. Thanks @docwilmot and @klonos for helping move this along!
