### ISSUE TITLE
[UX] Fixed: Export links are shown even when the Configuration Manager module is disabled.

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#5294]
**Description of the bug**

This is a minor issue, but from regular Backdrop user's perspective looks like a bug. When _Configuration Manager_ module is disabled, the Taxonomy page still shows the vocabulary export button pressing which gives no any warning or notice why user can not export.

**Steps To Reproduce**

To reproduce the behavior:
1. Go to /admin/structure/taxonomy > drop down _List Terms_ menu > export:

![export](https://user-images.githubusercontent.com/56604405/136713237-fed96d1e-8749-4a9f-b28f-8678a68dfda8.jpg)

2. just to see:

![export2](https://user-images.githubusercontent.com/56604405/136713255-c88642f8-6031-4ad6-afd6-96cee112879a.jpg)

**Expected behavior**

Depending what the consensus on this will be either export link needs to be disabled (if _Configuration Manager_  is also disabled) or the next page needs to display an explanation to user what's going on and what s/he needs to do to be able to export taxonomy vocabularies.

**Comment by indigoxela** [comment]
Personally, I'd prefer to remove that inoperative link, if the config manager is off. An admin disabled the module by intention (it's on by default), so a hint that "this does not work" feels redundant.

**Comment by BWPanda** [comment]
Here's a PR: https://github.com/backdrop/backdrop/pull/4100

I found a bunch of other places where Export links were only being hidden if the user didn't have the right permission (i.e. ignoring the status of the Config module). So fixed those too.

**Comment by indigoxela** [comment]
@BWPanda many thanks for providing this PR. I did a quick check in the views module, too - but that one already checks for the config module before attaching the links. So this change catches all remaining export links. Works for me. And the code looks good. :+1:

**Comment by argiepiano** [comment]
Wait a moment. Fully uninstalling a module does remove its permissions from its role. So I guess this issue here was posted  for situations when a module (Config) is disabled but not uninstalled In which case the PR makes more sense (though I've seen other situations when the "limbo" state of "disabled but not uninstalled" creates issues with other things - I guess that's why D8/9 doesn't have that limbo state?)

**Comment by argiepiano** [comment]
@indigoxela I don't understand your "fun" comment. Anyway...

Of course I support hiding the link to export. I wish there was a more consistent/organic way to do it. You can find a similar issue with menu items, for example. If you disable but not fully uninstall a module that creates a permission that a menu item use, you'll still see that menu item in the menu.  

But it seems like in this case the PR is the best we can do.

**Comment by indigoxela** [comment]
> I don't understand your "fun" comment.

The "fun" is that user 1 is allowed to do things that don't even exist. :smirk: Isn't it cool to be so powerful?

> it seems like in this case the PR is the best we can do.

I get why it seems a bit odd to you that the module_exists() check is necessary - but it is. And IMO it's no "lame workaround", but the right thing to do.

**Comment by indigoxela** [comment]
Revisiting this issue after a longer pause - it still works for me and the change absolutely makes sense. The code looks good, too. RTBC!

**Comment by kiamlaluno** [comment]
Yes, checking the user has the permission won't work for user #1, since for that account `user_access()` would always return `TRUE`, even for permissions that aren't defined from any module.

The alternatives I could see to verify the module exist are:

- Check the link points to an existing page
- Verify the *synchronize configuration* permission exists

The latter would in practice check something the module defines to verify the module is installed. I would rather verify directly the module exists, which at least won't require to change code when the permission is renamed, or a different permission is used for the link path.
The first would work even when the module name is changed, but it's probably more expensive than verifying the module exists.

**Comment by indigoxela** [comment]
> The first would work even when the module name is changed...

Sure, but I don't think we have to consider that here. Renaming core modules is uncommon - and even if that happened (not withing 1.x I guess) a lot of other things would have to be considered first.

**Comment by klonos** [comment]
FTR, I've just filed #5732 to make sure that permissions exist when we do `user_access()`. This I believe would fix things in the root, without forcing developers to have to do multiple `module_exists()` and the likes to achieve that.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/4100 into 1.x and 1.22.x. Thanks @BWPanda, @indigoxela, @argiepiano, @klonos, @kiamlaluno, and @alanmels!
