### ISSUE TITLE
Naming Convention for template file of a layout

### ISSUE THREAD

**Issue by JugglingCoder** [backdrop/backdrop-issues#5341]
Topic: Naming Convention for template file of a layout.

Although on the "Creating layout templates" page ( https://docs.backdropcms.org/creating-layouts ) it does show an example like " layout--three-three-four-column.tpl.php", an issue caused me a couple hours grief until I figured it out.  The name of my custom layout is 2 words so it is "one_two.info" (folder name also one_two). So naturally I thought the template name should be:
layout--one_two.tpl.php
with an underscore like in the folder and .info file name... BUT, it needs to be a dash like:
layout--one-two.tpl.php

I don't know... this did stump me and block my progress for a few hours so you might want to consider adding a sentence to the documentation about this.

**Comment by klonos** [comment]
Thanks @JugglingCoder for taking the time to report this. Can you please copy/paste things to the documentation issue queue instead of core?: https://github.com/backdrop-ops/docs.backdropcms.org/issues

Unless there are places in core where we should also change something, this issue here should then be closed.

**Comment by BWPanda** [comment]
I've updated the documentation. Closing this issue now. Further changes can be discussed in the docs issue queue.
