### ISSUE TITLE
Project Installer: search for partial words

### ISSUE THREAD

**Issue by Wylbur** [backdrop/backdrop-issues#5344]
**Description of the need**

While using the project installer today, I searched for "dragg", hoping to find the draggable views module.  It came up with an empty list.  

When I searched for draggable, it found the module.  

**Proposed solution**

Can the search function for projects use partial matches.  

**Alternatives that have been considered**

I don't know the mechanics behind this, but it could help people find projects even if they do not have the exact match.  

Not sure if this has been discussed yet, I looked through the issue queue and did not find anything.  

I can help with testing of this, let me know how I could help!

**Comment by olafgrabienski** [comment]
> Not sure if this has been discussed yet, I looked through the issue queue and did not find anything.

If I recall correct, the limited quality of the Project browser search is a known problem, but I couldn't find an open issue either. Then I found at least one [related but closed issue](https://github.com/backdrop/backdrop-issues/issues/2014) which led to an [issue in the backdropcms.org queue](https://github.com/backdrop-ops/backdropcms.org/issues/282). I guess, the latter could help to get information about the 'mechanics'.

**Comment by klonos** [comment]
I had a quick look, and it turns out that the `installer_browser_page()` function (which is responsible for building the list of modules/themes/layouts) calls `installer_browser_fetch_results()`, which basically builds a query and executes a `backdrop_http_request()` against backdropcms.org. So the results returned by the Project Browser are basically the same as the module/theme/layout search in the b.org site.

If you search for "dragg" in b.org, you get no results either: https://backdropcms.org/modules?s=dragg

So I guess that this becomes an issue with the search in b.org rather than an issue with Backdrop core. If we make the project search in b.org return partial matches, then the search within the Project Browser will return partial matches too.

**Comment by klonos** [comment]
...there's an existing issue about reducing the minimum required search length from 3 letters to 2: https://github.com/backdrop-ops/backdropcms.org/issues/803, and there's also this very early meta-issue re improving the search results to provide more info etc.: https://github.com/backdrop-ops/backdropcms.org/issues/95, but there is no issue that I could find re partial word matching.

So, close this issue here and open a new one in https://github.com/backdrop-ops/backdropcms.org instead?

**Comment by stpaultim** [comment]
I also took a look in both queues and could not find an issue specific to this problem, which surprised me because I know that we've talked about it. 

This seems like a relatively important PR issue since recently we've had a number of reports from folks evaluating Backdrop that it's not easy enough to find modules.

**Comment by Wylbur** [comment]
I'll close this issue, and opened a new issue on the queue mentioned by @klonos .  See issue https://github.com/backdrop-ops/backdropcms.org/issues/844 for followup discussion and action!

Thanks everyone!
