### ISSUE TITLE
Improved description for Path field in layout settings

### ISSUE THREAD

**Issue by behindthepage** [backdrop/backdrop-issues#535]
While I was creating the two column flipped layout I tested it out on "node/1" and was a puzzled for a while when entering "node/1" in the Path field didn't work. I thought I had found a bug. 

After a while I realized I needed to put "node/%" here and then add a condition.

This makes sense once you know but is not obvious. I think noobs could struggle with this so I propose a more verbose description.

Something like:

> Enter an existing path which will use this layout or a new path to create a new page. Use the "%" (percent) symbol to indicate a wildcard in the path. i.e. "node/%" or "node/%/edit" or "taxonomy/term/%". If you want a specific node e.g. "node/1" to use this layout then enter "node/%" here and add a "URL path" condition for "node/1".

Regards
Geoff

**Comment by docwilmot** [comment]
A noob did struggle with it indeed: https://github.com/backdrop/backdrop-issues/issues/345#issuecomment-68211679 first bullet point. Never even thought of using a condition, I assumed node/50 would just work. And why not anyway?

**Comment by behindthepage** [comment]
Hi @docwilmot 

There are a few reasons for this:
* If you have different layouts for different nodes they need to be grouped together in the admin page so they can be reordered. Currently they are grouped according to the Path (Field).
* In the condition "URL path" you can add multiple node paths. If you can add a single node path in the Path field then you would need two lots of code to process it. It becomes rather complex very quickly and too much code can have performance issues.
* other issues that we are not aware of

Keep in mind that there are many things needing to be done on Backdrop before it can be released. The aim is to get the main framework done well. Small tweaks like this can be done in the future when the Backdrop community has the time to ponder and debate different possibilities and the pros and cons of each.

Now that you know how it works what do you think would be helpful instructions for this field or page? Any changes to my proposal to make it clearer?

Regards
Geoff

**Comment by quicksketch** [comment]
Agreed this isn't an obvious thing to figure out.

> If you want a specific node e.g. "node/1" to use this layout then enter "node/%" here and add a "URL path" condition for "node/1".

If we tried to describe this situation, we'd probably want to recommend using a Node ID condition, rather than a path condition. I'm not sure path conditions work when the node is aliased (although I think it does).

I'm not sure we want to try and describe this situation in the description text. For in-depth documentation, I feel like we should reference users to stand-alone documentation.

**Comment by docwilmot** [comment]
Thanks @behindthepage.
> we'd probably want to recommend using a Node ID condition, rather than a path condition

I don't see a "Node ID" condition in the list, only URL Path.
> I'm not sure we want to try and describe this situation in the description text

I think we should in this situation. This was the first thing I tried to do, and it seemed very much like a bug to me at the time that I couldnt. We have more verbose advise on the text format tips, why not here? Perhaps bullet points here as well?
> * Enter an existing path which will use this layout or a new path to create a new page.  * Use the "%" (percent) symbol to indicate a wildcard in the path. i.e. "node/%" or "node/%/edit" or "taxonomy/term/%". If you want a specific path (e.g. "node/1") to use this layout then enter "node/%" here and add a "URL path" condition for "node/1".

**Comment by behindthepage** [comment]
I can confirm that using a path condition for "node/X" works if the node is aliased.

@quicksketch were you meaning to add a "Node ID" condition? As @docwilmot said there is only path condition available at the moment. I think just having the path condition is fine as long as people know that is what to use. Would you add another condition for "Taxonomy term IDs"?

I think a lot of people are going to assume node/x will work here and waste time trying it and be annoyed when it doesn't work. Then they will go to the doc page so I prefer a more verbose description or a tool tip style help box. My goal with any software I create is for it not to need extra documentation.

**Comment by quicksketch** [comment]
> @quicksketch were you meaning to add a "Node ID" condition?

Ah, yep sorry I thought there was one. Seems like something we might add in the future. The current conditions were created because they match the old block-based options and were necessary for the upgrade path.

> My goal with any software I create is for it not to need extra documentation.

Yep agreed (as much as that's possible). I'd just like to avoid over-doing the UI with description text that might not apply to the user's needs. I'd like to see is an inline notice when the user enters a path like `node/10` (or any other path that matches context-based paths) and suggest that they should use `node/%` instead, with a path-based condition. We already do an AJAX request on path changes to show available contexts, we could return an additional command with the message if the user entered a path that was intended to override an existing path instead of make a new one.

**Comment by docwilmot** [comment]
Did you have a look at https://github.com/backdrop/backdrop-issues/issues/345#issuecomment-68211679 ? I think the 2nd and last bullet point need attention.

**Comment by quicksketch** [comment]
I filed a PR at https://github.com/backdrop/backdrop/pull/640 to try and solve this problem; plus one from https://github.com/backdrop/backdrop-issues/issues/345#issuecomment-68211679 that is related:

> Should disable the "Create Layout" button till context ajax process is complete. After youve finished typing in the path, the natural reaction is to immediately click the "Create Layout" button because there is no other action to perform on this page. But if you click the button while the ajax is running you sometimes get ajax error about it being terminated (dont recall the exact error message but its the same one you get if you save a view while its generating a preview).

This is fixed, but the button isn't disabled, it's just now allowed to click it even before the AJAX request finishes. In the event of an error, the normal non-JS validation will display a message after reloading the page.

The set of changes is a bit more elaborate than I had originally intended. The AJAX-framework just didn't play nicely with a textfield like this where we're doing actions on keyup because it throttled AJAX requests to be done only one at a time, causing a pretty significant delay between keystrokes. This PR addresses it with the following changes:

- AJAX requests are now allowed to be done asynchronously for the same element (such as the Path textfield).
- All outstanding AJAX requests that are being processed are now exposed in the API, so they can be canceled if no longer needed.
- Even if multiple AJAX requests happen at the same time and are not canceled, ajax.js is now smart enough to ignore multiple responses from the server if they come back in the wrong order. Now only the latest response is processed.
- In the Layout interface, the path field is now validated on keyup instead of on change, which gives the user feedback faster than before.
- And finally, I added the AJAX message that notifies the user if they're defining a new path instead of overriding one like they might be intending. The current message text is:

> The path entered will disable the normal display of a system-provided path. If you intended to add a layout to an existing path, use the path "@new_path" instead of "@old_path".

A nice thing is this message is that it alerts the user when *any* hard-coded path should likely have been replaced with a wildcard one, such as `node/%` but also `node/%/edit` or `comment/%`. This should generally help with situations where knowledge of the menu system is required to determine the correct path. The user is still allowed to enter a hard-coded path if they choose, but the warning should now show up quick enough to alert them.

@behindthepage, even though this wasn't what you're were requesting, could you evaluate it and see if it adequately addresses your concern? @docwilmot if you can review the UX, I'd love to know what you think as well, since you've run into this also.

**Comment by behindthepage** [comment]
This is a good solution but I think the message above is a bit confusing, so I would use something like this:
>The path entered will create a new page and disable the current "@old_path". If you intended to add a layout for "@old_path", use the path "@new_path" and add a URL path condition for "@old_path".

**Comment by docwilmot** [comment]
> If someones enters "node/1" in the path field without any other fields filled in they get the 3 errors about the Layout name field, Machine-readable name field, and Layout field being required and the warning about "node/1" is not shown.

apart from this, works as advertised. well done again. can fine-tune later.

**Comment by quicksketch** [comment]
Thanks @docwilmot! We still have this in https://github.com/backdrop/backdrop-issues/issues/345#issuecomment-68211679 so we may be able to tackle it later. Thanks again for reviewing!

**Comment by docwilmot** [comment]
@quicksketch was there anything in these changes that should require a change notice?

**Comment by quicksketch** [comment]
Hm, yes actually. It's possible that some implementations of #ajax properties could be affected by this (but it wouldn't be common).

Because multiple AJAX requests can now be done asynchronously, it's possible to end up with multiple progress throbbers added to the page at the same time. Fortunately, by default elements are marked disabled while an AJAX event is occurring, so this would prevent multiple requests. The option to leave an element enabled during an AJAX event was added to Backdrop and doesn't exist in D7, so very little ported code would be affected, but it's worth noting.

If you previously had this code, multiple AJAX requests would be throttled to only allow one at a time:
```php
$form['my_button'] = array(
  '#type' => 'submit',
  '#title' => t('Update via AJAX'),
  '#ajax' => array(
    'callback' => 'my_ajax_response_function',
    'disable' => FALSE, // Defaults to TRUE.
  ),
);
```

If you need to throttle the requests, you can either omit the "disable" line or set it to TRUE.
```php
$form['my_button'] = array(
  '#type' => 'submit',
  '#title' => t('Update via AJAX'),
  '#ajax' => array(
    'callback' => 'my_ajax_response_function',
    'disable' => TRUE,
  ),
);
```

Or, if you *want* multiple AJAX requests to be allowed at the same time, you might leave the button enabled and disable the throbber (otherwise you'll end up with multiple throbbers, one for each request):
```php
$form['my_button'] = array(
  '#type' => 'submit',
  '#title' => t('Update via AJAX'),
  '#ajax' => array(
    'callback' => 'my_ajax_response_function',
    'disable' => FALSE,
    'throbber' => FALSE,
  ),
);
```
