### ISSUE TITLE
Field name is blank in error message "__ field is required" when a required field set to 2 or more

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#5377]
## Description of the bug

The field name is not shown in the error message for a required field if it is set to unlimited.

## Steps To Reproduce

To reproduce the behavior:
1. Create a text field on a "page" content type.
2. Set it to Required and to Unlimited (or even just 2).
3. Add a page and attempt to save without filling in fields.

## Actual behavior

![Screenshot from 2021-11-29 17-18-43](https://user-images.githubusercontent.com/1071483/143953490-954181ef-1be0-4235-92e1-be924f89f17d.png)
![Screenshot from 2021-11-29 17-19-30](https://user-images.githubusercontent.com/1071483/143953493-1dbe6884-f3d4-4e86-8da4-8c1e8d9aa78d.png)

## Expected behavior

Field name should be displayed (as it is if the field is set to 1).

**Comment by argiepiano** [comment]
It took a couple of hours, but I have discovered the source of the problem. The values for keys `#title` and `#description` are left empty in the deepest level of the element array. 

This means that, in the $form structure, the following element is empty:

`$form['field_name']['und'][0]['#title']`

This happens in [line 217](https://github.com/backdrop/backdrop/blob/b2690394c575ffe659186a6a818dba93da418f6e/core/modules/field/field.form.inc#L217) of `field.form.inc`:

```php
        '#title' => $multiple ? '' : $title,
```

This inline if does not exist in its Drupal equivalent. In fact, Drupal sets the `#title` value in ALL levels of the form array.

This value is unfortunately needed in the validation function that creates the error. See [line 1477](https://github.com/backdrop/backdrop/blob/b2690394c575ffe659186a6a818dba93da418f6e/core/includes/form.inc#L1477) in `form.inc`.  

The most straightforward solution might be to modify line 217 in `field.form.inc` above, BUT this may break other stuff. I haven't had the time to investigate all possible issues. If anyone has any idea why that shorthand if/else statement was added there, maybe we can safely remove that.

Otherwise the other possible solution is to somehow modify `form.inc` to get the element title from the parent element of the array?

**Comment by argiepiano** [comment]
I've verified that changing line 217 of `field.form.inc` to:

```php
'#title' => $title,
``` 

solves the issue of the validation error leaving the name of the field blank, BUT now the widget displays the title twice: 

<img width="385" alt="Screen Shot 2021-11-29 at 9 01 08 PM" src="https://user-images.githubusercontent.com/9938978/143983631-d31bcde7-8810-4c94-8038-dbdcf7ba0528.png">

Any thoughts?

**Comment by laryn** [comment]
Here's a D7 issue of interest:

 - https://www.drupal.org/project/drupal/issues/980144

**Comment by argiepiano** [comment]
> Here's a D7 issue of interest:
https://www.drupal.org/project/drupal/issues/980144

@laryn yes. I see that, in the [patch there](https://github.com/backdrop/backdrop-issues/issues/5377#issuecomment-982263527), the equivalent of line 217 was changed  to what I proposed above. But in Drupal they managed to avoid double-printing the title of the field.

**Comment by argiepiano** [comment]
I have created a PR (https://github.com/backdrop/backdrop/pull/3837) for this that includes the code used in D7 to solve a similar issue. In addition to solving the validation problem, this patch also makes the "floating red asterisk" seen in the snapshot attached by @herbdool invisible.

**Comment by laryn** [comment]
@argiepiano Thanks! I'll try to review this one soon, too. Your sleuthing (and then the "git blame" feature on the corresponding line in the Drupal repo) led me to the issue linked above. Thanks for tracking that down!

**Comment by argiepiano** [comment]
Thank YOU, Laryn! Knowing about that Drupal issue made the fix a breeze :)

**Comment by herbdool** [comment]
Thanks @argiepiano! I didn't expect a quick fix.

It works fine, but I set it to needs work because I think it would be good to copy the automated test over as well. Need test coverage where we can get it.

**Comment by argiepiano** [comment]
@herbdool I have an additional commit to my PR that includes an adapted version of the Drupal 7 test that checks that the asterisk is only visible on the table header, and that it's not shown in the individual elements. This test is inside is Field API -> Field form tests, and is passing in my local environment (but there are other field tests that are not, which are unrelated to this issue).

I guess we need an additional test that checks that the validation error shows the full name of the field? I could take a stab at that later, although my experience with the testing environment is pretty limited. 

Screenshot of the two new tests that I added: 

<img width="1151" alt="Screen Shot 2021-11-30 at 9 06 11 AM" src="https://user-images.githubusercontent.com/9938978/144086064-65745850-9d1d-47f4-934f-30d04347e048.png">

**Comment by argiepiano** [comment]
I have added a new test that checks for the correct text in the validation error. The test is passing. I believe this is ready for code review. 

<img width="1106" alt="Screen Shot 2021-11-30 at 6 56 08 PM" src="https://user-images.githubusercontent.com/9938978/144158580-10510841-ac1a-4672-be3f-1d39ada8f175.png">

**Comment by herbdool** [comment]
Test looks like it does the job. Thanks @argiepiano I've marked it ready.

**Comment by klonos** [comment]
Don't want to block this fix for the sake of nit-picking, but I've left a comment in the PR re the order of replacement variables in the `t()` function for your consideration consideration. Fix ing that shouldn't interfere with the functionality nor require further code review.

**Comment by argiepiano** [comment]
> Don't want to block this fix for the sake of nit-picking, but I've left a comment in the PR re the order of replacement variables in the `t()` function for your consideration. Fixing that shouldn't interfere with the functionality nor require further code review.

Thanks @klonos . Committed

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/3837 into 1.x and 1.20.x. Great work folks!
