### ISSUE TITLE
Currently no way to create a custom layout for node/add pages

### ISSUE THREAD

**Issue by stpaultim** [backdrop/backdrop-issues#5395]
## Description of the bug

While testing this PR https://github.com/backdrop/backdrop-issues/issues/4689, I ran into a problem that might be a bug or is more likely me overlooking something. 

There is enough going on in this scenario, that I may be missing a necessary permission or more likely have a misunderstanding about the correct layout path setting. Looking for help understanding this.

## Steps To Reproduce

To reproduce the behavior:
1) Spin up a fresh site and give authenticated users the ability to create and edit posts.
2) Create a special layout with the following configuration. 
  a- Path = node/%
  b- Visibility Rule: Current path is node/add/post
3) Add a custom block to your new custom layout for node/add/post
4) Login as an authenticated user and visit node/add/post 

## Actual behavior

If you follow the above steps, you will NOT see your new custom block on the node/add/post page.

## Expected behavior

I expected that an authenticated user would use the new custom layout when editing a POST and that I would see my custom block when logged in as an authenticated user viewing node/add/post.

## Additional information

Here is a screenshot of my configuration for custom layout. 

![image](https://user-images.githubusercontent.com/3144571/145731595-27b4c0c9-b07a-490f-a22d-5aa52d6cf5fc.png)

**Comment by bugfolder** [comment]
I don't think this is a bug; it's "working as expected."

Your new layout will show up on pages with paths of the form "node/%" where "%" is filled in with a node ID. The path "node/add/post" doesn't qualify because (a) it has 3 parts, not 2, and (b) "add" is not a node ID. So the layout won't apply on this page.

There is a contrib solution to accomplish what you want, though. The [Layout Wildcard](https://backdropcms.org/project/layout_wildcard) module would let you add the alternative path "node/add/post" to your layout, and then it would be applied there as well as to node pages. (At least, if the module is working properly. 😉)

**Comment by stpaultim** [comment]
Well, I did assume that my expectation for the path might be incorrect. So, this kinda makes sense. 

I'm inclined to leave this issue open a bit longer to see if anyone else thinks that my inability to create a custom layout for node/add or node/edit pages is a bug or legitimate feature request. 

Actually, I suspect that there are already issues in progress that might solve this. If anyone thinks this is actually a duplicate feature request, please feel free to link to the active issue and close this one.

**Comment by bugfolder** [comment]
You can create a layout that works for node/add/post; it just needs to be a different layout from the one that works for node/%. But you can put your custom block in both layouts.

There is a pending PR that is related; not sure if it would allow addressing both of those paths with the same layout. It's https://github.com/backdrop/backdrop-issues/issues/1602.

There is an issue that path node/% will have a context that is the node whose ID is given by the % placeholder value, and so blocks within that layout might rely on that context; but trying to use that layout on path node/add/post, there would be no node, so no context, so that could break custom blocks that relied on that context.

**Comment by stpaultim** [comment]
OK, I've not given up yet. :-)

Why doesn't this layout work for node/3/edit?

It is an actual node page with the node context?

![image](https://user-images.githubusercontent.com/3144571/145733110-806e2673-17cb-44fa-9224-62a4738c45a0.png)

**Comment by bugfolder** [comment]
Because you would need the layout path to be "node/%/edit" for the layout to be applied to "node/3/edit".

From the standpoint of layout path matching, "node/%" and "node/%/edit" are different paths.

**Comment by stpaultim** [comment]
> Because you would need the layout path to be "node/%/edit" for the layout to be applied to "node/3/edit".

Thanks, that worked. @bugfolder

**Comment by stpaultim** [comment]
OK, I'm confident that this entire issue was based upon my own confusion about that path setting and that there are sufficient issues already open regarding related issues/feature requests. I'm going to close this one.
