### ISSUE TITLE
Offset warning in form.inc when adding new content type.

### ISSUE THREAD

**Issue by jadamsbit** [backdrop/backdrop-issues#5410]
## Description of the bug

A short description of what the problem is.
When adding a new content type there is a warning for illegal offset.

Warning: Illegal offset type in form_type_checkboxes_value() (line 2444 of "Project"/core/includes/form.inc)

## Steps To Reproduce

To reproduce the behavior:
1. Go to "/admin/structure/types/add" fill out info for new content type then submit.
2. Go to "/admin/reports/dblog" and there is a new warning in the logs.

Add any other information that could help, such as:
- Backdrop CMS version: backdrop 1.20.3

![Screen Shot 2021-12-20 at 11 00 15 AM](https://user-images.githubusercontent.com/11961498/146796695-0cd26bba-abc7-4ff5-9098-3994754b3ad7.png)

**Comment by indigoxela** [comment]
Hi @jadamsbit,

welcome to Backdrop and many thanks for taking the time to report.

As I never see this error, we probably need a little more info about your setup, like:

- Your PHP version (from the status page /admin/reports/status
- A list of contrib modules you installed
- Maybe a list of enabled core modules, if you enabled some that aren't on by default

**Comment by jadamsbit** [comment]
PHP Version: 7.4.21

block
ckeditor
color
comment
config
dashboard
date
email
entity
feeds_import
feeds_tamper
feeds_tamper_ui
feeds_ui
field
field_group
field_sql_storage
field_ui
file
filter
image
installer
job_scheduler
link
list
menu
node
node_reference
node_revision_history
number
options
path
references
search
system
taxonomy
text
update
user
user_reference
views_ui
auto_nodetitle
simplify
views
contextual
layout
admin_bar
standard
dblog
feeds
redirect
syslog

@indigoxela Above is the full list of installed modules and the PHP version.

**Comment by argiepiano** [comment]
@jadamsbit this is an unusual warning that I'm not able to reproduce. My guess is that it has to do with one of the contrib modules you have enabled (there may be a bug in one of them).

To help us debug this, you can either start by disabling contrib modules until the error is not shown, or you  try the following:
- Tell Backdrop to show all errors by going to admin/config/development/logging and selecting "All messages"
- Install devel and enable it
- After installing go to admin/config/development/devel and select "Error handlers: Krumo backtrace in message area".
- Then try to reproduce the error. This time you'll see a Krumo output with a backtrace. That should allow you to backtrace all the function calls up until the error/notice, and should help us see what's causing it

(The backtrace will make the webpage slow to load.)

**Comment by klonos** [comment]
Hello @jadamsbit ...I wanted to follow up and see if you managed to get to the bottom of this, and if there's anything we can do to help. Unfortunately, we cannot reproduce the problem on our end, which makes it hard to fix.

I would like to what @argiepiano suggested above: if you cannot disable modules one by one until you trace which one is causing issues because you are working on a live site, then it may help if you set up a clone of your site on your local computer and try that there. If you need help with that, let us know.

Another thing that I would like to suggest is to join us tomorrow in our "Office Hours", which is a live zoom session where Backdrop people gather to discuss various topics and help each other with such issues. This meeting is on Wednesdays from 9pm-11pm UTC. Here's the details for the next one: https://backdropcms.org/news/events/office-hours-2

**Comment by jadamsbit** [comment]
I think I was able to figure out the issue. It went away when I disabled one of the devel modules.

**Comment by jadamsbit** [comment]
Thank you for following up with me.
