### ISSUE TITLE
Document that the `cancel-url` and `one-time-login-url` user tokens only work when sending out the admin notification emails

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#5445]
## Description of the bug

The tokens `cancel-url`  and `one-time-login-url` are listed under `['tokens']['user']` in the tokens array produced by `entity_get_tokens()`, yet these 2 tokens don't work.

## Steps To Reproduce
Try the following in Devel:

```php
$user = user_load(1);
$text = array(
  '[user:one-time-login-url]',
  '[user:cancel-url]',
);

foreach ($text as $t) {
  dpm(token_replace($t, array('user' => $user)), $t);
}
```

## Actual behavior
The output of the above shows that these two tokens are never replaced with the correct values.

## Expected behavior
The code above should output the one-time login URL and the account cancellation URL of the user.

## Additional information
The code for these replacements should have been included in `user_tokens()`. This should is a fairly simple fix.

**Comment by indigoxela** [comment]
> The output of the above shows that these two tokens are never replaced with the correct values.

This is not completely true, though. The account emails, for instance, also use `[user:one-time-login-url]` and the token works fine there.

@argiepiano there's a reason why these tokens aren't fully exposed, but only provided by function user_mail_tokens(): these urls are considered "dangerous".

Maybe this [Drupal issue](https://www.drupal.org/project/drupal/issues/554088) explains it better:

```
That will ensure that those two tokens are available *just when the system is sending out its official admin notification emails*, and not at any other time.
```

So IMO this is not a bug, but a security feature. :wink:

**Comment by argiepiano** [comment]
That's great @indigoxela! Thanks for the clarification. Makes sense. I will close this issue now.

**Comment by klonos** [comment]
@argiepiano / @indigoxela do you think that it is worth adding some description to these tokens, so that the next person that comes across this doesn't wonder the same. Something like this perhaps?:

![image](https://user-images.githubusercontent.com/2423362/148806773-8b1b2d95-63cd-4a0e-9250-0b6d41168364.png)

...and/or some inline comment in the code too?

**Comment by klonos** [comment]
Thanks @argiepiano 👍🏼

**Comment by argiepiano** [comment]
PR https://github.com/backdrop/backdrop/pull/3902

**Comment by klonos** [comment]
Thank you @argiepiano 🙏🏼  ...code looks good, and it works for me:

![image](https://user-images.githubusercontent.com/2423362/148860242-2b387908-bd11-466b-ae8b-d28849d8b332.png)

The in-code comments help anyone who's looking at the code, but not sure if anyone would expand the "more" link to see the notice. If we want a "there's a notice for that" approach to this, then that is fine - if we want to avoid people opening new issues or forum topics asking why "the tokens don't work" though (because they didn't bother reading the help text for the tokens), then we should be making the notice more obvious I think.

**Comment by argiepiano** [comment]
Thanks, @klonos . 

> we should be making the notice more obvious I think.

What do you suggest to make the notice more obvious?

**Comment by indigoxela** [comment]
> we should be making the notice more obvious I think.

Actually, for me the info already works as-is. I never tried to use these two tokens anywhere outside the account mails, but if I did and then realized that they're not working as expected, the token browser help text would be the first thing to check - in case I didn't bother to expand and read in the first place.

The inline comments in function user_token_info() are a good addition, too.

**Comment by klonos** [comment]
> Actually, for me the info already works as-is.

For me too, that's why I've set the issue to RTBC ...but I was thinking that we can improve the UX a bit...

Currently:
- If a person is looking at the code, they'll see the inline comments, so that's fine 👍🏼 
- If a person is adding the tokens via the token browser popup, they may add them somewhere, see that things aren't working, and they will scratch their head, try to troubleshoot/investigate, in general waste time 👎🏼  ...they might or might not think to expand the "more" link and read the help text.

Now, if we drew their attention **_before_** they add the tokens somewhere that won't work, we save them time. Something like this would work I think:
<img width=50% src="https://user-images.githubusercontent.com/2423362/149047796-c8960b6d-d2e5-40ea-bd87-6a6b2c1576fd.png">
The asterisks will make sure that people are aware that these tokens have something special about them. They are then more likely to expand the "more" link and read the help text, and the asterisk and bolded "Note" text will actually draw their attention to what is the special thing.

But as I said, I'm happy with the PR as is if you think that all that is not necessary 👍🏼 

PS: @argiepiano the comments added are going beyond the 80 character limit. Once that's fixed this is truly RTBC 😉

**Comment by argiepiano** [comment]
Fixed!

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/3902 into 1.x and 1.20.x. Great nice little fix @argiepiano! Thanks @indigoxela and @klonos for reviewing!

**Comment by jenlampton** [comment]
I found an issue with the new description text (we called people "users") so I've filed a follow-up PR: https://github.com/backdrop/backdrop-issues/issues/5459

I'd like to get that in before translations start getting updated, so I've slated it for 1.21.1.

**Comment by klonos** [comment]
How could I miss that 🤦🏼  ...RTBC 👍🏼
