### ISSUE TITLE
Misleading/obsolete function description for theme_html_tag()

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5452]
The change record in https://docs.backdropcms.org/change-records/themehtmltag-becomes-themeheadtag states:

> The function `theme_html_tag()` has been renamed [`theme_head_tag()`](https://docs.backdropcms.org/api/backdrop/core%21includes%21theme.inc/function/theme_head_tag/1), and as such, should only be used for adding HTML tags within the `<head>` tag on the page.

But https://docs.backdropcms.org/api/backdrop/core%21includes%21theme.inc/function/theme_head_tag/1 still says:

> Returns HTML for a generic HTML tag with attributes.

**Comment by klonos** [comment]
...well, the function still does the same thing as it used to - we are not enforcing the tags to be added to `<head>` in any way. So the `Returns HTML for a generic HTML tag with attributes.` still applies I guess.

Here's a PR that adds a note about intended use + also an `@since 1.0.0`: https://github.com/backdrop/backdrop/pull/3907

**Comment by indigoxela** [comment]
You want the functionality but fix the comment? #3892

The function does not do what the name implies, but does what the comment currently states "Returns HTML for a generic HTML tag with attributes."

Are you sure, you fix the right problem? This might even increase the confusion, no?

**Comment by jenlampton** [comment]
@klonos  documentation update looks good, and matches what I see on [`theme_head_tag()`](https://docs.backdropcms.org/api/backdrop/core%21includes%21theme.inc/function/theme_head_tag/1). RTBC.

> This might even increase the confusion, no?

I don't think this will increase confusion because it now includes recommendations of we hope people will be doing with it. We don't specifically state it can't do anything else, but the description at least matches the name.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/3907 into 1.x and 1.20.x. Thanks!
