### ISSUE TITLE
PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table variable doesn't exist

### ISSUE THREAD

**Issue by djzwerg** [backdrop/backdrop-issues#5495]
## Description of the bug

After running the update script to upgrade a Drupal website an error like this occurs:

`PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table variable doesn't exist: SELECT name, value FROM variable WHERE name LIKE 'authorize_filetransfer_connection_settings_%'; Array ( ) in system_update_1018() (line 1973 of system.install`

## Steps To Reproduce

To reproduce the behavior:
1. Upgrade a Drupal 7 website as described at [docs](https://docs.backdropcms.org/documentation/upgrading-from-drupal-7-1)

## Expected behavior

Changing line 1973 from system.install file (core/modules/system/system.install) from

`$settings = db_query("SELECT name, value FROM variable WHERE name LIKE 'authorize_filetransfer_connection_settings_%'");`

to

`$settings = db_query("SELECT name, value FROM {variable} WHERE name LIKE 'authorize_filetransfer_connection_settings_%'");`

solves this issue (minor code fixes).

**Comment by klonos** [comment]
Hello @djzwerg and thank you for taking the time to report this issue 🙏🏼 

> Changing line 1973 from system.install file...

Thanks for figuring that out, but I find it rather odd that we didn't have any previous reports of this. Can you please let us know which exact version of D7 you've been trying to upgrade from, and to which exact version of Backdrop? (shouldn't really matter, but I'd like to test a couple of things)

**Comment by indigoxela** [comment]
> SELECT name, value FROM variable WHERE...

Nice catch! `{variable}` would have been correct. @djzwerg mind to file a pull request?

> I find it rather odd that we didn't have any previous reports of this

@klonos it might be that it previously worked, but after some changes (like adding MySQL 8 support), this isn't tolerated anymore. I didn't dig deeper, though.

**Comment by djzwerg** [comment]
@klonos thanks for your reply. The facts:
- PHP 7.3
- MySQL 8.0.25
- source: Drupal 7.87
- destination: Backdrop 1.21.1

**Comment by indigoxela** [comment]
> The facts:... MySQL 8

Yes, that one can be a picky princess. :laughing:

Anyway, escaping with curly brackets is the correct way doing it in db_query().

**Comment by djzwerg** [comment]
@indigoxela I've tried but I have no access rights to make a PR.

**Comment by indigoxela** [comment]
> I've tried but I have no access rights to make a PR.

I'll try to guide you through the process as good as I can.

I don't see a forked backdrop repo on your Github account, so I'm assuming, you cloned the main repo - and for that you have no push access (only core committers can do that). Instead of cloning the main repo, you should create a fork:

1. Fork backdrop to your account via Github UI: that's on the top-right corner of https://github.com/backdrop/backdrop
2. Clone that fork to your local environment
3. Create a branch for your fix and switch to that branch
4. Do changes in that branch, commit and push (your IDE should guide you)
5. If done via command line, you'll get instructions (a link) how to open a PR
6. Otherwise you can go to your own fork's page on Github and start from there

If you have additional questions, come to the Zulip chat. People might come with better instructions. (My explanations tend to be more complicated than necessary.)

**Comment by djzwerg** [comment]
Thanks @indigoxela. I made a PR :-)

**Comment by klonos** [comment]
Thank you @djzwerg but you need to file the PR against the main backdrop repo ...you did it against your own fork though 😅  ...no worries though ...another way to do that (since this is a simple one-line change) would be as described here: https://backdropcms.org/news/creating-pull-requests-against-core-the-easy-noob-way

**Comment by klonos** [comment]
...oh, I see that you did file another PR then. Right 👍🏼

**Comment by klonos** [comment]
...code looks good, but haven't tested it yet.

**Comment by djzwerg** [comment]
@klonos now I'm confused 😅 The code did work in a second upgrade case but on the same server.

**Comment by indigoxela** [comment]
> now I'm confused sweat_smile The code did work in a second upgrade case but on the same server.

@djzwerg he mentioned testing, because that's part of our usual process - someone tests, someone reviews, someone else merges.

I took over the "testing" task here, but have to admit, that I don't have MySQL8 installed locally.

My setup: PHP 7.4, MariaDB 10.5

I started with a quick-and-dirty Drupal 7 setup, some common contrib modules, core version 7.87 and created some content (article / page).

- Setup a fresh Backdrop with your code change in another vhost
- Dropped this database, re-created it (so it's completely empty)
- Imported the Drupal database into that
- Went to core/update.php (again after setting update_free_access :wink:)
- In my case over 200 updates needed to run
- And a second run
- And then the utf8mb4 conversion

Success, content is there, no related PDOException.

Based on the fact that the change is small, I take the liberty to RTBC it. @klonos is that also OK for you?

**Comment by klonos** [comment]
@indigoxela since I've added the milestone label, I cannot add the actual milestone for this. Can you please do it instead? Thanks.

**Comment by klonos** [comment]
> I took over the "testing" task here, but have to admit, that I don't have MySQL8 installed locally.

I can set up MySQL v8 on my local using Lando. I'll do that and report back.

PS: thanks @indigoxela for providing exact steps 🙏🏼

**Comment by quicksketch** [comment]
Thank you @djzwerg, @indigoxela, and @klonos! I merged https://github.com/backdrop/backdrop/pull/3947 into 1.x and 1.21.x.

**Comment by indigoxela** [comment]
@djzwerg this probably has been your first core contribution. Congrats! :1st_place_medal:

**Comment by djzwerg** [comment]
@indigoxela thanks! But this was just a very small contribution ;-)

**Comment by klonos** [comment]
Every contribution regardless of "size" and type always counts and is appreciated in our community @djzwerg
