### ISSUE TITLE
Be consistent with the style of details summaries and fieldset legends

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5509]
While working on #5503, I noticed that fieldset legends have `text-decoration` on hover, while the summary link on `<details>` has no underline on hover.

We should be consistent with this, so either remove the underline from fieldsets, or add it to details.

* `<fieldset>` element: See "Administration" (or any other project group) on the page at `admin/modules/list` uses http://backdrop.local/core/themes/seven/css/style.css (approx line 723?)
* `<details>` element: See "How layouts work" at the top of the page at `admin/structure/layouts` uses http://backdrop.local/core/modules/system/css/system.theme.css (approx line 15)

Proposed solution:
* remove the underline from fieldset `<legend> <a>`  (on hover) to more closely match `<details>` styling.

**Comment by a-tanvi** [comment]
Hey ! Can i take on this issue ?

**Comment by stpaultim** [comment]
@a-tanvi - You should feel free to work on this issue. Post questions here is you need help. 

Start by reading this blog post: https://backdropcms.org/news/openforce-2022-getting-started

**Comment by a-tanvi** [comment]
Thank you! I can't seem to find the right CSS files please help me with it.

**Comment by stpaultim** [comment]
@klonos - I tried to help out here, but I'm not actually sure what you are talking about. 

Can you (or someone) provide a specific example of:
1) fieldset legend with "Text Decoration"
2) Summary Link on <details>

**Comment by bugfolder** [comment]
Hi @a-tanvi (and @stpaultim), here's examples of both:

* `<fieldset>` element: See "Administration" (or any other project group) on the page at `admin/modules/list`
* `<details>` element: See "How layouts work" at the top of the page at `admin/structure/layouts`

**Comment by stpaultim** [comment]
@a-tanvi - Any questions?
We have office hours this week, if you need help: [backdropcms.org/news/events/office-hours-2](https://backdropcms.org/news/events/office-hours-2)

**Comment by stpaultim** [comment]
@a-tanvi - I've removed your assignment, but feel free to let us know if you want to keep working on this. Please ask us if you need help. In the meantime, anyone can work on this.

**Comment by BWPanda** [comment]
Also, the arrows are different...

**Comment by RakeshPotnuru** [comment]
@klonos 
I am working on this.

**Comment by stpaultim** [comment]
@RakeshPotnuru - Actually, for both fieldsets and details the item just hides or exposes content, in neither case is it a link to another page, so I don't think we should treat them as links. 

I think we should remove the link from fieldsets. 

To demonstrate @RakeshPotnuru - see the example provided by @bugfolder. admin/modules/list - these fieldset labels do not link anywhere, they just open and close accordions. But, they have an underline as if they are a link.

![image](https://user-images.githubusercontent.com/3144571/159846727-96bb2923-40f7-4d6b-ae25-d294ce105474.png)

**Comment by RakeshPotnuru** [comment]
Okay, I will remove underline then.

**Comment by stpaultim** [comment]
@RakeshPotnuru - This is look pretty good. At first glance, it seemed like quite a bit of CSS for a small change, but it seems that most of the items are necessary. But, I'm not sure if the `width: 0; and height:0;` are doing anything.

**Comment by RakeshPotnuru** [comment]
I hope I placed CSS in right place.

**Comment by stpaultim** [comment]
@RakeshPotnuru - In fact, I don't think that the new CSS is in the right place. Sorry for not noticing this earlier. You have added it to the Layout module in Backdrop core, which would make sense if this were only for the layout page: /admin/structure/layouts

However, I believe that the request for this issue was to make "Details Summaries" in general consistent with fieldset legends. For this issue, we only have the one example of "details summaries" in the layout module. But, I believe that they could happen anywhere in core. 

The more appropriate location for this CSS is probably in the Seven admin theme. Since these are to be the equivalent of a fieldset legend, I would put this CSS in the same location where that CSS is. 

/core/themes/seven/css/style.css

Maybe here?

![image](https://user-images.githubusercontent.com/3144571/160332154-91abd6ff-d23e-4397-a97c-7aa4b73fc521.png)

I would love someone smarter than me to offer their opinion on this:

@indigoxela, @BWPanda, @jenlampton or @klonos ?

**Comment by jenlampton** [comment]
I agree, we shouldn't be adding any new CSS to the layout module. In fact, I don't think we need to add any CSS for details at all. Since we are happy with the details style, and only want to remove the underline from the link for fieldset, I think the only change that is necessary is the one in [core/themes/seven/css/style.css](https://github.com/backdrop/backdrop/pull/4021/files#diff-e376e77e7a112390744d75e640cc24b43108cea9c527cfcde90290cc705d7a90).

**Comment by stpaultim** [comment]
@RakeshPotnuru - are you still available to work on this PR?

**Comment by RakeshPotnuru** [comment]
@stpaultim 
Yeah, sure

**Comment by RakeshPotnuru** [comment]
Okay, I removed CSS for details.

**Comment by herbdool** [comment]
The PR's repo was deleleted but the change was small:

```
diff --git a/core/themes/seven/css/style.css b/core/themes/seven/css/style.css
index 16b0c91bb91..411163a6b4b 100644
--- a/core/themes/seven/css/style.css
+++ b/core/themes/seven/css/style.css
@@ -753,6 +753,9 @@ fieldset .fieldset-wrapper::before {
   right: .6em;
 }
 
+.fieldset-legend a:hover {
+  text-decoration: none;
+}
 .fieldset-legend span.summary {
   position: absolute;
   top: .4em;
```

**Comment by stpaultim** [comment]
Marking this "Works for Me."

**Comment by jenlampton** [comment]
I've Reviewed the code change, marking as RTBC. @stpaultim I'm also sure you could have reviewed this code change and added the RTBC label if you wanted.

**Comment by stpaultim** [comment]
> @stpaultim I'm also sure you could have reviewed this code change and added the RTBC label if you wanted.

Your right, I should have. There aren't too many code reviews I feel comfortable with, but I think I could have handled this one.

**Comment by quicksketch** [comment]
Thanks folks! I merged https://github.com/backdrop/backdrop/pull/4660 into 1.x and 1.27.x.
