### ISSUE TITLE
How best to use Drush to update/manage Backdrop websites?

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#553]
I love the fact that I can run `drush up drupal` to update my websites' Drupal installation without having to manually download and unpack the new version then copy all my sites over to it.

As it looks like Drush won't be available for Backdrop, I'm wondering how best to do this with Git...

From what I understand, I can setup Backdrop by cloning from git, then checkout the '1.0.0-preview' tag (`git checkout 1.0.0-preview`). I can setup my website(s), then, when '1.0.0' is released, I can update to the '1.0.0' tag from the '1.0.0-preview' tag (not quite sure how yet; `git pull` or `git fetch`?).

Is this the best way to do it? Note that this is referring specifically to running live, client websites; not development/testing sites that will be making changes to Backdrop and creating pull requests.

**Comment by quicksketch** [comment]
This would be a little tough if your code was already managed by a separate Git repository. Git is not very good at pulling code from multiple places, which would be the case if you kept your code (including contrib and custom modules) in one repo but were pulling from the main Backdrop repo. Git has the concept of submodules, but it's really, really messy in my experience.

We'll get drush support eventually I think, but in the mean time, I'd probably recommend doing the steps manually of downloading the new zip, deleting the "core" directory, and replacing it with the new "core" directory. You shouldn't ever need to modify any other files.

**Comment by jenlampton** [comment]
Drush++

**Comment by dboulet** [comment]
Drush = Drupal Shell
Backdrop Shell = ?

Backdrosh?

**Comment by klonos** [comment]
...or bush for short.

**Comment by BWPanda** [comment]
> Drush = Drupal Shell
Backdrop Shell = ?

I heard someone once suggest 'Bash', but that's obviously not appropriate :smile:

**Comment by jenlampton** [comment]
Let's stick with drush :)

**Comment by omega8cc** [comment]
We are working really hard to convince our Drush 7 fork to work with Backdrop CMS, so we could provision Backdrop CMS sites in Aegir.

So far we can add Backdrop CMS as a platform in Aegir and even trick Drush and Aegir to create a site with proper configuration files, vhost etc, just without properly provisioned db credentials, because there is still a problem caused by differences in bootstrap phases (I think).

If we will get the provisioning working, then you should be able to use Drush Make with Backdrop CMS as well.

We need a working Drush Make and not Git to manage codebases! Git is good to manage code on the module or theme (or core) level, not to manage the complete codebase with contrib added.

**Comment by jenlampton** [comment]
@omega8cc that is amazing, please let us know if any code changes are necessary for backdrop.

**Comment by BWPanda** [comment]
I think this can be closed now that Drush for Backdrop exists: https://github.com/backdrop-contrib/drush
