### ISSUE TITLE
[UX] Provide details about why a permission 'has security implications'.

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#5536]
## Description of the need

When I see that a certain permission "has security implications", I wonder what those implications are, and how much they'll affect my site/users...

## Proposed solution

I'd like to propose allowing developers to write an additional description for permissions that describe what the security implications are.

## Alternatives that have been considered

Backdrop already has this ability, with the `warning` key of `hook_permission()`. However, it says:

> This warning overrides the automatic warning generated by 'restrict access' being set to TRUE. This should rarely be used, since it is important for all permissions to have a clear, consistent security warning that is the same across the site.

## Additional information

I therefore propose re-purposing this `warning` key to allow providing an *additional* description. That way, the security warning (based on the `restrict access` key) remains clear and consistent, but more information can be provided if/as necessary.

I've looked through all core implementations of `hook_permission()`, and nowhere is this used. The only place that *almost* uses it is the Filter module, but it adds its own emphasised warning description, rather than utilising the dedicated 'warning' key.

Semi-related issue: https://github.com/backdrop/backdrop-issues/issues/3252

## Draft of feature description for Press Release (1 paragraph at most)

Backdrop now displays permission warning descriptions separately to the default security warning message. This allows for more consistent messaging and the ability to better describe why certain permissions have security implications.

**Comment by BWPanda** [comment]
Here's an example of the proposed functionality, and how it differs from the current functionality...

**Current (without 'warning')**:
```php
$permissions['synchronize configuration'] = array(
  'title' => t('Synchronize, import, and export configuration'),
  'restrict access' => TRUE,
);
```
![image](https://user-images.githubusercontent.com/2385329/157430944-334d045f-12f3-441c-b783-9790b35f55f0.png)

**Current (with 'warning')**:
```php
$permissions['synchronize configuration'] = array(
  'title' => t('Synchronize, import, and export configuration'),
  'restrict access' => TRUE,
  'warning' => t('With this permission, people can change functionality of the site they might not otherwise have access to.'),
);
```
![image](https://user-images.githubusercontent.com/2385329/157431590-75b49f17-4bd5-478e-8041-cc96044849f5.png)

**Proposed (with 'warning')**:
```php
$permissions['synchronize configuration'] = array(
  'title' => t('Synchronize, import, and export configuration'),
  'restrict access' => TRUE,
  'warning' => t('With this permission, people can change functionality of the site they might not otherwise have access to.'),
);
```
![Peek 2022-03-09 22-21](https://user-images.githubusercontent.com/2385329/157431933-176adc62-8f53-4c01-a926-c6d04d5cf23d.gif)

**Comment by BWPanda** [comment]
Here's a PR that provides the above functionality (without the addition of 'warning' text for permissions that didn't already have some - should that be added here or in a follow-up?): https://github.com/backdrop/backdrop/pull/3979

**Comment by BWPanda** [comment]
I've updated the PR to include warnings for all restricted core permissions. The only two I'm not sure about are `Administer fields` and `Administer tests`. Can someone shed some light of the security implications of those?

**Comment by quicksketch** [comment]
Administer fields was added here: https://www.drupal.org/project/drupal/issues/611294#comment-9542671

The explanation isn't clear but I could guess the following reasons:

* Administer fields allows setting up fields that contain text formats like Full HTML. Though access to actually _use_ Full HTML is controlled by a separate permission.
* It also allows configuring the uploading of files, which could be used in malicious attacks. Though that is mitigated somewhat by preventing the execution of PHP in uploaded files.
* But perhaps the most dangerous thing administer fields can do is delete fields, which could pretty quickly destroy all the content on a site.

Administer tests was given the warning in the initial set of restricted permissions: https://www.drupal.org/project/drupal/issues/248598#comment-2199854

* In that comment, it's noted that it's not clear if the administer tests permission really needs to be restricted. My guess is that it was added just because it has the word "administer" in it.
* The most dangerous thing I think administer tests does is consume a lot of CPU.

Maybe the following descriptions would be sufficient:

* **Administer fields**: Allows the creation, deletion, and modifying the configuration of fields, including text input and file uploads.
* **Administer tests**: Running tests consumes a large amount of CPU processing, and usually only needs to be executed by developers.

In all descriptions, I'm not sure about the use of the word "people". I don't think we use that word in other permission descriptions. Current descriptions either say "Allow users to X" or is imperative such as "Controls access to X"

**Comment by BWPanda** [comment]
> In all descriptions, I'm not sure about the use of the word "people". I don't think we use that word in other permission descriptions. Current descriptions either say "Allow users to X" or is imperative such as "Controls access to X"

I agree, I don't like the word "people" either. But @jenlampton thinks differently and apparently we shouldn't be using the word "user": https://github.com/backdrop/backdrop-issues/issues/5431

I've updated the PR based on @quicksketch's suggestions, though for now I've tried to keep consistency with the other warning descriptions. Once we have consensus on the whole "users" vs. "people" wording situation, I can update as needed.

**Comment by jenlampton** [comment]
For the record, "User accounts" is perfectly fine. If we are referring to the thing people use to access their website. If, however, we are referring to them, we should call them "people". In Drupal the word "users" was used for both, which not only makes it very confusing to everyone, but it also makes people unhappy, because people do not like being called users. 

I will update that issue title so people stop getting confused about what is okay and what is not okay.

**Comment by BWPanda** [comment]
FTR, I don't mind being called a 'user': https://tron.fandom.com/wiki/User 😉

**Comment by klonos** [comment]
> Also +1 to this issue. It'll be great to see some consistency brought to this page!

Same here ✋🏼

**Comment by klonos** [comment]
I've left some wording suggestions in the PR.

While at it, can we please also remove this useless description:

![image](https://user-images.githubusercontent.com/2423362/158729879-fe163a68-4dc8-48f1-bafe-9a17156ee226.png)

**Comment by klonos** [comment]
I don't see why this cannot go into the next bug fix release. This is a UX improvement, and doesn't really introduce anything new - we are updating descriptions and reusing already-established UI patterns (the more/less toggles etc.).

**Comment by BWPanda** [comment]
I've re-worded nearly everything, trying to avoid use of the word 'people'. Also tried implementing some of @klonos' suggestions.

**Comment by bugfolder** [comment]
Some tests failed under PHP 8.1. Random gremlin, or something real?

Testing-wise, checked and reviewed the permissons for the following:

* Synchronize, import, and export configuration
* Administer fields
* Bypass file access control
* Administer file types
* View private files
* Manage or replace any file
* Delete any file
* Administer text formats and filters
* Administer Layouts
* Administer Flexible Templates
* Bypass content access control
* Administer content types
* Administer content
* Install and update modules, themes & layouts
* Administer site configuration
* Administer software updates
* Administer permissions
* Administer user accounts
* Assign user roles
* Administer user account settings
* Select method for cancelling own account
* Administer views
* Bypass views access control

So, testing-wise, this looks good to me, but I'll leave "needs testing" in place until the automated tests are passing.

**Comment by bugfolder** [comment]
> Some tests failed under PHP 8.1. Random gremlin, or something real?

Was random gremlin. Closed and reopened PR, now all tests pass.

Code reviewed, looks good. RTBC!

**Comment by BWPanda** [comment]
Already in the next bugfix milestone. Just need a @backdrop/core-committers to merge.

**Comment by quicksketch** [comment]
Looks great. I wasn't sure about using the key `warning` for each permission, but to my surprise it was an existing key that we just had not been using previously. Great improvement to help administrators understand when to assign certain permissions. Merged https://github.com/backdrop/backdrop/pull/3979 into 1.x and 1.21.x.

https://github.com/backdrop/backdrop/commit/d9675244a7e79a4b7fd9fd7d16c714a931c80b1b by @BWPanda, @klonos, @jenlampton, @quicksketch, and @bugfolder.
