### ISSUE TITLE
deprecated function taxonomy_get_term_by_name() does not return any value

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5570]
```php
function taxonomy_get_term_by_name($name, $vocabulary = NULL) {
  watchdog_deprecated_function('taxonomy', __FUNCTION__);
  taxonomy_term_load_multiple_by_name($name, $vocabulary = NULL);
}
```
should be
```php
function taxonomy_get_term_by_name($name, $vocabulary = NULL) {
  watchdog_deprecated_function('taxonomy', __FUNCTION__);
  return taxonomy_term_load_multiple_by_name($name, $vocabulary = NULL);
}
```

**Comment by phershbe** [comment]
I'm relatively new to contributing to open source, I can change this if you would like. I've already found the correct file in the repository. Let me know!

**Comment by indigoxela** [comment]
> I can change this if you would like.

@phershbe That's great! Let us know if you need any instructions or help.

**Comment by phershbe** [comment]
@jenlampton @inidgoxela Thank you! It's done now. Sorry about the delay, I'm still learning GitHub and wanted to make sure that I did things correctly.

**Comment by argiepiano** [comment]
Thanks @phershbe! Code LGMT. Tests have not run since @phershbe is a first-time contributor. I think a one of the @backdrop/core-committers needs to approve the workflow?

@phershbe as a side note: please label your PRs starting with the words "Issue #XXX: [My PR label]" - this makes it easier to find the related issue in the backdrop-issues repository.  Also, in the description of the PR, use the magic  keyword "Fixes XXX" (in place of XXX, paste the URL of the issue this PR fixes). This will link the PR to the issue, and will close the issue once the PR is merged.

**Comment by herbdool** [comment]
I've kick-started the pr.

I guess we don't have a test for this one.

**Comment by quicksketch** [comment]
Thanks @indigoxela, @argiepiano, and @herbdool for the help here!

> please label your PRs starting with the words "Issue #XXX: [My PR label]"

The commit message is no big deal, since committers need to modify the message to include attribution on every merge anyway. But it is helpful if it's already formatted as close as possible. :smile: 

I merged https://github.com/backdrop/backdrop/pull/4032 into 1.x and 1.21.x, so this will be in 1.21.5.

Welcome @phershbe to our project! I've invited you to the Backdrop issue queue triage team so you can add your own issue labels as needed in the future. Thank you for fixing this! You did great!

**Comment by phershbe** [comment]
@quicksketch @indigoxela @argiepiano @herbdool Thank you everybody. Okay, noted on the PRs and thank you for adding me to the Backdrop issue queue triage team. I'm self-taught and haven't worked professionally in programming yet, but I'm confident enough in my full stack skills so I am studying up on your project now in order to be able to contribute more.

**Comment by jenlampton** [comment]
Wow, this issue was fixed so quickly! I only reported it 2 days ago. I came back today to create a PR for it -- but it's already fixed!  Thank you so much @phershbe for your quick work, and thanks to everyone else for the quick reviews, testing, and the merge!
