### ISSUE TITLE
Add a /layouts directory under root for custom/contrib layouts

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#559]
Do we need to have a /layouts/ folder in root? 
I'm just trying to understand Layout a bit more so I can help with docs. 
Modules can declare new layouts with hook_layout_info(). So is this the way new Layouts will be contributed, via modules, or will there be a contrib section for standalone Layouts like there is for themes and modules?

**Comment by klonos** [comment]
I don't know about contrib, but I'm sure there will definitely be custom ones though and IMO we better standardize on where they live. Thanx for opening this issue @docwilmot

That's as simple as adding a ```/layouts``` directory under root and it definitely can be done in 1.0.0

**Comment by quicksketch** [comment]
> So is this the way new Layouts will be contributed, via modules, or will there be a contrib section for standalone Layouts like there is for themes and modules?

The most standard practice will be making stand-alone layouts *without* a module. The hook_layout_info() exists so that a module could provide a layout-builder (e.g. like https://www.drupal.org/project/layout).

Agreed we should probably make an out-of-box `layouts` directory in the root, as it's where non-core layouts should live. It already works today, just like a module or theme, but you have to create the directory first.

I also expect that we'll get a number of layouts as contrib projects, probably ones that are grid-system based. e.g. a collection of Bootstrap layouts or ones using Foundation. Just like a module, a layout "project" could actually contain several layouts.

**Comment by BWPanda** [comment]
The README.txt file will need reviewing/updating as per https://github.com/backdrop/backdrop-issues/issues/266 (I pretty much just found & replaced 'themes' => 'layouts').
