### ISSUE TITLE
Fix main class and add more space to bottom of admin theme (Seven).

### ISSUE THREAD

**Issue by gitressa** [backdrop/backdrop-issues#5600]
## Description of the bug
It looks like there is no `<main>` tag in the mark up on the page, but maybe `.l-content` can work?

Also, I feel like there's too little space at the bottom, which makes it feel claustrophobic, so also adding some more space.

https://github.com/backdrop/backdrop/pull/3987

**Comment by stpaultim** [comment]
@gitressa - I updated the title because your PR makes changes to the admin theme Seven, but that is not mentioned in the issue title or description. Let correct me if I got that wrong.

It seems that the PR is mostly intended to add additional space at the bottom of the page for the admin theme. 

We are super cautious about updating the CSS in Basis or the front end, but I think that we can easily make changes to the admin theme as backward compatibility is not really such a big issue (making minor changes to the appearance of admin theme).

Here is what this PR does:

![image](https://user-images.githubusercontent.com/3144571/165671864-6355389c-6481-48ac-8a80-15277a04995f.png)

BEFORE:

![image](https://user-images.githubusercontent.com/3144571/165671676-0df6f34d-b418-4d38-8ba7-e1e18e6743e1.png)

AFTER:

![image](https://user-images.githubusercontent.com/3144571/165671566-d46dd990-fb09-485c-be2a-44683db0d43c.png)

**Comment by stpaultim** [comment]
I've looked a little closer and support this change. It's a minor change that makes admin pagers a little easier to use/read. I see no reason to NOT do this and it is a small UI improvement.

**Comment by stpaultim** [comment]
I marked this RTBC and then realized that the dashboard page does not have .l-content. Adding margin to l-wrapper does not work, but adding padding seems to work. Is this an acceptable alternative. This seems to work on dashboard as well as other pages. 

```
.l-wrapper {
  padding-bottom: 80px;
}
```

**Comment by olafgrabienski** [comment]
> I updated the title because your PR makes changes to the admin theme Seven

@stpaultim The title doesn't seem to have changed.

**Comment by gitressa** [comment]
Thanks for your suggestion, it works really well @stpaultim, and I have updated the PR.

Should Bartik and Basis likewise get PRs for more margin at the bottom?

**Comment by gitressa** [comment]
I have created #5605 to provide instructions about creating an issue when creating a PR, @stpaultim.

**Comment by stpaultim** [comment]
> Should Bartik and Basis likewise get PRs for more margin at the bottom?

We have to look and see if they need it. BUT, that is really a different issue. We can make a change like this on the administrative theme quite easily, because this does not effect the front end of anyones website. However, if make changes to Bartik or Basis, it does effect peoples websites and might cause unexpected problems. 

We only make CSS changes to Basis if we are confident it will not break anyones site. If you think the other themes need more space at the bottom, you would need to create new issues. Even if we can't fix them now, we may be able to in the future.

**Comment by gitressa** [comment]
Thanks for clarifying @stpaultim, I might create another issue. Other users are of course welcome to do this, if they think the other themes also need more space at the bottom.

**Comment by stpaultim** [comment]
@gitressa - for reference, our community is at a bit of a standstill on making improvements to Basis due to concerns about backward compatibility. See: https://github.com/backdrop/backdrop-issues/issues/4167

Your opinions would be welcome. A new voice in that discussion might help move it forward.

**Comment by stpaultim** [comment]
I went ahead and marked this "Works for me" and "RTBC," but would not mind additional thoughts if there is any reason NOT to do this. I have noticed this before, specifically on the logs pages where the newly moved "Clear Log Messages" button is (in my opinion) uncomfortably close to the bottom of the page. 

![image](https://user-images.githubusercontent.com/3144571/165882788-69ca809c-179f-4314-9083-66cf2b0c85ac.png)

This PR just adds 80px of padding.

**Comment by quicksketch** [comment]
Thanks @gitressa and @stpaultim! It would be nice to have a follow-up to recreate the `<main>` tag. Seems like there should definitely be one on all pages, even if they're just administrative pages.

I merged https://github.com/backdrop/backdrop/pull/3987 into 1.x and 1.21.x. Thanks!
