### ISSUE TITLE
[DX] Remove broken references to $conf from settings.php

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#563]
It looks like the $conf variable in settings.php does not work in Backdrop.  But our settings.php file still contains a few of these variables, along with instructions to the reader to uncomment them in certain circumstances.

If they really won't work, we need to remove them, and their incorrect instructions:
```
// $conf['site_name'] = 'My Backdrop site';
// $conf['theme_default'] = 'stark';
// $conf['anonymous'] = 'Visitor';
```
and 
```
// $conf['css_gzip_compression'] = FALSE;
// $conf['js_gzip_compression'] = FALSE;
```
and 
```
$conf['404_fast_paths_exclude'] = '/\/(?:styles)\//';
$conf['404_fast_paths'] = '/\.(?:txt|png|gif|jpe?g|css|js|ico|swf|flv|cgi|bat|pl|dll|exe|asp)$/i';
$conf['404_fast_html'] = '<!DOCTYPE html><html><head><title>404 Not Found</title></head><body><h1>Not Found</h1><p>The requested URL "@path" was not found on this server.</p></body></html>';
```

We also need to determine what the correct procedure is for overriding those variables, as per https://github.com/backdrop/backdrop-issues/issues/562

**Comment by behindthepage** [comment]
I can do this pretty quickly but should we wait to work out how these are overridden first so we can add the correct procedure to the settings.php file?

**Comment by quicksketch** [comment]
The Fast 404 settings should all just be switched from $conf to $settings, since they are now retrieved with settings_get() in https://api.backdropcms.org/api/backdrop/core!includes!bootstrap.inc/function/fast_404/1

Right now you can't override any other configuration directly in settings.php, so all the remaining references to $conf (site_name, theme, css_gzip_compression, etc) should be removed.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/657.

Thanks @behindthepage!
