### ISSUE TITLE
Duplicate modules cron_queue_test and system_cron_test after update

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop/backdrop-issues#5650]
## Description of the bug

A couple of sites that have just been updated are showing Status Report error messages for:

- Cron Queue test module
- System Cron test module

There are multiple versions of module Cron Queue test in the installation. [less](https://dev.systemhorizons.co.uk/admin/reports/status#)
The competing module files are listed below. Only the first of the module versions in the list will be loaded.
**core/modules/system/tests/cron_queue_test.module**
core/modules/system/tests/cron_queue_test/cron_queue_test.module

There are multiple versions of module System Cron Test in the installation. [less](https://dev.systemhorizons.co.uk/admin/reports/status#)
The competing module files are listed below. Only the first of the module versions in the list will be loaded.
**core/modules/system/tests/system_cron_test.module**
core/modules/system/tests/system_cron_test/system_cron_test.module

I believe this was introduced through PR [#3911](https://github.com/backdrop/backdrop/pull/3911) that was aiming to address #5465 (1.21.2) but only became apparent in status report in 1.22 when #5464 was implemented.

## Steps To Reproduce

To reproduce the behavior:
1. Start with version before 1.21.2
2. Update through the UI
3. Go to status report

## Actual behavior
Update has created duplicate files

## Expected behavior
Renaming of files should have removed old files

## Additional information

Add any other information that could help, such as:
- Backdrop CMS version: 1.22
- Web server and its version: litespeed
- Operating System and its version: linux ?
- Browser(s) and their versions: N/a

**Comment by indigoxela** [comment]
@yorkshire-pudding I think, you're correct with your analysis.

The main problem when updating core via UI: stale files won't get deleted. See also https://github.com/backdrop/backdrop-issues/issues/4285

The new core gets unpacked over the old one, so files that got moved around, will cause duplicates.

So what we need is an update hook, that removes the stale files (and a solution for the base problem would be nice, too :wink:).

**Comment by bugfolder** [comment]
> So what we need is an update hook, that removes the stale files.

[PR added that removes the stale files if they're present](https://github.com/backdrop/backdrop/pull/4090). Don't think anything more is needed, but this is a good reminder that if we move files around, we need to check for copies in their old locations in an update hook.

**Comment by indigoxela** [comment]
@bugfolder many thanks for the quick fix. Works like a charm.

This is how I tested:

- Installed a vanilla 1.21.1
- Updated to 1.22.0 via self-update, ran db updates
- Verified warnings on /admin/reports/status
- Applied patch 4090.diff, ran db updates again
- Verified warnings are gone on /admin/reports/status
- Also verified that the files are gone in core/modules/system/tests/

**Comment by indigoxela** [comment]
@bugfolder I've left some questions / suggestions on your PR.

**Comment by bugfolder** [comment]
@indigoxela, they're addressed, thanks.

**Comment by indigoxela** [comment]
Many thanks for updating your PR. This looks perfect now, RTBC :+1:

**Comment by argiepiano** [comment]
Quick questions here:
1. Would it be better to set the message level to `warning` rather than `error`? Error seems a bit extreme. I'm trying to find other instances of `backdrop_set_message` in update hooks. Found several in `field.install` - they are all warnings
2. Like `field` hooks, would it be a good idea for the hook to return a message as well? 

And third question: perhaps some guidance to the admin of what to do in this case? Like "You may try to remove the files XXX and YYY manually."

**Comment by argiepiano** [comment]
There are additional `backdrop_set_message()` in system.install. All are `warnings` there too...

**Comment by bugfolder** [comment]
This case where this would arise is if the file exists but can't be removed by the site itself, so a system-level permission problem (probably). I'll defer to those more experienced than I whether the serious-ness warrants only warning, not error, but it seemed to me that "something we're trying to do has failed" warranted an error.

**Comment by indigoxela** [comment]
> whether the serious-ness warrants only warning, not error, but it seemed to me that "something we're trying to do has failed" warranted an error.

Also a good point, but let's think it over:

If the files are there, there's a warning on the status page (note: warning, not error). That's because the existence of these files isn't desired, but doesn't break anything on the site - everything will function normally.
However, if the files can't get removed, there is a problem with (very likely) file system permissions in the core folder. If that's the case, I'd assume that self-updates wouldn't work at all, though. That core updates do work, but removing these two files isn't possible - that sure seems like an edge case to me.

Personally, I'm fine with "error", but also see the point that this might be extreme, as we know the existence of these files won't break the site.

**Comment by argiepiano** [comment]
Good thoughts you two, I'm fine with either error or warning. But how about the third point - adding a clue of what you can do to solve this manually? (remove the files)

**Comment by bugfolder** [comment]
So, there's different ways of doing an update, depending on how the site and host are configured:

* Self-update. As @indigoxela notes, if this is working, this issue shouldn't arise because apache already has write permission.
* Admin replaces core with the new version by removal and replacement. In this case, the spurious files are removed by that replacement.
* Admin updates from from version-controlled repo. This could potentially result in the situation that apache doesn't have write access to the core directory, but (depending on how they load their repo, e.g., by replacing core code) the files are likely already gone. But they might not be. So this is an edge case where this might be needed. But probably pretty rare.

Since the site will still work and the status warnings are persistent, I'm fine with leaving this as a warning. I agree with @argiepiano's suggestion of giving some instruction on what to do to fix it manually (there's no instruction in the status warning), so I'll add that presently.

**Comment by bugfolder** [comment]
Changed to 'warning', instructions added.

**Comment by indigoxela** [comment]
> Changed to 'warning', instructions added.

Great, still RTBC from my side. :+1:

**Comment by bugfolder** [comment]
The tests have failed twice, but it's a different test each time, so I'm going to claim it's the Tugboat gremlin and things are OK.

**Comment by quicksketch** [comment]
I filed another in the related issue at https://github.com/backdrop/backdrop-issues/issues/4285 that should prevent this from happening in the future. That issue would also "fix" any other stray files because the intended code replaces the entire "core" directory, rather than merging it like is happening now.

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/4178 into 1.x only, since the update hook `system_update_1085()` conflicts with the 1.22.x branch. Thanks @bugfolder, @indigoxela, @argiepiano, and @yorkshire-pudding!
