### ISSUE TITLE
Notice: Undefined index: header in bartik_preprocess_layout() (line 36 of /var/www/html/docroot/core/themes/bartik/template.php). => 

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#5652]
## Description of the bug

Attempting to create a new template gives the notice in title.

## Steps To Reproduce

To reproduce the behavior:
1. Enable Bartik theme.
2. Go to `/admin/structure/layouts/settings/flexible-template/ukraine/configure`.

## Additional information

Placing Devel module's dpm() function just above the offending line like below:

```
/**
 * Prepares variables for layout template files.
 *
 * @see layout.tpl.php
 */
function bartik_preprocess_layout(&$variables) {
  dpm($variables['content']);
  if ($variables['content']['header']) {
    $extra_header_classes = array();
    $extra_header_classes[] = theme_get_setting('main_menu_tabs');
    $legacy = array('one_column', 'two_column', 'two_column_flipped', 'three_three_four_column');
    if (in_array($variables['layout']->layout_template, $legacy)) {
      $extra_header_classes[] = 'l-header-inner';
    }
    $variables['content']['header'] = '<div class="' . implode(' ', $extra_header_classes) . '">' . $variables['content']['header'] . '</div>';
  }
}
```

gives the result in screenshot:

![Screen Shot 2022-06-16 at 1 22 24 AM](https://user-images.githubusercontent.com/56604405/174005045-00708d3e-c259-4851-bee1-ba261a7ca496.png)

which means there are more than one iteration through function and while the first one gives array of 5 members, one of which is `header`, the second round gives an empty array, causing the notice.

**Comment by alanmels** [comment]
Very simple fix is proposed, but I'm not sure if `bartik_preprocess_layout()` was supposed to iterate twice, so it might be not the ideal solution.

**Comment by indigoxela** [comment]
@alanmels many thanks for your report and bugfix. Using isset() for an array key that may or may not exist is correct. :+1: 

> I'm not sure if bartik_preprocess_layout() was supposed to iterate twice

I can't confirm that. If I put in a `debug('runs');` at the beginning of bartik_preprocess_layout(), I can see that it only runs once. For default layouts and also for flexis (without "header"). Maybe it's caused by something specific in your setup?

**Comment by alanmels** [comment]
It's pretty empty vanilla Backdrop. Doesn't `dpm()` return two arrays in your test setup?

**Comment by indigoxela** [comment]
As mentioned above, I'm using `debug()` directly - without devel/dpm. So maybe that's what's causing the (seemingly) duplicate run.

Can you try it with `debug` instead of `dpm` and check that on your setup?

**Comment by argiepiano** [comment]
I have been able to reproduce the notice. You have to work with a new custom flexible layout template that doesn't contain a row named "Header" (you have to purposely remove that row in 
http://bdentity.localhost:8888/admin/structure/layouts/settings/flexible-template/TEMPLATE/configure )

The fix works for me, too.

As for the double output of dpm - I wouldn't worry about it. Working with preprocess function and dpm sometimes has the effect of not showing your output on your first refresh (since dpm uses the message area, I suspect the message content has already been retrieved when the dpm is reached). So perhaps the double show there produced by another window accessing a page on Bartik that doesn't use the custom layout template.

**Comment by argiepiano** [comment]
Thanks for the PR @alanmels! I've added the 1.22.1 milestone
