### ISSUE TITLE
Custom logo/favicon have 'temporary' status

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#5660]
## Description of the bug

When you upload a custom site logo or favicon, they're listed under `admin/content/files` as 'temporary'. Also, when clicking the Manage link on that page, they don't have a default value for the Destination field.

## Steps To Reproduce

To reproduce the behavior:
1. Go to `admin/config/system/site-information` and upload a custom logo/favicon
2. Go to `admin/content/files` and note the Status of the newly-uploaded file
3. Click its Manage link and note the lack of a default value for the Destination field

## Actual behavior

![image](https://user-images.githubusercontent.com/2385329/176106920-38148192-4c4b-4338-a431-45a8a394a445.png)

![image](https://user-images.githubusercontent.com/2385329/176107128-fdc90660-e38e-4a44-a04f-d2d5555a818e.png)

![image](https://user-images.githubusercontent.com/2385329/176106989-0a7759fc-4cc9-4503-9b25-5dc758f1b63f.png)

**Comment by indigoxela** [comment]
Yikes, that's an ugly one! Confirmed. People will lose their custom logos, as soon as the grace time has passed and temporary files got remove.

**Comment by indigoxela** [comment]
On form submission (system_site_information_settings_submit) the file gets handled via `file_unmanaged_copy($file->uri);`, which is odd, because in system_site_information_settings_validate the file gets handled via file_save_upload, which adds the file to the "file_managed" table and creates the temporary path.

We could fix that mixup of unmanaged and managed either way:

- make it clearly unmanaged (don't try to insert it into file_managed)
- make it clearly managed (also the form item) and handle file usage

Which one's preferred? Both is safe, as the File module is a required module.

**Comment by BWPanda** [comment]
I'm afraid this is an area I'm not very familiar with... What're the benefits of managed files over unmanaged ones?

**Comment by indigoxela** [comment]
> What're the benefits of managed files over unmanaged ones?

Managed files are available in the overview on /admin/content/files, they are reusable, deleteble (by intention! :wink:), the uploaded file can be replaced via the File UI. They're also fieldable and have view modes - OK, we don't need that for logos.

Unmanaged files are just stuff in the file system. No overhead, but not way to manage them - besides uploading a new one.

**Comment by indigoxela** [comment]
Here's a related (very old) issue: https://github.com/backdrop/backdrop-issues/issues/405

**Comment by indigoxela** [comment]
It turned out that it's not all that bad. The File (leftover from file_save_upload()) is in "temporary://", and that gets deleted by cron run. But the file in public://, created by file_unmanaged_copy() stays intact.

However, there are several glitches with that leftover file:

If trying to delete or save it manually on /file/XX/manage, one get's an error "Invalid option temporary in Destination element."
That's confusing for admins
And it's also confusing that it's there in the listing, anyway.

So why does it get created in system_site_information_settings_validate()? For easier validation. After that the file entity (db record) is obsolete.

Based on the description in that other (old) issue, I'm assuming that we don't want a fully managed file entity with all overhead. So I made it clearly unmanaged. A [PR](https://github.com/backdrop/backdrop/pull/4113) is ready for testing and review.

**Comment by indigoxela** [comment]
> if you replace the logo/favicon with a new one, the old one remains in the files directory and will never be removed

Yes, correct. Same as before, same as in D7.

> perhaps using managed files instead would prevent this

If we completely switch to managed_file it would be ... manageable, yes. :wink: But I'm not sure if we want that. Might need more feedback. I searched the queue for something related (managed logo/favicon file), but couldn't find any previous issue.

**Comment by argiepiano** [comment]
I'm not sure it's a good idea to switch this to a managed file. One of the problems this may create is that the Manage Files UI shows the "internal" or original file name, not the real file name as saved in the actual server directory. See attached images. This will lead to confusion. For the snapshots below, for illustration purposes only, I actually uploaded the same png files a couple of times through the Manage Files UI (but I used the same file a third time directly through the Upload File button in `admin/config/system/site-information`)

- The shortcut icon file name shown in 'admin/config/system/site-information' is fcicon_0.png
-  Manage files UI shows the 2 original file names (fcicon.png) for all uploaded versions of the file (notice that the name shown is not the actual file name in the server directory, but the original file name of the file that was uploaded
- See snapshot from the public file folder

Shortcut icons settings in Configurations -> System ->Site information
<img width="1000" alt="Screen Shot 2022-06-28 at 8 31 00 AM" src="https://user-images.githubusercontent.com/9938978/176206158-120a63d9-27e0-4328-92a1-de8dba50ba80.png">

Manage Files UI:
<img width="539" alt="Screen Shot 2022-06-28 at 8 34 07 AM" src="https://user-images.githubusercontent.com/9938978/176206057-f9ead478-ed27-4537-b779-1d5c849b9339.png">

SErver directory
<img width="281" alt="Screen Shot 2022-06-28 at 8 27 57 AM" src="https://user-images.githubusercontent.com/9938978/176206301-35e3b584-dbf6-486e-aef0-4c3227c1e12c.png">

**Comment by indigoxela** [comment]
> Sounds good!

Great, follow-up created, currently as a question: #5661

**Comment by argiepiano** [comment]
> I don't think that the form type managed_file reports the entity name - I think it reports the actual file name.

The pasted image says otherwise. Try it

**Comment by indigoxela** [comment]
> ... when you upload the same image more than once. That '_X' is not shown in the UI

Now I get it! If one "manages" the file on /file/XX/manage - not the field directly - the referenced name is still the original one.
Will post that as a concern in the other issue.

**Comment by quicksketch** [comment]
Thanks folks! I merged https://github.com/backdrop/backdrop/pull/4113 that cleans up that unnecessary file entity.

I definitely would be interested in giving these forms a larger overhaul, so thanks @indigoxela for opening https://github.com/backdrop/backdrop-issues/issues/5661. 

Thanks @BWPanda and @argiepiano for the reviewing and feedback!
