### ISSUE TITLE
Fatal error when editing settings for default layout

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#568]
Steps to reproduce:
1) Edit the default layout
2) Click on the 'Settings' tab at top right
3) Change nothing, click 'Save layout'
4) Click on the 'Settings' tab at top right, again
5) get the error below

Error:
```
Fatal error: Call to a member function getContexts() on a non-object in backdrop/core/modules/layout/includes/layout.pages.inc on line 49
```

**Comment by tarekdj** [comment]
@jenlampton Also confirmed for other layouts.
PR: https://github.com/backdrop/backdrop/pull/658

**Comment by quicksketch** [comment]
Thanks @tarekdj! I'll give that PR a spin locally asap.

**Comment by quicksketch** [comment]
Fixed by merging https://github.com/backdrop/backdrop/pull/658. Thanks @tarekdj!

Although it fixed the problem by itself, I also found that saving the default layout the first time made a `layout.menu_item.default.json` file in the config directory. I fixed that in a followup commit (https://github.com/backdrop/backdrop/commit/327dfd0129cf3e3f66566ffe255be4dc09e4b4da).
