### ISSUE TITLE
Function path_admin_form should not have a path autocomplete for the source field

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#5686]
## Description of the bug

The form on "Add URL alias" (/admin/config/urls/path/add) has two fields, "Existing system path" and "URL alias".

The input for "Existing system path" has autocomplete functionality enabled, which is weird, as autocomplete will be an alias in most cases.

This leads to a "WTF" moment.

## Steps To Reproduce

1. Go to /admin/config/urls/path/add
2. Click into the first field and start typing and select something
3. Click into the next field and ... scratch your head

## Actual behavior

![alias-an-alias](https://user-images.githubusercontent.com/842066/179352675-431651ad-8e90-4178-b28b-1a23f9719915.png)

Sure, on submission the system path value gets submitted, so the alias ... for the (seemingly) alias will get created properly, but I find that very confusing.

## Expected behavior

Neither in D7 nor in D9 this field is path_autocomplete. And I think that makes much more sense. We need system paths here, but autocomplete *displays* aliases.

## Additional information

Here the autocomplete gets attached: https://github.com/backdrop/backdrop/blob/1.x/core/modules/path/path.admin.inc#L137

Besides the odd UX, this also leads to other problems, like #5684

**Comment by indigoxela** [comment]
A [PR](https://github.com/backdrop/backdrop/pull/4165) is available for testing and review.

**Comment by argiepiano** [comment]
Makes sense. LGTM

**Comment by kiamlaluno** [comment]
I checked the Tugboat site created for the pull request. Backdrop log doesn't record any error, nor does the user interface show errors. I was able to add a path alias.

**Comment by klonos** [comment]
Although I agree that showing page titles while we use paths in this field is a bit of a WTF, I think that removing the autocomplete here would be a UX regression. A proper solution would be to have the autocomplete return paths, with hints of the page title.

If we are set on removing the autocomplete because of the slight WTF, then I would like us to open a follow-up issue to re-introduce it properly. But in all honesty, I would prefer if we fixed this properly here in this issue.

**Comment by indigoxela** [comment]
> A proper solution would be to have the autocomplete return paths, with hints of the page title.

@klonos are you suggesting a new autocomplete callback for that single input?

For me the current situation is more than odd (I hope, in the issue description I explained properly, why). We really shouldn't leave it as it's now. I hope, we agree on that.
IMO the best solution would be to remove the autocomplete, but I'm open for suggestions.

**Comment by indigoxela** [comment]
@klonos you might have missed an important part (just came to my mind...). The autocomplete does not complete system paths at all. So if you type node/... - no autocompletion. Same if you type taxonomy... - nothing. That's why that autocomplete is bullshit on that specific input. :wink:

**Comment by klonos** [comment]
> @klonos are you suggesting a new autocomplete callback for that single input?

Yes. I was thinking either that, or use a `hook_path_autocomplete_alter()`, since once is already provided in `path_autocomplete()`: https://github.com/backdrop/backdrop/blob/1.x/core/modules/system/system.module#L4322

> We really shouldn't leave it as it's now. I hope, we agree on that.

Yes, we agree on that 👍🏼 

> The autocomplete does not complete system paths at all. So if you type node/... - no autocompletion. Same if you type taxonomy... - nothing.

Yes, I've been playing on my local with this, to see if there's a relatively easy way to achieve a good result (autocomplete that searches both on internal paths, as well as by node/taxonomy/user/menu/file title). Not quite there yet, but I think that it is doable.

My main point here is that the autocomplete is generally a better/faster way for people to provide input in forms. Removing it feels like a UX regression to me. We can do better than that.

**Comment by kiamlaluno** [comment]
I added a path alias for /user/1 on a Backdrop 1.22 site (without the change proposed here). When I entered *user*, the autocomplete suggested two pages that were related to user accounts ("User account (Menu item: *user*)" and "User accounts (Menu item: *search/user*)", but the same suggestions were still given when I entered the full path (*user/1*).
The same happened when I entered user/2 (even when that account didn't exist).

While I can understand "User account (Menu item: *user*)" suggested for the logged in user, the fact it's suggested for other accounts, even not existing ones, is confusing.

**Comment by kiamlaluno** [comment]
Is it possible to use an autocomplete that shows the autocompleted path instead of page titles? When I enter *node/1*, it would show, for example, _node/1_, _node/10_, _node/11_.

**Comment by indigoxela** [comment]
> When I enter node/1, it would show, for example, node/1, node/10, node/11

I'm not sure, but if I got it right, @klonos is currently exploring a way to do that.

**Comment by klonos** [comment]
Well yes and no 😅 ...what I'm exploring is this:
- include both internal paths (`node/*`, `taxonomy/*`, `user/*` etc), as well as titles in the results/matches of the query
- make it so instead of the current "Title + (description)" in the select list, we get "internal path + a description that includes the title"

So instead of the current:
![image](https://user-images.githubusercontent.com/2423362/185390565-bcf48434-39d3-47d9-b725-697ccb1a389c.png)

...something like this:
![image](https://user-images.githubusercontent.com/2423362/185391821-48f03f9e-0fc3-4120-a552-bce0da372259.png)

With the above, I believe that the emphasis on the returned results is on the internal path, while at the same time we are showing the users the title of the thing + what it is (which preserves the previous functionality).

**Comment by klonos** [comment]
Hey @indigoxela quick question before we proceed further with this: how is this autocomplete field in this form more of a WTF than for example the field where we ask for paths in `admin/config/system/site-information` or in `admin/config/urls/redirect/add` 🤔

**Comment by indigoxela** [comment]
> how is this autocomplete field in this form more of a WTF than for example the fields where we ask for paths in admin/config/system/site-information or in admin/config/urls/redirect/add

Oh, I thought that was clear so far - look at the help text for that input:

```
Specify the existing path you wish to alias. For example: node/28 or taxonomy/term/1
```
Only system paths make any sense here, but the autocomplete provides everything else, but _no system paths_.

> ... admin/config/system/site-information or in admin/config/urls/redirect/add

In both examples, the alias is just fine. Autocomplete on these fields *does* provide things we need.

**Comment by docwilmot** [comment]
I see @klonos point here: use the autocomplete to help you identify paths rather than having to remember the system path. I can see that helping. Only question is do we need to change the behavior in this issue or just remove the autocomplete, as the PR does, and write a new autocomplete function just for that field, in another issue. I think fix it would be my preference.

But, aside, perhaps that field's label should be "Add or edit a URL alias" since most of our entity paths would already have pathauto aliases. 🤔

**Comment by indigoxela** [comment]
I'd like to note that this form is hardly ever needed. Most things happen automagically by path patterns or via node forms. The only use-case for this form is to override (module provided) system paths, like for example "contact".

So let's not overdo things. :wink: 

Sure, we can create a follow-up or I close my PR and we switch to the "new autocomplete callback" path. I'm OK with either.

**Comment by docwilmot** [comment]
> I'd like to note that this form is hardly ever needed. Most things happen automagically by path patterns or via node forms. The only use-case for this form is to override (module provided) system paths, like for example "contact".

Exactly true. I'll say this is RTBC then but holding the RTBC label in case further discussion.

**Comment by klonos** [comment]
> ...merge this as is, and then do a follow through issue to add the new autocomplete function.

I'm fine with that too 👍🏼

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/4165 into 1.x and 1.22.x. Thanks folks!
