### ISSUE TITLE
Add external links to issue templates

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#5687]
When someone wants to create an issue in our core issue queue, then can currently choose from the following templates:

![image](https://user-images.githubusercontent.com/2385329/179395518-062cb86d-b373-45ce-aa56-6cb71519f8ba.png)

The 'Question' and 'Security issue' templates do allow opening issues here, but *recommend* instead using the forum and security email address respectively.

I'd like to remove these as options, and instead use GitHub's ability to link to external resources, such as:

- Our forum
- Our security page
- Zulip
- Other repos (Contrib, BackdropCMS.org, Docs, Events, etc.)

This should hopefully limit future issues in the core queue to just bugs and feature requests, but there remains the option to create issues without a template too (see the link at the bottom of the above screenshot - unless we want to remove that as well?).

**Comment by BWPanda** [comment]
Here's a PR that adds external links to the different places I could think of: https://github.com/backdrop/backdrop-issues/pull/5688

![image](https://user-images.githubusercontent.com/2385329/179395710-e21c3e0b-7375-43ea-ab2a-c37d3f492fb3.png)

The URLs these external links go to are (in order):

- https://forum.backdropcms.org/forum/how-and-troubleshooting
- https://forum.backdropcms.org/forum/requests-and-feedback
- https://backdropcms.org/security
- https://backdrop.zulipchat.com/
- https://github.com/backdrop-ops/contrib/issues
- https://github.com/backdrop-ops/backdropcms.org/issues
- https://github.com/backdrop-ops/docs.backdropcms.org/issues
- https://github.com/backdrop-ops/forum.backdropcms.org/issues
- https://github.com/backdrop-ops/events.backdropcms.org/issues

It looks like a lot (and it probably is), so we can trim it down if needed. But it's a starting point for discussion/feedback on the idea.

**Comment by BWPanda** [comment]
You can see the changes in action at my fork: https://github.com/BWPanda/backdrop-issues/issues/new/choose

**Comment by indigoxela** [comment]
> The 'Question' and 'Security issue' templates do allow opening issues here, but recommend instead using the forum and security email address respectively.

Plus one for switching the "Security issue" to an external link. :+1: 

But TBH I use the Question type from time to time, and others (including you :wink:) do that, too.

https://github.com/backdrop/backdrop-issues/labels/type%20-%20question

> You can see the changes in action at my fork:

Yes, that's currently a lot of options - I feel an immediate desire to reduce them.

So, in general I think it's a good idea, but I'm not really sure about removing the "Question" one-click thing.

**Comment by BWPanda** [comment]
> But TBH I use the Question type from time to time, and others (including you :wink:) do that, too.

True. But I have been thinking that I use the issue queue too much when I should probably be posting in the forum instead. I just prefer GitHub's interface over the forum, and I feel that the core issue queue probably has more (appropriate) eyes on it than the forum (hence my questions are more likely to get answered). But that shouldn't be the case, and perhaps the way to fix that is to get more people posting more regularly to the forum (instead of GitHub)...

And there'll still be the option to post a blank issue (and then tag it as a 'Question') if need be.

> Yes, that's currently a lot of options - I feel an immediate desire to reduce them.

Yeah, if we want to reduce them I'd suggest:

- Combining 'Help!' and 'Feedback' into one ('Help and feedback') that points to the Forum homepage
- Remove the links to other repos (contrib, docs, etc.)
- But add a link to https://github.com/backdrop-ops/backdrop-community/issues (I forgot that before) - perhaps this'd be a way to get more people posting general discussion items to that forgotten queue... (but then what's the difference between that and the forum?)

That'd take the number of external links down from 9 to 4.

**Comment by indigoxela** [comment]
> I use the issue queue too much when I should probably be posting in the forum instead. ... perhaps the way to fix that is to get more people posting more regularly to the forum

That's a very good point.

The questions I ask are more about core decision things. Sort of "should we do this or that"... I usually don't get any response here, so the forum might in fact be the better place for them.

> And there'll still be the option to post a blank issue

Sure, true.

Re the reduction: Plus one for all suggestions, especially the "forgotten queue" backdrop-community/issues. :wink:

**Comment by BWPanda** [comment]
PR updated to trim things down a bit:

![image](https://user-images.githubusercontent.com/2385329/180198260-40f5771c-f493-4c7c-8ce2-82d67fc32ff9.png)

**Comment by jenlampton** [comment]
I love it :)

**Comment by stpaultim** [comment]
Great idea!

**Comment by quicksketch** [comment]
Great! We can iterate as needed. Maybe move Security up to the 3rd item? And possibly restore "question"? But this already is such an improvement.
