### ISSUE TITLE
Contact module improvements

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#569]
When the Contact module is enabled, it adds a link to the Contact page to the main menu but leaves the link disabled. I can't imagine many scenarios where users wouldn't want the link displayed, so I suggest making the link enabled by default. Also, it seems the link was given a lighter weight than the Home link, so that should probably be fixed too (Contact link is generally at the end/bottom of main menu).

Also, I think the settings for the Contact module can be moved to the Configuration menu (rather than the Structure menu where they are now). The 'System' sub-menu seems like a good place to put them.

**Comment by oadaeh** [comment]
That has been the default behavior for the Contact module since at least D5, but probably since its inception.  I finally changed the default of Mass Contact (which is based on Contact) for D7, because it is so unintuituve.

**Comment by behindthepage** [comment]
* I agree that it should be enabled as this will make it easier for noobs. 
* The other thing to keep in mind is permissions have to be assigned before the user contact or site wide contact form can be used. I think a message explaining this should be shown when the contact modules is enabled. 
* I agree the contact menu link should be at the bottom of the main menu.
* I think the admin link should stay in structure. It is easier to find there and I think it is more structure than a system setting.

General ramble
The contact module was introduced in D4.7 and has changed little since. It's main functionality is to provide a contact form for each user and the site wide contact form has always seemed to me to be a last minute addition.  If you don't want user contact forms but do want a site wide contact form you are better off using the Webform module. 

Like @oadaeh I have had a close association with the Contact module since D4.7 with a module called Contact Forms and I converted the Backdrop contact module to use CMI. I have always thought that the site wide contact form should be split off from the contact module and them both be renamed as "User Contact" and "Site Wide Contact". This would require a Contact API that they both could use and that was easily built upon for other modules use.....but that is another discussion.

**Comment by BWPanda** [comment]
> The other thing to keep in mind is permissions have to be assigned before the user contact or site wide contact form can be used. I think a message explaining this should be shown when the contact modules is enabled.

I was originally going to suggest enabling the permission to access the site-wide contact form for all roles automatically, but without anti-spam functionality in core this probably isn't a good idea. I agree that there should be a message explaining this, but think that the message would be fine on the configuration page (currently admin/structure/contact).

**Comment by opi** [comment]
Some related issues:

- [UX] Have contact.module enabled by default on the standard profile. #1571
- [UX] Have the "Contact" menu item be enabled by default when enabling contact.module. #1572

**Comment by BWPanda** [comment]
Closing as there's nothing here that isn't already being addressed by the meta issue linked above.
