### ISSUE TITLE
Automatically remove blocks from layouts when a module is uninstalled

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#570]
If a module providing a block which has been added to Layout is uninstalled or disbled, the block remains but says: 'This block requires the %module module. Either re-enable the module, or remove this block.' Not nice.
How do I remove my_module's bock from Layouts (during hook_uninstall) so this doesnt show?

**Comment by BWPanda** [comment]
Correct me if I'm wrong, but this sounds like a bug with Layouts not handling uninstalled blocks properly. It makes sense that *disabled* modules leave their blocks there (so you don't lose settings/configuration on disable (the whole point behind disabling vs. uninstalling)), but uninstalling a module that provides a block shouldn't leave the block in Layouts, and it shouldn't be up to each block to write code to remove it.

**Comment by quicksketch** [comment]
Hi @docwilmot and @BWPanda, thanks for opening this. The behavior of Layouts is modeled after Views, which has the same behavior if you disable/uninstall a module that provides a View display mode, field/filter/context or any other kind of plugin. In Views, the entire configuration of the view stays intact, with only the unavailable portions showing up a a "Broken handler".

It is possible for your module to use hook_uninstall() to try and clean up blocks that have been used, but overall I'd say that it shouldn't be your module's responsibility to try and clean up blocks that are used in Layouts. The behavior that they show up as "Broken" is intentional, though if we can think of a better way to handle it, we could look into it.

**Comment by BWPanda** [comment]
> The behavior of Layouts is modeled after Views...

I think Layouts should be different though. With Views, if you were to remove fields, filters, etc. when the modules that provided them were uninstalled, the whole view could be messed up. I don't think that'd happen with Layouts though (correct me if I'm wrong); so I think it'd be safe to remove those blocks in that situation.

**Comment by quicksketch** [comment]
Sure, I can see it that way pretty easily. I'd be down for having Layout use hook_modules_uninstalled() to auto-remove blocks in layouts on uninstall. Auto-removing blocks has been the default behavior in every prior version of Drupal anyway, so continuing to do that would help match existing user expectations.

**Comment by docwilmot** [comment]
Ported Nice Menus and Nivo Slider if you want to test this (realise we dont have many block-providing modules)
See at https://github.com/docwilmot/nivo_slider
and https://github.com/docwilmot/nice_menus

**Comment by quicksketch** [comment]
Nice! @docwilmot, would you be interested in joining the Backdrop contrib group and moving those modules into it? See https://github.com/backdrop-ops/contrib to join up.

**Comment by docwilmot** [comment]
Did already apply for the theme port, https://github.com/backdrop-ops/contrib/issues/3, waiting.

**Comment by quicksketch** [comment]
> Did already apply for the theme port, backdrop-ops/contrib#3, waiting.

:( Dang! Working on it.

**Comment by quicksketch** [comment]
I switched this to a feature request, since although the current functionality is different than D7, it's the intentional behavior. I updated the title of this issue to reflect the task at hand.

**Comment by quicksketch** [comment]
Similar issue around menus: https://github.com/backdrop/backdrop-issues/issues/678

**Comment by klonos** [comment]
I do not know how this is planned to work and I do understand that from an advanced Drupal/Backdrop user point of view uninstalling a module should remove all traces of it, including any blocks. But new users might not know that uninstalling a module removes a block that they might need for their site. How I would like to see this work instead is like this:

- When a module is *disabled*, we leave the blocks in the layouts they were placed, but denote that the required module has been disabled.

- When a module is *uninstalled*, in the confirmation page, list the layouts where this module has blocks placed and the names of these blocks. This way people will know what functionality they are removing when it comes to blocks.

- When a module is *uninstalled*, still leave the "orphaned" blocks in place, but instead of "configure" actions, only have "remove" actions instead.

I would also like:

a) Some explanatory text right in the block with a list of required modules and their status (disabled/uninstalled). If a required module is disabled, the text should be in a yellow, warning-like color. If the module is missing, the text should be red/error. Explain to the user that they have the option to either re-enable or re-install the required module(s), or to **manually** delete the block. **Do not assume that users intentionally want their blocks removed when they remove modules**. IMO that constitutes data loss.

b) The block appearance to change to something like a yellow/red border (again depending on disabled or missing/uninstalled modules).

c) A "blocks missing requirements" message in the site status page (again depending on disabled or missing/uninstalled modules this should either be a warning or error).

d) A "block missing requirements" tag/label in the layouts list page next to layouts with missing requirements (again, yellow/red text for the tag)

e) A notification in the admin bar (this will be taken care of automatically by the level of severity of the issue, according to point c above).

**Comment by klonos** [comment]
...if the users go ahead and **manually** remove their blocks, then all errors/warnings go away.

For the cases where we are dealing with advanced users that intentionally remove modules and wish any respective blocks also removed in one go, we can still give them the option to select these from the confirmation page. A "Also remove any blocks provided by these modules" checkbox.

This will be something like for example the "also remove any files from quarantine" checkbox that you get when uninstalling antivirus software.

**Comment by docwilmot** [comment]
I don't think I'd agree with this. Keep in mind that this issue arose because a couple people experienced what youre proposing as a feature. When one uninstalls a module, this should be/is considered purging all traces of it from the system. To return and find it left cruft behind, red error message and all, is jarring. To worsen this by adding red/orange warnings all over the place is making it even worse IMHO. 

If you have intentions to reuse the data, then just disable.

**Comment by klonos** [comment]
That's fair enough about the left-overs and the warnings I guess. Not from a new user that is unfamiliar with Drupal/Backdrop, but still fair enough. Can we then at least warn about and list the blocks to be removed in the module uninstallation confirmation dialog? That should be enough to get new users not to remove things they might need. If they go ahead with it, we at least have an excuse.

**Comment by BWPanda** [comment]
> Can we then at least warn about and list the blocks to be removed in the module uninstallation confirmation dialog?

I like this idea, but I think it could be expanded to include listing other things that uninstalling a module would affect (e.g. field types, menu items, variables?, views/plugins, etc.). This would obviously be a whole other kettle of fish (whether there's a hook that modules can implement to list this stuff, or whether it happens automatically (that'd be better IMO)), but if people like the idea we can make it a feature request in another issue.

**Comment by klonos** [comment]
> ...but if people like the idea we can make it a feature request in another issue.

Done! :smile:

**Comment by quicksketch** [comment]
Fixed in https://github.com/backdrop/backdrop/pull/1251. Thanks again @docwilmot for all your great work! Sorry for the delay on merging this.
