### ISSUE TITLE
Update jQuery UI to the latest versions

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5705]
This is to match a Drupal core security hardening issue: https://www.drupal.org/project/drupal/issues/3300040 

> One of our drupal site's repositories in github, that uses dependabot alerts, raised this critical security warning in /docroot/core/yarn.lock file.
>
> * jQuery UI Cross-site Scripting when refreshing a checkboxradio with an HTML-like initial text label. Patched version: 1.13.2
>
> ## Proposed resolution
> Please, update these dependencies versions and compile the assets to remove this issue.

---

See also https://github.com/backdrop/backdrop-issues/issues/2493

**Comment by indigoxela** [comment]
Here we go, a [PR](https://github.com/backdrop/backdrop/pull/4156) is available for testing and review.

**Comment by indigoxela** [comment]
I you're unsure what to test, have a look at this [previous issue](https://github.com/backdrop/backdrop-issues/issues/5401)

**Comment by indigoxela** [comment]
It should be noted that this time the change in the library is way smaller than last time, so we don't have to be that cautious when testing.

Most changes are in localization. The rest seems to mostly fix deprecation warnings and smaller bugs. And the relevant one (in checkboxradio) looks fine, too (core isn't using that anyway).

(If anyone wonders, why I was so quick with that PR - I simply used the same build script as last time.)

**Comment by indigoxela** [comment]
Two months later... anyone interested in testing this PR? :wave:

@jenlampton eventually, who opened the issue?

**Comment by indigoxela** [comment]
Several months later, it seemed time for a rebase. :wink: Done. (1.13.2 is still the latest jQuery UI version)

**Comment by kiamlaluno** [comment]
@indigoxela Is there any specific page in the preview site that could be used to test the changes?

**Comment by indigoxela** [comment]
@kiamlaluno oh, a volunteer for testing! :rocket: :heart: 

jQuery UI is widely used in core:

- CKEditor in node forms - dialogs (image, link)
- CKEditor admin form (configure buttons)
- Views admin UI (drag reordering, dialogs)
- Date field widget (datepicker)
- Drag-and-drop for field admin UI, layout admin UI
- Reorder menu items (admin)

**Comment by kiamlaluno** [comment]
- I tested the node editor form. I did not find anything wrong with the CKEditor and its dialogs, including the ones for adding special characters, to make a table, or insert an image (I choose one from the library).  
- I enabled CKEditor for *Raw HTML*, added more buttons. I did not find anything wrong.
- I imported a view used for another issue and played with its settings to use Views dialogs. I just noticed that, for example, clicking on *Caching: None*, the dialog appears too low, at least the first time. It happens on my site too, but in the preview it is even lower. It does not happen all the times, though, and I cannot say what it causes it.
- I added a date field with a pop-up calendar to the *Post* content type. I did not find anything wrong, either when editing the field and when creating a *Post* node.
- I ordered the *Post* fields in *Manage fields*, using drag-and-drop. I did not find anything strange.
- I rearranged blocks using drag-and-drop in the Dashboard layout, in *Manage blocks*. I did not find anything strange.
- I re-ordered the links for the menus listed on /admin/structure/menu. I did not find anything strange.

I keep the Browser Console open all the time. It did not show errors caused by the PR changes.

**Comment by indigoxela** [comment]
@kiamlaluno many thanks for testing! I set the label "works for me" based on your findings.

Off topic: are you able to set labels in this issue queue? In theory you should be, as you're member of the Backdrop organization - but maybe GitHub changed something with permissions... :thinking:

**Comment by herbdool** [comment]
Great work @indigoxela and @kiamlaluno. Code looks good to me. I didn't inspect the jquery libraries with a fine-toothed comb since they've already been vetted in Drupal and elsewhere. The important thing is the manual testing of all the UI elements, which seem to all still work.

**Comment by herbdool** [comment]
There's a PHPCS issue, though this PR https://github.com/backdrop/backdrop/pull/4485 had the same lines that needed to change. So depends on which PR gets in first.

**Comment by kiamlaluno** [comment]
@indigoxela I apologize: I just saw your question. I am able to change labels on issues; I did not do it because I was not sure my tests were sufficient.

**Comment by quicksketch** [comment]
Thanks @indigoxela, @kiamlaluno, and @herbdool! I merged https://github.com/backdrop/backdrop/pull/4156 into 1.x and 1.25.x.
