### ISSUE TITLE
Make it clear you need to add a writeable files directory

### ISSUE THREAD

**Issue by themightywrighty** [backdrop/backdrop-issues#572]
I'm trying out Backdrop for the first time. I'm really like what you done with it!

However something that confused me after entering the database configuration settings. I got an error along the lines of "files/config_216d1cf77bdbf1f7cc7379797f695b5e/active" doesn't not exists or writeable. 

I created a new directory called "files", changed the permissions and refreshed the page and its fixed the problem. 

However I can't remember the installer telling me that I need to create files or and its doesn't mention it on your website. https://backdropcms.org/guide/installation

Is it possible to make this more clear, that you need to create the a writeable "files" directory?  

I look forward to using backdrop in the future! Martin

**Comment by quicksketch** [comment]
Hi @themightywrighty! Thanks for trying out Backdrop! We're working on increasing the robustness of the installer in a bunch of different ways in #531. I'll add this issue to the list there and see if we can get this situation covered.

**Comment by quicksketch** [comment]
We've merged in the main PR for fixing a number of install issues. Since this is one of several such issues, I'm going to close it directly. Please try it out again and if you encounter any new difficulties, open a new issue. Thanks again for trying out Backdrop! We're still on for the initial release tomorrow night. :)
