### ISSUE TITLE
Remove the messages about the GD toolkit being installed or the missing GD extension from `image_gd_settings()`.

### ISSUE THREAD

**Issue by avpaderno** [backdrop/backdrop-issues#5723]
[image_gd_settings()](https://docs.backdropcms.org/api/backdrop/core%21modules%21system%21image.gd.inc/function/image_gd_settings/1) shows the following message, when the GD extension is installed.

> The GD toolkit is installed and working properly.

When the GD extension isn't installed, it shows the following form error.

> The GD image toolkit requires that the GD module for PHP be installed and configured properly. For more information see <a href="@url">PHP\'s image documentation</a>.

Neither one of the other message is necessary since:

- When the GD extension is installed, the GD image toolkit will be available and it will show its settings form.
- When the GD extension isn't installed, the GD image toolkit won't be between the available image toolkits, and it won't be able to show its form error. [`system_requirements()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21system%21system.install/function/system_requirements/1) shows a requirement error (for runtime).

**Comment by klonos** [comment]
My understanding is that without GD things like image styles and/or preview thumbnails etc. won't work. If that is the case, then allowing installation to proceed will result in a site that has various things broken. Right?

Is this issue with regards to when multiple image kits are installed? (like an alternative to GD?) ...what am I missing?

**Comment by klonos** [comment]
Here's what I've done to test this, by simulating problems with the GD configuration:

1. Disabled the GD extension in php.
2. Attempted to install Backdrop -> got this error (from `system_requirements()`):
   ![image](https://user-images.githubusercontent.com/2423362/185771773-a0ca398d-1c54-4fce-a68d-f9a7fe923eda.png)
3. Enabled GD and restarted the webserver, to allow the installation to proceed.
4. Navigated to `/admin/config/media/image-toolkit` -> saw the message with the confirmation that things work:
   ![image](https://user-images.githubusercontent.com/2423362/185771838-bc0d3715-d16f-4b7b-8357-3ba2b9765534.png)
5. Disabled GD in php and restarted the server (this is a way to simulate for example moving the site to another server, which doesn't have GD enabled/available).
6. Refreshed the `/admin/config/media/image-toolkit` page -> got this error:
   ![image](https://user-images.githubusercontent.com/2423362/185771869-d1d6f809-1d08-4b7d-b9c0-0dc09f0bbbaf.png)
7. Headed to `/admin/reports/status` - saw these errors:
   ![image](https://user-images.githubusercontent.com/2423362/185771908-ae040245-b393-4b83-bafd-3b3c1dece2d1.png)

**Comment by kiamlaluno** [comment]
@klonos I am referring to the *The GD toolkit is installed and working properly.* sentence that is shown in the second screenshot, which is stating something obvious, as the settings for the GD image toolkit are visible.

I am also referring to the following form error the GD image toolkit tries to show.

> The GD image toolkit requires that the GD module for PHP be installed and configured properly. For more information see <a href="@url">PHP\'s image documentation</a>.

It cannot be shown, in the second screenshot you shown, because [`system_image_toolkit_settings()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21system%21system.admin.inc/function/system_image_toolkit_settings/1) contains the following code.

```php
$toolkits_available = image_get_available_toolkits();
$current_toolkit = image_get_toolkit();
```

[`image_get_available_toolkits()`](https://docs.backdropcms.org/api/backdrop/core%21includes%21image.inc/function/image_get_available_toolkits/1) doesn't return the GD image toolkit when the GD extension isn't enable; [`image_get_toolkit()`](https://docs.backdropcms.org/api/backdrop/core%21includes%21image.inc/function/image_get_toolkit/1) won't return the GD image toolkit either.

The condition for the GD image toolkit to be shown as available is that [`image_gd_check_settings()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21system%21image.gd.inc/function/image_gd_check_settings/1) returns `TRUE` as that is the value used from [`system_image_toolkits()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21system%21system.module/function/system_image_toolkits/1) for the *available* array key.

Consequentially, `system_image_toolkit_settings()` won't call `image_gs_settings()`, which cannot show a form error about the GD extension not being installed.

**Comment by kiamlaluno** [comment]
As a side note, what [`image_gd_check_settings()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21system%21image.gd.inc/function/image_gd_check_settings/1) verifies is the presence of the `imagegd2()` function. Showing a form error that says the GD extension isn't installed is probably wrong, as the server could be using a custom GD extension that doesn't have that function, or that function could be disabled.

**Comment by jenlampton** [comment]
This is a great code cleanup @kiamlaluno, thanks for spotting the issue and for filing the PR!

**Comment by quicksketch** [comment]
I think the check on the settings form (wrapping the entire form in an IF statement) is completely unnecessary, like @kiamlaluno says the form isn't even shown if GD isn't working.

Removing the "The GD toolkit is installed and working properly" message... I could go either way. I don't think I would add it if I were writing this new today, so let's go ahead and drop it.

I merged https://github.com/backdrop/backdrop/pull/4167 into 1.x and 1.23.x.
