### ISSUE TITLE
node_type_delete() doesn't check the value returned from node_type_get_type()

### ISSUE THREAD

**Issue by kiamlaluno** [backdrop/backdrop-issues#5726]
## Description of the bug

[`node_type_delete()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21node%21node.module/function/node_type_delete/1) doesn't check the value returned by [`node_type_get_type()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21node%21node.module/function/node_type_get_type/1), which can either return an object with the required information, or `FALSE`. This also means that:

- `node_type_delete()` is passing `FALSE` to [`hook_node_type_delete()`](https://docs.backdropcms.org/api/backdrop/core!modules!node!node.api.php/function/hook_node_type_delete/1) which only expects a `stdClass` instance; this would either cause further errors, if those hook implementations don't check they are getting `FALSE` instead of the documented value they should get (in the worse case), or invoke the hook implementations which don't perform any action (in the best case)
- `node_type_delete()` tries to delete a configuration object that has been already deleted
- `node_type_delete()` calls [`field_attach_delete_bundle()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21field%21field.attach.inc/function/field_attach_delete_bundle/1) for a content type that has been already deleted
- `node_type_delete()` calls [`node_type_cache_reset()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21node%21node.module/function/node_type_cache_reset/1) which would again clear the cache and reset the *_node_types_build* static value
The function should first check what `node_type_get_type()` returns and return immediately when the returned value is `FALSE`.

**Comment by klonos** [comment]
Thank for raising this @kiamlaluno

I'm all for defensive coding and this change makes sense, but do you by any chance have any way to reproduce some error due to this bug? Tat would help people with review/testing. I know that we could achieve some problematic behaviour programmatically, by passing some random string (non-existing node type) in `node_type_get_type()`, but did you happen to come across this by trying to do something via the admin UI?

**Comment by jenlampton** [comment]
I'm tempted to mark this RTBC so that we can get core committer eyes on it.

**Comment by argiepiano** [comment]
Left a tiny comment in the PR

**Comment by kiamlaluno** [comment]
I will expand the issue summary to explain better why the code should check the value returned from `node_type_get_type()`.

Clearly, calling `node_type_delete()` passing a node type that doesn't exist would cause a notice message, but the code that is calling `node_type_delete()` could eventually verify the node type exists, although it could be expected for `node_type_delete()` to verify such eventuality. (The documentation doesn't make explicit that is required for the code calling `node_type_delete()`.)

What I am thinking of is the case of two users who visit the /admin/structure/types page and try to delete the same node type. The first user to select the *Delete* link will be able to delete the node type, but when the second user would cause `node_type_delete()` to get `FALSE` from `node_type_get_type()`.

**Comment by kiamlaluno** [comment]
I have updated the issue summary. IMO, the main issue is that the `node_type_delete()` is passing to `hook_node_type_delete()` a value those hook implementations aren't expecting; then, various cache values are being usefully cleared, causing the cached data to be gathered again. (Cache is normally used to increase performance; clearing it without a good reason just lowers the performance.)

**Comment by kiamlaluno** [comment]
@argiepiano shown how to reproduce the error. It could either happen because a module is trying to delete a content type that has never existed, but also because two different functions/methods are deleting the same content type at the same time. (I could think of a `hook_cron()` implementation that invoked right at the same time a page callback or a form submission handler is invoked.)

In the first case, it would be a bug in that module; in the second case, it's a bug in the Backdrop code. (This issue fixes the latter case.)

**Comment by quicksketch** [comment]
I was still a little on the fence about this even with the explanation above. It seems that if you try to delete a content type that never existed, due to a typo or something (e.g. `node_type_delete('bloog')`), that an error _should_ be thrown. Rather than silently doing nothing.

But I see there may be valid situations where the error should actually be ignored. This could be solved with throwing an exception (then it could be caught optionally), but this approach is simple and solves the stated problem. So in the end, fine as it is.

I merged https://github.com/backdrop/backdrop/pull/4171 into 1.x and 1.23.x. Thanks @kiamlaluno for taking the time to explain this thoroughly and filing the PR! Thanks @klonos, @jenlampton, and @argiepiano for your feedback and help reviewing.
