### ISSUE TITLE
Change the group name "Node types" in the "Configuration group" dropdown to "Content types" instead

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5736]
In `admin/config/development/configuration/single/export`:

![image](https://user-images.githubusercontent.com/2423362/185806029-61d8a289-10e6-4010-96f1-1465fe470855.png)

We should generally be avoiding to expose the word "node" in the UI + everywhere else, like in the admin menu etc., we refer to these as "content types".

**Comment by klonos** [comment]
One-liner PR here: https://github.com/backdrop/backdrop/pull/4177

**Comment by bugfolder** [comment]
Checked the code (the one line that it is); looks good. Checked the dropdown in the sandbox; looks good. WFM, RTBC.

**Comment by klonos** [comment]
That was very prompt @bugfolder 🙂 ...do you mind also setting the milestone while at it?

**Comment by bugfolder** [comment]
Did it

**Comment by quicksketch** [comment]
I'm not sure about some of these places, where sometimes developer-oriented UIs still use "Node" instead of "Content". However, our only real policy is it's called "Content" in the UI and "Node" in code, so I guess this qualifies. I merged https://github.com/backdrop/backdrop/pull/4177 into 1.x and 1.22.x. Thanks @klonos and @bugfolder!
