### ISSUE TITLE
Default setting for `Who can register accounts?` should be Administrators only

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#574]
When you first install Backdrop, people are allowed to create accounts, but administrator approval is required.  This is not a great default.  No one should be able to create accounts until an admin decides the site is ready.  Let's change this.

------
PR https://github.com/backdrop/backdrop/issues/2600

**Comment by klonos** [comment]
A couple of thoughts here...

For long time, a thing that I consistently do after each installation is to create a "Site owner" role on each site I build because I like to reserve the "Administrator" role for people that have "super powers" (either me or an in-house person of the company I build the site for). I usually find myself in the situation where site owners request a little bit more power like being able to manage user accounts and in some cases rearranging menu items for certain menus etc.but adding them to the admin group feels to risky because they might actually break the site (accidentally disable/remove modules for example).

If other people find this use case to be a common thing for them too, then I propose to differentiate ourselves from Drupal and add a new "Site owner" role out of the box that has the permission to add/delete user accounts as well as assign roles to them (other than the "admin" role of course) but not the right to edit permissions for roles or add new roles. I mean usually in my experience leaving the permission to manage user accounts to the site admin role puts the overhead of managing user accounts on the site admin. In other words, you have these use cases...

- site owners calling you (site admin/builder) to manage their users. Who wants that?
- site owners requesting the permission to be able to manage user accounts themselves.

Both the above scenarios lead me to creating a "Site owner" role as I said and I'd absolutely love it if this was a Backdrop out-of-the-box feature. Let me know if you feel the same way and I'll file a new issue.

**Comment by klonos** [comment]
...now for the "Registration and cancellation" section of the "Account settings" page (```/admin/config/people/settings```):

1. Why are there both a "Visitors, but administrator approval is required" radio button option as well as the "Require e-mail verification when a visitor creates an account." checkbox for again? UX WTF?

2. "When cancelling a user account" has the following options and respective use cases (the way I see it):

- "Disable the account and keep its content." is for when say a content author leaves the company/site but their content needs to be kept intact along with their name for credit purposes.
- "Disable the account and unpublish its content." is for when some automated procedure deemed a user to be a *potential* spammer, so disable + unpublish but wait for moderators to approve or decide for final deletion.
- "Delete the account and make its content belong to the Anonymous user." I never needed but I guess content authors leave but there is need to keep their content without any credits to them.
- "Delete the account and its content." is for verified spam.

Now out of these use cases I think that the second is more common and "safe", so we should default to that. Either that, or make the entire "When cancelling a user account" section a list of checkbox options and call it "Available actions when cancelling a user account". This would add an additional step to the cancellation process of having to decide what to do with both the user account and it's content. Here's a possible mockup of that dialog:

```
User cancellation for the following account(s):

account1
account2
...

Action to take for the user account(s):
( ) Disable
( ) Delete

These accounts have site content associated with them.

Action to take on [user_name] account's content:
( ) Keep
( ) Unpublish
( ) Make it belong to the Anonymous user
( ) Move it to another user account ...
( ) Delete

[Cancel account(s) and apply actions]
```

What do you think?

**Comment by tjdjours** [comment]
>No one should be able to create accounts until an admin decides the site is ready. 
Excellent. It regularly stuns me that the default is switched on. 

>add a new "Site owner" role out of the box
Useful model, though I think that's too specific a use case to make it a default. There are sites that fall outside that discrete site-admin vs site-owner model or even owner vs user. Thorny to impose it by default, I think.

As an aside, I quite like the idea of having an option to [https://www.drupal.org/project/mail_new_user](customize the message sent to a new user at the time of account creation). Better if it had some orienteering with a link to the default canned form, too.

**Comment by jenlampton** [comment]
I agree that we shouldn't add any more roles to core out of the box.  There are too many possible use-cases out there.  Let's let each site decide what it wants to do with roles.

**Comment by quicksketch** [comment]
I merged in the PR at https://github.com/backdrop/backdrop/issues/678, which closes the relevant issue automatically. If we'd like to discuss adding more roles out-of-box, let's make another issue for that one.

**Comment by klonos** [comment]
...while working on #3170 I've noticed that still the default OOTB is "Visitors, but administrator approval is required". Huh!? Anyone care to confirm?

**Comment by Wylbur** [comment]
During the profile install, the config_set function is run that redefines the user_register value. There are 3 profiles, Testing, Minimal and Standard.  All three profiles reassign user_register to USER_REGISTER_VISITORS_ADMINISTRATIVE_APPROVAL.

@quicksketch 
Should we update all of these to the new value - USER_REGISTER_ADMINISTRATORS_ONLY?

I can test this locally and confirm it works.

**Comment by quicksketch** [comment]
Just deleting the line from all 3 profiles and letting the default from system.core.json seems like a cleaner approach.

**Comment by Wylbur** [comment]
Tested this solution locally.  It worked for the standard install.  The GUI site installer does not give you the option of selecting the minimal install profile, that probably needs to get called with a command line install instead. 

Running out of time, so did not test the minimal or testing profile process.  But I'm confident that this will resolve the issue with all the profile versions.  We can let the bots test this!

**Comment by herbdool** [comment]
Code looks good

**Comment by herbdool** [comment]
Oops, spoke too soon. I thought the tests had passed but I was looking at wrong one.

**Comment by herbdool** [comment]
Looks good now. Thanks @Wylbur!

**Comment by quicksketch** [comment]
Thanks @Wylbur! Merged https://github.com/backdrop/backdrop/pull/2600 into 1.x for 1.13.0. As this is a change in the default behavior of Backdrop and has the possibility of upsetting assumptions for tests, I've only merged this into 1.x and not 1.12.x.

**Comment by klonos** [comment]
Noting that setting the option for anon users to be able to create accounts should perhaps throw a warning/notice in #3624 and/or the site status page.
