### ISSUE TITLE
Preview of menu machine name is inaccurate while adding a menu

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#5807]
This corresponds to Drupal 7 issue: https://www.drupal.org/node/2021571 

The custom menu add form has an element to show the machine name while the title is being typed. After saving, that machine name is not editable, but is shown on the edit menu form.

During creation (add), if the menu title is "hello," it shows the machine name will be hello. That's not what happens, though. The machine name is actually "menu-hello", and "menu-hello" is what is shown after saving.

**Comment by argiepiano** [comment]
PR https://github.com/backdrop/backdrop/pull/4218

**Comment by argiepiano** [comment]
Before:
<img width="837" alt="Screen Shot 2022-09-27 at 6 11 34 PM" src="https://user-images.githubusercontent.com/9938978/192659127-fdbdc82b-2aeb-482f-9e6d-4a3187a56372.png">

After:
<img width="851" alt="Screen Shot 2022-09-27 at 6 11 49 PM" src="https://user-images.githubusercontent.com/9938978/192659152-35c24b2a-fe0d-4ad8-840f-ec51cc2a19ef.png">

**Comment by olafgrabienski** [comment]
Tested locally, and works for me! An important improvement, in my opinion.

FYI, in Drupal there has also been suggested another interesting approach (remove the `menu-` prefix), but [that issue](https://www.drupal.org/project/drupal/issues/2029197) was closed.

**Comment by kiamlaluno** [comment]
I think that *menu-* is added to avoid conflict between menus added via user interface and programmatically added menus, similarly to the *field* prefix added to fields created via the user interface.

**Comment by bugfolder** [comment]
This discrepancy long bugged me in D7-land. Confirm WFM, also code reviewed (simple!) and looks good. RTBC.

**Comment by klonos** [comment]
I have also reviewed and tested this and it works as expected 👍🏼 

Have you guys noticed the not-related-to-these-changes, per-existing bug where after you click the "edit" link in the machine name the field is shown to allow you to edit it, but the machine name preview and the "edit" link do not go away? ...you can actually see that happening in both the before/after screenshots that @argiepiano provided above. You need to click the "edit" link another time for the preview/edit-link combo to go away.

This must have regressed somewhere else, but I didn't see any linked issue here, and since I've been in a hiatus for a few months, I thought I'd mention it here. Anyone filed any issue for that already?

**Comment by argiepiano** [comment]
> Have you guys noticed the not-related-to-these-changes, per-existing bug where after you click the "edit" link in the machine name the field is shown to allow you to edit it, but the machine name preview and the "edit" link do not go away?

Yes, I noticed that. We should open an issue for that. I started working a bit on the machine_name issue listed in this crossport issue #5770, when I first noticed it. It's a bug in the machine name javascript code.

**Comment by klonos** [comment]
> We should open an issue for that.

Done: #5828

**Comment by quicksketch** [comment]
Thanks folks! I didn't see a reason why this needs to be held for 1.24.0. As a UX improvement we can pull it into 1.23.x. I merged https://github.com/backdrop/backdrop/pull/4218 into 1.x and 1.23.x.

https://github.com/backdrop/backdrop/commit/37f81ecc9603a3db9bbceccd078860d97ff4e7b9 by @argiepiano, @olafgrabienski, @kiamlaluno, @bugfolder, and @klonos.
