### ISSUE TITLE
Fixed: Layouts and Taxonomy Term view context conflict.

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#5809]
## Description of the bug

When using the core-provided (but disabled by default) Taxonomy Term view, conflicts can arise with Layouts.

## Steps To Reproduce

To reproduce the behavior:
1. Enable the "Taxonomy Term" view
2. Create a tag on a Post
3. Create a custom Layout with the `taxonomy/term/%` context and provide a visibility condition of `Taxonomy vocabulary = Tags`
4. Visit the term page for the tag you created in step 2.

## Actual behavior

> Error
> Call to a member function bundle() on string 

## Expected behavior

The new layout should be used without a problem when viewing terms from the chosen vocabulary.

## Additional information

In `core/modules/layout/plugins/access/entity_bundle_layout_access.inc`, modifying `checkAccess()` as follows is a quick-and-dirty fix. It may not be the best long-term fix (hopefully discussion here can help identify the best long-term fix).

Change:

```
    if (!$this->settings['bundles']) {
      return FALSE;
    };
```

To:
```
    if (!$this->settings['bundles']) {
      return FALSE;
    }
    else if (empty($entity->bundle)) {
      return TRUE;
    }
```

**Comment by indigoxela** [comment]
Wow, confirmed! I followed the steps - as soon as one adds the *visibility condition* things break - maybe that's the reason why I never saw this error before.

```
Error: Call to a member function bundle() on string in EntityBundleLayoutAccess->checkAccess() (line 77 of ...core/modules/layout/plugins/access/entity_bundle_layout_access.inc).
```

**Comment by indigoxela** [comment]
A little debugging... At that point (checkAccess) the data for terms and nodes differ.

`$this->contexts[$this->entity_type]->data;` contains the full Node object for node visibility conditions, but for terms it's simply the TID. Note: only if the term pages are _views_. The regular term pages have the full TaxonomyTerm object in context data.

Seems like Layout loads the term when the path is `taxonomy/term/%term`, but views provides `taxonomy/term/%` - no loading, no object.

Funny "workaround": set the views path to `Path: /taxonomy/term/%term`, then the view works again, as the "load callback" loads the required entity.

**Comment by argiepiano** [comment]
> Seems like Layout loads the term when the path is taxonomy/term/%term, but views provides taxonomy/term/% - no loading, no object.

In fact this will also work if you change the view path to anything other than `taxonomy/term/%` - you can have `taxonomy/term/%apples` and the workaround still works.

The problem lies in the `menu_router` table and the loader function defined there:

- When the view is disabled, the load_function for `taxonomy/term/%` is `taxonomy_term_load`, which returns a fully loaded taxonomy entity which is stored in the corresponding `$router_item`, which is then picked by Layout

- When the view is enabled, the entry in `menu_router` changes. The load_function is now `views_arg_load`. The problem is that this function (since it's used internally by views) doesn't return a fully loaded entity. It returns the $value argument (tid in this case).  So, that gets stored in the `$router_item`, and gets picked up by Layout in the context data - an ID instead of an entity.

It's unclear what the best solution is. The easiest fix would be to change the View path to `taxonomy/term`  - the `%` is really not needed, since the argument is at the end of the path. Views will pick up that argument without a need for the `%`. By making this change, we preserve the `menu_router` entry `taxonomy/term/%` AND its loader (`taxonomy_term_load`).

Another approach would be for the layout access checks to verify whether we have an object or and ID, and to load the entity if it's an ID...

**Comment by laryn** [comment]
I can confirm that changing the path of the "Taxonomy Term" view from `taxonomy/term/%` to `taxonomy/term` fixes the immediate problem!

**Comment by indigoxela** [comment]
@argiepiano many thanks for your in-depth recherche. Wow, I wasn't aware that when skipping the placeholder completely or adding a nonsense one (like %foobar), the view still works as expected. Also in D7 BTW.

I did a quick check with the feed (attached to the views page), but that's not affected by the conflict.

It's good that we have a solution for the immediate problem (adapting the path), but we should really prevent any php errors on views pages.

> It's unclear what the best solution is.

Totally. People coming from Drupal will still use the `%`, as they're used to it. Catching it in the layout access check might be the option with the smallest required change.

**Comment by laryn** [comment]
I'm afraid my excitement was premature -- changing the URL seems to disable the layout from being attached to the View after all. I got excited because the error went away but the functionality is not fixed quite that simply.

I'll submit a PR shortly to do this check in `checkAccess` and load the entity if needed.

**Comment by laryn** [comment]
Here's a PR. What do you think?
https://github.com/backdrop/backdrop/pull/4225

**Comment by indigoxela** [comment]
> ... changing the URL seems to disable the layout from being attached to the View after all

@laryn strange, I can't reproduce that. On my local testing site the layout works if I change the views path (I tried with %term, %foobar and with no placeholder at all).

However, I agree that we need to fix that in core - forcing admins to change the view to prevent errors seems like a workaround.

Tested in the sandbox - the PR works as expected. :+1:

**Comment by argiepiano** [comment]
@laryn, the solution works for this particular case and this particular method, checkAccess. However I wonder if this should be done at the `__construct` level, since this particular class, `EntityBundleLayoutAccess`, always expects $this->contexts[$this->entity_type]->data;` to contain a fully loaded entity.  To do this we would need to modify `EntityBundleLayoutAccess:__construct()`

**Comment by indigoxela** [comment]
@argiepiano I belief, @laryn is aware of that - he cautiously asked for feedback. :wink:

We're currently not aware of any other situation, where this problem might arise. AFAIK any other approach requires much bigger changes.

Your suggestion with EntityBundleLayoutAccess:__construct() seems interesting - is there a chance to make it backwards compatible?

**Comment by argiepiano** [comment]
Of course, @indigoxela; my comment was also cautious feedback. 😉  

The solution I propose is simple, and it is backward compatible as it doesn't change any property at all. Basically, moving the code @laryn suggested to the construct method (instead of having it in the checkAccess method), and nipping the problem from the bud. It would look like this:

```php
  /**
   * Constructor for a Layout access rule.
   */
  function __construct($plugin_name, array $data = array()) {
    parent::__construct($plugin_name, $data);
    $this->settings += array(
      'bundles' => array()
    );

    // Set entity type.
    $info = layout_get_access_info($plugin_name);
    $this->entity_type = $info['entity_type'];

    // @laryn's code starts here
    $entity = $this->contexts[$this->entity_type]->data;
    // Make sure we're testing an entity here. Views could override system
    // paths and cause difficulties. See issue #5809.
    if (!is_object($entity)) {
      $this->contexts[$this->entity_type]->data = entity_load($this->entity_type, $entity);
    }
   // @laryn's code ends here
  
  }
```

The benefit of doing it this way is that classes that extend `EntityBundleLayoutAccess::checkAccess()` don't have to worry about loading the entity if it's not available. By definition, `EntityBundleLayoutAccess::$contexts[$this->entity_type]->data` should always be an entity.

**Comment by docwilmot** [comment]
> When the view is enabled, the entry in menu_router changes. The load_function for taxonomy/term/% is now views_arg_load. 

Curious, why does this loader get called for Taxonomy but not other entity paths?

**Comment by laryn** [comment]
> strange, I can't reproduce that. On my local testing site the layout works if I change the views path (I tried with %term, %foobar and with no placeholder at all).

@indigoxela, At first I thought it was working but my layout used the `taxonomy/term/%` context, and I believe when changing the Views path it no longer matched. The error disappeared but it seemed to be because it was reverting to use the standard taxonomy listing rather than the view.

@argiepiano That seems to make sense, I'll try adjusting the PR.

**Comment by laryn** [comment]
@argiepiano It doesn't seem that contexts are available yet in `__construct`:

![2022-10-04_12-11](https://user-images.githubusercontent.com/871421/193883417-c150a6da-f8a8-4da2-b62e-656bc9a8c318.png)

**Comment by argiepiano** [comment]
> @argiepiano It doesn't seem that contexts are available yet in __construct

Yes, you are right. Context is added later on a call to the method `setContexts` which in turn calls `layout_set_handler_contexts`.

**Comment by laryn** [comment]
Since we have a `pr - works for me` tag, I'll add a milestone as well. (I had to [look up to make sure it was okay](https://docs.backdropcms.org/documentation/adding-milestones-to-issues) to do so first since I opened this issue).

**Comment by laryn** [comment]
@klonos I committed your suggestion.

**Comment by jenlampton** [comment]
The proposed solution looks simple, RTBC from me. I would like @quicksketch to do a second review though, since he has a deeper understanding of layouts and whether doing this load earlier might be possible. (maybe in `setContexts()` or something?)

**Comment by quicksketch** [comment]
I've run into this problem with Views and Layouts interfering with each other, I'm not sure what to do other than something similar to the provided fix. The issue is that when a normal menu item exists like `taxonomy/term/%taxonomy_term`, the menu item is converted to a full entity. But when Views overtakes the same path, it puts in place a placeholder like `taxonomy/term/%`, with no autoloader. The menu paths are now actually different things, and Layout doesn't really know which one it's going to get.

Changing this is non-trivial because Views could actually take over any path and change what an argument means. Even though it wouldn't make sense, Views could make `taxonomy/term/%` work with a Node ID or User ID, it's a completely arbitrary mapping that obeys the configuration of the view.

So let's proceed with the current work-around, since it so clearly demonstrates itself when enabling the out-of-box disabled Term Listing view.

**Comment by quicksketch** [comment]
Thanks folks! I merged https://github.com/backdrop/backdrop/pull/4225 into 1.x and 1.23.x.

https://github.com/backdrop/backdrop/commit/0fd1554ef4d9efee9fc684daf383810c2763e581 by @laryn, @argiepiano, @indigoxela, @docwilmot, @klonos, @jenlampton, and @quicksketch.
