### ISSUE TITLE
Fixed: Token browser disappears below viewport when resized.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5841]
## Steps To Reproduce
1. Go to the configuration page of any content type (or any page that has a token browser link, such as `admin/config/urls/path/patterns`)
2. Click on "Browse available tokens"
3. Try dragging and dropping the dialog that pops up -> that works fine 👍🏼 
4. Try resizing the dialog -> it disappears! 👎🏼 

## Actual behavior
The token browser dialog disappears (is moved outside viewport actually*)

## Expected behavior
The token browser dialog stays in place when/after resizing it.

## Additional information
If you have a big monitor and it's set to very high resolution, you will see that the dialog actually gets moved to the bottom of the page. If it is not visible, then simply scroll to the bottom of the page, and you can find and drag it back within viewport ...but once you try to resize it, this whole disappearing/moving of the dialog keeps happening.

**Comment by argiepiano** [comment]
This is very hard to debug. A couple of observations:
- Even before resizing, the page "grows" to the bottom when you open the token tree dialog. This shouldn't be happening (the element has a `position: relative` instead of `position: absolute` - see below)
- The dialog element on the page has some inline css that's added by one of the jquery ui plugins (not sure yet if it's jquery.ui.position or jquery.ui.resizable).  I'm seeing some differences between this inline css, and the one added in the multiple examples of jquery ui dialog found online. The most noticeable is the fact that, in Backdrop, the element uses `position: relative` inline, while in the other examples, this is `position: absolute` (which explains why the page grows in Backdrop).   When you resize the Backdrop dialog, the `top` inline css suddenly becomes `0`, and therefore the dialog is moved back to its original position (at the bottom of the page). 

I hope this helps someone...

**Comment by argiepiano** [comment]
Here's one more observations:

In Backdrop, the `position: relative` inline css I mentioned in the previous comment is added even if the dialog is not resizable nor draggable. This is not the case when you use jQueryUI dialog outside of Backdrop. Outside Backdrop, the `position` inline css property is ONLY added if the dialog is resizable. So, I suspect that this Bakdrop's `position: relative` css is being added somewhere else within Backdrop js libraries. This may be partly to blame for the problems seen in this issue, as I explained above. 

To compare dialogs between Backdrop and plain jQuery UI, you can use the following plain HTML snippet (just paste into a file like `test.html` and open directly in the browser). This code opens a dialog widget that's neither resizable nor draggable. Check the element with your browser's dev tools - the inline `position` css is not present, unless you make the dialog resizable. 

<details>
<summary>Plain HTML</summary>

```html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>jQuery UI Dialog - Default functionality</title>
  <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.0/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.js"></script>
  <script>
  $( function() {
    $( "#dialog" ).dialog({
       resizable: false,
      draggable: false
    });
  } );
  </script>
</head>
<body>
<h1>
  Hello!
</h1>
<div id="dialog" title="Basic dialog">
  <p>This is the default dialog which is useful for displaying information. The dialog window can be moved, resized and closed with the &apos;x&apos; icon.</p>
</div>
 
 
</body>
</html>
```
</details>

Then, to compare and see that the css `position` property is STILL included in Backdrop even when the dialog is not draggable or resizable, you can edit `system.pages.inc` lines 26 and 27 to make those false (**IMPORTANT**: `resizable` is MISSPELLED in this file. The correct spelling for the dialog setting is `resizable`, not `resizeable`). 

NB: I'm being careful to use the same versions of jQuery and jQuery ui in the snippet above.

**Comment by klonos** [comment]
> NB: I'm being careful to use the same versions of jQuery and jQuery ui in the snippet above as in Backdrop.

Thanks @argiepiano 👍🏼 🙏🏼 ...you have gotten much further in your investigation that I could have.

**Comment by argiepiano** [comment]
Bingo!... sort of

This issue is solved by adding the following line to the definition of `.ui-dialog {}` in `core/themes/seven/css/style.css`

```css
  position: absolute;
```

And here's an explanation/hypothesis:

1. The jQuery UI dialog plugin creates an inline css for the dialog element that includes `position` based on the `position` property already applied to the element. This is done within the method `_makeResizable()` of the jQuery UI dialog plugin
2. The css class `ui-dialog` is added to the dialog element early on, during method `_createWrapper()` of the dialog plugin. 
3. In a typical webpage situation that loads "normally" (i.e. not through an ajax call)  (for example, all the examples of dialog plugin available online, and the snippet I added above), the css class `ui-dialog` would be available through the loaded  in `core/misc/ui/jquery.ui.dialog.css`
4. The problem is that `core/misc/ui/jquery.ui.dialog.css` is loaded through an ajax call in Backdrop. So, we end up with a situation when both the plugin js files (`jquery.ui.dialog.min.js`, `dialog.js` and `dialog.ajax.js`) AND all the related css files are loaded through ajax, and apparently, the newly loaded js can't "see" the newly loaded css files. Those new css classes are only available after the js plugin has done the things described above
5. Thus, we have a dialog element in the DOM that doesn't have an `absolute` position, and this creates the whole problem

So, why does the solution above (single line in style.css) work? Because style.css is loaded when in the first page request, not the ajax call. Therefore `ui-dialog` now contains `position: absolute`, and the plugin is able to do its thing normally.

I can submit a PR, but it'd be good if someone could confirm my suspicion that the ajax-loaded JS cannot "see" the ajax-loaded CSS.  My PR will effectively duplicate the property `position: absolute` in both `style.css` and `jquery.ui.dialog.css`, but I don't see any other way to solve this (unless there is a way to force the ajax-loaded js to run after the ajax-loaded css takes effect).

I have encountered a similar issue before, in a couple of occasions. My solution then was to force-load the library `backdrop.dialog.ajax` in the **first page call**, rather than relying on an ajax-load of the library, as this always resulted in defective looking dialogs (shrunk, too small, etc) regardless of any setting I tried in the configuration of the element. 

I suspect something like this is happening in issues https://github.com/backdrop/backdrop-issues/issues/5835 and in contrib, https://github.com/backdrop-contrib/paragraphs/issues/140

**Comment by argiepiano** [comment]
PR submitted: https://github.com/backdrop/backdrop/pull/4239

**Comment by klonos** [comment]
Thank you @argiepiano 🙏🏼 

I have tested things in the PR sandbox, and the change seems to be fixing the issue 👍🏼 ...the code change is a very simple one-liner, and it only targets a very specific component (the `.ui-dialog` CSS class). However I'm hesitant to mark this RTBC. I would like people that have more in depth knowledge of the involved bits (js, jQuery UI, CSS) to have another look.

**Comment by argiepiano** [comment]
Thanks, @klonos. What my PR does is, it "anticipates" the `position: absolute` that will be applied by   `core/misc/ui/jquery.ui.dialog.css` after the ajax call. So in fact that addition does not change the end result at all. What it does, is applying that css property (which will be applied anyways) before the ajax call. This is done because the js loaded via ajax cannot "see" the css that has been loaded in the same ajax request.

I'm almost sure this is neither a Backdrop, nor a jQuery problem. I tried reversing the order in which ajax assets are loaded (css first, js second) and this did not make a difference - js scripts don't "see" the ajax-loaded css until they finish executing. But perhaps someone with more experience with http/ajax requests  can chime in to see if there is a way to solve this.

**Comment by klonos** [comment]
Thanks for taking the time to explain @argiepiano 👍🏼 

...as a PS: what about this?:

> ...IMPORTANT: `resizable` is MISSPELLED in this file. The correct spelling for the dialog setting is `resizable`, not `resizeable`.

I've searched for instances of the misspelled instances of the word in our codebase, and there's only 3 of them (as compared to 14 instances of `resizable`). See:
- https://github.com/backdrop/backdrop/search?q=resizeable
- https://github.com/backdrop/backdrop/search?q=resizable

Did this end up being unrelated? Separate follow-up issue?

**Comment by argiepiano** [comment]
I created an issue and PR for the issue related to the token tree dialog. Did not realize there were other misspellings.

**Comment by argiepiano** [comment]
One more piece of info: I just downloaded Firefox, and, unlike Chrome and Safari, there is no patch needed for the dialog to work fine. The dialog works as expected in Firefox, meaning that the ajax-loaded css is applied before the js.

So, this is definitely an issue with Chromium! I have not clue how to report these types of issues, or how to check if it's been reported. A search on Google did not turn in any relevant results.

**Comment by bugfolder** [comment]
Code reviewed, LGTM.

**Comment by quicksketch** [comment]
Thanks @argiepiano, @klonos, and @bugfolder! I merged https://github.com/backdrop/backdrop/pull/4239 into 1.x and 1.23.x.
