### ISSUE TITLE
Fixed: misspelling of dialog's "resizable" JS setting option in `system_token_output()`.

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#5842]
## Description of the bug

The jQuery UI dialog plugin contains a setting option called `resizable` [documented here](https://api.jqueryui.com/dialog/#option-resizable). That option is misspelled in the settings done for the token tree plugin [here](https://github.com/backdrop/backdrop/blob/08d182106e82521a39e6fe11f1ed49a61d77fa8f/core/modules/system/system.pages.inc#L27) in file `system.pages.inc`.

This misspelling has basically no effect; it's ignored. The default for resizable is true anyways.

## Steps To Reproduce

There is nothing to reproduce, as the misspelling doesn't affect the functioning of the dialog ("resizeable" is ignored, and the default `true` takes effect for `resizable`).

Add any other information that could help, such as:
- Backdrop CMS version: 1.23.0

**Comment by argiepiano** [comment]
PR https://github.com/backdrop/backdrop/pull/4240

**Comment by bugfolder** [comment]
Code reviewed (a simple change). Went to test, ran into https://github.com/backdrop/backdrop-issues/issues/5841 (of course). Applying its patch, and then https://github.com/backdrop/backdrop/pull/4240, and the dialog behaves properly and is resizable (which would have still been the case since that's the default).

WFM, LGTM, RTBC.

**Comment by quicksketch** [comment]
Thanks @argiepiano and @bugfolder! Merged https://github.com/backdrop/backdrop/pull/4240 into 1.x and 1.23.x.
