### ISSUE TITLE
Node layout not being used when viewing a node revision

### ISSUE THREAD

**Issue by kswan** [backdrop/backdrop-issues#5915]
## Description of the need

When a node display is configured with a layout, the layout is not used when viewing inactive revisions of the node. Instead of the node layout controlling the display, it falls back to the content type display mode. This is counterintuitive to the user.

## Proposed solution

When a node path is entered in a layout as "node/%", that layout should also be applied to the path "node/%/revisions/%/view".

## Alternatives that have been considered

A workaround/alternative is to clone the layout and change the path of the cloned layout. This means any layout edits need to be applied to both layouts.

## Draft of feature description for Press Release (1 paragraph at most)

Node layouts are now applied when an inactive revision is displayed.

**Comment by bugfolder** [comment]
I will note for implementers that the code that loads the right layout for a node for previews is in `node_layout_load_by_router_item_alter()`. That's probably the place to handle this case, too.

**Comment by kswan** [comment]
@bugfolder, Thank you for the PR. 

I tested the PR and it works for me. 

While reviewing the PR, I noticed a typo that is in the same comment block that was edited. It is part of the comment that wasn't changed, but may be worth including.

**Comment by bugfolder** [comment]
Fixed the typo, thanks. Thanks for the test & review. If you think it doesn't need more testing and/or the code passes review, would you update the labels (and, if you think appropriate, add the RTBC label)?

**Comment by kiamlaluno** [comment]
I tested the preview created for the PR. It works as expected: The layout set for node/% is used also for the revisions. To me, this is good to go.

**Comment by klonos** [comment]
Hey @bugfolder, nitpicking: `testNodeLayoutRevisions()` does the same things twice, once for the original node, and then for the revision of that node. Should we wrap that in a `foreach ($nodes as $node) {}`?

**Comment by bugfolder** [comment]
Sure, done.

**Comment by klonos** [comment]
Thanks @bugfolder (and for fixing that other issue in the PR). RTBC 👍🏼

**Comment by BWPanda** [comment]
I wanted to see the bug in action, so spun up my local sandbox to test this. I created a layout with the path `node/%` and confirmed that viewing nodes used that layout. I then created and checked a revision and confirmed that it didn't use that layout. So the bug was confirmed.

I then decided to see if creating a layout specifically for revisions would work. So created a new layout with the path `node/%/revisions/%/view`. After checking the revision I confirmed that it now used that new layout.

However, on checking the PR sandbox for this issue, I noticed that while it shows the node layout for revisions, it doesn't show the revision layout for revisions. I.e. the node layout is used regardless of whether you've specified a separate layout for revisions or not.

I believe we should allow users to use a dedicated layout for revisions if they so choose, and only show the generic node layout if there isn't a revision-specific one. So marking this as 'needs work' to address that issue.

**Comment by argiepiano** [comment]
> I believe we should allow users to use a dedicated layout for revisions if they so choose

Was it even possible to use a dedicated layout for revision before the PR? I'm not sure.

**Comment by bugfolder** [comment]
I agree that the current PR is an improvement (of course, I'm biased), but I think it should be possible to feed the right revision of a node to a `node/%/revisions/%/view` layout, the same way that `node/preview/type/<id>` fetches the appropriate node from the tempstore and feeds it to the `node/%` layout. But the lack of an easy way to have the Main Content block and to properly interpret the vid in such a layout seems like a bigger impediment.

(There's a workaround to get the Main Content block into the layout. First create the layout as a `node/%` layout and save it; it has the main content block. Then edit the path to `node/%/revisions/%/view`. It keeps the context at position 2, then adds a string pass-through for position 4. But that's not enough to turn that string into the appropriate vid; additional code would be needed.)

For that reason, I think that "Support alternative layouts for node revisions" should be a separate issue. (One might also ask for "Support alternative layouts for node previews" as a separate issue.) Just as using the `node/%` layout for a preview, rather than the default layout, is what most users would expect, using the `node/%` layout for a revision, rather than the default, is also what (I think) most people would expect.

**Comment by bugfolder** [comment]
Ah, the workaround isn't needed, but you need to save the layout before the Node context gets automatically applied. (I was expecting the instant feedback like what happens with `node/%`.)

**Comment by argiepiano** [comment]
> but you need to save the layout before the Node context gets automatically applied.

That's not what I'm seeing. This is working fine as an override for me (before applying the PR here). But after applying the PR, the layout override stops working:

<img width="626" alt="Screen Shot 2023-02-24 at 11 54 37 AM" src="https://user-images.githubusercontent.com/9938978/221267323-e41b5d73-423f-4d22-9f04-833e236477bc.png">

**Comment by bugfolder** [comment]
I just pushed a change that, I think, restores the override. Could you try it out?

**Comment by bugfolder** [comment]
And I figured out why I wasn't seeing the automatically created contexts. I entered the path before entering the layout title, and that (apparently) short-circuited the JS that automatically creates the contexts. (I really dislike a form that complains about what you haven't filled in before you're done filling things in.)

**Comment by argiepiano** [comment]
> I just pushed a change that, I think, restores the override. Could you try it out?

A quick test confirms that fixes it - hopefully the test failure is easy to fix.

I was thinking that a similar fix would be good for preview layout overrides, but apparently I can't override the layout for node previews (even before this patch).

**Comment by bugfolder** [comment]
In fact, we should probably have a test case for both scenarios:

* If a `node/%/revisions/%/view` layout exists, it's used for revisions.
* But if it doesn't, then revisions fall back to the `node/%` layout.

**Comment by argiepiano** [comment]
In fact, adding that `+=` to the **existing** code (line 1687 pre-PR) in `node_layout_load_by_router_item_alter()` also fixes the preview layout override!! Without that, the node preview override doesn't work.

**Comment by bugfolder** [comment]
Well, let's just do that, then, too while we're tinkering under the hood. (I think I feel another test case coming on...)

**Comment by bugfolder** [comment]
All right, new tests have been added for both previews and revisions, and all tests are passing.

**Comment by argiepiano** [comment]
Thanks @bugfolder! This is working well in my local; however, when I run `NodeLayoutRevisionTestCase` locally, this test is failing. Have you tried it locally?

**Comment by bugfolder** [comment]
Yes, I ran and tested it locally from the UI (successfully) before pushing to the PR. (Just ran it again, too, just to confirm.)

**Comment by argiepiano** [comment]
LGTM & RTBC again!

**Comment by quicksketch** [comment]
Yay, great fix everyone! I merged https://github.com/backdrop/backdrop/pull/4320 into 1.x and 1.24.x.

https://github.com/backdrop/backdrop/commit/9cae0e5a064897bc62e37899381c952d3b43b6b9 by @bugfolder, @argiepiano, @kswan, @kiamlaluno, @klonos, and @BWPanda.
