### ISSUE TITLE
[UX] Remove "help text" from new User Role Description

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5932]
## Description of the bug

I really dislike having two different descriptions for one thing (the recent role help text addition, for example) because it gets very confusing for both users and developers to determine when to use which one (and it's often handled incorrectly). 

Even when in the issue where we added the new feature to add role text, core developers got confused several times as to which description was which, and where each should be shown. This problem is worse for contrib developers deciding which to display on their own interfaces, and worse still for people trying to use the software.

The best solution is often the simplest: Have only one description so there is no confusion where to use which one, and everyone always uses it correctly.

I'd like to propose that we remove the "help" text, and leave only the "description" for the user roles. If an additional description is necessary for other purposes, that seems like a good candidate for contrib. 

## Additional information

Add any other information that could help, such as:
- Backdrop CMS version: 1.24.0
- Web server and its version:
- Operating System and its version:
- Browser(s) and their versions:

## Related

This is a follow-up to https://github.com/backdrop/backdrop-issues/issues/5748

**Comment by bugfolder** [comment]
> If an additional description is necessary for other purposes, that seems like a good candidate for contrib.

That's actually already in contrib: [Role Help](backdropcms.org/project/role_help) originally provided two versions (a short and a long version), and although [the short version will be replaced by core's once 1.24.0 comes out](https://github.com/backdrop-contrib/role_help/tree/3_support_backdrop_1_24_0), the long version will still be optionally supported. (Note, though, that the long version in RH is not a 1-for-1 functional match with core's long version, which is why RH's version will still be supported separately.)

**Comment by jenlampton** [comment]
Thanks @bugfolder, that sounds like a solid argument to remove the second description from core. :)

**Comment by bugfolder** [comment]
> a solid argument to remove the second description from core. :)

I had originally suggested a second description in core (so mea culpa?) based on my experience with RH, but I won't fight for its retention. 

But if the removal of the long version goes into core, then maybe RH should have more options and/or clarity about where the long form might show up (e.g., checkbox options for where the current long form shows up), and I would welcome further suggestions in [its issue queue](https://github.com/backdrop-contrib/role_help/issues).

**Comment by klonos** [comment]
> ...because it gets very confusing for both users and developers to determine when to use which one

@jenlampton I am also in favor of keeping things simple, however I think that the help text below each field does a pretty good job explaining the use (and they are really short and to-the-point as well):

> Summary of this role's purpose, shown on the role listing page.

> Description to present when assigning this role on the account edit form.

I also thought that:
- the "audience" of these texts were different: people that only manage user accounts and assign/unassign roles vs. full site admins that also manage permissions and can create/delete roles.
- the purpose of these texts is different: a full-blown description for site admin eyes only, which can be as lengthy as required (since only shown in the table in the role management page) vs. a very short description, to be shown in the limited space of the user creation/edit form.

Given the proximity of the 1.24 release, I'm not too fussed either way. Just trying to say that I see no problem.

**Comment by quicksketch** [comment]
I don't know what we can do about this. We are hours away from the 1.24.0 release; after which we can't remove this property because it creates a (very minor) API break.

In the PR there is an issue that the description text is incomplete/inaccurate:

![image](https://user-images.githubusercontent.com/100206/212568524-519c6118-361d-444f-81cb-906f87c4084f.png)

> Summary of this role's purpose, shown on the role listing page.

The description is now used not only on the role listing page but also when assigning roles. Either the description should be taken off the role assignment checkboxes, or the description here should include both uses, something like `Summary of this role's purpose, shown on the role listing page and when assigning this role on user account forms.`

**Comment by bugfolder** [comment]
> Summary of this role's purpose, shown on the role listing page and when assigning this role on user account forms.

That looks pretty good.

**Comment by jenlampton** [comment]
> however I think that the help text below each field does a pretty good job explaining the use (and they are really short and to-the-point as well):

The problem is that even when we are referring to the two descriptions in the issue we (core developers) are calling them by the wrong names and getting them backwards. That description on the form didn't seem to help us when we were no longer looking at the form :)

When I first went to test the issue I was really thrown by the fact that there were two role descriptions, and the fact that one of the was called "help text" (when the machine name is `description`) is also confusing. 

I just think we avoid all of that confusion by introducing only one description. It will be a lot better than what we have now, and we will have the opportunity to add a secondary help text field later (without an API break) if it seems necessary.

I'm going to update this PR with the recommended help text `Summary of this role's purpose, shown on the role listing page and when assigning this role on user account forms.`

**Comment by jenlampton** [comment]
I closed the other issue in favor of this one, and https://github.com/backdrop/backdrop-issues/issues/5940.

**Comment by klonos** [comment]
Code looks good, and things seem to be working as expected. RTBC 👍🏼

**Comment by quicksketch** [comment]
Seems fine to me too. Let's merge this to get moving on the other release checklist items.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/4311 into 1.x for 1.24.0, which acts as a "half-way revert" of the feature added in https://github.com/backdrop/backdrop-issues/issues/5748.
