### ISSUE TITLE
Clean install on Pantheon has "Temporary files directory" error... also it points to Drupal.org

### ISSUE THREAD

**Issue by kreynen** [backdrop/backdrop-issues#594]
![temp_file_message_on_pantheon](https://cloud.githubusercontent.com/assets/385234/5784096/62da30e2-9d86-11e4-99b5-f852179a3fad.png)

Not sure if this is a false positive for all Nginx servers or Pantheon specific yet.  

Couldn't find any issues that referenced Backdrop's plan for documentation about Drupal Security Alerts you are merging into Backdrop.  Should those point to Drupal.org or are you going to replicate that info on Backdropcms.org?

**Comment by quicksketch** [comment]
> Not sure if this is a false positive for all Nginx servers or Pantheon specific yet. 

Thanks, I think this is because Pantheon uses a different mechanism to ensure its temporary directory is secure. If you visit the file system page, can you just save the settings page to fix the error? We might also consider if we should just suppress this error entirely if the site isn't running on Apache in the first place, because the .htaccess file does nothing unless it's Apache in the first place.

> Couldn't find any issues that referenced Backdrop's plan for documentation about Drupal Security Alerts you are merging into Backdrop. Should those point to Drupal.org or are you going to replicate that info on Backdropcms.org?

Going forward, we'll publish our own security announcements. We're set up for upcoming SAs at https://backdropcms.org/security.

**Comment by klonos** [comment]
I have a local nginx setup (on Windows). I see no such error, so I guess it's not nginx-specific ...unless it's nginx + platform specific.

**Comment by jenlampton** [comment]
I'm not seeing this problem on my Backdrop site on pantheon. Going to close this issue, but please re-open if you see this happen again.
