### ISSUE TITLE
Add a `changed` (last updated/last modified) property to the `User` object.

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop/backdrop-issues#5944]
## Description of the bug

Drupal 7 has a `changed` field in the `users` table that recorded when the user was last updated. 

(EDIT: This was added in [7.83](https://www.drupal.org/project/drupal/issues/1835754). See https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/User.20account.20updated.20or.20changed/near/322036230)
~~This is missing from Backdrop, but I cannot find a change record, so it appears as though this is an oversight.~~

## Steps To Reproduce

To reproduce the behavior:
1. Check users table
2. Check Users view (`admin/people/list)

## Actual behavior
No field present in database and no record of when changed.

## Expected behavior

Has `changed` field in db
Has last updated field or similar in users view

## Additional information

Add any other information that could help, such as:
- Backdrop CMS version: 1.24.0
- Web server and its version: N/A
- Operating System and its version: N/A
- Browser(s) and their versions: N/A

**Comment by argiepiano** [comment]
It's not that this was removed in Backdrop. Rather, this is something that got added to D7 last year. See: https://www.drupal.org/project/drupal/issues/1835754

**Comment by argiepiano** [comment]
Oops - just saw your edit.

**Comment by herbdool** [comment]
I created a PR. No idea if it'll pass. It still needs to be added to the user admin View - D7 doesn't use Views for admin.

**Comment by yorkshire-pudding** [comment]
I've managed to test the work so far by putting the token in the users url pattern and that bit works as expected.

**Comment by kiamlaluno** [comment]
I am confused by the following comment.

```php
  // The "changed" column was renamed to "access" in system_update_136(), and
  // the "changed" index on "access" column may persist on old MySQL databases.
```

The *access* column is for the last time the user accessed the site, while *changed* should be the last time the user account has been changed.

**Comment by argiepiano** [comment]
> I am confused by the following comment.

That seems to be a copy/paste of a comment in the code source for this PR. What it says there is that, In Drupal 5 (!!) before `system_update_136()`, the users table had an indexed column named `changed` that was renamed to `access` on that update. That column was used to store when the user had access the site (in D5). So, this is warning the site admin that, if you have a site that was started in D5, that column index may still exist and will be removed before adding the new `changed` column.

The comment could be clearer.

**Comment by kiamlaluno** [comment]
@argiepiano I thought the comment was about a change in Drupal 7. Indeed, that is a change happened in Drupal 5, and that explains why I was not able to find `system_update_136()` in Drupal 7 not Backdrop.

**Comment by herbdool** [comment]
I can add a link to that comment.

What's the best way to handle the user_admin View in the update hook? Should it add the `changed` column to that View even if it has been customized? Or only to default ones? We must have previous examples in some other update hooks...

**Comment by herbdool** [comment]
Ready for review and testing. It now has the changed column in the user_admin View too (if it wasn't previously customized).

**Comment by yorkshire-pudding** [comment]
I've tested but changing the account doesn't seem to change the value.  I've tested the following:

- change email address
- change username
- add role
- remove role
- change timezone

The changed field remains the date of creation.

**Comment by herbdool** [comment]
@yorkshire-pudding ah yes, I made a couple silly mistakes and I hadn't actually tested that. Works for me now.

**Comment by yorkshire-pudding** [comment]
Thanks @herbdool - I've tested that with a couple of accounts and different types of changes and it's now working perfectly.
WFM 👍

**Comment by herbdool** [comment]
I'm wondering if anyone can test running the upgrade on an existing site. I noticed some people had problems with Drupal bootstrapping here https://www.drupal.org/project/drupal/issues/1835754#comment-14694812 before the update happens.

**Comment by argiepiano** [comment]
@herbdool thanks for providing this PR, and @klonos, thanks for the code review. I've left a couple of comments in the PR. 

I tested updating an existing site with users. The update worked fine - I did not encounter any bootstrapping problem.

**Comment by argiepiano** [comment]
@herbdool, I've found a situation when Backdrop will not allow you to bootstrap - because of a fatal error. This is serious.

1. Patch core with this PR
2. Do not run update.php
3. Clear caches
4. Load a user (e.g. view `user/1`)

So, what this does is, it caches the new schema (which includes `changed`) without having created the new `changed` column in the `users` table. So when you load a user, the controller class tries to load that column, and fails. 

This situation is most likely to occur for multi-sites installations. The admin would download the new Backdrop version, and run update.php on one of the sites. Then forgets to run update on the other sites. Then someone clears that site's cache, and everything explodes.

**Comment by argiepiano** [comment]
This is a possible way to catch the situation I described above:

```php
function user_schema_alter(&$schema) {
  if (backdrop_get_installed_schema_version('user') < 1025) {
    unset($schema['users']['fields']['changed']);
  }
}
```

This `unset` doesn't affect the table itself, but rather the column definitions, if the update hook 1025 hasn't been run. We could also add a `watchdog` call here.

**Comment by herbdool** [comment]
@argiepiano I've included your suggested code but haven't tested it.

**Comment by argiepiano** [comment]
Thanks, @herbdool. In D7, there was [a report of this WSOD situation](https://www.drupal.org/project/drupal/issues/3259997), but there, the maintainers decided not to use the preemptive code I suggested above and rather trust that site admins would follow the common procedure for all their sites (including in multi-site installations) of putting the sites in maintenance mode and run update.php in all of them.

Should we also follow this approach, or use the code above?

**Comment by herbdool** [comment]
I think we want to make it easier for site owners or admins. Not everyone will follow the right order.

**Comment by herbdool** [comment]
I could go either way. Can't hurt to add a warning in the watchdog so there's more context.

**Comment by argiepiano** [comment]
@herbdool thanks for adding the watchdog call. There is a problem with that now: the third parameter should be an array, not an int. This is creating a fatal error when you view the dblog

**Comment by argiepiano** [comment]
@herbdool thank for fixing the watchdog problem. Now that it's fixed I have found an issue that may be uncommon, but kind of give me pause about the whole idea of doing calling `watchdog()` inside `user_schema_alter()`.

I am testing clearing the cache without running update. I have a module (emaillog) in one of my sites that emails me the watchdog entry when there are watchdog messages. This module uses hook_watchdog() to catch any new entries, and it uses token replacements.

So,  since the watchdog call is being done inside `user_schema_alter()`, there is something in the process of token replacement that is attempting to load some entities. The problem is that, at this stage of the bootstrapping (inside `hook_schema_alter()`), the entity info is not yet complete (it's missing the key `schema_fields_sql`, which gets added later in the process). This is causing a fatal error. The site basically can't bootstrap again unless I revert the patch. 

So, it seems like invoking `watchdog()` inside `hook_schema_alter()` in these situations may have bad consequences in some instances as well. I'm inclined to say - let's not call `watchdog()` there just in case, and let's rely on the "red dot"   to alert the site admin that they have to run the update. What do you think?

**Comment by herbdool** [comment]
Let's remove it. I searched all core `*.install` files and didn't find any instance of watchdog being called (aside from this PR).  So on the safe side this PR should avoid it too.

**Comment by argiepiano** [comment]
WFM and RTBC! Thanks, @herbdool.

**Comment by argiepiano** [comment]
Should there be a change record for this?

**Comment by quicksketch** [comment]
I looked over the PR and it looks awesome! What a comprehensive set of changes, including Token and Views module updates. Great job folks!

**Comment by quicksketch** [comment]
Thanks folks! I merged https://github.com/backdrop/backdrop/pull/4322 into 1.x for 1.25.0!

This does not need a change record since it's not an API break, it's simply a new feature. However, I do think that adding a `@since` line to indicate when this was added wouldn't hurt, so I filed and merged a follow-up at https://github.com/backdrop/backdrop/pull/4391.

**Comment by jenlampton** [comment]
does this need a change record?

**Comment by quicksketch** [comment]
I don't believe so because it's not an API change, it's an addition.
