### ISSUE TITLE
Add a language switcher to the admin bar when locale is enabled

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#5983]
Add a language switcher to the admin bar when locale is enabled. This is handy for the admin pages for when someone wants to switch. I have often added the current core switcher to the admin layout but it looks clunky especially if there is more than 2 languages.

**Comment by herbdool** [comment]
@olafgrabienski @kiamlaluno This has a PR now if you're interested. I was first able to create a custom module but went the route of seeing if it's good enough for core first. See what people think and if it's not for core, then I can make it a contrib module.

**Comment by kiamlaluno** [comment]
I tried the preview site created for the PR, but I was not able to see the language switcher, although I enabled the Language and Locale module, and I added Italian and Esperanto as languages.  
On /admin/config/administration/admin-bar, *Locale links* was checked.

I guess I forgot to enable something, but I do not know what that should be.

**Comment by herbdool** [comment]
You also need to go to config > admin bar and enable it there. Maybe we should enable it by default?

**Comment by kiamlaluno** [comment]
@herbdool Is not that /admin/config/administration/admin-bar? Because there, all the checkboxes are selected.

**Comment by herbdool** [comment]
@kiamlaluno I logged into the test site. I had to enable the URL option for Detection and Selection of languages. Then I cleared the cache and it worked.

**Comment by olafgrabienski** [comment]
Tested in the PR sandbox prepared by the both of you. I've translated a couple of interface terms to Italian to see if the language is really switching, and it is. So, works for me!

**Comment by klonos** [comment]
@herbdool I have left a couple of comments/suggestions in the PR. In addition to those:
- can you please provide a link to the fonticon you have used to generate the icon?
- in order to increase the discoverability of this feature on existing sites (where I'm assuming we won't enable the option automatically), can we please make it so that:
  - the checkbox is still available even when the Locale module is disabled, but have the checkbox be disabled, with a note in its description saying that it only becomes available when the Locale module is enabled
  - when the Local module is enabled, we throw a message (in `locale_install()`), letting people that this option is available + a quick link to the admin bar settings page

**Comment by kiamlaluno** [comment]
@herbdool Yes, now it works for me too.

**Comment by herbdool** [comment]
@klonos:
Icon: https://fontawesome.com/v5/icons/language?s=solid&f=classic (I looked in the same fontawesome version as used for the layout icon in admin_bar.
I've incorporated your suggestions. Though I figured, why not just enable it right away if locale module is enabled? I think it's useful for almost all multilingual sites.

**Comment by herbdool** [comment]
Thanks @kiamlaluno and @olafgrabienski

**Comment by klonos** [comment]
Thanks @herbdool ...there were a few options for the language icon, and I just wanted to make sure that we were using the free version and not one of the "pro" ones. All good 👍🏼 

> Though I figured, why not just enable it right away if locale module is enabled? I think it's useful for almost all multilingual sites.

I'm fine with that as well 👍🏼

**Comment by klonos** [comment]
@herbdool last round of suggestions in the PR and this is good to go 👍🏼

**Comment by olafgrabienski** [comment]
> Maybe we should enable it by default?

Thinking again about the language switcher, I'd say it shouldn't be enabled by default for *localized* but for *multilingual* sites (check for _Content Translation_ module instead of _Locale_). In my opinion, on localized sites the switcher makes only sense for developers and site architects (who are used to the original English interface, or need them for bug reports etc), but not for editors.

Slightly off topic, speaking of options for certain people: Does anyone know of a permission (request) to enable individual Admin bar settings only for some roles?

**Comment by klonos** [comment]
🤔

**Comment by herbdool** [comment]
Made small changes. Needs another test and review.

**Comment by olafgrabienski** [comment]
@herbdool Thanks for updating the PR! I've had another look at the sandbox, and it still works works for me. Is there a way to test the 'by default' part regarding *Content Translation* in the sandbox. I guess that's only possible in a local environment :-/

**Comment by stpaultim** [comment]
I tried testing it and at first it did not seem to work, because the checkbox was off on the admin bar settings. 

I restarted the PR sandbox, enabled the locale and language modules, added German language (included the translation file), and it seems to work fine. 

I endorse this PR 100%, because earlier this week I tried to test the localization of a test site and had some difficulty figuring out how to change from English to German interface. I ended up enabling a switcher block in the header of the front page. This is much better. 

Good work. I did not test extra scenarios, but I think it's working.

**Comment by herbdool** [comment]
@stpaultim thanks. Willing to update the testing label? I think we can get it in for 1.25. just need someone to also review the code. Perhaps @laryn or @kiamlaluno ?

**Comment by kiamlaluno** [comment]
I checked the PR changes; I did not find anything wrong.

**Comment by herbdool** [comment]
@kiamlaluno are you willing to update the label to ready to commit?

**Comment by argiepiano** [comment]
@herbdool I gave this a try and I have some question, which may actually be issues. I installed this in an existing multilingual site:

- The switcher was enabled after update 👍🏽 
- There is no icon for the switcher (see image). Not sure if this is expected behavior
<img width="402" alt="Screen Shot 2023-04-15 at 7 17 15 AM" src="https://user-images.githubusercontent.com/9938978/232226221-1f0a92cb-6b14-4292-a11d-1a73683d9055.png">

- What's most problematic/confusing for me is that the languages are always shown in English, even if I'm switched to another language.  For example, if I'm switched to Spanish, I was expecting to see the switcher show me the names of all other languages in Spanish (Inglés, Francés, Español). Is this not the expected behavior?

**Comment by argiepiano** [comment]
One more issue I'm finding. When I use the switcher I'm always redirected to: `es/admin/config/regional/translate` instead of switching the language for the page I'm seeing right now. 👎🏽

**Comment by argiepiano** [comment]
> What's most problematic/confusing for me is that the languages are always shown in English, even if I'm switched to another language. For example, if I'm switched to Spanish, I was expecting to see the switcher show me the names of all other languages in Spanish (Inglés, Francés, Español). Is this not the expected behavior?

Actually, in the language switcher block provided by Backdrop, the languages are always listed in their native spelling. See below. I think we should keep this in the new functionality added here.
<img width="234" alt="Screen Shot 2023-04-15 at 7 34 14 AM" src="https://user-images.githubusercontent.com/9938978/232227164-dd749ade-1d3c-401b-bea4-4d776ac0fa8f.png">

**Comment by kiamlaluno** [comment]
Is the value returned by `theme_admin_bar_icon_locale()` the expected one (`$language->name`)?

**Comment by argiepiano** [comment]
Regarding the problem with the cached version of the language switcher in the admin bar: currently, the "This page" utility link uses `admin_bar_admin_bar_replacements()` (which is a hook invoked by `admin_bar_preprocess_page()`) to pass replacements to Javascript, which takes care of updating the link to match the currently viewed page.

That's clearly the solution here too.

**Comment by herbdool** [comment]
@kiamlaluno `theme_admin_bar_icon_*()` all return titles. And then the icons are added via the `admin_bar.css` file.

@argiepiano thanks. I was aware of that replacements hook but I hadn't understood how it worked. I now see that it basically has redundant logic to that in admin_bar.inc and then swaps cached items with current ones via jquery. So I've updated the PR.

**Comment by kiamlaluno** [comment]
It must be me again: I added Italian and Spanish as languages, I enabled the URL language detection, I imported translations, verified the admin bar settings enabled the language switcher, flushed the cache more than once, but I do not see the language switcher icon. 😅

**Comment by herbdool** [comment]
@kiamlaluno I am trying to debug something. It was complaining about not finding `$language->native` but while trying to fix that something else didn't work. Not sure what yet.

**Comment by herbdool** [comment]
@kiamlaluno now it should be working again. And the tests pass.

**Comment by kiamlaluno** [comment]
I did not find issues in the preview site. I also added Italian translations to verify the language was effectively switched, and it was.

**Comment by herbdool** [comment]
@kiamlaluno can you change the label to "works for me"?

**Comment by argiepiano** [comment]
I've tested and reviewed the code. RTBC.

**Comment by herbdool** [comment]
Ready for a (last) RTBC.

**Comment by argiepiano** [comment]
WFM and RTBC. Thanks @herbdool!

**Comment by klonos** [comment]
> I guess a solution to this is to modify the "+ Add language" submit handler to clear the admin bar cache.

Yes please. Let's polish this workflow, so that things work as expected.

**Comment by herbdool** [comment]
@argiepiano ready for testing. I did a quick test and it appeared without having to manually clear cache.

admin_bar already had `hook_language_update` and `hook_language_delete` in order to clear cache, so I simply added `hook_language_insert`.

**Comment by klonos** [comment]
@herbdool now there are merge conflicts. Can you please resolve them?

**Comment by argiepiano** [comment]
@herbdool, this works for me (I see you already added RTBC). 

I'm a bit uneasy about the manual removal of the `<ul>` wrappers via `preg_replace()` in  `admin_bar_admin_bar_replacements()`, but I haven't been able to come up with a good alternative. The problem is the way `theme_admin_bar_links()` is written (which is not touched by this PR) - this theming function takes care of theming the items AND adding the `<ul>` wrapper all in one function. I think it would make more sense to have two theming functions, one for the items themselves, and one for the wrapper. That way it would be possible to get the dropdown items without the `<ul>` wrappers, voiding the need to use regex to remove them.  Anyway, this can be addressed separately.

**Comment by klonos** [comment]
> I'm a bit uneasy about the manual removal of the `<ul>` wrappers via `preg_replace()`...

Yeah, not ideal and potentially prone to error 🤔 

> I think it would make more sense to have two theming functions, one for the items themselves, and one for the wrapper. That way it would be possible to get the dropdown items without the `<ul>` wrappers, voiding the need to use regex to remove them.

...or we could tweak the existing `theme_admin_bar_links()` function to accept an additional parameter (optional, with default being to retain the current functionality) which controls whether the wrapper `<ul>` is added or not. It would basically be used in the existing conditional towards the end of `theme_admin_bar_links()`:
```php
  if ($output && $add_wrapper_ul_tag) {
    $elements['#wrapper_attributes']['class'][] = 'dropdown';
    $attributes = [backdrop_attributes](https://docs.backdropcms.org/api/backdrop/core%21includes%21common.inc/function/backdrop_attributes/1)($elements['#wrapper_attributes']);
    $output = '<ul' . $attributes . '>' . $output . '</ul>';
  }
```

We allow API additions, so something like that would be OK 😉

**Comment by klonos** [comment]
...perhaps we could try using the native PHP `strip_tags($theme_locale_links, '<li><a><span>');` which might be a better way?

**Comment by klonos** [comment]
Setting to NW, as I have tried the following in the PR sandbox, which didn't work as I expected it to work:

- Enable the Language and Locale modules
- Added a Language -> no language switcher shown 👎🏼 
- Cleared caches -> still no language switcher shown 👎🏼 
- Added another Language, tried changing the default, their order -> still no joy 👎🏼 
- Enabled the "URL" method in `admin/config/regional/language/detection`, saved, cleared caches -> still nothing 👎🏼 
- Manually changed the language in the URL to `en/admin/config/regional/language/detection` -> still nothing 👎🏼 
- Manually changed the language bit in the URL from `en/...` to the other languages that I had added earlier (`it/...`, `ar/...`) -> the language switcher now showed 👍🏼 (without any cache clear)
- Manually changed the language in the URL to `en/...` -> the language switcher was gone 👎🏼 
- Manually change to one of the other languages to get the language switcher back, then used the language switcher itself to switch to "English" -> the language switcher vanished again 👎🏼

**Comment by klonos** [comment]
...so it seemed that the language switcher was problematic with English. So I tried to switch the default language to something other than English -> all languages worked as expected now with everything from the steps outlined in my previous comment 👍🏼 ...I then switched the default language back to English and tried to reproduce, but now I couldn't - everything worked as expected for some reason 🤷🏼 🤔 

Wondering if anyone can reproduce the same, and if so, then what could be the thing that changes once the default language changes that makes everything work after that's done?

**Comment by klonos** [comment]
...I've set things up on my local and cannot reproduce now 🤔

**Comment by klonos** [comment]
...setting this back to WFM, but if someone has the time to doublecheck by following the steps I've outlined above, it would be great.

**Comment by herbdool** [comment]
@klonos I switched it to use `strip_tags()` - that's a bit cleaner.

**Comment by klonos** [comment]
Thanks @herbdool ...I've left further comments in the PR. Can you please have a look?

**Comment by quicksketch** [comment]
I tested out the sandbox and reviewed the code. Everything is great! I merged https://github.com/backdrop/backdrop/pull/4352 into 1.x for 1.25.0. Thanks @herbdool, @klonos, @kiamlaluno, @argiepiano, @olafgrabienski, and @stpaultim!
