### ISSUE TITLE
[DX] Add `#indentation` property to FAPI elements.

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#5999]
## Description of the need

This request arose from #3292. The solution proposed there by @bugfolder alters to the core radio/checkbox widget form used for displaying the taxonomy term widget.  But there was discussion about the possibility of adding a `#indentation` property to make this feature available to all checkbox and radio elements beyond the taxonomy term widget.

## Proposed solution

Adding a `#indentation` property that would further theme the element using `theme_indentation()`. This function adds `<div>` elements with css class `indentation` to create indentation. 

The new `#indentation` property would take an integer >= 0. 

## Alternatives that have been considered

The alternative is to manually add indentations to the `#options` values before outputting the form element. This is the current solution used in #3292. 

Alternatively, it may be possible to add different css classes to each element depending on their depths. This was an earlier approach in #3292, but it was cumbersome, as it required the creation of several css classes, one for each level.

I will try to provide a PR later today.

**Comment by bugfolder** [comment]
Just wondering too if `'select'` form item should support this, in the same way that `checkbox` and `radios` do (by adding keys to the form that match the `#options` keys). Using the taxonomy term reference selection of https://github.com/backdrop/backdrop-issues/issues/3292 as an example, it would be nice to be consistent and use proper indentation everywhere, rather than indentation some places and dots others.

**Comment by argiepiano** [comment]
PR https://github.com/backdrop/backdrop/pull/4364 submitted.

The PR does the following:
- It adds the property `#indentations` to Form API elements `select`, `radios` and `checkboxes`
- It adds the property `#indentation` to Form API elements  `radio` and `checkbox`

To use:
- `#indentations` is an array keyed by the options ID, with an integer as value indicating the amount of indentation.
- `#indentation` is an integer indicating the amount of indentation

Example:
```php
  $form['my_checkboxes'] = array(
    '#type' => 'checkboxes',
    '#title' => 'Indented checkboxes',
    '#options' => array(
      '1' => 'No indentation',
      '2' => 'One indentation',
      '3' => 'No indentation 2',
      '4' => 'Two indentations',
    ),
    '#indentations' => array(
      '2' => 1,
      '4' => 2,
    ),
  );
```

NOTE: 
- In the case of `checkbox` and `radio`, the new code adds `<div class="indentation">&nbsp;</div>` as provided by `theme_indentation()`
- In the case of `select` elements, [it's currently not possible to indent select options](https://stackoverflow.com/questions/8987028/best-modern-way-of-creating-indentation-in-a-select). Therefore, the new code adds "midpoints" in front of the indented options

This tiny module should be helpful as an example, and to test the code:
[testing_stuff.zip](https://github.com/backdrop/backdrop-issues/files/10832749/testing_stuff.zip)
 
In addition, I had to modify `system.css`, specifically removing the `height` element for `div.indentation`. I'm not sure why this element was preventing the correct rendering of the indented `div` in Basis (but not in Seven). Apparently `height` is not needed - I checked other places in Backdrop that use `div.indendation` and it doesn't seem to affect output.

**Comment by klonos** [comment]
@bugfolder `'select'` does seem like a nice candidate for this new property as well, and we could definitely add it for future use, but not sure how we would implement the indentation in the rendered HTML. You see, `<optgroup>` in HTML only supports one level of "nesting" (and the reason I used quotes in that word is that these are basically acting as un-selectable "dividers").

If you have a look at https://stackoverflow.com/questions/1037732/nesting-optgroups-in-a-dropdownlist-select for example, you'll see how people try to "force" this to happen, by using multiple "bare" `&nbsp;`s (as in not within `<divs>` like we'll be doing here) since margin/padding doesn't seem to be supported by browsers. Some attempt to use classes/CSS in each option, which can only have a finite depth (which is what we are trying to avoid).

**Comment by klonos** [comment]
@argiepiano jinx 😅

**Comment by klonos** [comment]
@argiepiano nice work! 👍🏼 

Instead of (or in addition to?) using an `'#indentations'` array, can we have this behave consistently like the individual `'#description'` that can be added to radio/checkbox options? So instead of this:
```php
  $form['my_checkboxes'] = array(
    '#type' => 'checkboxes',
    '#title' => 'Indented checkboxes',
    '#options' => array(
      '1' => 'No indentation',
      '2' => 'One indentation',
      '3' => 'No indentation 2',
      '4' => 'Two indentations',
    ),
    '#indentations' => array(
      '2' => 1,
      '4' => 2,
    ),
  );
```

...we could do this:
```php
  $form['my_checkboxes'] = array(
    '#type' => 'checkboxes',
    '#title' => 'Indented checkboxes',
    '#options' => array(
      '1' => 'No indentation',
      '2' => 'One indentation',
      '3' => 'No indentation 2',
      '4' => 'Two indentations',
    ),
  );
  $form['my_checkboxes']['2']['#indentation'] = 1;
  $form['my_checkboxes']['4']['#indentation'] = 2;
```

That way, we'd only need a single `'#indentation'` property.

**Comment by argiepiano** [comment]
@klonos, actually that second way also works, I think. I'll test.

**Comment by argiepiano** [comment]
Snapshot of the outputs in Basis and Seven (after installing the tiny module above)

<img width="428" alt="Screen Shot 2023-02-25 at 7 31 10 PM" src="https://user-images.githubusercontent.com/9938978/221388989-845f5fe8-72b6-4789-a1b5-76ae688d47da.png">
<img width="384" alt="Screen Shot 2023-02-25 at 7 31 00 PM" src="https://user-images.githubusercontent.com/9938978/221388990-4291fd68-46dc-404f-be30-f599bbcd4f16.png">

**Comment by argiepiano** [comment]
> @klonos, actually that second way also works, I think. I'll test.

Yes, the second way you posted does work without a need to change anything in the PR. 

Updated tiny module:
[Uploading testing_stuff.zip…]()

**Comment by klonos** [comment]
> Yes, the second way you posted does work without a need to change anything in the PR.

Thanks again! ...now wondering if it'd be worth making it so the array way could be possible with the `'#description'` property (a new `'#descriptions'` array for consistency) 🤔 ...anyway, separate issue.

**Comment by klonos** [comment]
...btw, I'm really excited about this, as it seems that it might help with things like #4272 and #1968.

**Comment by bugfolder** [comment]
> That way, we'd only need a single '#indentation' property.

I agree that having a single property is better.

Quick and slick work! Looking forward to trying this out (but not tonight).

**Comment by klonos** [comment]
@argiepiano I tried setting some defaults for all the form elements in the test module you provided, and got this:

```
Warning: foreach() argument must be of type array|object, string given in form_type_checkboxes_value()
(line 2448 of /app/docroot/core/includes/form.inc).
```

**Comment by argiepiano** [comment]
> @argiepiano I tried setting some defaults for all the form elements in the test module you provided, and got this:

I'm not seeing that. I did:

```php
  $form['my_checkboxes_second'] = array(
    '#type' => 'checkboxes',
    '#title' => 'Indented checkboxes second way',
    '#options' => array(
      '1' => 'No indentation',
      '2' => 'One indentation',
      '3' => 'No indentation 2',
      '4' => 'Two indentations',
    ),
  );
  $form['my_checkboxes_second'][2]['#indentation'] = 1;
  $form['my_checkboxes_second'][4]['#indentation'] = 2;
```

and got no error. Can you paste how you did it?

**Comment by argiepiano** [comment]
@bugfolder are you suggesting to remove `#indentations` and leave `#indentation`?

**Comment by klonos** [comment]
@argiepiano I did this in the first form element (uncomment the `'#default_value'` and you should get the same error):

```php
  $form['my_checkboxes'] = array(
    '#type' => 'checkboxes',
    '#title' => 'Indented checkboxes',
    '#options' => array(
      '1' => 'No indentation',
      '2' => 'One indentation',
      '3' => 'No indentation 2',
      '4' => 'Two indentations',
    ),
    // '#default_value' => '2',
    '#indentations' => array(
      '2' => 1,
      '4' => 2,
    ),
  );
```

**Comment by argiepiano** [comment]
That's because `#default_value` for checkboxes must always be an array. It is not related to this PR.

**Comment by klonos** [comment]
Right 🤦🏼

**Comment by bugfolder** [comment]
> @bugfolder are you suggesting to remove #indentations and leave #indentation?

Yes, in the interest of simplicity, and since `#indentation` provides the same thing for `checkboxes` and `radios` using the extra keys approach. (Not strongly, though, if there's a good argument for having both.)

(As an aside, I think the docs at https://docs.backdropcms.org/form_api#checkboxes and https://docs.backdropcms.org/form_api#radios both need beefing-up, to point out that it's not just `#descriptions` that can be added to the extra keys, but other properties of individual checkboxes/radios as well—and this one, of course.)

**Comment by argiepiano** [comment]
Thanks @bugfolder. I think it's a good idea to simplify. I'm also working on adding an automated test, and also adding `#indentation` to select (in my PR only `#indentations` works for `select`). More soon.

**Comment by argiepiano** [comment]
Update the tiny testing module: 
[testing_stuff.zip](https://github.com/backdrop/backdrop-issues/files/10834329/testing_stuff.zip)

**Comment by docwilmot** [comment]
The way we're doing the array keys looks a bit unusual. Is there precedent for array keys without the `#` in Form API array?

**Comment by argiepiano** [comment]
> The way we're doing the array keys looks a bit unusual. Is there precedent for array keys without the # in Form API array?

Hi @docwilmot. I'm not sure what you mean. The array key for the new property is `#indentation` (it has the `#`).

**Comment by docwilmot** [comment]
Yep, thats precedent then.

**Comment by argiepiano** [comment]
Anybody willing to test and review? @bugfolder or @klonos?

**Comment by bugfolder** [comment]
Yes, I'll test soon; just a bit tied up at the moment.

**Comment by bugfolder** [comment]
Tested. All looks good! Code also reviewed, also looks good.

**Comment by quicksketch** [comment]
I think this looks great. Nice work @argiepiano!

I'd like to propose a few name-space suggestions. I'm a little concerned about sharing `div.indentation` between tabledrag and form elements. Although they have similar function, I could see themes assuming `div.indentation` is used specifically for tabledrag and overlook it on checkboxes/radios (or vice-versa). And there are probably reasons to style them differently anyway.

So I suggest the following name changes:

* Change the function name `theme_indentation()` to `theme_form_element_indentation()` (roughly matching `theme_form_element()` and `theme_form_element_label()`)
* Change the class name from `.indentation` to `.form-item-indentation` (to match `.form-item` used in `theme_form_element()`)

And then we'd need new CSS for the new type of indentation. Maybe we could use something simpler than the `float` approach used by tabledrag, like a `display: inline-block` element?

**Comment by argiepiano** [comment]
Thanks, @quicksketch. I've made the requested changes. The new css class (`.form-item-indentation`) uses inline-block. I tested RTL also, and seems to be working well. 

Ready for review and more testing.

**Comment by quicksketch** [comment]
Thanks @argiepiano! I also want to get your thoughts on how this could impact dependent form elements if a `#dependencies` property were added like in https://github.com/backdrop/backdrop-issues/issues/2732#issuecomment-309220460

If we were to add `#dependencies`, or if this was used indent dependent form elements that use `#states`, do you think this could scale out to apply to _all_ (or most) form elements? CTools used to automatically indent dependencies, but we could potentially make it a pattern to specify `#indentation` if a form element was dependent on a parent element. I know modules like Views Bulk Operations could benefit a lot from restoring that indentation = dependency pattern.

A separate question: What happens if you put a `#description` on a checkbox and combine it with `#indentation`? Based on reading the code, I guess that the checkbox and label will indent, but the description will not.

Maybe moving this up into `theme_form_element()` would both A) Make `#indentation` work on most form elements B) Also indent descriptions on checkboxes/radios. What do you think, too much?

**Comment by argiepiano** [comment]
@quicksketch thanks for the comments.

> If we were to add `#dependencies` ... do you think this could scale out to apply to all (or most) form elements? 

I think adding `#dependencies` to form elements makes sense. As stated in the issue it would help us avoid the complications of using `#states` and would allow for some server side logic (e.g. making the #required conditional on whether the parent item is selected). 

I agree also that `#indentation` could be an added thing. In D7 Ctools, `#dependencies` automatically indented things AFAIK. I never liked that.

So, it would make sense to make `#indentation` apply to most (all?) FAPI elements and moving the functionalityu to `theme_form_element()`. I can give this a try.

> A separate question: What happens if you put a #description on a checkbox and combine it with #indentation? 

It doesn't, actually. Good catch. If we move this to `theme_form_element()` then we could apply the indentation to the wrapper element, which would affect everything inside, including the description.

As a side note: In VBO (which I maintains) I replaced `#dependencies` with a combo of `#state` and css. Not sure if you've used the module, but the  messy UI that resulted from not having `#dependencies` in Views has been fixed.

**Comment by quicksketch** [comment]
Sound good!

**Comment by argiepiano** [comment]
I started working on moving the `#indentation` functionality to `theme_form_element()`. It's pretty straightforward, but I need some feedback.

Currently, `theme_form_element()` adds labels, descriptions, and wraps the item in a div. This is the current output for a radio button without any of the changes introduced by this PR:

<img width="744" alt="Screen Shot 2023-03-03 at 9 23 31 PM" src="https://user-images.githubusercontent.com/9938978/222875478-47bcebeb-c3aa-4ae5-8559-786bf1bf2639.png">

I see two options for adding indentations:

Pure CSS
-----------

Adding css classes to wrapping div. The classes would be different for each level, as in `indentation-level-1` etc. This implies the creation of several classes, one for each level (I guess up to level 5 or 6). This was the original approach in #3292, which was discarded in favor of using `theme_indentation()`, which adds `<div class="indentation">` before the element.

Combination of markup and CSS
--------

I've experimented with the best way to do this. The most reliable way to indent both the item and the description is to add another wrapper (an indentation wrapper) around the form-item `div`, and add indenting `divs` before the form-item wrapper.  The indentation wrapper can be a flexbox, which assures smooth and consisten indentation.

So, an item with one level would look like:

<img width="870" alt="Screen Shot 2023-03-03 at 9 32 16 PM" src="https://user-images.githubusercontent.com/9938978/222875827-479a2c80-7ec8-435b-b5a4-28d4b5ba0258.png">

And an item with two indentations:
<img width="783" alt="Screen Shot 2023-03-03 at 9 35 18 PM" src="https://user-images.githubusercontent.com/9938978/222875939-3e5d5a83-5a44-40ca-aec6-17c9e7ed86cd.png">

And the CSS classes for the new divs are:

```css
div.form-item-indentation-wrapper {
  display: flex;
}
div.form-item-indentation {
  width: 1em;
}
```

With this approach, items without indentation lack the indentation wrapper div, which creates inconsistencies in terms of sibling items as follows (showing one form item without indentation wrapper, and  one with):

<img width="867" alt="Screen Shot 2023-03-03 at 9 39 00 PM" src="https://user-images.githubusercontent.com/9938978/222876075-043c8eb7-dc72-400c-b8b2-df5c1273b5e7.png">

One possible solution would be to wrap ALL form items with the indentation wrapper, and simply not adding indentation divs when there is no indentation. But this adds one more level of div wrappers to form elements, even when they are not needed.

<img width="818" alt="Screen Shot 2023-03-03 at 9 47 02 PM" src="https://user-images.githubusercontent.com/9938978/222876292-ab9cb631-3caf-4918-91c7-b0eb1b3ba0fa.png">


Any feedback and/or alternatives greatly appreciated!

**Comment by quicksketch** [comment]
Personally, I like the CSS-only approach of making a collection of indentation classes rather than the repeated markup. In comparison to tabledrag, that system _required_ separate divs for a particular reason: to draw a background image within the divs when you drag a child and parents, like this:

![Peek 2023-03-03 22-32](https://user-images.githubusercontent.com/100206/222880093-71e1ac28-422d-4067-81f2-550f8747fd58.gif)

That line that appears is a set of background images on the `div.indentation` element. It does have the added benefit that it can handle any level of depth, but I don't like the repetitive markup.

**Comment by klonos** [comment]
> This implies the creation of several classes, one for each level (I guess up to level 5 or 6).

Than ^^ is very limiting. ...a few days ago, I was experimenting with using `data-*` attributes (like `data-indentation-depth="1"`) instead of CSS classes. The rough gist of it is that there is no proper (or at all) browser support for doing calculations with attributes, and the variables can only be used with the `content` CSS property, and only with the `::before`/`::after` pseudo-selectors. I have collected all that information somewhere (it took some serious time/effort), but I can't find it now 😞

I would still like us to add a `data-*` attribute with the depth of indentation, for when browser support is implemented (or use of JS/polyfills can be used in themes for that purpose).

**Comment by argiepiano** [comment]
@quicksketch, I've done all the changes you suggested:
- The theming of the indentation happens now at `theme_form_element()`. This means that `#indentation` can now be applied to all Form API elements
- The indentation is accomplished by added a css class such as `form-item-indentation-1`, `form-item-indentation-2`, etc.
- The css classes use `margin-left` or `margin-right` for RTL

Because this css class is overridden by the theme's `style.css`, I had to use `! important`. I know this is not ideal (you may want, after all, to override the class in your theme!).  I'm open to suggestions (I'm not very savvy with CSS).

**Comment by argiepiano** [comment]
> I would still like us to add a data-* attribute with the depth of indentation, for when browser support is implemented (or use of JS/polyfills in themes can allow for a better approach).

Interesting. But I'm wondering: wouldn't it be just as easy to add the `data-*` when we are ready to make all these css functionality work? (that is, when browser support is there). I don't know if it makes sense to add attributes that can't currently be used...

**Comment by argiepiano** [comment]
> Because margin-left in the new form element's css class is overridden by .form-item .form-item'smargin in the theme's style.css, I had to use ! important. 

Here's a bit more information. `style.css` (Seven) and `backdrop-form.css` (Basis) both modify all margins for form items that are inside other form items (e.g. each of the individual checkboxes). This is used so that the checkboxes and radios look closer to each other than other "normal" form items like textfields, etc.  

The latest change to the PR changes the declaration of margins for Seven and Basis. Instead of using a blanket `margin: 0;`, I've changed that to `margin-top` and `margin-bottom`, since that was the intent of those properties (keeping form-item children closer together).

Ready for more review and testing.

**Comment by bugfolder** [comment]
I've tested this out with the `testing_stuff` module, and (not surprisingly) verified that it works as advertised.

I also tried it with the Bootstrap Lite theme, and it also looks good:

![bsl](https://user-images.githubusercontent.com/29214084/222981888-9f4b6320-1307-48a0-8def-fd5ad31c2caa.jpg)

However, I raise the question of whether you should apply CSS `form-item-indentation-0` to unindented classes so that CSS overrides (or lack) will be applied uniformly. For example, I added this to a BSL theme:

```
.form-item {
  margin-left: 10em;
}
```

which is a bit contrived, but I can imagine a themer adding margin to form elements in that way, and they'd be a bit surprised to get something like this:

![bsl_2](https://user-images.githubusercontent.com/29214084/222982026-ebae76ba-4c9e-4928-b3dd-4cc50e29beda.jpg)

So perhaps consider adding `form-item-indentation-0` for completeness?

**Comment by argiepiano** [comment]
> However, I raise the question of whether you should apply CSS form-item-indentation-0 to unindented elements so that CSS overrides (or lack) will be applied uniformly

Good point. Added.

**Comment by argiepiano** [comment]
I've done some additional testing with other FAPI elements. `#indentation` works fine for elements that are themed by `theme_form_element()`. 

This excludes a few elements that don't use that theming hook; e.g.:  `fieldset` and `markup`. It may be helpful to add this functionality to those - separate issue, or here?

**Comment by quicksketch** [comment]
I think let's work on just supporting through `theme_form_element()` in this issue. I'm curious if it works on `#type = container` at this point. That could be nice to indent an entire group of elements without any other visual indicator. But either way, let's not expand the scope of this one further.

**Comment by argiepiano** [comment]
It does not work with `container` currently, but I think it'd make sense to add it here, as `containers` are close cousins of `form-item`s. Plus that would also make it work with the `radios` and `checkboxes` collections, as those also use `container`.

**Comment by argiepiano** [comment]
I went ahead and added `#indentation` to `theme_container()` - it was very simple to do. So, now most FAPI elements have that property with a few exceptions (`button` and `fieldset` don't).

And here's an updated version of the little module to show the indentations in most FAPI elements:

[testing_stuff.zip](https://github.com/backdrop/backdrop-issues/files/10903865/testing_stuff.zip)

**Comment by bugfolder** [comment]
Follow-up issue to update FAPI: https://github.com/backdrop-ops/docs.backdropcms.org/issues/221

**Comment by bugfolder** [comment]
Reapplied the patch, tested with testing.zip, everything worked. Also tried it again with Bootstrap Lite theme, and (again) everything worked. WFM.

Also checked the code. LGTM (again). Looks RTBC to me. (This will be nice to have.)

**Comment by quicksketch** [comment]
Code looks good to me too. Great work @argiepiano!

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/4364 into 1.x for 1.25.0!

https://github.com/backdrop/backdrop/commit/d190da4691d87ff3969376540d31ac63c7bd3cc6 by @argiepiano, @bugfolder, @klonos, @docwilmot, and @quicksketch.

**Comment by quicksketch** [comment]
Marking "needs - documentation" until https://github.com/backdrop-ops/docs.backdropcms.org/issues/221 is completed.

**Comment by klonos** [comment]
I wanted to suggest some improvements while we were working on the code that this change toughed, but didn't make it. So I've filed a follow-up here: #6028

**Comment by bugfolder** [comment]
Documentation created: https://docs.backdropcms.org/form_api#indentation

**Comment by argiepiano** [comment]
Thanks, @bugfolder. Looks good to me!
