### ISSUE TITLE
[D10] Layouts/blocks: Add visibility condition for 200/403/404 response codes

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#6016]
This is the respective issue as https://www.drupal.org/project/drupal/issues/2245767, and would be a good addition to the features of our layouts system.

> ## Problem/Motivation
> Some blocks, like user login, should be shown on 403/404 response pages.
> Others, like the help block, should not.
> 
> ## Proposed resolution
> Add a visibility setting to blocks that restricts visibility to any combination of 200/403/404 responses. Default this to show the block for all responses.

Perhaps in our case it also makes sense to add that visibility conditions to the layouts (besides blocks), so that if people really have the need for it, they can configure a different layout to be used based on response.

**Comment by klonos** [comment]
PR: https://github.com/backdrop/backdrop/pull/4374
<img src="https://user-images.githubusercontent.com/2423362/222839597-ea17ca03-4350-47bd-bfd3-bf5f8f87bdc2.png" width=60%>
<img src="https://user-images.githubusercontent.com/2423362/222839552-eaf5cd46-8a6c-4fc8-9458-14aeaf4a0b48.png" width=60%>

Would be good to have tests for this, but in the meantime up for review/testing/feedback.

**Comment by stpaultim** [comment]
@klonos 

Here is some general feedback. I would never have thought of this, so it's not something I think I need to have. Having played with your PR, I think I MIGHT find some use cases for this if I remeber that it's available, but I doubt I will remember this is even an option - it's seems like such an obscure use case.

I see the path that you set up for the layout with this visibility rule. But, I would never have figured that out myself and I'm not sure how to figure that out. That only works for page not found, how would I configure it for accessed denied. Do I want a layout for each type of server response. 

Adding a block with these visibility conditions makes more sense. But, I'm confused about where I need to put them. Would I always put them on the default layout? Do I need to put them on all layouts?

I am interested in this issue, but I'm having a hard time seeing how we make it useful for the average site architect.

**Comment by klonos** [comment]
Thanks for taking the time to test this @stpaultim and to then provide useful feedback🙏🏼 ...here's my thinking about this feature:
- Feature parity with D10 (don't want people saying "but I can't do that with Backdrop" ...or at least only say that for as few things as possible)
- At the same time I find it useful in the following scenarios:
  - People may want to have their "page not found" and "access denied" pages be "unbranded pages" (to use the term @jenlampton used in https://backdropcms.org/news/layouts-in-backdrop-cms-vs-layouts-in-drupal):
    > ...where the header and navigation can be removed to create a page entirely different from the rest of the website.

    In those cases, it would help having the visibility rules in the layout level, so that separate layouts can be created for them.
  - People may want to show an additional block in their 403/404 pages. Perhaps embed a search block or a menu block with some text saying "We didn't find what you were looking for, but here are some links that may help you find it". In these cases, having the visibility conditions on the block level seems more appropriate.

> I see the path that you set up for the layout with this visibility rule. But, I would never have figured that out myself and I'm not sure how to figure that out.

Perhaps that calls for a documentation page or a blog article then 😉 

I hope that the above answers your questions.

**Comment by stpaultim** [comment]
@klonos - Thanks for the additional context and information. I would not oppose putting this core, I just think I'd be unlikely to use it and am not sure how to test it, because I don't know how to configure it for all the scenarios.

I'm still not sure how to test the visibility condition for both a page not found and an access denied layout. Would I have to create two different layouts, one for each condition?

You gave me the path above for 404 'page not found', but what is the path for a 403 'access denied'?

**Comment by klonos** [comment]
> I'm still not sure how to test the visibility condition for both a page not found and an access denied layout. Would I have to create two different layouts, one for each condition?

Yes, either two layouts (one for each of the 403/404 codes) and/or two blocks similarly added to the default admin layout. You can then create a less privileged user and try to access admin pages they have access to vs. ones they don't have permissions to access, and see if the 403 block is shown or not.

> ...but what is the path for a 403 'access denied'?

You can try accessing a non-existing URL on the site (to trigger the "page not found" code) and see if the 404 block is shown (or 404 layout being used).

**Comment by jenlampton** [comment]
This feature was also part of the Drupal 7 panels module, and I used it often on my D7 sites, so +1 from me on this feature.
* For the `system/404` page (page not found), many people like to have a little fun with the design, and this would allow a completely different layout than for the rest of the site (which is a common use-case).  
* For the `system/403` page (access denied) I would often build a page with specific instructions for administrators helping them to log in - often with a log in block right there.

@stpaultim I would recommend adding the log in block to the default layout with the visibility rule of "Access denied 403" if you wanted to see how that could be useful, or place an angry dragon block (also on your default layout) for your 404 :)

**Comment by jenlampton** [comment]
I gave the PR a review and it's a great first pass! There are a few minor things that need work (like adding a `formValidate()`) but one thing that's worth discussing is whether theres value in the `Success (200)` option.

The way the code is written now this rule would execute even when the response code isn't 200, but before we spend time on fixing that -- is there a use case for having this option?  I can't think of one... 

I'd like to propose that we remove that option and leave the current access logic in place.

**Comment by kiamlaluno** [comment]
Would no visibility conditions make a block visible on 404 and 403 error pages? If that is the case, I can image somebody wants to show a block when those errors are not returned.

**Comment by klonos** [comment]
I plan to get back to this soon as I find time/energy.

**Comment by stpaultim** [comment]
Is there interest in trying to get this into the next release?

If @klonos is not available right now, I could rebase it. But, I'm not sure I could fix issues that folks raise. 

Picking out this issue as one that MIGHT be considered low hanging fruit for 1.29, if there is anyone interested enought to work on it.

**Comment by stpaultim** [comment]
Since @klonos is traveling at the moment and this PR seems to be pretty close to completion, I went ahead and rebased his PR to provide others and potentially core committers something that they might work with and at least make this a possible improvement in 1.29. 

As I have mentioned above, this is not an issue I feel strongly about. But, I hate seeing the previous work go to waste when it might be something we could move forward.

I'm not sure I can address the issues raised by @jenlampton here: https://github.com/backdrop/backdrop-issues/issues/6016#issuecomment-1518773114

If someone would like to help out and create a PR against mine OR simple copy my PR and submit your own, that would be welcome.

**Comment by stpaultim** [comment]
For anyone curious. On the current PR sandbox, I set up special layouts for 403 and 404 messages. 

Try these links:

https://pr4855-hwpuzc5wxlayg2ijjdtvcuwztdutdze4.tugboatqa.com/biking

Try this one, when not logged in:

https://pr4855-hwpuzc5wxlayg2ijjdtvcuwztdutdze4.tugboatqa.com/admin/dashboard

**Comment by quicksketch** [comment]
I think this a great feature! Seems like it could be used in a lot of situations. A common thing might also be to use this condition on the default layout to hide certain blocks from 404/403 pages (if 404/403 pages don't have a dedicate layout).

I'll work on adding some test coverage to the PR.

**Comment by quicksketch** [comment]
I pushed a commit to your PR @stpaultim that adds test coverage. In writing the tests, I discovered that this feature was not working when using a custom layout path and custom 403/404 pages. It was only working if using the default `system/403` and `system/404` paths.

> but one thing that's worth discussing is whether theres value in the `Success (200)` option.

You might use it to show a block only on non-200 pages (though you could achieve the same thing by checking both 404 and 403 checkboxes). Though that seems a bit contrived, I could see wanting to exclude expensive-to-generate blocks from all error pages.

You might also want a 200 condition if you were making a multi-purpose Layout that was _both_ a custom 403 page and could also be visited directly. Say you created a layout at `login` and you also set your site 403 setting to `login`. Then you might show show a block based on whether the user was visiting `/login` directly or was shown the layout by hitting an access denied page. Again, you could achieve the same thing using the 403 condition and negating it, but some people might find "Response code is 200" easier to interpret than "Response code is not 403".

So I guess what I'm saying is that the 200 response code is probably unnecessary since there are alternatives, but there are valid use-cases for adding a 200 Status check or negating a 200 Status check. I would be inclined to just leave it in place.

> There are a few minor things that need work (like adding a `formValidate()`)

I'm not sure what needs to be added here. Could we just make the Status checkboxes required?

**Comment by stpaultim** [comment]
> In writing the tests, I discovered that this feature was not working when using a custom layout path and custom 403/404 pages.

I'm not exactly sure what a custom layout path would be in this case. It's my understanding that the system path for 403 and 404 are:

system/403
system/404

How would one create custom versions of this? Would this be something done in code or through a redirect?

**Comment by quicksketch** [comment]
> How would one create custom versions of this? Would this be something done in code or through a redirect?

Specify the custom 403 or 404 path on the `admin/config/system/site-information` page:

![image](https://github.com/user-attachments/assets/9d466097-6f98-42c8-afd2-64afc585e8b2)

**Comment by stpaultim** [comment]
@quicksketch That's a bit embarassing..... 

A setting I've seen a thousand times and never used.

**Comment by quicksketch** [comment]
> Also, is this a blocker? If so, I'm not sure it's something I'll be able to address on my own.

Sorry, I wasn't clear. I've already fixed that problem and the tests cover it.

**Comment by stpaultim** [comment]
@quicksketch Can we remove the "Needs Work" label?

**Comment by quicksketch** [comment]
I pushed one more commit to address a code style issue and make the status code field required. I think this is ready for review. 

![image](https://github.com/user-attachments/assets/572e4af6-68eb-44b4-9bcd-3961ca9b3d48)

**Comment by argiepiano** [comment]
I'm not sure if I'm misunderstanding some of this functionality.

1. I created a layout override for `node/%` with a VC of `Server response code is 404`
2. I visited a node that doesn't exist, such as `node/123123123`
3. Backdrop does not use that layout override - instead it shows 

<img width="515" alt="Screen Shot 2024-09-02 at 3 01 35 PM" src="https://github.com/user-attachments/assets/c912fc8e-3737-4758-afb5-73a6b383a8d9">

Is this not a valid use case?

**Comment by laryn** [comment]
@quicksketch I tested this and it works as I'd expect. Code looks great except for a few minor coding standards that got flagged on the last run, at the top of the plugin related to a doc block and line spacing. Other than that minor fix I think it's ready to merge.

**Comment by quicksketch** [comment]
Thank you @laryn, @argiepiano, and @izmeez for the reviews!

@argiepiano Yeah, that's an interesting situation where the server response condition would probably never be useful, since the 403 or 404 page route gets rendered, not the node route, when hitting a non-existent node path. That is the intended behavior, but it might not be what's understandably expected.

The code style issue is one we have throughout Layout classes: whether we should include both a `@file` and a class docblock. For now, the PR is consistent with the other Layout classes by only including the `@file` docblock.

With the testing producing the expected results, I've merged this PR into 1.x for 1.29.0.
