### ISSUE TITLE
ImageFieldValidateTestCase::testTypeSupport() wrongly assume WebP images are not supported on PHP 5.6

### ISSUE THREAD

**Issue by avpaderno** [backdrop/backdrop-issues#6046]
[`ImageFieldValidateTestCase::testTypeSupport()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21image%21tests%21image.test/function/ImageFieldValidateTestCase%3A%3AtestTypeSupport/1) contains the following code.

```php
  if (version_compare(PHP_VERSION, '7.1.0', '<') || !$webp_supported) {
    $this->assertText(strip_tags($refused_message), 'WebP image type has been refused');
    // Also check the field description.
    $this->assertText('Allowed file types: jpg.', 'Field allows only jpg extension');
  }
```

That code assume that on PHP 5.6 WebP images are not supported, but that is not true.
I ran the following code on PHP 5.6 and PHP 7.3.

```php
echo "<pre>" . print_r(gd_info(),TRUE) . "</pre>";
```

With PHP 5.6, I got the following output.

```none
Array
(
    [GD Version] => bundled (2.1.0 compatible)
    [FreeType Support] => 1
    [FreeType Linkage] => with freetype
    [T1Lib Support] => 1
    [GIF Read Support] => 1
    [GIF Create Support] => 1
    [JPEG Support] => 1
    [PNG Support] => 1
    [WBMP Support] => 1
    [XPM Support] => 1
    [XBM Support] => 1
    [WebP Support] => 1
    [JIS-mapped Japanese Font Support] => 
)
```

With PHP 7.3, I got the following output.

```none
Array
(
    [GD Version] => bundled (2.1.0 compatible)
    [FreeType Support] => 1
    [FreeType Linkage] => with freetype
    [GIF Read Support] => 1
    [GIF Create Support] => 1
    [JPEG Support] => 1
    [PNG Support] => 1
    [WBMP Support] => 1
    [XPM Support] => 1
    [XBM Support] => 1
    [WebP Support] => 1
    [BMP Support] => 1
    [JIS-mapped Japanese Font Support] => 
)
```

In both the cases, the GD library bundled with PHP is used and in both the cases WebP images are supported.

Instead of checking the PHP version and if WebP images are supported, the code should just check WebP images are supported.

```php
  if (!$webp_supported) {
    $this->assertText(strip_tags($refused_message), 'WebP image type has been refused');
    // Also check the field description.
    $this->assertText('Allowed file types: jpg.', 'Field allows only jpg extension');
  }
```

**Comment by kiamlaluno** [comment]
(I knew it was not that easy.)

**Comment by klonos** [comment]
@kiamlaluno just to clarify: PHP's GD extension has supported WebP functionality since version 5.4, **but it must be explicitly compiled in to be available**. (libvpx for PHP 5.x, libwebp for PHP 7.x). In PHP 7.x that is not a requirement, since WebP support is in-built.

So I believe that you are right (and the approach in the PR seems right too): we shouldn't be explicitly restricting our WebP support based on PHP version alone - we should instead be checking if the current PHP in the system supports it (which the existing code already does by checking the entries in the array output of `gd_info()`). Lets see what others think though.

**Comment by kiamlaluno** [comment]
Just to be sure, I tried the following code on my site, after changing to PHP 5.6.

```php
echo '<pre>PHP version: ' .PHP_VERSION . '</pre>';

$file = './core/modules/image/tests/images/testimage.webp';
if ($resource = imagecreatefromwebp($file)) {
    echo '<pre>WebP image loaded</pre>';
}
```

The output of that script is the following.

```none
PHP version: 5.6.40

WebP image loaded
```

I tried to understand why the code contains a comment about WebP images being supported only starting from PHP 7.10.
I found a comment on [`imagecreatefromwebp()`](https://www.php.net/manual/en/function.imagecreatefromwebp.php) saying that:

- Normal WebP (VP8) images are supported since PHP 5.4
- Transparent WebP or alpha transparency (VP8X, VP8L) images are supported since PHP 7.0
- Animated WebP (VP8X) images are not supported at all

**Comment by klonos** [comment]
I recall reading the documentation and my understanding at the time was that PHP 7+ had in-built support OOTB (which was obviously wrong if I am reading things properly now), whereas for 5.x you had to compile it specifically to support the format.

**Comment by herbdool** [comment]
Ah, now I see. In https://github.com/backdrop/backdrop-issues/issues/4509#issuecomment-680037545: `getimagesize()` only gets webp support in 7.1. That's pretty key.

**Comment by herbdool** [comment]
I got the other pr working. The current code will only support webp on PHP 7.1.0 so the test was correct. Since I changed the way it sees if the system supports webp I had to just directly test the PHP version.

**Comment by kiamlaluno** [comment]
It has been an oversight on my part.
I was trying to fix tests for the other PR that failed only on PHP 5.6, but I didn't get the right fix.

**Comment by herbdool** [comment]
That was my oversight too. But now it's good. I'm guessing we can close this issue.

**Comment by klonos** [comment]
Perhaps we need to add some inline comments with an explanation, so that others don't wonder the same thing in the future?

**Comment by klonos** [comment]
Yup, I think that the comments here should suffice: https://github.com/backdrop/backdrop/pull/4366/files#diff-39cf1f5878136e0db7bb05e90af7ff310ec9bcfcf823edfff38a90bba081d9c5R37-R41
