### ISSUE TITLE
Remove default permission that allows editors to delete all pages, posts, and cards in new installs.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#6078]
While we were working on https://github.com/backdrop/backdrop-issues/issues/5885 I noticed that we were granting editors permission to `delete any X` which seemed overly permissive for a default.  My preference is always to do what's safest by default, and allow people to open things up more if needed. I think that allowing editors to be able to delete all the content on the site is not a very safe default. 

This is how I handle all my client sites as well: start by giving people only exactly what they need, and as they run into limitations, grant those additional permissions one permission at at time.

I'm not sure this has been discussed before. Below are some items I pulled from [the issue where the role was added](https://github.com/backdrop/backdrop-issues/issues/1285), for reference (since that was a very long issue)

When we were creating the new editor role we had initially discussed these permissions:

* access dashboard
* access content overview
* view own unpublished content
* view any unpublished content
* view revisions
* revert revisions
* delete revisions
* create page content
* edit own page content
* edit any page content
* delete own page content
* delete any page content
* create post content
* edit own post content
* edit any post content
* delete own post content
* delete any post content
* access administration bar
* access administration pages
* access site in maintenance mode
* view the administration theme
* flush caches
* search content
* use advanced search
* administer taxonomy
* edit terms in tags
* delete terms in tags

The initial set did include the "delete any", but there wasn't any further discussion about it specifically. 

We did have this (which is my perspective also)

> The consensus at the DEV meeting today seemed to be to lean towards a more restrictive set of permissions initially. We believe that it's easier for users to add tests than remove them (at least in terms of perception). We can change permissions at any time in the future, since this only effects new sites and will never effect an existing site.

But again, nothing specific.

**Comment by olafgrabienski** [comment]
Same here, I usually disable the "Delete any content" permissions for editors (but leave "Delete own content").

**Comment by olafgrabienski** [comment]
There is already a [Revisit permissions for the OOTB "Editor" role](https://github.com/backdrop/backdrop-issues/issues/4339) meta issue btw. (I'm going to add this issue to the description over there.)

**Comment by kiamlaluno** [comment]
As a side note, if this change is committed, should sites where the *editor* role can delete all the content be warned, in some way?

**Comment by stpaultim** [comment]
I helped create the original list of permissions for the editor role and I approve of this change. I marked this a good first issue, because it's a pretty simple PR to write. This will be changed in the default install profile.

**Comment by jenlampton** [comment]
This "delete any" option had only been applied to the `Page` and `Post` content type until now. Though still potentially problematic, it's not nearly as concerning as granting that permission for all content on the site. I don't think it warrants a warning being printed in the CMS, but perhaps an item in the release notes would be valuable.

**Comment by stpaultim** [comment]
I've created a PR that removed editor permission to:

"delete any posts"
"delete any pages"
"delete any cards"

**Comment by kiamlaluno** [comment]
The only failing test reports the following error.

> /bin/sh: 1: phpcs: not found

Probably, closing the PR and re-opening it would be sufficient to make the test pass.

**Comment by klonos** [comment]
If you consider larger sites, where there can be certain people with the "editor" role and then different people with "content approver" or "content moderator" roles, then sure, I understand the concern raised here. In smaller sites though, where you may have only one person as admin (the person that creates the content types) and only one or two people that manage all the content on the site, then having separate roles for those that edit/create and different for those that can delete any content is simply overkill.

When a site is mostly a one-man-show, there is usually one person configuring the site (their IT person, or the freelancer that looks after their site), and then the site owner and maybe another person that manage everything related to content. In that scenario (which is not far from our target audience), the ability to delete any content on the site can be considered basic and required. No? The people managing the content of such sites won't want to be charged by the hour for their IT person to simply delete content for them. And we surely don't want to encourage the practice where site admins give full admin permissions to people that should only be limited to content editing, nor to have them specifically tweak permissions each time they create content types (which mostly defeats the purpose of #5885). Right?

Having said all that, if people still insist that we shouldn't be giving the "delete any" permission by default OOTB, then as a follow-up to the feature I'm advocating for in #5885, we could file a PR here to add an extra "Also allow the content editor role to delete any content by default" checkbox (or something like that). Either way, I don't want to derail the feature in #5885, which I'm hoping to get in for 1.25.0.

**Comment by stpaultim** [comment]
@klonos - I hear your concerns. I did not feel strongly about this issue either way, because this permission is so easily changed. I believe that we did decide early on to be a bit conservative with these permissions requiring site admins to loosen them, rather than the reverse where site admins feel the need to make them more restrictive. That feel right to me. 

As a rule, I would personally give site editors the ability to delete any content. But, I don't see this default as problematic.

**Comment by olafgrabienski** [comment]
@klonos In my opinion the permission to delete "any" content is really dangerous, also because Backdrop, unlike WordPress, doesn't store deleted items temporarily in a "Trash" bin. For this reason, I use to not give the "delete any" permission to site owners or editors, at least not from the beginning, but the permission to unpublish content (via Override Node Options).

**Comment by klonos** [comment]
Yes, I have to admit that I agree (at least in principle) with not making it easy for people to "shoot themselves on the foot" and being safe than sorry when it comes to security/permissions 👍🏼

We have many issues in the core queue that would help us achieve the actual goal here, and I would like to work towards that goal. Some examples:
- #2498
- #3162
- #3157 (specifically the part where we expose the "unpublish" action as a submit button)

The luck of dedicated/explicit actions (UI) and per-content-type permissions (DX) to allow people to unpublish instead of delete seems to be the main blocker here I think (we only have global permissions to _view_ own/any unpublished content). If we had better unpublishing UI/UX/workflows like that in core, then I think that I'd have less concerns (which admitedly lean towards compromizing possibility of data loss for the sake of the ease of use 🤔).

**Comment by jenlampton** [comment]
I just want to add a note here that we forgot to remove the "delete any" permission from https://github.com/backdrop/backdrop-issues/issues/5885 so we should change that in this PR also.

**Comment by jenlampton** [comment]
Safety should really be our first priority. It's not a lot of work to grant editors additional permissions, but it is a whole lot of work to try to recover content that's been deleted. 

If/when any of the other solutions you linked get into core @klonos then we can evaluate if it's safe enough to grant editors access to delete everything from a site by default. For now, we should do what's safest.

**Comment by quicksketch** [comment]
For what it's worth, I agree with @klonos that I would expect an editor to have delete permissions, for the same reasons he stated. If this were a voting situation, we still have 3 in favor of this issue and only 2 opposed (with @stpaultim neutral).

But I think that the premise of having permissions be more restrictive by default for editors makes sense.

**Comment by klonos** [comment]
I'm (mostly, in principle) in agreement with this. I initially though that we could perhaps add an additional "also allow deleting any content by default" checkbox, but then thought that that would unnecessarily over-complicate the UI, which is not a good thing for UX. Besides, I strongly believe that the root problem here is the lack of individual "unpublish" permissions for content types (or a global one) + better exposure of the unpublish/archive feature (instead of deleting content) + perhaps a trash bin feature. ...we'll eventually work toword those things, I'm sure, and it will definitely make things easier by having "the best of both worlds":
- we wouldn't need to grant people the potentially dangerous `delete any *` permissions
- we would have a safe alternative to deleting (which is unpublishing), but with the same ease of use/workflow and granularity as the rest of the content-related permissions

**Comment by herbdool** [comment]
Looks good to me.

**Comment by klonos** [comment]
@herbdool almost. We missed one codding standard issue in the fix (space missing before one of the concatenation dots). See suggestion in PR.

**Comment by quicksketch** [comment]
I think @stpaultim updated the PR but didn't update the status. All coding standards are passing. I think this is ready to go.

**Comment by quicksketch** [comment]
Thanks folks! I merged https://github.com/backdrop/backdrop/pull/4419 into 1.x for 1.25.0.
