### ISSUE TITLE
Remove the "delete any" permission for new node types from the editor role.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#6101]
This was a change to the PR that everyone seemed to agree on, but was overlooked in 
https://github.com/backdrop/backdrop-issues/issues/5885

Adding this to the 1.25.0 milestone so we don't forget to do it before release :)

**Comment by quicksketch** [comment]
Maybe this should be combined with https://github.com/backdrop/backdrop-issues/issues/6078, since it's essentially the same question.

**Comment by jenlampton** [comment]
I'll do PRs for both, incase https://github.com/backdrop/backdrop-issues/issues/6078 isn't ready for 1.25.0.

**Comment by herbdool** [comment]
@jenlampton when initially creating a content type it will unselect the "delete any" permission for the editor, as expected. However, when updating the permissions on the content type, I was unable to save with the "delete any" permission selected. So it's not just affecting the defaults, but preventing it from every being changed.

**Comment by klonos** [comment]
I've left a couple of comments in the PR. One is for the inline comment, which needs tweaking in order to be 100% accurate and reflect what we are trying to do, and the other is to fix the issue that @herbdool mentioned in the previous comment here ^^ (untested though).

**Comment by klonos** [comment]
@jenlampton I had some ideas re cleaning up and standardizing most of the code related to the default content permissions (the ones that don't include the name of the content type, because we don't know it yet for new content types), and I tried to file a PR against yours, but because your branch is not rebased it came back with more changes than there were actually.

So I filed a separate alternative PR, starting off of your branch/commits: https://github.com/backdrop/backdrop/pull/4432 ...please see comment in the PR for a list of changes and reasoning. I have tested all the previous scenarios mentioned in previous comments, to make sure that no functionality breaks.

**Comment by klonos** [comment]
I've created a new follow-up here: #6106 and have linked my PR to it instead 😉

**Comment by quicksketch** [comment]
I applied the suggestions from the PR and this could use testing.

**Comment by laryn** [comment]
Works for me.

**Comment by laryn** [comment]
I'm going to remove 'needs code review' based on the fact that @klonos reviewed and had the changes applied in this PR.

**Comment by laryn** [comment]
Thanks for filing the followup and fixing in time for the release @jenlampton, and for code review, tweaks and testing @klonos, @quicksketch, and @herbdool. I've merged this into `1.25.0`.
