### ISSUE TITLE
Admin Bar Configuration Menu Leads to Blank White Screen

### ISSUE THREAD

**Issue by howardjacobson** [backdrop/backdrop-issues#616]
I have a default install of Backdrop CMS 1.0.0. Clicking on any menu or button to configure the Admin Bar leads to a blank white screen.  The URL is /admin/config/administration/admin_bar.

**Comment by klonos** [comment]
There was an issue with the admin bar config page that was fixed in #591. This is now resolved in 1.0.1 (to be out next week I think). You can manually apply [the changes from that issue](https://github.com/kunago/backdrop/commit/f2ae6ce5f76ef31f9bc18cee62511c61b37cd12c) and see if it fixes things for you.

**Comment by quicksketch** [comment]
Thanks @howardjacobson! Yes, like @klonos says, it's a (very visible) bug in the 1.0.0 version. We'll be making 1.0.1 shortly that includes the fix.

Thanks for filing this issue. Please let us know if you encounter any other issues with 1.0.0 and we'll try to get those fixed before the release next week as well!
