### ISSUE TITLE
Config override in settings.php file doesn't work for permissions

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#6193]
## Description of the need

We constantly sync DB from production to local dev branch and have to manually set permissions after each sync. Would be nice if the config override system worked also for permissions.

## Additional information

Unfortunately, the overrides in settings.php like:

```php
// Perms
$config['user.role.authenticated']['permissions'] = ['access devel information', 'switch users'];
```

or

```php
// Perms
$config['user.role.authenticated']['permissions'][] = 'access devel information';
$config['user.role.authenticated']['permissions'][] = 'switch users'];

```

have no effect.

**Comment by argiepiano** [comment]
Have you tried
```php
$config['user.role.authenticated.permissions'] = ['access devel information', 'switch users'];
```

**Comment by kiamlaluno** [comment]
Overrides do not work for roles (including their permissions) because the code loading a role from the configuration file is the following.

```php
$names = config_get_names_with_prefix('user.role.');
foreach ($names as $config_name) {
  $config = config($config_name);
  $role_name = str_replace('user.role.', '', $config_name);
  $role_data = $config->get();
  $role_data += array(
    'weight' => 0,
    'description' => '',
    'permissions' => array(),
  );
}
```

As the role data is loaded with `$config->get()` (without a value for `$key`), [`Config::getOverride()`](https://docs.backdropcms.org/api/backdrop/core%21includes%21config.inc/function/Config%3A%3AgetOverride/1) will return `NULL`.

```php
$value = NULL;
$parts = explode('.', (string) $key);
$popped_parts = array();
while ($parts) {
  $assembled_key = implode('.', $parts);
  if (isset($this->overrides[$assembled_key])) {
    // An override is matched at some level.
    $value = $this->overrides[$assembled_key];
    // Drill down back into the override value to get the requested key.
    foreach ($popped_parts as $popped_part) {
      if (isset($value[$popped_part])) {
        $value = $value[$popped_part];
      }
      else {
        $value = NULL;
        $popped_parts = array();
      }
    }
  }
  // If an override was not found at this key, go up a level in the key
  // and continue until there are no more $parts left.
  array_unshift($popped_parts, array_pop($parts));
}

return $value;
```

Differently, [`Config::getOriginal()`](https://docs.backdropcms.org/api/backdrop/core%21includes%21config.inc/function/Config%3A%3AgetOriginal/1) (without arguments, or when `$key` is `''`) will return all the config data stored in the config file.

```php
if (!$this->isLoaded) {
  $this->load();
}
if (empty($key)) {
  return $this->data;
}
```

Both those methods are called by [`Config::get()`](https://docs.backdropcms.org/api/backdrop/core%21includes%21config.inc/function/Config%3A%3Aget/1).

```php
$value = $this->getOverride($key);
if (!isset($value)) {
  $value = $this->getOriginal($key);
}
return $value;
```

The actual issue is that overrides in `$config` are never used when the code calls `Config::get()` (without parameters), for any configuration object and any configuration value, not just for roles and role permissions.

If a module were to use this code, the overrides would be used.

```php
// Load the authenticated role.
$config = config('user.role.authenticated');
// Get its permissions.
$permissions = $config->get('permissions');
```

**Comment by alanmels** [comment]
@kiamlaluno Thanks for analysis. That's why I created this as a feature request in hope we could make necessary changes in core.

**Comment by alanmels** [comment]
https://github.com/backdrop-contrib/state_override/issues/2 has been resolved, so now we can override permissions for roles.
