### ISSUE TITLE
Need update hook for date_views.settings - settings lost in D7 upgrade

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#6204]
## Description of the bug

When upgrading from D7, the date_views settings are lost.

This is a follow-up to https://github.com/backdrop/backdrop-issues/issues/2766 which restores the Page by Date functionality in Date. What is missing from that is an update hook to convert date_views_* variables to CMI.

Also `date_menu()` should not make the date-views admin page be `MENU_LOCAL_TASK` since there's no parent.

**Comment by herbdool** [comment]
Thanks @albanycomputers. I've made the fix to setting the config. The parts about `$config->isNew()` is fine, because in the second instance it returns before moving on.

By the way, you can add comments directly on the lines in the PR by clicking on the plus sign next to the line number. It also helps to wrap your code in comments with backticks "`".

**Comment by albanycomputers** [comment]
> The parts about `$config->isNew()` is fine, because in the second instance it returns before moving on.

No, I understand that :-)

> add comments directly on the lines in the PR by clicking on the plus sign

Oh, nice... I didn't know that :-)

**Comment by bugfolder** [comment]
@herbdool, there are conflicts; can you rebase the PR?

Also, a question: I see you `update_variable_get()` the config variables, but don't subsequently `update_variable_del()` them. Shouldn't they be deleted from `variables` after the upgrade?

**Comment by herbdool** [comment]
@bugfolder thanks, I'll rebase.

The `update_variable_del()`s were already there - they were removed without converting them. So I only needed to add the conversion part.

**Comment by bugfolder** [comment]
I've now tested this:

* Set up a new Drupal 7 site.
* Enable Views and Views UI and Date module (and their required modules).
* Create two Articles.
* Create a View that shows the articles, select "Page by Date" for the pager.
* Install Backdrop 1.26.0 (not including this patch), run the update.

Result: there is no date_views.settings config file (verifying the problem).

* Restore the D7 site.
* Apply the patch 4504.diff.
* Run the update.

Now there are default settings in date_views.settings.json config, verifying that defaults are properly set even when prior updates wiped out the variables.

* Restore the D7 site.
* Create non-default settings for the Date Views settings (add Time Zone, T, to each setting).
* Install Backdrop 1.26.0, but this time apply this patch.
* Run the update. (There's one more update than before, as expected.)

Inspect `date_views.settings`. Now the non-standard settings that were in D7 are present in the config file.

* Go to `admin/config/regional/date-views`. The values from D7 are present, but "Date view day format with year" is blank.

![Screen Shot 2023-09-28 at 6 47 06 PM](https://github.com/backdrop/backdrop-issues/assets/29214084/8e144d2b-9a86-4d7f-8ad4-35cc98352c5e)

I believe this is because the string `date_views_date_format_with_year` in the PR (which appears in 3 places) should be `date_views_day_format_with_year`.

And indeed, if I modify the patch to make this change, restore the D7 site, then re-run the upgrade, all of the Date Views settings do appear with their proper values.

So, after updating the PR to address that issue, I expect that this will be WFM.

**Comment by bugfolder** [comment]
@herbdool, just a small update to the PR and this will (probably) be ready to go...

**Comment by herbdool** [comment]
Thanks for catching that @bugfolder

**Comment by quicksketch** [comment]
Thanks @herbdool, @bugfolder, and @albanycomputers! I merged https://github.com/backdrop/backdrop/pull/4504 into 1.x and 1.26.x.
