### ISSUE TITLE
Accessing 'site_name'

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#621]
Apologies for asking something so basic but how should I replace
'@sitename' => variable_get('site_name', ' ') 
Is it simply '@sitename' => config_get('site_name')  ?

**Comment by quicksketch** [comment]
To get any configuration option, you have to specify which file it needs to be loaded from. So instead of

```
variable_get('site_name', ' ') 
```

It would be:

```
config_get('system.core', 'site_name);
```

Note that you no longer need to specify a default value, since a value should *always* be available in the current configuration. I answered a similar question over here earlier: https://github.com/backdrop-ops/contrib/issues/19

We're just getting started on documentation, but you can find a good overview of how to work with CMI at https://api.backdropcms.org/node/28621.

**Comment by Graham-72** [comment]
Thanks for explanation
