### ISSUE TITLE
Create a great api for designers

### ISSUE THREAD

**Issue by philippejadin** [backdrop/backdrop-issues#624]
Please work on an enhanced api that designers (themers) will understand.

Today again I tried (and failed) to theme links in Drupal 7. A royal pain.

I don't want to use theme preprocessing function. I don't want to use render arrays. Ever. I will not touch or learn this.

I'd like to see simple templates using simple, fail proof objects and simple render functions. I want to use simple php to control it all.

It's not evil to have display logic in template. It is evil (to a poor themer) to put presentation logic in a separate file with crazy syntax.

I want to do that : 
```php
<?php foreach ($comments as $comment): ?>

<?php print ($comment->title) ?>

<a href="<?php print ($comment->author->url) ?>">
<?php print ($comment->author->name); ?>
</a>

<?php print($comment->body->filter('Simple HTML')); ?>

<?php endforeach; ?>
```

Or that : 

```php
$links->get('comments_add')->hide();

<?php foreach ($links as $link): ?>
<a href="<?php print $link->url; ?>"><?php print $link->title->trim(50); ?></a>
<?php endforeach; ?>
```

Or that : 

```php
<?php if ($node->viewmode == 'teaser') : ?>
<?php print ($node->fields->get('body')->trim(300)); ?>
```
Frankly, who will ever understand this (taken from bootstrap theme): 

```php
function bootstrap_preprocess_breadcrumb(&$variables) {
  $breadcrumb = &$variables['breadcrumb'];

  // Optionally get rid of the homepage link.
  $show_breadcrumb_home = theme_get_setting('bootstrap_breadcrumb_home');
  if (!$show_breadcrumb_home) {
    array_shift($breadcrumb);
  }

  if (theme_get_setting('bootstrap_breadcrumb_title') && !empty($breadcrumb)) {
    $item = menu_get_item();
    $breadcrumb[] = array(
      // If we are on a non-default tab, use the tab's title.
      'data' => !empty($item['tab_parent']) ? check_plain($item['title']) : drupal_get_title(),
      'class' => array('active'),
    );
  }
}
```

Instead I'd like to see this : 

```php
<?php foreach ($breadcrumbs as $breadcrumb): ?>

    <a href="<?php print $breadcrumb->url; ?>"><?php print $breadcrumb->title->trim(50); ?></a>
    <?php 
    if (!$breadcrumb->isLast())
    {
        print '>';
    }
    ?>

<?php endforeach; ?>
```

And play with whatever iterator system there is in php object to make life easier and more understandable.

Start to document the ideal system (from a themer perspective), then implement it.

Yes this was a rant :-) I have huge hope for Backdrop.

**Comment by quicksketch** [comment]
LOL, thanks @philippejadin for opening this issue. It sounds like we've got shared goals for the most part. Check out the Theme System Meta issue in #125. We eliminated one layer of processing (but not both), simplified our templates, reduced use of renderables, moved CSS classes into templates, and a lot of other improvements in 1.0. We're also still using PHP template, not Twig or another theme engine. Although Twig is being touted as easy, when you look at the craziness that is D8 templates, you might think otherwise.

The overall simplification of the theme system are as far as we could take them in 1.0.0, most new changes will need to wait until the 2.x release to be fixed, since they usually involve modification of templates, which is an API change that would break existing sites.

**Comment by philippejadin** [comment]
A way to pave the future for templates in backdrop without breaking 1.x compatibility would be to introduce a new set of objects usable by templaters.

Introducing the $tpl object !

$tpl does everything, and saves lives at the same time.

With $tpl, you can do that : 
```php
$tpl->node->title(); // in the context of a node template
$tpl->view->results()->getfirst()->title() // in the context of a view template
$tpl->menu->name(); // when working with menus
$tpl->node->fields->cover_image->render('thumbnail');
```

And a always available `$tpl->help()`, a function that shows everything (public functions and variables, using php reflection api) the themer can use **in this specific template context**.  So the workflow would be for the themer, to first echo $tpl->help() and just read what (s)he can use in this specific context.

The themers could decide to enable backward compatibility and still have all the globals $node, $title, etc... and everything available in the scope of their theme, or they could use "strict" mode, where only the $tpl object would be available in the scope of their themes, ensuring a clean workflow.

You can introduce this new $tpl object in the course of backdrop 1.x and deprecate the rest for  2.x.

Sounds like a plan ?

**Comment by quicksketch** [comment]
I'm not sure, the proposal to use some kind of super-object basically mirrors the approach of jQuery, e.g. `$tpl` operates the same way as jQuery's `$`. Each time it is called, it returns itself. For a PHP equivalent, this is also the same approach used by DBTNG in Drupal 7.

Now obviously jQuery is a proven success, but I don't think we'd see the same positive results doing this in templates. Instead we'd probably end up with a generally disliked and over-abstracted system like DBTNG. Reasons why:

- Unlike jQuery where almost all chaining is done to traverse the DOM, there are lots of different types of data in Backdrop. In your example there is traversal of menu objects, view results, node titles, fields, etc. Each of these would likely require different methods. This makes documenting these things in a way like http://api.jquery.com (or even our own API site) very difficult. We'd probably end up with documentation similar to DBTNG (https://www.drupal.org/developing/api/database), scattered, verbose, and dense.
- The system proposed could in theory be "self-documenting" through a `->help()` method, but that means building out a fairly large amount of infrastructure to register all methods and variables that need to be documented. The likely solution to this would be using PHP's Reflection API, which reads docblocks on functions and variables. That sort of magic (code comments being used for functionality) is something we've been striving to avoid.
- The amount of overhead this would introduce would almost certainly have a performance impact. D8 implemented exactly what you're describing to access entity data. It's one of many reasons D8 so slow. I'm not sure the D8 system is fully documented at this point, but it's essentially the same as the D7 Entity API module: https://www.drupal.org/documentation/entity-metadata-wrappers
- Most themers I seen do not use an IDE of any kind. I could see this speeding up development for developers that have an autocomplete on available methods, but I don't think that's the majority of our users. Backdrop should be able to be developed with basic tools.

The overall proposal sounds as though it's trying to achieve "easy" but it's doing it by using a complex solution. I'd much prefer to attempt to reach easy by *simplifying* our approach rather than reinventing/replacing it.

If you haven't already read over them, I'd encourage you to read over our [project philosophy](https://backdropcms.org/philosophy) and weigh this proposal against Backdrop's principles. A lot of it depends on implementation of course, but from what's been described and the experience we have with existing similar solutions, I don't think it's a good fit.

**Comment by philippejadin** [comment]
Thank you for taking the time to elaborate on my ramblings :-)

- if it's slow then I agree it's not a good idea at all.
- if it cannot be documented easily (or if php reflection is evil) not a good idea either
- I've read philosophy, and that's why I will upgrade to backdrop when drupal 7 will be too problematic :-)

I was trying to find a solution to make it possible to work now on even more simplification without breaking compatibility with what works today.

For example, in node templates, you already have a $node var, so I thought that having some kind of namespace like $tpl->node would avoid breaking the existing $node in current templates.

But my main point is to provide **smarter** objects to themers. If they are not under a single $tpl, it's not a big problem. The goal was that it would be easy to print_r ($tpl) to know what you have access to (or simplier do : $tpl->help())

A smart object (in templates) means for example : 

- a node that allows one to iterate over each field easily, 
- a node that doesn't show a field twice if it has been rendered already elsewhere.
- a field that escapes/filters/render content by default
- a fields that allows access to raw data easily
- a field that allows one to access it's parent node easily
- a file field where you can get filesystem path, public url, image style url, using simple methods
- a view where each row and field can be accessed without being rendered twice if already rendered manually
-  a menu where you can do all sorts of queries to have only 1st level items, parent item, all tree

etc...

Or said otherwise, never access variables directly, use methods, so the smart object **knows** that something (a field) has been accessed (and rendered).

Templates must be beautiful to read. It must be as much as possible like reading natural language.

But I'm not a developer, sorry if this doesn't not make perfect sense. I'm sure you'll find a sensible way. And thanks for taking care!

**Comment by philippejadin** [comment]
Looking a bit deeper at backdrop, I came to the conclusion that you know way better than I (which was to be expected :-), so closing this one.

Great work so far !

**Comment by quicksketch** [comment]
Thanks @philippejadin! I really appreciate the feedback. :smile:
