### ISSUE TITLE
The node author name does not change upon editing the user account name.

### ISSUE THREAD

**Issue by suriyan2538** [backdrop/backdrop-issues#6243]
hello

Recently, I found that when editing a username When I returned to the node edit page In the node author name field Still my old name If I want to save a node I will need to edit the name in the node creator field to match my new username. Otherwise, the node cannot be saved. with the message: This user account was not found.

Generally, when a user changes the user account name. The node author name should automatically change to reflect the current name.

Additionally, if the user experiencing the problem is not an administrator, and does not have permission to edit the username in the node author field. That user will not be able to do anything. In addition to going back to using your old name

I'm not sure if this is an intentional feature or not. Or is it a Backdrop CMS bug?

Backdrop 1.26.0

If there is anything inappropriate in my comments I am very sorry.

**Comment by indigoxela** [comment]
Hi @suriyan2538, welcome to Backdrop CMS and many thanks for taking the time to report. :+1:

I can confirm the behavior, the **display** of author's name changes, but when I open the node _form_, it's still the previous username in the "Authored by" field.

But... if I flush all caches, the author field is also updated. I'm assuming, this has to do with the entity cache, but didn't dig deeper. My understanding is, that this is a bug, as it leads to "The username OLD_NAME does not exist.", when trying to save such a node without changes in the author (autocomplete) field.

**Comment by indigoxela** [comment]
After playing with it a bit: yes this is caused by the entity cache, so actually easy to fix. A [PR](https://github.com/backdrop/backdrop/pull/4530) is available for testing and review. Also contains a functional test.

@suriyan2538 you seem to be new here in our issue queue. Our PRs have a Tugboat sandbox, to directly test changes here, they're linked from the PR page.

If you'd prefer to test locally, you can get a diff to apply via [this url](https://patch-diff.githubusercontent.com/raw/backdrop/backdrop/pull/4530.diff). Whatever works best for you. :smiley:

**Comment by argiepiano** [comment]
Thank you both for your work on this. @indigoxela, I'm noticing that user_node_load() also attaches the user's `picture` and `data` columns to the node object. Your PR only tests for `name`. Would it be a good idea to test if these two other columns have also been updated?

**Comment by indigoxela** [comment]
@argiepiano many thanks for having a look.

Although only the name is relevant for the node form, you're right about additional data. They get attached and that info shouldn't be outdated in the cache.

**Comment by stpaultim** [comment]
Sorry, reread your comment and you state pretty clearly that you did both. You tested the PR and looked at the code. I'll assume it was an oversight to not remove the "Needs Testing" tag. I'll do that now.

**Comment by klonos** [comment]
@indigoxela I noticed that the test tries to load the node and user data programmatically, and then does an `assertEqual`. Should we actually be checking the process that was reported in this issue? In other words, should we add to the test to 
try to update a node via the UI after user data was updated since creation of the node, and then assert that there are no errors when the form is submitted.

**Comment by quicksketch** [comment]
Thanks folks, great work here! This seems like the sort of thing that might long-term be solved by cache tags (#4127), where nodes would be tagged with the author's UID. But this solution is direct and solves the immediate problem.

I merged https://github.com/backdrop/backdrop/pull/4530 into 1.x and 1.26.x for the 1.26.1 release. Thanks @indigoxela, @suriyan2538, @argiepiano, @izmeez, @klonos, and @stpaultim!

A special welcome to @suriyan2538! We are honored to have this be your first ever GitHub issue! Welcome to the Backdrop community and thanks so much for creating this issue.
