### ISSUE TITLE
Finish removing outdated Date settings.

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#6311]
## Description of the bug

At one point we renamed/moved from a `date.settings` config file to including date formats in the `system.date` config. We tried to clean up after ourselves in `date_update_1001()`:

> config('date_api.settings')->delete();
> config('date.settings')->delete();

We neglected to remove the `hook_config_info()` however, so essentially empty configs get recreated.

https://github.com/backdrop/backdrop/blob/1.x/core/modules/date/date.module#L647-L650

**Comment by argiepiano** [comment]
PR https://github.com/backdrop/backdrop/pull/4617 ready for testing and review.

I don't think these lines actually caused "empty configs [to] get recreated". But they should be removed, since the config is never used.

**Comment by kiamlaluno** [comment]
`hook_config_info()` is invoked by [`config_import_single_form_validate()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21config%21config.admin.inc/function/config_import_single_form_validate/1) which checks which configurations can be imported. With `date_config_info()`, the *The configuration could not be imported because no module could recognize the "date.settings" configuration name.* error would not be shown.

**Comment by argiepiano** [comment]
@kiamlaluno, the thing is, `date.settings.json` doesn't exist, so it will never be imported.

**Comment by kiamlaluno** [comment]
@argiepiano I did not say it will be created, but that `config_import_single_form_validate()` will not immediately give an error message. Not even [`config_sync_validate_file()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21config%21config.sync.inc/function/config_sync_validate_file/1) would give an immediate error message, since it calls [`config_get_info()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21config%21config.module/function/config_get_info/1).

I think that giving an immediate error is preferable. Ergo, it is better to remove part of the array returned by `date_config_info()`.

**Comment by argiepiano** [comment]
@kiamlaluno I'm really not sure what you are suggesting. Can you please look at the PR and perhaps post some comments there, or perhaps suggest a different approach here or there?

**Comment by kiamlaluno** [comment]
@argiepiano I am not suggesting anything. I just said a reason for removing the lines defining the *date.settings* configuration.  

A comment said those lines would create empty configuration; a comment said empty configuration would not be created; I commented saying that without those lines defining the *date.settings* configuration, `config_import_single_form_validate()` would give an immediate error message when that configuration would be imported. That's all.

**Comment by kiamlaluno** [comment]
To test the PR, I visited /admin/config/development/configuration/single and tried to import the following configuration.

```json
 {
    "_config_name": "date.settings",
    "date": "2023-03-03"
}
```

The preview site created for this PR shows the following error message.

> The configuration could not be imported because no module could recognize the "date.settings" configuration name. 

![screenshot](https://github.com/backdrop/backdrop-issues/assets/29851/e6e0c960-d149-4624-a4ed-7e91ba423d20)

On a site without this PR, no error message is shown. Instead, the configuration is said to be correctly imported.

> The date.settings configuration was imported successfully. 

![screenshot](https://github.com/backdrop/backdrop-issues/assets/29851/54baa806-74dc-47a3-8a7e-b8b95ec769aa)

I am not sure this is the correct way to test the PR.

**Comment by kiamlaluno** [comment]
(Yes, I uploaded twice the same image. Now I fixed it.)

**Comment by argiepiano** [comment]
@kiamlaluno, of course, if you try to import ANY configuration json file that is not defined anywhere, you will get that error. That's the expected behavior.

As for testing the PR, what you did actually works well as a test. Before the PR you did not get an error (that was a bug) when trying to import a config json file that doesn't exist. . After the PR you SHOULD get the error when trying to import `date.settings.json` since that file does not/ must not / should not exist.

So, if you are satisfied with your testing, can you please update the labels here?

**Comment by kiamlaluno** [comment]
Since I correctly tested the PR, I changed the labels.

**Comment by quicksketch** [comment]
Thanks @argiepiano, @kiamlaluno, and @laryn! I have merged https://github.com/backdrop/backdrop/pull/4617 into 1.x and 1.27.x.
