### ISSUE TITLE
PHP notice after update from 1.26.3 to 1.27.0

### ISSUE THREAD

**Issue by findlabnet** [backdrop/backdrop-issues#6372]
## Description of the bug

Notice: Undefined index: wrapper_attributes in theme_item_list() (line 2413 of /DOCROOT/core/includes/theme.inc).

## Actual behavior

Multiple notices in dblog.
Currently I cannot debug it, maybe someone else has seen it too.

## Additional information
- Web server and its version: Apache 2.4.56
- PHP version: 7.4.33
- Database sever (MySQL or MariaDB?) and its version: 5.5.5-10.5.21-MariaDB-0+deb11u1
- Operating System and its version: Debian GNU/Linux 11.8

**Comment by quicksketch** [comment]
Thanks @findlabnet for the report. This is probably cause by #6148, which was a new feature in 1.27.0.

It seems like "wrapper_attributes" should be provided by default as an empty array by `backdrop_common_theme()`.

This seems obvious, but could you try clearing the Backdrop caches from the admin toolbar? Once the theme registry is rebuilt, the error should stop.

**Comment by findlabnet** [comment]
For some reason clearing the cache (which I do every time with code changes) does not help.
My dblogs were only cleared of this notice when the problematic string was replaced with
```
$wrapper_attributes = $variables['wrapper_attributes'] ?? array();
``` 
This is my one-time workaround, so the variable needs to be defined more clearly.

**Comment by argiepiano** [comment]
What's being output that produces this warning? IS it a field that uses an item list? (e.g. entityreference field?) Is it a field provided by contrib?

**Comment by findlabnet** [comment]
Produced by random requests from bots, or even my own from the admin theme (Seven).
I'll try to debug it later. 
I wonder if I'm the only one who got such notices?

**Comment by bugfolder** [comment]
Clearing all caches on the prod site seems to have stopped the warnings.

**Comment by bugfolder** [comment]
I found a way to reproduce this. I have a B installation that I use for all my contrib modules, which is currently on 1.26.2, and I updated the code to 1.27.0, then went to run the updates. After clicking "Continue" on the "Backdrop database update" page, I get this:

<img width="845" alt="image" src="https://github.com/backdrop/backdrop-issues/assets/29214084/e33bb3fd-7fa4-430f-80a5-936a3426c59a">

(Actually, the error is on line 2413; the 2418 is because I've inserted some code that lets me break when `wrapper_attributes` is missing.) The offending line is in `theme_item_list()`, and is

```
 $wrapper_attributes = $variables['wrapper_attributes'];
```

Rather than proceeding with the update, I backed off and inserted some code so I could break and look at what's going on. Which is that we're calling `theme('item_list', ...)` for the list of updates (the "5 pending updates"). And when `theme()` is setting up to call `theme_item_list()`, it first sets the default variables according to the information in the theme registry.

But the theme registry being referred to is the OLD cached theme registry, i.e., pre-update. Since we added `wrapper_atttributes` in 1.27.0, that property isn't getting set. And that's why we see the error—and also why clearing caches stops the warning. (I've not done that on my dev site so I can preserve the generating condition.)

Clearing the theme registry cache seems to be a way of fixing this issue. Should that be done early in the updating process (e.g., on the `core/update.php?op=info` page)?

**Comment by bugfolder** [comment]
PR created. To test:

* set up a Backdrop 1.26.x site.
* Install 1.27.0, patched with this PR.
* Go to update.php.
* Click "Continue" on the "Backdrop database update" page.
* The next screen shows warnings about wrapper_attributes without the patch, and no warnings with the patch.

(N.B. Not to derail this issue, but shouldn't "Backdrop database update" be "Backdrop site update," since both the database and/or config files may get updated?)

**Comment by laryn** [comment]
@bugfolder RE: your final N.B.: https://github.com/backdrop/backdrop-issues/issues/5630

**Comment by bugfolder** [comment]
@laryn, I thought the issue sounded familiar!

**Comment by bugfolder** [comment]
> Did you find that both functions were necessary to solve the problem?

No, I just copied the cache-clearing code (two lines) that admin_bar.module does. Your explanation makes sense, thanks. Ready for re-review/re-test.

**Comment by quicksketch** [comment]
Looks perfect, thanks @bugfolder! I merged https://github.com/backdrop/backdrop/pull/4641 into 1.x and 1.27.x. Thanks @findlabnet for filing the issue and everyone for providing feedback and testing.

This solution won't solve the problem 100% of the time. If a user upgrades to Backdrop 1.27.0 and visits the administrative interface, they may still get the warning until they visit update.php (at which point the theme cache is cleared). However we can't clear the caches arbitrarily so this is a good compromise to clear the cache automatically at a reasonable time.
