### ISSUE TITLE
Improve the database configuration comments in settings.php.

### ISSUE THREAD

**Issue by bugfolder** [backdrop/backdrop-issues#6378]
It's been suggested that we add some description of the array format for database configuration in settings.php. See discussion starting here (and links therein):

https://github.com/backdrop/backdrop-issues/issues/2231#issuecomment-1904857316

Currently in the docblock for `$database`, there is a link to "advanced database documentation" at https://api.backdropcms.org/database-configuration. However, this currently redirects to https://docs.backdropcms.org/documentation/database-configuration, and so at the very least, we should update the link.

As for whether to add some commentary about the array format directly (rather than relying on click-through to the advanced docs), reasonable minds may differ, but I think the penalty of the extra reading material would be worth increasing people's awareness of the existence of of the array format. So perhaps giving a single example of the array format in the docblock, then directing the reader to the documentation page for the details.

**Comment by yorkshire-pudding** [comment]
@izmeez @bugfolder - please note the discussion regarding level of documentation in `settings.php`
https://github.com/backdrop/backdrop-issues/issues/2231#issuecomment-2333618035

**Comment by yorkshire-pudding** [comment]
> @yorkshire-pudding Thanks for bringing the issue to the dev meeting for discussion and for providing a link to the time. Following the discussion I am wondering where this leaves things. Is it just a matter of improving the comments in settings.php file as opposed to switching to a simplified array? In other words should this issue and #2231 be combined? Either way I think the additional comment in settings.php should include a brief comment that this may be needed for passwords with special characters and the utf8mb charset and collation lines should be included and a link to the documentation page. The "like D7" stuff can be dropped and replaced with "Alternatively,".

@izmeez - I will be reviving my old PR as it will need rebasing. We will be moving towards the simplified array and providing short documentation but looking to improve the online documentation.

Going forward, the installer will write to the simplified array rather than the db URL string, which, even with encoding, [can still cause issues with certain passwords.](https://github.com/backdrop/backdrop-issues/issues/2904).

Backdrop will support three different methods, the string, the simplified array and the D7-like array, which will be needed if people have secondary databases.  The D7-like array is used internally anyway.

Hope that helps.  It might be simpler to focus on one issue so all the changes happen at the same time

**Comment by quicksketch** [comment]
We discussed this today in the weekly meeting. Some changes discussed and agreed upon (both @yorkshire-pudding and @izmeez were present):

- Add charset and collation as allowed options in the new syntax, but provide reasonable defaults.
- Include charset and collation in the docblock list of advanced configuration options which can be set but link to the documentation for details.
- The default for charset should be changed to `utf8mb4`. So if you're using the simplified array syntax, that charset is implied.
