### ISSUE TITLE
[DX] Backward compatibility in theme_item_list()

### ISSUE THREAD

**Issue by VasasA** [backdrop/backdrop-issues#6398]
## Description of the need

Since 1.27.0 added the `'wrapper_attributes'` parameter in the `$variable` array in core/includes/theme.inc > `function theme_item_list($variables)`. We should check the existence of this parameter if we want backward compatibility for the contrib modules.

## Proposed solution

Now:
```
function theme_item_list($variables) {
  ...
  $wrapper_attributes = $variables['wrapper_attributes'];
```
Fixed:
```
$wrapper_attributes = isset($variables['wrapper_attributes']) ? $variables['wrapper_attributes'] : array();
```

## Additional information

Similar situation with the `'empty'` parameter since 1.21.0.
```
$empty= isset($variables['empty']) ? $variables['empty'] : '';
```

**Comment by bugfolder** [comment]
Also, https://github.com/backdrop/backdrop/pull/4641 (Issue #6372: Fix wrapper_attributes warnings when updating) was merged last week.

**Comment by argiepiano** [comment]
Great @bugfolder . I believe this issue can be closed, then.

**Comment by VasasA** [comment]
@argiepiano I had to set the `'wrapper_attributes'` parameter in the LDAP module in this [commit](https://github.com/backdrop-contrib/ldap/commit/2ec2d221ed9281e5e3447fc6561a14bca8e52807), because I was getting warnings.
There is another parameter too: `empty`
I think the backdrop/backdrop#4641 doesn't fix this problem.

**Comment by argiepiano** [comment]
@VasasA `empty` was added 2 years ago in 1.22, as [you can see here](https://github.com/backdrop/backdrop-issues/issues/5380). So, the issue with that has not been reported.  

I see a problem with the commit you linked above. `ldap_servers.test_form.inc` calls `theme_list_item()` directly, rather than calling `theme('list_item', array(PARAMS));`.

Calling the theming function directly is problematic, as no defaults will be provided. So, the problem is with  that function in ldap, not with Backdrop as far as I can tell.

**Comment by argiepiano** [comment]
In other words, the correct way in the code you linked in ldap is:

```php
$output = theme('item_list', array(
      'items' => $properties,
      'type' => 'ul',
      'title' => 'Server Properties',
    ));
```

**Comment by bugfolder** [comment]
To underscore what @argiepiano just said, the [theme functions documentation](https://docs.backdropcms.org/api/backdrop/theme-functions) says:

Note that you should never call a theme function directly; instead of
```
$output = theme_something($variables);
```
you should call
```
$output = theme('something', $variables);
```
to allow for overrides and modifications. See [Default theme implementations](https://docs.backdropcms.org/api/backdrop/core%21modules%21system%21theme.api.php/group/themeable/1) for more details.

**Comment by VasasA** [comment]
@argiepiano @bugfolder Thank you very much. I have tested with `theme()`, it works.
