### ISSUE TITLE
Redesign & re-style the edit / revisions / view tabs on the front end

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#641]
Something that has always bothered me is the way the edit/view tabs look by default.  Can we get a design refresh on these?  please please please? :)
![zomg-it-is-not-1994](https://cloud.githubusercontent.com/assets/397895/5914559/c8785cf2-a5ac-11e4-9538-32e34147b949.png)

**Comment by klonos** [comment]
Do you mean Bartik?

**Comment by docwilmot** [comment]
Related https://github.com/backdrop/backdrop-issues/issues/464, which I would love to see.

**Comment by tjdjours** [comment]
>Related #464, which I would love to see.
Related #370, one step removed. Could reuse/reinforce a pattern. 

Tabs as they are now, on a node page, are terribly confusing/annoying. The questions: What are they? Why are they taking up so much space? The tension between Where are they? vs Why do I have to see them ?

**Comment by Lowell20** [comment]
In my experience I get new admins confused about the node edit tab because
it looks like something that anonymous user will see, and it changes the
appearance of the node/page. I will usually try to disable those tabs and
add menu block or something similar for the node edit link.

Also, I never use contextual links for production site, only for
development efficiency, like block and view edits, because they are
invisible until hovered, and what about touch screens?

So something in between would be awesome like the edit link next to node
title, but what if title is hidden?

I guess the menu option that has been suggested is more in line with my
past practices

**Comment by docwilmot** [comment]
![node2](https://cloud.githubusercontent.com/assets/1042283/5880876/e6c81904-a309-11e4-8051-f9616ca14538.png)

or 

![node](https://cloud.githubusercontent.com/assets/1042283/5880877/e6cc8e1c-a309-11e4-9f73-31e93f387bb5.PNG)

**Comment by jenlampton** [comment]
Well, what I actually meant was changing the default tab-style that comes out of from core:
![zomg-it-is-not-1994](https://cloud.githubusercontent.com/assets/397895/5914559/c8785cf2-a5ac-11e4-9538-32e34147b949.png)

However, I do think we should do something completely different in 2.x for these tabs... they were a strange Drupalism that people don't understand, you are exactly right.  Let's carry on talking about our options here.  

I liked the idea of using contextual links, but you are right disabling that module (or denying access) does present a bit of an issue.  @quicksketch and I also once tossed around the idea once about putting a giant "Edit" button (or maybe drop-button with revisions/devel as other links) in the black admin bar like previous versions of WP used to do.

**Comment by wesruv** [comment]
I'm of the opinion that core should provide very little fancy styling, and Seven (or the admin theme) should give us the gloss. Makes it easier to override, and the use case for unthemed core tabs is suuuper small.

The default CSS and markup has been update from what you see in the screenshots above, it is incredibly vanilla, but **much** easier to override and theme. There were so many stupid gotchas in the core CSS before I got to it.

I'd like to close this, is that gravy @jenlampton?

**Comment by jenlampton** [comment]
yes, closing :)
