### ISSUE TITLE
BACKDROP_AUTHENTICATED_ROLE is not a RID

### ISSUE THREAD

**Issue by alexhass** [backdrop/backdrop-issues#642]
It looks like BACKDROP_AUTHENTICATED_ROLE is a string and not a Role ID. This breaks existing Drupal code. What was the reason for changing this from an integer to a string?

**Comment by yamlfd** [comment]
Found the reason, but I must say this breaks code for sure and is not backward compatible. Additional the checkboxes arrays are not removing 0 values from array before saving like D8 does. This adds additional issues.

Additional the user_roles() function does no longer return an RID. Hell this can cause serious security issues.

**Comment by quicksketch** [comment]
> What was the reason for changing this from an integer to a string?

Using a string instead of an auto-increment integer prevents conflicts between environments (say two developers adding two different roles). It also makes it easier to identify the roles when they're stored in config, and it helps when working with roles in code.

> this breaks code for sure and is not backward compatible.

Yep, we're trying to be as compatible as possible, but adding configuration management required a lot of changes that were impossible to make backwards-compatible. There are a number of API changes documented at https://api.backdropcms.org/change-records. We're trying to be *as compatible as possible*, since 100% compatibility is not possible.

> Additional the checkboxes arrays are not removing 0 values from array before saving like D8 does.

The behavior of checkboxes should match the behavior in Drupal 7, we didn't change anything around form handling of checkboxes.

> Additional the user_roles() function does no longer return an RID. Hell this can cause serious security issues.

It returns an array of role names (not numeric IDs) by necessity, since roles no longer have numeric IDs.

**Comment by yamlfd** [comment]
I'm confused. I read everywhere that backdrop allows the installation of d7 modules or plans to allow. 

The uncountable many changes I already found show me that this is a lie. Many very important things are not working like D7. It is more like a mix of D8 with D7 stuff. That is really highly strange. With the changes i've made on GA I wonder more and more where there a differences to D8. This code is very close to D8. These few differences / non-object code is a joke. You better help with D8 and learn a bit of D8. D8 is not more difficult than backdrop. Never read so much bullsh** that D8 will loose it's old D7 users. Funny joke.

**Comment by klonos** [comment]
> It is more like a mix of D8 with D7 stuff...

I think it's more like D7 with some D8 stuff actually.

As for the rest, I'll leave it up to the Backdrop maintainers to officially reply ...though I believe that a. answers to such questions have been already given and b. with such an attitude, I don't think if it's worth even bothering.

I will only say that I think you are taking this WAY too personally. If you don't like the product, then you are free to choose to go with D8. If you find it easier to rewrite a module to D8 than to adjust it to work with Backdrop, then by all means go for it.

**Comment by klonos** [comment]
...oh, and by the way: http://drupalreleasedate.com

Shows April 2017 at the time of writing.

(sorry, couldn't help myself)

**Comment by quicksketch** [comment]
> I read everywhere that backdrop allows the installation of d7 modules or plans to allow. 

I'm pretty sure we've *never* claimed that, at least in an "official" response. The first response we had to this question was Sept 13, 2013, in which I described pretty much exactly what we have today: https://github.com/backdrop/backdrop-issues/issues/65:

> There's a reason why this is a fork and not a "Drupal 7+" or a distribution like Spark. Namely, an API like CMI is absolutely incompatible with Drupal 7's database storage. Considering a large number of tables will be eliminated in favor of configuration files, there's no real way that Backdrop can be compatible with Drupal 7. Things like views, which were both a hook (hook_views_default_views()) and (if overridden) were stored in the database. In Backdrop, hook_views_default_views() won't exist, because it's saved to a config file which can be put into version control and moved between servers. The removal of even a hook like this means Backdrop is not API-compatible.

> That said, Drupal 8 only has a 15% code overlap with Drupal 7 (in individual modules, by line changes). So porting a module to Drupal 8 is nearly rewriting it. That's the thing we're going to avoid. Backdrop should have more along the lines of a 90% overlap, making the transition significantly easier. At worst, it will be a D6 to D7 level upgrade, but I'm hoping for significantly easier than that. Drupal has never attempted to limit API changes at all, so making a conscious effort of changes only when needed should reduce the amount of changes drastically.

I covered these differences our <a href="https://www.youtube.com/watch?v=by8mMhIpARA">video on porting</a>. And our <a href="https://api.backdropcms.org/node/28621">documentation on "porting" a module</a> clearly indicates that API is not 100% compatible.

If there is actually a place where we have claimed total compatibility with Drupal 7, or even been misleading about our compatibility, then we will do what we can to correct that misconception.

**Comment by yamlfd** [comment]
I have upgraded 3 modules in past 1.5 years for D8 and I can say now after the Backdrop port I had to change the same lines in D8 like I did in Backdrop. Retrospectively I may better made a D8 to Backdrop migration. Just a feeling, but these 15% overlap is for sure not correct. As an example I can copy all my forms 1:1 from D8 to backdrop and these are most of the code changes. The rest of the code has not changed except some hook names for user/page_alter/form submit and how JS is attached.

Some things are different for sure, but in general all code and logic is the same between D7/D8/BD. I do not see big differences to D8. $config->get('account') and others are the same under BD and D8 - if I write config() or \Drupal::config() is not really rocket science or any benefit. I have also not *rewritten* any of the modules when I upgraded them from D7 to D8. D8 upgrade was just a smart upgrade like D6 to D7.

The only difficulty was to follow the D8 changelog over the last 2 years. Sometimes I hated it a lot, at least when some big changes went in and changed something the 3rd time. But that was only because I started when alpha releases started. 3rd time I've made this fault.

**Comment by quicksketch** [comment]
The amount of effort it takes to do a port is proportional to the module, to be sure. I ported External Links module to Backdrop in 15 minutes. I doubt the D8 port took too much longer than that, because it's mostly just adding JavaScript to the page and a settings form. However many modules are faced with a huge hurdle to adapt to D8. <a href="http://d8rules.org/">Rules</a> is seeking $45K+ in funding. I know the <a href="https://www.drupal.org/node/2075941">Webform team</a> has been contemplating a rewrite (of which I'm not a part of course) that they're estimating at 12 - 18 months.

From the sounds of things, you've managed to port Google Analytics module for the most part in a week, even without knowing the first thing about Backdrop. I think that's a huge accomplishment and what we had hoped for regarding the level of compatibility with Drupal 7.

If you think D8 is just as easy to port and write modules for, then that's great for Drupal 8 and hopefully it will have a successful and easy transition for developers and users from Drupal 7. I don't share that perspective, but you can choose to develop on whichever platform you prefer. If nothing else, Backdrop provides a new choice that you wouldn't have had otherwise. Now that you've evaluated both, you can decide which is best for your purposes.
