### ISSUE TITLE
Do not give the admin bar alert dot an icon

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#6501]
## Description of the bug

The "red dot" shown in the admin bar for critical status report notifications currently gets assigned an automatic "right chevron" icon. Also the padding on the text is slightly off so the number is not quite perfectly centered:

![image](https://github.com/backdrop/backdrop-issues/assets/100206/a098d4e0-a474-442f-8fa8-8c5fcd44fd21)

## Steps To Reproduce

To reproduce the behavior:
1. Fresh install of 1.x, leave "Check for Updates" enabled.
2. Open bootstrap.inc and set `BACKDROP_VERSION` to an older number.
3. Clear the caches.
4. Observer the admin bar red dot notification.

## Additional information

Add any other information that could help, such as:
- Backdrop CMS version: 1.x (1.28.0-dev)
- Browser(s) and their versions: all

**Comment by quicksketch** [comment]
PR ready for testing https://github.com/backdrop/backdrop/pull/4727

There's not a great way to test this in a sandbox. It may need to be tested locally to artificially create an error.

**Comment by indigoxela** [comment]
>  It may need to be tested locally to artificially create an error.

That's what I assumed, anyway. :wink: Hello empty "foobar" module with an update hook added.

I can confirm, that the change fixes the icon-plus-dot problem:

![dot-no-icon](https://github.com/backdrop/backdrop-issues/assets/842066/02c42cba-c239-4e69-a6e5-b4aa9b82af4c)

I left an off topic comment on the PR - feel free to ignore. (Too early, not enough coffee, yet...)

**Comment by quicksketch** [comment]
I'm not sure, what would we gain by having it be an SVG?

**Comment by klonos** [comment]
The benefits are not as considerable as when replacing .png with .svg (and that dot icon is currently markup and CSS), but I recall having problems with aligning the number within the icon, and to this day I sometimes see it not being completely round (it seems slightly elliptical, like by 1px or something - I cannot recall exactly and that might only be the case when there's a double digit number of errors though). SVG on the other hand supports `<circle>`, which is consistently rendered as a circle across browsers.

FTR, this works very well for me:
```html
<span style="color:red">
  <svg height="80" width="80" xmlns="http://www.w3.org/2000/svg">
    <circle r="35" cx="40" cy="40" fill="currentColor" />
    <text x="50%" y="53%" text-anchor="middle" dominant-baseline="middle" fill="white" font-size=2em font-family="Sans, Arial">100</text>
  </svg>
</span>
```
Noting the use of `dominant-baseline="central"` instead of `alignment-baseline="central"`, in order to have everything behave consistently across browsers (Firefox seems to be the problem when it comes to that) - credits here: https://stackoverflow.com/a/60919616

**Comment by klonos** [comment]
>it seems slightly elliptical, like by 1px or something

See what I mean: 
<img width="173" alt="image" src="https://github.com/backdrop/backdrop-issues/assets/2423362/a924553f-eb86-4fad-bbc6-a6a7c83249ea">

**Comment by indigoxela** [comment]
@klonos re A11Y, if we switched to icons (which I don't recommend), we'd have to take care of the proper alt text. Currently it's just styled text. An inline icon would require a `<title>` **tag** with the (translated) information within the `<svg>` tag. (Not sure, if our API even provides that.) And we'd also have to take care, that we pick the correct one of the icons (the number we need). Or actually, we'd probably have to *generate* svg on-the-fly.

To me this seems like _huge_ effort for very little to no gain. However, if it's crucial for you, maybe open a feature request issue (bigger change... eventually additional API...). Otherwise the discussion here might block a simple bug fix.

Re that it's not a perfect circle for you: this might depend on system fonts (in your OS)? For me it's round. And, TBH, I wouldn't actually mind if it weren't. But that's me. :wink:

**Comment by klonos** [comment]
> ... maybe open a feature request issue ... Otherwise the discussion here might block a simple bug fix.

That's what I mean't by this:

> I think that in the long term we should be looking to replace that "dot icon" with an SVG.

...sorry if it wasn't clear - the emphasis was meant for the "in the long term". So yes. Separate issue - I ever meant to block this one here.

With regards to a11y and SVG titles, yes, I was reading up on these and was planning to :
- https://www.drupal.org/project/svg_image/issues/2988464
- https://www.drupal.org/project/drupal/issues/2433761 (points 6 and 7 in "Best practices")

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/4727 into 1.x for 1.28.0 to resolve this little issue.
