### ISSUE TITLE
Add Markdown Editor Support with CKEditor 5

### ISSUE THREAD

**Issue by farhannorth** [backdrop/backdrop-issues#6559]
Problem/Motivation:
Currently,  backdrop lacks native support for a Markdown editor. Many users prefer Markdown for its simplicity and ease of use. Integrating CKEditor 5 with Markdown support would enhance content editing capabilities and improve user experience.

Proposed Resolution:
Integrate CKEditor 5 with Markdown support as an optional text editor in backdrop. This can be achieved by leveraging CKEditor 5’s Markdown plugin, providing users with a seamless and modern markdown editing experience.

Alternatives:
An alternative would be to use a different Markdown editor plugin, but CKEditor 5 is preferred due to its robust features and active development community.

Additional Information:
For more details on CKEditor 5 and its Markdown plugin, see the [CKEditor 5 documentation](https://ckeditor.com/ckeditor-5/demo/markdown/).

**Comment by bugfolder** [comment]
There is a [Markdown](https://backdropcms.org/project/markdown) contrib module.

**Comment by klonos** [comment]
@farhannorth I believe that we are already including markdown-style editing by default with Backdrop since we introduced CKEditor 5. For instance, typing `- ` (dash followed by space) will start an unordered list, typing `1. ` (number, dot, space) will start an ordered list, typing `> ` (greater-then followed by a space) will start a quote, etc.

Are you talking about something different?

**Comment by quicksketch** [comment]
Hi @farhannorth, thanks for opening this issue request. We're happy to have new contributors and ideas.

In this case, I don't think this makes sense for core, since core does not have an ability to render Markdown. The [Markdown](https://backdropcms.org/project/markdown) contrib module adds that ability. But this request is different from what that module provides. This request is to use CKEditor 5 in combination with Markdown output. i.e. Editors would not actually enter markdown, they would use the visual editor, but it would save markdown into the database.

However, expanding core to support Markdown is probably not an in-scope feature for Backdrop core. Adding Markdown support to CKEditor would probably be best accomplished by a dedicated contrib module, i.e. a module named `ckeditor5_markdown` (this doesn't exist yet). And then combine that with the existing `Markdown` module to provide the rendering on the front-end.

Please reopen if you have further questions on the topic.
