### ISSUE TITLE
[DX] Make Coder (or similar solution) part of our workflow/testing infrastructure.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#659]
[Coder](https://www.drupal.org/project/coder)

This could automate certain things for us and ensure coding standards and best practices are "enforced". There's also a Coder Upgrade submodule I've never used that claims to "Modifies source code to assist with the upgrade of a module for changes to a relied upon API.". So, perhaps it could be used as a helper for porting modules from D7.

If these become part of core, it could call for a "Developer" or "Coder" installation profile that respective target group would have available upon installation.

Thoughts?

**Comment by quicksketch** [comment]
I do think it would be great to have more automated processes in place when submitting pull requests, e.g. ensuring coding standards with the PR and validating the commit message format. However, I'm not sure that putting Coder into core would be the right solution. Coder module takes a lot of effort to maintain and update, and it frequently reports false positives regarding some areas. The upgrade functionality is helpful, but not comprehensive or always accurate. Because of the difficulty of accurately reporting all possible issues with our code, I'd like to see basic checking put in place initially, such as checking for tabs, trailing whitespace, and the commit message is correctly formatted. That's probably more than 50% of the formatting problems with pull requests.

Whatever approach we take, integrating into the testing framework shouldn't be difficult. All we need to do is include the changes in the .travis.yml file to add an extra step after the tests themselves have been run.

**Comment by klonos** [comment]
...yeah, now that you mention false positives, I just run a vanilla D7 installation + Coder over at simplytest.me and I run a code review on a random core module. Here's what I got:

![update manager-code_review](https://cloud.githubusercontent.com/assets/2423362/5967905/fed056d6-a865-11e4-9881-361a2e5d09bd.png)

**Comment by quicksketch** [comment]
Yeah the last one is actually correct and would be easy to notice, though the message isn't correct. I think it's pointing out the space when defining the array: `array ('%file' => $file)`.

A good catch but not something we'd normally hold up a PR for in the first place.

**Comment by klonos** [comment]
Fair enough about the rest of your points. I only mentioned Coder because that was the only implementation I am aware of in Drupaland (hence the "or similar solution" part in the issue title). I am not a coder myself, but I've seen quite a few times patch reviews being dragged forever due to minor formatting issues and coder/reviewer back and forths till it's all "perfect". We could avoid all these sort of delays.

**Comment by quicksketch** [comment]
Yeah, agreed that syntax checking totally holds up issues unnecessarily. It's also a lot easier for people to accept feedback from a machine, assuming that machine effectively describes the problem and doesn't actually cause new problems, like failing a PR because of a false positive.

I'm not totally ruling out Coder, but I don't think I'd want it to be a part of core. We can adapt the .travis.yml file to check-out a copy of Coder (or any other syntax checker) and run the tests with it. That would allow Coder to develop in contrib while utilizing it in core's testing.

**Comment by docwilmot** [comment]
[Coder sniffer](https://www.drupal.org/node/1419980) (not the full Coder module, haven't tried, and won't try) works fine via command line. Using Drupal standards the code review and the code beautifier (automatically fixing malformed code) both work. Maybe we could plug that into Travis?

What would be nice is if this could be plugged into Backdrop contrib to run on each repository.

**Comment by kreynen** [comment]
Backdrop should be able to piggy back on the work Michael Hess and Neil Drumm are doing on code scanning referenced in https://www.drupal.org/node/2453587#comment-10126934.  Unfortunately there's no link to actual issue nodes or code :(

**Comment by docwilmot** [comment]
Any other thoughts on this? It's there any way to get coder integrated with contrib?

**Comment by klonos** [comment]
...depending on the outcome of #3213 we might eventually close this as a duplicate.

**Comment by serundeputy** [comment]
yes; I'm going to close this in favor of #3213; even though this issue came first we are discussing  the same toolsets, and the same outcomes over there, but with automated command line implementations that we can run in CI (travis, zen, etc.)

@docwilmot I use `composer require --dev backdrop/coder` on the `drush` contrib project and intend to use it on the rest of my contrib when I get a chance to implement.
