### ISSUE TITLE
[SOLVED] The token [node:book:parents:join-path] does not join path but joins the transliterated titles of the parent's book pages

### ISSUE THREAD

**Issue by paucku** [backdrop/backdrop-issues#6692]
## Description of the bug
First to say that I am not sure that this is a bug or it works as intended. But _according to me_ this is a bug.

What I expected that the token `[node:book:parents:join-path]` will join all the **paths** of the parent book pages.

What hapens is that the joined path are based on **their transliterated titles**. 

I want the paths to not neccessary be connected to the transliterated titles. I use the path as something like "machine name" for the pages.

## Expected behavior (according to me)
I am buidling a knowledge base with the Book module. I need the path to each subtopic to be automatically set on the base of the **paths** of all the parents on the chain line up to the root. 

In the settings URL ALIAS PATTERNS (admin/config/urls/path/patterns) for the specific content type – Book page – I set:
`[node:book:parents:join-path]/[node:title]`

What I expect here is that the token [node:book:parents:join-path] will join **all the paths** of the parent book pages.

## The real behaviour
What hapens is that the joined path is not based on the paths of the parents but **it is based on their transliterated titles**. 

## Why this is a problem?
I need to set a system for my path so they to be changed _as rarely as possible_ or _not changed at all_. 

I am writing a **math textbook** which is suitable for 5th, 6th and 7th grade. 

I want my 5th grade section to be at: `example.com/5`, my 6th grade section at `example.com/6` and my 7th grade section to be at "example.com/7".

I create a book titled "5th grade" but on the path settings i set simply "5".

Than make a child page to the current page which I title "Division".

The problem is that the path of the page "Division" **is not** `example.com/5/division` but is `example.com/5th-grade/division`.

Thus my hierarchy between book outline and paths **is not consistent**. 

An this happens because the _join-path_ token does not take the URLs of the parent book pages but it transliterates the titles every single time.

Yes, I can achieve the desirable behavoiur with mannually adjusting the paths when they are created. But would be more happy to set them automatically because the textbook will be very big.

I am happy to give more details if needed.

## SOLUTION
I achieved the wanted result by changing the **Default URL alias pattern** to 
`[node:book:parent:url:relative]/[node:book:title]` 

Read more for details.

**Comment by argiepiano** [comment]
Hi @paucku. Thanks for reporting. I can confirm that the token `[node:book:parents:join-path]` results in a string that uses a transliteration of the parent titles instead of the actual path alias of the parents. This has the same behavior in Drupal 7.

It is, indeed, a strange behavior, given the name of the token and its description. But it actually works as designed.

The token `join-path` is provided by the module `path` (`pathauto`) in D7, and it uses `path_clean_string()`, which transliterates whatever is passed - in this case, an array provided by the token `parents`.

`parents` on the other hand is provided by the module `menu` (in D7, by the module `token`). It actually provides an array of menu link **titles**. In the case of book pages, the book module creates entries in the menu_links table that allow the book navigation.

There is a cumbersome way to avoid this problem: manually edit the link titles. You can do this at `admin/content/book` by editing titles there (the base book page link title cannot be edited there - so that needs to be edited on the database table (!!!)). Of course, the disadvantage of doing this is that the book navigation will use the short titles (numbers, in your case, 4, 5...) instead of the full node title (5th Grade etc). 

A better solution would be to create a custom token that actually chains the path aliases of the parents. This would need to be a in a custom module. Or someone could add this to core. Creating a custom module for this may not be too complex (unfortunately I don't have the time right now).

It would be dangerous to "fix" the token `parents` to provide path aliases. It would break existing uses of the token, plus it is complicated since `parents` is not provided by the `path` module, but rather by `menu`, meaning that it would fail when `path` is disabled.

**Comment by argiepiano** [comment]
> I've just tried with the token [node:book:parents:join:/]. The result is the same as [node:book:parents:join-path] – it gives me the transliterated version of the parents titles, not the URLs.

Right. That's because `parents` returns the titles of the nodes, not the paths.

**Comment by argiepiano** [comment]
I just tried PHP Filter and Custom Tokens. It looks like PHP filter is not working (probably an incomplete port). So the best solution might be a custom module defining a custom token.

**Comment by paucku** [comment]
> So the best solution might be a custom module defining a custom token.

That is also what I am thinking about. 

Is it enough to create my own module and copy and modify `book.token.inc`?

`<?php
/**
 * @file
 * Builds placeholder replacement tokens for book-related data.
 */

/**
 * Implements hook_token_info().
 */
function book_token_info() {
  $info['tokens']['node']['book'] = array(
    'name' => t('Book'),
    'description' => t('The book page associated with the node.'),
    'type' => 'menu-link',
  );
  return $info;
}

/**
 * Implements hook_tokens() on behalf of book.module.
 */
function book_tokens($type, $tokens, array $data = array(), array $options = array()) {
  $replacements = array();
  $sanitize = !empty($options['sanitize']);

  // Node tokens.
  if ($type == 'node' && !empty($data['node'])) {
    $node = $data['node'];

    if (!empty($node->book['mlid'])) {
      // Skip access check to generate tokens before node grants are saved.
      $link = book_link_load($node->book['mlid'], TRUE);

      foreach ($tokens as $name => $original) {
        switch ($name) {
          case 'book':
            $replacements[$original] = $sanitize ? check_plain($link['title']) : $link['title'];
            break;
        }
      }

      // Chained token relationships.
      if ($book_tokens = token_find_with_prefix($tokens, 'book')) {
        $replacements += token_generate('menu-link', $book_tokens, array('menu-link' => $link), $options);
      }
    }
  }

  return $replacements;
}
`

**Comment by argiepiano** [comment]
I've put together a module / proof of concept for you:

https://github.com/argiepiano/mlink_alias_token

To use, enable it, then try the new token as follows:

`[node:book:parents-alias:join:/]`

This will generate a string of the parent aliases, joined by `/`. So, if your book alias pattern is 'book-page/[node:title]` and if you have three book pages in a tree as in 

- Level 1
-- Level 2
--- Level 3

Then the token will result into `book-page/level1/book-page/level2`  (notice the multiple `/`. This is because the alias pattern already contained a `/`).

**Comment by paucku** [comment]
> I've put together a module / proof of concept for you:
> 
> https://github.com/argiepiano/mlink_alias_token
> 
> To use, enable it, then try the new token as follows:
> 
> `[node:book:parents-alias:join:/]`

The modul is great. Thank you. 

It works great if the levels are one or two.

> Then the token will result into `book-page/level1/book-page/level2` (notice the multiple `/`. This is because the alias pattern already contained a `/`).

But there is some repetition for the deeper levels. I would like the URLs to be "level1/level2/level3".

For two levels things are: 
example.com/5/percentage

But for third level the URL is:
example.com/5/5/percentage/transformation

And for the fourth level:
example.com/5/5/percentage/5/5/percentage/transformation/from-decimal

**Comment by paucku** [comment]
A question: Shouldn't we use "==" instead of "=" in "if statements"?

**Comment by argiepiano** [comment]
Did you _actually_ try the module yourself?

There is no repetition of levels. The portion you see `book-page` is part of the alias. The module does exactly what I mentioned: it chains the aliases of the parents together. If your parent alias is `5` then that will be used.

**Comment by paucku** [comment]
> Did you _actually_ try the module yourself? 

Sorry to not be clear. Yes, I've tried the module myself. And this is _exactly_ the result:
```
- For two levels (correct): example.com/5/percentage
- For three levels(not correct): example.com/5/5/percentage/transformation
- For four levels(not correct): example.com/5/5/percentage/5/5/percentage/transformation/from-decimal
```
Maybe you didn't test it with more than two levels?

Here are the steps I make: 
1. Enable this module
2. Set URL path alias to `[node:book:parents-alias:join:/]/[node:title]`
3. Clear the cache
4. Go to an already published book page
5. Click Edit and then Save to update the URL path alias
6. The result is the above mentioned

The first level is manually generated. The other levels are generated automatically. (This doean's affect the result – I made first level also to be automatically generated and the result and there is the same repetition mentioned above.)

**Comment by paucku** [comment]
```
- For two levels (correct): example.com/5/percentage
- For three levels(not correct): example.com/5/5/percentage/transformation
- For four levels(not correct): example.com/5/5/percentage/5/5/percentage/transformation/from-decimal
```
Maybe for the every next level it takes the already generated URL for the previous levels instead of constructing a new one on the fly?

Between second and third level:
```
example.com/**5/percentage**
example.com/5/**5/percentage**/transformation
```

Between third and fourth level:
```
example.com/**5/5/percentage/transformation**
example.com/5/5/percentage/**5/5/percentage/transformation**/from-decimal
```

I've tried to debug it myself about like 3-4 hours or more. But I do not understand quite the internals of Backdrop so I have not find anything.

I see that your function `_mlink_alias_token_load_all_parents` is similar to the function `_menu_token_link_load_all_parents`  but instead of titles it takes the path alias.

`_mlink_alias_token_load_all_parents` calls `backdrop_get_path_alias` and I suspect somewhere here is the problem.

**Comment by paucku** [comment]
I finally cucceded by changing the **Default URL alias pattern** to `[node:book:parent:url:relative]/[node:book:title]`

This way the current path is combined by the current title in the end and before that the URL path alias of the parent element. But the parent element also has its parent element in its URL path alias... And thus recursively reaches the root element of the book outline. Now I have _consistency_ between the hierarchy of the book outline and the URLs.

@argiepiano, thank you very much. Although I most probably will not use the example module that you gave me, you helped me a lot to understand more the internals of Backdrop CMS. At least now I know how to create a simple module which provides a token :) For now I am site buiding with Backdrop CMS but I am planning to go deeper and to learn module developing and also to start creating simple tutorials ablut Backdorp CMS – something which is missing a lot.

I am still keeping this open so I can report the next week if this solution is the real sollution or there will be some problems.

**Comment by argiepiano** [comment]
OK, I finally understand what you meant by duplication. Yes, since the parent alias already had its own parent's alias, there will be duplication. Glad to see you figure out a way to make it work, and that the module was somewhat helpful. I will be removing that module, since it was just a proof of concept.

**Comment by paucku** [comment]
I close the issue because the problem was resolved.
