### ISSUE TITLE
Horizontal scrollbar appears in Seven (in Chrome)

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#670]
I'm using Chrome, Version 40.0.2214.93 (64-bit)
my browser size is 1024x768

For reference, I'm on this page:
http://backdrop.dev/admin/config/development/configuration/full/export

**Comment by quicksketch** [comment]
It looks like this happens when the active primary tab is the right-most tab ("Full Import/Export" in your example). This is because there is a hidden span:
```
<span class="element-invisible">(active tab)</span>
```

The "element-invisible" class sets a height of 1px but not a width, so the text "(active tab)" runs off the right-side of the window. To solve this, we can add a width of 1px to `.element-invisible` in system.css.

Long-term, I'd like to get rid of these invisible elements. We could probably replace them with `aria-` attributes and maintain accessibility.

Anyone up for filing a PR, this is a simple CSS fix, so marking novice.

**Comment by klonos** [comment]
I confirm this with Chrome. It doesn't happen with firefox though.

When the page width is shrunk to the point when tabs wrap (#671), the horizontal bar goes away:

![chrome-horizontal_bar_in_seven](https://cloud.githubusercontent.com/assets/2423362/5990678/e347f75a-aa10-11e4-9362-3577d3c0cad6.gif)

...not very helpful, I know but I thought I'd mention it.

**Comment by docwilmot** [comment]
Ugh the tabs! The ugly tabs!

**Comment by Bojhan** [comment]
As far as I know you can't really replace all instances of element invisible with aria tags. But this depends on how far you want to go with supporting ordinary screen readers.

**Comment by quicksketch** [comment]
> As far as I know you can't really replace all instances of element invisible with aria tags.

That's probably true. I wonder about this particular case. Surely there's some way to indicate an "active" item to screenreaders.

In any case, we already have a solution that would work here, just set a width on element-invisible elements.

@klonos yeah we have a larger issue with tabs having a respectable appearance on smaller screens.

**Comment by serundeputy** [comment]
travis testing: https://github.com/backdrop/backdrop/pull/723

**Comment by quicksketch** [comment]
Excellent, thanks again @serundeputy! Merged https://github.com/backdrop/backdrop/pull/723.

**Comment by serundeputy** [comment]
https://github.com/backdrop/backdrop/pull/723
this is merged; so should we close this?

**Comment by serundeputy** [comment]
doh!

**Comment by quicksketch** [comment]
Thanks, it's already closed, but I did forget to mark its milestone. Fixed that now! :smile:
