### ISSUE TITLE
cache_clear_all(NULL, $bin) doesn't clear expired items.

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#674]
This is inconsistent with previous method, at least should be an API change.

```
function cache_clear_all($cid = NULL, $bin = NULL, $wildcard = FALSE) {
  // Default value cache flush.
  if (!isset($cid) && !isset($bin)) { 
    if (module_exists('layout')) {
      cache('layout_path')->flush();
    }
    cache('page')->flush();
    return;
  }

  if (!$wildcard) {
    cache($bin)->delete($cid); <----clears that $bin, condition $cid. Doesnt call GarbageCollection()
  }
  else { 
    if ($cid === '*') {
      cache($bin)->flush();
    }
    else {
      cache($bin)->deletePrefix($cid);
    }
  }
}
```

D8 had an expire() method. Does BD propose calling GarbageCollection() directly?

**Comment by quicksketch** [comment]
> D8 had an expire() method. Does BD propose calling GarbageCollection() directly?

Yes, garbageCollection() should be called if you want to remove expired options. I think we ended up removing expire() (or a similarly named function) because of https://www.drupal.org/node/1944646.

Let's fix this inconsistency as a bug. The entire point of keeping `cache_clear_all()` is for compatibility. If you're writing new code, you'd probably be better off with the less-magical direct calls to the methods.

That said, wow this function has really screwed-up functionality. :stuck_out_tongue_closed_eyes: 

I'm not sure that a non-wildcard, specific $cid would mean a garbage collection. It looks to me like it should be deleting that entry. Key code from Drupal 7 is at https://api.drupal.org/api/drupal/includes!cache.inc/function/DrupalDatabaseCache%3A%3Aclear/7

```php
function clear($cid = NULL, $wildcard = FALSE) {
  global $user;

  if (empty($cid)) {
    if (variable_get('cache_lifetime', 0)) {
      // We store the time in the current user's session. We then simulate
      // that the cache was flushed for this user by not returning cached
      // data that was cached before the timestamp.
      $_SESSION['cache_expiration'][$this->bin] = REQUEST_TIME;

      $cache_flush = variable_get('cache_flush_' . $this->bin, 0);
      if ($cache_flush == 0) {
        // This is the first request to clear the cache, start a timer.
        variable_set('cache_flush_' . $this->bin, REQUEST_TIME);
      }
      elseif (REQUEST_TIME > ($cache_flush + variable_get('cache_lifetime', 0))) {
        // Clear the cache for everyone, cache_lifetime seconds have
        // passed since the first request to clear the cache.
        db_delete($this->bin)->condition('expire', CACHE_PERMANENT, '<>')->condition('expire', REQUEST_TIME, '<')->execute();
        variable_set('cache_flush_' . $this->bin, 0);
      }
    }
    else {
      // No minimum cache lifetime, flush all temporary cache entries now.
      db_delete($this->bin)->condition('expire', CACHE_PERMANENT, '<>')->condition('expire', REQUEST_TIME, '<')->execute();
    }
  }
  else {
    if ($wildcard) {
      if ($cid == '*') {
        // Check if $this->bin is a cache table before truncating. Other
        // cache_clear_all() operations throw a PDO error in this situation,
        // so we don't need to verify them first. This ensures that non-cache
        // tables cannot be truncated accidentally.
        if ($this->isValidBin()) {
          db_truncate($this->bin)->execute();
        }
        else {
          throw new Exception(t('Invalid or missing cache bin specified: %bin', array('%bin' => $this->bin)));
        }
      }
      else {
        db_delete($this->bin)->condition('cid', db_like($cid) . '%', 'LIKE')->execute();
      }
    }
    elseif (is_array($cid)) {
      // Delete in chunks when a large array is passed.
      do {
        db_delete($this->bin)->condition('cid', array_splice($cid, 0, 1000), 'IN')->execute();
      } while (count($cid));
    }
    else {
      db_delete($this->bin)->condition('cid', $cid)->execute();
    }
  }
}
```

It looks to me like the very last elseif would be called if `$wildcard` is `FALSE` and `$cid` is not `*`:

```php
    elseif (is_array($cid)) {
      // Delete in chunks when a large array is passed.
      do {
        db_delete($this->bin)->condition('cid', array_splice($cid, 0, 1000), 'IN')->execute();
      } while (count($cid));
    }
    else {
      db_delete($this->bin)->condition('cid', $cid)->execute();
    }
```

So that seems to map adequately to our condition:

```php
  if (!$wildcard) {
    cache($bin)->delete($cid);
  }
```

**Comment by quicksketch** [comment]
Oh! I get it now. You're talking about when `NULL` is passed in as `$cid`. Of course.

You're right.

So we need to add an additional IF statement:

```
  if (!$wildcard) {
    if (is_null($cid)) {
      cache($bin)->garbageCollection();
    }
    else {
      cache($bin)->delete($cid);
    }
  }
```

**Comment by docwilmot** [comment]
Thats it, sorry I wasnt clear.
But that function with all its permutations (NULL there * here, this TRUE, that FALSE) is very 'uncomfortable'. 
As part of a change record, we should document a more ideal set of methods to do all of this.
eg use ->flush(), ->delete() etc directly. And probably add an ->expire() since garbageCollection() is a bit unintuitive.
What do you think?

**Comment by quicksketch** [comment]
Thanks @docwilmot! Merged in https://github.com/backdrop/backdrop/issues/783.

> As part of a change record, we should document a more ideal set of methods to do all of this.
eg use ->flush(), ->delete() etc directly. And probably add an ->expire() since garbageCollection() is a bit unintuitive.

Let's reconsider expire(), but we can do that in a separate issue. Do we still need a change record at all now that compatibility has been restored?

**Comment by docwilmot** [comment]
Actually, no not a change record, just a best practice recommendation somewhere that there are  alternatives to using cache_clear_all() in its more complex forms. But thats another issue, and not urgent.
