### ISSUE TITLE
[DX] Restore a config-friendly version of system_settings_form()

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#675]
We've deprecated system_settings_form in favor of adding submit buttons and submit handlers to each settings form so that we can define where the config values get saved. 

I wonder if developers are going to miss the convenience of using `system_settings_form` or if having the magic removed is a worth the extra typing.

Opening a new issue here for developer feedback.

---

PR by @sentaidigital: https://github.com/backdrop/backdrop/pull/1601

**Comment by quicksketch** [comment]
Maybe we should just continue the discussion at https://github.com/backdrop/backdrop-issues/issues/397? That issue contains a number of ideas on possible replacements, but as you'll read, making a replacement is difficult when one form can save into multiple config files.

**Comment by quicksketch** [comment]
> I wonder if developers are going to miss the convenience of using ssystem_settings_form or if having the magic removed is a worth the extra typing.

Coming here again from https://github.com/backdrop/backdrop-issues/issues/1364, which suggested that we have a common function for setting the "The configuration options have been saved." message.

Replacing `system_settings_form()` as it existed in D7 is difficult because it was created in the *form definition*. What if we created a useful function that was called from the *form submit* handler instead? Then we wouldn't need to worry about the form definition getting mucked up with information about where saving should happen.

Example:

```php
/**
 * The form callback function.
 */
function my_module_settings_form() {
  $form['element1'] = array(
    //...
  );
  $form['element2'] = array(
    //...
  );
  $form['actions']['#type'] = 'actions';
  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save settings'),
  );
}

/**
 * The form submit callback.
 */
function my_module_settings_form_submit($form, &$form_state) {
  $data = array(
    'value1' = (bool) $form_state['values']['element1'],
    'value2' = (int) $form_state['values']['element2'],
  );
  config_save_settings('my_module.settings', $data);
}
``` 

This makes it so that this new function (`config_save_settings()` or whatever), would do the following:

```php
function config_save_settings($config_name, $config_data, $message = TRUE) {
  config_set($config_name, $config_data);
  if ($message) {
    backdrop_add_message(t('The configuration options have been saved.'));
  }
}
```

---

Well, after writing that all up. I'm not sure it saves us much effort at all and seems a needless abstraction. Any better ideas welcome.

**Comment by docwilmot** [comment]
> Well, after writing that all up. I'm not sure it saves us much effort at all and seems a needless abstraction. Any better ideas welcome.

:smile: 

Sadly, I was thinking that same thought until I got to that line.

How about
```
/**
 * The form callback function.
 */
function my_module_settings_form() {
  $form['element1'] = array(
    //...
  );
  $form['element2'] = array(
    //...
  );

  return config_save_settings('my_module.settings', $form);
}
```

With the clear statement in the docs that this **only** saves to the config in the first parameter. It would satisfy the most common case, which is saving all your settings in your own config. If you want to save to multiple configs, use a submit handler.

**Comment by jlfranklin** [comment]
Quoting myself from #397:

I know I'd miss it. It's not so much that we'll have to write a submit handler, it's that we'll be constantly writing the same commit handler over and over.

The common form is a single `mymodule.settings` bucket, and I think `system_settings_form()` should support that. I also like the more complicated `$form['my_setting']['#config'] = 'mymodule.special';` to handle the uncommon case.

I suggest taking it a step further and let the `#config` setting propagate down to sub-elements, so if you set:

```php
<?php
$form['grouping'] = array(
    '#type' => 'fieldset',
    '#config' => 'mymodule.special',
);
```

... any settings fields in the grouping fieldset would also be saved to `mymodule.special`. I think the common case for multiple config buckets will be (should be!) to group them together by bucket on the form itself, anyway, so allowing a form to set the config bucket on a fieldset keeps the form DRY.

Now that I think about it, adding `$form['#config'] = 'mymodule.settings';` could cover the entire form in the most common case, and would be a degenerate case of adding it to a fieldset. Then, `system_config_form()` doesn't even need a new parameter, just more smarts.

Without objection, I'll take a swing at this solution.

**Comment by jenlampton** [comment]
I'm not sure either of these two latest recommendations solve the problems that keeping something like system_settings_form() would present in the world of config. But, I also miss having it!  I would love to see some options, and we can iterate until all the problems are addressed :)

**Comment by jlfranklin** [comment]
> This is a non-issue in Drupal/Backdrop because the fieldset is dropped and only a flattened array is returned in $form_state['values'] unless tree is specifically set to TRUE and developers who are doing that should understand they'll need to write their own submit handler.

The `user_settings_email()` form has most of its elements saved in `user.mail`, but a couple are in `system.core`.  No part of the form uses `#tree`.  The `#config` settings at the top of the form specifies `user.mail`, but a couple items override it with `system.core`.  

Please check out PR backdrop/backdrop#1601 as an example of how it would work, not a final patch.  Here, the tests fail because the form element is called `user_mail_status_canceled_subject`, but the config item is called `status_canceled_subject`.  A way to handle config object/form element name mismatches and a way to handle settings when `#tree` is set to `TRUE` still need to be done.

**Comment by jenlampton** [comment]
I was referring to fieldsets and nested data, not where it's saved. That's a whole other can of worms!

**Comment by jenlampton** [comment]
> A way to handle config object/form element name mismatches.

We don't need to worry about that use-case because it was not part of `system_settings_form()` to start with.  It used the form element key as the variable name, we can do the same. If the config key is different, the developer will need to write their own submit handler - just like in Drupal.

**Comment by jenlampton** [comment]
> a way to handle settings when #tree is set to TRUE still need to be done.

I'm not sure we should account for this use-case either. We don't need to do more than system_settings_form() did.

**Comment by jlfranklin** [comment]
Well, that makes this _a lot_ easier.  :)

**Comment by jlfranklin** [comment]
Given the simpler scope, what do you think of it?  Should I continue to flesh out the patch, update all the admin forms, and write a few tests?

**Comment by jenlampton** [comment]
Yes please :) 

I also wonder if we can't just add a second parameter to `system_settings_form($form, $filename)` for BC purposes. It would be so much easier to port modules if all I had to do was add a config file name. Oh, I see it's already marked as deprecated. How about renaming it to `backdrop_settings_form($form, $filename)`?

**Comment by sentaidigital** [comment]
Actually, the patch above makes it easy to backport modules by adding a single entry, `$form['#config'] = 'mymodule.settings';` in the form array.  Until BD2, the absence of the `#config` entry will trigger a `WATCHDOG_DEPRECATED` warning.

If we're going to revive it, can we un-deprecate `system_settings_form()`?

**Comment by jenlampton** [comment]
> the patch above makes it easy to backport modules by adding a single entry, $form['#config'] = 'mymodule.settings';

even better! :) 👍 

> If we're going to revive it, can we un-deprecate `system_settings_form()`?

I actually don't know how that would work...  @quicksketch ?

**Comment by Gormartsen** [comment]
@sentaidigital tnx! I am looking to have it available!

**Comment by sentaidigital** [comment]
I've added `SystemSettingsFormTest` to test the `system_settings_form()` submit handlers.  `SystemConfigFormCase`, a config form helper class from `user.test` that I leveraged for my own tests, has been promoted to its own file, and included in both the `user.test` and the `form.test` where `SystemSettingsFormTest` lives.

If there is a better, preferred organization for those classes, I have no issue shuffling them around.

**Comment by sentaidigital** [comment]
As discussed above, it _does not_ handle config object/form element name mismatches or when `#tree` is set to `TRUE`.  The `user_settings_email()` form is an example of a config form with name mismatches.  I considered changing it to match form element names to their config object names, but I feel like that would be an API change breaking anything altering that form.

It _does_ support overriding individual elements and their children, which turns out to be really useful in `hook_form_alter`.  A module can insert their own config fields in a `fieldset` or individually, tag them with `'#config' => 'mymodule.settings'`, and not need their own submit handler.

**Comment by jenlampton** [comment]
> considered changing it to match form element names to their config object names, but I feel like that would be an API change breaking anything altering that form.

Form structure is not considered an API change, but it's best only to change it if/when we have a really good reason, due to reasons you stated. I think your decision was the right one :)

**Comment by jenlampton** [comment]
Tagging with 1.6 to get some more eyes on this. The more modules I port, the more I want it, so if others agree then the sooner the better for this one.

**Comment by Graham-72** [comment]
I miss the convenience of the system settings form but at least with the present method it is easy to understand what is happening. Would re-introducing it lead to more complexity for when I am trying to find out why my attempt at a port is not working?

**Comment by jenlampton** [comment]
yes.

**Comment by sentaidigital** [comment]
> Would re-introducing it lead to more complexity for when I am trying to find out why my attempt at a port is not working?

Why?  What complexity is it adding?  `system_settings_form()` doesn't keep you from adding calls to `dpm()` or adding your own validation and submit handlers.  It takes care of the common case of saving an admin page's settings to a settings file.  It is the same as Drupal 7's, smartened up a bit to work with CMI.  

It should make porting modules easier.  You won't accidentally forget to save one field out of a dozen or spell a field differently in the submit handler, two of the most common bugs in current forms.

**Comment by jenlampton** [comment]
> What complexity is it adding?

It's not complexity that's the problem here - it's "magic". 

By using `system_settings_form()` the process of saving the config file (or variables) is hidden from people reading the module code, so those who are new to Backdrop/Drupal don't see or understand how things actually get saved.  For the old pros it's a win since there's less typing! But since we're supposed to value beginners over experts in Backdrop, it's definitely worth some consideration.

**Comment by sentaidigital** [comment]
> It's not complexity that's the problem here - it's "magic".

Wait.  What?!   What does that even mean?  One, it's open source, and less than a hundred lines of patch ([c608fc6](https://github.com/backdrop/backdrop/pull/1601/commits/c608fc6fbda2ffe0124e08ee5b9a4974e5c4e599), specifically), half of which is comments.  Two, it will be documented on api.backdropcms.org.  Three, it performs a common operation, updated for CMI, avoids code bloat, and avoids common mistakes.  It makes writing code easier for beginners who can focus on the Form API part of the form, and faster for experts who just want their code done.

It's no more "magical" than any other part of Form API and no more than it was in Drupal 6.

> [T]hose who are new to Backdrop/Drupal don't see or understand how things actually get saved.

There are plenty of blog posts that describe how to save to config.

> Then when we get to 2.0, we can reevaluate based on how many projects are using it?

If it is marked `Deprecated` it won't be used by ported projects.  If Backdrop isn't going to use it in core, don't bother committing it.  Don't add dead code.

**Comment by jenlampton** [comment]
> Wait. What?! What does that even mean?

I use the term "magic" to mean code that is not intuitive, or can't be seen
and understood easily. There's no "magic" in writing your own submit
handler, and writing all the code to save your own variables manually.
Everything you need to do, you write yourself. The saving is done in the
same file as the setting, and everything is easy to locate. Very
straightforward.

Alternatively, when `system_settings_form()` is used, a submit handler is
added (where you can't see it). It's not the file you are reading, and
there's no indication in the function name what is happening. The saving of
the variables becomes "magic". Think of the experience for the beginner
attempting to debug a problem with the settings saving incorrectly. He'll
study the form, then wonder how anything is saved at all. "Magic!"

> One, it's open source, and less than a hundred lines of patch...

I didn't mean that the patch adds any magic - the patch is great as-is! The
"magic" was already in system_settings_form() and Backdrop's decision not
to replace or update that function back in 1.0 was, in part, to decrease
the "magic" in Backdrop, and make writing code more intuitive to new coders
for Backdrop. ("Intuitive" here means that more can be done without needing
to consult the API docs.)

> It makes writing code easier for beginners who can focus on the Form API
part of the form, and faster for experts who just want their code done.

Beginners will have no idea something like `system_settings_form()` exists,
or that it would help them in this situation. Change this reason to "easier
and faster for those with at least moderate experience" and I'm with you
100%. I miss `system_settings_form()` - which is why I opened this issue. :)

**Comment by docwilmot** [comment]
I for one support this patch. It restores a useful functionality. If you dont want to use it, patch doesnt stop you doing it the long way.

**Comment by quicksketch** [comment]
@sentaidigital @jlfranklin I posted a review to https://github.com/backdrop/backdrop/pull/1601#pullrequestreview-14807617. Just from the before/after results, I have to agree that this seems like very useful functionality. There are lots of items in the review, but the crucial ones are:

- `system_settings_form()` needs to be moved out of `drupal.inc` if it's no longer deprecated.
- Speaking of that function, do you think we should create a new name for this function? It makes me a little uncomfortable that it could accidentally save into the variable table instead of config. I think I may prefer to keep it (and all `variable_*` functions) clearly deprecated and make a new function for this purpose. OTOH, I can see leaving the function name alone would make for an even quicker/simpler porting job from D7. Thoughts?
- A few places we loose strict type casting, i.e. a string `'0'` or `'1'` is saved into the config file instead of a 'true/false` Boolean. Would it be possible to auto-cast checkboxes into Booleans on save?

> A module can insert their own config fields in a fieldset or individually, tag them with `'#config' => 'mymodule.settings'`, and not need their own submit handler.

Could we get the tests to cover this functionality? Right now it tests the entire form and an individual value, but not a fieldset with nested children.

Again, this looks like very useful functionality. The implementation is great as well (and even adds new tests!) Great job all around @sentaidigital on the work thus far.

**Comment by quicksketch** [comment]
> It makes me a little uncomfortable that it could accidentally save into the variable table instead of config.

Upon further review, I'm satisfied that we are logging `WATCHDOG_DEPRECATED` notices if the values are saved into variables instead of config. I do think we might be able to take this a step further though and simply make the function not save into variables if `!empty(settings_get('backdrop_drupal_compatibility'))`. Then if the compatibility layer is turned off, the variables don't save (as would have happened before this PR is applied).

**Comment by jlfranklin** [comment]
> I do think we might be able to take this a step further though and simply make the function not save into variables if !empty(settings_get('backdrop_drupal_compatibility')).

True.  Previously, the site would whitescreen trying to call `system_settings_form()`.  I'll add a warning in `system_settings_form()`, an error message in `system_settings_form_submit()` and abort saving.

**Comment by jlfranklin** [comment]
>    system_settings_form() needs to be moved out of drupal.inc if it's no longer deprecated.

Done.

>    Speaking of that function, do you think we should create a new name for this function? It makes me a little uncomfortable that it could accidentally save into the variable table instead of config. I think I may prefer to keep it (and all variable_* functions) clearly deprecated and make a new function for this purpose. OTOH, I can see leaving the function name alone would make for an even quicker/simpler porting job from D7. Thoughts?

I'm inclined to keep the function name to ease the porting job.  It's not explicitly a `variable_*` function, it's a function in the System module that handles the common parts of many settings forms.

Also, typing `system_settings_form` is  muscle memory for me, and probably a lot of other old Drupal devs.

> Could we get the tests to cover [field/fieldset inserted by `hook_form_alter`] functionality? Right now it tests the entire form and an individual value, but not a fieldset with nested children.

`contact_form_user_admin_settings_alter()` adds `#config` to a fieldset and `dblog_form_system_logging_settings_alter()` does the same for an individual element.  Adding a couple tests of those forms should be easy enough.

**Comment by jlfranklin** [comment]
>    A few places we loose strict type casting, i.e. a string '0' or '1' is saved into the config file instead of a true/false Boolean. Would it be possible to auto-cast checkboxes into Booleans on save?

Originally, I thought that this sounded reasonable and would be easy enough to write, although I (quietly) had concerns about special casing one FAPI element type. I'd be happier with the element code handling the values and leave `system_settings_form_submit()` to be a dumb function that just copies data. 

As I started to work on it, I remembered that `checkbox` elements don't _always_ return a boolean, they return whatever `#return_value` is set to.  By default, `#return_value` is set to (int) 1, but it could be another number, or a string, or really anything.  A quick test shows setting `'#return_value' => TRUE` indeed returns a boolean when checked, but (int) 0 when unchecked.  Setting '`#return_value' => array('foo' => 'bar', 'fred' => 'derf')` returns the array.  I don't think it is appropriate for `system_settings_form_submit()` to override FAPI like that.

In the case of `redirect_settings_form_submit()` from the patch, two of the setting with casts are `checkbox` elements, one is a set of `radios` with options '0' and '1' (strings), and the last (`purge_inactive`) is a 10 element select.

**Comment by jlfranklin** [comment]
> contact_form_user_admin_settings_alter() adds #config to a fieldset and dblog_form_system_logging_settings_alter() does the same for an individual element. Adding a couple tests of those forms should be easy enough.

`dblog_form_system_logging_settings_alter()` adds the same `#config` as the parent form, so it isn't a good test case.  (Raises an interesting question: Is that good practice because it's obvious where the setting will go and won't break if the parent form is rearranged?  Or is it bad because it's redundant?  I'm leaning towards good, myself.)

The `user_admin_settings` form has an override test in it, and there are both type of override tests (single-element and fieldset) in `SystemSettingsFormTest`.

**Comment by jlfranklin** [comment]
All review items are done except casting the values of `checkbox` elements.

**Comment by quicksketch** [comment]
Fair enough on the casting of data types on checkbox elements. I also had the same concerns you mentioned, so I'm glad you came to a solid conclusion there.

**Comment by quicksketch** [comment]
The new PR at https://github.com/backdrop/backdrop/pull/1601 looks great. I think this is ready to go, with the one exception that the docblocks on `system_settings_form()` and `system_settings_form_submit()` need to be updated to reflect their current capabilities. They still say that they shouldn't be used (even though the `@deprecated` line was removed).

**Comment by jlfranklin** [comment]
Docblocks updated and pushed.

**Comment by jenlampton** [comment]
Looking great, thanks for the quick turn-around @jlfranklin ! :)

**Comment by quicksketch** [comment]
Super! I have merged https://github.com/backdrop/backdrop/pull/1601 into 1.x for 1.6.0. Thanks for championing this and the great work @jlfranklin!

**Comment by jenlampton** [comment]
This is an issue that will require docs updates!  We'll need to update existing change records about system_settings_form() and update module porting instructions.

**Comment by klonos** [comment]
> This is an issue that will require docs updates!

Fancy the new issue tag then? 😉
