### ISSUE TITLE
Follow-up: Function _layout_get_all_info() (layout.module:1616) called deprecated function layout_layout_info()

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#6758]
## Description of the bug

This is a follow-up to https://github.com/backdrop/backdrop-issues/issues/6628, where hook_layout_info() has been renamed.

There's an oversight in function _layout_get_all_info() 

```php
  if (!isset($all_info[$data_type])) {
    _layout_include_files();
    $all_info[$data_type] = $init;

    foreach (module_implements($data_type . '_info') as $module) {
      $function = $module . '_' . $data_type . '_info';// $function is layout_layout_info
      $data = $function();
      $module_path = backdrop_get_path('module', $module);
...
```

## Steps To Reproduce

1. Make sure, you're on the latest dev version
2. Flush caches
3. Go to dblog to check

## Actual behavior

```
The function _layout_get_all_info() (layout.module:1616) called deprecated function layout_layout_info(). It will be removed in the next major release of Backdrop.
```

## Expected behavior

Core itself shouldn't call deprecated code - deprecated by itself. :wink: 

Didn't dig any deeper, but I'm confident, @docwilmot will find a quick solution.

## Additional information

- Backdrop CMS version: latest dev
- This change has been merged only a few days ago
- Link to code https://github.com/backdrop/backdrop/blob/1.x/core/modules/layout/layout.module#L1616

**Comment by quicksketch** [comment]
Let's put this into the bug-fix milestone since it's effectively a regression caused by 1.29.2.

**Comment by indigoxela** [comment]
> it's effectively a regression caused by 1.29.2.

It's not released yet, as the change from #6628 will be part of 1.30.0, but didn't go into 1.29.

**Comment by indigoxela** [comment]
Seems like nobody feels responsible here, yet... @docwilmot is there a chance, that you find the time to get this ready for 1.30?

Or does anyone else want to take over?

**Comment by argiepiano** [comment]
I vote for reverting the renaming done in #6628, and postponing it for the future. Renaming a hook only concerns developers, probably not an 80% use case. And the renaming causes tricky problems - not to mention we haven't checked (AFAIK) how it would affect contrib.

**Comment by yorkshire-pudding** [comment]
I had a look at this but the only idea I had was an exception in this function for that hook that does it differently; I doubt such a solution would be acceptable.

In contrib land there looks to be a few instances:
https://github.com/search?q=org%3Abackdrop-contrib+_layout_info&type=code

**Comment by docwilmot** [comment]
We could just remove the `watchdog_deprecated_function('layout', __FUNCTION__)` line from `layout_layout_info()`, no?

**Comment by quicksketch** [comment]
There's another small issue here in that `layout_get_layout_template_info()` loads both `hook_layout_template_info()` and `hook_layout_info()`. Since Layout module implements both, we load the template information twice for no reason.

```
    $info = _layout_get_all_info('layout_template', $init);
    // Account for implementations of the deprecated hook_layout_info().
    $info = _layout_get_all_info('layout', $info);
```

But overall it doesn't have a bad effect since they both return the same data, but it's unnecessary that we're generating that data twice. I would find it acceptable to simply delete all of `layout_layout_info()` (a hook implementation), since it should never have been called directly anyway. `layout_get_layout_info()` provides the backwards-compatible API here.

**Comment by indigoxela** [comment]
> I would find it acceptable to simply delete all of layout_layout_info() (a hook implementation), since it should never have been called directly anyway.

Hm. That *might* work... Are there possible side effects?

I have to admit - I agree with @argiepiano, that this renaming is just a developer thing and doesn't provide value beyond that. If we'd really want to fix all weirdly named hooks, I'd personally start with "hook_menu" :laughing: (Noooo, only joking!)

**Comment by laryn** [comment]
Personally I'm in favor of cleaning up and making code more understandable and consistent, of course providing it can be done in a backwards-compatible way.

**Comment by argiepiano** [comment]
> There's another small issue here in that layout_get_layout_template_info() loads both hook_layout_template_info() and hook_layout_info().

My understanding is that this was kept here because of all potential `hook_layout_info()` implementations in contrib. If we remove that hook invocation, we are effectively rendering all those implementations useless. All contrib maintainers (and authors of custom modules) would have to go back and rename all those hooks in their code.

This, again, reminds me of those "develop-y" decisions that seem like a good idea at first, but end up producing more work for developers. Vaguely reminds me of a similar discussion with the proposed renaming of `module_load_include()` !

**Comment by quicksketch** [comment]
Sorry, I wasn't clear before:

- Calling `hook_layout_info()` for backwards-compatibility: good.
- Leaving the old `layout_layout_info()` implementation (in addition to the new `layout_layout_template_info()`): bad

If a contrib module were to update from the old to new hook, it wouldn't leave the old one in place too, and I don't think core should either. We should just remove `layout_layout_info()` and let `layout_layout_template_info()` take its place.

**Comment by docwilmot** [comment]
I think this makes sense. No contrib calls `layout_layout_info()` directly as far as I can tell from GH search.

**Comment by indigoxela** [comment]
Here we go, a PR is available for testing and review: https://github.com/backdrop/backdrop/pull/4951

**Comment by herbdool** [comment]
Oh, I was about to comment on a possible solution but I'll look at your PR instead. I'm sure it's better than my idea.

**Comment by herbdool** [comment]
The code looks good and I tested the sandbox. Though we need someone to test the old hook.

**Comment by indigoxela** [comment]
> Oh, I was about to comment on a possible solution ... I'm sure it's better than my idea.

What was your idea? Mind to share?

> Though we need someone to test the old hook.

Yes. Here's a simple module, that triggers the problem:

<details>
<summary>foobar.module</summary>

```php
<?php

function foobar_layout_info() {
  $layouts['my_layout'] = array(
    'title' => t('A custom layout'),
    'path' => 'layouts',
    'regions' => array(
      'header' => t('Header'),
      'content' => t('Content'),
      'sidebar' => t('Sidebar'),
      'footer' => t('Footer'),
    ),
  );
  return $layouts;
}
```

</details>

Fun fact: as the code currently is (with watchdog_deprecated_function() only inside layout_layout_info()), other modules would never have triggered a deprecated message - only the Layout module itself. :stuck_out_tongue_winking_eye: 

I updated my PR to not use watchdog_deprecated_function(), but use watchdog() instead to avoid that totally misleading message.

Before my latest commit: :-1: 

```
The function layout_get_layout_template_info() (layout.module:1707) called deprecated function foobar_layout_info(). It will be removed in the next major release of Backdrop.
```

With latest commit:

```
Module foobar implements deprecated hook_layout_info() in foobar_layout_info.
```

Obviously watchdog_deprecated_function() was only supposed to handle functions, but is rather not helpful for renamed hooks. :wink:

**Comment by quicksketch** [comment]
I tested the PR and hacked node module to include `node_layout_template_info()`, used a layout provided, then switched it to `node_layout_info()`, which continued to work and threw the expected watchdog deprecated notice:

![image](https://github.com/user-attachments/assets/1838d420-bbfa-4b8a-a7ae-594e0e68fd33)

So all works as expected.

Thanks @indigoxela this is a much better solution, where now implementations of the hook throw the deprecated notice rather than only `layout_layout_info()` throwing the deprecated notice, which as you noted, didn't make any sense.

**Comment by quicksketch** [comment]
Thank you @indigoxela, I have merged https://github.com/backdrop/backdrop/pull/4951 into 1.x for 1.30.0.

Thank you @herbdool, @docwilmot, @argiepiano, @laryn, and @yorkshire-pudding for the input and review!
