### ISSUE TITLE
Self-update detection fails on shared hosting configuration

### ISSUE THREAD

**Issue by aydun** [backdrop/backdrop-issues#6759]
## Description of the bug

On some shared hosting (specifically civihosting.com), the file ownership and permissions do allow updates but the self-update detection does not recognise this leading to a screen requiring FTP details.

See https://github.com/backdrop/backdrop-issues/issues/6742 and https://backdrop.zulipchat.com/#narrow/channel/218635-Backdrop/topic/Core.20update.20-.20needs.20ftp.3F

## Steps To Reproduce

CiviHosting configuration is:
```
  drwxr-x--- root mygroup (home dir)
    drwxr-xr-t root mygroup www
      drwxrwxr-x root mygroup www
      drwxrwxr-x root mygroup subdomain1
```
The directories under `$HOME/www` are managed as part of the subdomain management via the control panel.

The default configuration directory is `$HOME/www/www` owned by root, writable by the webuser group.

The self-updater examines the ownership of the configuration directory and therefore fails in this configuration, resulting in a FTP screen.

## Actual behavior

FTP cred screen

## Expected behavior

Installation should continue.

## Additional information

Add any other information that could help, such as:
- Backdrop CMS version: 1.29.1

**Comment by quicksketch** [comment]
Hi @aydun, welcome to the Backdrop community! Thank you for filing this issue and the associated PR! The code looks good to me; solid conceptual improvement. `settings.php` is indeed much more likely to match the file ownership because it's typically written by the web-server during installation of Backdrop.

In the Drupal-sphere (where this code originated), the `conf_path()` was usually a nested directory (like `sites/default`), but in Backdrop it's usually the root directory. I wouldn't have expected a difference in ownership, but I think your example proves otherwise!

This could use a second set of eyes to verify, but this seems ready to me (minor code-comment issue aside, I left a note on the PR).

**Comment by aydun** [comment]
Thanks @quicksketch

**Comment by quicksketch** [comment]
@izmeez Are you also on civihosting.com?

The permissions check is not comprehensive. It's only checking the permissions of a single directory (or now a file, after the current PR https://github.com/backdrop/backdrop/pull/4909). On most sites, the ownership of all PHP files is the same, but a single file being the wrong permission may prevent an automatic update from being successful. Do you have permission to a terminal/console/ssh on your host? You might be able to fix the problem by following the [documentation on setting looser permissions](https://docs.backdropcms.org/documentation/looser-permissions).

**Comment by aydun** [comment]
Thanks for merging @quicksketch
