### ISSUE TITLE
Remove min/max values for 'Authored on' date field

### ISSUE THREAD

**Issue by NormPlum** [backdrop/backdrop-issues#6763]
## Description of the need

A node's 'Authored on' date field has min and max values of `1970-01-01` and `2037-12-31` respectively.

While not common, one way of using this field might be to store the date the book, movie, etc. the node represents was released. These dates can easily be pre-1970, which causes a problem with validation.

I'm assuming the max value of 2037 has to do with 32-bit support, so I'm not sure if that can also be removed or is a requirement to avoid breakage, but certainly dates pre-1970 should be possible.

![image](https://github.com/user-attachments/assets/da449f6c-f89e-4594-99a3-021fc22266a0)

## Proposed solution

No min/max values for the 'Authored on' date field.

## Alternatives that have been considered

One could always override the form to manually remove this requirement (it seems to be what I'll need to do), but if there's no real reason to have these in place I think better to support a wider range of dates without needing to override things.

## Additional information

It looks like this is where the change was made: https://github.com/backdrop/backdrop/pull/2852/files#diff-33587abdd49adfe3e7ed6069161cf441b7fde91b1642d5596a512a29110b3f89
It doesn't look like the previous solution had min/max values, so wondering why they were added here...

**Comment by argiepiano** [comment]
A important issue with this is that `created` is stored as a [32-bit Unix timestamp](https://en.wikipedia.org/wiki/Unix_time). That can't be change because of backward compatibility. Unix timestamp has a set limitation of times that can be represented with it. 

The node property `created` is supposed the actual time the node was created. In fact there is no UI that allows you to change it, and it's [prepopulated](https://github.com/backdrop/backdrop/blob/407e21d7979fae86f560ec2bfb9b0e4e62d2ccdf/core/modules/node/node.entity.inc#L177) with REQUEST_TIME. It's not a good idea to use it for other purposes.  Your potential scenario of storing the date a book or movie were published can easily be accomplished with an added Date field.

**Comment by argiepiano** [comment]
I stand corrected, then. 👍🏽

**Comment by bugfolder** [comment]
By golly, yes. The db column is `int(11)`, so negative values are acceptable in the db, and if I plug in a created value of -283996800, it shows up in Backdrop with a pre-1970 "Authored on" date (of course, the UI won't allow you to save that value).

**Comment by stpaultim** [comment]
I can't think of an obvious reason for this limitation. I assume it might be a carry over from early Drupal. Is it possible that this was impossible at one point in earlier versions of PHP?

Yes, it's a bit of an edge case to use this field in this way. But, I don't necessarily see a reason to prevent it. It would seem, that removing this restriction would be backward compatible - because we are simply removing a restriction. It should not prevent anything that was possible before, but would allow something that was previously impossible without custom code.

But, I could be missing something. 

@NormPlum any interest in submitting a PR that removes this restriction. I suggest this, because an issue with a PR is more likely to get attention and movement.

**Comment by stpaultim** [comment]
I can confirm that with this PR, I am able to set the date of posts to pre 1971. 

It's a very simple PR that does what is expected. I'm not sure if there are undiscovered reasons why this is a bad idea. But, I think that will come up in the code review stage. So, I'm going to mark this Works for me.

**Comment by avpaderno** [comment]
I agree with @argiepiano that, for the described purpose, it is better to create a new field. 

There are probably modules that would take the `created` value as the Unix timestamp when the node was created, which is the description given in `node_schema()`. Reusing an entity field/property for a different purpose is probably a bad idea.

**Comment by argiepiano** [comment]
Fatal error if you enter a date before 1900. Removing `min` is not a good idea. You could possibly make it 1901, but not remove it.

<img width="834" alt="Screen Shot 2024-11-24 at 7 16 46 AM" src="https://github.com/user-attachments/assets/ab7d370e-d4c2-4899-9f78-d27ef8501c6e">

**Comment by docwilmot** [comment]
Agreed to "works as designed", but just curious, is the max date fixed or is it calculated to a max timespan in the future. In other words, will we have a problem, come `2038-01-01`?

**Comment by argiepiano** [comment]
> In other words, will we have a problem, come 2038-01-01?

https://github.com/backdrop/backdrop-issues/issues/6307

**Comment by stpaultim** [comment]
> In other words, will we have a problem, come 2038-01-01?
I love the optimism here....

:-)
