### ISSUE TITLE
[DX] Language node setting "node_type_language" should just be "language"

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#677]
While working on the port of Pathauto, I found that the language settings within the node type object is still prefixed with "node_type_" as if it were in the variables table. All other properties in the node type have had that prefix removed. We must have missed this in our conversion.

Example:

```
$node_type = node_type_get_type('article');
if ($node_type->settings['node_type_language'] === TRANSLATION_ENABLED) {
```

It should be:

```
$node_type = node_type_get_type('article');
if ($node_type->settings['language'] === TRANSLATION_ENABLED) {
```

I'm not sure what to do about timeline on this issue. It's clearly an oversight, so fixing it is a "bug". However, having the crufty prefix doesn't actually hurt the functionality of the code. It works fine, it's just cruft from Drupal 7. If we want to fix this in 1.x, we should do it immediately before more contrib modules stabilize. Otherwise, we should wait until 2.x.

**Comment by jenlampton** [comment]
I vote that we fix it immediately since it's very likely that nothing other than pathauto is using this right now, and there are probably very few sites that have pathauto since it *just* got to a usable state.  We need to do this soon, or it will need to wait till 2.x.  If we can't get a PR in for this in 1.0.2 then let's hold off.

**Comment by quicksketch** [comment]
In that case, I've filed a PR at https://github.com/backdrop/backdrop/pull/730.
