### ISSUE TITLE
Display "Conditions" admin preview in admin UI for "Existing content" block

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#6780]
Currently, the "Existing content" does not display the Conditions preview in the admin UI. It'd be nice if it did, especially given that it's pretty common to add conditions when displaying existing content, for example, on the Home Page layout. 

Compare, for example, with the Primary navigation and other menu blocks.

Existing content blocks (with a Role conditions - not displayed):
<img width="1155" alt="Screen Shot 2024-12-15 at 12 09 13 PM" src="https://github.com/user-attachments/assets/6d011e6e-6afc-4fcd-b5c2-17f5ca4119fc" />

Primary navigation block (condition preview displayed):
<img width="1185" alt="Screen Shot 2024-12-15 at 12 09 28 PM" src="https://github.com/user-attachments/assets/e35d7926-6005-47f8-9d13-19bc29b05a6f" />

**Comment by argiepiano** [comment]
Simple, two line, PR provided. The capability already exists to do this. 

<img width="1140" alt="Screen Shot 2024-12-15 at 12 17 45 PM" src="https://github.com/user-attachments/assets/75bb6006-a0f3-49ef-b068-70fdf1c4baaf" />

**Comment by stpaultim** [comment]
I confirmed that the problem exists as described and that the provided PR seems to fix it!

WFM

**Comment by stpaultim** [comment]
Given that this has a PR in a near-ready state, I can go ahead and add this to the 1.29.3 milestone.
https://docs.backdropcms.org/documentation/adding-milestones-to-issues

**Comment by herbdool** [comment]
Code looks good to me.

**Comment by quicksketch** [comment]
This looks good but I think we have the same problem on all the blocks provided by Dashboard module:

- DashboardCreateBlock
- DashboardMenuBlock
- DashboardNewsBlock
- DashboardContentTypesBlock
- DashboardOverviewContentBlock
- DashboardOverviewUserBlock
- DashboardTaxonomyBlock
- DashboardUpdateBlock
- DashboardWelcomeBlock

Maybe that should be a separate issue since the existing content block might see a lot more end-user application than the dashboard blocks.

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/4933 into 1.x and 1.29.x. Thank you @argiepiano!
