### ISSUE TITLE
PHP Notice: Undefined index: alt in theme_icon() 

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#6784]
## Description of the bug

There is a small bug in icon API that is causing PHP warnings on my site. 
```
Notice: Undefined index: alt in theme_icon() (line 327 of /var/www/html/www/core/includes/icon.inc).
```

The problem is that the code is using `if ($variables['alt']) {` instead of `if (isset($variables['alt'])) {` accidentally making the `alt` attribute required. 

The documentation states that this value can be omitted:
`If not specified, the icon will automatically be assigned the aria-hidden="true" attribute.`

But the code required that it's specified, but `FALSE`. 

## Steps To Reproduce

To reproduce the behavior:
1. Install the [1.x-2.1.1 release of the On The Web module](https://github.com/backdrop-contrib/on_the_web/releases/tag/1.x-2.1.1)
2. Navigate to the settings page at `/admin/config/services/on_the_web`
3. (veryfiy that the "Icon type" is set to "SVG icons" under "Display options")

## Actual behavior

`alt` attribute required
```
Notice: Undefined index: alt in theme_icon() (line 327 of /var/www/html/www/core/includes/icon.inc).
```

## Expected behavior

`alt` attribute should be optional

## Additional information

Add any other information that could help, such as:
- Backdrop CMS version: 1.29.2 
- PHP version 7.4

**Comment by quicksketch** [comment]
Thanks @jenlampton, you're right that `$variables['alt']` is not always defined. Rather than changing the conditional, we should ensure it's always defined. `hook_theme()` is supposed to do this for us but when `'icon'` is declared in `backdrop_common_theme()`, it is missing the `alt` key. That's why there's no default. I filed a replacement PR at https://github.com/backdrop/backdrop/pull/4945 that should fix the problem by specifying that default. Could you verify that solves the problem?

I think this happened because early versions of the Icon API had `alt` under `attributes`, but later it was pulled out because it doesn't act like a normal attribute, since it actually renders as an internal `<title>` tag.

**Comment by quicksketch** [comment]
Seems this is the same issue as https://github.com/backdrop/backdrop-issues/issues/6760, which has the same fix as my pull request at https://github.com/backdrop/backdrop/pull/4945.
