### ISSUE TITLE
Shouldn't "install_version" rather be a state than config?

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#6790]
## Question

As part of #4782 a new config item `install_version` has been added, and set for all sites in system_update_1099(). OK, will be set when updating to 1.30.

Why a **config** item?
Config can be exported and imported to other sites, which means, that would change their "install_version" to the one the config came from. Doesn't that make the info useless for telemetry?

I really wonder, why this isn't a `state` instead, which is specific to a site and resides in the database, not config.

@stpaultim I didn't follow the discussion in that issue closely, so I wonder why that decision was made.

**Comment by herbdool** [comment]
While it's true that config can be imported to other sites, it's not a common use case, is it? Though I see your point; it's a bit awkward. I think state is not a good place for it since it's environment specific.

**Comment by stpaultim** [comment]
@indigoxela - I never considered state vs config myself and don't recall it coming up as an idea. My work on this PR was pushing the boundaries of my experience and I relied quite a bit on @quicksketch for advice. I'm not sure if he considered that. Will let him reply. 

I have no opinion on this as I'm not familiar enough with related situations in core.

**Comment by avpaderno** [comment]
I always thought to configuration values as values that I would import from a development environment to a staging environment, or from staging to production.

For example, the last time cron hooks have been invoked is not a value I would import from an environment to another one. `install_version` seems a value I would use as configuration value, as I would export its value from a staging environment to production.

**Comment by quicksketch** [comment]
I thought about whether `install_version` should be config or state. It's definitely a little weird that `install_time` is state, but `install_profile` -- and now `install_version` -- are config. State and config are both sort of equal in this particular situation, since this value never needs to be updated once set.

And to clarify, `state` can be useful to separate values between _environments_. Things like `cron_last` and `maintenance_mode` make a lot of sense as state because different environments (dev/test/live) should have the same config but can have different states that shouldn't be moved between them.

But again, since the `install_version` value never changes, I'm not sure if one is better than the other. I'm open to modifying `install_version` to be moved to state if we can think of a reason why it would be better there.

**Comment by indigoxela** [comment]
> I thought about whether install_version should be config or state. It's definitely a little weird that install_time is state, but install_profile -- and now install_version -- are config

Yeah, that was the "head scratching part" for me. :wink:

I do think, that module configs, for example, are pretty common to import from another site (where things got configured already). But system.core.json may be an uncommon use-case for that.

Many thanks to everyone who provided a quick response. I think, my question's answered. At least, config-vs-state has been considered, so it clearly was no oversight. :wink:
