### ISSUE TITLE
Better link for 'utf8mb4' documentation

### ISSUE THREAD

**Issue by NormPlum** [backdrop/backdrop-issues#6792]
## Description of the need

On the Status page there's a link to the documentation about 'utf8mb4' but it links to the top of the page, not the heading where this info is.

## Proposed solution

Change link from https://docs.backdropcms.org/documentation/database-configuration to https://docs.backdropcms.org/documentation/database-configuration#utf8mb4

## Alternatives that have been considered

The current link works but you have to scroll to find the relevent info.

**Comment by stpaultim** [comment]
This change makes sense to me. The only potential problem I can see would be if the ID link changes on the docs site, would the link still work? I would expect it would and may try to test that theory. 

In the meantime. Can't test this in sandbox site, because `MySQL Database 4-byte UTF-8 support` is already enabled and this link does not show. It only shows if that setting is NOT enabled.

When I spin up a new Backdrop site in DDEV, that setting is NOT enabled and I was able to test that the link appears and works as expected. 

![image](https://github.com/user-attachments/assets/dd397dec-7db0-4096-aa44-01800f2932d2)

The link now goes directly to:

![image](https://github.com/user-attachments/assets/378e5d7f-db98-49f6-88da-d10c86ec4dbf)

Works for me.

**Comment by stpaultim** [comment]
A minor change like this is usually considered a task or even a UX bug and is eligible for a bug fix release. Feature Requests are ONLY eligble for minor releases. Hence, I changed the label to task.

**Comment by avpaderno** [comment]
If the markup is changed from `<h2 id="utf8mb4">` to, for example, `<h2 id="utf8_mb4">`, the link will take to the top of the page.

**Comment by quicksketch** [comment]
Thanks @NormPlum! Merged https://github.com/backdrop/backdrop/pull/4954 into 1.x and 1.29.x. Thanks @stpaultim and @avpaderno for the review!
