### ISSUE TITLE
[UX] Allow text fields and textareas to use the other's widgets.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#684]
It's super frustrating when you want to have a text field (255chars) but the only way to see the entire 255 chars in that field is a really really reeeeally long textfield.  Text areas are a thing. We should be able to use them (and not just for longtext text fields).

in Drupal 7, to use a textarea you need to create a whole new field and migrate all your data into it, but the underlying data is exactly the same. This should not be necesary.

Let's add the textarea widget as an option for text fields (but leave the existing default in place)

edit: related [d.o issue](https://www.drupal.org/node/2479895)

**Comment by quicksketch** [comment]
This problem goes both way I think. You can't use a textfield for a "Long text" and you can't use a textarea for a (short) "Text". Should we try to solve both directions?

**Comment by klonos** [comment]
So, should we use long text/textarea everywhere and limit length or number of lines to 1 when it comes to display?

Googling a bit about it brought a number of questions asked over at Stack Overflow. All seem to resort in using a JS solution. Here's 3 working demos from https://stackoverflow.com/questions/22731394/max-lines-textarea that I've played with:

1) http://jsfiddle.net/5Q4U9/3/

- does NOT limit line length, so typing more characters gets your text outside the text area
- if the line limit is reached, you are NOT allowed to create a new line (hitting enter makes the text red)

2) http://jsfiddle.net/5Q4U9/5/

- does NOT limit line length either
- if the line limit is reached, you are allowed to create a new line but trying to type anything in the new line has no effect (text turns red)

3) http://jsfiddle.net/draditya91/9x5Fb/116/

- limits the line length, so typing beyond the length wraps the text to a next line
- allows creation of new lines (still up to the maximum number defined)
- any new line created by text wrapped (because it reached maximum line length) counts against the limit of lines

Are we looking for such a solution? If so, the behavior of the 3rd solution makes more sense to me.

Hope this quick research helps and saves you some time.

**Comment by quicksketch** [comment]
I'm not sure if we're looking for a JS-based solution. Though I do like those implementations, they might be better left to contrib (not sure). Just a note that we already support `#maxlength` on textfields *and* textareas. Although textfields support client-side limitations, both fields are validated server-side to prevent exceeding the `#maxlength` property.

**Comment by jenlampton** [comment]
I think all we need to do is allow both widgets on both text and longtext field types. Text defaults to textfield, and longtext defaults to textarea, but other options are available.

These JS based approaches are pretty slick, but I agree they should be left to contrib. let's just take the functionality we already have and apply it in both places.

**Comment by jenlampton** [comment]
I made two changes (to lines 437 and 432 of text.module) to see what would happen.  It looks like the textfield has a required maxlength that the textarea does not, and you only get the ability to enter that maxlength when creating a field of type Text (short).  

This is because the textfield uses the max size in the db to limit the number of characters that are allowed to be entered to prevent the site from dangerously long input.  However, if we have a textfield widget on a Text (long) field type that's not a risk. 

Would it be safe to only add the '#maxlength' to the text field if it were provided as part of the field? If so, a PR is in the works...

**Comment by jenlampton** [comment]
Interesting, it looks like the default widget for textarea is now being set to textfield...  not what we want. I checked the code and I'm not sure the default widget setting is even being used anywhere.

**Comment by jenlampton** [comment]
New PR at https://github.com/backdrop/backdrop/pull/727

**Comment by quicksketch** [comment]
Looks like this PR is passing. I'll give this a look in the next couple of days and see if we can make this in 1.1.0 (out Friday).

**Comment by wesruv** [comment]
this++

**Comment by quicksketch** [comment]
Manually merged in https://github.com/backdrop/backdrop/commit/bc63bf00d1453ff009719ec7bc23037b307a6046 to fix a typo and CSS display of textfields with text format selection (even though it's not common).
