### ISSUE TITLE
Installed contrib modules are not listed in /admin/reports/updates

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#700]
Is this a bug or by design because we don't have a "mothership" yet? Can we have the same "not implemented yet" message as for core?

**Comment by quicksketch** [comment]
Yeah this is because the update server isn't in place yet. Backdrop only lists contrib projects that include a "project" line in the .info file. For example:

```
; Information added by drupal.org packaging script on 2011-06-20
version = "7.x-1.0-beta3"
core = "7.x"
project = "features"
datestamp = "1308598915"
```

That "project" line is what triggers the update behavior for a module. If a module doesn't have one, it's not listed on the update status page. We *could* start adding `project` lines to all modules, but I don't think there's any point in it since the update server isn't implemented yet. Once the update server is in place, these lines will start being auto-generated when new releases are made.

**Comment by quicksketch** [comment]
I filed an issue on how we can automate this at https://github.com/backdrop-ops/backdropcms.org/issues/51.

.

**Comment by klonos** [comment]
> ...I don't think there's any point in it since the update server isn't implemented yet. Once the update server is in place, these lines will start being auto-generated when new releases are made.

What about people that have already downloaded versions of these modules without the ```project``` property in their .info? They will not be notified of updates. Will they?

**Comment by quicksketch** [comment]
> What about people that have already downloaded versions of these modules without the project property in their .info? They will not be notified of updates. Will they?

Nope. For the time being, we won't be able to get any information on contrib projects. I suppose we could try to encourage module developers (myself included) to include both the project and version information in the .info files, but hopefully this entire situation is going to be short-lived. I expect we'll be able to get at least https://github.com/backdrop-ops/backdropcms.org/issues/51 put together in the next couple of months. I don't think it's worth trying to get developers to add this information for such a short period of time. Most modules probably won't even have a final release by that date.
