### ISSUE TITLE
Cutomize login error message.

### ISSUE THREAD

**Issue by serundeputy** [backdrop/backdrop-issues#701]
Allow site administrators to customize the login failed error message.

**Comment by quicksketch** [comment]
You can already customize the login failed message (or any other message) because it runs through t(). I think the documentation was removed for custom strings in settings.php, but this trick still works in Backdrop. This would change the login message to just "Login failed".

```
$settings['locale_custom_strings_en'][''] = array(
  'Sorry, unrecognized username or password. <a href="@password">Have you forgotten your password?</a>' => 'Login failed.',
);
```

This works for any string in Backdrop that runs through `t()`.

**Comment by serundeputy** [comment]
This is to add it to the admin interface for site builders; /admin/config/people/settings

travis is testing: https://github.com/backdrop/backdrop/pull/737

**Comment by quicksketch** [comment]
I'm not sure about replacing this message in the UI. I think this would be affected by both of these issues: https://github.com/backdrop/backdrop-issues/issues/111 and https://github.com/backdrop/backdrop-issues/issues/277, because this one message may end up becoming 3 or 4 messages (Unknown username, unknown e-mail address, unknown username *em* or e-mail address, and incorrect password). That's probably too much granularity to include in the UI, and users that really want to change this message can already do so through the existing string replacement.

**Comment by serundeputy** [comment]
ok; closing out.

**Comment by quicksketch** [comment]
Cool, thanks @serundeputy! I appreciate the suggestion and PR. :smile:
