### ISSUE TITLE
settings.php for multisite not working

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#708]
As per https://github.com/backdrop/backdrop-issues/issues/683#issuecomment-73817638, when setting up a multisite, the settings.php file in the multisite isn't being read as Backdrop just sees the settings.php in the root directory. The root directory one needs to be renamed (default.settings.php like in Drupal) or something so that multisite installations work nicely.

**Comment by quicksketch** [comment]
Hi @BWPanda! I think this may be a combination of intentional and unintentional behavior. Backdrop includes an efficiency optimization that it *assumes* a non-multisite situation. In Drupal 7, every bootstrap checked a variety of locations for settings.php and then used `sites/default/settings.php` as the *fallback*. However, since this was the most common situation and checking in 3 other locations was a waste of resources, Backdrop flipped the logic so that a root `settings.php` was checked first. If it's not found, then it flips to multisite logic.

However, multisite functionality can be enabled *by default* if the `sites/sites.php` file is set up to include the aliasing for multisite. If sites.php is configured, multisite is enabled and the root settings.php becomes the fallback. Some of this is documented in the `sites/README.md` file, but I think it may not be as clear as it could be. Could you try the `sites.php` approach and check that it works adequately for you? If so, this is primarily a documentation problem.

**Comment by BWPanda** [comment]
Thanks for the clarification @quicksketch. Using sites.php does indeed seem to make it check the right settings.php file (I just ignored sites.php in Drupal as I never seemed to need it...).

**Comment by docwilmot** [comment]
I havent tried this yet. For documentation purposes though, are you saying that Backdrop requires that multisites be set up explicitly in sites.php?

**Comment by quicksketch** [comment]
@docwilmot Multisite should require `sites.php` now, but it looks like deleting the root settings.php also triggers the functionality. I'm not sure how that works, it doesn't look like the code would support that. For the purpose of documentation, yes I think we should say that `sites.php` is required for multisite.

Here's the link to `find_conf_path()` that looks for settings.php files:
https://api.backdropcms.org/api/backdrop/core!includes!bootstrap.inc/function/find_conf_path/1

If `sites.php` is not set up or does not exist, then the path to settings.php will always just be `./settings.php`. Compare this to Drupal 7, where `sites.php` was optional, and it used pattern matching if sites.php was empty or missing: 

https://api.drupal.org/api/drupal/includes!bootstrap.inc/function/conf_path/7

**Comment by quicksketch** [comment]
Thanks @BWPanda!
