### ISSUE TITLE
DrupalDefaultEntityController missing

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#710]
The WYSIWYG Drupal module shows:
> PHP Fatal error:  Class 'DrupalDefaultEntityController' not found in /[BACKDROP]/sites/panda.id.au/modules/wysiwyg/wysiwyg.module on line 31...

There's no change record for this, but I noticed that a [DefaultEntityController](https://api.backdropcms.org/api/backdrop/core!modules!entity!entity.controller.inc/class/DefaultEntityController/1) class exists in Backdrop, so I changed 'DrupalDefaultEntityController' in WYSIWYG to 'DefaultEntityController'.

However, now I get:
> PHP Fatal error:  Class 'Layout' not found in /[BACKDROP]/core/modules/layout/layout.module on line 710...

So have I messed something up? Is DrupalDefaultEntityController != DefaultEntityController?

**Comment by quicksketch** [comment]
Yeah DrupalDefaultEntityController should be DefaultEntityController. Seems like that should be in the drupal.inc file, we may have missed it. This renaming was part of replacing "Drupal" with "Backdrop" throughout the code I think, but you're right that class is missing: https://api.backdropcms.org/node/26857

I don't know how the Layout class could be missing under the circumstances. Perhaps WYSIWYG module is calling code outside of any function wrappers? That might result in trying try load the class registry before all modules are loaded, resulting in classes going "missing" once the static cache has been set?

**Comment by quicksketch** [comment]
Oh, I see what happened.

There is a class directly in wysiwyg.module:

```
class WysiwygProfileController extends DrupalDefaultEntityController {
```

Once you change that `DrupalDefaultEntityController` to `DefaultEntityController`, it will immediately do a class registry lookup for `DefaultEntityController` when the file is loaded. But since all modules haven't been loaded when files are being parsed, classes might be missing.

So to fix this, you need to move that class into a separate file. Then use hook_autoload_info() to point at it. Change record for that is at https://api.backdropcms.org/node/26859.

**Comment by BWPanda** [comment]
Seems this is a bug then...

**Comment by BWPanda** [comment]
@quicksketch I've patch Backdrop with the code from the PR, but still getting the same error when trying to enable WYSIWYG. Do I still need to do the `hook_autoload_info()` thing?

**Comment by quicksketch** [comment]
Yeah, I added a comment on the PR. Those backwards-compatible classes need to be added to `backdrop_class_list()` (there's a section in there for renamed classes). Additionally, even with the backwards-compatibility fix, you'll still need to move the class from within wysiwyg.module to a separate file (and then point at it in `wysiwyg_autoload_info()`). The autoloader in Backdrop simply does not work when classes are intermixed in .module code, since loading the module will immediately trigger the autoloader. This happened in Drupal 7 as well, but the problem was invisible there most of the time (until your registry was corrupted and your site got hosed).

**Comment by quicksketch** [comment]
I updated https://api.backdropcms.org/node/26857 to include these two new classes/interfaces.
