### ISSUE TITLE
Upgrade path from block system to layout system

### ISSUE THREAD

**Issue by jdanthinne** [backdrop/backdrop-issues#715]
Is there an easy way for the upgrade path when the original module was defining multiple identical blocks (with deltas)? Is there a function that could create programmatically blocks with settings in layout?

**Comment by quicksketch** [comment]
> Is there a function that could create programmatically blocks with settings in layout?

The upgrade path should automatically create and place those blocks in the default layout in `system_update_1025()`. However if each of those blocks have unique settings (stored in the variables table or a database table), that makes things a bit trickier if you want to save those settings into block instances. You'll probably need to load each layout (there will be at least the admin layout and the default layout; possibly a `node/%` layout), then modify it with the settings and then save.

```php
function my_module_update_1000() {
  $layouts = layout_load_all();
  foreach ($layouts as $layout) {
    // Because each $block is an object and is always passed by reference, modifying it
    // will update the copy in the parent $layout.
    foreach ($layout->content as $block_uuid => $block) {
      $block->settings['foo'] = update_variable_get('my_module_foo_setting', 'default_value');
    }
    $layout->save();
  }
}
```

We don't yet have shortcuts for the layout API, so you have to load, modify, and then save everything manually. Because of the wide variety of scenarios you may get into with Layouts, we're not sure which shortcuts would be used frequently enough to merit them.

**Comment by jdanthinne** [comment]
Thanks for this advice, I've almost done with the upgrade, but I have a small problem… Some of my settings were linked to taxonomy vids, and it seems that this field (vid) is now gone, and replaced by machine names. Is there an easy way to retrieve that?
Or do I have to store those vids/machine_names association in a last Drupal version update, and specify this new schema version in hook_update_last_removed()?

**Comment by quicksketch** [comment]
> Some of my settings were linked to taxonomy vids, and it seems that this field (vid) is now gone, and replaced by machine names. Is there an easy way to retrieve that?

In situations like this, you can tell your update to run *after* the vocabularies have been converted to config but *before* the taxonomy tables are dropped. We split the updates in Taxonomy module specifically for this sort of situation.

Taxonomies are converted to config in `taxonomy_update_1001()` and then the tables are dropped in `taxonomy_update_1002()`. So if you want to have your update run between them, you can use `hook_update_dependencies()`:

```php
/**
 * Implements hook_update_dependencies().
 */
function my_module_update_dependencies() {
  // Run before the Taxonomy tables are dropped.
  $dependencies['my_module'][1000] = array(
    'taxonomy' => 1001,
  );
  $dependencies['taxonomy'][1002] = array(
    'my_module' => 1000,
  );

  return $dependencies;
}
```

Unfortunately, this approach would only work if the user had downloaded the Backdrop version of your module *before* running update.php for the first time. If they upgraded core first and then downloaded your module later, there wouldn't be any record of the old VIDs.

**Comment by jdanthinne** [comment]
Thanks for the advice, but I've just tested my upgrade path, and it seems that `layout_load_all()` is not supported there…
`Fatal error: Call to undefined function layout_load_all() in /backdrop-migration/modules/custom_search/custom_search.install`

**Comment by quicksketch** [comment]
Hm, that's interesting. The update must be getting run before Layout module is enabled. I suppose that makes some sense if your module starts with "c" and system module starts with "s" and they both have the same weight. You may need to also specify system_update_1025 as a dependency, which is where Layout module first gets enabled. So the full hook would now be:

```php
/**
 * Implements hook_update_dependencies().
 */
function my_module_update_dependencies() {
  // Run update 1000 after taxonomy_update_1001() but before taxonomy_update_1002().
  $dependencies['my_module'][1000] = array(
    'taxonomy' => 1001,
    'system' => 1025,
  );
  $dependencies['taxonomy'][1002] = array(
    'my_module' => 1000,
  );

  return $dependencies;
}
```

**Comment by jdanthinne** [comment]
I'm going to try that, but for your information, my module had already a weight of 100 before the migration so I'm not sure the upgrade respects those weights…

**Comment by quicksketch** [comment]
> so I'm not sure the upgrade respects those weights…

Ah, yeah I'm not sure either. I think once the dependencies are figured out, it may be somewhat random which ones get executed when, so long as the rules of the dependencies are met.

**Comment by jdanthinne** [comment]
Nope, still getting the same error, even with dependencies. Do I have to include a module file to make the function layout_load_all() available?

**Comment by quicksketch** [comment]
Huh, interesting. I thought that would have worked. It is a good idea to load a module file directly via `backdrop_load()` because there is no guarantee that the module will actually be enabled at the time (updates are run for disabled modules as well), but in the case of Layout, it should always be enabled after `system_update_1025()`.

Well, as an alternative, you could just load all layout files directly from config and modify them that way. It should be very similar and not require any of the APIs of Layout module.

Use `config_get_names_with_prefix('layout.layout.')` to get a list of layout config files, load each one, modify and then save.

**Comment by jdanthinne** [comment]
Used `config_get_names_with_prefix('layout.layout.')`. My upgrade path is working now. A but uglier than working the Layout class, but it's ok. Thanks.
