### ISSUE TITLE
[UX] I can't find my menu when trying to add a block

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#717]
The problem: I upgraded a Drupal 7 site to Backdrop. That Drupal 7 site has a menu called "Main menu". I can't find a block called "Main menu".

Thats because Backdrop calls this block "Primary navigation" in spite of the fact that it has it's own name.  the function `menu_list_system_menus` needs to check if these menus have real names, and if they do, use those instead.

Here's the new code for menu.inc

```
/**
 * Returns an array containing the names of system-defined (default) menus.
 */
function menu_list_system_menus() {
  $menus = array();
  $all = menu_load_all(); // Pulled from cache.
  foreach (array('main-menu', 'management', 'user-menu') as $machine) {
    if (array_key_exists($machine, $all)) {
      $menus[$machine] = $all[$machine]['title'];
    }
  }

  return $menus;
}
```

Someone make us a PR please? :)

**Comment by quicksketch** [comment]
I closed https://github.com/backdrop/backdrop/pull/967 to do a rebase and take a more conservative approach. Because `menu_list_system_menus()` previously did not need a database query but now it does, I was worried about problems this may cause in early page load situations and on performance.

So to fix it in a different way, in hook_block_info() and hook_block_view() in system.module, we just load the customizations from menu module specifically where we need them.

**Comment by quicksketch** [comment]
Merged into 1.x and 1.2.x.
