### ISSUE TITLE
hook_image_default_styles() deprecated

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#724]
likely part of https://github.com/backdrop/backdrop-issues/issues/169, but no record of this. wonder if anything else on that page needs documenting

**Comment by docwilmot** [comment]
Also its still mention in image.api.php

**Comment by quicksketch** [comment]
Thanks @docwilmot. `hook_image_default_styles()` is entirely removed (rather than just deprecated). Modules that want to include default styles can simply include an `image.style.[name].json` config file, or use hook_install() to add their initial image style config.

Modules can specify their style as being a module-provided style by including a "storage" and "module" key in their config file, like those provided by image.module itself:

```json
{
    "_config_name": "image.style.large.json",
    "storage": 4,
    "module": "image",
    "label": "Large (480x480)",
    "name": "large",
    "effects": [
        {
            "name": "image_scale",
            "data": {
                "width": "480",
                "height": "480",
                "upscale": 1
            },
            "weight": 1
        }
    ]
}
```

**Comment by docwilmot** [comment]
Could we add info about the storage types to image.api.php?

**Comment by JugglingCoder** [comment]
How can I "can simply include an image.style.[name].json config file"?  I downloaded some modules and looked all over but can find no examples.  Do I do a PHP include somewhere? in the .info file? in a .module > function? Please show a full example of how to do this.
