### ISSUE TITLE
Hook from which to change the active trail?

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#727]
I'm trying to port the relatively simple [Menu Trail By Path](https://www.drupal.org/project/menu_trail_by_path) module, but have come across a problem.

The main part of that module is the implementation of `hook_page_delivery_callback_alter()` which is where it calls `menu_tree_set_path()`. Even though `hook_page_delivery_callback_alter()` [exists](https://api.backdropcms.org/api/backdrop/core!modules!system!system.api.php/function/hook_page_delivery_callback_alter/1) in Backdrop, it doesn't seem to run at the same time (if at all) as in Drupal, hence the active trail is never set.

I've tried changing `hook_page_delivery_callback_alter()` to `hook_preprocess_page()`, `hook_preprocess_menu_tree()` and `hook_preprocess_menu_link()` but to no avail.
Any suggestions?

**Comment by quicksketch** [comment]
Yeah the page build process is quite a bit different in Backdrop due to the addition of layouts. If previously you used a `hook_page_*` hook, usually the replacement you need to use in Backdrop is a Layout-provided hook.

Based on the docblock from this module:
```
 * This is the only hook that occurs after the page callback, but before
 * hook_page_build (when blocks are added). We're using this hook for its
 * timing, not its data.
```

I think the best hook to use that is *after* the page content is rendered but *before* blocks are rendered is actually `hook_preprocess_block__system__main()`. I'm not sure that's close enough to where `hook_page_delivery_callback_alter()` was called, but it's worth giving a shot.

**Comment by BWPanda** [comment]
@quicksketch That seems to have done the trick, thanks!

Is `hook_preprocess_block__system__main()` documented anywhere? It seems to be a version of [`hook_preprocess_HOOK()`](https://api.backdropcms.org/api/backdrop/core!modules!system!theme.api.php/function/hook_preprocess_HOOK/1), but that would mean there should be a `theme_block()` and I can't find it...

**Comment by quicksketch** [comment]
block.tpl.php now lives in layout module. All blocks are run through template suggestions, so you can use `block--[module-name]--[delta].tpl.php`, and that extended to preprocess functions as well. So any block can have a `hook_preprocess__[module_name]_[delta]`.

**Comment by BWPanda** [comment]
Thanks for the help!
