### ISSUE TITLE
PHP notices & warnings thrown when adding classes to views

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#729]
If you wanted to make a flexslider in Backdrop (without the module) the easiest thing to do is add an unformated list view, and add some classes.  You add the `flexslider` class to the surrounding DIV tag and the `slides` class to the UL tag.  Both of these things are very straightforward to do in views module.  That is, if you don't get these errors:
```
Notice: Undefined offset: 0 in include() (line 17 of www/core/modules/views/templates/views-view-list.tpl.php).
Warning: implode(): Invalid arguments passed in include() (line 17 of www/core/modules/views/templates/views-view-list.tpl.php).
Notice: Undefined offset: 1 in include() (line 17 of www/core/modules/views/templates/views-view-list.tpl.php).
Warning: implode(): Invalid arguments passed in include() (line 17 of www/core/modules/views/templates/views-view-list.tpl.php).
Notice: Undefined offset: 2 in include() (line 17 of www/core/modules/views/templates/views-view-list.tpl.php).
Warning: implode(): Invalid arguments passed in include() (line 17 of www/core/modules/views/templates/views-view-list.tpl.php).
Notice: Undefined offset: 3 in include() (line 17 of www/core/modules/views/templates/views-view-list.tpl.php).
Warning: implode(): Invalid arguments passed in include() (line 17 of www/core/modules/views/templates/views-view-list.tpl.php).
Notice: Undefined offset: 4 in include() (line 17 of www/core/modules/views/templates/views-view-list.tpl.php).
Warning: implode(): Invalid arguments passed in include() (line 17 of www/core/modules/views/templates/views-view-list.tpl.php).
```

**Comment by quicksketch** [comment]
The fix looks good but there are some unrelated changes to the PHPDoc of a tpl.php file. Could those be separated out?

**Comment by jromine** [comment]
Ran into this working on references module.

There is some minor inconsistency among the various preprocess functions and the templates. Some preprocess functions explicitly set the row_classes array, and some templates check for empty() before assuming there is a value. 

Since the array is being imploded() in the template, I think the templates should all check for empty() before assuming there are values.

These test `if (empty($row_classes[$id]))`
* views-view-summary-unformatted.tpl.php
* views-view-summary.tpl.php

These test `if ($row_classes[$id])`
* views-view-grid.tpl.php
* views-view-table.tpl.php
* views-view-unformatted.tpl.php

This one assumes `$row_classes[$id]` is non-empty:
* views-view-list.tpl.php

**Comment by quicksketch** [comment]
Thanks @jromine for the fixes! Merged both PRs.
