### ISSUE TITLE
Layout "is front page" condition not firing

### ISSUE THREAD

**Issue by nicxvan** [backdrop/backdrop-issues#734]
I created a new layout with the condition that it fire on the home page. I added a custom block to the right sidebar and the backdrop block to the content region. However after saving the home page is still the default page with no blocks.

**Comment by quicksketch** [comment]
> I created a new layout with the condition that it fire on the home page.

Layout module doesn't automatically set the home page setting. So after creating the new layout, say at the path "frontpage". You have to visit `admin/config/system/site-information` and set the front page path to match. By default it's still going to be "node". Perhaps that's the problem?

**Comment by nicxvan** [comment]
Sorry that is not quite the issue, I have set the conditional is "the front page"
However after looking at it I didn't realize that the path was required. I assume you need to set the path to the wildcard since I always want this layout to show even if I change the home page path.

However, I cannot set the first part of the path to a wildcard. How would I get a layout that controls the homepage without manually setting the path each time it changes. I had assumed the conditional is front page accomplished that.
![layout issue](https://cloud.githubusercontent.com/assets/1300070/6255885/8b5018d8-b781-11e4-9e94-37d67826c971.png)

**Comment by nicxvan** [comment]
Setting the path equal to the path of the home page made it work. Seems as if we can't have a front page layout that doesn't care what the current home page is though unless I'm misunderstanding something.

**Comment by quicksketch** [comment]
Right, I don't think there's much point in creating a new layout with the condition "is front page". The same list of conditions is available for both blocks and layouts, and that condition is intended to be used in a situation like the default layout, where you might want a block to only show up on the homepage.

This brings up an interesting point though. We should either remove the "is front page" condition from the list of conditions for layouts (since it does no good there) or we should leave it but provide some kind of integration or notice informing the user how to make that layout their homepage. Making a custom layout for your homepage is probably the most common task you could imagine with Layouts in core.

**Comment by nicxvan** [comment]
Maybe add support for <front>

I just tested, it accepts the path, but doesn't work as expected either.

**Comment by quicksketch** [comment]
> I just tested, it accepts the path, but doesn't work as expected either.

Maybe I should ask, what is the behavior you were expecting here?

There may be a disconnect where you may be expecting that a multiple layouts can affect the same path. Backdrop only supports one layout per path. If no layout is specified at a particular path, then the Default layout is used. Supporting a path like `<front>` would mean that some path may end up with two layouts at the same time, such as if the site had both a `<front>` layout and a layout on the `node` path.

I like the idea of making `<front>` somehow work as a layout path, but what it would likely do behind the scenes is check what the current front page path is (e.g. `node`), then set that as the path, but that doesn't sound like what you'd be expecting either.

**Comment by nicxvan** [comment]
I would be expecting how <front> works with paths in context, it just uses
whatever the current front page is, but it is a variable placeholder so if
the front page changes it goes along with it. This is useful e.g. you need
a banner on the home page always. So you create the view and place it with
the layout, then you publish a new home page, you would expect the layout
to still put the banner there rather than having to edit the layout and
change the path to "follow" the front page.

**Comment by quicksketch** [comment]
> Seems as if we can't have a front page layout that doesn't care what the current home page is though unless I'm misunderstanding something.

Right, the only layout that doesn't care what path you're on at all is the Default layout. Perhaps what you're describing (if this were Drupal 7 and Panels) is the concept of adding variants to the Default layout? We don't support that concept (although we technically code) for simplicity and performance reasons.

**Comment by quicksketch** [comment]
> I would be expecting how <front> works with paths in context, it just uses whatever the current front page is, but it is a variable placeholder so if the front page changes it goes along with it. This is useful e.g. you need a banner on the home page always.

Ah, yes. This sort of thing is definitely not supported. That's exactly the concept of supporting multiple layouts on the same page. You get into a bucket of problems with that, such as trying to manage the order of the blocks in the same region. In D7 Context, you get around that with manually setting the block weights using numbers instead of a drag-and-drop, but it can be a headache. In our case, I think the primary concern would be performance. If we have to load and compare conditions for multiple layouts on every page it would result in a lot of additional overhead on every page. For simplicity and performance, only one layout is *ever* used on a particular path, whether that's a specific layout for that path, or the default layout if no other layout path matches.

**Comment by nicxvan** [comment]
This is interesting, I understand your reasoning now, however some things
like this that are a common and expected paradigm in Drupal will likely be
hangups, maybe a FAQ (if you don't already have one I didn't look) would
help clear some of that up.

**Comment by quicksketch** [comment]
Absolutely, although we're making great headway on developer documentation over in http://api.backdropcms.org, our end-user/site-builder documentation is almost non-existent. Once we get the basics in place, a feature like https://github.com/backdrop/backdrop-issues/issues/119 might help point people in the right direction.

If you have any suggestions as to how to improve the inline help or validation to help prevent the confusion, we can take a look at implementing them.

> some things like this that are a common and expected paradigm in Drupal 

It's really interesting to see how the upgrade path works for layouts (in `system_update_1025()`). In Drupal 7 (without Context module) we had only a single layout a bunch of different conditions. The upgrade path actually converts block positions into a layout if possible (based on matching region names). A from-scratch Backdrop site could be set up the same way and only use the "Default" layout, and that would match the out-of-box functionality of D7. Of course as soon as you have the ability to make different layouts per path, using a single layout for the entire site seems like it'd be a crazy.

I think what I'm getting at is that the same paradigms still exist (or could be created in contrib), but you probably wouldn't want to use them in the first place now that we have better tools at the base level.

**Comment by quicksketch** [comment]
Closing this issue as it's Q/A rather than an bug or feature request.
