### ISSUE TITLE
Main content block not available in layouts to place.

### ISSUE THREAD

**Issue by nicxvan** [backdrop/backdrop-issues#735]

**Comment by quicksketch** [comment]
Hey @nicxvan! The behavior of the "Main content" block can be confusing. It's only available if you're overriding an existing menu path. If you make a new path, like "frontpage" there is no "main content" available. If you override an existing menu path, like "node/%" then the main content block shows what would normally be at that path.

Muddying things a bit further is the caveat that if you want to override "node/1" you actually need to override "node/%" and then use a conditional to target NID 1. Fortunately, we have a warning that informs you if you've specified a path that looks as though it should be using a wildcard. Layout module won't stop you from overriding "node/1", but if you do that it's going to create an entirely new menu callback at that path, so the main content block won't be available.

**Comment by nicxvan** [comment]
Hmm, that's interesting, what is the reasoning behind that?

**Comment by quicksketch** [comment]
Although Layouts make some aspects of page creation transparent (i.e. you can just make a new page or override the layout of any existing one), it's still tied into the menu system pretty heavily. If you make a new path that's not defined in hook_menu(), the main content block won't be available because there's no page callback to populate it; so the page callback is provided by Layout module and the page become just a bunch of arbitrary blocks. When overriding an existing path, Layout basically wraps the existing page content and moves its content into a block.

**Comment by nicxvan** [comment]
Ah that makes perfect sense now.

**Comment by quicksketch** [comment]
Oh good, it didn't seem like I was explaining it very clearly. Thanks for sharing your initial experience here, it helps us understand the problems people are likely to face. :+1:

**Comment by nicxvan** [comment]
No problem!
