### ISSUE TITLE
[UX] Simplify the default content type names from "Article" and "Basic page" to "Post" and "Page" respectively.

### ISSUE THREAD

**Issue by clickbox** [backdrop/backdrop-issues#742]
Calling Article content types "Post" is more intuitive. The description for Articles is also confusing. Something like "This is the default content type for post" seems easier to understand.

**Comment by quicksketch** [comment]
I think "Post" is probably a more universal term than "Article", so I agree there. It could be used for a blog post, an article, or whatever the user wants. Though if the content type is named "Post", we'd need a different word in the description. The current description isn't far off the mark:

> **Article**
> Use *articles* for time-sensitive content like news, press releases or blog posts.

I'd like to drop the awkward "time-sensitive" phrase, but otherwise it's not bad and would work for Posts as well. How about we change the description to be more active, with "Add" instead of "Use" as the verb.

> **Post**
> Add a blog post, news article, or press release.

We'd need to do the same thing for "Basic page" of course, and maybe drop the "Basic" while we're at it.

> **Basic page**
> Use *basic pages* for your static content, such as an 'About us' page.

To:

> **Page**
> Add a page for static content, such as an 'About us' page.

This would actually bring inline with exactly the same terminology as WordPress (Post and Page). Thoughts?

**Comment by docwilmot** [comment]
great ideas, agreed

**Comment by dariusgarza** [comment]
+1

**Comment by clickbox** [comment]
@quicksketch I think that description for post is a vast improvement. I personally have a huge problem with the term "Basic." Turning it to "Page" makes the most sense to me also. I don't like the description for basic page from drupal 7. I think that by emphasizing on "static" content it makes conceptualizing how to use views more difficult for new users. A post or a page can be used in views to create dynamic content.

**Comment by dariusgarza** [comment]
Post and Page nomenclature makes sense but also aligns perfectly with Wordpress. I guess that's not terrible. That sorta happens when the general consensus around an idea just works, i.e. all tissues are kleenex, all mp3 players are iPods, etc.

Even if we change the names, we still have the disconnect between Post content types and what will eventually become a view, but that's another issue onto itself.

**Comment by quicksketch** [comment]
As this isn't a "bug" in the typical sense, I'm moving this to the 1.1.0 release. We haven't yet branched 1.0.x, so as soon as this (or any other 1.1.0 issue) is ready, we'll make the branch to start separating our bug fixes (1.0.x branch) from our features (1.x branch).

**Comment by klonos** [comment]
Just a thought here, the words "post" and "page" are also verbs and it might get tricky to get certain UI and documentation text right. For example, in #743 I proposed to change the "Edit" tab label to "Post settings" and "Page settings". If one reads the "post" and "page" as verbs, they might get the wrong meaning. Hope this makes sense.

**Comment by quicksketch** [comment]
I'm up for including this relatively simple change in the 1.1.0 release, but getting this done could require more time than we have (I believe a lot of tests may be affected). Is anyone interested in taking this on?

**Comment by clickbox** [comment]
i'll give it a shot

**Comment by quicksketch** [comment]
Let's kick this to 1.2.0. The release of 1.1.0 is imminent.

**Comment by jenlampton** [comment]
Very well, at least there is  PR now for testing :)

**Comment by quicksketch** [comment]
@hellomrcat has almost got this working in https://github.com/backdrop/backdrop/pull/948. Nice job!

**Comment by quicksketch** [comment]
I've been testing out the PR from @hellomrcat and it works great! The code is top-notch as well. There was a minor merge conflict so I made a new PR at https://github.com/backdrop/backdrop/pull/1046. If it passes tests then this is good to go.

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/pull/1046. Wow great job @clickbox for the ideas and @hellomrcat for the implementation!
