### ISSUE TITLE
Can/should modules store their settings in another module's contrib file?

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#746]
I'm porting the [Submitted By module](https://www.drupal.org/project/submitted_by) which stores its settings in per-node-type variables (e.g. `variable_get('submitted_by_' . $node_type->type, NULL)`).

Is the best way to convert this to CMI to store settings in:
1. 'submitted_by.settings.json'
2. 'submitted_by.[node_type].json'
3. 'node.type.[node_type].json'?

**Comment by quicksketch** [comment]
I think generally, modules should probably store settings in their own config files, even if they're extending another module's functionality. That makes cleanup of that module's configuration easiest in the event that the module is uninstalled.

**However**, in the case of node types, we already have special functionality to allow for other module's settings within a `node.type.[node_type].json` config file. It also makes things easier so that you don't have to implement `hook_node_type_delete()`. So in this case, you should use that. All core modules already extend the config form for node types, such as Book or Menu modules. See `menu_form_node_type_form_alter()`. We also now support providing default values in the $node_type->settings array, to save you the hassle of using `isset()` or `empty()` checks all over the place. See `menu_node_type_load()` for an example there.

**Comment by klonos** [comment]
> I'm porting the [Submitted By module](https://www.drupal.org/project/submitted_by) module...

Now with Token (soon to be) in core, perhaps we should just implement #885 and then simply allow that field to accept tokens? Just an idea.
