### ISSUE TITLE
Get list of view modes in hook_node_type_load()

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#748]
I need a list of view modes for the 'node' entity type in `hook_node_type_load()` as certain settings are stored per view mode. However, the following code causes errors with the site not loading (I think it's a timeout issue):

```php
function submitted_by_node_type_load(&$types) {
  dpm($entity_info = entity_get_info('node'));
}
```

It looks like `entity_get_info()` is cached, so not sure why this is happening...

**Comment by quicksketch** [comment]
I think you may be causing a recursion loop, as `entity_get_info()` may be loading a list of node types, which in turn calls this hook again.

You might use `hook_entity_info_alter()` instead of `hook_node_type_load()` to prevent this looping problem, and you'll have the view modes passed directly into your hook so you don't have to look them up separately.

**Comment by BWPanda** [comment]
The problem is that I need to use `hook_node_type_load()` to set default values as per https://github.com/backdrop/backdrop-issues/issues/746#issuecomment-75184277. It doesn't seem that `hook_entity_info_alter()` allows for that...

**Comment by quicksketch** [comment]
Hm, well one other alternative is simply keeping these settings in your own config files instead of storing them in the node.type.[type].json files, but I agree it doesn't seem ideal, however that's the current situation we're in with view modes. Even for node module itself, all view mode settings are stored separately in `field.bundle.node.[bundle].json` files. That's a legacy effect from this information previously being stored in the variables table.

So... bottom line. I'm not sure where you should store this information as I haven't looked at the full use-case. But the solution I *know* would work would be specifying an entirely new "group" of configuration files, one for each node type and loading those configs whenever the settings are necessary.

**Comment by BWPanda** [comment]
Thanks @quicksketch. I ended up doing a bit of a hack: https://github.com/backdrop-contrib/submitted_by/blob/1.x-1.x/submitted_by.module

The 'submitted_by' setting should be an array of view modes, but I initialise it as a string and then do a check for the '#default_value': `is_array($node_type->settings['submitted_by']) ? $node_type->settings['submitted_by'][$view_mode] : $node_type->settings['submitted_by'],`
