### ISSUE TITLE
Changing theme settings causes CMI import to fail

### ISSUE THREAD

**Issue by cellear** [backdrop/backdrop-issues#752]
It appears that CMI import assumes that only modules can generate variables, and thus fails when a theme has a settings file.

Steps to reproduce:

1. Add a contributed theme that supports color - for example, https://github.com/backdrop-contrib/aeon5
2. Visit admin/appearance/settings/aeon5 and change some parameters
3. Export CMI: admin/config/development/configuration/full/export
4. On another installation of backdrop, add theme to /themes directory and start full CMI import: admin/config/development/configuration/full/import, upload and click Stage Import.  
5. You'll be directed to admin/config/development/configuration. See your settings change, View Differences if you want, and click Import all.

Error message:
> Configuration sync failed. The following errors were reported:
> The configuration "aeon5.settings" is not owned by any module. Try enabling the module that provides  this configuration, then importing again.

**Comment by quicksketch** [comment]
Thanks for filing this issue @cellear! I could definitely see how this would occur. I think you could even cause this problem just by setting the color settings in Bartik. The problem here is that all modules have to declare their config files in hook_config_info(), but in the case of themes, they don't have the ability to use this hook in the first place. We need to make system module responsible for declaring config for all themes.

This is a serious issue that breaks our probably-most-important feature. It must be fixed for the next release (and is probably trivial), so I'm tagging this to 1.0.4.

**Comment by quicksketch** [comment]
I filed an issue for this at https://github.com/backdrop/backdrop/pull/758.

I also ran across another issue with Color module not generating CSS/images on config Import. I filed a new issue for that over in https://github.com/backdrop/backdrop-issues/issues/792.
