### ISSUE TITLE
Re#736 - Form Elements, complex (Pt 2)

### ISSUE THREAD

**Issue by wesruv** [backdrop/backdrop-issues#754]
Implement the following form element styles as per the style guide:

* Select (add new style)
* Checkboxes (confirm default styles don't need tweaking)
* Radio buttons (confirm default styles don't need tweaking)
* General buttons (add new style)

See master issue for instructions/guidelines for implementation:
https://github.com/backdrop/backdrop-issues/issues/736

![select](https://cloud.githubusercontent.com/assets/397895/7290727/11ee608c-e939-11e4-84cf-b1bd391ba71c.png)

![button](https://cloud.githubusercontent.com/assets/397895/7290446/ddd7c8b0-e933-11e4-9a42-51d36ab2b535.png)

top photo here shows normal, lower shows hover state

**Comment by klonos** [comment]
It was mentioned before, but the gray color in drop-down selects menus makes them look disabled. We should change this.

**Comment by quicksketch** [comment]
The Select list colors will be addressed in the next round of revisions on the styleguide. We should have that in the next couple of days. Let's just keep an eye on http://backdrop-ops.github.io/styleguide/ for the latest.

**Comment by jenlampton** [comment]
I moved the more complex button styles over into https://github.com/backdrop/backdrop-issues/issues/883 to unblock this issue.  The rest of the items in this issue are now ready for implementation.

**Comment by Graham-72** [comment]
I have made PR https://github.com/backdrop/backdrop/pull/837 in order to apply the styleguide CSS to select.form-select in style.css

**Comment by Graham-72** [comment]
I have made PR backdrop/backdrop/pull/838 in order to apply the styleguide to the buttons. With this PR all the form buttons (Submint, Preview, Confirm and Search) have the same revised appearance and I assume that specific colours will be assigned in a future PR.

I have had a look at checkboxes and radio buttons and it seems that no changes are needed

**Comment by quicksketch** [comment]
Hi @Graham-72! I looked at your PR for .form-select (and other inputs). Everything looks pretty good. I checked in Safari, Chrome, Firefox, and IE10. The only problem I noticed was that Safari didn't take the changes to the select list:

![select](https://cloud.githubusercontent.com/assets/100206/7310654/baa8a498-e9e4-11e4-8ff2-440fc6f17333.png)

Unfortunately this gets us into a whole bag of worms. You can remove the glossy look with `-webkit-appearance: none;`, but then the little arrow disappears as well. The only apparent solution is to replace the little arrow with your own manually with CSS. I think we should merge https://github.com/backdrop/backdrop/issues/837 as-is and make a followup for select lists specifically. This is going to get messy.

**Comment by jenlampton** [comment]
We should have a single PR here that includes all changes (if necessary) for 
* Select (add new style)
* Checkboxes (confirm default styles don't need tweaking)
* Radio buttons (confirm default styles don't need tweaking)
* General buttons (add new style)

@Graham-72 it looks like https://github.com/backdrop/backdrop/pull/838 covers the buttons and https://github.com/backdrop/backdrop/pull/837 includes the select styles, but we're still missing those for checkboxes and radios.

I'm going to take a stab at merging these two PRs together and adding the radio / checkbox styles.

**Comment by jenlampton** [comment]
trying this again, since my PRs seem al SNAFU tonight

**Comment by jenlampton** [comment]
Alrighty, I think I finally got those up there correctly.  Phew. So, heres what I did for this one:
- combined @Graham-72's two previous commits, plus minor updates
- added a 5px right-margin to radios and checkboxes, 
- added a vertical-align: middle to the labels of radios and checkboxes
- switched out the inner box-shadow for a border on select elements (which still look almost default on safari and chrome, sadly, but look very nice on FF)
- de-emphasized the text-format select box by decreasing padding, and removing bold from the label
- and cleaned up some styles in the views UI.

**Comment by Graham-72** [comment]
@jenlampton From your PRs I have built myself a fresh local version of style.css, Though I had to do quite a bit of it manually because of a problem with commit 8c8f772 failing for me - something wrong in line numbering. I will try and track this down.

Anyway, the result is that the styleguide demo page is now looking excellent (in Firefox at least). If it helps, I will review 'normal' admin pages, also use other browsers. Would you like comments against this issue or as new issues?

**Comment by Graham-72** [comment]
@jenlampton From your PRs I have built myself a fresh local version of style.css, Though I had to do quite a bit of it manually because of a problem with commit 8c8f772 failing for me - something wrong in line numbering. I will try and track this down.

Anyway, the result is that the styleguide demo page is now looking excellent (in Firefox at least). If it helps, I will review 'normal' admin pages, also use other browsers. Would you like comments against this issue or as new issues?

Related issue:
https://github.com/backdrop/backdrop-issues/issues/753

**Comment by quicksketch** [comment]
Let's merge this in and continue iterating in followups. The code looks great and we can keep improving or fixing missing pieces.

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/issues/844. Thanks @Graham-72 and @jenlampton!
