### ISSUE TITLE
Help debugging layout dialog

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#762]
I'm trying to include a form in a block config form. In a custom class I have 
```
  function form(&$form, &$form_state) {
    module_load_include('inc', 'modbox', 'modbox.admin'); 
    $form += backdrop_get_form('modbox_edit_box', 'edit');
    //dpm($form);
  }
```
the form modbox is like
```
function modbox_edit_box($form, &$form_state, $type, $modbox= array()) {
```
In Layout, I can click add block, the configuration form pops up normally, my included form appears in the block configuration quite well, but on clicking "add block" the ajax loader icon pops up briefly then nothing happens. I cannot figure how to find out what is wrong. because there is no error anywhere.

Is there anyway to debug this?

**Comment by serundeputy** [comment]
I would say:
  check watchdog logs
  right click | inspect element | {check for js errors} 
  apache error logs

~Geoff

**Comment by quicksketch** [comment]
```
    $form += backdrop_get_form('modbox_edit_box', 'edit');
```

This is going to cause a lot of unexpected behavior, because `backdrop_get_form()` actually can *process* a form on a POST request. If you just want to merge the raw form definition into $form, you could do this:

```php
  function form(&$form, &$form_state) {
    module_load_include('inc', 'modbox', 'modbox.admin'); 
    modbox_edit_box($form, $form_state, 'edit');
    //dpm($form);
  }
```

However, calling a form callback with a stubbed-out or incorrect $form_state() could lead to other problems. If you have a partial form that you'll be using in two different places, it's best if that partial-form were its own function that was not intended to be used with `backdrop_get_form()` at all, and could work without a $form_state parameter.

**Comment by docwilmot** [comment]
dupe of 790
