### ISSUE TITLE
Running your module hook_update_N before or after another modules update.

### ISSUE THREAD

**Issue by behindthepage** [backdrop/backdrop-issues#766]
You can tell backdrop to run your hook_update_N function before or after another modules update by using hook_update_dependencies().

https://api.backdropcms.org/api/backdrop/core%21modules%21system%21system.api.php/function/hook_update_dependencies/1

**Comment by klonos** [comment]
...and the question/issue here is? What??

**Comment by behindthepage** [comment]
This came about after a discussion on IRC. I asked how to do this and Jen Lampton thought it would be good to have this information in the issue queue. So it can be closed.

**Comment by quicksketch** [comment]
It's all good. :smile:

If there's a particular item you think should be documented on api.backdropcms.org, you can also file an issue at https://github.com/backdrop-ops/backdropcms.org/issues. I don't think there's anything to be done in core about this, since it's already documented in the hook itself.

@behindthepage We can add you to the list of editors at api.backdropcms.org if you're interested in helping maintain documentation also. The site eventually will be shared login with the main site which will allow open registration, but until then we're manually adding accounts. Thanks!
