### ISSUE TITLE
Re#736 - Pager

### ISSUE THREAD

**Issue by wesruv** [backdrop/backdrop-issues#784]
See master issue for instructions/guidelines for implementation: 
https://github.com/backdrop/backdrop-issues/issues/736

![style guide backdrop](https://cloud.githubusercontent.com/assets/5607236/6402972/d401db1c-bdd9-11e4-82d5-e1366cc0af9a.png)

**Comment by jenlampton** [comment]
dibbs.

**Comment by jenlampton** [comment]
Okay, so I first implemented this as a change to `system.theme.css` but then when I looked at bartik with the new pager styles it looked really weird. So I moved the new pager style from System to Seven and now Bartik has it's previous style back, and seven still looks sweet.

Let me know what you guys think - if we want the new pager styles to be base styles or not.

**Comment by quicksketch** [comment]
:+1: for changing Seven but leaving system.theme.css as-is. Less styles that need to be overridden by themes that keep system.theme.css in place.

**Comment by quicksketch** [comment]
The PR looks good, but at least on `admin/content`, the pager is really cramping the style of the content table. I think this because previously we didn't have outlines around these numbers, so you had the combined padding of the pager links and the overall pager. Now it appears pretty tight with only the overall pager margin. It looks like the current margin is 0.25em, could we increase that (both top and bottom) to 1em?

**Comment by jenlampton** [comment]
Easy enough to rectify.

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/pull/763 to 1.x-new-style.
