### ISSUE TITLE
[UX] Keep admin_bar sticky at the top of the page by default.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#788]
I think that this is the most common setting but could be wrong. It has no effect in short pages, but reduces the scrolling to get to other admin sections in long pages so UX+. Until we get metrics in place (#285), I'd like to hear what others say:

![screen shot 2018-12-11 at 1 30 59 am](https://user-images.githubusercontent.com/2423362/49768297-86da5a00-fce4-11e8-947c-aca89d0d3f1f.png)

Might not be ideal for mobile, so we can have a conditional. Not sure if we want to expose that as another setting (as a "only on wide screens" sub-checkbox).

**Comment by quicksketch** [comment]
This was an intentional change from D7's admin_menu.module for a couple of reasons:

- Sticky headers/menu reduces available vertical space on mobile (as you mentioned).
- Mid-page anchor tags are broken by sticky headers/menus.
- There is a current trend of front-end themes including sticky headers/menus, combining two levels of sticky header (plus the table sticky headers potentially), causing administrators to end up with double or triple sticky header items on front-end pages.

But ultimately, whether the admin bar is sticky or not comes down to a lot of personal preference, which is why admin bar has the option in the first place. I'm also not sure which setting is more popular, but non-sticky is definitely the most compatible, which is why it's the default.

**Comment by Bojhan** [comment]
I would largely say that if Backdrop is opinionated. That it doesn't add checkboxes for user interface parts (no checkbox-irtus)

http://limi.net/checkboxes-that-kill/

**Comment by quicksketch** [comment]
Ha, that's an awesome article. I see Firefox took it seriously though, I don't think a single one of those checkboxes exists in new versions of Firefox.

In this case though, I think it'd be wise to keep the option because it was actually the default for the Drupal 7 version of the module. That's a lot of users that probably expect the previous behavior. If we manage to get metrics on this and find that 90%+ of users leave the default setting, we can look into removing it in 2.x.

**Comment by klonos** [comment]
That seems fair enough. Metrics would save us a lot of guesswork and assumptions and would have saved a few dozen comments in 300+ comment issues in d.org.

**Comment by klonos** [comment]
I would like to revive this. I admit that this is a personal preference of mine, but the D8 admin bar is sticky, and the same goes for WordPress too.

To couter @quicksketch's arguments...

> - Sticky headers/menu reduces available vertical space on mobile (as you mentioned).

This is true, but then again a) how many people perform admin tasks on mobile, and b) we could have the stickyness be conditional (only on non-mobile).

> - Mid-page anchor tags are broken by sticky headers/menus.

That is true for sticky table headers too (#3414), but we have not disabled them.

> - There is a current trend of front-end themes including sticky headers/menus, combining two levels of sticky header (plus the table sticky headers potentially), causing administrators to end up with double or triple sticky header items on front-end pages.

Yep, that's what's happening with the preview bar in D8, but I have yet to hear anyone complain about it:

![image](https://user-images.githubusercontent.com/2423362/49768864-86db5980-fce6-11e8-901d-357ad5da7afc.png)

...there's even design proposals/implementations that merge the edit/save/submit buttons in the admin bar. For example, a toggle button that shows/hides contextual link edit buttons:

<img width="1081" alt="screen shot 2018-12-11 at 1 48 12 am" src="https://user-images.githubusercontent.com/2423362/49769084-8b544200-fce7-11e8-9fae-72be44453f17.png">

...this in fact improves the UX on mobile, because otherwise mobile users do not get access to the contextual links (they are only activated on hover - which is not available on mobile).

**Comment by vstemen** [comment]
I think I agree with @klonos.  I would vote for making it sticky by default.
I hadn't even noticed the setting for it until @klonos pointed out this
issue in the chat :-).   Now I have enabled it on mine.  I also never or
rarely do site admin from a phone.  It is more convenient keeping the admin
bar visible at all times when logged in managing a site.

I also noticed that my Drupal 7 sites have a shadow below the admin bar,
which looks nice, but does detract from the natural look of your theme when
you are doing site development.  Especially if your theme or page has
decorations, shading, or buttons, etc. at the very top.  I think I like
Backdrops bar better.  It allows your page to look the way it will to normal
users without having to log out to verify the appearance.  I Just thought
I would throw my opinion out on that as well while on the subject.

**Comment by stpaultim** [comment]
I don't feel strongly about this, but I will always turn on the sticky admin bar if it is not already turned on and would appreciate having it turned on by default. I currently have the sticky admin bar turned on in my sites that also have sticky user menus and do not find that a problem. 

I know that in the past I have on occasion forgotten that this was an option and been frustrated by the fact that the admin bar was not sticky. On the up site, I was very happy when I remembered or stumbled across this option.

**Comment by BWPanda** [comment]
I *do* feel strongly about this! :wink: I also enable the 'sticky' option on all my sites and would love to see it made the default option. My personal opinion is that the majority of people do the same, though I've no stats to back this up.

I do take issue, however, with removing this checkbox, as seemed to be suggested above. This is clearly a feature that some like and some don't, so removing the option altogether (whatever the default) would be a bad move IMO.

**Comment by indigoxela** [comment]
I never turn on "sticky" for several reasons.
Whatever you decide here (default on/off) - _please_ do not rip out the ability to configure this. I'd consider that a regression.

**Comment by klonos** [comment]
> ...though I've no stats to back this up.

That's why I started creating polls in Zulip 😉 ...I know that actual metrics would be better, but something is better than nothing.

**Comment by oadaeh** [comment]
For reference, in case anyone was wondering: https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/Polls/near/206693075

**Comment by klonos** [comment]
...and the current tally at the time of writing is:

![image](https://user-images.githubusercontent.com/2423362/90415404-b3e62f00-e0b9-11ea-88c9-9f0b3f3b3aa6.png)

**Comment by BWPanda** [comment]
Here's a PR: https://github.com/backdrop/backdrop/pull/3518

**Comment by klonos** [comment]
Thanks @BWPanda ...RTBC 👍 

It would still help to have usage metrics on this before merging. That way, we won't be going back and forth, we people in the future opening an issue to revert this change.

**Comment by quicksketch** [comment]
I'm with @indigoxela in that I'm fine changing the default as long as the option is left in place. My original comment from 2015 still summarizes my reservations: https://github.com/backdrop/backdrop-issues/issues/788#issuecomment-76679645

I think the anti-stickies are outnumbered here though. Should we put this into 1.19.0 then? If we wait on usage metrics, (assuming that were to go into 1.19.0 or 1.20.0), it would probably be a year before we had enough data to even help.

**Comment by BWPanda** [comment]
> Should we put this into 1.19.0 then?

Sounds good.

**Comment by BWPanda** [comment]
Adding milestone directly and bypassing need for an advocate because of the RTBC status.

**Comment by stpaultim** [comment]
I would say that we should go ahead and include it sooner rather than later. I would love to have metrics, but 1) they have limitations, because user settings are often what they are because users don't realize they can change them 2) well I am working towards implementing metrics, I don't think we should stop putting in new UI changes until we get them and I don't see why this issue needs them anymore than lots of other issues that are going in or have gone it recently. 

Sure, we don't want to be going back and forth. But, this is a default setting on new sites and if there is an unexpected uproar about this change, that is probably more reliable than metrics and and it's easy to change back with little downside.

**Comment by BWPanda** [comment]
Thanks @klonos for reviewing, and to everyone else for their feedback on this. I've merged https://github.com/backdrop/backdrop/pull/3518 into 1.x.

**Comment by jenlampton** [comment]
I just wanted to note here that i've been having a lot of problems navigating large sites with a sticky adminbar. When a drop-down menu is sticky, and the drop-down part is longer than the opened viewport, it's impossible to click any link that's out of sight. When "Webform" is out of sight on the content-types list, for example, the only alternative is to click on the parent page "Content types" and then select "Webform" from the landing page.

I'm not sure this problem warrants reverting this change, but I did want to note that the non-sticky setting never made any of the menu unusable -- which explains why that setting was the default :)

**Comment by BWPanda** [comment]
Understood @jenlampton. I've also experienced that problem (mainly in Drupal though). I think the best solution would be to open an issue to address/fix the problem, rather than just avoiding it...
