### ISSUE TITLE
User guide for site editors 

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#808]
The documentation we already have for Backdrop is great for those who are setting out to build a website on Backdrop and are already familiar with simple procedures like adding and editing content.

My experience with clients for whom I have provided Drupal sites is that they need a separate level of documentation just to walk them though the process of adding and editing content, particularly when it comes to controlling their navigation menu. So I have usually put together a few sheets of basic instructions, including screenshots. I shall need to be doing this for Backdrop and I would be pleased to contribute to documentation that serves this purpose.

I guess the first problem we face is that any such documentation would have to describe use of the editor, and anything I do would be based on CKEditor, and IMCE for uploading images and attached files.

I would be interested to hear whether (a) I can be of any use in contributing to Backdrop in this way, and (b) anyone else is interested in helping.

**Comment by docwilmot** [comment]
Hi @Graham-72, the docs on the API site are as you noticed developer focused. I agree we need more user focused docs as well.
https://github.com/backdrop-ops/backdropcms.org/issues/26, and 
https://github.com/backdrop-ops/api.backdropcms.org/issues/3
were discussions about getting this started, so we ended up having developer docs on the API site while waiting for a proper docs site to land for user docs. I think/suspect we were waiting to port the main site to Backdrop before launching that. 
So now is a good time to raise this again, since the porting is complete.
Should we do a separate docs.backdropcms.org or just have docs content on the main site?
@jenlampton 
@quicksketch

**Comment by jenlampton** [comment]
@docwilmot I think we should add some very basic user-focused documentation into the handbook, under user guide.  We need some explanations of terms and concepts for the building blocks of Backdrop: what are nodes, fields, terms, blocks, layouts? How do they fit together to make a site?

Beyond that, I'm not sure how the docs should be organized. docs.backdropcms.org seems like potentially too much, since contributed docs will likely be on github wikis.

**Comment by docwilmot** [comment]
Thinking of a new user though, @jenlampton we'd need to explain many more things than that for core modules. Not just the 'what' for the above, but all the 'howto'. Roles, permissions, views, registration, media, etc etc. Not to mention things that are more best practice advice (reuse fields, turn on caching, disable update module etc. And code snippets and tips and bits. 
I know that coming in as a complete newbie to everything CMS- and website-related just a few years ago, stuff like that was very helpful. Recalling who we say are our target audience, we need to be helpful as possible.
I can build another outline of user documentation as a proposal for you to approve again, and then use that to decide if a dedicated subdomain is warranted.

**Comment by quicksketch** [comment]
>  I can build another outline of user documentation as a proposal for you to approve again, and then use that to decide if a dedicated subdomain is warranted. 

That sounds amazing. Thanks @docwilmot.

**Comment by Graham-72** [comment]
I like very much what you have achieved with 'Developer Documentation' though I would like to see the addition of issue or version numbers and dates so that we can see if a document has been updated.

Also, a very user-friendly search facility is important. I find the one on drupal.org overwhelming at times and it becomes easier to use Google.

For user documentation, please could we somehow structure it in layers, with a beginners 'introductory' layer, then an 'experienced user' layer, and finally an 'advanced' layer. So often guide books are written by experts who forget how daunting it can be for a newbie.

**Comment by jenlampton** [comment]
@Graham-72 really great feedback, thank you!

We will be structuring things in layers just by the nature of having a the "Handbook" user guide (very high level, newbie stuff) and also this deeper how-to documentation section @docwilmot is outlining now.  There's a lot of gray between experienced and advanced, but considering we don't have any of it yet maybe thinking about ways to divide that are premature?

I like the idea of adding version information (but again that's not something that's relevant until we have a backdrop 2.0).  We have been thinking about how we could possibly leverage the translation system to translate 1.x content into 2.x content as needed.  This would allow easy integration with search. 

We were actually just talking about search - do people really use on-site search boxes anymore?  I was just wondering because I, too, have been trained to use google for searching drupal.org, and also anything else I'm looking for answers for these days. It would be interesting to learn the habbits of the average site visitor, and compare that to the backdrop demographic.

**Comment by Graham-72** [comment]
Hi @jenlampton thanks for your response. If I may just amplify my thoughts. About the user handbook, I was impressed but a bit daunted by the list from @docwilmot and I thought, although early days, it might be useful to have a structure that recognises different levels of ability. I should like to contribute to consideration of what the beginner really needs to know, and also write some of it if I can help.

About version information, I guess I used the wrong word 'version' because I was thinking more about revisions to a document. For example I was reading "Converting modules to Backdrop from Drupal 7" again just recently and thinking that it had changed (improved!) since my last viewing, and I would have liked to see some sort of issue number and date.

Regarding search, if I have an instruction manual for a product it is usually a pdf and hopefully has a good index, but I can always do a pdf search within the document for a particular word. The other day I was wanting to see what Backdrop documentation has to say about 'uninstall', there are plenty of answers to the search which includes all the api specifications. We need to be able to search just the user handbook, for example. All in good time of course, but worth thinking about.

**Comment by docwilmot** [comment]
+1 to everything @Graham-72 has said. Drupal search is well nigh useless. You search for 'Webform' and the actual webform module doesnt come up in the first 3 pages of search results. But yes the site search is good for limiting search results (just modules, or just forums).

> version information ... not something that's relevant until we have a backdrop 2.0

I'd like to suggest the reason that Drupal docs are such a wonderful mess might be that the team didnt plan for growth and got too busy by Drupal version 2.0. We should definitely plan now for how we want docs to grow, and we should start now, by publishing everything as version 1.x.x. See http://symfony.com/doc/current/book/controller.html (version and language info attached to every document, nice!). Something like that. Please dont accept that we should wait till version 2.0. That to me would be a mistake.

**Comment by docwilmot** [comment]
Moved response to https://github.com/backdrop-ops/backdropcms.org/issues/55

**Comment by quicksketch** [comment]
Thanks @docwilmot. This really should be in the backdropcms.org queue rather than here in the core queue, so let's continue in your new issue.
