### ISSUE TITLE
Fix mime type for site favicon

### ISSUE THREAD

**Issue by findlabnet** [backdrop/backdrop-issues#814]
core/includes/common.inc - s.340  
instead 'site_favicon_mime'  should be 'site_favicon_mimetype'

**Comment by findlabnet** [comment]
Pull Request #776 Fix mime type for site favicon #814

**Comment by findlabnet** [comment]
Pull Request #776 Fix mime type for site favicon #814

**Comment by quicksketch** [comment]
Thanks for finding and reporting this bug @findlabnet! Note because our issue repository and code repository are separate (due to GitHub's loose permissions system), just issue numbers isn't enough to cross-link between issues and PRs. Pasting in the full URL is what I do usually to cross-link. Current PR is at https://github.com/backdrop/backdrop/pull/776 for reference.

The PR needs a slight adjustment to the commit message.

**Comment by quicksketch** [comment]
Thanks @findlabnet! This will be in 1.0.5.

**Comment by quicksketch** [comment]
@findlabnet We sent you a shout-out on Twitter. :wink:

https://twitter.com/backdropcms/status/577742491115503617

Thanks again!

**Comment by findlabnet** [comment]
So many thanks for just 4 chars! ;-) But many thanks to you for help on this way!
