### ISSUE TITLE
Fix failing Breadcrumb test in menut.test line ~ 1072 - 1073

### ISSUE THREAD

**Issue by serundeputy** [backdrop/backdrop-issues#825]
breadcrumb test failing in: menu.test on about line 1072.
```bash
---- Menu: Breadcrumbs (MenuBreadcrumbTestCase) ----
Status    Group      Filename          Line Function                            
--------------------------------------------------------------------------------
Fail      Other      menu.test         1072 MenuBreadcrumbTestCase->testBreadCr
    Breadcrumb Home » Administration » Structure » Content types » Article
    found on http://localhost/admin/structure/types/manage/article/delete.
```

**Comment by quicksketch** [comment]
To elaborate here, we previously had set `admin/structure/types/manage/%node_type/delete` to be a `MENU_NORMAL_ITEM`, which in turn made it so that the breadcrumbs functioned but the "Delete" links for content types showed up in the Admin Bar (which was the point of the previous issue at https://github.com/backdrop/backdrop-issues/issues/577).

What we need here is the ability to make it so that an item shows up in the breadcrumb, but not in the admin menu tree.

**Comment by quicksketch** [comment]
Huh, upon further testing, we already have this functionality. In `menu.inc`, we have the `MENU_VISIBLE_IN_BREADCRUMB` bit flag, which is separate from `MENU_VISIBLE_IN_TREE`. The normal item is just a combination of the two flags:

```
define('MENU_NORMAL_ITEM', MENU_VISIBLE_IN_TREE | MENU_VISIBLE_IN_BREADCRUMB);
```

So it looks to me like we could solve the original problem in https://github.com/backdrop/backdrop-issues/issues/577 just by using this flag instead. Let's return back to that other issue and try to fix this all at once.

**Comment by quicksketch** [comment]
We don't need this now that we're resolving this directly in https://github.com/backdrop/backdrop-issues/issues/577.
