### ISSUE TITLE
#element_validate not working in block configure, if form is in include file.

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#828]
menu_block.module has 

```
function menu_block_block_configure($delta = '', $settings = array()) {
  module_load_include('inc', 'menu_block', 'menu_block.admin');
  return _menu_block_block_configure($delta, $settings);
}
```

and the _menu_block_block_configure() form itself has:

```
  $form['follow'] = array(
    '#type' => 'checkbox',
    ...
    '#element_validate' => array('menu_block_configure_form_follow_validate'),
  );
```

When you try to save the configuration form dialogue ('Add block'), the form doesnt submit (ajax spinner pops up, goes away). PHP logs say `Call to undefined function menu_block_configure_form_follow_validate()`. 

If this is tried with javascript disabled, there is no error, everything works fine.

I've tried putting `menu_block_configure_form_follow_validate()` in `menu_block.module`, and that gets rid of the `Call to undefined function menu_block_configure_form_follow_validate()` but instead I get `Undefined index: follow'. But if you close the dialogue, and refresh the page, the block is actually added where you wanted it!

Any help would be apprecuiated.

**Comment by quicksketch** [comment]
Hi @docwilmot! Thanks again for filing an issue about the troubles with block forms. It's good that we're making a record of these problems.

Normally, if your form modifications required an included file, you'd use [`form_load_include()`](https://api.backdropcms.org/api/backdrop/core!includes!form.inc/function/form_load_include/1). That ensures that the included file is loaded even if the form is pulled out of the form tempstore instead of rebuilding the form from scratch.

Unfortunately, `$form_state` isn't around at this point, so we can't use that function.

Hm. To solve this problem, we may need to explicitly tell Form API to rebuild this form in Layout module.

We might try just putting the following at the top of `layout_block_configure_form()`:

```php
$form_state['rebuild'] = TRUE;
```

That will force Form API to rebuild the form every time it's needed, instead of loading it from the form tempstore. I think this might be okay because Layout module separately stores in-progress changes, and it doesn't rely on Backdrop's built-in form state anyway.

**Comment by docwilmot** [comment]
I 'fixed' this by putting the validate function in menu_block.module and adding the block_settings key to `$form_state['values']`:
```
function menu_block_configure_form_follow_validate($element, &$form_state) {
  if ($form_state['values']['block_settings']['follow'] && !empty($form_state['values']['block_settings']['follow_parent'])) {
    $form_state['values']['block_settings']['follow'] = $form_state['values']['block_settings']['follow_parent'];
  }
}
```
So far this works. Any thoughts?

**Comment by quicksketch** [comment]
Moving the function will definitely solve the inclusion problem; not ideal but it will do.

> and adding the ['block_settings'] key to $form_state['values']:

Normally I'd suggest trying to make this cleaner by using `form_set_value($element, $new_value)`, so you wouldn't have to worry about the position in `$form_state['values']`. However, since you're pulling from one field and setting the value of another field, you're going to need to dig into `$form_state['values']` anyway. I think this approach will work just fine.

**Comment by joelpittet** [comment]
To close the loop, adding this patch for Drupal Core: https://www.drupal.org/node/1596244
