### ISSUE TITLE
Cant have block titles as links

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#832]
Porting the Menu Block module. Working port [on my GitHub page](https://github.com/docwilmot/menu_block). Everything looks working well except linked titles come out as plain text.
I've tracked it down to line 236 of layout.theme.inc
```
  $variables['title'] = !empty($content->title) ? check_plain($content->title) : '';
```
Any way around this?

**Comment by quicksketch** [comment]
This could be done using `hook_preprocess_block()` I believe, where you could modify the `$variables['title']` variable. However, using an HTML string for the title is not something that is normally possible in Backdrop (in Drupal either I don't think). It may be a candidate for feature-reduction instead of attempting to provide it.

From the looks of things, menu_block.module is doing a lot of crazy things in its implementation, like the custom block wrapper and renderable array for a title. Reducing the complexity might be a good thing for this module.

**Comment by docwilmot** [comment]
> Reducing complexity

Sounds good. Will work with that.

**Comment by quicksketch** [comment]
:+1:
