### ISSUE TITLE
Display jQuery and jQuery UI versions in the Status report page.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#846]
We have entries for other components like the web server, the database and PHP. jQuery Update offers this. They just seem to have overlooked making sure that the entry is listed in the correct alphabetical order and always place it last: https://www.drupal.org/node/2465275

**Comment by quicksketch** [comment]
jQuery isn't quite the same as these other items, as MySQL, web server, and PHP versions are all independent of the code base. But in any case, I agree it would be helpful because site builders and themers frequently need to know the version of jQuery when integrating with various 3rd-party libraries.

**Comment by Dinornis** [comment]
Closing and marking as fixed.
jQuery version included in status report as of 1.6.1 (https://github.com/backdrop/backdrop-issues/issues/2492#issuecomment-279284759)

**Comment by klonos** [comment]
Another duplicate of my own issues. I'm getting old and losing my touch it seems. Tsk tsk tsk.
