### ISSUE TITLE
Procedural entity handing functions need to be updated

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#848]
entity_uri and entity_label need to be updated, perhaps others too.

1) These functions are no longer deprecated, comments in the docblock need to be removed
~~2) Remove $entity_type, the first parameter, and create change records for these changes
3) Check the core codebase and make sure no calls to these functions pass in $entity_type~~

UPDATE: We just need to do 1) for the current release. 2) and 3) should be in 2.x.

**Comment by quicksketch** [comment]
For the 1.x release, I'd suggest just doing 1 and not 2 or 3. We can't change the API of these functions in the 1.x release.

So the shortened task of this issue is just remove the `@deprecated` tags from the functions.

Some history for explanation: We had both of these functions in D7 see:

- https://api.drupal.org/api/drupal/includes!common.inc/function/entity_uri/7
- https://api.drupal.org/api/drupal/includes!common.inc/function/entity_label/7

The signatures were left the same to maintain compatibility (so changing the parameters would eliminate a good portion of the reason for their existence). In D7, we needed to pass in the entity type because the entity didn't know what type it was. Now we have `$entity->entityType()`, so the extra parameter isn't necessary. Maybe we remove it in 2.x?

**Comment by jenlampton** [comment]
Sounds good.  Let's do 1 and then tag this issue for 2.x (or should we open a new one?)

**Comment by klonos** [comment]
>...or should we open a new issue now

Done! :wink:

**Comment by quicksketch** [comment]
Thanks @BWPanda for knocking off this last item. :+1:
