### ISSUE TITLE
Is config() cached?

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#856]
Can I use `config_` functions as freely as I used to use `variable_` functions? I was [designing a module](https://github.com/backdrop-contrib/joyride) which frequently used `config_get_names_with_prefix()` followed by `config()` and wondered if I should add static caching.
I dont see caching with `config_get_names_with_prefix()`. How about `config()` though?

**Comment by quicksketch** [comment]
Generally, calls to config() should be considered equivalent to doing a database query. That is, it's going to be hitting the disk. Configuration is considered extremely low-level by Backdrop, it doesn't require cache back-ends or even the database. `config_get_names_with_prefix()` is similarly not cached and does a directory scan when called.

If you're reading out a list of config files frequently, you should build an API around accessing those items just like you would for database queries. That's why things like `node_type_get_types()` and `layout_load_multiple()` still implement their own caching (both static memory cache and database cache).

There's one exception to this rule, and that's configuration files like `system.core.json` that include a special indicator at the top of the config file:

```
{
    "_config_name": "system.performance",
    "_config_static": true,
```

This `"_config_static"` flag indicates that the `config()` function should cache this file in memory after it is read. So it will be read at most once per request. Otherwise, each and every call to `config()` (or `config_get()`) will be reading the file from disk each time.

As a general rule, if you're using a `config_get()` to store settings in a single small file (e.g. a single settings form for your module), it's a good idea to set `_config_static` in your config file. If you're loading a set of config files frequently, you should make your own static variable and cache entry like you would for large number of database queries.

**Comment by docwilmot** [comment]
thanks
