### ISSUE TITLE
Fix or (preferred) remove extra meta tags

### ISSUE THREAD

**Issue by findlabnet** [backdrop/backdrop-issues#865]
In core/modules/node/node.module and core/modules/taxonomy/taxonomy.pages.inc we have calls of backdrop_add_html_head_link() put "canonical" and "shortlink" meta tags.
But canonical links: 
- need only for the duplicated pages (now for any node or taxonomy page);
- "href" will be absolute path (not relative as now) .
Use backdor path (e.g "node/123") as "href" for "shortlink"? AFAIK "shortlink" it is URL shortener service generated URL. 
IMHO we need just remove both.

**Comment by quicksketch** [comment]
Hi @findlabnet! Thanks for opening this issue. Let's go through the two issues one at a time:

> need only for the duplicated pages (now for any node or taxonomy page);

In Backdrop, it's already possible to view a path-aliased node in at least 6 places. Say the alias was set to "contact" for node 1:

- `/contact`
- `/?q=contact`
- `index.php/?q=contact`
- `/node/1`
- `?q=node/1`
- `index.php/?q=node/1`

In addition to that, there may also be reasons for tacking on additional query strings on a per-site basis, e.g. `contact?category=help`, but the content of the page is unchanged. Search engines need to be informed that the additional parameters do not affect the content significantly, and that the "canonical" URL is still just `contact`.

Lastly, it's also possible to assign multiple aliases to the same path, but only one of them should be the "canonical" version. I'm not sure this should be allowed personally, but it's been the case for as long as aliases have existed in Drupal.

Google's docs on canonical for reference: http://googlewebmastercentral.blogspot.com/2009/02/specify-your-canonical.html

So for "canonical", it looks as though it would be a good idea to keep this meta tag in place to prevent penalties from search engines if they were to encounter duplicate versions of the page.

> Use backdor path (e.g "node/123") as "href" for "shortlink"? AFAIK "shortlink" it is URL shortener service generated URL. 

I think you're right that we're not using shortlink correctly. We *could* also use `node/x` as the "shortlink", but I think shortlinks are intended to be redirects (e.g. a `bit.ly` link) rather than alternative URLs. There are lots of examples of shortlink given at http://microformats.org/wiki/rel-shortlink. I think it would be best to provide shortlink support through a contrib module (e.g. https://www.drupal.org/project/shorten).

**Comment by findlabnet** [comment]
Thank you for detailed answer, @quicksketch !
 You're right, 6 (or more) "shades" of path-aliased node is a good reason to keep "canonical" in place. 
But about absolute path - also by Google: https://support.google.com/webmasters/answer/139066?hl=en#2 
>Avoid errors: use absolute paths rather than relative paths with the rel="canonical" link element.
>
>Use this structure:  https://www.example.com/dresses/green/greendresss.html
>Not this structure: /dresses/green/greendress.html).

If we decide to use absolute path in "canonical" - only one attribute need to be changed in `url` function's parameters.

Second: if I understand correctly, nothing prevents remove calls for "shortlink" meta from core in favor future contribs.

**Comment by quicksketch** [comment]
> If we decide to use absolute path in "canonical" - only one attribute need to be changed in url function's parameters.

You're right! We should be using absolute URLs, definitely. Do you have any ideas on how we should handle HTTP vs. HTTPS? I believe Backdrop will use whichever one you're currently on, resulting in two "canonical" URLs. I've had a lot of unfortunate experience with Facebook and Pinterest considering HTTP and HTTPS "different" URLs as far as indexing likes, pins, etc.

> Second: if I understand correctly, nothing prevents remove calls for "shortlink" meta from core in favor future contribs. 

Correct. Let's kill the shortlink meta tag. My understanding is that we're not using it correctly (and can't easily do so in core), so it should be left to contrib.

**Comment by findlabnet** [comment]
>how we should handle HTTP vs. HTTPS?

To avoid  two "canonical" URLs we can define field in settings for "canonicals base URL" - same way it work in Drupal's contribs such as  "nodewords". Additionally, sitemap.xml must contain only one from two concurrent in protocols links.
And back to subject - Shall I prepare PR?

**Comment by quicksketch** [comment]
> To avoid two "canonical" URLs we can define field in settings for "canonicals base URL" - same way it work in Drupal's contribs such as "nodewords"

Any idea where we would put such a setting? It seems relatively related to Clean URLs, but currently that has its own path. Maybe we could rename the "clean-urls" path to just be "URL handling" (or something)?

>  And back to subject - Shall I prepare PR?

Sure, let's do the easy part if you're up for it (removing shortlink). But I'd like to figure out where we're headed with handling the canonical meta tag. A setting sounds fine if it comes down to it.

**Comment by findlabnet** [comment]
You right, under renamed to "URL handling" menu item we can have additional checkbox  titled "Use HTTPS for canonical URLs" - and when checked - add "https" parameter to `url` call. 
If this scenario looks acceptable, during weekend I can prepare complex solution for PR.

**Comment by quicksketch** [comment]
Sounds great!

**Comment by quicksketch** [comment]
> Lastly, it's also possible to assign multiple aliases to the same path, but only one of them should be the "canonical" version. I'm not sure this should be allowed personally, but it's been the case for as long as aliases have existed in Drupal.

This issue got me thinking about other "URL handling" options we could add. I filed a new issue to followup after this one: https://github.com/backdrop/backdrop-issues/issues/868

**Comment by findlabnet** [comment]
Created PR #817

**Comment by quicksketch** [comment]
Thanks @findlabnet! The PR looks great! I added a few items of feedback on the PR.

This issue is also slightly related to https://github.com/backdrop/backdrop-issues/issues/635, which is currently unresolved in terms of what solution we should use there. I'm all for iterating as we progress though. It looks like this is going to get finished shortly, afterwards we may move this menu item again if that issue comes to resolution.

**Comment by findlabnet** [comment]
https://github.com/backdrop/backdrop/pull/817 replaced with https://github.com/backdrop/backdrop/pull/822

**Comment by quicksketch** [comment]
Looking great! Instead of replacing your PRs, you can force push to your existing branch to update the PR with any changes.

The new PR looks great to me. It's only missing an update hook to set the default value of the new canonical_secure option. The new option should be added in system.install `system_update_1037()`.

**Comment by findlabnet** [comment]
Done and travis-ed. Thank you for patience.

**Comment by quicksketch** [comment]
Thanks to you @findlabnet! This is looking great. Tests are passing and it looks like the update runs well. Thanks for optimizing the submit handler config saving as well.

![url-handling](https://cloud.githubusercontent.com/assets/100206/7290474/6fb7dfa4-e934-11e4-8cc0-c189b6bc5fdb.png)


The only problem I encountered during testing is that now Admin Menu shows *both* items in the admin bar. I'm not sure why this is, as a `MENU_CALLBACK` shouldn't be shown in the menu tree. We had a similar issue recently with [Removing Delete links from the Admin Bar](https://github.com/backdrop/backdrop-issues/issues/577). We had a fix in there that skipped MENU_CALLBACKs, but ultimately found it was unnecessary to solve the problem at hand. We might need to introduce that change to prevent the Clean URLs menu item from showing up here.

**Comment by findlabnet** [comment]
After short investigation I've found this as an existing menu item under "management "(or "Administration menu") - `admin/structure/menu/manage/management`. It was on only one of four my test installations and I found it after update core via replacing "core" directory. DB tables `menu_links` and `cache_menu` have records for it (should be removed when renamed?). 
Maybe I need check menu clean-up on update?
When I do clean new install such item doesn't exist.

**Comment by quicksketch** [comment]
>  When I do clean new install such item doesn't exist. 

Ah! In that case, maybe we should do a deletion from the `menu_links` table in our hook_update()? The caches are already cleared and the menu rebuilt after an update.php run, so I think we just need to delete that link from the table.

**Comment by findlabnet** [comment]
>maybe we should do a deletion from the `menu_links` table in our hook_update()?

Added to system_update_1037()

**Comment by quicksketch** [comment]
Thanks @findlabnet! I merged this manually to optimize the update hook. There's no need for a separate SELECT and DELETE statement when you could just put a condition on the DELETE statement.

This was merged in https://github.com/backdrop/backdrop/commit/f1024b70ce62b3514eaa37ae77a304f6c05e2667. Thanks for your work on this. It's a small feature but opens the door to additional exciting options such as https://github.com/backdrop/backdrop-issues/issues/868.

As a new feature, this will be in the 1.1.0 version, due May 15.
