### ISSUE TITLE
Add "group" functionality to core

### ISSUE THREAD

**Issue by philippejadin** [backdrop/backdrop-issues#867]
Of course the first idea that comes to mind is "just port organic group". But I think that backdrop can provide something new here, by providing a base "group" feature in core that would be extended by modules.
- most sme's, associations, target users of backdrop need a group feature
- belonging to a group is a facet of content and other site features (like menu, views, blocks). The same as internationalization and revisions. It hurts badly Drupal to have this "group" facet out of core.
- I'm pretty sure it's possible to do something simpler in backdrop core than the current og (read this slide : https://youtu.be/XglUUroifsg?t=29s :-) )

(speaking for me) : 
- I don't need _any_ entity type as group, one is enough
- I don't want to add some weird field reference to my content, let the group module handle that for everything (like the built in internationalization & revisioning, just check a box and it works)
- I'd like built-in support for per-group views (with automatic filtering of content), per group contact & web forms, per group blocks and layouts, per group permissions. Only a core initiative will provide that in a meaningful and easy to use way.

(and sorry if it reads like a rant, it is actually trying not to be one)

**Comment by quicksketch** [comment]
Hi @philippejadin, thanks for taking the time to write this all down.

We're trying to bring some focus to the core development cycle (as in https://backdropcms.org/roadmap), so this is the sort of thing that we could consider for a minor release or (more likely) the 2.0.0 release, as I expect this would require some API changes.

However from the current description, it's a bit too nebulous to make a call. It does sound like a pretty extensive expansion of complexity that we'd have to support and test, which makes me feel like it might not be the best fit for Backdrop based on our project goals. For most sites, the need for access control and permissions is covered by the user role system. The capabilities of OG provide support for most of the remaining sites, but what you've said is that you want something *easier* than OG but at the same time *more comprehensive*. That's not an easy thing to accomplish.

If this can be justified as a feature that most sites will need and can be shown to be simple to implement and understand, then we can try to schedule it for a release, but honestly this sounds like it would be a sprawling long-term project.

**Comment by sgarcata** [comment]
Maybe the new Group module for Drupal 8 combined with Rules  and messaging would work.

**Comment by klonos** [comment]
@sgarcata are you referring to https://www.drupal.org/project/group ? ...if so, then that project does have a D7 version available. Since Backdrop is API-compatible with D7, the 7.x version could be ported (Rules are already ported: https://backdropcms.org/project/rules).

**Comment by sgarcata** [comment]
That is good to hear... to be honest I'd forgotten that there was a D7 version of Group.
I'm afraid I don't have the knowledge to port over... I could change the s/w reference as in Nate Haug's video, but I wouldn't be able to do the work to fix up the code when/if it doesn't work straight away. I'm co-developing a collaboration web site for a non-profit group I'm part of and we need a workgroup space for team work in between meetings. We were trying to get up to speed with D8, but running into too much headwinds... I'm thrilled to have come across BackdropCMS. I'll give it a go once I get a little more familiar with BD-CMS - I don't even know D7 very well yet and it has been over 20 years since I did much coding other than dabbling in C# a little. Thanks for getting back so quickly.

**Comment by philippejadin** [comment]
<shameless plug>
In the meantime (time flies, ha!) I built a groupware software for citizen which might help : https://agorakit.org/en/
</end>

I was a bit worried of the complexity with the group system in drupal, and after implementing a drupal based solution, I ended up going the custom way, laravel based.

Hope that helps someone and that it's not too unrelated

**Comment by sgarcata** [comment]
Wow!! So generous of you Philippe... I'll have a look at it once I figure out how to install it in my domain space to try it out. My group is called Arcata CERT (CERT = Community Emergency Response Team) This could be the answer for our Intranet needs. We will also have a public-facing site to dispense Emergency prep info (localized) to the general public. We are way north in California... right near the triple junction of faults and plates that are colliding and subducting continuously so big threat of earthquakes. Here's a link to another CERT group in CA: http://www.cert-la.com/ - this is just a public-facing web site for Los Angeles, CA. We'll be doing this plus the intranet/work group part for the certified members.
Thank you so very much. Merci beaucoup! C'est tres belle d'vous. (Excuse the terrible grammar... it's been 48 years since I lived in a french speaking country).

**Comment by oadaeh** [comment]
For anyone considering porting the Group module, it relies heavily on the Entity API module. I started porting it to Backdrop some time ago (maybe a year) and quickly ran into road blocks with missing Entity API functionality the Group module used.
That being said, since that time, @docwilmot created the Entity Plus module (https://backdropcms.org/project/entity_plus) that may fill in the missing gaps. I have not looked into it yet, being currently rather busy trying to reinvent myself.

**Comment by jenlampton** [comment]
I don't think group functionality meets the 80% requirement for a core feature, this is probably best left to contrib. On the upside, we now have a version of organic groups for contrib! https://github.com/backdrop-contrib/og
