### ISSUE TITLE
Content types owned by modules other than "node" have incorrect "Delete" link

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#871]
After installing [Project module](https://github.com/backdrop-contrib/project) I wanted to delete the "Project" content type it came with to set up my own different types. However, I found that on `admin/structure/types`, the link to Delete the "Project" content type actually was linking to the form to delete the Page content type! This obviously could cause some accidental data loss if the user were not to read the confirmation form.

My guess is that this behavior is caused by project module specifying a "module" in the content type when it creates it hook_install(). This is supposed to prevent the content type from being renamed, but looks like it's also having some odd behavior when deleting the content type.

**Comment by BWPanda** [comment]
So this issue is most definitely a bug, though not what @quicksketch thought.

When `node` module creates the operations links for each node type (e.g. configure, manage fields, delete, etc.), it doesn't initialise/reset the `$links` array (this is the bug). Therefore, when it loops from one node type to the next, all the links from the previous node type are still there. This isn't generally an issue as the new node type just overwrites the links from the previous one, but it popped up in @quicksketch's use case above as the Project module's `module` value is set to `project` (whereas most other content type modules are set to `node`). The `delete` link is a bit unique in that it's only added if the `module == node`. The Project module therefore shouldn't have a delete link for that reason, but because of this bug the delete link for the previous node type (in my case 'Post') is still there, so that's why the Project module's `delete` link links to a different node type.

My very simple [PR](https://github.com/backdrop/backdrop/pull/2843) fixes this.

**Comment by klonos** [comment]
Thanks for figuring this one out @BWPanda 👍 RTBC!

**Comment by quicksketch** [comment]
Ha! Wow I can't believe how trivial that fix is. Thanks @BWPanda! Merged into 1.x and 1.13.x.
