### ISSUE TITLE
Ship Backdrop with a 'Blog' profile

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#881]
From https://github.com/backdrop-ops/backdropcms.org/issues/58#issuecomment-94113280

Response from @quicksketch:

> I think we could meet the need of creating a "blog" content type by simply renaming "Article" to "Post" in the default profile, as suggested in backdrop/backdrop-issues#742. The only thing remaining from the first tutorial would be creating a block of recent posts (easy enough). The second tutorial is equally simple only it describes making a blog section instead of using the homepage as the blog. That sounds like one possible option as well (bundle a default front page layout instead of using the blog as the homepage).
> 
> There just don't seem to be enough steps to warrant a different profile. I think the out-of-box experience should be a blog, because almost all sites have one anyway.

Reasonable response, and I am not pushing, but to explain my motivation: The current normal profile is more a Swiss-Army-Knife approach which gives you a relatively non-discrete 'website' which has to be modified to suit whatever purpose you have in mind, regardless. Its a list of posts, really.

My thought was to have a profile that completely, undoubtedly says 'Blog', for those persons who want nothing but that. Install, click/select the blog checkbox, _voila!_: blog list, blog archive block, 'About me' page, pathauto (eventually) formatted to say `/blog/<date>/1`, the whole thing. 

Thoughts anyone?

**Comment by Graham-72** [comment]
I think that having it set up as a ready-to-use blog is an excellent proposal.

However, it does remind me of my early frustration with Wordpress in the days when it was primarily a blog and it was hard, at first, to understand how to get conventional pages. But I am sure we are well on top of that one.

Can we start with a simple question something like "Is your initial aim to start your own blog or to create pages for a website?"

**Comment by jenlampton** [comment]
I also agree that a single-user blog profile would be a great one to start with, and makes sense if we want to compete with WP. :+1:

**Comment by cellear** [comment]
Would this be a good time to ponder what are some of the broad use-cases that Backdrop will be (or even already is) suited for?  

The "Audience" statement at https://backdropcms.org/philosophy identifies 4 targets.

>Backdrop CMS is for the small to medium sized business, non-profits, educational institutions, and companies or organizations who are delivering comprehensive websites on a budget.

- small to medium sized business
- non-profits
- educational institutions
- companies/organizations on a budget.
- ...and since we're contemplating a blog profile, it seems reasonable to add "individuals" to this list.

So...what do we think these five groups will actually be making?

1. Single-user blog (with commenting)
2. Company/organization's "presence" page - Products, services, about, contact
3. Multi-user online community
4. Artist or photographer's gallery 
5. Online store
6. News
7. Reference/guides/manuals

What's missing?  Has this already been covered?

**Comment by biolithic** [comment]
Hey Luke,nice to see you.
It's always good to think about these things as people review it for the
release of 1.1, though I'm not in a position in the company(s) to make
decisions on Backdrop.

I'm not too concerned that Heroku can't run Drupal or Magento...because
it's always there when I need to run Node+Angular through Yeoman and that's
all.
I'm not too concerned with the SEO or linking of Angular, because I can
just run Drupal to do that.
...etc...

Something like this might be of interest:
http://www.reddit.com/r/backdrop/comments/360046/starting_a_new_blog

An initial market might be Youtube content makers like:
https://socialblade.com/youtube/user/getmovies
https://socialblade.com/youtube/user/machinima
https://socialblade.com/youtube/user/smosh

who have content, cash, a brand, but not exactly the most cohesive or
exciting web experiences or blue-chip/enterprise profile when I've seen,
but I haven't been there in months.

Also, I wish we knew someone with expertise in making Youtube modules for
Drupal/Backdrop ;)

Sorry to hijack this thread, but I think the "blog" as people think of it
is kinda played out.  You have Drupal 7, Ghost, Wordpress, Tumblr, Medium,
social networks, Weebly/Wix/
SquareSpace,, Blogger/Blogspot, etc... -- not too much you can innovate
over these in a short amount of time in that your main draw is an
out-of-box blog.  Not saying that we shouldn't have one, I just feel like
this space is already kinda full where Backdrop's "killer app" or strength
might lie elsewhere like organization/aggregation or something else.

**Comment by docwilmot** [comment]
to remind me: https://github.com/backdrop/backdrop-issues/issues/239

**Comment by jenlampton** [comment]
> Also, I wish we knew someone with expertise in making Youtube modules for
Drupal/Backdrop ;)

:+1: 

@cellear, I don't think Backdrop is targeting a single-user blog persona, those people likely don't have a nee for structured data and may be better served by WP. 

What I had in mind for a "blog" was actually a company blog (many users, plus comments, but one blog as opposed to each person having their own) also equivalent: a "news" or "press release" section.

That said, the single-user-plus-comments type blog should be something Backdrop can do it in it's sleep, so why not set it up and ship it? If we want to compete with WP long term this is a problem that will need solving, and well.

**Comment by behindthepage** [comment]
I think this would be serviced with a module called Blog. 
Which has the following config files:

1. views.view.news.json - View consisting of a list of articles with newest at top. A standard blog page with url of /news
2. views.view.archives.json - A page of articles filtered by year and month and a block with a list of years and months. 
3. views.view.tags.json - A block of tags linked to their taxonomy page
4. layout.layout.news.json - A layout for /news with the archive and tags blocks in the right column.

Enable the module and Voila you have a blog page.

Regards
Geoff

**Comment by docwilmot** [comment]
That still leaves a weakness: a new user must know what a 'module' is, know how to install it, what a 'layout' is etc. With a profile: install, done.

But working with the project_browser module, I'm thinking that a "packager" module could be a new concept if project_browser was in core. A packager that lists dependencies (automatically downloaded) including other modules and themes and layouts, and configure files, and code to sort them all out. 

Dreaming, but I think it is a good dream. Wish I had the skill to do it.

**Comment by behindthepage** [comment]
I would envisage the blog module is in core so it just needs to be enabled.
The config files are copied into the sites config folder automatically when the module is enabled so it is one step process.

Here is some code to check out
https://github.com/behindthepage/blog

Of course these config files could be shipped with core but i like a module for a one click out of the box solution. 

Regards 
Geoff

**Comment by jenlampton** [comment]
> a new user must know what a 'module' is, know how to install it, what a 'layout' is etc. With a profile: install, done.

I disagree with this. I think it's a much bigger hurdle for a new user to understand what a profile is than a module, and the consequences are much more dire.  

If you choose wrong during the profile selection phase (during install), the only recourse is to throw away the site and start over. However, if you install the standard profile and play around, you can enable / disable modules, play with layouts, and enable/disable/edit views to your hearts content without needing to start all over.

I think I'm leaning towards a block package. (modules, themes, layouts + config). Once we figure out how to do that.  Related
* https://github.com/backdrop/backdrop-issues/issues/1238
* https://github.com/backdrop/backdrop-issues/issues/1175
* https://github.com/backdrop/backdrop-issues/issues/99
