### ISSUE TITLE
Add three core classes for use on form-submit buttons

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#882]
There are several places in core where we want fancy submit buttons.  In order to have them, we need a class. 

1) add the ~~`dangerous`~~ `danger` class to indicate when clicking a certain button will do something dangerous. All confirm forms, by their nature, do something dangerous.  The submit button on any confirm form should have the `danger` class. There should be no other examples of dangerous buttons.  If there are, a confirm form needs to be added.

2) add the `primary` class to help users differentiate between the most commonly intended action when a form has more than one button that will submit that form.  For example, the comment form has both a "Save" button and a "Preview" button. The "Save" button should be indicated as primary.  Other good examples of forms with multiple submit buttons are the Views UI, and the Layouts UI.

3) add the `secondary` class to other buttons in an `actions` element that are not the primary button.

An additional part of this ticket will involve inspecting all the forms in Backdrop and evaluating whether we need a primary class added. 

Part of the larger meta at https://github.com/backdrop/backdrop-issues/issues/736.

**Comment by quicksketch** [comment]
I think to match Bootstrap's semi-universal name, we could shorten "dangerous" to just "danger": http://getbootstrap.com/components/#btn-dropdowns-single

However, unlike bootstrap, we don't have the convention of abbreviations, so instead of "btn-danger" we'll use "button-danger". We'll also need a secondary button style to match the mocks (and I think this is a good idea as well): https://github.com/backdrop/backdrop-issues/issues/883#issuecomment-98203847. So the new classes would be:

- button-primary
- button-secondary
- button-danger

**Comment by quicksketch** [comment]
I filed a PR at https://github.com/backdrop/backdrop/issues/875 that includes all these classes and the styling from https://github.com/backdrop/backdrop-issues/issues/883#issuecomment-98203847.

Here they are in action:
Primary/secondary buttons:
![button-node](https://cloud.githubusercontent.com/assets/100206/7544144/cf8763e6-f587-11e4-8099-a1bbdd2e35fc.png)
![button-views](https://cloud.githubusercontent.com/assets/100206/7544145/cf8d06b6-f587-11e4-8bf1-5cef0c7e9127.png)
Confirm ('danger') buttons:
![button-confirm](https://cloud.githubusercontent.com/assets/100206/7544143/cf83042c-f587-11e4-9a93-58dd253b5fc2.png)
Normal buttons (unchanged):
![button-upload](https://cloud.githubusercontent.com/assets/100206/7544146/cf923f78-f587-11e4-81bc-7e47597c04b7.png)
Bulk operations:
![button-bulk-ops](https://cloud.githubusercontent.com/assets/100206/7544234/8733969a-f588-11e4-851b-ed8a41875a27.png)
In a dialog:
![button-dialog](https://cloud.githubusercontent.com/assets/100206/7544192/3db2b9f6-f588-11e4-98aa-03fc40d354e1.png)

The "primary" button will be assumed to be the first button in a `#type = 'actions'` element, unless another button specifically has the class "button-primary" or "button-danger" applied. All other buttons in the actions wrapper are assigned "button-secondary". The styling of all other generic buttons remains unchanged, only the buttons in actions wrappers are affected.

A nice side-effect of this is that it makes it much easier to see where actions wrappers are missing, and gives developers a good incentive to make sure they use the actions wrapper where appropriate. This PR adds the wrapper to the Views creation form, but removes it from the bulk operations form for example.

**Comment by jenlampton** [comment]
In general I think these look fabulous.   huge improvement over what we have now!

I do think we should open a UX follow-up that focuses on how to tell which button is active.

**Comment by quicksketch** [comment]
Great, merged in https://github.com/backdrop/backdrop/pull/875. We're really close to complete implementation!

**Comment by klonos** [comment]
Just a quick question: wouldn't it be better to have two classes added instead of a single two-word class? I mean instead of:

.button-primary
.button-secondary
.button-danger

have it be

.button .primary
.button .secondary
.button .danger

This way, we can target all buttons in css by ```.button``` instead of ```.button .primary, button .secondary, .button .danger``` while still being able for example to use ```.button.primary``` instead of ```.button-primary```.

**Comment by quicksketch** [comment]
Hmm, not sure. We already have a class for input buttons (.form-submit), but as I found out, we also have a separate class for button tags (.form-button). We also already use `.button` on links (or at least provide support for it in Seven), so you can have `a.button`.

I think some of the reason for having more specific classes is because it reduces accidental overlap. We already have a small problem with classes like "warning" that are used on messages and as paragraph text. Sometimes the bleeding of styles between different types of elements can have some unexpected effects. At the same time, it's become a common convention to use *only* classes, never elements, IDs, or attributes, so as to prevent specificity wars between different selectors.

But basically, I'm not sure.

@wesruv or some of our front-enders could probably provide some good insights here.

**Comment by wesruv** [comment]
@klonos 
I prefer one class, especially since we're working on a system that people will want to build upon.
The lower the specificity in core, the better. That way people who may not be as front-end savvy will have an easier time overriding styles. 

Even if we're talking about Seven or Bartik, there's a chance people will use it as a sub-theme and lower specificity will be desirable.

If we plan on having A LOT of button variations, I say we go with having two classes on the button element, like `button button-primary`. If we only have around 5 button types, I'd keep the markup simpler and stick with the one class.
