### ISSUE TITLE
Add custom redirects functionality (Redirect module) to core

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#905]
We're rapidly coming across several areas where redirecting to a pages canonical path would be ideal, and wonder if this kind of functionality should be added to core.

There is a path(auto) setting that retains a previous alias when a new one is created. Ideally that old alias would redirect visitors to the new one, preventing the "wrong" path from being indexed, linked to, or bookmarked. Now that duplicate paths for content can be created automatically (pathauto in core) we're likely to feel the need for some kind of redirect very soon.

Places where redirects would be useful:
- http to htttps
- ?q= to clean url
- (duplicate) alias to canonical path

I propose that we provide a way to indicate which path (or option) should be the canonical one, and also provide a checkbox somewhere for "always redirect to canonical".

In this way all aliases would essentially become redirects, and we wouldn't need a separate system to manage redirects. 

We should look at the UI redirect module provides, and consider adding something similar to the entity form (a list of all available paths for the entity). We can further indicate there which one is canonical, and allow that to be adjusted by the editor.

**Comment by sutibun** [comment]
Yes, please.

Regarding "(duplicate) alias to canonical path", the redirect should be a 301 redirect for SEO-friendliness. (i.e. return an HTTP 301 status code when redirecting from an old/duplicate URL to the new/canonical one)

**Comment by docwilmot** [comment]
Is anyone working on this yet? Its been bumped from May. I know nothing of Path. 

Just checking up on 1.3.0 issues to make sure theyre not too under the radar.

**Comment by serundeputy** [comment]
`PR` https://github.com/backdrop/backdrop/pull/1249

this gets redirects working with at least `Basic Page`'s

* need to look into views
* taxonomy terms
* users?
* tests, tests, tests

**Comment by quicksketch** [comment]
Great job so far @serundeputy! I gave the PR a full review at https://github.com/backdrop/backdrop/pull/1249.

Besides the feedback in that PR, I wanted to take a step back and reconsider the merging of Path and Redirect. The way this is merged right now, Path module starts owning some redirect-namespaced hooks such a `hook_redirect_access()` and a bunch of functions like `redirect_redirect()`, `redirect_get_current_redirect()`, `redirect_load()`, etc.

We did a similar mashup for Filter module owning several `editor_*` namespaced hooks and functions, but there was a very strong connection between the two concepts. Redirects and Aliases are fairly separate from each other, with no form altering or menu changes at all. Considering their level of separation, I think it may be good for both implementation and compatibility to leave these as separate modules.

I'm sorry we may have suggested that merging was preferred during the weekly calls when that may not be the right approach. Anyone else have thoughts on this matter?

**Comment by serundeputy** [comment]
@quicksketch thanks for the thorough review; I'll have a go at keeping it a separate module.

thanks!
~Geoff

**Comment by serundeputy** [comment]
New `PR` here with `./core/redirect` as a standalone module.
https://github.com/backdrop/backdrop/pull/1277

I could not figure out the cacheing test: `function testPageCache`

@quicksketch maybe when you get a chance you can have a look at that test.

thanks,
~Geoff

**Comment by serundeputy** [comment]
Udated `PR` w/ update hook `system_update_1051()` to detect existing installs w/ contrib `redirect` installed.

<img width="845" alt="screen shot 2016-02-27 at 5 17 05 pm" src="https://cloud.githubusercontent.com/assets/6763671/13375787/1852095a-dd77-11e5-820b-45a692f65794.png">


Will be requiring an `nid` on api.backdrop.com.  @quicksketch or @jenlampton if you want to give me an account with edit access on the api site I'll write up the `Redirect change notice` in the style and format of the others we have for CKEditor, Date, Link and Email.

~Geoff

**Comment by quicksketch** [comment]
@mikemccaffrey Mentioned this in Gitter chat, but I wanted to bring up the idea here.

Drupal 7 (and 8) had a little bit of an issue that everything that was an object somehow was also turned into an Entity. We don't need the extensive powers of entities for something so simple as a redirect. However, Redirect module as written is OOP because of Entities. We could keep the current code but remove unneeded abstraction by just making Redirect objects *not* inherit from Entity objects and removing the `hook_entity_info()`.

**Comment by klonos** [comment]
> ...reduce the abilities of redirects in the future (e.g. translation...

When you mention translation or redirects here, do you by any chance refer to what's needed to address issues like #1638? Because if so,...

> But if we need the abilities in the future, we could always turn them back into entities at that time.

...then this might need to happen sooner than you think.

**Comment by serundeputy** [comment]
So should I write a new `save()` function in the 'new' Redirect class as we can not: `$redirect->save()` w/out extending entity?

not sure by looking at `entity.class.inc`:

```php
/**
   * Implements EntityInterface::save().
   */
  public function save() {
    return entity_get_controller($this->entityType())->save($this);
  }
```

how that even goes about saving.

**Comment by quicksketch** [comment]
> So should I write a new save() function in the 'new' Redirect class

Yep, that would be the idea. With entities, there is a separate class that is responsible for doing the saving, `RedirectController`. We could take the code out of the controller and put it in `Redirect::save()`, or we can keep it where it is and change the code in `Redirect::save()` to:

```php
  /**
   * Save a redirect to the database.
   */
  public function save() {
    return RedirectController::save();
  }
```

Personally, I prefer to eliminate the controller. The point of controllers is that they could be swapped out with alternatives that implement saving/loading/deleting in a different manner. As we've been explicitly avoiding such abstraction, I'm not sure keeping the controller around makes sense.

**Comment by quicksketch** [comment]
Hi @serundeputy, I made a PR to your branch: https://github.com/serundeputy/backdrop/pull/1

If merged into your branch that should update the PR and move us forward a little further:

- Redirects are no longer entities. This resulted in simplified code execution but perhaps not less code overall, since we do our own saving instead of letting the entity system handle it. I found that Redirects couldn't even use a different storage system in D7 because they depended on the "redirect" database table. Redirects are still objects (good for compatibility), but they no longer have a controller class.
- I reworked the settings page:
  Before:
![selection_093](https://cloud.githubusercontent.com/assets/100206/14099448/672ef97c-f53a-11e5-85d1-7153d3d1d9ca.png)
  After:
![selection_092](https://cloud.githubusercontent.com/assets/100206/14099454/7170f64c-f53a-11e5-9eed-83d5519012a5.png)
  - Removed "Default redirect status". The default is now always "301 - Moved Permanently"; the most common redirect and best for SEO. Can still be changed through contrib if needed.
  - Removed "Show warning" setting, which was hidden and didn't work anyway. Can still be added through contrib if needed.
  - Removed "Allow redirect to be saved into the page cache". This option is now always enabled and no longer requires any special settings in settings.php, though it works slightly differently now in that cached redirects don't increment the count (as they wouldn't if you were using a reverse proxy like Varnish or nginx anyway). This is both good for performance and consistency, and it simplifies the UI. Though it does make the redirect counter into "Redirects handled by Backdrop", rather than total redirects served.
- Integrated directly into node, user, and taxonomy modules instead of using hook_entity_info_alter().
- Removed (by default) the uncommon redirect types. Now only 301 and 302 are shown by default. Removed the "Advanced settings" fieldset as there was only one option in there.
Before:
![selection_094](https://cloud.githubusercontent.com/assets/100206/14099476/a15ff9d4-f53a-11e5-9f00-2c0243b586e0.png)
After:
![selection_095](https://cloud.githubusercontent.com/assets/100206/14099484/b5ce3fca-f53a-11e5-859b-ff16c4a55f0e.png)

**Comment by quicksketch** [comment]
There are still some areas I think we need to improve upon. In particular the redirect settings on node forms should use dialogs rather than taking me off the form:
![selection_096](https://cloud.githubusercontent.com/assets/100206/14099572/878d45d8-f53b-11e5-88e5-6f0d41966606.png)

There is a lot of cruft around providing Global Redirect like functionality. Right now the code is either commented out or UI elements are hidden. It looks like there is a working patch to bring full Global Redirect functionality to Redirect module in https://www.drupal.org/node/905914. However, I'm not sure if this should go in Redirect module or not. It seems like it would be more appropriate to add it to our existing "URL handling" settings page. We'll have to see how tightly integrated into Redirect module it is to determine if we should use the existing code or move it somewhere else.

**Comment by quicksketch** [comment]
>  It seems like it would be more appropriate to add it to our existing "URL handling" settings page. We'll have to see how tightly integrated into Redirect module it is to determine if we should use the existing code or move it somewhere else.

For the basic redirect module (without global redirects) perhaps we should remove all the existing global redirect code and implement it separately in #868?

**Comment by mikemccaffrey** [comment]
Despite redirect being in both names, it seems like there is very little
overlap between the Redirect module and the Global Redirect module. I vote
for keeping these projects separate.

**Comment by quicksketch** [comment]
I'm going to work to finish this up. I drafted a changelog entry at https://api.backdropcms.org/node/43994 so that we can reference it in the status report page if you were running a contrib version of Redirect module.

**Comment by jenlampton** [comment]
> Despite redirect being in both names, it seems like there is very little overlap between the Redirect module and the Global Redirect module.

Unfortunately, that is the problem.  :(

I'd be fine with putting global redirect into core (without a module) in https://github.com/backdrop/backdrop-issues/issues/868 or merging it into the module. As long as we don't end up with two modules that don't work properly without each-other.

**Comment by quicksketch** [comment]
Yeah, we'll definitely want them working together, I don't think that will be a problem. Redirect module currently uses `hook_url_inbound_alter()` (yuk!) because it's the absolutely earliest hook available. If we built global redirect into core, we'd probably put it directly in menu.inc. Let's handle it either way in https://github.com/backdrop/backdrop-issues/issues/868

**Comment by quicksketch** [comment]
I've been pushing regular updates to the PR at https://github.com/backdrop/backdrop/pull/1317

The most recent updates now remove all TODOs, including the fixing of an issue with `hook_path_delete()` not working properly, for which Redirect module had to compensate. I merged in an updated version of https://www.drupal.org/node/1025904 to the PR.

I'm fairly satisfied with tests at this point. The documentation in `redirect.api.php` could use more work in filling out examples, but all the documentation is there an appears accurate. I'm really hoping to get this merged in the next couple of days.

We want redirect module enable by default in the standard profile, correct? I just noticed that on fresh installs, it's not turned on. Seems like that should be in place if we've also got automatic aliases enabled.

**Comment by quicksketch** [comment]
Another round of updates pushed to https://github.com/backdrop/backdrop/pull/1317. I did an extensive code inspection and fixed a bunch of documentation:

- Removed all remaining references to redirects being entities.
- Built out some more hook examples.
- Documented hook_redirect_operations().
- Added lots of missing docblocks on parameters throughout the code.
- Removed the default views that hadn't been enabled in Backdrop anyway. These were disabled by default in Drupal as well, I think they may be better left out by default.
- Enabled Redirect in the standard profile.

@docwilmot also [left a note on the current PR](https://github.com/backdrop/backdrop/pull/1317#issuecomment-213413315) around validating the "To" path, but (I think) that has been resolved through the subsequent discussion.

This is ready to be committed from my perspective. I've reviewed it in whole 6 separate times now. It does get better each time, but this is far beyond first-iteration work at this point and definitely shippable as-is. Unless there are any items brought up, I plan on committing this over the weekend.

**Comment by quicksketch** [comment]
Doh, of course my latest "code style" fixes caused test failures. I've rolled back some of the fixes and filed a new issue regarding type-hints on `hook_field_attach_form()` at #1819.

**Comment by quicksketch** [comment]
Actually it looks like most failures came from enabling Redirect in the standard profile (which changed the way path aliases are handled on deletion/rename/etc.) I've pushed up more fixes to the tests to compensate for the change.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/1317 for 1.4.0. Thanks @serundeputy for all your work porting the module to Backdrop and then for core! @klonos and @docwilmot for reviewing. This is a banner improvement for 1.4.0!

**Comment by klonos** [comment]
:tada:
