### ISSUE TITLE
How to get a list of PRs merged in a release?

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#932]
Wanted to see all thats been merged in 1.1.0, but cant figure how.

**Comment by serundeputy** [comment]
I think this does it @docwilmot : `git log v1.0.0..1.1.0`

output to a file for convienient perusal: `git log v1.0.0..1.1.0 > /path/to/log/file/name_of_file`


~Geoff

**Comment by klonos** [comment]
:wink:

**Comment by docwilmot** [comment]
:+1:  @klonos thanks for the cleanup, again.

It would be good to have that list online somewhere.

**Comment by quicksketch** [comment]
You can also see the list on GitHub for all changes since a release version to the present. Click on the number of of commits next to each release's authoring information here: https://github.com/backdrop/backdrop/releases

For Backdrop 1.1.0, there were 233 commits on top of 1.0.6: https://github.com/backdrop/backdrop/compare/1.0.6...1.x

**Comment by docwilmot** [comment]
May be useful to document this, for those of us who wouldnt have found it otherwise. tagging for future reference.
