### ISSUE TITLE
Simplify Layout edit page titles?

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#934]
Fixing https://github.com/backdrop/backdrop-issues/issues/637
Layout edit page titles  are a bit unusual. Other edit pages titles are a single word representing the bundle being edited; like "Article" or "Account menu". 

Layouts prefers the word "edit" then `<Layout name>` then `<path>`. Makes for unattractive menu links, Should we simplify them to suit other edit page title formats?

![layout titles](https://cloud.githubusercontent.com/assets/1042283/7670659/889d1240-fc72-11e4-8992-f8662d2cf488.png)

**Comment by quicksketch** [comment]
Hm, Views doesn't include the word "Edit" or "Configure" at all. It shortens the name, but is it better?

![views](https://cloud.githubusercontent.com/assets/100206/7671838/e747b186-fc92-11e4-8bef-a2e9caf7782c.png)

**Comment by docwilmot** [comment]
Really the Layouts title is practical, and I have no problem with it as such, just that it makes a terrible menu link. Perhaps like views, use `<layout name>`(`<path>`)?
In either case, for long paths its going to look funny.

![layout title2](https://cloud.githubusercontent.com/assets/1042283/7672442/dc5817cc-fcb8-11e4-8456-845606c956ed.png)

With views-like links:

![layout titles long](https://cloud.githubusercontent.com/assets/1042283/7672468/a1edf236-fcb9-11e4-9a32-c508f6b11220.png)

**Comment by docwilmot** [comment]
@klonos can we get an opinion on this?

**Comment by klonos** [comment]
> ... Views doesn't include the word "Edit" or "Configure" at all....

It actually includes "Edit". It is *Structure > Views > [view_name] > Edit view* and it is in tandem with what we have for menus (*Structure > Menus > [menu_name] > Edit menu*), so it only makes sense to have *Structure > Layouts > [layout_name] > Edit layout*.

This menu needs to be adjusted in successive steps because there's too many things that need to be corrected. I could post a before/after menu structure of how I think this could be improved, but they would be very long lists. So lets just start with being consistent with the 2nd level children:

1. Make sure that the "add", "list", "configure"/"settings" items that apply to the parent item are listed first **before** the individual actual items and that they also have the same order across the various 1st level items.

2. So far, we have consistency with "Add xyz" for all 1st level items (thanks to #399). Lets also get #525 in so that we are consistent with "List xyz" too. Additionally, we should also have it either be "Configure xyz" or "xyz settings" rather than simply "configure"/"settings".

3. As I said above, lets make it be *Structure > something > [something_name] > Edit something*

Hope all this makes sense because the alternative would be to type long lists of menu structures and it is really tedious and it would make this issue a long scroll to go through.

**Comment by docwilmot** [comment]
Hi @klonos, thanks for your overview. I dont know if I could try out #525 anytime soon but good ideas.

BUT the insight I was looking for for this issue is actually what the `[something_name]` in `Structure > something > [something_name] > Edit something` should be in admin menu for layout links. Notice that all other menus have simple menu names, whereas layouts has the word "Edit" then [Layout name] then [path]. This is automatically generated from the page title on the layout edit page as noted in the image.

![layout title2](https://cloud.githubusercontent.com/assets/1042283/7789011/959c6f68-0217-11e5-9daa-88d5bb7e29cb.png)

The issue here is that the menu name looks weird; that image would be the actual menu link for a layout with that name at that path. This is a reasonable page title I suppose, but as a menu link it sucks. 

To fix this though, we'd have to change the formats of the page titles themself to something simpler and menu friendly.

**Comment by quicksketch** [comment]
> This is a reasonable page title I suppose, but as a menu link it sucks. 
> To fix this though, we'd have to change the formats of the page titles themself to something simpler and menu friendly. 

I think the page title is a good UX feature, but you're right it doesn't work in the admin bar. If we simplify the menu item, I think we should still keep the full page title when on the page itself.

**Comment by klonos** [comment]
I'm with Nate on this one. Loose the path from the menu item (so just ```Edit [layout_name]```), but keep it on the page.

Just one minor thing though. I think we should implement #945 first so that we don't have ```Edit "xyz layout" layout``` menu items.

...and also either loose the double quotes from the layout name or use them everywhere (like in views names for example) for consistently throughout the menu. If we want to distinguish a name of a thing, I think italics are better than quotes.

**Comment by docwilmot** [comment]
@klonos I'm shocked. 

The pattern of using the word "Edit xxx" doesnt exist anywhere else where a thing is being edited, I'm surprised you're OK with it on layout pages. All other editing pages just have the name of the entity type/bundle/whatever your editing:

Views: just "Admin Content (Content)"
Node: just "Article"
Taxonomy: just "Tags"
Menu: just "Account menu"
etc.

BUT Layout: "Edit 'This Layout' at 'this/path'"

Personally I didnt really mind although the voice of Klonos, Lord of Consistent UIs, was constantly echoing in the back of my mind: "Thou shalt be consistent!" 

But now, shocked!

p.s. if we're keeping this atrocity, how do I get a different menu link from the page title? `hook_admin_bar_map()` doesnt seem to allow this?

p.p.s. In case its not obvious, I'm exaggerating with the 'shock'.

**Comment by quicksketch** [comment]
> p.s. if we're keeping this atrocity, how do I get a different menu link from the page title? hook_admin_bar_map() doesnt seem to allow this?

Just use backdrop_set_title() in the menu callback and use the short title in hook_menu().

**Comment by klonos** [comment]
> @klonos I'm shocked.

> The pattern of using the word "Edit xxx" doesnt exist anywhere else where a thing is being edited... "Thou shalt be consistent!"

:laughing: Yes, you are right. What I meant there actually was *Structure > Layouts > [layout_name] > Edit layout*. My point was that we need to loose the path portion.

**Comment by klonos** [comment]
...

> I'm with Nate on this one.

There I meant the part of loosing the path portion from the menu entries but still keeping it in the page title.

**Comment by docwilmot** [comment]
Great!

Suggestions for template for the **page title**:
> MyLayout (path: *new/path*)
> MyLayout (*new/path*)
> MyLayout at *new/path*

Including `path: ` in the first option may help with understanding a bit more what the title is about? Not so sure. And the second borrows from Views' page titles format. I'm going with number 3 unless there is disagreement.

And for the **admin bar menu link**, just the layout name, no path. So just 
> MyLayout

PR to come.

**Comment by docwilmot** [comment]
Actually number 4 may be better for short aliased paths, no? A path called just `books` would have a page title:
> MyLayout at books

which isnt as clear as:
> MyLayout at path: books

Guidance please!

**Comment by klonos** [comment]
Perhaps we could wrap the path part in ```<code>``` tags just to emphasize that it is a path? Italics and wrapping it in brackets would work equally fine I guess.

**Comment by docwilmot** [comment]
Tried the code tags, didnt work. Went with brackets for... consistency:

![menu](https://cloud.githubusercontent.com/assets/1042283/8020221/97246a38-0c36-11e5-90a6-293a097fd61d.png)
![page title](https://cloud.githubusercontent.com/assets/1042283/8020222/9725944e-0c36-11e5-90dc-de9543c49dc0.PNG)

**Comment by quicksketch** [comment]
Nice! Looks pretty good to me! Though a few things should be done about the order. Add and List should definitely be first, but then should we follow with the default layouts second?

- Add layout
- List layouts
- Default Layout
- Default Administrative Layout
- [all other layouts alphabetically]

**Comment by klonos** [comment]
*Structure > Layouts > Another > Layout* ???

...was it meant to be *Structure > Layouts > Another > **Edit** layout* perhaps instead?

> ...but then should we follow with the default layouts second?

We don't do that with core themes/views. I think that listing all alphabetically (including default) would be better.

**Comment by quicksketch** [comment]
> We don't do that with core themes/views. I think that listing all alphabetically (including default) would be better.

In Drupal 7, themes had the concept of "Global", but that didn't show up at all in admin_menu. Views don't have a concept of a default view, so the situation isn't quite analogous. Default layouts are special, so I thought they should be given special treatment (maybe not though).

> ...was it meant to be Structure > Layouts > Another > Edit layout perhaps instead?

This is a good idea and would bring it inline with Views. However, I'd love to see this last level of depth just dropped entirely, for Views and Layouts. Unfortunately, that might get complicated due to the way admin bar and the menu system interact. What do you think, do we need the last level of "Edit layout" or "Edit view" at all? Maybe that could be a followup.

**Comment by docwilmot** [comment]
I agree with @quicksketch here: the default is the one youre most likely to be going to in the menu bar, so it should be top.

Having said this I cant figure how to fix its position as recommended; any pointers please?

**Comment by quicksketch** [comment]
> Having said this I cant figure how to fix its position as recommended; any pointers please?

You may need to explicitly specify the default and admin default layout in hook_menu(), then assign these items a negative weight. I'm not 100% sure though.

**Comment by docwilmot** [comment]
I think Ive tried everything but that. And really, I am doubting whether it is worth it to go that far just to fix a menu item. Perhaps we should let @klonos' opinion win and call it a day?

**Comment by quicksketch** [comment]
> I am doubting whether it is worth it to go that far just to fix a menu item.

Sounds good to me. Iterate and improve. :+1: 

I'll give the PR a review when I get the chance.
