### ISSUE TITLE
Token on 1.1?

### ISSUE THREAD

**Issue by JordiTR** [backdrop/backdrop-issues#935]
Hi, I've installed 1.1 and I can´t find Token or Pathauto anywhere and I thought they should come on that new release, am I wrong?

**Comment by serundeputy** [comment]
Hi @JordiTR ;

No. You are not wrong; You are right!
`pathauto` is integrated into the `path` module; so if `path` is enabled you will have pathauto functionality at `/admin/config/search/path/patterns`

and the `token` browser will be there too since it is integrated into core as well.

hope that helps!
cheers,
~Geoff

**Comment by JordiTR** [comment]
It's true. I expected something like the classic Drupal modules Token and Pathauto to be found somewhere, and I was surprised for not finding them. Nice and smooth integration I would say! :-D

**Comment by quicksketch** [comment]
:+1: :smile:
