### ISSUE TITLE
What about using Google Fonts for Seven?

### ISSUE THREAD

**Issue by jdanthinne** [backdrop/backdrop-issues#941]
It could reduce the size of core (which includes unused fonts, like ExtraBold, Light, …, btw), and get some benefits using the Google CDN (one external request to http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,700 instead of four).

**Comment by dboulet** [comment]
One thing to consider here is privacy. Because websites built with Backdrop could potentially contain sensitive information—especially in the admin—loading third-party resources on every page load is not something that everyone is comfortable with. A while back, the WordPress admin switched to using Google Fonts, and it caused some concern among developers: http://blog.milandinic.com/wordpress/plugins/disable-google-fonts/.

Aside from that, the performance benefits might not be that substantial. Browsers will only load fonts as they are required, so the number of requests will be the same in both cases.

**Comment by jdanthinne** [comment]
Allright, that makes sense. Perhaps just removing the extra unused weights could help reduce the core release size.

**Comment by quicksketch** [comment]
Yeah, I'll add in that exceptionally controlled intranets and off-line use are also considerations. I think the built-in fonts are a good idea, with using Google Fonts as a possible contrib opportunity.

**Comment by quicksketch** [comment]
As we about to use Open Sans for both the new front end theme (Basis) and the existing admin theme (Seven), we're moving Open Sans to a central location in #1452, which has the side-effect of making it a library instead of a CSS file. This makes it a bit easier to change how it works, switching to a remote copy if you prefer.

Let's close this feature request. It still is a good candidate for contrib.
