### ISSUE TITLE
Baseline / standard vagrant

### ISSUE THREAD

**Issue by btopro** [backdrop/backdrop-issues#971]
A lot of git repos I see any more have a standard vagrant image. This isn't to say that it's the only way to do it or "the correct" way to run the application, but it sure as hell makes it easier for hobbyists to do some weekend-hacking and play around with stuff when they can click clone to local, run vagrant up, and go get some coffee while the application builds.

That said, I think it'd be a massive advantage over Drupal to provide a vagrant image that allowed for bringing Backdrop up quickly, even just for demonstration purposes. This is based off the vagrant image utilized by the ELMSLN and PSU Drupal User Group with an emphasis on making it simple and optimized. It avoids chef / puppet / ansible for greater host environment compatibility and lower barrier to entry for others to hack on it.

I'll be issuing a PR shortly that would bring the approach to backdrop via core/misc/vagrant and associated files.

This is built off of Centos 6.5 though it could be easily modified for ubuntu/debian/other. It also optimizes apc, php, mysql, apache and the VM based on available host resources so it should run pretty fast OOTB.

**Comment by btopro** [comment]
associated PR in case others would like to try out: https://github.com/backdrop/backdrop/pull/936

**Comment by quicksketch** [comment]
Hi @btopro! Thanks for submitting the PR.

I'm not sure how I feel about this feature. On one hand, it may be useful to developers that use Vagrant and want to get a site up and running quickly. On the other, I'm not sure that Vagrant users are squarely in our target audience, and those developers may have particular preferences when they set up their configuration (e.g. using Ubuntu instead of CentOS). It seems the number of variations could be endless.

I'd still love to see this code available in public, perhaps in the https://github.com/backdrop-contrib/ group, but including a specific configuration in core seems like it would both be making a lot of assumptions and require a fair deal of maintenance. I personally don't use Vagrant and wouldn't have the time to test changes. If we did include this, we'd need a new maintainer to look after it. :wink:

**Comment by btopro** [comment]
With how prevalent vagrant is in higher education and the nice stepping stone Backdrop provides I think it is in a large part of your target audience. I agree from maintenance / endless variations. So, how do I get access to backdrop-contrib so I can get it up there?

**Comment by quicksketch** [comment]
> So, how do I get access to backdrop-contrib so I can get it up there?

We have a small process for application documented at https://github.com/backdrop-ops/contrib (you'll open an issue there). This isn't like most projects however, as it's not a module, theme, or layout, but I think it will work out okay.

Is any of your work associated with https://www.drupal.org/project/vdd?

**Comment by btopro** [comment]
I think we might have gotten things accepted into there associated w/ performance optimization in the VagrantFile but no. Moved away from Chef / any packaging formats because it was just another thing to learn and debug :)

**Comment by quicksketch** [comment]
Cool, let's continue this in https://github.com/backdrop-ops/contrib/issues/96. Thanks!

**Comment by quicksketch** [comment]
Nice! https://github.com/backdrop-contrib/backdrop-vagrant
