### ISSUE TITLE
[Layout UI] The layout selection page ("Settings") wraps available layouts in a funny way.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#988]
To reproduce this, install the [Radix Layouts](https://github.com/backdrop-contrib/radix_layouts) layout set, visit the default layout settings page (`/admin/structure/layouts/manage/default/settings`) **remember to flush caches** (#984) and resize your browser to various widths (sorry in advance for the ~2MB .gif file taking too long to load this page on slow connections):

![layout_settings_page-funny_wrapping](https://cloud.githubusercontent.com/assets/2423362/8096815/74e07d40-101e-11e5-9a01-64e6e2af3d6d.gif)

**Comment by quicksketch** [comment]
Thanks again @klonos. We could probably fix this short-term with a min-height on the layout icon wrapper, that's usually the sort of thing I do to solve this problem myself. Maybe one of our front-enders has a better solution? cc @wesruv

**Comment by klonos** [comment]
> Thanks again @klonos...

You're welcome Nate, I get my thrills when I manage to break things :stuck_out_tongue:

**Comment by wesruv** [comment]
Lol :stuck_out_tongue: 

There are a few things we could do, not sure what'll work best for this case. I'll mess around with it.

**Comment by wesruv** [comment]
@klonos++ for the awesome ticket description.

**Comment by wesruv** [comment]
@quicksketch 
I think the best solution to this is flexbox by a **very** large margin. It does the 'float-like' behavior and makes sure nothing 'gets snagged' because it doesn't clear an abnormally tall item. 

If we wanted to stick with floats as the primary method of layout (not the fallback) the best thing I can come up with is using nth-child and clearing every so many items depending on breakpoint (*shudder*)

`min-height` gets us an 'okay' fix, I'm sure we're going to eventually have 4 and 5 line layout names, so it's making this bug less likely, but not really fixing it.

The flexbox features I need will work in these browsers:
* IE10+
* FF22+
* Chrome 21+
* Safari 6 on OSX Mt Lion+
* Safari on iOS7+
* Android 2.1+

According to browser stats I have from October 2014 from a very popular cable station's site, the browsers that don't support this are below the 5% mark except IE 9, and I'm able to easily provide a fallback for old IE (it's in my PR).

Ideally we'd have modernizr in Seven to detect if flexbox is available. 

Safari versions that don't support flexbox (iPhone5s and down, OSX Lion and down) don't have an easy way of adding a fallback.

I'm pretty sure we talked about modernizr before and it got pushed back on... but considering how much of a game changer flexbox is for web layout, and how hard it is to provide a proper fallback without a feature test, I thought it was worth bringing up again.

Current PR: https://github.com/backdrop/backdrop/pull/956

**Comment by wesruv** [comment]
To be clear, the only thing I'm asking is that we have a custom build of modernizr with a small set of tests to make sure our admin UI is as good as possible. So I only need it in the admin theme, Seven.

**Comment by wesruv** [comment]
New PR, couldn't re-open the old one after I updated it. I just added some better accessibility stuffs after having thought about it for a bit.

Another thing I want to point out, the flexbox/modernizr stuff is for the bugfix, the prettiness updates do not require any feature detection or flexbox.

https://github.com/backdrop/backdrop/pull/965

**Comment by quicksketch** [comment]
I posted an update with my thoughts on Modernizr over in https://github.com/backdrop/backdrop-issues/issues/1009. In the mean time while that is getting sorted out, we could simply write a small feature detection borrowed from Modernizr and put it in `layout.admin.js` to detect flexbox support:

```js
/**
 * Behavior for showing a list of layouts.
 *
 * Detect flexbox support for displaying our list of layouts with vertical
 * height matching for each row of layout template icons.
 */
Backdrop.behaviors.layoutDisplayEditor = {
  attach: function(context) {
    var $element = $(context).find('.layout-options');
    if ($element.length) {
      if ($element.css('flex-basis')) {
        $element.addClass('flexbox');
      }
      else {
        $element.addClass('no-flexbox');
      }
    }
  }
};
```

Then @wesruv could write his CSS as if Modernizr were already added to core, but we'd only have flexbox detection on this one page, rather than on every page of the site. In some ways, this could be beneficial, as we're only doing the detection when needed instead of on every page load. On the other hand, we'll need to do the same thing in other areas where we need flexbox or other detection such as on the themes page (https://github.com/backdrop/backdrop-issues/issues/1047).

**Comment by klonos** [comment]
Sounds reasonable to me.

**Comment by wesruv** [comment]
@quicksketch I had no idea it was so reasonable to add detection for a feature, guess I assumed Modernizer was made of magik, lol.

Thanks!

**Comment by klonos** [comment]
Yep, not magic - just a 3rd-party thing that we don't have to maintain. So, if in core, all we'd have to do is keep it up to date and that way we'll get any bug fixes or new features for free. Any bugs or feature requests that we need fixed/implemented can be contributed against their queue.

**Comment by wesruv** [comment]
@quicksketch 
Added your code (with a slight modification to detect flex-wrap) and found an IE10+ flexbox bug that I had to address. Should be good now:
https://github.com/backdrop/backdrop/pull/965

**Comment by quicksketch** [comment]
I rerolled the existing PR with a few changes at https://github.com/backdrop/backdrop/pull/1168.

- All styles related to the pretty radio buttons move to the Seven theme.
- Added specific `:focus` styles so that keyboard access is visible.
- I couldn't find a way to make the green background mesh with a focus color, so I copied the appearance of textfields with focus.

@wesruv Could you check if the changes are acceptable?

This issue still present (mentioned by @klonos) in the first PR:

> Nitpicking: When clicking a layout by clicking the icon, then the icon gets a blue-ish overlay while selecting it by clicking the layout title it doesn't:

![backdrop-issue988-pull965-hover-select_issue](https://cloud.githubusercontent.com/assets/2423362/9562343/92eb7bb4-4ead-11e5-99df-01da9c6066b5.gif)

I found that removing the `z-index: -1` would fix this, but sound like it would break IE from the code comment:
```
  z-index: -1; /* Fix IE issue clicking on image doesn't trigger radio */
```

So I've left it intact for now.

**Comment by quicksketch** [comment]
I've merged in https://github.com/backdrop/backdrop/pull/1168. Thanks @wesruv for this awesome improvement!
